### ISSUE TITLE
Cannot set items per row when using mouse

### ISSUE THREAD

**Issue by nfinite-recursion** [tachiyomiorg/tachiyomi#10009]
### Steps to reproduce

Connect a mouse or use Android on a PC or virtual machine.

Go to: Settings > Library > Items per row.

Use the scroll wheel to cycle the numbers up and down.

"Ok" will never become clickable so changing this setting is impossible.

### Expected behavior

Behavior with touchscreen input snaps to the nearest number while swiping up or down. If the number is changed from when the user entered this menu, "Ok" will become tappable allowing the user to save their new settings.

### Actual behavior

Behavior with mouse scrolling does NOT snap to the nearest number while scrolling up or down. This results in a situation where the user cannot change the Items per row setting and "Ok" never becomes clickable.

### Crash logs

N/A

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Blu G91 Pro

### Other details

Initially discovered in a Virtualbox virtual machine running Android x86 9.0 r-2. Initially, I chalked it up to a bug with the virtual machine or possibly the Android port itself. After thinking about this for a bit, that made little sense.

Next, I plugged a mouse into my Android phone and the exact same issue occurred on it as well. If I use the touchscreen it works as expected.

My assumption is that the submenu for Items per row is coded to only respond properly to touchscreen events and not events in general. One other thing that may be worth pointing out is that keyboard events can only affect the "Cancel" and presumably "Ok" buttons. Using the arrow keys to select a number is completely impossible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The UI for this has changed already in the Preview versions, so I guess this has already been fixed as a side effect.

**Comment by nfinite-recursion** [comment]
Thank you for the heads up. Just tested the latest preview build and its implementation as intended in a virtual machine and on real hardware, mouse or touchscreen. Looking forward to the official update!

Also moving the setting to the main Library tab was a great call as it allows users to see the change as they change it. Keep up the great work!
