### ISSUE TITLE
How to open downloaded chap？

### ISSUE THREAD

**Issue by pkhubpp8** [tachiyomiorg/tachiyomi#10001]
### Steps to reproduce

1. do not add the manga into "In Library"
2. do not read any chap, or just delete the manga cache
3. download 5 chap from the manga, source is local komga server(or any other source)
4. download completed
5. close app
6. close mobile network(or shutdown komga server, or manga server down)

### Expected behavior

1. open "source" fail due to no network, expected
2. can't find the manga from library, expected
3. More--Statistics--Chapters--Downloaded 5 chaps, expected
4. No chapters in "downloaded queue" due to download completed, expected
5. any method open/read downloaded 5 chapters?

### Actual behavior

can't find any way to read

### Tachiyomi version

0.14.6

### Android version

any

### Device

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Add it to your library.

**Comment by pkhubpp8** [comment]
> Add it to your library.

If remote server down forever, how I clean downloaded chapters?
I have 5 chapters that I can't delete or open, it might downloaded many months ago.

**Comment by BrutuZ** [comment]
https://tachiyomi.org/docs/guides/local-source/

**Comment by arkon** [comment]
> If remote server down forever, how I clean downloaded chapters?

That isn't a problem if the chapter list can't successfully get updated and removes existing chapters. If existing chapters disappear from the source but you still have them downloaded, then it's a duplicate of #2108

> Is it possible add a new feature to read/delete downloaded chapters without add in library?

No, the entire paradigm of the app revolves around adding things to your library. It is not, and will not be, designed for arbitrary downloaded content that isn't associated with anything locally.
