### ISSUE TITLE
Can't Restore a Backup File

### ISSUE THREAD

**Issue by 0xrefr** [tachiyomiorg/tachiyomi#10003]
### Steps to reproduce

When I click a restore backup in the backup and restore section and select the file that I want to restore, it shows me an error dialog message (image 👇).

![Screenshot_20231011-015731_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/74292334/6ef27d56-2592-4509-91ec-737f04866851)

And I am sure that I gave the application access to the files. Also, I have checked again that the application has privileged access to the permissions.

👉🏻 [Video](https://streamable.com/8nh72m) 👈🏻

### Expected behavior

Restore all data and see it in the library, etc.

### Actual behavior

It didn't get anything back.

### Crash logs

He didn't get anything back--------- beginning of main
10-11 12:57:11.312  2714  2714 E anade.tachiyom: Failed to open file '/data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GNhk.frro@idmap': No such file or directory
10-11 12:57:11.312  2714  2714 E anade.tachiyom: failed to read IDMAP /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GNhk.frro@idmap
10-11 12:57:11.312  2714  2714 E anade.tachiyom: Failed to open file '/data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GNhk.frro@idmap': No such file or directory
10-11 12:57:11.312  2714  2714 E anade.tachiyom: failed to read IDMAP /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GNhk.frro@idmap
10-11 13:14:26.411 28682 28682 E USNET   : USNET: appName: eu.kanade.tachiyomi
10-11 13:14:26.622 28682 28723 E SQLiteLog: (283) recovered 225 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-11 13:14:26.631 28682 28733 E chromium: [1011/131426.631284:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: error while doing initial calls
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: java.io.IOException: java.net.ConnectException: Failed to connect to /192.168.0.10:5000
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at eu.kanade.tachiyomi.network.interceptor.UncaughtExceptionInterceptor.intercept(UncaughtExceptionInterceptor.kt:18)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:47)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita.doLogin(Kavita.kt:1123)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita._init_$lambda$144(Kavita.kt:1151)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita.$r8$lambda$hSazyudeDM_066vi1FyP5ZXre9U(Unknown Source:0)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita$$ExternalSyntheticLambda3.call(Unknown Source:2)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:2)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:1)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.Single.subscribe(Single.java:13)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.Single$13$1.call(Single.java:15)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:12)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:10)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.lang.Thread.run(Thread.java:920)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: Caused by: java.net.ConnectException: Failed to connect to /192.168.0.10:5000
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:161)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:36)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:3)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:19)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:55)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	... 3 more
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: Caused by: java.net.ConnectException: failed to connect to /192.168.0.10 (port 5000) from /10.0.0.213 (port 39472) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at libcore.io.IoBridge.isConnected(IoBridge.java:349)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:238)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at libcore.io.IoBridge.connect(IoBridge.java:180)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at java.net.Socket.connect(Socket.java:621)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:11)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:94)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	... 7 more
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	at libcore.io.IoBridge.isConnected(IoBridge.java:336)
10-11 13:14:30.081 28682 28780 E extension.all.kavita_[1]_Home_Server: 	... 17 more
10-11 13:15:08.059 28682 28849 E SQLiteLog: (284) automatic index on C(manga_id)
10-11 13:15:08.059 28682 28849 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-11 13:17:02.299  2324  2324 E USNET   : USNET: appName: eu.kanade.tachiyomi
10-11 13:17:02.543  2324  2388 E chromium: [1011/131702.543591:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
10-11 13:17:03.162  2324  2512 E SQLiteLog: (284) automatic index on C(manga_id)
10-11 13:17:03.162  2324  2512 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N975USQS8HWG1
Device brand: samsung
Device manufacturer: samsung
Device name: d2q
Device model: SM-N975U
Device product name: d2qsq

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Samsung Note10+

### Other details

I wrote this error in the support section of the tachiyomi discord server, and they told me to give a tachiyomi "all file access", but when I go to the "all file access" section, the tachiyomi isn't there.

Also, they told me to disable the "Sava as CBZ archive", and I disabled it, but the issue is still there.

The same problem exists when I create a backup; it shows me the same issue when I click to restore the backup file, and the automatic backup is disabled. The last backup was 20 days ago.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If the section for All Files Access has an app called something like "External Storage", enable it for that.

The error message is saying that your file picker is failing to actually read/return the content, so it's beyond the control of the Tachiyomi app.
