### ISSUE TITLE
Some extensions are not displayed 

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi#10006]
### Steps to reproduce

Search mangatigre or Yugenmangas or nhentai

### Expected behavior

must be shown

### Actual behavior

Not listed 

### Tachiyomi version

Preview 6078

### Android version

13

### Device

Redmi 10c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Make sure you haven't disabled the relevant languages or 18+ sources from Settings.

**Comment by christmovies** [comment]
> Make sure you haven't disabled the relevant languages or 18+ sources from Settings.

Yes, I did that hahaha

**Comment by christmovies** [comment]
> Make sure you haven't disabled the relevant languages or 18+ sources from Settings.

Thanks
