### ISSUE TITLE
Redirect to Another App When Reading Chapters

### ISSUE THREAD

**Issue by cybekoo** [tachiyomiorg/tachiyomi#10000]
### Steps to reproduce

1. I add manga from the NovelCool extension to my library.
2. I enter or download chapters to read them.
When I open the chapters, images with the message appear: "Notice: Urgent! Please Update for the best user experience, please update now. Your account will not be affected. Download the latest version: https://www.mangadogs.com/" 
3.This redirects me to download another application to access the chapters.
4. This problem has occurred with two manga titles from the same extension.

### Expected behavior

I expect to be able to open a chapter from the NovelCool extension and read it normally without being redirected to another application.

### Actual behavior

Many times I attempt to open a chapter of any manga added from this extension, I only see images promoting another app and am prompted to update, even when the extension is already up-to-date.

### Tachiyomi version

0.14.6

### Android version

Android 10 

### Device

Xiaomi Redmi 9A

### Other details

I have already checked if the extension or the application needed to be updated and both are, and I have already uninstalled and reinstalled the extension but it still has not been solved. The strangest thing about this, through the WebView option and I can view the chapters perfectly, I don't know if there is a problem with the extension or what is happening, other than that there is no they're with all the chapters at the beginning if you can read them but as you progress, those images begin to appear. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
