### ISSUE TITLE
Migrate Nude-moon

### ISSUE THREAD

**Issue by Gostik21** [tachiyomiorg/tachiyomi#10015]
### Steps to reproduce

Nude-moon change address from Nude-moon.org to Nude-moon.net

### Expected behavior

Nude moon extension is opened

### Actual behavior

Connection reset

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Poco

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
