### ISSUE TITLE
Can't Install on Android 14 (Pixel 8?)

### ISSUE THREAD

**Issue by BeeeQueue** [tachiyomiorg/tachiyomi#10010]
### Steps to reproduce

1. Download APK
2. Try to install

### Expected behavior

App should be installed

### Actual behavior

Popup saying "You can't install the app on your device." is shown

### Crash logs

```
husky:/ $ pm install /data/local/tmp/tachiyomi-x86-v0.14.6.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

### Tachiyomi version

0.14.6

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Download the arm64 one, the Pixel 8 Pro doesn't have an x86 CPU.
