### ISSUE TITLE
Application crashes 

### ISSUE THREAD

**Issue by RoSiCyBeR** [tachiyomiorg/tachiyomi#10013]
### Steps to reproduce

I opened the application and I opened the update section 

### Expected behavior

Previously the application was fine

### Actual behavior

This has never happened before

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12903893/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Sony Xperia xz2

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/34416860/10dc5fd0-74b2-42e8-9ce6-d4caa9971a3b

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
10-09 15:50:02.765 25484 25484 E AndroidRuntime: java.lang.IllegalArgumentException: Key updatesHeader--743928504 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```

This was a relatively common issue in the current stable version. The preview version _should_ be better, but it may still happen on weaker devices.
