### ISSUE TITLE
library

### ISSUE THREAD

**Issue by Chellyph14** [tachiyomiorg/tachiyomi#10021]
### Steps to reproduce

I can't update my library, when I put it to update it suddenly stops, sometimes it exits the application by itself.

### Expected behavior

What should happen is that it updates until the end, but it always stops and this means that the manga doesn't update, so I don't know if there is a new chapter.

### Actual behavior

It happens that when I go to update the library to see if there are new chapters in my manga, but instead it isn't updating, it stops out of nowhere.

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Samsung Galaxy A6 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/docs/faq/library#why-aren-t-library-updates-working
