### ISSUE TITLE
Library updating very slowly 

### ISSUE THREAD

**Issue by Astrokinng** [tachiyomiorg/tachiyomi#10024]
### Steps to reproduce

1.open app
2.update library
3.keeps updating library for 2hr+

### Expected behavior

Normally it should update within like 10 or 15 minutes.

### Actual behavior

Keeps on updating very very slowly. Checked with both cellular and wifi it's the same on both. 

### Tachiyomi version

App version: 0.14.6-6101 

### Android version

Android 13

### Device

Samsung galaxy s23ultra 

### Other details

This just happened when I updated to this version it was working perfectly fine before in the previous preview version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Followed the steps you mentioned, can't reproduce.
<details><summary>FYI</summary>Any chance you have hundreds of entries in the same source and its extension got updated recently? In which case perhaps that extension got a rate-limiter</details>

**Comment by Astrokinng** [comment]
> Followed the steps you mentioned, can't reproduce.
> 
> FYI
> Any chance you have hundreds of entries in the same source and its extension got updated recently? In which case perhaps that extension got a rate-limiter

**Comment by Astrokinng** [comment]
How to remove the rate limiter then cause this was not happening in the previous version

**Comment by BrutuZ** [comment]
You don't, it was put in place for a reason.

**Comment by Astrokinng** [comment]
![Screenshot_20231016_134006_Chrome](https://github.com/tachiyomiorg/tachiyomi/assets/89287848/fd7ac5c6-b08c-4aa4-949a-d47b10ed46b5)
 As you can see it started around 11.35 am and right now it's 1.40pm is there any other way like should I migrate stuff to other extension etc etc

**Comment by Astrokinng** [comment]
What is the minimum or the optimal I can I have on one source so that it won't slow down. And i have put not to update the completed ones

**Comment by CrepeTF** [comment]
There is no minimum or optimal, having more intrinsically slows it down because the app has to go and check the source website for each and every entry you have in your library

**Comment by christmovies** [comment]
Maybe it's a phone thing like me, this doesn't mean that your phone is damaged, it happened to me that it took about 20s to enter the app, Erase all data on the phone and nothing until I put the phone in Safe mode (this solves errors) and it worked for me, it is now normal

**Comment by arkon** [comment]
I doubt this is related to the app update, it's likely a source issue.
