### ISSUE TITLE
Able to remove orphaned entries from migrate tab

### ISSUE THREAD

**Issue by Mister-HACB** [tachiyomiorg/tachiyomi#10025]
### Describe your suggested feature

It's currently not possible to remove an orphaned entry from the migrate tab, where it shows up when the extension got removed/deprecated.
The migrate tab can only migrate entries, but it would be very helpful if you also can also remove entries without having to migrate them first.

Maybe through a context menu or by opening the library entry by pressing longer on it and then remove by clicking the "In libary" button.

![Screenshot_2023-10-16-01-30-20-89_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/54818612/892eb94d-1185-418e-9eca-b5f5bbc39c79)

![IMG_20231016_015156](https://github.com/tachiyomiorg/tachiyomi/assets/54818612/8a519fb3-9e0d-44dd-8449-b19092165b08)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Click the cover
