### ISSUE TITLE
'Items per row' setting is missing.

### ISSUE THREAD

**Issue by Riskbreaker92** [tachiyomiorg/tachiyomi#10020]
### Steps to reproduce

Go to settings> library
The 'items per row' setting is gone. 

### Expected behavior

Go to settings> library
Usually, there's a 'items per row' setting is available at the top

### Actual behavior

The 'items per row' setting is gone.

This is from the stable version settings.
![Screenshot_20231015-103246](https://github.com/tachiyomiorg/tachiyomi/assets/67619543/3d21422e-89dd-48d6-aa98-270df07ac344)

And this is from the latest preview version r6101
![Screenshot_20231015-103133](https://github.com/tachiyomiorg/tachiyomi/assets/67619543/c4c16b58-a860-4a51-98fe-6887f4a3e9c5)

### Tachiyomi version

r6101

### Android version

Android 9

### Device

Xperia XZ1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It was moved to the settings sheet in the Library screen a few months back.
