### ISSUE TITLE
Tachiyomi 0.14.6 Crash Report

### ISSUE THREAD

**Issue by halehydrie** [tachiyomiorg/tachiyomi#10036]
### Steps to reproduce

When I opened the app, it looked fine and at the second tap, while I was reading, the app suddenly stopped scrolling, and then it showed the greeting screen.

### Expected behavior

Fix the bug, make it stop on turning back to greeting screen or that blue thing with tachiyomi's logo.

### Actual behavior

I don't know if this is a bug or what, it doesn't shows any code error, it just keeps going back to greeting screen, as if I remove the app's tab and open it again. It's so annoying that the app has to stop in the middle of my reading and then go to the greeting screen. I don't exactly know how to explain it because it doesn't show any code error. It just keeps crashing on me.

### Tachiyomi version

0.14.6

### Android version

7.1.1

### Device

OPPO F5

### Other details

![Screenshot_2023-10-19-00-12-09-78](https://github.com/tachiyomiorg/tachiyomi/assets/148368755/9e76ae98-ef68-4497-831b-1010bae15785)
![Screenshot_2023-10-19-00-12-07-09](https://github.com/tachiyomiorg/tachiyomi/assets/148368755/0e3d4bd3-024a-4b67-bd72-b543757d622e)

https://github.com/tachiyomiorg/tachiyomi/assets/148368755/4b88e3a1-f096-4208-b4fa-164a731fa893

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can you post the crash logs?
