### ISSUE TITLE
Issue: private installer 

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi#10032]
### Steps to reproduce

![Screenshot_2023-10-17-17-39-13-593_eu kanade tachiyomi debug](https://github.com/tachiyomiorg/tachiyomi/assets/97629848/32561e01-732a-4c52-a16d-4a367702e9eb)

### Expected behavior

They installed

### Actual behavior

Does not install the extension after it is downloaded

### Tachiyomi version

Preview r60101

### Android version

13

### Device

Redmi 10c

### Other details

This came up in the last update 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Was fixed by #10026
