### ISSUE TITLE
Local manga update from web url

### ISSUE THREAD

**Issue by kevin930321** [tachiyomiorg/tachiyomi#10037]
### Describe your suggested feature

Is it possible to update local manga from website, like maybe type the url in details.json allows it to download manga chapter directly from the website

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
So literally the opposite of a local manga? Just migrate the entry to another source if you want to read it from an online source instead.

**Comment by kevin930321** [comment]
Yeah i know, but if its possible we'll have more options, cause not every website have an extension, and also more editable on manga information

**Comment by arkon** [comment]
You would obviously need a functional source to be able to get info, including downloading chapters, from any given website.

Providing a random URL wouldn't work.

**Comment by kevin930321** [comment]
Ok understood, just wondering if it can be done, it'll be pretty convenient
