### ISSUE TITLE
Anilist not connecting

### ISSUE THREAD

**Issue by aniforprez** [tachiyomiorg/tachiyomi#10030]
### Steps to reproduce

1. Select any tracked manga and attempt to make changes on anilist
2. Try to connect to your anilist account on the app to initiate tracking	

### Expected behavior

1. Tracked manga should be updated on anilist
2. Anilist should connect without issues

### Actual behavior

1. Tracked manga refuse to update, instead returning a `403` error when trying to update star rating, start date, end date and so on.
2. Anilist refuses to connect, instead opening the browser, briefly showing a loading screen and then taking you back to the trackers list screen but not connecting anilist.

### Crash logs

```
--------- beginning of main 10-17 08:46:15.838 22341 22388 E chromium: 
[1017/084615.838233:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2 
10-17 08:46:16.130 22341 22341 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found. 
10-17 08:46:16.170 22341 22503 E SQLiteLog: (284) automatic index on C(manga_id) 
10-17 08:46:16.170 22341 22503 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) 
Android version: 13 (SDK 33) 
Android build ID: TP1A.220624.014.S901EXXS7CWH6 Device brand: samsung 
Device manufacturer: samsung 
Device name: r0q 
Device model: SM-S901E 
Device product name: r0qxxx
```

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung S22

### Other details

Anilist recently started aggressively using the Cloudflare Turnstile captcha system which might have messed up the responses coming in from API. The 403 is possibly related to the "incorrect" user agent we may be sending to Anilist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Ref: https://anilist.co/forum/thread/68889/comment/2429831

Not sure if there's a need to particularly handle it apart from waiting for AniList (& their Cloudflare infra) to fend off their current DDoS attacks

**Comment by aniforprez** [comment]
Makes sense. I will close this then. This seems like a local issue and a very anilist cloudflare specific issue. Nothing Tachi can do to resolve this. Thanks @curche

**Comment by aniforprez** [comment]
Closing
