### ISSUE TITLE
Error in opening zip file in local source (cbr, cbz)

### ISSUE THREAD

**Issue by CV-Carlos** [tachiyomiorg/tachiyomi#10040]
### Steps to reproduce

Put a file on the local source following the guide
Try to open the file on the app

### Expected behavior

App should open the file
Other local readers are working

### Actual behavior

App attempts to open the file then fails with message "Error in opening zip file"

### Tachiyomi version

0.14.6

### Android version

10

### Device

Samsung Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Is this a RAR5 file?
Can you try to check if this helps: unzip the .cbr/.cbz and rezip it into a zip (using 7zip or similar)

**Comment by CV-Carlos** [comment]
> Is this a RAR5 file? Can you try to check if this helps: unzip the .cbr/.cbz and rezip it into a zip (using 7zip or similar)

Yea, apparently is RAR5 file. I cleaned up the cache and database in the app and now the error is RAR5 file is not supported....

**Comment by curche** [comment]
Refer to https://github.com/tachiyomiorg/tachiyomi/issues/3988

RAR5 is just generally finnicky with opensource apps given its proprietary nature so I recommend converting everything to .zip or zip renamed to .cbz
