### ISSUE TITLE
EOF bug

### ISSUE THREAD

**Issue by 6uez** [tachiyomiorg/tachiyomi#10044]
### Steps to reproduce

We can't download or open mangas

### Expected behavior

Expected start of the object "{', but had 'EOF' instead at path: $....

### Actual behavior

Expected start of the object "{', but had 'EOF' instead at path: $....

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung s20 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably a source problem, so:

> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
