### ISSUE TITLE
Updates skipping all sources

### ISSUE THREAD

**Issue by Alpha999888** [tachiyomiorg/tachiyomi#10053]
### Steps to reproduce

1. Attempt to update
2. All updates skipped

### Expected behavior

It should update from the installed sources.

### Actual behavior

It skips all sources and doesn't update any manga in my library even though the sources are still accessible manually through the app.

### Crash logs

No crashes.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy Note20 Ultra

### Other details

I have attempted to load each source individually and I can see series that were updated daily, but when I attempt to update my personal library to search for new chapters it ends up skipping all series. I have attempted other fixes that I have found and nothing seems to work in regards to attempted fixes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries
