### ISSUE TITLE
BacaKomik Page Not Cpund

### ISSUE THREAD

**Issue by FakeModz** [tachiyomiorg/tachiyomi#10054]
### Steps to reproduce

1. Open any comic
2. Select chapter
3. Its say "No Pages Found"

### Expected behavior

The comic should be appears and you can read the comic

### Actual behavior

Its say no pages found

### Crash logs

No Crash Logs

### Tachiyomi version

1.4.6

### Android version

Android 13

### Device

Xiaomi 11 T

### Other details

All comic is no pages found only can be opened by webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FakeModz** [comment]
Sorry typo, Page not found

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
