### ISSUE TITLE
Add back option to save pages to Pictures/Tachiyomi

### ISSUE THREAD

**Issue by kairusds** [tachiyomiorg/tachiyomi#10052]
### Describe your suggested feature

The directory of where the chapters are saved has recently changed in a development build, there should be an option that allows you to change back to the previous behavior of only saving to the `Pictures/Tachiyomi` directory.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KraXen72** [comment]
+1, alongside with #9951

**Comment by KraXen72** [comment]
@arkon thank you so much you are actuallly so based for adding this back ily <33333333
