### ISSUE TITLE
Add timeout option during migration 

### ISSUE THREAD

**Issue by nexus671** [tachiyomiorg/tachiyomi#10058]
### Describe your suggested feature

If a source takes x amount of time to respond just mark as timedout and finish the migration search. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
what do you mean finish the migration search? are you actually using tachiyomi? or is this a fork because you may be in the wrong repo then.
