### ISSUE TITLE
When the library is updated, the mangas are deleted from the history

### ISSUE THREAD

**Issue by ayaxSRE** [tachiyomiorg/tachiyomi#10062]
### Steps to reproduce

When I update the library some manga are deleted from the history, it is as if they were not in my library and they were deleted

### Expected behavior

It should update the library and not affect the history and statistics

### Actual behavior

mangas are deleted from history

### Tachiyomi version

0.14.6 and 0.14.3

### Android version

Android 11

### Device

Xiaomi redmi 8 note

### Other details

I have tried updating the version, updating one by one, changing the extension and there is no solution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ayaxSRE** [comment]
from one moment to another, the (complete) mangas began to be deleted from the history, apparently it only happens with the mangas of the "TuMangaOnline" extension

**Comment by Raj8369** [comment]
Apparently I am also getting the same issue with my extension asura scan website in it

**Comment by arkon** [comment]
If this is about chapters, particularly downloads, seemingly disappearing, it's probably because the source changed the chapters and the app ended up orphaning the existing downloads since it couldn't figure out whether they were the same or not. This is a known issue: #2108
