### ISSUE TITLE
Cloudflare blob issue

### ISSUE THREAD

**Issue by puffyqi** [tachiyomiorg/tachiyomi#10060]
### Steps to reproduce

I try to open webview to complete the cloudflare verification but it redirect to a blob page and give a blank screen when trying to load the cloudflare verification checkbox

If I directly open from my chrome browser, I am able to tick the verification and redirect to the chapter but webview will still stuck at verification and redirect to blob blank screen.

It started happening since this week.

Extensions affected: baozi manhua and happymh

### Expected behavior

1. Access webview
2. Tick verification
3. Verification success and redirect to chapter

### Actual behavior

1. Access webview
2. Try to load the cloudflare verification but redirect to blob page empty screen

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung S22+

### Other details

![Screenshot_20231025_085940_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/31648386/63108398-6072-46cd-a1e1-878f40c3a290)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Turhvjbufv** [comment]
Every extension with cloud flare has this issue unfortunately

**Comment by Crayonmuncher698056imdum** [comment]
Excuse me gentlemen ladies what is this i have the same problem explain to me like I'm a child

**Comment by Turhvjbufv** [comment]
> Excuse me gentlemen ladies what is this i have the same problem explain to me like I'm a child

Just download the new tachiyomi version or wait or an update on the fork you currently use, it should fix the problem

**Comment by Crayonmuncher698056imdum** [comment]
Oh thank you I should backup my data first

**Comment by Crayonmuncher698056imdum** [comment]
Nvm I had like 500  hump hump mangas but I let it all go
