### ISSUE TITLE
"center" zoom start position is not true center 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#10067]
### Steps to reproduce

Set zoom start position to center, and it will zoom to the center of the page from left/right but not centered in top/bottom

### Expected behavior

Should be true center left right and top bottom 

### Actual behavior

Only centered in left right 

### Tachiyomi version

0.14.7

### Android version

Android 11

### Device

Boox leaf 2 

### Other details

I read here that it's already updated to be true center https://github.com/tachiyomiorg/tachiyomi/issues/8747

Sorry for opening a new issue, I can't comment there as it's marked as only open for contributors 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It'll be in the next stable update that's an actual feature update and not just some cherry picked critical bug fixes.

Or you can just use the preview version.
