### ISSUE TITLE
Auto updates  issue

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi#10066]
### Steps to reproduce

...

### Expected behavior

Update

### Actual behavior

It does not update automatically, only manually, this only if I do it from the manga itself.
![Screenshot_2023-10-25-16-58-23-919_eu kanade tachiyomi debug](https://github.com/tachiyomiorg/tachiyomi/assets/97629848/d3b03d89-11cf-4ddd-b746-02e571e4f3a9)

I updated the first one manually. 

### Tachiyomi version

Preview r60101

### Android version

13

### Device

Redmi10c 

### Other details

On estable version it works

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Since you're using a Xiaomi device, you'll need to carefully follow https://tachiyomi.org/docs/faq/library#why-aren-t-library-updates-working, including all of the Don't Kill My App instructions.

Xiaomi devices are well known for not working well.
