### ISSUE TITLE
App crashes when attempting to search in Settings (Preview r6132)

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi#10069]
### Steps to reproduce

1. Go to More -> Settings
2. Tap the search icon on the top right
3. Search something (tried "cover")

(Video demonstration:)

https://github.com/tachiyomiorg/tachiyomi/assets/31158494/4c13c6f8-8897-4176-9820-74256aab9ebc

### Expected behavior

Should return the search result and don't crash like this (from Tachiyomi Stable 0.14.7):
![Screenshot_2023-10-26-16-23-41-36_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/31158494/e7202994-7073-4df2-a3b3-2aa2b29f930f)

### Actual behavior

Immediately crashes and I had to relaunch the app again (and dump the crash log immediately).

### Crash logs

I send the log file instead since it had character limits.

[tachiyomi_crash_logs 10-26-2023.txt](https://github.com/tachiyomiorg/tachiyomi/files/13174858/tachiyomi_crash_logs.10-26-2023.txt)

### Tachiyomi version

Preview r6132 (0.14.6-r6132)

### Android version

Android 13

### Device

WSA version 2308.40000.4.0

### Other details

I originally thought that the language (Filipino) was the issue, I changed it to English in Settings -> Appearance. But it still crashes the app regardless of language.

When I opened the crash log, it told me an error relating to: "IndexOutOfBoundsException" (specifically java.lang.IndexOutOfBoundsException: Index 4, size 4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by gauravagrwal** [comment]
App also crashes while searching for extensions in the Extensions tab under Browse

**Comment by arkon** [comment]
Compose issue: https://issuetracker.google.com/issues/300504058
