### ISSUE TITLE
[Feature request] Save filters Global search

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi#10064]
### Describe your suggested feature

Save the last state filters Global search https://github.com/tachiyomiorg/tachiyomi/pull/9691
Pinned, All, Has results (optional)
<img src="https://github.com/tachiyomiorg/tachiyomi/assets/35057681/5e8d1abc-ba46-4cea-9eaa-7fe306ab399d" width="600" />
as Library filters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can you elaborate?

**Comment by e-shl** [comment]
> Can you elaborate?

When changing the filters, they should remain same next run the global search and even after restarting Tachi

**Comment by arkon** [comment]
Would be more preferable to implement #6654 (also with persisting previously selected sources).
