### ISSUE TITLE
[Feature request] Reset chapter settings

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi#10063]
### Describe your suggested feature

Chapter settings may be Set as default (Filter, Sort, Display).
But not may be fast Reset to default for the current manga.
<img src="https://github.com/tachiyomiorg/tachiyomi/assets/35057681/51e9c7f4-e4cb-49ef-8dde-35259a6446bc" width="400" />

how is this realized in j2k
<img src="https://github.com/tachiyomiorg/tachiyomi/assets/35057681/6905bf32-2f3a-4a55-b92b-1c5b9729916b" width="400" />

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
Which is the second app?

**Comment by e-shl** [comment]
> Which is the second app?

https://github.com/Jays2Kings/tachiyomiJ2K
