### ISSUE TITLE
Date of saved image

### ISSUE THREAD

**Issue by Boloblux** [tachiyomiorg/tachiyomi#10070]
### Steps to reproduce

1. Open a manga chapter
2. Hold touch on screen
3. Download the page

### Expected behavior

The page should be downloaded with the date of the moment it has been downloaded

### Actual behavior

What's happening is that the date of the page often is the date the chapter have been released and sometimes the normal behavior happen

### Tachiyomi version

O.14.7

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Other details

I frequently download manga page and this behavior started happening after the last update released

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Nothing about this changed between 0.14.6 and 0.14.7.
