### ISSUE TITLE
Extention Source broke after update

### ISSUE THREAD

**Issue by BaronCandy** [tachiyomiorg/tachiyomi#10076]
### Steps to reproduce

Update app 
  Open omegascans source 
    Recive error 400

### Expected behavior

Source should work as it was working before the update

### Actual behavior

Keep running into 400 dispite opening in webview no captcha to solve and return to app

### Tachiyomi version

App version: 0.14.6

### Android version

Android 13

### Device

Samsung s23 ultra

### Other details

Hello i was reading a manga and saw a popup for new update as so far have never had an issue so did the update but now a source is not working 

Suggestions a button to ignore this update and or revert to old one would also be appreciated 
Thanks in advance 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18761
