### ISSUE TITLE
App freezes when attempting extension update/install

### ISSUE THREAD

**Issue by CyberJman1** [tachiyomiorg/tachiyomi#10072]
### Steps to reproduce

1. Open app
2. Go to extension tab
3. Click update or install on new extension
4. Result: app freezes and phone states "app is not responding." Wait or close options given. Waiting does nothing. Stays frozen.

Tried clearing app cache, didn't fix...

### Expected behavior

When "update" or "install" is chosen, it should do the expected action.

### Actual behavior

App freezes when attempting extension update/install

### Crash logs

It's not crashing. Just freezing and causing me to force close it.

### Tachiyomi version

0.14.6 and 0.14.7 both have the error.

### Android version

Android 14

### Device

Google Pixel 7a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CyberJman1** [comment]
![Screenshot_20231026-150240](https://github.com/tachiyomiorg/tachiyomi/assets/149048403/966ab23d-65f4-4c69-b846-cb3d95a42c44)

**Comment by CyberJman1** [comment]
![Screenshot_20231026-150514](https://github.com/tachiyomiorg/tachiyomi/assets/149048403/5e0fe88b-d91a-4b92-8e13-a68501b56f80)

**Comment by CyberJman1** [comment]
Forgot to mention this above, but I was able to update the extensions manually using the GitHub extension repository.

**Comment by arkon** [comment]
Merging with #4106
