### ISSUE TITLE
Tachiyomi crashes when finishing a chapter in long strip mode.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#10078]
### Steps to reproduce

1. Open any chapter that is in long strip mode.
2. Read it to the end of a  chapter, position doesn't matter and can be the last chapter in a series.

### Expected behavior

Tachiyomi doesn't crash.

### Actual behavior

Tachiyomi crashes.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13195058/tachiyomi_crash_logs.txt)

### Tachiyomi version

r6132

### Android version

Android 13

### Device

Samsung S21 FE

### Other details

Only seems to happen as wasn't able to reproduce on left to right mode but can also be related to number of pages in a chapter as the left to right only had 2-3 pages in a chapter.
Also probably different from #9704 as crash happen on end of current chapter and not on load of next.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's quite a few errors in those logs, but at least some of them are the same as #10069, so it might be fixed in the next preview build.

**Comment by THElegend5** [comment]
Yeah that seems to have fixed it so closong this.
