### ISSUE TITLE
Updated library widget error 

### ISSUE THREAD

**Issue by sriwijaya572** [tachiyomiorg/tachiyomi#10086]
### Steps to reproduce

1. Update from tachiyomi 0.14.3 to 0.14.7
2. After installed, go to your phone home screen
3. widget just reload continuously 

### Expected behavior

![Screenshot_20231029_160153](https://github.com/tachiyomiorg/tachiyomi/assets/108703365/1cf678f0-5ce3-4bd9-815f-c98c2abe745f)

Just ask for sauce if anyone interested🤣

### Actual behavior

![Screenshot_20231029_163848](https://github.com/tachiyomiorg/tachiyomi/assets/108703365/52f04e16-b218-4dec-95b5-9af3e8b58da2)

### Tachiyomi version

0.14.7

### Android version

Android version: 8.1.0 (SDK 27) Android build ID: OPM1.171019.026

### Device

Vivo Y93

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I believe this is already improved in the preview builds after some Glance updates.
