### ISSUE TITLE
Download link not working 

### ISSUE THREAD

**Issue by GZMaster** [tachiyomiorg/tachiyomi#10088]
### Steps to reproduce

1. When you go to the GitHub link to download the app it doesn't work 
2. Or if you try to update from the app it doesn't work as well

### Expected behavior

When you press the download link the download would start 

### Actual behavior

When you press the download link the download doesn't start and the page doesn't load

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi note 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The fact that you can't even download it normally from GitHub directly implies that your network is blocking GitHub's raw assets domain. You could try using a VPN.
