### ISSUE TITLE
can't complete captcha 

### ISSUE THREAD

**Issue by yasnil03** [tachiyomiorg/tachiyomi#10080]
### Steps to reproduce

1. open myreadingmanga or nhentai
2. open the website for captcha
3. do the I'm not a robot to get the 

### Expected behavior

Once you complete the captcha all the manga for the extension should show

### Actual behavior

However instead of you doing captcha after opening it in webview it will show the lage for captcha then after few seconds error of blob:https://nhentai.net

### Tachiyomi version

0.14.6 having problem downloading the new update

### Android version

Android 12

### Device

Xiaomi Note 9s

### Other details

![Screenshot_2023-10-28-23-08-42-708_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/48662401/270a6a8d-9033-46cf-82b7-68a835eb020f)

I'm also having trouble downloading the new version. It won't complete at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you need to update, if you're having issues updating you can ask on discord for help
