### ISSUE TITLE
Mark the Icons with NAMES

### ISSUE THREAD

**Issue by yujianjuzi** [tachiyomiorg/tachiyomi#10081]
### Describe your suggested feature

No one is born knowing the variety of icons.  We use language to communicate.  Please include text for them, I really don't know them.  Thank you very much, and there may be more places where the icons need to be marked with text. Please mark them if there is enough space.
Even if there is no multilingual version, it is better than 
none.

![IMG_20231028_233234](https://github.com/tachiyomiorg/tachiyomi/assets/104896412/46b62169-ca2f-47f6-af34-29ee6e5ff483)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by yujianjuzi** [comment]
I'm sorry.

**Comment by arkon** [comment]
Long press them.
