### ISSUE TITLE
Authentic color mode (aka disable Night Light)

### ISSUE THREAD

**Issue by mirh** [tachiyomiorg/tachiyomi#10091]
### Describe your suggested feature

During late hours, my eyes certainly benefit from warmer light - yet this isn't exactly the best experience when reading comics.  
(then it's true that stuff like halftone manga has less to loose - but conversely there's also not much wrong that OG whites can do)
Of course I could just toggle this from the quick settings, but clearly if it could be automatic it'd be better (let alone, I always eventually forget about the action and I don't get to remember I had done it until my retinas start to burn later when I'm messaging or watching videos). 

### Other details

Everything I know technically is [here](https://stackoverflow.com/questions/56974867/toggle-night-light-mode-in-android-by-code/77303019#77303019)
Thankfully you at least already support root/shizuku

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We plan on eventually dropping Shizuku anyway once private extensions are stable, so there's no intention on supporting functionality that requires root, especially managing system settings.

**Comment by mirh** [comment]
`WRITE_SECURE_SETTINGS` can also be granted through adb. 
So.. could this functionality ship as an extension (a bit like AutoTools for tasker)?

**Comment by BrutuZ** [comment]
Since it was brought up, why not toggle it via Tasker itself then?
Add a Time and Active App trigger to the profile and you're good to go

**Comment by mirh** [comment]
I guess that checks out too (or using whatever the free alternative)
It's just that it seemed something that was intuitive to sit between dark mode and brightness
Too bad they didn't expose any normal api for adjustments.
