### ISSUE TITLE
Page auto refreshes when bypassing cloudflare

### ISSUE THREAD

**Issue by R3TR0nn** [tachiyomiorg/tachiyomi#10094]
### Steps to reproduce

1. bypassing cloudflare by clicking "verify" 
2. page auto refreshes and you need to click verify again
3. refreshes till eternity

### Expected behavior

cloudflare bypassed

### Actual behavior

clicked verify then auto refreshes again and being asked to verify again

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Xiaomi 12T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
