### ISSUE TITLE
Hide category 

### ISSUE THREAD

**Issue by Abhishek10299** [tachiyomiorg/tachiyomi#10106]
### Describe your suggested feature

Can you please add a feature to hide category in tachiyomi and we can unlock it by a special password it is needed because I don't want to show my cultured manga to everyone because showing your collection to your friends is a important part of reading and someone can judge you by your cultured collection so if we can hide some categories or lock them that can be a great feature to add

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate of #1508
