### ISSUE TITLE
Plot editing and chapter dispersion merging.

### ISSUE THREAD

**Issue by ItsukaShiroInfinity** [tachiyomiorg/tachiyomi#10100]
### Describe your suggested feature

Sometimes some series appear to me with the "unknown title" or with a description in another language. I wonder if you can add a function to edit its properties freely, by doing this you can show a button to intersperse between the original description and the personalized one.
in some series (mainly Hentai) you can find scattered chapters I wonder if you can add next to the "add to library: a button: "add as chapter" when doing this allows you to navigate between the series in the library and when selecting one you Save as another chapter of that series, allowing you to choose the chapter number. In this part, when downloading the chapter, you must add the corresponding chapter number since I have noticed that the name of the cbz can coincide and I have seen different chapters with the same name but since it is in different folders it does not collide but when saved in the same one it can create a collision by adding the assigned chapter number. It is avoided: seotranslations.cbz will become seotranslations(2).cbz

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> I wonder if you can add a function to edit its properties freely

#4398

> I wonder if you can add next to the "add to library: a button: "add as chapter" when doing this allows you to navigate between the series in the library and when selecting one you Save as another chapter of that series, allowing you to choose the chapter number.

No.
