### ISSUE TITLE
Add, copy comics, expand

### ISSUE THREAD

**Issue by lichi10032** [tachiyomiorg/tachiyomi#10116]
### Describe your suggested feature

Add, copy comics,Extension. website is：copymanga.tv

### Other details

Copying comics is relatively comprehensive in Chinese comics, so we hope to add this extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
