### ISSUE TITLE
Limit Global Update Bandwidth

### ISSUE THREAD

**Issue by mastermach50** [tachiyomiorg/tachiyomi#10117]
### Describe your suggested feature

An option to limit the global library ubdate bandwidth can help with not flooding manga sites with requests.

If not a bandwidth limit a request per second limit can be implemented.

This will especially be useful for people with large libraries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Similar to #6968
