### ISSUE TITLE
Show total chapters on title when searching in browser tab or make it possible to short using total number of chapters something.

### ISSUE THREAD

**Issue by imDusht** [tachiyomiorg/tachiyomi#10114]
### Describe your suggested feature

Is should show up like this so we can get total number of chapters already before opening
![Screenshot_20231106-172314_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79660867/4206b759-42b6-43ea-b1ba-25bcfe5bb565)
![Screenshot_20231106-172906_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79660867/7c9451ce-59db-4f10-b6c5-32c49ecee003)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
mostly the same idea as #2867
