### ISSUE TITLE
symlinks don't work on tachiyomi

### ISSUE THREAD

**Issue by gaitas13** [tachiyomiorg/tachiyomi#10118]
### Steps to reproduce

 1. Create a symlink from Tachiyomi/local to another folder
 2. Browse local sources on tachiyomi

### Expected behavior

the folder should appear on local sources

### Actual behavior

It doesn't appear on local sources, neither with a link to a folder on internal storage or a link to a folder in sdcard

### Tachiyomi version

0.14.7

### Android version

Android 13 Derpfest OS

### Device

Redmi Note 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I wouldn't expect symlinks to work, especially when we eventually move to scoped storage.
