### ISSUE TITLE
Backup fail

### ISSUE THREAD

**Issue by totally-not-suspicious** [tachiyomiorg/tachiyomi#10124]
### Steps to reproduce

make a backup 
clear data
restore backup

### Expected behavior

backup should restore titles with chapters, read chapters, trackers and categories

### Actual behavior

only titles are restored and are missing all their data
in the restoreation details every title fails with "FOREIGN KEY constraint failed (code 787)"

### Tachiyomi version

preview r532

### Android version

Android 13

### Device

Samsung Galaxy A34 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/jobobby04/tachiyomisy
