### ISSUE TITLE
The Update List Doesnt Show Updates

### ISSUE THREAD

**Issue by Itsyua** [tachiyomiorg/tachiyomi#10125]
### Steps to reproduce

![Screenshot_2023-11-11-12-24-18-49_f9ee0578fe1cc94de7482bd41accb329](https://github.com/tachiyomiorg/tachiyomi/assets/141234782/39e46020-bee0-4a6b-a288-e9d0792163f3)

### Expected behavior

It doesn't show updates on mangas

### Actual behavior

It doesnt show updates on lists

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Realme 8

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Bit hard to tell what you're expecting if you don't actually describe the exact content.

If you're wondering why there's no updates in general: https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries
