### ISSUE TITLE
I can not put the manga/comic that into my library without download it

### ISSUE THREAD

**Issue by MrBearkun** [tachiyomiorg/tachiyomi#10129]
### Steps to reproduce

1. Open Browse tab and look for any manga/comic
2. Open that manga/comic and add it to library (default or any category) but don't download it
3. Open the library and check the manga/comic that just added
4. Notice that the manga/comic does not appear

Note :
1. I tried to consult with my friends but they don't have any problem like I do
2. This issue only occur if don't download any chapter of that comic. If I download just 1 chapter, it will appear in the library

### Expected behavior

Any manga/comic that put into library will be appear in the library. Either User download it or not

### Actual behavior

Any Manga/comic that put into library without download it, will be appear in the library but user can only read it if there is internet connection

### Crash logs

No crash logs

### Tachiyomi version

0.14.7

### Android version

Android version 12

### Device

Poco M5s

### Other details

This issue does not occur in
1. Xiaomi Redmi 9 pro android version 11 in Tachiyomi version 0.14.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Disable the `Downloaded` filter.
Either https://tachiyomi.org/docs/faq/library#why-can-t-i-disable-the-downloaded-filter or ![Image](https://media.discordapp.net/attachments/349436576037732355/1172768066329911366/Screenshot_20231111_001942_Tachiyomi.jpg)

**Comment by MrBearkun** [comment]
Oh my god. That easy. Thank you very much
