### ISSUE TITLE
Tachiyomi Update Issue 

### ISSUE THREAD

**Issue by Deenie13** [tachiyomiorg/tachiyomi#10130]
### Steps to reproduce

Whenever I try to update my tachiyomi app to the latest version it doesn't update 

### Expected behavior

I should be able to update my app

### Actual behavior

It would just stop downloading midway and I see no update and I still have the same old version of the app

### Tachiyomi version

 0.14.6

### Android version

Android version: 13 (SDK 33) 

### Device

Device name: Samsung A52q Device model: SM-A525F 

### Other details

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.A525FXXS6DWI1
Device brand: samsung
Device manufacturer: samsung
Device name: a52q
Device model: SM-A525F
Device product name: a52qnsxx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loaffalli** [comment]
What are u talking about?

**Comment by arkon** [comment]
You could try this, which also applies to other background jobs like download app updates: https://tachiyomi.org/docs/faq/library#why-aren-t-library-updates-working

If it still doesn't work, you can go to https://tachiyomi.org/download/ to download the APK file to update with.
