### ISSUE TITLE
Integrated anilist Comment Feature

### ISSUE THREAD

**Issue by SatoX69** [tachiyomiorg/tachiyomi#10131]
### Describe your suggested feature

Suppose you tracked a manga in anilist, make it so that after finishing each chapter of the tracked mangas, it will prompt a message confirmation, you can type your message and press upload, it will upload that message to anilist

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Pretty sure we won't be adding any kind of commenting system to the app. 

Something we can do and arkon has also agreed is linking to the comment section of that title on that tracker so you get a quick access

**Comment by arkon** [comment]
Definite no to any sort of comment/forum system integration.

You can already tap the tracker icons in the tracking sheet to open it up in the browser, which seems close enough.
