### ISSUE TITLE
In old version of Tachiyomi, e.g. tachiyomi-v0.13.6. "Failed to get extension list" in Extensions of Browse.

### ISSUE THREAD

**Issue by lusaty** [tachiyomiorg/tachiyomi#10144]
### Steps to reproduce

Steps to Reproduce:

1. install tachiyomi-v0.13.6;
2. click "Browse";
3. click "Extensions"
4. swip down the page;
5. The "Failed to get extension list" will appear.

The case occurs in all versions below tachiyomi-v0.13.6. Are these versions out of maintenance? 

### Expected behavior

The extensions list  appears in the page.

### Actual behavior

The "Failed to get extension list" appear.

### Tachiyomi version

0.13.6

### Android version

android 9

### Device

pixel

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.

**Comment by arkon** [comment]
Yes, we only support the latest version.
