### ISSUE TITLE
Tracking Issues

### ISSUE THREAD

**Issue by friday06** [tachiyomiorg/tachiyomi#10145]
### Steps to reproduce

Add Two - Three Sources
Read a Manga 
Even The Chapters you've read are still being downloaded from other sources no matter If it's being tracked or not.

### Expected behavior

The chapters of Manga that Are already read from other sources shouldn't be downloaded / shown in the first place if the chapter is marked in tracker.

### Actual behavior

Chapter is Being Downloaded Even Though we've read it from some other sources.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Redmi K40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Considering that functionality doesn't exist, this isn't a bug.

See #1626 for feature request.

**Comment by BrutuZ** [comment]
No issue there, entries from different sources are just that, different entries, regardless of having the same title.
[Tracker (MyAnimeList, Anilist, Kitsu, etc...) progress is one-way only](https://tachiyomi.org/docs/guides/tracking). Tachiyomi updates them, not the other way around.
