### ISSUE TITLE
Setting a custom storage location makes app need time (~31 secs) to check for downloads on every fresh start

### ISSUE THREAD

**Issue by Pizza989** [tachiyomiorg/tachiyomi#10159]
### Steps to reproduce

1. Set the storage location to a custom one. I have mine on an SD card.
2. Close the app and the daemon process (if there is one i dont know)
3. Start the app

### Expected behavior

Downloads should just show immediately. This used to be the case for me until i changed the storage location.

### Actual behavior

No downloads will show. Checking downloads badge appears at the top and after a while the downloads are there. But going to the history tab  will still show the manga and still lets you open them.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Samsung Galaxy Tab S7 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This should be improved already in Preview with some additional caching. However, SD cards will always be slow due unless Android itself changes how they handle them.
