### ISSUE TITLE
Image crop

### ISSUE THREAD

**Issue by Thomas-unique** [tachiyomiorg/tachiyomi#10156]
### Steps to reproduce

Hi, recently I've been having problems with page breaks that can be violent, I see a lot of them on webtoon fr but I've also seen them on the asura (breaks that are only there when I'm reading on the tatchiyomi player, not on the web player).

### Expected behavior

![Screenshot_2023-11-19-23-38-38-660_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/960152fd-d1f6-4005-ba21-ef6473e98b8a)
![Screenshot_2023-11-19-23-38-48-155_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/2479e2b6-939c-490f-b468-b6c73fcfb81c)
![Screenshot_2023-11-19-23-28-32-783_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/4ddd3a09-f4ce-4855-a3fc-cc9c1d1eac0b)

### Actual behavior

![Screenshot_2023-11-19-23-28-00-946_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/3f8be90f-9fe9-4e89-ad59-1488a79fa086)
![Screenshot_2023-11-19-23-30-18-097_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/47096d17-b7f9-4552-bb32-b544f039f3a2)
![Screenshot_2023-11-19-23-30-24-568_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/ddba3e94-e280-4026-849e-a8b421fa45a7)
![Screenshot_2023-11-19-23-30-34-881_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/362e65a2-8a7f-4576-b61e-f15208e799d0)
![Screenshot_2023-11-19-23-30-38-583_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/79210977/c9930d72-4a9d-473f-a2f2-8f9a48a48cc0)

### Tachiyomi version

0.14.7

### Android version

13

### Device

POCO X5 PRO 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
turn off crop borders in the reader settings
