### ISSUE TITLE
The installed extension will be prompted that it is not installed when it is restarted, and the plug-in will go to the migtate tab

### ISSUE THREAD

**Issue by feida2021** [tachiyomiorg/tachiyomi#10168]
### Steps to reproduce

1、install  tachiyomi in HUAWEI Harmony OS 4
2、install “包子漫画” extension
3、exit tachiyomi app and restart it 
4、app prompt the "“包子漫画” extension  has not been installed
![image](https://github.com/tachiyomiorg/tachiyomi/assets/77482360/a32bd2f2-4e3a-43ca-881c-b087c3078695)

![Screenshot_20231124_160422_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/77482360/41b48742-c51a-4f0a-9d1b-eda301f01fb4)

### Expected behavior

the extension works well and can browse comics normally

### Actual behavior

the extension is not working properly,indicating that it is not installed

### Tachiyomi version

0.14.7

### Android version

 HUAWEI Harmony OS 4

### Device

huawei matepad air

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is the extension still installed if you check in the system settings? If it isn't, there isn't much we can do if something else is uninstalling it.

If you use the Preview version of the app, you can use the "Private" installation mode that just loads extensions from disk rather than installing them as separate apps.

If you're in China, Huawei's supposed to stop supporting Android apps entirely soon anyway so maybe it's a non-issue in that sense.

**Comment by feida2021** [comment]
> Is the extension still installed if you check in the system settings?

yes , it's still installed

**Comment by feida2021** [comment]
Hello, I think it's because I disabled the permission to read the list of installed applications. After I released the permission, it returned to normal.

**Comment by feida2021** [comment]
thanks!
