### ISSUE TITLE
DOWNLOAD

### ISSUE THREAD

**Issue by SMY19** [tachiyomiorg/tachiyomi#10169]
### Steps to reproduce

The manhwa i download gets deleted from my device the next day.

### Expected behavior

The manhwa should not get deleted and only be deleted after i remove from downloads.

### Actual behavior

Instead of remaining in my phone storage it automatically gets deleted and is not stored even in my recycle bin.

### Tachiyomi version

1.7.3

### Android version

Android 13

### Device

Samsung Galaxy F14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't the J2K repo, and you probably need to just check your settings.
