### ISSUE TITLE
Atualização de mangas para

### ISSUE THREAD

**Issue by MarkLeeGold** [tachiyomiorg/tachiyomi#10162]
### Steps to reproduce

A atualização dos mangas para antes de completar

### Expected behavior

Atualiza-se até o fim

### Actual behavior

Faltando uns 10 mangas da minha lista para atualizar 
Atualização some e não faz download

### Tachiyomi version

1.7.3

### Android version

Android 13

### Device

Tab galaxy a8 2021

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do read and follow what you have acknowledged.

> If this is an issue with an extension, I should be opening an issue in the extensions repository.

> I have gone through the FAQ and troubleshooting guide.
