### ISSUE TITLE
The app contains a trojan 

### ISSUE THREAD

**Issue by AngelSaid16** [tachiyomiorg/tachiyomi#10161]
### Steps to reproduce

In virustotal.com i did a test of its application, the results showed me that the application had a Trojan 
![Screenshot_20231120_104652_Chrome](https://github.com/tachiyomiorg/tachiyomi/assets/98722818/dbfd3c06-7bc8-4ed8-8847-00895d558a01)

![Screenshot_20231120_104633_Chrome](https://github.com/tachiyomiorg/tachiyomi/assets/98722818/6d28bee6-b1f5-482e-abf9-49c425c16e5c)

https://www.virustotal.com/gui/file/73fbb8678274bbc90878237192c9c2f7cdcfac25b8f75a81e10d65c06d524d75/detection

### Expected behavior

I hope the trojan is removed from the application 

### Actual behavior

The behavior of the application is the same but I am not sure if the trojan generates any vulnerability to the system 

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Samsung Galaxy Tab A7 Lite

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [ ] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [ ] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Read this  thread
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1678
