### ISSUE TITLE
Like manga preview on apps with the web is different

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi#10163]
### Steps to reproduce

1. having an likemanga extension  https://likemanga.io/
2. while reading the manhwa the picture got crop
3. but at the site. its all fine

### Expected behavior

1. having an likemanga extension https://likemanga.io/
2. while reading the manhwa the picture is all show with no problem until the end and same preview with the site

### Actual behavior

1 having extension on like manga    https://likemanga.io/
read one of the manhwa that been updated by likemanga, but the view at apps with the site is different. it got crop

### Tachiyomi version

0.14.7

### Android version

Android 12

### Device

samsung galaxy note 10

### Other details

![Screenshot_20231121_164439](https://github.com/tachiyomiorg/tachiyomi/assets/105035665/ef40226a-d4ec-4e97-b770-79c7f84f6981)
![Screenshot_20231121-164354_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi/assets/105035665/a3562d80-8d85-48d4-a727-3c3d149864b0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
