### ISSUE TITLE
Non-gesture system navigation bar tinted with theme color

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#10179]
### Steps to reproduce

Open the app

### Expected behavior

The taskbar should be the same color as the rest of the app

### Actual behavior

![Screenshot_20231126_013630_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/61708534/c682182b-e32b-4fee-a113-baec8654c1c4)

### Tachiyomi version

r6232

### Android version

Android 13

### Device

Galaxy Tab A8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I edited the title assuming you meant the navigation bar, but now I'm not actually sure.

What is a "taskbar", and which color is "the same color as the rest of the app"?

**Comment by BrutuZ** [comment]
I don't even see the taskbar there, only the system soft buttons.
When talking about tablet mode taskbar I think of the one at the bottom:
![Screenshot_20231126-194547](https://github.com/tachiyomiorg/tachiyomi/assets/7104931/6b080562-15f8-483d-a743-41a755cdd9f5)

Which like yours, is also drawn on top of the application (despite being opaque in this case) instead of being the lower boundary for the application canvas

**Comment by specterflare** [comment]
Ok, wow, mind blown. I guess the navigation bar (yes, that was what I was referencing) has always been tinted, though it used to be such a subtle tint that I never noticed:
![Screenshot_20231126-195529](https://github.com/tachiyomiorg/tachiyomi/assets/61708534/e86a3f15-4b93-474e-ad00-843eec9718c1)

IMHO I think it looks better the old way.
