### ISSUE TITLE
The extension does not work Manga Fire

### ISSUE THREAD

**Issue by AngelSaid16** [tachiyomiorg/tachiyomi#10170]
### Steps to reproduce

1. Intall the extensión Manga Fire
2. Search manga un the extension manga fire
3. The website does work, however it seems the application is not compatible with Manga Fire

### Expected behavior

The extension Manga Fire Work properly 

### Actual behavior

The extension does not work

### Tachiyomi version

0.14.7-6210

### Android version

Android 10

### Device

Oppo A15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
