### ISSUE TITLE
Comics

### ISSUE THREAD

**Issue by AngelSaid16** [tachiyomiorg/tachiyomi#10171]
### Describe your suggested feature

I would like the application to not only be compatible with manga extensions, but also comics.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It already have some comic websites. Explore the app and you will find it. Also this isn't the repository to request extensions.
