### ISSUE TITLE
Filter by scanlator

### ISSUE THREAD

**Issue by earl-bulasa** [tachiyomiorg/tachiyomi#10189]
### Describe your suggested feature

It would be good if we can filter by scanlator like what we have with other forks.

### Other details

I don't want to use other forks since I like the vanilla tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already done in #969
