### ISSUE TITLE
Plz

### ISSUE THREAD

**Issue by KingreyArthur** [tachiyomiorg/tachiyomi#10185]
### Describe your suggested feature

Hi i like the tachiyomi app and it an amazing app however if u could could add a new appearance in tachij2k
Grey wolf like in neko app and keep the pure black mode also change the manga page and make it simillair to neko app that it thank u

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/issues

Also do try to actually put effort in writing a title.

**Comment by KingreyArthur** [comment]
So r u gonna do it ?????

**Comment by arkon** [comment]
This isn't the TachiyomiJ2K repo, go request it there.

**Comment by KingreyArthur** [comment]
I couldnt find it could u give me a link plz

**Comment by arkon** [comment]
Are you ever reading the replies...
