### ISSUE TITLE
Duplicate calls to source when opening entry from browse screen

### ISSUE THREAD

**Issue by AwkwardPeak7** [tachiyomiorg/tachiyomi#10198]
### Steps to reproduce

Open new entry from browse screen on any source

### Expected behavior

should call for details and chapters once each

### Actual behavior

calls both twice

### Tachiyomi version

r6237

### Android version

Android 14

### Device

Android Studio emulator

### Other details

For comparison:

Stable:
![Capture-stable](https://github.com/tachiyomiorg/tachiyomi/assets/48650614/99ecec49-8432-4fcb-8603-8e0a621fc697)

Preview:
![Capture](https://github.com/tachiyomiorg/tachiyomi/assets/48650614/2bfb0567-86d0-4db1-9efd-4e0934f82753)
same requests are repeated twice

Also, on manual refresh, this behavior is not observed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
May be related to M3 PTR migration (#10164) triggering `onRefresh`.
