### ISSUE TITLE
New themes

### ISSUE THREAD

**Issue by Herciyuan** [tachiyomiorg/tachiyomi#10194]
### Describe your suggested feature

Add these themes from aniyomi: 
![Screenshot_2023-11-30-12-57-23-403_xyz jmir tachiyomi mi debug](https://github.com/tachiyomiorg/tachiyomi/assets/88514130/ea618cec-d700-4fdf-8990-b118e4eb13fb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Other than Matrix, which only works in dark mode and is already similar to Green Apple, all of them look pretty bad.
