### ISSUE TITLE
Option to filter by categories inside categories 

### ISSUE THREAD

**Issue by lilToucan** [tachiyomiorg/tachiyomi#10205]
let's say you have Manga X & Y 
and category ⭐ & ⏸️ 

now X is in category ⭐ 
while Y is in both ⭐ and ⏸️

let's say that Y has more unread ch then X 
so if I sort by unread ch then Y will be on top

this becomes a little frustrating when you have a bunch of ⏸️ Manga that are also in ⭐

what could be the fix is that I can filter out the manga from ⏸️ and then sort by unread ch

ex. below
![IMG_20231203_002120](https://github.com/tachiyomiorg/tachiyomi/assets/151180862/efd361d2-0e1b-47fc-8ac3-fb1375fd9fcd)
![IMG_20231203_002230](https://github.com/tachiyomiorg/tachiyomi/assets/151180862/04636952-1045-464c-ab08-4db705bb0fd8)

### Other details

Anyways great app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/9822#issuecomment-1826937509
