### ISSUE TITLE
Issues with downloading multiple chapters of the same name

### ISSUE THREAD

**Issue by AEX120** [tachiyomiorg/tachiyomi#10203]
### Steps to reproduce

Find source with multiple chapters of the same name.

Download one of the chapters.

All chapters with the same name now only show the images of the downloaded chapter, regardless of what the original images were.

### Expected behavior

When downloading 2 different chapters the downloaded chapters should show the intended images, regardless of the chapter name.

### Actual behavior

If multiple chapters have the same name, and you download one of the chapters, ALL chapters will show the images of the most recently downloaded chapter (of the same name).

### Crash logs

N/A

### Tachiyomi version

0.14.7 (or 1.7.3 for J2k)

### Android version

Android 12

### Device

Huawei Mate 40 Pro

### Other details

Very niche issue as most people name chapters differently, but I've experienced it enough for it to annoy me.

Especially prevalent on Kimono and Mangadex, as on Kemono many creators use the same generic name for uploads (eg "Archive works" or "works of march" thus overwriting the previously posted "works of march").

Mangadex has many users uploading different scans of the same chapters. One is often noticeably lower quality so it can be annoying when trying to read specifically one persons uploads.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/5051#issuecomment-878400011
