### ISSUE TITLE
Tachiyomi Preview r6258 invalidate download index clears downloaded but do not regenerate

### ISSUE THREAD

**Issue by kevin01523** [tachiyomiorg/tachiyomi#10218]
### Steps to reproduce

1, download a manga chapter 
2. checks that its downloaded and it shows as downloaded
3. use invalidate download index 
4. wait for library to refresh or try to refresh it manunally via scrolling it down or restarting app

### Expected behavior

after invalidating the download index it should re appear as donwloaded again,
downloaded chapter should appear as downloaded
only local source appear on downloaded filter

### Actual behavior

downloaded mark/count dissappear
and doesnt regenerate

### Tachiyomi version

Tachiyomi Preview r6258

### Android version

android 10 lineage OS

### Device

redmi note 6 pro

### Other details

might be related to https://github.com/tachiyomiorg/tachiyomi/issues/10187 as my old downloads also doesnt appear but also new downloads is affected once i invalidate the index

work around is to revert/downgrade to r6210  and it works as intended again and even the new downloaded chapter on the newer version appear as downloaded

since it also affects new downloaded chapters im making this issue as its only slightly related 

might also an issue related to the download folder being located on the external sd card

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Andre-Oliveira** [comment]
I'm having the same issue in r6274, downloads are in a SD card in the "downloads" folder created by the app when I set the storage location. Android version is 7.0 in my case.

The app has no issue opening the chapters when I'm offline, it just doesn't recognize them in the GUI.

**Comment by tulang3587** [comment]
> I'm having the same issue in r6274, downloads are in a SD card in the "downloads" folder created by the app when I set the storage location. Android version is 7.0 in my case.
> 
> The app has no issue opening the chapters when I'm offline, it just doesn't recognize them in the GUI.

Same here, in r6274 downloaded chapters can be read (tried turning off wifi & data, then load a chapter that should already be downloaded, works fine).
I tried clearing data & restore backup, and downloaded chapters are still not shown in UI.
