### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by DragonELlis304** [tachiyomiorg/tachiyomi#10216]
### Steps to reproduce

1. Opening Tachiyomi
2. Opening Extension
3. Issue

### Expected behavior

The extension should've open and I can browse the library

### Actual behavior

I can't browse the library

### Crash logs

 javax.net.ssl.SSLHandshakeException:java.security.cert.CertPathValidatorException:Trust anchor for certification path not found

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

OPPO Reno 5 4G, model CPH2159

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
