### ISSUE TITLE
Manga error

### ISSUE THREAD

**Issue by Ksetrar** [tachiyomiorg/tachiyomi#10226]
### Steps to reproduce

Whenever I try to open the manga, it shows this error

### Expected behavior

! Error in {min,max} interval near index 57
^The Story of How I Can Change the World With My Skill {Translation} ~ How I Used {Translation} to Become the World's Strongest! summary:\s

### Actual behavior

! Error in {min,max} interval near index 57
^The Story of How I Can Change the World With My Skill {Translation} ~ How I Used {Translation} to Become the World's Strongest! summary:\s

### Tachiyomi version

App version: 0.14.7

### Android version

12

### Device

CPH2477

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
