### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by Pantyhose-X** [tachiyomiorg/tachiyomi#10221]
### Describe your suggested feature

[Build Tor into your app, and Integrate with external Orbot or TorServices app](https://tordev.guardianproject.info/mobile-concepts/all-the-ways-to-torify)

> If you do not want to add the additional code complexity and size directly into your app, you can instead only offer active Tor features if the user has [Orbot](https://github.com/tor-on-android/netcipher-with-orbot-legacy) or [TorServices](https://github.com/tor-on-android/torservices) installed on their device. Apps like [F-Droid](https://github.com/mobile-apps-with-tor), [Save by OpenArchive](https://github.com/mobile-apps-with-tor), and [ReThinkDNS](https://github.com/mobile-apps-with-tor) do this today, to enable proxying through Tor without having to build in all of Tor.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
But why

**Comment by Pantyhose-X** [comment]
> But why

TOR can bypass the website or ISP GFW limit blockade

**Comment by AntsyLich** [comment]
Multi website also block Tor clients 🙄

**Comment by arkon** [comment]
We've rejected VPN and proxy functionality in the past in favor of just doing it with other apps/system-level functionality, so this is no different.

**Comment by curche** [comment]
fwiw, and for future reference, previous discussion(s) on proxying can be found here: https://github.com/tachiyomiorg/tachiyomi/issues/9606
