### ISSUE TITLE
Deleting the app should not lead to deletion of user data

### ISSUE THREAD

**Issue by MaggotHATE** [tachiyomiorg/tachiyomi#10224]
### Steps to reproduce

1. Install as usual
2. Keep manga saved
3. Move to another client
4. Point the client to the same location
5. Delete Tachiyomi

### Expected behavior

Data is kept since it is used by another client

### Actual behavior

Data is wiped by android system

### Tachiyomi version

any

### Android version

Android 10

### Device

Redmi Note 9s

### Other details

* Users should not be expected to move data when switching clients
* Application should not store downloaded manga in places where it can be wiped along with the app itself
* Application should not encourage android system to delete user data

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Essentially #1432.

Just make a backup and save that file somewhere

**Comment by MaggotHATE** [comment]
@CrepeTF Backup of what, all the downloaded manga? In a case when the official client was used for a long time, the total size can get quite large. 

It's not adequate to expect that a user will make backups of the entire collection before deleting an application. It's not about in-app data, it's external user data.

**Comment by CrepeTF** [comment]
https://tachiyomi.org/docs/guides/backups#backups

**Comment by MaggotHATE** [comment]
@CrepeTF 
# What's NOT included in a backup?
* Reading history of titles NOT in library
* Settings including app settings and extension-specific settings
* **Downloaded chapters including [local source](https://tachiyomi.org/docs/guides/local-source/) chapters**

So you are saying I cannot back downloads up, but can easily delete them by deleting the client?

There's even no mentioning of the issue on https://tachiyomi.org/docs/guides/local-source/ .

**Comment by CrepeTF** [comment]
Downloads won't be deleted from your phone as long as the download location is not on your android/data folder (which tachiyomi does not do by default - it saves to Internal storage/Tachiyomi/downloads).


As for transferring downloads to another device; Tachiyomi is open-source and non-profit so it is just not feasible for us to pay for a server for your andthe other 1million+ users downloads.

**Comment by MaggotHATE** [comment]
I didn't have /Tachiyomi/downloads as a default folder, it was pointing at appdata either on Internal or on SD card. I guess it was fixed at some point. If the new default is outside of appdata, sorry for the fuzz.

**Comment by arkon** [comment]
We indeed removed that option a while back since people weren't aware that the app data folder gets removed with the app. Newer versions of Android also prohibit users from normally accessing those folders anyway.

**Comment by MaggotHATE** [comment]
@arkon sorry for another question, but I was under the impression that it is the opposite on newer versions of Android (i.e. appdata is the only folder where application can store their data, not in custom folders).

If newer Android versions prevent users from accessing those folders, why are they still in default options?

**Comment by arkon** [comment]
> appdata is the only folder where application can store their data, not in custom folders

Yes, unless the user grants access to a folder. The user however cannot select the app data folders, at least normally.

> If newer Android versions prevent users from accessing those folders, why are they still in default options?

It's not.

**Comment by MaggotHATE** [comment]
So these folders are only shown if updated from a very-very old version? Alright, thanks for the answers!
