### ISSUE TITLE
Restoration backup resets if run in background

### ISSUE THREAD

**Issue by jxsl13** [tachiyomiorg/tachiyomi#10229]
I updated to the latest version a few hours ago which seemingly reset my whole library.

Trying to restore a backup (like 15mb) takes quite long, so I am running it in the background.

Running it for too long in background continues to restore the backup but seemingly closes the main application. When switching back to the app while the restoration is ongoing, the backup is reset to the beginning, wiping all of the progress that has been restored so far.   

```
App version: 0.14.7-6274 (standard, 8c21aa86e, 112, 2023-12-09T23:25Z)
Android version: 14 (SDK 34; build UP1A.231105.003)
Device brand: google
Device manufacturer: Google
Device name: lynx (lynx)
Device model: Pixel 7a
WebView: Android System WebView 119.0.6045.193
```

**Comment by arkon** [comment]
Please do use the templates in the future: https://github.com/tachiyomiorg/tachiyomi/issues/new/choose

You could try turning off battery optimizations in the advanced settings so that the app is less likely to get killed by the system.

Longer term, #7966 is probably the only way to deal with this by allowing people to effectively chunk it themselves.

**Comment by jxsl13** [comment]
The restoration with the progress bar seems to still do its job but starting the (by battery optimization) killed app again, seemingly interrupts whatever is happening there with the progress bar, aborting or completely resetting whatever of the backup has been restored.
Either it's just a visual bug that the restoration progress is visible even tho the main app was killed (kinda doubt, as long running library updates are also running in the background just fine).

My guess is there might be some check missing to check if a restoration is already running before resetting/starting another backup restoration automatically (whatever triggers that) upon resuming of the main application that was killed by battery optimization.

**Comment by arkon** [comment]
> starting the (by battery optimization) killed app again

I don't understand this part.

> starting another backup restoration automatically (whatever triggers that)

Restores can only be triggered manually, and it checks if something's already running.

Can you share the crash logs from More → Settings → Advanced?
