### ISSUE TITLE
API limit reached error

### ISSUE THREAD

**Issue by Resimaa** [tachiyomiorg/tachiyomi#10230]
### Steps to reproduce

1.Tap on a chapter
2. It will open a black screen and it will load
3. And the message wil appear

### Expected behavior

To open the chapter and that i can read it.

### Actual behavior

![Screenshot_20231212_172148_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/143012426/6ea930cd-46ba-4388-a1f7-5a01d15a07c4)

### Tachiyomi version

0.14.7

### Android version

Android 14

### Device

Samsung galaxy a53 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
