### ISSUE TITLE
Bug yang harus di perbaharui

### ISSUE THREAD

**Issue by Ashuravein** [tachiyomiorg/tachiyomi#10234]
### Steps to reproduce

Klik eksistensi doujin desu
Tidak ada halaman saat mengklik chapter
Jadi harus segera di perbaiki

### Expected behavior

Eksistensi berjalan tapi saat mengklik chapter tidak ada halaman

### Actual behavior

Tidak ada halaman saat mengklik chapter di doujindesu

### Crash logs

Tidak ada halaman saat membuka chapter tolong di perbaiki

### Tachiyomi version

0.14.7

### Android version

Andoid 13

### Device

Infinix

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Ashuravein** [comment]
Please fixed the bug

Pada tanggal Kam, 14 Des 2023 05.55, arkon ***@***.***>
menulis:
