### ISSUE TITLE
Añadir extensión 

### ISSUE THREAD

**Issue by 12346lotw** [tachiyomiorg/tachiyomi#10243]
### Describe your suggested feature

Yugenmanga dejara de funcionar.
Cambiar extensión a su nueva pagina ikigaimangas.com

### Other details

Ikigaimangas ya está en funcionamiento.
Se eliminará la página de yugenmangas.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
