### ISSUE TITLE
[Feature Request] Allow toggling off unread chapter marker

### ISSUE THREAD

**Issue by Raxcoms** [tachiyomiorg/tachiyomi#10249]
### Describe your suggested feature

A dot marking unread chapters was added to tachiyomi to solve the issue #4261, however when not using an e-ink device the repeated pattern and misalligned chapter title just adds complexity and redundancy to the overall experience as the read and unread chapters are already distinct enough for most people through their luminosity alone.

I want to suggest the ability to toggle off the unread chapter marker, while keeping the marker on as the default option to help e-ink users and any visually impaired individuals that might benefit from it.

### Other details

Image for reference

<img src="https://private-user-images.githubusercontent.com/15233644/291628139-03cc19ea-11c7-4780-8bd4-1b5dcc1581ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTg3MzcsIm5iZiI6MTcwMjk5ODQzNywicGF0aCI6Ii8xNTIzMzY0NC8yOTE2MjgxMzktMDNjYzE5ZWEtMTFjNy00NzgwLThiZDQtMWI1ZGNjMTU4MWVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Y2RhMzU2NzhlZTRjMTMwZWYwNDIwMDg2ZGJkOTEzOWM5NGNmNTMwZWEzMjNlNTYxZDkxNmJiYzZjYzliMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf2SmkKuHT64O2_W5KAtM64rGHKWvf06urOJYB0D2Tc" width="360">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Doesn't hurt to have for anyone; not worth the complexity of adding another option.
