### ISSUE TITLE
Malware/antivirus detection for extensions

### ISSUE THREAD

**Issue by jcayzac** [tachiyomiorg/tachiyomi#10246]
### Describe your suggested feature

My phone's antivirus (which uses Avast's DB) just reported a rootkit shipping with the MangaRead and MangaRead.org extensions.

It would be nice if infected extensions weren't available in the menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It's just a false positive. You can confirm by checking the source code in the extensions repository. Please report it as a false positive to your antivirus company.
