### ISSUE TITLE
[Feature Request] tachiyomi API for interaction with another app.

### ISSUE THREAD

**Issue by X-Oracle** [tachiyomiorg/tachiyomi#10254]
### Describe your suggested feature

There is a situation where I want to add manga from an anilist client app to tachiyomi but I need to copy it's name and do global search for it.

It is good but if mangas are too many then it would be tiering.

The could be an API or something like that ( ex: in android text share ) so it could go to tachiyomi global search directly from another app.

I would like to know your opinion for this.
Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by JDKamalakar** [comment]
It's already Present.

**Comment by X-Oracle** [comment]
Oh . I just saw that. Thanks
