### ISSUE TITLE
Issue duplicate pages downloaded

### ISSUE THREAD

**Issue by MrNoob001** [tachiyomiorg/tachiyomi#10258]
### Steps to reproduce

- Go to : Settings >> Downloads >> ( Enable ) Split tall images
- and download any Chapter ( didn't test with any other manga )

### Expected behavior

to download the chapter without extra copies for the page 

### Actual behavior

downloads the chapter with extra copies for every page from 1 to 3 copies

it downloads the image with Sorting and then duplicates 2 - 4 pages with or without sorting
![Screenshot_٢٠٢٣١٢٢٢-١٢٥٢٣٤](https://github.com/tachiyomiorg/tachiyomi/assets/23222675/baa87aea-af66-4b22-9606-555d55eadfac)

### Crash logs

sorry don't have it
you can reproduce the bug with ease

### Tachiyomi version

0.14.7

### Android version

11

### Device

Infinix HOT 10 Play

### Other details

this bug was mentioned beffore : https://github.com/tachiyomiorg/tachiyomi/issues/6977

but was closed for claiming that it's not a bug.. 
manga in screenshot : I Picked A Hammer To Save The World
source : Mangakakalot (EN)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MrNoob001** [comment]
right this did  happen beffore ( in older version a few months ago ) but i didn't know if the reason was "Split tall images" or not

**Comment by arkon** [comment]
Seems probably related to split tall images. Are those file names numbers after the `__` parts?

**Comment by MrNoob001** [comment]
> Seems probably related to split tall images. Are those file names numbers after the `__` parts?

Yes and Yes 
And if there any other way to check if there is no other reason please do 
like i said beffore :
> right and this **happend beffore** ( in older version a few months ago ) but i didn't know if the reason was "Split tall images" or not
Thanks .
