### ISSUE TITLE
[Manga-scan] [FR] images don't load

### ISSUE THREAD

**Issue by ElCacciatore** [tachiyomiorg/tachiyomi#10253]
### Steps to reproduce

Go to a manga, read Last Chapter, images don't load. 

### Expected behavior

Images load. 

### Actual behavior

When i open the Chapter in the browser in app,
![Screenshot_2023-12-21-01-06-18-144_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/147109743/8c1e3b1d-3e29-4eec-ba30-b77d030e1fde)
![Screenshot_2023-12-21-01-06-35-583_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/147109743/9e25f909-918c-45e7-9519-a9cb6e0ae5d5)
![Screenshot_2023-12-21-01-07-01-531_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/147109743/a4c80297-d5c4-449b-be8b-ea3ad52a533c)
![Screenshot_2023-12-21-01-07-23-907_com android chrome](https://github.com/tachiyomiorg/tachiyomi/assets/147109743/d162353e-6d74-48c8-b532-ff6e6e832e27)
 images don't load. With an external browser (chrome) images load

### Tachiyomi version

0.14.7

### Android version

11

### Device

Xiaomi pad 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
