### ISSUE TITLE
The site does not have its own search

### ISSUE THREAD

**Issue by matheus-giordani** [tachiyomiorg/tachiyomi#10251]
### Steps to reproduce

1 - Install "ler mangá" extension
2 - search any manga 
![Screenshot_20231220_135401_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/74312355/3960c5b3-572a-4ecf-9353-13e7309a3721)

### Expected behavior

The expected behavior would be to load a title or say that it doesn't have one because when I open the website's webview it has the same search as the others

### Actual behavior

"o site não possui busca própria" (The site does not have its own search)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Samsung s20 fe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Cool story.

> If this is an issue with an extension, I should be opening an issue in the extensions repository.
