### ISSUE TITLE
all my download manga has been deleted from the app. The problem is that I have the manga in the Tachiyomi files in cbz shape but it doesn't show in app

### ISSUE THREAD

**Issue by KDRAGON1** [tachiyomiorg/tachiyomi#10259]
### Steps to reproduce

![Screenshot_20231223-004746_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/154638373/3d112ede-3830-4ee4-b083-3e62cdc3391b)

### Expected behavior

Please provide a solution to the problem

### Actual behavior

all my download manga has been deleted from the app. The problem is that I have the manga in the Tachiyomi files in cbz shape but it doesn't show in app

### Tachiyomi version

0.14.7

### Android version

Android 11

### Device

Samsung galaxy A30. Model SM_A305F

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably same behavior as #10062
