### ISSUE TITLE
Install unknown permissions is mandatory during setup

### ISSUE THREAD

**Issue by Eskuero** [tachiyomiorg/tachiyomi#10257]
### Steps to reproduce

1. Run a clean install of Tachiyomi
2. Asks for a few required permissions, one of them being "Allow to install unknown apps"

### Expected behavior

The general public will install extensions within the app but since we can install them externally and the ability to "trust" those later exists within Tachiyomi I think it would be fair to not mandate the permissions.

I understand is a very minor inconvenience and probably low priority tho.

### Actual behavior

You are forced to give the permission as otherwise the continue button is greyed out. After setup you can remove the permission without any further issues.

### Tachiyomi version

0.14.7 (built from master branch)

### Android version

Android 13

### Device

Galaxy A23 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Was discussed internally as well. Other options include:

- A banner in extensions list if permission not granted
- Alert dialog when attempting to install if permission not granted
