### ISSUE TITLE
Geckoview instead of Webview

### ISSUE THREAD

**Issue by david79111** [tachiyomiorg/tachiyomi#10260]
### Describe your suggested feature

Is it possible to add a feature that lets tachiyomi use geckoview if firefox is installed, instead of using webview?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/mozilla/geckoview/issues/167

This isn't possible without embedded the entirety of Geckoview ourselves, which isn't worth it.
