### ISSUE TITLE
Rate the sources out of 5 for ease of selection

### ISSUE THREAD

**Issue by Safwam-daw** [tachiyomiorg/tachiyomi#10266]
### Describe your suggested feature

When opening the list of sources, there is no clarification of the source, whether it is good or bad, so I thought that if there was an evaluation of the sources by the users, they would log in to the program and add the evaluation out of 5, in order to make it easier for the users to choose the good sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We have no desire to maintain servers.

We also intentionally do not recommend sources to avoid having a majority of users skewed towards very few sources, which can overload/kill them.

If there's "bad" sources that don't work properly, report them to https://github.com/tachiyomiorg/tachiyomi-extensions to either be fixed or removed.

**Comment by Safwam-daw** [comment]
Thank you for clarifying the vision 🌹
