### ISSUE TITLE
For old version android users

### ISSUE THREAD

**Issue by FemanD-AI** [tachiyomiorg/tachiyomi#10264]
### Describe your suggested feature

It should be available for androId 5.1.1 users as well

### Other details

The current update isn't compatible with my android version so , please add a new feature for that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We have no intention to support a 9 year old android version
