### ISSUE TITLE
Downloaded chapters aren't available to read

### ISSUE THREAD

**Issue by WeepingClown13** [tachiyomiorg/tachiyomi#10268]
### Steps to reproduce

Not sure if this is a recurrent issue, I have faced only this once yet. The issue happened in Wind Spirit manhwa from Mangakakalot extension. Steps are, I'd say, download the chapters of the same from the given extension.

### Expected behavior

Downloaded chapters are available and readable and it does not need to look for internet.

### Actual behavior

Thumbnail shows the downloaded chapter count as well as the download location also contains the downloaded chapters, but when the manhwa is opened, none of the chapters are marked as downloaded (i.e. the downloads aren't loaded) and upon opening each chapter it loads from the internet instead of using the local download.

![Screenshot_20231225_231053_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/95921427/63d1cc77-ff3d-4633-8860-2a424c87f8c6)
![Screenshot_20231225_231618_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/95921427/021c0852-8d68-4463-bb97-f5f482c84c7f)
![Screenshot_20231225_231216_My Files](https://github.com/tachiyomiorg/tachiyomi/assets/95921427/8d7869cb-6ef1-4780-b44c-b81526b6110e)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Samsung Galaxy S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The scanlators "changed" from ".com" to ".to" so none of those downloads are considered matching. You can rename them to match, or move them to local to read (https://tachiyomi.org/docs/guides/local-source/).

**Comment by WeepingClown13** [comment]
@arkon the solution works, so thanks :)
But in this scenario, it doesn't make sense for the downloaded chapters badge to show the _unmatched_ chapters count, I'd flag it as a bug. The downloaded chapters badge should count the chapters iff those chapters can be loaded, otherwise it only misleads. If you agree with me on this, I'm willing to open a seperate bug for that.

**Comment by arkon** [comment]
I think it was already discussed a few years ago and consensus was people would rather know there's stray files lying around than not.
