### ISSUE TITLE
Flash black and white on page change to mitigate ghosting on e-ink devices

### ISSUE THREAD

**Issue by I2ujbNGakP8KfLKbho0Z** [tachiyomiorg/tachiyomi#10269]
### Describe your suggested feature

**Steps to reproduce:** 
1. Use android e-ink device
2. Use preview after [r6150](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r6150), that includes fix for #2123.
3. Enable white flashing on page change
4. Open a manga with lots of black patterns
5. Change page

**Expected behavior:**
After page change and the white flash, next page is displayed without ghosting of the previous page.

**Actual behavior:**
The page changes, the display flashes white but there still is ghosting in the image on the next page.

**Suggestion:**
This might be mitigated by a different flashing cycle. For example, the tolino epos 3 (similar to Kobo Sage 2) first flashes black for a short duration, then white for a longer duration, and then black again. The whole refresh cycle takes approximately 1.5 seconds.

Maybe add options for different flashing cycles?

Flashing the whole screen white is pretty uncommon on e-ink devices, so if there should just be one option, the one described above or just flashing black would probably be better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I changed it to a 1.5s black flash, so you can try that in the next build. I don't really have anything to test with.

**Comment by I2ujbNGakP8KfLKbho0Z** [comment]
I will try it out as soon as possible! Currently, #10270 is still a problem for me, so all previews with the onboarding screen sadly don't allow me to test anything.

**Comment by THElegend5** [comment]
> I changed it to a 1.5s black flash, so you can try that in the next build. I don't really have anything to test with.

@arkon from what I can tell my kindle displays the inverse of the image after every page turn,  so that might be somethign to consider if this doesn't work?
