### ISSUE TITLE
I cant read some mangas

### ISSUE THREAD

**Issue by AboloMase** [tachiyomiorg/tachiyomi#10261]
### Steps to reproduce

I was just reading and then out of no where this message kept popping up preventing me from reading 

https://github.com/tachiyomiorg/tachiyomi/assets/149656160/0b436ace-39a5-4a62-80e9-ca9e6a5a0f27

### Expected behavior

I expect the chapter to open up and be available for me to read 

### Actual behavior

Whenever it click to open the chapter it doesn't let me read 

https://github.com/tachiyomiorg/tachiyomi/assets/149656160/ee8768e9-5be8-4b98-a72f-800e9de473b3

### Crash logs

https://github.com/tachiyomiorg/tachiyomi/assets/149656160/6f03dd95-b158-4452-8444-f9b09b3bed9a

### Tachiyomi version

0.14 7

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra 

### Other details

I hope this can be fixed so I can continue reading and I also would like to wish u a Merry Christmas and a Happy New Yeae 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Turn off whatever Telstra is doing to intercept your Internet traffic if you can or use a VPN.

**Comment by AboloMase** [comment]
How exactly do I turn of what telstra is doing

**Comment by arkon** [comment]
I don't know, I'm not a Telstra customer nor a Telstra customer service agent.
