### ISSUE TITLE
Error trying to restore backup

### ISSUE THREAD

**Issue by FoxythePlush** [tachiyomiorg/tachiyomi#10275]
### Steps to reproduce

1. Opened app on new phone and found no library
2. Attempted to restore backup but got error
3. Uninstalled current version and installed previous version
4. Tried to restore again, same result
![Screenshot_20231228_215849_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi/assets/30099856/210de7ba-4c2a-43e7-ae3d-40f952174b35)

### Expected behavior

Smooth easy backup restoration from previous    backup file. File is attached
[2023-12-28-release.log](https://github.com/tachiyomiorg/tachiyomi/files/13790819/2023-12-28-release.log)

### Actual behavior

Invalid Backup File: kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 7
![Screenshot_20231228_215849_TachiyomiSY](https://github.com/tachiyomiorg/tachiyomi/assets/30099856/945dac7c-a5b5-4092-904f-b2ccb3a6eab1)

### Tachiyomi version

1.9.4 -> 1.9.3

### Android version

S9 -> S23

### Device

Android

### Other details

I transferred to a new phone today and when tried restoring the last backup from 12/28, I got an error message. I show the update from 12/29 so I thought maybe it was a compatibility issue but the error still shows.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That's not a backup file, it should either be a `.proto.gz` or a `.tachibk` file.
