### ISSUE TITLE
HTTP Error 500 mangahere

### ISSUE THREAD

**Issue by Ancienttwist** [tachiyomiorg/tachiyomi#10287]
### Steps to reproduce

*

### Expected behavior

*

### Actual behavior

Cant update library mangahere

### Crash logs

![IMG_20240104_083746](https://github.com/tachiyomiorg/tachiyomi/assets/80474536/b195f882-e234-445f-b907-7827a686879c)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Device

POCO X3 NFC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
