### ISSUE TITLE
[FR] Allow user-addable extension repos 

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#10289]
### Describe your suggested feature

Currently, the app only pays attention to the extensions repo https://github.com/tachiyomiorg/tachiyomi-extensions - I think that users should be able to add additional sources, should they choose to. Of course, these will be unsigned, and warning labels will be in place, but a re-install of a modified app should not be a requirement do do so. 

### Other details

A bit similar to issue #9928 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Has been added. Wait for next update
