### ISSUE TITLE
(Set as cover,Share,Save)

### ISSUE THREAD

**Issue by lxymix** [tachiyomiorg/tachiyomi#10293]
### Describe your suggested feature

Please add a setting to on and off for these (Set as cover,Share,Save)

Because when I'm reading manga etc... i tend to read in webtoon and scrolling activate these and i find it annoying (I don't know if others find it annoying or try have the same problem)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already exists ("Show actions on long tap").
