### ISSUE TITLE
升级到0.15.0后，已下载漫画的状态消失

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi#10292]
### Steps to reproduce

在0.14.7下载了很多漫画，升级到0.15.0后，选择了原本的tachiyomi文件夹，在已下载的章节后不显示“✓”（但不影响离线阅读），且使用“已下载”筛选无结果
已下载章节点击下载按钮无反应，标记为已读后本地文件会被删除
经过清除数据重新恢复，卸载重装均不能正常显示

### Expected behavior

![Screenshot_2024-01-06-23-46-38-909_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/36665073/a7287fa0-6d51-441e-8015-ac5e6a2001c1)
图片中未读章节在0.14.7版本中已经下载，点击下载按钮没有反应

### Actual behavior

不显示已下载图标，无法筛选已下载

### Tachiyomi version

0.15.0

### Android version

Android 14

### Device

Xiaomi 14 Pro

### Other details

下载漫画较多，无法筛选严重影响使用，现已降级到0.14.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Select "Tachiyomi" folder. Not "Tachiyomi/downloads"

**Comment by 362516282** [comment]
i have already done that since the first time, but didn't work....

**Comment by AntsyLich** [comment]
can you join the support server?

**Comment by Achuabdu** [comment]
@362516282 brp which manga is it

**Comment by 362516282** [comment]
@AntsyLich sorry, we are not allowed to get out from the wall.

**Comment by AntsyLich** [comment]
> @AntsyLich sorry, we are not allowed to get out from the wall.

right. Can you send a screenshot of Data and Storage settings and the folder your downloads are in?
