### ISSUE TITLE
> Select "Tachiyomi" folder. Not "Tachiyomi/downloads"

### ISSUE THREAD

**Issue by Irfan000666** [tachiyomiorg/tachiyomi#10296]
> Select "Tachiyomi" folder. Not "Tachiyomi/downloads"

I did select the "Tachiyomi" folder. But it does not shows the manga that you have downloaded. And when I try to re-download the manga it dosent let me.

_Originally posted by @Irfan000666 in https://github.com/tachiyomiorg/tachiyomi/issues/10295#issuecomment-1879758332_

**Comment by haffizhissham** [comment]
Similar issue.

Local folder however are working fine.

**Comment by arkon** [comment]
See https://tachiyomi.org/docs/faq/storage

If you're confident you're following the structure correctly, create an issue showing examples of your set storage location and what your folders look like.
