### ISSUE TITLE
Download Not detected 

### ISSUE THREAD

**Issue by Irfan000666** [tachiyomiorg/tachiyomi#10295]
### Steps to reproduce

Just updated to the newest version 
And let it have access to my storage on my sd card 
But could not detect any of the downloads that I already have.

### Expected behavior

Should be able to detect all of my downloads.

### Actual behavior

Could not detect anything.

### Tachiyomi version

0.15.0

### Android version

Android 12

### Device

Samsung S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Select "Tachiyomi" folder. Not "Tachiyomi/downloads"

**Comment by Irfan000666** [comment]
> Select "Tachiyomi" folder. Not "Tachiyomi/downloads"

I did select the "Tachiyomi" folder. But it does not shows the manga that you have downloaded. And when I try to re-download the manga it dosent let me.
