### ISSUE TITLE
The ability to change font in the app

### ISSUE THREAD

**Issue by Tamzid09** [tachiyomiorg/tachiyomi#10300]
### Describe your suggested feature

It would be nice if we could change the font in the app. Providing a variety of fonts would help the users customize the app to their taste a bit better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Change your phone's font
