### ISSUE TITLE
Credibility of third-party book sources.

### ISSUE THREAD

**Issue by EVOKF** [tachiyomiorg/tachiyomi#10307]
### Describe your suggested feature

Every time I open an application to use third-party book sources, I need to give my consent every time. However, in previous versions, I needed to give my consent once to continue using them, which greatly affects the experience.

### Other details

I hope to make changes so that it can be used all the time with one consent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#10290
