### ISSUE TITLE
Error "No file picker app found" when trying to create a backup.

### ISSUE THREAD

**Issue by Giwayume** [tachiyomiorg/tachiyomi#10301]
### Steps to reproduce

1. Click "create backup" button in settings
2. Click ok on the dialog that asks what to back up

### Expected behavior

Files app should open to choose a backup location

### Actual behavior

Toast is displayed "No file picker app found"

### Tachiyomi version

0.14.7

(I can't update the app because I can't back up my data!)

### Android version

Android 9

### Device

Pixel 3a XL

### Other details

I have several file apps installed (for testing):
- Files by google
- Material files
- Amaze
- ASTRO
- File Manager +

When I choose the option to restore a backup, that works to open a file manager app and pick a file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Considering we're not doing anything special to open those, this seems like a ROM issue. The Pixel 3a received updates until Android 12L, so try updating your phone?

**Comment by Giwayume** [comment]
That's not going to happen, Android gets much worse in the later versions. ROM is stock, does this app not support older versions of Android? Which app is it looking for as a file picker? You have an example app that works?

**Comment by arkon** [comment]
Whatever the built-in system document picker that Android normally ships with is.

It works fine in a stock Android 9 emulator, for what it's worth.

**Comment by Giwayume** [comment]
Ok, I disabled the out of the box files app because it was terrible, can't even access my NAS with it. It works with that one specifically. Honestly surprised none of these other apps handle the ACTION_OPEN_DOCUMENT_TREE intent.
