### ISSUE TITLE
Lost downloads

### ISSUE THREAD

**Issue by Yunaren** [tachiyomiorg/tachiyomi#10311]
### Steps to reproduce

I have updated my app then when I checked my downloads it was all gone not in my phone but in the app it self 

### Expected behavior

It should display all of my downloads

### Actual behavior

It didn't display my downloads even though I use the right folder where all of my downloads are located
Please fix this issue

![Screenshot_20240107_115459_My Files](https://github.com/tachiyomiorg/tachiyomi/assets/112523210/309ef160-279f-4e56-862d-08753127b271)
![Screenshot_20240107_115538_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/112523210/21349d80-765c-410f-b3a7-5ec014cbc2d4)
![Screenshot_20240107_115546_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/112523210/3d1d90b2-8020-4c34-95c2-a0b339a9e600)

### Tachiyomi version

0.15.0

### Android version

Android 14

### Device

Samsung A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Move all your blurred folders into "downloads".

https://tachiyomi.org/docs/faq/storage

**Comment by Yunaren** [comment]
> Move all your blurred folders into "downloads".
> 
> https://tachiyomi.org/docs/faq/storage

I'm but where? Again that's the same folder though

**Comment by Yunaren** [comment]
> > Move all your blurred folders into "downloads".
> > https://tachiyomi.org/docs/faq/storage
> 
> I'm but where? Again that's the same folder though

Sorry but I created a new folder and move it to a new downloads folder and it didn't read the downloads

**Comment by szyrei** [comment]
Has this been solved? I have the same problem.

**Comment by Yunaren** [comment]
> Has this been solved? I have the same problem. And the stories in my library can't be opened, it shows "couldn't find script in image data"

Yes I'm just dumb anyway to solve it just transfer the extension folders to the downloads folder just that and nothing else then use the main folder you'll see it injecting the downloads

**Comment by Yunaren** [comment]
> > > Move all your blurred folders into "downloads".
> > > https://tachiyomi.org/docs/faq/storage
> > 
> > 
> > I'm but where? Again that's the same folder though
> 
> Sorry but I created a new folder and move it to a new downloads folder and it didn't read the downloads

I just wanna say tysm for the help I'm just not understanding earlier thank you
