### ISSUE TITLE
turn off download alert

### ISSUE THREAD

**Issue by engineer011** [tachiyomiorg/tachiyomi#10315]
### Steps to reproduce

can you add a switch to adjust your download policy? Because of your download alert,I can't download any manga right now.

### Expected behavior

download 400 chapters and you will find the problem.

### Actual behavior

just say tachiyomi will be stopped.start again and you will find you can't download anything.

### Tachiyomi version

0.15.0

### Android version

harmony os 3

### Device

honor play 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
What download alert?

**Comment by arkon** [comment]
Actually I assume you mean the warning saying that downloading a ton of chapters is probably killing the sources and your battery life.

That doesn't prevent you from actually downloading the chapters.
