### ISSUE TITLE
No update notification when manually updating library category in v0.15.0

### ISSUE THREAD

**Issue by Aabhas-Sinha** [tachiyomiorg/tachiyomi#10313]
### Steps to reproduce

1. Navigate to library
2. Trigger manual update with gesture

### Expected behavior

It says updating category but the update notification showing per entry progress and the final update notification showing how many new chapters and chapters skipped, etc, are missing.

### Actual behavior

No notifications at all

### Tachiyomi version

0.15.0

### Android version

Android 13

### Device

OnePlus Nord CE 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's probably just too fast if there's nothing to try updating yet.

https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries

**Comment by Lordminnion1** [comment]
Only manual refresh works for me. When I just press update library nothing happens it goes way to fast to check for updates. but when I manual update the chapters it shows new chapters. I turned off battery saving for my phone, I've even made categories but that does nothing. I even had a manga with a new chapter that wasn't there yet in a new category with only a few others in it and only manually updating it worked.

**Comment by Abdallah-amara021** [comment]
I have fix it go to MORE then setting then library smart update make it unselected all thing and that's it
![Screenshot_20240108-153650_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/65ead412-6f38-40cb-ab77-a6b585c040ae)
![Screenshot_20240108-153655_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/2591a092-6b79-442e-a3fa-2b4b874183fd)
![Screenshot_20240108-153705_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/1d8dd1bb-35a7-4360-855c-a2652044388f)
![Screenshot_20240108-153708_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/0db8d820-4088-4be5-b092-041936e59674)

**Comment by arkon** [comment]
Duplicate of #10313

**Comment by Abdallah-amara021** [comment]
> Only manual refresh works for me. When I just press update library nothing happens it goes way to fast to check for updates. but when I manual update the chapters it shows new chapters. I turned off battery saving for my phone, I've even made categories but that does nothing. I even had a manga with a new chapter that wasn't there yet in a new category with only a few others in it and only manually updating it worked.

See my comment
