### ISSUE TITLE
allow the user to disable the auto-disabling of third party extensions. (whether from third party repos or apks)

### ISSUE THREAD

**Issue by samiscool51** [tachiyomiorg/tachiyomi#10326]
### Describe your suggested feature

just like the title says
considering that third party extension repo's have just been added, it defeats their purpose if the extensions can't be properly used as if they were official extensions.
while i understand a trust system is being worked on in issue #10290, the current measure of having them be disabled at boot up is annoying at best and downright malicious at worst.
it'd be better off adding a option for the user to disable this behavior with warnings saying that unless they're extension devs or know what they're doing, they shouldn't enable it.
sorry if i came off abrasive in this issue, i'm just very disappointed in how it's being handled.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No plan to make a kill switch for the warning. We are instead going to work on changing the system as you can see in #10290
