### ISSUE TITLE
I can't add download location for my dual tachiyomi app

### ISSUE THREAD

**Issue by Achuabdu** [tachiyomiorg/tachiyomi#10322]
### Steps to reproduce

1 I can't add for my dual app tachiyomi
2 it was fine before the update because tachiyomi itself would have taken the location

### Expected behavior

Before the new update tachiyomi dual app was picking it's on location in dual app interface now I can't add location after the update came

### Actual behavior

Now location can't be added

### Crash logs

App version: 0.15.0 (standard, a3ef360, 115, 2024-01-06T15:41Z)
Android version: 13 (SDK 33; build TKQ1.221013.002 test-keys)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sunstone (sunstone_in)
Device model: 22111317I
WebView: Android System WebView 120.0.6099.144

--------- beginning of main
01-07 12:32:03.323 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:03.378 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:03.435 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:04.443 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:05.273 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:05.340 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:19.254 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:24.161 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:27.627 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:32:31.606 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:10.812 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:14.710 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:16.223 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:39.969 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:44.372 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:33:52.339 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:34:06.843 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:34:08.225 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:34:15.322 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:34:25.982 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:36:42.036 28505 28505 E FileUtils: err write to mi_exception_log
01-07 12:42:39.905 27592 27592 E anade.tachiyomi: Not starting debugger since process cannot load the jdwp agent.
01-07 12:42:40.240 27592 27592 E FileUtils: err open mi_exception_log errno=2
01-07 12:42:40.240 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:42:40.289 27592  6395 E SQLiteLog: (283) recovered 5 frames from WAL file /data/user/999/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
01-07 12:42:40.336 27592  6406 E chromium: [0107/124240.333782:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
01-07 12:42:40.388 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:42:40.388 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.280 27592  7696 E SQLiteLog: (284) automatic index on C(manga_id)
01-07 12:43:12.280 27592  7696 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-07 12:43:12.701 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.843 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.843 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.854 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.859 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:12.873 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:13.988 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:14.012 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:14.130 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:27.321 27592  6398 E libEGL  : pre_cache appList: ,,
01-07 12:43:27.383 27592  6398 E LB      : fail to open node: No such file or directory
01-07 12:43:27.389 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:28.474 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:30.092 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:31.201 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:32.382 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:33.410 27592 27592 E BinderMonitor: err open binder_delay errno=2
01-07 12:43:33.410 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:36.203 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:36.940 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:42.187 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:43.510 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:44.346 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:45.035 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:50.841 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:43:56.457 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:03.102 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:04.871 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:05.745 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:07.270 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:09.987 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:11.084 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:44:16.198 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:45:16.252 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:46:41.493 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:48:36.602 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:48:36.719 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:48:38.053 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:48:38.874 27592 27592 E FileUtils: err write to mi_exception_log
01-07 12:48:43.657 27592 27592 E FileUtils: err write to mi_exception_log

### Tachiyomi version

0.15.0

### Android version

Android 13

### Device

Redmi note 12 5g

### Other details

![Screenshot_2024-01-07-12-44-12-486_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/145904014/c0b5490c-9cfa-43a4-8a83-dcf2830d48ad)

![Screenshot_2024-01-07-12-44-19-183_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/145904014/82f980c5-7601-46b2-b736-b4e0d0c2d026)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No plans to work around Xiaomi's broken Android functionality.
