### ISSUE TITLE
Error to refresh a manga

### ISSUE THREAD

**Issue by Samurai5966** [tachiyomiorg/tachiyomi#10328]
### Steps to reproduce

First I click in a random manga, then I try to refresh it but the error "ID1ID2:actual0x00001fef!=expected0x00001f8b" appears.

### Expected behavior

The manga should refresh normally.

### Actual behavior

The error prevents it to happen.

### Crash logs

ID1ID2:actual0x00001fef!=expected0x00001f8b

### Tachiyomi version

0.15.0

### Android version

Android 12.

### Device

Xiaomi Redmi 12C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Which source? Does it happen for manga not from that source?

**Comment by Samurai5966** [comment]
The source is Opex (One Piece Ex). It only happens with this source. More
specifically with One Piece from this source.

Em dom., 7 de jan. de 2024 09:32, AntsyLich ***@***.***>
escreveu:

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Samurai5966** [comment]
Ok, thanks for the update.

Em dom., 7 de jan. de 2024 10:50, Alessandro Jean ***@***.***>
escreveu:
