### ISSUE TITLE
Some Bugs I Encountered

### ISSUE THREAD

**Issue by SatoX69** [tachiyomiorg/tachiyomi#10320]
### Steps to reproduce

1. Open the application and navigate to the library.
2. Check the Total Chapter count for any source (book) in your library.
3. Observe if there's a "Missing 1 Chapter" message displayed.
4. Read a portion of a book, encounter a side story, and note changes in the "Missing Chapters" display after a library refresh.
5. Attempt to download chapters and monitor the library update prompts.

### Expected behavior

1. Upon opening sources, eliminate the persistent display of "Missing 1 Chapter" as seen in the recent update.
2. Rectify the missing chapters count, ensuring it doesn't include side stories with distinct chapter numbering (e.g., Chapter 120 after Side Story 3 after Chapter 119 should not result in a "Missing 117 Chapters" line).
3. In case of download interruptions or failures, prevent random library updates; updates should only occur when it is Prompted by the User or has the timed update option enabled in settings.
4. Enhance the accuracy of the Smart Timer functionality (low priority).

Here is some Proof:

![IMG_20240107_124815](https://github.com/tachiyomiorg/tachiyomi/assets/127420166/09483722-2301-4454-9494-843df672b926)

![IMG_20240107_125158](https://github.com/tachiyomiorg/tachiyomi/assets/127420166/4f327dfe-92e8-47c4-acad-263f74a94e32)

### Actual behavior

1. Total Chapter count displays a "Missing 1 Chapter" message across all sources.
2. "Missing Chapters" inaccurately indicates missing chapters, especially after encountering side stories.
3. Continuous prompts for "Updating Library" and "Downloader Finished" during chapter downloads.
4. The Smart Timer feature doesn't function as expected (not a critical issue).

### Tachiyomi version

0.15.0

### Android version

Android 12

### Device

Redmi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please create 1 issue per issue, and please check that you're not creating spam duplicates.

**Comment by SatoX69** [comment]
> Please create 1 issue per issue, and please check that you're not creating spam duplicates.

Okay, My bad
