### ISSUE TITLE
Manganelos cant loaded image

### ISSUE THREAD

**Issue by Ancienttwist** [tachiyomiorg/tachiyomi#10329]
### Steps to reproduce

*

### Expected behavior

*

### Actual behavior

Cant loaded image manganelos.com

### Crash logs
![Screenshot_2024-01-07-20-52-07-834_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/80474536/9d7b7115-7974-4880-af5a-1ee9c9464af2)

### Tachiyomi version

0.15.0

### Android version

Android 11

### Device

POCO X3 NFC

### Other details

*

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
