### ISSUE TITLE
Downloads not detected after updating the app

### ISSUE THREAD

**Issue by Maidenless0524** [tachiyomiorg/tachiyomi#10331]
### Steps to reproduce

Have downloaded chapters.
Update app to 0.15.0.
Downloaded chapters are not detected in the app. 

### Expected behavior

Downloaded chapters should be detected in the app.

### Actual behavior

Downloads can still be found in file manager but tachiyomi doesn't detect them. Tried moving the downloaded files to the new folder called downloads created by the app after I downloaded one chapter as a test, only the chapter was detected and when viewed in file manager the file name has (1) on it since it is a duplicate chapter.

For additional context, previous downloaded files were inside a folder named Tachiyomi, after the update the new files I downloaded were now inside Tachiyomi>downloads. And even after moving the old downloaded files to the downloads folder, Tachiyomi still doesn't detect them.

### Tachiyomi version

0.15.0

### Android version

13

### Device

Realme 8 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/docs/faq/storage

Do the "Invalidate downloads index" part too after having moved the files manually.
