### ISSUE TITLE
Download Ahead does not start downloading until reaching un-downloaded chapters

### ISSUE THREAD

**Issue by btmcsweeney** [tachiyomiorg/tachiyomi#10335]
### Steps to reproduce

1. Set "Auto download while reading" to any value other than Disabled (I am using 5, but have tested with other values)
2. Download 3 consecutive chapters of any series to test
3. Scroll through the first downloaded chapter into the second one
4. Exit out of the reader to see if the following chapters are downloading

### Expected behavior

The auto-download should trigger as soon as you start reading the second downloaded chapter, before you get to the ones that have not been downloaded. As explained on the settings page, "Only works if the current chapter + the next one are already downloaded".

### Actual behavior

The auto-download does not begin until you reach the chapters that have not been downloaded. e.g. if you have chapters 1-3 downloaded and set download ahead to 5, chapters 4-8 will only start downloading once you begin reading chapter 4.

### Tachiyomi version

0.15.1 (and 0.15.0)

### Android version

Android 11

### Device

Lenovo Legion Tab Y700

### Other details

I have tested this in both 0.15.0 and 0.15.1, with series from both the Mangadex and Mangabat extensions. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#10151
