### ISSUE TITLE
Creates a download folder inside tachiyomi folder instead of using the tachiyomi folder itself.

### ISSUE THREAD

**Issue by Casshernsins** [tachiyomiorg/tachiyomi#10332]
### Steps to reproduce

1. Download a chapter
2. Go to tachiyomi folder.
3. A "downloads" folder shows up
4. Delete the "downloads" folder then repeat from step 1.

### Expected behavior

Read from tachiyomi folder

### Actual behavior

Creates downloads folder within tachiyomi

### Tachiyomi version

0.15.0

### Android version

MIUI 14.0.5

### Device

Poco X3 NFC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is expected behavior. https://tachiyomi.org/docs/faq/storage

**Comment by Casshernsins** [comment]
> This is expected behavior. https://tachiyomi.org/docs/faq/storage

Thank you I was able to fix it but now it says, invalid location. It was working just fine but I had to restart my phone and now it says that.
