### ISSUE TITLE
Full storage even though everything was deleted

### ISSUE THREAD

**Issue by juyeomiii** [tachiyomiorg/tachiyomi#10334]
### Steps to reproduce

1 delete app content
2 storage should be cleared

### Expected behavior

When I updated tachiyomi and the obsolete sources got removed, the downloaded stories in those extensions should have been removed

### Actual behavior

The downloads were not deleted even though I cleared all cache and data. I tried deleting all of the stories so my library was empty and deleted the extensions yet it still took up a lot of storage.
![Screenshot_20240107_221833](https://github.com/tachiyomiorg/tachiyomi/assets/155893742/f7640cc8-6bee-44d1-a81d-ad5d1fd18c6d)

Then I deleted the app and then in my phone downloads and reinstalled it. Still, the storage was almost full even though there was not downloads in the app.
![Screenshot_20240107_221817](https://github.com/tachiyomiorg/tachiyomi/assets/155893742/079fb6d9-965f-46da-b843-c55773879cfb)

I'm new to tachiyomi so I searched for similar problems to mine but I couldn't find anything so I had to make an account and ask for help here

### Tachiyomi version

0.15.0

### Android version

9

### Device

Huawei 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Downloaded chapters are typically not stored within the app data, they're stored in whatever user-set location was specified. You'd need to go delete it using an external file manager.

**Comment by juyeomiii** [comment]
Whats an external file manager and where do I find it or download it

**Comment by AntsyLich** [comment]
he means something outside tachiyomi. the one that comes with your phone

**Comment by juyeomiii** [comment]
Deleted absolutely everything in my phone I could find thats related to tachiyomi. I found some chapters in the files manager but it wasnt all of it and wasnt enough. Deleted the app from downloads then reinstalled it, it reduced but not much
![Screenshot_20240107_230040](https://github.com/tachiyomiorg/tachiyomi/assets/155893742/f775c3fc-6a58-4408-ad6a-52c7afe2fc39)

Im about to throw this phone away, im laughing at myself rn. Welp my only hope now is resetting this phone but I have to backup every other file I have

**Comment by juyeomiii** [comment]
I rlly just wished those files were deleted when the extensions were removed
