### ISSUE TITLE
Chapters not being downloaded

### ISSUE THREAD

**Issue by Eny74929** [tachiyomiorg/tachiyomi#10341]
### Steps to reproduce

First I opened the manga I want to read later to download its chapters
Then the download started but when the chpater's downloading was completed i didn't find it in the downloaded section

### Expected behavior

The downloaded chapters should be visible when I opej the downloaded section

### Actual behavior

But instead I didn't find anything and it was empty 

### Tachiyomi version

0.15.1

### Android version

Huawei p40 lite 

### Device

Huawei p40 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Did you check in a file manager whether the downloaded chapters actually exist?

If it does, try invalidating the downloads index from the advanced settings.
