### ISSUE TITLE
MangaUpdates Score Renders Too Many Decimals

### ISSUE THREAD

**Issue by CalebMorris** [tachiyomiorg/tachiyomi#10343]
### Steps to reproduce

1. Connect to MangaUpdates tracker
2. Open a manga
3. Track manga by MU
4. Select a score
5. Observe render of selection 

### Expected behavior

Should show score at single decimal places. Ex: 9.8, 6.7

### Actual behavior

Shows 8+ decimals

### Tachiyomi version

* 0.15.0
* 0.15.1
* master (6510a9617a)

### Android version

Android 13

### Device

Nokia XR20

### Other details

Also confirmed in v0.15.1.

![Screenshot_20240107-013741](https://github.com/tachiyomiorg/tachiyomi/assets/347395/58937843-d33b-41a1-9313-fdd176dd993c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CalebMorris** [comment]
Confirmed present in `master` (6510a9617a)

**Comment by CalebMorris** [comment]
Correction: partially present in `master` (https://github.com/tachiyomiorg/tachiyomi/commit/6510a9617a2b5b5389cb5776a2fb91019206f6fc).
When viewing a score that was saved in a previous version, it shows the same rendering bug, but when saving a new score, it shows correct number of decimals.

It seems like this might be a persistence layer issue and it's fixed, but requires user input to correctly display

**Comment by CalebMorris** [comment]
Pretty sure it's the conversion here to DomainModel by way of `toDouble` here - https://github.com/tachiyomiorg/tachiyomi/blob/v0.15.1/app/src/main/java/eu/kanade/domain/track/model/Track.kt#L43

**Comment by arkon** [comment]
Yeah, that's probably it. Thanks for deep diving!
