### ISSUE TITLE
Extensions appear as obsolete, but work in browser 

### ISSUE THREAD

**Issue by ImperatrixDomina** [tachiyomiorg/tachiyomi#10344]
### Steps to reproduce

After the latest app update, extensions such as Mangadex and Batoto appear as obsolete. The new chapters appear to update, but when clicking to read,  an error message appears stating "couldn't find script image data". When viewing the Manga in webview, it works.

### Expected behavior

The newest chapters of Mangadex and Batoto appear in view. When clicking, they open to read. 

### Actual behavior

The new chapters appear in Mangadex and Batoto appear,  when clicking the error message "couldn't find script image data" appears. The chapters can be found in the webview though. Also, when navigating to the extensions, Mangadex and Batoto are flagged as obsolete and it's not possible to find a new version or update.

### Tachiyomi version

0.15.1

### Android version

Android 13

### Device

One Plus 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
obsolete means removed/unsupported

**Comment by ImperatrixDomina** [comment]
So, two major extensions such as Mangadex and Batoto  will not be supported anymore? No plans to fix this?

**Comment by laghelli** [comment]
This is happening to me too :/
