### ISSUE TITLE
Tachiyomi Issue 

### ISSUE THREAD

**Issue by 230303u** [tachiyomiorg/tachiyomi#10350]
### Steps to reproduce

1. I'm installing the new version of tachiyomi
2. When I'm done installing it, it ask me to choose file for backups and restore, so I choose my files.
3. But then, when I want to start reading, my manhwa/manga can't loading the pages. It says that couldn't find script with image data. 

### Expected behavior

I'm expected the new version is better than the old version 

### Actual behavior

1. I'm installing the new version of tachiyomi
2. When I'm done installing it, it ask me to choose file for backups and restore, so I choose my files.
3. But then, when I want to start reading, my manhwa/manga can't loading the pages. It says that couldn't find script with image data. 

### Tachiyomi version

0.15.1

### Android version

Android 13

### Device

Vivo 23e 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Bato.to has been removed and isn't supported anymore

**Comment by IZATENKA** [comment]
is there any reason why bato and mangadex are now obsolete?
