### ISSUE TITLE
optionally trust non-official source

### ISSUE THREAD

**Issue by laplace618** [tachiyomiorg/tachiyomi#10359]
### Describe your suggested feature

each time we open tachiyomi, we need to re-trust the unofficial source. which is unnecessary.
I wish we are able to manually choose to trust an unofficial source permanently or at least over a period of time.
:)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ZerOri** [comment]
same issue.

**Comment by CnTripto** [comment]
This is a new feature for v0.15.1 apparently, such text contained in the release note.

<br \>

### Browse
- "In Library" badge text replaced with icon
- Don't do extra calls to initialize missing details from BrowseSource or Search screens
- Open result directly when opening links if possible (@ivaniskandar)
- <font style="color: firebrick; font-weight: bold">Unofficial extensions must be retrusted on every cold start</font>

It may be used to protect against some insecure unofficial extension，a nice idea but a nightmare for users sxperience.

**Comment by AntsyLich** [comment]
Duplicate of #10290 too
