### ISSUE TITLE
Couldn't find script with image data ? 

### ISSUE THREAD

**Issue by Ardo25** [tachiyomiorg/tachiyomi#10361]
### Steps to reproduce

1. Pergi ke **jelajahi**
2. Cari bato.to versi Indonesia
3. Pilih komik 
4. Klik lalu pilih chapter 

### Expected behavior

Ini seharusnya bisa dibuka atau dibaca 

### Actual behavior

Saya rasa dari tachiyomi nya
![Screenshot_20240108_134359](https://github.com/tachiyomiorg/tachiyomi/assets/125936428/4d06cdbd-a477-4b9a-9371-b95e58552bde)

### Crash logs

App version: 0.15.1 (standard, 8a83622, 116, 2024-01-07T14:53Z)
Android version: 11 (SDK 30; build RP1A.200720.012 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 1951 (1951)
Device model: vivo 1918
WebView: Android System WebView 120.0.6099.145

Problematic extensions:
- Bato.to
  Installed: 1.4.32 / Available: ?
  Obsolete: true / Unofficial: false
- MangaDex
  Installed: 1.4.192 / Available: ?
  Obsolete: true / Unofficial: false

--------- beginning of system
01-08 11:58:38.866  8466  8466 E ActivityThread: Failed to find provider info for eu.kanade.tachiyomi.DropDataProvider
--------- beginning of main
01-08 12:59:24.414  8466  8922 E chromium: [ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -202

### Tachiyomi version

0.15.1

### Android version

Funtouch OS ; PD1911F_EX_A_7.5.6

### Device

Vivo Z1 pro

### Other details

Saya tidak tau kenapa kok bisa 
couldn't find script with image data
Padahal bato to nya bisa di buka karena saya memakai VPN di webview pun bisa tapi entah kenapa ketika di aplikasi tachiyominya tidak bisa dibuka, semua komik begitu padahal sebelum update versi bisa bisa saja

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Ardo25** [comment]
Maksud dari tidak bisa dibuka nya itu chapternya

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also, Batoto has been removed and we do not provide support for it.
