### ISSUE TITLE
Allow a differing backup path

### ISSUE THREAD

**Issue by mpldr** [tachiyomiorg/tachiyomi#10376]
### Describe your suggested feature

Please bring back the option to have the backup location be different. I am using syncthing to sync a directory containing all automatic app backups to somewhere in case my phone dies without prior announcement. For obvious reasons, setting the library directory inside that synchronized directory would be less than ideal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by shmightworks** [comment]
TBH, they shouldn't have messed with this setting.  Or at least the update should have detected the old path and reuse it.
Luckily I found this out this change, so I was able to moved all my downloaded manga to the right spot.
Was freaked out when I saw all my downloaded chapters were gone.

**Comment by BrutuZ** [comment]
Just point you syncing application to the `autobackup` subfolder instead of its parent.

Reusing the old path wouldn't have worked because there were two user-defined paths (backups and downloads) that could potentially be on different storages, so the user has to decide where the "One Folder to Rule Them All" should be. As for why it happened, blame Google for changing Android requirements

**Comment by mpldr** [comment]
> Just point you syncing application to the autobackup subfolder instead of its parent.

It feels a bit weird to have my signal, calendar, and contact backups in the tachiyomi directory.

**Comment by BrutuZ** [comment]
So your syncing application can only access one folder?

**Comment by CrepeTF** [comment]
But syncthing should be able to sync multiple folders?

**Comment by mpldr** [comment]
Of course, but having *one* backup directory with one subdirectory per backed up application is significantly less work than one per application.

**Comment by CrepeTF** [comment]
You should still be able to do what you did before, but have a separate sync for tachiyomi only.

So you'd have 2.

**Comment by mpldr** [comment]
I'm afraid you're missing the point. I would prefer the app to not lose a useful feature even if it would be trivial to circumvent. I could also set up a cronjob, use some automation app, send it to myself via email. But that's significantly more work than just re-adding the feature.

**Comment by BrutuZ** [comment]
We all would, but alas Google disagrees and changed the Android requirements regardless of our preferences.

**Comment by arkon** [comment]
Scoped storage is meant so that users of app can isolate files in such a way that other apps can not easily gain unauthorized access to arbitrary content, which is why Tachiyomi has a single folder it has access to that the user grants access to.

You could potentially finagle your folders such that your other apps' backups end up within the same place, but I'm afraid it wouldn't make sense to reopen Tachiyomi to arbitrary file access again.

**Comment by mpldr** [comment]
Thanks for your reply @arkon,
I am not very deep inside the android development world, but can't apps have multiple scopes? I think I remember some apps having these options. So having the scopes
- /storage/emulated/0/Tachiyomi
- /storage/emulated/0/Backups/Tachiyomi
should work while preserving the isolation features, right?

**Comment by mpldr** [comment]
![Screenshot_20240108-201955](https://github.com/tachiyomiorg/tachiyomi/assets/33086936/dbb7d9f0-5841-404a-9bdb-0dda45590173)
At least this app has access to three directories.

**Comment by arkon** [comment]
Flud only prompts for 1 directory as far as I'm aware. That number is the number of items that the app has directly managed (you should eventually see the number for Tachiyomi increase too).

**Comment by mpldr** [comment]
![Screenshot_20240108-225723](https://github.com/tachiyomiorg/tachiyomi/assets/33086936/d6982de4-caca-4a67-9daa-3308ae47c8f8)
They are: incoming, in process, and completed. At least to me this seems to indicate multiple scopes.
