### ISSUE TITLE
failed to fetch available extensions

### ISSUE THREAD

**Issue by rubicon31** [tachiyomiorg/tachiyomi#10383]
### Steps to reproduce

1.Update to latest version
2.go under extension

### Expected behavior

extension list should be available

### Actual behavior

message pops up:"failed to fetch available extensions", additionally all installed extensions show as untrusted

### Tachiyomi version

0.15.2

### Android version

android 12

### Device

realme gt 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/news/2024-01-09-extensions-removal
