### ISSUE TITLE
Can't download new extension 

### ISSUE THREAD

**Issue by timeskipp** [tachiyomiorg/tachiyomi#10392]
### Steps to reproduce

Entered the extension download tab but can't access it

### Expected behavior

I can download or update new version of extension 

### Actual behavior

I can't view list of extension 

### Tachiyomi version

0.15.2

### Android version

8

### Device

Oppo a3s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
https://tachiyomi.org/news/2024-01-09-extensions-removal
