### ISSUE TITLE
Weird bug which completely corrupted the app data.

### ISSUE THREAD

**Issue by tippl** [tachiyomiorg/tachiyomi#1060]
So, this bug report will probably not be useful, but i thought i should report it anyways.
App version: 0.6.3
Phone: Pixel 2
Android: 8.0.0 Build: OPD1.170816.025

---

I was in the library, and decided to download next 10 chapters of a manga. While it was downloading i removed the app from recents. The download stopped and i was able to swipe away the notification.
But when i attempted to reopen the app, it instantly crashed. Only thing that helped was clearing the app data and restoring from backup.

Attempted to reproduce the bug, successfully so i tried it on other devices.

My old phone and android emulator did not have this bug on the same app version.
Phone2: Nexus 5X on the 8.1 public beta
AVD on 8.0 image

So i got the source and compiled the app at current HEAD and did not reproduce on my phone, but when i recompiled at v0.6.3 tag i did not reproduce it either.

As the compiled app installed along the already installed app i tried the installed app again and it corrupted again.

Today, i tried to reproduce again, but i can't.

I have the send crash report button enabled, so i hope it sent some logs as i don't have any to post.
Good luck on the road of searching for unreproduceable bugs.

**Comment by libjared** [comment]
I got bit by this. I was downloading a rather large amount of chapters, and when I woke up the next day, the notification was still there, saying it was downloading. Now the app crashes on startup. I don't have a recent settings backup so I'm willing to try and unfuck it manually. I'm using a Pixel 1 on Android 8.0.0.

**Comment by arkon** [comment]
Closing due to age.
