### ISSUE TITLE
Access migrating manga in source migration

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#1256]
The manga view can be accessed by long pressing the manga in the list of categories, however the manga being migrated cannot be accessed. This would help migrating to up-to-date sources (or ones that didn't die when their Batoto importer broke :smirk:)

<details><summary>Original Issue</summary>

~~This is currently blocking me from migrating from Batoto, as to avoid migrating to a source that has no/some chapters I'd have to exit the source migration, search for the manga in library, then do a catalogue search.~~

~~Which at that point is much slower than manually migrating from a source by making a note of them all and doing catalogue searches for several hours 😅~~

- ~~Display details of the manga being migrated~~
	- ~~Total chapters, latest chapter released~~
- ~~Tracking services connected~~
	- ~~Find last read chapter if above is unreliable (backups?)~~
- ~~Chapter counts/total of source migrating to~~
	- ~~Currently, clicking on the search result in the list of sources opens the migration modal~~
	- ℹ️ Long-press manga poster to open details/chapter list/trackers view
</details>

**Comment by LinkCable** [comment]
You can long press on the manga in migration and it will open the detailed view for you to see the chapter list.

**Comment by LinkCable** [comment]
(But yes this could be done better)

**Comment by CarlosEsco** [comment]
I did not know you could do that

**Comment by wopian** [comment]
@LinkCable damn didn't know that was a thing. Probably cause there's no feedback when long-tapping on the posters 😅

**Comment by Bm12347** [comment]
I think this should be closed as you can access the migrated manga by long pressing and compare
