### ISSUE TITLE
Volume/chapter subfolders

### ISSUE THREAD

**Issue by shogunreaper** [tachiyomiorg/tachiyomi#1321]
When opening zip files tachiyomi is also able to read all the subfolders inside of the zip

but if you just have a regular folder such as "Volume 1" with chapter folders inside it gives a "Page list empty" error.

so can the functionality to read the files inside subfolders be added outside of zips?

**Comment by arkon** [comment]
AFAIK, the folder structure is actually just ignored completely for ZIP files.

The file structure is actually important for the app to handle downloads the way that it does.
