### ISSUE TITLE
Tachiyomi doesn't open pages of the currently-downloading chapter

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#1332]
**App version:** 0.7.0

**Issue/Request:** When I start to read a chapter that's currently being downloaded, Tachiyomi doesn't open the downloaded pages but starts downloading them to cache. That means I have to wait for the chapter download to finish to start reading.

Another thing: If I finished reading a chapter without downloading, then I download it, why does the app start downloading it from the start instead of coping it from cache?

**Comment by asdkant** [comment]
This is especially problematic for people with slow and/or flaky connections

**Comment by arkon** [comment]
Doesn't seem to be the case anymore.
