### ISSUE TITLE
[Feature Request] Split dual page Manga into two single pages

### ISSUE THREAD

**Issue by ForkOnTheLeft** [tachiyomiorg/tachiyomi#1384]
Currently reading Vento aureo and the source from Mangadex has dual-pages, meaning that it is very hard to read smaller text and details without zooming in manually every time. It would be great if there was a "single-layer" mode like in Perfect Viewer to automatically split these dual paged Mangas in half.

**Comment by jogerj** [comment]
Issues with this suggestion:
1. Works best only with right to left reading direction (for two-page panels) 
2. May cause uneven crops. 
3. Not possible to differentiate between two-page and single-page panels.

**Comment by edward-shen** [comment]
Regarding point 3, you could just check for aspect ratio. Most manga are designed for book use, so 90% of the time it's easy to determine when it's suppose to be a two-page panel.

On the other hand, there are some translation groups that use a square or wide picture as their recruitment/notes/etc page, so the issue still exists.

**Comment by jonathanv81** [comment]
I'm currently using "Adapt to height" so the double pages appear the same scale as others but then I have to realize it's a double page and drag to see the other half of the page, because if I just tap as I usually do, it will go to the next page without showing the other half of the double page. For me it would be better if the tap would advance (or go back) to the other "half" of the page instead of skipping straight to the next page like for normal pages. Or it could be nice to have some indication (an arrow or something) that it's a double page and you have to drag it to see the rest.
Another possibility for me would be to have an option to show double pages in landscape, that's what is done by kmanga.net to read mangas on Kindle (because I have an e-ink reader without a gyroscope hence zooming, dragging and rotating is a pain).

**Comment by 7sevenseven** [comment]
If every page needs to be enlarged, it is really troublesome.

**Comment by Boiethios** [comment]
> 
> 
> Issues with this suggestion:
> 
>     1. Works best only with right to left reading direction (for two-page panels)
> 
>     2. May cause uneven crops.
> 
>     3. Not possible to differentiate between two-page and single-page panels.

Hi, I'd like to see this feature as well! The lack of this option makes some mangas hard to read (I switch to another reader in this case).

I'd like to answer to your issues: in my opinion, this option shouldn't be automatic, but should be activated by hand by the user, with a way to easily go back to the classical view when needed (for example with a pinch, or a tickbox, etc.).

There should also be an option to specify if the manga is read from right-to-left or left-to-right. For example, the Western translations of Berserk are read from left-to-right.

**Comment by 7sevenseven** [comment]
So can this practical function be done? Please

**Comment by hXtreme** [comment]
@7sevenseven highly unlikely. Any such implementation would have to decide if a particular page needs to be split or not as well as where to split it. Any robust solution I could think of requires a reasonable computational power.

Furthermore, there could always be false positives and true negatives that could make the entire experience of reading worse.

So my guess is that this feature won't be implemented at least for quite some time. You can always prove me wrong, hint hint nudge nudge ; )

**Comment by 7sevenseven** [comment]
> @7sevenseven highly unlikely. Any such implementation would have to decide if a particular page needs to be split or not as well as where to split it. Any robust solution I could think of requires a reasonable computational power.
> 
> Furthermore, there could always be false positives and true negatives that could make the entire experience of reading worse.
> 
> So my guess is that this feature won't be implemented at least for quite some time. You can always prove me wrong, hint hint nudge nudge ; )

Just split the position in the middle and not think if it is right, a lot of comic APP do this. Split the position in the middle usually doesn't go wrong.Now most comics are single-page, but the sweepers sweep two pages together. It's painful to look at, and It's a hassle to zoom in every time you turn a page. As for the "Furthermore, There could always be false positives and true negatives that could make the worse - the experience of reading ", anyway, this scheme is better than the existing schemes, The plan now to read double page is to enlarge The page or use The scale type that can only display a page of 3/5. Slicing two pages into one doesn't make it any worse. People who like this feature Can Turn it on, and people who don't like it can Turn it off, but tachiyomi is not perfect without this feature.

**Comment by Dangelman** [comment]
I agree with 7sevenseven, even just splitting in the middle when _width>height_ would be a betterment.
Just add an option **_"Split page (BETA)"_**

**Comment by hosinjung** [comment]
Any updates for this feature?

**Comment by psychowood** [comment]
I'm not sure about viewing it as a page split: imho it should just scroll left (or right) moving to the next part of a page intercepting the next/previous page function based on the position of the image on the screen. 

Obviously this would work mostly (only?) if used with fit-height mode:

- Normal page (page that fits): nothing special here, on load it fits
- Horizontal larger page: page will load as usual, focused on the left margin
- Go to next page action: if the right border of the image is not presented on screen, scroll right by a page width or to the left border (whatever is the smaller one)

Swap left<->right depending on the reading direction :)

**Comment by rawfh** [comment]
My idea is spliting the original image into left and right and merging them into a new image. Here is a possible solution: 
```kotlin
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Rect

fun splitAndMerge(toTransform: Bitmap): Bitmap {
    val height = toTransform.height
    val width = toTransform.width
    if (width <= height) {
        return toTransform
    }
    val result = Bitmap.createBitmap(width / 2, height * 2, Bitmap.Config.ARGB_8888)
    val canvas = Canvas(result)
    // right -> upper
    val rightPart = Rect(width - width / 2, 0, width, height)
    val upperPart = Rect(0, 0, width / 2, height)
    canvas.drawBitmap(toTransform, rightPart, upperPart, null)
    // left -> bottom
    val leftPart = Rect(0, 0, width / 2, height)
    val bottomPart = Rect(0, height, width / 2, height * 2)
    canvas.drawBitmap(toTransform, leftPart, bottomPart, null)
    return result
}
```
But I don't know where to put the code. Can anyone give some advice?
