### ISSUE TITLE
[Feature Request] Stats box in "My Library" in the 3 bar menu under "Display" section

### ISSUE THREAD

**Issue by EtorixGaming** [tachiyomiorg/tachiyomi#1392]
I was thinking a stats feature would be nice. It would display the number of Completed, Ongoing, and Total manga per Category and per Source. My example below would be a possible way to do it.
```
Stats
    Categories
     - ExampleCategory1
        ~ Completed: 10
        ~ Ongoing: 10
        ~ Total: 20
     - ExampleCategory2
        ~ Completed: 10
        ~ Ongoing: 10
        ~ Total: 20
     - All
        ~ Completed: 20
        ~ Ongoing: 20
        ~ Total: 40
    Sources
     - ExampleSource1
        ~ Completed: 10
        ~ Ongoing: 10
        ~ Total: 20
     - ExampleSource2
        ~ Completed: 10
        ~ Ongoing: 10
        ~ Total: 20
     - All
        ~ Completed: 20
        ~ Ongoing: 20
        ~ Total: 40
```

**Comment by LakotaGray** [comment]
If it was per category I think the drop down menu would be a good place for it. If it was per source, maybe have it in another section, like settings, or extensions somewhere. But I do like the concept of a way to see quantity of manga in library

**Comment by arkon** [comment]
Duplicate of #115
