### ISSUE TITLE
[Feature Request] Export a list containing Manga Title, Author/Artist, Source, etc from settings

### ISSUE THREAD

**Issue by EtorixGaming** [tachiyomiorg/tachiyomi#1393]
**App version:**
0.7.3

**Issue/Request:**
An option in the settings to export a file containing every manga I have, including the Title, Author/Artist, Source, and anything else applicable. Preferably each on its own line.

**Example.txt:**
One Piece, Eiichiro Oda, Kissmanga, Latest Read Chapter: 803
Boku no Hero Academia, Kohei Horikoshi, Mangago, Latest Read Chapter: 92
Bleach, Tite Kubo, Mangarock, Latest Read Chapter: 234

Something such as this.

**Comment by LogicInABox** [comment]
~~Score~~ Source

**Comment by LakotaGray** [comment]
Or perhaps a feature that would be able to convert the json back up file into a clearer list of title-author/artist-source?

**Comment by explosivedeer** [comment]
This would be fantastic!
Perhaps it could also print the titles separated by the Categories you've assigned them in the application, and print the source its coming from (i.e Kissmanga, Mangareader, etc...)

**Comment by arkon** [comment]
Probably not happening, but someone could something to convert the backup files to other formats.
