### ISSUE TITLE
[Feature Request] Option to change Play-Button Functionality to last read

### ISSUE THREAD

**Issue by iuw22** [tachiyomiorg/tachiyomi#1399]
Hi,

The play button currently does lead to the last unread chapter.
I see that most people seem to like this, but I'd like to to have the option that the button leads to the last page I've left reading:
For Example if I've read Chapter 5 but not 1,
because I know it already from elsewhere for example another source,
it sends me to chapter 1, unless I mark all chapters as read.

Thanks.

**Comment by CarlosEsco** [comment]
Why not just mark the chapters read?

**Comment by iuw22** [comment]
It'd be just convenient to have the option to not have to.

**Comment by jogerj** [comment]
Who the hell reads a manga mid way?

**Comment by Chibicon** [comment]
@jogerj I read a few chapters during my breaks at work and when my alarm goes off to go back inside I turn my tablet off and resume it during the next break or the next day etc.

**Comment by pervertkirito** [comment]
as for myself, I usually find new manga to read by select random manga on recent releases and peek at random chapter.
If this feature implanted, hope got option to disable it.

**Comment by zunjae** [comment]
Indeed, if this gets released make sure it's disabled by default. It'll ruin the flow for current Tachiyomi users

**Comment by joaoandre120** [comment]
Hi, I know its an old issue, but I've read a manga from first cap to last, but in middle, it started to not resume correctly, on going to cap 55. 
Manga: The Beginning after the end.
Source: Leitor.net (PT-BR)
(It was the first I've read on the app).
After I've tried others, and some time it even gives error (No pages found) instead of opening the cap.
Manga: Versatile Mage
Source: ReadM (EN)

App Version: 0.10.5
Android Version: 8.0.0
Since I don't know if it's a device-dependent issue: Galaxy J5 Prime

**Comment by Pierre-Monier** [comment]
Is this still a desired feature ? I can work on that if it's the case. I think it can be a great option

**Comment by arkon** [comment]
I'm not sure if this is really desirable. Is there a common valid use case where you'd want to read a newer chapter that isn't the next unread one that _isn't_ just a symptom of being too lazy to properly mark older chapters as read?

**Comment by Pierre-Monier** [comment]
It's always a symptom of being too lazy to properly mark older chapters as read. I just discovered the mark all chapter after this one as read feature, so yes it might be useless, and you already have this behavior in the history panel so closing this might be a good idea
