### ISSUE TITLE
[Bug] long series name gets ellipsis when searching on MAL

### ISSUE THREAD

**Issue by SynderBlack** [tachiyomiorg/tachiyomi#1409]
Title.
(dev 1411)

When searching to add tracking for a series, if the name is too long it'll add ellipsis (...) and break it at a certain point, which causes the search to fail.
This isn't a huge problem but more often than not, you'd rather it found the series right off the bat instead of having to manually remove the ellipsis or even complete the rest of the title.

EDIT: This may also be the cause for a 400 when trying to actually *add* a series which has had it's name cut.

**Comment by arkon** [comment]
Closing as this is pretty old and the MAL tracker was rewritten.
