### ISSUE TITLE
[Feature Request] Exclude specific user categories from source migration

### ISSUE THREAD

**Issue by RobotoDroid** [tachiyomiorg/tachiyomi#1486]
App version: v0.7.4

When using the source migration feature to migrate series to other sources, I have a lot of "completed" series showing up in the lists.

When I have finished a manga series I move it to a completed or archived category, source information for these are no longer important, so I don't need to migrate them. Allowing the user to exclude certain categories from appearing in source migration will make it much easier to manage sources. This feature could be linked to "sources to include in global update" string to make it easier to implement through UI.

**Comment by arkon** [comment]
Sort of workaround: you can migrate directly from the library entries nowadays.

Not going to implement this since it seems a bit niche.
