### ISSUE TITLE
Cache 'tracking' 

### ISSUE THREAD

**Issue by Deterio** [tachiyomiorg/tachiyomi#1497]
This is a feature request. When you don't have internet, but you still want to track manga, would it be possible to cache requests to the tracking sites and submit these requests when you get your internet connection back, something like Simple Last.fm Scrobbler.

**Comment by KrisKamweru** [comment]
+1

**Comment by bbtora** [comment]
+1

**Comment by Hakim567** [comment]
+1? idk how github works.
