### ISSUE TITLE
18:9 and 19:9 phones zoomed in too close in landscape mode (feature request?)

### ISSUE THREAD

**Issue by willham1** [tachiyomiorg/tachiyomi#1498]
This isn't necessarily a bug and more of a feature request. With ultrawide phones (18:9/19:9) becoming the norm the app still defaults to fit to width when in landscape mode and as a result, we only see about 1/3 of the page height. It's annoying when there's a tall vertical scene and you'd have to scroll down and back up to follow the reading flow. The image also because unpleasant as a result of the loss in pixel density.

I'd love for there to be an option to have 60% or even 80% zoom instead of the default 100%. That way I can see more of the page when in landscape mode.

**Comment by MariuszBielecki288728** [comment]
I would really love to see it implemented!

**Comment by arkon** [comment]
#3863
