### ISSUE TITLE
Remove .tmp folder after download is cancelled/failed

### ISSUE THREAD

**Issue by einstein95** [tachiyomiorg/tachiyomi#1501]
**App version:**
0.7.4

**Issue/Request:**
Remove .tmp folder left over from a cancelled download

**Other details:**
After the downloads are cleared, a .tmp folder is left over. This also counts towards the download count icon on the manga listing (if enabled).

**Comment by wopian** [comment]
Somewhat a duplicate of #1193

**Comment by arkon** [comment]
Closing in favour of #7492
