### ISSUE TITLE
REQUEST: Ability to hide certain manga from My Library

### ISSUE THREAD

**Issue by alebustelo** [tachiyomiorg/tachiyomi#1508]
**App version:**
0.7.4
**Issue/Request:**
The ability to hide certain manga from My Library, especially local manga. An easy button that will hide/show manga tagged or selected as "hidden". Removing and re-adding manga from My Library can be cumbersome if there is a lot of manga that needs to be hidden, so a feature to quickly hide a bunch of manga at once and then painlessly bring it back later would be useful.

**Comment by Deterio** [comment]
+1

**Comment by WindowsXp16** [comment]
My workaround was to put manga in a category with the name of this category being a space. Hides the category unless you click on it.

**Comment by MercerBoi** [comment]
I was thinking of something like this...

The hidden category would simply not be there at all under normal circumstances. When you're at your last category, sliding the screen away from that (like attempting to go the next, non-existent category) will reveal a prompt to enter a passcode/fingerprint and that's going to give access to the hidden category. This category will again be locked if you spend time away from it for... let's say 10 seconds (should be configurable).

You could also have multiple hidden categories which would be unlockable by the process I described above. Just a thought.

**Comment by arkon** [comment]
Whoops, I forgot that there was even an open issue for this.

This was rejected on Discord at some point. This feature belongs more in one of the hentai-focused forks than the main app.
