### ISSUE TITLE
Multiple sources extensions: list the sources in the extension's page

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#1562]
I think this should be in this repo as it's an app behavior.

My request is for the extensions with multiple sources to list all the offered sources _before and after_ installing in each extension's page (see below). Currently these pages are available to installed extensions only but having them for the non-installed extensions too would allow us to know which sources they offer.

![screenshot_20180804-025508 2](https://user-images.githubusercontent.com/17810950/43671061-cf14189e-9793-11e8-9f5c-cbdc8e35a0a1.png)

**Comment by arkon** [comment]
Not relevant nowadays since multi-source extensions were split.
