### ISSUE TITLE
Zoom Start Position always center (gif files)

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi#1643]
**App version:**
0.7.4 1438
**Issue/Request:**
Whenever I try to zoom from a corner, the page starts zooming in from the center. Even though I have the settings to be automatic. I don't if it's just me or not.
Edit: Looks like it only happens with GIF files (?)

**Comment by inorichi** [comment]
GIFs ignore the scale type and zoom preferences, but manual zoom (pinch) works fine. I don't think they will be supported because the view used for GIFs is the built-in ImageView from Android and we don't have much control over it.

Crop borders is also ignored too.
