### ISSUE TITLE
Make the default reader work when swiping at sharper angles.

### ISSUE THREAD

**Issue by tippl** [tachiyomiorg/tachiyomi#1662]
**App version:** 0.8.0

**Issue/Request:**
When trying to switch a page, or scroll on a zoomed page in default reader, swiping at sharper angle has a bit weird behavior in the default reader. Swiping more up/down than left/right doesn't switch pages and is weird when zoomed in. Comparably in the Webtoon reader, swiping more left/right than up/down is of no issue and it still scrolls correctly.

Since my explanation probably doesn't make much sense, i have recorded a video [here](https://streamable.com/9zi7h).

It seems to be trying to scroll "up" so it disables left/right movement, even when there is no "up". Not sure how well this can be fixed, since it probably is default behavior of the layout elements used.

**Steps to reproduce (if applicable)**

 1. Open a manga with default reader set
 2. Try to switch page, but swipe at around 45° angle
 3. The page will not switch, or in case of zoomed picture will stop scrolling until you lift your finger.

**Comment by arkon** [comment]
No plans to address this since it's basically just the standard ViewPager behaviour.
