### ISSUE TITLE
Cant change cover when cover does not exist

### ISSUE THREAD

**Issue by thu2468** [tachiyomiorg/tachiyomi#1663]
So i cant change a cover in a library when the cover does exist. 
For example the manga inside of mangazuki some dont have cover because the wevsite does not have one but chapter loads fine. Here the error that show up when trying to change cover.
![screenshot_20181015-023425_tachiyomi](https://user-images.githubusercontent.com/1341488/46933649-ebe63c00-d022-11e8-85f9-878f21868636.jpg)

**Comment by AmineI** [comment]
Can confirm this issue happening on the latest dev version. Easy to repro ; as JapScan french source has no manga covers, trying this on any manga from JapScan triggers the error

**Comment by CarlosEsco** [comment]
@inorichi  
code for this is line 508 in ReaderPresenter
`                    val thumbUrl = manga.thumbnail_url ?: throw Exception("Image url not found")
`

suprisingly just not throwing the exception and setting it as something like the manga url doesnt work

**Comment by ChrisJAllan** [comment]
PR with the second option.

**Comment by FourTOne5** [comment]
Custom created a new extension where manga has no cover url provided.
Was able successfully set one from reader and from manga info
