### ISSUE TITLE
Can not zoom out when using 'smart fit'

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#1668]
**App version:** 0.8.0

I can't zoom out when the scale type is set to 'smart fit'. Only zooming in is possible.

**Comment by coltaku** [comment]
I would love for this to be possible as well. It's really annoying because I'm constantly switching between 'smart fit' and 'fit height'. It's actually a pretty for me in 'fit height' mode so I usually just end up switching back and forth on occasion.

**Comment by arkon** [comment]
Seems like #4566 addresses the same issue.
