### ISSUE TITLE
[Feature] Auto-email/send backups to user-defined services

### ISSUE THREAD

**Issue by ZaneHannanAU** [tachiyomiorg/tachiyomi#1685]
Essentially an option to automatically email or otherwise save the files to some external network; such as ftp, sftp or so on.

sftp would require ssh/sshfs use (and likely require choice of wifi to use); email would create _some_ issues but would be more-or-less automated; and as email access keys are easier to set up also probably be better.

Currently just saving the files to a place --- at least, without an external automation system --- is near pointless I think. Sorry for being quite vague though...

Regardless, thank you for your constant work.

**Comment by metroid112** [comment]
Since we're here, automatically sending the backup to Google Drive would be something I'd love to be able to do.

**Comment by arkon** [comment]
+1, I currently have uploads to Google Drive automated via Tasker but it'd be nice to have it built in.

**Comment by Flat** [comment]
There are plenty of apps to upload/sync files to the cloud or ssh connections. Implementing this would require either further large dependencies or writing our own clients which seems out of scope imo.

**Comment by frymezim** [comment]
I've lost my phone due to water damaged. I have backups on my phone but there's no way I could get them. This is a must have feature.

**Comment by CarlosEsco** [comment]
Can use something like in the mean time.

https://play.google.com/store/apps/details?id=com.ttxapps.drivesync&hl=en_US&gl=US

**Comment by arkon** [comment]
Merging with #912
