### ISSUE TITLE
 Cannot search more for small length manga titles in Anilist tracking

### ISSUE THREAD

**Issue by dhanjit** [tachiyomiorg/tachiyomi#1727]
**App version:** 8.0

**Issue/Request** Cannot search more for small length manga titles in Anilist tracking

**Steps to reproduce (if applicable)** 

 1. Search for "Kuro" in Anilist tracking tab.
 2. Expecting https://anilist.co/manga/85277/Kuro-/
 3. But the search result doesn't list it because more results are required.

**Other details:** Maybe support for filtering by author? Or force track by URL or id? I am in support of the latter as it would probably be taken as a workaround any time search doesn't work for whatever reason.

**Comment by dhanjit** [comment]
They seem to have infinite scroll https://anilist.co/search/manga?sort=SEARCH_MATCH&search=kuro

I would hazard a guess that such isn't possible/needlessly complex to implement on the app?

Also as a workaround
> Or force track by URL or id?

**Comment by CarlosEsco** [comment]
They have a paging in their API. Just currently the setup for tachi it would require a lot of work to rewrite. We upped it to Max for first page which I think is like 40. But again it's still dumb that exact name search the result doesn't show in 1st 40 results

**Comment by dhanjit** [comment]
Queried around in anilist forums for this. They said they are going to revisit the search function in some time so that it doesn't suck.

**Comment by arkon** [comment]
This particular example is fine now. If it's still an issue, open another issue and we could consider a workaround similar to MAL to search by ID.
