### ISSUE TITLE
Changing WiFi endpoints mid-download breaks downloading

### ISSUE THREAD

**Issue by chrisbrown** [tachiyomiorg/tachiyomi#1757]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:*0.8.0*

**Issue/Request:*WiFi downloading breaks seemingly permanently if you change wifi connections while downloading*

**Steps to reproduce (if applicable)**

 1. Connect to a wifi endpoint
 2. Queue chapters for downloading
 3. Change endpoints

When going back to the app, clearing the download queue, and attempting to download chapters again,  the error "No wifi connection available" appears in the notifications. You can still read the chapters without downloading, and access the internet through other apps, however.

**Other details:**
Clearing the app cache, restarting the device, and using different wifi did not remedy this issue.

**Comment by arkon** [comment]
Can't reproduce. If anything, the issue may be that it pauses the queue, but there's another issue for that.
