### ISSUE TITLE
Force Landscape and Fit Width Scrolling Issue

### ISSUE THREAD

**Issue by auras3** [tachiyomiorg/tachiyomi#1773]
**App version:** 0.8.0

**Issue/Request:**

When rotation is force landscape and the scale type is set to fit width, scrolling to the next page will position the view slightly past the top of page.

**Steps to reproduce (if applicable)**

 1. Set rotation to force landscape
 2. Set scale type to fit width
 3. Swipe up to scroll to next page
4. View is positioned slightly past the top of the page

**Other details:**

This didn't happen in 0.7.4, I think.

**Comment by CrepeTF** [comment]
can't replicate
