### ISSUE TITLE
[Request] Backup Sync

### ISSUE THREAD

**Issue by grravity** [tachiyomiorg/tachiyomi#1775]
**App version:**
0.8.0
**Issue/Request:**
It would be nice to have a feature that let's us log in with Google or something and backup our lists/extensions and stuff. I know there's a option to make backup file, but a sync option would be awesome.

**Steps to reproduce (if applicable)**

not applicable

**Other details:**

**Comment by Z3ROGRAV1TYx** [comment]
@as280093 The thing is, with Google drive it doesn't automatically sync right? Meaning you have to constantly create a new save file say every chapter you read, or every book you add or whatever. If you don't you're stuck with whenever your last save was made. A introduction of an auto sync between Google would be a feature that most apps have that this one lacks. It would make ease of use a lot better, especially for users who say constantly swap between a phone and tablet to read.

**Comment by as280093** [comment]
@Z3ROGRAV1TYx thill then you can use an app called AutoSync to google drive.

it auto syncs you folder to google drive 
just use local backup and then configure this app.


https://play.google.com/store/apps/details?id=com.ttxapps.drivesync

**Comment by serjflint** [comment]
#1146 will be much better.

**Comment by CrepeTF** [comment]
Basically #912
