### ISSUE TITLE
Anime-Planet tracker

### ISSUE THREAD

**Issue by Vesnyx** [tachiyomiorg/tachiyomi#1785]
**Issue/Request:**
Support for tracking manga on [Anime-Planet](https://www.anime-planet.com/)

**Other details:**
Currently, they have no public API. However, I believe a workaround could be done using the same method used for MAL's current implementation. 

At the top of a page for Anime-Planet, a token will be generated:

```
var TOKEN = '0b716xxxxxxxxxxxxxxxxxxxxxxxxxxx';
```
This token allows you to make requests like so:
`https://www.anime-planet.com/api/list/status/manga/21385/0/0b716xxxxxxxxxxxxxxxxxxxxxxxxxxx`
where 21385 is the manga ID  and 0 is the current state of the manga.

If you want to update the manga's current read state you can do so like this:
`https://www.anime-planet.com/api/list/update/manga/15429/0/19/0b716xxxxxxxxxxxxxxxxxxxxxxxxxxx`
where the 0 is a placeholder for # of chapters and 19 is the number of volumes
or like this:
`https://www.anime-planet.com/api/list/update/manga/15429/211/0/0b716xxxxxxxxxxxxxxxxxxxxxxxxxxx`
where 211 is the chapter # and 0 is the volumes.

Anime-Planet only supports tracking of volumes or chapters, so it would probably easier for tachiyomi to  send requests for only the chapters.

**Comment by as280093** [comment]
it could be nice to include many tracking services but i think rather then putting this feature now tachiyomi team should work on other problems or other implementations 
@Vesnyx why  dont you use kitsu anilist till then once tachiyoi team is free they can work on this as anime-planet doesn't have an official API it could be complicated so i think you should wait of a long time or as @inorichi  say we will try but don't gets your hopes up now.

**Comment by Vesnyx** [comment]
@as280093 From a cursory glance at the MAL workaround, it shouldn't be super difficult to implement. MAL uses a CSRF token to make the requests, which is acquired as a "session" token similar to Anime-Planet. 

Besides, if inorichi won't work on it, I'll start working on it at some point. This issue is mostly for the sake of having the data easily accessible so I can debug in the future.

**Comment by gilbertv722** [comment]
Any update?

**Comment by toprak** [comment]
@Vesnyx How is it going?

**Comment by loocool2** [comment]
@toprak When half life 3 comes out

**Comment by joelchrono12** [comment]
I am citing this from a dupe issue just so other people see it quicker lol:

@Vesnyx said in this in #2039 : 
> I'm currently planning on adding this in once the app hits the 1.0 milestone. I don't know if it'll impact the authentication methods currently used and I'd rather have it done all at once. :)

So, we are at 0.12.3 lol, but any plans now in 2022? :P

**Comment by Vesnyx** [comment]
Well, the 1.0 rewrite is still happening so idk. Anime-Planet was also supposed to release an API a while back and that also hasn't gone anywhere. Also, if anyone does want to go ahead and try implementing it, don't let me hold you back and go for it. :)

**Comment by arkon** [comment]
Closed by the automod because of "anime" in the title, but also true unless Anime-Planet ever offers an actual API.
