### ISSUE TITLE
[Feature Request ] Show Extension Working Status

### ISSUE THREAD

**Issue by as280093** [tachiyomiorg/tachiyomi#1818]
It Could be nice if everyone can view that Extension is working or Not just going to Extension tab in Tachiyomi App 
I Think its a a Tachiyomi Extension Feature but its Main App related

I have Made this Image for easy Understanding if anyone want to change the look or concept then its ok. 

the main objective is that everyone should know which extension is working and which are not 
this will reduce the complaints about  extensions not working in their device.

they can directly see that  the extension is down rather then asking question on discord , GitHub and other sites that X extension is not working.

![screenshot_2019-01-26-10-02-21-489_eu](https://user-images.githubusercontent.com/25240839/51782968-3a45c380-2158-11e9-8de2-1f8b0bd78546.png)

Green Means its Working and Red Means Not.
Anyone can Tell that its not working if its green then main moderators or other person with right permission  can simply confirm it and edit the status json or txt file so other person can see that extension is down and everyone will know it
the data can be Taken from json or txt file and anyone with right permission can edit it

**Comment by arkon** [comment]
At best, #4431 would be a better mechanism for surfacing status updates. This would be a pain to maintain.
