### ISSUE TITLE
[Feature Request] Fingerprint scanner gestures for page navigation

### ISSUE THREAD

**Issue by Kittyplx** [tachiyomiorg/tachiyomi#1832]
App version: 0.8.0

Issue/Request: Option to use the Fingerprint scanner as next page function.

Other details: It's kind of hard to swipe or tap one handed with a 6+ inch phone (volume up or down for navigation is also clumsy one handed and the buttons are a bit hard to press down consecutively). 

The Fingerprint scanner however is positioned perfectly in the back and is easy to reach while holding the phone one handed. So can we have an option where we can use it as a next page function?

**Comment by Soitora** [comment]
I support this

**Comment by AmineI** [comment]
Looks complicated since many phones have the FP scanner on the home button, on the front of the phone

**Comment by toshiro9117** [comment]
Yup it looks complicated...

**Comment by AmineI** [comment]
However, Starting with SDK 26 (Oreo) there's a way to register for fingerprint gestures. Would make sense (swipe left/right on FP to change pages).

But I'm afraid it requires an accessibility service, if I understood the docs correctly - feel free to correct me on that

https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController

**Comment by Kittyplx** [comment]
There are a couple other fingerprint gestures app in android stores, for example https://play.google.com/store/apps/details?id=com.ztc1997.fingerprint2sleep 

We don't really need it to be too advanced, only for it to jump to next page when it register your finger.

**Comment by exp0nge** [comment]
I think this is made easier with https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController?

Is there interest in doing this? I might be able to take a crack at it

**Comment by AmineI** [comment]
> I think this is made easier with https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController?
> 
> Is there interest in doing this? I might be able to take a crack at it

Yeah, I linked this as well a year ago, but when I looked into it more this API seems designed to handle fingerprint gestures system-wide (even while the app is closed), which is probably why it needs the app to be set as an accessibility service. 
Probably possible however if you want to try, but I'm afraid of the potential issues.

**Comment by exp0nge** [comment]
> 
> 
> > I think this is made easier with https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController?
> > Is there interest in doing this? I might be able to take a crack at it
> 
> Yeah, I linked this as well a year ago, but when I looked into it more this API seems designed to handle fingerprint gestures system-wide (even while the app is closed), which is probably why it needs the app to be set as an accessibility service.
> Probably possible however if you want to try, but I'm afraid of the potential issues.

Ah, unfortunate then. Seems like a hammer for what we want I guess? Maybe the better option is to just use something like https://play.google.com/store/apps/details?id=com.superthomaslab.fingerprintgestures&hl=en_US&gl=US (which would be a superset, sure)

**Comment by AmineI** [comment]
> Ah, unfortunate then. Seems like a hammer for what we want I guess? 

Yeah, that's how I feel about it as well ! I think we could `registerFingerprintGestureCallback` in the reader, and  `unregisterFingerprintGestureCallback` whenever the reader is closed or apps are switched, but it feels strange and unreliable to me ? Not to mention conflicts with other fingerprint gestures ? 

But I am no expert in Android development, so if anyone around is more knowledgeable I'd be glad to hear their opinions 🙂

**Comment by AmineI** [comment]
With how it has to be implemented, it is easier to do such a thing system-wide. And I think that users who would want page navigation with the fingerprint gesture are likely to want it when browsing the web or what not as well.

With that said, a third party app would be more suited to implement such a feature system-wide. Both third party apps mentioned above do not support this specific scenario without root.

It can be done with an automation tool however, such as [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate&referrer=utm_source%3Dhomepage). This [premade Automate flow](https://llamalab.com/automate/community/flows/28649) is enough to be able to scroll left/right/up/down with the fingerprint scanner on any app. (Note that I'm not the author of this flow)

If some people want this ability only in one or two apps, they are able to change the flow to do so as well.

**Comment by arkon** [comment]
Closing this as there seems to be no interest in implementing it by others.

I personally don't want to since:
- It requires an accessibility service, which is a bit painful to direct users to enable
- Fingerprint readers on back of devices have gotten less popular since 2019
