### ISSUE TITLE
[Feature Request] Allow us to leave certain extensions out of "Library Updates"

### ISSUE THREAD

**Issue by HamGoblin** [tachiyomiorg/tachiyomi#1839]
**App version:** 0.8.0

**Issue/Request:** Allow us to leave certain extensions out of "Library  Updates"

**Other details:** Hentai extensions used to not be included in my "Library Updates" list. Now they are, and they seriously clog up the list and make it hard to see updates for series that actually update. A way to keep NSFW sources out of our library updates would be very appreciated, especially now that TachiyomiEH is basically moot in comparison to Tachiyomi.

**Comment by metroid112** [comment]
Maybe you can move those titles back again to a new list?

**Comment by AmineI** [comment]
Just move them to a different category in your library and exclude that category

**Comment by hXtreme** [comment]
@Aminel manually moving mangas to different categories seems like an excessive amount of work for a feature that seems quite straightforward.  
However I think that a better way to do this would be to allow users to disable an extension temporarily as opposed to giving fine grained option to opt out of library updates.

**Comment by hXtreme** [comment]
Alternatively @HamGoblin, it might be possible to get a NSFW filter in the library. I personally really like this but, the downside of this approach is that it is not exactly straightforward to implement and would require a lot of minor changes in a bunch of different places.

**Comment by baraa272** [comment]
i would say excluding categories from library updates is the way to go about this
