### ISSUE TITLE
[Feature Request] Override autodownload per-manga

### ISSUE THREAD

**Issue by JukePlz** [tachiyomiorg/tachiyomi#1844]
**App version:** 
8.x

**Issue/Request:**
I think a feature to override the autodownload setting on individual manga would be much more useful than shoving everything into duplicate categories or a single category for mangas you want to download. The autodownload setting has literally nothing to do with a clasification of genre or any other thing, but it forces the user to use categories in weird ways to have autodownloads.

My sugestion is:
- Add the setting to the manga reader settings, so it's on an individual basis.
- Make the setting override the category setting.
- 3 options: Obey category (Default), Always autodownload (Override), Never autodownload (Override)

Implementing it this way shouldn't affect any current user, as those will remain in the default setting without even noticing any changes to autodownloads.

**Comment by metroid112** [comment]
What do you mean weird ways? Those are the purpose of categories, separate Manga according to behaviour (update timer, auto download,...)

**Comment by JukePlz** [comment]
> 
> 
> What do you mean weird ways? Those are the purpose of categories, separate Manga according to behaviour (update timer, auto download,...)

No, they're not. The official Tachiyomi proyect definition of categories is "to organize your library". Organizing is something done based on the user needs, and has nothing to do with automating downloads. You can organize with genres: "Isekai, Ecchi, Romance, Shonen..." other user may organize by states: "Finished, Reading, Plan to read...", other by format: "Manga, Manhua, Manhwa.."

This is how categories operate in almost every single software that has them, including other manga readers.

**Comment by metroid112** [comment]
I'm not denying those uses, I'm just saying it's not weird to use categories that way (behavioral) since that's their big functional purpose on this app. 
Organizing the library is also a plus but those categories won't change anything other than making the navigation easier.

**Comment by JukePlz** [comment]
Just because that is their current behaviour doesn't mean that the UX design is ideal. That's the point of making a sugestion, to improve the feature so it's tied to the logical way it should work, managing downloads automatically is a per-manga setting for users, forcing them into groups of "fake" categories doesn't make any sense, it's just a workaround for bad design. No other app does this, it isn't explained to the user why the behaviour is better nor does it offer any advantage. On the contrary, what it does is separate every manga you want to auto-download from it's proper (descriptive) category into a big cesspool of all mangas you want to download. Either that, or having a nondescript category of duplicates solely for the pourpose of autodownloads.

Not only that, the flow to change the setting could be considerably faster if it was redesigned into an individual setting. Just longpress over the library cover and set (or unset) an "autodownload" flag to the manga. Right now you have to 1) Create a separate category for autodownloads 2) Set that category in autodownload settings and 3) Asign that category tag to the manga by long pressing.

This is much more discoverable as a feature and more intuitive/less complicated for any new user.

**Comment by arkon** [comment]
Not quite the same, but you can exclude categories from auto-download now. You can create an additional category (e.g. "Don't download") and put any manga into that as well, and it'll be ignored since exclusion takes priority over inclusion.
