### ISSUE TITLE
[Feature Request] Per-series Scale type

### ISSUE THREAD

**Issue by FaultyGolem** [tachiyomiorg/tachiyomi#1849]
Just a really minor QoL change. Some series are dual pages instead of being split, so I use 'Smart Fit' for them and 'Fit Screen' for everything else. 
The problem is, Scale type is a global setting, so you have to change it each time you go from reading a single page series to reading a dual page series.

**Comment by arkon** [comment]
#6306 would be more preferable to make it easier to toggle, since per-series settings are generally too troublesome to add.

**Comment by wopian** [comment]
Buttons at the bottom don't solve this issue, it just moves the pain point to somewhere else on the screen.

You'll still have to switch scale types every single time.
