### ISSUE TITLE
Include app and source settings in backups

### ISSUE THREAD

**Issue by phanirithvij** [tachiyomiorg/tachiyomi#1857]
**App version:**
0.8.0
**Issue/Request:**
Backup Theme, Reader Settings, and Library per row settings.
**Other details:**
Please do it as I don't see how it is going to add an extra compatibility layer. That you mentioned here.
https://github.com/inorichi/tachiyomi/issues/795#issuecomment-301329864
~Please elaborate this further on why you're not implementing this as it looks as simple as adding 3 lines of code where the code for backing up is written.
And a checkbox logic to do it or not.~ Edit: Nevermind I take this back, I didn't know android dev when I created this issue. Sorry about that.

[Screenshot](https://user-images.githubusercontent.com/29627898/53304868-73c93600-38a0-11e9-84b8-204bb1b25816.jpg)

**Comment by phanirithvij** [comment]
@inorichi @CarlosEsco Please explain why not. It's just exporting and importing.

**Comment by arkon** [comment]
Because you need to ensure that it handles importing newer or older versions of settings. If you actually do think it's 3 lines of code, you could open a PR.

**Comment by XiangRongLin** [comment]
@arkon 
I would be interested in working on this. But seeing that there is resistance against it because of added complexity I wanted to know what the requirements would be for this to be added.  
I planned to apply the migrations from Migrations.kt file to allow restoring older versions of the settings and completely disallow restoring newer versions if a migration exists between the versions.

**Comment by arkon** [comment]
@XiangRongLin Sure! If you could detail your approach, I (and maybe others) can provide feedback.

Some things to keep in mind:

- Storage location settings might be problematic due to different folders, SD cards, and/or permissions
- Handle if preference keys are no longer available
- Handle if preference keys for some reason changed types (e.g. int to string, although this ideally would never happen)
- Decision around overwriting settings that are already set
- Might need to tweak restore to allow selectively restoring parts of the backup (e.g. restoring manga but not settings)

There's probably more that I'm not thinking of right now, but that ought to be enough for you to start thinking of an approach?

**Comment by Flat** [comment]
I've been doing research into re-writing backups to use something like kotlinx.serialization, which may help for this case as well as provide for an easier path to more reliable backups overall. I'd be happy to provide help on the issue as well when I have time.

**Comment by XiangRongLin** [comment]
>Storage location settings might be problematic due to different folders, SD cards, and/or permissions

This would then be excluded from the backup/restore. 

> Handle if preference keys are no longer available
Handle if preference keys for some reason changed types (e.g. int to string, although this ideally would never happen

This should be the [Migrations.kt](app/src/main/java/eu/kanade/tachiyomi/Migrations.kt), so i would modify that, so i can apply the preference migrations on the import if versions are different. Or are the preferences changes without it being in there?

>Decision around overwriting settings that are already set

I would overwrite everything with the backup.

**Comment by CarlosEsco** [comment]
preference changes are not in migrations.kt

**Comment by arkon** [comment]
There is some, but those are tied to the app updates. Backups need to work across app versions. You can consider tracking setting versions in the backup itself.

**Comment by SakuraCodes** [comment]
I think it's possible to backup comics and settings in separate files, for example you can use bak or zip or txt to store system settings files. The format can be backed up in a way that a variable corresponds to a value, which is convenient for adding new variables later.

**Comment by BhaturaGuy** [comment]
This [beta](https://github.com/jmir1/aniyomi-mpv-beta) version of Aniyomi does support settings backup and restore.

**Comment by Saud-97** [comment]
I suggest to do a check before restoring settings to verify if the backed up app version matches the exact current app version. So restoring will only work for apps with the same version. This is just a workaround for compatibility tho.

**Comment by arkon** [comment]
For reference: https://github.com/jmir1/aniyomi/commit/e2ad7ac82c8f0eab464e2536a29f2e2b8176451f

Notably doesn't handle migrations or invalid values from other versions of the app (forks, main app, etc.). It'd be ideal if whatever's implemented handles settings across forks, but it might be fine to just restrict it to a certain variant to help ensure compatibility.

**Comment by jmir1** [comment]
> For reference: [jmir1@e2ad7ac](https://github.com/jmir1/aniyomi/commit/e2ad7ac82c8f0eab464e2536a29f2e2b8176451f)
> 
> Notably doesn't handle migrations or invalid values from other versions of the app (forks, main app, etc.). It'd be ideal if whatever's implemented handles settings across forks, but it might be fine to just restrict it to a certain variant to help ensure compatibility.

my thought process behind this feature was this:
when i remove/change some setting in the future and a user restores an old backup file there will be a useless setting stored under that old key and the user will again have to manually change the new setting to their liking.
but as far as I'm aware, there shouldn't be any "breaking" issues with this...
to be fair, I haven't tested this a lot, so consider my implementation a sort of test-flight. if it works without issues, you should consider putting it in the main app as well.

**Comment by Kryptox95** [comment]
Just gonna leave this here:

After updating my entire library on my phone, i came across the case, that after exporting and important my current library, it won't backup the custom covers i have set for each entry. Just wanting to point out that once you are trying to publish an newer solution for this issue, i would greatly appreciate to include the covers as well. (ofc, you should be free to decide wheater you want this to be backup'ed up or not). 

Anyways, just felt like sharing this...

**Comment by arkon** [comment]
@jmir1 I believe there's a possibility of it crashing with enum values that don't exist, but it may be dependant on their usage.

**Comment by GitExploraa** [comment]
+1 hope this gets included

**Comment by soredake** [comment]
Tachiyomi's fork [aniyomi ](https://github.com/jmir1/aniyomi) now can backup settings too.

![image](https://github.com/tachiyomiorg/tachiyomi/assets/5204968/ea42731d-210b-49b8-b84c-8a270ca1e91a)

**Comment by Jerrk** [comment]
https://github.com/jmir1/aniyomi/commit/05b72eee1b8e7469f49fc47ac86dc354267d0557

**Comment by hruzgar** [comment]
When will this be implemented? Aniyomi already did it. So the same changes just need to be done? Just wanted to give some life to this issue.

**Comment by grphine** [comment]
i was just migrating to a new phone and was looking to see if there was an option for this. it's a shame there isn't at the moment.

**Comment by arkon** [comment]
Notes on the implementation:
- This is based on Aniyomi's implementation and is compatible with backups from it.
- This does _not_ include any tracker credentials in the app settings (or anything else that has keys prefixed with `__PRIVATE_`). Note that source settings may contain sensitive data, including credentials.
