### ISSUE TITLE
[Feature Request] Filter by Tracking or untracking

### ISSUE THREAD

**Issue by as280093** [tachiyomiorg/tachiyomi#1899]
Adding this filter like this will help us to track which manga are tracked and which not 

![Capture11111](https://user-images.githubusercontent.com/25240839/54529773-e5c80300-49a6-11e9-9169-c7a347cb1e69.PNG)

**Comment by haldi4803** [comment]
I also think this would be a really neat Feature.

**Comment by hXtreme** [comment]
Maybe just one for Tracking instead of one for every tracking?

It kind of bloats up the filters.
