### ISSUE TITLE
[Feature Request] Extension information before installation

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#1926]
On the extension screen it would be really helpful to be able to tap on an extension to open up a page that shows information about the extension such as:  

- Name of Extension (in case the name was too big to fit on the  previous screen)  
- Download size of the extension   
- Sources provided by the extension.
- Obsolete sources (alternative extensions)
- Change-logs,  etc.

This information would make it easier to decide which extension to install and avoid the need for ~~users to just try and guess to see which extension they need~~ maintaining a list on the website or on the faq section on discord, neither of which are being utilized by a lot of users.

**Comment by as280093** [comment]
i think name of extension out of the box and size doesn't matters as all extensions are below 1 mb and for the sources, that should not be a problem in 1.x as extension will be separate not bundled in one extension and more info will be available like short description

**Comment by inorichi** [comment]
I don't think this screen will be redesigned before 1.x.

1.x handles this better. An extension can provide at most 1 source so we don't need a list of sources provided.

Also, as mentioned, extension sizes are very low so it's not really worth.

**Comment by hXtreme** [comment]
Well, I guess this can be closed then.

**Comment by hXtreme** [comment]
@CarlosEsco can we reopen this? I've edited this to also include content from #2420.

**Comment by arkon** [comment]
Largely irrelevant now with multisource extensions having been split.
