### ISSUE TITLE
Automatically rotate based on image size/aspect ratio

### ISSUE THREAD

**Issue by kaiteck** [tachiyomiorg/tachiyomi#1977]
**App version:**
0.8.4

**Issue/Request:**

Change screen orientation by image size

**Other details:**
If the app detects a landscape image, like 4:3 or 16:9, the whole app itself automatically rotate to landscape orientation so there's no need to wait/reply on the sensor. This also benefits users who read manga lying down sideways(Thereby they can't rely on the sensor)

This feature is also present under [ QuickPic app > Settings > View > Change screen orientation > By image size ] for reference.

**Comment by Matth7878** [comment]
It would be nice to add a smart forced portrait rotation mode.
When width is longer than height it would auto rotate to landscape. If not portrait would be used.

For webtoon or vertical reading mode smart forced portrait should never rotate to landscape.

If there was such a mode I think it would also solve issue #3521

**Comment by arkon** [comment]
I feel like the root case to ask for this is addressed by dual page split, which avoids having "smaller" images being shown and being forced to zoom in.

**Comment by kaiteck** [comment]
No, dual page split only addressed to image that has dual page in 1 image
file.

The issue here is referring to full landscape image single page drawn by
artist. I mean, sure you can just rotate your tablet to landscape but
gyroscope does not work well on bed and you have to wait for rotation delay
so it is faster for the image to rotate itself before the user rotates the
tablet.

Example
https://images.app.goo.gl/cy6gXWZ9vnY5DaBD7

**Comment by Sreinumder** [comment]
If tachiyomi can detect and split dual pages, then It should be possible to rotate the image by 90 degrees.

**Comment by mpzaborski** [comment]
Same as @kaiteck I address image that has dual page in 1 image file. I would highly appreciate this feature, because not every ebook reader has accelerometer, thus option to rotate based on position is not working. Lack of self rotate makes experience more time consuming.

**Comment by juniorjacob** [comment]
I wanted to readdress that this would be a really nice feature to have. I prefer seeing double pages in their full glory and if the app would manage changing orientation for me so that i can simply tilt my phone, with the image already in the correct orientation, it would give the app that much more ease of use.

**Comment by opensource0apps0enthusiast** [comment]
is this feature available in other forks? If so, please reply which one. thank you

**Comment by restingcarcass** [comment]
Timothyng-164's version wouldn't work with extensions for me, so I did the same changes to a more recent version of tachiyomi. Now extensions work. Big ups timothyng for figuring this out in the first place.
