### ISSUE TITLE
Reversing direction when zoomed in at page border causes next/previous page to appear instead of showing rest of page

### ISSUE THREAD

**Issue by Tibowl** [tachiyomiorg/tachiyomi#1980]
**App version:** r1499

**Android version:** 8.0.0

**Issue:** Reversing direction when zoomed in at page border causes next/previous page to appear instead of showing rest of page

**Steps to reproduce (if applicable)**

 1. Zoom into page
 2. Move to side with previous page
 3. Start swiping to previous page
 4. When previous page shows up, reverse direction of finger (eg to next page)
Expected: rest of page shows up
Actual: goes to next page

**Other details:** Vid demonstrating https://streamable.com/8vlya

For normal pages this isn't much of a problem since it's quite noticeable when this happens, but when reading vertical in full width, it can be a bit confusing as to when it's scrolling just down, or scrolling to next page (which like could spoil the current page).

**Comment by wmahmoud** [comment]
I'm not sure this is a bug. This seems to work as I would expect it to without a separate "zoom” portrait being opened when you zoom in. 

If you lift your finger, the "page turn mode" won't be active and you can move the zoom box as expected. If you keep your finger on the screen, the page turn will still be active.

**Comment by arkon** [comment]
The actual behaviour seems sensible enough; not worth "fixing".
