### ISSUE TITLE
Tracking default status Plan to read

### ISSUE THREAD

**Issue by j2ghz** [tachiyomiorg/tachiyomi#200]
- When binding a manga without any read chapters, make status Plan to read
- When changing chapter count from 0 and status is Plan to read, make status Reading

**Comment by IceKreem** [comment]
I second this +1

**Comment by inorichi** [comment]
I could make the default status Plan to read. For the second point, I think it's better to let the user decide, some may want to keep them in on-hold, for example.

**Comment by j2ghz** [comment]
Without the second I wouldn't like the first, because the I would forget to set the right status all the time.

The change is supposed to happen just when the number of read is 0 and it's changing to something other than 0 and the status is plan to read. I think there are hardly any cases when all of this is true and you still want to keep it plan to read.

**Comment by hyoretsu** [comment]
Does bumping work? I wrongly populate my reading list by pre-downloading new manga.
