### ISSUE TITLE
[BUG] Graphical bug on last page flip with volume keys

### ISSUE THREAD

**Issue by skipfie** [tachiyomiorg/tachiyomi#2003]
**App version:**
r1500
**Android version:**
9.1
**Issue/Request:**
Graphical bug on last page flip, doesn't display the "next chapter" page, only shows blank screen.
**Steps to reproduce (if applicable)**

 1. Enable flip using volume keys
 2. Navigate to last page using volume keys
 3. Flip page with volume key
 4. Page should be black with no text.

**Other details:**
Huawei P30 Pro, latest EMUI
Running full screen mode

Screen recording:
https://cdn.discordapp.com/attachments/449074357424095233/569958735573942283/SVID_20190422_113035_1.mp4

**Comment by arkon** [comment]
Can't reproduce in current version.
