### ISSUE TITLE
Single tap 

### ISSUE THREAD

**Issue by starkgate** [tachiyomiorg/tachiyomi#2010]
**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:** 0.8.4

**Android version:** 5.x

**Issue/Request:** I would love to see the single tap behaviour of CDisplayEx implemented in tachiyomi; whereby single tap scrolls to the bottom of the page. Only if the bottom is already reached does it turn the page.

This is especially useful in cases where the page's height doesn't quite fit on the screen, and part of the bottom is cut out. I prefer not using "fit to height", since it makes the page smaller.

It could be implemented in another way than CDisplayEx, single tap in the bottom left or right corner scrolls down; single tap in the center left or right turns the page left or right.

**Other details:**

Additionally, if you consider this feature, it'd be great if there was an option to disable the scrolling animation. I'm using tachiyomi on an ereader, so any animations are slow and look bad.

**Comment by hXtreme** [comment]
Are you dealing with long strips format? Or is it that some pages of your manga are long and don't fit?

**Comment by CreeperLava** [comment]
Just too long and don't fit. But you make a good point with strips, too.

**Comment by arkon** [comment]
Closing in favour of #2161, which is a bit clearer.
