### ISSUE TITLE
[Feature Request] Add more update timers

### ISSUE THREAD

**Issue by sharedkestrel** [tachiyomiorg/tachiyomi#2055]
I didn't see another issue open about this, so I'll ask.  
Is it possible to add some more options to General > Library Update Frequency? Something like 30 minutes / a week. Or maybe add the option to input a custom timer, if it's possible and doesn't cause headaches with Android.

**Comment by Matth7878** [comment]
An option to update when opening app would also be great. :-)

**Comment by arkon** [comment]
A week was added at some point, but 30 minutes is too often. The current list seems reasonable enough.
