### ISSUE TITLE
[feature request] delete downloaded chapter after done migrate manga

### ISSUE THREAD

**Issue by pervertkirito** [tachiyomiorg/tachiyomi#2059]
I noticed that downloaded manga chapter is not deleted and stay on Tachiyomi download folder.

would be great if tachiyomi could delete it automatically.

**Comment by jasonhpchu** [comment]
Do a copy when you migrate, then delete manually after.
Doing this allows you to also check the new sourced manga to make sure it has what you're looking for first before removing the old one.

**Comment by pervertkirito** [comment]
> Doing this allows you to also check the new sourced manga to make sure it has what you're looking for.

I don't think that is necessary. I mean you can view directly from source migration result by hold on the search results for few seconds

**Comment by jasonhpchu** [comment]
> I don't think that is necessary. I mean you can view directly from source migration result by hold on the search results for few seconds
Ohh interesting, that'll help.  I currently migrate copy a bunch and see which one's the best then delete the others.

**Comment by arkon** [comment]
Closing in favour of #3529
