### ISSUE TITLE
[REQUEST][FEATURE] Add "Vertical Scroll" for Vertical, Left to right, right to left when pressing "Next Page"

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#2060]
Current behavior:
1. Open a manga page that's taller than screen size with smart fit. The manga page will fit device's screen width, but its bottom will be cut-off.
2. Press page down (via touch or via button press)
3. It will go to NEXT PAGE

Proposed behavior:
1. Open a manga page that's taller than screen size with smart fit. The manga page will fit device's screen width, but its bottom will be cut-off.
2. Press page down (via touch or via button press)
3. It will scroll down, revealing the cut-off part. (even better if it have an option to skip the scroll down animation)
4. Press page down again, and it will go to the next page.

Why:
- This allows the full page to be read simply by tap or button press. No need to do "scroll down gesture".
- This is pretty handy for eReader (because it usually have hardware button and its sluggish)

Workaround:
- use WEBTOON viewer mode. It doesn't have paging so it will have tons of awkward layouts (bottom of page 1 and top of page 2 in the middle of the screen)

Thankyou

**Comment by arkon** [comment]
Closing in favour of #2161
