### ISSUE TITLE
[Feature request] max download folder size/downloaded file lifetime/automated namespace garbage collector

### ISSUE THREAD

**Issue by ZaneHannanAU** [tachiyomiorg/tachiyomi#2067]
More or less wanted some means of limiting the size of the download folder; perhaps by removing downloaded files from storage after a certain time, and when certain limits are exceeded.

For example, some rules would be to delete only whole downloaded sets of manga (eg from directly under the namespace; before the volume-chapter folder) after a few rules.

Personally I would put it as 2/3 of

- Disk space is running low
- Title has not been read for the most amount of time (filter by downloaded, sort by last read, pop)
- Disk usage has exceeded the warning for a given amount of time; or is currently exceeding the set limit

This is more of an idea than an actual request but it might be something for the backburner; or a background service that runs after a download service has completed at a low priority.

Though it would have some custom settings; eg lowest bar to remove downloads more than *n* weeks unread, maximum storage that is allowed to be used before deleting items that have not been read, categories which can have downloaded chapters deleted, categories exempt from adding to the total used storage and so on. Would probably end up as its own thing, though.

**Comment by arkon** [comment]
I feel like this would be _very_ confusing to most people since they wouldn't expect downloads to disappear after some time if they accidentally turned it on.

It does basically just sound like you want a bigger cache though.

**Comment by ZaneHannanAU** [comment]
Indeed. I have 40 GB for tachi at the moment (including a bunch of large titles), but a lot of that is filled by titles I'm in the process of reading, or haven't read in a long time. I might go through and see if I can effectively write it in once I have a computer that can run android studio.
