### ISSUE TITLE
Custom location for local manga

### ISSUE THREAD

**Issue by farahnur42** [tachiyomiorg/tachiyomi#2086]
App version: 0.8.4

Android version: 9.0

Issue/Request: Manually adjustable local manga folder path i.e the ability to set a custom path for the local manga folder

Something like: %LOCAL_PATH% = *PATH* in the settings for Tachiyomi

**Comment by arkon** [comment]
This will likely make it much slower, FWIW.

**Comment by farahnur42** [comment]
I'm fine with that, considering it wouldn't exactly be fast anyways (due to the fact that the folder I'd be selecting has about 300 gigs worth of stuff). The main reason why I'd like something this is to be able to mount a remote folder and have Tachiyomi as my reader for that folder. Perfect Viewer is an alternative but I prefer Tachiyomi's UI and overall capabilities.

**Comment by alittlebitofit** [comment]
Hello, I seem to have a similar issue, I would like to set the local manga path to a custom directory in my internal storage itself.

Tachiyomi version: 0.8.5
Android version: 4.4.4

Is this being implemented?

**Comment by curche** [comment]
/edit-title "Manually adjustable local manga folder path"

**Comment by arkon** [comment]
Superseded by #9591
