### ISSUE TITLE
[feature request] option to always flash white / black every page change (useful for eink devices) 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#2123]
Eink devices have image retention issue. It looks worst with manga that have lots of blacks (like montage by watanabe Jun). 

Would be nice if tachiyomi have an option to flash the screen white or black for every page change. So there will be almost zero image retention. 

Thankyou.

**Comment by hXtreme** [comment]
**Note to anyone who tries to solve this issue:** It may be a good idea to create a new viewer for e-ink devices so that all future e-ink specific requests can just be implemented into the new viewer instead of cluttering the other viewers with a bunch of options.

**Comment by fukuimaunicorn** [comment]
I would propose adding an E-Ink Mode that removes/reduces animations to minimize flicker on e paper screens.
Additionally I think it could be of great benifit to add a gray-scale theme that is easily ledgible on non-color e-ink devices.

But the main thing to work well on e ink, would be getting rid of as many animations as possible and just having instant full screen updates (for example when flipping pages) even if it adds delay, that would still be better than the ghosting/performance issues the animations create.

**Comment by johnledezma34** [comment]
For now some eink android companies (like boox) already include hacks to disable animations and flash the screen by page, time limit or operation. But honestly they are hacks and require fiddling that distracts from reading.

**Comment by hXtreme** [comment]
A bit of a hack but it might improve your experience (not just with tachiyomi but also many other apps)

Go to your phone settings > System > Developer options

From there you can disable transition animations and animator duration scale.

If you don't see developer options, just Google "How to enable developer settings on Android"

**Comment by Boiethios** [comment]
Honestly, as someone reading on an eink tablet, animations don't bother me that much. What I'd like to see, though, it a theme adding more borders, because shades don't work well on such a screen.
