### ISSUE TITLE
[Feature Request] Categories as filters

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#2126]
It would be really nice if there could be filters for categories just like we have filters for Download, Unread, and Completed.

This would work really well along with #943 

It would also be really nice if the categories filters were tri-state as suggested by #1814

**Comment by CarlosEsco** [comment]
Not sure how feasible this is as each site is defining their own genres most are standard but some like hentai ones go based off of tags and their tags can be unique.

 I guess you would have to keep a list of seen genres from manga you see or in your library then normalize them  so Shonen and shonen end up being the same.

**Comment by hXtreme** [comment]
I'm not asking for categories to be generated automatically from tags.

**Comment by hXtreme** [comment]
I just want the user defined categories to also act as filter in Library.

**Comment by hXtreme** [comment]
As an example here's the list of categories that I use
![cat](https://i.imgur.com/YI7o68k.png)

What I would like is a filter for each one of them in library so that I can effectively find manga that I read irregularly is short and something that gives me the feels.

**Comment by CarlosEsco** [comment]
Oh i see.  I saw categories and assumed you meant the genres.

**Comment by hXtreme** [comment]
No problem.

Also, the code from the gist doesn't work because I don't know how to get the list of all categories, can you suggest something for it?

**Comment by CarlosEsco** [comment]
make a new sql request to read entire category table?

**Comment by hXtreme** [comment]
Can you point me to somewhere that's done, I'm not well versed in SQL so I'll need that.

**Comment by CarlosEsco** [comment]
I think it would be this first method
https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/database/queries/CategoryQueries.kt

**Comment by hXtreme** [comment]
@CarlosEsco I'm just going to wait for #2127 to be merged it adds a few things I would need for catalogue filters.

**Comment by arkon** [comment]
I don't actually understand what this request means. Please open another issue with more details if desired.
