### ISSUE TITLE
[Feature Request] View cover images

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#2130]
The ability to open cover images in full screen by tapping on the cover in manga info page.

**Comment by as280093** [comment]
someting like this

![Screenshot_2019-05-22-21-44-27-332_eu kanade tachiyo](https://user-images.githubusercontent.com/25240839/61097145-b702fa80-a477-11e9-922f-ce851db60a05.png)

with close button and hold & save image 💾

**Comment by hXtreme** [comment]
Yes but cover should be even larger (covering the whole page).

**Comment by as280093** [comment]
i don't think its necessary for a full screen cover preview
adding double to fit to screen 
and pinch to zoom 
could be enough

**Comment by hXtreme** [comment]
If you look at your mock up image there's all kinds of things poking out from under the cover preview; on right there's the fab and a few letters. On left there's words, tags and part of the cover image.

One way to get around this is to completely dim out the background and the other way is by making the preview full screen, I'm actually fine with either of these two solutions.

**Comment by GuyInDogSuit** [comment]
I agree, this should be a feature. Much easier than opening the manga info in your browser to look at or save the cover images.

**Comment by as280093** [comment]
Fit to screen will just blur if it's low quality image
Based on image size high it full screen if possible and blur background if image is small and show based on size

**Comment by hXtreme** [comment]
Having two different behaviour on clicking doesn't sound that good, perhaps it should always just dim the background and show the cover.

**Comment by night-zhang** [comment]
How to use it?
I have downloaded 0.10.9.
It doesn't work to click or double-click the cover, and i can't find the setting.

**Comment by rohan-gt** [comment]
An option to download the cover image would also be useful
