### ISSUE TITLE
[Feature Request] [1.x] Tapping on an uninstalled extension opens the corresponding source in web view.

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#2133]
This give the option to people to check out a source before installing the extension.

One reason why someone would want to do this is to check if a particular source has the manga they're interested in. They could open it up in web view, look it up and then choose to install.

**Comment by hXtreme** [comment]
This may be feasible as [inorichi stated that](https://github.com/inorichi/tachiyomi/issues/1926#issuecomment-476211212) in 1.x each extension may only have at most one source.

**Comment by arkon** [comment]
Closing this since it's likely not going to happen in 0.x given how the extensions are structured still (we'd need to manually define all of the URLs to be in the listings file).
