### ISSUE TITLE
No wifi connection notification cant be dismissed

### ISSUE THREAD

**Issue by chrisadipascual** [tachiyomiorg/tachiyomi#2137]
**App version:**
0.8.4

**Android version:**
9

**Issue/Request:**
"No wifi connection available" notification cant be dismissed

**Steps to reproduce (if applicable)**
 1. Set wifi as update restriction
 2. Turn off wifi
 3. Turn on mobile data
 4. Download chapters of a "new" manga (anything that isnt in your library)

**Comment by chrisadipascual** [comment]
Workarounds :

1) Force stop the app by going to settings > app & notifications > tachiyomi

2) Force stop the app by going to system > developer options > memory > tachiyomi
 
 3) Reboot your device

**Comment by arkon** [comment]
Can't reproduce in latest version.
