### ISSUE TITLE
Arrows to increase/decrease chapter number in tracking page

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi#2139]
**Issue/Request:**
Add arrows (or something) in the manga tracking page to increase or decrease the chapter number, as the current method to tap the number and start scrolling is rather a bit tardy (lol) even for a single chapter.

Adding the arrows will decrease the number of steps for this particular task.

**Comment by arkon** [comment]
You don't need to tap before scrolling through the numbers.
