### ISSUE TITLE
[Feature Request] Ok Google "Update library in Tachiyomi"

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#2154]
This voice command/intent should, in the background start updating the library.

Furthermore it might be nice to have:

"Update <category name> category in Tachiyomi"

but I don't know how complicated that would be.

<sup>This is in lieu of the Discord conversation about being able to update library without opening Tachiyomi</sup>

**Comment by RYNAPU** [comment]
Doesn't look to hard to implement if you follow this guide : https://developers.google.com/voice-actions/interaction/voice-interactions

**Comment by arkon** [comment]
It's practically impossible to get Google Assistant to understand "Tachiyomi" so nah.
