### ISSUE TITLE
[Feature Request] Literally scroll through pages instead of navigating to other pages if needed

### ISSUE THREAD

**Issue by 0xAdk** [tachiyomiorg/tachiyomi#2161]
**Idea: The ability to use the volume buttons to through scroll pages for optimal laziness**

**Just to clarify** 

- Since there was a similarly named request #95 that lead to the volume key navigation feature. What I am requesting is the ability to Scroll the page (not "turn" it).

**How I see it**
- This would be a child option of the previously mentioned feature. 
When enabled pressing the volume keys while the page has content that is hidden off screen on only one of the screen's sides, the viewer smoothly translates a preset amount (Something like a whole, 1/2, or 1/4 of a screen's width / height) before "turning" to the next page

**Little note** for ease of implementation making it only compatible with "smart fit" scale type might make it more simple as you know what say you need to scroll.

**Comment by PhaZ90771** [comment]
This would be especially useful for webtoon series, since the page split is often through a panel in order to keep the page height consistent.

**Comment by arkon** [comment]
S-Pen integration also relevant to this: #4235

**Comment by arkon** [comment]
Navigate to pan addresses this.
