### ISSUE TITLE
Feature Request: Delete read chapters after a certain period of time not right away

### ISSUE THREAD

**Issue by mirouhml** [tachiyomiorg/tachiyomi#2170]
I think it would be nice if the read chapters will get deleted after a certain period of time rather than deleting them right away (I thought it's available but it's not there I kept searching for it) like sometimes after I finish a One Piece chapter I would read it again or check some pages again.

**Comment by metroid112** [comment]
I don't know how often you do this but why not just disable the feature and delete them manually?

**Comment by mirouhml** [comment]
I do it pretty often doing it manually would be tiring

**Comment by joseph619** [comment]
There's already this option. Go to settings, downloads, then tick Remove when marked as read. Easy.

**Comment by mirouhml** [comment]
read what I said carefully please I said " Delete read chapters after a certain period of time" like after 24h of reading the chapter it gets deleted

**Comment by joseph619** [comment]
What is the point of that? You can simply set 'delete second last chapter' and the last chapter you read won't be deleted. What you suggested will add bloat to the app.

**Comment by hXtreme** [comment]
The kind of functionality you want seems more like cache and less like 'downloads'

**Comment by mirouhml** [comment]
@joseph619 I used an app before that had this feature and it was very helpful I have a slow net so downloading manga is the only option for me to read it, sometimes I return to several chapters after reading them the functionalities available ("delete second last chapter" and so on) are not helpful sometimes I read more than 50 chapters in a small period of time especially if it's a webtoon and sometimes I like to return to a specific chapter to notice more stuff, so that's why it's helpful for me, and I am sure it's helpful to many others.

**Comment by mirouhml** [comment]
@hXtreme can you explain your point, please? I didn't get why does it seem like cache and not like 'downloads'.

**Comment by hXtreme** [comment]
While Cache and downloads both save data offline, cache would automatically clean up old or unused data over time(something that you want). So if Tachiyomi had a larger cache any manga that you recently read would be stored in cache for some time and afterwards it would be removed automatically.

**Comment by mirouhml** [comment]
@hXtreme oh that's a pretty good idea thanks for explaining the point

**Comment by arkon** [comment]
Not going to implement this.
