### ISSUE TITLE
[Feature Request] Select Sorting mode for all/multiple mangas

### ISSUE THREAD

**Issue by Kush-Patel** [tachiyomiorg/tachiyomi#2182]
**Request:**
I would like to have a option to set same Sorting mode (Ex :- By chapter number) to all mangas or selected mangas. Also I would like to have a setting for default Sorting mode such that when a new manga is added to library its Sorting mode is set to default

**Comment by hXtreme** [comment]
I like the idea of a default sorting mode.

Selecting the sort mode is usually a one time action for any manga so I'm not sure if it makes sense to add functionality to batch set the sorting mode.

**Comment by Johndeep** [comment]
Oh, oh! If we're talking about this feature, it might be great to have the following:
1. the ability to actually quickly select all manga at once (it is very tiresome to select all one by one)
2. Why select all? I use that to actually just count the Mangas now and then. Maybe having a Manga counter somewhere would be very appreciated. (Not really related to this issue, but a statistic for all mangas and manga per source for better overview would be nice)
3. If sorting by Source, maybe visibly group the Mangas in a drop down menu even? Similar to that, sorting by alphabet, grouping or maybe a letter scrolling on the side (similar to many contact apps).

**Comment by arkon** [comment]
This was added a while back.
