### ISSUE TITLE
[Feature Request] Reader 'Swiping' Navigation Toggle

### ISSUE THREAD

**Issue by badfoxtrot** [tachiyomiorg/tachiyomi#2208]
**App version:** 0.8.4

**Android version:** 10 (QP1A.190711.019)

**Request:** With the release of Android 10 and gesture navigation, it would be nice to be able to disable swipe navigation to change pages. This could be a toggle in Reader settings where you would navigate with either volume keys or tapping.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:** With 'normal' back sensitivity in Android 10 gesture navigation, it's very hit or miss when trying to do the Back gesture or advance to the next page (left to right)

**Comment by arkon** [comment]
I haven't heard anybody else ever bring this up, so I'm assuming people got used to how to use gestures properly without interfering with the app content.
