### ISSUE TITLE
[Feature Request] Set specific chapters to 'ignore' from reading / updating.

### ISSUE THREAD

**Issue by Matakor** [tachiyomiorg/tachiyomi#2224]
This is mostly a request around Mangadex specifically, but would apply to any that allow multiple sources or has duplicate chapters.

I'm hoping for a way to set duplicate chapters to be ignored by the reader and otherwise ignored by the update process. This way I don't scroll into the chapter thinking it's the next chapter only to realize I'm just re-reading it all over again.

It'd also be nice to be able to ignore the extra content chapters in some manga that I don't particularly care about. While I can delete these from downloads, they still automatically load in when I am reading in bulk, and I'd rather just stick to the main story only. This would also assist in lowering data usage, as well as being a QoL thing.

Bonus if you can limit by upload source within the category source.

**Comment by Matth7878** [comment]
+1 for this

Besides what's already requested it would be great to have an option to automatically ignore new available chapters older than last read.
When ignoring those you shouldn't get notifications about these chapters and they shouldn't be considered as unread.

If there is a need an ignored state could be implemented later to be able to identify ignored chapters from read one.

**Comment by arkon** [comment]
You can manually mark as read + set the reader to skip filtered or read items.
