### ISSUE TITLE
[Feature Request] Disable library update with WiFi on

### ISSUE THREAD

**Issue by Infiziert90** [tachiyomiorg/tachiyomi#2234]
**App version:**
0.8.4 F-Droid

**Android version:**
9

**Issue/Request:**
It would be really nice if i could restrict library updates when WiFi is active.
My reason for that request is simple, when i use my phone it is 95% mobile network, and the other 5% is in spots where i can't use mobile network, so i have to activate WiFi. But that is only in places like work, where updating my library is not my goal.

**Comment by foxlore** [comment]
If possible a WiFi blacklist would solve this issue in a wider variety of cases.

**Comment by arkon** [comment]
Seems like too niche of a usecase to support.
