### ISSUE TITLE
Don't automatically resume in-progress chapters

### ISSUE THREAD

**Issue by boxjohn** [tachiyomiorg/tachiyomi#2253]
一旦读过了这个位置，再倒回去看，下次打开也回不到原来那个点，只会跳到最后面的位置

**Comment by arkon** [comment]
Google Translated:

> Once you have read this position, go back and look at it. The next time you open it, you will not be able to return to the original point. It will only jump to the last position.

**Comment by arkon** [comment]
Could potentially have a setting to resume or restart started chapters.

**Comment by arkon** [comment]
Probably not worth having a setting for this.
