### ISSUE TITLE
One finger zooming and configurable double tap zooming

### ISSUE THREAD

**Issue by hyuuki** [tachiyomiorg/tachiyomi#228]
Please enable one finger zooming. Long press (lets say 3 secs) on tapping by one finger will trigger zooming (in or out), swiping up while keep tapping to zoom in, and swiping down to zoom out. It will be greatly useful when we only use one hand to hold the phone while reading and still enable us to zoom (using thumb, swipe up/down).

And also please add setting to let use choose the zoom factor when zooming by double tap (125%,150%, 200% or arbitrary value). Sometime I feel 2x zoom factor is too big and have to pinch to zoom manually to adjust appropriate zooming, but its kinda nagging to re-adjust in next pages (since there is no zoom lock).

**Comment by hyuuki** [comment]
Just found out that double click followed with swiping down can trigger zoom in and up to zoom out. So...this function is already exist, but I wish I can zoom in-out with single tap hold and wait.

**Comment by j2ghz** [comment]
#41 (similar)

**Comment by hyuuki** [comment]
Yeah I just read and its really similar, sorry before. But the distinction in my suggestion are, configurable zoom factor (in double tap) and also maybe zoom lock (lets say per chapter).

**Comment by Matth7878** [comment]
+1
To be able to configure default zoom would really be good. Right now zoom when double tapping is really too big and I always end up manually resizing. (Which is really annoying when there is a lot of double page)

**Comment by lucfig** [comment]
Would be great to have options to zoom until fit width or height when double tapping.

**Comment by scb261** [comment]
You can zoom with one finger: double tap without releasing the finger and then move it up/down. Maybe rename the issue to "Configurable double tap zooming"

**Comment by lucfig** [comment]
> You can zoom with one finger: double tap without releasing the finger and then move it up/down. Maybe rename the issue to "Configurable double tap zooming"

Yes, but it's not the same as it requires precision and is not centered, is related to the position of our finger.

I mean, the double tap to fit to width or height would be a much faster way to precisely zoom to a predictable location.
It's not a deal breaker not to have this, it's just a suggestion.

**Comment by arkon** [comment]
As originally pointed out 6 years ago, the Android-wide standard way of controlling zoom (double tap and drag) already offers more fine-grained control if needed.

I'm not sure it'd make sense to implement custom zooming behavior that deviates from what's normally expected in Android.
