### ISSUE TITLE
[Feature Request] Group all Multi-source extensions together for easier search

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#2280]
Currently Multi-source extensions are hard to identify, requesting them to be grouped together as we do for for extensions by their language.

**Comment by joseph619** [comment]
1.0 is far away and this is for 0.x only. Currently we have no way of knowing which extensions are multi-source without going to the website or asking on discord.

**Comment by Sparh4wk** [comment]
its the same with other features like cross device sync :P

**Comment by Bm12347** [comment]
This should also be closed as extensions are currently being splitted
