### ISSUE TITLE
[Feature Request] Reading List

### ISSUE THREAD

**Issue by marquesjpf** [tachiyomiorg/tachiyomi#2282]
I'd like the possibility of making some kind of reading list / playlist with individual issues / volumes.  
While I can make a new tab and put there a bunch of mangas, I cannot sort a reading order for individual volumes.

Some story arcs in comics jump from series to series, so having the means to organize a reading list would be helpful.

Example:
[Comic A Issue 1]
[Comic A Issue 2]
[Comic A Issue 3]
[Comic B Issue 1]
[Comic B Issue 2]
[Comic A Issue 4]
[Comic A Issue 5]
etc

**Comment by EfronC** [comment]
I strongly support this feature, it's very necessary, especially with comics.

**Comment by arkon** [comment]
Unlike to be implemented as comics are not the main focus of the app.

Workaround would be curating your own content via local source or something like Komga.
