### ISSUE TITLE
[Feature Requests] Github unofficial CDN support( jsdelivr.net )

### ISSUE THREAD

**Issue by zhihaofans** [tachiyomiorg/tachiyomi#2299]
**App version:** 0.8.4

**Android version:** 9.0

**Request:** Github unofficial CDN support( [jsdelivr.net](https://jsdelivr.net)  )

**Steps to reproduce (if applicable)**

- Use [`https://cdn.jsdelivr.net/gh`](https://cdn.jsdelivr.net/gh/inorichi/tachiyomi-extensions@repo/) instead of [`https://raw.githubusercontent.com/`](https://raw.githubusercontent.com/inorichi/tachiyomi-extensions/repo) 

**Other details:** This CDN has servers in China

**Comment by de-odex** [comment]
https://www.jsdelivr.com/ seems to be the actual site

**Comment by arkon** [comment]
Isn't GitHub accessible in China?
