### ISSUE TITLE
[Feature Request] Sort by Last Updated + Prioritize Downloaded on top

### ISSUE THREAD

**Issue by FabrizioMFE** [tachiyomiorg/tachiyomi#2321]
**App version:** Dev r1532 Build: Nov 3, 2019

**Android version:** Android 9 Pie

**Issue/Request:** I'd like a sorting option that puts at the top the last updated manga (already a thing) but prioritizes keeping at the top, manga with chapters downloaded.

Why? Well, in the screenshots below it can be seen that neither Last Updated nor Unread fix this problem. As the first one has manga with downloaded chapters lost below manga that have been more recently updated, and the latter, simply lists manga by how many unread chapters are there, regardless on whether the manga was updated recently or not.

I tried looking for a similar requested feature but couldn't find anything similar, I'm sorry if this has been asked/accepted/rejected before.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

Screenshots:
1. Sort by Last Updated
![Sort Last Updated](https://user-images.githubusercontent.com/13880444/68615982-dd2abc80-04a2-11ea-90c7-b6b6f5a7e3d4.png)

2. Sort by Unread
![Sort Unread](https://user-images.githubusercontent.com/13880444/68615998-e582f780-04a2-11ea-8fab-c2f2d9ee7160.png)

**Comment by metroid112** [comment]
Wouldn't having a Downloaded + Unread filter and a Last Updated sorting work for you? Then once you're done through the downloaded manga you can remove said filter and keep reading.

**Comment by MakiabelMFE** [comment]
I guess, though going back and forth in filters that often would get bothersome. I currently only use the Unread filter so that I don't see manga without any new chapters, using that is a fairly permanent way to not have too many manga in the list while keeping the ones I should look out for in view.

**Comment by arkon** [comment]
Sorting by date fetched is probably what you'd want for the sorting nowadays.
