### ISSUE TITLE
[Feature Request] "Continue Reading" button in library

### ISSUE THREAD

**Issue by kmlkmljkl** [tachiyomiorg/tachiyomi#2339]
**App version:** 0.8.4

**Android version:** 5.1.1

**Issue/Request:** a button to continue reading whatever you read last but haven't finished (in the chapters list it'll say page x). Could work like the already existing continue button in the chapters list, but for a more general use, and instead located on the library and recently read screens.

**Other details:** I don't always remember I haven't finished something yet, so this would be a nice feature.

**Comment by kmlkmljkl** [comment]
made this in case clarification was needed

![photo_2019-11-22_12-08-59](https://user-images.githubusercontent.com/24592780/69421968-bf6f1a00-0d22-11ea-8568-ec13e334ecc6.png)

**Comment by hXtreme** [comment]
Currently you can go to the recently read list and resume reading from there. Does that not work for you? If so it would be really helpful if you could explain why.

**Comment by kmlkmljkl** [comment]
Recently read doesn't specify if something is in progress or not, it just lists everything you've read, and the most recently read chapters.

Also, I dunno if this is easier or not, but perhaps an unread badge could be done instead? Like the download badge option, except it tells you if there are any partially read chapters.

![unread](https://user-images.githubusercontent.com/24592780/69429700-7031e500-0d34-11ea-8ce1-26009a60aaa3.png)

ok I'll stop now. I feel like I'm asking too much

**Comment by RuthlessRuler** [comment]
Please also change the icon from the play button to read button too. Its simple but will give nicer feel to the app.

**Comment by arkon** [comment]
Closing in favour of #3071
