### ISSUE TITLE
[Feature Request] Left screen border to also proceed to next page

### ISSUE THREAD

**Issue by Charuru** [tachiyomiorg/tachiyomi#2361]
### Why/User Benefit/User Problem
Currently right edge goes to the next page and left edge goes to the previous page. This makes it impossible to hold a tablet with the left hand on the left side and still read.

### What/Requirements
Both left and right edge taps should go to the next page, and a bottom tap or a slide can be used to change page back. This is fine because going to the next page is many times more common than going to a previous page.

I would do this myself if someone can point out where in the code the edge reader behaviors are.

**Comment by hXtreme** [comment]
Partly covered by the Kindlish Navigation scheme in #2152

**Comment by Charuru** [comment]
Looks interesting, do you have a release I could try?

**Comment by CarlosEsco** [comment]
Can't you just swipe?

**Comment by Charuru** [comment]
It's tiring and bad UX to have to do so every time.

**Comment by CarlosEsco** [comment]
Hold with your right hand? 😂

**Comment by Charuru** [comment]
Nope that hand is busy.

**Comment by hXtreme** [comment]
@Charuru unfortunately you'll have to compile it yourself plus there are a few minor things that I need to resolve (it's already usable though)
