### ISSUE TITLE
[Feature Request] Automatic synchronization after being online again

### ISSUE THREAD

**Issue by WasdeAsde** [tachiyomiorg/tachiyomi#2397]
**Problem:**
After reading a chapter within offline mode with activated synchronization, the read chapter will not be added/updated when coming online again. Therefore, the chapter requires a manual update.

**What should the feature do?**
After a chapter has been read offline, it should be synced automatically with the used synchronization platform (e.g. MyAnimeList, Kitsu) in the background or when opening the app online.

**Comment by Disposablegloves** [comment]
+1 upping this. I read offline then update and do other stuff when I'm online so this feature will be really useful to me.

I suggest keeping read logs offline then only syncing them whenever that manga/the library is updated, instead of whenever you finish reading.

**Comment by CarlosEsco** [comment]
@Disposablegloves  may i ask why you turn off wifi/mobile data when you read downloaded content?

**Comment by wopian** [comment]
+1 as I tend to read the most while on the London Underground these days.

**Comment by Disposablegloves** [comment]
Family wifi just doesn't reach my room and I tend to read before I sleep.

**Comment by pervertkirito** [comment]
Just like how Taiga(windows anime tracking app) works.
its will put on offline queue list if you don't have internet access. Once online, queued list will update to tracking service

**Comment by serjflint** [comment]
When traveling switching to an airplane mode saves a lot of battery. Revisiting all chapters to update tracking is a drag.

**Comment by CaptainHalflife** [comment]
I wish someone can implement this feature as when im on the go i read my downloaded content offline and its a pain to update them manually.

**Comment by arkon** [comment]
#1497
