### ISSUE TITLE
[Bug] "Page list is empty" when attempting to read a downloaded chapter

### ISSUE THREAD

**Issue by E66666666** [tachiyomiorg/tachiyomi#2408]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Download a bunch of chapters
2. Leave it to simmer for a (long) while
3. Attempt to read an old chapter

### Expected behavior
The chapter is readable.

### Actual behavior
The app throws the "Page list is empty" error message.

### Other details
The issue is "fixed" when the old chapters are deleted and re-downloaded.

At home it's not so much of an issue, but can be quite annoying when travelling.

**Comment by 0klux** [comment]
Can you actually give an detailed example of this problem? Like sources this happens, in what manga this happened, if they had the "Downloaded" text in the chapter list, etc.

I actually have some manga doenloaded that has been sitting for months, and they still work.

And just as an addendum, changes made to chapters by source, such as renaming, should just render the downloaded files unused, while making the changed chapter being recognized as new, so tachi should just be defaulting to online reading if that was the case, what makes your situation quite strange.

**Comment by E66666666** [comment]
I can't reproduce the exact occurrence any more now, as I fixed Yuru Camp (where it happened).

A similar issue I did find with One Punch Man, where a chapter does show with with the `DOWNLOADED` in the chapter list, but results in a "Page list is empty".

After checking `Internal Storage/Tachiyomi/downloads/MangaDex (EN)/One Punch-Man/`, I do see affected chapters having 0 files in their folders. (The folder does exist).

Something might've gone wrong with downloading, causing it to create the directory but not putting anything in there.

So I think the probable fix should be to unmark it as downloaded and defaulting to online, when an empty folder is found for a downloaded chapter.

**Comment by das22** [comment]
I get the same error for all the manga in my library from certain sources (e.g. Manga Rock).

**Comment by arkon** [comment]
@das22 Manga Rock is dead, migrate away from it.

**Comment by shubhrit-D** [comment]
Using kissmanga extension
While trying to download chapters Keep getting the error "Page list is empty"
KissManga version -  1.2.17
Tachiyomi Version - 0.8.5
Android 9

**Comment by CarlosEsco** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2496 @shubhrit-D

**Comment by arkon** [comment]
Doesn't seem relevant anymore.
