### ISSUE TITLE
[Bug] Cloud Directory "The Image could not be decoded" error

### ISSUE THREAD

**Issue by Muxoid** [tachiyomiorg/tachiyomi#2418]
### Device information
* Tachiyomi version: tachiyomi-r1571
* Android version: 9

## Steps to reproduce
1. First step: Set downloads directory to a cloud source
2. Second step: download chapters, upload to the cloud happens automatically
3. Third step: try to read downloaded chapters

### Expected behavior
Pages should download from the cloud source without error.

### Actual behavior
Got a blank page with the error "The image could not be decoded"

### Other details
Screenshot
![Screenshot_20200103-172756](https://user-images.githubusercontent.com/17557003/71750423-b65b8780-2e4e-11ea-8045-c73fc476dee4.png)

**Comment by arkon** [comment]
> Set downloads directory to a cloud source

What cloud source are you using? They typically don't just magically hook into the filesystem like you seem to be expecting.

**Comment by Muxoid** [comment]
Nextcloud, it seems to have hooked properly but I could be mistaken, it is an option when picking a custome directory.

**Comment by hXtreme** [comment]
@Muxoid I think that the cloud storage needs to be mounted to a folder for this to work seamlessly.

**Comment by Muxoid** [comment]
My goal was to save data on my devices by uploading the chapters to the cloud, by mounting the cloud service to a folder that would defeat the goal I was trying to achieve. If it is not possible, I will close this issue.

**Comment by hXtreme** [comment]
I think that you may be mistaken by what it means to mount a network storage service.

Say you have a storage device (could be anything from cloud to CD) once you mount it becomes available for everything else as if it was just a folder. Think of the Google drive or Dropbox folder on your PC, like that.

**Comment by Muxoid** [comment]
What I do not understand is that google drive does not show up as if it was a mounted device in Tachiyomi but Nextcloud does. In file explorer, for example, both are visible as if they are mounted devices Nextcloud and Google drive. The exception is that Nexcloud shows up as a mounted device on Tachiyomi and Google drive does not. 

The way I see it is that mounted on a device or a folder should not make a difference in the method the files are retrieved. I have Nextcloud mounted to a folder as well but for Tachiyomi to register the folders they must be synced to the device which takes space on the device similar to the PC cloud services work. The latest method works but needs to make a local copy on the device.

**Comment by arkon** [comment]
No idea how Nextcloud works, but network (or cloud) drives aren't really a standard thing in Android. Unless the system could seamlessly handle those, the app isn't going to.
