### ISSUE TITLE
[Feature Request] An option to set a reminder notification for specific manga that haven't been updated for a customizable amount of time

### ISSUE THREAD

**Issue by apav** [tachiyomiorg/tachiyomi#2419]
I have a large library of ongoing manga, which a use a mix of scanlator, MangaDex and aggregator sources for. Unfortunately I find scenarios where the scanlator pulls it off of MangaDex without my knowledge, the scanlator stops updating for whatever reason and another group starts posting chapters for it, and the aggregator isn't updating new chapters despite them being out happening all too frequently.  It is hard for me to remind myself to keep up to date with all the various scanlators' project statuses as well as checking other sites to see if the manga is updated. 

I'd like to have an option to be able to set a timer for each specific manga series of your choice that will notify you via push notification when it hasn't been updated in a certain customizable amount of time. For instance, I'd set Manga A to notify me when it hasn't been updated in 2 weeks, and I'd set manga B to notify me when it hasn't been updated in 1 month. That way I'll be reminded to check and migrate sources if need be, so I don't miss out on chapters that have been released for months like I sometimes do.

Is doing something like this possible? It would certainly be helpful. Thanks!

**Comment by arkon** [comment]
Maybe having the "Last updated" sort actually mean what people would expect would be a viable solution over this?

**Comment by apav** [comment]
> Maybe having the "Last updated" sort actually mean what people would expect would be a viable solution over this?

I certainly wouldn't be opposed to this, but I still prefer what I requested only because my library is so large. I have a lot of series that update irregularly from the scanlator, so it would be hard to pinpoint specific series that are likely to have a chapter released in a different source over those.

**Comment by hXtreme** [comment]
While I understand where you're coming from as I myself am someone with a really large library. I don't think that this is the kind of feature anyone would expect in a manga *reader*, this looks like a problem that should be solved by proper management. 

Ex: Say you write a python script to manage your library (manga, movies, ...)

**Comment by pervertkirito** [comment]
I actually want this kind of features.
few days ago I decided to update my Library because mangadex down and I don't have anything to read. Found out some manga from Manga Rock source didn't get an update for a months because it got licensed. Same with other dead source/extension.
If only there a way to know which source have been move etc from within the app

**Comment by arkon** [comment]
I think the date fetched sort could be used to address this.
