### ISSUE TITLE
[Bug] Not deleting chapters with _tmp suffix

### ISSUE THREAD

**Issue by milenamonteiro** [tachiyomiorg/tachiyomi#2429]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

By sorting the library by downloaded, some mangas with all the chapters deleted showed up.

I thought it was a sorting bug at first, but when I was looking at my files, I found that all these chapters folders had a _tmp sufix:

`\storage\Tachiyomi\downloads\source\manga\[Name of the chapter]_tmp`

Those can't be deleted by Tachiyomi, only manually.

It doesn't happen with all mangas, only with those that don't completely download or had any other problems downloading, due to connection errors mostly.

**Comment by arkon** [comment]
Somewhat related to #1501

**Comment by arkon** [comment]
Deleting from the library should delete everything within the manga folder nowadays.
