### ISSUE TITLE
[Bug] Title Names on Some rare cases do not display Properly

### ISSUE THREAD

**Issue by RuthlessRuler** [tachiyomiorg/tachiyomi#2492]
### Device information
* Tachiyomi version: 0.8.4-1633
* Android version: 9

## Steps to reproduce
1. Add Manga Like: Fights Break Sphere - Return of The Beasts from Mangadex.
2. Or add manga which has '/è may also result in this problem.
3. Removing/Re adding or refreshing Library Metdata doesn't fix the problem.

### Expected behavior
Dash is shown as -.

### Actual behavior
The dash is rather written as &ndash; due to improper parsing

### Other details
![Screenshot_20200112-232543](https://user-images.githubusercontent.com/20885012/72223295-0f20d380-3565-11ea-9314-167602d0242d.jpg)
![Screenshot_20200112-232509](https://user-images.githubusercontent.com/20885012/72223309-2b247500-3565-11ea-958e-6562819321fe.jpg)

A Case where it's properly displayed.
![Screenshot_20200112-232535](https://user-images.githubusercontent.com/20885012/72223312-311a5600-3565-11ea-96d2-c9975d5dee96.jpg)

**Comment by arkon** [comment]
I believe this is an issue with MangaDex's API.

**Comment by CarlosEsco** [comment]
Probably need to adjust the title cleaning logic

**Comment by RuthlessRuler** [comment]
> I believe this is an issue with MangaDex's API.

I think it's not API issue cause others are handled pretty well(As Show In SS)

Also, while we are at it can we please change the Play Button (icon) which is under Chapter of Manga to a Book Button(Icon) (Like In Moon Reader) as it makes more sense.

**Comment by arkon** [comment]
I can't find it right now but I'm pretty sure nulldev opened an issue at some point about it too. The API seems to sometimes return weird things, but yeah we could probably try to handle it better.

**Comment by SnakeDoc83** [comment]
Probably thinking of https://github.com/inorichi/tachiyomi-extensions/issues/1020 which was closed by https://github.com/inorichi/tachiyomi-extensions/pull/1537

**Comment by arkon** [comment]
You're right, my memory sucks :(

**Comment by arkon** [comment]
Doesn't seem relevant anymore.
