### ISSUE TITLE
[Feature Request] Anilist tracking score carousel 

### ISSUE THREAD

**Issue by metroid112** [tachiyomiorg/tachiyomi#2498]
Add the option to input a number on the Anilist tracking score carousel. It allows values from 0-100 but you have to manually scroll to select one, it's pretty tiring when my most common score is 50 lol

![](https://i.imgur.com/pMVIkrK.png)

**Comment by wopian** [comment]
I feel a slider and/or a number input would be better suited for all of the tracking sources than the current scrollable list to be honest.

**Comment by Flat** [comment]
The chapter carousel already does this. Can likely just "drag and drop" it to replace and check for valid values before making the API call.

**Comment by arkon** [comment]
It's a bit of a tough one since you can have the smiley system that Anilist uses too. We could potentially do the check first, but that doesn't seem very ideal to me either.

**Comment by wopian** [comment]
Are we not using Kitsu/AniList's user preferences for rating?

**Comment by arkon** [comment]
We are. I'm not sure what you're implying by that?
