### ISSUE TITLE
[Bug] Tracking not autoupdating if selected manga has seasons

### ISSUE THREAD

**Issue by cowly** [tachiyomiorg/tachiyomi#2502]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Find a manga with seasons, counting chapters for each season individually
2. Complete a season while having the tracker synced
3. Continue reading till you're on a new season. The tracker will now stop tracking.

### Expected behavior
This should happen.
The tracker should still track what chapter you're on, despite there being a new season.
### Actual behavior
This happened instead.
The tracker stops when a new season starts.
### Other details
Additional details and attachments.
No additional info needed. Please make a fix for this, it's infuriating having to manually update it after every chapter, and keeping track of what chapter you're on.

**Comment by MCAxiaz** [comment]
Please provide an example of a manga with seasons and which source you're reading it on.

**Comment by cowly** [comment]
I've seen lots that has the same issue, however the one I use the most would be Tower of God from kissmanga. I assume the tracking works by indentifying the chapter in the title, and setting it to that? This wouldn't work here, because the chapters gets reset for every season.

**Comment by arkon** [comment]
So if I go from "Season 1 Chapter 10" to "Season 2 Chapter 1", is that supposed to be tracked as chapter 11?

**Comment by cowly** [comment]
Yes, at least having an option to do that would be nice since that's how it's normally tracked and listed on sites such as anilist.

**Comment by cowly** [comment]
> So if I go from "Season 1 Chapter 10" to "Season 2 Chapter 1", is that supposed to be tracked as chapter 11?

Yes, at least having the option to track it like that would be nice, because that's how it's normally tracked on sites such as anilist.

**Comment by MCAxiaz** [comment]
Any sources besides kissmanga that do this?
https://mangaowl.com/single/47351/tower-of-god
https://www.webtoons.com/en/fantasy/tower-of-god/list?title_no=95&page=1
Also tried out "The Gamer" on both mangaowl and webtoons extensions in the app and they both provide proper chapter ordering.

Webtoons:
![Screenshot_1579054839](https://user-images.githubusercontent.com/24946428/72399284-95bae980-36fa-11ea-89c6-446751730b7a.png)

In the meantime if you just want to resolve this issue right now I suggest switching to webtoons (it's also the official legal publisher so there's no reason not to use it really).

I'm heavily leaning towards having the extension handle the logic.

**Comment by pervertkirito** [comment]
I have this problem with Comic Girl from mangadex
https://mangadex.org/title/17912/comic-girls/chapters/

**Comment by arkon** [comment]
Agreed that the app shouldn't try to handle this and the sources/extensions should try to normalize chapter numbers in a way that the app and trackers expect it.
