### ISSUE TITLE
[Feature Request] Ability to rename "Default" Category

### ISSUE THREAD

**Issue by RuthlessRuler** [tachiyomiorg/tachiyomi#2507]
### Why/User Benefit/User Problem
Well, it sucks to be unable to rename the default category.

### What/Requirements
When there are more than one Category, the ability to rename the default category should be added.

**Comment by keinezeit8** [comment]
A workaround that works right now, is putting all series into a different category, and name that. The default category vanishes then.

**Comment by RuthlessRuler** [comment]
> A workaround that works right now, is putting all series into a different category, and name that. The default category vanishes then.

Yeah it's an option but when we have 100+ Mangas, It's quite a work to select all as there is no way to select all in the App.(I think it's there in Other Like EH version tho.)

**Comment by CrepeTF** [comment]
There is now a select all in the library.

**Comment by CrepeTF** [comment]
Again, this should be closed due to the above ^

**Comment by arkon** [comment]
I could still see the usecase for having it name-able, or at least localized.
