### ISSUE TITLE
[Feature Request] Unread badge on catagories

### ISSUE THREAD

**Issue by CapnCranch** [tachiyomiorg/tachiyomi#2556]
### Why/User Benefit/User Problem
It would allow people to see how many unread chapters they have in custom catagories in their libraries without have to navigate into them to see

### What/Requirements
Show total amount of unread chapters in custom catagories next to the catagories name

**Comment by fhadiel** [comment]
👍 +1

**Comment by arkon** [comment]
Not quite the same thing, but filtering by unread + showing number of items already achieves this.
