### ISSUE TITLE
[Feature Request] ABI (Application Binary Interface) implementation

### ISSUE THREAD

**Issue by Doomsdayrs** [tachiyomiorg/tachiyomi#2623]
### Why/User Benefit/User Problem
Currently, Tachiyomi dev is a slow process, New features in the app take so long, that forks are made to just have the features before Tachiyomi implements it. 

An Tachiyomi ABI would allow applications to be developed to modify&use Tachiyomi's content. But all regulated by the user. This is to prevent an application from maliciously harvesting data from Tachiyomi without user consent. Examples with brief descriptions: 
- **Tachi-Sync** An Application to sync your library between devices using external sources. IE Google drive (so Tachiyomi doesn't have to touch proprietary code)
- **Tachi-Stat** Using an external API (may be proprietary) to read the users manga library, compare it to other users, and provide statistics. IE: `Clocks has read 50 more fantasy Mangas then you`, `Because you were reading Isekai mangas, Your friend Clocks recommends **Ishuzoku Reviewers**`
- **Tachi-Link** An application to link Mangas between different apis automatically
- **Shosetsu** Currently exists and developed by me. It is for Light Novel reading, I could theoretically use such an API to compare manga names to light novel names. So if a user has a manga of a ln in Tachiyomi, The info page of the LN would have a FAB to open Tachiyomi and read the manga too. Or if the user stumbles across a LN in catalogue with the same name to a Tachiyomi manga (that the user has in their tachi library) it provides a visible hint towards it. 

### What/Requirements
Now how this can be implemented is something of a choice. It can be done in many different ways. Mostly behind a library that would handle the interactions. The following is a rough interface idea about how this library may work. 
```kotlin
import eu.kanade.tachiyomi.data.database.models.MangaImpl
import eu.kanade.tachiyomi.extension.model.Extension
interface ABI {

    /**
     * @return [Boolean] of if tachiyomi is installed
    */
    fun isTachiyomiInstalled() : Boolean

    /**
     * @return [Array] of Mangas the user has in their library
     */
    fun getLibrary(): Array<MangaImpl>

    /**
     * @return [Array] of Extensions that may include methods to use their functionality
     */
    fun getExtensions(): Array<Extension>

    /**
     * Generic idea to set data. IE:
     * Input manga ID, and data to change
     */
    fun setData(vararg any: Any)

    /**
     * Register your application with tachiyomi as trusted. Tachiyomi may log actions other applications do so they can be reverted or monitored
     */
    fun register(vararg any: Any)
}
```
A theoretical idea of implementation would be sending Intents and receiving them, then processing them.

Registering would limit the interactions that can happen with Tachiyomi. To prevent a malicious developer from accessing information without consent. Settings in Tachiyomi (under advanced settings) can have a listing of applications registered, and their recent actions. May include an option to revert the action. 

Maybe a bit complicated, But something worth investing in to create a more vibrant community

**Comment by hXtreme** [comment]
Tachiyomi is essentially an end-user application so having a ABI might not make a lot of sense.

But, having a nice ABI to interact with Tachiyomi would be so awesome if you want to use it with some automation system.

Ex: Say you setup IIFT to ask Tachiyomi to update whenever you reach home/right before breaks.

You can also setup some Reddit bots that respond to certain terms (HunterxHunter) and then via automation tools ask Tachiyomi to check for updates for certain manga whenever that term is heavily discussed.

The possibility is endless

**Comment by arkon** [comment]
Could maybe have some Tasker hooks, but the proposal still sounds overkill for what the app is.
