### ISSUE TITLE
[Feature Request] Black Bar between pages

### ISSUE THREAD

**Issue by ElerTheMagnanimous** [tachiyomiorg/tachiyomi#2624]
### Why/User Benefit/User Problem
Because this will make reading more fluid, and looks like a little weird when i change the page and looks like this: 
![Screenshot_20200223-195638_Tachiyomi](https://user-images.githubusercontent.com/57354246/75127939-838c7d80-56a0-11ea-8aa8-ecc04dc68d45.jpg)

### What/Requirements
Just a black bar between the pages like mangarock reader ( with a on-off feature because some mangas have a 2 page picture)
![Screenshot_20200223-195548_Manga Rock](https://user-images.githubusercontent.com/57354246/75127902-5cce4700-56a0-11ea-814a-1edbe8dc2b04.jpg)

**Comment by pervertkirito** [comment]
Some Manga have 1 page split into 2 page, this will ruin the seamless reading experience. It would be great if have on and off button

**Comment by UWNG99** [comment]
Could we add in here an on/off button for the black screen that says which chapter was read and which one comes? Some one page manga like Wonder Cat Kyuu-chan become very annoying having one content page and one black page

**Comment by arkon** [comment]
@UWNG99 That's #1653, not this issue.

**Comment by UWNG99** [comment]
I'm sorry and thank you very much
