### ISSUE TITLE
[Bug] Transient icons make the transition feel janky

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#2632]
### Device information
* Tachiyomi version: r1768
* Android version: ?

## Steps to reproduce
1. Start from Library
2. Click on Updates

### Expected behavior
The screen should transition smoothly (say cross-fade or fade-out, fade-in or single "jump cut")

### Actual behavior
The active screen fades out, the new screen loads with a large icon and then the new screen is populated (feels like fade-in)

### Other details
[YouTube](https://youtu.be/DW_Jt2AQsak) video to kinda show the transient icon.

**Comment by arkon** [comment]
I think this was improved on at some point.
