### ISSUE TITLE
[Feature Request] Default Search Filter for individual sources

### ISSUE THREAD

**Issue by SCDevel** [tachiyomiorg/tachiyomi#2661]
### Why/User Benefit/User Problem
This would make searching for manga faster for sources with filters. it would make it so if you did not like a genre or wanted to change somthing it would always default to it instead of changing it everytime.

### What/Requirements
I think it should go in the extentions/details under the uninstall button. it would take the filter options from the source and you can set them to the default setting you want, so everytime you open the source to find manga it would use the defaults you have set.

Steps/Example:
1. take filter list from mangasee extention
2. put the filter options in 
 extentions/mangasee (details)
3. whenever opening mangasee (source) set the filter options to the options in the extentions/mangasee (details)

![Screenshot_20200304-140433_Tachiyomi](https://user-images.githubusercontent.com/32443069/75927371-16f04c00-5e21-11ea-84a8-aab387649bc1.jpg)

![Screenshot_20200304-140422_Tachiyomi](https://user-images.githubusercontent.com/32443069/75927398-21aae100-5e21-11ea-9bf2-dd224649389a.jpg)

**Comment by arkon** [comment]
#1484 would be more preferable.
