### ISSUE TITLE
[Bug] 3k+ Bookmarks, Library and Updates loading 2+ minutes

### ISSUE THREAD

**Issue by Axelrhode** [tachiyomiorg/tachiyomi#2676]
### Device information
* Tachiyomi version: 8.5
* Android version: 8.1

## Actions taken
1. Cleared app database
2. Cleared cookies
3. Cleared app cache

### Expected behavior
The app will load faster or at least, within 1 minute

### Actual behavior
App still won't load any faster. It still takes 2+ minutes to load My Library and Library Updates. If they do load, sometimes it takes a couple of minutes for the chapters to load.

**Comment by arkon** [comment]
Where are your manga stored?

**Comment by Axelrhode** [comment]
My mangas are stored on my SD Card

**Comment by arkon** [comment]
Are you using the default location or a custom one? Custom locations are known to be slower.

**Comment by Axelrhode** [comment]
I did use a recommended location, assuming it counts as default.

**Comment by 0xbad1d3a5** [comment]
Been having the same problem for awhile as well.

I wouldn't say it's taking minutes to load the main library but it definitely takes a good half minute before series start appearing on my Galaxy Tab S6. Also experiencing chapters sometimes taking more than a few seconds to show up sometimes.

**Comment by CarlosEsco** [comment]
If you move your library. To internal memory. Is the speed issue resolved?

**Comment by 0xbad1d3a5** [comment]
That... actually fixed it. Why is this the case? Shouldn't the initial load only read from a DB somewhere from Tachiyomi's app-specific folder (which should be in internal storage anyways)?

Is it actually also going through the sdcard and trying to look for all downloaded series/chapters as well? That seems like something that can be delayed for later, or even loaded on demand when you tap on a series.

**Comment by CarlosEsco** [comment]
Your image cache I believe is on the ad card also. So all your covers.  It's not looking for downloaded chapters at all unless it's enabled.

**Comment by 0xbad1d3a5** [comment]
Holy crap. I never knew how slow sdards were. Trying to copy over eu.kanade.tachiyomi/files/covers to the sdcard took over a good ten-something seconds (550 covers, ~170mb). Trying to delete that folder is somehow taking minutes (?! wtf).

Why not always have `CoverCache` use the internal storage instead (at least, I think this is where covers are getting loaded from a quick glance at the code)? I think for users with not a lot of series, the internal storage use is negligible, and for users with over a couple hundred bookmarks... I think they'd rather sacrifice a couple hundred megs of internal storage to be able to load series faster on boot if they chose to set the download location to the sdcard.

Either that or provide a toggle? I think generally having series being downloaded to the sdcard was fine, it was mostly the initial load that was super long (though, I did sometimes remember chapters taking awhile to load - maybe also related to sdcard performance)?

**Comment by arkon** [comment]
I think it makes sense to respect the user's choice of download location for the cover cache since they likely chose it due to space considerations.

SD card class generally doesn't matter since Android is horrible with it regardless of how fast the SD card itself is.
