### ISSUE TITLE
Mangalib tracker

### ISSUE THREAD

**Issue by topikana** [tachiyomiorg/tachiyomi#2693]
You can make tracking from the site mangalib.me, because they have the largest manga base, manhwa?
They have a pretty popular [website](https://www.similarweb.com/website/mangalib.me#overview).
https://a.pr-cy.ru/tools/traffic/?domain=mangalib.me

**Comment by arkon** [comment]
This would require a developer that understands Russian and willing to add/support the feature.

**Comment by arkon** [comment]
Seems dead.
