### ISSUE TITLE
[Bug] Incorrect scaling in webtoon view on high resolution screens

### ISSUE THREAD

**Issue by w1kl4s** [tachiyomiorg/tachiyomi#2736]
### Device information
* Tachiyomi version: dev, 0.8.5, 0.8.4
* Android version: 9

## Steps to reproduce
1. Use a high resolution device (in this case, tablet Lenovo Yoga Tab 3 Plus, 2560x1600 screen)
2. Load any series with horizontal resolution below 900 pixels
3. Enable Webtoon view

### Expected behavior
Pages get properly, seamlessly stitched   

### Actual behavior

Anything below 900 horizontal pixels presents is scaled incorrectly, and shows blank space between pages. Size of effect is linear with horizontal resolution "missing" from 900px point. 
Relevant screenshots:

![900x5000_vertical](https://user-images.githubusercontent.com/11419952/77006078-21066480-6962-11ea-8288-4763e9cf3be1.png)

![899x500_vertical](https://user-images.githubusercontent.com/11419952/77006082-21066480-6962-11ea-802e-03ed6b3c0600.png)

![880x5000_vertical](https://user-images.githubusercontent.com/11419952/77006084-219efb00-6962-11ea-9f55-cd7b61060ab7.png)

As ratio of horizontal screen resolution and image breaking point width looked awfully familiar, I also checked horizontal view, and it perfectly matches: 1440px width seems to be the minimum size for no gaps between pages ( 2560 / (16/9) ). 

Relevant screenshots:
![1420x5000_horizontal](https://user-images.githubusercontent.com/11419952/77006074-1f3ca100-6962-11ea-81fd-af3f83c6566c.png)

![1440x5000_horizontal](https://user-images.githubusercontent.com/11419952/77006076-206dce00-6962-11ea-9e48-fb8a64f6c076.png)

![1439x5000_horizontal](https://user-images.githubusercontent.com/11419952/77006086-22379180-6962-11ea-874d-fbe6ff30f2ae.png)

### Other details
I could not reproduce the issue on phone with smaller resolution screen.

**Comment by arkon** [comment]
What happens if you have even smaller images?

**Comment by w1kl4s** [comment]
Smaller width results in bigger gap between pages (800px): 
![800x5000](https://user-images.githubusercontent.com/11419952/77010946-18fef280-696b-11ea-993d-fbe17a49812f.png)


at 700px width they become so large that they just barely fit in the screen (you can see just a bit of both previous and next pages)
![700x5000](https://user-images.githubusercontent.com/11419952/77010944-18665c00-696b-11ea-9186-47ee53c01a40.png)

**Comment by arkon** [comment]
Could you take a video too, if possible? It seems as if the allocated page sizes are proportional to the image sizes, but the images themselves are too small and not being zoomed into by default.

**Comment by w1kl4s** [comment]
[Here](https://0x0.st/im5p.mp4) is a video of trying out various sized images.

**Comment by w1kl4s** [comment]
Github now allows for hosting mp4 files, reuploading (with slight reencode so it fits in 10MB) before 0x0 deletes the video which should happen soon(ish) according to their retention period rules.


https://user-images.githubusercontent.com/11419952/103039257-b1687a00-4570-11eb-9c54-df7f9fea026a.mp4

**Comment by Shwetabh007** [comment]
I updated my os today and had this problem but then I reverted back to the previous version and it is back to the normal

Android version - 11
Here are image of what happened before and how is now
![Screenshot_20210216-025911](https://user-images.githubusercontent.com/36888386/107997657-4768d000-7009-11eb-8323-a90260c3ee8c.png)




![Screenshot_20210216-032912](https://user-images.githubusercontent.com/36888386/107997721-7a12c880-7009-11eb-9b0d-8911a6ef944b.png)

**Comment by arkon** [comment]
@Shwetabh007 That's not quite the same issue, but it's come up before with custom ROMS that have incorrect configurations (e.g. https://github.com/tachiyomiorg/tachiyomi/issues/4131).

**Comment by Shwetabh007** [comment]
Maybe it's the same custom rom issue as today a test build was released so it may be because of that

**Comment by CrepeTF** [comment]
Someone "fixed" their issue by setting webtoon side-padding to 10%.
Could someone investigate this claim?

Source:
https://www.reddit.com/r/mangarockapp/comments/lkw9pt/_/gnmikwf

**Comment by w1kl4s** [comment]
I can confirm this works. 10% doesn't always do the job, depending on resolution - the lower it is, the bigger padding is required. It's kind of a workaround, but it leaves sides and you can't scroll just up or down, but to the sides - annoying when trying to read any webtoon.

**Comment by ahmubashshir** [comment]
It happens in anbox too.

**Comment by allquiet-hub** [comment]
As of version 0.10.11 the bug is still present.

**Comment by Byakko92** [comment]
With the last update (v0.12.2) it was solved on my tablet

**Comment by ahmubashshir** [comment]
Fixed in anbox too.
	Mubashshir

**Comment by arkon** [comment]
I'll close this if @w1kl4s confirms it's fine for them too. I didn't actually do anything for this though...

**Comment by ivaniskandar** [comment]
It's probably fixed by the consistent zoom changes included in my reader image view PR.

**Comment by w1kl4s** [comment]
Yes, i can confirm this is fixed - seems it was done between 3799 and 3812, so the fix should be somewhere [here](https://github.com/tachiyomiorg/tachiyomi/compare/7b3c18bb9...3eec20716), but i'm not versed enough in Kotlin to confirm. However, considering it does indeed include @ivaniskandar  commit (https://github.com/tachiyomiorg/tachiyomi/commit/746d35b52be76b1ba75be62cdc1192a769fb9661) , it's probably that one.

Thanks for the help, it took some time but it's all good now :)
