### ISSUE TITLE
[Feature Request] Sticky updates for sorting

### ISSUE THREAD

**Issue by cktab** [tachiyomiorg/tachiyomi#2740]
### Why/User Benefit/User Problem
For better user experience.
I have quite a lot of mangas and I like sorting by last read but in tachiyomi it's not great. I don't see new updates (there are too many updates to use `library updates`) with that option while with sort by updates - I'm searching for things I'm currently reading.  Checkbox `sticky updates` in piramid would be great - like in manga bird. It's some kind of double sorting.
### What/Requirements
To work like in `manga-bird`:
Sorted by (as an example) `last read` but new updates are always on top (until newest chapter will be read):

![Screenshot_20200319_181725](https://user-images.githubusercontent.com/62395865/77095301-feca2080-6a0d-11ea-8fc4-c66e2e2f7310.jpg)

Thank you!

**Comment by arkon** [comment]
So does it just prioritize updates first by the same sort (history)?

**Comment by CarlosEsco** [comment]
Wouldn't this just put newly added manga to the top of the list until you finally clicked into it?

**Comment by arkon** [comment]
I think this is basically the same as #6355
