### ISSUE TITLE
[Feature Request] Option to not automatically show new sources when updating extensions

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#2821]
### Why/User Benefit/User Problem
Now when I for example update my Madara extension and they add new sources (catalogues) to this. It will automatically be added to my list of sources which I don't want. This will for example increase the time it takes when I want to find a certain manga in a different source

### What/Requirements
I want to have a setting to disable automatically adding new catalogues when updating (not installing) a extension. This setting should by default just add them like now. Which needs to be set to disable manually.

**Comment by X9VoiD** [comment]
Are you using the latest dev build? The latest dev build already have the capability of filtering sources to exclude from the global search. Source tab have a filter button.

**Comment by MrAndre96** [comment]
> Are you using the latest dev build? The latest dev build already have the capability of filtering sources to exclude from the global search. Source tab have a filter button.

You can just disable sources I know that. But it is annoying to find out that after you updated a extension that there are suddenly new sources which you have to disable. It would be nice if those new sources which came with a extension update could be disabled by default

**Comment by Soitora** [comment]
Ah yes, so essentially a "Don't display newly added sources by default" button, reasonable request.

**Comment by CrepeTF** [comment]
This should be a non-problem because of multisource splitting
