### ISSUE TITLE
[Feature Request] grayscale filter (per-title or per chapter) 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#2822]
### Why/User Benefit/User Problem
(explain why this feature should be added)

Because some scanlation didn't properly do the grayscale filter. So black is very dark brown for example. 

### What/Requirements
(explain how this feature would behave)

Like toggling grayscale in Android developer menu or display setting.

**Comment by CarlosEsco** [comment]
It's not per manga but can't you just enable the color filter adjust to your liking to fix this?

**Comment by orangpelupa** [comment]
Technically you can do that, but it's really hard to get real black with those sliders.
