### ISSUE TITLE
[Feature Request] Make it clear which elements of a manga info screen are clickable and which are not

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#2865]
### Why/User Benefit/User Problem
At the moment, it is not obvious which elements of a manga card can be clicked on for functionality. There is no indication that clicking on the author or artist will search your catalog for them, or that the source will do the same. They appear exactly the same as non-clickable text like the chapter count.

### What/Requirements
The clickable text in the info screen should look clickable, perhaps like the genre chips.

**Comment by arkon** [comment]
Not really clear how we'd do it without it being super ugly. If you have mockups, feel free to open up another issue.
