### ISSUE TITLE
[Feature Request] Minor Request From A Right Handed User.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi#2901]
### Why/User Benefit/User Problem
After updating to the latest dev, I noticed a new look with regards to the positions of `add to library`, `share` and `webview` options. They've been moved down below the cover, on the left side. This may be a minor issue for right handed users/people with large screens.

### What/Requirements
My request is to move them to the right, or give us the option to have them on whichever side we choose, as currently this can be a _little_ annoying for right handed users (such as myself). I realise this is not really a gamebreaking issue as much as it is about a personal preference, but I'd appreciate it if this was addressed. Cheers.

**Comment by arkon** [comment]
The UI's changed since then and I like to think it's a _bit_ more reachable.
