### ISSUE TITLE
Dialog UI Inconsistencies

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#2907]
### Device information
* Tachiyomi version: dev r2081
* Android version: 8.1.0

### Other details
I saw two different dialog ui in the app. 

The first style (which is used more) has
- a dark background scrim
- items/choices don't have an active effect
- buttons have a blue active effect
![1st-x](https://user-images.githubusercontent.com/63973749/79699276-13296380-82c1-11ea-8035-ed6601a22b68.jpg)
![1st-y](https://user-images.githubusercontent.com/63973749/79699277-145a9080-82c1-11ea-970b-2031a53c7564.jpg)

The second style (which is used less) has
- a dark**er** background scrim
- items/choices have an active effect
- buttons have a gray active effect
![2nd-x](https://user-images.githubusercontent.com/63973749/79699271-0ad12880-82c1-11ea-85ed-879ed3fcaf51.jpg)
![2nd-y](https://user-images.githubusercontent.com/63973749/79699272-0c025580-82c1-11ea-9cdd-93faba723086.jpg)

Here are all the dialogs I saw:
First style:
- Misc > Extensions > [Any extension] > [Any option with a dialog]
- Misc > Settings > General > Start screen
- Misc > Settings > General > Language
- Misc > Settings > General > App theme
- Misc > Settings > General > Light theme variant
- Misc > Settings > General > Dark theme variant
- Misc > Settings > Library > Library update frequency
- Misc > Settings > Library > Library update restrictions
- Misc > Settings > Library > Categories to include in global update
- Misc > Settings > Library > Library update order
- Misc > Settings > Library > Default category
- Misc > Settings > Reader > Default viewer
- Misc > Settings > Reader > Scale type
- Misc > Settings > Reader > Zoom start position
- Misc > Settings > Reader > Rotation
- Misc > Settings > Reader > Background color
- Misc > Settings > Reader > Double tap animation speed
- Misc > Settings > Reader > Side padding
- Misc > Settings > Backup > Backup frequency
- Misc > Settings > Backup > Max automatic backups

Second style:
- [Any selected manga] > Move to categories
- Misc > Source Migration > [Any source] > [Any manga] > [New source] > Select data to include
- Misc > Settings > Library > Library manga per row
- Misc > Settings > Library > Edit categories > Add/Edit category
- Misc > Settings > Downloads > Download location
- Misc > Settings > Tracking > Log in to MyAnimeList/Kitsu
- Misc > Settings > Backup > Create Backup
- Misc > Settings > About > Version
- Misc > Settings > About > Build time 

- \+ [Any selected manga] > [Add tracking]
- \+ [Any selected manga] > [Any tracking provider] > Status / Chapters / Score

**Comment by arkon** [comment]
The first style is because they're all `DialogPreference`s, which use AndroidX's stuff.

Presumably the second style are all the legacy `MaterialDialog` stuff, which needs to be updated to the newer version.

**Comment by vengiare** [comment]
Looks like Dialog UI for tracking services also uses the old one.
