### ISSUE TITLE
[Feature Request] Covers and info page

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#2922]
I'm new to this app so I don't know if this is just hidden away in the options menu somewhere.

It would be nice if, when looking at the "library updates" page, it showed the covers as large images (like in the "my library section"). It would also be nice to be able to access the info page for a manga from the drop-down in the same place as the "download" and "mark as unread" (in "library updates").

**Comment by arkon** [comment]
1. It's the list since it can repeat manga for multiple chapters. I haven't thought of a better way to present that.
2. Tap the cover image.

**Comment by uuu26** [comment]
> 1. It's the list since it can repeat manga for multiple chapters. I haven't thought of a better way to present that.
> 2. Tap the cover image.

That's fair, what if, you used a larger image, then represented new chapters similarly to how you represent unread chapters, then clicking on that would bring to the chapter list or something.

**Comment by arkon** [comment]
Maybe if #2774 is implemented somehow.
