### ISSUE TITLE
[Feature Request] Dev build, --- sources --- total chapters amount info

### ISSUE THREAD

**Issue by xlixAxilx** [tachiyomiorg/tachiyomi#2928]
I've been trying to look through all the sources that I have for specific manga, and usually what ends up happening is that I tap on the cover, go to the chapters tab and see if that source is up to date with it's chapters.

Example: 
source__1 : 50 chapters
source__2 : 32 chapters
source__3 : 50 chapters
source__4 : 51 chapters
...

If out of 83 sources I get 10 results, then I have to go in each one to verify which one is the best option with the most chapters.

If you add a small number at the bottom of the cover mentioning how many chapters it has currently, this whole process would be avoided.

Thank you for taking the time to read. :)

**Comment by arkon** [comment]
This is unlikely to get added anytime soon, partially because it'd add a lot of network overhead due to it making an additional request for every manga.

**Comment by serjflint** [comment]
Also several sites have duplicates or wrong order and you still need to check it manually.
