### ISSUE TITLE
[Feature Request] Show Count/Number of Favourites (Manga/Webtoon)

### ISSUE THREAD

**Issue by shashank-p** [tachiyomiorg/tachiyomi#2937]
### Why/User Benefit/User Problem
It helps to keep count of favourite manga which might be helpful while migrating etc

### What/Requirements
In My Library (Total Count) and for each Category (category count) we can show count in Badges (or Text)

**Comment by shashank-p** [comment]
any update on this

**Comment by CarlosEsco** [comment]
you can just select all in the category and see the count right?

**Comment by shashank-p** [comment]
Yes we can but if there is many categories then we have manually slide and select each categories all chapters so isn't it better to display count as whole or per category.

**Comment by rafalohaki** [comment]
like this one
![image](https://user-images.githubusercontent.com/20607107/100211561-93c1d980-2f0c-11eb-8047-fd99eb04205a.png)
