### ISSUE TITLE
Option to hide already added manga when browsing sources

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#2941]
### Describe your suggested feature

Discovering manga could be way easier if manga you already have is hidden visually.

Option could be either inside a contextual menu, or a toggle in Settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by serjflint** [comment]
I think it will be great as a filter

**Comment by IIOMNIVERSEII** [comment]
Hope they add this soon.

**Comment by mm12** [comment]
See also https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11988 
from the extensions repo

**Comment by Pulungrp** [comment]
Hello, Is there an update for this feature?

**Comment by AntsyLich** [comment]
As you can see no

**Comment by Lukyzzz** [comment]
Wow, it was mentioned 8x in the last 3y, seems ppl are really looking forward to it.... right ? 👀👀👀
