### ISSUE TITLE
[Feature Request] Grouping Similar Manga/Webtoon chapter by name in Updates section

### ISSUE THREAD

**Issue by shashank-p** [tachiyomiorg/tachiyomi#2948]
### Why/User Benefit/User Problem
In current app state scrolling through updates takes time and some time some updated chapters get overlooked in updates.

### What/Requirements
We can group updated manga/webtoon by name with chapter. We can show either count of number of chapter updated or we can show range from which number to which number chapter got updated.

**Comment by arkon** [comment]
Duplicate of #2774
