### ISSUE TITLE
[Feature Request] Pop-up Cloudflare 

### ISSUE THREAD

**Issue by Slayer015** [tachiyomiorg/tachiyomi#2954]
### Why/User Benefit/User Problem

Could be great when a source needs cloudflare verification, a popup webview shows up with the verification. The benefits are:

- It could avoid users from opening a lot of issues in GitHub repository when they have errors with cloudflare and don't know about it.
- It's an easier and fast way to open a chapter when cloudflare appears.

I attach a screenshot of Anyme app that do this when we try to watch an anime chapter and cloudflare verification is needed.

### What/Requirements

Steps:
- A user open a manga chapter.
- If there are no cloudflare then the chapter open up as normally.
- If there are cloudflare then a similar window like the next appears to make the verification and the the chapter open up as normally.
![Screenshot_2020-04-24-16-43-17-893_com zunjae anyme](https://user-images.githubusercontent.com/43118963/80262307-a6acbc80-8652-11ea-98e6-3a30f63a5fbd.jpg)

In Anyme app case you have to press play button after verification, in this case it would be automatized. Sorry for the bad english.

**Comment by arkon** [comment]
Is this in consideration of what's already happening with Cloudflare in the app, where this process in the webview is already happening automatically in the background? Not sure if you're trying to address edge cases (like stricter Cloudflare checks), or if you're unaware that's already happening.

**Comment by Slayer015** [comment]
I didn't know that this is happening in the background. In my case I use LectorManga extension and I need sometimes to open the embed webview to pass the cloudflare. Actually the extension page needs a second verification, as you say, a stricter Cloudflare check, because after the first verifiation I need to open any chapter in the webview and do a captcha (this could be a captcha or the normal verification) to finally access to chapter. 

When KissManga was supported I also needed to open the webview (don't know if this last was an issue related with the page).

**Comment by jfcaraujo** [comment]
> When KissManga was supported I also needed to open the webview (don't know if this last was an issue related with the page).
From what I saw of kissmanga, the problem was that there a timeout happened before the cloud flare verification ended, but I think they changed the timeout time in version 0.9.0 of tachiyomi from 10 to 30 seconds

**Comment by arkon** [comment]
Closing this since the app does try to handle this automatically in the background. It then presents an option to the user to open in WebView if it fails.
