### ISSUE TITLE
[Feature Request] Searching manga when selected

### ISSUE THREAD

**Issue by Shulqo** [tachiyomiorg/tachiyomi#2983]
When you want to select a few specific mangas you cant search for it and you must scroll down looking for them.

It should be possible to search for books with several selected.

**Comment by arkon** [comment]
Is there an example app that behaves similarly? I can't think of anything that works like that.

**Comment by Shulqo** [comment]
I didn't saw this option anywhere but I think it would be good feature. It's that hard to make? I'm noob in creating apps for android.

**Comment by arkon** [comment]
The bigger issue would be the UX around it isn't very clear.

**Comment by Shulqo** [comment]
It's not like this would just change selecting manga and just people who want to can use it. Everywhere selected line cover searching bar. Maybe we could move it to make it possible to search. It could create problems because we would change our pool of mangas every time we would search other manga but maybe it could work with some variable. I don't think it would change the current way of selecting but could make life easier in some situations. 
![searching](https://user-images.githubusercontent.com/64423000/80654065-c2152e80-8a7b-11ea-9310-d060b58fcebf.png)

**Comment by samanta-widjaja** [comment]
It would have to make a big changes on the layout and the code

**Comment by arkon** [comment]
Still seems unintuitive.
