### ISSUE TITLE
[Feature Request] Option to limit registered taps to middle area

### ISSUE THREAD

**Issue by ckl33** [tachiyomiorg/tachiyomi#3032]
I just updated to the latest version and noticed that I'm getting a lot more instances where it's registering doubletap zooms and bringing up the single tap context menu while I'm scroll reading through webtoons.

On the previous versions I was on, tapping outside of the middle 1/3 area of the screen did not register as a valid input for those commands and the latest update seems to have changed that, unless it was somehow a glitch for me for the past year.

I think it would be useful to reintroduce this feature as an optional setting to reduce the number of mis-zooms while quickly scrolling.

**Comment by appledomino12** [comment]
I have had the exact same problem, the one tap context menu used to stay out of the way, it's now pretty frustrating for me due to a tremor in my hand. Would be nice to see this reinstated or made into an option.

**Comment by arkon** [comment]
The new navigation modes and overlay make it more obvious what areas are what, so closing this.
