### ISSUE TITLE
[Bug] Extension downloads stuck on pending 

### ISSUE THREAD

**Issue by SlurpelDur** [tachiyomiorg/tachiyomi#3035]
### Device information
* Tachiyomi version: 1.0.1 (tachiyomiJ2K)
* Android version: 9

### Source information
* Source name:  Any Source 
* Source extension version:  Any Version

## Steps to reproduce
1. First Step: Open tachiyomiJ2K and select whatever source you want to download/update.
2. Second Step: Press the install/update button.

### Expected behavior
The source should have updated or installed without any issues.

### Actual behavior
The source is stuck on pending and will not download or update.

### Other details 
I can still update and download sources through the extension list. 
                               ↓
https://tachiyomi.org/extensions/
---
I'm also on the tachiyomiJ2K app instead of the regular tachiyomi app.

**Comment by developedby** [comment]
I've been having the same problem. It started about a year ago, although I wouldn't know exactly when it started. I was using the stable version and the decided to switch to dev to see if it solved, but it was the same.  
After clicking install and waiting some time, eventually it changes from pending to retry, a built-in timeout, I imagine.

I have Android 8.1.

**Comment by SlurpelDur** [comment]
Yeah, I've had this issue for about 2-3 months.

**Comment by developedby** [comment]
After testing around, it seems to be some bad interaction with the adblocker for me.

The app requests raw.githubusercontent.com which the adblocker says it allowed. However, the app is only able to download the extension if adblocker is disabled, even though the request is not getting blocked. Not sure what is going wrong, adblocker doesn't cause any problem in other apps.

**Comment by guestname** [comment]
I'm having the same problem, with no sort of VPN or ad blocker.

**Comment by arkon** [comment]
Closing in favour of #4106
