### ISSUE TITLE
Bring download marks from j2k to official debug

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi#3039]
![Screenshot_2020-05-02-19-20-40-910_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/39062952/80869689-890ed100-8caa-11ea-8116-0f5bfa7949fc.jpg)
I think this is an optimal way to download chapters. Please bring this to debug version. Leave all in ui like it being now but add this icons to download chapters in chapter list. And mark chapters read/unread can be longtap

**Comment by Akazotik** [comment]
Sorry for duplicate

**Comment by arkon** [comment]
Added in Preview, to be released as part of next Stable release.

Please report any bugs from the Preview builds.
