### ISSUE TITLE
[Feature Request] Add Pinlock, Passcode Option.

### ISSUE THREAD

**Issue by Assassin143** [tachiyomiorg/tachiyomi#3040]
### Why/User Benefit/User Problem
It would be great for people who don't use or have bio-metric unlock.

### What/Requirements
Ask for pin or passcode to open or access app

**Comment by fux0r2009** [comment]
> ### Why/User Benefit/User Problem
> It would be great for people who don't use or have bio-metric unlock.
> 
> ### What/Requirements
> Ask for pin or passcode to open or access app

Yes a much needed feature! Hope we see it implemented in the future releases

**Comment by arkon** [comment]
This should work in the latest preview / next stable release.
