### ISSUE TITLE
Cancel option for "Downloading update" notification

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#3045]
### Describe your suggested feature

The 99% bug (#3044) happens occasionally and the only way to restart the download is by force-closing the app.

Having a cancel button would be helpful for this scenario.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Have you tried pressing "Check for updates" while that notification is there? That has always fixed the issue for me as it restarts the download

**Comment by vengiare** [comment]
I mean, I don't really have a problem with it myself but it will be an issue for everyone else who don't know other ways to restart the download.
