### ISSUE TITLE
[Bug] Can't scroll down to the bottom of the webtoon on the last chapter

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#3052]
### Device information
* Tachiyomi version: R2252
* Android version: Android 9
* Device: Oneplus 5T

## Steps to reproduce
1. Open the last chapter of a webtoon (so webtoon reader mode)
2. Zoom out
3. Now zoom in again
4. Scroll down untill you can't anymore
5. Now you can't see the last part of the chapter and you won't see 'There's no next chapter'

### Expected behavior
Seeing the last part of the chapter

### Actual behavior
Not seeing it untill you close and open the reader

**Comment by vipzzx** [comment]
Having the same issue 

https://github.com/Jays2Kings/tachiyomiJ2K/files/4632033/Screen_Recording_20200514-230606.zip

**Comment by bLu02th** [comment]
Same thing still hapening too:

App version: 0.10.9 (standard, f590378, 56)
Android version: 9 (SDK 28)
Android build ID: PKQ1.WW_Phone-16.2017.2011.105-20210108
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X01BD_2
Device model: ASUS_X01BDA
Device product name: WW_X01BD

**Comment by Bexa2** [comment]
App version: 0.10.9
Android version: 9 (Custom ROM Epic Rom Plus V4)
Device : Xiaomi Mi Mix 2

Happens to me too.

Go to a long strip manwha
Go to the last chapter
Go to the last page
See the "There's no next chapter" message
Scroll back up
Pinch and zoom out (the "There's no next chapter" message zooms out too?)
Double click and zoom in
Try to scroll to bottom.

[Video Here](https://www.dropbox.com/s/qd1r6mry1t2d0g2/tachiyomi_zoom_bug.mp4).

**Comment by Silvermane06** [comment]
Also having this issue, but it seems to be happening a lot more since the last iteration of stable 0.10.x and 0.11.1

**Comment by AwesomeQuest** [comment]
Also happening on:
App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BULA
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

**Comment by Yavos** [comment]
I can also confirm this happens on app version 0.13.1, Android 11 (Xiaomi Pad 5) and Android 10 (Xiaomi Redmi Note 9 Pro).

It seems this only happens when (accidentally) zooming out and then double tapping to get the correct zoom level again. When zooming in this does not happen and/or it (seemingly) resets the faulty behavior.

My guess is that zooming out saves the height of the now smaller picture (translating into less scroll down length) and it doesn't reset that on double tapping leading to tachiyomi thinking it can't scroll further down. If you on the other hand zoom in the height increases and a non-reset scroll length won't disturb anything (probably because some code of the next chapter part interfering).

Without double tap, the error won't occur for me.

**Comment by AgentX2006** [comment]
I can also confirm this happens on app version 0.14.2, Android 11 (Sky Devices Elite Octa) and Android 13 (Google Pixel 6a).

This is definitely triggered by zooming out (pinch zoom or the bug that causes a zoom out followed by rapid scrolling) and then using double tap to zoom back in. This also causes the page number to change when scrolling up (i.e. page 3 to page 2) at a point further up than it would normally occur (i.e. you have  to scroll further up before the page number changes). An example being it changing normally when a characters ankle is a the top of the screen but instead changing. when their shoulder is at the top of the screen.

There are no changes in behavior when zooming out and then pinch zooming in to any zoom level ( I tried zooming in to many ranging from full zoom in to near +/- the default).

There are no changes in behavior when zooming in then double tapping to zoom out.

This leads me to believe that there is a failure to update some scaling variable only when using double tap to zoom in.
