### ISSUE TITLE
Auto-update tracker status, start/end dates

### ISSUE THREAD

**Issue by swinericvuong** [tachiyomiorg/tachiyomi#3058]
### Why/User Benefit/User Problem
Quality of Life change. We already have auto-update on the chapters read, since in 0.9.0 the MAL start/finish date feature is added. It is expected for this feature to be automatic too.

### What/Requirements
Start date.
- User goes into tracking and adds MAL title.
- User starts ready a chapter and it has been marked as read
- If MAL start date exists then ignore.
- If MAL start date is empty, update with current time.

**Comment by Riztard** [comment]
maybe it should update too with current time if manga already tracked but the start date is empty
