### ISSUE TITLE
[Feature Request] "lock zoom" option in reader options

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#3059]
### Why/User Benefit/User Problem
Often times, when I tap to scroll / advance page, especially in webtoon view, the zoom is changes unintentionally. Having a way to lock the zoom (especially if it's something easily switchable) would help with usability.

In particular I'm using a bit tablet (with a 10.1" screen), this may or may not be as useful in smaller devices.

### What/Requirements
- A way to lock for the zoom so that accidental double-tapping doesn't zoom
- A toggle for this close at hand in the reader mode (the reader options accesible from the gear icon on the top-right would be a good place to put the toggle for the zoom lock)

Alternatively, a switch for the double-tapping zooming action could solve my original issue, but some users may want to keep that functionality when not having the zoom lock enabled, or may want to have a zoom lock for different reasons.

**Comment by Jaykoerner** [comment]
Agreed, as a tablet user zoom is unnecessary and causes more frustration then help, but it definitely has to exist for phones

**Comment by stevenyomi** [comment]
#4145 and #9384
