### ISSUE TITLE
[Feature Request] background download of extension updates, notification of available extension updates

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#3061]
### Why/User Benefit/User Problem
As of now, the user has to manually update the extensions and the process is basically:
1. tap on "update extension"
2. wait for the extension to download (this can take a while depending on the connection)
3. the device offers the security confirmation, the user taps to install

The user experience here can be optimized a bit within the limitations the app is bound to (for example, step 3 is unavoidable). The stated goal here is to minimize both user actions and user wait required for the process of updating the extensions, and we are assuming that nobody actively  wants to stay in an older version of an extension.

### What/Requirements
* Extension updates should downloaded automatically in the background
* The user should be notified that there are extension updates available (I suppose notify once the downloads are already done)
* #2665 suggests a way to make the install step better for when multiple extensions updates are available (basically queue the install of all upgradeable extensions with a single tap), which could work well in tandem with background downloads of extension updates.
* all of this should ideally have a toggle switch in the configuration

**Comment by plW0lf** [comment]
Fully agreed. I have 100+ outdated extensions right now and "queue install all" button would be really handy.

**Comment by arkon** [comment]
"Update All" button in preview builds immediately queues downloads/installations appropriately.
