### ISSUE TITLE
Change gap size between pages for "Continuous Vertical" viewer

### ISSUE THREAD

**Issue by heybbygurl** [tachiyomiorg/tachiyomi#3072]
### Why/User Benefit/User Problem
Personally I prefer the gap size to be smaller similar to what mangadex has for their long strip viewer but others may prefer how it is right now or slightly different so a good solution is to be able to change it according to preference.

### What/Requirements
Have a setting under "Reader" called "Gap size for continuous vertical" and be able to adjust by pixel thickness.

**Comment by cyyeong** [comment]
> ### Why/User Benefit/User Problem
> Personally I prefer the gap size to be smaller similar to what mangadex has for their long strip viewer but others may prefer how it is right now or slightly different so a good solution is to be able to change it according to preference.
> 
> ### What/Requirements
> Have a setting under "Reader" called "Gap size for continuous vertical" and be able to adjust by pixel thickness.


Agree! Some manga page have longer width on all pages. Continuous vertical by joining the pages would be nice, similarly what has been done in MangaRock app in the past.

Really hard to read these manga now. Example screenshots:
![Screenshot_20200510-230721_Tachiyomi](https://user-images.githubusercontent.com/19303279/81502887-56508280-9313-11ea-8bf6-7b94d140f640.jpg)
 ![Screenshot_20200510-230743_Tachiyomi](https://user-images.githubusercontent.com/19303279/81502906-6ff1ca00-9313-11ea-85bf-aedcfe523c1f.jpg)

**Comment by CarlosEsco** [comment]
I think your phone is bugged based off the screen shots

**Comment by CarlosEsco** [comment]
Here's what it should look like

https://i.imgur.com/fiiD2Bk.jpg

**Comment by wabash1** [comment]
That would be nice, I noticed on how to fight there's a huge gap on continuous vertical and after changing backgrounds I noticed it isn't part of the scans

**Comment by wabash1** [comment]
![Screenshot_2020-08-30-21-43-57](https://user-images.githubusercontent.com/3643969/91675540-c2493780-eb0a-11ea-9eb3-aa86295ce963.png)

**Comment by arkon** [comment]
You should be using Webtoon for that.

**Comment by wabash1** [comment]
> You should be using Webtoon for that.

My apologies, Thank you that did it!

**Comment by arkon** [comment]
No plans to do this.
