### ISSUE TITLE
[Feature Request] Start/end date for trackers

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#3106]
### Why/User Benefit/User Problem
- Feature parity across trackers

### What/Requirements
- Start/end date functionality for Kitsu, Bangumi, and Shikimori (if possible)

**Comment by arkon** [comment]
No longer relevant since it'll have to be removed for MAL anyway (#4140).

**Comment by paulo27ms** [comment]
Are you sure it doesn't? This seems like a really odd thing to not support and other apps I use that use the API support this functionality. Unless you're using a different type of API from them.
https://github.com/erengy/taiga is an example.

**Comment by arkon** [comment]
The Taiga code does seem to suggest it does: https://github.com/erengy/taiga/blob/develop/src/sync/myanimelist.cpp#L776-L779

The official docs, perhaps unsurprisingly at this point, does not: https://myanimelist.net/apiconfig/references/api/v2#operation/manga_manga_id_my_list_status_put

I'll reopen this and look into adding it back.

**Comment by arkon** [comment]
Okay now the issue is that MAL's API has a really non-standard way of requesting response fields: https://myanimelist.net/forum/?topicid=1850699, i.e. something like `"$baseApiUrl/manga/$id/my_list_status{start_date,finish_date}"`

However, I can't see any way to avoid OkHttp from not encoding the `{` and `}`, to which MAL just responds with a 404 instead of handling the encoded URL like a sane API would.

I'll have to toss this onto the back burner since the API _technically_ supports it, but there's no great way of doing it from the app right now.

**Comment by arkon** [comment]
Closing this since it's at least been implemented for the main English trackers (MAL, AniList, Kitsu).
