### ISSUE TITLE
[Feature Request] Scroll with background when zoomed out

### ISSUE THREAD

**Issue by SakuraYagami** [tachiyomiorg/tachiyomi#3127]
### Why/User Benefit/User Problem
When using a large phone or tablet zooming out is sometimes needed since using set-width on comic strip formats make them incredibly large and 1 panel could take up the whole screen. I use zoom out to help with the size but the issue is that the width space is filled with the 'background' and is not scrollable. This means that I have to stretch my fingers over every time I want to scroll since I need to scroll with the image at the centre and not the borders on the side.

### What/Requirements
Make the background scrollable

**Comment by IsekaiLife** [comment]
If its open does that mean this issue is still being worked on? If so is any progress being made or is it kind of a problem that cant be fix easily?
