### ISSUE TITLE
Customizable restore

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#3136]
### Describe your suggested feature

So that people can customize what to restore without having to make a custom backup. (say, restoring using auto backup.)

Basically this image below, but for the restore dialog. 

![Screenshot_Tachiyomi_20200510-090916~01](https://user-images.githubusercontent.com/63973749/81488672-7e51ce80-929e-11ea-8482-293e6367e95a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
This is especially true now that they have introduced backup of application settings, which breaks the work of forks.

**Comment by e-shl** [comment]
I would even like a copy of the settings to be kept separately. Maybe this is too much.
