### ISSUE TITLE
[Bug] Weird fastscroll behaviour when top (and bottom) navbar is visible

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#3143]
### Device information
* Tachiyomi version: r2289
* Android version: 8.1.0

## Steps to reproduce
1. Use fast scroll (library, browse, chapter list) when top (and bottom) bar is visible
2. Scroll to bottom

### Expected behavior
Well, scrolls to the bottom of the list

### Actual behavior
https://cdn.discordapp.com/attachments/694092459839455243/709020665172328499/ScreenRecord_20200510_203204_trim.mp4

### Other details
Suggested fix may be to hide top and bottom bars whenever you use the fast scroll. Dunno.

**Comment by arkon** [comment]
Not going to be fixed.
