### ISSUE TITLE
[Feature Request] Add option "Scale type : Custom"

### ISSUE THREAD

**Issue by eXmendiC** [tachiyomiorg/tachiyomi#3146]
### User Problem
My tablet has a pretty big display and it's too big for enjoying manga full screen.
Solving that problem is only possible when I pick "Original Resolution" and downscale the pictures on my own. 

- It costs time which might be avoidable
- Auto downloading new chapters and reading them ASAP isn't possible
- JPEG -> JPEG reduces quality

### Requirements
An option to set up a custom area where you want the content displayed.
It should be possible resizing (height/weight) that area to one's liking.
Some might prefer that area center/top/bottom or center/left/right.
That option is for all manga and pages -> "Scale type : Custom".

### Example
![example](https://user-images.githubusercontent.com/26603887/81503104-50d24880-92d1-11ea-9593-1a90f20fd52d.jpg)

**Comment by CarlosEsco** [comment]
What source are using with resolutions?  99% or sources don't offer anything so it's the quality of the website

**Comment by eXmendiC** [comment]
Most of the legal E-Books have a pretty high resolution. Higher than the resolution of my tablet.
For example: Yuri is My Job has  2587x3684.

**Comment by stevenyomi** [comment]
Sounds like too niche. Probably #3348 + #5959 or request margin feature.
