### ISSUE TITLE
[Feature Request] Automatic clear cookies

### ISSUE THREAD

**Issue by joootdooot** [tachiyomiorg/tachiyomi#3169]
### Why/User Benefit/User Problem
Sources like readcomiconline throw up a "failed to bypass cloudflare" error after some time of continuous reading. This can be solved by clearing cookies, albeit manually.

### What/Requirements
The bypass cloudflare feature would attempt to clear cookies if a setting is enabled. The setting exists to preserve cookies for those who log in.

**Comment by arkon** [comment]
This would mess up any sort of sessions (especially for sources that require logging in via WebView), so I'll leave it as a manual workflow.
