### ISSUE TITLE
[Bug] Chapters won't load

### ISSUE THREAD

**Issue by tr1xy** [tachiyomiorg/tachiyomi#3187]
---

### Device information
* Tachiyomi version: 0.9.2
* Android version: Android 8.0.0 😪
* Device: Honor 7C

## Steps to reproduce
1. READ THE MANGA
2. Read the manga :') 

### Expected behavior
Sm00thness 

### Actual behavior
After some time, chapters just won't load (forever loading), I need to Kill the app in the settings and chapter loads normally after that

### Other details
Mangakakalot Unoriginal

**Comment by tr1xy** [comment]
Still persistent.

**Comment by arkon** [comment]
Please provide useful reproduction steps. After how long? Is it consistent?

**Comment by tr1xy** [comment]
It just randomly stops loading, no exact time...

Like sometimes it doesn't happen and sometimes it happens three times in a row...
