### ISSUE TITLE
[Bug] App freezes if clicked on a Library title while restoring backup

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#3189]
### Device information
* Tachiyomi version: r2331
* Android version: 10
* Device: Galaxy S10+

## Steps to reproduce
1. On a fresh install of Preview, restore backup.
2. Click on any manga in Library while backup is being restored.  

### Expected behavior
Manga info should open.

### Actual behavior
App freezes completely.

### Other details
Only tested for fresh preview install.

**Comment by arkon** [comment]
This is because of the background restores locking the database when it's inserting something.

I could just restrict browsing the library entirely as a workaround, or let people live with the brief lag during the restore.

**Comment by joseph619** [comment]
I am torn between the two choice, as neither is particularly pleasant. However the lag definitely looks worse for the app, perhaps restricting would be the better choice.

**Comment by arkon** [comment]
I don't think we lock anymore post-SQLDelight migration anyway.
