### ISSUE TITLE
[Feature Request] Add timer to lock screen

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi#3251]
### Why/User Benefit/User Problem
I (and probably some other users) want to have different time before locking screen in some apps (like readers for books or for manga). The option to lock or not isn't enough, because sometimes I leave phone and forget to lock. Also I often read before sleeping and find unlocked screen in morning. It's no good because of battery power and accidental clicks.

### What/Requirements
Add setting to increase awake time like in Moon+ Reader (screenshot).
![Screenshot_2020-05-30-17-57-29](https://user-images.githubusercontent.com/65343233/83332499-2ce89e00-a2a4-11ea-87a1-c25656ad4f09.png)

### Usefull but not required
- Some inducator to show that the timer is up (but there is still system timer left), so users could tap the screen to prevent lock when they're still reading (I'm not always fast enough to react to system fading).
- Ability to disable the timer for chosen mangas/categories. Usefull to disable it for webtoons (pages are read pretty fast). Could also be different timers for each manga/category, but it's probably overkill.

**Comment by theAkito** [comment]
@arkon I might have a go at this.
