### ISSUE TITLE
[Bug] Long tap dialog shows even if disabled

### ISSUE THREAD

**Issue by Mymiano** [tachiyomiorg/tachiyomi#3263]
### Device information
* Tachiyomi version: 0.9.2-2373
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

### Steps to reproduce
1. Disable long tap dialog
2. Tap again to show title bar/navigation bar
3. Long tap while bars were shown

### Expected behavior
Do not show long tap dialog

### Actual behavior
The dialog will show even if you disable it.
It works while the navbar not shown but not when the navbar is present

**Comment by lmj0011** [comment]
Tachiyomi version: [v0.9.2](https://github.com/inorichi/tachiyomi/tree/v0.9.2)
Android version: 10 (SDK 29)
Device: PixeL XL

Was able to reproduce. Is this expected behavior?

**Comment by arkon** [comment]
This is the intended behaviour, although the option is poorly worded. I've also considered moving sheet contents somewhere else but not sure where.
