### ISSUE TITLE
[Feature Request] Disable update notification/download for read chapters

### ISSUE THREAD

**Issue by Schadows** [tachiyomiorg/tachiyomi#3271]
Some sources re-upload/refresh chapters (or whole volumes sometimes) which is obviously reflected in the app. This "false positive" are not always welcome, more so when you configure the app to automatically download new chapters.

Would it be possible to prevent any notification (and automatic download) for any chapter update which has already been marked as read in the app?

Maybe through an option in the settings?

**Comment by serjflint** [comment]
Like MangaPlus

**Comment by arkon** [comment]
The app doesn't really recognize chapters as "replaced", so the current system is simpler to keep.
