### ISSUE TITLE
"Reset reader settings for individual manga" option in Settings > Advanced

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#3277]

**Comment by arkon** [comment]
There's only one setting, which is the viewer mode. I don't really think that warrants a global reset button?

**Comment by vengiare** [comment]
What I meant was "Reading mode (For this series)"

**Comment by vengiare** [comment]
edited reply btw cause i forgot a detail

**Comment by vengiare** [comment]
Bumping this as "For this series" has multiple options now.
