### ISSUE TITLE
[Bug] Removing manga from library reverts while global update is ongoing

### ISSUE THREAD

**Issue by Mymiano** [tachiyomiorg/tachiyomi#3281]
### Device information
* Tachiyomi version: 0.9.2-2373
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Tap global update in library
2. Select one manga and remove it from library while update is ongoing

### Expected behavior
Removed from library

### Actual behavior
After removing from library, wait for a moment and it will indicate again `In library`. When you tap again it will display a dialog of categories (do not select anything, just ignore). When you go back to the library, the manga that you remove was there and when you select it again, it was `In library`.

**Comment by lmj0011** [comment]
Tachiyomi version: [v0.9.2](https://github.com/inorichi/tachiyomi/tree/v0.9.2)
Android version: 10 (SDK 29)
Device: PixeL XL

Attempted to reproduce with 12 manga in my library, was unsuccessful. 

@Mymiano How many manga did you have in your library when this happen?

**Comment by arkon** [comment]
I've reproduced this. We probably need to just add a check that the manga is still favorited before doing or applying updates on the manga instance, but haven't looked into a good way of doing it.

**Comment by lmj0011** [comment]
@arkon 

Under what conditions would I be able to reproduce this, I assume it's when you have a large amount of manga in the library to be updated. Looking for a ballpark number.

**Comment by arkon** [comment]
Any number, you just need to unfavourite something between the time you initiate an update and it actually being updated. I don't remember if it's triggered if it's chapters updated or only if the manga info is updated.

**Comment by lmj0011** [comment]
>I don't remember if it's triggered if it's chapters updated or only if the manga info is updated.

I upped my manga count to 36 and tried reproducing a few more times, for both of those cases, on the latest build r2474 and couldn't trigger the bug.

**Comment by arkon** [comment]
Did they actually have updates?

**Comment by lmj0011** [comment]
>Did they actually have updates?

Yes

**Comment by Mymiano** [comment]
@lmj0011 
Incase of WIP

still in `r2493` 
I have 200+ manga in my library
Unfavorited 1~2 manga while global update is ongoing and it will be favorited again when manga passes update list
