### ISSUE TITLE
[Feature Request] crop borders when the background is non-white 

### ISSUE THREAD

**Issue by igalic** [tachiyomiorg/tachiyomi#3290]
### Why/User Benefit/User Problem

in #219 detecting borders was introduced, by detecting where the white ends and the first ink starts 

however, a lot of manga use black for dream sequences, or scenes that happen in the past / a flashback

that means that the zoom isn't quite the same as a page before

### What/Requirements

probably the same as #219 but for black background

**Comment by arkon** [comment]
Would require a change in https://github.com/tachiyomiorg/tachimage

**Comment by igalic** [comment]
since opening this issue, I've been thinking more about the impact this could have on the mood of a page

i can imagine how this could cut into a vast night sky, and make something that previously seemed endless very, very tiny

disclaimer: while looking at the algorithm from the original PR implementing cropping, i didn't actually fully understand how it does that, so perhaps my imagination here is very much off-base

**Comment by inorichi** [comment]
Already implemented in the new preview version.
