### ISSUE TITLE
[Feature Request] Have the next chapter automatically download while reading. 

### ISSUE THREAD

**Issue by lmj0011** [tachiyomiorg/tachiyomi#3295]
### Why/User Benefit/User Problem
The option to have the next chapter **download** while reading will improve the manga reading experience in Tachiyomi (particularly for readers normally on a Wi-Fi connection). From my experience, I encounter a couple of inconveniences when the [HttpPageLoader](https://github.com/inorichi/tachiyomi/blob/ec9d592cf1c120500e11cb39f92c485aa3d66e4e/app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/HttpPageLoader.kt) is used to preload pages in a chapter:

1. If the chapter has a lot of pages, lengthy loading times and timeouts are likely to occur.
2. resuming a chapter after opening the app causes the loader to fetch pages again, causing a few seconds of delay before the page shows.

Other benefits I see this feature having is alleviating the reader from having to remember to download X amount of chapters before continuing with their favorite manga and also decreasing the chance a manga host throttling or breaking client connection, causing those dreaded download errors, because of bulk chapter downloading.

### What/Requirements

Add a new Downloads option to enable this feature (off by default), see "Steady Downloads":

<img src="https://user-images.githubusercontent.com/9396189/84071745-d6f6b300-a993-11ea-92ad-f26c12bfa8a9.png" height="500">

Then whenever you start a manga chapter, instead of the usual preload, the next chapter is now downloaded:

<img src="https://user-images.githubusercontent.com/9396189/84072556-fb06c400-a994-11ea-9062-61f383301766.png" height="500"> <img src="https://user-images.githubusercontent.com/9396189/84072908-897b4580-a995-11ea-95ee-0b3045394581.png" height="500"> <img src="https://user-images.githubusercontent.com/9396189/84072566-fe9a4b00-a994-11ea-8da0-9cd4acf8efa0.png" height="500"> <img src="https://user-images.githubusercontent.com/9396189/84072574-00fca500-a995-11ea-97d3-20d0cef86953.png" height="500">

**Comment by DuccinatorAlpha** [comment]
iirc just having the next chapter downloaded had some issues (I remember talking on discord about it). Some of em were mentioned here: https://github.com/Jays2Kings/tachiyomiJ2K/issues/80

**Comment by lmj0011** [comment]
>iirc just having the next chapter downloaded had some issues (I remember talking on discord about it).

what were the issues exactly? looking back at those previous issues, it doesn't appear that one dev saw a reason to implement it

**Comment by joseph619** [comment]
Visit the TachiyomiAZ channel on Discord, jobobby04 (Syer10) did some testing and found some issues with this commit that should be addressed

https://discordapp.com/channels/349436576037732353/566585518171881493/719720613459132427

**Comment by lmj0011** [comment]
> My first impression of the feature is that it technically works as advertised
> I encountered some weirdness though
> - While the next chapter hasn't finished downloading, you cannot go to the next chapter through the reader

I'm guessing slow internet or a large next chapter is the cause of this, either way it would be worth seeing if it's possible to start off with the HttpPageLoader and switching to DownloadPageLoader once the whole chapter has finished downloading


> - The download next chapter fired when on data while the download only on wifi was enabled, making the next chapter fail download and load(because of the above issue)

Would it be reasonable to make this an "only on wifi" feature?

@joseph619

**Comment by jobobby04** [comment]
I would have it check if the only download on wifi setting is enabled, and the not add it to the download queue if on data

**Comment by lmj0011** [comment]
Made these changes:

https://github.com/inorichi/tachiyomi/pull/3296/commits/ec91320e6413e6f4f11fc87ceb4adaf7639a619f, https://github.com/inorichi/tachiyomi/pull/3296/commits/22327d088b5978dd2a27470d0cbd003242b5005d

in summary, when this feature is enabled:
- it will not try to download the next chapter over a [metered network](https://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered())
- it begins next chapter download at the beginning of the current chapter, not towards the end.
