### ISSUE TITLE
[Feature Request] Update LATEST manga by Gallery

### ISSUE THREAD

**Issue by Schezuk** [tachiyomiorg/tachiyomi#3309]
Now we have 2 modes to update manga.
1. Update your whole library, with some filters available like which category not to update, or optional update order, etc.
2. Drag and update the particular category selected in your library.

### Why/User Benefit/User Problem
While both ARE useful and working most of times, if you have favored a big deal of manga into the library (above 1 thousand as a example), updating the whole library (where most of the manga don't have new chapters to subscribe ) will be time-consuming, and a big burden to the source server. (If you hold a gallery online, you won't like people snapshot your whole metadata server on a daily basis.)

Mode 2 won't solve it, either. They are not arranged in the update-time order anyway.

### What/Requirements
1. Open column `Galleries`.
2. Enter one of the galleries either through `LATEST` or `BROWSE`.
3. Scroll down and load enough items (say 100) of latest or hottest (according to your filter) manga.
4. [Feature Request] Click `Update your favorites` bottom. 
5. Only the items ALREADY added in your gallery (they are displayed darker btw) in all those items loaded should be put into the `Update Queue`.
6. Update the Queue, which contains all you need to update.

**Comment by CarlosEsco** [comment]
I assume by gallery you mean source.

And what this issue request is asking for is.  Update library manga by source

**Comment by Schezuk** [comment]
> I assume by gallery you mean source.
> 
> And what this issue request is asking for is. Update library manga by source

Exactly. To update from the most recent part of the source.

**Comment by serjflint** [comment]
You can have a special category for updates

**Comment by Schezuk** [comment]
> You can have a special category for updates
> 
> Edit: Like me

Well, in my case, I have archived about 30,000 manga in about 50 categories which I can't tell when and where there will be new chapters to come, and feel guilty updating them all. But it is quite a pain to update each of them in the LATEST view of the source MANUALLY.

**Comment by joseph619** [comment]
If you're using TachiyomiEh, it's no longer maintained. I suggest you move your backup to another fork

https://tachiyomi.org/forks/

**Comment by Schezuk** [comment]
> If you're using TachiyomiEh, it's no longer maintained. I suggest you move your backup to another fork
> 
> https://tachiyomi.org/forks/

I moved to TachiyomiAZ last month, however I can't find out where to post issues.

**Comment by joseph619** [comment]
TachiyomiAZ doesn't have issues section on Github, you have to talk to the dev personally on Tachiyomi discord

**Comment by arkon** [comment]
Closing in favour of #4060
