### ISSUE TITLE
[Bug] Scrolls comic instead of using device nav bar buttons.

### ISSUE THREAD

**Issue by zrsp** [tachiyomiorg/tachiyomi#3310]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Samsung Galaxy A7

### Steps to reproduce
1. Enable "Full screen gestures" for navigation bar in device settings. (ss: https://i.imgur.com/Z5t8svw.png)
2. Have Tachiyomi reader "Default viewer" setting set as "Vertical."
3. Open comic. Try to use navigation bar. (e.g. left arrow to get to previous screen)

### Expected behavior
Being able to use the nav bar via the gesture.

### Actual behavior
Scrolls the comic downwards/to the next page.

### Other details
Current workaround is to open the reader nav, then using system nav. So it's definitely not a huge issue. Guessing that adding a few pixels at the very bottom of the screen where finger gesture wouldn't scroll the comic would fix this.

**Comment by arkon** [comment]
Does this happen in other full screen apps? Seems like a Samsung issue.

**Comment by zrsp** [comment]
Nope, works properly on other apps. Also forgot to mention that it only started happening after updating to 0.9.2.

**Comment by arkon** [comment]
That sounds weird to me. Are you saying that in a full screen game, swiping on the edges invokes the system navigation?

**Comment by zrsp** [comment]
Yeah at the bottom of the screen. Like if you gesture from outside the screen, over to the screen.
Visual presentation, by yours truly: https://i.imgur.com/2FHsl1J.png

**Comment by arkon** [comment]
If any developer who uses a Samsung device ends up looking a this, I'd appreciate any help trying to fix this.

This isn't reproducible on my device (running OxygenOS) or emulators using normal Android gestures.

**Comment by bbtora** [comment]
I am not encountering any issues while using gestures, albeit it's a bit difficult to trigger system navigation by finding correct trigger edges (probably because I don't use gesture navigation).

**Comment by TheUnlocked** [comment]
I'm seeing this when the nav bar is set to the button mode, but that's to be expected since the nav bar is hidden and it's not in gesture mode. When in gesture mode I'm not having this issue.

**Comment by peltax** [comment]
This behaves like in other apps that handle gestures on Sony Xperia 10 II. First swipe up shows borders (System status bar and horizontal bar on bottom) and the second one invokes up gesture.

**Comment by arkon** [comment]
Can't seem to reproduce this on my Samsung devices.
