### ISSUE TITLE
[Feature Request] source search instead of extension search

### ISSUE THREAD

**Issue by AriaMoradi** [tachiyomiorg/tachiyomi#3338]
## Motive
Users should be able to find their source from within the app;
- sometimes a source has aliases
- some extensions are multi-source
- all available data is `Tachiyomi: <extension name>` and package names but it doesn't revile all the necessary data
- so user has to check out the spreadsheet or ask in discord.
    - most users are ignorant/not aware of this and won't do that. most people never read the manual. even less read a manual that was not shipped with the product. 
- the spreadsheet is maintained by @SnakeDoc83 and is volunteer work, it's not always up to date  

## My proposal
- add a database alongside https://github.com/inorichi/tachiyomi-extensions/blob/repo/index.json or replace it with something with the said info.
    - the said database is best if generated automatically, but if it's maintained manually, still should be available through the app, not some external resource.
```json
{
  "name": "Tachiyomi: Paprika",
  "pkg": "eu.kanade.tachiyomi.extension.all.paprika",
  "apk": "tachiyomi-all.paprika-v1.2.3.apk",
  "lang": "all",
  "code": 3,
  "version": "1.2.3",
  "sources": [
    {
      "name": "BoomManga",
      "aliases": [
        "boommanga.com",
        "bManga"
      ]
    },
    {
      "name": "ManManga",
      "aliases": [
        "manmanga.com",
        "NotWomanManga",
        "NotNotManManga"
      ]
    },
    {
      "name": "TwinsComics",
      "aliases": [
        "twinscomics.net",
        "a boy and a girl! the comic version"
      ]
    }
  ]
}
```
or a separate file:
```json
{
  "pkg": "eu.kanade.tachiyomi.extension.all.paprika",
  "sources": [
    {
      "name": "BoomManga",
      "aliases": [
        "boommanga.com",
        "bManga"
      ]
    },
    {
      "name": "ManManga",
      "aliases": [
        "manmanga.com",
        "NotWomanManga",
        "NotNotManManga"
      ]
    },
    {
      "name": "TwinsComics",
      "aliases": [
        "twinscomics.net",
        "a boy and a girl! the comic version"
      ]
    }
  ]
}
```
- make some changes to the app to read that data.
- hold the alias data in the extension class, or never implement it (to stay backwards compatible?).

##### Num 1.1
shell scripts: to make the said DB automatic it needs an environment to run kotlin with all android libs, install and import apks and be allways present for updates. no such thing has been ever made to run under a server/daemon.
##### Num 1.2
gradle: not possible.
refer: 
- https://stackoverflow.com/questions/50874250/use-a-java-class-in-build-gradle?noredirect=1&lq=1
- https://stackoverflow.com/questions/54520266/how-can-i-use-my-compiled-classes-in-dolast-gradle-build?noredirect=1&lq=1

#### Idea Num 2: declare all sources with aliases in build.gradle
while building apk, the data gets spited somewhere. later travis gathers all the data to a database while deploying apks.

#### Idea Num 2.1: declare all sources with aliases within the extension, but a new file like: `metadata.json`
travis gathers all the data to one place while deploying apks.

### search
- cache the database. update when user searches(if online) and when updating apk list.
- read the said database and incorporate in search.

#### Idea Num 0: Don't do anything!
Yeah. nothing.

#### Idea Num 1: add new data to the existing strucure
- show all sources and aliases in the extensions tab under each extension.
    - if extension is single source only show aliases. (because source name and appName are the same)

#### Idea Num 2: show sources instead of extensions
- sources are first citizen not extensions!
- show a list of sources and which extension it is associated to

#### Idea Num 3: remove the extensions tab completely!
- only have a sources tab
- extensions are hidden and in the background.
- have a button: "add more sources" as a menu item or as the last item in the RecyclerView.
- sources menu has sources only with a "add" button. if the associated extension is installed just enable it, otherwise download and ask to install. 
- enabling or disabling a source looses it's meaning. added or not is what we do here.  

## Final thoughts
- this can be implemented while breaking backwards compatibility or not.

**Comment by arkon** [comment]
Your proposal is too vague. Did you have an actual implementation idea in mind?

**Comment by AriaMoradi** [comment]
> Your proposal is too vague. Did you have an actual implementation idea in mind?

Will add everything

**Comment by AriaMoradi** [comment]
finally this can be implemented while breaking backwards compatibility or not.

**Comment by AriaMoradi** [comment]
> this can be implemented while breaking backwards compatibility or not.

let's discuss which route is the best.
I prefer the last idea from each section.

**Comment by arkon** [comment]
## File format
- We can keep it in one file so all of the apps don't need to be changed to do 2 requests.
- I don't think we need aliases as it complicates things. At best, we can include the `baseUrl`s from each source.

## Extension side
- I did try a super basic approach of just having an extra `txt` file that ends up included within the `index.json` file, but I didn't really like it: https://github.com/inorichi/tachiyomi-extensions/pull/1714
- We should be able to make use of something like annotation processing and codegen. Ideally we'd be able to just generate something that gets the `name` and `baseUrl` of every source at build time.

## App side
- If we continue just keeping the existing file, there's no changes required in terms of the request part.
- We'd just have to put the extra information when parsing the JSON into the `Extension.Available` and other related classes, then present that information in the UI. The search functionality would need to be modified to take the extra data into consideration.

## Other thoughts
- Yes, this can be backwards compatible. Older versions of the app should just ignore any new fields in the JSON file.

**Comment by AriaMoradi** [comment]
what's against something like https://github.com/inorichi/tachiyomi-extensions/pull/1714?
(with better format than that txt file of course)

**Comment by arkon** [comment]
The fact that it's manually maintained. It seems reasonable for smaller sources, but it doesn't really make sense for something like Madara, and it's something that can easily be forgotten in the review process.

**Comment by AriaMoradi** [comment]
Ok, I'm going to play with annotation processing stuff and see what I can come up with...

**Comment by AriaMoradi** [comment]
There is a possible way to do this, https://tachiyomi.org/extensions/ the spreadsheet tab extracts it's info directly from the spreadsheet.

**Comment by arkon** [comment]
Yeah, but having the app query a spreadsheet is peak jank...

**Comment by arkon** [comment]
Realistically this isn't an issue in 1.x, so this isn't worth solving.

**Comment by AriaMoradi** [comment]
> Yeah, but having the app query a spreadsheet is peak jank...

Looks like there is a API for this, and there should be a library...

**Comment by AriaMoradi** [comment]
https://spreadsheets.google.com/feeds/cells/1Kh_O8VyPKTdrcIsso0zz5gD3A9aw_9v2Ygnmr13RuOU/1/public/full?alt=json

This gets a json response. shoud be doable with Gson?

**Comment by arkon** [comment]
The issue isn't getting the data from Google Sheets, it's the fact that it needs to be manually kept up to date. It's fine if it's something that isn't referenced that often (i.e. on the website or the sheet directly), but using it as a source of truth within the app isn't something that I'd be willing to settle on. It'd be the equivalent of someone manually curating the existing extensions list.

If the app is going to have this data, it **must** be automated.

**Comment by AriaMoradi** [comment]
I would argue, if someone wants to find something in the mutlisource, The Spreadsheet™ is the only source of truth they get. we are only making it easier to access.

**Comment by arkon** [comment]
That's incorrect. The only real source of truth at this time is the codebase because the spreadsheet is prone to error since it's manually curated.

The app will only have real sources of truth, and I'm unwilling to budge on that stance.

**Comment by Soitora** [comment]
I agree with Arkon here, even for the website I'm iffy about using a table based on a manually managed Google Spreadsheet.

**Comment by AriaMoradi** [comment]
I tried extracting names and urls by instantiating extensions in a android local unit test solution.
It should work in theory but in order for it to work we need to substitute the application code that a extension depends on.
I committed and pushed what I've got now. Maybe someone will peruse it further.
https://github.com/AriaMoradi/tachiyomi-extensions/tree/tachiyomi-3338

**Comment by AriaMoradi** [comment]
I found a solution for this issue: Annotations

we can make a annotate class:
```kotlin
package eu.kanade.tachiyomi.annotations

@Target(AnnotationTarget.CLASS)
annotation class MultiSource(val sources: Array<String>)
```
Anotate the mulitsource Extension:
```kotlin
@MultiSource(arrayOf("BoomManga", "ManManga", "TwinsComics"))
class BoomMangaFactory : SourceFactory {
    override fun createSources(): List<Source> = listOf(
        BoomMangacom(),
        ManManga(),
        TwinsComics(),
        BoomMangazh(),
        ManMangazh(),
        TwinsComicszh()
    )
}

// ... rest of the file
```
Inspect the annotation at build time:
```kotlin
class Inspector {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            BoomMangaFactory::class.annotations.forEach {
                if(it is MultiSource)
                    println(it.sources.forEach { println(it) })
            }
        }
    }
}
```
it prints:
```
BoomManga
ManManga
TwinsComics
```
Then we can collect this info with extension package and at build time. and the app can use it.

**Comment by CrepeTF** [comment]
:harold: this issue not aging well with the multisource split
