### ISSUE TITLE
[Feature Request] <A counter in the extensions tab that shows how many manga are attached to each extension>

### ISSUE THREAD

**Issue by Thegreatbenjie** [tachiyomiorg/tachiyomi#3341]
---

### Why/User Benefit/User Problem
(I can only speak for myself, but I'm sure plenty of users download extensions in batches to ensure full coverage of the manga they like. Once they find what they're looking for though, theres no easy way to see what extensions aren't actually used. This would make it easy to see which extensions aren't needed.)

### What/Requirements
(In the extensions tab next to the name of each extension there would be a number ie. Mangadex[23] that would tell the user how many manga are tracked through that extension.)

**Comment by joseph619** [comment]
This is actually in the works at the moment, you can check the progress here 

https://github.com/inorichi/tachiyomi/pull/3191

**Comment by arkon** [comment]
The migration tab shows this info.
