### ISSUE TITLE
[Feature Request] Compare manga when migrating

### ISSUE THREAD

**Issue by Saladaladad** [tachiyomiorg/tachiyomi#3347]
Helps with migrating to see the differences between sources, since some extensions have fewer chapters and some have more. Specially with obsolete extensions that I can't view anymore in the selection of sources I can choose from i.e. Mangarock.

A simple "view from previous source" button would be nice

**Comment by haldi4803** [comment]
You know that you can long press a cover in the migration search and then enger the manga directly?

**Comment by Bm12347** [comment]
Should be closed as you can compare by long pressing and it is not hard
