### ISSUE TITLE
[Feature Request] <Pinch fingers in/out to change no. of items per row in the library>

### ISSUE THREAD

**Issue by chocoblin** [tachiyomiorg/tachiyomi#3369]
### Why/User Benefit/User Problem
we don't need to go again and again to the settings and change the no. of items per row in the library. it can be really frustrating

### What/Requirements
in the library pinch your fingers towards each other to make the thumbnails smaller, and thus make much more no. of items visible in a single screen
similarly, pinch out fingers away from each other to basically zoom in and view thumbnails larger. 
think of it as changing no. of items per row each second of pinching in and out our fingers
thank you! it will be much appreciated!

**Comment by arkon** [comment]
Sounds like an XY problem. Why are you even changing it over and over again? Not really sure what the use case here is.

**Comment by crusaside** [comment]
> Sounds like an XY problem. Why are you even changing it over and over again? Not really sure what the use case here is.

good point. but what exactly does XY issue mean? 😅

**Comment by arkon** [comment]
https://en.m.wikipedia.org/wiki/XY_problem

**Comment by crusaside** [comment]
> https://en.m.wikipedia.org/wiki/XY_problem

wow. i don't see how that would apply here

**Comment by CarlosEsco** [comment]
Because why are you needing to change the library grid size so frequently. What is the use case?
