### ISSUE TITLE
[Bug] Downloading long-titled chapters causes SD card to become unreadable

### ISSUE THREAD

**Issue by NGProj** [tachiyomiorg/tachiyomi#3373]
### Device information
* Tachiyomi version: Preview r2447 (65091c05)
* Android version: 10 QP1A.190711.020
* Device: Xiaomi Redmi Note 8 Pro

## Steps to reproduce
1. Set download location to be on SD storage device.
2. Add MangaDex extension.
3. Add "The Strongest Wizard Becomes a Countryside Guardsman After Taking an Arrow to the Knee" to the library.
4. Download chapter 4.
5. Reboot the device.

### Expected behavior
Device should work properly. Tachiyomi library should display the manga and chapters.

### Actual behavior
Device doesn't succeed in reading SD card's data. SD card informs an "issue" and requires reformatting.

### Other details
SD card issues happened on older versions of Tachiyomi and Android (was also happening on Android 9)
When this happened to me:
1. I downloaded a large amount of manga and chapters to the library.
2. I had to reboot the device and got the "SD card issue" error.
3. I connected the SD card to a PC using a card reader, which proved the card was not unreadable.
4. I moved Tachiyomi library for backup.
5. I ran into an error of a chapter folder having a "name too long" error.
6. I couldn't manually delete the chapter unless I renamed it.
7. After deleting just that chapter and restoring all other files, I mounted the SD card and saw that no issue was being raised. All manga chapters were present and readable.

**Comment by cecoates** [comment]
I've been running into an problem lately where images are consistently corrupted.

Is it possible a deep directory structure with long names and/or long file names and folder names could cause that? I'm not saving to a MicroSD, and I can't think of anything else various titles yielding corrupt images have in common.

When I switched to the base directory on internal (not something custom that's deeper with longer directory names) things seem fine (so far).

**Comment by ZIDOUZI** [comment]
I have this question also: it seems that too long title will cause the downloaded file can't be detected by the app. Also can't rename them in the file system. More seriously, using the default download path can't download these manga.  

For example, [this manga](https://nhentai.net/g/415173)

More info below.

> App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
> Android version: 10 (SDK 29)
> Device: HUAWEI HONOR PCT-AL10

**Comment by arkon** [comment]
Something like #9238 would address this, but it'd be quite a large change.
