### ISSUE TITLE
[Bug] Image fails to load when using resume button.

### ISSUE THREAD

**Issue by Leonime** [tachiyomiorg/tachiyomi#3375]
# Device information
* Tachiyomi version: 0.9.2
* Android version: 8.1.0
* Device: Galaxy Tab A (2016)

## Steps to reproduce
1. Start reading a chapter.
2. Read the whole chapter.
4. Start reading the next chapter.
3. On the first page of the next chapter press back button. (it may be possible that it happens on other pages, but I haven't tested beyond the first page).
4. Go to the info tab.
5. Tap share manga.
6. Share it and return to the app.
7. Return to the chapters tab.
8. Tap resume.

### Expected behavior
The image for the page should load

### Actual behavior
It keeps displaying the loading icon.

### Other details
If you do nothing the icon persists forever.
Right now I'm able to fix it by exiting and resuming again, or by turning the device, so it changes from portrait to landscape.

**Comment by arkon** [comment]
Can't reproduce in latest version.
