### ISSUE TITLE
[Bug] Problem with local manga and sd card

### ISSUE THREAD

**Issue by shogunreaper** [tachiyomiorg/tachiyomi#3394]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 7.1.2
* Device: Kindle Fire HD 10 (2017)

## Steps to reproduce
1. copy manga folders to local folder
2. refresh/close app/restart device

### Expected behavior
local manga should show up

### Actual behavior
local manga doesn't show up

### Other details

I've looked over a bunch of other topics before making one and haven't seen a solution, i see [this link](https://tachiyomi.org/help/guides/reading-local-manga/) posted but it doesn't apply to me as all my folders are already correct and were used in tachiyomi app previously, they were all on my sd card and are didn't get modified. They also work fine if copied directly to internal storage so its not an issue with the naming.

Everything was working fine with the app but amazon's skin finally annoyed me enough and i wanted a more stock android so i flashed the nougat rom, so i assume that this is some issue with nougat that is screwing things up.

But it's not as if the sd card isn't being read/written to, i can download from regular sources to the sd card and they appear under the library fine, it is only the local folder that doesn't seem to want to cooperate.

**Comment by arkon** [comment]
Hard to say without actually seeing what your folders look like. I assume your regular downloads on the SD card are working fine too?

**Comment by leftl** [comment]
Similar issue here, local manga on SD card wasn't recognized. After moving from internal storage (could read from here) back to SD card, the media was recognized and readable. However, when trying to set cover art, it was re-creating the `local` folder on the internal storage with a cover.jpg, but it would stay empty in my library. 

This might be an issue involving recovering backups with local media (no errors reported). From a fresh library, my local media works as expected from the SD card. I can post logs next time I make a backup and try recovering.

**Comment by Sunspark-007** [comment]
The creating the cover.jpg on the internal storage instead of the sd card is part of why covers don't display because the library still points to the sd card.
