### ISSUE TITLE
[Feature Request] Refactor extension concept into an android library for re-use

### ISSUE THREAD

**Issue by ChrisCrisis** [tachiyomiorg/tachiyomi#3412]
Hello there,
first of all I'm currently using Tachiyomi and really like how it tackled the problem of supporting multiple manga sources with its extension concept.

This feature request is more on a developer side of view and about a possible refactoring of the extension & source packages (also including necessary dependencies )

### Developer Benefit
This could make the manga sources also available to other possible applications.
An even clearer abstraction of the extension could also improve its ease of use through Tachiyomi.

### What/Requirements
This feature would require moving the packages & their dependencies to another android library module, probably tweaking  their function signatures a bit.
Also work for a proper documentation would be required.

**Comment by CarlosEsco** [comment]
I'm sorry but what benefit does this actually provide to tachiyomi?  If it was a library wouldn't it just then need a new release of app anytime an extension broke?

**Comment by ChrisCrisis** [comment]
Ok sorry,
I don't mean to move all the extensions into the app, the extensions should still be kept in their own apks and distributed the same way.
The idea is to simply splitting the code apart into another module, to make the extensions re-usable for other projects that might want to have access the data from many manga sources.

I might be missing something, but I don't see how an broken extension would require a new release of the app though.

**Comment by arkon** [comment]
I assume you mean splitting out and documenting the system that loads the separately packaged extension APKs into a library. It's possible, although I'm not sure if there's a high demand for it.

**Comment by ChrisCrisis** [comment]
Yeah, that's what I had in mind.
It's true that the demand might not be that high though.

**Comment by CarlosEsco** [comment]
Ok that makes more sense. Though I think it would need more work than a simple new module. Since everything rx and and realistically extensions would need rewritten for more generic access.  Even then though. This provides little benefits to tachiyomi and just benefits people trying to reuse the extensions for their own apps

**Comment by arkon** [comment]
@CarlosEsco He's just referring to the `ExtensionLoader` object, not the extensions API itself.

**Comment by ChrisCrisis** [comment]
Yeah, I thought about several ways of doing this in a fork myself. 
But that would still require the extensions to probably be recompiled, to be used with it.

**Comment by ChrisCrisis** [comment]
After digging a bit more, I noticed that mixed up the following repos all the time:

https://github.com/inorichi/tachiyomi-extensions-lib 
https://github.com/tachiyomiorg/extensions-lib 

After I just found the second one, I noticed that this was mainly what I was looking for. 
To correct my request, it would be about moving the `ExtensionLoader` & required `extension` package content to the extensions-lib.

But TBH for my request,  it is nearly sufficient to use `extensions-lib`, which contains at least all the `source` related classes.

Also maybe inorichi could archive https://github.com/inorichi/tachiyomi-extensions-lib, if it is not used anymore, or update the README.md & reference the project in the tachiyomiorg,  to stop possible confusion.

**Comment by arkon** [comment]
> To correct my request, it would be about moving the `ExtensionLoader` & required `extension` package content to the extensions-lib.

extensions-lib is a stubs package to compile extensions with, so it's not the right place. You're free to use extensions-lib in your own projects to compile extensions with though.

> Also maybe inorichi could archive https://github.com/inorichi/tachiyomi-extensions-lib, if it is not used anymore, or update the README.md & reference the project in the tachiyomiorg, to stop possible confusion.

I'll follow up on this.

**Comment by arkon** [comment]
Probably not happening. The logic to query for packages and the concept of stubs isn't really that complicated.
