### ISSUE TITLE
[Feature Request] <Configure hiding uploaded chapters>

### ISSUE THREAD

**Issue by Hell13Cat** [tachiyomiorg/tachiyomi#3432]
### User Benefit/User Problem
You have to delete the file every time from each folder after loading the chapters so that other applications begin to see what they downloaded.
No need to delete the ".nomedia" file manually to enable visibility by other application.

### What/Requirements
You will have to add the settings item and condition when saving files.

**Comment by arkon** [comment]
Nobody else has requested this before and instead complained when it wasn't working, so I'm not sure if this will ever be added.

**Comment by arkon** [comment]
Nobody else has ever suggested this, so going to close this.

Tachiyomi isn't really meant to be a downloading tool for other apps.
