### ISSUE TITLE
[Bug] allow collapsing of groups in filter selection even when they are "stuck" to the top of the screen

### ISSUE THREAD

**Issue by Jaykoerner** [tachiyomiorg/tachiyomi#3457]
Not sure if this is a bug(or if it's a bug with the extensions, but it is a issue with every extension in the app so...), or feature request, seems non intuitive, and cumbersome when you have a 100+ item selection box to have to scroll all the way to the top to close it, so I've assumed it is a bug. Sorry if this assumption is incorrect.

### Device information
* Tachiyomi version: 0.9.2(still exists as of 0.10.5)
* Android version: 9(now 10)
* Device: Samsung Galaxy Tab S4

## Steps to reproduce
1. Open any extension with a expandable group in the filter selection dialogue box(Example: MangaDex)
2. Expand any group (Example: Genres)
3. Scroll down till the groups container sticks to the top of the screen(example 3a shows a group not stuck to the top, while 3b shows when a group is stuck)
4. Tap the group container 

### Expected behavior
The group is collapsed(this should be possible in either state shown in the example images)

### Actual behavior
The Input is ignored till the top of the container is scrolled to(app only accepts input in the state shown in image 3a)

### Other details
Example image to show the items I'm talking about

Example 3a
![Screenshot_20200712-030521_Tachiyomi](https://user-images.githubusercontent.com/6897487/87241851-a2d83d00-c3ec-11ea-8b9f-2d6fe1f11138.jpg)

Example 3b
![Screenshot_20200712-030552_Tachiyomi](https://user-images.githubusercontent.com/6897487/87241854-abc90e80-c3ec-11ea-867a-6bbcc647be59.jpg)

**Comment by Jaykoerner** [comment]
FMI, is this a ux issue, extension issue, or a bug? Just wondering if I categorized it properly.

**Comment by arkon** [comment]
It's a bug, as far as I can tell.

**Comment by Jaykoerner** [comment]
Ok at least i labeled it correctly, I assume this is low priority though since you guys are looking for ux designers atm, and this would likely get fixed with any ux changes

**Comment by arkon** [comment]
No longer relevant as sticky headers were removed due to other issues.
