### ISSUE TITLE
[Feature Request] Blacklist specific manga to not update

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi#3467]
### Why/User Benefit/User Problem
In my isekai category,I have manga which are already completed but the website says it is still ongoing.So tachiyomi is also searching for update.With a specific manga(not category) blacklist,update will be a bit faster.

### What/Requirements
Add a blaclist of manga to not update![Blacklist.jpg](https://user-images.githubusercontent.com/56766778/91014389-98af7e00-e5e9-11ea-9218-0ff94b1793fb.jpg)

**Comment by Mitia99** [comment]
*Uptaded post

**Comment by lmj0011** [comment]
Try updating the "categories to include in global update"  and exclude the isekai category

**Comment by Mitia99** [comment]
@lmj0011 It is not the issue.I don't want to exclude my isekai category just a specific manga in the category.

**Comment by joseph619** [comment]
Create a category and put all the manga which you don't want to update in it.

**Comment by Mitia99** [comment]
@joseph619 That's an alternative but I categorize my manga by genre.I don't want my romance,isekai,sci-fi...manga to be mixed in one category.That's the reason of the feature request.

**Comment by CarlosEsco** [comment]
@Mitia99 you realize you can have a manga in more than 1 category right?  You can add two additional categories.  Update and don't update.  divide your library how you want.  Then set the library to only update the update category.  This will not effect your other categories at all and you can still view them how you currently do.

As for this request its niche, and not something that really needs to be done when there is an easy solution above.
