### ISSUE TITLE
[Feature Request] Under Backup settings can we have a option to view a timestamp of when the daily automatic/manual  backup was taken ?

### ISSUE THREAD

**Issue by aditbharadwaj** [tachiyomiorg/tachiyomi#3474]
---

### Why/User Benefit/User Problem
This will help the user to know and confirm that their daily/monthly or any type of bacup was generated at this point of time and date?

### What/Requirements
Just a Normal timestamp update  whenever the daily backup service runs or a manual backup was done by the user.

**Comment by arkon** [comment]
Couldn't you just look at the folder contents?

**Comment by arkon** [comment]
Also suggested as subtitle in More: #5391
