### ISSUE TITLE
[Feature Request] Source name in the library

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#3491]
### Why/User Benefit/User Problem
I'm probably the only one, but if available, I add the same manga from 3 sources (or whatever available) to the library, so that I'm sure to get it if other sources upload it later.
When the upload happens on all 3 of them, though, I have to open the manga first to check the source and choose the best one I wanna use.

### What/Requirements
When on compact/comfortable grid display type, it would appear like the download/unread badges on the cover.
When list display type, it would appear grayed out below the manga name, like it happens for the "author name" on mangadex or mangaplus.

**Comment by arkon** [comment]
This only seems to make sense for people who "hoard" entries, which we do not want to encourage.
