### ISSUE TITLE
[Downloads] <i changed my sd card to have more space but the app wont recognize the manga downloaded in the card>

### ISSUE THREAD

**Issue by AriaS73** [tachiyomiorg/tachiyomi#3494]
### Device information
* Tachiyomi version: 0.9.2-2543
* Android version: 10
* Device: Samsung Galaxy Tab S6

## Steps to reproduce
1. I changed my SD card in order to have more space
2. Copied all the downloaded manga to the new card and set the download location to that folder

### Expected behavior
The app recognizing that the manga were downloaded.

### Actual behavior
Not only does the app not recognize the downloaded manga, even when i deleted a manga using file manager in order to redownload it, it would later no longer say the chapter was downloaded

### Other details
Additional details and attachments.

**Comment by ConnorWGarvey** [comment]
I also have this issue. I've been downloading to an SD card. I can see files in the file manager, but in Tachiyomi, if I filter to downloaded, there isn't anything. I also don't have the option to show download badges in the library.

**Comment by arkon** [comment]
If you still have issues, please try asking for help on Discord. If there's a specific technical issue that seems to be opening, please open another issue on GitHub.
