### ISSUE TITLE
[Bug] After the period of time of usage, the cover page no longer loading automatically

### ISSUE THREAD

**Issue by mineyfxdx** [tachiyomiorg/tachiyomi#3496]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: vivo v9

## Steps to reproduce
1. First step
- having alot(hundreds) of non library tracking manga
2. Second step
-the problem start here

### Expected behavior
This should happen.
-the app should loading the coverpage automatically without a problems at all.

### Actual behavior
This happened instead.
-the cover page of almost all extension can not be loading automatically by the app.

### Other details
Additional details and attachments.
-This bug happened when the database of non library full(? Dunno but my phone memory not yet full,maybe it the app reach it limit program memory limit).  The bug : almost affected extension , it can't loading the cover page, even the internet already at peak. I need to click that specific manga and load the cover page(by swipe down) it manually.  But solved it by: Clear Database at Advanced setting.  Cons: i lost all my non library tracking list database.

**Comment by orangpelupa** [comment]
I got the same issue on asus fonepad 8.

I did not that issue when I use custom location on sd card. It starts to crop up after I moved it to standard location.

**Comment by PaoloLM** [comment]
I have the same problem, redmi note 8
