### ISSUE TITLE
[Feature Request] Add manga-wised rotation mode settings (similar to viewer)

### ISSUE THREAD

**Issue by bboyz269** [tachiyomiorg/tachiyomi#3521]
### Why/User Benefit/User Problem
I'm reading a mix of mangas and manhwas in vertical continuous viewer. Force portrait is good for reading manhwa or webtoon but it's impossible to read manga as the texts are so smalls, especially on low resolution phones.  
So I have to frequently change the rotation mode (portrait - landscape) for each manga / manhwa. And it's quite a problem for heavy reader like me.

### What/Requirements
Exactly like the viewer settings.  

A system-wised default rotation mode settings.  
![Screenshot_1595725457](https://user-images.githubusercontent.com/4453811/88469178-a0abcd80-cf18-11ea-9dc5-a89dad54ae44.png)

And a manga-wised rotation mode settings which is override the default settings.  
![Screenshot_1595727177](https://user-images.githubusercontent.com/4453811/88469333-d05bd500-cf1a-11ea-90a7-5f48bd235264.png)
![Screenshot_1595727234](https://user-images.githubusercontent.com/4453811/88469336-d18d0200-cf1a-11ea-9f31-97934fc4df32.png)

### Pull request
I took myself and created a working example codes based on the Viewer settings. Would you take a look?

https://github.com/inorichi/tachiyomi/pull/3522

**Comment by arkon** [comment]
> I took myself and created a working example codes based on the Viewer settings. Would you take a look?

Sure, submit a PR.

**Comment by bboyz269** [comment]
> > I took myself and created a working example codes based on the Viewer settings. Would you take a look?
> 
> Sure, submit a PR.

@arkon I updated the issue with the link to pull request or [here](https://github.com/inorichi/tachiyomi/pull/3522).
