### ISSUE TITLE
[Feature Request] Option to disable extension update notifications per extension.

### ISSUE THREAD

**Issue by AgentX2006** [tachiyomiorg/tachiyomi#3525]
Would really like an option to be able to disable extension update notifications for individual extensions.
---

### Why/User Benefit/User Problem
I mainly use two extensions for 95% of what I read. There is one however that I only use for a few manga (Madara) that is constantly updating. Almost daily and sometime multiple times per day. I feel like there is almost always a notification that there is an update for this extension and it's quite annoying as it is always at the top of my notifications list. As it is the only way to avoid this is to turn off notifications for all extensions. Doing so causes me to not realize when there is an update for the ones I use regularly which unlike the Madra extension often stop working when an update is missed. I assume this is due do most of these updates seeming to just be new sources being added to the Madra extension.

### What/Requirements
All that would be required is a toggle in a menu somewhere for the update notifications for each installed extension.

**Comment by arkon** [comment]
Not quite as relevant post multisource split. Please keep extensions up to date.
