### ISSUE TITLE
[Feature Request] ask the user to delete chapters when migrating to a different source

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#3529]
### Why/User Benefit/User Problem
Currently when you migrate from a source for a manga and you had downloaded chapters in the previous source they will stay which takes in unwanted space.

### What/Requirements
When you migrate you get a popup like when you unfavorite a source to delete the chapters you had downloaded before for the source you had migrated from.

**Comment by arkon** [comment]
Duplicate of #9153
