### ISSUE TITLE
[Feature Request]: When choosing the "Library update frequency," give the option to also choose at what time of day.

### ISSUE THREAD

**Issue by ManyMangaAreMangos** [tachiyomiorg/tachiyomi#3589]
Currently, if I want to choose what time of day my library checks for updates, I have to wait til that time of day rolls around, and then I have to set my frequency and manually update. Then it will (usually, not always) update automatically at that time of day the next time.

For a few reasons, this is inconvenient and tedious. It would be much easier if there were an independant setting which allowed me to choose the desired time (say, 8pm, for instance.)

Thanks.

**Comment by Puddintame349** [comment]
P.S. could someone add the Feature label for me?

**Comment by Puddintame349** [comment]
A humble bump, if I may.

**Comment by Mangavillia** [comment]
I would also like to add that manually updating around the time of day you want it to update is often unreliable. A lot this is obscure or doesn't work all the time, so being to set the preferred time would really help.

**Comment by arkon** [comment]
The only way to do this is to have the app act as an alarm, which I'm not particularly interested in implementing. I'm going to close this since there's no plans to do it, but if someone wants to implement it and open a PR, feel free to do so.
