### ISSUE TITLE
Swipe to mark chapters as read

### ISSUE THREAD

**Issue by vongdong** [tachiyomiorg/tachiyomi#3630]
I feel J2K's implementation of the swiping to 'mark as read' is more intuitive but I also like the current hold to select/multiselect. Same goes for the way to download chapters. Having the option to quickly download/swipe individually and multiselecting is something I'd like to see in the future. 

Maybe it could be done so mark as read is swipe left and download is swipe right. I know swipe right is used for bookmarking but I feel it's something used often enough for a swipe feature.

**Comment by vengiare** [comment]
There's already an issue for J2K download buttons #3039

I'd call swipe actions a quicker gesture, but I'd never call it intuitive.

**Comment by vongdong** [comment]
Ah, good to know the download button has been brought up.

Yeah, i couldn't really find the right way to describe it. Just swiping seems easier to do.

**Comment by joseph619** [comment]
I also agree that swiping is much quicker and easier, after using J2K and main UI forever a year.

**Comment by KraXen72** [comment]
yes, swiping is faster, but please do keep the long press for more options (don't remove it like jay) because downloading a select range is a pain on j2k and settings a select range as read/unread is impossible

**Comment by joseph619** [comment]
@KraXen72 I don't see why range select has to clash with the swipe. Swipe would only add mark as read/unread and bookmark. Both can coexist.

**Comment by d-najd** [comment]
I am working on this
