### ISSUE TITLE
[Bug] Unable to Long Press

### ISSUE THREAD

**Issue by EyangKodok** [tachiyomiorg/tachiyomi#3637]
### Device information
* Tachiyomi version: Stable 0.10.3
* Android version: 10 (SDK 29)
* Device: Samsung, SM-G985F

## Steps to reproduce
1. Update lots of mangas (go to updates then pull down to update all mangas)
2. Got to one of your manga
3. Long tap to one of the chapter that available (Note: do it while manga updates on going (thus you might need more than 5 mangas))

### Expected behavior
Select the chapter that long tapped on.

### Actual behavior
1. Successfully select it
2. Unsellect it self (which is not gamebreaking or appbreaking? but it's REALLY annoying). 

### Other details
This bug happen while i'm trying to update my mangas, you gonna need to long tap it WHILE manga update happening.
this havent happen before, it happen after new update (i think (you gotta try this guy on other version if you really want to know)). Also i might look like tapping or long hold then release it but i'm not, i'm long tapping it.
![Evidence EyangKodok](https://user-images.githubusercontent.com/64497015/89724001-cc09de80-da27-11ea-8fa8-8bc9ff4b4f6a.gif)

**Comment by arkon** [comment]
I don't think this is still an issue.
