### ISSUE TITLE
[Feature Request] Put the function "crop borders" to be "for this series" instead of being global

### ISSUE THREAD

**Issue by lionkobin** [tachiyomiorg/tachiyomi#3657]
## Why
For some mangas we want it to be borderless but for others we dont (example weebtoons) and having to be set up every time we change magas is boring.

## What
Like the title, just put the function crop borders to be for this series instead of being global.

**Comment by developedby** [comment]
Not exactly the feature you're asking for, but the app already diferentiates between crop borders for paged and crop borders for webtoon

**Comment by lionkobin** [comment]
I know, but is global and i have to change ever time

**Comment by Nodd** [comment]
> Not exactly the feature you're asking for, but the app already diferentiates between crop borders for paged and crop borders for webtoon

Yes, but sadly it treats "vertical continous" as "webtoon", while vertical continous is actually paged (at least the way I use it). The new button to switch crop mode and the direct update of the pages is already a nice quality of life improvement (thanks a lot!).

Anyway a configuration for each series would also solve the problem.

**Comment by arkon** [comment]
It's easier to toggle this in the reader now, so I'm going to close this since per-series settings are annoying to implement.
