### ISSUE TITLE
[Feature Request] Tap left or right side of screen to go to next page

### ISSUE THREAD

**Issue by JustWhelmed** [tachiyomiorg/tachiyomi#3678]
Currently you're only able to have it so that tapping the right side of the screen will flip to next page while tapping left side will flip to previous (or inverted) but you can't have it so that both sides of the screen will go next. I'd prefer it that way (while I'd swipe to go previous). 

---

## Why/User Benefit/User Problem
More user customization.

## What/Requirements
Should be in the options.

**Comment by arkon** [comment]
Could be addressed by #2152
