### ISSUE TITLE
[Bug] Delete Chapters - After last chapter read overrides "Save downloaded & bookmarked chapters"

### ISSUE THREAD

**Issue by shukero** [tachiyomiorg/tachiyomi#3723]
Hello, 

I'm seeing a bug within Tachiyomi that "disregards" / "overrides" the "Delete bookmarked Chapters" option when the option is turned off, and the "Delete chapter - After latest chapter is read" option is selected.

## Device information
App version: 0.10.4 (standard, 65b32ddeb, 50)
Android version: 10 (SDK 29)
Android build ID: QQ3A.200805.001
Device brand: google
Device manufacturer: Google
Device name: coral
Device model: Pixel 4 XL
Device product name: coral*

## Steps to reproduce
1. Setup Chapter downloads settings to "delete chapter after reading latest chapter" & disable "delete bookmarked chapters".
2. Download any two chapters of any manga.
3. Bookmark these two chapters, and then read through them.
4. Note that both of the chapters that were previously downloaded are no longer downloaded, and are now deleted.

### Expected behavior
With the settings screenshot above in place; I am expecting Tachiyomi  to delete any "read" chapters UNLESS I bookmarked that chapter. If I have bookmarked a chapter, Tachiyomi should leave those chapters alone and NOT delete them.

### Actual behavior
Tachiyomi is overriding / disregarding the "Delete bookmarked chapters" option and automatically deletes previously read chapters even if the "Delete bookmarked Chapters" option is disabled.

## Other details
Screenshot of setup:
![Screenshot_20200827-110329](https://user-images.githubusercontent.com/15789167/91461841-7ae75080-e857-11ea-9374-103b9734478c.png)

**Comment by arkon** [comment]
I think this is related to https://github.com/inorichi/tachiyomi/issues/3697

**Comment by shukero** [comment]
Hi arkon,

I thought the "last chapter read" deletion setting was supposed to delete a chapter after you've read that individual chapter. (I really like the fact it currently does this) So if Tachiyomi still do delete each individual chapter, but also did not delete bookmarked chapters, I'd be happy.

**Comment by arkon** [comment]
Doesn't seem like this is happening in the latest version.
