### ISSUE TITLE
Disable chapter transaction doesn't work going backwards

### ISSUE THREAD

**Issue by Signum21** [tachiyomiorg/tachiyomi#3756]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 7.1.1
* Device: Moto X Play

## Steps to reproduce
1. Open new chapter (the bug doesn't work if you've opened the previous chapter and went forward and than backwards)
2. Go back to the previous chapter

### Expected behavior
It should show the last page of the previous chapter

### Actual behavior
It shows the chapter transaction

**Comment by CarlosEsco** [comment]
I think this intended.  Disable transitions is not a guarantee going forwarded as it only disables when the next chapter has successfully loaded.  So when going backwards the application does not preload any pages/chapters so its always going to show

**Comment by arkon** [comment]
We don't preload going backwards, so this is fine.
