### ISSUE TITLE
[Bug] Can't click "Add to Library","Share" or "Open in Browser" on Android TV with mouse or remote

### ISSUE THREAD

**Issue by DaisyF8** [tachiyomiorg/tachiyomi#3766]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 9
* Device: Android TV - Sony Bravia - So Tachiyomi is rotated in landscape

## Steps to reproduce
1. First step
Go to any manga
2. Second step
Click any of the three buttons "Add to Library","Share" or "Open in Browser".  You can't click these three buttons

With remote you can click right from "back" to "download", but then click right or down doesn't reach "Add to library"
### Expected behavior
Click on the three buttons

### Actual behavior
Clicking with mouse or going there with remote (left right up down) doesn't work. It's as if the buttons are in another layer.  

## Other details
Android TV is alway landscape, don't know if this is important

**Comment by arkon** [comment]
Is this still an issue in 0.10.6? I admittedly am too lazy to set up my TV for dev work.

**Comment by SofStartsFires** [comment]
> Is this still an issue in 0.10.6? I admittedly am too lazy to set up my TV for dev work.

Still an issue, just tried it after getting android TV. There's something that sounds really comfy about reading manga from my ocuch on a giant TV. The controls are a bit wonky but work up till then, but definitely can't do add to library.
