### ISSUE TITLE
[Bug] Cover art reset to default after refreshing a specific manga

### ISSUE THREAD

**Issue by ShhShawn** [tachiyomiorg/tachiyomi#3767]
## Device information
* Tachiyomi version: 10.4
* Android version: 10
* Device: Pocophone f1

## Steps to reproduce
1. Select a manga.
2. Select a chapter and set the cover by: long press -> set as cover.
3. Refresh the manga.
(Note: "automatically refresh metadata" has been turned off)

### Expected behavior
Cover art remain the same as what I set.

### Actual behavior
Cover art revert to default after refreshing.

## Other details
This bug only happens when I refresh a specific manga and does not happen if I refresh the library.

Screen recording and screenshot:
[screen recording and screenshot.zip](https://github.com/inorichi/tachiyomi/files/5183579/screen.recording.and.screenshot.zip)

**Comment by FourTOne5** [comment]
Couldn't reproduce
