### ISSUE TITLE
[Bug] multi select not working after some steps

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tachiyomiorg/tachiyomi#3769]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 9
* Device: any device can be reproduced

## Steps to reproduce
1. open chapter menu
2. select one chapter by long press
3. select another chapter by single tap, and cancel this selection of this chapter
4. try to select multiple chapter from step 2 selected to here by long press

### Expected behavior
multiple chapter selected (behavior like select one chapter and long press another chapter to select select multiple chapter between them)

### Actual behavior
multi select not be triggered, only chapters in step 1 and 4 was being selected

## Other details
nope

**Comment by arkon** [comment]
> try to select multiple chapter from step 2 selected to here by long press

Can you provide more specific steps?

**Comment by scb261** [comment]
I think this:
1. Select chapter 1 with long tap
1. Select chapter 3 with single tap
1. Deselect chapter 3 with single tap
1. Select chapter 5 with long tap

Expected behavior: chapters 1-5 selected
Actual behavior: chapters 1, 4-5 selected

**Comment by curche** [comment]
can reproduce this on latest Sy Preview r326 (which is on latest preview)


If it helps, also adding a link to the video that I uploaded at the discord channel: 
https://cdn.discordapp.com/attachments/566585518171881493/801106847985696788/ScreenRecord-2021-01-19-20-37-25.mp4
