### ISSUE TITLE
[Feature Request] Crop border for 'Webtoon' mode and 'Continuous Vertical' separately

### ISSUE THREAD

**Issue by MigDowe** [tachiyomiorg/tachiyomi#3771]
I like to read japanese manga on 'Continuous Vertical' because it separates the pages, and manhua/manhwa on 'Webtoon' but the crop border function of those 2 are shared, cropping 'manhua/manhwa' are not ideal because it messes it format, and cropping japanese manga is a must, now I alternat manually every time I start reading 
---

## Why/User Benefit/User Problem
It adds options for users that like to read manga on infinity scroll

## What/Requirements
A new tab of options for Reader (paged/webtoon)
Exemple on where to add:

![72917ccc-04c3-405d-b611-93304c3e8667](https://user-images.githubusercontent.com/69957369/92561196-1f02cb80-f24a-11ea-8c18-f0c2cf1a9d2c.jpg)

**Comment by Nodd** [comment]
Yes please !
What is even more annoying is that to apply the crop border change, I have to leave the manga and return to it, it's not applying dynamically.

**Comment by arkon** [comment]
#3657 would make more sense, so closing this.
