### ISSUE TITLE
[Feature Request] Search in library include manga description

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#3773]
## Why/User Benefit/User Problem
there is something on the description that sometimes pique people interest in that manga. for example about alchemist, dungeon, shop, or anything else. or if someone only remember the protagonist name that usually included in manga description. 
or if you want to find duplicate manga (since we didnt save alt name) with a different title and the other doesnt contain author name, you can search with description as clue 

## What/Requirements
for example, if we search alchemist manga which contain alchemist description would show as well on search result

**Comment by mra1412** [comment]
Same should be for that manga tags.

**Comment by Riztard** [comment]
added in sy https://github.com/jobobby04/TachiyomiSY/commit/33fac3e96bf83c702db6690ca2184d0d9068443d
