### ISSUE TITLE
[Feature Request] Show Mark as unread button for mid-read chapters

### ISSUE THREAD

**Issue by XPJ38** [tachiyomiorg/tachiyomi#3777]
I frequently leave chapters mid-read because either I am interrupted (I mostly use Tachiyomi on the go) or when I take a quick peek at a random chapter to see if a manga I didn't read yet looks interesting. When this happens, I mark them as unread to read them from scratch later when I have the time.

Before v0.10, I could select one or multiple unread chapters in the chapter list then click on "Mark as unread". With v0.10 I can't anymore because the Mark as unread button only appears for chapters that have been fully read. So I either Mark as read then Mark as unread, or manually go back to page 1, which in both cases is kind of annoying/counter-intuitive.

I am talking about this button...

![Screenshot_20200911-113113](https://user-images.githubusercontent.com/4924563/92905194-c0914500-f423-11ea-9753-cf75cdd1c996.png)

...to be added in this context:

![Screenshot_20200911-113034](https://user-images.githubusercontent.com/4924563/92905236-ca1aad00-f423-11ea-8d4c-a2c209af6f19.png)

**Comment by AbsurdlySuspicious** [comment]
I'm voting for this

There's not really much free space on smaller screens for one more button, so maybe it's better to make a context menu with "mark as read" and "mark as unread" options on long-press? This will conflict with help/description popup all other buttons here have on long-press, but I think it's okay as long as context menu has icons for both options so it's clear for user what button does what. Another option is to make this entire bar overflow into three-dot menu
