### ISSUE TITLE
[Bug] Strange download behavior

### ISSUE THREAD

**Issue by Kugumin** [tachiyomiorg/tachiyomi#3789]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 10
* Device: Xiaomi Mi 9T Pro

## Steps to reproduce
1. Queue downloading of 2 different mangas from same source (I used Readmanga).

### Expected behavior
It should download first to appear manga chapter in one thread.

### Actual behavior
It started to download chapters from different manga in 2 threads. A thread for first manga and second thread for second manga.

## Other details
Occasion of bug is rare, not sure that reproduce way is right, but that's the only way it appears for me.

**Comment by shipoxx** [comment]
Same thing happened to me!

**Comment by arkon** [comment]
Closing in favour of #7492
