### ISSUE TITLE
[Bug] Begin to lag after reading manga for a while

### ISSUE THREAD

**Issue by VuNguyenLong** [tachiyomiorg/tachiyomi#3822]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 8.0.0
* Device: HUAWEI Y6 Prime 2018

## Steps to reproduce
1. Open app
2. Reading manga for a while
3. App begin to lag

### Expected behavior
3. It should be normal

**Comment by scb261** [comment]
#2100 is related but closed by author

**Comment by Koomongous** [comment]
I believe this is why my phone eventually froze so i've closed my original post.

**Comment by scb261** [comment]
Is there someone who had this problem (lag due to reading for a while, not due to long strips)? It could be fixed with new image decoder in 0.10.8, need someone to confirm

**Comment by arkon** [comment]
v0.10.8 doesn't include the new image decoder.

**Comment by arkon** [comment]
Should be better in the next stable release.
