### ISSUE TITLE
[Feature Request] Auto-"complete" in tracking services after reading known last chapter

### ISSUE THREAD

**Issue by jivmakawili** [tachiyomiorg/tachiyomi#3830]
just as the title says

**Comment by Neolel** [comment]
I am seconding this and want to add something. On AniList, a series is automatically set to complete if you update your chapter progress incrementally by clicking on the + on the [Manga in Progress](https://i.imgur.com/ETo4PB9.png) for that manga and hit the latest chapter. 

This is just speculation: I think Tachiyomi, at least on AniList, updates the chapter progress by manually inputting the chapter number after reading a chapter into its [list editor](https://i.imgur.com/FWiOgDO.png). 

While this works for tracking chapters, it is not the intended way on AniList as far as I understood. 

Doing it with the + on the manga in progress section seems to be the intended way solves the issue of not auto-completing as well. A downside would be that Tachiyomi probably would need to compare your current chapter number in it with the chapter number on AniList and raise the chapter number on AniList if it is lower compared to the number in Tachiyomi every time you read a chapter.

**Comment by arkon** [comment]
Closing in favour of #5779
