### ISSUE TITLE
[Feature Request] Show "Set categories" option when doing a migration.

### ISSUE THREAD

**Issue by AgentX2006** [tachiyomiorg/tachiyomi#3832]
## Why/User Benefit/User Problem
When doing a migration it would be nice to be able to set/change categories (like when you add something new to your library)  especially if you have your categories set up as the source of that particular manga. Am still in the process of migrating kissmanga over to other sources but every time I migrate one I have to find it and go through the extra steps of changing the category (back out to library, locate it in the list, long press, and then press the categories button at the bottom) which is often made more difficult because the cover art and or title used by the new source is different. For a user not wanting to make any changes it would be as simple as pressing OK when the option comes up which is far simpler than what is required to assign a category after a migration.

## What/Requirements
Just display the "Set categories" option after the "Select data to include" option.

**Comment by arkon** [comment]
Seems like an odd workflow. If it's already in your library, it'd hopefully already be in the correct categories.
