### ISSUE TITLE
[Bug] Tachiyomi scaling issues

### ISSUE THREAD

**Issue by 0xAB51NTH** [tachiyomiorg/tachiyomi#3836]
---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 7.0
* Device: Huawei P9 lite mini

## Steps to reproduce
1. Open up high res scan of manga that has small patterns (small checkerboxes etc.)
2. Try to zoom in or out and see how image changes dynamicly

### Expected behavior
Image should scale fine, without creating weird artifacts when looking at it zoomed out

### Actual behavior
Image is scaled inproperly causing weird artifacts and image quality loss
If you are unable to reproduce it heres comp to the perfect viewer vs tachi reproduction of the same page. (thanks to my friend RainingTerror  for providing one, the perfectviewer used lanczos as scaler)
https://slow.pics/c/Ak1KHcAS

## Other details
Maybe adding different scalers or allowing to pick scaling algorithm could fix that.

**Comment by ChrisJAllan** [comment]
It seems to be an issue with the library used to display images [here](https://github.com/davemorrissey/subsampling-scale-image-view), and can be seen in the demo video

**Comment by arkon** [comment]
Yeah, this isn't going to be fixed in 0.x. Image rendering will be revisited in the 1.x rewrite.
