### ISSUE TITLE
[Feature Request] Sources interface

### ISSUE THREAD

**Issue by DieSmilePN** [tachiyomiorg/tachiyomi#3866]
## Why/User Benefit/User Problem
It will make it look cleaner and easier to queue sources while global searching

## What/Requirements
Instead of **pinning** the sources. Use the method you guys use in **Edit Categories** that thing you just drag Up or Down. Make a **Edit Sources queue** something like that so may it not accidentally drag up or down

**Comment by arkon** [comment]
It's easier to force consistent ordering as it is currently.
