### ISSUE TITLE
[Feature Request] +18 on individual sources

### ISSUE THREAD

**Issue by BD-1988** [tachiyomiorg/tachiyomi#3872]
## Why/User Benefit/User Problem
Adding a +18 warning text to each source that contained +18 materials would benifit both users trying to avoid such materials and those seeking it

## What/Requirements
Just like in the recent update that added the red +18 text on extensions same should be done to individual sources that contain such materials

**Comment by vengiare** [comment]
Technically this will be addressed soon since the extensions repo is trying to avoid multi-source extensions now.
