### ISSUE TITLE
[Feature Request] Categories Group

### ISSUE THREAD

**Issue by gonz1324** [tachiyomiorg/tachiyomi#3880]
##  Why/User Benefit/User Problem
Put categories with the same criteria in one group will help search and manage a way lot more
## What/Requirements
- Edit Categories Group : can edit/add new group just like Edit categories
-- When edit an available group, open new display like edit categories. In there, when click add button will show 2 options : Choose from available categories or Add new category
-- Edit a category now will have a new heart button to add it to group. Each category can add in multi-group too, just like bookmark a series
- Bookmark new series : basically swipe left/right to changer group
- Categories group in Library : when Categories group is on, Show category tabs in Display option will be off
-- Group name will replace "Library" text
-- Can swipe up/down at group name to changer group
-- Can tap at group name to show groups list

**Comment by scb261** [comment]
#1803 (subcategory) and this request (metacategory) are kinda similar, but there are some differences. I doubt that both will be implemented, so maybe it's better to describe your version on #1803 and when/if someone will be implementing this they could see both and decide what's better

**Comment by arkon** [comment]
Closing in favour of #1803
