### ISSUE TITLE
[Feature Request] Adding a button in reader to change the default read mode intuitively and quickly

### ISSUE THREAD

**Issue by useeeeer** [tachiyomiorg/tachiyomi#3905]
## Why/User Benefit/User Problem
(explain why this feature should be added)

The setting of changing the default read mode is inconvenient. People want to change this setting in the comic reader intuitively and quickly.
Because according to usage scenarios and body postures, users usually want to use another hand or other finger to turn the page. Thus, sometimes users want to click the right side of the screen to go to the next page, and sometimes the left side.

## What/Requirements
(explain how this feature would behave)

Currently, in the reader, users only have the ability to change the read mode for the current reading comic, but not change the read mode for all comics.
I suggest adding a button in reader, so that users can change the default read mode for all comics intuitively and quickly.

**Comment by sainAk** [comment]
It's alerady being discussed here #3453

**Comment by arkon** [comment]
I'm not sure it actually makes sense to be changing the _default_ mode all the time. Making it easier per-manga makes sense though.
