### ISSUE TITLE
Downloaded Chapters are automatically renamed and can therefore no longer be read by the App!

### ISSUE THREAD

**Issue by AlbedoSuzuki** [tachiyomiorg/tachiyomi#3916]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 8.0.0
* Device: Tablet
![Screenshot_20201008-123412~2](https://user-images.githubusercontent.com/61992892/95449949-c9633100-0965-11eb-9fab-75b8e35195c6.png)

## Steps to reproduce
1. I downloaded the chapter
2. Next day IT was renamed and can no longer be displayed by tachiyomi

## Issue/Request
I downloaded the chapter and the next day it was renamed as shown and not readable.

## Other details
MangaBox: 1.2.24
Mangabat
Originaly the filenames should be read.mangabat.com_Chapter xxx

**Comment by scb261** [comment]
There is one more user with the same problem, and it is mangabat as well 
![image](https://user-images.githubusercontent.com/65343233/95653938-0ca7d600-0b05-11eb-8a98-299c7541fdd6.png)

**Comment by arkon** [comment]
Closing due to age.
