### ISSUE TITLE
[Feature Request] Disable zooming out of 100% from webtoon layout

### ISSUE THREAD

**Issue by mrwm** [tachiyomiorg/tachiyomi#3918]
## Why/User Benefit/User Problem
Sometimes I accidentally zoom out when reading manga, but I don't want to zoom out from 100% view. Another problem with zooming out is it occasionally leads to the current page count to jump ahead of the page that is currently viewed.

To recreate:

- open any manga with more than 3/4 pages in webtoon mode
- zoom out to less than 100%
- reset zoom to 100% by double tapping
- try to read to end of manga, only to be stopped a couple pages short.

Video example: https://streamable.com/yup8vn
Google drive backup in case streamable deletes it: https://drive.google.com/file/d/16Nj7ME7dV_bB7JedFmYFBVhjPkkPCwGq/view

## What/Requirements
Enable an option to limit the zoom to 100% and no less.

***
The bug is related to #3555, but feature request limiting zooming out would be nice.

**Comment by arkon** [comment]
Closing in favour of #4145
