### ISSUE TITLE
[Feature Request] Click text to search in Browse tab

### ISSUE THREAD

**Issue by WildOrangutan** [tachiyomiorg/tachiyomi#3920]
## Where
Browse tab -> Sources

## Why / User Benefit / User Problem
When I first used search it confused me a bit. When you search for a specific text it appears very similar to normal search field.

See example below. Top image is how text looks like, just before search is executed. Bottom image how it looks like, after you search for something.

not clicked search yet
![image](https://user-images.githubusercontent.com/5972966/95633291-a630a280-0a87-11eb-8821-600511a62906.png) ![image](https://user-images.githubusercontent.com/5972966/95633358-cf513300-0a87-11eb-82d0-0cb4e52cb440.png)

## What / Requirements
Maybe better differentiate between search field and title text. Or just plainly  allow clicking on title.

## Version

git head: `e637f22540de4f6571d3`

**Comment by arkon** [comment]
Closing in favour of #7201
