### ISSUE TITLE
[Bug] Shows black page after loading 

### ISSUE THREAD

**Issue by taz-ib** [tachiyomiorg/tachiyomi#3938]
Some pages loads completely but doesn't show in the app. That page can be saved and read from other gallery app, but isn't visible in Tachiyomi. Only some pages become like this. 
---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Xiaomi Mi A2

## Steps to reproduce
Was reading manga "Dark lady". Page 2 from Chapter 52 isn't visible. 

### Expected behavior
Should open the page after loading completely. 

### Actual behavior
Shows black screen

![Screenshot_20201013-213312.png](https://user-images.githubusercontent.com/68166127/95883274-91f8e800-0d9c-11eb-847d-d5fa86bfd377.png)![Screenshot_20201013-213301.png](https://user-images.githubusercontent.com/68166127/95883294-958c6f00-0d9c-11eb-9bef-4a9449b56d2e.png)

**Comment by scb261** [comment]
Can you check if it works when you set *Vertical* reading mode and *Fit screen* scale type?

**Comment by tazibmldl** [comment]
> Can you check if it works when you set *Vertical* reading mode and *Fit screen* scale type?

Did everything. But it won't show those pages whatever I do.

**Comment by tazibmldl** [comment]
So another thing I found is that from that chapter, app shows only 3 pages, and those 3 are lower than 10 mb. App seems to be unable to open pages larger than 10mb.
![Screenshot_20201013-215359.png](https://user-images.githubusercontent.com/68166127/95885190-cd94b180-0d9e-11eb-9028-6951355896de.png)
