### ISSUE TITLE
[Bug] <All sources never stops loading>

### ISSUE THREAD

**Issue by MaxVal92** [tachiyomiorg/tachiyomi#3944]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Galaxy S20 Ultra 5G

## Steps to reproduce
1. I just installed app
2. I install about 20 different extensions
3. I try to open the sources 

### Expected behavior
There should come up mangas from the particular source that I am using

### Actual behavior
It just keeps loading, no error message, nothing.

## Other details
I went through all the steps in the troubleshoot, with no success. I tried opening all the sources I installed with all of them doing the same. Examples:
- mangahere
- mangadex
- toomics
- webtoons 

The weird thing is that I am able to open the webview on all of the sources

**Comment by yegorgunko** [comment]
I can't reproduce on the latest dev build: 0.10.5-2774 (standard, b88e444c, 51)

For me it doesn't load at all - just shows the sources immediately (even though animation lags a little).

Would you like to try to install the dev build without deleting extensions? Do not forget to backup if you have valuable information.

**Comment by arkon** [comment]
Not enough info.
