### ISSUE TITLE
[Feature Request] Use sync icon instead of checkmark for tracked manga

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#3952]
## Why/User Benefit/User Problem
![Screenshot_20201019-070549~01](https://user-images.githubusercontent.com/63973749/96388811-f58c7680-11dd-11eb-86f6-c6c351d0bca0.png)

I don't really think we need a checkmark anymore now that the icon has an accent color.

**Comment by arkon** [comment]
What's wrong with a checkmark? The library icon changes when active too.

**Comment by vengiare** [comment]
I think a checkmark (plus a sync error icon) would make more sense if app can detect if progress is actually synced.

**Comment by arkon** [comment]
Nah dog.
