### ISSUE TITLE
[Feature Request] Possibilty to have multiples folders as "local directory"

### ISSUE THREAD

**Issue by o01210o** [tachiyomiorg/tachiyomi#3953]
## Why/User Benefit/User Problem
It allows us to set a specific folder as "local source" in addition to the native "local" folder in the "Tachiyomi" folder.
Right now, If we have a sd card, we can add a manga folder in the local folder in the internal storage _or/and_ in the local folder in the sd card and the manga is added in the local source.

A very specific example: you probably know that Manga Plus has only the three last chapters in their website. When you download the chapters, it is stored in your phone, but at the moment the chapter is no more avalaible in the website (and then in the chapters list), you can't acces to the chapter directly (but they are always in your phone). You have to acces it from the file manager and move them to another folder in the local folder then you can view the chapters in the app. The idea is to set that specific folder as local so you can acces it directly.

## What/Requirements
A "Local" section in the option, so you can have a list of your "local directory" and you can manage it (add/edit/delete).
When you go to the "local source" in the explorer tab, the app scan all the folders that you marked as "local" and show you all the mangas in those folders.
  
    
It's big text, sorry for the eventual mistakes, I'm french.

**Comment by scb261** [comment]
Related issue #2086 (custom local path, but they ask for only one path)

**Comment by arkon** [comment]
This will be more difficult when dealing with newer Android version's file restrictions and would also likely make things slower, so I'm denying this request.
