### ISSUE TITLE
[Bug] Manual migrate in source is just normal browse

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi#3959]
When one goes to migrate a series, manual searches, taps on a source title, and then picks a series - it should pick that series as the migrate destination.
However, in Preview r2790 when tapping a series now it just opens the manga info and chapters screen.

---

## Device information
* Tachiyomi version: Preview r2790
* Android version: 10
* Device: OnePlus 6t

## Steps to reproduce
1. Migrate series
2. Wait for option to load
3. Manual search in 3 dot menu
4. Expand a source by tapping source title
5. Tap on series destination

### Expected behavior
Should go back to initial migrate screen with chosen series as migrate output

### Actual behavior
Opens manga info and chapters screen

## Other details
N/a

**Comment by arkon** [comment]
Should be fixed.
