### ISSUE TITLE
[Feature Request] Unify library display settings

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#3969]
## Why/User Benefit/User Problem
Currently, the library's display settings are split between two different places. A few are in the "Display" sections of the "Library" portion under "More" -> "Settings", but the rest are in the "Display" portion of the filter button on the library screen. This can be very confusing, and it is a pain to navigate between the two to try to customize how the library looks. It would be much easier for all users if they were consolidated on the Settings section, and it also just makes more sense for all the settings to be under "Settings' instead of being tucked away in an unrelated portion of the app.

## What/Requirements
The "Display" portion of the library filter would be removed, and those settings would be moved to the already existing "Display" portion of the "Library" section of "More" -> "Settings".

**Comment by arkon** [comment]
I'd be okay with having them duplicated in settings, but not having them at all in the actual library view sounds inconvenient.
