### ISSUE TITLE
[Feature Request] Ability to Favorite (♥) a Manga

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#3980]
The Favorited Manga Will Not Be affected by "remove after Read" in all Chapters and The Favorited Manga Is The Most Prioritize If Youre Looking For an Global Update. 
Unlike Bookmark.. That You need to Bookmark It to Prevent it from Deleting

## Why/User Benefit/User Problem
I think that Some of us. Dont want to delete Some of the downloaded Chapters Like "Solo leveling".. So That It can Be Read Multiple times 
![Screenshot_20201028_091606_eu kanade tachiyomi](https://user-images.githubusercontent.com/65703094/97378866-62022680-18fe-11eb-9eae-7fb13f14e7c3.jpg)
SO TO PREVENT IT FROM DELETING the Chapters IS TO BOOKMARK.

**Comment by CrepeTF** [comment]
Use categories
