### ISSUE TITLE
[Feature Request] Prioritize The Lower Chapter

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#3983]
When Selecting multiple Chapters In Updates. And Download it... it Always Download The Higher Chapter first.. It is Posible to Download The Lower Chapter first
![Screenshot_20201028_174800](https://user-images.githubusercontent.com/65703094/97420067-c98f9480-1945-11eb-94f1-58cff1ce4792.jpg)

**Comment by Nexr0n** [comment]
Reorder by oldest

**Comment by CrepeTF** [comment]
Pretty sure this issue should be closed now
