### ISSUE TITLE
[Feature Request] Floating Botton in library to resume last reading.

### ISSUE THREAD

**Issue by alfaazian** [tachiyomiorg/tachiyomi#3985]
## Why/User Benefit/User Problem
This way even if you have sorted mangas alphabetically, you will not need to go and find the manga you are currently reading and can resume reading by just clicking the botton.

## What/Requirements
Read/Play botton out in the library which resumes to where you were reading in the last readed manga of the current Category (same as play botton in MX player to resume last played video).

**Comment by scb261** [comment]
Similar to #3071 (where they ask for play button for each manga, not just latest)

**Comment by alfaazian** [comment]
> Similar to #3071 (where they ask for play button for each manga, not just latest)

Yes but while that feature is useful for 1 or 2 chapter reading and each manga has its own button,
This will be a common button to all mangas in the current Category and will open/resume the last readed manga and will be more useful for when you are starting a new manga and have more chapters to read.

**Comment by arkon** [comment]
Sorry, but the History section already serves this purpose.

I'd rather not clutter the library.
