### ISSUE TITLE
[Feature Request]Show How much time you've invested reading manga in tachiyomi

### ISSUE THREAD

**Issue by himanshu03vsk** [tachiyomiorg/tachiyomi#3993]
It can be a timer which only starts whenever you open a chapter and you can see it whenever you open the settings tab
If possible it should avoid counting loading time(should ignore the loading time).

Also if this can be implemented for every manga(i.e shows the timer or time spent reading that particular manga on its title screen would be great)

# benefits
We can see how much time we've invested reading one particular manga or all the manga as a whole.

**Comment by arkon** [comment]
#115
