### ISSUE TITLE
[Feature Request] <Set time period before deleting cache>

### ISSUE THREAD

**Issue by Samy-darker** [tachiyomiorg/tachiyomi#4021]
---

## Why/User Benefit/User Problem

I think it would be nice if the user can set the amount of time before his app cache(chapter/pages) got deleted like hours/day or.. making it forced to be manually deleted only and stop auto-delete ,  

-why it should be added? 
Sometimes i used to check & read manga chapters or some pages online and then decide to get back in later and read it again when i missed something , 
So.. i noticed it does reload pages again its just anoying that the chapter pages u already been reading are getting deleted and must wait for them to load again,
    I know u would say its just to avoid storage problem but.. its also just consuming Data charges again and again for mobile data users, well i know it would be better if we read it using Wifi, but its also wasting time, hope my describing is clear. And thanks

## What/Requirements
Add option in settings to set periode time ⌚ before the app clears its chapters/pages Cache, 

also if its possible add option to stop auto-delete cach and switch to manually cache delete.

**Comment by arkon** [comment]
Cache is limited by size, not time. You're filling up the cache and evicting old content.
