### ISSUE TITLE
[Feature Request] Border crop options

### ISSUE THREAD

**Issue by ophixus** [tachiyomiorg/tachiyomi#4026]
## Why/User Benefit/User Problem

For webtoons, the crop borders option sometimes ends up cutting up text bubbles and images. For example:
 
![pixlr_20201110185222665](https://user-images.githubusercontent.com/74233360/98645365-f308e100-2385-11eb-8841-da90553ddbcf.jpg)

This seems to happen fairly often so I don't think it's specific to the webtoon/manga or its source. I think implementing extra options for the border crop tool would allow the user to control any unnecessary cropping (to some extent) and hence improve readability, especially for webtoons.

## What/Requirements

- Being able to toggle the border crop for horizontal borders only (i.e. it would get rid of the borders on the left and right of the image but not on the top or bottom)
OR
- Being able to specify the number of pixels you want cropped on the X axis and Y axis (i.e. override the auto border crop with a manual one)

**Comment by tripathi-abhishek** [comment]
@ophixus  Have you tried zooming in. That might help. Just double tap and it might adjust to readable zoom setting, you might not even need to crop.

**Comment by arkon** [comment]
Closing in favour of #4995.
