### ISSUE TITLE
[Bug] Once clicked, the sources tab scrolls up before opening the source

### ISSUE THREAD

**Issue by bsushmith** [tachiyomiorg/tachiyomi#4037]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Samsung M51

## Steps to reproduce
1. Open installed sources page
2. Click on anyone one of the source

### Expected behavior
The view should change to the source smoothly.

### Actual behavior
The view scrolls a bit up and then opens the manga source.

## Other details
This happens in the teeny amount of time between the source is clicked and its view is opened. But this UX feels a bit off, as it gives off the uncertainty whether one has clicked the right thing or not as the sources view changes before the manga source is opened. PFA recorded attachment. 

[Screen_Recording_20201116-005831_Tachiyomi.mp4.zip](https://github.com/inorichi/tachiyomi/files/5543024/Screen_Recording_20201116-005831_Tachiyomi.mp4.zip)

**Comment by arkon** [comment]
The transitions are janky because of the tab "animation", but I wouldn't consider this a bug.

Probably not going to change either, unless someone like @jobobby04 decides to tweak it more for 0.x.
