### ISSUE TITLE
I can't save panels from chapters

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi#4077]
## Device information
* Tachiyomi version: 0.10..5
* Android version: 10
* Device: oppo a5 2020

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Save the panel

### Actual behavior
It doesn't save.
![IMG_20201130_170029](https://user-images.githubusercontent.com/75262438/100625744-928a1580-332d-11eb-80b7-588bfc9ba047.jpg)

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
Not enough info.

- What's the source, manga, chapter, and page in your example?
- Does this happen for all sources/manga/chapters/pages?
- Does it error only when saving a page, or even when downloading chapters?
- Have you tried it on another device to see if it's just your device?
