### ISSUE TITLE
[Bug] issue downloading chapters with same name

### ISSUE THREAD

**Issue by jdw1023** [tachiyomiorg/tachiyomi#4092]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Nokia 6.1

## Steps to reproduce
1. First step
browse to `向阳素描` manga on dmzj
2. Second step
download chapters with same name e.g. 6.1卷(vol 6.1) (they are actually different parts of a volume) 

![image](https://user-images.githubusercontent.com/43763092/101276603-16079480-377c-11eb-9d5b-98e8677cd579.png)

### Expected behavior
should download successfully

### Actual behavior
download failed
![image](https://user-images.githubusercontent.com/43763092/101276746-ff157200-377c-11eb-85be-9d82ccfe7ca7.png)
![image](https://user-images.githubusercontent.com/43763092/101276752-105e7e80-377d-11eb-8f04-48518a59a1e4.png)

## Other details
some what related to https://github.com/inorichi/tachiyomi/issues/1893 however this time these chapters are not from multiple scanlators but are actually different parts of a volume so renaming directory to "${chapter.scanlator}_${chapter.name}" won't work.
https://github.com/inorichi/tachiyomi/blob/f762598c5c54bd8fcb9ff308af94715c9dc31c35/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt#L138

**Comment by arkon** [comment]
The name and scanlators are pretty much all we have to uniquely identify chapters. We could use the date, but that could change if the site decides to reupload things (which some do for no apparent reason).

Are those chapter names really correct? Why would the names be the same even if they're all part of the same volume?

**Comment by jdw1023** [comment]
> Are those chapter names really correct? 

on closer inspection, I think these chapter names are incorrect but they are what got returned from dmzj's api
![image](https://user-images.githubusercontent.com/43763092/101301540-26188600-3807-11eb-9f74-4e052082d024.png)

**Comment by arkon** [comment]
I don't think this is going to be handled because this isn't technically a valid usecase as chapters _should_ be unique if they're from the same source/scanlator.

The extension could potentially be updated to prepend the `chapter_order` value to make them unique.
