### ISSUE TITLE
[Feature Request] Cancel download from the chapter list

### ISSUE THREAD

**Issue by diogenesdirkx** [tachiyomiorg/tachiyomi#4098]
Today when there is a chapter "available offline" and a chapter "in queue" if both chapters are selected, the delete button is available, clicking on it will delete the chapter already downloaded and cancel what is in the queue.

When i select just a chapter "in queue" the the delete button is not avalible.

I would like the delete button to be available when I select chapters "in queue", maintaining the same behavior as when I select it together with a downloaded chapter.

**Comment by asdkant** [comment]
This used to be available and I'd also like the functionality back.

Also, muscle memory becomes useless when buttons change place, maybe grey them out instead of hiding them in a way that shifts the test?

**Comment by Bm12347** [comment]
Should be closed as it is available now

**Comment by Bm12347** [comment]
Also as a way to stop them you can long press the manga cover in library and choose to delete downloaded only
