### ISSUE TITLE
[Feature Request] Parallelize library updates by source

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#4103]
## Why/User Benefit/User Problem
Much like the benefits laid out in #3060, this would make updating the library faster, as currently even on a extremely fast network connection, a library update would take a long time to check each manga, i.e. a 1 Gbps connection and 1.2k manga still takes ~30 minutes to check for all manga. 
## What/Requirements
The feature would check multiple sites at once. In the progress notification, it could show the queue of each source it's checking at once. For people with slower networks, this could be optional.

**Comment by Riztard** [comment]
i think the new splitted source solve the problem? 🤔

**Comment by arkon** [comment]
Main app doesn't do parallel updates yet.

**Comment by Riztard** [comment]
so its not multisource issue to begin with? :/
