### ISSUE TITLE
[Feature Request] (UI) simplify download for single-chapter manga

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#4109]
## Why/User Benefit/User Problem
The download button opens up a combo box with options such as "download unread", "download all", etc., which is useful for multi-chapter manga, but if you only have one chapter this is useless because the only possible action is to download that single chapter.

## What/Requirements
Have that button straight up download the single chapter when there is a single chapter, otherwise keep the current behaviour.

**Comment by arkon** [comment]
This is addressed by #3039
