### ISSUE TITLE
[Feature Request] easier way to search more by the same author/artist

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#4110]
## Why/User Benefit/User Problem
From time to time I want to search more manga by the same author/artist, which is a cumbersome process because I have to copy the author/artist name, go back to the search page for the same source, open the filter, then add the name on the corresponding field.

## What/Requirements
Have some way to jump straight from a manga's page to a search of manga by the author/artist in the same source. Maybe make the long-press open a menu offering both copying the name and searching more.

This could also be applied to other pieces of metadata. possible issue would be the limitations of how the source can be searched.

**Comment by scb261** [comment]
You already can tap author/artist name and it will open global search. As for the filed - it's not possible in 0.x, see #3462
