### ISSUE TITLE
[Bug] 0.10.5 won't download app updates

### ISSUE THREAD

**Issue by GuyInDogSuit** [tachiyomiorg/tachiyomi#4115]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: LG G Pad 5

## Steps to reproduce
1. Go to the "More" tab and tap "About."
2. Tap "Check for updates" and "Download" when the changlog pops up.
3. Wait, and.... nothing happens.

### Expected behavior
The APK should download.

### Actual behavior
Nothing downloads. No error, either.

## Other details
I was able to update to 0.10.6 with no issues though. Sent the Github page to my tablet via Firefox's tab share feature, and installed it from there.

**Comment by scb261** [comment]
Do you have notifications from the app disabled? It should show download progress there

**Comment by GuyInDogSuit** [comment]
No, they're enabled. I did check the storage folders, and did not find any apks other than the one in the main downloads folder, which came from Firefox.
