### ISSUE TITLE
[Bug] History list jumps to top after delete

### ISSUE THREAD

**Issue by privatmamtora** [tachiyomiorg/tachiyomi#4118]
## Device information
* Tachiyomi version: 0.10.6
* Android version: 11
* Device: Mi Mix 2

## Steps to reproduce
1. Scroll down history
2. Delete item

### Expected behavior
It should return to the same position in the history list

### Actual behavior
User is returned to the top of the history list

**Comment by arkon** [comment]
I can't reproduce this. Does this happen for anyone else?

**Comment by Riztard** [comment]
only happen once, not sure if it has anything to do with "reset all chapter for this manga" checked. but only happen once so not sure if just a coincidence

**Comment by privatmamtora** [comment]
I tried it again for 0.10.7, still happening.
I don't check the "reset all chapters"

**Comment by arkon** [comment]
I'm willing to bet that this is yet another issue specific go MIUI/other Chinese phones.

**Comment by privatmamtora** [comment]
I am running crDroid 7.1, so no MIUI.
I will reflash rom and try a clean install

**Comment by arkon** [comment]
Can't reproduce.
