### ISSUE TITLE
Reading mode not saved when adding new manga

### ISSUE THREAD

**Issue by Husbug** [tachiyomiorg/tachiyomi#4120]
## Device information
* Tachiyomi version: 0.10.16
* Android version: 9
* Device: Honor View 10

## Steps to reproduce
1. First step
Browse new manga, start reading one, change reading mode (e.g to webtoon)
2. Second step
Add new manga to library to save it. Restart reading it, reading mode has returned to default

### Expected behavior
Reading mode stays as webtoon after adding to library

### Actual behaviour
Manga reading mode reverts to default

## Other details
Additional details and attachments.

**Comment by CrepeTF** [comment]
You can change the default reading mode in `More > Settings > Reader`

**Comment by arkon** [comment]
Can't reproduce.
