### ISSUE TITLE
[Bug] loading icon on individual manga doesn't disappear on timeout.

### ISSUE THREAD

**Issue by PennyJim** [tachiyomiorg/tachiyomi#4125]
## Device information
* Tachiyomi version: App version: 0.10.6 (standard, 45ca470, 52)
* Android version: 10 (SDK 29)
* Android build ID: QPM30.80-63-6-8
* Device brand: motorola
* Device manufacturer: motorola
* Device name: sofia
* Device model: moto g power
* Device product name: sofia_retail

## Steps to reproduce
1. Find a manga in your library with its parent server down
2. Individually reload the manga

### Expected behavior
When the timeout notification appears, the loading icon should disappear

### Actual behavior
The loading icon stays indefinitely (or at least for too long)

## Other details
I'm not actually sure of the status of the parent server. All I know is the requests for that specific manga timed out.

**Comment by arkon** [comment]
Probably not relevant after Compose changes.
