### ISSUE TITLE
[Bug] Manga pages render too small in size

### ISSUE THREAD

**Issue by theimpulson** [tachiyomiorg/tachiyomi#4131]
## Device information
* Tachiyomi version: 0.10.7 | 0.10.7-2893
* Android version: 11.0
* Device: Nokia 6.1

## Steps to reproduce
1.Open Tachiyomi & Try to read some manga

### Expected behavior
Images should be rendered fullscreen

### Actual behavior
Images appear too small

## Other details
- Logcat while reproducing the issue: https://paste.ubuntu.com/p/HpF37ZXmXG/
- I am using a Custom ROM called LineageOS: [Website](https://www.lineageos.org/), [GitHub](https://github.com/LineageOS/), [Downloads](https://download.lineageos.org/PL2)
- I am also the maintainer of the said ROM. I would love to help to debug this issue if my assistance is required.
- Video reproduction of the said issue: https://drive.google.com/file/d/1ELBONmgMCU0YYQurVGWKl0V42uGHDSqP/view?usp=sharing

**Comment by theimpulson** [comment]
I am not sure what happens when the manga image is loaded but as manga thumbnails render just fine, maybe it is possible to use the same technique to render manga images as well.

**Comment by theimpulson** [comment]
Just tried Shonen Jump and ManagaZone apps, both are able to render images properly.

**Comment by arkon** [comment]
Likely relevant: https://github.com/davemorrissey/subsampling-scale-image-view/issues/505

I believe Sync for Reddit uses the same library, so you could test in that too.

**Comment by theimpulson** [comment]
Just tried, it seems to be affected as well but images are still visible a bit (probably because of the enormous size). Images that are not large like around (<1000*something) appear small and I am unable to zoom in even a bit. Images having a large resolution than that are rendered properly but I still can't zoom a lot (a bit zoom is possible if the image is around 4000/3000*something).

While using the app: https://drive.google.com/file/d/1fDO3GKHUrvghyS6mG6TBKotUPZBFIH5v/view?usp=sharing

Just to make sure,  I downloaded the same images on the device from the reddit app and viewed them via Gallery. They were visible like normal images and allowed me to zoom more than the app did.

**Comment by arkon** [comment]
The referenced library repo has a sample app that can also be used for testing it.

It's very likely that your screen density isn't correct (maybe something in `build.prop`?).

**Comment by theimpulson** [comment]
So, I looked into screen density as per your hint and it is fine. I notice that the referenced library uses [DisplayMetrics](https://developer.android.com/reference/android/util/DisplayMetrics) to get screen density information. When used on devices running a custom ROM, this device seems to be returning:

```
DisplayMetrics{density=2.625,width=1080,height=1920,scaledDensity=2.625,xdpi=4.031,ydpi=4.031}
```

As you can notice xdpi and ydpi are being reported terribly wrong when compared with the density. Same xdpi and ydpi are reported as 403.174 and 403.174 respectively on the stock OS. I am unable to find any satisfactory reason why this happens on the framework side unless the responses given by hardware changes on non-stock OS.  If I am right, the library uses xdpi and ydpi to scale the image and set dpi limits. is it possible for you to add an if-else statement that might compare the density and xdpi and ydpi and uses the other one to scale images in case another one is terrible small?

**Comment by theimpulson** [comment]
Just to be sure, I confirmed that density is reported fine even when checked via `adb shell` commands.
[Imgur](https://i.imgur.com/0Ih3ZaK.png)

**Comment by arkon** [comment]
You'd need to file a bug with the library so that it's fixed there since it's ultimately not an issue with the app itself.

You can reference the new issue here so we can keep track of it though.

**Comment by theimpulson** [comment]
So, I managed to figure a bad fix for this issue from my device side. In case someone else comes here looking for a fix for this issue, please read my comment here: https://github.com/davemorrissey/subsampling-scale-image-view/issues/536#issuecomment-745772687

Closing this issue for now. Thanks for your help on referencing the library which helped me to figure what was actually wrong in the API.
