### ISSUE TITLE
[Feature Request] More Automatic Backup options

### ISSUE THREAD

**Issue by Doomoocloo** [tachiyomiorg/tachiyomi#4137]
More automatic backup options, such as:
1) back up after every chapter read
2) back up on specific days/hours
3) back up after custom amount of hours/minutes

**Comment by ChillHorse** [comment]
I would like an additional option to include the $device_name as prefix or suffix in the backup file.

My reasoning for this is that I use tachiyomi on two devices and it's backup file to import titles that I added on the go. I use a cloud service to sync the backup directory between both devices but I never know which came from which device without actually importing or doing _diff_ in a terminal

**Comment by arkon** [comment]
#1 is overkill, #2 is a bit non-trivial to do with the existing WorkManager dependency (it doesn't allow precise timing), #3 is relatively close to what already exists anyway.

#6248 covers the ability to externally trigger a backup creation.
