### ISSUE TITLE
Download line moves back and forth

### ISSUE THREAD

**Issue by Signum21** [tachiyomiorg/tachiyomi#4144]
## Device information
* Tachiyomi version: 0.10.7
* Android version: Oxygen OS 10.5.9 (Android 10)
* Device: Oneplus Nord

## Steps to reproduce
Download update from notification bar

### Expected behavior
Only one line should move forward

### Actual behavior
It switches between two lines until one of them ends

## Other details
Video of the issue - https://imgur.com/a/lRwLpnL

**Comment by arkon** [comment]
Yeah it's definitely janky since it's doing parallel downloads but the notification logic was never updated.

**Comment by arkon** [comment]
Closing in favour of #7492
