### ISSUE TITLE
[Bug] reader gets stuck on continues vertical mode.

### ISSUE THREAD

**Issue by AriaMoradi** [tachiyomiorg/tachiyomi#4146]
## Device information
* Tachiyomi version: 10.7
* Android version: Q
* Device: Galaxy A50

## Steps to reproduce
1- Open 1 page manga entry on TwoKinds source(Keenspot extension)
2- Set reader to continues vertical mode
4- scroll down a few chapters
5- try to scroll up
6- the reader gets stuck trying scroll up to chapter spacer(if that's what we call it).

### Expected behavior
Scrolling up and down should work. 

### Actual behavior
Explored in steps to reproduce

## Other details
- This only happens in portrait mode. 
- I think it's actually caused when there is a current chapter, next chapter and the spacer between them all visible, then trying to scroll up to see the spacer between the current and previous chapter it gets stuck. somehow we either cant show more than 2 chapters or the more than one chapter spacer.
- This probably should also happen with chapters that have more than 1 page on devices that have really long aspect ratios.

**Comment by CarlosEsco** [comment]
#3749

**Comment by AriaMoradi** [comment]
@CarlosEsco 
This might be different, but if you say so...

**Comment by CarlosEsco** [comment]
I would just add this info to it.  IIRC it might something to do with the image size when there are shorter images it can mess up the reader
