### ISSUE TITLE
HTTP error 400: on adding manga to MyAnimeList Tracker

### ISSUE THREAD

**Issue by willyreza** [tachiyomiorg/tachiyomi#4147]
## Device information
* Tachiyomi version: 0.10.7 (stable)
* Android version: 10
* Device: Samsung M11

![Screenshot_20201216-215816_Tachiyomi](https://user-images.githubusercontent.com/3974476/102365439-232d4a80-3fea-11eb-9fe9-af9d32b46583.jpg)

**Comment by CrepeTF** [comment]
Go to webview, click on MAL profile, and relogin

**Comment by CarlosEsco** [comment]
clear cookies in advanced, then relogin to mal

**Comment by willyreza** [comment]
Ok

**Comment by willyreza** [comment]
Not work.

**Comment by willyreza** [comment]
Not work please

**Comment by AriaMoradi** [comment]
@willyreza 
join our discord to get support https://discord.gg/tachiyomi
