### ISSUE TITLE
[Bug] Can't update from 0.10.5

### ISSUE THREAD

**Issue by griffinevans** [tachiyomiorg/tachiyomi#4148]
---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 11
* Device: Pixel 3

## Steps to reproduce
1. When I check the about screen there is no option to check for updates. The list is Version, Build Time, What's new, then a divider, and then Website, Discord, etc. 
2. When I download the apk from github and try to install, it says "failed to install" 

## Other details
Maybe in would work if I updated through F-Droid?

**Comment by arkon** [comment]
If you installed the Fdroid version, you have to wait for the Fdroid update. There's no guarantee on when that is.
