### ISSUE TITLE
[Bug] <Cannot read / download paid chapters>

### ISSUE THREAD

**Issue by Arekkusu1998** [tachiyomiorg/tachiyomi#4149]
Most of the chapters of many Manhwa/Manhua/WebToon platforms are only visible following the payment of a fee (tokens' system): it's necessary to ensure that Tachiyomi can also access the blocked chapters so we can read / download them.

**Comment by CarlosEsco** [comment]
If you login to the source and buy the chapters, are they not visible now on a chapter refresh inside Tachiyomi?

**Comment by AriaMoradi** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5165
@CarlosEsco

**Comment by CarlosEsco** [comment]
Tachiyomi does not and will not try to bypass paid chapters.  
You need to buy them if the source requires that to be an option. 
there are no plans to natively allow buying chapters from sources.  
If you have bought the chapters, logged into webview in tachiyomi, and the chapters still don't show.  Then that is a source specific issue

**Comment by Arekkusu1998** [comment]
I understood: sorry but I really had to ask. I don't have money to buy the chapters of a manhwa that interests me a lot, so I was hoping for a solution.
Thanks anyway.
