### ISSUE TITLE
Unable to update MyAnimeList from app but can load info from MyAnimeList

### ISSUE THREAD

**Issue by Joshua011203** [tachiyomiorg/tachiyomi#4150]
I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.7)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

## Device information
* Tachiyomi version: Stable 0.10.7
* Android version: Android 10
* Device: Samsung A30

## Steps to reproduce
1.open tracking
2.refresh

### Expected behavior
chapters read and rating and reading/completed/on-hold should update

### Actual behavior
HTTP error 400

## Other details
nope

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4147

**Comment by willyreza** [comment]
Not work
