### ISSUE TITLE
[Feature Request] Restore backups from other applications

### ISSUE THREAD

**Issue by Alex10082005** [tachiyomiorg/tachiyomi#4151]
If a person wants to switch to tachiemi after using other applications, he will want to transfer his library, if he has been using it for a long time, then his library will be quite extensive, and it will be difficult to transfer it manually
Add the ability to restore a backup from the kitsune app.  This function will be useful for those who are switching from the kitsune app to tachiemi

**Comment by CarlosEsco** [comment]
There are no plans to support restoring from other non tachiyomi based apps

**Comment by CrepeTF** [comment]
Paperback backup support when Cesco : risitas2:
