### ISSUE TITLE
[Feature Request] Click on icon of manga when migrate shows more info about it

### ISSUE THREAD

**Issue by ArmeF97** [tachiyomiorg/tachiyomi#4152]
When migrating a manga from a source to another, there is the list of mangas to migrate. My feature request ask to create the ability to click on the image of the manga and see more info about it, so I know better of it and can choose better which source I will migrate that manga to

## Why/User Benefit/User Problem
Easier migration

## What/Requirements
Read above or ask any questions, I'll update this post

**Comment by CrepeTF** [comment]
You can hold tap it

**Comment by ArmeF97** [comment]
@CrepeTF  doesn't work. I can make a video if you want

**Comment by CrepeTF** [comment]
@ArmeF97 
????
https://streamable.com/9z8kco

From Stable 0.10.7

**Comment by ArmeF97** [comment]
@CrepeTF  that is not the section I use 


https://user-images.githubusercontent.com/6240983/102809025-973c6980-43c1-11eb-8f91-b9981299afe4.mp4

**Comment by arkon** [comment]
It's the same thing.

**Comment by CrepeTF** [comment]
Also update your app

**Comment by ArmeF97** [comment]
> 
> 
> Also update your app

I know the lates is 0.10.7

But I have the f-droid version, and I can't update, signature check fails. I'll update to 0.10.7 when it will be available for f-droid



> It's the same thing.

It's not? At 00:04 in my video, you can see that I tried to long press, but it didn't work. I wanted to display full info about that manga, but instead I only could click to search in other sources to migrate to

**Comment by CrepeTF** [comment]
you're supposed to hold at the 0:06-ish screen

**Comment by ArmeF97** [comment]
> 
> 
> you're supposed to hold at the 0:06-ish screen

No, I wanted more info on the item I'm migrating from, not the item I'm migrating to

**Comment by ArmeF97** [comment]
@CarlosEsco now that we all understand that I'm asking for something that it's in the app yet, can you open this issue? Thanks
