### ISSUE TITLE
[Feature Request] extension id -> extension pkg conversion

### ISSUE THREAD

**Issue by AriaMoradi** [tachiyomiorg/tachiyomi#4153]
## Why/User Benefit/User Problem
When a extension has some favorite mangas saved and get's removed, when user open's the manga, extension id is shown instead of it's name, and if the user has no backups and doesn't remember the extension name they are left with installing random extensions until they get one right.

## Possible solutions
1- The app can hold a database of which extensions it has seen.
2- There can be a database made inside/alongside the extension json and the app can use it. This solution won't work if a extension is removed from the extensions repo.

**Comment by arkon** [comment]
Closing in favour of #4904 (of which this would be a requirement, but that one better captures the need).
