### ISSUE TITLE
[Feature Request] option to disable system wide search in tachiyomi

### ISSUE THREAD

**Issue by AbdelO** [tachiyomiorg/tachiyomi#4155]
Hey there, first of all I've been a happy user of this app for God knows how long. However I've noticed a nifty and in my eyes very intrusive feature: the system wide "search in tachiyomi" option. I'd like it if this was a. Optional thing, because I find it rather intrusive on the levels on how Microsoft sneaked bing search through their app on android a while back. 

![Screenshot_20201219-104507](https://user-images.githubusercontent.com/8789983/102686338-47a24600-41e7-11eb-92ea-b7d87c3c4455.jpg)

See screenshot for example. I am using the most recent version of Android 11(OxygenOS) on my Oneplus 8 pro.

**Comment by arkon** [comment]
No. It's not really sneaking, apps just rarely implement this feature.

**Comment by AbdelO** [comment]
> No. It's not really sneaking, apps just rarely implement this feature.

I think you are missing the entire point of my post: It is a request, to make it optional. I'm one of the people, who don't really have a use for this feature. Nor can I recall this actually being requested at all.

**Comment by arkon** [comment]
Sorry, I didn't really expand but no, it's not possible to make it optional.

**Comment by AbdelO** [comment]
> Sorry, I didn't really expand but no, it's not possible to make it optional.

Alright, thank you anyway! As I stated before, love the app. :)
Keep up the good work.

**Comment by ObserverOfTime** [comment]
I'm not particularly fond of this new feature either.
I think using the sharing menu to search would have been better.

**Comment by hugwalk** [comment]
This is still bothering me everytime I see it, can't it be implemented in share menu (Share text to Tachiyomi to search) instead of always showing in context menu?
