### ISSUE TITLE
[Feature Request] Add "reload page" button...

### ISSUE THREAD

**Issue by borrougagnou** [tachiyomiorg/tachiyomi#4159]
Add "reload page" button...

I downloaded a manga, but I have some white page (not appear in the website)
so, is it possible to add "reload" button for reload/redownload the page correctly?

also I have that in multiple page: ![img](https://cdn.discordapp.com/attachments/349436576037732355/790085058068873216/IMG_20201220_061525.jpg)

![img2](https://cdn.discordapp.com/attachments/349436576037732355/790085236771782666/IMG_20201220_061624.jpg)

So, without this kind of button it's really difficult to fix all of this, and the experience is degraded...

**Comment by Lohit244** [comment]
This is usually caused by the source website having images like this. Reloading doesn't usually solve this, i'd recommend switching to vertical mode in the reader to make the lines less noticable

**Comment by borrougagnou** [comment]
I found a solution to solve this...
delete chapter - redownload the chapter... (same if the chapter have 130p...)

and no, the problem is caused by tachiyomi...

**Comment by arkon** [comment]
It's rare to ever want to replace individual pages of a downloaded chapter, so not worth the effort of implementing this. As noted, there's a relatively easy way to replace a downloaded chapter already.
