### ISSUE TITLE
[Bug] Animated Gif Lag

### ISSUE THREAD

**Issue by Xeiniac** [tachiyomiorg/tachiyomi#4162]
## Device information
* Tachiyomi version: Preview r2903 (7ae5c3b2)
* Android version: Android 8.1
* Device: Mi Pad

## Steps to reproduce
1. Open series
2. Open chapter with gif

### Expected behavior
Smooth gif playback after it's been loaded

### Actual behavior
Gif is really slow and choppy even when it loops after the first time

## Other details
Additional details and attachments.
It's the same on stable and TachiyomiSY however the playback is smooth on TachiyomiJ2K on the same device.

**Comment by arkon** [comment]
Closing in favour of #4193
