### ISSUE TITLE
[Bug] App crashes when updating/refreshing tracker

### ISSUE THREAD

**Issue by dtrazzi** [tachiyomiorg/tachiyomi#4165]
## Device information
* Tachiyomi version: 0.10.7-2903
* Android version: 10
* Device: Samsung SM-G960U

## Steps to reproduce
1. Go to tracker on the manga page
2. Refresh or update tracker (in my case, MyAnimeList)

### Expected behavior
Tracker updates

### Actual behavior
App crashes, no chapter read or tracker update

## Other details
Also happens if "update tracker after reading" is turned on. Not sure if this is a MyAnimeList-specific problem.

**Comment by arkon** [comment]
1. Did you try relogging into MAL from settings?
2. If you did, can you try setting up the tracking the manga again?

**Comment by dtrazzi** [comment]
Huh, re-logging seems to have fixed it. Strange.

**Comment by arkon** [comment]
Yeah, MAL was rewritten again in the latest preview build. I should've forced a logout.

**Comment by giosann** [comment]
A force log-out is needed since it also crashes the app when you arrive to the last page on a Manga tracked on myanimelist.

**Comment by arkon** [comment]
It will for the stable build for sure. Preview builds are meant to find bugs from people willing to test and report them.

**Comment by antocs** [comment]
It happened to me too, I can confirm re-syncing MAL solved it.

**Comment by arkon** [comment]
Closing this since 2909 forced a log out.
