### ISSUE TITLE
[Bug] MAL tracker does not work after the latest update (0.10.7)

### ISSUE THREAD

**Issue by SayalHajare** [tachiyomiorg/tachiyomi#4167]
Device information
Tachiyomi version: Stable 0.10.7
Android version: Android 8.0 Oreo
Device: Honor RNE-L22
Steps to reproduce
Go to tracking settings
Log into MyAnimeList
Expected behavior
The MyAnimeList tracker should start tracking manga episodes.

Actual behavior
The MyAnimeList tracker doesn't show that you're logged in. If you open webview, you'd be logged in.

Other details
Screenshots: https://imgur.com/a/JkhAMc4

**Comment by arkon** [comment]
Did you wait for the WebView to close by itself after logging in, or did you manually close it?

**Comment by SayalHajare** [comment]
It does not close by itself. I kept it open for a while, but it stays open as it is.

**Comment by arkon** [comment]
This will be fixed in the next release.

Closing to keep the issue list somewhat manageable.
