### ISSUE TITLE
[Bug] MAL search failing to find some manga titles

### ISSUE THREAD

**Issue by Aedyrn** [tachiyomiorg/tachiyomi#4168]
## Device information
* Tachiyomi version: Preview r2903
* Android version: 5.0

## Steps to reproduce
1. Search for one of the manga listed bellow to track them in tachiyomi.

### Expected behavior
Provided the name is listed on MAL it should be displayed on the list of manga available.

### Actual behavior
Despite using the exact same name whilst searching for match, some manga will not appear. To be clear I think most manga do show up only some, for some reason, do not.

## Other details
I've made certain to have the name exactly as they are on MAL, and have tried the english, romaji, and japanese titles. I can find them fine either through the android browser(bromite) or pc browser.
Here are the links I've found so far, but there are probably more.

https://myanimelist.net/manga/22207/Kanojo_no_Kagi_wo_Akeru_Houhou
https://myanimelist.net/manga/115796/Yuki-neechan_no_Kannou-gokko
https://myanimelist.net/manga/109840/Peter_Grill_to_Kenja_no_Jikan
https://myanimelist.net/manga/124797/Jikan_Teishi_Yuusha
https://myanimelist.net/manga/126798/Ushiro_no_Shoumen_Kamui-san

##
![3](https://user-images.githubusercontent.com/35850104/102739251-83065700-4344-11eb-968c-f92e8d54206c.jpeg)
![1](https://user-images.githubusercontent.com/35850104/102739243-7eda3980-4344-11eb-873a-3d5b80c07c42.jpeg)

**Comment by arkon** [comment]
Well that's certainly unfortunate. It's just calling the official search API now.

**Comment by arkon** [comment]
The workaround is to search for `my:####`, where the number is the ID from the entry on MAL (which you can see in the URL).
