### ISSUE TITLE
[Bug] Tracking does not auto-update

### ISSUE THREAD

**Issue by Osyx** [tachiyomiorg/tachiyomi#4174]
## Device information
* Tachiyomi version: 0.10.7-2903
* Android version: 11
* Device: OnePlus 8 Pro

## Steps to reproduce
1. Use tracker that isn't the new MAL api, e.g. I'm using MAL, AniList and Kitsu
2. Enable 'Update chapter progress after reading'
3. Read manga, and after last page expect all to have updated to the latest chapter #.

### Expected behavior
All services should have the latest # synced.

### Actual behavior
Only MAL has updated.

## Other details
I have logged out and re-logged in again on both of the other services and it still happens.

**Comment by arkon** [comment]
This is already fixed in r2909.

**Comment by Osyx** [comment]
Ah nice, thanks, missed the commit.

**Comment by Osyx** [comment]
@arkon The trackers after MAL seems to lag behind in chapter tracking, is that something that is being fixed by going over to coroutines, or should I open another issue for it?

**Comment by arkon** [comment]
Open another issue if it still persists after this Saturday's build.

**Comment by Osyx** [comment]
Okay, will check!

**Comment by Osyx** [comment]
Have tried it for a bit, and it seems to work as expected now. 👍
