### ISSUE TITLE
[Feature Request] <Latest version is not on the f droid repository, license info for extensions>

### ISSUE THREAD

**Issue by peryngveohlin666** [tachiyomiorg/tachiyomi#4178]
## Why/User Benefit/User Problem
(explain why this feature should be added)
The apk version on f-droid at the moment is 0.10.5 which means it doesn't sync to my anime list if it would be more regularly updated that would be beneficial as we wouldn't have to use github to get the latest apk. Except than that if there was more information regarding the licenses of extensions that are offered that would be more suitable as people wouldn't have to check the repos for them before downloading those extensions as there are -free software only- users alike.
## What/Requirements
more frequent updates plus maybe a notice on top of the extensions or an info button next to the extension that pops up information about the license/what the extension website is like that would be beneficial for the users.

**Comment by arkon** [comment]
We don't control the speed of releases on F-Droid. We don't advocate using it because of that reason.
