### ISSUE TITLE
[Bug] When migrating a Manga with a very long name, 3 dots are added to the name, causing the manga not to be located

### ISSUE THREAD

**Issue by luzfcb** [tachiyomiorg/tachiyomi#4179]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: Xiaomi Redmi Note 5

## Steps to reproduce
1. Select a Manga that has a very long name
2. Click in the 3 dots icon and select Migrate
3. The Manga cannot be located because it contains 3 dots characters at the final of the string, forcing the user to manually edit the search text and remove the 3 dots to search return the expected results.

### Expected behavior
When migrating a Manga with a very long name, the 3 dots should not be added to the manga name to locate the manga.

### Actual behavior
When migrating a Manga with a very long name, 3 dots are added to the name, causing the manga not to be located.

**Comment by arkon** [comment]
Do you have a video of this behaviour? Are you sure you're not just misguided by the truncated text in the non-search UI title?

**Comment by luzfcb** [comment]
@arkon the video https://youtu.be/E5giZA9nYfo

**Comment by arkon** [comment]
Do you have another example? That manga title in your library literally ends with "..." for whatever reason.

**Comment by luzfcb** [comment]
@arkon 
is there any way to debug and check how exactly the manga title is saved in the local database?  perhaps it may be that for some reason the title is being saved and / or obtained with the three dots, and then this could be a problem with one of the extensions I use, or with the data source itself.  If you give me the instructions, I can debug this via adb or any other way that you indicate.

**Comment by scb261** [comment]
The app shows full title on manga info page, so you have titles saved with three dots for some reason. If anything, it's the extension problem, but it's fine on my end. Maybe you added it with older extension version or when the site had issues. 

Try updating the manga by pulling down on manga info page (the one where you can see the chapter list). If this doesn't help, then you'll need to remember/note how many chapters you've read, remove the manga from library, Settings > Advanced > Clear database, add the manga back to library, mark chapters as read and add trackers.

But considering you want to migrate them, it would be easier to just remove the three dots while migrating, as you did in the video.

**Comment by arkon** [comment]
What he said ^
