### ISSUE TITLE
Delete in the local 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#4184]
I recently have been using the local source and discovered a problem, after I finished reading the manga and remove it from my storage it still stays in the local source. I would like a delete or remove button in the local source to prevent that

**Comment by arkon** [comment]
You need to fully close the app for it to "recheck" the disk. The app does that to avoid excessive disk reads, which are very slow.

**Comment by zayin02** [comment]
> You need to fully close the app for it to "recheck" the disk. The app does that to avoid excessive disk reads, which are very slow.
> 
> EDIT: I'm assuming you also removed it from your library too.

I did but it still there

**Comment by arkon** [comment]
Did you actually force close the app?

**Comment by zayin02** [comment]
Yes I did

**Comment by zayin02** [comment]
No matter what I try the deleted manga won't disappear from my local source

**Comment by zayin02** [comment]
It was also saved to my internal memory as well, I would still like something to help people that may have not understood how to get rid of it
