### ISSUE TITLE
[Bug] App wont start after installation (crashes before it can even load) (stable.ver.10.7)

### ISSUE THREAD

**Issue by confusion202** [tachiyomiorg/tachiyomi#4185]
---

## Device information
* Tachiyomi version: 10.7
* Android version: 9
* Device: Samsung S9

## Steps to reproduce
1. Install tachiyomi stable version from homepage.
2. Successfully launch the tachiyomi app.

### Expected behavior
Tachiyomi should not crash and launch normally.

### Actual behavior
It crashes within 2 seconds of pressing the app icon (rendering the app unusable).

## Other details
Additional details and attachments.
The tachiyomi unstable version works and so does tachiyomi J2K but the stable version isn't working. 

It does work on my Samsung S7 but not my Samsung S9, and I don't know what to do.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by confusion202** [comment]
I followed the first method, but what email do I send the report to? Also, what other information would I be sharing by sending this?

**Comment by confusion202** [comment]
I'm very sorry but I feel a bit uncomfortable sharing my phone logs over the internet. 

I'm sorry for being uncooperative with this, but since the issue still persists on my Samsung S9 I just wanted to let someone know it was happening.

Sorry again, and thank you.

**Comment by arkon** [comment]
Closing since logs aren't provided.
