### ISSUE TITLE
App stoped working

### ISSUE THREAD

**Issue by TheLamed** [tachiyomiorg/tachiyomi#4187]
## Device information
* Tachiyomi version: 10.7
* Android version: 7.0
* Device: Xiaomi Redmi Note 4X

## Steps to reproduce
try to load any information in the app

### Expected behavior
![image](https://user-images.githubusercontent.com/56411527/103127923-01902b00-469c-11eb-86f9-81a6ba81731d.png)
![image](https://user-images.githubusercontent.com/56411527/103127929-048b1b80-469c-11eb-8ce9-6d73c717fe04.png)
also webviw doesn`t work
![image](https://user-images.githubusercontent.com/56411527/103127940-1240a100-469c-11eb-8f54-181e83c32745.png)

### Actual behavior
I`ve didnt use app for 2 days, and today get this problem

**Comment by arkon** [comment]
There's something wrong with your network.
