### ISSUE TITLE
[Bug] Can't delete Tachiyomi's empty folders into BlueStacks Android Simulator

### ISSUE THREAD

**Issue by Arekkusu1998** [tachiyomiorg/tachiyomi#4188]
I installed the simulator BlueStacks 4.25 for Android.10 and, then, I installed Tachiyomi in its latest stable version, 0.10.7. I downloaded some manhwas and transferred their pages to my PC without problems, then I deleted the images; however, when it came to deleting the (now superfluous) folders containing the images, it wasn't possible.
In other words: the folders, stored into "**Explore**" - "**Tachiyomi**" folder - "**Downloads**" sub-folder, _how can they be deleted_?
Here is the screenshot showing where the "Tachiyomi" folder is located.
![01](https://user-images.githubusercontent.com/48092608/103134072-a74c9580-46ae-11eb-90ea-8fd0c4051881.png)
And here are the Sub-Folders that I would like to delete, now empty of the manhwas' pages saved.
![02](https://user-images.githubusercontent.com/48092608/103134075-b3385780-46ae-11eb-9c08-a2b261e87734.png)
Once I've transferred the images to the PC, I don't need dozens of empty folders and subfolders in the Android simulator. Please, can anyone help me? In BlueStacks these informations is stored in the "**sdcard**", but there's no folder with this name in my PC, not even in hidden files and folders.

**Comment by arkon** [comment]
Just delete them from there...?

**Comment by Arekkusu1998** [comment]
Sorry **@arkon**, but why did you close the problem? Too rushed.
Obviously I tried to delete them from there, but I can't at all: if I try "**Export**" + "**Select all**", and then throw them into "**Trash**", firstly they disappear, but right after BlueStacks tells me "**error while deleting the media**" (?) and all the folders reappear as soon as I reopen the "Tachiyomi" Folder.

**Comment by arkon** [comment]
This isn't an issue with Tachiyomi, it's an issue with Bluestacks.

**Comment by Arekkusu1998** [comment]
I understand. Poor me ... I'm at the starting point: I don't even know where to write. Uff!
