### ISSUE TITLE
[Bug] Setting > Reader > Webtoon > Crop Borders applies to all reading modes

### ISSUE THREAD

**Issue by Noriller** [tachiyomiorg/tachiyomi#4191]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: motorola one

## Steps to reproduce
1. First step - Turn it on/off

### Expected behavior
Expected to work only when "readind mode" is set to "webtoon"

### Actual behavior
Applies "crop borders" ~~in all reading modes~~ also in continuous vertical.

## Other details
Could be an option per reading more or one for webtoon and another for "others".
Since I've started reading webtoons I tough it was some problem with with the conversion that made the edges not align, afterwards realized that it was the crop border option.
But the option is nice on some others, since it cuts "useless space", so an option to have this on all but webtoons would be nice.

**Comment by arkon** [comment]
By "all reading modes", do you mean just Webtoon and continuous vertical?

**Comment by Noriller** [comment]
Actually yes, been using continuous vertical instead of vertical so long that didn't remember that.
Changed there.

**Comment by arkon** [comment]
This is intended. See #3657 for the request to make it per series.
