### ISSUE TITLE
[Feature Request] All in One Widgets

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#4192]
![Screenshot_20201226_175245](https://user-images.githubusercontent.com/65703094/103149304-35a24380-47a3-11eb-84b3-c5b731ae4d9b.jpg)

Having Many Tachyomi Forks.. Quite Difficult To Handle... I Think that Im Not the Only One who Uses One Tachiyomi App
And I think That Having Tachiyomi Widgets Is A Good Idea..
**The Widget Has The Ability..**
- Check Latest Updates For All Forks 
- Check For Latest Chapters For All Forks
- BackUp
- Clear Cache/Cookies/Refresh Tracking/etc.

Feel Free to Close (This is Just a Shower Thought 😂)

**Comment by ImPudding-tech** [comment]
IF Youre Curious Why I Have Different Fork... THIS is My Reason
TACHIYOMI PREVIEW - All  NonFantasy Manga
Tachiyomi - Manhwa
Tachiyomi Az - R18 DOUJINSHI Manga
TachiyomiSy - R18 Manhwa
NEKO - FANTASY MANGA

**Comment by shashank-p** [comment]
You can create multiple categories in single fork which will solve your problems

**Comment by ImPudding-tech** [comment]
WELL This Is How I Category... 
![Screenshot_20201226_204426_eu kanade tachiyomi](https://user-images.githubusercontent.com/65703094/103151688-4b236780-47bb-11eb-8b7d-c6c8c7b6d437.jpg)

If Create Multiple Categories... It will mess up my Bookshelf
Because I have Almost 45-50 Manga Per Categories...

**Comment by arkon** [comment]
This is out of scope, especially because we do not support forks.
