### ISSUE TITLE
Use Coil for image loading

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#4193]
We currently use Glide, but Coil seems to offer better performance based on anecdotal feedback from J2K/Neko users in the context of viewing GIFs.

**Comment by NotTsunami** [comment]
It would be nice to see some benchmarks supporting this, benchmarks from last year seem to contradict this. I understand Coil is still relatively newer though, so perhaps it has improved.

**Comment by arkon** [comment]
I did say it's anecdotal, but there's been some instances like #4162 and on Discord where people have said the same thing.

#2875 was another attempt at improving GIF performance using another library.

This is all in the context of GIFs though. The earlier benchmarks that I saw were generally based on "normal" images, but I'm not sure if those rankings have changed over time.

It's worth noting that 1.x already uses Coil anyway.

**Comment by CarlosEsco** [comment]
@NotTsunami fyi performance doesn't really matter.  The image loading library isn't used for the reader.  So it's basically only used for cover loading.

**Comment by arkon** [comment]
@CarlosEsco It's used for GIFs in the reader.
