### ISSUE TITLE
Update f-droid version

### ISSUE THREAD

**Issue by wuniversales** [tachiyomiorg/tachiyomi#4194]
Please, Update f-droid versión...

**Comment by Soitora** [comment]
We don't release to F-Droid and haven't for almost two years now. Take this up with the people hosting the unofficial one or simply download Tachiyomi like normal.

**Comment by CrepeTF** [comment]
We don't control the frequency of updates to the F-Droid version.

Backup your data,
Uninstall F-Droid version,
Install the GitHub version,
Restore.

**Comment by arkon** [comment]
> We don't release to F-Droid and haven't for almost two years now. 

There is, but we don't really control it.

If you need to expedite it, please open an issue in the F-Droid Gitlab.
