### ISSUE TITLE
[Feature Request] <Add webview function in tracking settings>

### ISSUE THREAD

**Issue by LunaticHatter** [tachiyomiorg/tachiyomi#4199]
## Why/User Benefit/User Problem
It's impossible to add tracking for MAL accounts created through google because, the moment the user tries to login with google, error 403 disallowed_useragent will come up.

## What/Requirements
A button to enable webview in the top right of the screen when you are in the tracking service page might do the trick.
\
\
\
Basically I can't add my MAL account in the tracking settings; I believe my suggestion could fix the problem but I don't really know how the app interacts with google and what code you would need to write to fix the issue, so if anyone has a better idea on how to solve this, please go ahead. Thanks for the help!

**Comment by ghostbear** [comment]
This is fixed with the MAL rewrite, currently available on the preview build
