### ISSUE TITLE
[Feature Request]Zoom tweak 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#4203]
I've come across an annoying thing while zooming. If I zoom in with 2 fingers then double tap it zoom in more, I would like it to zoom out instead. Please please can someone do that for me

**Comment by arkon** [comment]
You can just double tap and drag up/down to control the zoom, which is standard Android behaviour.

**Comment by zayin02** [comment]
> You can just double tap and drag up/down to control the zoom, which is standard Android behaviour.

I know that

**Comment by zayin02** [comment]
Just try what I was saying and you'll understand

**Comment by arkon** [comment]
I do understand, but this won't be implemented because you can already use the standard behaviour as a "workaround".

**Comment by zayin02** [comment]
> I do understand, but this won't be implemented because you can already use the standard behaviour as a "workaround".

😪Even so, I do think it should be implanted
