### ISSUE TITLE
[Bug] <App Crashed When Reading in Offline Mode With Update Chapter Progress After Reading in the Tracker Setting Enabled>

### ISSUE THREAD

**Issue by HaruSasaki** [tachiyomiorg/tachiyomi#4207]
## Device information
App version: TachiyomiSY 1.4.1 (standard, 4b3d92a05, 12)
Preview build: 319
Android version: 8.1.0 (SDK 27) 
Android build ID: LAVA_iris88_2_16_S101_IDR_18F13
Device Name: Lava Iris88

### Expected behavior
Go to the next chapter.

### Actual behavior
App stopped.

## Other details
When I enable update chapter progress after reading in the tracking setting, the app getting crashes every time go to the next chapter. This bug only happens when reading in offline mode after downloading the chapter.

I know i'm use TachiyomiSY, but the people in discord say Tachiyomi Preview have a same issue.

**Comment by CarlosEsco** [comment]
Can you download Tachiyomi preview and verify it is a bug in that version.

**Comment by scb261** [comment]
Can confirm, I was the one who said that it happens on Tachiyomi Preview as well. Happens with both MAL and AniList (tested separately)
```
[12-28 14:42:48.258 13798:13844 D/libc-netbsd]
getaddrinfo: api.myanimelist.net NO result from proxy 
[12-28 14:42:48.282 13798:13829 E/ACRA]
ACRA caught a UnknownHostException for eu.kanade.tachiyomi.debug

[12-28 14:49:40.777 14596:15207 D/libc-netbsd]
getaddrinfo: graphql.anilist.co NO result from proxy 
[12-28 14:49:40.820 14596:14627 E/ACRA]
ACRA caught a UnknownHostException for eu.kanade.tachiyomi.debug
```
