### ISSUE TITLE
[Feature Request] Please add synchronization with https://mangalib.me 

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4209]
I want you to make sure that reading a magician from the reading app has been transferred to my account. 

---

## Why/User Benefit/User Problem
This will be much more convenient for me and other users. 

## What/Requirements
Status about reading or adding a manga will be sent to the user's page

**Comment by arkon** [comment]
Do you mean mangalib.me? It doesn't even load for me. Is it a source or a tracker?

**Comment by MM001-r** [comment]
https://mangalib.me that's it.

**Comment by arkon** [comment]
You didn't answer the second question. The website 404s for me.

**Comment by MM001-r** [comment]
With a VPN in Russia, try
This is a site that loads manga and there are many tights that are frequently updated.

**Comment by arkon** [comment]
A Mangalib extension already exists.
