### ISSUE TITLE
[Feature Request] i hope the function of download unread will be back

### ISSUE THREAD

**Issue by Yanskie007** [tachiyomiorg/tachiyomi#4210]
I hope the download unread button will be back so hard to manually tap the chapter 1 by 1. Especially when it has a 500 chapter and you already read the 200 and now you cant download all cause you read 200chapter already . The only way is download all and unselect the 200 chapter and it takes a lot of time and tapping. Please 🥺 consider getting back the download unread chapter.. thank you 🙏

**Comment by CarlosEsco** [comment]
you can long press chapter 201 then long press chapter 500 and that will select all in between.

**Comment by Yanskie007** [comment]
Thank you 👌 this help a lot ❤️

**Comment by scb261** [comment]
Also, the unread option is still there
![2](https://user-images.githubusercontent.com/65343233/103217651-c6069280-4921-11eb-8017-5a4bc59fddc5.png)

**Comment by Yanskie007** [comment]
It was at the top in the right corner download button. I didn't see it last time.. thank you so much❣️
