### ISSUE TITLE
hitomi.la pages not loading

### ISSUE THREAD

**Issue by Yuricchi** [tachiyomiorg/tachiyomi#4212]
## Device information
* Tachiyomi version: 0.10.7
* Android version: Android 10
* Device: Xiaomi Mi 9T

## Steps to reproduce
1. Open hitomi.la (set with a single language and that is English)
2. Enter tags/scroll a bit down and open any desired doujin
3. 98% of them are stuck on "Retry"

## Issue/Request
Most doujins stuck on "Retry" even after clearimg cache and cookies

## Other details
None

**Comment by CarlosEsco** [comment]
please read the template next time.  This is the wrong repository for source issues, and this is a duplicate.
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/4679
