### ISSUE TITLE
[Feature Request]  Detect and store Urls that have changed

### ISSUE THREAD

**Issue by wolfhowling** [tachiyomiorg/tachiyomi#4213]
## Why/User Benefit/User Problem
Mangabox mangas change source URL too frequently and as someone that keeps track of more than 100 mangas that update infrequently is often hard to detect whether the manga has not updated or the source has changed without going directly to it and refreshing it manually which is harder to detect with greater numbers. I often find myself by chance looking at a new manga to read in the latest updated section just to see that there is the same manga there that's not in my favorites which is also an indication that the source has changed.

## What/Requirements
One idea would be in the updates history page to have a tab that also records the URLs without a valid source from the last check that way we will know which ones need to be migrated to the new source.

**Comment by Seishirou101** [comment]
the extension already does this, you have to enable update errors in options and update your library afterwards.

**Comment by wolfhowling** [comment]
Thanks that helps a lot.
