### ISSUE TITLE
[Bug] Long press options hidden behind "add to library" pop-up

### ISSUE THREAD

**Issue by Sekuiya** [tachiyomiorg/tachiyomi#4214]
## Device information
* Tachiyomi version: v0.10.7
* Android version: 9
* Device: Samsung Galaxy S8

## Steps to reproduce
1. Browse a manga currently not in your library
2. Download a chapter of said manga (the "Add manga to library" pop up should show up) 
3. Long press a chapter

### Expected behavior
Long press options should appear. 

### Actual behavior
Long press options hidden behind "add to library" pop-up.

**Comment by arkon** [comment]
You should swipe away the "Add manga to library" snackbar if you don't intend to do it.

**Comment by lsequeiraa** [comment]
> 
> 
> You should swipe away the "Add manga to library" snackbar if you don't intend to do it.

Today I learned that you can swipe that away.
Since it looks so much like the long press menu, and you can't swipe that one away, I think it simply never occurred to me that you could swipe that one.

**Comment by Sekuiya** [comment]
Today I learned that you can swipe that away.
Since it looks so much like the long press menu, and you can't swipe that one away, I think it simply never occurred to me that you could swipe that one.
