### ISSUE TITLE
[Bug] <Not really sure if this is a bug but I came across this issue where I can't read Black Clover no matter the chapter>

### ISSUE THREAD

**Issue by Eeyyernnnng** [tachiyomiorg/tachiyomi#4215]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: Samsung S10+

## Steps to reproduce
1. Open tachiyomi app
2. Open MangaHere 
3. Open Black Clover

### Expected behavior
open Black Clover and load up

### Actual behavior

Didn't open and couldn't load

## Other details
Additional details and attachments 

![Screenshot_20201229-124842_Tachiyomi](https://user-images.githubusercontent.com/53168496/103266766-4c3adb80-49eb-11eb-8275-0fc3aeb86ef5.jpg)

**Comment by scb261** [comment]
It's not a problem with the app, but with the extension, see https://github.com/inorichi/tachiyomi-extensions

Also it works fine for me, maybe it was temporary, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems)
