### ISSUE TITLE
[Bug] Backup doesn't open 

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4216]
The backup is not unpacked

---

## Device information
* Tachiyomi version: 010.7
* Android version: 9
* Device: honor 9 lite
![Screenshot_20201229_113334_eu kanade tachiyomi](https://user-images.githubusercontent.com/71752683/103270841-ec800880-49c9-11eb-9493-9253789ab49c.jpg)

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
In what version of the app did you create the backup? What version of backup are you trying to restore, `.json` or `.proto.gz`? Are you sure that backup file isn't corrupted?

**Comment by MM001-r** [comment]
I created a backup, and then I stopped an app that didn't work properly. Version 0.10.7

**Comment by MM001-r** [comment]
.json In this format, a backup file

**Comment by MM001-r** [comment]
I think because of the application's malfunction, it created a backup with an error.

**Comment by scb261** [comment]
If it's json, then you can open it with any text or json editor to check it. You need to create a new backup if old one was corrupted. The reason could be battery optimizer. Disable it, check out https://dontkillmyapp.com/ , also try to go to the developer settings in your phone and deactivate the Don't Keep Activities option.

**Comment by MM001-r** [comment]
That's it, my whole manga has gone off, and the old backup has only been in my place since September, which means that my library is almost empty and I don't know which chapters I've stopped at.
