### ISSUE TITLE
[Bug] <Restoring Backup Not Working>

### ISSUE THREAD

**Issue by Zuccuvae** [tachiyomiorg/tachiyomi#4217]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: Galaxy Tab S6 Lite

## Steps to reproduce
1. Install all the extensions at the time of backup.
2. Go to Backup setting and choose the backup file.

### Expected behavior
Selects the backup file and restores all the informations.

### Actual behavior
Backup file can't be clicked at all.

## Other details
I was using another Tablet when I made the backup file.
I didn't use any Tracking services when I made the backup file.
I didn't have any manga saved nor did I have any MangaDex account when I made the backup file.

**Comment by scb261** [comment]
Try using different file manager

**Comment by Zuccuvae** [comment]
I finally able to solve it!
