### ISSUE TITLE
[Bug] <page only loads after going back to chapter select>

### ISSUE THREAD

**Issue by Robonau** [tachiyomiorg/tachiyomi#4226]
---

## Device information
* Tachiyomi version: 0.10.7
* Android version: 7.1.2
* Device: memu (emulator)

## Steps to reproduce
1. read a manga/webtoon
2. page won't load (i have them downloaded so it's not that it can't get em from the site)
3. to make it load go back to chapter select and resume

### Expected behavior
it should load

### Actual behavior
i never loads without going back to chapter select

## Other details
Additional details and attachments.
this happens with any site (even local, though much less)
video of it happening in a webtoon 

https://user-images.githubusercontent.com/30987265/103421295-7a5b1f80-4b93-11eb-8303-863bc980605d.mp4

**Comment by arkon** [comment]
This seems like an issue specific to the emulator you're using, so I doubt anyone will be trying to investigate this.

**Comment by Robonau** [comment]
it's the same in a bunch of different emulators (bluestacks, ldplayer are the ones ive tried)
