### ISSUE TITLE
[Feature Request] Update history delete

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#4228]
In the update section there is no delete button or way to delete the update history.

Its takes up unwanted data overtime please add this feature

**Comment by arkon** [comment]
> Its takes up unwanted data overtime

What?

**Comment by zayin02** [comment]
I just want a way to delete the update history

**Comment by arkon** [comment]
That doesn't make sense, it's literally just getting all your library chapters and sorting them by recency.

**Comment by zayin02** [comment]
I didn't know that, my bad
