### ISSUE TITLE
[Feature Request] <Insert from which source a manga belongs in the backup restore error logs>

### ISSUE THREAD

**Issue by otakuprograma2020** [tachiyomiorg/tachiyomi#4230]
## Why/User Benefit/User Problem
When a user has the same manga added in several sources and will restore the backup on another device, errors can occur and as it is only indicated which manga and which error, it is difficult to know which source that manga belongs to

## What/Requirements
Basically it would be put in the backup restore error log to which source belongs that manga that error occurred when restoring the backup

**Comment by otakuprograma2020** [comment]
why?

**Comment by arkon** [comment]
It was added in 3bb2102eb46af2ae2c03e505ade2512666b5cc91, as the issue timeline states.

**Comment by otakuprograma2020** [comment]
Was it added in version 10.6?

**Comment by arkon** [comment]
It'll be in the next stable release.
