### ISSUE TITLE
[Feature Request] Force reading mode for tags

### ISSUE THREAD

**Issue by Bexa2** [tachiyomiorg/tachiyomi#4234]
It would be nice if the lecture mode changed automatically to webtoon or continuous vertical if the tags "webtoon", "korean" or "long strip" are present.

This could be hard-coded as an option or maybe we could assign tags or sources and tags to a reading mode.

**Comment by scb261** [comment]
Duplicate of #1664

**Comment by Bexa2** [comment]
Closing this for #1664
