### ISSUE TITLE
[Feature Request] Add Scroll Up/ Down to S Pen Air Gestures as Next/ Previous Page does not work in Landscape 

### ISSUE THREAD

**Issue by kalinskym** [tachiyomiorg/tachiyomi#4235]
This is a feature request to add "Scroll Up/ Down" to S Pen Air Gestures. I've seen you have "Next Page" and "Previous Page" which while it's great to have when in portrait orientation.

It does not work correctly in landscape orientation. As when you use "Next Page" or "Previous Page", it goes to beginning of the page. It cuts off the bottom section of the page, when it moves to the next/previous page. As reader does not realise the page is cut off due to not fitting on the screen. Only fix is scrolling up manually which defeats the purpose of using the function which exists on S Pen now.

An easy solution seems to be adding a Scroll function to S Pen Air Gestures.

I hope you do consider this. The same function occurs when you use volume keys as well, if you need to test this out. It moves to next page however does not scroll so it misses out the bottom page of previous page which could not fit on the screen

This be a large help to those who want to not touch their devices. Thank you for reading this.

**Comment by kalinskym** [comment]
![Uploading Screenshot_20210103-002802_Air command.jpg…]()

**Comment by arkon** [comment]
Effectively the same as #2161.
