### ISSUE TITLE
Recommendation system

### ISSUE THREAD

**Issue by 01Moonlight** [tachiyomiorg/tachiyomi#4239]
# Why:
-To help people to find more manga from their own genre. 
#User benefit:
-Less time searching for a new manga. 
-More time reading without problems. 
#User Problem:
-Wasting time on websites searching for new manga. 
## What/Requirements
-at the end of the Manga main page they can find some Manga recommended by the system with the same Manga genre or writer.

**Comment by scb261** [comment]
Duplicate of #376
