### ISSUE TITLE
Can't load the Image, on Hentai Nexus

### ISSUE THREAD

**Issue by lolruler** [tachiyomiorg/tachiyomi#4245]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 6.0
* Device: redmi note 8 po

## Steps to reproduce
1. First stepq
2. Second stepq

### Expected behavior
is was working a month or less before
### Actual behavior
HentaiNexus is opening its site but cant open any mange not cant even download

its SHOWS (BAD BASE 64)

## Other details
plz fix it( BAD BASE 64)

**Comment by Bm12347** [comment]
You should close this issue
As the site owner requested its removal

**Comment by scb261** [comment]
1. Just as the bot mentioned in #4243 and #4244, it's wrong repository
2. As said above and in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475 , HN won't be added back
