### ISSUE TITLE
[Bug] COCO manhua decryption failed

### ISSUE THREAD

**Issue by EricFoodTab** [tachiyomiorg/tachiyomi#4246]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: vivo v11

## Steps to reproduce
1. when i want to read the manhua

### Expected behavior
It will normally load into the manhua

### Actual behavior
it says decryption failed when i try to read the manhua

## Other details
![Screenshot_2021-01-04-18-26-50-263_eu kanade tachiyomi](https://user-images.githubusercontent.com/70044043/103529325-6c254000-4ec0-11eb-8525-cb46a686cb14.jpg)

**Comment by scb261** [comment]
Wrong repository, I just noticed that bot in Discord gives wrong link. Here is the right repository https://github.com/tachiyomiorg/tachiyomi-extensions
