### ISSUE TITLE
能否支持自定义页码下载

### ISSUE THREAD

**Issue by Yofo-me** [tachiyomiorg/tachiyomi#4247]
下载漫画是能不能自定义页码范围，比如说我只想离线一个漫画的第200到最后一章，我不需要全部离线观看

**Comment by arkon** [comment]
Google Translate:

> Can support custom page number download

> Can I customize the page number range for downloading comics, for example, I only want to offline the 200th to the last chapters of a comic, I don’t need to watch them all offline

**Comment by arkon** [comment]
You can select chapters to download.

You can not select pages within chapters to download.
