### ISSUE TITLE
[Bug] MAL search tracking problems (potentially NSFW related?)

### ISSUE THREAD

**Issue by Aedyrn** [tachiyomiorg/tachiyomi#4249]
## Device information
* Tachiyomi version: 2059
* Android version: 5.0

Opening new issue as requested.
So due to the tracking search issue with MAL I went through the about 500 manga I have on tachiyomi looking for a pattern for which ones you can and cannot find. Eventually I noticed that 99% of them were tagged as "ecchi" on MAL and the ones that weren't clearly were ecchi but had not had their tags updated, and most of the ones that were ecchi but I _could_ find were newer entries that I assumed had not been properly updated. So I checked the API page and noticed the NSFW section had this there:

https://myanimelist.net/apiconfig/references/api/v2#section/Common-parameters

> **Not Safe For Work**
By default, some APIs don’t return nsfw content.
You can control this behavior with the `nsfw` parameter.

And manga details responses had an nsfw tag I can't see on their website.

>`"nsfw": "white",`

Considering everyone of the manga I couldn't find had some amount or frequently focused on fanservice, including relatively major ones like [Yuragi-sou no Yuuna-san](https://myanimelist.net/manga/96582/Yuragi-sou_no_Yuuna-san), I assume this means some manga are tagged as NSFW, and this is making them get filtered. This including both explicit 18+ ones and fanservice-y ones.

Now assuming this is the case (my assumption), I don't know what the correct answer is as really all of those I can't find certainly aren't SFW.

Something like **(NSFW)** [Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?](https://myanimelist.net/manga/111770/Kawaikereba_Hentai_demo_Suki_ni_Natte_Kuremasu_ka) is certainly NSFW just based off of the MAL cover alone.

Maybe something like a setting or using an `nsfw:` tag as a means of searching with nfsw content on and still having it by default off?
Then again I'm pretty sure iirc Anilist tracking provides all manga as a response, including 18+ ones, so maybe just having nfsw content always on would be better. Ideally I think internally they should have an explicit tag in addition to nsfw to separate ecchi, from outright porn but that's just me.

If this indeed the problem not sure what should be done as I can see some reasons why it would be a problem (ie:undermines parental controls if there is no option because you can find 18+ titles due to similar names without filter)

Not exactly a programmer so feel free to correct me if I said something dumb.

**Comment by arkon** [comment]
Turning on the NSFW option for the search API did indeed surface Yuragi-sou no Yuuna-san at least.

You're right that other trackers (at least Anilist and Kitsu) by default show (censored) NSFW content too, so it's at least on par with those.

We haven't added any sort of configuration for trackers but maybe it's something we could eventually consider down the road, but I feel like the tracker stuff generally "just works" and people forget about it after setting them up.

**Comment by Aedyrn** [comment]
To me personally the nsfw settings aren't really important, just thought that should be added as a potential problem because using anilist iirc it sometimes gave me some, uh, interesting results next to some slice of life manga due to sometimes similar names, so it could be a concern for the future.
