### ISSUE TITLE
[Bug] Circle progress bars not animating.

### ISSUE THREAD

**Issue by Aedyrn** [tachiyomiorg/tachiyomi#4251]
## Device information
* Tachiyomi version: r2959
* Android version: 5.0

## Steps to reproduce
Go to catalogue or tracking, when the results begin loading the progress bar won't animate.

https://user-images.githubusercontent.com/35850104/103631067-7421c600-4f3a-11eb-9d30-53bcebd7a1c1.mp4

## Other details
It's just a visual bug works fine otherwise. Appeared in r2903 preview build I believe. Was not present in previous preview build, and works as expected on stable 0.10.7. Maybe Android version problem?

**Comment by arkon** [comment]
This was a bug upstream: https://github.com/material-components/material-components-android/commit/46d8fbadf88b0e2fdf7138170dffda5048928676
