### ISSUE TITLE
[Bug] Webtoon reading mode

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#4259]
## Device information
* Tachiyomi version: Preview r2959 (updated earlier today)
* Android version: 10
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Open a webtoon in webtoon mode.
2. See some pages are weirdly adapted.

### Expected behavior
It shouldn't be this weird, last time i read the webtoon in the screenshot was December 28 and it was fine.

### Actual behavior
Some pages don't adapt to the adjacent ones, it seems vertical mode shows them fine, same going webview.

## Other details
webtoon read mode
![Screenshot_20210105-205457_Tachiyomi](https://user-images.githubusercontent.com/22413659/103693298-5b94c880-4f99-11eb-9959-f47418b5972c.jpg)
vertical read mode
![Screenshot_20210105-205449_Tachiyomi](https://user-images.githubusercontent.com/22413659/103693302-5c2d5f00-4f99-11eb-94e9-a0759eae11d9.jpg)

**Comment by antocs** [comment]
Another proof just in case
![Screenshot_20210105-210413_Tachiyomi](https://user-images.githubusercontent.com/22413659/103693451-9991ec80-4f99-11eb-8d46-3304910afb3d.jpg)

**Comment by scb261** [comment]
turn off _Crop borders_ option

**Comment by inorichi** [comment]
This should be fixed too with the new decoder.

**Comment by inorichi** [comment]
Well, not quite, I misunderstood the issue. Border cropping will work like that on webtoon viewer, so it's better to keep it disabled there.

**Comment by antocs** [comment]
I wanna point out that I never touch reading options, so "border cropping" has always been enabled and never gave me problem before, but yes, disabling it solved the issue.

**Comment by arkon** [comment]
It's disabled by default:

https://github.com/tachiyomiorg/tachiyomi/blob/7192b264024f23e71723ae989ac57a0602f6fc03/app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt#L122-L124
