### ISSUE TITLE
[UX] Multiple comics add/remove catalog, not rewrite

### ISSUE THREAD

**Issue by quangkieu** [tachiyomiorg/tachiyomi#4260]
**App version:** 0.10.7

**Android version:** 10

**Issue/Request:**
Add/remove catalog of multiple comics, not rewrite

**Steps to reproduce (if applicable)**

 1. Set one comic in both A, B catalogs
 2. Set another comic in both A, C catalogs
 3. Select both comics, the catalog menu would show A checked
 4. Now add catalog D
 5. Both comics now have tag A, D but none of them have catalog B or C

**Expected:**
Tag menu has catalog A checked, indicate common catalog, but B and C should be filled square to indicate uncommon catalog between comics.
When i add a catalog for both comics, it should add a catalog to multiple comics, not rewrite all of their categories to new values
Same for remove a common/uncommon catalog

**Other details:**

**Comment by arkon** [comment]
Is the same thing as #961?
