### ISSUE TITLE
[Bug] Read and unread chapters are indistinguishable on e-ink devices

### ISSUE THREAD

**Issue by basileus-sys** [tachiyomiorg/tachiyomi#4261]
Issue: On E-Ink devices read and unread chapters are indistinguishable, both in manga chapter lists and in the "updates" tab. 
![image](https://user-images.githubusercontent.com/52258368/103710565-9c023f80-4fb5-11eb-9b9f-a002635422e6.png)

It would be nice if there was some kind of symbol indicating the status of each chapter. Here is a suggested solution:
![image](https://user-images.githubusercontent.com/52258368/103713102-b8a17600-4fbb-11eb-9e49-4c4e26f5bb77.png)

## Device information
* Tachiyomi version: 0.10.7
* Android version: 8.0
* Device: Likebook Mars

**Comment by joseph619** [comment]
The checkmark will be used for downloaded chapters, if you have tried the latest preview build. So a duplicate checkmark for read/unread would be confusing and/or likely not possible.

**Comment by basileus-sys** [comment]
Bummer, I guess another symbol would be needed or the "open book" symbol could be used for both partially read chapters completed with just the former/both with a page counter

**Comment by CarlosEsco** [comment]
temp fix would be just to hide read in the filter.  But yea this definitely is an issue.  It seems there is no "grey scale"

**Comment by orangpelupa** [comment]
> The checkmark will be used for downloaded chapters, if you have tried the latest preview build. So a duplicate checkmark for read/unread would be confusing and/or likely not possible.

But on the chapter list page, downloaded chapters was indicated by "downloaded" text on the right side. It doesn't use iconography. 

So... Can the text be added with more stuff? Like... 

Read, downloaded (for downloaded chapter that was already read)

Pardon my English

**Comment by joseph619** [comment]
> > The checkmark will be used for downloaded chapters, if you have tried the latest preview build. So a duplicate checkmark for read/unread would be confusing and/or likely not possible.
> 
> But on the chapter list page, downloaded chapters was indicated by "downloaded" text on the right side. It doesn't use iconography.
> 
> So... Can the text be added with more stuff? Like...
> 
> Read, downloaded (for downloaded chapter that was already read)
> 
> Pardon my English

Check the preview build, downloaded text will be replaced by check mark icon next stable update.

**Comment by Jigoku-r** [comment]
I have the same problem.
It would be nice to have some kind of icon that automatically appears near the chapter name when you're done reading it.

**Comment by arkon** [comment]
I'm thinking a dot to the left of unread chapters' titles?

**Comment by CrepeTF** [comment]
Could use a filled and outlined circle

**Comment by vengiare** [comment]
If semibold text for unread (google messages/gmail) is too ugly, yeah a dot to the left would be a good pick.

**Comment by Jigoku-r** [comment]
> I'm thinking a dot to the left of unread chapters' titles?

That sounds good. If the dot is thick enough (like a small circle. I think it might look good on e-ink screens. I can test it on my device if you need tests
