### ISSUE TITLE
[Bug] <some pages mainly manhwas don't load in the reader>

### ISSUE THREAD

**Issue by Bm12347** [tachiyomiorg/tachiyomi#4264]
## Device information
* Tachiyomi version: r2990
* Android version: 10
* Device: samsung a31

## Steps to reproduce
Open a manhwa if it loads try with another
The page loads but the image doesn't
It worked well in the previous preview version and is still working well in 0.10.7
## Other details
It works well in webview
I have tried with many sites and manhwas
Also it appears in left to right and right to left and vertical modes
It seems that the problem is in webtoon and continuous vertical modes
Additional details and attachments 
![A Returner's Magic Should Be Special - Chapter 129 - 2.jpg](https://user-images.githubusercontent.com/66433732/103751228-a1d93e80-5010-11eb-9749-f77eccec854b.jpg)![Screenshot_20210106-111714_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/103751319-c7664800-5010-11eb-851c-37ad2538a467.jpg)
This is from vertical mode
![Screenshot_20210106-122617_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/103758107-66437200-501a-11eb-895a-62e60b51a63d.jpg)

**Comment by inorichi** [comment]
Do you have crop borders enabled? If so, does turning them off make a difference?

**Comment by Bm12347** [comment]
> Do you have crop borders enabled? If so, does turning them off make a difference?

No I don't have it enabled 
And enabling it does not make a difference

**Comment by inorichi** [comment]
Which source are you using? I'd like to take a glance at the source image

**Comment by Bm12347** [comment]
> Which source are you using? I'd like to take a glance at the source image

This image is from mangakakalot
A Returner's Magic Should Be Special 
Chapter 129

**Comment by tobiena** [comment]
Same here some pages are not loading while other ones whole episode just blank but when you try it at webview it loads properly

**Comment by inorichi** [comment]
Pushed a fix. There should be a new release shortly.

**Comment by inorichi** [comment]
Fix is now available. Closing.
