### ISSUE TITLE
[Feature request] enable face recognition biometric unlock

### ISSUE THREAD

**Issue by ptoump** [tachiyomiorg/tachiyomi#4265]
## Device information
* Tachiyomi version: latest preview
* Android version: 10
* Device: samsung galaxy tab s7

## Steps to reproduce
1. Enable security lock
2. Enable biometric unlock 

## Issue/Request
Only fingerprint is available, where for example in bitwarden you can choose face unlock (during the unlock progress) 

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
I looked briefly at the Bitwarden code. It seems like it's using Xamarin, so there's an additional abstraction over the AndroidX biometric library, except it's using an older version.

AFAIK newer versions of the library actually "better" enforce what you're allowed to use based on some security levels that they've defined, and I think they've reclassified things between strong and weak levels. I suspect whatever Samsung put in their device is now considered weak.

I could potentially just enable weak biometrics though.
