### ISSUE TITLE
[Bug] Not all extensions show in an emulator(eg. nox player)

### ISSUE THREAD

**Issue by waptik** [tachiyomiorg/tachiyomi#4266]
## Device information
* Tachiyomi version: ?
* Android version: 7.1?
* Device: Nox Player v6.6.1.5?

## Steps to reproduce
1. First step: [Download Nox Player](https://www.bignox.com/en/download/fullPackage?beta) and install it
2. Second step: Open a browser and install tachiyomi
3. Third step: Open Tachiyomi, tap the browse tab and goto extensions.

### Expected behavior
All extensions available on the extensions repo or [the website](https://tachiyomi.org/extensions/) should show in extensions tab.
### Actual behavior
Only extensions installed, extensions with english language and all catgegory show up. No chinese or extensions in other languages show up

## Other details
Additional details and attachments.

https://user-images.githubusercontent.com/1687551/103768061-afdf8d00-5019-11eb-88dd-f1cdc12dfd95.mp4

**Comment by Bm12347** [comment]
There should be a tab like this![20210106_143558.jpg](https://user-images.githubusercontent.com/66433732/103769268-aca1cc80-502c-11eb-80c2-71c92a30fa15.jpg)![Screenshot_20210106-143341_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/103769271-af042680-502c-11eb-89c4-ce1ef2288fb8.jpg)

**Comment by waptik** [comment]
Sorry, i missed that.
Thanks
