### ISSUE TITLE
[Feature Request] add an option to enable or disalbe showing the title when sharing a page

### ISSUE THREAD

**Issue by trowaw** [tachiyomiorg/tachiyomi#4269]
## Why/User Benefit/User Problem
It is incredibly annoying and time-consuming to delete titles, especially very long ones, when sharing a page through social media apps e.g. WhatsApp.

## What/Requirements
A simple on/off button in the "reader" category in the options would suffice.
![Screenshot_20210107-112659_WhatsApp](https://user-images.githubusercontent.com/77101087/103881871-5344a680-50db-11eb-891f-5a7bc250b080.jpg)

**Comment by curche** [comment]
Previous discussion at #3846
