### ISSUE TITLE
[Bug] Opening Mangadex links doesn't show the manga.

### ISSUE THREAD

**Issue by thecloakmaster** [tachiyomiorg/tachiyomi#4270]
There was a recent md extension update and now whenever I open md links, it doesn't show the manga.
![Screenshot_2021-01-07-16-44-00-210_eu kanade tachiyomi](https://user-images.githubusercontent.com/51017498/103894122-e398e080-5107-11eb-8a95-6087e20a3b52.jpg) Here's an example.

**Comment by ghostbear** [comment]
Wrong repo
Also already reported: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5338
And have a fix on the way: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5345
