### ISSUE TITLE
[Bug] Crop Borders crops page content

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#4273]
## Device information
* Tachiyomi version: 0.10.7-2991 (standard, 7192b264, 54)
* Android version: 10
* Device: OnePlus 6T

## Steps to reproduce
1. Enable crop borders
2. Open chapter 14 of https://mangadex.org/manga/45580/ (e.g page 7)
3. Most pages have the left hand side of the speech bubbles cut off
4. Disabling crop borders reveals the remaining portion of the speech bubbles *and* the border padding

### Expected behavior

Crop should only go as far as the first non-white pixel

### Actual behavior

Crop is cropping content inside panel borders

## Other details

- Reading Mode: Default (Any)
- Scale Type: Fit Height (Any)
- Zoom Start Position: Right (Any)

#### Crop off, scrolled to far left of image

![Screenshot_20210108-064434.jpg](https://user-images.githubusercontent.com/3440094/103983900-0cf45380-517e-11eb-85c4-7770f9ce6c51.jpg)

#### Crop on, scrolled to far left of image

![Screenshot_20210108-064454.jpg](https://user-images.githubusercontent.com/3440094/103983905-1087da80-517e-11eb-963a-931c5f6f4e73.jpg)

#### Crop on, page transition

![Screenshot_20210108-064459.jpg](https://user-images.githubusercontent.com/3440094/103983908-12519e00-517e-11eb-8000-d99faab57900.jpg)

#### Crop off, page transition

![Screenshot_20210108-064510.jpg](https://user-images.githubusercontent.com/3440094/103983915-14b3f800-517e-11eb-92be-f7385a423091.jpg)

**Comment by inorichi** [comment]
Should be fixed by 365b849

**Comment by wopian** [comment]
Yup, fix working as intended on r3002 :tada:

**Comment by wopian** [comment]
@inorichi found another image that gets cut off on the left edge with crop borders on (cuts at the middle of the left most speech bubble)

Page 4 of Jashin-chan Dropkick, Chapter 131

https://mangadex.org/chapter/1213971/4

App version: 0.10.9-3121 (standard, 89837e4c, 56)

**Comment by wopian** [comment]
### Source image

![4-c384921597761b66a19a3c5a1703e92952a8af5b782d76dc6edfe5a7a60a577e.png](https://user-images.githubusercontent.com/3440094/108518128-2087f380-72c0-11eb-8294-e1d22178ef3f.png)

### Crop Borders enabled

(Swiping to next page from far left of image)

![Screenshot_20210219-143812.jpg](https://user-images.githubusercontent.com/3440094/108518166-2a115b80-72c0-11eb-85ac-b6f89461b1b2.jpg)

**Comment by inorichi** [comment]
I believe that version is using the old image decoder, can you confirm @arkon ?

I've tried this image on the one and it also crops more than it should, but a bit less somehow.

**Comment by arkon** [comment]
@inorichi It's using the new decoder: https://github.com/tachiyomiorg/tachiyomi/blob/89837e4cedca4fa0c7518c32cd13142ec85b5f97/app/build.gradle.kts#L207

**Comment by inorichi** [comment]
Uh, I misread the release notes of the preview version. Thought it was reverted too.

**Comment by inorichi** [comment]
I finally found the issue. Fixed on dev branch
