### ISSUE TITLE
[Feature Request] <add googleweblight  on tachiyomi>

### ISSUE THREAD

**Issue by julptk** [tachiyomiorg/tachiyomi#4274]
![2021_01_08_17 08 39](https://user-images.githubusercontent.com/56266781/104002875-3c35af80-51d4-11eb-8f31-4c52b6652a41.jpg)
hi sir, how to add googleweblight on tachiyomi?my phone jellybean rooted,thank you

**Comment by CarlosEsco** [comment]
please read the disclaimer before you post.   Extension requests belong in
https://github.com/tachiyomiorg/tachiyomi-extensions

**Comment by arkon** [comment]
Googleweblight is the data saver proxy used in Chrome. But no, the idea of funneling all of your data through Google sounds like a terrible idea for a FOSS app anyway.
