### ISSUE TITLE
[Bug] Long strips of comic not loading on latest preview build

### ISSUE THREAD

**Issue by rebelxd** [tachiyomiorg/tachiyomi#4275]
## Device information
* Tachiyomi version: 0.10.7-2990 (standard, 762f5bdc, 54)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190915.002
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: violet
Device model: Redmi Note 7 Pro
Device product name: violet
## Steps to reproduce
1. Open a webtoon with a long page in webtoon mode
2. (Small pages still load correctly)

### Expected behavior
Loads the images 

### Actual behavior
Black screen in webtoon mode, and very blurred images in vertical mode

### Vertical Mode screenshot of Mangahub/Take Me Out/40/2
![Screenshot_2021-01-08-18-47-53-553_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/77157176/104021497-ddc4fd00-51e4-11eb-9fbb-988e825cf78e.jpg)
### Webtoon Mode screenshot of the same
![Screenshot_2021-01-08-18-47-44-422_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/77157176/104021571-04833380-51e5-11eb-839e-315d64bfb83b.jpg)

**Comment by arkon** [comment]
Please update to r2991.
