### ISSUE TITLE
[Bug] [preview] Opening extension setting makes extensions list disappear

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi#4277]
## Device information
App version: 0.10.7-2991 (standard, 7192b264, 54) 
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.T865XXU4BTK2
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea

## Steps to reproduce
1. Open the "Browse" - "Extensions" tab
2. Open settings of any extension
3. Go back to extensions list

https://user-images.githubusercontent.com/10052873/104060947-fab6fb80-51f7-11eb-82a7-f7bde4141846.mp4

### Expected behavior
Extensions list shows

### Actual behavior
Extensions list does not show

## Other details
It fixes quickly going to any other first level tab (library updates history more) and going back

**Comment by arkon** [comment]
This will be fixed in the next preview build.

**Comment by giosann** [comment]
Fixed with latest build
