### ISSUE TITLE
[Bug] Chapter crashes when using Webtoon

### ISSUE THREAD

**Issue by MakiabelMFE** [tachiyomiorg/tachiyomi#4278]
## Device information
* Tachiyomi version: r2991
* Android version: 10
* Device: Xiaomi Redmi 5 Plus (vince)

## Steps to reproduce
1. Open chapter 123 from Doctor Elise (Mangakakalot source)
2. Set reading mode to webtoon
3. Scroll until a black box as if an image is missing appears and crashes the app.

### Expected behavior
Working in webtoon mode without crashing

### Actual behavior
Scroll and crash, had to change to vertical mode for it to work

## Other details

[Crash Log](https://del.dog/unonacrygh.txt)

**Comment by inorichi** [comment]
This was fixed on dedb8d2

**Comment by MxxS07** [comment]
> This was fixed on dedb8d2

I don't understand. How is it fixed?

**Comment by ghostbear** [comment]
> I don't understand. How is it fixed?

He fixed it in a code library we use to decoding images, which caused the crash 

Also, the fixed should be available in the new preview build released yesterday

**Comment by MxxS07** [comment]
> Also, the fixed should be available in the new preview build `r3002` released yesterday

Is the preview version better than the stable one?

**Comment by scb261** [comment]
https://tachiyomi.org/help/faq/#what-is-tachiyomi-preview

> What is Tachiyomi Preview?

> It's a weekly updated version of the app. It contains features that can be added to Tachiyomi in the future, but there is a higher chance for bugs. Tachiyomi Preview is used by developers and contributors to test the app and find bugs.

> If you are willing to use Tachiyomi Preview, be sure to [turn on auto-backup](https://tachiyomi.org/help/guides/creating-backups/#turning-on-auto-backups) to prevent losing your library due to potential bugs.

Refer to the site I linked or [Discord](https://discord.gg/tachiyomi) for more questions, since this is off-topic
