### ISSUE TITLE
[Feature Request] Show used extensions and unused in Extensions section

### ISSUE THREAD

**Issue by jedymatt** [tachiyomiorg/tachiyomi#4279]
## Why/User Benefit/User Problem
So the user can keep track of their extensions and decide to whether keep or uninstall their unused extension

## What/Requirements
Used extensions are those extensions that are used in your library. The used and unused extension should be in Extensions section. Alongside 'installed' and 'all'

**Comment by Matth7878** [comment]
It would be nice to have next to extension the number of manga you have in your library from them. (For both extensions and migrate tab)

**Comment by joseph619** [comment]
> It would be nice to have next to extension the number of manga you have in your library from them. (For both extensions and migrate tab)

This has irrelevant to the topic, open a new ticket for feature request

**Comment by Matth7878** [comment]
It is relevant as it would indicate which extension is used or not.
I don't really care and won't open an issue, it was just a suggestion to improve this feature request.

**Comment by wopian** [comment]
I too would prefer a count of the total entries associated with an extension to be the indicator of (un)used extensions rather than a "has (no) entries" label. 

I.e if an installed extension only has 2 entries linked to it, I would likely migrate them and uninstall the extension.

**Comment by haldi4803** [comment]
Why show that in the Extensions Section and not in the Migrate Section?
It would be awesome to have a "Source" on the Left side and on the right side "12 Mangas on this hoster"  thingy.

Do Extensions that don't have any mangas even show up in the Migrate tab?

**Comment by Matth7878** [comment]
@haldi4803 it could be shown into migrate tab (and I think it would be useful) but for this issue it has to be in extension tab because : 
- unused extension don't show in migrate tab (which seems logic)
- having this indication is what will help to decide if you want to uninstall extensions (which is what this issue has been opened for and uninstalling is only possible from extensions tab)

**Comment by arkon** [comment]
#6236 is probably more ideal, as suggested earlier in this issue.
