### ISSUE TITLE
[Bug] Occasional crashing before an automatic global update

### ISSUE THREAD

**Issue by Resaarts** [tachiyomiorg/tachiyomi#4280]
## Device information
* Tachiyomi version: Stable 0.10.7
* Android version: 7.0
* Device: SM-A310F

## Steps to reproduce
1. Wait for automatic global update
2. This isn't consistently reproducable, but is noticeable when I am using my phone during the crash

### Expected behavior
Shouldn't be crashing, stays open while a global update begins

### Actual behavior
Occasionally shows "Tachiyomi has stopped" error message, reopening immediately (or after a short period of time) and starting the automatic global update
The last 2 times I noticed this happened at the same time on 2 consecutive days, though prior to that, it happens more randomly and at different times of day

## Other details
Log file below pulled from my Android Bug Report 
[logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/5791970/logs.txt)

**Comment by arkon** [comment]
Those logs unfortunately don't contain a crash as far as I can tell. If it's still happening in v0.10.10, please open another issue with newer logs.
