### ISSUE TITLE
[Meta] read progress hooks

### ISSUE THREAD

**Issue by gotson** [tachiyomiorg/tachiyomi#4282]
# Why/Project's Benefit/Existing Problem
Currently Tachiyomi has tracking, but it requires to manually match mangas. 

Komga server has read progress management, per page and also per chapter. 

I would like Tachiyomi to provide some hooks to trigger some code from the extension whenever either a page is read, or a chapter is read. That way the extension could mark progress as read on the server directly. Since read progress is built in Komga, it wouldn't require any matching of mangas.

That would also play nicely with the multiple Komga servers (extension currently supports 3 servers).

**Comment by goldbattle** [comment]
Another possible approach is being able for extensions to request a list of what chapters have been read on startup (or maybe on manga detail request). This could then be sent externally / wouldn't require the main app to provide events to the extensions.

**Comment by gotson** [comment]
I think this could be closed, given we now have enhanced trackers that solve the initial problem.
