### ISSUE TITLE
[Bug] New Chapters will not download or view in app

### ISSUE THREAD

**Issue by SaintLamp** [tachiyomiorg/tachiyomi#4284]
---

## Device information
* Tachiyomi version: stable 0.10.7
* Android version: 9.0
* Device: Alcatel 1s

## Steps to reproduce
1. Attempt to download or open chapter of (seemingly only new) manga
2. 

### Expected behavior
Either download chapter for viewing or let view immediately

### Actual behavior
Instead errors when attempting either, with downloads it will fail to download and with viewing without downloading it will instead say retry on every page

## Other details
When viewing effected chapters via other browser 
(chrome for Android) I am able to see the chapter without any errors

Assumed effected sources and chapters (will update when on device more suited for typing):
Hanging out with a gamer girl , Mangadex latest chapter

**Comment by scb261** [comment]
Wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions

Works for me though, you probably have cached chapters from when Mangadex API was broken. Go to Advanced settings and clear chapter cache
