### ISSUE TITLE
[Feature Request] See manga cover in fullscreen

### ISSUE THREAD

**Issue by Signum21** [tachiyomiorg/tachiyomi#4285]
## User Benefit
Manga covers are small, it would be useful to be able to click on them and see them in fullscreen.

## What/Requirements
Click on a manga cover and see it as a single page chapter with the ability to zoom.

![Screen](https://user-images.githubusercontent.com/22285224/104207114-84e9a480-5430-11eb-9e77-48d45f6d2ab1.jpg)

**Comment by scb261** [comment]
Duplicate of #2130

**Comment by Signum21** [comment]
Sorry, closing
