### ISSUE TITLE
[Bug] Android 11 issues: slow downloaded flags and deletion

### ISSUE THREAD

**Issue by desmondk91** [tachiyomiorg/tachiyomi#4286]
## Device information
* Tachiyomi version: stable 0.10.7
* Android version: 11
* Device: Samsung galaxy note 10 plus

## Steps to reproduce
1. Lauch tachiyomi
2. Click on the manga in library
3. the unread downloaded content list is empty

### Expected behavior
The downloaded content should appears in the list

### Actual behavior
The downloaded content is empty for a couple minutes before showing up again. This issue will reoccur when reopen tachiyomi after some times.

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
Tachiyomi is not updated to properly handle Android 11's storage changes and likely won't anytime soon since it complicates things and will likely force us to remove things like custom locations.

**Comment by powermad80** [comment]
This happens to me too, but on Android 10. My phone (ASUS Zenfone 6) does not show this issue, but my tablet (Samsung Galaxy Tab S6 Lite) does. Downloaded content is very slow to appear after the app is launched. Both read from a custom location on external microSD storage, and I have swapped their microSD cards to test if it is a storage hardware issue, no change in behavior.

**Comment by arkon** [comment]
This is largely mitigated by better parallelizing download indexing and how download states are shown in the UI in more recent versions.
