### ISSUE TITLE
[Bug] <local cover disappear>

### ISSUE THREAD

**Issue by naxil** [tachiyomiorg/tachiyomi#4289]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.7)
- 

---

## Device information
* Tachiyomi version: 10.07
* Android version: android 10 color os 7.2
* Device: oppo a5 2020 

## Steps to reproduce
1. Add local manga with image 
2. Use tachiyomi for add cover.jpg or add it manually

### Expected behavior
Show cover

### Actual behavior
No cover at all

## Other details
Preview version show the cover, stable version not show the cover

**Comment by scb261** [comment]
Duplicate of #932. Solution in the comments

**Comment by naxil** [comment]
Yes thank you! U can delete this issue is redundant
