### ISSUE TITLE
White over chapter list

### ISSUE THREAD

**Issue by CCBETTER11** [tachiyomiorg/tachiyomi#4292]
App version: 0.10.7 (standard, c87ba62, 53)
Android version: 10 (SDK 29)
Android build ID: CLT-L09 10.0.0.171(C55E7R1P3)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWCLT
Device model: CLT-L09
Device product name: CLT-L09

## Steps to reproduce
1. Open the app
2. Select a manga

### Expected behavior
I should see the chapter list

### Actual behavior
When I open a manga to start reading it, I don't see anymore the chapter list, I can only see a white space. It's like that non only for the Mangas In my library or downloaded, but also for the ones on the different extensions. 

## Other details
It happened yesterday afternoon and in the morning it was normal. I tried re installing the app or even restarting the telephone but nothing changed

**Comment by CarlosEsco** [comment]
can you attach a screenshot

**Comment by CCBETTER11** [comment]
Il gio 14 gen 2021, 13:31 Carlos <notifications@github.com> ha scritto:

**Comment by arkon** [comment]
You need to upload it on GitHub, not reply in an email.

**Comment by arkon** [comment]
I think another Huawei user reported something similar. Are you using some sort of system theme?

**Comment by CCBETTER11** [comment]
![Screenshot_20210114_143414_eu kanade tachiyomi](https://user-images.githubusercontent.com/77442700/104606162-b60be400-567f-11eb-9219-f637579fb09e.jpg)

**Comment by CCBETTER11** [comment]
> I think another Huawei user reported something similar. Are you using some sort of system theme?

In the app I use the default settings, I only decided to set up the dark mode. But I opted for this months ago. I have this problem only from yesterday or two days ago

**Comment by arkon** [comment]
Did you update the app recently?

**Comment by CCBETTER11** [comment]
> Did you update the app recently?

I think probably two weeks ago. I have checked and at this moment there isn't any available update

**Comment by arkon** [comment]
So nothing in the app changed when this started happening?

**Comment by CCBETTER11** [comment]
No, nothing changed, the app is still working the same. It's not really interfering with anything else, so it's not a big problem, but I thought it was the most correct thing to do informing you about this matter

**Comment by scb261** [comment]
There were 2 similar problems recently on discord:

<details>
  <summary>3 Jan 2021 (Huawei)</summary>
  
  Stable 0.10.7
  Huawei P30 Lite
  Android 10
  https://discord.com/channels/349436576037732353/349436576037732355/795363243651498004

![Screenshot_20210103_204902_eu kanade tachiyomi](https://user-images.githubusercontent.com/65343233/104621782-270bc580-5699-11eb-9aa4-8908533f014b.jpg)
![Screenshot_20210103_165809_eu kanade tachiyomi](https://user-images.githubusercontent.com/65343233/104621819-2ffc9700-5699-11eb-9f3d-cb456e01e04e.jpg)
</details>

<details>
  <summary>7 Jan 2021</summary>

https://discord.com/channels/349436576037732353/349436576037732355/796778148351311902

![Screenshot_20210107_182918_eu kanade tachiyomi](https://user-images.githubusercontent.com/65343233/104621215-8917fb00-5698-11eb-8255-005409b5db7a.jpg)
![Screenshot_20210107_182924_eu kanade tachiyomi](https://user-images.githubusercontent.com/65343233/104621237-8d441880-5698-11eb-8271-2756976ee325.jpg)
</details>


Also j2k had this problem for a while now, was something taken from it recently? Examples https://github.com/Jays2Kings/tachiyomiJ2K/issues/592 (Huawei) or:

<details>
  <summary>j2k 10 Nov 2020</summary>
  
  https://discord.com/channels/349436576037732353/657923584811073566/775787256396906526

![unnamed](https://user-images.githubusercontent.com/65343233/104622153-91246a80-5699-11eb-9bcb-b45ae068faf4.jpg)
![unnamed_1](https://user-images.githubusercontent.com/65343233/104622139-8c5fb680-5699-11eb-8191-b76aeafa8d61.jpg)
</details>

<details>
  <summary>j2k 30 Sep 2020</summary>
  
  https://discord.com/channels/349436576037732353/657923584811073566/760833326239580242

![](https://cdn.discordapp.com/attachments/657923584811073566/760833322644668447/Screenshot_20200930-135656_TachiyomiJ2K.jpg)

</details>

**Comment by arkon** [comment]
> Also j2k had this problem for a while now, was something taken from it recently?

Only some code pertaining to the download icons, but that's not even in stable.

Regardless, the fact that it started happening for the OP yesterday despite having the current version installed from two weeks ago suggests it isn't related to the app update.

Also considering all of the other reports, I'm sort of assuming this is a Huawei issue.

**Comment by CCBETTER11** [comment]
Now the problem it's gone, I can see the chapter list as usual. I don't know why I can see the app as some days ago, but I've not done anything to solve the issue. Thank you all for your concern and support
