### ISSUE TITLE
[Bug] Optimize mangalib.me 

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4296]
Mangalib.me doesn't work in the app, as I realized it was due to the fact that the site has been updated. I hope you will solve this problem as soon as possible. Thank you. 
---

## Device information
* Tachiyomi version: 10.7
* Android version: 9
* Device: honor 9 lite

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

**Comment by Kongs23** [comment]
Yes I'm waiting for that too!!

**Comment by scb261** [comment]
You already opened an issue about it in the extensions repo https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5415, why did you duplicate it here
