### ISSUE TITLE
[Bug] <Unable to download chapters with missing pages>

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#4300]
## Device information
* Tachiyomi version: v0.10.7
* Android version: 6.0.1
* Device: vivo 1606

### Steps to reproduce 
1. Download a chapter with missing page/s.

### Expected behavior
When you download a chapter with missing page/s, the chapter should be downloaded and the missing page/s should be left as error.

### Actual behavior
When you download a chapter with missing page/s, the download queue will pause and the chapter won't be downloaded.

## Other details
Additional details and attachments.

**Comment by stevenyomi** [comment]
Duplicate of #3957
