### ISSUE TITLE
[Bug] Mangabox, manganelo only loads 2 images

### ISSUE THREAD

**Issue by TerroFlys** [tachiyomiorg/tachiyomi#4301]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: Samsung galaxy S10

## Steps to reproduce
1. Open chapter from manganelo (MangaBox)
2. Look past second image

### Expected behavior
Loads every image past the second.

### Actual behavior
After the first two images have been loaded, the rest says "retry".

## Other details
Mangabox extention, Manganelo
I have not checked if it also is like this with other sources from this extention, nor have i checked other extentions.

**Comment by scb261** [comment]
Works for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). If it won't help - specify manga and chapter with the issue

**Comment by TerroFlys** [comment]
> Works for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). If it won't help - specify manga and chapter with the issue

Thanks
