### ISSUE TITLE
[Feature Request] <multiple synchronization over multiple seasons>

### ISSUE THREAD

**Issue by Wip-Sama** [tachiyomiorg/tachiyomi#4302]
## Why/User Benefit/User Problem
Some manga have multiple seasons, if the first season end anilist and other site will mark that Manga as completed and if the Manga actually release another season that will be marked as a new one. 
The sites where tachiyomi take the Manga usually don't do the same thing so the new season is in the same page as the first. 
When this hannep you can't automatically synchronize your progress because you can't add other synchronization to the same Manga. 

## What/Requirements
When you press the synchronization button in the buttom a botton with something "new season" will allow you to set:
> From what chapter the season start
> The name of the season(Manga) 

![IMG_20210116_170354_332](https://user-images.githubusercontent.com/47224042/104816688-11bfa400-581d-11eb-9dd2-b4edbf0d120d.jpg)

**Comment by arkon** [comment]
At best, #4262 would be a better solution to this.
