### ISSUE TITLE
[Feature Request] <A bookmark filter in the library to find which manga you have bookmarks in them.>

### ISSUE THREAD

**Issue by IIOMNIVERSEII** [tachiyomiorg/tachiyomi#4308]
## Why/User Benefit/User Problem
(explain why this feature should be added)

I've got almost 10000 manga now I bookmark some really awesome chapters so I can read them later or if they have important info for later in the plot.I remember booking marking certain chapters where things were said I know what was said but don't remember the character or which manga there from and the only way to find which manga have bookmarks is to go through them one at a time

## What/Requirements
(explain how this feature would behave)

In the library when you click on filters under completed would be bookmarks pressing that option will show only manga with bookmarks inside of them or put a bookmark symbol on the cover art in the library.

**Comment by arkon** [comment]
Something like #5046 would probably be a lot more usable.
