### ISSUE TITLE
[Bug] Tachiyomi crashes when download notification tapped.

### ISSUE THREAD

**Issue by Aedyrn** [tachiyomiorg/tachiyomi#4311]
## Device information
* Tachiyomi version: r3013
* Android version: 5.0

## Steps to reproduce
1. Queue chapters for download
2. Slide down top menu and tap download notification, whether in ongoing or completed status.

### Expected behavior
Tapping the notification should lead to the download queue.

### Actual behavior
App crashes.

## Other details
So this is something I had forgotten to open an issue about but thanks to https://github.com/tachiyomiorg/tachiyomi/issues/4309 and accidentally tapping the notification as I do not use it most of the time, I rediscovered it. To be clear I don't believe these are related as this is a -very- old problem I forgot to open an issue for.

https://user-images.githubusercontent.com/35850104/104946804-9bed4100-59b2-11eb-8c96-c03864d651de.mp4

Pause, resume and clear commands work as intended. 
Additionally as you can see from the second example bellow, it does work when you tap whilst in the 'more' menu, but not from any other place

https://user-images.githubusercontent.com/35850104/104946812-9f80c800-59b2-11eb-902f-f485ef0a07a4.mp4

It's present in all releases from Stable 0.9.0 to Stable 0.10.7 and last preview (r3013). Works as intended in 0.8.5 unfortunately don't have any more precise numbers as 0.8.5 was almost a year ago.

Logs:
[bugreport-2021-01-18-15-52-55.txt](https://github.com/tachiyomiorg/tachiyomi/files/5831823/bugreport-2021-01-18-15-52-55.txt)
[logcat_01-18-2021_19-02-08.txt](https://github.com/tachiyomiorg/tachiyomi/files/5832009/logcat_01-18-2021_19-02-08.txt)
[data_app_native_crash@1610997296163.txt](https://github.com/tachiyomiorg/tachiyomi/files/5832060/data_app_native_crash%401610997296163.txt)
[tombstone_03.txt](https://github.com/tachiyomiorg/tachiyomi/files/5832080/tombstone_03.txt)

**Comment by arkon** [comment]
I don't think that crash log contains the correct info. Can you try getting the logs again?

**Comment by Aedyrn** [comment]
Would this be what you're looking for or something else?
[bugreport-2021-01-18-15-52-55.txt](https://github.com/tachiyomiorg/tachiyomi/files/5831823/bugreport-2021-01-18-15-52-55.txt)

**Comment by Aedyrn** [comment]
Maybe this could help aswell?
[tombstone_03.txt](https://github.com/tachiyomiorg/tachiyomi/files/5832080/tombstone_03.txt)

**Comment by arkon** [comment]
Nope, but I reproduced it in an emulator so it's okay.

**Comment by arkon** [comment]
Crashes from this: https://github.com/tachiyomiorg/tachiyomi/blob/1a5858e99ba98482a6470c7f70b2e4c43323940f/app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt#L379
