### ISSUE TITLE
"Dowload complete" notification pop-up comes back again and again

### ISSUE THREAD

**Issue by PhoenixAlpha63** [tachiyomiorg/tachiyomi#4314]
## Device information
* Tachiyomi version: r3013
* Android version: 9
* Device: Samsung Galaxy S8+

## Steps to reproduce
1. "Available Update for Tachiyomi" notification > Download button
2. Download has stopped in progress
3. Force stop the app
4. Open Tachiyomi
5. About > Search for an update > Download ok
6. Download complete notification > Update app
7. Open Tachiyomi
8. Complete a chapter (to the end)
9. Exit
10. "Dowload complete" notification pop-up

https://user-images.githubusercontent.com/24302919/104962126-111f3d00-59d8-11eb-8211-cd99bf60a0fe.mp4

## Other details
Tap on the notification > Downloads queue

**Comment by Aedyrn** [comment]
Fairly certain this is the same as this issue. https://github.com/tachiyomiorg/tachiyomi/issues/4309

**Comment by PhoenixAlpha63** [comment]
Yes, sorry.
