### ISSUE TITLE
[Bug] No manga covers from mangalib.me

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4317]
No cover on titles from mangalib.me, also on some of the titles there are no chapters, makes a mistake 
Error code:
![Screenshot_20210119_163717_com android chrome](https://user-images.githubusercontent.com/71752683/105041940-b38cfe00-5a74-11eb-9512-d0e7f6fa8faf.jpg)

content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_update_errors.txt
---

## Device information
* Tachiyomi version: 10.7
* Android version: 9
* Device: honor 9 lite

## Steps to reproduce
1. Open tachiyomi
2. Update your library
3. See the cover of the manga 

### Expected behavior
Error-free update, All titles have a cover

### Actual behavior
Update with no manga cover

**Comment by arkon** [comment]
This is not the first time you've been told that you're creating issues in the wrong place.

**Comment by MM001-r** [comment]
And where to create?

**Comment by arkon** [comment]
Follow the instructions that we ask you to read and remove in the template.
