### ISSUE TITLE
[Feature Request] Enable/disable tapping from within chapter option.

### ISSUE THREAD

**Issue by nickhdfan** [tachiyomiorg/tachiyomi#4318]
## Why/User Benefit/User Problem
Make the option to enable and disable tapping right from within the chapter option instead of having to go back to main menu --> reader --> navigation --> tapping (toggle). Tapping while reading manga is useful but for webtoon, not so much.

## What/Requirements
The option (toggle) to enable and disable tap to change chapter page should be available right from the option within the chapter instead of having to go back to the main menu.

**Comment by Owerlords** [comment]
Even better option Would be nice to have option when u open a manga that the app asks you if its the default reader you have set or webtoon reader? I read webtoons and normal manga and its annoying to change the old fashion way always.

Maybe ask before the manga is opened or maybe ask when manga is opened and it shows you the reader mode ur on and alternative button to change webtoon mode on the fly.

**Comment by CVIUS** [comment]
You can set navigation layout to `Disabled` with https://github.com/tachiyomiorg/tachiyomi/pull/6876
