### ISSUE TITLE
[Bug] Http error 403 on trying to add manga to tracklist

### ISSUE THREAD

**Issue by centipede13** [tachiyomiorg/tachiyomi#4320]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: Poco F1

## Steps to reproduce
1. Go to tracking
2. Select and add manga

### Expected behavior
Manga should be added to MyAnimeList tracking list

### Actual behavior
Instead of saving manga to tracking list, it is showing 403 error.

## Other details
I already tried clearing cookies and logging in again.
But now I am not able to log in to my animelist account.

**Comment by scb261** [comment]
MAL tracking was rewritten for the next release. For now you can try changing password, it usually helps

**Comment by willyreza** [comment]
it's the same as mine. My device Samsung M11. Please fix it🙂

**Comment by centipede13** [comment]
> MAL tracking was rewritten for the next release. For now you can try changing password, it usually helps

Trued that , still cant save the manga to MyAnimeList trracking Lkst

**Comment by arkon** [comment]
This will be fixed in the next stable release.

For current 0.10.7 users, you can try to clear your cookies, restart the app, and log in again.
