### ISSUE TITLE
[Feature Request] <Faster way to choose reader mode>

### ISSUE THREAD

**Issue by Owerlords** [tachiyomiorg/tachiyomi#4322]
## Why/User Benefit/User Problem
Option in settings when u open a manga that the app asks you if its the default reader you have set or webtoon reader. I read lots of webtoons and normal manga and its slow and painfull to change from the reader page settings.

## What/Requirements
Ask what to use before the manga is opened or maybe ask when the manga is open and it shows you the reader mode ur on and alternative button to change webtoon mode on the fly when you have the option on to show what reader ur using.

**Comment by karageee** [comment]
to be honest there is a way that this could be even faster. Such as the app reads the API from the manga website tags and search for webtoon and automatically change the setting to webtoon reading mode.
But I haven't read the docs and the tachiyomi source code so idk.

**Comment by CarlosEsco** [comment]
@karageee 
1st you assume there is an api. 
2nd you assume websites actually tag their stuff correctly
3rd you assume that every site uses english tags 
4th your suggestion is not really related to what is being asked

**Comment by Waelwindows** [comment]
How about setting a default reader for each category?
That way if you have a webtoon category you could set it so that by default it'll choose webtoon reader mode

**Comment by arkon** [comment]
Covered by #3453.

For comments unrelated to the original request, please open separate ones if there isn't already an existing one.
