### ISSUE TITLE
[Bug] <DMZJ Extension is not working>

### ISSUE THREAD

**Issue by ESAKA996** [tachiyomiorg/tachiyomi#4325]
Since yesterday, DMZJ became unaccessible inTachiyomi while it could be accessed through its own APP. I doubt your extension is blocked by the site holder. DMZJ is a major manga site in China, hence this loss could be significant. Your app works much better than their own, and many Chinese users would have to suffer from their app if the DMZJ extension is not working.
---

## Device information
* Tachiyomi version:0.10.7
* Android version: 10
* Device: HUAWEI P20 Pro

## Steps to reproduce
1. First step: Open Tachiyomi and download the DMZJ extension
2. open DMZJ

### Expected behavior
Read DMZJ's manga smoothly

### Actual behavior
No mangas are shown, and it shows "HTTP Error 304: Check the site in Web View"

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5501
