### ISSUE TITLE
[Bug] <the app crashes too many times>

### ISSUE THREAD

**Issue by Bm12347** [tachiyomiorg/tachiyomi#4326]
## Device information
* Tachiyomi version: preview r3013
* Android version: 10
* Device: samsung a31

## Steps to reproduce
1. Open the app
2. Open any manga

### Expected behavior
Should open normally

### Actual behavior
The app crashes 
The problem is that happens randomly
Sometimes it crashes
And sometimes it does not

## Other details
Additional details and attachments.

**Comment by scb261** [comment]
Make sure you have updated all extensions and [WebView](https://play.google.com/store/apps/details?id=com.google.android.webview). Provide logcat. Possible ways to get logcat:
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android

**Comment by arkon** [comment]
Please provide crash logs. There's no useful information in this issue otherwise unless we're psychic.

**Comment by Bm12347** [comment]
https://drive.google.com/file/d/1MrgGKvdmVmqP3UMKY-dsNGNGjcYo43_4/view?usp=drivesdk
I tried to use the first method but couldn't because my phone is not rooted and I don't have a pc
When I was randomly doing things to see what will cause the app to crash 
I found that opening a manga while the library is updating causes the app to crash
Sometimes
