### ISSUE TITLE
[Feature Request] auto skip same chapter from different source

### ISSUE THREAD

**Issue by karageee** [tachiyomiorg/tachiyomi#4328]
## Why/User Benefit/User Problem
We really need to skip same chapter with the different source since when the user slides to the next chapter we needed to press skip/next chapter everytime when the next chapter is the exact same but with different source.

## What/Requirements
The code must check if the source of the chapter is the same and skip the same chapter with different source.

**Comment by karageee** [comment]
In an extremely simplified python code it's like this
```py
If current_chapter == next_chapter:
      skip()
```
or something like that

**Comment by scb261** [comment]
Sort chapter list by chapter number and the reader will skip chapters with the same number

**Comment by CarlosEsco** [comment]
^^

**Comment by karageee** [comment]
But it's still troublesome to change the sorting every time you want to read a manga that has the same chapter released by multiple sources. Especially when some didn't know such a method exist as well.

**Comment by arkon** [comment]
#969 seems like a better idea than this. Chapter number detection isn't always accurate.

**Comment by Wiz1991** [comment]
What i did to solve this is enable "skip read chapters". Then when i read a manga i set chapters from sources(groups) i dont want to read as read and thus skip them. Its not that much of a hassle to do and is better because you can choose the source you want to read from
