### ISSUE TITLE
[Feature Request] Customizable Inter-chapter Text

### ISSUE THREAD

**Issue by Schezuk** [tachiyomiorg/tachiyomi#4330]
Many a source of manga has a comment section.

#2203 #3721 People require to display the comment section at the end of every chapter.
#2155 #2662 Commenting is regarded as a legit requirement.
#1653 There is a meta-data section between chapters telling if any more chapters available.

So why not make the inter-chapter text customizable?

## Why/User Benefit/User Problem
* People enjoy reading comments of others, if not posted by themselves.
* Feature to submit a comment may be too much a trouble. But read-only is not.
* I don't want to bother open the comment page on the source website, as I do now every time.

## What/Requirements
1. Extension submits plain-text comments extracted from source of every chapter alongside image URLs.
2. Insert the text before "Next Chapter: xxx" (```transition_next```) or "There is no next chapter" (```transition_no_next```)
3. If people configured not to display ```transition_next``` and ```transition_no_next```, comments will not be displayed.

As long as Tachiyomi is reluctant to implement this feature, extensions are not able to follow up.

**Comment by arkon** [comment]
I'm confused, what do comments, notes, and the transitions have in relation?

The rationale for not having a comment system was already given in the linked issues, and the other ones are still open.

I don't understand what your requirements mean?

**Comment by Schezuk** [comment]
> I'm confused, what do comments, notes, and the transitions have in relation?
> 
> The rationale for not having a comment system was already given in the linked issues, and the other ones are still open.
> 
> I don't understand what your requirements mean?

All I mean is to implement a way to view the comments after each chapter, without bothering to allow users to post any comments, which would be way more easy than what people have asked for.

**Comment by arkon** [comment]
This is basically the same thing as #3721 except with a UI suggestion then.

The answer is still the same — having the extensions need to scrape comments would be difficult to do and maintain.

Just open the website in WebView if you want to read comments.

**Comment by Schezuk** [comment]
> This is basically the same thing as #3721 except with a UI suggestion then.
I apollogize if I didn't make myself clear, but you didn't get the point.

> The answer is still the same — having the extensions need to scrape comments would be difficult to do and maintain.
You can just leave it as a choice to the extension makers. And if they are reluctant, other people will submit PR.

> Just open the website in WebView if you want to read comments.
Webview will show the page of whole manga, and it offers no GO BACK functionality.
It is the comment of chapters that is required, not comments of the whole manga.
[Some extensions do treat different updates of one single manga as different chapters, which is non-sense and time-consuming when tracing back.]

And as in the case of DMZJ, they offer chapters and comments in different api. You just cannot view it in WebView.
```
https://v3api.dmzj1.com/comic/comic_50000.json?version=2.7.019
http://v3comment.dmzj1.com/v1/4/latest/50000?page_index=1&limit=10
https://api.m.dmzj1.com/comic/chapter/50000/43118.html
http://v3api.dmzj1.com/viewPoint/0/50000/93172.json
```
And even if you managed to view it, it is encoded in JSON and escaped.
```
[{"id":47682407,"uid":12416679,"content":"\u8fd9\u4e2a\u5c31\u8fd9\u4e9b","num":1,"page":27},{"id":47681493,"uid":106231155,"content":"\uff1f\uff1f\uff1f","num":1,"page":28},{"id":47681038,"uid":100209851,"content":"\u53c8\u662f\u534a\u8def\u5f03\u8f66\uff1f2333","num":8,"page":0},{"id":47679664,"uid":108655525,"content":"\u8f66\u5462\uff1f\uff1f\uff1f","num":7,"page":28},{"id":47679450,"uid":107155950,"content":"\u4eb2\u5634\uff01","num":4,"page":0}]
```
which equals
```
0: {id: 47682407, uid: 12416679, content: "这个就这些", num: 1, page: 27}
1: {id: 47681493, uid: 106231155, content: "？？？", num: 1, page: 28}
2: {id: 47681038, uid: 100209851, content: "又是半路弃车？2333", num: 8, page: 0}
3: {id: 47679664, uid: 108655525, content: "车呢？？？", num: 7, page: 28}
4: {id: 47679450, uid: 107155950, content: "亲嘴！", num: 4, page: 0}
```
