### ISSUE TITLE
[Bug] One Piece Kitsu Not Tracking

### ISSUE THREAD

**Issue by cuzzbaby** [tachiyomiorg/tachiyomi#4334]
So as it says in title, My One piece won't track. Every other manga I've tried tracking works fine with Kitsu. I'll press "Add Tracking" on One piece and will get an infinite load, if I just leave my phone open the load will eventually go ago but nothing will appear. If i try this with an other manga, Kitsu will appear options will appear within seconds. The source I am using for One piece is Mangabat (EN). MAL tracking works fine but I just prefer using Kitsu over it.

**Comment by arkon** [comment]
There's an issue where it's not showing the error properly.

I can't actually test why it's erroring right now though, since it looks like Kitsu's down for maintenance.
