### ISSUE TITLE
Comment Section for Chapters, not the Whole Manga

### ISSUE THREAD

**Issue by Schezuk** [tachiyomiorg/tachiyomi#4336]
_Originally posted by @arkon in https://github.com/tachiyomiorg/tachiyomi/issues/4330#issuecomment-765401629_```

> This is basically the same thing as #3721 except with a UI suggestion then.

I apologize if I didn't make myself clear, but you didn't get the point.  
I recommend a minimum or none effort to be made by the app and extension for the comment, rather than adding a button and a new view of comment sections

> The answer is still the same — having the extensions need to scrape comments would be difficult to do and maintain.

You can just leave it as a choice to the extension makers.   
They may feed extra text after image, or leave the field empty if it is difficult.  
And other people may submit PR if they are reluctant.

> Just open the website in WebView if you want to read comments.

It is the comment of chapters that is required, not comments of the whole manga.  
Webview will show the page of whole manga, not any chapter.  
(If you offer a WebView button for every chapter, I will do with that, as I did with SOME 
manga sources' .)  
And webview offers no GO BACK functionality if you go into any chapter.  

[BTW, SOME extensions do treat different updates/versions of one single manga as different chapters, which is non-sense and time-consuming when tracing back.]

And, as in the case of DMZJ, they offer chapters and comments in different apis. You just cannot jump from image list to comment list in WebView.  
For example, 
```
Manga Chapter List: https://v3api.dmzj1.com/comic/comic_50000.json?version=2.7.019
Manga Comments: http://v3comment.dmzj1.com/v1/4/latest/50000?page_index=1&limit=10
Chapter Image List: https://api.m.dmzj1.com/comic/chapter/50000/43118.html
Chapter Comment: http://v3api.dmzj1.com/viewPoint/0/50000/93172.json
```
And even if you managed to view it, it is encoded in escaped JSON and totally unreadable.
```
[{"id":47682407,"uid":12416679,"content":"\u8fd9\u4e2a\u5c31\u8fd9\u4e9b","num":1,"page":27},{"id":47681493,"uid":106231155,"content":"\uff1f\uff1f\uff1f","num":1,"page":28},{"id":47681038,"uid":100209851,"content":"\u53c8\u662f\u534a\u8def\u5f03\u8f66\uff1f2333","num":8,"page":0},{"id":47679664,"uid":108655525,"content":"\u8f66\u5462\uff1f\uff1f\uff1f","num":7,"page":28},{"id":47679450,"uid":107155950,"content":"\u4eb2\u5634\uff01","num":4,"page":0}]
```
which equals
```
{
  {id: 47682407, uid: 12416679, content: "这个就这些", num: 1, page: 27},
  {id: 47681493, uid: 106231155, content: "？？？", num: 1, page: 28},
  {id: 47681038, uid: 100209851, content: "又是半路弃车？2333", num: 8, page: 0},
  {id: 47679664, uid: 108655525, content: "车呢？？？", num: 7, page: 28},
  {id: 47679450, uid: 107155950, content: "亲嘴！", num: 4, page: 0}
}
```

**Comment by arkon** [comment]
> I recommend a minimum or none effort to be made by the app and extension for the comment, rather than adding a button and a new view of comment sections

The UI isn't the main issue, making any sort of change to the extensions API is generally an immense effort due to backwards compatibility issues.

> And webview offers no GO BACK functionality if you go into any chapter.

What? Just press back on your device.

> And, as in the case of DMZJ, they offer chapters and comments in different apis.

It's nice that DMZJ surfaces comments in their API, but most sites wouldn't. Scraping Facebook or Disqus comments (which are the more common third-party comment systems) would be difficult since extensions don't handle JS-heavy usecases well either.

**Comment by Schezuk** [comment]
> > I recommend a minimum or none effort to be made by the app and extension for the comment, rather than adding a button and a new view of comment sections
> 
> The UI isn't the main issue, making any sort of change to the extensions API is generally an immense effort due to backwards compatibility issues.

I wonder if you mean forward compatible...to be backward compatible, just keep the old APIs and add new ones. Or you mean binary compatible?

A dirty patch may be to just receive the text in the very API of images. Say
```
http://domain/path/file1
...
http://domain/path/file10
text://escaped_plain_text_%0A%0D_next_line_of_plain_text
```

> > And webview offers no GO BACK functionality if you go into any chapter.
> 
> What? Just press back on your device.

In most Android devices I have used, webview comes without a BACKWARD button and quits when back key is pressed. Maybe you have a customed one?

> > And, as in the case of DMZJ, they offer chapters and comments in different apis.
> 
> It's nice that DMZJ surfaces comments in their API, but most sites wouldn't. Scraping Facebook or Disqus comments (which are the more common third-party comment systems) would be difficult since extensions don't handle JS-heavy usecases well either.

I get the point and agree with you. In that case, a webview button linked to source chapters would do the favor.

**Comment by Schezuk** [comment]
If that's still impossible, may you accept base64 encoded image URLs? So that it is possible to post a PR to render text into image and feed it.

**Comment by arkon** [comment]
Nothing's stopping you from using an interceptor and manually manipulating the images.

**Comment by Schezuk** [comment]
> Nothing's stopping you from using an interceptor and manually manipulating the images.

I don't think Tachiyomi would ignore MITM attack.

**Comment by arkon** [comment]
I mean within the extension. I don't remember which ones do it currently, but the mangarock extension used to do it to decode the images.

**Comment by Schezuk** [comment]
> I mean within the extension. I don't remember which ones do it currently, but the mangarock extension used to do it to decode the images.

Great, I will have a look.

**Comment by Schezuk** [comment]
> I mean within the extension. I don't remember which ones do it currently, but the mangarock extension used to do it to decode the images.

BTW, does Tachiyomi support **ONLINE** .zip sources? I've found a new api and maybe I could do something.

**Comment by CarlosEsco** [comment]
no it does not

**Comment by arkon** [comment]
Anyway, I'm going to close this as it isn't something that we want to support.

A generic way of viewing comments is likely difficult to support for a majority of sources (which are generally just scraping sites), regardless of whether the comments are for a chapter or for the entire manga entry. It's a lot easier to handle it in apps that are handling specific source features (e.g. Neko for MangaDex).
