### ISSUE TITLE
[Feature Request] Refresh downloaded chapter

### ISSUE THREAD

**Issue by o01210o** [tachiyomiorg/tachiyomi#4339]
## Why/User Benefit/User Problem
Some websites add "raw chapter" in japanese and when you have set automatic download in the app, it normally download these "raws" chapters, no problem. But when they update the chapter with the real translated chapter, the app doesn't refresh the chapter and you have to delete the previous file (raws chapter) and download again the chapter.

## What/Requirements
When a chapter is updated in the website, delete the previous downloaded file and download the updated chapter.

**Comment by arkon** [comment]
There isn't really a good way for the app to know it was actually updated versus something like a rename.
