### ISSUE TITLE
Some new chapters have just 5 pages and not the complete chapter that you can find in the site

### ISSUE THREAD

**Issue by mrey666** [tachiyomiorg/tachiyomi#4340]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: Galxy J7 prime

## Steps to reproduce
1. Open a new chapter. for example: martial peak 918 (source:mangahere)
2. There are only 5 pages in the chapter while in the site there is the whole chapter.
3. This problem occured to me in other manga. And it's always 5 pages when there is the problem. (The problem doesn't appear every new chapter)

## Issue/Request
Please fix the incomplete chapters.

**Comment by arkon** [comment]
As mentioned in the issue template instructions, this belongs in https://github.com/tachiyomiorg/tachiyomi-extensions.
