### ISSUE TITLE
[Bug] App Freeze at Library Update

### ISSUE THREAD

**Issue by Ahsan400** [tachiyomiorg/tachiyomi#4341]
## Device information
* Tachiyomi version: 0.10.7 (3041)
* Android version: 9
* Device: Redmi Note 5 (whyred)

## Steps to reproduce
1. Goto update tab
2. Update library

### Expected behavior
Keep updating and shouldn't freeze.

### Actual behavior
Keep updating but app freezes nothing works at that moment. Also Cancel from notification panel doesn't work at the same time. Force close is the only way to stop.

### Logs
[logcat_01-24-2021_06-17-02.txt](https://github.com/tachiyomiorg/tachiyomi/files/5861370/logcat_01-24-2021_06-17-02.txt)

**Comment by arkon** [comment]
Thanks, I'll release another build where this should be fixed.

---

https://github.com/tachiyomiorg/tachiyomi-preview/actions/runs/506543589
