### ISSUE TITLE
[Feature Request] Update manga info when refreshing tracking data

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4348]
## Why/User Benefit/User Problem
This occurred to me today where a manga had 16 chapters total displayed on Tachiyomi but opening MAL's site showed 15 total, only way to update the value on Tachiyomi was to retrack the manga.
I haven't been able to check myself recently but if there's no updating whatsoever right now, this will pose a problem for when a manga finishes and information for it isn't updated to match the tracking site.

## What/Requirements
Maybe not on every update by the user (i.e. read chapter) but on a manual refresh of tracking data (pulling down on tracking menu) or global tracking update from the settings menu, update all manga information.
I believe this was a thing before but it seems like now manga won't update information? Not sure if a bug or change in behavior.

**Comment by arkon** [comment]
I'm assuming you're using the preview version? If so, this is likely because of the MAL rewrite. I'll make it update the total chapters number as part of the refresh.
