### ISSUE TITLE
[Feature Request] Add start reading date after reading a chapter to tracked manga that have no start date

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4349]
App version: 0.10.7-3045 (standard, 8a668ba7, 54)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190825.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: davinci
Device model: Mi 9T
Device product name: davinci_eea

## Why/User Benefit/User Problem
 Tachiyomi adds today's date when you first track a manga but if you don't start reading on that day, you might remove it, it makes sense to add the date for the current day if the date is blank and you read a chapter.

## What/Requirements
Add start date for the day in which the chapter number is updated if the start date is empty/null

**Comment by arkon** [comment]
It's never updated the data before sending new data (see #1652).

I'm also unclear what you're trying to describe. Can you provide clear steps to reproduce the problems?

For future reference:
- These sound like bugs, not feature requests
- You should open one issue per item

**Comment by paulo27ms** [comment]
Oh boy, I had no idea I suggested this in the past, maybe that's why I thought it was a thing already.
But it's as the other issue I opened suggests, if you update a manga on MAL but don't refresh tracking data on Tachiyomi, when you go to read a chapter on Tachiyomi then it sends outdated info (like score) to MAL and you end up with old data.

Should I edit this issue to be just about adding a start date to manga with no start date?
Sorry about putting stuff together, just seemed relevant enough and they didn't really seem like "bugs" per se.

**Comment by arkon** [comment]
Yeah, editing this one should be fine.

**Comment by paulo27ms** [comment]
Not sure if this one still counts as a bug now but I'll leave it as is. Sorry for the dupe request, didn't mean to bump.

**Comment by arkon** [comment]
I'm going to keep it simple for now and just not set the start date automatically and let the user do it manually.

If we want to be "smart" and try to infer that the user's first reading it, we'd need to add more logic in. That being said, the tracker code is kind of redundant across the different trackers' implementations right now.
