### ISSUE TITLE
[Feature Request] Migrate to ViewPager2

### ISSUE THREAD

**Issue by TacoTheDank** [tachiyomiorg/tachiyomi#4351]
### References:
- https://medium.com/google-developer-experts/exploring-the-view-pager-2-86dbce06ff71
- https://developer.android.com/training/animation/vp2-migration
- https://www.raywenderlich.com/8192680-viewpager2-in-android-getting-started

### Why/User Benefit/User Problem
1. Supports both horizontal and vertical orientation / scrolling, so we won't need DirectionalViewPager anymore
2. Supports RTL (no more hacky stuff in Pager.kt)
3. Modifiable fragment collections
4. Built on RecyclerView

### What/Requirements
- Look at references

Ignoring stuff that relies on the ViewStatePagerAdapter library, this can just be done for the Pager for now if that's fine.

I'm aware that this may be something that's being saved for the rewrite, but I truly believe the codebase and the UX can be improved by this (especially for users of RTL languages like Arabic, Hebrew, Persian, and Urdu, since scrolling won't be confusing anymore).

**Comment by jobobby04** [comment]
This was attempted before in the library here https://github.com/tachiyomiorg/tachiyomi/commit/2a202bd510bf667153a40eea9bd641172533f603
And was then reverted when it produced weird bugs such as cover size and ratio being broken
https://github.com/tachiyomiorg/tachiyomi/commit/08dc57fd024004e1b0466eb50c2d07a56d30d244

**Comment by arkon** [comment]
The animation/transitions are pretty slow for some reason too, and iirc you can't extend the class for whatever reason.

**Comment by TacoTheDank** [comment]
@jobobby04 dang

@arkon I think the slowness is just how it's programmed. Things I've migrated to ViewPager2 move around a bit differently like that. I think what they want you to do now is to create an inner class that extends ViewPager2 and use that

> The animation/transitions are pretty slow for some reason too, and iirc you can't extend the class for whatever reason.

**Comment by TacoTheDank** [comment]
@jobobby04 dang, thanks for telling me about this

@arkon I think the slowness is just how it's programmed. Things I've migrated to ViewPager2 move around a bit differently like that. I kinda like it more tbh (though the transitions might feel a bit strange in a manga-viewing app like this).

> The animation/transitions are pretty slow for some reason too, and iirc you can't extend the class for whatever reason.

I think what they want you to do now is to create an inner class that extends ViewPager2, and then use that...

**Comment by arkon** [comment]
It's probably not actually worth it anyway, since it's not like the performance of ViewPager is bad compared to ViewPager2.

The rewrite uses Jetpack Compose, so ViewPager is irrelevant there too.

**Comment by TacoTheDank** [comment]
@arkon That's okay with me, thanks for responding.
