### ISSUE TITLE
nHentai option to enable pages instead of infinite scroll

### ISSUE THREAD

**Issue by MatteCrystal** [tachiyomiorg/tachiyomi#4354]
I believe this can be useful for all extensions not just nHentai. This is not a duplicate of #4350 that issue had multiple requests too it and it was closed due to one of the requests unrelated to this feature. 

## Why/User Benefit/User Problem
Infinite scroll not always the best option. If a user browses multiple pages worth of content, leaves the app, and then comes back. They will be forced to scroll 100's if not 1000's of entries to get to their last browsing spot. 
## What/Requirements
In these cases it's much more simple to have a simple page system. If I left off on page 8 I can just say go to page 8 next time I browse. The user would have the option to choose page or infinite scroll and if they choose page they would have an option of how many entries to display per page.

Also, if #407 is ever implemented it will need to be made compatible with paging and be able to handle resuming even if the user constantly switches between the viewing modes.

**Comment by arkon** [comment]
Can you please follow the issue templates and keep it concise?

**Comment by arkon** [comment]
Closing this in favour of #407. I commented on that one with what was added here since realistically they should both be added together, if ever.
