### ISSUE TITLE
[Bug] Apps restarted after checking update library and force closed when searching manga globally

### ISSUE THREAD

**Issue by eazzy-lab** [tachiyomiorg/tachiyomi#4355]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: Pocophone F1

## Steps to reproduce
Hi guys, 
I want to report some issues after update from 0.10.5 to 0.10.7 :
- The apps always restarted after checking update library 
- The apps force closed when searching manga globally in Browse > Source (not searching inside of manga source) when is not an issue in version 0.10.5.

Issue for app force closed when using global search : 
1. Navigate to Browse menu
2. Search manga using Global Search
3. Apps force closed in the middle of searching manga

### Expected behavior
Apps did not restart after checking update library and is not force closed when searching in global search

### Actual behavior
Apps restarted after checking update and force closed when searching in global search

## Other details
Here is a video attachment for issue of global search : 
![Gif 1](https://user-images.githubusercontent.com/61447146/105894082-79a89280-6046-11eb-8952-23f74a5494fa.gif)

**Comment by arkon** [comment]
Please update your extensions first.

**Comment by eazzy-lab** [comment]
Wow it works like charm. Maybe because I updated from version 0.10.5 so I don't know there are changes about this in version 0.10.6 and submit as an issues in version 0.10.7.

Thank you :) 👍
