### ISSUE TITLE
[Feature Request] Browse Source List Compact

### ISSUE THREAD

**Issue by thu2468** [tachiyomiorg/tachiyomi#4356]
## Why/User Benefit/User Problem
So that source are not spaced out as much

## What/Requirements
So you can maybe make it so that Description for the source language on the right side of the source name instead of the bottom. or option to remove the language description

**Comment by themakshter** [comment]
Just to understand what you mean -

The current way it may look: 

![image](https://user-images.githubusercontent.com/2033876/106037015-05193680-60ce-11eb-9e93-f51a6ceaf5f1.png)

How you would like it to look? Something like this: 

![image](https://user-images.githubusercontent.com/2033876/106037620-d780bd00-60ce-11eb-83c8-778790858d5b.png)

**Comment by thu2468** [comment]
yes a option to do that or make the word English to be on the right side between source name and latest

**Comment by themakshter** [comment]
Personally, depending on how that looks, the one where it is in between might take up space and it may not always be visible, but I'll try giving both some shots

**Comment by thu2468** [comment]
ok ty that will be nice to have a option so u can have it more compact

**Comment by arkon** [comment]
I don't think this is going to get added since we don't really do anything like this anywhere else. It may be worth redesigning the page at some point, but there haven't been any good suggestions for that.
