### ISSUE TITLE
Team X arabic change there website

### ISSUE THREAD

**Issue by nawafaltlasi96** [tachiyomiorg/tachiyomi#4362]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 11
* Device: Samsung note 10+

the problem with the extension that team X have change there website from team1x1.com
to team1x.com and i don't have the Experience to change it i wish that you all help me and thank you.

**Comment by CarlosEsco** [comment]
wrong repo.  please read the stuff you deleted in the issue.  finally https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475
