### ISSUE TITLE
[Feature Request] Invert color option

### ISSUE THREAD

**Issue by cpetry** [tachiyomiorg/tachiyomi#4366]
Why/User Benefit/User Problem
(explain why this feature should be added)

I stumbled upon pages being inverted in color (black should be white and vice versa when reading monochrome manga). It is really strange to read like this.

What/Requirements
(explain how this feature would behave)

An invert colors toggle inside the custom color settings would fix this.

**Comment by cpetry** [comment]
Damn... Sorry this happened due my dark mode on xiaomi smartphone. Seems that this was the cause.
Disabling the dark mode fixed this for me.

**Comment by arkon** [comment]
Oof, good work Xiaomi. Thanks for sharing at least, it'll help if anyone else comes across this.

**Comment by arkon** [comment]
There were requests for this before too, but AOSP ships with an accessiblity setting to invert colors.
