### ISSUE TITLE
[Bug] App crashes when changing reading mode

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#4368]
## Device information
* Tachiyomi version: r3045
* Android version: Android 10
* Device: Oneplus 7

## Steps to reproduce
1. Open a webtoon chapter or something and make sure it is in 'Default mode'
2. If it was not in 'Default mode' restart the app and open said webtoon chapter again
3. Change the reading mode to 'Webtoon' and after a few seconds it crashes

### Expected behavior
Just changing the reading mode without restarting

### Actual behavior
It crashes and restarts the entire app (it does change the reading mode)

## Other details
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/5897965/tachiyomi_crash_logs.txt)

**Comment by inorichi** [comment]
Fixed with d4c9ab7
