### ISSUE TITLE
[Bug] Occasionally Crashes while try to open chapter from update page

### ISSUE THREAD

**Issue by Ahsan400** [tachiyomiorg/tachiyomi#4369]
## Device information
* Tachiyomi version: 0.10.7 (3045 - 3113)
* Android version: 9
* Device: Redmi Note 5 Ai (Whyred)

## Steps to reproduce
Well, I am not sure how to produce it again but every time the app crashed I noticed few common thing.
1. Update Library
2. Auto download updated chapter
3. Exit from app. 
4. Come back some times later and try to open last downloaded chapter.

Everytime the app crashed these were the common part. But following these steps does not guarantee reproduction. It just happens out of no where in a complete unexpected time. That's why I couldn't capture logcat.

### Expected behavior
Should open chapter.

### Actual behavior
App crashes.

## Other details
[tachiyomi_crash_logs.txt (3045)](https://github.com/tachiyomiorg/tachiyomi/files/5898157/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs.txt (3063)](https://github.com/tachiyomiorg/tachiyomi/files/5904311/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs.txt (3095)](https://github.com/tachiyomiorg/tachiyomi/files/5950415/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs.txt (3113)](https://github.com/tachiyomiorg/tachiyomi/files/5976582/tachiyomi_crash_logs.txt)

**Comment by inorichi** [comment]
Fixed with d4c9ab7
