### ISSUE TITLE
[BUG] / [NEW FEATURE REQUEST] something wrong in resolution. 

### ISSUE THREAD

**Issue by illidan1337** [tachiyomiorg/tachiyomi#4370]
So for some reason when I use tachiyomi to read comics on my tablet it gives me two black bars on the top and bottom of my screen
![Screenshot_20210130-161025](https://user-images.githubusercontent.com/20922653/106369401-9f6bbb00-6316-11eb-8baf-04b867a241a8.jpg)
No matter how I adjust the scale type it never gives me the ideal resolution. 
This is a screenshot of the same page but using comic rack
![Screenshot_20210130-161042](https://user-images.githubusercontent.com/20922653/106369442-f1acdc00-6316-11eb-8bf1-a17b1a570f9e.jpg)
As you can see it shows the full page and takes up the entire screen. 
I don't know why this happens whether comic rack distorts the image slightly or somethings happening between tachiyomi and the hardware on my device but I find it pretty hard to move past... 
Just to clarify, no matter what I choose in the scale type, it either gives me the two black bars or it zooms in so I don't see the full image... 

---

## Device information
* Tachiyomi version: 0.10.7
* Android version: 8.0.0
* Device: huawei mediapad t5 

## Steps to reproduce
1. Open comic
2. See screen

## Issue/Request
Both because having a true stretch to fit feature would solve this issue

**Comment by scb261** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/1395#issuecomment-385977832

**Comment by illidan1337** [comment]
why does it fit in comic rack but not tachiyomi? there certainly isnt anything in the documentation about distorting the image so that it fits... but also why does the stretch feature just scale the image to whatever aspect that needs to be filled? do you not know what the meaning of the word stretch is?

**Comment by arkon** [comment]
It's hard to tell without actually overlaying the images, which I'm not going to bother doing, but you could do it yourself to figure out what comic rack is doing.

Perfect is objective. The idea of actually stretching images in such a way that distorts them is blasphemous to me.

However, since this is a FOSS project, anyone is free to make a change as they see fit (i.e. a fork) even if the main project maintainers don't want to do something.

**Comment by illidan1337** [comment]
well i am very unskilled when it comes to coding in general. if something is simple i can probably figure out how to make it work... is there anyway you would tell me what part of the source code exactly handles the stretch feature? maybe i can figure out how to modify it to suit my needs...

**Comment by arkon** [comment]
It'd be somewhere in https://github.com/tachiyomiorg/subsampling-scale-image-view
