### ISSUE TITLE
[Bug] Search function doesn't work properly on History or Extensions section

### ISSUE THREAD

**Issue by davidtuning** [tachiyomiorg/tachiyomi#4371]
## Device information
* Tachiyomi version: Last stable from Github (10.7).
* Android version: 9.1
* Device: Huawei Y9 2019 Plus 

## Steps to reproduce
1. First step: Search on the History or Addons sections. 
2. Second step: Go back to the results list. 

### Expected behavior
It should maintain the results list until you delete what are you looking for from it. As it's in the library. 

### Actual behavior
The search results just reset it by itself while still having the keywords on the search section. 

## Other details
Thanks for reading this. And many thanks for adding the infinite scroll down and the search function for History and Recents!

**Comment by arkon** [comment]
Seems to be fine in latest version.
