### ISSUE TITLE
[Feature Request] "only update ongoing manga" in library setting to have completed manga update monthly / custom

### ISSUE THREAD

**Issue by saberkevin** [tachiyomiorg/tachiyomi#4374]
## Why/User Benefit/User Problem
Sometimes completed manga has update of extra stories eventhough the manga is already completed and if we turn on "only update ongoing manga" in library setting, it will not be updated, so i want to have a feature to update completed manga chapter to get new chapter on monthly/custom basis.

(because i has many completed manga, turning on "only update ongoing manga" is helpful to reduce the hourly update manga title, so i want to keep that on, and only update the completed manga part once in a while (ex: monthly))

## What/Requirements
add "update completed manga" with option of weekly/monthly/yearly/custom in library setting when "only update ongoing manga" is on.

**Comment by Umairuem** [comment]
Yes, this feature would be nice.

**Comment by SeriousMatters** [comment]
How about make a 'completed' category and set it to not automatically update?
