### ISSUE TITLE
[Bug] <some chapters does not load in the reader even though they can be read in webview or gallery when downloaded>

### ISSUE THREAD

**Issue by Bm12347** [tachiyomiorg/tachiyomi#4382]
## Device information
App version: 0.10.7-3063 (standard, 17109ab7, 54)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BTK3
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
1. Open the app
2. Open the 28 or 29 chapter of
This Italian Girl Has Become Such A Freeloader
### Expected behavior
Chapter should load correctly

### Actual behavior
It doesn't load except for the first page

## Other details
![Screenshot_20210203-140543_My Files.jpg](https://user-images.githubusercontent.com/66433732/106745461-cdf4d900-6629-11eb-800c-3d4374fa76c3.jpg)![Screenshot_20210203-140500_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/106745473-d0573300-6629-11eb-82fc-ffe23b6ec8b6.jpg)![Screenshot_20210203-140416_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/106745478-d220f680-6629-11eb-9cf1-54c68db4281c.jpg)![Screenshot_20210203-140404_Tachiyomi.jpg](https://user-images.githubusercontent.com/66433732/106745484-d3522380-6629-11eb-97df-f225d3e1c2e4.jpg)

**Comment by scb261** [comment]
Can reproduce, looks like the new decoder problem

**Comment by Bm12347** [comment]
I will close this since it is fixed in the latest update

**Comment by scb261** [comment]
Last update doesn't use the new decoder, it still needs to be fixed

**Comment by inorichi** [comment]
JPEG CMYK and YCCK are supported now.
