### ISSUE TITLE
[Feature Request] Support for Imgur links

### ISSUE THREAD

**Issue by Dangelman** [tachiyomiorg/tachiyomi#4385]
## Why/User Benefit/User Problem
A lot of scalation teams post their chapters on Imgur due to limitations (eg. Mangadex DMCA). The Imgur app is pretty bad for reading mangas, and the websites that repost them take 1-2 days from the scanlation teams' release.
Miscellany comics are also often posted on Imgur.

## What/Requirements
In "Sources", under "Other", add a feature that allows you to import pictures from an URL (Imgur gallery), similar to "Local sources". Example of links: https://imgur.com/a/AIRPpma https://imgur.com/a/knH0d https://imgur.com/a/6FOHO

**Comment by scb261** [comment]
wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions

**Comment by arkon** [comment]
This can be implemented as an extension to handle any Imgur album.

**Comment by Dangelman** [comment]
> wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions

I mean it's not an extension, you're not supposed to browse imgur with it (there are a lot of single pictures), just import links.
