### ISSUE TITLE
[Bug] <MyAnimeList doesn't sync chapters (Neither Automatically nor manually)>

### ISSUE THREAD

**Issue by Umairuem** [tachiyomiorg/tachiyomi#4388]
## Device information
* Tachiyomi version: v0.10.7
* Android version: 7
* Device: HTC One A9

## Steps to reproduce
1. Open a manga entry
2. Read a chapter OR Open "Tracking" section in any entry and update the chapter

### Expected behavior
The chapter should be updated on MyAnimeList when I update it on Tachiyomi.

### Actual behavior
It shows Error 302, and nothing happens to my MAL Account either.

## Other details
I've enabled the Tracking for both Anilist and MAL. Anilist works perfectly fine. But for many weeks, MAL Tracking has been behaving this way even though it was working fine before that. I've tried using "DNS over HTTPS" and clearing cookies and stuff, but the problem is still there. 
I used Tachiyomij2k and thought that it might be the problem because of app, but when I used it on Tachiyomi this problem is still there.
It might be something only limited to my device. But is there any solution for solving such problem? Anilist tracking has been fine, but MAL tracking has been behaving this way for a long time. Is using the VPN or Adblocker on mobile can be a cause of this? Or is there something else that might be the reason it is behaving this way? (I'm using Adguard Adblocker, but I tried disabling this and then using the MAL Tracking, but it still didn't sync).

**Comment by paulo27ms** [comment]
I use Adguard as well and don't have any issues.
Can you actually access MAL's site on a browser? Can you login at all through Tachiyomi? (You might just need to relogin.)

**Comment by arkon** [comment]
Please update to 0.10.8 and login again.

**Comment by Umairuem** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4388#issuecomment-774449547
> Can you actually access MAL's site on a browser? Can you login at all through Tachiyomi? (You might just need to relogin.)

Yes, MAL works everywhere on my phone including Tachiyomi itself, the only problem is that it doesn't sync the chapters. 
I've already tried relogins (and clearing cookies) many times, but it doesn't work.
Now that there's a new update I'll check it. It still is not working on Tachiyomij2k though, I hope they release an update too.
