### ISSUE TITLE
[Feature Request] <Add Additional View Toggles to Chapter List>

### ISSUE THREAD

**Issue by ngomile** [tachiyomiorg/tachiyomi#4389]
## Why/User Benefit/User Problem
Currently the app shows the chapters of a manga as a list with the title and the date. This works well enough but isn't informative if you want to take a glance at what the contents are without opening the  chapter itself. Essentially apart from having thumbnails for the manga itself, the chapters would have thumbnails as well.

## What/Requirements
The feature would need to have a way to toggle between the different view modes, the default list view, a grid view with the thumbnail and title and date beneath and a list view with a leading thumbnail. To change between these views there can be an icon button next to the filter button that shows placeholder of what the view would look like or simply just have the names themselves without the placeholders.

**Comment by scb261** [comment]
Related to #1632, but this one asks for only first page of each chapter

**Comment by arkon** [comment]
I can't find it right now, but a similar request from quite a while ago was already rejected on the basis that chapter pages usually aren't loaded unless it's downloaded or a local manga. The inconsistency would be an issue.
