### ISSUE TITLE
[Bug] auto download doesn't work with categories 

### ISSUE THREAD

**Issue by mohdats** [tachiyomiorg/tachiyomi#4393]
## Device information
App version: 0.10.8-3078 (standard, 45a19d15, 55)
Android version: 7.0 (SDK 24)
Device brand: HUAWEI p9 plus

## Steps to reproduce
1. Update library
2. Waiting for new chapter
3. 

### Expected behavior
This should happen ( when a new chapter appears it's should be in the download queue after the update finish it should start downloading )

### Actual behavior
This happened instead. ( a new chapter appears but it doesn't appear in the download queue )

## Other details
The chapter that I want to download is in a categories and I checked the manga that it is in the categories 

![Screenshot_20210206-225747](https://user-images.githubusercontent.com/73858727/107128917-92c90300-68d2-11eb-9e20-38ef8ef1b657.png)
![Screenshot_20210206-225723](https://user-images.githubusercontent.com/73858727/107128921-9492c680-68d2-11eb-8427-1adb5684b9d4.png)
![Screenshot_20210206-225807](https://user-images.githubusercontent.com/73858727/107128922-952b5d00-68d2-11eb-8825-7e379f759304.png)
![Screenshot_20210206-225650](https://user-images.githubusercontent.com/73858727/107128924-965c8a00-68d2-11eb-85d4-ac87b60f0ab6.png)
![Screenshot_20210206-225723](https://user-images.githubusercontent.com/73858727/107128925-96f52080-68d2-11eb-8e5c-a3f43198f675.png)
![Screenshot_20210206-225726](https://user-images.githubusercontent.com/73858727/107128926-978db700-68d2-11eb-8e3e-8590af357302.png)
![Screenshot_20210206-225811](https://user-images.githubusercontent.com/73858727/107128927-98264d80-68d2-11eb-9258-f10431288baf.png)

**Comment by scb261** [comment]
I couldn't reproduce it either way, but just to get more details - does it happen only with Default category?

**Comment by mohdats** [comment]
> I couldn't reproduce it either way, but just to get more details - does it happen only with Default category?

No it happened to all categories

But when I don't choose any categories it work fine

**Comment by arkon** [comment]
I can't reproduce this.

Do you have steps to reliably make the problem happen?

**Comment by mohdats** [comment]
> I can't reproduce this.
> 
> Do you have steps to reliably make the problem happen?

Put some manga in a categories then choose to download from that specific categories and update the library and wait don't put download at all categories but some specific categories

**Comment by arkon** [comment]
Sorry, but I need more specific reproduction steps than that.

**Comment by mohdats** [comment]
There aren't any thing else to do
![Screenshot_20210210-025121](https://user-images.githubusercontent.com/73858727/107444092-0b39f900-6b4b-11eb-8a04-9f567dad30b2.png)
![Screenshot_20210210-025128](https://user-images.githubusercontent.com/73858727/107444098-0c6b2600-6b4b-11eb-8709-e768245a7cc7.png)
![Screenshot_20210210-025133](https://user-images.githubusercontent.com/73858727/107444099-0d03bc80-6b4b-11eb-9c2b-e98b2675d776.png)




> Sorry, but I need more specific reproduction steps than that.

**Comment by DanAl27** [comment]
I have the same problem.

**Comment by arkon** [comment]
@DanAl27 Do you have reproduction steps?

**Comment by DanAl27** [comment]
> @DanAl27 Do you have reproduction steps?

I believe it's the same as TS, coz after updating the application 2 days ago things just fine, but today it's just weird all of a sudden.

**Comment by mohdats** [comment]
I found that the auto download some time work but most of the time it's doesn't work

**Comment by mohdats** [comment]
Problem solved

**Comment by arkon** [comment]
Did you do something?

**Comment by mohdats** [comment]
> Did you do something?

Nothing 

After the new update it got fixed
