### ISSUE TITLE
[Bug] lag during scrolling chapter list (and possibly during download

### ISSUE THREAD

**Issue by FDmZ** [tachiyomiorg/tachiyomi#4395]
## Device information
* Tachiyomi version: 0.10.8
* Android version: 9
* Device: Samsung Galaxy Note 8

## Steps to reproduce
1. Open a series
2. Tried to scroll down-up the chapters list

### Expected behavior
The scroll should performed smoothly without any lag

### Actual behavior
The scroll performed with lag, especially with a series that has many chapters that required a lot of scrolling

## Other details
I should also add that previous version of tachi (0.10.7) does not have this problem. The new version sometimes causing the lag to occur, especially while I am updating the library
And another user also stated that the lag become worse when they use the app while downloading chapters, sometime causing the phone to froze. Unfortunately I never download chapters so I cannot confirm this particular problem

**Comment by Fatcakes** [comment]
I get lag when scrolling through my library.

**Comment by arkon** [comment]
Let me know if this is any better in v0.10.9.
