### ISSUE TITLE
[Feature Request] Add file compression to save space on device

### ISSUE THREAD

**Issue by PXLCR** [tachiyomiorg/tachiyomi#4404]
I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.8)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---

## Why/User Benefit/User Problem
This feature would allow for better usage of storage space since uncompressed .pngs take up a lot of space
My problem is that I have limited storage space on my device and am not able to always read online, which would mitigaste this issue.

## What/Requirements
This feature would require the implementation of compression for downloaded chapters or entire manga. 
Perhaps chapters could be compressed until the user opens the corresponding manga.
A buffer where the uncompressed chapters are going to be stored would also be required, unless this could be implemented in RAM.

**Comment by scb261** [comment]
Duplicate of #918

**Comment by arkon** [comment]
Also #4415
