### ISSUE TITLE
Updates should only show the latest chapter in the series

### ISSUE THREAD

**Issue by CSalsa** [tachiyomiorg/tachiyomi#4407]
Updates told me that a series got 15 new chapters since the last time I saw it. That means that there were 15 entries of the same series within the same screen, mixing with other updated series. The thumbnails and font are small too, so it's hard to tell between the series sometimes, especially when they don't have a thumbnail.

The updates screen should only show the latest chapter in the series, and possibly the chapter that you left off at.

**Comment by scb261** [comment]
#2774 would be better implementation to solve the problem

**Comment by arkon** [comment]
Closing in favour of #2774, which has more details fleshed out. Feel free to comment on that if you have more ideas.
