### ISSUE TITLE
[Feature Request] Convert chapter or series to epub/mobi etc

### ISSUE THREAD

**Issue by ArcdoesMC** [tachiyomiorg/tachiyomi#4408]
I often use Kindle comic converter to convert chapters or entire series or parts of series into a single mobi/azw3 file for my kindle. But I thought it'd be nice if I could do that in the app so I could either mail it to my kindle or just transfer it over USB.

## Why?
Tachiyomi did a terrific job of sorting, searching, and auto downloading/updating manga. Sometimes I don't read manga for a while or find a new one and want to read it on my kindle for better battery life and a paper like feel.

## What Requirements?
It would obviously be able to set it to advance from right to left reading, I know KCC can automatically do this depending on what settings you use.
As for how the user would do it, they could highlight one or multiple chapters of a series and choose to either convert them individually into separate PDFs/mobi's/azw3's/epub's depending on what format their e-reader needs or they could merge them into one big e-book like chapters 50-55 all in one. I think there are size limitations so if it got too big it would need to be breaken up into separate ebooks. 
You could also convert an entire series into one by highlighting the series, if it's small enough it can be made into one big one, and if not it could be made into parts (MHA pt1/5, pt2/5, etc). And when you are merging multiple chapters into one a table of contents would be generated so you can quickly go to an individual chapter.

##Icing on top
It would be cool if you could also have a built in feature to mail the ebooks to a kindle if you can save the mail-to-kindle address in the app. It would be nice even if it just auto punched the email address and attached the file and opened your default email app and you just had to hit send.

##Unreasonable demands
If when it auto updated different series you could set it to automatically convert that chapter and email it to your kindle that would be fantastic. But I understand at this point it would be straying farther from the app's original intent.

**Comment by scb261** [comment]
Similar to #918, but different formats. And I'm pretty sure sending to e-mail won't happen in any way

**Comment by CarlosEsco** [comment]
you should be using something like https://github.com/manga-download/hakuneko for your use case

**Comment by arkon** [comment]
To expand on what Carlos said, Tachiyomi isn't meant to be used purely as a downloading tool. It's also hard to justify making it convert things into formats that it itself cannot handle (i.e. everything except epub from the given examples, although epubs are already a questionable format).
