### ISSUE TITLE
[Feature Request] <Adding a download in notifications>

### ISSUE THREAD

**Issue by malayangluha** [tachiyomiorg/tachiyomi#4410]
I have this feeling that adding a download link in the notification area after getting the list of updates will be a wonderful feature.

![20210208_182031](https://user-images.githubusercontent.com/78729726/107206725-616b4700-6a3a-11eb-9032-dd07b9446b0d.jpg)

---

## Why/User Benefit/User Problem
(explain why this feature should be added)

## What/Requirements
(explain how this feature would behave)

**Comment by arkon** [comment]
Duplicate of #2986
