### ISSUE TITLE
[Bug] Some mangas can no longer be sorted by Latest Chapter 

### ISSUE THREAD

**Issue by SeriousMatters** [tachiyomiorg/tachiyomi#4412]
## Device information
* Tachiyomi version: v0.10.8
* Android version: 6.0.1
* Device: tablet

## Steps to reproduce
1. Use a source that show chapter uploaded date and add some manga
2. Use a source that do not show chapter uploaded date, such as COCO漫画 (cocomanhua.com), and add some mangas
3. Set Library to sort by Latest Chapter
4. Update Library

### Expected behavior
All mangas with new chapter move to top of library. This is the behaviour in v0.10.7

### Actual behavior
Only mangas with chapter uploaded date move to the top. Mangas from sources without chapter uploaded date stay at bottom. 

## Other details
Most Chinese Manhua sites do not show chapter uploaded date.

**Comment by CarlosEsco** [comment]
If there is no chapter upload date, doesn't that mean all the chapters are grouped at the top (0.10.7) or at the bottom (0.10.8)  and neither are actually sorted by latest chapter

**Comment by CrepeTF** [comment]
Date fetched sorting option should have addressed this issue.
