### ISSUE TITLE
[Bug] Mangadex not updating with latest chapter

### ISSUE THREAD

**Issue by sdair** [tachiyomiorg/tachiyomi#4417]
## Device information
* Tachiyomi version: V10.8
* Android version: 10
* Device: Galaxy note 9

## Steps to reproduce
1. Manually update manga from mangadex

### Expected behavior
New chapter should populate

### Actual behavior
No new chapter

## Other details
https://imgur.com/a/nD8wmQI

**Comment by arkon** [comment]
Wrong repo.

See https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5627
