### ISSUE TITLE
[Feature Request] Consolidate duplicates of a manga from different sources into one

### ISSUE THREAD

**Issue by MangoTornado** [tachiyomiorg/tachiyomi#4418]
## Why/User Benefit/User Problem
I have many manga that are in my library multiple times but in different sources, potentially due to restoring from backup or other migration problems. Its difficult to comb through a long list of manga in order to remove certain ones especially if there are a lot of manga duplicates.

## What/Requirements
Similar to the source migration, there could be a button in the settings menu that allows you to "Consolidate" or "Combine" manga, basically it would go through your library finding duplicates, and allow you to select the source that you want to keep, possibly a list of numbered preferred sources just incase one manga isn't in the top source. I don't know if anyone has used it but similar to the google contacts "Merge and Fix" option that checks for duplicate contacts and merges them into one, however for this function it would just remove the duplicates from the library keeping only the preferred source.

**Comment by scb261** [comment]
Denied before #3596
