### ISSUE TITLE
Searching settings crashes App

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4420]
App crashed when using the search function of the settings to lok for options. No idea why. All information is given below.

## Device information
* Tachiyomi version: 0.10.8
* Android version: 10
* Device: Samsung Galaxy S9+

## Steps to reproduce
1. Go to settings
2. Click the search icon

### Expected behavior
Launch a search interface and allow users to search the settings for different options

### Actual behavior
Crashed

## Other details
One UI Version: 2.5
February's security patch

**Comment by CrepeTF** [comment]
Try doing a [logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp)

**Comment by scb261** [comment]
The app has built-in logcat now. Go to *More > Settings > Advanced > Dump crash logs* and send the file here

**Comment by rsmyst** [comment]
Oh i was trying to find that option. Lemme send it real quick.

**Comment by rsmyst** [comment]
nvm, the issue seems to have fixed itself after I did teh crash report save thing. The search is back to normal

**Comment by arkon** [comment]
@rsmyst please provide the crash log anyway

**Comment by rsmyst** [comment]
Oh alright. H

**Comment by CrepeTF** [comment]
> Oh alright. Here is the crash log from that day.
> [tachiyomi_2021-02-08_10-25.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/5959010/tachiyomi_2021-02-08_10-25.proto.gz)
> 

That's a backup file

**Comment by rsmyst** [comment]
> > Oh alright. Here is the crash log from that day.
> > [tachiyomi_2021-02-08_10-25.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/5959010/tachiyomi_2021-02-08_10-25.proto.gz)
> 
> That's a backup file

May I know where I can find the crash log? I tried looking through the tachiyomi folder in internal storage and only found this file...

**Comment by Bm12347** [comment]
Go to settings then advanced settings then press dump crash logs

**Comment by rsmyst** [comment]
> Go to settings then advanced settings then press dump crash logs

uh... The thing is I can't find a share option AFTER pressing it. It shows open log but there is no option to share it... Where does it get saved?

**Comment by ghostbear** [comment]
It saved in `Android > Data > eu.kanade.tachiyomi > cache`

**Comment by arkon** [comment]
Closing this due to no response.

Will reopen if @rsmyst ever provides the crash logs.

**Comment by rsmyst** [comment]
I seem to have missed the mails from this issue. I'm sorry. 
I would also like to inform that No crash logs were there to be found in the en.kanade.tachiyomi folder. Sorry. I will quickly share the crash logs if the problem comes up again sometime.

**Comment by Sleeping-Donut** [comment]
I have this problem as well
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6096403/tachiyomi_crash_logs.txt)
Tachiyomi version: 0.10.9
Android version: 10
Device: OnePlus 5

**Comment by arkon** [comment]
This should be fixed in the latest preview / for the next stable release.
