### ISSUE TITLE
[Feature Request] Please add a weekly new chapter check option

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4422]
I am a person who reads all the manga I am currently keeping up with weekly. I don't usually check for updates every day since all the manga would have updates every week and it feels better to binge read multiple chapters.
**_Currently, the lowest is 2 days per check. I would like for a 1 week option to be added. THANK YOU Developers._**

**Comment by rsmyst** [comment]
Wait, why was this closed? is this feature impossible? or does it already exist?

**Comment by CrepeTF** [comment]
> Wait, why was this closed? is this feature impossible? or does it already exist?
> 

https://github.com/tachiyomiorg/tachiyomi/commit/aa67229dafb87e298ea5b4826bee5424754d1ee1

**Comment by rsmyst** [comment]
Oh ok. That's cool. TY. I was confused since I don't use github for anything
