### ISSUE TITLE
[Feature Request] Displaying global scores for a manga from the tracking website we are using

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4423]
Getting the average scores/rating of all the manga from for eg: Anilist and displaying it on the main page of that particular manga to make it easy to find the global rating.

---

## Why/User Benefit/User Problem
They would be able to choose between reading a manga easily. It would also become easier to browse and pickup a new series from the app itself rather than visiting the tracking site.

## What/Requirements
Explained above.

**Comment by scb261** [comment]
Denied before #1099 and #3022
