### ISSUE TITLE
[Feature Request] add a button where you can force download a certain page, and other things as well.

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#4424]
## Request
Boost Page (force redownload page).
Page download thread customization.
Predownload the whole chapter while reading (Optional).
Retry immediately instead of wating for the rest of the preloaded pages to finish downloading.
Customize image cache size (how much space Tachiyomi has available to store future pages).

## Why/User Benefit/User Problem
It's just improving quality of reading basically.
Well, currently if you wanna read a specific page, for example page 56/78, you have to wait for the pages before page 56 to download first and then, after waiting for them to download you finally are able to read, but with a button to force download a specific page, you don't have to wait and it can be a whole lot faster.

## What/Requirements
Add a dropdown button on top of the page where you can click that to force download page. 

If you want codes, i don't really know that kind of stuff so you guys have to figure that out yourself. Thank you very much, if you guys actually decide to implement it :).

**Comment by Omar-AbdulAzeez** [comment]
Instead of force downloading a certain page, forcing the app to only download pages starting from the page you are currently on would be better
So if you skip to 50/70 and press that button the app would stop downloading 1-49 and start downloading 50-70

**Comment by CrepeTF** [comment]
Fellas, just download the whole chapter lmao
