### ISSUE TITLE
[Bug] <I can't download anything or read>

### ISSUE THREAD

**Issue by Zextokar** [tachiyomiorg/tachiyomi#4429]
Device Information
Tachiyomi version: 0.10.80
Android version: 7.0
Device: Alcatel
steps to reproduce
First step
Second step
Expected behavior
Should be able to read and download manga

Actual behavior
I can't read and download manga

Other details
Additional details and attachments.

**Comment by CrepeTF** [comment]
Check
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5672

**Comment by Zextokar** [comment]
it is tumangaonline which does not work

**Comment by CrepeTF** [comment]
Issue is on wrong repo then
Also have a look at 
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5479
And
https://tachiyomi.org/help/guides/troubleshooting-problems/
Before making a new issue

**Comment by CrepeTF** [comment]
If you do make a new issue make it on
https://github.com/tachiyomiorg/tachiyomi-extensions/

**Comment by Zextokar** [comment]
Thanks you
