### ISSUE TITLE
[Bug] Is anybody else getting this?

### ISSUE THREAD

**Issue by starkyparky** [tachiyomiorg/tachiyomi#4434]
## Device information
* Tachiyomi version: 1.08
* Android version: 10
* Device: Samsung S9+

![Yankee Jk Kuzuhana-Chan - Chapter 44_ Tug of Love - 1](https://user-images.githubusercontent.com/78871755/107548667-e5bff480-6c09-11eb-8340-fd6a7dc03335.jpg)

**Comment by arkon** [comment]
Yes, you can see the website itself is affected. There's nothing for Tachi to do.
