### ISSUE TITLE
A mysterious message appears

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi#4440]
## Device information
* Tachiyomi version: up to date
* Android version: 10
* Device:oppo a5 2020

## Steps to reproduce
1. I open any manga
2. Second step

### Expected behavior
Pages appear

### Actual behavior
The is nothing

## Other details
This important
https://user-images.githubusercontent.com/75262438/107564469-252b1880-6beb-11eb-8da1-fc9fde6fac96.mp4
![Screenshot_2021-02-10-21-36-59-90_afd66b7916d19a60815f56273408b73e]
(https://user-images.githubusercontent.com/75262438/107564802-89e67300-6beb-11eb-9867-a9a22421caf4.jpg)

**Comment by scb261** [comment]
Check WebView, not tachi issue
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

**Comment by hakudansho** [comment]
What shoud i do then??!

**Comment by CrepeTF** [comment]
Not Tachiyomi thing, what you expect us to do?
Just migrate away from the source or wait it out

**Comment by Vanjiga** [comment]
Of you use mangakakalot extension its the issue with the site not the app. If you open the site you can replicate it 
![IMG_20210210_214536](https://user-images.githubusercontent.com/69387875/107570075-5a366b80-6be9-11eb-93d0-e8bdfc4c0197.jpg)

**Comment by CrepeTF** [comment]
Also this is the wrong repo anyway

**Comment by hakudansho** [comment]
Not only mangakakalot but also mangabat and it appears also in the website
,i really don't know what to do anymore. 😔😔😔

**Comment by hakudansho** [comment]
I hope other extensions remain unchanged.🥺🥺

**Comment by arkon** [comment]
Please stop spamming our email inboxes with something that isn't in our control.
