### ISSUE TITLE
Searching for manga updates problem

### ISSUE THREAD

**Issue by ConfusedDiscord** [tachiyomiorg/tachiyomi#4442]
## Device information
* Tachiyomi version: 

App version: 0.10.8 (standard, 45a19d1, 55)
Android version: 10 (SDK 29)
Android build ID: RMX2040_11_A.38
Device brand: realme
Device manufacturer: realme
Device name: RMX2040
Device model: RMX2040
Device product name: RMX2040EEA

## Steps to reproduce
1. When updating manga, any title you have bookmarked from mangahere will take too long to update, it took me almost 10 minutes to update my bookmarks.

## Issue/Request
problem with searching for updates

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
@ConfusedDiscord Please share the crash logs.

More > Settings > Advanced > Dump crash logs

**Comment by ConfusedDiscord** [comment]
The crash is zero bytes, and i can't send it. My app did not crash

**Comment by ConfusedDiscord** [comment]
It was not the apps problem, sorry for this request
