### ISSUE TITLE
[Bug] is anybody else getting this?

### ISSUE THREAD

**Issue by starkyparky** [tachiyomiorg/tachiyomi#4444]
## Device information
* Tachiyomi version: 1.08
* Android version: 10
* Device: Samsung s9+

## Steps to reproduce
1. Open tachiyomi
2. Open a manga

### Expected behavior
Manga opens

### Actual behavior
Black screen with text appears

## Other details
Started around 5 hours ago and now it wont work on anything

![Yankee Jk Kuzuhana-Chan - Chapter 44_ Tug of Love - 1](https://user-images.githubusercontent.com/78871755/107583621-26cdfe00-6c36-11eb-8015-86d6799a5768.jpg)

**Comment by arkon** [comment]
You already asked 5 hours ago.
