### ISSUE TITLE
[Feature Request] Have sources in the library act like tags or similar to it

### ISSUE THREAD

**Issue by HybridOta** [tachiyomiorg/tachiyomi#4446]
## Why/User Benefit/User Problem
Currently in the library you can search for multiple tags with "," and exclude with "-" but you cannot with sources.
I know you can search for a specific source in general but examples like
-MangaDex
or
MangaPark, Fantasy
are not currently possible.

## What/Requirements
Have sources names act similar to tags in the library search.

**Comment by Presac** [comment]
This would be especially useful right now to filter out source entries from the library when there are downtimes. E.g currently mangadex has a lot of downtime in periodes where it could be smart to be able to filter out those Manga in question.
