### ISSUE TITLE
[Bug] Favorited chapters for now-deleted sources show no downloads but they're still on storage 

### ISSUE THREAD

**Issue by HereticWilson** [tachiyomiorg/tachiyomi#4449]
## Device information
* Tachiyomi version: r3095
* Android version: 9
* Device: honor view 10

## Steps to reproduce
1. Have a favorited manga title, with unread and downloaded chapters, under a source that is now deleted because  of the great multi source extension purge. Note that it no longer shows downloaded unread chapters. On advice of mod in support channel, unfavorite, hoping to be offered option to delete downloads. Fail to be offered that option. After ID matching check SD card and find chapters are still in old folder for source. Meaning dozens of titles with downloads must be manually hunted down and deleted 
2. Check a second title, from a different now-deleted source, and then also get no offer to delete downloads, and also confirm that chapters are still present on SD card. 

### Expected behavior
Either change the folder name to the numerical code or auto delete chapters when it's decided we don't get to have that extension anymore. 

### Actual behavior
Chapters sit there taking up space till ID matched and hunted down one by one. 

## Other details
Additional details and attachments.

**Comment by HereticWilson** [comment]
Oh fuck off I forgot to write the title

**Comment by arkon** [comment]
Addressed by #6389
