### ISSUE TITLE
[Bug] All of my downloaded sources/extensions just suddenly all disappeared as if they were never installed then reappear after idk how long

### ISSUE THREAD

**Issue by nak2303** [tachiyomiorg/tachiyomi#4453]
## Device information
* Tachiyomi version: 0.10.8
* Android version: 10
* Device: xiaomi redmi k20 pro

## Steps to reproduce
idk, it just randomly happens

## Other details
video 
[https://drive.google.com/file/d/1nz1v6rXgnpzCxnFZWtAJJuTSi8DTygX3/view?usp=sharing](url)

**Comment by arkon** [comment]
Try going through https://dontkillmyapp.com/xiaomi

**Comment by nak2303** [comment]
I have turned autostart on and set battery saver to no restrictions but it's no use, it still happens

**Comment by arkon** [comment]
There was this, but it's only relevant for Android 11: https://github.com/tachiyomiorg/tachiyomi/issues/4313

This seems like a system-level issue though, most likely having something to do with Xiaomi's famously sloppy software.
