### ISSUE TITLE
[Bug] <Restoring from back up doesn't restore all titles>

### ISSUE THREAD

**Issue by Puddintame349** [tachiyomiorg/tachiyomi#4456]
## Device information
* Tachiyomi version: v0.10.8
* Android version: 10
* Device: Galaxy S8

## Steps to reproduce
1. Delete app data and uninstall
2. Reinstall app, and attempt to restore from manual backup (new backup type)

### Expected behavior
All manga, including any downloads, should be restored in ~15-25 minutes

### Actual behavior
The app displays a notification claiming that the restore was finished in only a few seconds. (In the latest example, it said two seconds.) In reality, only a relative handful of manga have actually been restored. As of my latest attempt, outside of the inital list, only a few more manga have popped up in the library in the last 3 hours. It seems like not much is being done, otherwise.

## Other details
This seems to have coincided with the latest update. Also worth noting I tried this twice, with approximately the same effects.

P.S. On the subject of the library, could we get an option to choose what time of day the library updates for daily updates? This would be immensely more convenient than trying to set it indirectly.

Thanks.

**Comment by CrepeTF** [comment]
Downloads aren't insured by [any] backups

**Comment by Puddintame349** [comment]
> Downloads aren't insured by [any] backups

That's not really the main issue to me, though I would point out that all my experience with previous backups resulted in the downloads also being restored

The real problem is that the bulk of my titles are missing and that the backup really doesn't seem to be working as intended

**Comment by arkon** [comment]
Can you share your backup file? I also assume you're restoring on a fresh version of the app with no library?

**Comment by scb261** [comment]
@jobobby04 said that he knows the reason and it actually restores in background without progress notification, but I'm not sure if 9f9f987 is the fix for it

**Comment by Puddintame349** [comment]
@arkon 
Yes. Given the reinstall, the app itself was fresh, except for signing in to trackers and MangaDex

@scb261 
Interesting, though I'm confused as to why it's so very slow. My number of downloads are about the same as the last time I did a back up a month or so ago, and that took about a little less than 20 mins

**Comment by arkon** [comment]
@Puddintame349 I need the file.

**Comment by arkon** [comment]
Also, are you choosing offline or online as the restore mode?

**Comment by jobobby04** [comment]
Now that restoring launches each manga restore in IO, the backup service thinks that the restore for that manga is done, which lets it complete and stop itself before the restores are done

**Comment by arkon** [comment]
Guess I don't need the file anymore. :D

**Comment by Puddintame349** [comment]
> Guess I don't need the file anymore. :D

Alright. Sorry for the delay. Got distracted.

P.S. I think I did both offline and online, but online for sure

**Comment by Puddintame349** [comment]
Update:
I tried it offline again, and it seems to have worked this time. Not sure why it didn't work as well the last "offline" try, but it seems to have this time. Mostly, at least. It's also a little annoying not having my downloads, but this can certainly work til the next update

**Comment by arkon** [comment]
Downloads aren't part of the backup, and never have been. They just work based on the names, so if the names are still the same, they'll appear to work as before.

**Comment by arkon** [comment]
Let me know if this is any better in v0.10.9.

**Comment by Puddintame349** [comment]
> Let me know if this is any better in v0.10.9.

The restore went smoothly, and took about 20.5 minutes.

Thanks guys
