### ISSUE TITLE
[Bug] Some pages in mangakakalot don't load

### ISSUE THREAD

**Issue by kmqx** [tachiyomiorg/tachiyomi#4459]
## Device information
* Tachiyomi version: stable 0.10.8
* Android version: 10
* Device: Galaxy S9

## Steps to reproduce
1. Open Manga
2. Try to read

### Expected behavior
All pages should load

### Actual behavior
Some pages do not load or they take very long to load

## Other details
Chapter seems to load normally in webview
Tried Clearing cache, cookies, database, history

**Comment by scb261** [comment]
Wrong repo and duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5276
