### ISSUE TITLE
[Feature Request] showing manag score in mangadex titles.

### ISSUE THREAD

**Issue by Triplesweet** [tachiyomiorg/tachiyomi#4462]
Showing the user score and number of the voters for the mangadex titles.
---

## Why/User Benefit/User Problem
Telling us if the manga really is worth the try or not. Or it is liked or disliked by how many person, with out opening the webview

## What/Requirements
An extension update to fetch the score and number of the voters and a update to the apk to show the data in description (or with a new api with icons And stuff if you feel generous)

**Comment by scb261** [comment]
Implementing your request would mean changing interface between the app and extensions, and this won't be done for a feature that already was denied for trackers (see #1099 and #3022), were it would be easier to implement.
