### ISSUE TITLE
Invalid backup file

### ISSUE THREAD

**Issue by astraea19** [tachiyomiorg/tachiyomi#4463]
Device information
Tachiyomi version: 0.10.8
Android version: 10
Device: Samsung Galaxy J6

Steps to reproduce
1. Restore backup
2. Pick backup source and choose network mode

Issue/Request
When restoring backup, either offline and online choices wouldn't work. It would pop a message saying "gzip finished without exhausting source".

Other details
This happened after I reinstalled the app. I made sure to use the same extensions again but it just won't work.

**Comment by arkon** [comment]
Can you share the backup file?

**Comment by Moralde-Sama** [comment]
@arkon [https://cdn.discordapp.com/attachments/800688431641526313/809291934572347402/tachiyomi_2021-02-11_06-17.proto.gz](tachiyomi_2021-02-11_06-17.proto.gz) It's @astraea19 backup file.

**Comment by astraea19** [comment]
Hello can I ask an update regarding this issue? Thank you.

**Comment by curche** [comment]
Checked the file that was sent
It seems that the backup file is now corrupted and that is why restore fails
Thus, this file can't be used for restoring.

I'm unsure what caused the file to be corrupted though. 
On my device (xiaomi), I was able to create and restore backups fine.

If this issue persists even when you try to restore a new backup, do report again.

**Comment by arkon** [comment]
Yup, unfortunately can't do much about a corrupted file. Try to keep multiple backups if possible.

**Comment by astraea19** [comment]
Thank you very much.
