### ISSUE TITLE
[Bug] MAL won't tracking some manga 

### ISSUE THREAD

**Issue by raijinraz0r** [tachiyomiorg/tachiyomi#4466]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: 8.1.0
* Device: Samsung

## Steps to reproduce
1. Open a manga
2. Add a MAL tracker on it

### Expected behavior
After step 2, a tracker on a manga should have been added

### Actual behavior
Getting HTTP error 400 even after troubleshooting, update the app, force stop and update MAL app

## Other details
I'm using mangahere and even migrate the manga to mangakakalot, some manga getting HTTP error 400 like 100-nin no eiyuu o sodatate saikyou yogensha wa and A betrayed S-rank adventurer, I make a slave only harem guild.

**Comment by DarremMolko** [comment]
This happened to me before and the solution was shortening the manga's title, in your case try searching only "100-nin no eiyu" or just "100-nin". I'm not sure why it throws error 400 when the title is too large.

**Comment by arkon** [comment]
This seems to be an issue with MAL. As @DarremMolko mentioned, try adjusting your search. If the search results aren't precise enough, you can always use the following workarounds that are implemented specifically for MAL search:

- Search by ID using `id:####`
- Search your added list titles using `my:title`
