### ISSUE TITLE
[Feature Request] Extension wise filter option in Library

### ISSUE THREAD

**Issue by VishalNikam1295** [tachiyomiorg/tachiyomi#4469]
---

## Why/User Benefit/User Problem
Sorting out various manga added from multiple extensions.

## What/Requirements

In the oprions which slide up when tapped on the Library Button, there should be a category of filters which lists out the extensions from which various mamga are added. Clicking on their respective check boxes keep the manga taken only from those extensions and hides the rest, just like the Unread/Downloaded/Completed/Tracked filter.

**Comment by CrepeTF** [comment]
You can type the source name into the search bar and it'll filter to manga from that source
