### ISSUE TITLE
[Bug] app exist itself

### ISSUE THREAD

**Issue by JOJOyesyesyes** [tachiyomiorg/tachiyomi#4472]
Tachiyomi version: 0.10.8
Android version: 7
Device: accent pearl a4 plus
so my problem is with the application is that when I start browsing for a new manga from browse it's just keep exit from the app
and this bug isn't new it was from the last version and I really did updated the app
I hope you guys fix this I hope it's not just me

**Comment by JOJOyesyesyes** [comment]
help please

**Comment by scb261** [comment]
Make sure you have updated all extensions, [WebView](https://tachiyomi.org/help/guides/troubleshooting-problems/#update-webview) and [the app](https://tachiyomi.org/download/) (it's 0.10.9 now). If still happens - please share crash log here (More > Settings > Advanced > Dump crash log > Share)

**Comment by arkon** [comment]
Please open another issue with crash logs if you're still experiencing this on 0.10.9.
