### ISSUE TITLE
[Bug] <mangadex bug>

### ISSUE THREAD

**Issue by Yuuaki** [tachiyomiorg/tachiyomi#4479]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 9 
* Device: zenphone

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.
Issue:
Mangadex new chapter doesn't update
Not even show new chapters after refreshing

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5780
