### ISSUE TITLE
Trying to install app

### ISSUE THREAD

**Issue by Nerodacles** [tachiyomiorg/tachiyomi#4483]
##Device information
Tachiyomi version: 10.0.9
Android version: 11
Device: Xiaomi Mi A3

##Steps to reproduce
1. Try to install it
2. Fails every time

###Expected behavior
It installs

###Actual behavior
Fails

**Comment by scb261** [comment]
Do you have f-droid version installed? If yes - remove it (backup first). If not - try to install with [sai](https://play.google.com/store/apps/details?id=com.aefyr.sai), it will either install the app or will give more useful error

**Comment by Nerodacles** [comment]
> Do you have f-droid version installed? If yes - remove it (backup first). If not - try to install with [sai](https://play.google.com/store/apps/details?id=com.aefyr.sai), it will either install the app or will give more useful error

ok, let me do it.

**Comment by Nerodacles** [comment]
well, i had to do the android adb uninstall [pakage], beacause when i uninstalled it a few months back, it left some things, and the phone believed that it was an app. Sorry for my grammar, english isnt my first language.
