### ISSUE TITLE
Ability to filter tags out from sources

### ISSUE THREAD

**Issue by Volern** [tachiyomiorg/tachiyomi#4484]
The ability to filter out some tags from a source would be great. For example there are a fair few sources with good stuff but a lot of ecchi or hentai manga that take up a lot of the source e.g. Bato.to, which can be annoying to try and find anything good on the source. 

The ability to filter those tags out would make some sources way better to go through. Currently some sources let you filter for specific tags, but not filter out tags, atleast that's how it appears it should work but I have noticed that pressing on a tag just searches the text rather than going through tags, perhaps that is something to be looked in to adding/fixing too. 

Perhaps having the filter set in the extension settings would be a good place for it so you don't have to set it every time you want to use the source.

I get that this may not work for some sources because some dont let you filter for tags within it, but for those that can it would be a good addition.

**Comment by scb261** [comment]
That depends on the source/extension you're using, not the app. If there is a tag filter on the site, request it to be added to the extension https://github.com/tachiyomiorg/tachiyomi-extensions/issues

As for saving filters - #1484
