### ISSUE TITLE
[Feature Request] bypass Cloudflare security

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi#4488]
## Why/User Benefit/User Problem
(explain why this feature should be added)
I can't reade some source because cloudflare security check 
## What/Requirements
(explain how this feature would behave)

**Comment by Noname-noragami** [comment]
One of them is cloundflare.captcha

**Comment by scb261** [comment]
https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-the-cloudflare-issue
