### ISSUE TITLE
[Bug] <app crashed when I migrate>

### ISSUE THREAD

**Issue by Haru4278** [tachiyomiorg/tachiyomi#4491]
---

## Device information
* Tachiyomi version: 0.10.9
* Android version: 9
* Device: Vivo y11

## Steps to reproduce
1. First step: I opened the manga called "The max level hero has returned"
2. Second step: the tapped the thee dots on the upper right corner, then select migrate, then choose manganelo to migrate

### Expected behavior
The app will open the manga then it will migrate the manga

### Actual behavior
Before I even open the manga the app crashed

## Other detail
 video: https://drive.google.com/file/d/1e6AbRJF9wE4RkNEie3HpTc2iO4tdYE9d/view?usp=drivesdk

logs: https://drive.google.com/file/d/1eAo59W0f5LfIgVxHSX_3hiEMk2-riFxE/view?usp=drivesdk

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Are you able to reproduce consistently? If so, can you also share what extensions you have, assuming they're all updated?

**Comment by Haru4278** [comment]
for now I asked the members of the Discord server. and they said that the
Hitomi extension causes it. I removed it and tried to migrate then it
didn't happen again.

**Comment by Haru4278** [comment]
Awesome, thanks!

**Comment by arkon** [comment]
FWIW, I don't have a good solution to this since Hitomi is very complex and it seems to be running out of memory. If you need to migrate, you may be better off manually searching only in Hitomi for it to avoid the extra overhead of searching the other sources.

(Or use a source that isn't as crazy)
