### ISSUE TITLE
[Feature Request] request add "only next page" reader navigation mode

### ISSUE THREAD

**Issue by AlphaAnother** [tachiyomiorg/tachiyomi#4492]
## Why/User Benefit/User Problem
when controlling the phone with one hand, it is difficult to touch the next page zone after switching to the other hand, but it is still easy to scroll back to the previous page.
## What/Requirements
modify the previous page zone of the L-shape into the next page zone.

**Comment by curche** [comment]
Have you checked other navigation options?
The Edge Navigation might be useful

For a visualisation of each option, check this issue comment: https://github.com/tachiyomiorg/website/issues/503

**Comment by Omar-AbdulAzeez** [comment]
Why not just use the bottom edge? Anywhere below the center is the next page

**Comment by AlphaAnother** [comment]
> Have you checked other navigation options?
> The Edge Navigation might be useful
> 
> For a visualisation of each option, check this issue comment: [tachiyomiorg/website#503](https://github.com/tachiyomiorg/website/issues/503)

thanks! i'm confused because there is no navigation zone preview.

**Comment by curche** [comment]
I guess your issue is now resolved and can be closed

As for this:
> there is no navigation zone preview

do make a new feature request
