### ISSUE TITLE
[Feature Request] <Save your email Mangas, "Manga Bird style".>

### ISSUE THREAD

**Issue by deividgabrielpeira** [tachiyomiorg/tachiyomi#4497]
PLEASE READ THIS

I acknowledge that:

I have updated to the latest version of the app (stable is v0.10.9)
I have updated all extensions
If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---
### Why/User Benefit/User Problem
If someone loses their phone or gets stolen, they can save it on their computer, but they get lost too! a guy saves but 500 mango but not that to repeat again even lost the backup.
This almost identified system or "manga bird".

---

### What/Requirements
Email system that saves your sleeves, even with a stolen cell phone and lost your backup on the computer, so as not to have too many problems with emails, just do a cell phone verification system or activate code, if you have ghost email (it is inactive) for a few 30 days should be deleted so it doesn't cause a lot of problems with the servers.

**Comment by CarlosEsco** [comment]
There are no plans to have a Tachiyomi server.  Use something like this with auto backups enabled  
https://play.google.com/store/apps/details?id=com.ttxapps.drivesync&hl=en_US&gl=US
