### ISSUE TITLE
[Bug] <Some downloaded chapters are converted into some unreadable unwritable file after downloading>

### ISSUE THREAD

**Issue by Arkonil** [tachiyomiorg/tachiyomi#4500]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 7.0
* Device: Redmi Note 4

## Steps to reproduce
Download chapters into storage.

### Expected behavior
The chapter should be downloaded with a tree like structure (Ex. Tachiyomi -> downloads -> Website or Extension Name -> Manga Name -> Chapter title -> images) with each chapter folder containing its images.

### Actual behavior
The chapter folder is created -> all images but the last one downloaded (So far so good) -> last image downloaded -> the chapter folder is converted into some kind of unreadable, unwritable file which I cannot even delete from my storage. 

## Other details
This issue occurred in a number of extensions (Webtoons, MangaOwl, ReadManga etc.) and the chapters that are showing this issue are random (I cannot sense any type of pattern there). For example, it occurred in the manga "Us Right Now" from "webtoons.com" chapter 2, 17 etc.

![WhatsApp Image 2021-02-17 at 12 25 07 PM](https://user-images.githubusercontent.com/69111799/108167248-68214a80-711b-11eb-866a-0e8230fd7206.jpeg)

And what about the date and time of the file created?

**Comment by Omar-AbdulAzeez** [comment]
@Arkonil Send the logs

**Comment by Arkonil** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/5995239/tachiyomi_crash_logs.txt)

I have added the logs though I don't think it will show the error. Because, if I open a chapter with this issue the app just shows black screen as if all images in the chapter is pure black, nothing else. I can still scroll through the chapter and it shows the next chapter just fine (that is if the next chapter doesn't have the same problem).

**Comment by arkon** [comment]
Seems like a device/ROM issue...
