### ISSUE TITLE
[Feature Request] For offline restore, mention whether the error was by tracker or not

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#4504]
## Why/User Benefit/User Problem
(explain why this feature should be added)
While doing an offline restore on Sy Preview fork (r338), the following error was observed:
```
[2021-02-17 12:52:49.799] Ookami Shounen wa Kyou mo Uso o Kasaneru - HTTP error 429
[2021-02-17 12:52:49.859] Osananajimi ni najimitai - HTTP error 429
[2021-02-17 12:52:50.224] Orenchi no Maid-san - HTTP error 429
[2021-02-17 12:52:50.867] Rengoku no Ashe - HTTP error 429
[2021-02-17 12:52:51.170] SAKAMOTO DAYS - HTTP error 429
[2021-02-17 12:52:51.578] Sakurai-san Wants to Be Noticed - HTTP error 429
[2021-02-17 12:52:51.737] See You at the Food Court Tomorrow. - HTTP error 429
```
This is likely caused by Anilist tracker (which I use) since it was an offline restore.
The manga are actually present in library and a quick refresh also fixed the tracker data.

## What/Requirements
(explain how this feature would behave)
Explicitly mention when the Tracker is the one causing the Error
Example: 
```
[2021-02-17 12:52:49.799] Ookami Shounen wa Kyou mo Uso o Kasaneru - HTTP error 429 (Anilist)
```
Format needn't be the same and could be better

**Comment by Omar-AbdulAzeez** [comment]
Maybe if tachiyomi can test for internet connection before restoring it would be a good idea to show a pop up informing the user that an offline restore will happen and that tracking data will not be restored and prompting the user for an answer
Then tachiyomi in this case could just ignore the tracking data

In the case of a normal restore tho its still a good idea to show which part in the restore is causing the error besides the too many requests error

**Comment by arkon** [comment]
Closing since offline restore doesn't update trackers anymore.

**Comment by curche** [comment]
To be clear, from now on, after restoring from the backup, we have to refresh tracker metadata from advanced settings. Right?

Would a feature request for adding a button to Restore success notification to start 'Refresh Metadata' make sense? The button would call that function (used from advanced settings)

**Comment by arkon** [comment]
Yeah, you could create a new issue for that.
