### ISSUE TITLE
[Bug] Mark chapter as unread causes UI problems

### ISSUE THREAD

**Issue by Horodep** [tachiyomiorg/tachiyomi#4505]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Samsung A71

## Steps to reproduce
1. Open a title with at least 100 chapters
2. Mark chapter as unread
3. Go back to library

### Expected behavior
After step 2 chapter has to be marked unread.
After step 3 UI has to be correctly displayed.

### Actual behavior
After step 2 chapter is not marked as unread
After step 3:
Library UI missing: refresh button, category titles
Library horisontal scroll doesn't work correctly, screen can be stopped between the categories.

## Other details
Swapping app to another and back fixes problems.

![image](https://user-images.githubusercontent.com/8913017/108306178-acb0f280-71bc-11eb-82ac-d8809c9eb5de.png)

**Comment by Horodep** [comment]
Video:
![video](https://cdn.discordapp.com/attachments/349436576037732355/811812646067240972/Screen_Recording_20210218-071220_Tachiyomi.mp4)

**Comment by Horodep** [comment]
https://user-images.githubusercontent.com/8913017/108306695-c999f580-71bd-11eb-964a-23fc08c8dd0f.mp4

**Comment by giosann** [comment]
If you need I also had this issue (latest preview):

https://youtu.be/GtTWDF83Kng

App version: 0.10.9-3128 (standard, 776610d0, 56)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.T865XXS4BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea
