### ISSUE TITLE
[Bug] Tachiyomi crashes when rotating while reading

### ISSUE THREAD

**Issue by apav** [tachiyomiorg/tachiyomi#4506]
## Device information
* Tachiyomi version: r3121
* Android version: 11
* Device: Galaxy Note 20 Ultra

## Steps to reproduce
1. Open a manga chapter
2. Rotate your phone back and forth. The amount of rotates it takes to crash varies every time for me. 

## Issue/Request
I'm on dev but I have noticed this issue happening for about two weeks. After opening Tachiyomi back up after the crash, the  manga and chapter I was reading when it crashed doesn't appear in my history. I also don't get any "Tachiyomi has stopped working" sort of error message either. 

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

https://gist.github.com/apav/b7f85237e4aa19cddacf6075b2e40d64

**Comment by TacoTheDank** [comment]
I crashed it a couple times, here's the log. Android 10 device. https://gist.github.com/TacoTheDank/925f8db82aba2b5c4aa6f031872144ba

**Comment by inorichi** [comment]
Fixed with d4c9ab7
