### ISSUE TITLE
[Bug] Not resuming when all chapters are marked as read

### ISSUE THREAD

**Issue by saket1999** [tachiyomiorg/tachiyomi#4509]
## Device information
* Tachiyomi version: 0.10.9
* Android version: Android 10
* Device: OnePlus 6T

## Steps to reproduce
If manga is marked as read and one reads from beginning or any other chapter and then leaves. Then on pressing resume button, either it jumps to first unread chapter or nothing if all chapters are marked as read.

### Expected behavior
The manga should be resumed from where it was left.

### Actual behavior
Either nothing happens if all chapters are marked as read or first unread chapter is opened.

**Comment by CrepeTF** [comment]
That's not a bug, that's how it works. It chooses the oldest unread chapter.

There's already a github issue to change it to choose the latest read chapter or something like that.

**Comment by CrepeTF** [comment]
#1399

**Comment by saket1999** [comment]
Thanks, I thought it was a bug cause that's how it was supposed to work.
