### ISSUE TITLE
[Feature Request] Set a cooldown between request

### ISSUE THREAD

**Issue by Sosep** [tachiyomiorg/tachiyomi#4510]
## Why/User Benefit/User Problem
In some servers there are limited the number of request in a determined quantity of time. If we have got many mangas when we upgrade the chapters we have to do it one by one.

## What/Requirements
I think that it would be a option, in the extension settings or in the global settings to set the cooldown in seconds.

**Comment by arkon** [comment]
Rate limiting is set within each source programatically. If you're noticing that some sources require rate limiting, open issues in [the extensions repo](https://github.com/tachiyomiorg/tachiyomi-extensions).
