### ISSUE TITLE
can you please add azporncomics.com to the app extensions?

### ISSUE THREAD

**Issue by rahul1522** [tachiyomiorg/tachiyomi#4512]
## Why/User Benefit/User Problem

It contain some different type of comics and some of them are not available in already existing sources

**Comment by scb261** [comment]
wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions/issues

**Comment by Bm12347** [comment]
Someone close this

**Comment by rahul1522** [comment]
ty
