### ISSUE TITLE
[Bug] Tachiyomi crash when opening and downloading a chapter

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi#4515]
## Device information
* Tachiyomi version: v0.10.9 (and forks)
* Android version: AOSP 7-11

## Steps to reproduce
1. Open/download 32 Chapter of the manga https://remanga.org/manga/lightning-degree (Lightning Degree)
2. When opening it lags and then crash 

## Other details
I am writing here, and not in extensions, because Tachiyomi flies out and not on all devices(with exceptions ).
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6011433/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Your device doesn't have enough memory to handle the images.

**Comment by e-shl** [comment]
@arkon, on one device 1.5 gigabytes are free and does not crash, and on the other 2 gigabytes and crashes

**Comment by arkon** [comment]
```
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 48487692 byte allocation with 16777216 free bytes and 41MB until OOM
```

Your system is reporting that that's only 0.01GB free.

Regardless, this seems to be a result of the Remanga extension trying to build images: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt#L348

Not entirely sure if the extension can attempt to handle that better.
