### ISSUE TITLE
[Feature Request] "Download new chapters" whitelist/blacklist

### ISSUE THREAD

**Issue by LordZZT** [tachiyomiorg/tachiyomi#4516]
Howdy, 
As the title suggests I'd like it if I were able to limit the use of the "Download new chapters" feature to specific manga.
To me, a whitelist/blacklist filter makes the most sense/is easiest to implement and use.

## Why/User Benefit/User Problem
Some manga are just not worth the hastle of downloading.

## What/Requirements
N/A

**Comment by Seishirou101** [comment]
you can specify what categories to download.

**Comment by LordZZT** [comment]
I was unaware, where is the option located? If you don't mind sharing.

I do still think this suggestion is beneficial

**Comment by Seishirou101** [comment]
its right under the option where you enable download new chapters.

**Comment by LordZZT** [comment]
Odd, must be in one of the new builds, I'm only on 0.10.7 due to fdroid, and the 0.10.9 fails to update for w/e reason.
I didn't see that in the changelohs for 0.10.8, and 0.10.9 unless I'm blind

**Comment by arkon** [comment]
It's been there for years.

**Comment by LordZZT** [comment]
Ah, turns out you need to have the downloading enabled for it to show.

Works I guess
Tad rude to slam the door though
