### ISSUE TITLE
Not all manga settings are per-manga

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#452]
In the settings modal, only `Viewer for this series`/`Default viewer` is per-manga. It is also the only option which has `Default` as an option.

For example, if your global reader setting for `Scale type` is `Fit height`, changing this to `Stretch` in the modal will make all manga open with that setting.

This is particularly annoying with many manhwa, which are generally read left-to-right - as I have the zoom start position on the right and swiping right to left. Which means until all the settings are per-manga I have to swipe the page to the left every page, or change the reader settings every time going from manga -> manhwa -> manga.

Version: r857

**Comment by Noc0002** [comment]
I would also like this feature, especially the ability to set rotation per manga since I prefer to set force portrait for some manga and landscape for others.

**Comment by AthanFields** [comment]
This rotation by manga feature could facilitate reading a lot, since most of us, I assume read webtoons and mangas that have different images ratios. Having that option to open your series in it's preferred orientation would be nice.

**Comment by Unnnordinary** [comment]
May I request to this feature to have 𝗦𝗽𝗲𝗰𝗶𝗳𝗶𝗰 𝘀𝗲𝘁𝘁𝗶𝗻𝗴𝘀 for orientation 𝗽𝗲𝗿 manga. For example, I want to read manga in 𝗙𝗼𝗿𝗰𝗲𝗱 𝗹𝗮𝗻𝗱𝘀𝗰𝗮𝗽𝗲 𝗺𝗼𝗱𝗲 and Webtoon in 𝗽𝗼𝗿𝘁𝗿𝗮𝗶𝘁 𝗺𝗼𝗱𝗲. I see that you can change orientation when you start reading the manga but when you change that, It is applied to global settings, what I request is for it to be applied for the specific opened manga.
Thank you!

![IMG_20210228_014057](https://user-images.githubusercontent.com/79761416/109395188-0906d580-7966-11eb-8b86-ce6c634210bf.jpg)

**Comment by arkon** [comment]
Closing this since rotation was added. There's a lot of settings that aren't per-manga, so if there's specific ones wanted, please create individual issues for those.

**Comment by wopian** [comment]
The only two settings mentioned in my issue were not addressed.
