### ISSUE TITLE
[Feature Request] <Daily Screen time limiter option>

### ISSUE THREAD

**Issue by kuroBi99** [tachiyomiorg/tachiyomi#4521]
---

## Why/User Benefit/User Problem
(This feature helps addicted users by helping them manage their daily usage time, it's especially very useful for students who have their exams coming and want to spend a more specifically limited time on the app than their average days. Users will have better time management, better lifestyle and life. this solves the addiction problems)

## What/Requirements
(Once the feature starts it shall not be canceled, not like how you can cancel Digital wellbeing )

**Comment by arkon** [comment]
This is widely out of scope. I understand that some people have poor self control, but individual apps shouldn't need to have the infrastructure to curb that.

You could experiment with just turning off your phone and giving it to someone else when you need to actually focus.
