### ISSUE TITLE
[Feature Request] <languages written from right to left >

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/tachiyomi#4522]
currently the app mirrors the controls and interface when using the app in arabic 

it would be nice if we could disable this or choose not to change from the base look

**Comment by arkon** [comment]
Why would you not want _some_ apps to not be in RTL if you're using an RTL locale? It isn't that easily configurable.

**Comment by areyance** [comment]
> Why would you not want _some_ apps to not be in RTL if you're using an RTL locale? It isn't that easily configurable.

some apps simply work better for me with the LTR format since the absolute majority of apps have a similar format 
  most the time dont even provide the option for arabic/ or keep it the same while the words are all messed up ,not fitting the boundaries of the intended LTR design 
so i just got used to that shit

if its a software limiation and just an annoyance u can discard it ,
and just so you know i really appreciate the work you have done 
it looks quite clean and this is a very quality localisation that even multi million companies fail misrabely to do

**Comment by arkon** [comment]
> this is a very quality localisation that even multi million companies fail misrabely to do

Thanks to our volunteer translators. If you ever notice any issues with the localisation, feel free to contribute too: https://tachiyomi.org/help/contribution/#translation
