### ISSUE TITLE
[Bug] Trying to install the most recent dev update causes share dialog to pop up

### ISSUE THREAD

**Issue by kaosjr** [tachiyomiorg/tachiyomi#4523]
## Device information
* Tachiyomi version: r3095
* Android version: 11
* Device: Poco F2 Pro

## Steps to reproduce
1. Download the latest update from the notification
2. Click the install button on the notification, or anywhere else on the notification 

## Issue/Request
Instead of opening the package installer, the Share dialog opens with no option to select the package installer

## Other details
Video: https://photos.app.goo.gl/D3DgegHGF6jVPBhR6
The previous version I updated from (not sure which it was) worked normally, the device has not been updated since that update so my guess is it has to do with Tachiyomi

**Comment by arkon** [comment]
Couldn't reproduce from a Samsung device.

As a workaround, download it in your browser from https://github.com/tachiyomiorg/tachiyomi-preview/releases
