### ISSUE TITLE
[Bug] Tachiyomi crashed. Now shows Tachiyomi keeps stopping notification

### ISSUE THREAD

**Issue by chenxi896896** [tachiyomiorg/tachiyomi#4524]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Samsung Note 9

## Steps to reproduce
1. Search up Sakamoto Days on Mangadex extension.
2. Click on the manga.

### Expected behavior
I should be able to view the manga page.

### Actual behavior
App crashed. Couldn't open the app afterwards and there wasn't a process to force stop. I restarted my phone and I was able to use the app again. Now I keep getting the "Tachiyomi keeps stopping" notification. Tapping on "Close app" doesn't close the app and I am able to continue using the app with no problem. The notification randomly appears again some time later.

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6017169/tachiyomi_crash_logs.txt)
![Image_20210220224730](https://user-images.githubusercontent.com/79389876/108615081-59ae8980-73ce-11eb-90d3-0312f69818ad.jpg)

**Comment by arkon** [comment]
Looks like the kanade.eu certificate expired so it's failing to send the automatic crash logs. You could disable automatically sending crash logs for now until that's fixed.

I'll leave this issue open until @inorichi renews his certificate.

**Comment by inorichi** [comment]
This is fixed now. I keep forgetting to schedule a cron to automatically renew SSL certificates. I'll see if I can automate it so that it doesn't happen again.
