### ISSUE TITLE
[Bug] Chapter skipping

### ISSUE THREAD

**Issue by Bexa2** [tachiyomiorg/tachiyomi#4526]
In the manga "Ramia - Hero & Demon Lord Chronicles"
in mangadex, if you sort by chapter number ad start reading it'll skip from 1.5 to 1.6.1 to 1.7.1

I'm not sure if it's just bad numbering by the uploader or some strange cases that tachiyomi doesn't consider.

**Comment by Omar-AbdulAzeez** [comment]
There is a display option to choose chapter numbers where you sort the chapters... always make sure to check if chapters are numbered correctly before you fully commit to reading with chapter numbers...
The current problem is how tachiyomi is handling sorting... it seems that the current sorting algorithm isn't given a secondary field to sort equals just like how "ab" might come before "aa" if you only look at the first letter...
![Screenshot_20210222-080603_Tachiyomi](https://user-images.githubusercontent.com/49833164/108669067-f9f6d200-74e4-11eb-87a3-3f7e913e9e84.jpg)


In the current case it seems that the dates can be used to differentiate between the chapters or maybe even source titles but in the case of how the source is sorting this, it seems the source also has the same issue at chapter 2.1???
![20210222_081716](https://user-images.githubusercontent.com/49833164/108669981-bef59e00-74e6-11eb-9445-948f71db7961.jpg)

So now that we've figured the issue it technically is the site's fault for numbering the chapters incorrectly (or does the extension handle this????)
Anyways this could be seen as a joint mistake from the site, the extension, and the app but it mainly is the fault of which one numbered the chapters.  nonetheless, tachiyomi can account for this and fix it on it's end but that's only if the secondary sorting field isn't also equal...

**Comment by arkon** [comment]
Can't seem to find the same content on MangaDex anymore.
