### ISSUE TITLE
[Bug] update not working 

### ISSUE THREAD

**Issue by funsom123** [tachiyomiorg/tachiyomi#4529]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---

## Device information
* Tachiyomi version: 0.10.8
* Android version: 10
* Device: samsung galaxy a11

## Steps to reproduce
1. Getting the update notifacationu
2. Pressing update 

### Expected behavior
It updates to the next version 

### Actual behavior.
It gets stuck of the same percentace and doesnt move 

## Other details
It will stay this way untill i restart my phone and the notification wont go away 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by Seishirou101** [comment]
This is something that happens to some people for some reason, but you can always download the latest from the website which pulls from the same source as the app does. https://tachiyomi.org/download/
