### ISSUE TITLE
[Feature Request] Remove the rotation button

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi#4531]
![Screenshot_20210222-195755.jpg](https://user-images.githubusercontent.com/70870719/108763013-b46bf080-7548-11eb-9866-893338560c4d.jpg)

## Why/User Benefit/User Problem
The button is dumb, it takes up space and had literal no use, people can just rotate their device etc.
Space could be used for a better button. E.g. Webview, Reader mode, or even bookmark.

## What/Requirements
Just delete and replace it.

**Comment by arkon** [comment]
Nah dog.

**Comment by CrepeTF** [comment]
I'll make a PR just to remove it

**Comment by arkon** [comment]
Why would you even bother wasting your own time with that

**Comment by CrepeTF** [comment]
It's not about the button, it's about sending a message

**Comment by CrepeTF** [comment]
Actually it is about the button, it's useless
