### ISSUE TITLE
[Feature Request] <Color filter/overlay>

### ISSUE THREAD

**Issue by RunicAce** [tachiyomiorg/tachiyomi#4536]
## Why/User Benefit/User Problem
Looking at black and white all the time is rather tiring, being able to change the color every now and then would prevent dowsiness

## What/Requirements
When you click color filter button, you can choose a color from either a specific amount of colors, or from a color wheel, as well as transparency from completely opaque, to might not even have it enabled because it's completely transparent. 

If there are only a few colors to choose from, i recommend a minty green, as well as amber. Both colors are easy on the eyes.

**Comment by CrepeTF** [comment]
You mean this thing?

![Screenshot_20210223-204501.jpg](https://user-images.githubusercontent.com/70870719/108905887-2828fe80-7618-11eb-9271-6ea0f1f579c6.jpg)

![Screenshot_20210223-204451.jpg](https://user-images.githubusercontent.com/70870719/108905922-3119d000-7618-11eb-9160-97f07eb8056c.jpg)

**Comment by RunicAce** [comment]
Ah, seems it just doesn't exist in stable yet
