### ISSUE TITLE
[Bug] Chapter takes minutes to load

### ISSUE THREAD

**Issue by jc65536** [tachiyomiorg/tachiyomi#4537]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: 10
* Device: Nokia 6.2

## Steps to reproduce
1. Open a chapter (Mangadex chapters have this issue; not sure for other sources)

### Expected behavior
The chapter should load promptly.

### Actual behavior
The loading circle will spin all the way but get stuck at the very end. The images will load only after several minutes. The chapter loads instantly in WebView or through Firefox, however.
![](https://i.imgur.com/03MuRQS.png)

## Other details
I've encountered similar behavior in a react app I was building, where JSON data would take over 2 minutes to load. I thought it very strange until I stumbled across [this issue in another project](https://github.com/expo/expo/issues/2756). Apparently, IPv6 DNS records were the culprit for them. I don't know if it's the same issue here, but the behavior is similar.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by DieSmilePN** [comment]
I noticed that too. Only MangaDex have that problem. I sometimes migrate to other extensions. I assume it got has to do with server, slow net, mbps drop or full chapter cache. When that happen I just go to setting > Advanced > clear chapter cache, you'll notice the chapter cache always at 104 MB it's always takes time to load a pages when it is in that rate when you're net are slow, just clear it and you're good to go. You can enable data saver on MangaDex setting it will lower the resolution each pages its unnoticeable change.

**Comment by arkon** [comment]
If this is MangaDex-specific, it's very likely something to do with the networking aspect for MD@Home. You could try asking in their Discord server to see if anyone else is encountering similar issues.

**Comment by arkon** [comment]
Closing since I don't think we can do much about it.
