### ISSUE TITLE
[Feature Request] Option to show number of pages in a series instead of chapters on the library page badge

### ISSUE THREAD

**Issue by HugoFernandes2343** [tachiyomiorg/tachiyomi#4538]
## Why/User Benefit/User Problem
Many series have a large ammount of small chapters and many other series have a small amount of large chapters, this can lead to think that a series is a lot larger or smaller than another for example, if there are 2 series fully downloaded, and one has 100 chapters with 20 pages each give or take, and the other has 70 chapters but with roughly 40 pages each, this makes the second series seem smaller than the first one in the library tab while in fact it is longer. It is mostly a QoL funcionality adition and i believe a simple one to implement.

## What/Requirements
Currently in the library tab you can chose to display the number of downloaded/unread chapters badge this feature would only add another option in the library display tab that lets the badge be changed to "Total pages" or "total pages downloaded". 

![image](https://user-images.githubusercontent.com/56555196/109013802-74714e80-76ab-11eb-9a8c-5f55246b39f3.png)

The calculation of the number of pages shoudnt be too intensive on the devices to be implemented and just offers a small QoL change to the app.

**Comment by arkon** [comment]
This would rely on contents being downloaded already, so it isn't really feasible.
