### ISSUE TITLE
[Bug] Installed extensions are lost when the app exits completely

### ISSUE THREAD

**Issue by Orienser** [tachiyomiorg/tachiyomi#4539]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: Android 10
* Device: vivo iQOO

## Steps to reproduce
1. Install any extension(s).
2. Exit app completely. (Kill from the recent apps screen)
3. Start Tachiyomi again, the list of installed extensions is empty. But the extension app still can be found in android’s built-in app manager.

### Expected behavior
After the application is completely exited, the installed extensions should be found in the extension list.

### Actual behavior
After the application is completely exited, the installed extension list is empty.

## Other details
If not exit the application completely (for example, just press the back button to return to the home page), I can still find the installed extension after I re-enter the application.

Below is a video of the steps to reproduce:

https://user-images.githubusercontent.com/13484542/109018372-06507a00-76f3-11eb-80ea-9fef24d9b827.mp4

**Comment by arkon** [comment]
I appreciate the effort in creating the video.

Unfortunately, this seems like there's something with Vivo's software preventing the app from querying for existing apps properly. We're only using standard Android APIs, so you can try seeing if Vivo has an additional "security" or "privacy" settings that may be interfering with it.

**Comment by Orienser** [comment]
> try seeing if Vivo has an additional "security" or "privacy" settings that may be interfering with it.

Thanks for the reminder, Vivo does have a permission called “Read installed apps info”, which must be granted to the application to find the installed extension.

Here are the steps:
1. System Settings
2. Applications and Permissions
3. Permission management
4. Permission Tab
5. Read installed apps info
6. Find Tachiyomi
7. Make sure "Security level" is Low
