### ISSUE TITLE
I want it for iPhone and Android app keeps on crashing while refreshing

### ISSUE THREAD

**Issue by JedidiahJohnNagarajan** [tachiyomiorg/tachiyomi#4542]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

Can you make it available for iPhone somehow.... And the app crashes more often I don't know what to do in android
---

## Why/User Benefit/User Problem
(explain why this feature should be added)

## What/Requirements
(explain how this feature would behave)

**Comment by scb261** [comment]
iPhone - no, because it would require full rewrite
crash - you need to open bug issue (as you tried in #4541), read template and fill it in
