### ISSUE TITLE
[Feature Request] Setting for navigation button to go directly to latest

### ISSUE THREAD

**Issue by MirandaLe** [tachiyomiorg/tachiyomi#4543]
## Why/User Benefit/User Problem
I only use 1 extension, so it would be convenient if I can set one of the navigation buttons to go directly to an extension's Latest page. 

## What/Requirements
Have an optional setting to set Browse/Updates to go directly to a specific source's Latest page, or have an extra, optional navigation button.

**Comment by arkon** [comment]
For the sake of keeping the codebase less complicated than it already is, I'll have to reject this.
