### ISSUE TITLE
[Feature Request] <App Reset with Backup Features>

### ISSUE THREAD

**Issue by KenDxD** [tachiyomiorg/tachiyomi#4545]
## Why/User Benefit/User Problem
It can fix many bugs if the app going to update

## What/Requirements
Resetting the app with backup features that clear all history and the app back to the default values

**Comment by scb261** [comment]
Just make backup in app settings and clear app data in phone settings

**Comment by curche** [comment]
Steps to follow:
1. backup option (allows to store all info about manga in library)
2. then you can reset the app from phone settings like how scb261 said above. resetting the app puts all settings to default values.
3. restore the backup created in step 1

you can also enable automatic backup creation from settings, if it helps.

note that backups don't contain information about app settings just manga in library (which is an open issue #1857)

issue can be closed.

**Comment by KenDxD** [comment]
But its easier for non techies user, but also I appreciate the comments. Its the same way that I use 😁.
