### ISSUE TITLE
[Bug] <Scrolling bar bug>

### ISSUE THREAD

**Issue by MAT-OUT** [tachiyomiorg/tachiyomi#4547]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: whyred

## Steps to reproduce
1. First step:open fixed bottom bar
2. Second step:scroll to the bottom

### Expected behavior
We can see:The scroll bar layout should be restricted by the bottom bar

### Actual behavior
No, even the scroll bar is missing.

## Other details
none

**Comment by arkon** [comment]
Sorry, I'm not sure I understand.

**Comment by scb261** [comment]
I think they mean that scroll bar goes behind bottom nav bar when `Hide bottom bar on scroll` is disabled

**Comment by arkon** [comment]
Won't be fixed, it's a side effect of how the stuff is laid out.
