### ISSUE TITLE
[Feature Request] <Custom Titles Order>

### ISSUE THREAD

**Issue by lolomimi21** [tachiyomiorg/tachiyomi#4548]
## Why/User Benefit/User Problem

The app's library allows us to organize the titles alphabetically and in order of publication. It would be great if it also allows us to change the order of the titles according to our preference. This can be used (for example) to create reading orders with Marvel and DC comics

## What/Requirements

To change the order of the titles, what could be done is: Hold down the title of the library that we want to change places and move it with the finger to the place where we want to put it, or on the title that we want to replace

Srry if my English it's a little bad!

**Comment by iinxl** [comment]
Try

**Comment by arkon** [comment]
This has been rejected in the past. However, [some forks](https://tachiyomi.org/forks/) such as J2K and SY offer custom drag and drop sorting in the library.
