### ISSUE TITLE
[Bug] Searching for chapter updates is really slow

### ISSUE THREAD

**Issue by eeneg** [tachiyomiorg/tachiyomi#4549]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Samsung A50

Im sorry if this is a duplicate issue or if this is a device issue instead of an issue within the app but searching for chapter updates is considerably slower than the previous versions.

Main Extentions:
Mangakakalot (& others)
Madara (Multiple Sources)
MangaDex
Manga plus by shueisha

**Comment by scb261** [comment]
> **Disclaimer**
Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

**Comment by eeneg** [comment]
> > **Disclaimer**
> > Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

Thank you for the response. Im not talking about the content updates. Im talking about the update tab where the app goes over each manga saved in the library and checks for new chapters.

**Comment by CarlosEsco** [comment]
Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: **slow**, down, missing chapters, or has subpar image quality.

You need to figure out which is the source that is causing the issue specifically to you, and either migrate from it or verify its not broken/down

**Comment by eeneg** [comment]
Thanks for the response. Is this process slow because of the content providers? 

And yep I know that **Tachiyomi is not hosting any content** haha. The **slow** thing that im mentioning is this. Sometimes its stuck on a single manga for a few mins. but ive checked using **web view** and the site works. If this truly is because of the content providers then..

![155307785_184124853510414_4356035533298550726_n](https://user-images.githubusercontent.com/51152900/109387510-ce3c7780-793c-11eb-9a47-ce4aad4d41b0.jpg)

**Comment by CarlosEsco** [comment]
@eeneg if its you narrowed it down, check the source for the manga verify it's not broken or has issues in the extensions repository. If there is no issue then open one there

**Comment by eeneg** [comment]
Unfortunately the stuck manga is random, and ive already checked the the sources of those I caught. Also tried changing some battery settings and tried a much stronger wifi connection to no avail.

It gets worse when I lock my phone. I try to refresh the update tab then I lock my phone, only to come back around an hour or so and its still not finished.

Il just try to reinstall the app and see if the problems persists. I dont want to do it since some errors pop-up during back-up restore and ill have to search those manga one by one

**Comment by arkon** [comment]
https://dontkillmyapp.com/samsung
