### ISSUE TITLE
[Feature Request] Mangadex and Mangaupdates trackers

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#4550]
## Why/User Benefit/User Problem
Databases not always list *all* the entries found online, sometimes less known works or oneshots don't exist, so you can't save it as read anywhere.
While these 2 new trackers could miss things too, they are for sure a way better library.

## What/Requirements
They would just work like the tracker for MAL, AniList and the other websites, linking your account and tracking chapter per chapter what you read/set completed etc.

**Comment by CarlosEsco** [comment]
#624 

As for MDList  i wouldn't add them as a tracker until v5 of their api comes out.  MDList api is half baked at this time
