### ISSUE TITLE
[Feature Request] A way to retry failed updates without retrying successful ones.

### ISSUE THREAD

**Issue by connect192168** [tachiyomiorg/tachiyomi#4558]
## Why/User Benefit/User Problem
It would save users time and device resources to be able to retry the last set of failed updates at their convenience.

When users have failed updates they can currently either:
A) retry all updates (which would re-trigger a ratelimit if that's what stopped them the first time) 
or
B) manually update each failed title separately (which is time consuming if there are a lot of failed updates).

This feature would mean that the user could retry any failed updates.

Personally, it would significantly reduce the work I'd need to put in when a dozen of my titles get error 502d because of ratelimiting (I have a lot of titles in my library).

#### For the interface, there's 2 parts:

1. A button on the updates section of the app to retry failed updates.

>  This would probably be next to the existing update all button.     

2. An option on the errors notification to retry failed updates.    

>  This would be next to the "open log" option on the updates failed notification.

#### As for how the code would work:
Note: for this bit, I'll be using tachiyomi_failed_updates.txt as an example file.

Where (in the code) the app writes the failed updates to tachiyomi_update_errors.txt:
- namely  (if I understand the code correctly)  
https://github.com/tachiyomiorg/tachiyomi/blob/7a373fb43a2d3f736c032d88b31a4a3bffd8dc5b/app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt#L417 
1.If tachiyomi_failed_updates.txt doesn't exist, make it.
2.Erase the contents of the file
This is so that the new set of failed updates isn't polluted by any old failed updates that may have been ignored or successfully updated.   
3.For each failed update: 
Write the data needed to identify the title that failed to update to the file.(afaik: a manga url and sourceId)

When the new "retry failed updates" button (in the updates section of the app or the update error notification option) is pressed:
1. Read each line from tachiyomi_failed_updates.txt
2. Generate a new mangaList from the data stored in tachiyomi_failed_updates.txt
3. Update the manga titles in the generated list 
I don't know enough about how the updater works to speculate on the best way to go about this part tbh.
I'll let someone better versed in the workings of this project figure it out.

**Comment by arkon** [comment]
A single retry for everything is almost never a good idea since most things fail for actually valid reasons.

If we implement a list/section in Updates (i.e. #4616), users should be able to open individual items to retry if they so desire.
