### ISSUE TITLE
[Bug] Cannot delete downloaded chapters if they are bookmarked.

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi#4559]
---

## Device information
* Tachiyomi version: 0.10.9 (standard, f590378, 56)
*Android version: 11 (SDK 30)
* Device: Samsung tab s7

## Steps to reproduce
1. Open any manga title select 3 or more chapters to download
2. Bookmark some downloaded chapters
3. Now select all downloaded chapters (plus the downloaded bookmarked ones) and delete them

### Expected behavior
All chapters that were selected should be deleted.

### Actual behavior
Chapters that are bookmarked are not deleted rest of the chapters are deleted

## Other details
Need to unbookmark and then manual delete chapter and after deleting mark again as bookmark. Added screenshots for reference.

Downloaded chapters
![Screenshot_20210228-182822_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/109419378-2766e280-79f3-11eb-9931-bd919b2c739f.jpg)

Selected and pressed delete
![Screenshot_20210228-182920_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/109419383-3057b400-79f3-11eb-9345-c93375ae8d3a.jpg)

Only non bookmarked chapter's deleted
![Screenshot_20210228-182946_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/109419390-351c6800-79f3-11eb-969e-827ce604c75b.jpg)

**Comment by scb261** [comment]
`More > Settings > Downloads > Delete bookmarked chapters` enable this

**Comment by Samk19** [comment]
Oh thanks
