### ISSUE TITLE
[Feature Request] Sort titles by sources

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi#4560]
## Why/User Benefit/User Problem
Helps to see if a title chapters is updated on a particular source and if not we can migrate.
Also help to see title what sources are used most (number of titles from a particular source).

This can be viewed right from manga library 

## What/Requirements

Open library
Now click filter button
Then select sort category 
Select 'By Source' (*added option)
Now all mangas are grouped by sources 

Added rough diagram below 
![Screenshot_20210228-185057_Samsung Notes.jpg](https://user-images.githubusercontent.com/36104528/109419950-fd62ef80-79f5-11eb-95df-cc2ac9688623.jpg)

**Comment by scb261** [comment]
Sorting by source was removed in favor of searching by source name

**Comment by Samk19** [comment]
Can it be enabled again as an optional feature for those who want it

Searching by name it more tiring as you have to type the source you are looking for everytime

Rather than selecting an option that categories all titles into their sources

**Comment by arkon** [comment]
The headings never existed, so the sort was a bit useless. You can just tap the source name when in a manga to search it in your library.

**Comment by Unimatrix007** [comment]
I want this feature to come back becouse i want to know how much of my manga belong to which source. Searching it manualy by hand is useles if in my library of 150 items, 117 are used by mangadex [i had to bloody count it miself coz the library count doesnt change when searching by sourve] how the hell am i gonna know to which source the rest belong unless i go manualy into each bloddy manga and check the info there.
This feature is useful even if its clunky. 
To get it back you dont have to change much just add it as an toogleable option in sort menu.

**Comment by joseph619** [comment]
> I want this feature to come back becouse i want to know how much of my manga belong to which source. Searching it manualy by hand is useles if in my library of 150 items, 117 are used by mangadex [i had to bloody count it miself coz the library count doesnt change when searching by sourve] how the hell am i gonna know to which source the rest belong unless i go manualy into each bloddy manga and check the info there.
> This feature is useful even if its clunky.
> To get it back you dont have to change much just add it as an toogleable option in sort menu.

Read above why it was completely useless and thus removed, it didn't work the way you think it worked. There was no indication where one source started and one source ended, nor it showed how many manga from each source were present in the library.
