### ISSUE TITLE
[Feature Request] <Request For New Category Option>

### ISSUE THREAD

**Issue by Wizling** [tachiyomiorg/tachiyomi#4562]
---

## Why/User Benefit/User Problem
This would help the readers/users of tachiyomi that has several books in their library to avoid double books in their library and also easier way for them to remove and organize books.

Problem:
Once a user has over 500+ in their library it tends to be hard to keep track if you had selected an already marked book for your library thus creating double title books that takes up your library space and also takes up more time for you to reupdate the books and it also kinda waste data for those who uses data and not wifi.

## What/Requirements
This should be an addition for the category tab that has the function to scan the library of the user for double titled books (from all extensions). This then shall help the user to see the double titled books from the library to help with organizing and removing the additional titles.

only issue that might be hard to make this come true is the fact that some titles in other sources have different titles from others.

**Comment by Bexa2** [comment]
How would this be different from sorting your gallery alphabetically and checking for duplicates?

It would be one thing if tachiyomi checked the title when adding to the library and warned you if there's already a similar title.

**Comment by Wizling** [comment]
> How would this be different from sorting your gallery alphabetically and checking for duplicates?
> 
> It would be one thing if tachiyomi checked the title when adding to the library and warned you if there's already a similar title.

Hmm i suppose it is better if there a warning and is much simpler. What i was just suggesting was the lil fact that when u reach over 500+ in your library or so it gets hard to navigate through it all to check if you have duplicate titles. I mean it is possible to do it your way manually that is but for those who has a lot more titles in their library that would take a considerable amount of time. (i have 700+ and its already getting hard to navigate duplicates)

well im just suggesting anyway it doesnt meed to be implemented at all im already happy for what i have

**Comment by arkon** [comment]
#5591 is probably a better solution.
