### ISSUE TITLE
[Bug] Kiryuu extension Chapter number error

### ISSUE THREAD

**Issue by Hannaichi** [tachiyomiorg/tachiyomi#4568]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 8
* Device: MI 6

## Steps to reproduce
1. Open Kiryuu Sources
2. Choose any title

### Expected behavior
Displays the latest chapter at the top

### Actual behavior
there is an additional Chapter{{number}} with no pages found when clicked.

## Other details
![eu kanade tachiyomi](https://user-images.githubusercontent.com/79848320/109499718-da087500-7ac7-11eb-928f-0004749f139d.png)

**Comment by scb261** [comment]
Wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions/issues
