### ISSUE TITLE
[Bug] Unable to Install App on Device

### ISSUE THREAD

**Issue by easybreezyb** [tachiyomiorg/tachiyomi#4572]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: Samsung Galaxy S20FE

## Steps to reproduce
1. Download Tachiyomi apk from Tachiyomi website.
2. Attempt to install.

### Expected behavior
Tachiyomi should be installed on the device.

### Actual behavior
Without SAI: There was a problem parsing the package.
With SAI: DISPLAY_NAME column is null.

## Other details
I'm trying to install the app itself, not even the extensions yet. I tried SAI on the advice of support from the Tachiyomi Discord, but it still didn't work.

I have not previously installed any version of Tachiyomi on the device.

I have taken the following measures to try to install the APK:
1. installation from unknown sources enabled app-specific for Chrome (used to download the apk from the site), My Files, and SAI;
2. updated my Android OS to the latest version; and
3. enabled USB debugging on the device.

**Comment by Seishirou101** [comment]
I don't know if this would help you, but I actually got the error when updating compared to just installing... It only fixed itself after redownloading the apk, a *3rd* time.

**Comment by easybreezyb** [comment]
> I don't know if this would help you, but I actually got the error when updating compared to just installing... It only fixed itself after redownloading the apk, a _3rd_ time.

Thank you! I'm on my 11th download of the apk so far... but I'll keep trying, no loss even if it doesn't work.

**Comment by easybreezyb** [comment]
Found a workaround! I downloaded the apk file on my computer and used a cable to add it to my device instead of downloading it directly. Managed to install it on the device with SAI this way.

If you read this message, thank you Seishirou101 for being really nice and all your efforts to help. :)
