### ISSUE TITLE
[Feature Request] Retain Search Results in Library Even if App is in Background.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi#4574]
## The Issue
Let's say you have a bunch of manga in your library by the author John Smith. You type "smith" in your library and it automatically sorts all the manga by that author (or anything else with "smith" in its name). However, if you close the app (still in background) for whatever reason, and then come back, this sorting is reset, but the search bar still has "smith" written on it. Could you make it so that the search results are not reset, even if the app had been temporarily closed?

**Comment by arkon** [comment]
This is fixed in preview.
