### ISSUE TITLE
[Feature Request] █▓░ When there're new chapters, download next unread chapters

### ISSUE THREAD

**Issue by khonkhortisan** [tachiyomiorg/tachiyomi#4575]
## Why/User Benefit/User Problem
For a given title, the list of chapters can have chapter statuses in these orders:
░░░░░░ unread __________________ (not started, no new chapter OR new chapter, download is in queue)
░░░░▓▓ unread-downloaded ____ (not started, new chapter, downloaded new chapter) ❌ undesired state
▓▓░░░░ downloaded-unread ____ (not started, new chapter, downloaded in reading order) ✔️ desired state
▓▓▓▓▓▓ downloaded ____________ (not started, manually downloaded)
██████ read ____________________ (caught up, no new chapter)
███░░░ read-unread ____________ (not caught up, no new chapter OR new chapter, download is in queue)
███▓▓▓ read-downloaded _______ (caught up, new chapter, downloaded new chapter)
██░░▓▓ read-unread-downloaded (not caught up, new chapter, downloaded new chapter) ❌ undesired state
██▓▓░░ read-downloaded-unread (not caught up, new chapter, downloaded in reading order) ✔️ desired state

If I have Download new chapters on, and go somewhere without internet access:
* without this feature: Only if I was caught up before it downloaded the updated chapter can I start reading a title, because otherwise there will be a gap of read-unread-downloaded.
    When I've read 10 of 100 chapters and I have download new chapters on, it downloads chapter 101 instead of chapter 11. This isn't useful until I've read chapters 11-100, and I can run out of space when it does this for multiple titles/updates.
    If there were two chapters updated, it downloads 101+102 instead of 11+12.
* with this feature: **I can immediately start reading** any title that has a downloaded chapter, because it downloads the next unread chapter.
    If it downloads chapter 11, then I get the space back after reading 1 chapter, and I don't have to wait for that chapter to load.
    If there were two chapters updated, it downloads 11+12 instead of 101+102.

## What/Requirements
*If the old behavior should still exist*, add a new setting, called (name pending) `Download in reading order` or `Download next unread` (whatever's clearest to understand)
```
  Download new chapters
  Download new chapters [off/on]
  Download in reading order [off/on]
  Categories to include in download [All/Default/…]
```
☐ With the setting unset in its default position, act as normal: download exactly those chapters that have updated.
  If I've read 10/100 chapters, and there are 10 new chapters, download chapters 101-110 (1-10 read, 11-100 unread undownloaded, 101-110 downloaded). Ditto for the next 10 new chapters.
█░░░░░░░░░
█░░░░░░░░░▓
█░░░░░░░░░▓▓
☑ With the setting set, count how many chapters updated, then out of the list of chapters that are unread and undownloaded, download that count out of that list.
  If I've read 10/100 chapters, and there are 10 new chapters, download chapters 11-20 (1-10 read, 11-20 downloaded, 21-120 unread undownloaded). Ditto for the next 10 new chapters.
█░░░░░░░░░
█▓░░░░░░░░░
█▓▓░░░░░░░░░

**Comment by scb261** [comment]
I think #3295 is better for this, because downloading old chapter only when new one available sounds weird

**Comment by Omar-AbdulAzeez** [comment]
As scb261 said... downloading chapter 11 when chapter 101 comes out is just weird
You can just make a different category for the manga you're not caught up with and turn downloading off for that category

**Comment by arkon** [comment]
Closing in favour of #3295
