### ISSUE TITLE
[Feature Request] <add hidden and locked category>

### ISSUE THREAD

**Issue by MohamedNafea180** [tachiyomiorg/tachiyomi#4582]
add a hidden and a locked categories
. when the user touch the locked category , it requires 
a passcode
.when the user want to access to the hidden one he should turn on the incognito mode and insert the passcode
features:
locked category (passcode)
hidden category(incognito mode)
hidden locked category(incognito mode then pass code)

**Comment by CarlosEsco** [comment]
#4297
