### ISSUE TITLE
[Bug] A local .cbr comic not loading correctly

### ISSUE THREAD

**Issue by CaptainHalflife** [tachiyomiorg/tachiyomi#4584]
## Device information
* Tachiyomi version: r3130
* Android version: 8.1.0
* Device: Samsung J7 Prime

## Steps to reproduce
1. Place the comic in local folder (I only encounter this with 1 comic, download it [Here](https://drive.google.com/file/d/1mXwl6vHg3_jRGRaLfx5Z0RRUYKmNaksf/view?usp=drivesdk) 
2. Open the comic

### Expected behavior
The comic load properly.

### Actual behavior
The comic don't load correctly (some pages load, other with the wrong color or get a grey page instead.)
![Screenshot_20210303-173334_TachiyomiSY](https://user-images.githubusercontent.com/65003109/109814419-eadff480-7c47-11eb-9ab5-0835d0bf7dc2.jpg)
![Screenshot_20210303-173145_TachiyomiSY](https://user-images.githubusercontent.com/65003109/109813627-0c8cac00-7c47-11eb-8f93-23ee0207f9cf.jpg)

## Other details
I tested with a different .cbr and a .cbz and it work, so I thought that the comic was corrupted but that is not the case, it work on J2K but same problem on SY.

While looking at the comic tachiyomi crashed (it was on the SY fork hope its still useful)
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6076325/tachiyomi_crash_logs.txt) 
After the crash more page loaded compare to before but still with the wrong color

**Comment by inorichi** [comment]
There seems to be some issue with how the image is read on .rar files. I'd suggest you to use .zip in the meantime, as it should be bug-free (or so I think).

**Comment by inorichi** [comment]
I've found the issue and fixed it. Thank you for your time getting the logs.
