### ISSUE TITLE
[Bug] new chapters not detected by tachiyomi. Visible in web view 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#4585]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 7
* Device: huawei mediapad m3

## Steps to reproduce
1. Refresh category or refresh a manga

### Expected behavior
New chapters are found 

### Actual behavior
Some manga didn't detect new chapters 

## Other details
All manga that have issues are from mangadex. But 90% of my manga are from mangadex so I'm not sure if it's due to mangadex. Or simply because most of my Manga are from mangadex thus it have more chance for the bug to occur. 

But this has never happen on older tachiyomi (before the UX redesign with more iconography replacing texts) 

Hunting down some Manga, I found a manga with high frequency updates (every few days), that's "lonely attach in different world", and the last one detected by tachiyomi is from 18 days ago (ch67) but in web view latest is 3 days ago(ch70) 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by orangpelupa** [comment]
Just checked again, and yep, most manga from manga dex updates just fine. 

For the example 

Koushaku Reijou no Tashinami
Manga also from mangadex and it detects new chapter just fine. latest chapter is 3 days ago in tachiyomi and in web view.

**Comment by curche** [comment]
mangadex was subject to a ddos attack for past few days
there has been development ongoing on mitigating it

this would have affected the MD API, that tachi uses to fetch updates
expect minor disturbances
once the mitigation is complete, everything should work same as before

you can keep a close eye at https://twitter.com/MangaDex/status/1366416937190834178 
and MD or Tachiyomi discord server

**Comment by Seishirou101** [comment]
you're in the wrong repo, but its because of the api. you can see more info about it in tachiyomiorg/tachiyomi-extensions#5780. It is currently closed because there was a small bit where it was fixed without md doing anything but is acting up again after being ddos'd

**Comment by orangpelupa** [comment]
Thank you! I'll close this
