### ISSUE TITLE
[Bug] A navigation layout is missing in the main settings menu 

### ISSUE THREAD

**Issue by Eragonnogare** [tachiyomiorg/tachiyomi#4586]
## Device information
* Tachiyomi version: stable 0.10.9
* Android version: 
* Device: Galaxy s10

## Steps to reproduce
1. Open settings
2. Open reader options
3. Open navigation layout dropdown

### Expected behavior
All navigation layouts are there

### Actual behavior
Only 4 of the navigation layouts are there (right and left is missing) 

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by scb261** [comment]
Duplicate of #4487 (it's fixed for the next release)

**Comment by Eragonnogare** [comment]
Ah, good to hear
