### ISSUE TITLE
[Bug?]Manga with 999+ chapter not show correctly

### ISSUE THREAD

**Issue by moonphilia** [tachiyomiorg/tachiyomi#4588]
## Device information
* Tachiyomi version: stable 0.10.9
* Android version: 10
* Device:  xiaomi redmi 8

## Steps to reproduce
1. Open manga with 999+ chapter( in this case i opening manga with name "Martial Peak" from mangahere

## Issue/Request
? The issue is, chapter 1000 and the rest will not appear on chapter list

## Other details
Additional details and attachments.
![IMG_20210304_123320](https://user-images.githubusercontent.com/79213283/109916263-df430b00-7ce5-11eb-9239-954957585918.jpg)
![IMG_20210304_123302](https://user-images.githubusercontent.com/79213283/109916277-e538ec00-7ce5-11eb-9f95-e6188f7a798b.jpg)

**Comment by Seishirou101** [comment]
it's showing exactly what it is suppose to. https://www.mangahere.cc/manga/martial_peak/ has 999 as the latest. That's either from a different source, or mangahere uploaded it by mistake and you just happened to catch it when it was updating.

**Comment by moonphilia** [comment]
I dont think it from different souce.
And i can read it just fine.
And at the end of chapter it will jump to... see Attachment
![Screenshot_2021-03-04-12-47-17-734_eu kanade tachiyomi](https://user-images.githubusercontent.com/79213283/109917361-c5a2c300-7ce7-11eb-8d65-3143f0e9fc5e.jpg)

**Comment by Seishirou101** [comment]
Oh, I see. its how mangahere organizes their chapter, you can see here that its after 100 on their website too 
![1252-1230-max](https://user-images.githubusercontent.com/57241064/109917789-ccacdf80-7cad-11eb-921e-83a9db1a420e.png)

you can sort the manga by chapter order and it should fix it.

**Comment by moonphilia** [comment]
Its not from mine. ._.
Weird indeed
![Screenshot_2021-03-04-12-53-05-854_com android chrome](https://user-images.githubusercontent.com/79213283/109917961-cbe56f00-7ce8-11eb-8991-3942c2a3e37f.jpg)

**Comment by Seishirou101** [comment]
is this webview? what is the exact address you have in your bar?

**Comment by moonphilia** [comment]
It show just fine if i scrolldown to chapter 101.
Thank you for help.
![Screenshot_2021-03-04-12-56-00-915_eu kanade tachiyomi](https://user-images.githubusercontent.com/79213283/109918643-e835db80-7ce9-11eb-8476-b7b88751fb48.jpg)
