### ISSUE TITLE
[Feature Request] Make It Optional To Have Download Icons Beside Chapters.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi#4590]
## Why/User Benefit/User Problem
We can already access the download option at the **top-right**. Pressing-and-holding chapters also brings up download option at the **bottom**. Why include a third avenue for download **beside** the chapters as well? Especially one which is prone to accidental touches during one-handed usage?

## What/Requirements
I think a simple option to turn this off would be great. Both proponents and opponents of the feature will be happy. No harm done.

**Comment by CarlosEsco** [comment]
the main purpose of this is to allow you to see download status of a chapter clearly, as well as a quick download for single chapters.  An option to remove is not going to be added

**Comment by MercerBoi** [comment]
Amazing.
