### ISSUE TITLE
[Feature Request] Provide option to use update scan date if not supplied by source for new chapters

### ISSUE THREAD

**Issue by RickSaysMeh** [tachiyomiorg/tachiyomi#4594]
## Why/User Benefit/User Problem
Currently, if a source does not provide the date (or sets it to '0') of new chapters, Tachiyomi simply leaves it blank. This causes the title to remain in its current position in the library if sorting by Latest Chapter and keeps the title from appearing in the Updates screen.

## What/Requirements
Provide a an option to use the update scan date for new chapters (all or just those without dates). With this enabled, Tachiyomi could use the current date at the time of the update scan for either all new chapters or just those that do not provide valid dates.

**Comment by FourTOne5** [comment]
Closed in #6358
