### ISSUE TITLE
[Feature Request] Put chapter list dropdown in reading mode

### ISSUE THREAD

**Issue by RocGoddess** [tachiyomiorg/tachiyomi#4596]
## Why/User Benefit/User Problem
This would make it easier for the user to jump to any chapter they want. Instead of going back to the main page and then selecting a chapter, they can conveniently do it while reading.

## What/Requirements
The number that indicates the current chapter at the top of the page will have a dropdown arrow next to it that when clicked/tapped shows all the chapters of the work being read.
![20210305_061103](https://user-images.githubusercontent.com/80088483/110075668-10b9e600-7d7b-11eb-9b8d-2dcec7b80085.jpg)

**Comment by arkon** [comment]
The toolbar title/subtitle just takes you back to the full chapters list (in the preview/next stable version), which serves that purpose.
