### ISSUE TITLE
[Feature Request] Extension/source sorting/badge in library

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4597]
## Why/User Benefit/User Problem
As someone who tries to keep a duplicate of every manga in their library, it can be an issue to distinguish/organize the library with the dupes as they can be indistinguishable.

## What/Requirements
The suggestion is to either add the option to sort the library by extension/source or add an option to show a badge in the manga cover with the extension's icon so it's easily identifiable.

**Comment by CarlosEsco** [comment]
#4560
