### ISSUE TITLE
[Feature Request] Automatically Set Manga as Completed

### ISSUE THREAD

**Issue by george-emerald** [tachiyomiorg/tachiyomi#4598]
When you finish reading the manga, the tracker updates the chapter count, yet it doesn't set the title as completed. You've implemented dates (i.e. when you read the first chapter, the start date is set; when you set it as completed, the finished date is set), yet the tracker doesn't change the status. This issue is also present if you read the first chapter of a manga on your planning list. It updates the chapter count but doesn't mark it as reading.

**Comment by arkon** [comment]
Closing in favour of #5779
