### ISSUE TITLE
[Feature Request] Possibility to navigate through your mangas by swiping them

### ISSUE THREAD

**Issue by o01210o** [tachiyomiorg/tachiyomi#4602]
## Why/User Benefit/User Problem
When you finished reading _manga1_ and want to read _manga2_, you have to quit the page of _manga1_, go back to your library and select _manga2_.
The idea is to switch from _manga1_ to _manga2_ just by swiping your screen.

It may be very useful when you read weekly manga and want to read them in a row when they're released.

![image](https://user-images.githubusercontent.com/45663409/110208718-d58ce500-7e56-11eb-8c1f-c1c647ca7c65.png)

## What/Requirements
![image](https://user-images.githubusercontent.com/45663409/110208761-09680a80-7e57-11eb-9e81-0c5d32dd71af.png)

**Comment by arkon** [comment]
This greatly overcomplicates things, so I'm going to have to reject this.
