### ISSUE TITLE
[BUG] HTTP 502 Error on Mangadex 1.2.104

### ISSUE THREAD

**Issue by keiichiiownsu12** [tachiyomiorg/tachiyomi#4603]
## Device information
* Tachiyomi version: 0.10.9 (stable)
* Android version: 10
* Device: Note 9

## Steps to reproduce
1. Browse MangaDex listings in app
2. Select Manga

## Issue/Request
On current version of MangaDex extension, 1.2.104, manga pages return 502 errors when either 1) loading manga info or 2) loading a chapter (i.e. for manga bookmarked in library).

## Other details
I am logged in on MangaDex in the web portal. In the web portal, manga pages and chapters load without issue.

**Comment by scb261** [comment]
Wrong repository and it's mangadex api server issue, not tachiyomi issue tachiyomiorg/tachiyomi-extensions#5780

**Comment by keiichiiownsu12** [comment]
Thank you for the clarification!
