### ISSUE TITLE
[Bug] The app animations aren't processing properly but instead all the pages related to the section is being displayed simultaneously then faded to the correct page when switching tabs. Most likely the transition animation is the issue.

### ISSUE THREAD

**Issue by abelqwerty** [tachiyomiorg/tachiyomi#4605]
---

## Device information
* Tachiyomi version: Just installed latest beta
* Android version: lineage os 17.1 (android 10)
* Device: Samsung galaxy S8

## Steps to reproduce
1. Open the app
2. Switch between tabs

### Expected behavior
Tab view should display regularly.

### Actual behavior
Tab animations crossfade into each other showing all fragments briefly.

## Other details
I'm using a custom firmware so not sure if it's specific to me but it was working fine right before I updated.

**Comment by arkon** [comment]
c68e7c8da78309a0b091c11379a8da5c6222572d
