### ISSUE TITLE
[Bug] Unable to delete chapters

### ISSUE THREAD

**Issue by AstralSpace** [tachiyomiorg/tachiyomi#4606]
## Device information
* Tachiyomi version: Stable 0.10.9 (latest)
* Android version: ColorOS Version V11, Android Version 11
* Device: Oppo Reno3 Pro

## Steps to reproduce
1. Have chapters downloaded
2. Delete multiple chapters

### Expected behavior
Chapters display as deleted and corresponding files deleted from storage.

### Actual behavior
Display did not show chapter deleted, files are also not deleted from storage.

## Other details
Deleting chapters 1 by 1 works, but it has a lag period, it takes about 20 seconds up to 1-2 minutes to show and actually delete a chapter, highlighting and deleting multiple won't work altogether, even if just 2-3 highlighted.

**Comment by scb261** [comment]
Probably better keep all Android 11 storage issues in one place https://github.com/tachiyomiorg/tachiyomi/issues/4286#issuecomment-761586576

**Comment by ManyMangaAreMangos** [comment]
Having the same issue, though I can also add a little.

It seems this is an issue of the deletion taking extremely long, if occuring at all. Deleting one chapter takes 5+ seconds, double that for two, and notably more than triple that time for three. This quickly scales to being unmanagable, obviously

**Comment by arkon** [comment]
Closing in favour of #4286. This is indeed an issue with our lack of Android 11 support.
