### ISSUE TITLE
[Bug] improuvment of chap transation

### ISSUE THREAD

**Issue by zdig1** [tachiyomiorg/tachiyomi#4608]
not a bug but a little error in chapter transation ( error existing from old version )

you have to coorect the order , in fact 
previous chapter must be  above the actual one 

![Screenshot_20210219-191542_Tachiyomi](https://user-images.githubusercontent.com/24459105/110232135-40ecba80-7f1c-11eb-8509-c4b57c490e48.jpg)

**Comment by arkon** [comment]
Why did you not provide any of the information that is asked for in the template? You need to at least tell us the following to even start to figure out what the issue is:

- App version
- Source
- Your sorting setting

**Comment by scb261** [comment]
I think it's this (also bugs me sometimes) - if you go from chapter 1004 to chapter 1003, it will be displayed like this:
1. Last page of chapter 1003
2. Text "Current: Chapter 1004"
3. Text: "Previous: Chapter 1003"
4. First page of chapter 1004

Happens even if sorting is correct. Especially noticeable in webtoon mode.
