### ISSUE TITLE
[Bug] can't select chapters while downloading

### ISSUE THREAD

**Issue by KraXen72** [tachiyomiorg/tachiyomi#4609]
## Device information
* Tachiyomi version: latest preview, stable and sy, occurs on every one of them
* Android version: 11
* Device: Samsung galaxy m21

## Steps to reproduce
1. click the download button (the arrow in the cirlce) for like 10 chapters
2. try holding on a chapter, no menu will come up

### Expected behavior
You should be able to select chapters while other ones are downloading

### Actual behavior
There is a slight animation sometimes and nothing happens

**Comment by arkon** [comment]
Can't reproduce in newer version.

**Comment by KraXen72** [comment]
yes, it appears not to be a thing anymore. i can't reproduce it either
