### ISSUE TITLE
[Bug] Download spinner animation resets every time a new page is downloaded

### ISSUE THREAD

**Issue by KraXen72** [tachiyomiorg/tachiyomi#4610]
## Device information
* Tachiyomi version: stable, preview and sy, occurs on all of them
* Android version: 11
* Device: Samsung galaxy m21

## Steps to reproduce
1. start downloading like 10 chapters or so
2. look at the chapter that is currently downloading - every time the progress bar moves, all of the other waiting spinners of other chapters start their animation from the start

### Expected behavior
The spinner animation while the chapter is waiting to be downloaded should not restart after a page is downloaded

**Comment by arkon** [comment]
Fixed by #4958
