### ISSUE TITLE
[Bug] Incorrect image scaling in webtoon mode

### ISSUE THREAD

**Issue by d4rky-pl** [tachiyomiorg/tachiyomi#4611]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Galaxy Tab S6

## Steps to reproduce
1. Open a manhwa with the first image being wider than the rest (for ex. https://mangatx.com/manga/solo-auto-hunting/chapter-86/)

### Expected behavior
The images are scaled to fit the width

### Actual behavior
The width of the first image is taken and then the dimensions seem to be rescaled for it but the images are centered inside the new bounding box instead of stretched properly, resulting in massive padding between subsequent images 

## Other details
![Screenshot_20210307-151836_Tachiyomi](https://user-images.githubusercontent.com/284395/110242920-757e6780-7f58-11eb-8182-18f457d209e2.jpg)
![Screenshot_20210307-151853_Brave](https://user-images.githubusercontent.com/284395/110242921-76af9480-7f58-11eb-96be-ec35dc8d9321.jpg)

**Comment by scb261** [comment]
Works fine on my phone, probably duplicate of #2736

**Comment by d4rky-pl** [comment]
@scb261 I can confirm that it does indeed work on my phone too, closing as duplicate
