### ISSUE TITLE
[Feature Request] <History Button Held Down Deletes History of all Mangas>

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi#4613]
## Why/User Benefit/User Problem
(explain why this feature should be added)
It's a lot more convenient.

## What/Requirements
(explain how this feature would behave)
Basically, instead of going to the advanced settings every time and deleting the history from there, you could just press and hold on the "History" button in the middle below and an alert would pop up: "Do you want to delete the history of all mangas? Yes/No". This feature could also have a switch in the settings for those who don't want it.

**Comment by arkon** [comment]
I'm going to move the advanced setting to an overflow menu in the history screen instead.
