### ISSUE TITLE
[Bug] Chapter Download icon animations not updating for all chapters in Updates section

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#4615]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10 (Lineage 17.1)
* Device: Redmi 7

## Steps to reproduce
1. Find a Manga which has got multiple new chapters recently (so that it shows up in Updates section) Eg. Blue Period (MangaDex)
2. Download new chapters from the Update section and also from within the Manga
3. Look at the download animation for all chapters in Updates section

### Expected behavior
All chapters should have a downloading animation

### Actual behavior
Only some of the chapters have animation in Updates section
To be precise, some chapters downloaded from within manga get skipped
However, they are still there in the downloading queue

## Other details
Issue can also be reproduced in Sy Preview r340
A video demo is shown below:

https://user-images.githubusercontent.com/72807749/110279573-48d15b00-7fff-11eb-8881-3f112ba91144.mp4

**Comment by arkon** [comment]
Is this still happening?

**Comment by curche** [comment]
Can still reproduce in r3631.
Easier steps to reproduce this issue:
1. Go to Browse, choose a source and add any manga by Long pressing on it (long press is required so that chapter list isn't loaded).
2. Now open the manga added in Step 1 and let the chapter list refresh and load completely. 
3. At this point, some chapters will appear in the Updates section. I was only able to notice the bug when the same series had >=3 chapters appearing in Updates section
4. Once you have >3 chapters in Update, click Download on top two chapters and then go inside the manga (by tapping on the manga thumbnail in Updates) and then click download on few more chapters.
5. Now come back to Updates tab and you'll see not all chapters will have the Downloading Indeterminate (aka the rotating animation) animation but all chapters are clearly there in Download queue

### Video
1. Add Kuno Chiyo Precog from Mangadex
2. Load the chapter list 
3. Note that there are 4chapters in Updates. Now click download on 2 of them right there and open the Manga
4. Click download on next two chapters
5. Check Download queue to see 4 chapters. Check Updates section to see only 3 chapters with download animation.


https://user-images.githubusercontent.com/72807749/127743561-4821da25-4057-4532-9ab3-02ac879c90b3.mov

### Notes
1. While the above steps are certainly not a normal usecase, this is probably the easiest way to notice the change
2. I initially noticed this UI inconsistency when a manga had a bunch of new chapters and then accidently noticed this when I went to download them.

**Comment by AntsyLich** [comment]
UI was moved to compose. And the issue was fixed in compose by #8035
