### ISSUE TITLE
[Feature Request] Preset tags/generes

### ISSUE THREAD

**Issue by Chiro-kun** [tachiyomiorg/tachiyomi#4617]
## Why/User Benefit/User Problem
it would be very convenient and quick to search manga or comics

## What/Requirements
I would like to suggest a feature about filters, in sites likes mangadex or e-hentai you have to manually select every time which tags you want to include/exclude.

In the section filters I would like an option to create a "preset" of tags/generes, once you have created a preset with all categories you desired you don’t need to manually do it anymore.

**Comment by curche** [comment]
I think you are referring to something like Saved Filters which is an already pending request #1484
That'd make this a duplicate issue
