### ISSUE TITLE
include extension Please.

### ISSUE THREAD

**Issue by allastor007** [tachiyomiorg/tachiyomi#4619]
Hello, they could include support for mangatrigre.com
 In Spanish. And it would not be bad if the application worked on Android 4.0 tablets. Thanks.

**Comment by Seishirou101** [comment]
You're in the wrong repo, see https://github.com/tachiyomiorg/tachiyomi-extensions/issues. As for your 2nd question, it'll be probably be no. 4.0 is 9 years old.

**Comment by arkon** [comment]
It would be bad, actually. Supporting old versions of Android is hell, and people who use old versions are security risks anyway.
