### ISSUE TITLE
[Feature Request] adding new sound feature

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi#4622]
## Why/User Benefit/User Problem
(You know in webtoon where they have different music playing in the background while reading,I wonna enjoy that experience so I want you to try and add it)

## What/Requirements
(You just need to add an audio feature while reading and while you are at it, add a setting in the settings to disable it for the people who don't want it and also add a feature to turn it off while you are reading a chapter and you can turn it back on from there too)

**Comment by CarlosEsco** [comment]
#3738
