### ISSUE TITLE
[Bug] Mangasee Extension 

### ISSUE THREAD

**Issue by bloodhound11** [tachiyomiorg/tachiyomi#4625]
**PLEASE READ THIS**
The Mangasee Extension can't open in the app but still updating manga

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Device information
* Tachiyomi version: 1.0.10
* Android version: 9.0
* Device: J7 Pro Samsung

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by Jalen347** [comment]
Mangasee isn't working for me. It will not load the chapter for me. It says "mangasee has blocked tachiyomi"
