### ISSUE TITLE
[Feature Request] category download button

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi#4626]
## Why/User Benefit/User Problem
(I have a category where I download every chapter of the man has there and when I update it,there is like 20 or something new chapters in different man has and it is a pain in the ass to download it manually every time so can you add a download button next to the category name)

## What/Requirements
(Add a download button next to the category that download every chapter of every manga in that category,also ass a bonus make it like normal download,make it ask you if you want to download all chapters or the unread ones)

**Comment by arkon** [comment]
Use the automatic download functionality.
