### ISSUE TITLE
Mangabat

### ISSUE THREAD

**Issue by JustAchie** [tachiyomiorg/tachiyomi#4627]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 6.0
* Device: cellphone

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
All manga should appear if you click the extension or the latest button

### Actual behavior
All the manga don't show up if you click the the extension or the latest button

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by scb261** [comment]
Wrong repo and there is already PR that fixes it, it's just not merged yet tachiyomiorg/tachiyomi-extensions#6137
