### ISSUE TITLE
[Bug] black paged mangas

### ISSUE THREAD

**Issue by medoria0** [tachiyomiorg/tachiyomi#4628]
## Device information
* Tachiyomi version: j2k 1.0.10
* Android version: 10
* Device: Samsung A71

## Steps to reproduce
1. Download any manga chapter, the more the better
2. Open read any manga while the mangas are downloading

### Expected behavior
The pages should download normally

### Actual behavior
Some if not all pages are blank/dark

## Other details
![Screenshot_20210311-113148_TachiyomiJ2K](https://user-images.githubusercontent.com/64145746/110766044-71569080-825d-11eb-88a6-5e4d945d6cfb.jpg)
It finished loading but the screen is black

**Comment by scb261** [comment]
Wrong repo, see https://github.com/jays2Kings/tachiyomiJ2K
