### ISSUE TITLE
[Feature Request] <Adding back the Reader option in Reader UI>

### ISSUE THREAD

**Issue by H3NL0** [tachiyomiorg/tachiyomi#4629]
## Why/User Benefit/User Problem
(The reason why this should be added back is because it would be easier to change the reader option without having to go out of the manga and go to the option section every time just to change a few things.)

## What/Requirements
(Adding back Reader option into the Reader UI, just like in the version r3130)

**Comment by scb261** [comment]
Which reader option are you talking about?

**Comment by H3NL0** [comment]
> Which reader option are you talking about?

This one
![Screenshot_2021-03-11-23-50-18](https://user-images.githubusercontent.com/80454307/110815426-62a3c400-82c5-11eb-8d1a-565c17b5ac90.png)

The UI used to be here, at the bottom of the manga reader (Version r3130)
![Screenshot_20210311-235304](https://user-images.githubusercontent.com/80454307/110816251-245ad480-82c6-11eb-8099-e9e9d604f395.png)


But now, it isn't there anymore (Version r3136)
![Screenshot_2021-03-11-23-50-41](https://user-images.githubusercontent.com/80454307/110815802-ba422f80-82c5-11eb-99e9-94b78eb5ff45.png)

**Comment by scb261** [comment]
Are you using Android 5? It was fixed by 90351c6 and the fix will be in the next release

**Comment by H3NL0** [comment]
Yes, I'm using Android 5.1 device. And it finally show up again after I turn off the fullscreen, thank you very much.
