### ISSUE TITLE
[Bug] <Manga Owl Cloudfare>

### ISSUE THREAD

**Issue by Natillax** [tachiyomiorg/tachiyomi#4630]
Hi!
When I try to search chapters of a new manga in Manga Owl Extension, it shows that it couldn't surpass the cloudfare protection and I couldn't access to the chapters.
Some help?

Thanks!

**Comment by scb261** [comment]
Wrong repository. Also see this https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-the-cloudflare-issue
