### ISSUE TITLE
[Bug] <Invalid URL host>

### ISSUE THREAD

**Issue by tobiena** [tachiyomiorg/tachiyomi#4631]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by tobiena** [comment]
Was having an issue viewing/downloading from Mangasee extension experience this early morning after an update of the extension.

**Comment by CrepeTF** [comment]
![dNlB2Vs.jpg](https://user-images.githubusercontent.com/70870719/110803755-6c063f80-8277-11eb-8e88-08ca9ccffd2b.jpg)
