### ISSUE TITLE
[Feature Request] sorting downloads by sources

### ISSUE THREAD

**Issue by eak0mo** [tachiyomiorg/tachiyomi#4632]
## Why/User Benefit/User Problem
since tachiyomi has a multi download feature based on different sources, it would be much faster to download if the downloads could be sorted according to each unique source so the download gets completed quickly.

## What/Requirements
this feature would sort the download list by alternating the sources from the first to the last, and when there are no new unique sources it adds the remaining.

**Comment by arkon** [comment]
This is possible in the preview version.
