### ISSUE TITLE
Questions and suggestions about software not being posted

### ISSUE THREAD

**Issue by Root-1404** [tachiyomiorg/tachiyomi#4634]
## Device information
* Tachiyomi version: tachiyomi-v0.10.9
* Android version: 11
* Device: xiaomi k30

## Issue/Request
Software appears 0.0.0.0/443

I don’t know if the author has open access to the Chinese Internet，The software can’t install the plug-in (maybe I didn’t connect the agent)

I hope the developers will see and reply to me (the above English are all Google translations)

**Comment by scb261** [comment]
If you can't install extensions - try to download from the site http://tachiyomi.org/extensions . If you still can't install extensions, try to install them using [SAI](https://play.google.com/store/apps/details?id=com.aefyr.sai).

**Comment by arkon** [comment]
Parts of GitHub had issues earlier so I'm not sure if that was what you experienced.

**Comment by Root-1404** [comment]
> GitHub的某些部分较早出现了问题，所以我不确定这是否就是您所经历的。


I don’t know if it’s my problem, but I’ll give it a try

**Comment by Root-1404** [comment]
I read it online, it seems that my network problem is 443. If I don’t open the proxy, I can’t download the extension.
The software is good, but you have to open an agent to get it. Not very friendly to Chinese users

**Comment by arkon** [comment]
Great Firewall of China. 🤷‍♂️
