### ISSUE TITLE
[Bug] <Application not opening any chapter at all>

### ISSUE THREAD

**Issue by sea123-ea** [tachiyomiorg/tachiyomi#4636]
## Device information
* Tachiyomi version: latest
* Android version: 7.0
* Device: Huawei P9

## Steps to reproduce
1. Open app
2. Open manga chapter
3. JSON Document error

### Expected behavior
The manga chapter should open

### Actual behavior
No manga chapters are opening

## Other details
whenever I open any manga chapter to read, the error is shown as 'JSON Document was not fully consumed'. Please fix this as soon as possible. I tried reinstalling the application, both versions and still no luck.

No crashes.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6136
