### ISSUE TITLE
[Feature Request] Assign titles as Webtoon or manga

### ISSUE THREAD

**Issue by i8noodles-square-better** [tachiyomiorg/tachiyomi#4637]
---

## Why/User Benefit/User Problem
Some Webtoons like The Beginning after the end , Solo Leveling, Spirit Sword Sovereign are cut off if you read them left to right or in horizontal mode. This makes it so, sometimes, words are hard to read because speech bubbles are cut off or sentences are cut in half or images are harder to see. Rather then having to swap between continuous vertical and horizontal mode for your preferred reading method
This also solves an ongoing problem where you have to zoom in to read sometimes when the chapter is split in smaller numbers of pages so the images and words are way to small to read.

## What/Requirements
In general, u can assign any title as "webtoon" or "manga" and it assigns it to your preferred reading method of that particular title. I.e If it is assigned webtoon it would force continuous vertical scroll (or your preferred method) and for manga it would force it to left to right (of your preferred method)

**Comment by arkon** [comment]
You can set reading modes per title already from the in-reader settings.

**Comment by arkon** [comment]
You can set reading modes per title already from the in-reader settings.
