### ISSUE TITLE
[Bug] Random crashes

### ISSUE THREAD

**Issue by totopesce** [tachiyomiorg/tachiyomi#4638]
---

## Device information
* Tachiyomi version: 0.10.9
* Android version: 7.0
* Device: samsung galaxy tab s2 9.7'

## Steps to reproduce
1. Just having it open, doesnt matter if its in background or actively in use.

### Expected behavior
Should not crash.

### Actual behavior
Crashes, message appears saying it stopped working and it restarts.

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

Dont know where to find the crash dumps after doing what says above, but have this logs.
Also tried updating chrome webview as I read that could cause issues and still happens. And its been happening for a couple months.
[logcat_03-12-2021_16-43-10.zip](https://github.com/tachiyomiorg/tachiyomi/files/6132656/logcat_03-12-2021_16-43-10.zip)

**Comment by Lyoooooo** [comment]
Got the exact same problem with android version 10 on a honor 10 lite

**Comment by Chaostheorie** [comment]
Reproduced on Redmi note 8 Pro with MIUI 12.

Apparently due to Null Pointer dereference. Appears on multiple occasions such as: Downloading some Mangas, opening extensions or trying to download & install a new extension.

**Comment by arkon** [comment]
@Lyoooooo @Chaostheorie Your crashes are not related to this issue.

See https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952

**Comment by totopesce** [comment]
That happened with my phone.
It seems my tablet is too old and I didnt get that update, I can only update to v58, and still having the same problems. 
Tried updating by apk and updating chrome and cant get a newer webview, cant even roll updates back.

**Comment by samanta-widjaja** [comment]
I'm having it too. And all my download queue is gone, when i open tachiyomi back. Please fix

**Comment by arkon** [comment]
Please provide crashlogs if possible, otherwise nobody knows what you're experiencing.

**Comment by samanta-widjaja** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6215925/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Not sure what's wrong here. If it's still happening in v0.10.10, please open another issue with the shared logs.
