### ISSUE TITLE
[Bug] <unable to open manga>

### ISSUE THREAD

**Issue by Rahhhmoy** [tachiyomiorg/tachiyomi#4639]
Device information
* Tachiyomi version: 0.10.9
* Android version: 7
* Device: samsung A7

## Steps to reproduce
1. Force stop and reopen the app.
2. Still same massage notified.

### Expected behavior
Can open and download chapter like other source.

### Actual behavior
Unable to download and read thru app for mangasee and mangalife. It stated that overloaded and blocking tachiyomi .

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by curche** [comment]
wrong repo
already reported at https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6136

also latest #status-update from discord server:
*2021-03-12* We don't know if or when Mangasee/MangaLife will unblock us. Don't ask us about it. And definitely don't bother Mangasee/MangaLife site owner, it will only further agitate them. **Migrate to a difference source**

**Disclaimer:** Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
