### ISSUE TITLE
[Feature Request] <Add option to filter by extension/source>

### ISSUE THREAD

**Issue by ysnsmth** [tachiyomiorg/tachiyomi#4640]
Add an option to filter or sort by extension/source

## Why/User Benefit/User Problem
very helpful when an extension doesn't work (I don't really keep track of what extension/source a manga/webtoon is from, I think most people don't), also helpful when you have more than 100 mangas and webtoon

it also makes migrating mangas/webtoons from one source to another easier 

## What/Requirements
just like how filter by trackers was implemented

**Comment by ysnsmth** [comment]
nvm i just saw the 3rd option in browse🤦‍♂️

feature would still be appreciated tho if possible

**Comment by arkon** [comment]
You can already search by the source name in the library.
