### ISSUE TITLE
[Bug] Wide Webtoon images split when Dual Page Split is on

### ISSUE THREAD

**Issue by Waelwindows** [tachiyomiorg/tachiyomi#4643]
## Device information
* Tachiyomi version: v.0.10.9
* Android version: Android 10
* Device: OnePlus 7 Pro

## Steps to reproduce
1. Turn on [ALPHA] Dual Page Split
2. Open up a series with Webtoon rendering.
3. Scroll to a wide panel.

### Expected behavior
Page should render like normal with Dual split page off
![tachiyomi_correct](https://user-images.githubusercontent.com/5228243/111039572-cf42ce00-843f-11eb-9d86-21a0cfb974c0.png)

### Actual behavior
![tachiyomi_incorrect](https://user-images.githubusercontent.com/5228243/111039582-db2e9000-843f-11eb-9bc6-76eed6ae1610.png)

## Other details
Examples are taken from Bluechair ch 12, in the Webtoons.com extension.

**Comment by arkon** [comment]
Sort of addressed by #4527, which would let you turn it off for the webtoon mode (where it makes less sense normally).
