### ISSUE TITLE
[Feature Request] Set default reading mode for each source/extension

### ISSUE THREAD

**Issue by zedseven** [tachiyomiorg/tachiyomi#4649]
## Why/User Benefit/User Problem
Many of the extensions/sources are for only one type of content (manga, comic, webtoon), so allowing the user to set a default reading mode for everything from a specific source would easily allow for the correct reading mode to be used by default for different types of content.

For example: If a user sets R2L for all their manga sources, Webtoon for their manhwa, and L2R for their comics, all three will have the correct defaults with minimal extra effort.

## What/Requirements
Allow the user to set a default reading mode for each source, so the Default setting on individual issues uses what's been set for the source.

**Comment by arkon** [comment]
It'll be easier to toggle the reading mode in the reader in the next stable release, so I'd point people towards that to reduce complexity.
