### ISSUE TITLE
tags 

### ISSUE THREAD

**Issue by MeDemon0** [tachiyomiorg/tachiyomi#4650]
## Request
I would like it if we can click on tags in the sources tap or any where for that matter and it'll search by tag.

Please and Thank you

**Comment by scb261** [comment]
You mean tapping on tag would open search for this tag? Just like it already does?

**Comment by MeDemon0** [comment]
Yes that would be great. I used to do it befor , I just searched for
something and then I open the source tap on back one time and search using
tags that way.

**Comment by scb261** [comment]
As I said, you already can tap on tag to search by it

**Comment by arkon** [comment]
^ What he said.

It works if you're browsing from the "Browse" mode, but not "Latest", as searching is only accessible via Browse.

**Comment by MeDemon0** [comment]
> ^ What he said.
> 
> It works if you're browsing from the "Browse" mode, but not "Latest", as searching is only accessible via Browse.

yes exactly
