### ISSUE TITLE
[Feature Request] Graying out manga when all available chapters are read

### ISSUE THREAD

**Issue by tinbolw** [tachiyomiorg/tachiyomi#4654]
## Why/User Benefit/User Problem
(explain why this feature should be added)
If you are reading a lot of ongoing manga, it would be useful for manga with new chapters to be prioritized in the list over ones without new chapters yet, by Graying out every manga without new chapters, for example

## What/Requirements
(explain how this feature would behave)
This would be an optional setting.
When all chapters of a manga are read, it will turn slightly gray or perhaps a bit transparent and it will be moved under mangas that have available chapters. Mangas that have available chapters will not be grayed out.

**Comment by arkon** [comment]
You can just use the existing filters and sorting options.
