### ISSUE TITLE
[Feature Request] <Remote control>

### ISSUE THREAD

**Issue by Nonamow** [tachiyomiorg/tachiyomi#4656]
Idea: Tachiyomi create local site, so we can connect, read and manage manga this way:

  **Android-Tachiyomi**  <----> **router**  <---->  **Other devices e.g. PC (just type ip in browser)**

Minuses: 
-Is it really important?
-Complicating the app. 
-Increasing size.
-A lot of work.
-Adding some bugs.

Suggestion: should we add this as an extension?

I really want to help add this feature... but I am a noob.

**Comment by Seishirou101** [comment]
are you asking tachi to host their own website? if so, thats a no cause tachi doesn't have a server. Or are you asking for a way to host your own? You can host your own using komga, lanraragi, or foolslide and connect to them through their respective extension.

**Comment by az4521** [comment]
the feature requested is for the tachiyomi app to also act as a web server, allowing other devices on the local network to connect to a phone running tachiyomi and read manga.

**Comment by arkon** [comment]
Duplicate of #2118

**Comment by az4521** [comment]
> @az4521, is it technically possible to do this within _tachiyomi-extensions_? (Without editing main code and creating fork)

no.
