### ISSUE TITLE
[Bug] <Crete Backup/Create Legacy Backup Malfunctioning>

### ISSUE THREAD

**Issue by fatenoteface** [tachiyomiorg/tachiyomi#4658]
## Device information
* Tachiyomi version: Preview r3159
* Android version: 10
* Device: Galaxy Tab A7 SM-T500

## Steps to reproduce
1. First step: Create backup/Create legacy backup

### Expected behavior
Create a backup were the mangas are organized in each category and the read chapters are counted.

### Actual behavior
A backup were all mangas are only located in the default category of the library is created, although that the categories are properly created, they remain empty.
The chapters read count are not included in the backup

## Other details
Currently trying to restore the backup form the preview version r3159 to the stable version 0.10.9
I believe that the issue is regarding to the creation of the backup, my previews (stable version) backup are 580 KB and the currently from the preview version is 105 KB. Legacy also is 0.96 MB to 43,27 KB
When restoring old versions of the backup from previews versions the (580 KB and 0.96 MB) mentioned earlier, everything works fine.

**Comment by scb261** [comment]
Could be similar to #2800, try this https://dontkillmyapp.com/

**Comment by fatenoteface** [comment]
Solved the issue, it was the device developer mode setting "don't keep ativities"
