### ISSUE TITLE
[Bug] Bangumi can't sync track 

### ISSUE THREAD

**Issue by OYcedar** [tachiyomiorg/tachiyomi#4659]
## Device information
* Tachiyomi version: stable 0.10.9
* Android version: 10
* Device: oneplus 7 pro

## Steps to reproduce
1. First step 
setting-sync-login bangumi
2. Second step 
add mange to sync , choice score or chapter, alertview show unknown status : 0

## Other details

![Screenshot_20210316-233402](https://user-images.githubusercontent.com/13297960/111337391-0370f580-86b1-11eb-8445-4e139f0a9a94.jpg)

**Comment by arkon** [comment]
I'm actually not sure why this is happening since I'm not familiar with the Bangumi API, but as a workaround you should set the status first.
