### ISSUE TITLE
[Bug | MangaJar] Pages are being downloaded to .txt files

### ISSUE THREAD

**Issue by Mrnofish** [tachiyomiorg/tachiyomi#4660]
## Device information
* Tachiyomi version: 0.10.9
* Extension version: 1.2.3
* Android version: Multiple
* Device: Multiple

## Steps to reproduce
1. Add Manga from MangaJar
2. Download some chapters
3. Some chapters may error out
4. Tachiyomi will save all pages with a .txt extension. The images can still be viewed with another app that checks the file type independently from the extension.
5. When opening one of the affected chapters, Tachiyomi will display a "No pages found" error.

### Expected behavior
Tachiyomi should be saving files from MangaJar with the correct extension.

### Actual behavior
Tachiyomi is still downloading pages, but files are saved with a .txt extension.

**Comment by scb261** [comment]
Wrong repo and can't reproduce. Open an issue in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose and give examples: what chapters are giving error, what chapters have pages with txt extension.
