### ISSUE TITLE
skips versioned chapters. optional?

### ISSUE THREAD

**Issue by MasoudRahmani** [tachiyomiorg/tachiyomi#4663]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Samsung Tab-A

## Steps to reproduce
1. a source that has versioned chapters
like :
-chapter 129
-chapter 129 [v2]
example: https://read.mangabat.com/read-tb13698

2. start reading from 128 and when you go for the next chapter  it skips version number 1

## Issue/Request
there are some instances that i want to read both version and find out the diffrence if this feature is intentional please include an option to have control over it

**Comment by scb261** [comment]
You can use sort by source or sort by date. Sort by number skips duplicates

**Comment by MasoudRahmani** [comment]
Thanks for your great app and all this feature.
just a little thought, This could count as a implicit feature, as thought finding how to use it require more than playing with application and reading through this powerful and complete FAQ or Guide or by asking. wouldn't it be better if it was included as a setting ?

**Comment by arkon** [comment]
You should ideally be manually marking the ones you don't want to read as read and setting the reader to respect your filters.
