### ISSUE TITLE
[Feature Request] Downloaded Chapter List that stored on Storage

### ISSUE THREAD

**Issue by Alp-o** [tachiyomiorg/tachiyomi#4664]
Downloaded Chapter List that stored on Storage

---

## Why/User Benefit/User Problem
I have an issue when I delete a chapter, of course it disappear from tachiyomi, but not in my SD Card. The downloaded chapter still remain on SD Card, but not in library.  I have about 300 titles that are still stored on the SD Card, but in my library there are only 100. I'm sure I already deleted some of the title, and check the 'Downloaded Chapters' checkbox too, but the file still remain. You can consider this as an issue too.

## What/Requirements
The feature will provide a list of which files have been downloaded but haven't added in the library, and which have been downloaded and have added in the library, and the ability to delete / add chapter files that have been downloaded from / to the library

**Comment by Alp-o** [comment]
Sorry for my bad english

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/1767
