### ISSUE TITLE
[Bug] <Restoring backup crashes the app at 80/105>

### ISSUE THREAD

**Issue by Magnex1991** [tachiyomiorg/tachiyomi#4666]
---

## Device information, android phone
* Tachiyomi version: 0.804
* Android version: 10
* Device: samsung galaxy note s10+

## Steps to reproduce
1. First step reset phone
2. Second step uninstalled and reinstalled app

### Expected behavior
This should happen. should just restore backup.

### Actual behavior
This happened instead. crashes and closes app at 80 out of 105 restores (nothing actually restores)

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by scb261** [comment]
What version of tachi is `0.804`? Make sure you have newest version https://tachiyomi.org/download/

**Comment by Magnex1991** [comment]
@scb261 ive updated it to the newest version, its saying invalid file type now.

**Comment by scb261** [comment]
How is your backup file named? Can you send it here?

**Comment by Magnex1991** [comment]
@scb261 Sure. ive had to make a link as githup is saying it doesnt support that file type. https://easyupload.io/szp98g

**Comment by scb261** [comment]
That's some shady site and the file doesn't even have an extension at the end. Your backup file is probably corrupted. It should end with `.json` or `.proto.gz`.

**Comment by Magnex1991** [comment]
@scb261 probably is sorry i just googled file upload, ahh damn that sucks gonna have to find all 105 mangas again xD cheers for replying though.
