### ISSUE TITLE
[Bug]The extension of Komikcast is installed but not in the source

### ISSUE THREAD

**Issue by fuad04** [tachiyomiorg/tachiyomi#4672]
## Device information
* Tachiyomi version: v10.9
* Android version: 6
* Device: j2 prime

## Steps to reproduce
1. Unnistall komikcast
2. Install komikcast

![Screenshot_20210319-162022](https://user-images.githubusercontent.com/80931279/111758420-16611100-88cf-11eb-991a-968dd856fd44.png)
![Screenshot_20210319-162017](https://user-images.githubusercontent.com/80931279/111758432-19f49800-88cf-11eb-8ffe-ce00978d11c8.png)

**Comment by scb261** [comment]
<details>
<summary>Make sure it's enabled in the filter</summary>
 
![image](https://user-images.githubusercontent.com/65343233/111826819-d1020b00-88f1-11eb-9828-60cfabfd02cf.png)

</details>

<details>
<summary>Also check if it's enabled in the extension settings</summary>
 
![image](https://user-images.githubusercontent.com/65343233/111827134-3655fc00-88f2-11eb-9728-292a9c6c5f9b.png)

</details>

**Comment by fuad04** [comment]
> Make sure it's enabled in the filter
> Also check if it's enabled in the extension settings

it's the same, I've checked it
![Screenshot_20210320-044907](https://user-images.githubusercontent.com/80931279/111845911-5a3c3080-8938-11eb-80c4-e719e900b901.png)

**Comment by scb261** [comment]
And how about source filter? (the first image in my previous comment)

**Comment by fuad04** [comment]
> And how about source filter? (the first image in my previous comment)

yes it's the same

**Comment by scb261** [comment]
The same compared to what? Is it present and enabled in the filter?

**Comment by fuad04** [comment]
> The same compared to what? Is it present and enabled in the filter?

yes it is there but the filter is not there, I've been looking for it

**Comment by scb261** [comment]
Can you open filter and screenshot it?

<details>
<summary>Like this</summary>

| tap filter button | find Komik Cast there |
| --- | --- |
| ![filter_button](https://user-images.githubusercontent.com/65343233/111847990-b12f0f00-8912-11eb-9976-9d4b6dcffce1.png) | ![filter_list](https://user-images.githubusercontent.com/65343233/111848006-b8561d00-8912-11eb-8629-d07f5befa0d6.png) |



</details>

**Comment by fuad04** [comment]
![Uploading Screenshot_20210320-052745.png…]()

**Comment by fuad04** [comment]
> Can you open filter and screenshot it?
> 
> Like this
> tap filter button	find Komik Cast there
> ![filter_button](https://user-images.githubusercontent.com/65343233/111847990-b12f0f00-8912-11eb-9976-9d4b6dcffce1.png)	![filter_list](https://user-images.githubusercontent.com/65343233/111848006-b8561d00-8912-11eb-8629-d07f5befa0d6.png)

![Screenshot_20210320-052745](https://user-images.githubusercontent.com/80931279/111848210-1f88c700-893d-11eb-8d26-69777f44deb2.png)

**Comment by fuad04** [comment]
![IMG-20210320-WA0000](https://user-images.githubusercontent.com/80931279/111848363-78f0f600-893d-11eb-92f7-ef74d6733e82.jpg)

since then some extensions are not in the source

**Comment by scb261** [comment]
Try to force close the app in phone settings. If this doesn't help - try to reinstall the extension and force close again.
