### ISSUE TITLE
[Feature Request] <Update history limit>

### ISSUE THREAD

**Issue by rafalohaki** [tachiyomiorg/tachiyomi#4673]
We need to show latest 50-100 chapters in update history with added button show more. 
My phone almost crashing from buffering. 
Need to wait 5seconds to load tab.
Btw, I have snapdragon 865

**Comment by arkon** [comment]
Updates or history? They're not the same thing.

Are you using preview? Did it get slower after the recent update?

**Comment by rafalohaki** [comment]
> 
> 
> Updates or history? They're not the same thing.
> 
> Are you using preview? Did it get slower after the recent update?

There is infinity list of updates. 
Im using preview version and its slow like i wrote.

**Comment by arkon** [comment]
You're not answering the questions correctly.

History has infinite scrolling. Updates has the past 3 months of updates.

You also didn't answer the "Did it get slower after the recent update?" part.

If English isn't your first language, please post in your native language and we'll get someone to translate it.

**Comment by rafalohaki** [comment]
> 
> 
> You're not answering the questions correctly.
> 
> History has infinite scrolling. Updates has the past 3 months of updates.
> 
> You also didn't answer the "Did it get slower after the recent update?" part.
> 
> If English isn't your first language, please post in your native language and we'll get someone to translate it.

I'm sorry that u can't understand.
I didn't knew it has 3months expire but after you use backup with 500+ titles, u get very huge amount of chapters which are logged in update history. That's how i got long loading in updates tab.

**Comment by scb261** [comment]
There were some [changes](https://github.com/tachiyomiorg/tachiyomi/pull/4645) in fetching new chapters from database, can you downgrade to [the previous version](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3144) and check if the issue happens there?

**Comment by rafalohaki** [comment]
> 
> 
> There were some [changes](https://github.com/tachiyomiorg/tachiyomi/pull/4645) in fetching new chapters from database, can you downgrade to [the previous version](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3144) and check if the issue happens there?

I just wanted to give opinion about how its working for me and would be nice to limit view of history update even if its expiring there is a still problem with this, beacause of large history update from migrations or backups.

**Comment by rafalohaki** [comment]
video: https://siasky.net/AACFzBEDle4SFCTgroht79eanwjETFlK5Ui10J9gRVDbqQ

**Comment by dmswd** [comment]
In simple words the updates tab becomes super slow to load it takes about 1 minute to load and my suggestion is either to limit it to 100 or 1000 chapters
As I had about 50000 chapters so it was very slow
