### ISSUE TITLE
[Feature Request] <A tachiyomi windows app>

### ISSUE THREAD

**Issue by ESCANES** [tachiyomiorg/tachiyomi#4675]
there really isn't any good manga app for Pc's and i think the tachiyomi app would be great

**Comment by scb261** [comment]
Tachiyomi developers are **Android** developers, and they won't make an app for PC because it means writing entirely new app and requires different programming knowledge. You can search for other manga apps for PC that may or may not be similar to Tachiyomi's interface and functional.
