### ISSUE TITLE
[Bug] Help!

### ISSUE THREAD

**Issue by Ho-Sang** [tachiyomiorg/tachiyomi#4680]
I just recently downloaded the app but in my app there are only two extensions. I can't read the manhwas I would like to read. I gave tried things such as refreshing or reinstalling the app but there's still only two extensions. Can you help me?

**Comment by Ho-Sang** [comment]
![Screenshot_20210320-180946_Tachiyomi](https://user-images.githubusercontent.com/81019219/111868352-e2a5ea00-89a7-11eb-9b68-15cceadd9a45.jpg)

**Comment by CrepeTF** [comment]
Have you enabled other languages under the source and browse filters?

![111868352-e2a5ea00-89a7-11eb-9b68-15cceadd9a45__01.jpg](https://user-images.githubusercontent.com/70870719/111868563-97251900-8972-11eb-9a94-62c1f2dd8b39.jpg)

**Comment by arkon** [comment]
Whatever work/private profile thing you're using is potentially blocking access to GitHub if you can't seem to load the extensions list.
