### ISSUE TITLE
[Feature Request] Read/Download Chapters from Source B instead of Source A

### ISSUE THREAD

**Issue by rona0503** [tachiyomiorg/tachiyomi#4682]
## Why/User Benefit/User Problem
Some chapters of a manga does not load properly even if there is high speed data, so this feature would be handy

## What/Requirements
When you hold a chapter, there is a option to read/Download chapter from another source
Ex.
Chapter 10 of Manga X from Source A
If Chapter 10 does not load
Then hold Chapter, then click Read/Download Chapter from another source (Source B)
Then whenever you click Chapter 10 from Source A, It will always linked to Chapter 10 of Manga X from Source B unless clicked otherwise

**Comment by scb261** [comment]
Pretty much the same as #886
