### ISSUE TITLE
[Bug] Getting Crashes after Android 11 update

### ISSUE THREAD

**Issue by salmanbacok** [tachiyomiorg/tachiyomi#4694]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: Galaxy A50s

## Steps to reproduce
1. Click anything on the app
2. Crash

## Other details

https://user-images.githubusercontent.com/81198736/112073430-aa202f00-8ba6-11eb-87d3-185a06f17be2.mp4

**Comment by arkon** [comment]
See https://twitter.com/tachiyomiorg/status/1374128475586621442?s=19

---

🚨 A possible fix has been found for users encountering #Tachiyomi, #TachiyomiJ2K, #TachiyomiSY, and other apps crashing.

Uninstall all Chrome or WebView updates in your device settings, alternatively uninstall and reinstall them.

Read more here: https://t.co/SONRqFRY9D
