### ISSUE TITLE
[Bug] App crashes if you click on any extension in the browse section.

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi#4695]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: Android 11.0 (Samsung One UI 3.0) 
* Device: Samsung Galaxy S10

## Steps to reproduce
1. Install the extensions that you want to keep/that are needed in a multi source extension. (I installed like 20 extensions).
2. Uninstall said multi source extension. (In this case i uninstalled 2).
3. Reboot the app. Sources show up as correct and manga can be read.
4. Go to the browse section.

### Expected behavior
You should be able to search for a manga or view manga inside an extension.

### Actual behavior
 As soon as you click on the search icon in the browse section, or you click on an extension to view the manga it may have, the app force crashes. This does not happen, however if you go to the "extensions" tab of the browse section and it will let you change settings of an extension. The search icon, however, will still not work.

## Other details
Additional details and attachments.
Crash log: https://drive.google.com/file/d/1f0H_maCVfTqfP1UJxL6D1X99JS50xkhQ/view?usp=sharing
If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

Edit: I have also already tried restarting my phone and force stopping, restarting the app multiple times. I'm not sure if wiping the cache partition would help but i can do that next.

Edit 2: On second look, it seems like I can't actually read manga either except for one (i.e. not a source problem), and these manga are all from the same source, the app just crashes.

**Comment by Silvermane06** [comment]
It also seems like issue #4693 which was closed because of having no title is having a problem as well of reading manga, also with a samsung phone.

**Comment by Neoterux** [comment]
This issue seems to be caused by an update to webview, to fix that i installed a magisk module that change my default webview to another and this issues gone. Some websites are reporting crashes with another apps with the same problem, this sites recommend uninstall the latest update of webview from play store, or (ir you have root) install the module Webview module until Webview get a fix.

**Comment by Silvermane06** [comment]
I just found a reddit post saying the same thing. Is there a specific webview version that is needed/site to get that?

Post: https://www.reddit.com/r/samsung/comments/mb08jj/to_fix_the_crash_issue_go_to_google_playstore_and/?utm_medium=android_app&utm_source=share

**Comment by Neoterux** [comment]
I think that you can use Bromite: https://www.bromite.org/system_web_view.
But I have not tested because I use a magisk module.

**Comment by Silvermane06** [comment]
Uninstalled webview and reverted to stock out of box webview, none of my apps crash anymore and tachiyomi works. 
~~Not sure if I should close the issue since it's solved or leave it open for anyone in the future since it seems to be a widespread problem for samsung androids in general until webview is fixed~~
Went ahead and closed it.
