### ISSUE TITLE
My library is gone

### ISSUE THREAD

**Issue by walsand987** [tachiyomiorg/tachiyomi#4696]
I was unable to update to v0.10.9 and my tachiyomi was no longer able to start up for some reason, so I installed v0.10.9 online an started it up, but my library and all my saved manga is not in the updated version since its a fresh install, i have all my extensions. 

I still have the previous verion which I can't start up, so I can't manually search up every single manga I want to transfer. 

Any help on how to transfer my library from the previous version to the new version?

**Comment by scb261** [comment]
I'm not sure how you installed two 0.10.9 versions, but for the one that doesn't open - https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952

**Comment by walsand987** [comment]
the previous one couldnt update, so its stuck in a previous version

**Comment by walsand987** [comment]
update: updated my chrome, fixed the old app, now making a backup and going to move to v0.10.9
