### ISSUE TITLE
Can't open any Manga, extensions or my library

### ISSUE THREAD

**Issue by Austria-chan** [tachiyomiorg/tachiyomi#4697]
## Device information
* Tachiyomi version: stable 0.10.9
* Android version: 11
* Device: Samsung A71

## Steps to reproduce
1. I open Tachyiomi
2. I open any manga, extensions or my library
3. Then it crashes

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6187650/tachiyomi_crash_logs.txt)

**Comment by evenns** [comment]
I have a similar issue. I open the app, and a few seconds later it crashes. Happens with stable version and preview version. Tried using an older version of stable version and it still crashed. Uninstalling and reinstalling seems to fix the issue for a little while, but after exiting and opening the app a few times it comes back and crashes.

Running android version 10, motorola 5g  plus. Could be an android issue and not an issue with the app itself?

**Comment by scb261** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952

@evenns you too, read the link above

**Comment by Austria-chan** [comment]
Just found out by uninstalling uptades of Android system webview fixes the problem.
