### ISSUE TITLE
The app is crashing

### ISSUE THREAD

**Issue by vincent1805** [tachiyomiorg/tachiyomi#4698]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

The app is crashing before I can access the library

**Comment by scb261** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952

**Comment by Austria-chan** [comment]
Try goimg to apps im system settings. Find Androod system webview. Tap the three dots on the top right and uninstall uptades

**Comment by Unimatrix007** [comment]
Thanks the uninstall of webwiew helped, and for those that use WEBTOON app that crashes this fix works for it too. Bloody google messing stuff up.
