### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by kaoru013** [tachiyomiorg/tachiyomi#4699]
## Device information
* Tachiyomi version:  Tachiyomi 0.10.9
* Android version: 9
* Device: Samsung S8+

## Steps to reproduce
1. Open the app
2. I can read my manga

### Expected behavior
It would run smoothly

### Actual behavior
This happened instead, when I choose a manga it forces close the app, or when I'm in the chapters area it closes

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

![Screenshot_20210323-160530_Tachiyomi](https://user-images.githubusercontent.com/81219627/112113360-af569b80-8bf1-11eb-88ed-17b16f4ddce0.jpg)

![Screenshot_20210323-160536_One UI Home](https://user-images.githubusercontent.com/81219627/112113369-b1b8f580-8bf1-11eb-8f95-218610c00ef6.jpg)

content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt

**Comment by scb261** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952

**Comment by kaoru013** [comment]
Thank you for citing that scb261!! It's working already!! 😊 thank you very much for helping!! God bless!! 😀
