### ISSUE TITLE
[Bug] Tachiyomi crashes when searching sources for manga

### ISSUE THREAD

**Issue by Prometheus0000** [tachiyomiorg/tachiyomi#4700]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 7.0
* Device: Asus Zenpad 3S 10, model P027

## Steps to reproduce
1. Type anything in the search for global search of sources. Just to be clear, this is under browse -> sources.
2. Launch search

### Expected behavior
Searches manga

### Actual behavior
Crashes

## Other details
It worked yesterday, and I don't remember doing anything to change any settings or something.

Search of library works, as does extensions.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6190127/tachiyomi_crash_logs.txt)

**Comment by scb261** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952
