### ISSUE TITLE
[Bug] <Library Update but crashes instead>

### ISSUE THREAD

**Issue by Morileck** [tachiyomiorg/tachiyomi#4702]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 9
* Device: Huawei Y9

## Steps to reproduce
1. open app
2. update library for new chapters

### Expected behavior
This should happen.
progress of updating and searching for new chapters, progress bar shown in notification bar

### Actual behavior
This happened instead.
App tries to update library but freezes and crashes then tries to restart

## Other details
Additional details and attachments.
i tried to uninstall and reinstall but it still happens

content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4694#issuecomment-804492952
