### ISSUE TITLE
[Feature Request] Library cleanup (Duplicates, Missing source, Orphaned downloads, etc)

### ISSUE THREAD

**Issue by B10Reaper** [tachiyomiorg/tachiyomi#4706]
If this exists elsewhere I could not find it.
Currently there is no way I can see to do a cleanup besides checking one by one, and over the year(s) I've used this app the various extension changes/deletions have resulted in various entries in my library having numbers in the source (missing source), duplicate entries either due to language or source differences, and a few that were downloaded but then all I could get was "chapters not found" that ended up in my folder but not my library.

What I would like is a function that checks for at least the first 2 so I can update the entry or delete the duplicate. Having dead sources has been especially a problem lately with the extensions getting their sources split to their own and then not transferring for whatever reason.

The dead sources is by far the biggest problem, with hundreds of manga in my library the only way I can find to check right now is to go one by one, so if considering please give that priority.

**Comment by scb261** [comment]
Duplicate manga - #2230
Missing source / dead source - you can enable `Show update errors notifications` and update library to see them
Orphaned downloads - #1767
