### ISSUE TITLE
[Bug] Migration Fails

### ISSUE THREAD

**Issue by Qnomei** [tachiyomiorg/tachiyomi#4707]
## Device information
Tachiyomi Version: 0.10.9-3172 (standard, 99ba84c8, 56)
Android version: 9 (SDK 28)
Android build ID: PKQ1.181105.001
Device brand: lge
Device manufacturer: LGE
Device name: judyln
Device model: LM-G710
Device product name: judyln_lao_com

## Steps to reproduce
1. Pick any manga from any working source. 
2. Migrate manga to any other working source with all options enabled, not using the copy option. 

### Expected behavior
The old source manga is removed from the library and the new source manga is added with progress and tracking transferred. 

### Actual behavior
The old source manga is untouched. The new source manga is placed in the default category with no reading progress or tracking from the old one. 

## Other details
Crash Log:

--------- beginning of system
--------- beginning of main
03-23 22:30:50.361 23701 23701 E tachiyomi.debu: Invalid ID 0x00000000.
03-23 22:30:50.365 23701 23701 E tachiyomi.debu: Invalid ID 0x00000000.
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: rx.exceptions.MissingBackpressureException: PublishSubject: could not emit value due to lack of requests
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:307)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter.fetchImage(GlobalSearchPresenter.kt:218)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter.access$fetchImage(GlobalSearchPresenter.kt:37)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$search$1$5.call(GlobalSearchPresenter.kt:178)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$search$1$5.call(GlobalSearchPresenter.kt:37)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onNext(OperatorSubscribeOn.java:74)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:38)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:159)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Subscriber.setProducer(Subscriber.java:205)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Subscriber.setProducer(Subscriber.java:205)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:58)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:26)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-23 22:32:35.896 24073 24073 E GlobalSearchPresenter$initializeFetchImageSubscription: 	at java.lang.Thread.run(Thread.java:764)

**Comment by arkon** [comment]
Should be fixed in r3185. Please let us know if not.
