### ISSUE TITLE
[Bug]  Download issue

### ISSUE THREAD

**Issue by Funny-Bunny** [tachiyomiorg/tachiyomi#4708]
There's a problem with the download of the chapters. The issue goes like this: I marked a few chapters to download, started the process then saw that it required WiFi to go through. I realized I forgot to disable the 'Download only over wifi' option so I went in Settings and did that. The problem is that the download didn't resume over data and I couldn't stop the process as I didn't see any option to do that. I had to delete the app's data and restore from a backup to be able to start downloading over mobile data.
Maybe I'm blind and couldn't see a 'stop downloads' option but if there's no such thing, this is pretty much an essential option that's missing.
Loving the app nonetheless.

**Comment by scb261** [comment]
You can open download queue (`More > Download queue`) and pause/resume/cancel downloads.
