### ISSUE TITLE
[Cover Download Option] <I just wanted to say that, if you could add a manga cover download option it would be a lot better for us weebs to get wallpapers because most people use covers as their wallpapers.>

### ISSUE THREAD

**Issue by Soumaan-dark** [tachiyomiorg/tachiyomi#4712]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

## Why/User Benefit/User Problem
(explain why this feature should be added)

## What/Requirements
(explain how this feature would behave)

**Comment by Soumaan-dark** [comment]
Yes, it's totally worth it.

**Comment by joaoandre120** [comment]
Maybe you should try opening the ticket again, it's worth.
