### ISSUE TITLE
[Bug] <No Pages>

### ISSUE THREAD

**Issue by dtrain45** [tachiyomiorg/tachiyomi#4715]
I have the ReadComicOnline downloaded and it was working perfectly. It wasn't until today that I've had issues with it. Everytime I clicked on a chapter in a comic, it loads on the screen and then it exits off back where I started with all the chapters saying 'no pages found'. I've uninstalled Tachiyomi as well as the extension many times but it hasn't changed yet. I was pretty vexed so I came on here to see if anything can be done because I'll be a very content and happy boy. Thanks!

**Comment by scb261** [comment]
Works for me. Why did you remove the template where you should fill in details about the issue?
