### ISSUE TITLE
[Bug] Copying a manga from one source to another does transfer read chapters, chapter progress and category to the new source

### ISSUE THREAD

**Issue by apav** [tachiyomiorg/tachiyomi#4716]
## Device information
* Tachiyomi version: r3172
* Android version: 11
* Device: Galaxy Note 20 Ultra 5G

## Steps to reproduce
1. Bring up the migrate prompt either by selecting the Migrate button on the manga in the Library tab, or thorough the Migrate tab in the Browse tab. 
2. Select Chapters, Categories, and Tracking then press Copy.

### Expected behavior
Saved data from the source manga should copy over when you select them to.

### Actual behavior
The copied manga from the new source will always appear in your default category without any read chapters and chapter progress transferred from the original. 

## Other details
Tested with different manga using multiple source and destination sources, and the result is the same each time.

**Comment by scb261** [comment]
Should be fixed with 472ce5a

**Comment by arkon** [comment]
Should be fixed in r3185. Please let us know if not.
