### ISSUE TITLE
[Feature Request] When a manga's tracking is updated after reading a chapter, update all manga in library with same tracking ID

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4717]
## Why/User Benefit/User Problem
This comes up from having duplicates of the same manga in the library.
I know it's possible to mass refresh tracking data but it's a manual action and from what I see in MAL's case, it doesn't work that well because it'll timeout after a few manga.

## What/Requirements
When you read a chapter or make a modification on the tracking page, search the entire library for manga with the same tracking ID and update their data to match with the one that was just updated.

**Comment by curche** [comment]
As of v0.10.9, Tracking sheet already fetches the latest tracking info from the tracker when you tap on it

Example:
1. Read a chapter from Manga A in Source 1 (or just manually change it). Check if the tracking data is updated
2. Go to Manga A in Source 2. Tap on Tracking. The new tracking sheet pops up, wait for a while and you get the updated chapter count from the tracking website

If you'd like to do it in bulk for a lot of manga then you have Advanced Settings > Refresh tracking.

**Comment by paulo27ms** [comment]
It's just a lot of manual actions that could be avoided and would avoid headaches with mismatched information or rollbacks.
This is partially because Tachiyomi also takes the wrong approach to updating tracking data and sends everything at once even if you only change the chapter.

This is somewhat related to #1652 but ideally, both things get implemented and you'll never be in a position where your tracking service ends up with wrong information.

**Comment by paulo27ms** [comment]
https://github.com/tachiyomiorg/tachiyomi/pull/5163 is good enough for me for this case.

Would almost close https://github.com/tachiyomiorg/tachiyomi/issues/1652 but I think it's still something that'd improve things and should be added at some point.
