### ISSUE TITLE
[Bug] chapters list takes time load when opening a manga

### ISSUE THREAD

**Issue by Krustcpher** [tachiyomiorg/tachiyomi#4724]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.9)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---

## Device information
* Tachiyomi version: 10.9
* Android version: 8
* Device: HUAWEI

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
in previous versions, chapter list immediately pops up

### Actual behavior
Now it takes a bit to show. ``

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by scb261** [comment]
The info you gave is definitely not enough to understand the issue.

Are you talking about manga in library that already have fetched list of chapters? Is there a difference when a manga has a few or a thousand chapters? How many downloads do you have? Are you using sd card or internal memory for downloads?

Are you talking about browsing new manga on some source? In this case it's your internet or the source you're using, can't be fixed on the app side.

**Comment by arkon** [comment]
Please provide more info. We'll reopen this if you provide enough info for us to action on it.
