### ISSUE TITLE
[Bug] download button in snackbar updates tab

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#4729]
## Device information
* Tachiyomi version: 0.10.9, r3185
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. open updates tab
2. hold tap any chapter
3. press the download button in the snackbar

### Expected behavior
snackbar should disappear

### Actual behavior
snackbar stay

## Other details
snackbar -loo
Action toolbar -tf

<img src="https://cdn.discordapp.com/attachments/349466829212876813/825681177432162324/IMG_20210328_174145.jpg" width="250px">

**Comment by CrepeTF** [comment]
Action toolbar

**Comment by CrepeTF** [comment]
The snack bar is this thing
![IMG_20210328_115003.jpg](https://user-images.githubusercontent.com/70870719/112749681-d0393b00-8fbb-11eb-9601-e9d46d307d9a.jpg)
