### ISSUE TITLE
[Bug] Crop border not work with webtoon reader mode

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi#4734]
## Device information
* Tachiyomi version: preview 3185
* Android version: 10
* Device: galaxy A70

## Steps to reproduce
1. change reader to webtoon
2. click crop border button in reader

### Expected behavior
cropping should happen

### Actual behavior
nothing happen

## Other details
it probably work fine before new update, unsure. but not work now confirm

**Comment by CrepeTF** [comment]
Sounds like a positive for me, crop borders always makes the pages mismatch at the seams
![Screenshot_20210329-105703.jpg](https://user-images.githubusercontent.com/70870719/112820470-89ac1500-907d-11eb-84e5-53035c2ad0b5.jpg)

**Comment by jferdous70** [comment]
try it for regular manga in cont vertical, button have no effect

**Comment by arkon** [comment]
Doesn't seem to take immediate effect in 0.10.9 either.
