### ISSUE TITLE
[Bug] Navigation overlay is always showing

### ISSUE THREAD

**Issue by ghostbear** [tachiyomiorg/tachiyomi#4736]
## Device information
* Tachiyomi version: HEAD
* Android version: Android 11
* Device: Android Emulator

## Steps to reproduce
1. Open any chapter, and navigation overlay will show (even though `Show navigation overlay` is off)

### Expected behavior
Navigation overlay should not show if `Show navigation overlay` is off when opening a chapter (if you are not a first time user)

### Actual behavior
Navigation overlay is showing always

## Other details
Broke with commit 437c995d129b398174e36512f5f180a4602e6e37

This bug is also present in TachiyomiSY (preview build has the commit so users have reported it on Discord), and SY Comics

**Comment by CrepeTF** [comment]
SY Comics too

**Comment by arkon** [comment]
This is fixed locally.
