### ISSUE TITLE
[Bug] disabling Dual Page Split mode while in Reader duplicates pages

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#4738]
## Device information
* Tachiyomi version: Sy Preview r348
* Android version: 10 (Lineage OS)
* Device: Redmi 7 onclite

## Steps to reproduce
1. Find a manga with double page spreads (any old manga scans/rips would do, eg Veritas)
2. Open manga chapters to see if double page spreads exist
3. Enable dual page split
4. Check if pages are split
5. without exiting the Reader, disable dual page split

### Expected behavior
Pages should be as in Step 2.

### Actual behavior
Pages are duplicated

## Other details
This is likely because the reader creates new screens for placing split pages and when the option is disabled, those arent deleted
Perhaps destroying the reader and making a new one would fix this but unsure whether it helps

Video attached

https://user-images.githubusercontent.com/72807749/112849492-c18b7a80-90c6-11eb-887c-e26787026d04.mov

**Comment by CarlosEsco** [comment]
Did you verify it is also broken in the main app?

**Comment by ghostbear** [comment]
It doesn't remove the insert page so yes it a bug

**Comment by curche** [comment]
checked in r3185: bug also exists there

shouldve checked it beforehand and also added that in App version, my bad.
