### ISSUE TITLE
[Feature Request] <If you can add an extension of comics in Spanish and English>

### ISSUE THREAD

**Issue by KOOL4** [tachiyomiorg/tachiyomi#4740]
Hello I hope you are well, I have followed this project for more than 1 year and it is very good but I have seen on the web that there is no comic app, there is only manga and an extension of said content would be good for your project comics like marvel, dc .etc here are some links to some pages that could be used for the extension

In Spanish: - https://leercomicsonline2.blogspot.com/ (the most complete of the others)
-https: //tiocammoi.com (Only for download)
-https: //comicpedia.blogspot.com
-https: //issuu.com/tiodc21
-https: //issuu.com/jorgedominguez78
-https: //issuu.com/todo.marvel.comics
In English -http: //xoxocomics.com

I hope you can do the extension, and I apologize for English, I am Spanish-speaking
I send you a big greeting

**Comment by DarremMolko** [comment]
Hola. Los pedidos de extensiones se realizan en este otro repositorio:
https://github.com/tachiyomiorg/tachiyomi-extensions
Por cierto, hace un tiempo hice un pedido similar y me dijeron que no es fácil hacerle scraping a los blogs de blogspot, puedes leer más aquí:
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/1883
En cuanto a extensiones de cómics en inglés, hay varias, ahora mismo se me ocurren ReadComicOnline y ComicExtra.
