### ISSUE TITLE
Bug ongoing/completed manga

### ISSUE THREAD

**Issue by nchagnet** [tachiyomiorg/tachiyomi#4743]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Samsung Tab S6

I have some ongoing mangas for which AniList seems to know how many chapters there are (for some the chapter number is a "free" field, for others it's bounded). The issue is when I catch up to the mangas, the tracking automatically sets the mangas as completed (since it detects I have read everything). Now that seems like a feature and I don't mind it, my issue is that I can't manually override it. Setting it back to reading doesn't work.

**Comment by CarlosEsco** [comment]
Can you check anilist and make the chapter bound is correct?  Usually they only set it when a manga has a known final chapter. 

The app keeps marking it complete because anilist is telling it that that's the last chapter of the manga

**Comment by arkon** [comment]
This app doesn't change the status IIRC, but Anilist itself does.

**Comment by nchagnet** [comment]
Yes you are right, it seems to be an issue of anilist itself which considers this manga finished somehow.

Thank you for your assistance!
