### ISSUE TITLE
[Bug] Migrating comics from one source to other causes all the chapters to appear in the updates section of the app

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4744]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Galaxy S9+

## Steps to reproduce
1. Read comic up to a couple dozen chapters
2. Migrate it to a different source

### Expected behavior
App migrates all information to another source properly.

### Actual behavior
Information is migrated properly but all chapters available in the comic show up on the updates section. (Check SC below for better understanding)

## Other details
![Issue image](https://user-images.githubusercontent.com/30620767/112936337-52497100-912e-11eb-9d52-de238e0ff21d.jpeg)

**Comment by scb261** [comment]
Duplicate of #4732

Are you sure you're using 0.10.9?

**Comment by rsmyst** [comment]
> Duplicate of #4732
> 
> Are you sure you're using 0.10.9?

Yup. I'm sure of it. Checked it again too

**Comment by scb261** [comment]
0.10.9 shouldn't show all chapters unless the new source recently uploaded all chapters. In r3185 it became even worse, because now it shows all chapters regardless of upload date. Anyway, the issue is a duplicate and should be closed.

**Comment by rsmyst** [comment]
Oh ok. As long as someone is aware... This issue has persisted since i downloaded tachiyomi 2-3 months back too
