### ISSUE TITLE
[Bug] Reader missing page number 

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#4746]
## Device information
* Tachiyomi version: 0.10.9, r3185
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. change reader to webtoon/cont vertical
2. open manga with long page 1/current one (page need to be longer than screen)

### Expected behavior
can see page number

### Actual behavior
only can see page number if scroll to another page

## Other details
https://streamable.com/84geyn

**Comment by arkon** [comment]
This might be fixed by 5f0493f1e55634471414b1369e2e1b8a1b56c656

**Comment by Riztard** [comment]
yes, that fixed the issue
