### ISSUE TITLE
[Feature Request] Extension install/update improvements

### ISSUE THREAD

**Issue by elitearmedforce** [tachiyomiorg/tachiyomi#4748]
First of all, thank you for the app, big respect. Made anime readers life easier. I hope this makes dev reader happy.

First of all, the app is updated to the latest. I wasn't sure where to post this here or on extension github repo page. This is more of app problem I believe, as the app installs/updates/removes the extension. I even believe this problem is faced by other users too. I didn't update my extension, to show the problem.

**Starting with the problem:**
- Installing multiple extension is a huge hassle. Presently, I have to click each and every extension install button and I am sure install speed for each extension is really slow. Imagine this for 20+ or 100+ extensions. It's like installing 20 apps in row, even installing a single app itself is slow. (screenshot attached)
![WhatsApp Image 2021-03-31 at 02 06 18](https://user-images.githubusercontent.com/61043834/113063410-51fcb480-91c6-11eb-9276-19b5a625ccc7.jpeg)
- Now imagine the same situation to remove like 20 extensions.
- Same thing goes for updating 100+ extensions.
![image](https://user-images.githubusercontent.com/61043834/113066271-4cee3400-91cb-11eb-97c5-01d1f307f228.png)
Problem conclusion: It is a really slow process for anything as Tachiyomi app installs/update/remove extension like an app instead of packages(suggestion/solution is also mentioned below, screenshot attached)

**Solution:**
I believe u have used Google Maps app, where u can download offline portion of map. Here the portion of the map gets download as packages. Which can be updated in one click of a button as it gets expired, sometimes it gets updated automatically as per the setting.
![InkedWhatsApp Image 2021-03-31 at 01 32 53_LI](https://user-images.githubusercontent.com/61043834/113060732-1829af00-91c2-11eb-975e-99b963ca8896.jpg)
Another example but I don't have a screenshot, in Real Racing 3(android game) the base app is downloaded first and then extra cars and locations assets can be downloaded later with a click of a button. Or auto-downloads cars that are only needed for a location I am playing.
Coming to the point for Tachiyomi app, the extensions can be installed as a package instead of app like installation thingy(screenshot attached). When I click install, it installs without a pop like this (screenshot above, installation popup), just downloads in background and once downloaded a user interface feedback with a tick ✔ sign
![image](https://user-images.githubusercontent.com/61043834/113064776-bfa9e000-91c8-11eb-82af-e48f23ecf024.png)
After updating all extension:
![image](https://user-images.githubusercontent.com/61043834/113065345-c38a3200-91c9-11eb-8926-e245a9f3b532.png)
I tried to make immediate medication using felegoo, to show some examples on what I mean. 

## User Benefit
Makes life convenient in using ur app. I am definitely sure, I am not only that wants this feature.

Thank you for ur work, keep up the good work coming. Once again love the app and ur work.

**Comment by arkon** [comment]
The most we can do is adding the ability to download the APKs as a separate step so that they can be batch downloaded.

Android apps cannot be automatically installed without user interaction (the pop-up you're referring to) unless you have root permissions or a privileged system app like the Google Play Store.

**Comment by elitearmedforce** [comment]
@arkon thank you for going through that long msg.
> Android apps cannot be automatically installed without user interaction (the pop-up you're referring to) unless you have root permissions or a privileged system app like the Google Play Store.

I know that user interaction is required to install outsource apps. That's why I suggested the extensions apps can be converted to packages instead as a separate app(i hope u understood this statement, to understand the concept), as this won't require any extra user interaction to install extension, just with a click of one button (update all), it will update all extensions.

> The most we can do is adding the ability to download the APKs as a separate step so that they can be batch downloaded.

Don't mind, but I believe u didn't understand my point(i think so). 

If u still don't understand what I meant, I can explain it by showing more examples or we can talk about this in discord?

**Comment by arkon** [comment]
Maps and game assets are typically just data assets. Extensions are arbitrary Android-compatible code that needs to get loaded and executed.

We could potentially shift to a way that doesn't require installations for a majority of them (which is what's happening in the current version of the 1.x rewrite), but anything that requires app-level manifest things like URL handlers have to be installed as "proper" apps. We haven't actually really thought about how to handle the UX of that, since some extensions would seemingly just load without any effort, while some still require user interaction.

If you're suggesting moving away from the Android app code paradigm entirely, that's very unlikely to happen, as it's how most extensions are even able to achieve most of their functionality without the need for us to somehow embedded some sort of interpreter.

**Comment by elitearmedforce** [comment]
> Maps and game assets are typically just data assets. Extensions are arbitrary Android-compatible code that needs to get loaded and executed.

Now I get it. That is why it is like this.
> We could potentially shift to a way that doesn't require installations for a majority of them (which is what's happening in the current version of the 1.x rewrite), but anything that requires app-level manifest things like URL handlers have to be installed as "proper" apps. 

I understand now,
> If you're suggesting moving away from the Android app code paradigm entirely, that's very unlikely to happen, as it's how most extensions are even able to achieve most of their functionality without the need for us to somehow embedded some sort of interpreter.

No, I didn't mean that. I was just suggesting to improve user experiences, now I understand why it is this way.

> The most we can do is adding the ability to download the APKs as a separate step so that they can be batch downloaded.

I am not sure what is the best approach. All I can do is suggest. If you think this way can solve the problem, why not, am happy to accept it.

Once again thanks, keep up the good work coming,
