### ISSUE TITLE
[Bug] Spontaneous Crashing

### ISSUE THREAD

**Issue by 98ne** [tachiyomiorg/tachiyomi#4751]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 8.0
* Device: LG V20 (H918)

## Steps to reproduce
1. Use the app normally/leave it running in the background.

### Expected behavior
No crashes.

### Actual behavior
Spontaneous crashes-- they could occur in the middle of reading a manga, while browsing the app, or while letting it run in the background. I'd say it crashes about 1-3 times per day.

## Other details
These crashes have been happening for the past few months (at least 4) over the various stable builds of the app, on the preview builds, as well as on TachiyomiSY.

Countless uninstalls/reinstalls and system (factory) resets do not seem to help, and, unfortunately, I cannot seem figure out the steps to reproduce the crashes consistently.

No crashes occur on my other device, an LG V35 (ULM) running Android 9.0. Might be hardware/OS related? Not sure.

Anyway, I've attached the crash logs since my last reinstall of the app (about a day or two ago). Hopefully they could help shed some light into the issue.

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6239380/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Looks like the Chrome/WebView issue from around a week ago. Have you not updated those apps yet?

**Comment by arkon** [comment]
The only info in that crash log file is some instance of Chromium crashing. ¯\\\_(ツ)_/¯
