### ISSUE TITLE
[Feature Request] Import and Export Download Queue

### ISSUE THREAD

**Issue by wruizcanal** [tachiyomiorg/tachiyomi#4757]
## Why/User Benefit/User Problem
(explain why this feature should be added)
This new feature allows you to export and import the download queue to be able to create a download queue of the comics you want, export the queue and then import it to another device that may have a higher connection speed or not be for mobile data.  Later you can copy the downloaded comics to your original device that you use to watch comics.

Example: I live in Cuba and the connection is very expensive.  So I have an Android emulator with Tachiyomi on my work PC where I download the comics I want at night and the next day I copy everything downloaded to my mobile where I see the comics.  This is easy when it is a new comic but when I have to update a lot of comic it is very problematic.  If this option exists, I just have to create a download list on my phone and export it to the PC very easily to download it.  The comics don't even need to be in the Tachiyomi library on the PC.  You just have to have the same extensions.

## What/Requirements
(explain how this feature would behave)
You just need to add the import and export option in the download queue menu and save the exported file in the same way as for the migration.

**Comment by arkon** [comment]
The download queue isn't transferrable if your database contents aren't the same, so this isn't possible.
