### ISSUE TITLE
[Feature Request] Backup Extesions

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#4760]
## Why/User Benefit/User Problem
If we had the possibility to choose to also backup the extension and its information, it would make the installation of Tachiyomi on another device way easier.

## What/Requirements
An option on the settings to allow the user to backup the extensions (installed, actives and pinned), so when we restore it, it installs then again, or prompt us to choose which of them reinstall.

**Comment by arkon** [comment]
Backups already contain info about what sources are used in your library. The backup restore system can't install apps for you.
