### ISSUE TITLE
[Bug] Cant connect to manga after public IP Change

### ISSUE THREAD

**Issue by xx255q** [tachiyomiorg/tachiyomi#4761]
## Device information
* Tachiyomi version: ? 0.10.9
* Android version: ? 11
* Device: ? Pixel 3

## Steps to reproduce
1. First step connect to a manga with original public ip
2. Second step try to read again after public IP change

### Expected behavior
This should happen. you can still read

### Actual behavior
This happened instead. it says can not connect and it list original ip

## Other details
Additional details and attachments.

Uninstalled tachiyomi and the extension and error is still there

**Comment by xx255q** [comment]
It was filled out

**Comment by arkon** [comment]
You can't leave the question marks.

**Comment by arkon** [comment]
But also, restart your router and/or phone.

**Comment by xx255q** [comment]
I have already restarted my router and just now I did my phone still says failed to connect to original public ip

**Comment by xx255q** [comment]
I need a way for the app to forget the original connection so it can remake a new one with the current ip

**Comment by arkon** [comment]
I'm confused, which IP is changing? Yours or the source's?

**Comment by xx255q** [comment]
well, both my and source ip is the same since we are in the same home. So the source public IP changed and all the manga I read before with that previous IP can no longer be read because if I try it gives that error of failed to connect to (Orginal IP)

**Comment by arkon** [comment]
Try getting more support on our Discord (link is in the README). I feel like there's too many missing details here to really understand what your issue is, and we don't really do this kind of support in GitHub issues.
