### ISSUE TITLE
[Bug] tachi crashes after few minutes

### ISSUE THREAD

**Issue by SamSensei** [tachiyomiorg/tachiyomi#4763]
After launching Tachiyomi after few minutes it automatically crashes , can't find pattern to what causes crash.
Uninstalled webview & Chrome , updated them to latest version , still the same issue

I have attached crash log for more info

## Device information
* Tachiyomi version: 0.10.9
* Android version: 7.0
* Device: Redmi Note 4X , code name : Mido

Crash log : https://drive.google.com/file/d/1lCc5F8fGTtHFJEsPM0CjUdvUnJ_kten8/view?usp=sharing

**Comment by arkon** [comment]
That file doesn't have anything useful.

Potential ways of getting more logs:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by SamSensei** [comment]
Crash is random , don't know what causes it , and re-launching after crash tachi works fine.
Crash happens when i left my phone for quite sometime and later run Tachiyomi and then it crashes after few seconds.
Issue might be related with miui battery optimisation but chances are less because it didn't happen before tachi 0.10.6 (can't confirm version).
Ran logcat(root) and tachi still hasn't crashed yet.
Pocket log - can't take it missing option "take crash log" in developer options.
Will update if logcat records the crash log.

**Comment by SamSensei** [comment]
After disabling "MIUI Optimization" Tachiyomi hasn't crashed since a day has passed.
Must be due to some miui functions.
Closing issue.
