### ISSUE TITLE
[Feature Request] manga commentary feature

### ISSUE THREAD

**Issue by ketek-kuda** [tachiyomiorg/tachiyomi#4767]
## Why/User Benefit/User Problem
because I like to see comments and reviews from other readers because from these comments and reviews I can choose and determine whether the manga is good or not for me and I also like to comment on manga that I read in the comments column because I hope that there is a comment feature in the tachiyomi application.

User benefit
can comment and discuss about manga in the comments column. and sites that work on the manga can find out whether the manga project is in great demand by readers or not Because usually a site works on a manga based on the number of enthusiasts and usually a site knows the number of enthusiasts through comments and likes from readers.

## What/Requirements
commented on every manga title and manga chapter

Note : sorry if the English that I speak is not clear because I use google translate and I can not speak English

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4336
