### ISSUE TITLE
[Bug] <Mangalib HTTP ERROR 403>

### ISSUE THREAD

**Issue by GraYGaY1234** [tachiyomiorg/tachiyomi#4768]
When I refresh manga
manga from Mangalib doesn't refresh
And I see HTTP ERROR 403

**Comment by WiNE-iNEFF** [comment]
Everyone I asked has the same problem. Tried to include DNS over HTTPS, but problem did not disappear. I also checked it using the webview and the site works fine, no protection from cloudflaer

**Comment by curche** [comment]
Wrong repo
Already reported at https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6376
