### ISSUE TITLE
[Feature Request] WebView for chapter link

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#4770]
## Why/User Benefit/User Problem
i will lot easier to check, because most of the issues would need to check chapter in webview
like page issue

## What/Requirements
hold tap chapter, if chapter selected only 1, show webview icon to open

**Comment by arkon** [comment]
I think this is feasible now with the addition of `getChapterUrl` in `HttpSource`?

**Comment by d-najd** [comment]
> I think this is feasible now with the addition of `getChapterUrl` in `HttpSource`?

yep shouldn't take more than a few hours, I will look into this.

**Comment by Riztard** [comment]
only in reader? wer in manga pages?

**Comment by d-najd** [comment]
> only in reader? wer in manga pages?

seems like a nieche feature to me, and more importantly where would you even put such button?

**Comment by Riztard** [comment]
> > only in reader? wer in manga pages?
> 
> seems like a nieche feature to me, and more importantly where would you even put such button?

`hold tap chapter, if chapter selected only 1, show webview icon to open`

**Comment by d-najd** [comment]
> > seems like a nieche feature to me, and more importantly where would you even put such button?
> 
> > `hold tap chapter, if chapter selected only 1, show webview icon to open`

if you mean having button with the same functionality in the bottom bar, then you could have 6 buttons on the bottom bar at one time which can get anoying especially on devices with small width.

if you still like there to be a button there I tried to do it like that the at first so the code is there you only need to restore

**Comment by arkon** [comment]
I think it's fine without it. We don't have WebView shortcuts for entries from the library screen either.
