### ISSUE TITLE
[Feature Request] Chapter Stacking

### ISSUE THREAD

**Issue by exaltedcelestial** [tachiyomiorg/tachiyomi#4772]
## Why/User Benefit/User Problem
There are some very good manhuas/manhwas that release few pages per chapter. So if there's like a snooze for the series, then we could binge read after a certain amount of new chapters have been uploaded.

## What/Requirements
- As a user, I would like to long press on a series then select **stack** or **snooze** option
- After clicking stack or snooze, I would then input the number of chapters to stack before giving me a notification about it
- Once a series is snoozed, for _i.e_ 10 chapters, if the user updates the library and the series in question retrieves 3 new updates, the 3 new chapters won't go to the **updates** tab, instead, after the number of new chapters reaches 10 chapters, that would be the time it shows up in the **updates** tab

**Comment by arkon** [comment]
Too complex to be worth it, just use unread badges or something.
