### ISSUE TITLE
[Bug] Mangalib.me Error 403 doesn't work! 

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4774]
Mangalib hasn't been working for more than 5 days! Are you going to decide? 
---

## Device information
* Tachiyomi version: 0.10.9
* Android version: 9
* Device: honor 9 lite

## Steps to reproduce
1. Just update the manga list 

### Expected behavior
Long-awaited manga update

### Actual behavior
No update and IS REPORTED 403

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by Riztard** [comment]
> - If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

wrong place, next time read the instruction
