### ISSUE TITLE
[Feature Request] "Refresh Tracking" upon Successful Restore

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#4775]
## Why/User Benefit/User Problem
Continuing from #4504, now that restore doesn't update tracker information (thus, completely offline), there is a need  to use "Refresh Tracking" from Advanced Settings to ensure uptodate tracker data

## What/Requirements
Add an action to the notification that does "Refresh Tracking"
A quick and dirty mockup below

![tachi-restore-success-mockup-metadata](https://user-images.githubusercontent.com/72807749/113520101-74b81000-95ae-11eb-8800-6f5be6a44b81.png)

## Other Details
Note that the button could be needed only after successful restore. In case of Errors, the option may be skipped or maybe added besides the "Open Error Log" option

**Comment by CarlosEsco** [comment]
Unless it wasn't added yet, clicking into the manga should refresh the tracking now

**Comment by curche** [comment]
Yeah, currently a refresh occurs when you click the Tracker for a particular Manga
However, after a restore, you will have to do it for each manga manually
That is fine and all but I felt that since we already have `Refresh Tracking` under Advanced Settings, a quick button in Notification to trigger that after a successful restore could prove useful to many
