### ISSUE TITLE
[Bug] Reset scans extension not showing manga

### ISSUE THREAD

**Issue by Khan-MC** [tachiyomiorg/tachiyomi#4776]
---

## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: 11
* Device: Samsung Galaxy M21

## Steps to reproduce
1. Go under Browse
2. Click on Reset Scans extension

### Expected behavior
Should show manga

### Actual behavior
Says "Timeout"

## Other details
![Screenshot_20210405-133219_Tachiyomi](https://user-images.githubusercontent.com/80331492/113553357-7965de00-9619-11eb-8f2b-4048dc35d4f8.png)

**Comment by Seishirou101** [comment]
you're in the wrong repo. please read the template that you acknowledged.
