### ISSUE TITLE
Manga downloaded to SD card becomes corrupted

### ISSUE THREAD

**Issue by DragonMage899** [tachiyomiorg/tachiyomi#4778]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: Android 6.0.1
* Device: Redmi 4A

## Steps to reproduce
1. First step
Set download location to SD card
2. Second step
Download Manga

## Issue/Request
Chapter folder corrupts once the download of the chapter completes in app.
(Folder appears as a 0kb file once the download completes)

## Other details
I have tried multiple sources and all bear the same result (Though it's not consistent for all chapters. A few chapters are viewable while others appear as a black screen)
Every time I attempt to download a manga the folder is created for the manga and the images begin to download (viewable in file manager) However once the download completes the chapter folder turns into a 0kb file with no extension.
This is not true for all chapters however chapters that show this behavior don't seem to recover even after reinstalling the app and remounting my SD card.
Moving my download location to my internal storage does fix this problem but there's not much space on there so downloading in bulk is not an option.
I have tried creating a new folder on the SD using tachiyomi for my downloads but it didn't work.
(The number of pages could be an issue as I've tried downloading a few extra chapters which only contain ~3-12 pages from different manga and none of them have corrupted
Sources I mainly use: MangaLife, MangaHub)

I'm not really sure what else to do
Help would be appreciated 

Screenshots
![Screenshot_2021-04-05-17-31-58-871_eu kanade tachiyomi](https://user-images.githubusercontent.com/65770411/113593086-49790380-9636-11eb-8700-cb1acab4a8f0.png)
![Screenshot_2021-04-05-17-32-07-194_com mi android globalFileexplorer](https://user-images.githubusercontent.com/65770411/113593099-4c73f400-9636-11eb-8799-7a82414112ee.png)
![Screenshot_2021-04-05-17-33-27-595_eu kanade tachiyomi](https://user-images.githubusercontent.com/65770411/113593101-4d0c8a80-9636-11eb-9480-18aa073c2de4.png)
![Screenshot_2021-04-05-17-33-39-189_eu kanade tachiyomi](https://user-images.githubusercontent.com/65770411/113593103-4d0c8a80-9636-11eb-8ddc-7826e9eb1d54.png)
![Screenshot_2021-04-05-17-33-43-392_eu kanade tachiyomi](https://user-images.githubusercontent.com/65770411/113593106-4da52100-9636-11eb-8eea-31b145fc06d4.png)
![Screenshot_2021-04-05-17-33-46-644_eu kanade tachiyomi](https://user-images.githubusercontent.com/65770411/113593107-4e3db780-9636-11eb-9654-2b3f461c37ab.png)
![Screenshot_2021-04-05-17-33-57-067_com mi android globalFileexplorer](https://user-images.githubusercontent.com/65770411/113593108-4ed64e00-9636-11eb-8970-71a4057bd309.png)

**Comment by arkon** [comment]
There's a fairly good chance that your SD card is borked.

**Comment by DragonMage899** [comment]
> There's a fairly good chance that your SD card is borked.

SD card is pretty new so I doubt it and I'm only having problems with tachi. My initial thought was a permission problem that as not all manga get corrupted I doubt it's this.
Though it could be a possibility, I'll try to experiment more

**Comment by curche** [comment]
> Moving my download location [from sdcard] to my internal storage does fix this problem
> Sources I mainly use: MangaLife, MangaHub

Could be due to the file names or the file formats of the manga chapters. check what filesystem your sdcard is running on (eg FAT32, NTFS, ext4, etc). Also try on other sources. 
As last resort, perhaps try downloading the manga chapters externally (using a PC) and set it up as [Local Manga](https://tachiyomi.org/help/guides/reading-local-manga/) on your sdcard to see if it works

If you don't face the issue currently, consider closing the issue instead.

**Comment by DragonMage899** [comment]
> > Moving my download location [from sdcard] to my internal storage does fix this problem
> > Sources I mainly use: MangaLife, MangaHub
> 
> Could be due to the file names or the file formats of the manga chapters. check what filesystem your sdcard is running on (eg FAT32, NTFS, ext4, etc). Also try on other sources.
> As last resort, perhaps try downloading the manga chapters externally (using a PC) and set it up as [Local Manga](https://tachiyomi.org/help/guides/reading-local-manga/) on your sdcard to see if it works
> 
> If you don't face the issue currently, consider closing the issue instead.

(Downloading the chapters on bluestacks and copying it over does work.)

I am able to get the chapters working by force closing app and restarting my phone, though the issue still persists. I'll close the thread, thanks for the help!
