### ISSUE TITLE
[Feature Request] <ability to detect whether there is an sd card, and give the option when downloading manga to download to the sd card, with the ability to choose a new folder or have the app create one for you>

### ISSUE THREAD

**Issue by Xellerate005** [tachiyomiorg/tachiyomi#4781]
## Why/User Benefit/User Problem
(Because of convience, i know that some mangas can take up a lot of storage, so instead of downloading to internal storage you could download to the sd card, but the main problem is that its inconvient because you have to always go to the settings to change, so doing this would make it easier, instead of having to change it back when your free of space)

## What/Requirements
(First when you put your sd card in nothing will happen, but when you open the app, it will scan for folders, including sd, nothing will actually happen, but it will then unlock the option to download manga to sd card from the download icon, so instead of going to settings to change the download location, you can just tell the app to download to the sd card for that specific  and if left unspecified it will download to the internal storage, and thats it
It may not be much of a change, but it will definitely be better than constanly going to the settings and changing over and over again, and plus if you do it this way you can read from both the sd card and the internal storage)

**Comment by CrepeTF** [comment]
Why would you not just use 1 folder downloads

Also rip for Android 11

**Comment by Xellerate005** [comment]
> Why would you not just use 1 folder for downloads
> 
> Also rip for Android 11

If your low in space you can download to the sd card, i dont know about other people, but i get through manag fast

**Comment by CrepeTF** [comment]
Just set the download location to your SD card permanently and transfer existing downloads from internal to SD

**Comment by arkon** [comment]
There's no plans to support multiple download locations as it'd make it much more complex.

If you want to use your SD card, then point to that.

**Comment by Xellerate005** [comment]
But you also have limited space on a sd card, plus i use my sd card for other things, that's why
