### ISSUE TITLE
[Bug] Tachiyomi get restarted in multitasking

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi#4783]
When you are on a server for example Ninemanga and you change the application, (multitasking) when you return to Tachiyomi the server restarts, that is, if you were browsing at a certain point or manga it does not remain there, also the filter button disappears and you have to leave the server and enter again  so that it reappears.

It could be assumed that my kernel's LKM (low memory killer) module is too aggressive and that is why tachiyomi restarts, but apart from tachiyomi no other app has this problem so I don't think it's due to lkm

**Comment by arkon** [comment]
The app can be a bit memory intensive with all the images, so I could imagine low-memory devices being aggressive with killing it earlier. 

Also try https://dontkillmyapp.com/
