### ISSUE TITLE
[Bug] " No Page Found " on tsumino downloaded chapter

### ISSUE THREAD

**Issue by yooman1213** [tachiyomiorg/tachiyomi#4794]
---

## Device information
App version: 1.5.0 (standard, 3bf070d88, 13)
Preview build: 351
Android version: 11 (SDK 30) 
Android build ID: RP1A.200720.012.G988U1UES1DUBA
Device brand: samsung
Device manufacturer: samsung
Device name: z3q
Device model: SM-G988U1
Device product name: z3quew

## Steps to reproduce
After downloading a certain manga the downloaded chapter appears " No page Found " , when checking the downloaded files its there and the content is present it appears the downloaded chapter is in .bin file instead of .png file so that the app cannot read

Current workarounds that i use is to change the .cbz file into zip and use WinRar app to rename each file

Can it be fix? 

## Other details
Here are some detailed screenshoot from downloaded manga files

![Screenshot_20210408-022213_My Files](https://user-images.githubusercontent.com/67755845/113922286-530a9300-9811-11eb-8fab-8e39405971dd.jpg)

The manga name from tsumino is Yorita Yoshino to Yashiro no Hikage de / 依田芳乃と社の日陰で 

for anyone like to try it

In that image the is a manga just Recently uploaded by the tsumino and its downloaded as .bin file instead of .png file

**Comment by arkon** [comment]
This isn't the TachiyomiSY repo.

**Comment by yooman1213** [comment]
Sorry wrong section
