### ISSUE TITLE
[Bug] Page colors become inverted with dark theme and 32-bit colors

### ISSUE THREAD

**Issue by DenisSamilton** [tachiyomiorg/tachiyomi#4795]
## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: 11
* Device: Xiaomi Mi 11

## Steps to reproduce
1. Set dark theme on device 
2. Enable 32-bit colors in Tachiyomi reader
3. Open "Guran Buru" or "Chang Ge Xing" manga via Mangalib or Readmanga extension (Could be also reproduced on other manga and extensions) 

### Expected behavior
All pages should be normal. With white background and black text and illustrations (except the colored one) 

### Actual behavior
Some pages (~40%) became inverted on colors. Background became black and text with illustrations became white

## Other details
If I disable dark theme on device and left 32-bit color enabled in app, the pages will became back to normal colors. 
If I disable 32-bit color in app and left enabled dark theme on device, the pages will became back to normal colors

## Screenshot
![Screenshot_2021-04-08-02-53-51-903_eu kanade tachiyomi](https://user-images.githubusercontent.com/22996142/113950203-6faac900-9819-11eb-9b94-d81aeccffff4.jpg)

**Comment by arkon** [comment]
I'm like 95% sure this is just Xiaomi's horrible dark mode system.

**Comment by DenisSamilton** [comment]
Didn't have any other device to test this in dark theme, but yeah, could be. But for now, this is the only app that I have, that have problem with dark theme. I wonder why disabling 32-bit also fix this problem. Of course I can disable it use like that, but... Sad story😒

**Comment by arkon** [comment]
Potentially fixed in next release. If not, I have no idea how to address this.
