### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by loathelife** [tachiyomiorg/tachiyomi#4800]
I have been using the app all day bookmarking my favorite comic's. Then the app crashed. Afterwards "page not found" the extension are readcomicsonline. I have reinstalled the app five times, cleared my cache multiple times. That extension is working. I was gonna get rid of the app itself. Then I found here. Please help!

**Comment by arkon** [comment]
Please follow the issue template instructions and fill it out appropriately if applicable.
