### ISSUE TITLE
[Bug] Unable to Save Images From Manga With Reserved Characters in Their Titles

### ISSUE THREAD

**Issue by atrhioan** [tachiyomiorg/tachiyomi#4803]
## Device information
* Tachiyomi version: Preview r351 (3b070d88)
* Android version: 11
* Device: Google Pixel 3 XL

## Steps to reproduce
1. Press and hold page
2. Press save

### Expected behavior
Page saved to device in a folder under the manga's name

### Actual behavior
App creates a folder under the manga's name but throws an error without saving anything to it

## Other details
The issue seems to be caused by Tachiyomi creating folders for manga with reserved characters in their titles (e.g. the ":" in the title "Kaguya-sama: Love is War"), making them inaccessible to the device and subsequently unable to save images. Tested by removing the reserved character from the title of the manga, which allowed it to save images normally.

**Comment by antocs** [comment]
I have the same problem, got sent here to send my info.
Device Samsung Galaxy S10, Android 11, app to the latest version (preview r3218), file manager updated, the default one on android.

I also had the problem with renaming the Mangasee folder to MangaSee, I had to delete the folder and let the app make it anew downloading chapters.
