### ISSUE TITLE
<Bug>擴展源禁漫天堂的下載副檔名

### ISSUE THREAD

**Issue by lonely854** [tachiyomiorg/tachiyomi#4804]
使用環境： S9
儲存位置：SD card
下載下來的檔案非圖檔，
儲存為.bin 使其不能在APP打開
![Screenshot_20210410-112302_My Files](https://user-images.githubusercontent.com/82249984/114257037-bf42ed80-99ef-11eb-95c8-e95f8c80697e.jpg)
![Screenshot_20210410-112225_Tachiyomi](https://user-images.githubusercontent.com/82249984/114257044-c5d16500-99ef-11eb-8b2d-ec2748f24096.jpg)

**Comment by arkon** [comment]
Downloads as JPGs for me.

Note to self, we can probably check for the Content-Type header here too: https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L433

**Comment by lonely854** [comment]
找到原因了 SD card上建立的根目錄資料夾不能為中文
謝謝

**Comment by arkon** [comment]
Maybe I'm going crazy, but my email says the OP said:

> 找到原因了 SD card上建立的根目錄資料夾不能為中文
> 謝謝
