### ISSUE TITLE
[Feature Request] Animation For "Update Library"  button

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#4806]
Animation For "Update Library" Button 
(Do it Like the Download Button) 

![Screenshot_20210411_080950](https://user-images.githubusercontent.com/65703094/114287942-e526cb80-9a9d-11eb-9a11-6a34570d27f8.jpg)

And I realized That The Only way To cancel the Update is To Cancel It at The notif Bar (Add Cancel Like the "Download Button") 
![Screenshot_20210411_080815](https://user-images.githubusercontent.com/65703094/114287997-477fcc00-9a9e-11eb-9f10-d17188c42d36.jpg)

**Comment by arkon** [comment]
The notification serves that purpose though.
