### ISSUE TITLE
[Feature Request] Improved crop for dual pages.

### ISSUE THREAD

**Issue by burner8557** [tachiyomiorg/tachiyomi#4807]
Sometimes there will be a white bar separating the 2 pages. An extra option to remove this would be appreciated. Example below.
![Screenshot_20210430-215637_Tachiyomi](https://user-images.githubusercontent.com/82297026/116767752-302e6180-aa00-11eb-912d-1735ae69a365.jpg)

**Comment by arkon** [comment]
Crop borders is already a thing. Did you mean something else?

**Comment by burner8557** [comment]
yeah, on dual pages sometimes they will have a white bar separating the 2 pages. if you look at a double page on mangasee berserk you can see what i mean.

**Comment by arkon** [comment]
I'm assuming the page you're referring to is actually a single image served by the source? We can't do much about it for that kind of issue.

That seems to be the case for page 8 of chapter 1 of Berserk on Mangasee anyway.
