### ISSUE TITLE
[Bug] Webview now shows pop-up ads

### ISSUE THREAD

**Issue by NcReality** [tachiyomiorg/tachiyomi#4809]
## Device information 
* Tachiyomi version: Latest from stable 
* Android version: 10
* Device: Huawei P smart 2019

## Steps to reproduce
1. First step: Open any Manga in Webview on Manganelo or Mangakakalot
2. Second step: Click on a chapter

### Expected behavior
Integrated ads are ok. Pops up not

## Other details
Additional details and attachments.
![Screenshot_20210411_155157_eu kanade tachiyomi](https://user-images.githubusercontent.com/78872698/114307204-eb896780-9ade-11eb-96b7-48f30a31a954.jpg)
 
Issue still remains after deep cleaning the device and clear cache, cookies, history etc.

**Comment by arkon** [comment]
Then don't visit a site with intrusive ads...

**Comment by MercerBoi** [comment]
I think this post is implying that an ad-blocker should be added to webview lol

**Comment by CrepeTF** [comment]
~~We don't own webview~~

**Comment by NcReality** [comment]
Apparently reinstalling Tachiyomi fixed the issue.
Sry if I caused any confusion. This never happened before so I didn't know what to do.
I wish y'all a great weekend
