### ISSUE TITLE
[Bug] <Can open chapter, shows "Case sensitivity relies on underlying file system"

### ISSUE THREAD

**Issue by Evineit** [tachiyomiorg/tachiyomi#4813]
## Device information
* Tachiyomi version: stable 0.10.10
* Android version: 9
* Device: moto g(6) play

## Steps to reproduce
1. Press resume button or any chapter

### Expected behavior
Display the chapter in the reader

### Actual behavior
Shows "Case sensitivity relies on underlying file system", a transition blue background and returns to the chapter list.

## Other details
![Screenshot_20210411-172417](https://user-images.githubusercontent.com/46513310/114323594-838d4e00-9aeb-11eb-9f75-0917d65c4ef0.jpg)

**Comment by CrepeTF** [comment]
New update was pushed, update again by installing the latest release in GitHub

**Comment by arkon** [comment]
Please try downloading and installing (the new and improved iteration of) v0.10.10 over your existing version: https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.10.10/tachiyomi-v0.10.10.apk

**Comment by Evineit** [comment]
Now is working.
I tried to press the search for new updates button but didn't find the new bug-fixed release, had to use the link from @arkon, maybe it was too soon after the previous bugged release.
Thanks.

**Comment by arkon** [comment]
Yeah, I replaced it with the same version. Let's just pretend the first buggy version never happened.
