### ISSUE TITLE
[Feature Request] "Update All" button for extensions.

### ISSUE THREAD

**Issue by AefRal** [tachiyomiorg/tachiyomi#4815]
I opened the app today to find I had 139 extensions that have an available update.
![Screenshot_20210411_163543_eu kanade tachiyomi](https://user-images.githubusercontent.com/68062495/114324079-7d946e80-9ae5-11eb-87e4-66f558f546e0.jpg)
It is so tedious as I tap a few and be interrupted by the pop-up to install the update while going down the list.
Please create a button to Update and Install All.

A one-tap-done, button.

**Comment by arkon** [comment]
See discussion in #4748

**Comment by giulianoriccio** [comment]
There are apps like AppMgr III that asks for accessibility permission to detect buttons and interact with the interface to mass clear apps' cache or move them to the SD.

Maybe something like that could be done to mass install the extensions?

**Comment by arkon** [comment]
The app installation interface explicitly blocks any sort of overlay/programmatic interactions for security reasons.

**Comment by AefRal** [comment]
I didn't ask for automatic updates.
I'd still be pushing a button, just that, that button would check the list for all those that can be updated and subsequently push their respective update buttons, all at once.

Kind of like many dynamite fuses twisted together take only once match.

**Comment by giulianoriccio** [comment]
Then, as AefRal suggests, triggering all the updates with a single button would still make it easier. The user would only need to accept the installation.

**Comment by arkon** [comment]
That's what I said in the other issue...

**Comment by apav** [comment]
Another way to get around this issue entirely is to offer all  in one extensions like the single Foolslide FM Reader, Madara, etc extensions we had before, but as an optional download. The user can choose if he wants to install that one or the individual sources we have now. You could put it in new category (like the one labeled "English") at the bottom to seperate it from the other extensions so people aren't confused.

**Comment by hyoretsu** [comment]
> Another way to get around this issue entirely is to offer all the single Foolslide, FM Reader, Madara, ComiCake, etc extensions (the ones that combined all their sources into one) we had before, but as an optional download. That way we could choose if we want to install that one for all of its sources or the individual sources from it that we have now. You could put it in new category at the bottom to seperate it from the other extensions so people aren't confused.

You'd still need to update multiple extensions depending on which ones you have and when they had an update.

**Comment by apav** [comment]
> > Another way to get around this issue entirely is to offer all the single Foolslide, FM Reader, Madara, ComiCake, etc extensions (the ones that combined all their sources into one) we had before, but as an optional download. That way we could choose if we want to install that one for all of its sources or the individual sources from it that we have now. You could put it in new category at the bottom to seperate it from the other extensions so people aren't confused.
> 
> You'd still need to update multiple extensions depending on which ones you have and when they had an update.

Yes, that is what I was doing and was fine with before. 5 is much better than 50.

**Comment by CarlosEsco** [comment]
> 
> 
> Another way to get around this issue entirely is to offer all the single Foolslide, FM Reader, Madara, ComiCake, etc extensions (the ones that combined all their sources into one) we had before, but as an optional download. That way we could choose if we want to install that one for all of its sources or the individual sources from it that we have now. You could put it in new category at the bottom to seperate it from the other extensions so people aren't confused.

This wouldn't work at all because versions are now specific to a source unless there are broad changes across the extension (which is not frequent)

**Comment by hyoretsu** [comment]
Here to advocate for this again, just opened Tachiyomi to find 19 updates.

**Comment by FourTOne5** [comment]
> Here to advocate for this again, just opened Tachiyomi to find 19 updates.

Here is a Tip for the future if you are running Android 12(iirc) install TachiyomiJ2K and there will be a "Update All" button to update all the extension silently.

**Comment by metroid112** [comment]
After finding I had 200 updates today, I am in complete agreement with a feature like this.

**Comment by LittleHans8** [comment]
@arkon 

First of all, thank the developers very much. I have a question, if we don't consider security issues, can we update the extension through hotfix? I pay attention to resolving the extension by calling the `PathClassLoader ()` fun in the code. If we use the `DexClassLoader()` fun, can we update the extension without installing APK?

> **DexClassLoader** - A class loader that loads classes from .jar and .apk files containing a classes.dex entry. This can be used to execute code **not installed as part of an application.**  https://developer.android.com/reference/dalvik/system/DexClassLoader

**Comment by arkon** [comment]
It is possible, yes. We actually did implement that in 1.x, but it presents the challenge of how to deal with the UX of handling deep links, which still requires a regular installation. It could be a 2 step process in those cases, but I'm not sure if that's really ideal.

That said, Android 12 allows for seamless app updates after the initial installation. The J2K fork already has an implementation of that, so that's likely what'll be adopted in the main app too.

**Comment by alexkoay** [comment]
My main problem without "Update All" is that my interaction to update all the extensions is interleaved between pressing the "Update" button on each extension, and then pressing "Install" from the system UI.

I don't mind pressing the Install button per se (since this is an OS limitation after all), but it would be helpful to simply keep my finger on one button and tap Install for them all. At the moment, I tap as many "Update" buttons as possible (usually 2-3) before the system prompt appears, then I wait for each "Install" button to become tappable then go back to searching for the next Update (if I didn't cause the screen to transition elsewhere, e.g. to an extension info page).

While J2K has made it seamless for Android 12, it still leaves the users pre-Android 12 in a tight spot without replacing our devices.
