### ISSUE TITLE
[Bug] <Global search crashes the app>

### ISSUE THREAD

**Issue by yaminokizuna7** [tachiyomiorg/tachiyomi#4816]
## Device information
* Tachiyomi version: v0.10.10
* Android version: 11
* Device: Samsung note 10+

## Steps to reproduce
1. Clicking the search to global search a specific manga or clicking the manga title to search globally 

### Expected behavior
load the same manga title across multiple sources if available in those sources. 

### Actual behavior
Loads the screen for a couple seconds before crashing and closing down the app. 

## Other details
trying to attach the crash logs, not sure if I did it or not, sorry! 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Can you try uploading the log file again?

**Comment by yaminokizuna7** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6292944/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Try updating the MangaPlus extension. If it still persists, open an issue in the TachiyomiJ2K repo, as it looks like your crash log is from that app.

**Comment by yaminokizuna7** [comment]
Omg thank you!!
