### ISSUE TITLE
[Feature Request] Make Dual Page Split Series-Specific

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi#4817]
## Why/User Benefit/User Problem
Not every series suffers from the two-pages-in-one problem. It'd be convenient if we could leave DPS on only for those series, because it might interfere with **page spreads**, which a lot of other manga employ.

## What/Requirements
Just make the DPS setting work like the viewing mode. It remains enabled for the series you turned it on for, and disabled for the rest.

**Comment by arkon** [comment]
Per-series settings are incredibly annoying to implement and handle and this doesn't seem worth it when you can toggle it relatively easily.
