### ISSUE TITLE
[Bug] Toolbar jumps back down when scrolling

### ISSUE THREAD

**Issue by Jhnyx** [tachiyomiorg/tachiyomi#4819]
Device information
Tachiyomi version: 0.10.10
Android version: 10
Device: CPH1933

Steps to reproduce
1. Open tachiyomi
2. Scroll down in library

Expected behavior
Smooth animation while scrolling

Actual behavior
Laggy and snappy

Other details
Happened after i updated to the latest version

https://user-images.githubusercontent.com/82367432/114359284-5f427780-9ba6-11eb-891c-e3ff90de2338.mp4

**Comment by arkon** [comment]
To be verified by Preview testers; going to leave this open until then.

**Comment by arkon** [comment]
Verified; will be in the next stable release.
