### ISSUE TITLE
[Bug] <Weird transparent UI when long taping a comic then immediately tap on another comic when the library category show up>

### ISSUE THREAD

**Issue by Rifaditya** [tachiyomiorg/tachiyomi#4824]
## Device information
* Tachiyomi version: Stable 0.10.10
* Android version: 10
* Device: Honor 8X

## Steps to reproduce
1. Long tap on a comic.
2. immediately tap on another comic ~~before~~ right after or the same time the library category show up. *Try not to tap on the library box panel*

### Expected behavior
Showing the library ignore taping on another comic

### Actual behavior
Not showing the library category but showing a comic detail with transparent UI and then show the library thing after pressing the back button(the left top/back on phone button)

## Other details
Additional details and attachments.
Not a new bug on 0.10.10 i already experience this before updating to newest ver. 
Only can happen outside library tab/in browse on any extension doesn't matter what extension

![UI Weird](https://user-images.githubusercontent.com/46129932/114412455-4ef6c080-9bd7-11eb-8faf-df9f052a4d4a.gif)

https://user-images.githubusercontent.com/46129932/114413025-d3e1da00-9bd7-11eb-99e9-8d1b005a54f9.mp4

**Comment by arkon** [comment]
This realistically won't be fixed in 0.x without replacing/fixing the underlying navigation system, which we have no plans to do so. It'd ultimately be a non-issue in the 1.x rewrite.
