### ISSUE TITLE
update notifications should do something

### ISSUE THREAD

**Issue by cpsquonk** [tachiyomiorg/tachiyomi#4825]
So I get notifications like this:
![Screenshot_20210412-095856_One UI Home](https://user-images.githubusercontent.com/75129161/114416349-35715c80-9b76-11eb-8909-fe2f2c4fd199.jpg). Pressing the notification does nothing, which is not how notifications are supposed to work. At that point I have to remember how to update Tachiyomi. This is an ulcer on UX. I'm pretty sure everyone expects pressing that notifications brings you to a screen that asks for the update, then you go yes or no.

**Comment by arkon** [comment]
You could've worded the issue in a less snappy way, but yes this is a valid suggestion.

**Comment by cpsquonk** [comment]
That is a weirdly passive-aggressive response. If it isn't a repeat issue, I suggest never responding that way on a valid UX complaint again. Discouraging bug tickets on an open source project is a huge problem. I didn't submit this ticket with the expectation it's gonna get prioritized, but I didn't expect sass. All I said were factual statements.

**Comment by CarlosEsco** [comment]
usually when opening a ticket on an open source project you should be considerate and understanding.  @cpsquonk your first interaction with this repo was passive aggressiveness "Pressing the notification does nothing, which is not how notifications are supposed to work. At that point I have to remember how to update Tachiyomi. This is an ulcer on UX."
