### ISSUE TITLE
[Bug] Text pasted into search field has different font size

### ISSUE THREAD

**Issue by T3sT3ro** [tachiyomiorg/tachiyomi#4828]
Text pasted into search boxes by long pressing field and selecting "paste" option may have different style depending on what elements it was copied from.

![image](https://user-images.githubusercontent.com/5300963/114464545-3215b980-9be6-11eb-810b-ce3a53c40326.png)

On the image above pasted text is "Synopsis" - it's a bold text copied from a random MyAnimeList page:
![image](https://user-images.githubusercontent.com/5300963/114464746-72753780-9be6-11eb-8910-33aff2514879.png)

Problem is clearly seen when copying and pasting manga title from Mangakalot webpage:
![image](https://user-images.githubusercontent.com/5300963/114464518-29bd7e80-9be6-11eb-8a87-9b5207d32fc2.png)
![image](https://user-images.githubusercontent.com/5300963/114464958-c41dc200-9be6-11eb-8062-d629230a78ab.png)

---

## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: Huaweii P20 Pro

## Steps to reproduce
1. copy formatted text from the web - some H1 element - for example visit [this mangakalot page](https://mangakakalot.com/read-kh6ab158504854282) and copy manga title
2. paste into any searchbox in app (preferably search in library) by long pressing the field and selecting "paste" (won't work when selecting from above-keyboard clipboard drawer)

### Expected behavior
Text should be pasted as plaintext.

### Actual behavior
Text is weirdly formatted - It's font is bigger and probably heavier. It may be that only font size is affected - I'm not sure. I

**Comment by arkon** [comment]
You should have a "Paste as plain text" option, assuming Huawei didn't remove that.

---

Note for devs: https://stackoverflow.com/questions/17932616/how-can-i-remove-formatting-from-text-that-is-pasted-into-a-searchview

**Comment by T3sT3ro** [comment]
Ofc this option is present, but is pasting with formatting as intended ?

**Comment by arkon** [comment]
It's not really intentional, but it is the default behaviour. It's kind of a pain to deal with it everywhere.

**Comment by arkon** [comment]
Marking as won't fix since the system gives you a way to paste normally, and AFAIK there's no easy way to handle it everywhere in the app.
