### ISSUE TITLE
 [Bug] Force closes the app/crashes

### ISSUE THREAD

**Issue by mcalava** [tachiyomiorg/tachiyomi#4830]
---

## Device information
* Tachiyomi version: Stable
* Android version: 10
* Device: Redmi Note 9 pro

### Expected behavior
Manga that is selected should load. 

### Actual behavior
Closes/crashes the app when opening some manga but works fine with other manga. 

## Other details
- using J2k and Neko but Stable and Sy isn't working properly. 
- 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6301608/tachiyomi_crash_logs.txt)

[tachiyomi_crash_logs (2).txt](https://github.com/tachiyomiorg/tachiyomi/files/6301631/tachiyomi_crash_logs.2.txt)

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6301632/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Sorry, none of those logs have anything useful in them. Were they taken after a crash occurred?

**Comment by mcalava** [comment]
@arkon yes, these are taken after the crash. 

content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt

**Comment by arkon** [comment]
Can you try uploading it again?

**Comment by mcalava** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6305033/tachiyomi_crash_logs.txt)

Here's the recent one. 

Picture of the report bug from phone 
![Screenshot_2021-04-13-23-45-42-845_com miui bugreport](https://user-images.githubusercontent.com/30865574/114582526-3e1b7d00-9cb3-11eb-94fa-766c3d165c2e.jpg)

https://drive.google.com/file/d/18w7m3Uj73otV3dd8d2qi2UtkeO-Njg2D/view?usp=drivesdk

**Comment by arkon** [comment]
Unfortunately those logs and video aren't enough to tell what's happening.

Potential ways of getting more detailed logs:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by mcalava** [comment]
I'll try to get more detailed logs. Sorry for the trouble.

**Comment by arkon** [comment]
Please open another issue if you get more logs. This is currently unactionable, so I'm closing it to help declutter the issues list.
