### ISSUE TITLE
[Bug] Unlock screen missing pattern option

### ISSUE THREAD

**Issue by jasonhpchu** [tachiyomiorg/tachiyomi#4833]
## Device information
* Tachiyomi version: r3218
* Android version: 10
* Device: LG G7

## Steps to reproduce
Turn on Require unlock

### Expected behavior
Shows pattern unlock screen, where you can also do fingerprint to unlock.

### Actual behavior
No pattern unlock screen, only shows dialog asking to unlock with fingerprint.  No way to switch to pattern screen.
So I can only use fingerprint unlock.  There are situations where I cannot use the fingerprint sensor, during which I cannot use the app.

I don't know when exactly this happened, but after one of the tachiyomi update, this change happened.

Thanks.

**Comment by arkon** [comment]
This is the expected behaviour of the underlying biometrics system.

**Comment by jasonhpchu** [comment]
I didn't have a system update, and this changed.
Have the unlock function in Tachiyomi been updated to call the system unlocking differently recently?
I have both fingerprint and pattern set in my android system.

**Comment by CarlosEsco** [comment]
there has never been pin unlock on tachiyomi, only biometric.  Either you were using a fork that had pin unlock, or your phone changed something

**Comment by jasonhpchu** [comment]
It wasn't pin, it was pattern unlock.
Had it for a long time with tachiyomi ever since it added the secure unlock thing.

**Comment by arkon** [comment]
The support library was updated in Tachiyomi to use its updated behaviour that prefers stronger methods.

**Comment by jasonhpchu** [comment]
Thanks, that's probably why then.

What's that library used?
Maybe I can dig in that direction.

**Comment by arkon** [comment]
https://developer.android.com/jetpack/androidx/releases/biometric

**Comment by jasonhpchu** [comment]
hmm interesting, so shouldn't what's done here add back in the weaker one?
https://github.com/jobobby04/TachiyomiSY/commit/c2e882cb5bde41119f2835731e14d5bdd196870f

**Comment by arkon** [comment]
It allows weaker ones, but the library still prioritized the strongest one specified. If you have multiple methods available, it'll pick the strongest one (fingerprint over pattern), but if you only have weak ones (pattern), that'll also be available (where it wasn't before).

**Comment by jasonhpchu** [comment]
ok, here's something interesting.
I've gone ahead and turned off fingerprint phone unlock option in android, but kept the saved fingerprints.
Locking the phone obviously now needs me to put in my pattern, no fingerprint.
Opening Tachiyomi, it still asked me for my fingerprint.
Then I've totally removed fingerprints.
Now Tachiyomi totally removed the lock, and the option for require unlock disappears from the settings.
So seems currently, it can only take fingerprint as unlock method.

**Comment by arkon** [comment]
Ah, you're right. I might be able to fix that, I'll post an update later.

**Comment by jasonhpchu** [comment]
Awesome thanks.

**Comment by arkon** [comment]
I'll have a fix out for the next release.
