### ISSUE TITLE
[Bug] <Selection toolbar doesn't fully display>

### ISSUE THREAD

**Issue by jrgerhardt** [tachiyomiorg/tachiyomi#4834]
## Device information
App version: 0.10.10-3254 (standard, 15bed1ac, 57)
Android version: 11 (SDK 30)
Android build ID: RQ2A.210405.005
Device brand: google
Device manufacturer: Google
Device name: crosshatch
Device model: Pixel 3 XL
Device product name: crosshatch

## Steps to reproduce
1. Select one or more chapters in a manga
2. Toolbar doesn't fully display

### Expected behavior
Toolbar should display with Download, Mark as Read, Bookmark, etc. options

### Actual behavior
Toolbar partially displays so none of the options are able to be tapped on

## Other details
See attached screenshot
![Screenshot_20210413-101149](https://user-images.githubusercontent.com/1783037/114578020-26f07700-9c42-11eb-8e6e-a3035524ad01.png)

**Comment by ghostbear** [comment]
`r3254` is not the latest dev version. The latest version is `r3259`

**Comment by jrgerhardt** [comment]
Worked like a charm! Thanks and sorry for the inconvenience!
