### ISSUE TITLE
[Bug] Content goes under the nav

### ISSUE THREAD

**Issue by Mapsred** [tachiyomiorg/tachiyomi#4836]
## Device information
* Tachiyomi version:  Preview r3259 and Stable v0.10.10 
* Android version: 10
* Device: OnePlus 6T

## Steps to reproduce
1. First step
Go to any page with overflow to see 

### Expected behavior
The overflow should be visible only outside of the navbar

### Actual behavior
The content should not go under the nav buttons. Even in apps without a menu to the bottom (eg. settings) the overflow is not under the nav buttons.
And, if I hide the navbar, the last option (here on the Library options) goes outside the screen, the content below the navbar is not properly accessible.

## Other details
![Webp net-resizeimage(1)](https://user-images.githubusercontent.com/13522273/114594133-32b55b00-9c8d-11eb-8aff-76af0759779a.jpg)

https://user-images.githubusercontent.com/13522273/114593702-aa36ba80-9c8c-11eb-926e-e729a1d9cc79.mp4

**Comment by Flat** [comment]
While not being able to tap something because it is under the navbar should be addressed, showing items under nav is the norm and google does this in many apps including the play store.

**Comment by vengiare** [comment]
Examples of first-party apps that do this are Messages, Calendar, and Contacts.

I think this is most likely intended behaviour and not a bug.

**Comment by Mapsred** [comment]
Indeed I checked these apps, the difference is that they have a background on the nav where this is transparent in Tachiyomi
I will try a feature request for this one, but here there is still the problem of the content below the navbar is not properly accessible on this issue.

Thanks

**Comment by arkon** [comment]
This is obviously intended, but we may want to add scrims.

**Comment by piggehperson** [comment]
Recommended behavior for Android 10+ is to show a scrim for button navigation, and have nothing behind the bar on gesture navigation. I believe that setting `<item name="android:navigationBarColor">@android:color/transparent</item>` in styles.xml will have the system do this automatically, per the docs at https://developer.android.com/training/gestures/gesturenav

I can take a crack at this myself if you are done with this issue.

**Comment by arkon** [comment]
@piggehperson Sure, you can take a stab at it.

**Comment by ivaniskandar** [comment]
We can just set enforceNavigationBarContrast to true but as I said on my initial PR for this, the system-provided scrim is IMO not fitting to the app themes.

I'll make a follow-up PR for a universal custom scrim.

**Comment by arkon** [comment]
@ivaniskandar You can check out what's been added so far too.

**Comment by ivaniskandar** [comment]
@arkon I opened PR #4845 for my take on this scrim thing.
