### ISSUE TITLE
[Feature Request] <Auto delete downloaded chapters after X days>

### ISSUE THREAD

**Issue by AdarshRise** [tachiyomiorg/tachiyomi#4837]
## Why/User Benefit/User Problem
(explain why this feature should be added)

I have many manga and I usually download them, once I read them I sometimes don't spend time to delete what I have read. 
An auto delete feature will help me save a ton of time.

## What/Requirements
(explain how this feature would behave)

We can select a category where downloaded manga/Chapters will get auto deleted if not read for (30 days), deleted chapters could be given some symbol which shows that it was there but was deleted as per the rule set by the user.

**Comment by arkon** [comment]
There's already a delete after read setting.

**Comment by AdarshRise** [comment]
Sorry, if the request is unclear. 
I downloaded many manga in hopes to read in future, and sometimes I re-read downloaded manga. 

But if I don't open them for a long time they get auto deleted.  I understand if this feature is not prioritized for now, through pls consider it for those phone which has less storage.
