### ISSUE TITLE
[Bug] Parameters overflow under the navbar

### ISSUE THREAD

**Issue by Mapsred** [tachiyomiorg/tachiyomi#4838]
## Device information
* Tachiyomi version: Preview r3264
* Android version: 10
* Device: OnePlus 6T

## Steps to reproduce
1. First step
More -> Settings -> Library / Reader
2. Second step
Scroll to the bottom of the page 

### Expected behavior
The last option of the page should be accessible 

### Actual behavior
The last option of the page is stuck in the navbar preventing to click on this option correctly 

## Other details
Additional details and attachments

![Screenshot_20210414-004903](https://user-images.githubusercontent.com/13522273/114632045-154cb500-9cbe-11eb-875f-ca94008e44f4.jpg)
![Screenshot_20210414-004916](https://user-images.githubusercontent.com/13522273/114632047-15e54b80-9cbe-11eb-9389-8a8214080bab.jpg)

**Comment by arkon** [comment]
Fixed in latest preview build.
