### ISSUE TITLE
[Feature Request] Allow Use of Arbitrary GLSL Shaders in Reader

### ISSUE THREAD

**Issue by lukasubo** [tachiyomiorg/tachiyomi#4840]
## Why/User Benefit/User Problem
This would allow the use of shaders such as https://github.com/bloc97/Anime4K for denoising/deblurring/upscaling low quality manga and comic scans.

## What/Requirements
Being able to add shaders and enable them on a per-title basis would allow a user to select the appropriate ones for each scan.

**Comment by arkon** [comment]
Rejected before, you can preprocess your content if you want to.
