### ISSUE TITLE
[Feature Request] Add 'see recommendation/see similar manga' feature.

### ISSUE THREAD

**Issue by aydinarsalan40** [tachiyomiorg/tachiyomi#4844]
## Why/User Benefit/User Problem
Tachiomy is almost perfect. If there was a feature to see recommendation/similar manga , it would be great. 

## What/Requirements
Extra feature option if possible  -------------------
Like in global search, there is an option to "only include pinned sources,

There can be a option to pin  3-7 sources (ranking 1 from 7) in settings .
So that while seeing recommended mangas or similar mangas, users don't have to select a manga than pick a source and wait for the source to find it.

After clicking a manga from recommended mangas, app should instantly start searching the sources. And-
     a) Upon clicking, app should  search the rank 1 source and show result. if not found search for rank 2 and show result. Like this ,rank 3,4,5,6,7 will be searched if the previous source cant find result.
     b) Upon clicking, app should search all 3-7 sources and show the one that have the most chapters.

**Comment by curche** [comment]
Dupilcate of #376
