### ISSUE TITLE
[Bug] <code bug>

### ISSUE THREAD

**Issue by giuliobz** [tachiyomiorg/tachiyomi#4847]
I try to update manga chapter anche there Is this message:

'Attempt ti invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference'

This appen on a Mangaword (ita extension) manga. When i open mangaword i can't see the catalog, but if i open the web version It works.

I update the extension and the application.

**Comment by Riztard** [comment]
youre in the wrong repo. please read the template that you acknowledged and delete.
