### ISSUE TITLE
[Bug] Cannot go back from search if you didn't finish it

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi#4850]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 5.1
* Device: Huawei TIT-U02

Also made sure it happens in a newer Android (9 to be exact) in an emulator

## Steps to reproduce
1. Open a source
2. Start typing
3. Try to go back (do not tap search button)

### Expected behavior
Go back.

### Actual behavior
Can't go back.

## Other details
<details>
<summary>Video with the bug</summary>

https://user-images.githubusercontent.com/65343233/114754359-27336400-9d61-11eb-807f-6f686ce69169.mp4

</details>
PR that maybe caused the bug #4494

**Comment by MercerBoi** [comment]
Facing the same issue here.
