### ISSUE TITLE
[Bug] Bug report of tachiyomi

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#4853]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 8
* Device: huawei p8 lite 2017

### Expected behavior
the app shouldn't crash

### Actual behavior
the app crashed

## Other details

[tachiyomi_crash_logs-1.txt](https://github.com/tachiyomiorg/tachiyomi/files/6313259/tachiyomi_crash_logs-1.txt)

**Comment by Palloxin** [comment]
i forgot to write that it is a crash report

**Comment by arkon** [comment]
Please try to update your Android System Webview.

**Comment by Palloxin** [comment]
> Please try to update your Android System Webview.

but it takes too much space, is there another way?

**Comment by arkon** [comment]
No, this isn't a Tachiyomi issue.
