### ISSUE TITLE
[Bug] Bug Tachiyomi extension

### ISSUE THREAD

**Issue by Bellini26** [tachiyomiorg/tachiyomi#4854]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: Huawei mate 20

## Steps to reproduce
1. Open the source mangaworld (ITA)
2. choose any manga
3. open any chapter
4. no page found

### Expected behavior
Read manga
### Actual behavior
Can't read manga

## Other details
Whenever I open any manga this appears 
![photo_2021-04-14_22-03-58](https://user-images.githubusercontent.com/82541841/114772114-b6467900-9d6d-11eb-976d-db08816a29bd.jpg)

**Comment by arkon** [comment]
Wrong repo, issue already opened in the correct place.
