### ISSUE TITLE
[Bug] downloaded files disappear from the library

### ISSUE THREAD

**Issue by Memi2** [tachiyomiorg/tachiyomi#4855]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 11
* Device: Samsung s20 fe

## Issue/Request
I lost the downloaded chapters from 3 manga.  That is, they are physically available through the file manager and can be viewed, but in the application it shows that they are not loaded and cannot be viewed through the application.  I observe this bug 5 times, the reason is unknown to me and this happens regardless of my interventions.  This is not due to the update, they disappeared a day before the update and did not appear after the update.  This bug occurred to me on different versions of the application, different phones and different versions of android.

**Comment by arkon** [comment]
Not enough info to work off of here. A few things that might help:

- Do the chapter names match up? Did they maybe change and get orphaned? 
- What source(s)?
- Is it only those 3 specific manga?
