### ISSUE TITLE
[Bug] Lily manga still error

### ISSUE THREAD

**Issue by meru77** [tachiyomiorg/tachiyomi#4858]
![Screenshot_2021-04-15-14-46-43-46_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/82571801/114833105-6dd49d00-9df9-11eb-81af-d7e6b3fd345d.jpg)
Cant open manga without open web mode first
![Screenshot_2021-04-15-14-39-04-55_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/82571801/114833173-7dec7c80-9df9-11eb-9b95-227c7ef7e83c.jpg)
After open web mode lily manga is to slow
![Screenshot_2021-04-15-14-40-09-87_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/82571801/114833249-90ff4c80-9df9-11eb-88b3-1e4231dc85b0.jpg)
But not slow at using web mode

**Comment by arkon** [comment]
Wrong repo.
