### ISSUE TITLE
[Bug] gif is lagging when played in portrait mode 

### ISSUE THREAD

**Issue by abdazez01** [tachiyomiorg/tachiyomi#4863]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 9
* Device: honor play 

## Steps to reproduce
1. Open any manga that have gif
2. Put the device in portrait 

### Expected behavior
Play the gif normally. 

### Actual behavior
Play the gif with lagging .

**Comment by arkon** [comment]
Duplicate of #4162
