### ISSUE TITLE
[Feature Request] <delete or give option to close the toast that pop up when open a chapter >

### ISSUE THREAD

**Issue by smarttommyau** [tachiyomiorg/tachiyomi#4864]
## Why/User Benefit/User Problem
The toast that tell you what your reader type pop up on the middle of the screen everytime you open a chapter which is very annoying and you need to waste time to wait it to disappear. 

## What/Requirements
Just delete it, or give option to close it or change the position to pop up to the bottom.

**Comment by arkon** [comment]
There's already a setting to turn it off.
