### ISSUE TITLE
[Bug] Viewer setting stuck on webtoon

### ISSUE THREAD

**Issue by SlickBastard** [tachiyomiorg/tachiyomi#4865]
## Device information
* Tachiyomi version: 1.0.13
* Android version: 10
* Device: galaxy note 9

## Steps to reproduce
1. Open viewer settings when reading

### Expected behavior
Change viewer settings to liking

### Actual behavior
When reading some manga/manwha the viewer setting gets stuck on webtoon and i can not change it

**Comment by Riztard** [comment]
> Tachiyomi version: 1.0.13

thats J2K issue

**Comment by arkon** [comment]
I assume you're using J2K and you're in the wrong place, but you need to remove the tag.
