### ISSUE TITLE
[Feature Request] <bring back easy custom filter or brightness shortcut please>



### ISSUE THREAD

**Issue by MFDaus47** [tachiyomiorg/tachiyomi#4867]
In the latest update, you guys have removed the custom filter section to the bottom and that makes it hard to use. I need to do some extra steps before reaching the custom filter section. The brightness part is also at the bottom, so when I scroll down to get to the brightness slider, the interface cover the whole screen and I can't see how dark or bright the pages is because of that. Here's how it looks ![Screenshot_2021-04-16-06-30-00-13_afd66b7916d19a60815f56273408b73e.png](https://user-images.githubusercontent.com/79355837/114946425-b170ea80-9e7d-11eb-938e-d5b5a0d251a5.png) This feature is very useful for reading at late night, so i would always use this feature. This will surely benefit other night readers as well, hope you could bring it back!🙏

**Comment by zayin02** [comment]
Long pressing solves the problem with the extra steps but still doesn't solve the brightness problem.

**Comment by MFDaus47** [comment]
How about removing the blank space on the page? Or maybe limit it that it wouldn't show that much unnecessary blank area on that page. It's okay enough to see half of the page at least, or something similar in the V0.10.9(second former version from today).

This is what it looks like on the old version 
![Screenshot_2021-04-25-05-32-43-34_afd66b7916d19a60815f56273408b73e.png](https://user-images.githubusercontent.com/79355837/115973525-419ee600-a588-11eb-8237-d86fadb3f579.png)

**Comment by zayin02** [comment]
I don't think it possible to fix it like the older versions because of the way it is designed in 10.11

**Comment by MFDaus47** [comment]
I see, then how about you make the page could show the slider right when you open it. Right now the page only shows until the toggle of the custom brightness, not the slider. How about you make it till it shows slider right when you open it
 
Or if that's still impossible, you can swap the places with the custom color filter. I think this is a good way because not many people know how to use custom color filter, and people use the custom brightness more than the custom color filter.

**Comment by paulo27ms** [comment]
For me it's possible to drag the slider right after opening, it'd be better if there was a bit more padding at the bottom of the menu though, yeah.
