### ISSUE TITLE
[Bug] New Anilist Start date support wipes out start date if already set

### ISSUE THREAD

**Issue by HackingPheasant** [tachiyomiorg/tachiyomi#4868]
## Device information
* App version: 0.10.10 (standard, 0dc4862, 57)
* Android version: 10 (SDK 29)
* Device: OnePlus5

## Steps to reproduce
1. Update to newest stable release (0.10.10).
2. Read and complete a chapter. State of the app/setup should be:
 - Tracking Setting: _Update chapter progress after reading_ is set to **ON**
 - The tracking page on a **_manga should already have Anilist linked_**, but not have the **_start date populated in the Tachiyomi_** app. And **_Anilist should have the start date already set_**. This is easy enough to achieve.
3. Click the Tracker button and notice that date is blank. Visit the Anilist website and notice the start date has been wiped because of Tachiyomi. Tachiyomi has inadvertandly blanked out the start date.

### Expected behavior
It shouldn't clear your start date on Anilist

### Actual behavior
It clears the start date on Anilist

## Other details
I haven't tried this with the MAL tracker (only other tracker I make use of) but I assume it won't be an issue since it has that tab for a long while now.

**Comment by paulo27ms** [comment]
Happens on all trackers probably, not exclusive to dates. #1652
Issue is that Tachiyomi sends all the information it has and not just what it updated, it also doesn't check if there were updates before sending, it just assumes it's updated.

**Comment by arkon** [comment]
Yeah, #1652 is the root issue.
