### ISSUE TITLE
[Bug] Cannot install latest version

### ISSUE THREAD

**Issue by Elodain** [tachiyomiorg/tachiyomi#4869]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: One Plus Nord N10 5G

## Steps to reproduce
1. Try to update from 0.10.09 to 0.10.10

### Expected behavior
App should update to latest version.

### Actual behavior
Receive "App Not Installed" message, app still at previous version.

## Other details
Also tried to Uninstall previous version, unaware of the MicroSD bug with using Android 10. App uninstalled seemingly, but I chose to keep my app data in hopes to not have to restore a backup or set things back the way I want, an apk installing app reports that it conflicts with an installed package of the same name. Not sure if that is from my keeping app data or the Android 10 Bug, but apparently the system thinks the app is still there.

**Comment by arkon** [comment]
I'm not sure we can help with this if it's a bug in Android or OxygenOS...
