### ISSUE TITLE
[Feature request] option to create a SUB CATEGORY 

### ISSUE THREAD

**Issue by forlorn12** [tachiyomiorg/tachiyomi#4876]
**Improving user experience**

This feature can be such that 
a user will be able to create a sub-category 
Inside a category 
 
This will help user to split 
their manga manhwa and manhua inside 
A category 

**For example** 
This is my planing category (its pretty long)
![Screenshot_20210416-210129_Tachiyomi](https://user-images.githubusercontent.com/82667133/115048266-000e9b00-9ef7-11eb-822a-2c3da314655e.jpg)

If I am able to divide it in 
Different sub-categories it will be a huge help

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/1803
