### ISSUE TITLE
[Feature Request] Scrolling down on Webcomics or Manhwas

### ISSUE THREAD

**Issue by ram16230** [tachiyomiorg/tachiyomi#4879]
## Why/User Benefit/User Problem
The readers can benefit of being able to read the content as it was designed to be read. This makes a more friendly experience.

## What/Requirements
What i have notice using the app with manhwas and webcomics are that they come in two formas.

1. Conventional: the source of the file has being splitted in many pages that fit inside a viewer, normal page. This sometimes cut long art and scenes that are famous on webcomics to preserve the pages size.
2. Long: that present the chapters in multiple long images per page. So you have to zoom in and scroll down until you finish reading then you can go to de next page or chapter by swiping left to right.

Adding an option on the viewer to stack pages and allow a seemless borderless scroll down of the pages. This way the user decides if they want to read the manga or webcomic as an scrollviews without having to add more complexity.

Or let the viewer recognize or decide if the file being display should be display as a scrollview rather than an slideview. This can be made by checking the ratio of the images in the chapters.

PS: Sorry for the grammar english is not my main language. Also I'm a developer of web apps, I dont have any experience with developing with kotlin but Im willing to help if needed.

**Comment by CarlosEsco** [comment]
There is already an option to change the reader to webtoon mode. If you are unable to find it ask in the discord channel and someone can send a screenshot
