### ISSUE TITLE
[Feature Request] Add option to disable the Split bottom shortcut toolbar and seekbar

### ISSUE THREAD

**Issue by Mohammed-D** [tachiyomiorg/tachiyomi#4883]
I dont exactly have any need for the quick options and rarely need to switch any of them, so the shortcut toolbae is just unnecessarily pushing the seek bar upwards.

Just an extra toggle in settings to revert to the original seekbar would be enough.

**Comment by arkon** [comment]
Sorry, but you'll just need to get used to it.
