### ISSUE TITLE
[Feature Request] Add optional back button/header bar in fullscreen

### ISSUE THREAD

**Issue by brendenhoffman** [tachiyomiorg/tachiyomi#4886]
## Why/User Benefit/User Problem
When using gesture based navigation buttons in Android it becomes difficult, though not impossible, to exit a fullscreen manga when a single tap or swipe from the side changes the page and double tapping zooms. If fullscreen is turned off then the page navigation bar covers some of the page. 

## What/Requirements
Add optional back button or the top header bar with manga title in fullscreen, aka only hiding the bottom settings panel and page navigation in fullscreen. Tapping the header could bring up the bottom settings panel and page navigation, easier than triple tapping which triggers zoom as well. It would also be nice if long tap brought up an exit menu and might be an easy alternative to the feature I would like to see.

**Comment by arkon** [comment]
You can already tap in the middle to bring up the menus, including the system navigation bar. Is that not sufficient?

**Comment by paulo27ms** [comment]
Dragging from the bottom also brings up the buttons, it does move the page up a bit in webtoon but doesn't impact other modes.

**Comment by brendenhoffman** [comment]
I feel a little silly, I did try that and I kept flipping pages. I do see that does work though. It is sufficient, even before it was nothing stopping me from using the app, but depending on the scale of the work it would be a nice feature. The ability to adjust the size of the tapping zones would also help, the middle zone seems to be a little less than a thumb width for me.
