### ISSUE TITLE
[Feature Request] Add indication of applied filter in chapter list

### ISSUE THREAD

**Issue by Kyle2142** [tachiyomiorg/tachiyomi#4888]
## Why/User Benefit/User Problem
When a user filters the chapter list (e.g by unread) it is not obvious that one has been applied.  
After some time the user might think the extension isn't working and the chapters are "gone" if new chapters are not added frequently

## What/Requirements
Add an indication of a filter being applied to the chapter count, 
Current: 0 chapters
New:
- 0 chapters unread
- 0 unread chapters
- 0 chapters (unread) 
- etc

This will provide a reminder that a filter has been applied

**Comment by joseph619** [comment]
The filter button changes from white to yellow, so there is already indicator

**Comment by Kyle2142** [comment]
Apologies, that is true.
However the yellow is almost indistinguishable from white, at least when using black theme. 
Most apps rather add a large (red?) dot or such to the icon than change the colour

**Comment by Kyle2142** [comment]
Just a follow up on the yellow icon, the visibility isn't as bad as I thought, but if your screen is dim or you're using a blue light filter it will be easy to miss. 
Here's an example from Emby 
![Screenshot_20210418-144541683 (1)](https://user-images.githubusercontent.com/19349418/115145973-cce21e00-a054-11eb-89e1-051979dd5362.jpg)

**Comment by stevenyomi** [comment]
- #8840

Maybe we should tweak it to show a badge or with a round theme-colored background.

**Comment by arkon** [comment]
Has the same tint as the library filter icon nowadays.
