### ISSUE TITLE
[Bug] <crash>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#4890]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6330513/tachiyomi_crash_logs.txt)

## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: samsung a10s

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
The chapter should load with no issues 

### Actual behavior
The app turned into a black screen then crashed stopping the library update and download operations 
## Other details
Additional details and attachments.

**Comment by arkon** [comment]
The logs don't include the crash. Do you have steps to reproduce it consistently? Are you trying to load very large images? Your phone seems like it's a pretty underpowered model.

**Comment by kasakaka** [comment]
> The logs don't include the crash. Do you have steps to reproduce it consistently? Are you trying to load very large images? Your phone seems like it's a pretty underpowered model.

yeah they're most likely webtoons that have no more than 7 page but when the page number goes up to like 10 it does not have a problem, my phone was released in 2019 so i think it can still keep up but if its the problem then its ok ill just read on a browser

**Comment by arkon** [comment]
In that case, you could also use the other reader types (not webtoon or continuous vertical) as they handle larger images a bit better.

#4791 may help in the future, so can keep an eye for out that too.
