### ISSUE TITLE
[Feature Request] Hide reader settings that don't apply to current mode/settings

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4891]
## Why/User Benefit/User Problem
Stuff like tapping settings shouldn't show in the reader settings if tapping is disabled.
Automatic zoom position is only for when you're using original size right? Shouldn't show either if you're using fit to screen.

## What/Requirements
Just generates unnecessary confusion.

**Comment by arkon** [comment]
Tap settings hide appropriately nowadays AFAIK.

Zoom depends on screen ratio/page size, not necessarily the scale type.
