### ISSUE TITLE
[Bug] Migrated manga do not keep read status of chapters

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi#4892]
## Device information
* Tachiyomi version: 0.10.10-3289
* Android version: 11

## Steps to reproduce
1. Migrate manga containing read chapters

### Expected behavior
Read chapter status should carryover to the new source.

### Actual behavior
Migrated source has all unread chapters

**Comment by paulo27ms** [comment]
Which sources? I doubt Tachiyomi will migrate chapter read status properly if it's impossible to tell the chapter number on either source.

**Comment by bbtora** [comment]
Normal sources, in this case MD to MangaSee.

**Comment by paulo27ms** [comment]
This applies to all manga?

**Comment by bbtora** [comment]
Yup, only started happening after today's update.
