### ISSUE TITLE
[Bug] Crash report (logs)

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#4893]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 8
* Device: huawei p8 lite 2017

## Steps to reproduce
1. i dont know how to reproduce since it is a crash

### Expected behavior
The app shouldn't crash

### Actual behavior
the app crashed

## Other details
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6330690/tachiyomi_crash_logs.txt)

**Comment by Palloxin** [comment]
this time i uploaded webview

**Comment by arkon** [comment]
What language are you using the app in?

**Comment by arkon** [comment]
```
04-16 22:12:17.712 26861 26861 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: message: You must specify a resource ID or literal value
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at com.afollestad.materialdialogs.utils.MDUtil.assertOneSet(MDUtil.kt:328)
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at com.afollestad.materialdialogs.MaterialDialog.message(MaterialDialog.kt:174)
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at com.afollestad.materialdialogs.MaterialDialog.message$default(MaterialDialog.kt:172)
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.setting.SettingsBackupController$RestoreBackupDialog.onCreateDialog(SettingsBackupController.kt:355)
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.DialogController.onCreateView(DialogController.kt:39)
04-16 22:12:17.712 26861 26861 E AndroidRuntime: 	at com.bluelinelabs.conductor.RestoreViewOnCreateController.onCreateView(RestoreViewOnCreateController.java:35)
```

**Comment by Palloxin** [comment]
> What language are you using the app in?

italian

**Comment by Palloxin** [comment]
> What language are you using the app in?

italian

**Comment by Palloxin** [comment]
i got another crash today, so here is another crash report 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6371471/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Closing since it should be irrelevant after #5423
