### ISSUE TITLE
[Bug] Bottom Navbar stays disabled when switching categories

### ISSUE THREAD

**Issue by HerrHulaHoop** [tachiyomiorg/tachiyomi#4895]
## Device information
* Tachiyomi version: Stable 0.10.10
* Android version: 10
* Device: OnePlus 6

## Steps to reproduce
1. Create two categories - One with multiple items (big) allowing for vertical scrolling and another with few items (small) where scrolling is not available.
2. Go to the big category and scroll down. This hides the bottom navbar.
3. Switch to the small category.

### Expected behavior
The bottom navbar should become visible as there is no scrolling functionality in the small category.

### Actual behavior
The bottom navbar remains hidden until you switch back to the big category and scroll up.

## Other details
[Video](https://imgur.com/a/787Wsxw) demonstrating this.

**Comment by forlorn12** [comment]
I have also noticed this

**Comment by paulo27ms** [comment]
#4819

**Comment by HerrHulaHoop** [comment]
> 
> 
> #4819

The ticket you've linked is not related to the issue mentioned here.
