### ISSUE TITLE
[Bug] Random crashes

### ISSUE THREAD

**Issue by totopesce** [tachiyomiorg/tachiyomi#4899]
-

## Device information
* Tachiyomi version: 0.10.10
* Android version: 7.0
* Device: Samsung galaxy tab s2

## Steps to reproduce
Having the program open, even in backgroung, at random it will crash and restart.

### Expected behavior
Shouldnt crash

### Actual behavior
Crashes, been happening since over a year.

Managed to find where the crash log was, for some reason I couldnt find it. (could add where its being saved when you click on save crash dump)

[tachiyomi_crash_logs.txt]

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6331397/tachiyomi_crash_logs.txt)

(https://github.com/tachiyomiorg/tachiyomi/files/6331390/tachiyomi_crash_logs.txt)

Same as issue #4638

**Comment by arkon** [comment]
```
F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9458 (Profile Saver)
```

**Comment by totopesce** [comment]
I havent been able to find anything about that error except that jt may be a problem with hardware acceleration(turned it off) or a problem with native memory handling, but havent found anything else in days.

**Comment by arkon** [comment]
Create another issue if still happening.
