### ISSUE TITLE
[Feature Request] Lock button for touch presses

### ISSUE THREAD

**Issue by FluffyDiscord** [tachiyomiorg/tachiyomi#4900]
## Why/User Benefit/User Problem
Personally I often swipe somewhat weirdly (I guess not enough) and it's considered as a tap instead of swipe in the reader and because of it, the top and bottom menu shows up. It gets annoying real fast. Simple lock button would do wonders here.

## What/Requirements
At the top left (or right) add lock icon button, which will prevent showing the top and bottom menu, as long as it's activated. Example can be found in the MX Player app (not advertising, just so I am clear on what I would like it to behave as)

**Comment by arkon** [comment]
Not going to implement this, but maybe you could consider using a different navigation layout that better suits however you're holding/touching your device.
