### ISSUE TITLE
[Bug] <When using webtoon reader mode, the app sometimes turn into a black screen and crashes>

### ISSUE THREAD

**Issue by Vedouved** [tachiyomiorg/tachiyomi#4901]
## Device information
*Tachiyomi version: 0.10.10
* Android version: 10
* Device: samsung galaxy a10

## Steps to reproduce
1. Open a chapter in webtoon reader mode.

### Expected behavior
Chapter should load with no issues.

### Actual behavior
The screen turns black and the chapter crashes.

## Other details
It mostly happens with chapters which are laggy when loaded correctly.

**Comment by arkon** [comment]
Same thing as #4890
