### ISSUE TITLE
[Feature Request] Put number of chapters when migrating

### ISSUE THREAD

**Issue by liyahhhhhhh** [tachiyomiorg/tachiyomi#4905]
## Why/User Benefit/User Problem
I'm really having a difficult time migrating my my books because I have to constantly look at the number of chapters of the current extension and the number of chapters in the new extension that I will choose from. To see the number of chapters in the new extension I still have to go to that specific extension, then click the book, then check the number of chapters. I am currently migrating since some of the extensions I use are obsolete.

## What/Requirements
After selecting the Extension to migrate from in the 'Migrate' tab in Browse, the number of chapters are included in each book. In addition, when selecting a new extension to migrate to, the number of chapters in each book also have number of chapters. If you can also add the latest upload date then it would be better.

**Comment by paulo27ms** [comment]
This is the same as requests to add this to normal search. This would mean you'd need to fetch data for each individual manga, making too many requests.
Could still have the first half of your request and include the total/latest chapter of the manga you're migrating somewhere so it's faster to check.

**Comment by liyahhhhhhh** [comment]
youre right
I hope so tho

**Comment by thebrokenfacade** [comment]
@liyahhhhhhh 
Not sure if you will see this, but if you press and hold on the manga cover in the migration search, it does open the manga info page where you can see the number of chapters. Pressing the back button returns to the migration search.

**Comment by arkon** [comment]
#2867
