### ISSUE TITLE
[Bug] navigation button background

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#4908]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. go to library
2. hold tap manga

### Expected behavior
nav button background stay

### Actual behavior
nav button background disappear entirely

## Other details

<table>
<tr>
	<td>currently
	<td>how it should be
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/833716347191033886/IMG_20210419_215059.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/833716044500697108/IMG_20210419_214944.jpg">
</table>

**Comment by arkon** [comment]
It just turns transparent because the bottom nav isn't there. There's a translucent scrim in the next release though, so closing this.

**Comment by Riztard** [comment]
> because the bottom nav isn't there

it is there, but yea the translucent fix it

**Comment by arkon** [comment]
Bottom nav, not system nav.

**Comment by Riztard** [comment]
ah that one 👌
