### ISSUE TITLE
[Bug] Whenever I press resume any manga, the reader opens on the chapter at the bottom of the list, not the one I was reading

### ISSUE THREAD

**Issue by onekowalski** [tachiyomiorg/tachiyomi#4909]
## Device information
* Tachiyomi version: v0.10.11
* Android version: 10
* Device: moto g(9) power

## Steps to reproduce
1. Open any manga, currently reading or not.
2. Tap resume.

### Expected behavior
The reader should open whichever unread chapter would be next. Be it the first chapter of the manga if the manga wasn't started by the user, or the one that follows the latest read chapter (i.e. if I read chapter 53 already, the reader should open chapter 54).

### Actual behavior
The app opens the chapter that is displayed in the bottom of the list. Sorting order doesn't matter, it's always the one that sits at the bottom (i.e. if I sort by chapter number, it will take me to the last chapter numerically).

## Other details
Again, sorting order doesn't matter. And this only started happening with the latest update, which at the date is v0.10.11.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by Mohammed-D** [comment]
I have the same complaint.

Follow the configured chapter sort when:
Tapping the start/resume button

This feature was never needed and is causing an unnecessary hindrance while reading manga.

**Comment by arkon** [comment]
This is fixed in v0.10.12.
