### ISSUE TITLE
[Bug] Always show toast of "Tachiyomi: Left to right" when start reading

### ISSUE THREAD

**Issue by sunbeams001** [tachiyomiorg/tachiyomi#4911]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 9
* Device: Xiaomi 6

## Steps to reproduce
Just read any manga

### Expected behavior
I don't know if it's a feature or bug, but I think it's unnecessary to know the reading order at every time.

### Actual behavior
A toast of "Tachiyomi: Left to right" shows

## Other details

**Comment by ivaniskandar** [comment]
You can disable "Show reading mode" in reader settings to disable the toast.

**Comment by sunbeams001** [comment]
@ivaniskandar Thanks
