### ISSUE TITLE
[Feature Request] Add an option to jump to the migrated manga

### ISSUE THREAD

**Issue by punoqun** [tachiyomiorg/tachiyomi#4915]
## Why/User Benefit/User Problem
With a big library, currently, you have to search or skim through your other manga to find the newly migrated one. 

## What/Requirements
A pop-up asking if you want to go to the migrated manga or an option in the settings to open the migrated manga directly after the migration would be a definite improvement in my eyes.

**Comment by arkon** [comment]
Closed by #5005
