### ISSUE TITLE
[Bug] Last n chapters are downloaded instead of next n chapters in all ascending chapter sort options

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi#4916]
## Device information
* Tachiyomi version: 0.10.11-3306
* Android version: 11

## Steps to reproduce
1. Open a manga
2. Chapter sort in any ascending option
3. Download next n chapters through Download options

### Expected behavior
Next n chapters should be downloaded.

### Actual behavior
Last n chapters are downloaded.

**Comment by arkon** [comment]
This is fixed in v0.10.12.
