### ISSUE TITLE
[Feature Request] <Add manga who u no read in the app>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi#4917]
## Why/User Benefit/User Problem
This will be help the peoples who use the app as a manga list
This will be help the peoples who use the app as a manga list
For example, you buy a mangá at amazon and you would like to add the manga who you buy into tachiyomi to update your list, its possible to do this now (Adding by local font or just add using some extension), but this is dificult

## What/Requirements
My sugestion is a feature who u can add a cover and a name for a manga, without extension or local fonts (just in the UI into the app), you must be able to add trakers too (To set as complete)

I knoow thats not a feature for all users, but i suppose this can be verry helpful for somer users

**Comment by arkon** [comment]
This is a manga reading app, not a tracker app.
