### ISSUE TITLE
[Feature Request] <Custom covers>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi#4918]
## Why/User Benefit/User Problem
This feature may help the user who using backups, the custom covers not moved into the backups, so when u restore one backup the cover return for the original, and thats a problem

## What/Requirements
My suggestion is add an option to link the custom cover to a imgur link or other service, so when you restore a backup the custom cover will be restored too

**Comment by arkon** [comment]
Duplicate of #3851
