### ISSUE TITLE
[Feature Request] Download next to read chapters automatically

### ISSUE THREAD

**Issue by murilo-simio** [tachiyomiorg/tachiyomi#4919]
## Why/User Benefit/User Problem
This feature is specially good for users that can't download all chapters at once and still want to have some chapters downloaded at all times. It's also good for user with poor internet connections, because they can download more chapters as they read. It also helps users that read a lot of chapters at once, but can't afford to store them all at once.

## What/Requirements
The user set a amount of chapters he wants to be downloaded. If the number of downloaded chapter is already that nothing happens, but if it less than that the correct amount should be downloaded. So while a user is reading a series he never has to worry about loading times, e.g.  I'm reading a manga and I'm on chapter 23 out of 300, I've already downloaded up to chapter 33 and I have exclude after read on, when I finish the 23rd chapter tachiy will start downloading chapter 34 to keep it at 10 downloaded chapters.

**Comment by CarlosEsco** [comment]
#3295
