### ISSUE TITLE
Getting this error:-  com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path 

### ISSUE THREAD

**Issue by BikramKumar6928** [tachiyomiorg/tachiyomi#4921]
## Device information
* Tachiyomi version: 0.10.11
* Android version: Android Pie
* Device: Asus X00TD

## Steps to reproduce
1. Open any manga.
2. Click on Resume button
2. See error in toast.

## Issue/Request
Getting this error:-

com.google.gson.stream.MalformedJsonException: Use
JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path 

![Screenshot_20210421-102742_Tachiyomi](https://user-images.githubusercontent.com/24207657/115499844-c7bbe380-a28d-11eb-871d-6d4bbced4781.png)

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by paulo27ms** [comment]
MangaDex is still down. Also wrong repo.

**Comment by BikramKumar6928** [comment]
Ah. So this is related to mangadex?
Ok. Closing this issue.
