### ISSUE TITLE
[Bug] Kitsu tracking didnt work, due couldn't resolve the API url (?)

### ISSUE THREAD

**Issue by krakerz** [tachiyomiorg/tachiyomi#4923]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 10
* Device: Realme 7 Pro

## Steps to reproduce
1. Open any manga from any source
2. Make sure you already logged in @ kitsu tracking
3. Click tracking
4. Add kitsu tracking

### Expected behavior
Search working normally

### Actual behavior
Failed to do the search due pop up error said couldn't resolve the API url

## Other details
tried fresh install, or anything else, the API url still same somehow, and i can't resolve it even with ping etc
here is the url : http://awqo5j657s-dsn.algolia.net/0.0.0.0:443
also attached the image for the toast pic :

![Screenshot_2021-04-21-14-23-43-55_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/8030983/115514021-e336e680-a2ad-11eb-8036-c81a1cf0b6b7.jpg)

**Comment by arkon** [comment]
Works fine for me.

**Comment by krakerz** [comment]
hmmmmm....., i'm probably got the fault one then, due Regional access perhaps
is it DNS problem then?? 
after searching some stackoverflow and some google, it seems its from server side (kitsu side) (probably) by laravel??
https://stackoverflow.com/questions/51609059/could-not-resolve-host-1l9zstkurf-algolia-net
https://www.gitmemory.com/issue/erengy/taiga/958/776499498


if yes RIP then ._.

**Comment by arkon** [comment]
You could try a different network to see if that works, if possible. 

I'm closing this though, since it's not in our control.

**Comment by NuckChorris** [comment]
Kitsu dev here 👋 That's not a valid url, and I don't believe we expose the Algolia url on our end, just the tokens. How are you getting the url to Algolia?

**Comment by arkon** [comment]
We apparently [hit Algolia directly](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt#L234), which was apparently [recommended 3 years ago](https://github.com/tachiyomiorg/tachiyomi/commit/fd825b1049c1c94e9d4907f1f523662c46e463a3#diff-c86ccf475bdb4f3da6e7ee9b2aac62de6ef7690548a7e6324a5b9b540557b592).

I believe the `0.0.0.0:443` part is just part of what's thrown though, not necessarily the fully formed URL it's actually trying to hit.

**Comment by krakerz** [comment]
> You could try a different network to see if that works, if possible.
> 
> I'm closing this though, since it's not in our control.

after changeng some network (trying different VPN, yes it's works fine now

> Kitsu dev here 👋 That's not a valid url, and I don't believe we expose the Algolia url on our end, just the tokens. How are you getting the url to Algolia?

from user standpoint, i just go as the steps i'm described in here, nothing specific need to be do

**Comment by NuckChorris** [comment]
> We apparently [hit Algolia directly](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt#L234), which was apparently [recommended 3 years ago](https://github.com/tachiyomiorg/tachiyomi/commit/fd825b1049c1c94e9d4907f1f523662c46e463a3#diff-c86ccf475bdb4f3da6e7ee9b2aac62de6ef7690548a7e6324a5b9b540557b592).
> 
> 
> 
> I believe the `0.0.0.0:443` part is just part of what's thrown though, not necessarily the fully formed URL it's actually trying to hit.

Ah, good, that's correct behavior! In that case, this is probably just some networking issue. It's quite possible that a "privacy" service like a VPN might blackhole Algolia by returning 0.0.0.0 in the DNS for some reason 🤔

**Comment by krakerz** [comment]
> > We apparently [hit Algolia directly](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt#L234), which was apparently [recommended 3 years ago](https://github.com/tachiyomiorg/tachiyomi/commit/fd825b1049c1c94e9d4907f1f523662c46e463a3#diff-c86ccf475bdb4f3da6e7ee9b2aac62de6ef7690548a7e6324a5b9b540557b592).
> > I believe the `0.0.0.0:443` part is just part of what's thrown though, not necessarily the fully formed URL it's actually trying to hit.
> 
> Ah, good, that's correct behavior! In that case, this is probably just some networking issue. It's quite possible that a "privacy" service like a VPN might blackhole Algolia by returning 0.0.0.0 in the DNS for some reason 🤔

tho in real case, my normal connection that got the error (with static IP), after changed it to VPN, it's works flawlessly, or use DoH feature in another tachiyomi client (TachiyomiSY), my network connection should be using cloudlfare DNS for references
