### ISSUE TITLE
[Feature Request] UI Brightness control

### ISSUE THREAD

**Issue by GMak9** [tachiyomiorg/tachiyomi#4927]
## User Benefit
With these changes will give more practicality when changing light ed or dark environment. 

## What
Particularly, I think with the recent changes in the UI layout my UX has gotten a bit problematic. With the brightness control going to the "bottom" of the UI the step by step for simple change has been boring and tiring

So my suggestion, change in UI, It's putting the brightness control in place of the "trim edges" option or add an option to create shortcuts in the reader for certain settings. 
The focus of the suggestion is to bring the brightness control back to the reader layoutThe focus of the suggestion is to bring the brightness control back to the reader layout.

**Comment by CrepeTF** [comment]
#1720

**Comment by arkon** [comment]
It's still there with the same number of taps. You can long press the settings icon to get to that setting.
