### ISSUE TITLE
[Bug] Downloaded Manga Becomes 0 size

### ISSUE THREAD

**Issue by UchihaItachi1416** [tachiyomiorg/tachiyomi#4929]
https://user-images.githubusercontent.com/49075509/115619395-9edf3100-a315-11eb-9a20-86c6a2431606.mp4

https://user-images.githubusercontent.com/49075509/115619407-a1da2180-a315-11eb-9eb9-0eee4202f8d9.mp4

after updating to 0.10.11 version when I download a manga I can't read it. I can read it online but when I download it it's all a blank black page. So I went to the download location and saw that every files become 0.0byte. When I start downloading the file it writes on storage like 16/17 mb per chapter but when the download is complete it becomes 0.0byte

**Comment by arkon** [comment]
Missing a lot of details here:

- I assume this didn't happen in the previous version (v0.10.10)? If you're willing to try, does this happen in forks as well?
- Does this happen for all manga?
- What phone are you using, and Android version?
- Are you using an SD card? If so, have you tried using internal storage?

**Comment by UchihaItachi1416** [comment]
It happens with all manga.
Android version 7.0 
I don't remember if it happend with previous version, I'm new to this application just installed this few hours ago when this newer 0.10.11 version became available.
It only happens while download location is customized in sd card. 
If I download at /storage/emulated/0/Android/data/eu.kanade.tachiyomi/files   it works perfectly. 
But if I select custom location->sd card->Tachhiyomi (or anyother folder) it happens as same as video.

**Comment by arkon** [comment]
Have you tried a different SD card, if possible? This is potentially an issue specific to your device or SD card.

**Comment by UchihaItachi1416** [comment]
Yes I've tried another sd card. But the result is same. If i use custom location on sd card then fiiles gets 0 byte after downloading it.

**Comment by arkon** [comment]
Unfortunately didn't get enough info to figure out what happened here. I'd encourage you try a different device or at least ROM (it looks like you're using MIUI, which is known to be very buggy).
