### ISSUE TITLE
[Feature Request] To add last read status in manga info or library

### ISSUE THREAD

**Issue by BaccanoMob** [tachiyomiorg/tachiyomi#4930]
Is it possible to add in something like a last read status under the manga information (personally want it there as shown in the pics as green) or in the library as a badge perhaps? 

I feel it's beneficial for the series with hundreds of chapters or with many extras (point chapters) which mislead the remaining chapter count. So it's easier to check which chapter I'm at or last read later quickly rather than scrolling down.

![Screenshot_20210421-224314_Tachiyomi](https://user-images.githubusercontent.com/82655889/115618477-059f2300-a2f3-11eb-9374-55beaa56af2d.jpg)

![Screenshot_20210421-230253_Tachiyomi](https://user-images.githubusercontent.com/82655889/115620655-bc040780-a2f5-11eb-954a-6fe38bff3708.jpg)

In the green boxes, it can written something like

**Currently read:** Chapter 321
Or 
**Last read:** --- (if it's just opened to view)

Or something similar.

 But for the library badge it might be bit tricky if the chapters are having alpha numeric naming I think (like in the second picture) or if it's possible to take first numeric part of the string of the chapter title alone maybe. 

Please do let me know the possibilities of this feature to be implemented.

**Comment by paulo27ms** [comment]
You can: 
-filter read chapters out
-invert the order
You'll always get the one you're on first.

**Comment by BaccanoMob** [comment]
Checked out what you suggested just now. Think that should work too but,

Is it possible to add it to the settings menu to have a default order or filter details? Rather than changing for each and every manga

**Comment by paulo27ms** [comment]
3 dot menu > apply to all

**Comment by BaccanoMob** [comment]
I feel a bit stupid for not noticing it but that's for clarifying quickly! It works as I wanted it to be.
