### ISSUE TITLE
[Bug] Local Manga Cover Page not displayed (Cover File Size might be too big)

### ISSUE THREAD

**Issue by boreslayer** [tachiyomiorg/tachiyomi#4933]
## Device information
Tachiyomi version: 0.10.11
Android version: Android 10, One UI 2.5
Device: Samsung Galaxy Note 9

## Steps to reproduce
1. First step
Add **local** manga to library via "Browse" tab
2. Second step
Catagorize managa to be added into library.  

### Expected behavior
Manga properly categorized and manga cover page to be shown

### Actual behavior
Manga properly categorized but manga cover page not shown

## Other details
I suspect this might be the issue.  

If the cover is a huge file e.g. 10+mb color image, the cover stops working and a black cover (Dark Theme maybe?) is shown instead. Even manually setting the cover page does not fix this issue. However, if I manually select a smaller sized image as a cover page, it works.

Using the latest version (0.10.11) of the app. Older versions of the app didn't have any issues. Can't remember what version I was using previously but I only noticed this issue from 0.10.10 onwards.

**Comment by arkon** [comment]
Potentially addressed by #4870

**Comment by arkon** [comment]
Create another issue if still happening.
