### ISSUE TITLE
[Feature Request] Add an ability to add trackers via extension

### ISSUE THREAD

**Issue by VlasovRoman** [tachiyomiorg/tachiyomi#4934]
## Why/User Benefit/User Problem
It will allow to create and add trackers for custom sites without changes in main repository. 

## What/Requirements
Trackers can be installed like a usual extension from app. 
[ - ] : it will require big code refactoring.
[ - ] : moving all available trackers in extensions
[ + ] : independent  trackers developing 
[ + ] : allow for developers making own trackers

**Comment by Seishirou101** [comment]
duplicate of #4290
