### ISSUE TITLE
[Bug] Virustotal.com 1/62 detected Jiangmin "Trojan/Banker.AndroidOS.bzd"

### ISSUE THREAD

**Issue by runboy93** [tachiyomiorg/tachiyomi#4935]
Last time send "tachiyomi-r3306.apk" to virustotal.com test around 2 days ago and there were no detections.

Just while ago send "tachiyomi-r3312.apk" and now tachiyomi is detected by "Jiangmin" for Trojan/Banker.AndroidOS.bzd

Very likely false detection, but just wanted inform.

**Comment by arkon** [comment]
You're free to audit the code yourself, but that's a false positive.
