### ISSUE TITLE
[Feature Request] Option to update library on source to source basis

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#4939]
## Why/User Benefit/User Problem
Getting updates or updating the library on sources to succeed basis from a single source. I just think updating energy single manga in the library is waste of resource when you 50 , 100 comics from multiple sources.

## What/Requirements
(explain how this feature would behave)
After opening a source in the browse tap using a slide to update all the comics that are advocated with that source

**Comment by Seishirou101** [comment]
You can put them in their own category and update only that category.
