### ISSUE TITLE
[Feature Request] please add support to read .bin files as image

### ISSUE THREAD

**Issue by yooman1213** [tachiyomiorg/tachiyomi#4941]
---

## Why/User Benefit/User Problem
1. Future proofing 
2. maybe faster loading time for downloaded files because of it's native binary reading

## What/Requirements
Please add support to read .bin file as image or any kind of image or media because there's a prove that there is a web that changes their database manga with .bin file so it would load faster 

When downloaded and compressed into .cbz the content would be in .bin file thus rendering it to be unreadable and mark as " no page found ".

What if many popular source start implementing this kind of strategies? It would make the app cannot read any downloaded manga.

**Comment by Seishirou101** [comment]
I meant to post it on this issue, but I accidentally posted it on your comment in the ext repo, but I'll repeat it since the one you responded to doesn't actually match your issue. 

I don't believe that's the case. There was a similar issue and the op said it was because the root dir was in Chinese. (Google translate) #4804 I also verified that your issue #4794 regardless if I download on tachi or sy, I get jpgs like arkon does in #4804

**Comment by arkon** [comment]
Yup, and it already attempts to figure out the image type from the file headers: 

https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L438

**Comment by yooman1213** [comment]
> I meant to post it on this issue, but I accidentally posted it on your comment in the ext repo, but I'll repeat it since the one you responded to doesn't actually match your issue.
> 
> I don't believe that's the case. There was a similar issue and the op said it was because the root dir was in Chinese. (Google translate) #4804 I also verified that your issue #4794 regardless if I download on tachi or sy, I get jpgs like arkon does in #4804

But i use English language

**Comment by yooman1213** [comment]
![Screenshot_20210423-233543_TachiyomiSY](https://user-images.githubusercontent.com/67755845/115902443-a543e900-a48c-11eb-9ecf-ce4c65d2b1f4.jpg)

**Comment by yooman1213** [comment]
https://user-images.githubusercontent.com/67755845/115903246-8d209980-a48d-11eb-87db-1d2714d326db.mp4
