### ISSUE TITLE
[Bug] tachiyomi : download queue crash, dup dir source name renaming on  create

### ISSUE THREAD

**Issue by Wyld-One** [tachiyomiorg/tachiyomi#4945]
## Device information
- Tachiyomi v10.10
- id version: 9

## Source information
- Name: Read Nanatsu no taizai/7 Deadly Sins Manga Online (EN)
- Extension version: ?
newest

## Steps to reproduce
1. First Step
2. Second Step

1 select source
2 select 7 deadly sins
3 favorite (heart)
4 download all chapters

### Expected behavior
Describe what should have happened
downloads all chapters to single dir

### Actual behavi
Describe what happens instead

queue crashes after 33 chapters downloaded. 

## Other details

download dir was on SD external card

after short debug, found multiple renamed dir of the source name with one chapter in each.

rename is a feature of android to avoid saving over same named files

suspect source name too long

crash report:

--------- beginning of main
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: Failed to createFile
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:51:49.836  9540 13723 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: Failed to createFile
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:52:18.935  9540 15455 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: Failed to createFile
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:52:20.975  9540 15452 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: Failed to createFile
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:53:03.831  9540 13728 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: Failed to createFile
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: java.io.FileNotFoundException: Failed to create unique file
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.readParcelable(Parcel.java:2774)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:1945)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:1918)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:56)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createDirectory(DocumentsContractApi21.java:66)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:105)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:54)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:271)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 01:53:04.294  9540 15454 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:764)
[tachiyomi_crash_logs.txt]

**Comment by arkon** [comment]
You can test it in the next preview release if you want.
