### ISSUE TITLE
[Bug] Resume begins from the last chapter 

### ISSUE THREAD

**Issue by vishruth27** [tachiyomiorg/tachiyomi#4949]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 10
* Device: OnePlus 6

## Steps to reproduce
1. Open app
2. Read any chapter of a manga
3. Go back to library
4. Open the manga you've just read
5. Click the resume button

### Expected behavior
Open from the chapter I have last read.

### Actual behavior
Opens the last chapter that exists.

**Comment by arkon** [comment]
#4909
