### ISSUE TITLE
[Bug][Regression] 

### ISSUE THREAD

**Issue by feildmaster** [tachiyomiorg/tachiyomi#4954]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 11
* Device: Pixel 5

## Steps to reproduce
1. Set to portrait or landscape mode
2. Flip screen around

### Expected behavior
Display should rotate 180 degrees

### Actual behavior
Display remains upside-down

## Other details
This used to work in previous versions. Had I known this was removed I'd have not updated. Will be downgrading after making this report. This update is less user friendly as well, requiring many steps to change brightness, which is something that needs to be changed on a case by case basis depending on lighting and the time of day it is.

**Comment by arkon** [comment]
Upside down portrait was never supported.

Sensor-based orientation is still available if you lock it, whereas forced is not sensor-based.

**Comment by feildmaster** [comment]
Never supported? You're saying what I used on a daily basis on previous versions was a bug and the current behavior is the intended behavior?

I see. Guess I can't bother to update anymore then, since the app is perfect in older versions.

**Comment by arkon** [comment]
Rather than be snappy, you're free to contribute a change as you see fit.
