### ISSUE TITLE
The page number gets cut off. 

### ISSUE THREAD

**Issue by HackerThames** [tachiyomiorg/tachiyomi#4955]
## Device information
App version: 0.10.11 (standard, 0eb8d7d, 58)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315GDXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315G
Device product name: a31nsdx

## Steps to reproduce
1. Open reader.

## Issue/Request
The page number was cut off in the new update. (Note: I use swipe gestures).

## Other details
![Screenshot_20210424-143323_Tachiyomi](https://user-images.githubusercontent.com/64459916/115951444-f0044600-a50a-11eb-84e4-82ad1bc5ea64.jpg)

![20210424_144120](https://user-images.githubusercontent.com/64459916/115951483-2e9a0080-a50b-11eb-9b6f-354055c9ea08.jpg)

>

**Comment by arkon** [comment]
Can't reproduce, even on Samsung devices.
