### ISSUE TITLE
[Feature Request] <Anime section>

### ISSUE THREAD

**Issue by webbad** [tachiyomiorg/tachiyomi#4960]
Hi, the is really soo good and i suppose a lot of people who read manga watch  some anime too.

I know this is a manga app, but I would like to propose a simple section for anime (not something as sophisticated as tachiyomi for anime).
If it's okay to add this anime "section" the idea would be this:
to keep that simple, give the possibility to add to the library(or another section for it) in the various tabs as well as manga also the anime to keep track of the seasons / episodes seen and the release of the episodes (date/countdown) with maybe a notification.
this since the app already communicates with anilist, for example, if I'm not mistaken the Api for these functions are open.

**Comment by paulo27ms** [comment]
There's tons of other apps for this, even things that let you watch and update lists ala Tachiyomi.
Seems extremely out of scope.
