### ISSUE TITLE
[Feature Request] Improving reader settings menu usage when dragging instead of sliding

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4961]
App version: 0.10.11-3324 (standard, bf80dd62, 58)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190825.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: davinci
Device model: Mi 9T
Device product name: davinci_eea

## Why/User Benefit/User Problem
The menu just feels a bit clunky and unpredictable if you're trying to drag it instead of using sliding movements.
This is a relatively minor issue because you can just adapt to how the menu expects you to operate it and honestly if fixing this introduces other issues then it's not worth it to change things.

## What/Requirements
Video: https://streamable.com/a78fpx
Issues: 
- A slightly longer tap will change the settings in the dropdown menus, this isn't entirely undesirable but as you can see, sometimes there's barely any delay before it opens the dropdown (second case where a setting changes in the video, it was more of a slide than a drag and the setting changed), it needs to wait for a long tap before it gives the option to change a setting - personally though, this could be disabled entirely to avoid this issue even if it consistently waited for a long tap before showing the dropdown
- Closing the menu by dragging just doesn't work if you are dragging it from the wrong place, you gotta mess around a bit but it'll be clear where you can hold to drag and where you can't for closing the menu, most of the time it actually pushes the menu up, in the case of the general tab sometimes it only shortens the menu, this happens in the other tabs too but not as often

**Comment by arkon** [comment]
Behavior has changed with the recent Compose migration in preview builds.
