### ISSUE TITLE
[Bug] Missing buttons when manga long pressed from "Updates" tab

### ISSUE THREAD

**Issue by T3sT3ro** [tachiyomiorg/tachiyomi#4964]
## Device information
* Tachiyomi version: stable 0.10.11
* Android version: 10
* Device: Huaweii P20 Pro

## Steps to reproduce
1. Long tap any title in the "Updates" tab

### Expected behavior
The same menu as by long-pressing a title in Library should appear.

### Actual behavior
Menu contains only 2 buttons, weirdly spaced to the edges - `download` and `mark [un]read` based on status.
![image](https://user-images.githubusercontent.com/5300963/116006228-853a3400-a60a-11eb-873e-b3a3b22972ac.png)

Even if this is intentional, buttons should be grouped together - NOT looking like Sid's eyes from the Ice Age movie.

**Comment by paulo27ms** [comment]
What other buttons do you expect here?

**Comment by T3sT3ro** [comment]
The same functionality as in the library tab:
- download (already present)
- edit category, delete from library (I don't see why not. My only concern is that it's an action performed on a whole title but in a context menu of just one chapter)
- separate mark read, mark unread (questionable, because it's just one chapter, so the only inbetween state is partially read chapter)

**Comment by Rishi-Goyal** [comment]
Hey! I am new to collaboration and was checking out this issue, and I have run into the problem that even though the item "Delete" and "Mark as Unread" exist in the code, they aren't showing up in the final execution of the build.
If someone can help me out/teach me please let me know. Thank you !

**Comment by arkon** [comment]
@Rishi-Goyal They appear contextually, i.e. the delete icon would only show up if it's downloaded.

I'm hesitant to really change this though, since it's considered consistent with how chapters work. The only thing that _might_ be relevant in that context is the bookmarking actions.

**Comment by Rishi-Goyal** [comment]
@arkon Thank you so much for responding. I will try and understand how you made them contextual soon :)

**Comment by zhaza** [comment]
Hi all, I am new to the app. Great work btw! I have no coding experience, so I couldn't fix this if I wanted to. 
However, I think the Updates tab needs a delete button. Example - After reading the latest released chapter, I would expect the chapter to delete itself from this tab. If not, then one should be able to manually delete the chapter. right?

**Comment by paulo27ms** [comment]
You're asking for a feature. Open another issue. Check if one doesn't exist for that already.

**Comment by vengiare** [comment]
Wait is this still a thing even? Could this be closed? If I recall correctly Updates tab have 3 items in action bar now.

#5984

**Comment by CrepeTF** [comment]
Well, sure. If Author has any qualms then they can make a new issue
