### ISSUE TITLE
[Feature Request] ComicInfo.xml Support for Local Manga

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#4965]
## Why/User Benefit/User Problem
There is no standard for tagging comics/manga, but the ComicRack.xml by ComicRack is widely supported by self hosted services like Ubiqooquity, Komga and Calibre plugins. ComicTagger and MangaTagger use the ComicRack.xml format to automatically tag manga/comics using Anilist or ComicVine metadata, making it much faster and easier to tag things.
## What/Requirements
Tachiyomi would be able to read the xml file from a cbz/cbr file or from the chapter folder, and parse the information outlined in the wiki page
https://wiki.mobileread.com/wiki/ComicRack

Implemented in komga using kotlin like this
https://github.com/gotson/komga/commit/af01d25ede29feb5159e8a800b789f200e6e7e5c

**Comment by Fraetor** [comment]
This format seems to be being maintained here, now that ComicRack is dead:
<https://anansi-project.github.io/docs/category/comicinfo>
Version 2.0 would be much nicer as it allows listing a translator, as well as making the format much more extensible.
