### ISSUE TITLE
[Feature Request] Add toggle to disable double tap zoom

### ISSUE THREAD

**Issue by Myuki** [tachiyomiorg/tachiyomi#4970]
## Why/User Benefit/User Problem
Disable double touch zoom can reduce some palm rejection. And most other comic readers like Perfect Viewer are support to disable this function.

**Comment by benji009** [comment]
Yes, i second this. I tap quite fast through manga by scrolling down.. so i always accidently triggering the zoom function.

**Comment by kigiri** [comment]
Yes, as I don't use it, I would also like to be able to skip pages faster and avoid accidental zooms

**Comment by arkon** [comment]
Duplicate of #4145
