### ISSUE TITLE
captcha loop

### ISSUE THREAD

**Issue by srrisco** [tachiyomiorg/tachiyomi#4974]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 10
* Device: S9+

## Steps to reproduce
1- explore
2- choose the source
3- webview
4- solve captcha
5- rescued captcha
6- solve captcha
...

### Expected behavior
captcha resolved access to the source website

### Actual behavior
Getting a captcha loop

## Other details
source used: mangahost, unionmanga

**Comment by alessandrojean** [comment]
These sources are actively blocking Tachiyomi requests, and there's nothing that can be done on the extension side. You can migrate to other sources.

**Comment by srrisco** [comment]
Thanks for the answer. 
sorry I thought it was the right place to ask,

I tried to migrate my library to the only Portuguese source that works for me, Yes mangas, but it gives me error 403

**Comment by alessandrojean** [comment]
HTTP error 403 means Forbidden. I might be wrong, but from what I now, Yes Mangas is just a mirror of MangaHost, so probably they are blocking Tachiyomi too. Test other sources and check what works best for you before migrate.
