### ISSUE TITLE
[Bug] <Download Unsuccessful - not enough free space>

### ISSUE THREAD

**Issue by jhynzar** [tachiyomiorg/tachiyomi#4975]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 8.1.0
* Device: Asus Zenfone 4 Max

## Steps to reproduce
1. Not enough free space on device
2. Try to update extensions
3. Clear space and have ENOUGH free space
4. Update the extensions 

### Expected behavior
The Extensions will be updated and the notifications for "not enough free space" will be removed

### Actual behavior
The Extensions are updated, but the "not enough free space notification is still there. Also, it displays again every time I update/install any extensions

## Other details
Additional details and attachments.
![Screenshot_20210428-114734.jpg](https://user-images.githubusercontent.com/24986853/116360790-d9bff800-a832-11eb-8b68-e2dfeef47e35.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

--------- beginning of system --------- beginning of main 04-28 15:03:05.149 32102 32110 E System : Uncaught exception thrown by finalizer 04-28 15:03:05.150 32102 32110 E System : java.lang.AssertionError: Failed to close dex file in finalizer. 04-28 15:03:05.150 32102 32110 E System : 	at dalvik.system.DexFile.finalize(DexFile.java:336) 04-28 15:03:05.150 32102 32110 E System : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250) 04-28 15:03:05.150 32102 32110 E System : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237) 04-28 15:03:05.150 32102 32110 E System : 	at java.lang.Daemons$Daemon.run(Daemons.java:103) 04-28 15:03:05.150 32102 32110 E System : 	at java.lang.Thread.run(Thread.java:764) App version: 0.10.12 (standard, 6aff438, 59) Android version: 8.1.0 (SDK 27) Android build ID: OPM1.171019.011.WW_Phone-15.2016.1907.519-0 Device brand: asus Device manufacturer: asus Device name: ASUS_X00IDB Device model: ASUS_X00ID Device product name: WW_Phone

**Comment by arkon** [comment]
That's the Android download manager, not even ours. How much space do you have?

**Comment by jhynzar** [comment]
> That's the Android download manager, not even ours. How much space do you have?

Oh, you're right. The Extensions are installed like other apps. I haven't thought of that, sorry. I solved the issue after clearing the cache and data of download manager. Thanks for guiding me to the right direction!
