### ISSUE TITLE
[Feature Request] Can find same manga title/name but in categories/library

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#4977]
## Why/User Benefit/User Problem
It can knew if the title already added to library or not

## What/Requirements
It can find same manga title like find it through source (when you press the title you will find manga on another source with same title) but it through library.
If possible, it can also narrow which categories that we will find it.

**Comment by paulo27ms** [comment]
Having a hard time figuring out what you're trying to say.
Can you give some examples like screenshot mockups of what you want this to look like/do?

**Comment by HapyEnding** [comment]
![Search](https://user-images.githubusercontent.com/82807360/116821008-217fb000-aba2-11eb-965d-c6dafd011ff7.jpeg)

**Comment by Lightjohn** [comment]
I would also be interested by that feature as well, when you have a full library of manga but some are on sources that are slow or not updated it would nice to quickly have something like the "migrate" but just to start a search to see the current title compared to other sources.

**Comment by arkon** [comment]
The app now prompts you when first adding something to the library with the same name.

Issue tracking adding the same when long pressing from source list: #6640

**Comment by paulo27ms** [comment]
I'm not sure that's what this was about? I think they wanted a search similar to global search but in the library itself.

**Comment by arkon** [comment]
It was to find library entries with the same name, but the prompt when adding addresses the root issue.
