### ISSUE TITLE
[Feature Request] Erase old manga history after migrating its source.

### ISSUE THREAD

**Issue by LuDColl** [tachiyomiorg/tachiyomi#4979]
---

## Device information
* Tachiyomi version: 0.10.11
* Android version: 11
* Device: Galaxy M31

## Steps to reproduce
1. migrate the manga
2. access it through history

### Expected behavior
Open the manga with the new source

### Actual behavior
Open the manga with the old source

## Other details
If you open the manga through the library, your history will be doubled.

**Comment by paulo27ms** [comment]
Not sure if history gets migrated.
I'm assuming you're doing a full migration and not a copy right?
Go to advanced settings and clear your database and the old one will probably disappear from history.
Whether it's a bug or not that history isn't copied I'm not sure.

**Comment by LuDColl** [comment]
I didn't know about this functionality, thank you very much.  It would be nice if migrating the source of manga migrates the history as well.

**Comment by LuDColl** [comment]
Can someone change the label of the issue to feature, I don't think I have authorization for that.

**Comment by joseph619** [comment]
History is not saved for manga that's not in library, so it's technically already deleted when you migrate.

**Comment by Riztard** [comment]
> History is not saved for manga that's not in library, so it's technically already deleted when you migrate.

it is saved, but not in backup

**Comment by arkon** [comment]
We generally don't automatically delete history anyway, so this doesn't seem to align with how the app normally behaves.
