### ISSUE TITLE
[Feature Request] Add second local search layer

### ISSUE THREAD

**Issue by Markus40** [tachiyomiorg/tachiyomi#4981]
## Why/User Benefit/User Problem
I have thought about whether this is more of an extension problem but I think it could be a good feature for the main app. Tachiyomi seems to be completely dependent on the website search algorithm. The site "Method Scans", for example, does not have a working search and just dumps every title (all 4 of them) into the list of results in global search.

## What/Requirements
A optional secondary local search algorithm could filter out these results. If it is implemented in the main app not every extension with search-problems has to implement an individual solution and can just use the already available local search.

Users could also use a slower search option that looks at every title on every site but uses the local search and is independent from the different website search algorithms. This is probably impractical for the larger aggregator sites with thousands of titles but could still be useful for smaller sites.

**Comment by CarlosEsco** [comment]
What do you even mean by local search? Can you provide an example?

**Comment by CrepeTF** [comment]
@CarlosEsco they probably mean for search to show the browse results, but have it programmatically hide the results not matching the search

**Comment by Markus40** [comment]
@CarlosEsco When I say local search i am thinking of an algorithm that runs on the smartphone instead of using the search function that is provided by a website.

This could be used if a website does not provide search. It could hide bad search results or completely replace the website search if it is subpar and ot could be used to order the global search results from different websites.

**Comment by CarlosEsco** [comment]
This wouldn't work at all, because tag and other information is not know to tachiyomi until a user actually clicks into the manga

**Comment by arkon** [comment]
Yeah, that's not going to happen. Search is complicated. Search across multiple languages is even more complicated (a majority of users are not from primarily English speaking countries).

Even if we did do a filter over the data that the site returns, we'd need the data in the first place. It's fine in the case of a source that only ever returns 4 things regardless of what you search, but what about other sources?

**Comment by Markus40** [comment]
Thats a pity. I hoped to at least get sorting of the sites in global search. It is pretty annoying when there are multiple sources where the only word that matches is "The" and the site with a perfect match is buried below because the sites with results are sorted alphabetically.
