### ISSUE TITLE
[Feature Request] <Exclude Categories from being updated>

### ISSUE THREAD

**Issue by Yuricchi** [tachiyomiorg/tachiyomi#4984]
## Why/User Benefit/User Problem
People who have many categories with tons of entries from which they need to update only a few will get significantly shorter update time of everything, because the 1 or 2 categories filled with something won't update and therefore won't bloat the whole update process

## What/Requirements
User checks a mark in the "Categories" setting next to each one they have created (or have some disable button added) which disables/enables updating of said category

**Comment by arkon** [comment]
You can already do this in Settings > Library > Categories
