### ISSUE TITLE
[Feature Request] Double Page view (opposite of dual-page split)

### ISSUE THREAD

**Issue by omfganimal** [tachiyomiorg/tachiyomi#4985]
Hello, I'd like to kindly request a double page viewer mode. This mode basically combines pages, unlike the page splitter, and shows them adjacent to each other, two at a time. It could potentially combine two images while vertical, or just when one's phone is rotated horizontally. I think it'd be best only when horizontal, like in the following example: https://imgur.com/a/VCGE8Xj (amazon kindle. Video is only weird because I started recording when rotated vertically). This is the same as the double page view on MangaDex. This would benefit users by being able to view pages that are meant to be read together that are split to begin with and even give greater immersion as if you're reading a book (as many manga series cater to works actually being read like this). In case the scan group or whomever would not be aware of lining up the pages correctly, I'd suggest making an easy-to-access option that allows to offset the double page viewer by one, in case it is misaligned due to the content being poorly handled by the content providers. Consideration of this feature would be immensely appreciated🙇‍♀️

**Comment by CarlosEsco** [comment]
Duplicate please search issues before opening one..
