### ISSUE TITLE
[Feature Request] Can show how many manga chapter when search manga on source (not on library)

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#4986]
## Why/User Benefit/User Problem
It's can know how many chapter when we search manga on source

## What/Requirements
show chapter like on library

**Comment by CarlosEsco** [comment]
It's been declined before.  99% of sources don't have chapter totals in search.  This means anytime you search a source you would need to N times more calls for however many manga there are.  It's not worth make sources hate tachi more
