### ISSUE TITLE
[Feature Request] Cut only upper and lower borders option

### ISSUE THREAD

**Issue by nboroboid** [tachiyomiorg/tachiyomi#4988]
## Why/User Benefit/User Problem
When reading a webtoon some of them have text boxes that go into the empty lateral space, but some of the following or previous pages don't go beyond that, so when the borders are cut the images end up mismatched.

#### Before cutting 
![Screenshot_20210430-111630](https://user-images.githubusercontent.com/83466416/116725205-40feb900-a9a7-11eb-8b46-3d9fa43c5330.jpg)

#### After cutting
![Screenshot_20210430-111643](https://user-images.githubusercontent.com/83466416/116725235-46f49a00-a9a7-11eb-837d-b1c6ae979473.jpg)

## What/Requirements
- Add a sub-option to only cut the upper and lower borders in the webtoon reader?

**Comment by arkon** [comment]
Closing in favour of #4995
