### ISSUE TITLE
[Bug] Trackers not working

### ISSUE THREAD

**Issue by myhtiical** [tachiyomiorg/tachiyomi#4989]
---

## Device information
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1819
Device model: vivo 1819
Device product name: 1819
## Steps to reproduce
1. First step
2. Second step

### Expected behaviors
Before it was ok like 2 days ago and now it stopped tracked my manga
### Actual behavior
The trackers for myanimelist not working

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Log in again if it's giving you HTTP 401 errors.
