### ISSUE TITLE
[Bug] Android 6 - android version is no longer supported

### ISSUE THREAD

**Issue by silvercrow07** [tachiyomiorg/tachiyomi#4992]
## Device information
* Tachiyomi version: 0.10.12-3328 (standard, 6aff438a, 59)
* Android version: 6.0.1 (SDK 23)
* Android build ID: MMB29P.WW_Phone-13.8.26.113-20180123
* Device brand: asus
* Device manufacturer: asus
* Device name: ASUS_Z010_2
* Device model: ASUS_Z010D
* Device product name: WW_Phone

## Steps to reproduce
1. Touch MORE TAB
2. touch ABOUT
3. Touch CHECK FOR UPDATES

### Expected behavior
update app version  / no update available 

### Actual behavior
This android version is no longer supported 

## Other details
NA

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Yeah, that wasn't intentional but can't really do much about it at this point. When the next stable release is out, you'll need to manually download it from GitHub or the website.
