### ISSUE TITLE
Unable to restore backup from an older phone (android 4.4.4)

### ISSUE THREAD

**Issue by Bangistus** [tachiyomiorg/tachiyomi#4993]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 9
* Device: ZTE Blade A3 2020

## Steps to reproduce
1. Create backup on the phone I'm moving from
2. Restore backup on my new phone

### Expected behavior
Restoring backup successfully

### Actual behavior
Restore gets completed in 01 sec with 234 errors (nothing gets restored)
## Other details
I don't know if it's because of my old phone, if it's because of android 4.x not being supported anymore then please notify me, I have no clue

**Comment by arkon** [comment]
What do the errors say?

**Comment by Bangistus** [comment]
> What do the errors say?

A bunch of numbers, title and "source not found" for all the manga on my library. Just realized it may be because I haven't installed any extensions, I'm dumb, I'll go check it out and comment again if it doesn't work

**Comment by Bangistus** [comment]
So I tried again after installing the extensions and only got like half of my manga, everything else had the same error as before (source not found), also didn't get anything else besides the manga, no tracking and history and all that

**Comment by paulo27ms** [comment]
Note that if you were on an old phone you might be on old sources. There's extensions which just don't exist anymore and Mangadex is also currently down. What sources are you using on your old phone?
Does the log not tell you the errors in more detail?

**Comment by Bangistus** [comment]
> Note that if you were on an old phone you might be on old sources. There's extensions which just don't exist anymore and Mangadex is also currently down. What sources are you using on your old phone?
> Does the log not tell you the errors in more detail?

I tried redownloading the sources that were giving errors and it worked except for mangadex and mangarock which makes sense I suppose. And the log really doesn't tell me much, only the titles of the manga that gives errors and the source

**Comment by paulo27ms** [comment]
> and the source

And what other sources are those? We still won't know what's wrong without knowing what else is wrong.
Did the backup complete normally except for MD and MR or is there still some manga missing?

**Comment by Bangistus** [comment]
I guess there's some compatibility thing going on since it doesn't seem like I can transfer any data from the older versions beside manga titles, I'll try to download the same version and restore backup there. I guess the problem is technically solved so I'll close the issue. Thanks for the help
