### ISSUE TITLE
[Bug] 'Require unlock' feature breaks app with no finger print reader

### ISSUE THREAD

**Issue by slughappy1** [tachiyomiorg/tachiyomi#4999]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Galaxy Tab A (SM-T510)

## Steps to reproduce
1. Go to More, Settings, Security
2. Turn on Require unlock
3. Lock when idle doesn't matter as it happens on all values
4. Get out of the app by either going home or locking the device
5. Open app
6. App closes without fully opening

### Expected behavior
Require entering unlock pin same as lock screen

### Actual behavior
The app doesn't open and instead immediately closes.

## Other details
This feature works just fine on my phone with a finger print reader, but not on my tablet which doesn't have a finger print reader. Once this feature is enabled, the only way to get the application to be able to open again is to clear app data. I am unsure how to dump crash logs as the application cannot open until I clear the app data.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Alternate ways of getting logs:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by DraHD** [comment]
This bug also happens on Oculus Quest 2. It has no other way of unlocking beside in-app pincode.

In case of confusion, Oculus Quest 2 is an android devices, so it can run any apk file natively.

**Comment by GunbleR** [comment]
also experiencing crash, probably because of lack of fingerprint reader.
unable to open app at all after setting the lock, untill app data clear.
release log:
   E/BiometricFragment: Biometric hardware unavailable

using tachiomiSY
App version: 1.7.0 (standard, 51a1092, 19, 2021-06-02T00:51Z)
Preview build: 0
Android version: 10 (SDK 29)
Android build ID: TB-J606F_S120025_210107_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: J606F
Device model: Lenovo TB-J606F
Device product name: LenovoTB-J606F_PRC

[catlog.txt](https://github.com/tachiyomiorg/tachiyomi/files/6678257/catlog.txt)
[2021-06-18-release.log](https://github.com/tachiyomiorg/tachiyomi/files/6678258/2021-06-18-release.log)

**Comment by arkon** [comment]
@slughappy1 @DraHD @GunbleR Can you install this app and share what it says? https://github.com/arkon/android-system-info-dumper/releases/tag/v1.0

**Comment by DraHD** [comment]
> @slughappy1 @DraHD @GunbleR Can you install this app and share what it says? https://github.com/arkon/android-system-info-dumper/releases/tag/v1.0
Here is mine:
`Device info
Android version: 10 (SDK 29)
Android build ID: user-17007100222900000
Brand: oculus
Manufacturer: Oculus
Name: hollywood
Model: quest
Product name: hollywood
ABIs: arm64-v8a, armeabi-v7a, armeabi}

Biometrics info
Supported: true
Is legacy: true
Device credentials allowed: true
Strong: false
Weak: false
Device credentials: false

App info
App version: 1.0 (1)`

**Comment by slughappy1** [comment]
@arkon Here you go:

Device info
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T510XXU5CUF4
Brand: samsung
Manufacturer: samsung
Name: gta3xlwifi
Model: SM-T510
Product name: gta3xlwifixx
ABIs: armeabi-v7a, armeabi}

Biometrics info
Supported: true
Is legacy: false
Device credentials allowed: true
Strong: false
Weak: false
Device credentials: true

App info
App version: 1.0.(1)

**Comment by GunbleR** [comment]
Device info
Android version: 10 (SDK 29)
Android build ID: TB-J606F_S120025_210107_ROW 
Brand: Lenovo 
Manufacturer: LENOVO 
Name: J606F
Model: Lenovo TB-J606F 
Product name: LenovoTB-J606F_PRC 
ABIs: arm64v8a, armeabi-v7a, armeabi}

Biometrics info
Supported: true
Is legacy: true
Device credentials allowed: true
Strong: false
Weak: false
Device credentials: false

App info
App version: 1.0.(1)
