### ISSUE TITLE
[Bug] <The download feature's kinda bugged, can't download some manga and webtoon even though there's the folder created and file is saved as temp, tried renaming it but couldn't (on phone)>

### ISSUE THREAD

**Issue by phoenix2z** [tachiyomiorg/tachiyomi#5000]
## Device information
* Tachiyomi version: Version 0.10.12-3328
* Android version: Android 11
* Device: Nokia 8.1

Additional details and attachments.
Download location is set to custom location: SD card and I even tried changing it but the results same.
This problem persists in some manga and webtoon and in Kingdom from Sense scans previous 10 chapters are Downloaded and the latest one's saved as temp and there's just a warning symbol when download finishes and the file is saved as temp. I thought that the chapter was broken or something and now the problem occurs in a webtoon can't even download a single chapter all chapters are saved as temp and download again when try to view them.

**Comment by arkon** [comment]
Create another issue if still happening.
