### ISSUE TITLE
[Bug] rendering of pages is not proper

### ISSUE THREAD

**Issue by psychopomp9** [tachiyomiorg/tachiyomi#5001]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 9
* Device: redmi y2

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Every part of a page should be same.

### Actual behavior
Some part of few pages is larger/smaller than usual(normal).

## Other details
Attaching ss
![Screenshot_2021-05-01-12-12-12-381_eu kanade tachiyomi](https://user-images.githubusercontent.com/67730075/116795346-47259000-aaa2-11eb-9e6d-67098bdd2ec2.jpg)

**Comment by psychopomp9** [comment]
![Screenshot_2021-05-01-17-26-30-496_eu kanade tachiyomi](https://user-images.githubusercontent.com/67730075/116795355-63c1c800-aaa2-11eb-957a-cddc309836b5.jpg)

**Comment by arkon** [comment]
Crop borders generally doesn't work well for webtoons because of this, but it's working as intended.
