### ISSUE TITLE
[Bug] <App crashes when clicking search button in settings>

### ISSUE THREAD

**Issue by Qabbout** [tachiyomiorg/tachiyomi#5002]
App version: 0.10.12-3346 (standard, cb203ef0, 60)
Android version: 10 (SDK 29)
Android build ID: BLA-L29 10.0.0.159(C185E4R1P3)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWBLA
Device model: BLA-L29
Device product name: BLA-L29

## Steps to reproduce
1. Go to settings
2. Click search icon

### Expected behavior
Should show a search screen/inputfield.

### Actual behavior
The app crashs.

## Other details

Crash logs:

-------- beginning of system
--------- beginning of main
05-02 04:35:27.226 16581 16656 E SQLiteLog: (284) automatic index on C(manga_id)
05-02 04:35:27.226 16581 16656 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-02 04:35:27.394 16581 16622 E         : APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
App version: 0.10.12-3346 (standard, cb203ef0, 60)
Android version: 10 (SDK 29)
Android build ID: BLA-L29 10.0.0.159(C185E4R1P3)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWBLA
Device model: BLA-L29
Device product name: BLA-L29

**Comment by arkon** [comment]
Hi, that log doesn't seem to include the crash. Can you make it crash again and post the logs generated after that?

**Comment by Qabbout** [comment]
I tried again, similar logs:


--------- beginning of system --------- beginning of main 05-02 20:19:39.429 17448 17509 E SQLiteLog: (284) automatic index on C(manga_id) 05-02 20:19:39.429 17448 17509 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-02 20:19:39.584 17448 17488 E : APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils App version: 0.10.12-3346 (standard, cb203ef0, 60) Android version: 10 (SDK 29) Android build ID: BLA-L29 10.0.0.159(C185E4R1P3) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWBLA Device model: BLA-L29 Device product name: BLA-L29

Here's a video for the crash [crash](http://imgur.com/a/UrJZUM0)
