### ISSUE TITLE
[Bug] Tachiyomi browse in not working

### ISSUE THREAD

**Issue by Bbk2468** [tachiyomiorg/tachiyomi#5003]
*PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- I will fill out the title and the information in this template

Note 

## Device information
* Tachiyomi version: 0.10.12
* Android version: Android 11
* Device: Samsung M21

## Steps to reproduce
1. Open apps
2. Browse the manga

### Expected behavior
Apps is running normally

### Actual behavior
Most of the extension is not working. Only work on webview.
## Other details
![Screenshot_20210502-083753_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800563-0cfbd300-ab22-11eb-8ec3-f4e94ceb7b65.jpg)
![Screenshot_20210502-083803_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800572-27ce4780-ab22-11eb-944a-5b307e7b8200.jpg)
![Screenshot_20210502-083934_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800573-29980b00-ab22-11eb-86c3-c9a21ae4c76f.jpg)
![Screenshot_20210502-083949_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800574-2a30a180-ab22-11eb-9c55-f461e4e81817.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Refer to the troubleshooting guide. If it doesn't work, consult support on Discord or open issues for the individual extensions in the correct repo.
