### ISSUE TITLE
Ability to move page slider when reading manga up or down. 

### ISSUE THREAD

**Issue by sarweshMaharjan** [tachiyomiorg/tachiyomi#5006]
## Why/User Benefit/User Problem
The benefit of having a switch to move page slider up or down are as follows. 
+ Individual with tiny hands like me mistakenly press "page slider" that in result changes the page. 
+ We would like the page slider and if we could move it up, it be less likely for us to hit it by mistake as we are reading manga. 
+ Small screen devices also have high chances of mistakenly pressing "page slider" again and again. 

## What/Requirements
In the manga reader setting, a switch that can change the position of the page slider to up or bottom. Or hide or unhide.

**Comment by CrepeTF** [comment]
#4874
