### ISSUE TITLE
[Bug] download queue still download deleted chapter

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi#5010]
## Device information
* Tachiyomi version: 0.10.2
* Android version: 7.1.1
* Device: xiaomi mi max 2

## Steps to reproduce
1. From library, select a title. choose trash bin from below toolbar
2. Chose remove downloaded chapter
3. The chapter is deleted from queue, but it still downloaded

### Expected behavior
The deleted chapter should not be downloaded and fully deleted from queue

**Comment by arkon** [comment]
Closing in favour of https://github.com/tachiyomiorg/tachiyomi/issues/7492
