### ISSUE TITLE
[Bug] <crash>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi#5011]
## Device information
* Tachiyomi version: r3346 and sy dev build 361
* Android version: 10
* Device: samsung galaxy a31

## Steps to reproduce
1- open the app
2-Search manganelo for king of apocalypse
3-open chapter 307

### Expected behavior
The chapter should open normally

### Actual behavior
The app crashes

## Other details

Crash logs

--------- beginning of main 05-03 10:46:37.672 29493 29493 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000 --------- beginning of system 05-03 10:46:42.234 29493 29734 E SQLiteLog: (284) automatic index on C(manga_id) 05-03 10:46:42.234 29493 29734 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-03 10:46:42.340 29493 29671 E gralloc : Arm Module v1.0 05-03 10:46:42.342 29493 29671 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-03 10:46:55.922 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:46:55.994 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:46:57.346 29493 29493 E ViewRootImpl: sendUserActionEvent() mView returned. 05-03 10:47:03.630 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:47:03.690 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:47:04.894 29493 29493 E ViewRootImpl: sendUserActionEvent() mView returned. 05-03 10:47:15.663 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:47:15.713 29493 29493 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:47:16.796 29493 29493 E ViewRootImpl: sendUserActionEvent() mView returned. 05-03 10:47:20.888 29493 29493 E tachiyomi.debu: Invalid ID 0x00000000. 05-03 10:47:54.587 26454 26454 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000 05-03 10:48:02.317 26454 31862 E gralloc : Arm Module v1.0 05-03 10:48:02.323 26454 31862 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-03 10:48:34.012 1134 1134 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000 05-03 10:48:38.443 1134 2661 E SQLiteLog: (284) automatic index on C(manga_id) 05-03 10:48:38.443 1134 2661 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-03 10:48:38.601 1134 2600 E gralloc : Arm Module v1.0 05-03 10:48:38.605 1134 2600 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-03 10:48:49.240 1134 1134 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:48:49.351 1134 1134 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:48:50.404 1134 1134 E ViewRootImpl: sendUserActionEvent() mView returned. 05-03 10:48:51.273 1134 1134 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:48:51.340 1134 1134 E DecorView: mWindow.mActivityCurrentConfig is null 05-03 10:48:52.338 1134 1134 E ViewRootImpl: sendUserActionEvent() mView returned. 05-03 10:49:42.692 2364 2364 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000 05-03 10:49:48.339 2364 4174 E gralloc : Arm Module v1.0 05-03 10:49:48.345 2364 4174 E ion : ioctl c0044901 failed with code -1: Invalid argument App version: 0.10.12-3346 (standard, cb203ef0, 60) Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

**Comment by arkon** [comment]
Your device is probably too weak and/or has too little memory to handle the massive images. #4791 (or similar) may address it.

As a workaround, find a source that serves the chapter with smaller images.

**Comment by dmswd** [comment]
Regarding this
I found another workaround 
Setting side padding to 20%
Solved the problem and it didn't crash again
