### ISSUE TITLE
[Feature Request] <Ability to have custom sound notification, per category>

### ISSUE THREAD

**Issue by Rodark** [tachiyomiorg/tachiyomi#5014]
## Why/User Benefit/User Problem

It improves customization, makes it a fun experience for the user adding their own sound notifications, is immediately informed which of their categories have a manga update

## What/Requirements

My idea is this. I personally have 4 categories on the app. Currently it allows me to have a checking for downloads sound and a chapter found sound.
Id love to have the ability to have a custom notification sound per category. So, DC has an update? My Batman sound effect, Marvel has an update? Iron Man effect. Manga has an update? insert x anime notification sound.

**Comment by arkon** [comment]
Same as https://github.com/tachiyomiorg/tachiyomi/issues/6324#issuecomment-1287471446; don't really want to add the complexity of associating different categories with separate notification channels.
