### ISSUE TITLE
[Feature Request] Mark unread any below

### ISSUE THREAD

**Issue by Auno94** [tachiyomiorg/tachiyomi#5015]
**PLEASE READ THIS**

---

## Why/User Benefit/User Problem
With long running series it can be interesting to do a re-read. For download purposes or just out of convienience it can be nice set a series as "unread". Right now we can only mark chapters as unread by marking on bulk or individual

## What/Requirements
Could be simple as a "Mark all" and then we can do the "unread" ourself or same as the "mark chapters below as read" just for unread

**Comment by arkon** [comment]
That seems like a bit too niche to warrant adding a new menu item (especially with the space constraints). You can easily do a mass selection of items by long pressing the first item and then long pressing the second item though to select everything in between.
