### ISSUE TITLE
[Bug] Rotating the device kicks you back to the source lost

### ISSUE THREAD

**Issue by MxBlu** [tachiyomiorg/tachiyomi#5017]
## Device information
* Tachiyomi version: App version: 0.10.12-3346 (standard, cb203ef0, 60) r3346
Android version: 11 (SDK 30)
Device brand: samsung
Device manufacturer: samsung
Device name: o1s
Device model: SM-G991B
Device product name: o1sxxx

## Steps to reproduce
1. Visit any screen past sources (e.g. Source "latest", chapter list, chapter)
2. Rotate the screen
### Expected behavior
The same screen should be rendered, but rotated

### Actual behavior
For screens other than chapter, it will kick you back to the sources list. For chapter, you will be kicked back if you exit the chapter.

**Comment by arkon** [comment]
Already fixed for the next preview release.
