### ISSUE TITLE
[Bug] Page not found

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#5019]
## Device information
* Tachiyomi version: Stable 0.10.12
* Android version: 11
* Device: Oppo

## Steps to reproduce
1. Open the manga
2. Click the chapter

### Expected behavior
The manga opened

### Actual behavior
Not page found

## Other details
The manga will not be able to read (no page found) and i need to migrate it one by one. 
This happen quite many time usually whenever the source got update. 
The extensions is manytoon.
I tried tips on [https://github.com/tachiyomiorg/tachiyomi/issues/1461](url) but still like this.
Already do the troubleshooting thing

**Comment by paulo27ms** [comment]
There's nothing to be done. Also, should be in https://github.com/tachiyomiorg/tachiyomi-extensions
