### ISSUE TITLE
[Feature Request] Adding an option to change zoom percentage when double tapping.

### ISSUE THREAD

**Issue by suvakhiiin** [tachiyomiorg/tachiyomi#5020]
## Why/User Benefit/User Problem
Because the current double tap zoom gives A LOT of zoom. Adding this option would make one handed app usage a lot easier, since the only "acceptable" way to zoom requires two hands.

## What/Requirements
No big effort needed. Just an option in the settings to put a preset percentage.

Or

A slider in the settings, so the user can put his own ideal percentage.

(By the way, sorry for my bad English. English is not my main language.)

**Comment by Seishirou101** [comment]
duplicate of #228
