### ISSUE TITLE
[Feature Request] Provide multi thread download support for download function

### ISSUE THREAD

**Issue by XGMO9** [tachiyomiorg/tachiyomi#5021]
---

## Why/User Benefit/User Problem
My network speed is up to 10m / s, but the download speed of comic books is only 300KB / s. I think multi thread download support can improve this problem. Thank you very much

## What/Requirements
Provide multi thread download support for download function

**Comment by joseph619** [comment]
Declined in #1567 which mentions why it won't be added

**Comment by XGMO9** [comment]
ok,thank you
