### ISSUE TITLE
[Feature Request] <Pause Icon>

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5023]
## Why/User Benefit/User Problem
When viewing manga chapters, it would be easy to see the difference between downloading chapters and paused chapters without checking the download queue and the download icon doesn't annoyingly keep flashing when the queue is paused. 

## What/Requirements
Chapter icons should indicate a paused sign of chapters in the queue when queue is paused.

**Comment by arkon** [comment]
There's the concept of a paused queue, but not a paused chapter download.
