### ISSUE TITLE
[Bug] <Swiping Function>

### ISSUE THREAD

**Issue by Nomore32** [tachiyomiorg/tachiyomi#5030]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Samsung A8 Star

## Steps to reproduce
1. Setting → Reader → Default Reading Mode → Choose Right to Left or Left to Right
2. Go read a manga and swipes Right to Left

### Expected behavior
Swiping From The Right to left will go to the next page

### Actual behavior
Goes to the previous chapter

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by CarlosEsco** [comment]
> Setting → Reader → Default Reading Mode → Choose Right to Left or Left to Right
Well if you choose left to right and then swipe right to left, you are going backwards...

**Comment by Nomore32** [comment]
But the thing is i chose left to right that didnt work then right to left
that also didnt work and it goes to the same direction each time want a
video of it?

**Comment by CarlosEsco** [comment]
sure that will help

**Comment by Nomore32** [comment]
Here you go

**Comment by Nomore32** [comment]
So....how do i fix it?

**Comment by arkon** [comment]
You didn't post a video.

**Comment by Nomore32** [comment]
https://youtu.be/0tI1JMM40QQ

**Comment by arkon** [comment]
Your uploaded a video that's mostly just a black screen....

**Comment by Nomore32** [comment]
Wut...

**Comment by Nomore32** [comment]
HAAAAAAAAAAAAA...wait a few

**Comment by Nomore32** [comment]
Ok..i think it just doesnt save as default that i changed, it just saved
the default to what it defaulted to

**Comment by Nomore32** [comment]
https://youtube.com/shorts/9UKjaFKIhtI?feature=share

**Comment by Nomore32** [comment]
So...i think all i have to do is just keep on ticking the default option on
each manga for it to be fixed

**Comment by arkon** [comment]
I think this is a duplicate of #5068. Closing this one since the other issue has more descriptive content.
