### ISSUE TITLE
[Feature Request] Include "Cover" When Migrating to Another Extension 

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#5031]
## Why/User Benefit/User Problem
When Migrating manga To a different Extension It gives/provide the different Cover. 
I think it is More Organized if Ypu migrate and use the Former Cover and Use it to the Next Migrate
(Like Todays Current Mangadex, when Migrating There is no Cover, I think while Waiting For the New Manga Dex is Use the former Cover of the Mangadex to the New Manga Dex)... Hdhsisixnanwihznwnwishe whhxbsjejwjwnw I Love Hentai 
## What/Requirements
ADD "Cover" to the Include Selection In the Migrate panel.. 
![Screenshot_20210506_182108](https://user-images.githubusercontent.com/65703094/117282931-db736680-ae97-11eb-89cd-edb984e82fa2.jpg)
![Untitled137_20210506183709](https://user-images.githubusercontent.com/65703094/117285040-1d9da780-ae9a-11eb-8a51-259136dce5b1.png)

**Comment by Saud-97** [comment]
Closed by #7196

**Comment by Saud-97** [comment]
Although my PR only migrates custom covers not the original cover but a user can save it and set it manually.
