### ISSUE TITLE
artist name not updated for empty changes

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5032]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. find manga(make one with komga/something else) with wrong artist name
2. remove the artist name or make it null
3. refresh manga

### Expected behavior
artist name should be changed to empty/unkown

### Actual behavior
wrong artist name stay

**Comment by Riztard** [comment]
not sure how but it seems now it work as expected

**Comment by arkon** [comment]
This doesn't still happen, does it?

**Comment by Riztard** [comment]
lol forgot to test it
