### ISSUE TITLE
Gmanga extension doesn't work with me 

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi#5034]
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- I will fill out the title and the information in this template

---

## Device information
* Tachiyomi version: latest
* Android version: 10
* Device: oppo a5 2020

## Steps to reproduce
1. I open any manga in gmanga or update them

### Expected behavior
It shoud open 

### Actual behavior
Sometimes a message says index 7 or some other wierd staff and a small black shape appears
![Screenshot_2021-05-07-01-34-14-23_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/75262438/117378815-75f29a80-aed6-11eb-959a-da4a2eb0446e.jpg)

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Wrong repo.

**Comment by hakudansho** [comment]
What shoud i do then?
