### ISSUE TITLE
[Bug] Auto background color not available in main settings

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi#5048]
## Device information
App version: 0.10.12-3354 (standard, 47c120e5, 60)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T865XXU4CUC1
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea

## Steps to reproduce
1. Go to settings - reader - background color

### Expected behavior
The new option for [automatic](https://github.com/tachiyomiorg/tachiyomi/issues/584) should be present

### Actual behavior
The automatic option is only present within the reader itself and not in the settings

**Comment by ghostbear** [comment]
Already fixed and will be in the next preview build https://github.com/tachiyomiorg/tachiyomi/commit/4bfd395d9fb639625190284e21f1dbaf0649ce13

**Comment by giosann** [comment]
Thanks. I'll try to pay more attention to pull requests in the future.
