### ISSUE TITLE
download bug. chapter pages limited to <1000. download queue stops

### ISSUE THREAD

**Issue by Wyld-One** [tachiyomiorg/tachiyomi#5050]
https://github.com/tachiyomiorg/tachiyomi/blob/5700c7a0c7bf532faadf50e261a03b84f36c6fe1/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L341

format limits pages in single chapter to less than 1000, causes queue crash

fix? change to "%04d"

**Comment by CarlosEsco** [comment]
what um source has 1000+ page chapters lol

**Comment by Wyld-One** [comment]
ehentai
Artist Max Blackrabbit

precious, luscious API
Waifu Academy 3DCG Gallery

**Comment by arkon** [comment]
Duplicate of #1561
