### ISSUE TITLE
[Bug] <crash when i search scan>

### ISSUE THREAD

**Issue by Borger17** [tachiyomiorg/tachiyomi#5053]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Xiaomi Redmi note7

## Steps to reproduce
1. Search manga name in extension

### Expected behavior
Show me which reader and the numer of chapters for this manga
### Actual behavior
Crash and app close

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

--------- beginning of system
--------- beginning of main
05-11 07:23:04.749 17503 17503 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-11 07:23:04.908 17503 17503 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
05-11 07:23:05.535 17503 17536 E Perf    : Fail to get file list eu.kanade.tachiyomi
05-11 07:23:05.536 17503 17536 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
05-11 07:23:05.537 17503 17536 E Perf    : Fail to get file list oat
05-11 07:23:05.537 17503 17536 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
05-11 07:23:06.311 17503 17550 E SQLiteLog: (284) automatic index on C(manga_id)
05-11 07:23:06.311 17503 17550 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190910.002 V12.0.3.0.QFGEUXM
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: lavender
Device model: Redmi Note 7
Device product name: lavender_ee

**Comment by mehali19** [comment]
Hello, I have the exactly same bug in my Oppo Find X2 Lite. 
It is the crash log file of the app.
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 11 (SDK 30)
Android build ID: CPH2005_11_C.76
Device brand: OPPO
Device manufacturer: OPPO
Device name: OP4C41L1
Device model: CPH2005
Device product name: CPH2005EEA

Sorry if my english Is bad.

**Comment by arkon** [comment]
Not enough info here. Open another issue with better steps (what manga name, what source, etc.). The crash logs also don't seem to actually include a crash.
