### ISSUE TITLE
[Bug] <GManga is not working>

### ISSUE THREAD

**Issue by mjjood10** [tachiyomiorg/tachiyomi#5055]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 6.0.1
* Device: 1+ A0001

## Steps to reproduce
1. Go to GMANGA
2. entering to any manga

### Expected behavior
the chapters which up

### Actual behavior
the chapters didn't which up

## Other details
the chapters didn't which up
in gmanga extension

**Comment by loocool2** [comment]
#6852

**Comment by mjjood10** [comment]
I'm sorry but what does this mean
