### ISSUE TITLE
[Feature Request] export/download manga details

### ISSUE THREAD

**Issue by laurinvesely** [tachiyomiorg/tachiyomi#5057]
## Why/User Benefit/User Problem
the user quickly wants to create a details.json for their local manga. it is possible to find the manga in an extension. it would be very comfortable to just download the manga details and then add them to the local manga. maybe even a settings option that allows details.json to be automatically created for downloaded manga.

## What/Requirements
there should be an option that automatically creates details.json for downloaded manga. also there should be a manual download details for a manga from an extension.

**Comment by arkon** [comment]
Closing in favour of #2289
