### ISSUE TITLE
Local manga doesn't load Title from details.json file

### ISSUE THREAD

**Issue by laurinvesely** [tachiyomiorg/tachiyomi#5058]
## Why/User Benefit/User Problem
The user wants to add a local manga that has a special character (for example ':') in its title.
The manga folder naming cant support special characters so title is added as title in details.json.
Tachiyomi only shows the folder name as title of the manga instead of title set in details.json.

## What/Requirements
Tachiyomi should use details.json title for the manga title and if it doesnt exist then use folder name.

**Comment by curche** [comment]
> Tachiyomi should use details.json title for the manga title and if it doesnt exist then use folder name.

Afaik this is how it does work. 

> The manga folder naming cant support special characters so title is added as title in details.json.

Tried at my end and works fine. 
Some users have reported similar problems before (#4803) and I think this is caused due to the device filesystem not accepting it

**Comment by laurinvesely** [comment]
> Tried at my end and works fine.

Have you tried creating a folder with characters like `* < > : ? " / \ |` ? this is not possible on most smartphones and neighter on OS like Windows 10.

> Afaik this is how it does work.

I use latest Tachiyomi on Samsung Galaxy S10e and this does not work as intended on the phone. Title attribute in json has no impact on manga name in Tachiyomi.

**Comment by curche** [comment]
Checked again, can confirm that the title is not getting updated from *.json file for local manga in preview version r3368
Sorry for the confusion. Can be marked as a [Bug].

https://user-images.githubusercontent.com/72807749/118523572-df866a80-b75a-11eb-86c0-148faf6c438c.mov

**Comment by laurinvesely** [comment]
> 
> 
> Checked again, can confirm that the title is not getting updated from *.json file for local manga in preview version r3368
> Sorry for the confusion. Can be marked as a [Bug].
> MNML-May17-094903PM.mov

it seems like i cant change the label to bug

**Comment by curche** [comment]
/edit-title "Local manga doesn't load Title from details.json file"

**Comment by arkon** [comment]
We actually just never update the title, which is tracked in #3608.
