### ISSUE TITLE
[Bug] Kiryuu.co not updating (Indonesia)

### ISSUE THREAD

**Issue by RyanRay55** [tachiyomiorg/tachiyomi#5061]
I realized my bookmark from this source : kiryuu.co not updating anymore. I check the latest update tab and it didn't show the new manga/manhwa. So, I went to their site and saw that they have changed their site to the new one from {  https://kiryuu.co/  to the 
https://kiryuu.id/.  So I hope that you can update their new site on the old source. Thank you

**Comment by jopejoe1** [comment]
Wrong repository.
Please create this issue at [https://github.com/tachiyomiorg/tachiyomi-extensions/issues](https://github.com/tachiyomiorg/tachiyomi-extensions/issues)

**Comment by RyanRay55** [comment]
> 
> 
> Wrong repository.
> Please create this issue at https://github.com/tachiyomiorg/tachiyomi-extensions/issues

Thank you
