### ISSUE TITLE
[Bug] <Categories flickers/glitches>

### ISSUE THREAD

**Issue by dinosw** [tachiyomiorg/tachiyomi#5064]
## Device information
* Tachiyomi version: Stable 0.10.12 
* Android version: 10
* Device: Samsung Galaxy Note 9 (SM-N960F) 

## Steps to reproduce
1. It might have to do with the number of categories I have (I have 20 categories). 

### Expected behavior
I would expect that I could scroll to the categories, which are further to the right. (if I scroll fast, and quickly tap a category, I might make it before it flickers back to the leftmost categories. 

### Actual behavior
When I try to scroll to the right in my categories, it keeps going back to the far left side of my categories. And even when I do not scroll through my categories, they keep "flickering"/"glitching".  It has done this for the last few versions of tachiyomi. 

## Other details

**Comment by arkon** [comment]
Do you have a video?

**Comment by dinosw** [comment]
@arkon [Categories flickering](https://streamable.com/ki4wc5) 
I only pull down to update, and scroll to the right in the categories. I do not scroll left in the categories in this video.

**Comment by arkon** [comment]
I can't reproduce this.

**Comment by dinosw** [comment]
@arkon 
Might it be due to the number of categories I have? (I have 20 categories)  
The bug appeared a few months ago.

**Comment by dinosw** [comment]
I think that the glitching happens once per title, when Tachiyomi is checking for library updates.

**Comment by arkon** [comment]
No longer happens in preview after the Compose rewrite.
