### ISSUE TITLE
[Bug] <Reading mode starts in right to left instead of default>

### ISSUE THREAD

**Issue by blanknoob36** [tachiyomiorg/tachiyomi#5068]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 8.1.0
* Device: Walton Primo X5

## Steps to reproduce
1. Opening any random mangadex entry in the library.
2. Opening any chapter in that entry.

### Expected behavior
After opening any chapter in any of the random mangadex entries in my library (which reading mode settings hasn't been changed or reading mode hasn't been changed using the settings button you get while reading) will start/open in webtoon reading mode(as that is set as default reading mode in setting>reader>default reading mode).

### Actual behavior
After opening any chapter in any of the random mangadex entries in my library (which reading mode settings hasn't been changed or reading mode hasn't been changed using the settings button you get while reading) starts/opens right to left reading mode(instead of webtoon even tho it is the default).

## Other details
I also have manganelo extension and the manganelo entries don't have this problem only the MD ones.

This happens both in stable and preview version I only use stable version but tried in preview verison cause discord support said it might be fixed in that but it still same thing happens.  PreviewApp version: 0.10.12-3354 (standard, 47c120e5, 60).

The mangadex entries doesn't even show the reading mode either when I open a chapter even tho it is on in settings.
If I open a random mangadex entry from browser mode that isn't in my library it works just fine starts/opens in webtoon mode like it should(can't try one of my library entires from there as md search is unoptimised atm). By browser mode I mean here 
![IMG_20210512_231820_893](https://user-images.githubusercontent.com/84096880/118030964-cd39b480-b387-11eb-92f4-3c12d0429c12.JPG)

If I suppose open one of the mangadex entries, then open a chapter and change the reading mode while reading  it starts following/acknowledge(don't know the correct word) the main settings again that same entry and all chapters of that entry even if I close and open tachiyomi. So the entries whichs reading mode hasn't been changed before/now while reading starts in right to left read mode instead of the default webtoon.
I tried other reading modes same thing happens.
I also reinstalled tachi yesterday cause of this issue.
And here a crash log cause now on the stable version if I press on the setting button while reading a chapter it crashes.
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6468534/tachiyomi_crash_logs.txt)

Edit: this crash seems to be only with the mangadex entries when i open a mangadex entry chapter and then click on settings in there app crashes the setting on the bottom right that one.
![IMG_20210513_021852_836](https://user-images.githubusercontent.com/84096880/118039280-f8c19c80-b391-11eb-9a6f-1594344e05d0.JPG)

**Comment by blanknoob36** [comment]
This is my firs time in GitHub so do I  close the issue or will u guys do it? Since u already fixed the code I guess. @arkon

**Comment by arkon** [comment]
Is it fixed? I couldn't actually reproduce.

**Comment by blanknoob36** [comment]
I guess we will have to see in the next update when the code is implemented (I don't know if I can download and test with the code u edited I am new to GitHub so I have like 0 ideas how to do things here) and only some people well 2 in total I saw has the problem me and the other guy who opened another topic here #5030. And a guy from that issue carlosesco closed this topic.

**Comment by blanknoob36** [comment]
I just noticed it was implemented in the preview lemme try it

**Comment by blanknoob36** [comment]
Nop it doesn't seem like it is fixed gotta still manually change reading mode after opening a chapter to fix the issue for that entry only 
Here are pic of two random mangadex entry manga I opened and it opened in  left to right read more instead of webtoon (I selected webtoon as default in main settings) 

![IMG_20210521_150941_229](https://user-images.githubusercontent.com/84096880/119113189-a8f46c80-ba46-11eb-92da-e1aee3e26d1e.JPG)
![IMG_20210521_150951_315](https://user-images.githubusercontent.com/84096880/119113195-aabe3000-ba46-11eb-9d35-067406d7c9fb.JPG)

preview version : App version: 0.10.12-3368 (standard, 09c07faa, 60)
Android version: 8.1.0 (SDK 27)
Android build ID: Primo_X5_T_W181018_V12
Device brand: WALTON
Device manufacturer: WALTON
Device name: Primo_X5
Device model: Walton Primo X5
Device product name: Primo_X5

**Comment by blanknoob36** [comment]
From what I have observed using 2 extensions manganelo and mangadex it is seems to be a problem with mangadex entries only

**Comment by blanknoob36** [comment]
Ok another obersevation is that I random added 2 random mangadex entry they seem to be working fine when opening in the library they open in webtoon reading mode instead of right to left reading mode in the preview version r3368 . So basically the entries that I restored using backup(stable version 0.10.12 backup)  on the preview version seems to have the problem still, but any new mangadex entry I add seems to work just fine as it should on the preview version.

I also tried adding new random mangadex entry in my library in the stable version it seems to work fine the new entries only.
So somehow the entries which I restored using on the stable (I reinstalled tachi stable when I had this problem) is corrupted or something.

**Comment by blanknoob36** [comment]
You know what I think this problem happened after I used j2k fork to migrate all of old md entries to new MD v5 then use j2k backup file to restore in stable tachi.

**Comment by blanknoob36** [comment]
You know what I think u can reproduce this if you use my backup file let me upload it but I think it would be better if I could send it to u in private lol that way won't have to make it public.

**Comment by arkon** [comment]
You can find my email address if you like around from my GitHub profile.

**Comment by blanknoob36** [comment]
Sent it

**Comment by blanknoob36** [comment]
So were u able to reproduce the problem with the backup file?

**Comment by arkon** [comment]
I'll look at it when I have time.

**Comment by arkon** [comment]
Seems like `viewer = -1` for the entries from that backup, which is apparently how J2K initializes it. We can try to handle invalid entries as the default viewer better in the main app.

**Comment by blanknoob36** [comment]
I have one question hope u don't mind why wasn't the manganelo entries affected only(most of ) mangadex ones just asking. If the explanation is too long no need.

**Comment by arkon** [comment]
You'd have to ask Jay, I don't know what J2K does.
