### ISSUE TITLE
[Feature Request] Multi-source grouping

### ISSUE THREAD

**Issue by Roukira** [tachiyomiorg/tachiyomi#5070]
## Why/User Benefit/User Problem
Allowing multiple sources to be grouped on a manga-per-manga basis would make it easier to follow multiple sources on a manga without having many times the same manga taking multple slots.

## What/Requirements
This feature would display an additionnal bar under the "genre" bar when you click on a manga, allowing to filter by source added for this chapter (radio buttons). Ideally, each source would behave like the chapters, being greyed if you're up to date in that source, and white color if there is a chapter you haven't read there, allowing the user to know which source has a new chapter.

**Comment by loocool2** [comment]
Similar to #886
