### ISSUE TITLE
[Bug] Download button in dark mode has the wrong color in some chapters

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5075]
## Device information
App version: 0.10.12-3354 (standard, 47c120e5, 60)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190825.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: davinci
Device model: Mi 9T
Device product name: davinci_eea

## Steps to reproduce
1. Default themes, follow system mode (dark mode)
2. Open any manga
3. Sometimes the download button has the wrong color

![Screenshot_2021-05-14-02-32-36-020_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/13546823/118207744-3b03e000-b45d-11eb-8ecd-75fdeaee5366.jpg)

### Expected behavior
Buttons should all be equal.

### Actual behavior
Buttons are inconsistent.

## Other details
Can't really pinpoint what's causing it, some manga have them all black, some have none, some have them at random.

**Comment by arkon** [comment]
Do you have the MIUI force dark mode thing turned on? If so, turn it off.

**Comment by paulo27ms** [comment]
Bit confused since I can't find it but I see it in search...
MIUI optimizations is off.

![Screenshot_2021-05-14-02-54-19-249_com android settings](https://user-images.githubusercontent.com/13546823/118209406-75bb4780-b460-11eb-8df3-0b0729f0d14a.jpg)
![Screenshot_2021-05-14-02-54-50-739_com android settings](https://user-images.githubusercontent.com/13546823/118209416-78b63800-b460-11eb-8163-baa43c2c0cf9.jpg)
![Screenshot_2021-05-14-02-57-54-223_com android settings](https://user-images.githubusercontent.com/13546823/118209419-7b189200-b460-11eb-9393-e2ae6e50d1eb.jpg)
![Screenshot_2021-05-14-02-58-54-706_com android settings](https://user-images.githubusercontent.com/13546823/118209425-7ce25580-b460-11eb-82b6-e6937366cb71.jpg)

**Comment by paulo27ms** [comment]
Turning Tachiyomi off in the Individual apps menu fixed it (still detects automatically).
