### ISSUE TITLE
[Bug] I can't use the resume feature properly 

### ISSUE THREAD

**Issue by NJ321** [tachiyomiorg/tachiyomi#5076]
I really don't get how I'm supposed to use the resume feature I can't find a way to make it save where I left off reading. In one manga it starts me of on the first chapter even if I checkmark another chapter and in another manga I only get the hollowed checkmark to mark(which I think is normally supposed to unmark) it and then I can resume but as soon as l finish the chapter it no longer marks where I leave off. Another is working fine but I think that's just because I started that one from the beginning.

**Comment by CarlosEsco** [comment]
It goes to the first unread.  so if you read chapter 11 and chapter 1-10 are unread.  You are going to go back to chapter 1.  Mark those chapters read and you will be fine

**Comment by NJ321** [comment]
> It goes to the first unread. so if you read chapter 11 and chapter 1-10 are unread. You are going to go back to chapter 1. Mark those chapters read and you will be fine
