### ISSUE TITLE
[Feature Request] <Proper genre tag search in Local Manga>

### ISSUE THREAD

**Issue by MapleSyrup29** [tachiyomiorg/tachiyomi#5078]
## Why/User Benefit/User Problem
The current functionality is that when tapping on a created custom genre tag in Local Manga, the search results show manga that have the tag in the manga's name and not the manga that are tagged with the custom genre tags themselves. I feel that it would be much more useful if the user is able to add custom tags nature.

![1](https://user-images.githubusercontent.com/84200358/118313570-7c5fc280-b525-11eb-97c1-6db0bd8db401.jpg)
![2](https://user-images.githubusercontent.com/84200358/118313580-808be000-b525-11eb-9b05-7de8f4da8776.jpg)
![3](https://user-images.githubusercontent.com/84200358/118313593-8681c100-b525-11eb-8b18-e5cacb50fb7a.jpg)

## What/Requirements
Feature Behavior: Tapping on a genre tag in Local Manga searches for Local Manga with the same tag.

**Comment by arkon** [comment]
#5892 is broader, so I'll close this in favour of that.
