### ISSUE TITLE
[Bug] App crash if u enable Crop borders option & view some manga with continuous vertical reading mode

### ISSUE THREAD

**Issue by balagurusurendar** [tachiyomiorg/tachiyomi#5081]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: Samsung Tab s7 SM-T875

## Steps to reproduce
1. enable Crop borders in reader settings
2. install mangabat extn
3. open manga Cultivation Chat Group
4. go to chapter 64
5. set navigation layout as continuous vertical
6. scroll to end

### Expected behavior
able to view every page without crash

### Actual behavior
app crashed while viewing particular page

## Other details
crash log : 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6487841/tachiyomi_crash_logs.txt)

**Comment by balagurusurendar** [comment]
FYI: for now i am using app with disabling Crop borders option.
It works fine for now.

**Comment by inorichi** [comment]
Forgot to update this issue. It should be fixed now, thanks for reporting it.
