### ISSUE TITLE
[Feature Request] Update library, skip source titles after an errors

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi#5082]
## Why/User Benefit/User Problem
When you update your library, and there is an extension with a server error (like 502s, timeouts, and so on) updating takes a long time since it tries to sync each title in your library. If after a title in an extension has an error, Tachiyomi's update would skip all the others from that extension, it would save a lot of time for the sync. 

## What/Requirements
For instance, if Tachiyomi's updater encounters an error for a title (something like timeout or 500 errors) Tachiyomi would skip all other titles from that source and move on to the next. Then, in the error log the message could display the first title with the error and then a note saying that it skipped however many from the source.

**Comment by arkon** [comment]
We're updating the library parallelized by sources (up to 5 sources in parallel) now, so other sources should be unblocked. In the case that a source is having issue, you should be able to let the others finish and cancel it after that point.
