### ISSUE TITLE
[Feature Request] <Add option to throttle downloads>

### ISSUE THREAD

**Issue by autive42** [tachiyomiorg/tachiyomi#5083]
## Why/User Benefit/User Problem
When trying to bulk download from Viz, I repeatedly get the error com.google.gson.stream.MalformedJsonException. In addition, Viz's Terms of Use state the following:
> You may not use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, "scrape," "data mine" or in any way reproduce or circumvent the navigational structure or presentation of the Sites without VIZ Media's prior written consent.
While I do not know for sure the reason for the error, it might be helpful to be able to restrict the download speed to one that seems more humanly reasonable to avoid suspicion.

## What/Requirements
I'm suggesting that on the downloads tab or in settings there is an option to restrict download speeds to a certain number of pages/second. Setting it to something like .5 would seem much less suspicious upon review by any staff.

**Comment by arkon** [comment]
Extensions are already rate limited as needed. Open an issue in the extensions repo if you think any source requires it.
