### ISSUE TITLE
MaxSecure flags tachiyomi with "Android.Android.WIN32.SpyNote.e"

### ISSUE THREAD

**Issue by runboy93** [tachiyomiorg/tachiyomi#5084]
https://www.virustotal.com/gui/file/3cca4224c1a5c4317ba1c8c1e0ab0ce85410ef28439a05886b6e2e496236e49a/detection

I know it might be another false positive, but where to report these?

**Comment by Flat** [comment]
Probably to https://www.maxsecureantivirus.com/maxIS/submit_aFalse_Positive.htm
