### ISSUE TITLE
[Feature Request] Toggleable menus on navbar

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5085]
## Why/User Benefit/User Problem
Since now we can hide history and update tab, we should be able to let people add the menus they want in place of those removed, like a quick button to downloads or settings.

## What/Requirements
Make all menus toggleable on the navbar but limit them to 4 at a time.

**Comment by arkon** [comment]
That'd overcomplicate the navigation tree, so no.
