### ISSUE TITLE
[Feature Request] Ignorable errors

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5086]
## Why/User Benefit/User Problem
This is mostly for the "No chapters found" error personally as it doesn't seem necessary to throw this error every time when you willingly pick a manga without chapters and are waiting for it to update.

## What/Requirements
I'm not sure how the code is structured but if every extension has the same base errors which are consistently identifiable across sources, this could be implemented to be able to not log/notify for certain errors, if this would need to be tweaked on an extension by extension basis, there's no point in implementing it.

**Comment by CrepeTF** [comment]
Sounds troublesome holistically, some users might disable errors accidentally (and they will) which will cause general confusion for the user and support staff.

**Comment by arkon** [comment]
Agreed, I'd rather errors be blatantly obvious and annoying than having users being confused as to what's happening.

**Comment by paulo27ms** [comment]
Users gotta ruin everything. 😔
