### ISSUE TITLE
[Bug] Crashed because Driver indicates EGL 1.5 support,but does not have a critical API

### ISSUE THREAD

**Issue by SatriaXV** [tachiyomiorg/tachiyomi#5088]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Redmi 4A

## Steps to reproduce
1. open some Manga/manhwa (I guess Manga with high image resolution that cause this issue)
2. Crashed when trying to load the image

### Expected behavior
- Manga or manhwa open as usual

### Actual behavior
- Crashed 

## Other details
- I just recently update the app and it was not crashed in version 0.10.9

##Crash log
--------- beginning of main
05-16 15:17:36.981 30666 30703 E libEGL  : Driver indicates EGL 1.5 support, but does not have a critical API
05-16 15:18:15.493 30666  6645 E Image   : /home/jitpack/build/library/src/main/jni/image/image.c(38): Library init func bmp_init failed
05-16 15:23:52.202 10096 10096 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-16 15:23:54.490 10096 10167 E SQLiteLog: (284) automatic index on C(manga_id)
05-16 15:23:54.490 10096 10167 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-16 15:23:54.799 10096 10139 E libEGL  : Driver indicates EGL 1.5 support, but does not have a critical API
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 10 (SDK 29)
Android build ID: QQ1B.191205.011
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: rolex
Device model: Redmi 4A
Device product name: rolex

**Comment by arkon** [comment]
Create another issue if still happening.
