### ISSUE TITLE
[Feature Request] Add a toggle to disable the reader menu or add an option to open it with double tap instead of single tap

### ISSUE THREAD

**Issue by Shamicen** [tachiyomiorg/tachiyomi#5090]
## Why/User Benefit/User Problem
Tachiyomi often registers the normal scrolling motion as a single tap and opens the menu.  

Another option would be to add a deadzone at the sides so only tapping in the middle would bring up the menu, like it currently works when the Tapping toggle is enabled just that instead of jumping up or down when a single tap is registered the reader would do nothing instead. 

to clarify I mean this menu: 
![Tachiyomi_reader_menu_1](https://user-images.githubusercontent.com/84282253/118405224-1420f600-b677-11eb-9bb7-82bc448c878a.jpg) 
![Tachiyomi_reader_menu_2](https://user-images.githubusercontent.com/84282253/118405225-1420f600-b677-11eb-885f-d64819a3d9d8.jpg)

**Comment by arkon** [comment]
This is actually a Samsung-specific issue. You need to not swipe from close to the edges.
