### ISSUE TITLE
No pages found

### ISSUE THREAD

**Issue by Scarlet00** [tachiyomiorg/tachiyomi#5091]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: Samsung s20+

## Steps to reproduce
1. Open remarried empress from manhuascan extension

## Issue/Request
The pages won't load even if I checked the website, it still has the pages, but it won't load on tachiyomi. It just says no pages found

## Other details
![Screenshot_20210517-021035_Tachiyomi](https://user-images.githubusercontent.com/17315157/118407850-376a9600-b6b5-11eb-8042-f00635ee600b.jpg)

**Comment by arkon** [comment]
Wrong repo and already reported.

**Comment by h-hyuuga** [comment]
The update fixing this went live about a minute before you posted this
