### ISSUE TITLE
[Bug] <Crop borders webtoon>

### ISSUE THREAD

**Issue by ligneo** [tachiyomiorg/tachiyomi#5092]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: OnePlus A5010

## Steps to reproduce
1. Enable the crop broders
2. Read with webtoon mode
3.Speech bubbles cut off and some images cut off
4.Disabling crop borders turns normal the speech bubbles and cropped images

### Expected behavior
Crop should only cut the edge white parts 

### Actual behavior
Crop cropping the content of images 

## Other details
Reading mode : Webtoon 
Scale Type : Fit Height (any)

**Comment by ligneo** [comment]
![Screenshot_20210516-231931.jpg](https://user-images.githubusercontent.com/29066289/118411574-e1d6bf00-b69d-11eb-8672-745533f4740d.jpg)
![Screenshot_20210516-231924.jpg](https://user-images.githubusercontent.com/29066289/118411581-e7cca000-b69d-11eb-9f83-cbbc6b51968e.jpg)
![Screenshot_20210516-231854.jpg](https://user-images.githubusercontent.com/29066289/118411585-ec915400-b69d-11eb-86e6-84d6e692829f.jpg)![Screenshot_20210516-231840.jpg](https://user-images.githubusercontent.com/29066289/118411593-f024db00-b69d-11eb-8623-764f985e7160.jpg)![Screenshot_20210516-231833.jpg](https://user-images.githubusercontent.com/29066289/118411596-f2873500-b69d-11eb-9897-4f0326f06cb6.jpg)

**Comment by ligneo** [comment]
![Screenshot_20210516-231854__01.jpg](https://user-images.githubusercontent.com/29066289/118411623-1d718900-b69e-11eb-9d58-45a9c3b5374d.jpg)![Screenshot_20210516-231931.jpg](https://user-images.githubusercontent.com/29066289/118411626-1f3b4c80-b69e-11eb-8a0a-439e5e43a2f0.jpg)![Screenshot_20210516-231924.jpg](https://user-images.githubusercontent.com/29066289/118411629-1fd3e300-b69e-11eb-9b69-eb68f347d790.jpg)![Screenshot_20210516-231840.jpg](https://user-images.githubusercontent.com/29066289/118411630-219da680-b69e-11eb-9488-9d7cb9cf3151.jpg)![Screenshot_20210516-231833.jpg](https://user-images.githubusercontent.com/29066289/118411632-22ced380-b69e-11eb-9b76-103f0d3e6f0f.jpg)

**Comment by CrepeTF** [comment]
This isn't a bug, it's just to do with how Webtoons are spliced on the website.

Different images will have different borders when you look at them individually and the crop borders is doing exactly what it's meant to do.

Making crop border work for Webtoons would likely require too much work for little effect when you can just zoom in.
