### ISSUE TITLE
[Feature Request] Make Updates/History show up on "More" when hidden from bottom nav

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5093]
## Why/User Benefit/User Problem
Related to #5077 
While a huge amount of users rarely go to these screens, "rarely" still counts as usage. It would be nice to have a way of accessing these screens when it's hidden from the bottom nav.

## What/Requirements
Maybe near Download queue on More tab

**Comment by simakover** [comment]
Im can try add this feature, but dont know is it usefull\needed. didnt use these tabs at all and made feature to hide tabs. By default tabs are still here, and if you hide it, you must know there hide options placed. 

May be more expirienced devs\product owners can say need access to this tabs anyway or not

**Comment by CarlosEsco** [comment]
I don't think hiding the buttons was useful either, but i agree with Vengiare.  Completely removing a navigation feature and not having a way to navigate to it is bad UX.

**Comment by joseph619** [comment]
I don't use the updates tab but it would be nice if I could access the Downloads queue while Updates is hidden.

**Comment by simakover** [comment]
> I don't think hiding the buttons was useful either, but i agree with Vengiare. Completely removing a navigation feature and not having a way to navigate to it is bad UX.

Im just not use this buttons for years, so hide it)
Like minimalistic design. If you want and everybody confirms, would try to show this buttons in any other place)

**Comment by arkon** [comment]
I'm more tempted to just revert it than deal with these "alternative" means of doing things.

**Comment by simakover** [comment]
> I'm more tempted to just revert it than deal with these "alternative" means of doing things.

Im hope that this changes would be useful not only gor me(

**Comment by paulo27ms** [comment]
So you have a problem:
A useless button that you use once a year.
Solution:
You hide the button that you never use.
Now you have a new problem:
Gotta go into the menu once a year to enable it to use it again.
New solution:
Enable it forever as it was before.
You're welcome.

**Comment by simakover** [comment]
Yeah, so im hide this buttons and would never use them. But people want to see it anyways.
Solution: just not hide them

**Comment by arkon** [comment]
I'm just going to revert the settings. ¯\\\_(ツ)_/¯

**Comment by simakover** [comment]
> I'm just going to revert the settings. ¯\_(ツ)_/¯

still dont know why reverting, it is an option, nobody force users to hide buttons

**Comment by ztimms73** [comment]
It would be nice to implement this feature, so I am in favor of implementing it.

**Comment by vengiare** [comment]
> > I'm just going to revert the settings. ¯_(ツ)_/¯
> 
> still dont know why reverting, it is an option, nobody force users to hide buttons

Moving it from bottom nav to somewhere else would've been okay. Completely hiding it from the whole app is just bad UX.

**Comment by simakover** [comment]
> > > I'm just going to revert the settings. ¯_(ツ)_/¯
> > 
> > 
> > still dont know why reverting, it is an option, nobody force users to hide buttons
> 
> Moving it from bottom nav to somewhere else would've been okay. Completely hiding it from the whole app is just bad UX.

no one force you to hide. its a preference, why it is bad UX if im completle dont use this buttons

**Comment by paulo27ms** [comment]
> > > I'm just going to revert the settings. ¯_(ツ)_/¯
> > 
> > 
> > still dont know why reverting, it is an option, nobody force users to hide buttons
> 
> Moving it from bottom nav to somewhere else would've been okay. Completely hiding it from the whole app is just bad UX.

Like how it's bad UX when you filter out manga and the only way to see it again is changing the filter manually to the default?
How does applying a setting to hide something instantly make it bad UX? Just turn it back on.
I get the not wanting to expand on the setting by adding the buttons somewhere else if they are hidden but just deny the request then, not remove the entire feature people found useful.
Equally confused by the people who seem happy when features are removed but alas.

**Comment by vengiare** [comment]
> no one force you to hide. its a preference, why it is bad UX if im completle dont use this buttons

That's not even the problem. I'm not against hiding it from bottom nav but there must be an alternative way to navigate to it when it's hidden from bottom nav.

**Comment by paulo27ms** [comment]
There hasn't, it's not an essential menu like settings or browse.

**Comment by simakover** [comment]
Arkon already revert it, sadness. dont want maintain my fork only for this feature)

**Comment by arkon** [comment]
Frankly, I do agree that it's silly because you can just unhide it, but I'd rather avoid the complaints by forcing the existing UX.
