### ISSUE TITLE
[Feature Request] 增加一个迁移时显示目标网站对应书籍最新章节的信息

### ISSUE THREAD

**Issue by scetus** [tachiyomiorg/tachiyomi#5095]
## Why/User Benefit/User Problem
因为不同漫画在不同网站上的进度或者文章量是不同的。迁移的时候，只会显示名称和封面，很容易就出现点击迁移后发现那个网站并不全，还要再次迁移的情况。或者现在只能先全局搜索，找到那个有最新，然后再用迁移功能

## What/Requirements
希望能在迁移的时候，用合适的方式点击查看对应网站上的最新章节。提高迁移效率

**Comment by paulo27ms** [comment]
Based on seeing your question through Google translate... What you want is already available, just hold press the cover of the destination manga and it'll open its details.
