### ISSUE TITLE
[Feature Request] Make Downloads queue accessible from somewhere else if Updates tab is hidden

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#5097]
I don't use the Updates tab ever, but I do access Downloads Queue pretty often. When updates tab is hidden, requesting Downloads queue to be made accessible from somewhere else, like long pressing More button (which already hosts it)

Could be discussed on Discord if needed

**Comment by arkon** [comment]
No longer relevant as it was reverted.
