### ISSUE TITLE
[Bug] Popup menu not flush with bottom when gesture navigation enabled

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#5099]
## Device information
* App version: 0.10.12-3368 (standard, 09c07faa, 60)
* Android version: 10 (SDK 29)
* Device name: OnePlus 6T

## Steps to reproduce
1. Enable gesture navigation (no software buttons for back/home/recents) in device settings
2. Long press either:
   - A manga in the library view
   - A chapter in the manga view
3. Popup menu appears

### Expected behavior
Popup menu should be flush with the bottom of the screen

### Actual behavior
Popup menu has a gap between the bottom of the menu and the bottom of the screen, where the software buttons would usually be situated.

## Other details

This does not happen with the various flyouts, like the reader settings (while reading chapter). [Example screenshots](https://imgur.com/a/CeO9hxz)

### Screenshots of bug

![Screenshot_20210517-162327.jpg](https://user-images.githubusercontent.com/3440094/118516621-62450080-b72e-11eb-90bc-d00099a9b1f6.jpg)

![Screenshot_20210517-161448.jpg](https://user-images.githubusercontent.com/3440094/118516634-6709b480-b72e-11eb-85ed-0a6171192383.jpg)

**Comment by paulo27ms** [comment]
You want it sticking to the bottom? Why.

**Comment by CarlosEsco** [comment]
Because it looks out of place.  When you have on screen buttons it sits right above.  When you have a gesture pill it's in the middle of no man's land instead of right above the pill

**Comment by wopian** [comment]
While there is significantly less padding than before, with the above change there is a small gap between the bar and the bottom of the screen:

![Screenshot_20210524-074408__01.jpg](https://user-images.githubusercontent.com/3440094/119308026-7031de80-bc64-11eb-99aa-305aa293c3bb.jpg)

![Screenshot_20210524-074527__01.jpg](https://user-images.githubusercontent.com/3440094/119308038-758f2900-bc64-11eb-98e0-ac99a6361f5a.jpg)

**Comment by arkon** [comment]
It was supposed to be like that originally. It just looks bad in the AMOLED theme, where you can't really distinguish between anything properly.
