### ISSUE TITLE
[Bug] Impossible to download a chapter

### ISSUE THREAD

**Issue by Diego10pedro** [tachiyomiorg/tachiyomi#5102]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10 
* Device: xiaomi redmi note 8 pro 

## Steps to reproduce
1. Put a chapter to download 
2. Waiting download to begin

## Issue/Request
All my dowloads goes to the download queue but they never starts. They all rest at the beginning and nothing happened.

**Comment by arkon** [comment]
Have you tried pressing the resume button?

If you're not sure what to do, you can ask for help on Discord first.

**Comment by Diego10pedro** [comment]
> Have you tried pressing the resume button?
> 
> If you're not sure what to do, you can ask for help on Discord first.

Apparently my problem come from the extension...
