### ISSUE TITLE
[Bug] <Date gets reset on anilist when a new chapter is read the Next Day>

### ISSUE THREAD

**Issue by Newieb** [tachiyomiorg/tachiyomi#5105]
## Device information
* Tachiyomi version: v0.10.12
* Android version: 10
* Device: Realme XT

## Steps to reproduce
1. Start a new manga and set a date on Anilist. Read 1-2 Chapters on Tachiyomi the same day. The chapters get updated on the Anilist. For Eg: On 17th May 2021 read 1-2 chapters of a particular manga.
2. Open the app on 18th May 2021 (next day) and read chapters 3-4 on Tachiyomi. 

### Expected behavior
Chapters should get updated and the started date should be 17th May.

### Actual behavior
Chapters get updated, but the start date of the manga gets reset on Anilist.

## Other details
Video of the issue is attached.
https://user-images.githubusercontent.com/84270165/118600707-fa92c200-b7ce-11eb-9061-c372671124fa.mp4

**Comment by arkon** [comment]
Same issue as #1652
