### ISSUE TITLE
When i am trying to read any manhua or manga , the app closes the chapter and says something error.

### ISSUE THREAD

**Issue by UnwaveredSoul** [tachiyomiorg/tachiyomi#5112]
Hello Team Service,
This is in regards to the problem that i have recently occured .
![Screenshot_20210519_221655](https://user-images.githubusercontent.com/84467382/118853309-3d4cbb00-b8f1-11eb-8c9a-a02eac2d0cfd.jpg)
Version - Stable 0.10.12
Build time - 4/27/21 19:12
 I am attaching the screenshot to further explain the error/bug.
I hope you can fix it as soon as possible so i may enjoy reading further and support Tachiyomi Family .

Thanks and Regards,
UnwaveredSoul,
Regular Reader

**Comment by dmswd** [comment]
Wrong repo
Please visit https://github.com/tachiyomiorg/tachiyomi-extensions
For extension issues
Also regarding this issue there is an already opened ticket there

**Comment by CarlosEsco** [comment]
also there is already an open issue for that source
