### ISSUE TITLE
Can't Reload Library

### ISSUE THREAD

**Issue by Kurtiyildo** [tachiyomiorg/tachiyomi#5114]
## Device information
* Tachiyomi version: 0,10.12
* Android version: Android 10
* Device: Xiaomi Mi A2

## Steps to reproduce
1. First step: Open the app
2. Second step: Tap to the reload button in the library

## Issue/Request
the app crashes when i try to reload the library.  I tried clearing everything and restarting my phone but it doesn't work. 

## Other details
My extensions does not work when ı try to open an extension it just tries to load but it cant so it keeps spinning.

My crash log
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6511996/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Did you restore the library recently, or do anything related to somehow manipulating the database? It seems to be missing some data, but that should never happen.

**Comment by Kurtiyildo** [comment]
I wasn't using the app for more than a year sı it was a older version. I opened the older version and tried reading Readcomiconline but ı was not able to open any comics. Then ı deleted the app and downloaded the latest stable version of it. Now ı can't use it. I don't know why but ı can't reload my library. I can't even go to library settings. It crashes immediatly as i press the button.

**Comment by arkon** [comment]
Did you explicitly restore your library after reinstalling, or was it just there already?

What older version were you using before deleting it?

**Comment by Kurtiyildo** [comment]
I don't remember the version i was using but it had the old interface. I tried to reload because ı couldn't use the app. When ı tried to open an extention ıt just tries to load it but can't. It doesn't give me a refresh button too it just keeps spinning. If you did not understood it from my explanation ı can show the problem on discord maybe?

**Comment by arkon** [comment]
Can you please answer all the questions?

**Comment by Kurtiyildo** [comment]
I didn't explicitly restore the library. It was there. I don't know the version i was using.

**Comment by arkon** [comment]
Are you able to make a backup? If so try to do that, wipe the app data, then restore it again.

I suspect the app restored a backup from Google Drive but it doesn't apply the migrations in that case.

**Comment by Kurtiyildo** [comment]
I couldn't make backup it says "Backup failed NOT NULL constaint failed: mangas.date_added(...." i can't read anything other than this.

**Comment by arkon** [comment]
Did you make a backup prior to uninstalling the app and installing the newer version?

**Comment by Kurtiyildo** [comment]
No i didn't

**Comment by arkon** [comment]
Not much we can do then. You can either:

1. Wipe the app and start fresh.
2. Attempt to uninstall/reinstall the older version and hope that the data stays and you can make a backup in that, then restore that in a newer version.

As an action item on our side, we probably want to just disable this automatic Google Drive backup thing, since it's super unreliable.
