### ISSUE TITLE
[Bug] <MANGAS GONE AFTER UPDATING THE LIBRARY>

### ISSUE THREAD

**Issue by Deed021** [tachiyomiorg/tachiyomi#5115]
## Device information
* Tachiyomi version: v0.10.12
* Android version: 10
* Device: Xiaomi Redmi note 9s

## Steps to reproduce
1. Open the app;
2. Update the library.

### Expected behavior
update the manga with the latest chapters.

### Actual behavior
I entered the APP normally and put it to update the saved manga (of only one category).  However, after the update was over, more than 3,000 manga disappeared from all categories, with only a few remaining.  I tried to update again, but to no avail.

## Other details
After the first update, some manga that disappeared had the new chapters downloaded (automatic download).  But after the second update, they even disappeared from the recent chapter updates.

![Screenshot_2021-05-19-21-24-40-269_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/66533174/118902024-25723880-b8eb-11eb-8a39-f9aeea952f7c.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
This is unactionable without actual reproduction steps. This obviously isn't happening for other people.

**Comment by Deed021** [comment]
> This is unactionable without actual reproduction steps. This obviously isn't happening for other people.

Yes, I know that it is not happening to other people because I asked in a group.  But, oddly enough, that is exactly what I did.  Anyway, I only reported the bug to analyze and fix it, since I managed to recover them all via backup.

**Comment by CarlosEsco** [comment]
It is impossible to analyze a bug and fix it, if there is no log, video, or repeatable steps aka actionable items.
