### ISSUE TITLE
[Bug] <Manhuascan: unable to open chapter

### ISSUE THREAD

**Issue by cargan21** [tachiyomiorg/tachiyomi#5121]
## Device information
* Tachiyomi version: Stable 0.10.12 
* Android version: 10 
* Device: HMA-L29

## Steps to reproduce
1. First step: Open story
2. Second step: Open chapter

### Expected behavior
chapter should work

### Actual behavior 
it says "com.google.gson.stream. MalformedJSonException: Use JSonReader.setLenient(true) to accept malformed JSon at line 1 column 21 path $" when i try to open a chapter

## Other details
![Screenshot_20210521_075806_eu kanade tachiyomi](https://user-images.githubusercontent.com/84219859/119063743-6a41c080-ba0c-11eb-9b2d-86c251a3fc5d.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by loocool2** [comment]
this is the wrong repo, and we've removed manhuascan
