### ISSUE TITLE
[Bug] ununiform "check manga update" behavior in different tab

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tachiyomiorg/tachiyomi#5122]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: normal arm64 device

## Steps to reproduce
1. pull down to refresh in Library tab

### Expected behavior
updates are shown in both Library and Updates tab

### Actual behavior
updates only shown in Library tab

## Other details
only refresh in Updates tab will shown manga update in Updates tab. it seems like a unexpected behavior, both refresh in Library or Updates tab are doing same things: check manga updates. so why updates are only shown in current tab, not all tab which have manga updates function (such as Library and Updates tab)?

**Comment by arkon** [comment]
For the same chapters? The updates tab isn't doing anything special, it's just getting all recent chapters. If the chapter doesn't have a date though, it won't show up in updates.
