### ISSUE TITLE
[Bug]Download icon is overlapped by page index

### ISSUE THREAD

**Issue by Mark-Joy** [tachiyomiorg/tachiyomi#5123]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 9
* Device: Redmi Note 8 Pro

## Steps to reproduce
Long press a picture for download icon to show up. The download icon is overlapped by the page index.

## Issue/Request
It's just cosmetic issue, but please fix it.

## Other details

![IMG_20210521_141354](https://user-images.githubusercontent.com/22109528/119097874-6da26f80-ba3f-11eb-8adc-1dfc324f2474.jpg)

**Comment by arkon** [comment]
Can't reproduce, likely a Xiaomi-specific issue.

**Comment by Mark-Joy** [comment]
> Can't reproduce, likely a Xiaomi-specific issue.

In my phone, the bug can be reproduced if "full screen gestures display mode" is enable. "Buttons" mode doesn't have this bug.

Buttons mode (buttons in bottom bar):
![Screenshot_2021-06-14-15-01-14-555_eu kanade tachiyomi](https://user-images.githubusercontent.com/22109528/121859787-572bc300-cd22-11eb-9839-612b506625c8.jpg)
![Screenshot_2021-06-14-15-01-08-428_eu kanade tachiyomi](https://user-images.githubusercontent.com/22109528/121859795-598e1d00-cd22-11eb-829d-3e2aa36dbdad.jpg)

Full screen gestures mode:
![Screenshot_2021-06-14-15-01-50-870_com android settings](https://user-images.githubusercontent.com/22109528/121859922-84787100-cd22-11eb-8dc2-ba89d5cd5e6f.jpg)
![Screenshot_2021-06-14-15-00-38-685_eu kanade tachiyomi](https://user-images.githubusercontent.com/22109528/121859933-86423480-cd22-11eb-9807-a5ffe2658e42.jpg)

**Comment by arkon** [comment]
We use the standardized way of handling insets. Xiaomi will need to fix their software to follow Android standards.
