### ISSUE TITLE
[Feature Request] Force dual page split option for each manga

### ISSUE THREAD

**Issue by Mark-Joy** [tachiyomiorg/tachiyomi#5125]
## Why/User Benefit/User Problem
Some manga have dual page format by default, but currently can't be split even if the split option was enabled because there are some logics under it.
![Screenshot_2021-05-21-14-23-10-661_eu kanade tachiyomi](https://user-images.githubusercontent.com/22109528/119100881-9aa45180-ba42-11eb-9d2b-469eac7d7c96.jpg)

## What/Requirements
Please make the "force dual page split" for each manga.

**Comment by CrepeTF** [comment]
That's not dual page, that's single page

**Comment by CarlosEsco** [comment]
if you provide an actual dual page example that is not splitting then feel free to reopen

**Comment by Mark-Joy** [comment]
Yeah, maybe the page is split in 2 columns is more accurate term in this case.
But the principal is the same. Here you have to read the right column all the way down, then read the left one all the way down. I have to zoom in everytime I read, otherwise can't see the words and pictures clearly on my phone.
Force split option is clearly help in this case.
The name of the manga is: Machikado Mazoku

**Comment by vengiare** [comment]
https://en.wikipedia.org/wiki/Glossary_of_comics_terminology#Spread

**Comment by ghostbear** [comment]
That is a 4-koma with 2 skits per page, and it meant for the reader to know that it read column per column. `Dual page split` is meant to be used on spreads and not single pages.

And with the example you provided there will be things that ruin the reading experience like the speech bubble in the middle will be chopped and hard to read.
![image](https://user-images.githubusercontent.com/6576096/119177967-59756700-ba6d-11eb-9f93-9632be3327d9.png)
^ Red line marks where it chops the page roughly 

So I don't think it a great idea to introduce forced `Dual page split`

**Comment by CrepeTF** [comment]
The whole half page would also be lopsided since there would be an ill-sized padding on the side of the 4koma

**Comment by Mark-Joy** [comment]
It's true that different pages may divide the column's size a little bit different. Here is an example when viewing in "continuous vertical" mode.

![IMG_20210522_093726](https://user-images.githubusercontent.com/22109528/119215889-ae12f380-bafa-11eb-8cd9-6a839a8b7d65.png)

So, instead of clearly cut the image in the middle and display it as "fit width", we can display the image as "fit height" and calculate the "width". By this, it would never miss the "width" content even if the column's size is a bit ill-defined. Something like the below would work.
![Screenshot_2021-05-22-12-31-59-946_eu kanade tachiyomi](https://user-images.githubusercontent.com/22109528/119216119-eb2bb580-bafb-11eb-90e2-ab594270b906.jpg)

Or we can simply display "a little more width" for both columns (can be calibrated) to prevent missing the contents.

**Comment by CarlosEsco** [comment]
Yea this gonna be a no
