### ISSUE TITLE
[Feature Request] App-wide tag blacklisting/blocking

### ISSUE THREAD

**Issue by Matakor** [tachiyomiorg/tachiyomi#5126]
## Why / Benefit

User can specify certain tags that they don't want to appear during normal browsing

## How it would work

Setting toggle for "blacklist" where a user could input certain tags they do not want to see during browsing or searching. (E.g, sexual violence, rape, etc)

Manga already in library could be excluded or included based on a separate setting?

During normal browsing in an extension or title searching, manga/manwha/comics/etc with blacklisted tags would no longer appear.

This should probably be over-ridden in the case of a filtered search, but maybe only if specifically selected? (Likely would need extensions to be modified to support, but I'm not a programmer, I don't know)

**Comment by arkon** [comment]
Tags aren't known until you open an entry, so this isn't possible.

Some sources may offer search filters if the website supports it.
