### ISSUE TITLE
[Bug] <Mangadex library update error>

### ISSUE THREAD

**Issue by ArzuHrpt** [tachiyomiorg/tachiyomi#5129]
#App version: 0.10.12-3368 (standard, 09c07faa, 60)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.N960FXXS8FUC4
Device brand: samsung
Device manufacturer: samsung
Device name: crownlte
Device model: SM-N960F
Device product name: crownltexx

## Steps to reproduce
1. Check for updates
2. See the updated manga without issue

### Expected behavior
Should be able to check updates without issue and aside from that if there are any updates for the extension itself, it should be shown properly too.

### Actual behavior
For a while now Mangadex gives the same error and doesn't update manga. It says "migrate from mangadex to mangadex to see updates" however when I check for updates about the extension, none comes out. And there is no new extension with same name or something similar like the ones we migrated before. I will add a screenshot of the note here if I can. Thank you for your time. 

![SmartSelect_20210522-014024_Word](https://user-images.githubusercontent.com/57169390/119205333-aaeb1980-baa0-11eb-9571-c85ec3e9dfa8.jpg)

**Comment by arkon** [comment]
From Discord:

---

For users that need to migrate from the old MangaDex IDs to the new MangaDex UUIDs, one of our contributors has made a small app that migrates all the manga at once with perfect accuracy.

https://github.com/ivaniskandar/tachiyomi-mangadex-migrator/releases/latest

Note: .JSON support is currently broken and may not be fixed
To use this app, follow these steps:
1. Make a backup of your library. 
Make sure it isn't corrupted by trying to restore from that backup
2. Let the app process the backup. If any manga are skipped, the app will say why.
3. Remove all MangaDex manga from your library to prevent duplicates. 
You can do this by searching "mangadex" in the search bar, tap and holding a manga, then press the select all button (tap the image link below to see what it looks like), and finally tap the trash can.

Do not check "Downloaded chapters" if you'd like to keep your downloaded chapters. The downloaded chapters should be automatically detected once you restore.
4. Restore the new backup. Make sure it ends in .proto.gz

Important that you do step 3 as there's no way to automatically sort out the old manga.
https://cdn.discordapp.com/attachments/489436766013489163/840814029759971348/select_all_white_192x192.png

**Comment by ArzuHrpt** [comment]
Thanks a lot 😊
