### ISSUE TITLE
[Bug] Library button dissapear

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5135]
## Device information
* Tachiyomi version: r3368
* Android version: 10
* Device: redmi 8

## Steps to reproduce
1. search something in library
2. open manga
3. back to library
4. remove search input

### Expected behavior
button on top show back

### Actual behavior
button replaced by unusable three dot 

## Other details
didnt happen to stable

<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/845612144254124043/IMG_20210522_174038.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/845612285681598474/IMG_20210522_174111.jpg">
</table>

**Comment by AntoineGS** [comment]
Good catch ;)
