### ISSUE TITLE
[Feature Request] Automatic Manga Mover / Unregistered File Deleter

### ISSUE THREAD

**Issue by EyangKodok** [tachiyomiorg/tachiyomi#5136]
## Why/User Benefit/User Problem

-make user able to remove downloaded manga that they already read that they haven't delete yet or automatic deleter not used by user yet to remove space.
-user might already have way too many manga that they already download and forget to delete, that pile up, ie. mine which pile up to 66gb.
-they might have like 500+ manga to look through which is not worth the effort and better to just delete all and then redownload.

## What/Requirements

-it move registered manga (from user fav) to new ditectories.
or
-it delete unregistered manga or files (manga thats not on fav or manga that not registered as downloaded from user) but not from local folder

**Comment by arkon** [comment]
1. #2289
2. Kind of #2108, but the solution would be to have the cleanup function from J2K.
