### ISSUE TITLE
[Feature Request] Add comments after each chapter

### ISSUE THREAD

**Issue by hari01584** [tachiyomiorg/tachiyomi#5138]
## Why/User Benefit/User Problem
Like most of the other manga reading apps, they have comments in the last(or somewhere), although being not a part of chapter, the comment improves reading experience a lot, it allows you give your own thought while reading what others think, I believe comments must be an important feature to be implemented and as soon as possible.

## What/Requirements
Knowledgeable about Android dev and web scraping or API usage to get different sites comments, or make tachiyomi exclusive comments platform system.

**Comment by arkon** [comment]
#4336
