### ISSUE TITLE
[Bug] RIFF (little-endian) data, Web/P image : are loded as blank images

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi#5139]
## Device information
* Tachiyomi version: r3368
* Android version: 10
* Device: Samsung S10+

## Steps to reproduce
1. Open Chapter containg image in the format of `RIFF (little-endian) data, Web/P image
`

### Expected behavior
Image Should be displayed

### Actual behavior
Getting a blank image

## Other details
Work fine as cover image

The image file examples I have are NSFW

**Comment by inorichi** [comment]
I have a picture in `RIFF (little-endian) data, Web/P image, VP8 encoding, 1365x2048, Scaling: [none]x[none], YUV color,` that is properly decoded. I'd need the failing pictures in order to test why it happens. If you want you can send me an email to len@kanade.eu with a .zip

**Comment by jopejoe1** [comment]
Send an email with the images that are failing to you.

**Comment by inorichi** [comment]
I see. The reason it happens is because they're animated WebP, and that's not supported.

I could just decode the first frame (but it wouldn't be animated) or try to integrate a better header parsing into tachiyomi and fallback to Coil/Glide (this is done for GIF files only), as SSIV won't be able to handle animated images (it's too tied to Bitmap). Thoughts @arkon?

**Comment by arkon** [comment]
We use Coil now, and it only supports animated WebPs in Android 9.0+: https://coil-kt.github.io/coil/getting_started/#supported-image-formats

I'd be fine with it showing it as animated in Android 9.0+ and as the first frame in lower versions, but definitely wouldn't want to try to support animated WebPs in lower versions.

**Comment by inorichi** [comment]
I guess I could provide Coil an AnimatedDrawable from our decoder to support all platforms, but it won't be easy at the moment as there are no interfaces for animated images.

For now, I'll decode the first frame if the decode function is called. Later on, I'll add another function to the decoder to check if a given InputStream contains an animated image.
