### ISSUE TITLE
[Feature Request] Add folders within the library.

### ISSUE THREAD

**Issue by MadHub223** [tachiyomiorg/tachiyomi#5153]
## Why/User Benefit/User Problem
This feature would benefit those who have many Mangas from different sources, genres, etc, to be able to organize themselves and create a way to not have to scroll all the way through their library to find a manga they forgot the name of.

## What/Requirements
It would react the same way of pressing down and holding a manga in the library, but on the top, it would give the option to create a folder, like with Android devices, and with that, you can set the name and maybe a border color of the primary colors to give a sense of uniqueness to the folder. After the folder has been created, it would sit at the top of the library no matter the changes to order in the library. To add another manga, simply, hold and select those you want to add, then at the top, it would give the option to add to existing folder.

**Comment by Riztard** [comment]
there is a thing called categories

**Comment by Riztard** [comment]
explore the app or check website for guide https://tachiyomi.org
