### ISSUE TITLE
[Bug] Missing places for Ripple

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi#5154]
# Unfixed

## No results found
Related file: [`EmptyView.kt` #L60](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/widget/EmptyView.kt#L60)
Setting `setRippleColorResource` works but it requires a Color and not just the theme color attribute.

| No results found |
| --------------------------- |
| <img src="https://user-images.githubusercontent.com/10836780/119270062-2a8cfb80-bbfb-11eb-90fd-fb8ce417c9f4.png" height="200" /> |

Both of the images below are affected somewhat by `Theme.Widget.Button.Action`.
This style is imported here on [`EmptyView.kt` #L46](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/widget/EmptyView.kt#L46)

Except I can't find a way to actually set it for the `EmptyView` one.

| EmptyView | Library Buttons |
| ---------- | ------------------- |
| ![EmptyView](https://user-images.githubusercontent.com/10836780/119589096-67f7b180-bdd2-11eb-8455-8688ef7b009e.png) | ![Library Buttons](https://user-images.githubusercontent.com/10836780/119589132-7e9e0880-bdd2-11eb-9f4f-898e87985ba4.png) |

## Material dialogs buttons
After hours of testing, I've yet to manage to succeed with this.
| Material dialogs buttons |
| --------------------------- |
| <img src="https://user-images.githubusercontent.com/10836780/119270106-5c9e5d80-bbfb-11eb-9527-b4ffbe358aad.png" height="200" /> |

# Fixed

## Dialog highlight
Fixed by #5197.

## Source filter dropdown
Fixed by #5197.

## Tracker login pw revealer
Fixed by #5197.

## Download cancel/etc dialog
Fixed by #5197.

**Comment by vengiare** [comment]
https://github.com/afollestad/material-dialogs/blob/main/documentation/CORE.md#ripple-color

> Related doc: [afollestad/material-dialogs](https://github.com/afollestad/material-dialogs/blob/main/README_OLD.md#global-theming)

Have you looked at [Core tutorial?](https://github.com/afollestad/material-dialogs/blob/main/documentation/CORE.md#ripple-color)
