### ISSUE TITLE
[Bug] <Unexpected Crash>

### ISSUE THREAD

**Issue by Alexluther5** [tachiyomiorg/tachiyomi#5155]
## Device information
* Tachiyomi version: J2K 1.0.17
* Android version: 9(pie)
* Device: Xiaomi Note 3

## Steps to reproduce
1. Reading or downloading 

### Expected behavior
The app should works normally.

### Actual behavior
Sometimes the app crashes unexpectedly.

## Other details
This crashing suddenly started happening yesterday. The app version was still 1.0.13. So, I thought the app needed to upgrade. Even after updating to 1.0.17, the crashing is still happening. The crashing becomes more frequently as the time goes by.

--------- beginning of system
--------- beginning of main
05-23 23:51:43.229 28843 28843 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
05-23 23:51:45.270 28843 28868 E SQLiteLog: (284) automatic index on newest_chapter(_id)
05-23 23:52:15.016 28843 29013 E SQLiteLog: (284) automatic index on newest_chapter(_id)
05-23 23:52:22.047 28843 29013 E SQLiteLog: (284) automatic index on mangas(_id)
05-23 23:54:07.956 28843 29316 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.j2k
05-23 23:54:07.956 28843 29316 E ACRA    : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at java.lang.Thread.run(Thread.java:764)
05-23 23:54:07.956 28843 29316 E ACRA    : Caused by: rx.exceptions.OnErrorNotImplementedException: interrupted
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:42)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:209)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:57)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:25)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10423)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10390)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10195)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:307)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:50)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-23 23:54:07.956 28843 29316 E ACRA    : 	... 6 more
05-23 23:54:07.956 28843 29316 E ACRA    : Caused by: java.io.InterruptedIOException: interrupted
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okio.Timeout.throwIfReached(Timeout.kt:98)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okio.OutputStreamSink.write(JvmOkio.kt:53)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http2.Http2Writer.connectionPreface(Http2Writer.kt:62)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.kt:497)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http2.Http2Connection.start$default(Http2Connection.kt:495)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealConnection.startHttp2(RealConnection.kt:358)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:341)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:56)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
05-23 23:54:07.956 28843 29316 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:35)
05-23 23:54:07.956 28843 29316 E ACRA    : 	... 30 more
05-23 23:54:07.956 28843 29316 E ACRA    : 	Suppressed: java.net.NoRouteToHostException: Host unreachable
05-23 23:54:07.956 28843 29316 E ACRA    : 		at libcore.io.IoBridge.connect(IoBridge.java:132)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.Socket.connect(Socket.java:621)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
05-23 23:54:07.956 28843 29316 E ACRA    : 		... 49 more
05-23 23:54:07.956 28843 29316 E ACRA    : 	Suppressed: java.net.NoRouteToHostException: Host unreachable
05-23 23:54:07.956 28843 29316 E ACRA    : 		at libcore.io.IoBridge.connect(IoBridge.java:132)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at java.net.Socket.connect(Socket.java:621)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
05-23 23:54:07.956 28843 29316 E ACRA    : 		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
05-23 23:54:07.956 28843 29316 E ACRA    : 		... 49 more
05-23 23:54:12.731 29439 29439 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
05-23 23:54:14.544 29439 29465 E SQLiteLog: (284) automatic index on newest_chapter(_id)

**Comment by arkon** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K

**Comment by Alexluther5** [comment]
Sorry I thought it was J2K github.
Seems I got in the wrong place.
