### ISSUE TITLE
[Bug] lag in settings

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi#5156]
## Device information
App version: 0.10.12-3411 (standard, 7875f363, 61, 2021-05-23T16:39Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T865XXU4CUC1
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea

## Steps to reproduce
1. Shiwtch between tabs, expexially the "more" one
2. Video: https://youtu.be/DOc8vvCzr3Y 

### Expected behavior
Not seeing the previous tab for a split second 

### Actual behavior
When changing page you can see the previous one for a split second, it seems like half the screen updates before the rest.

**Comment by arkon** [comment]
Caused by #5152, will be reverted for now.
