### ISSUE TITLE
[Bug] Sorting by descending make it so next chapter is previous chapter

### ISSUE THREAD

**Issue by ghostbear** [tachiyomiorg/tachiyomi#5157]
## Device information
* Tachiyomi version: r3411
* Android version: 11
* Device: OnePlus 8

## Steps to reproduce
1. Sort any of the sorting options with descending ( ↓ )
2. Read manga, R2L
3. Read to the end of chapter

### Expected behavior
No next chapter

### Actual behavior
Goes to previous chapter

## Other details
Guessing this was introduced with aefd2bf6f89c327b11c443de1fe51e45822af432

**Comment by Kithio** [comment]
I dunno if I should make a new bug post for this as well, it's same  behavior problem in infinite scrolling layout (Webtoon Layout) with the default sorting which is descending.

Before the latest updates, Even if Chapter 1 is listed at the bottom, going to the last page and continuing to scroll would take me to chapter 2 which is listed above it... That no longer happens and instead I'm taken to a "no chapter" or the previous chapter, It's quite bothersome

**Comment by jhrdcr87** [comment]
Reading mode didn't matter (L2R/R2L/Webtoons), reading until the end will bring previous chapter as Next.
If Skip read chapters is on then we'll get no more chapters.

Temporary solution:
Change chapter list sorting from descending to ascending
