### ISSUE TITLE
[Feature Request] Use dialogs instead of sheets for tablets

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#5160]
## Why/User Benefit/User Problem
Bottom sheet is hard to reach and pull up in tablet, would be better to have it as a dialog instead

## What/Requirements
Make it a dialog instead of sheet for tablets

**Comment by arkon** [comment]
Don't see why this would apply specifically to tracking and not every other sheet. 

This would ideally be done for everything, but the framework doesn't let you do it very easily unlike on iOS. Maybe something to experiment with though, since `BottomSheetDialog` is kind of a dialog?

**Comment by joseph619** [comment]
Yeah it could be done for other sheet too, I only mentioned tracking since that's what I use most often.

**Comment by arkon** [comment]
I'm going to close this since it isn't an easily implementable thing right now. I do see trends changing in Android 12L+ though, so maybe we'll revisit this in the future if they provide something.
