### ISSUE TITLE
[Bug] manga disappearing

### ISSUE THREAD

**Issue by Kyousei11** [tachiyomiorg/tachiyomi#5162]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: Samsung note 10+

## Steps to reproduce
1. favourite the manga
2. read all of the chapters

### Expected behavior
should be visible after i read all of the chapters

### Actual behavior
my favourites keeps disappearing when i read all of the chapters
the manga actually still is in my favourite but when i try to search for it in my library, nothing came up. when i search globally it's still there and as my favourites. it's a small issue but an annoying one 

## Other details
Before reading all of the chapters

![Screenshot_20210524-093539_Tachiyomi](https://user-images.githubusercontent.com/84692940/119290997-e5f37580-bc77-11eb-9c3b-3e2d4c46078a.jpg)

after reading all of the chapters 

![Screenshot_20210524-093712_Tachiyomi](https://user-images.githubusercontent.com/84692940/119291076-06233480-bc78-11eb-81d2-49913b02c2cf.jpg)

Global search

![Screenshot_20210524-093857_Tachiyomi](https://user-images.githubusercontent.com/84692940/119291132-16d3aa80-bc78-11eb-8597-14469ff11458.jpg)

**Comment by dhruvsaran** [comment]
Ok same thing happening here but somewhat different. The mangas get removed from favorites and when I search for them they are their in the site but have been reoved from my favourite list. I'm afraid to loose the mangas that i have read and might forget about.

**Comment by CarlosEsco** [comment]
@Kyousei11 you have a filter enabled at top, can  you disable it and then search. I have a feeling the filter is filtering out the manga after you read it

**Comment by Kyousei11** [comment]
> @Kyousei11 you have a filter enabled at top, can you disable it and then search. I have a feeling the filter is filtering out the manga after you read it

God why am i so dumb, Thanks for the advice. It was the filter l, like bruh. Thx @CarlosEsco

**Comment by CarlosEsco** [comment]
@dhruvsaran open a new ticket and provide all your info in it
