### ISSUE TITLE
[Feature Request] Automatic Refresh Tracking

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#5165]
## Why/User Benefit/User Problem

- There are users that uses Tachiyomi on their Android Tablet, Android Smartphone and Android Emulator on Desktop. Each perhaps has a copy of restored backup of the most recent backup version.

- However, the syncing of read history across devices is not real time since you have to go to Settings > Advanced > Refresh Tracking on the Tachiyomi app to manually sync the Read Status of the chapters based on the tracking service.

- Automating the Refresh Tracking function will allow real-time or scheduled syncing across devices to ensure whichever device you use with Tachiyomi. It will always has the up-to-date read history.

## What/Requirements

- On Settings > Tracking. Add "Automatic Refresh Tracking" as an option.
- If "Enabled", it can either have its own schedule sync or it will follow the Update frequnecy found on Settings > Library > Global Update settings.

**Comment by 8227846265** [comment]
Additional Notes:

- It seems "Refresh Tracking" via Anilist doesn't update the Read Chapters that are downloaded. It would be better if it's automatically read as well.

**Comment by loocool2** [comment]
#5166 should fulfill everything in your top comment
#3705 should sync read tracked chapters but it's not automatic

**Comment by 8227846265** [comment]
#5166 - Will this be available on the upcoming version of Tachiyomi (Stable) or I have to download Beta for it?

#3705 - Yes, if this function can be combined with 5166 wherein it automatatically mark as read the chapters that are below the current read chapter on the Tracker. That would be better.

Since Anilist also works via MAL-Sync and readers can perhaps read ahead via reading on their desktops.

**Comment by loocool2** [comment]
if #5166 is accepted, it should be available in the next stable. Once #3705 is accepted in 0.11.x, it may require another PR to make it automatic

**Comment by 8227846265** [comment]
Noted on this. Thank you. Keep up the good work :)
