### ISSUE TITLE
[Feature Request] <Easier way to delete downloaded chapters and mark as unread>

### ISSUE THREAD

**Issue by Aguiar16** [tachiyomiorg/tachiyomi#5179]
## Why/User Benefit/User Problem
Currently we have to select all chapters one by one to mark as unread, and this is really difficult if we're trying to read again, from the beggining, a manga with 300+ chapters.

Mass deleting of downloaded chapters have the same problem, we have to delete 1 by 1, or search for the folder to delete from there.

## What/Requirements
for the first feature, a button with "read again from the begginning" that would unmark all the chapters as readed, after a confirmation.

for the second, a downloaded chapter manager, in the manga page or outside, that make easier to know/locate/manage the downloaded chapters

**Comment by arkon** [comment]
> for the first feature, a button with "read again from the begginning" that would unmark all the chapters as readed, after a confirmation.

You can select multiple things at once by either:
- Long pressing your first item, then long pressing another item. This will select everything in between those two as well.
- Long press something. Use the select all icon from the menu at the top right to select everything.

> for the second, a downloaded chapter manager, in the manga page or outside, that make easier to know/locate/manage the downloaded chapters

Not much point to this, you can only have a single download location and everything is named accordingly.
