### ISSUE TITLE
Make dead space in tablet view scrollable for chapter list

### ISSUE THREAD

**Issue by siteod** [tachiyomiorg/tachiyomi#5180]
## Why/User Benefit/User Problem
In the new tablet view apparently the idea is to have the description auto expanded in the left side panel all the time, but when the description is tiny, in portrait mode this leaves multiple inches of dead space. 

First off, there isn't a need to have the description and tags shown 100% of the time when using the app at all. Reading the description is only useful if you are looking at a title for the first time. If you want to see tags, scrolling up or pressing "More" is not at all hard to do. If you are following a title there is literally no need to ever see it, and carving off a chunk of screen real estate to show me something I don't need to look at is pointless. 

Moreover, this actually reduces the functionality of the UI because this cuts off the user from being able to use the app while holding a tablet in their left hand. I can no longer scroll the chapter list, or press/long press on chapters when holding the tablet with only my left hand. As far as I can tell this layout only eliminates functionality I use on a regular basis, and there does not seem to be anything gained.

## What/Requirements

According to the discord an option to just choose to use the old layout has been rejected, so I guess at least some ability to actually use the library portion of the app with the assumption that you are holding the tablet with your left hand? Maybe have the left side panel able to be slid off screen to allow access to the chapter section? Or at least make it so if you slide up or down from the bottom left corner the chapter list will scroll in the corresponding direction?

**Comment by arkon** [comment]
I'm sorry, but you'll just have to get used to it. As Google pushes for these designs on foldables/tablets, more and more apps will be like this anyway.

**Comment by siteod** [comment]
Tachiyomi isn't even on google play so what do you care about their specs

**Comment by siteod** [comment]
> 
> 
> Tachiyomi isn't even on google play so what do you care about their specs



> 
> 
> I'm sorry, but you'll just have to get used to it. As Google pushes for these designs on foldables/tablets, more and more apps will be like this anyway.

Tachiyomi isn't even on google play so what do you care about their specs
