### ISSUE TITLE
[Bug] <Gifs is not playing>

### ISSUE THREAD

**Issue by abdu99** [tachiyomiorg/tachiyomi#5190]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: huawei P30 pro

## Steps to reproduce
1. Open any chapter that contains gifs

### Expected behavior
gifs should start playing

### Actual behavior
gifs displayed as a still image

## Other details
this was working but after the latest update it broke, and if i try to download the chapter the gifs are downloaded as jpg

**Comment by abdu99** [comment]
luscious, everything with gifs in it are not playing.

**Comment by arkon** [comment]
Seems like an extension issue, some of them seem to work fine.
