### ISSUE TITLE
[Bug] Crash on Webtoon

### ISSUE THREAD

**Issue by starscream00** [tachiyomiorg/tachiyomi#5191]
## Device information
* Tachiyomi version: 0.10.12/J2k:1.0.17/SY:1.6.2
* Android version: 7.1. 1
* Device: Fujitsu F-02H 

## Steps to reproduce
1. First step : Open app
2. Second step : extension : Webtoonxyz & Toonlily
3. Download Crime and Punishment chap 19 or any webtoon with many parts
4. Read chap 19 : instant crash or crash when loading next chapter (I'm offline) 

### Expected behavior
Normal usage and failed to load next chapter message 

### Actual behavior
Crash

## Other details
Additional details and attachments.
Affect Tachiyomi, TachiyomiSY(latest & preview) and TachiyomiJ2k(latest) 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.
--------- beginning of system
--------- beginning of main
05-25 16:47:40.286 28071 28248 E SQLiteLog: (284) automatic index on C(manga_id)
05-25 16:47:40.286 28071 28248 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
--------- beginning of crash
05-25 16:48:11.214 28071 28334 E AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-11
05-25 16:48:11.214 28071 28334 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 28071
05-25 16:48:20.685 28497 28643 E SQLiteLog: (284) automatic index on C(manga_id)
05-25 16:48:20.686 28497 28643 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 7.1.1 (SDK 25)
Android build ID: V09R048A
Device brand: DOCOMO
Device manufacturer: FUJITSU
Device name: F02H
Device model: F-02H
Device product name: F02H

**Comment by starscream00** [comment]
- download chap 19 & 20 of crime and Punishment, then goes offline(data off) 
- read chap 19, no problem, the crash occurs when loading chap 21 but no internet.

**Comment by SamSensei** [comment]
Similar issue #5151 
Update in last comment with same issue
