### ISSUE TITLE
[Feature Request] Cap initial bottom sheet height to 50% again

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5200]
## Why/User Benefit/User Problem
![IMG_20210526_161941](https://user-images.githubusercontent.com/63973749/119626926-48966e00-be3e-11eb-8854-f4ca56e67cda.jpg)

## What/Requirements
Reverts 1557f71 I believe.

**Comment by arkon** [comment]
Related: #5183

I assume you mean the source filter sheet though, of which the linked commit is irrelevant to.

**Comment by vengiare** [comment]
> I assume you mean the source filter sheet though

I meant all the sheets, but the issue was made the same day this commit added the 50% cap back https://github.com/tachiyomiorg/tachiyomi/pull/5183/commits/0a1f08c27ab5f07a37019f862e8fd710fbab9858

**Comment by vengiare** [comment]
> It was never 50% before though.

That's the point. It was like this before.

![Screenshot_2021-06-01-20-35-42-064_eu kanade tachiyomi](https://user-images.githubusercontent.com/63973749/120324307-104ccf00-c319-11eb-9e0c-ac19ab64dfed.jpg)

And I made this issue 3 hours before 0a1f08c

**Comment by arkon** [comment]
So you're complaining that the default, as per the specs, is too high?

**Comment by vengiare** [comment]
Dunno about it but their website says it should be 50% for reachability.

![image](https://user-images.githubusercontent.com/63973749/120325390-2c04a500-c31a-11eb-83db-509e3750071b.png)

**Comment by arkon** [comment]
You should make an issue in the Material Components issue tracker then.

**Comment by vengiare** [comment]
This is a feature request, not a bug report.
