### ISSUE TITLE
[Bug] <Mangairo loading gif>

### ISSUE THREAD

**Issue by ligneo** [tachiyomiorg/tachiyomi#5204]
## Device information
* Tachiyomi version: v0.10.12
* Android version: 10
* Device: oneplus 5t

## Steps to reproduce
1. First step : open tomb rider king mangairo chapter 207-208
2. Second step in page 3-4 you see a loading gif

## Other details
![Screenshot_20210526-213102.jpg](https://user-images.githubusercontent.com/29066289/119713418-582bac00-be6a-11eb-9975-1e0dec364eae.jpg)![Uploading f0{951d4f4} (53ab5cc1-54ac-4538-980a-b0550c25ca1d > id=0x7f0a01b2 tag=CreateIssueFragment) …]()![Screenshot_20210526-213055.jpg](https://user-images.githubusercontent.com/29066289/119713558-7ee9e280-be6a-11eb-85b8-05840bd17eea.jpg)

**Comment by arkon** [comment]
Wrong repo, refer to the acknowledgement section that you're supposed to read.
