### ISSUE TITLE
[Bug] border cropping issue - Split, zoomed panals

### ISSUE THREAD

**Issue by spicysweetboy** [tachiyomiorg/tachiyomi#5210]
## Device information
* Tachiyomi version: App version: 0.10.12-3417 (standard, a462ce36, 61, 2021-05-23T18:33Z)
Android version: 10 (SDK 29)
Android build ID: QPWS30.61-21-18-7
Device brand: motorola
Device manufacturer: motorola
Device name: lake_n
Device model: moto g(7) plus
Device product name: lake_n

## Steps to reproduce
1. First step
Open Tachiyomi
2. Second step
Read any manga

### Expected behavior
Normal rendering

### Actual behavior
Pages breaks where there shouldn't be, with one half zoomed in and the other half normal (e.g. speech bubble cut in half horizontally, bottom half of the bubble is twice as big. Text size is also magnetized.) ** This happens across sources and in old chapters as well, thus an app problem rather than source issue.

## Other details
Tachiyomi won't let me screenshot, so I can't share an image of the issue, but it is described above.

**Comment by loocool2** [comment]
Turn off crop borders, then turn off secure screen so you can screenshot. 

https://tachiyomi.org/help/guides/reader-settings/#crop-borders

**Comment by spicysweetboy** [comment]
> Turn off crop borders, then turn off secure screen so you can screenshot.
> 
> https://tachiyomi.org/help/guides/reader-settings/#crop-borders

Looks like it was a cropping issue! Turning off cropped borders fixed the issue! But I've attached an image of the issue - as this is now a bug with border cropping! *Not the cropping issue in both the image of the two on the couches as well as the text section below*
![Screenshot_20210526-215927](https://user-images.githubusercontent.com/64571873/119768592-b908b380-be6d-11eb-84c6-59e56c5bd863.png)

**Comment by arkon** [comment]
It's probably working fine on the overall image. If not, please open another issue with the specific pages that aren't cropped properly.
