### ISSUE TITLE
Filtering Manga/Webtoon in your library based on extension 

### ISSUE THREAD

**Issue by Kato13** [tachiyomiorg/tachiyomi#5211]
## Why/User Benefit/User Problem

I decide to suggest this "filter" feature because last time MangaBat Extension was deleted on Tachiyomi and apparently most of the manga in my library are using MangaBat as an extension. Having 5-10 Manga/Webtoon in your library when you encounter this kind of problem wouldn't bother you but unfortunately I have over 50 Manga/Webtoon in my library for me to migrate to another working extension, and having my Manga filtered based on the extension I have chosen would definitely saved me a lot of time.

## What/Requirements
The Filter will act as how the other filter do by showing Manga/Webtoon in your library based on what extension you filtered.

**Comment by Riztard** [comment]
you can use migrate in te browse>migrate

**Comment by Kato13** [comment]
> you can use migrate in te browse>migrate

Ah.I am very sorry, I didn't knew it was there. Should I delete the issue?

**Comment by Riztard** [comment]
just close the issue
