### ISSUE TITLE
[Bug] massive amount of history removed

### ISSUE THREAD

**Issue by BOBAHSAUR** [tachiyomiorg/tachiyomi#5214]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 11
* Device: Pixel 3

## Steps to reproduce
1. Open the app 
2. Global update (pull down)
3. Go to updates and see almost everything gone (might have been gone before but that's when I first saw it)

### Expected behavior
Should have updates history everyday since I update every morning

### Actual behavior
Missing updates/history for almost every single day
 
## Other details
History
![Screenshot_20210527-121020](https://user-images.githubusercontent.com/84926320/119862664-bb5b2400-bee6-11eb-9d25-3f708301013b.png)
Updates
![Screenshot_20210527-121010](https://user-images.githubusercontent.com/84926320/119862750-d29a1180-bee6-11eb-9b78-6ec5ba9b728a.png)

**Comment by CrepeTF** [comment]
What source are you using

**Comment by arkon** [comment]
Probably affected by a source that lost chapter upload date data.
