### ISSUE TITLE
[Feature Request] Automatic smooth line-to-line scrolling. 

### ISSUE THREAD

**Issue by desito** [tachiyomiorg/tachiyomi#5219]
Hello,

First, this proyect is magic, thank you very much.

My request is:

In the forks of tachiyomy there are automatic scrolling functionalities. But they are "leaps and bounds". Each shift marks a leap and the reading is comfortable but not perfect.

In other types of text readers I have seen another type of scrolling that I think, which especially for webtoons, would be great.

It is a smooth scroll that would slide the image up smoothly. Continuously, from the beginning to the end of the chapter. If the speed of this movement could be selected, we would have a visualization of the ultrcinematographic webtoon.

I think it would be a nice addition. But I leave it to your discretion.

Thank you again for a wonderful app. 

---

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/2093
