### ISSUE TITLE
[Feature Request] Compare image quality among Sources

### ISSUE THREAD

**Issue by rohan-gt** [tachiyomiorg/tachiyomi#5220]
## Why/User Benefit/User Problem
It would be easy to select the source with the best image quality based on parameters like resolution, file size, format etc.

## What/Requirements
Basically a search functionality that searches for the same title across multiple sources that you've added and sorts them by an image quality parameter that you choose. If there's no manga ID that links the titles across sources, it would be useful to select the titles manually from the results using checkboxes

**Comment by CrepeTF** [comment]
So anyway no

**Comment by loocool2** [comment]
this feature request would require too many network requests to do, and it's out of scope for a manga reader, we're not a image comparison tool
