### ISSUE TITLE
Crashing when going through chapter when using gestures(volume button and touch gesture)

### ISSUE THREAD

**Issue by MFDaus47** [tachiyomiorg/tachiyomi#5229]
I've encountered this big a few times already. It doesn't happen not to all the manga, but when it happens to the certain manga, it wil keep happening everytime i advance trough the chapter.

So far it happened on jujutsu kaisen starting on chap 4 from mangadoom. And shikimori-san not just a cutie from mangalife. 

This bug is quite random, so i don't know if you can recreate it or not. I can't send a video cause it's too big. Please tell me how I can share the video if you want to.

App version: 0.10.12 (standard, 6aff438, 59)
Android version: 9 (SDK 28)
Android build ID: RMX1941EX_11_A.34
Device brand: Realme
Device manufacturer: Realme
Device name: RMX1941
Device model: RMX1941
Device product name: RMX1941

**Comment by MFDaus47** [comment]
Forgot to say that it is not an extension issue as I've checked the other manga from the same extension, and it work just fine

**Comment by loocool2** [comment]
Do you have crash logs that you can attach?

**Comment by MFDaus47** [comment]
> Do you have crash logs that you can attach?

I did press on it, but it doesn't show anything other than my device information. Which is at the last part of my description

**Comment by MFDaus47** [comment]
> Do you have crash logs that you can attach?

I opened it using WPS office and html viewer. Both gave the same thing. Do tell me if there's a specific way to read the file

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by MFDaus47** [comment]
> Please provide crash logs if possible.
> 
> Potential ways of getting them:
> 
> - https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
> - https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

I've tried both of the method, and it failed. But i just tried using opera to open the crash log and i got the log.


--------- beginning of crash
05-29 22:33:57.549 26738 26738 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:33:57.549 26738 26738 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 26738
05-29 22:33:57.549 26738 26738 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=30; index=-1
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:33:57.549 26738 26738 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:36:33.059 27497 27497 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 27497
05-29 22:36:33.059 27497 27497 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=30; index=-1
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:36:33.059 27497 27497 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:40:21.785 29651 29651 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 29651
05-29 22:40:21.785 29651 29651 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=31; index=-1
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:40:21.785 29651 29651 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:41:45.121 29919 29919 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 29919
05-29 22:41:45.121 29919 29919 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=31; index=-1
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:41:45.121 29919 29919 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:43:34.546 30485 30485 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 30485
05-29 22:43:34.546 30485 30485 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=30; index=-1
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:43:34.546 30485 30485 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: FATAL EXCEPTION: main
05-29 22:47:02.587 30637 30637 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 30637
05-29 22:47:02.587 30637 30637 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=31; index=-1
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.onPageSplit(PagerViewerAdapter.kt:141)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$onPageSplit$1.run(PagerViewer.kt:390)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:226)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7191)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
05-29 22:47:02.587 30637 30637 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
--------- beginning of main
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 9 (SDK 28)
Android build ID: RMX1941EX_11_A.34
Device brand: Realme
Device manufacturer: Realme
Device name: RMX1941
Device model: RMX1941
Device product name: RMX1941
