### ISSUE TITLE
[Feature Request] <Manga Self Migration>

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#5233]
## Why/User Benefit/User Problem
There are some Manga Sources that tends to change the Manga Url on a weekly(more or less) basis so the self migration will directly search for the manga in it's source rather than searching all the sources or only the pinned one.

**Comment by samanta-widjaja** [comment]
I like this as well. Just like manganelo change to manganato, i have a hard time migrating. My library said no chapter, but when i click on the source there are chapter

**Comment by arkon** [comment]
#5338 would be a better idea than this since it'd be less specific.
