### ISSUE TITLE
[Bug] <Update not working>

### ISSUE THREAD

**Issue by Xinnamon** [tachiyomiorg/tachiyomi#5235]
## Device information

App version: 0.10.12 (standard, 6aff438, 59)
Android version: 11 (SDK 30)
Device brand: google
Device manufacturer: Google
Device model: Pixel 4a (5G)

## Steps to reproduce

1. Go to Updates tab
2. Drag down OR press refresh button to check for updates (I tried both)

### Expected behavior

See either new chapters appear OR see notice saying no new updates

### Actual behavior

Nothing happens.
The update bar runs through all my series from library but then nothing happens once it's done. 
No update or notice.

## Other details

update runs all the way through, does not show any errors with the setting under library settings toggled, and I see new chapters for  series when I visit that page in webview/source website that I don't get in app

**Comment by arkon** [comment]
Open issues in the extensions repo if the sources aren't reflecting the sites properly.
