### ISSUE TITLE
[Bug] App crash while trying to browse 

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#5242]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: Samsung Galaxy A11

## Steps to reproduce
1. Open Mangahub or Isekai Scan 
2. Open King of Apocalypse manga, Chapter 320

### Expected behavior
App should open manga

### Actual behavior
Crash

## Other details
User KAZUMA#9584 reported on Discord 

Crash log - [tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6566988/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Seems to be gigantic images, so it's probably running out of memory (it lags on mine). Could try to find a source that splits it into smaller images.

Somewhat related: #4791
