### ISSUE TITLE
[Bug] <Mangas.pw missing chapters>

### ISSUE THREAD

**Issue by bhs642** [tachiyomiorg/tachiyomi#5248]
## Device information
* Tachiyomi version: 0.10.12-3458
* Android version: 10 (SDK 29)
* Device: POCO F1

## Steps to reproduce
1. Open Tachiyomi
2. Select Browse
3. Select Extensions
4. Go to the spanish section 
5. Install manga.pw 
6. Now go to the sources
7. Open Mangas.pw
8. Select any series

### Expected behavior
Show all chapters released 

### Actual behavior
Show only one released chapter or Out of date list of chapters 

## Other details
I do not know if it will have to do, but it may be because the domain of the page changed from mangas.pw to mangas.in

**Comment by KasukeLp23** [comment]
The domain of Mangas.pw a Mangas.in it has nothing to do with it.

NT: This issue must be in "Tachiyomi-extensions" not here
