### ISSUE TITLE
[Bug] Double tapping "Updates" in bottom bar will open download queue twice

### ISSUE THREAD

**Issue by Mymiano** [tachiyomiorg/tachiyomi#5249]
## Device information
* Tachiyomi version: 0.10.12-3465 (standard, 5e5ceef1, 61, 2021-05-30T22:09Z)
* Android version: 10 (SDK 29)
* Device: Mi 9T Pro

## Steps to reproduce
1. Tap "Updates" once to go updates
2. Double tap "Updates" (fast tap)

### Expected behavior
Display download queue once only

### Actual behavior
Download queue open twice and needed to go back twice

### Other details

https://user-images.githubusercontent.com/24500122/120270457-386a0d00-c2dc-11eb-90b4-63f05365911c.mp4

**Comment by Soitora** [comment]
Surprised you can even tap it twice, mine instantly opens first tap
