### ISSUE TITLE
[Bug] Download storing issue

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#5250]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 8
* Device: huawei p8 lite 2017

## Steps to reproduce
1. download the extension HeavenManga
2. Search the manhwa "Dark Mortal"
3. download some chapters

### Expected behavior
The app should save the whole chapter, but since one page is missing, the app when i am offline doesn't allow me to read it( without internet) despite i already downloaded like 12/13 pages (the last one is missing every time on that extension) and every time i download the chapter again the download bar of that chapter acts like there are already pages download (like when you stop the download at like 50/120 pages of a chapter, and later when you start it again seeing the bar going super fast since that pages were already downloaded) so it is a bug.

### Actual behavior
Download failed i can't read it offline (the app downaloded 12/13 and the last one was missing)

## Other details
![Screenshot_20210531-195638](https://user-images.githubusercontent.com/75091899/120228617-c813ab00-c24b-11eb-9686-42f0a9152f2f.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
#3957
