### ISSUE TITLE
[Feature Request] Drag & Drop Download

### ISSUE THREAD

**Issue by venya-san** [tachiyomiorg/tachiyomi#5251]
## Why/User Benefit/User Problem
Users no longer need to download chapters by clicking buttons one by one.

## What/Requirements
The drag and drop download would be like this:

https://user-images.githubusercontent.com/60911510/120308726-9c053200-c2fe-11eb-8dd2-22fc0d35f97d.mp4

**Comment by arkon** [comment]
1. Long press first chapter in range
2. Long press last chapter in range
3. Tap download icon in action toolbar
