### ISSUE TITLE
[Feature Request] add folder libraries for chapter

### ISSUE THREAD

**Issue by sumacool** [tachiyomiorg/tachiyomi#5255]
My concept:
![1622562378873](https://user-images.githubusercontent.com/66295833/120352845-c58c8080-c333-11eb-8db8-839a4d612565.jpg)

Basically you can put the chapter in the custom folder you make it’s kinda like the library but chapter

**Comment by arkon** [comment]
Not going to be added. There's some open issues about customizable bookmarks though, so that could work (although that also likely won't get added anytime soon).
