### ISSUE TITLE
[Feature Request] Tablet UI toggle

### ISSUE THREAD

**Issue by Cheese659** [tachiyomiorg/tachiyomi#5258]
## Why/User Benefit/User Problem
The new tablet ui is not user friendly and creates dead space where there wasnt any aswell as reducing the manga collumns in the library(by default). Also putting the sidebar on the left side without any option to move it to the right is very user unfriendly. This is just my personal opinion but the old interface and layout on tablet was perfect and i fount no issue with it

## What/Requirements
Add a toggle in the general settings to use the old layout so people who dont like the tablet layout dont have to wrestle with it

![Screenshot_2021-06-01-21-41-38](https://user-images.githubusercontent.com/85194868/120381819-3aa38a00-c323-11eb-9711-192469dff3ae.jpeg)
![Screenshot_2021-06-01-21-41-26](https://user-images.githubusercontent.com/85194868/120381833-3ecfa780-c323-11eb-94fb-e3edd8197ced.jpeg)

**Comment by CarlosEsco** [comment]
No plans to support multiple ui. This is following the  suggested material design

**Comment by ronfar-x** [comment]
> No plans to support multiple ui. This is following the suggested material design

This is nonsense. Multiple UI already exist in the application. You already have the old UI available in a non-tablet device. I can install tachiyomi on a non-tablet smartphone and use the old UI, but am FORCED to use the clunky tablet UI in a tablet android device. Just allow a flag to force non-tablet in the app, this shouldn't be so painful for you.

**Comment by arkon** [comment]
See #5292
