### ISSUE TITLE
[Bug] Does not open on Android 12

### ISSUE THREAD

**Issue by mpldr** [tachiyomiorg/tachiyomi#5260]
## Device information
* Tachiyomi version: 0.10.12/0.11.1
* Android version: 12 Beta
* Device: Google Pixel 5

## Steps to reproduce
1. Install Android 12 Beta
2. Open Tachi

### Expected behavior
App opens

### Actual behavior
App does not open

## Other details

https://user-images.githubusercontent.com/33086936/120391402-4137fe80-c32f-11eb-9f68-7a9dc0b0262a.mp4

~~If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.~~
*Hard to do without opening the app*

**Comment by loocool2** [comment]
Tachiyomi currently does not support Android 12 in any capacity as it has not been released yet, and as such we will not be providing support for it. If you run into any issues with it, you can fix them for us as the intended audience for the beta is developers. 
you can grab a logcat if you'd like to see what's happening, but any android beta bug will not be fixed until it is officially out
https://play.google.com/store/apps/details?id=com.dp.logcatapp
