### ISSUE TITLE
[Feature Request] <Exclude specific GENRES using the filters>

### ISSUE THREAD

**Issue by FrostAlev** [tachiyomiorg/tachiyomi#5265]
## Why/User Benefit/User Problem
I think that such a feature will be welcomed by many users.
Like, when I browse a source searching for the next work I will read, I use the filter tool to select some of the categories that I want to find works related to, for example, comedy, adventure, and school life. The application does what is expected of it, which is to show the works related to these categories. That's fine but in this example, I don't want some categories like shoujo or yaoi or ecchi which I don't think there is a way to do right now.
This feature will come in very handy especially while browsing sources with many and varied works.

## What/Requirements
I think that adopting this feature will not pose a problem for the team, especially since it is present in many places in the application such as the library and the chapters filter (screenshot attached), which is when you click the checkbox twice so the mark turns from true to false and thus the specified categories are excluded.

![image](https://user-images.githubusercontent.com/29895907/120405013-e1018680-c347-11eb-98e2-793c15284bf4.png)

**Comment by loocool2** [comment]
That's TachiyomiSy, not mainline Tachiyomi for one. Source tags are not standardized across sources, all the tags aside from Completed you see there are determined by Tachiyomi and not grabbed from the source. I don't think it's worth getting your entire list of tags from manga in your library every time your app starts up and then autopopulating that list if that's what's you're thinking. You can however search "-yaoi" to remove a tag from search though

**Comment by FrostAlev** [comment]
I think you miss understood what I'm trying to say here. please watch this video for more details:
https://drive.google.com/file/d/1yjQ430EgKs1Pt81VYlYRv7slY5zQPE0U/view?usp=sharing
thanks.

**Comment by arkon** [comment]
Thanks for the video, it explained it well.

However, the source filters rely on the websites' available functionality. If you've noticed that some websites have that functionality but the Tachiyomi source doesn't surface it, please open issues in the extensions repo.
