### ISSUE TITLE
[Feature Request]  Range Selection Mode (for manual selecting chapters) 

### ISSUE THREAD

**Issue by nouseeme** [tachiyomiorg/tachiyomi#5266]
## Why/User Benefit/User Problem
I find it difficult when I need to select some particular range of manga chapters. Like when I need to select only the 50th chapter to the 90th chapter. I have to select it manually by tapping the chapters one by one until it all selected. 

## What/Requirements
Create a **`Range Select Button`** by when it is pressed, it automatically **select all the chapters between the two** chapters I selected before.

For Eg, when I need to select ch 50th to 90th, I manually select the 50th one and the 90th one. Then I press the button to select all the chapters between them. It'll be very useful for those who need to download some particular chapters. Tx before. 
![IMG_20210602_085637](https://user-images.githubusercontent.com/82750093/120412282-7f114300-c380-11eb-8610-04fcfbb22d20.jpg)

**Comment by CrepeTF** [comment]
Mate you can hold tap the chapters

**Comment by nouseeme** [comment]
> Mate you can hold tap the chapters

That's not what I mean. I need to select bunch of the chapters between them. It'll be sucks if I have to long tap bunch of chapters. 

What I mean is, create a button that makes the selection easier. Auto select the chapters between them

**Comment by Jays2Kings** [comment]
1. Long tap chapter 60
2. Long tap (not short tap)  chapter 90

All chapters will be selected in between

**Comment by nouseeme** [comment]
> 1. Long tap chapter 35
> 2. Long tap (not short tap)  chapter 41
> 
> All chapters will be selected in between

Tf why didn't I know about it earlier?? Lol

Btw tx mate.
