### ISSUE TITLE
[Bug] Theme not followed inside the reader

### ISSUE THREAD

**Issue by forlorn12** [tachiyomiorg/tachiyomi#5271]
## Device information
* Tachiyomi version: latest (0.11.1)
* Android version: 11
* Device: Samsung galaxy  a31

## Steps to reproduce
1. First step : open any chapter 
2. Second step : go to settings 

### Expected behavior
It must follow theme for example Midnight Dusk 
In my case

### Actual behavior
It shows the default theme 

## Other details
![Screenshot_20210602-121129_Tachiyomi](https://user-images.githubusercontent.com/82667133/120436465-952cfc80-c39c-11eb-8428-4c7a86d73067.jpg)

( the theme set in the settings is  "Midnight Dusk")

**Comment by CrepeTF** [comment]
#5196
