### ISSUE TITLE
Migrate all manga from one source to another

### ISSUE THREAD

**Issue by vagabondsajib** [tachiyomiorg/tachiyomi#5274]
I'm currently facing an issue because **mangenelo** decided to change it's name. All the manga i read from this source is currently not updating when I update my Library. Now how can i migrate all my manga? Thats why I am requesting for a feature that enables users to migrate all their manga from any source if that perticular source have any problem like manganelo.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/1729  

also don't use 1 source only
