### ISSUE TITLE
[Feature Request] Option to have bottom navigation on tablets

### ISSUE THREAD

**Issue by Amasuke** [tachiyomiorg/tachiyomi#5278]
## Why/User Benefit/User Problem
On the tablet, especially as a right handed person it's more awkward to navigate with the side navigation.
On top of that it looks really silly while taking up more space in the vertical orientation.

## What/Requirements
Let the user decide what view is used with an option in the settings menu. (Side navigation or bottom navigation.

Extra:
Split manga info/chapters view would fall into that too.
It would be good to have an option to change the tablet layout to the phone layout.

**Comment by arkon** [comment]
Tablet layout only applies if the width is 600dp or higher, which is deemed as enough space.

Also see https://material.io/components/navigation-rail

**Comment by Ramon20000** [comment]
> Tablet layout only applies if the width is 600dp or higher, which is deemed as enough space.

I fell like that is hardly a reason to force people to use it. Some people don't like it and i feel like it shouldn't be hard to implement a override.


> Also see https://material.io/components/navigation-rail
They are material _guidelines_ not material _rules._ Heck, even google themselves don't follow them to the letter, on my device with 800dp(if my 4am math doesn't fail me) youtube looks like this
![youtube](https://user-images.githubusercontent.com/37456831/120600567-4d9b8480-c41f-11eb-9059-834cd355f114.png) and google play 
![google play](https://user-images.githubusercontent.com/37456831/120603516-838e3800-c422-11eb-9dc0-514b74896afa.png)

**Comment by arkon** [comment]
Google's own internal inconsistency isn't relevant.

We're one of the first apps to adopt the newer pattern anyway, so you can expect more to eventually pick it up.
