### ISSUE TITLE
[Feature Request] <Change in Font>

### ISSUE THREAD

**Issue by Ubdert** [tachiyomiorg/tachiyomi#5279]
I'd like to suggest that the font in the app be changed to Google Montserrat, which is the closest font to Google Product Sans and is free to use.

https://fonts.google.com/share?selection.family=Montserrat

---

## Device information
* Tachiyomi version: 0.11.1
* Android version: 10
* Device: Moto One Power (chef)

## Issue/Request
(Suggestion) Change of font

**Comment by ztimms73** [comment]
Nobody bothers to put the font directly in the phone (firmware) settings.  Many people like the standard font and not everyone will like the font you suggested.

**Comment by arkon** [comment]
The default font is fine. Product Sans (or Montserrat) is generally only used for headings anyway, and I'm not sure if the added asset size is worth it.
