### ISSUE TITLE
[Bug] <Chinese name comic alphabet sorting problem>

### ISSUE THREAD

**Issue by ODBLK** [tachiyomiorg/tachiyomi#5281]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 11
* Device: OnePlus 8T KB2000

## Steps to reproduce
1. library
2. Sort
3.Alphabetically

### Expected behavior
It’s okay for English comics to be arranged from A to Z. Chinese comics cannot be arranged in the order of pinyin A～Z

### Actual behavior
The Chinese name comics do not know in which order they are arranged, they seem to be random.

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
So what's the suggestion? We're just using whatever the default sort is.

**Comment by ODBLK** [comment]
I don’t know how the Chinese comics are sorted. Can the sorting method of Chinese comics be changed to the alphabetical order of the name’s Pinyin initials? For example：猫和我的奇妙生活：MHWDQMSH

**Comment by ODBLK** [comment]
Is it possible to use the Windows sorting method for Chinese? Here‘s the example
![image](https://user-images.githubusercontent.com/25927859/122250974-b2b1a880-cefc-11eb-8db6-eae165b2e3b3.png)

**Comment by ODBLK** [comment]
> So what's the suggestion? We're just using whatever the default sort is.
Is it possible to use the Windows sorting method for Chinese? Here‘s the example
![image](https://user-images.githubusercontent.com/25927859/122251102-cc52f000-cefc-11eb-974d-fd54f8f758d7.png)

**Comment by ODBLK** [comment]
> So what's the suggestion? We're just using whatever the default sort is.

Is it possible to use the Windows sorting method for Chinese? Here‘s the example
![image](https://user-images.githubusercontent.com/25927859/122251206-e2f94700-cefc-11eb-8c53-ddd7ae4e8ba0.png)
