### ISSUE TITLE
[Bug] Ripple feedback doesn't appear on any theme when pressing 'Latest' on Browse

### ISSUE THREAD

**Issue by aodtonix** [tachiyomiorg/tachiyomi#5285]
---

## Device information
* Tachiyomi version: 0.11.1
* Android version: Android 10 (Miui 12)
* Device: Xiaomi Redmi Note 8 (Ginkgo)

## Steps to reproduce
1. Press 'Latest' on Browse Tab

### Expected behavior
Ripple feedback animation when pressing 'Latest' to indicate you pressed it.

### Actual behavior
Nothing happened, just immediately went to the extension's library.

## Other details
None.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Do you have MIUI's force dark mode on?

**Comment by aodtonix** [comment]
> 
> 
> Do you have MIUI's force dark mode on?

Yes.

**Comment by arkon** [comment]
Turn it off then, it tends to break the UI.
