### ISSUE TITLE
[Feature Request] Account Sync

### ISSUE THREAD

**Issue by Ayley** [tachiyomiorg/tachiyomi#5289]
## Why/User Benefit/User Problem
When users use this applikation an two different devices but can not transfer the saved data or the User changed the device quickly

## What/Requirements
When the user starts the app, the library and the progress of the manga should be synchronized so that you can continue reading where you left off

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/912
