### ISSUE TITLE
[Feature Request] Please revert the tablet-specific UI changes

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#5293]
## Why/User Benefit/User Problem
Tachiyomi, like all FOSS, is maintained for free by volunteers, and I, along with the tens of thousands of other people who use the app, are enormously grateful for all the work put in by these volunteers to continue to improve it. Likewise, it is commendable that the volunteers behind the app would commit to creating a tablet-specific experience, especially considering the scarcity of them in other apps, even ones published by companies as big as Google. 

Unfortunately, I, along with a large contingent of the userbase, judging by the discourse on the subreddit and in other GitHub issues, have found the new tablet UI to be a noticeable step backwards, both in terms of aesthetics and usability. The side navigation bar is kind of a pain, as it squashes your manga covers and makes them smaller while simultaneously being harder to navigate with than the old bottom bar navigation. The split description-chapter display for each series, too, uses the available space poorly and is overall a worse experience for tablet users. Overall, while I and many others are very grateful for the effort put forward, we respectfully disagree about the conclusions you have come to about tablet UI design.

## What/Requirements
The changes to tablet UI would be reverted, and the bottom bar navigation and merged manga series layout reinstated.

**Comment by arkon** [comment]
See #5292

**Comment by specterflare** [comment]
I see. While I understand your reasoning, this is still very disappointing. Hopefully at some point in the future, you can rethink this. Until then, thanks for all the work you do.
