### ISSUE TITLE
[Feature Request] Listening to the users

### ISSUE THREAD

**Issue by justmadethis67** [tachiyomiorg/tachiyomi#5294]
## Why/User Benefit/User Problem
When I commented in another "issue", as they are apparently called, about how the app should go back to the old tablet layout, I was told to "See #5292". When I did so, this particular quote caught my eye: 

Q: Why aren't you listening to users?!

A: We are.

Respectfully, I disagree. Below are some of the reactions to the change that I have compiled. Remember, this was only what could find after like 10 minutes of looking. I am sure there is much more out there:

![Screenshot (525)](https://user-images.githubusercontent.com/85300347/120674626-45b10400-c462-11eb-85c3-62c09292b6c2.png)

![Screenshot (526)](https://user-images.githubusercontent.com/85300347/120674635-49448b00-c462-11eb-9485-edb705475aca.png)

![Screenshot (528)](https://user-images.githubusercontent.com/85300347/120674651-4cd81200-c462-11eb-92a9-77b9ca3391bc.png)

![Screenshot (529)](https://user-images.githubusercontent.com/85300347/120674673-53668980-c462-11eb-8392-00d1551fbacb.png)

![Screenshot (530)](https://user-images.githubusercontent.com/85300347/120674700-5bbec480-c462-11eb-9a65-c8bf222b211e.png)

![Screenshot (538)](https://user-images.githubusercontent.com/85300347/120674719-611c0f00-c462-11eb-8017-49e343e82174.png)

![Screenshot (531)](https://user-images.githubusercontent.com/85300347/120674726-637e6900-c462-11eb-98a2-7650b31f4705.png)

![Screenshot (495)](https://user-images.githubusercontent.com/85300347/120674822-7d1fb080-c462-11eb-915a-5aa794112f4c.png)

![Screenshot (496)](https://user-images.githubusercontent.com/85300347/120674835-801aa100-c462-11eb-85db-34169808257c.png)

![Screenshot (498)](https://user-images.githubusercontent.com/85300347/120674859-84df5500-c462-11eb-8bcb-7ffc5bbd86f0.png)

![Screenshot (499)](https://user-images.githubusercontent.com/85300347/120674875-89a40900-c462-11eb-882a-193ebaa24a2c.png)

![Screenshot (500)](https://user-images.githubusercontent.com/85300347/120674926-96c0f800-c462-11eb-888e-8f5df2135dae.png)

![Screenshot (501)](https://user-images.githubusercontent.com/85300347/120674970-a3455080-c462-11eb-8590-87929bb79f03.png)

![Screenshot (536)](https://user-images.githubusercontent.com/85300347/120674956-9de80600-c462-11eb-921a-fc7ffb43297b.png)

![Screenshot (502)](https://user-images.githubusercontent.com/85300347/120675046-b9531100-c462-11eb-81bd-5b6fbe602c54.png)

![Screenshot (504)](https://user-images.githubusercontent.com/85300347/120675067-bf48f200-c462-11eb-9048-e54acaf33084.png)

![Screenshot (505)](https://user-images.githubusercontent.com/85300347/120675084-c2dc7900-c462-11eb-9bda-4f54aa36cd04.png)

![Screenshot (506)](https://user-images.githubusercontent.com/85300347/120675116-c96af080-c462-11eb-907a-c5496fc80199.png)

![Screenshot (507)](https://user-images.githubusercontent.com/85300347/120675140-cff96800-c462-11eb-9dbf-3bb4ca6b8499.png)

![Screenshot (508)](https://user-images.githubusercontent.com/85300347/120675171-d7207600-c462-11eb-83ba-33baa28643b2.png)

![Screenshot (509)](https://user-images.githubusercontent.com/85300347/120675192-dbe52a00-c462-11eb-94b9-d3e2029a0221.png)

![Screenshot (510)](https://user-images.githubusercontent.com/85300347/120675212-e1427480-c462-11eb-8023-83a7b6b70be8.png)

## Here we even have someone with the role "Staff" acknowledging its unpopularity:
![Screenshot (511)](https://user-images.githubusercontent.com/85300347/120675230-e4d5fb80-c462-11eb-99ec-93136c247d71.png)

![Screenshot (512)](https://user-images.githubusercontent.com/85300347/120675558-2e264b00-c463-11eb-8128-e9344cb65ab5.png)

![Screenshot (513)](https://user-images.githubusercontent.com/85300347/120675580-32526880-c463-11eb-82e4-baa5bdc9147f.png)

![Screenshot (517)](https://user-images.githubusercontent.com/85300347/120675597-37171c80-c463-11eb-9d26-7b5c8b9c9e9f.png)

![Screenshot (518)](https://user-images.githubusercontent.com/85300347/120675612-3aaaa380-c463-11eb-80e8-c4dcf237daa8.png)

## Lmao:
![Screenshot (519)](https://user-images.githubusercontent.com/85300347/120675632-4007ee00-c463-11eb-99c7-938b06f4ae22.png)

![Screenshot (537)](https://user-images.githubusercontent.com/85300347/120675674-47c79280-c463-11eb-890e-f7c23a201c49.png)

![Screenshot (520)](https://user-images.githubusercontent.com/85300347/120675689-4b5b1980-c463-11eb-8c76-8c7eca9bc508.png)

![Screenshot (522)](https://user-images.githubusercontent.com/85300347/120675733-57df7200-c463-11eb-9d3d-4c6486064f68.png)

![Screenshot (523)](https://user-images.githubusercontent.com/85300347/120675751-5ca42600-c463-11eb-9d90-bbe919964074.png)

![Screenshot (521)](https://user-images.githubusercontent.com/85300347/120676912-8578eb00-c464-11eb-8c3a-7c4fd05a2dbd.png)

![Screenshot (532)](https://user-images.githubusercontent.com/85300347/120675804-66c62480-c463-11eb-9b91-3130028ed792.png)

![Screenshot (539)](https://user-images.githubusercontent.com/85300347/120675835-6ded3280-c463-11eb-83c0-94346083e001.png)

![Screenshot (533)](https://user-images.githubusercontent.com/85300347/120675886-78a7c780-c463-11eb-8802-6f9d8c628bf1.png)

![Screenshot (534)](https://user-images.githubusercontent.com/85300347/120675924-82312f80-c463-11eb-84fd-9f7823448045.png)

### Last but most least, me!
![Screenshot (535)](https://user-images.githubusercontent.com/85300347/120675938-85c4b680-c463-11eb-961c-2230e06471a9.png)

Anyone can see that even the by loosest and most generous definition of "listening to the community", such changes would be deemed a mistake and reverted. I have the utmost gratitude and respect for the developers behind this app, and I hope they have the same respect for its users.

## What/Requirements
Please revert the tablet changes

**Comment by CarlosEsco** [comment]
You are free to make your own fork, or app.

**Comment by arkon** [comment]
Your selective quoting conveniently left out the rest of that answer.

> Q: Why aren't you listening to users?!
>
> A: We are. There are many users. Some like it, some dislike it, and some aren't noisy enough to be heard. We also frankly do not have a responsibility to listen to every demand. Since this is a FOSS project (of which people do not pay for), you are always free to fork it and maintain whatever features as you see fit.

A few other things:
- The developers do not look at the subreddit. We only look at GitHub and Discord.
- AZ is the maintainer of a fork that's explicitly keeping the UI from 0.8.x, so interpret that however you want.
- More reasoning is already addressed in #5292. 
- This is literally the same sort of "constructive feedback" we got from users when we switched to bottom navigation back in 0.9.0 wanting the sidebar back, and now we see essentially the opposite.

Please at least try to live with it for a while before having a kneejerk reaction to any form of change.

Also please keep in mind that there are _many_ more users than those who are vocal.
