### ISSUE TITLE
[Feature Request] <Go back to the source tab in mass migration>

### ISSUE THREAD

**Issue by bolso96** [tachiyomiorg/tachiyomi#5297]
## Why/User Benefit/User Problem
When you go back after migrating in mass migration, it sends you back to select a new source rather than to the source tab you were

## What/Requirements
After migrating, it should allow you to go back to the source list, so you don't have to select the source again and scroll all the way down where you were to continue migrating

**Comment by GMak9** [comment]
Feature Request: Bulk Migration.: It would be a very useful feature, given that some sources are committed to blocking the App, tachiyomi. 
Desc: In the "migrate" tab while holding down on one source an option to migrate all comics to another source would appear. Those "comics" in which there have been errors remain in the original source.

**Comment by arkon** [comment]
There is no mass migration, so idk what this issue even means.
