### ISSUE TITLE
[Bug] bug with download animation

### ISSUE THREAD

**Issue by PtakuKing** [tachiyomiorg/tachiyomi#5300]
---

## Device information
* Tachiyomi version: satble 0.11.1
* Android version: 11
* Device: Private

## Steps to reproduce
1. Just started multiple downloads in a row.
2. Once one of them starts progressing
3. I add multiple chapters to the queue 
4. when i start deleting the multiple added chapters that are waiting in the queue. 
5. It causes one or multiple chapters that are not added to the queue to change to change their download icon.

P.S the chapters that randomly change icons don't actually get added to the queue.

### Expected behavior
Only the download icon for the chapters that are added to the queue should change.

### Actual behavior
Download icon for a random chapter changes to the icon used in the initial stages of a download starting.

## Other details
I tried this in multiple extensions it kept happening.

I did not add chapter 11 to the download queue.
![20210604_002726](https://user-images.githubusercontent.com/85317141/120712798-57cc8a00-c4d6-11eb-974e-c0bfec65505d.jpg)

Video of the Behavior shown below

https://user-images.githubusercontent.com/85317141/120712830-61ee8880-c4d6-11eb-9bed-820ad641a6c0.mp4

**Comment by PtakuKing** [comment]
It also happed a few times after split second when i added my first download to the queue

**Comment by zayin02** [comment]
Known issues #5277
