### ISSUE TITLE
[Feature Request] Do not crop on expanded image

### ISSUE THREAD

**Issue by jobobby04** [tachiyomiorg/tachiyomi#5301]
## Why/User Benefit/User Problem
With the new manga info menu, tapping on the cover allows you to view a higher resolution then the normal cover, but it doesn't allow you to view the full image without the cover ratio cropping, which can make it blurry on non-standard images.

For example: Warning, nsfw
https://user-images.githubusercontent.com/17078382/120721989-e91f0a80-c49c-11eb-99e9-dff6ca0ec2c3.gif
And what it should actually look like: Warning, nsfw
https://user-images.githubusercontent.com/17078382/120722706-3780d900-c49e-11eb-83ff-841ba9031136.gif

## What/Requirements
My suggestion is to expand the image in a way that removes the cropping on the expanded version, allowing you to view the non-standard cover without issue.

**Comment by arkon** [comment]
I think your second gif link is wrong.

**Comment by jobobby04** [comment]
Fixed :harold:
