### ISSUE TITLE
[Bug] unable to update mangas from lector manga error 404 no found, web view broken same error http 404 page no found

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi#5303]
but if you search any manga in a web browser in lector manga is fine, for example "Kage no Jitsuryokusha ni Naritakute"  this manga is totally fine in lector manga if you access from a web browser, but in yachiyomi when i try to update say 404 page no found same in web view mode

**Comment by arkon** [comment]
Wrong repo, please follow the issue instructions.

**Comment by Mtkmanjaro** [comment]
what do you mean with wrong repo

**Comment by h-hyuuga** [comment]
> what do you mean with wrong repo

The bug report instructions that you ignored say: `If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions`
