### ISSUE TITLE
[Bug] all mangas from lectormanga are unable to update error 404

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi#5304]
tachiyomi version: 0.11.1 (63)
cleared database after update
android version: A11

steps to reproduce:
try to update an manga from lector manga falied error HTTP 404

expected behavior:
update the new charters

all mangas from lectormanga are unable to update   but if you search any manga in a web browser in lector manga web page  is fine, for example "Kage no Jitsuryokusha ni Naritakute" this manga is totally fine in lector manga if you access from a web browser, but in tachiyomi when i try to update say 404 page no found same in web view mode,

**Comment by arkon** [comment]
Still the wrong repo. See comments in #5303
