### ISSUE TITLE
[Feature Request] Ability to swap which side has manga information and chapter list in tablet UI

### ISSUE THREAD

**Issue by profHawkeye** [tachiyomiorg/tachiyomi#5306]
## Why/User Benefit/User Problem
This feature is extremely useful for people who mainly use their left hand for touching the tablet, since it will be much less of a stretch to reach the area more likely to be consistently clicked while in use. I've found myself liking the majority of the tablet UI update since I've gotten used to it, but this is the one area that isn't working for me, because my left hand is the one I'd prefer to be opening chapters with.

## What/Requirements
An option that swaps the chapter list+start FAB with the manga information, similar to how there is an option to move the navigation buttons to the bottom instead of the top.

**Comment by arkon** [comment]
No plans to do so, as I can't think of any other app that does this.
