### ISSUE TITLE
[Bug] Reappearing persistent loading indicator in History Tab

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/tachiyomi#5307]
## Device information
* Tachiyomi version: 0.11.1 Stable
* Android version: 11
* Device: Emulated Pixel 3

## Steps to reproduce
1. Have an empty History
2. Read a chapter (or just a couple pages) of a manga from a source (I've reproduced issue with several manga from Mangadex and Mangakalot)
3. Go to the History tab / screen
4. Click on the history entry for the manga (**not the "read" arrow on the right side**) to open manga details
5. Press the back arrow to return to the History tab

### Expected behavior
The UI should look the same as it did before clicking on the history entry to view manga details

### Actual behavior
An indeterminate circular progress indicator appears below the item and does not go away until navigating away from and back to the history tab

**Comment by binxsahib** [comment]
`App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.T290XXU3BUE1
Device brand: samsung
Device manufacturer: samsung
Device model: SM-T290`

same issue facing.

**Comment by binxsahib** [comment]
```
App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T290XXU3CUF8
Device manufacturer: samsung
Device model: SM-T290
```

updated my device today. issue remains the same.

**Comment by arkon** [comment]
@midyHamdoun Go ahead.
