### ISSUE TITLE
[Bug] <Screen orientation adjustment does not take effect.>

### ISSUE THREAD

**Issue by Ink-lotus** [tachiyomiorg/tachiyomi#5310]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 9
* Device: MI MIX2

## Steps to reproduce
1. First step: Open any cartoon reading interface to adjust the screen direction. or: Set the screen direction of comic book reading mode in settings.
2. Second step: Adjust the screen orientation in the reading interface.

### Expected behavior
Change the screen direction to the horizontal screen or set the auto rotation to rotate with the phone.
### Actual behavior
The orientation of the screen does not change.
## Other details
The screen direction that was adjusted in settings failed to take effect.

**Comment by arkon** [comment]
Can't seem to reproduce this, although it did make me notice that the icon isn't set correctly when first opening the reader.

Do you have anything that might be interfering with it, like an external orientation setting app? Does your regular auto rotation setting seem to affect it too?

**Comment by Ink-lotus** [comment]
Sorry, I found that this problem can only reappear on my mobile phone. This problem was solved after I reset my phone. The options in the settings are different from the icons in the reading interface, which makes me mistakenly think that there is something wrong with the APP.
