### ISSUE TITLE
[Feature Request] Splitting "secure screen" setting into 2 settings

### ISSUE THREAD

**Issue by somechazzy** [tachiyomiorg/tachiyomi#5313]
## Why/User Benefit/User Problem
These 2 settings aren't particularly related and users may want one without the other.
Personally I like taking screenshots often rather than saving an entire manga page due to easy access to cropping. However, if I forget to close the app and I'm showing a friend something on my screen, I don't want them to see the app's preview while switching apps.

## What/Requirements
Nothing required, just a small change.
I suspect that them coming together is a restriction on Android's side, altho after checking on Google I didn't get an answer whether this is true or not.

**Comment by arkon** [comment]
> I suspect that them coming together is a restriction on Android's side

It is, so this can't be done.
