### ISSUE TITLE
[Bug] app crashes whenever i i click on the author or series title in a mangas homepage

### ISSUE THREAD

**Issue by jordamuk** [tachiyomiorg/tachiyomi#5314]
Logs

--------- beginning of system
--------- beginning of main
06-04 22:18:51.532 26973 26973 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
06-04 22:18:52.395 26973 27018 E SQLiteLog: (284) automatic index on C(manga_id)
06-04 22:18:52.395 26973 27018 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 9 (SDK 28)
Android build ID: 00WW_5_15K
Device brand: Nokia
Device manufacturer: HMD Global
Device name: NB1
Device model: TA-1012
Device product name: TA-1012_00WW

**Comment by loocool2** [comment]
you didn't attach any logs

**Comment by jordamuk** [comment]
> you didn't attach any logs

I went to the dump section of the app and copied the contents to the clipboard and pasted them as text. I thought those were the logs. Im new to this

**Comment by jordamuk** [comment]
> you didn't attach any logs

I've attached the logs now

**Comment by arkon** [comment]
There's no useful info in those logs. Try uninstalling some extensions to see if that helps.

If you get more info, please open another issue with it.
