### ISSUE TITLE
[Feature Request] (Toggle-able?) Swap side of new Side Navigation

### ISSUE THREAD

**Issue by alexjade96** [tachiyomiorg/tachiyomi#5315]
As one of the many users who uses a smaller tablet/ Tachiyomi in portrait mode/right-handed user, having the new menu navigation be at the top-left/left side in general creates poor UX experience for those like me.  

Looking at the many other users here/on the discord requesting the navigation be brought back to bottom-navigation or toggle-able, I would think it would be easy to create a toggle to satisfy these requests as this is already being done to differentiate phone users from tablet users.  I believe the fact there is a meta thread dedicated _solely_ to this particular issue should merit better than the developers' "tough luck, deal with it" response; even in meta #5292 there are contradictions, in the first few dialogs alone: 

- Lack of a market to really target (Android tablets are not common)
- Tachiyomi is an Android app, and we strive to match the overall ecosystem.
- Sure, and many people like you hated it when it first came out, just like any other major UI change. _(As far as this one goes, I don't believe there's ever been a meta thread for those other major UI changes unlike this one, so there should be more consideration in place)_

So you can see why people are confused about decision and explanation when these kinds of things contradict in official statements.

However I would like to request an alternative that hopefully still satisfies developer decision progression and might appease some users, which is to shift the navigation rail from the left side to the right side, keeping the ability to decide top-right vs bottom-right (or at least making this toggle-able).

**Comment by banananos** [comment]
Seconding this. I'm all for UI feature changes, but fixing this to one side makes this very difficult for people who have left hand mobility issues. Personally I'm rolling back to the update before tablet mode implementation until a new UI is released. It's honestly so awful I made this GitHub account just to ensure that the devs know more than one person wants this. I could work with top, bottom, or even right nav, but left makes the app unusable for me.

**Comment by icewind1991** [comment]
Note that the threshold of when tablet UI kicks in seems to be already increased in master compared to the current release: https://github.com/tachiyomiorg/tachiyomi/commit/b03ebc1fa4d2fd4321ff736ddd9eda239fa2fdde

This should mean that smaller tablets wont get the new UI

**Comment by arkon** [comment]
We generally don't see apps offering this sort of option (e.g. having bottom nav at the top or left navigation drawers on the right).

Probably not going to happen unless we there's other apps doing that in the future.
