### ISSUE TITLE
[Bug] Failure to restore back up

### ISSUE THREAD

**Issue by Chief15** [tachiyomiorg/tachiyomi#5317]
I got a new phone (galaxy 21+) and when i transferred my  app and my files over including my backup file (tachiyomi-v0.9.2.apk) and when i try to reload it i was told to change the file type to .proto.gz or .json and when i do, it fails to load both file types.

---

## Device information
* Tachiyomi version: 0.11.1
* Android version: 11
* Device: galaxy s21+

## Steps to reproduce
1. Go to backup files
2. Finds backup file as .apk file type
3. i change file type to .json
4. doesn't load
5. change file to .proto.gz 
6. fails

### Expected behavior
restores back up
### Actual behavior
fails to restore back up

## Other details
got a new phone at time of posting and have changed file type to suggested files types.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by loocool2** [comment]
.apks aren't backup files

**Comment by Chief15** [comment]
So what would a back up file read as?

**Comment by arkon** [comment]
See https://tachiyomi.org/help/guides/backups/
