### ISSUE TITLE
Extensions doesn't updated

### ISSUE THREAD

**Issue by imapisofsheet** [tachiyomiorg/tachiyomi#5321]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 8.1.0
* Device: Asus Zenfone 4 Selfie Lite ASUS_X00LDB

## Steps to reproduce
1. Extensions 
2. Hit Update

### Expected behavior
It should update immediately like 5 seconds after i hit the update.

### Actual behavior
I hit the update in the extensions it stays like that and still pending for 5 minutes and doesn't update.

## Other details
![195895126_4086706691421516_3294616993172729457_n](https://user-images.githubusercontent.com/85398606/120892766-6cc62c00-c642-11eb-9b52-c2ef23d74d09.jpg)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by CrepeTF** [comment]
Just install the updated apk from the [website](https://tachiyomi.org/extensions/) and install.

**Comment by imapisofsheet** [comment]
i have the updated apk tho? isn't 0.11.1 is the latest version?
