### ISSUE TITLE
[Feature Request] Generate APKs per CPU architecture for preview builds

### ISSUE THREAD

**Issue by TacoTheDank** [tachiyomiorg/tachiyomi#5324]
## Why/User Benefit/User Problem
- This should be added because if the official releases will have it, might as well do it for the preview builds too.

## What/Requirements
- Preview builds will be auto-generated with individual architectures (as well as a universal one because why not).

**Comment by arkon** [comment]
Not sure why you made this issue...

Duplicate of #5262
