### ISSUE TITLE
[Bug] Cannot Authorise Myanimelist. ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by arun07as** [tachiyomiorg/tachiyomi#5327]
## Device information
* App version: 0.11.1-3497 (standard, fdf178d4, 63, 2021-06-05T21:18Z)
* Android version: 9 (SDK 28)
* Android build ID: LLD-AL10 9.1.0.173(C675E9R1P4)
* Device brand: HONOR
* Device manufacturer: HUAWEI
* Device name: HWLLD-H
* Device model: LLD-AL10
* Device product name: LLD-AL10

## Steps to reproduce
1. Click Settings->Tracking->MyAnimelist. Webview will open if not already logged in.
2. Fill Account credentials and click login
3. When asked to allow Access to tachiyomi, click Allow

### Expected behavior
Webview should close and myanimelist should be authorised and tracking should be enabled

### Actual behavior
Webview fails to close because it can't recognise the `tachiyomi://myanimelist-auth` url schema. We get an error page saying unknown url scheme. Tracking not enabled in tachiyomi.
![Screenshot_20210606_120429_com huawei himovie overseas](https://user-images.githubusercontent.com/17740186/120920440-684e5180-c6dc-11eb-8299-56e7a37c7065.jpg)

## Other details
Have chrome installed and set as default browser. 
All apps are updated ( have auto update on ).

https://github.com/tachiyomiorg/tachiyomi/issues/1768
This is related, but the solution there was installing firefox, which I don't think should be necessary

**Comment by arkon** [comment]
What browser is opening when you try to login? It should be using your default browser (Chrome), not WebView.

**Comment by arun07as** [comment]
> What browser is opening when you try to login? It should be using your default browser (Chrome), not WebView.

Hi @arkon 
You may be right, I assumed it was webview, but it might be chrome itself, I'm not sure though, there's no controls and I can't tell the difference. I don't have any other browsers installed, just chrome. I've attached a video


https://user-images.githubusercontent.com/17740186/120929606-4b7b4380-c707-11eb-84ea-2d2ec01ac763.mp4

**Comment by arkon** [comment]
That doesn't look like Chrome, and that error page is indeed something like what you'd see in WebView. It's possible that your system is doing something weird (Huawei and other Chinese OEMs tend to do that), so you could try fiddling around with different browsers/resetting what's the default.

**Comment by arun07as** [comment]
I downloaded firefox, set it as default, restarted phone, and tried but still the same, no chane at all. 

Uninstalled chrome updates ( doesn't allow uninstall because it's system App ). Force stop and Disabled Chrome. Try again, still same result.


Guess it's my phone doing something weird and not using default browser ( which is strange because it doesn't show any other browser, probably doing something behind the scenes). 

But what's strange is that I've never had this issue before using tachiyomi, issue came after I updated today....

Guess I'll just try and wait it out and try again after few days

**Comment by arun07as** [comment]
Hi @arkon 

Nothing I've tried has worked yet. So I was thinking that since I already got an auth code for myanimelist, would it be possible to manually paste the auth code somewhere in the app so the app can use it for getting access token since the redirect isn't working? Could be a temporary fix.

**Comment by arun07as** [comment]
Nevermind, Finally found the culprit, it was an app called Honor Store. I noticed that when I did a simple Google search in the Google app and opened some link, it was being opened in Honor Store instead of chrome and the ui looked exactly as what I got in tachiyomi, so I uninstalled it and...........

Viola, everything works properly now. Was able to Authorize Myanimelist
