### ISSUE TITLE
Backup files contain invalid protobuf field numbers

### ISSUE THREAD

**Issue by f00f-32** [tachiyomiorg/tachiyomi#5334]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 11
* Device: Redmi Note 4

## Steps to reproduce
1. Create a backup
2. Try parsing it using `protoc` or other protobuf decoder/library

### Expected behavior
Backup file with data that can be properly read by other protobuf parsers.

### Actual behavior
Decoder errors or corrupt data, depending on the parser implementation.

## Other details
I discovered this while trying to write a script for extracting my read history from a backup file. Both `BackupHistory` and `BackupSource` define a field with `@ProtoNumber(0)`, but [the documentation](https://developers.google.com/protocol-buffers/docs/proto#simple) says the minimum valid field number is 1, in fact, `protoc` will throw a fatal error if you try to compile a message definition that sets the number of a field to 0.

https://github.com/tachiyomiorg/tachiyomi/blob/ec5e6958ef4f12f6cdf6694a37637770ca1e67da/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupHistory.kt#L8
https://github.com/tachiyomiorg/tachiyomi/blob/ec5e6958ef4f12f6cdf6694a37637770ca1e67da/app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupSource.kt#L9

Trying to parse the backup files may generate errors or return corrupt data, depending on the library used. For example, `protoc` 3.16 interprets the affected fields as a sequence of raw bytes:

```
100: "\002\004Guya\010\226\377\245\206\360\334\330\256@"
```

Although `kotlinx.serialization` doesn't seem to care and the app can load the data just fine, I guess it _may_ cause trouble if something changes in a future version. People interested in reading backup files using external tools can either use a library that allows zeros as field numbers or try to patch the file before attempting to load it.

**Comment by 2ion** [comment]
Most notably, this affects a lot of the tooling for working with protobuf vendored by Google itself.

**Comment by Soitora** [comment]
/edit-title "Backup files contain invalid protobuf field numbers"
