### ISSUE TITLE
[Feature Request] R/manga integration

### ISSUE THREAD

**Issue by enaaab460** [tachiyomiorg/tachiyomi#5336]
## Why/User Benefit/User Problem
Checking reddit discussion threads of chapters is fun, and helps discover new manga, so I think that an easy way to access them would improve the user experience to a lot of people.

## What/Requirements
In the transition page between chapters, the bottom of the reader would show a reddit button which searches reddit.com/r/manga for the chapter and open the most relevant match.

## Workaround
I made a tasker project that does this, however it relies on AutoInput to read the screen to find the manga name and chapter, and it is quite clumsy.
I can share it the project if you think it can help your workflow.  [Gdrive link](https://drive.google.com/file/d/1dzpi2GRWZibObFYi6Yhxgmvgrm5Sf06W/view?usp=sharing)
Here is a demo of how it works right now (no reddit button, swiping the notification slider triggers autoinput (to check the name and chapter) and shows the discussion thread as a button with its thumbnail):[Imgur demo 1](https://imgur.com/a/3E6qjUa) [Imgur demo 2](https://imgur.com/a/sq4hW1W)

If it is too much hassle to include in tachiyomi, could it be included as an extension for the button to send the name and chapter number and unique identifier of library item to tasker (as an intent maybe) and leave it handle the rest? Of course then the tasker project would remain available for anyone and I would continue maintaining and bug fixing it.

I am not a programmer so unfortunately tasker "lego" is all i can handle (and some python) 
If there is interest but the script looks gibberish i can explain it in more detail
Ps: I just figured out that the script can be exported as a standalone apk, but first I will have to figure out how exactly. Edit2: it won't work as long as it needs autoinput

**Comment by nikhilCad** [comment]
Reddit has an RSS feed at https://www.reddit.com/r/manga.rss so posts can be taken from there, though personally I think this feature is overkill.

**Comment by arkon** [comment]
Agreed, I'm hesitant to add something like this (even if optional) since Reddit isn't necessarily the go-to place for many people and I don't want this to be the start of people trying to get a ton of different forums/comment pages integrated somehow.

There could be maybe some function to copy some text to the clipboard on the transition pages. If you're interested in that, please open another issue.
