### ISSUE TITLE
[Feature Request] <Grey filter on manga when no source attached.>

### ISSUE THREAD

**Issue by Lesorin** [tachiyomiorg/tachiyomi#5337]
---

## Why/User Benefit/User Problem
So sometimes a source changes or is re-uploaded but there is no real way of seeing unless you to to the migrate option or error. My idea would simply put either a gray filter over the manga cover in library or even simpler change the Manga title text to red and revert back once it has a source again. This would provide fast visual queues to the user the the current source is not finding the manga. 

A second feature request I'd like to suggest is that on the migrate screen there be an option to show the number of released chapters a source has to speed up finding the a more up to date source.

## What/Requirements
I don't have much programing knowledge but the first suggestion would use the existing error log to determine which mangas to either give a Grey filter or red filter. A second check would be if your library says 11 chapters current released and the source says 0. I'm sure there's a better way to go about this but that's just my rough idea.

As per the secondary suggestion,
It could work the same way as remaining chapters read but on separately say in a green highlight as total chapters the source has.

**Comment by arkon** [comment]
Seems a bit unnecessary when the error log already tells you which entries have issues.
