### ISSUE TITLE
[Feature Request] <Option To Choose Source While Migrating Manga>

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#5338]
## Why/User Benefit/User Problem
My Pinned is filled with Mangadex, Batoto etc. Now when I migrate manga to their Scanlator's Dedicated site like Reaper, Manga+ I need to add them to pinned source every time and remove it after migrating. Implementing this will remove this unnecessary step.

## What/Requirements
This is already Implemented in TachiJ2K so... Hippity Hoppity The Code Is Now Tachi's Property

**Comment by arkon** [comment]
Duplicate of #6654
