### ISSUE TITLE
[Feature Request] Dim history resume button if no next chapter

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi#5342]
## Why/User Benefit/User Problem
Quality of life feature, you know at a quick glance on History which items you've read that has readable chapters.

## What/Requirements
If history item has a next chapter = Same tint as current
If history item has no next chapter = Tint the button like disabled (dimmed)

**Comment by arkon** [comment]
This would require checking all of the chapters lists, which probably isn't desirable.

**Comment by Soitora** [comment]
Makes sense, right now it just check it on press
