### ISSUE TITLE
[Bug] Black stripe between pages in landscape mode in tablet

### ISSUE THREAD

**Issue by Byakko92** [tachiyomiorg/tachiyomi#5349]
## Device information
* Tachiyomi version: Stable v0.11.1
* Android version: 11
* Device: SM-T500 (Galaxy Tab A7 2020)

## Steps to reproduce
1. Open a comic and rotate tablet to activate landscape mode
2. Activate webtoon reader mode

### Expected behavior
There is no space between the pages

### Actual behavior
A black stripe between pages in landscape mode in my tablet, not in my smartphone with the same configuration 

Bug in Tablet
https://user-images.githubusercontent.com/61310988/121194282-e5a9cb80-c86e-11eb-93c9-a5a74029c0ea.mp4

The bug does not occur on my smartphone (Android 6.0, Alcatel A5 LED 5085Y, Tachiyomi Stable v0.11.1)
https://user-images.githubusercontent.com/61310988/121194297-e93d5280-c86e-11eb-89b0-f717432eb7fd.mp4

**Comment by CrepeTF** [comment]
#2736
