### ISSUE TITLE
[Bug] Restore from backup not working

### ISSUE THREAD

**Issue by Araxeus** [tachiyomiorg/tachiyomi#5357]
## Device information
* Tachiyomi version: v0.11.1
* Android version: 11
* Device: Xiaomi Poco F3
* OS: MIUI 12.5.1

## Steps to reproduce
1. Made backup on tablet (tab A7)
2. Transfer to phone
3. Restore backup from file

### Expected behavior
Something happen (even some error message perhaps)

### Actual behavior
After selecting the file, the file chooser close and nothing happens

## Other details
It worked when backup was made on phone and restored on tablet, but not the other way around

**Comment by arkon** [comment]
I believe some other Xiaomi users have had this problem too and solved it by installing a better file manager (e.g. Solid Explorer) than the preinstalled one.

**Comment by Araxeus** [comment]
> I believe some other Xiaomi users have had this problem too and solved it by installing a better file manager (e.g. Solid Explorer) than the preinstalled one.

That didn't work


----


> Some users were able to restore the backup only after Enabling MIUI Optimisations
> You can try that out as well
> 
> (normally, it is recommended to disable MIUI optimizations because of how brutally it kills apps and background services. Doing this however has led to backup restores not working for some reason ¯_(ツ)_/¯ )

that works - but MIUI optimizations cause other problems like you said :(

anyways it could be nice if this could be made to work without it turned on

and meanwhile there should be a warning for miui users about this, or some kind of error when it fails
because its really hard to know whats going on when nothing happens.

Thanks for the help 🙂
