### ISSUE TITLE
[Bug] <my extension is deleting itself

### ISSUE THREAD

**Issue by IiiiiIi765** [tachiyomiorg/tachiyomi#5360]
---

## Device information
* Tachiyomi version: v0.11.1
* Android version: 10
* Device: oppo r17

## Steps to reproduce
1. First step
2. Second step

### Expected behaviour
Was extension is installed it should stay and not delete it self once exited from app
This should happen.

### Actual behaviour
Once exited the extension is gone
This happened instead.

## Other details
It says that I have to allow some permissions but I have allowed them  I have video proof but I do not know how to send it
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

>

**Comment by arkon** [comment]
I doubt the actual extension apps are getting uninstalled, but rather Oppo's software is likely revoking the permission for Tachiyomi to read other apps.
