### ISSUE TITLE
[Feature Request] deleting chapters tab

### ISSUE THREAD

**Issue by gamintoad** [tachiyomiorg/tachiyomi#5361]
## Why/User Benefit/User Problem

Making a deleted tab will help the user track which chapter is being deleted and how long it takes for it to be deleted 

## What/Requirements

Basically the opposite of the "download queue" and will be under the download queue tab  in settings I would assume.  Tab that says "deleted chapters" when  deleting a chapter or more, you can go on the tab and see what is being deleted and how long it's going to take.

**Comment by CarlosEsco** [comment]
This seems pretty specific, only slow devices on A11 don't delete almost immediately.

**Comment by gamintoad** [comment]
> This seems pretty specific, only slow devices on A11 don't delete almost immediately.

I'm not on A11 and it still takes a while to delete (my internet is good too) it would just be nice to track it, and usually when I delete chapters it usually the whole manga, I deleted a 100 ch manga the other day I couldn't keep track of which chapter was deleted or not. (Because it would still have the check mark when I pressed delete)

**Comment by CarlosEsco** [comment]
No it wouldnt.  You are comparing something that is downloading over the network, to  a android system action.

**Comment by gamintoad** [comment]
> Deleting files should generally be instantaneous. Are you seeing the badges not being updated even when the files are actually gone?

Yeah ,so I'm pressing delete but the check mark is still there, it would only disappear after a while
