### ISSUE TITLE
[Feature Request] Append Shared/Saved pages with SPOILER_

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#5362]
## Why/User Benefit/User Problem
When sharing images to discord, it takes a lot of extra steps to name the image for discord spoilers, and discord doesn't have mobile marking spoilers on upload like desktop.
## What/Requirements
There would be a preference for this, and it would append SPOILER_ to the beginning of every shared or saved image

**Comment by kyoyacchi** [comment]
I agree with you.

**Comment by loocool2** [comment]
Discord added it (kinda)
