### ISSUE TITLE
Splicing double-page spread picture

### ISSUE THREAD

**Issue by 1024kilobytes** [tachiyomiorg/tachiyomi#5370]
Just like dual page split, some comic strips spread across two page, I think it will be easy to read if they can be spliced ​​into one page. Hope I conveyed it to you.

I'm not sure I understand.

_Originally posted by @arkon in https://github.com/tachiyomiorg/tachiyomi/issues/5199#issuecomment-848723412_

**Comment by loocool2** [comment]
Dual Page Reader already been marked as a duplicate of #149 in your linked issue
