### ISSUE TITLE
[Feature Request] Parallel download chapter

### ISSUE THREAD

**Issue by Rosabis** [tachiyomiorg/tachiyomi#5373]
## Why/User Benefit/User Problem
(explain why this feature should be added)
1.I want this feature. 
2.I can download multiple chapters in parallel at one time. 
3.This is very slow If you need to download each chapter of each comic with more than 100 pictures, if you have this function, you can greatly save the download time.
4.I know that there is a similar issue that has been closed for a while, but the problem is that if you use parallel downloads on some sites and will not cause IP bans, you can add This function is advanced to the advanced level, it is closed by default and a prompt is added.
## What/Requirements
(explain how this feature would behave)
Download at least 10 chapters at a time.

**Comment by CrepeTF** [comment]
Mass downloads put a lot of pressure on website's servers when Tachiyomi has over a million active users.

It's basically a non-intentional DDoS tool.

Parallel downloading for the same sources will not come.

**Comment by CrepeTF** [comment]
Don't make anymore issues regarding this.
