### ISSUE TITLE
App Crashes cause of bug in save option

### ISSUE THREAD

**Issue by crybabyRK** [tachiyomiorg/tachiyomi#5375]
## Device information
* Tachiyomi version: App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 9 (SDK 28)
Device brand: samsung
Device manufacturer: samsung
Device name: j4primelte
Device model: SM-J415F

## Steps to reproduce
1.Saving any long page of any manhwa which is downloaded.
2.Bookmarking of chapters.

### Expected behavior
1.It used to be saved without any crashes no matter how long the pages were.
2.bookmarks the chapter as soon as you touch bookmark in reader view.

### Actual behavior
1.When saving long pages the app crashes and it gets to manhwa info view from chapter reader view and page gets saved , but crashes everytime for long page saves.
2.Bookmarking takes its time most of the time and sometime the reader view closes itself.

## Other details
Additional details and attachments.
content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt
If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Can you upload the actual crash logs file?

**Comment by crybabyRK** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6633057/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
It also seems like you're reporting 2 bugs. Please create 1 issue per bug for proper tracking in the future.

For 1: is it consistently reproducible with specific pages? If so, can you share what source/manga/chapter/page?

For 2: is this also consistently happening?

---

For the crash logs, I assume it's for 1 and not for 2?

**Comment by crybabyRK** [comment]
1. It happens as long as the page of the chapter is long(manhwa long pages) regardless of what extension I use, what chapter, or what page...I just now tried saving in mangalife,MangaSee,isekaiscans.com everytime crash happened.I can normally save(no issues or no crashes) manga pages.It crashed again with a manhwa which I downloaded the chapters before the update(manyToon extension).
2. As for Bookmarking it rarely happens, so I don't know it's in the crash log.
(Sorry, for reporting two bugs)

**Comment by Phoenic1** [comment]
Having the same problem with crash on page save

**Comment by crybabyRK** [comment]
Tachiyomi new version I installed today.
version stable 0.12.1

The image save issue still happening.

[tachiyomi_crash_logs (1).txt](https://github.com/tachiyomiorg/tachiyomi/files/6948846/tachiyomi_crash_logs.1.txt)

**Comment by arkon** [comment]
These all seem to native Android-level errors when trying to create bitmaps on low-end Samsung devices.
