### ISSUE TITLE
[Bug] Tracker list popup not "popping" all the way up

### ISSUE THREAD

**Issue by kalebC** [tachiyomiorg/tachiyomi#5376]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 10
* Device: Redmi Note 8 Pro

## Steps to reproduce
1. Click in X manga
2. Click the "Trackers" icon

### Expected behavior
The tracking list popup shows up

### Actual behavior
The popup does, well, pop up, but the window doesn't completely extend, you can still drag what's left manually.

Kind of a minor thing, so I figure it's easy to fix (don't quote me on that, I have no idea). I've attached a recording of what it looks like, if the explanation wasn't clear enough:

https://user-images.githubusercontent.com/12353487/121601302-23982280-ca1c-11eb-93a5-21d53ff9180d.mp4

### Other details
This only happens if you have all the 3 trackers filled, as far as I know. When the list is empty, the popup behaves as expected.

**Comment by arkon** [comment]
This is amusingly the opposite of #5200. It's intentionally 50% on initial open, which seems a bit awkward given the total height.

**Comment by arkon** [comment]
We could maybe try to make the tracker sheet fully expandable though.

**Comment by kalebC** [comment]
> We could maybe try to make the tracker sheet fully expandable though.

As to cover the entire screen? There'd be a lot of empty space.

**Comment by vengiare** [comment]
I'd say it's really just an unfortunate occurrence of the sheet being a little bit over 50%, which does also happen in certain sources like below. A lot of things can affect this like screen ratio, using gestures/using nav buttons, and device smallest width.

Don't know a good solution for this.

![Screenshot_2021-06-11-07-14-13-633_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/63973749/121608468-a6ed5e80-ca84-11eb-8bfb-900818a5a260.jpg)
![Screenshot_2021-06-11-07-14-17-505_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/63973749/121608474-a94fb880-ca84-11eb-8a78-738e6b3ceb1d.jpg)

**Comment by arkon** [comment]
No plans to fix as it's dependant on content and screen height.
