### ISSUE TITLE
[Bug] MangaDex Chapters out of order (source order issues)

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi#5378]
## Device information
- Tachiyomi version: SY r383
- Android version: 10
- MangaDex extension version: 1.2.118
- (I was [told](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7599) that the issue is with the main app and not the extension and to open a ticket here) 

## Steps to reproduce
1. Open a MangaDex title from your library (doesn't happen for every MangaDex title)
2. Chapters are out of order (See example below. Also occurs often for titles that have a mixture of chapters with and without volume numbers included)
3. Syncing the title does not fix it. Clearing database, cache, etc does not help

### Expected behavior
Chapters should be in the correct order

### Actual behavior
Chapters in your library from before API relaunched (titles have been migrated from the old to the new IDs - I did not use the migrator app, but just did the migration by hand) have their chapters all out of order. 
- Deleting the title from your library, clearing database cache etc, and then re-adding the title fixes the issue - but that is quite burdensome depending on the size of your library.

## Other details
Example image of out of order chapters: 
![2021-6-10_19-15-31](https://user-images.githubusercontent.com/25085973/121613149-7fb17580-ca21-11eb-81f9-94620038b114.JPEG)

**Comment by CarlosEsco** [comment]
To clarify

The main app does not change the source order for existing chapters if the network manga returns the same chapters back.  

So even though a source might return a new source order, the app uses the existing source order saved in db.

**Comment by jadoff630** [comment]
@CarlosEsco That makes sense. Would a fix be something similar to the "Refresh Library Covers" in settings, but refresh sync order? (Not sure if that would even be doable, but thought I'd ask).

**Comment by CarlosEsco** [comment]
Currently the db doesn't get updated if the chapters that come back don't change. This should be as simple as updating the existing db with the new source order

**Comment by arkon** [comment]
App bug addressed by 07e5525c7433914f8e4b7dad03eb3081e622df48

Actual ordering issue addressed by MD just recently.
