### ISSUE TITLE
[Bug] Invalid download location

### ISSUE THREAD

**Issue by Infiziert90** [tachiyomiorg/tachiyomi#5381]
## Device information
* Tachiyomi version: App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 10 (SDK 29)
Device brand: HUAWEI
Device product name: VOG-L29EEA

## Steps to reproduce
1. Have "A Returner's Magic Should Be Special" from the Source MangaSee in your Library 
2. Try to download it

### Expected behavior
Gets downloaded. 

### Actual behavior
Invalid download location, like the issue #4126 already had 

## Other details
Save Location:
/storage/emulated/0/Tachiyomi/.nomedia

This phone has no SD Card! 
Free space is 20 GB
All other downloads in tachiyomi work perfectly fine

Crash Report:
https://pastebin.pl/view/raw/12761d54

**Comment by arkon** [comment]
Do you have duplicate folders for MangaSee? You may need to fix the folder naming.

**Comment by Infiziert90** [comment]
> Do you have duplicate folders for MangaSee? You may need to fix the folder naming.

As I just checked that.... There are 32 Copies of MangaSee

**Comment by Infiziert90** [comment]
My fail

**Comment by G0DTATSU** [comment]
you can try changing the download location to your sd card but create a different folder, i tried doing it and it worked for me

**Comment by Infiziert90** [comment]
Why is this closed and not getting fixed or atleast giving out some error message explaining what todo?

**Comment by arkon** [comment]
There's too many underlying reasons why something might fail. In your case, your filesystem for some reason isn't allowing case insensitive folder name checks, which was already done as a mitigation for this particular issue.
