### ISSUE TITLE
[Feature Request] Merge multiple updates 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5384]
## Why/User Benefit/User Problem
When going through updates I find often sources update multiple chapters from the same manga and it takes unnecessary space on the screen especially if it is a manga the reader has in the library but not reading and wants to have a quick look at new chapter, by merging the multiple chapters it will fixe simple problems like this which usually not even given a thought.

## What/Requirements
If on the same day multiple chapters from the same manga is released it will state the first chapter's number and show a sign +<Number of chapters>. This can also be built on with an expand button( 🔽) which will then list the chapters if the user is interested.

**Comment by CrepeTF** [comment]
#2774
