### ISSUE TITLE
[Feature Request] Multi line for chapter in tablet

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi#5393]
## Why/User Benefit/User Problem
some source like mangadex, have long title. in tablet, the chapter title often cut out

## What/Requirements
make each chapter in list vertically wider to accommodate multiple lines for title text

**Comment by kiriya-aoi** [comment]
See also: https://github.com/tachiyomiorg/tachiyomi/issues/5272
