### ISSUE TITLE
Nothing's happening when backing up, not even an error message

### ISSUE THREAD

**Issue by Ichisinn** [tachiyomiorg/tachiyomi#5394]
I think there's something wrong with the Tachi app on Poco phones, I was supposed to transfer my backup to my poco from my old phone but nothing's happening
I have all the extensions needed, tried all versions, even old and legacy and still nothing's responding to my backup
Would really appreciate the help cuz I have over 700 lib

Here's the backup link https://drive.google.com/file/d/1-rEKMej3n88o0J9N-MnEqzMvLBpb56tH/view

I'm using a Poco X3 pro if that helps

**Comment by arkon** [comment]
Try turning on MIUI optimizations when restoring. Not sure what's up with Xiaomi's software.
