### ISSUE TITLE
Can't change local manga cover

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi#5395]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 11 (MIUI Global 12.1.5 Stable)
* Device: Xiaomi Mi 10T Pro

## Steps to reproduce
1. Click on a Manga to see the chapters
2. Click on the top right dots and click edit cover
3. Choose the cover, select
4. It goes back to the manga without the cover changed

### Expected behavior
It should change the cover.

### Actual behavior
It doesn't change the cover

## Other details
If I open a chapter, hold down and click set as cover, it works after a restart of the application.

**Comment by zayin02** [comment]
What type of image where you using to set as cover?

**Comment by AlexMiniReal** [comment]
Both JPG and PNG. Neither of them work.

**Comment by AlexMiniReal** [comment]
_If I open a chapter, hold down and click set as cover, it works after a restart of the application._
I tried this only in local manga.

**Comment by zayin02** [comment]
Oh then there is no bug because local manga only reads data, so it only recognizes the new cover art when app is reopened. Might as well close this issue

**Comment by AlexMiniReal** [comment]
How can I change the covers in non-local manga? It still doesn't work..

**Comment by curche** [comment]
This has to be fixed in the app.
The issue is related to Coil and was fixed in j2k in a recent release. Relevant commit: https://github.com/Jays2Kings/tachiyomiJ2K/commit/a503d95bec45b6eacce5f0c9b7dbe46f8239e821

**Comment by AlexMiniReal** [comment]
Ok, I hope you'll merge the fixed code soon. Thanks for your work!

**Comment by AlexMiniReal** [comment]
Still doesn't work... :(

**Comment by AlexMiniReal** [comment]
After the update nothing as changed as well

**Comment by AlexMiniReal** [comment]
Fixed. Just enable MIUI Optimization in Developer Settings and it'll work.
