### ISSUE TITLE
Two-page segmentation problem of comics

### ISSUE THREAD

**Issue by PZH2000s** [tachiyomiorg/tachiyomi#5398]
## Device information
* Tachiyomi version: TachiyomiJ2K 1.0.17
* Android version: Android10
* Device: REDMI K20 PRO MIUI 12.0.5

## Steps to reproduce
1. Page Layout
2. Single page

## Issue/Request
Two-page comics cannot be divided into single pages

**Comment by CrepeTF** [comment]
Need more info.

Extension, series, chapters etc.

**Comment by PZH2000s** [comment]
> 需要更多信息。
> 
> 扩展、系列、章节等。
Any two pages of comics are inseparable

**Comment by arkon** [comment]
Wrong repo.

https://github.com/Jays2Kings/tachiyomiJ2K

**Comment by PZH2000s** [comment]
Sorry what is Wrong repo.

**Comment by arkon** [comment]
This isn't the TachiyomiJ2K project.

**Comment by PZH2000s** [comment]
This is it tachiyomij2k

---Original---
From: ***@***.***&gt;
Date: Tue, Jun 15, 2021 20:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tachiyomiorg/tachiyomi] Two-page segmentation problem of comics (#5398)




 
This isn't the TachiyomiJ2K project.

**Comment by arkon** [comment]
What?
