### ISSUE TITLE
[Feature Request] Add green apple AMOLED version theme

### ISSUE THREAD

**Issue by ash10r** [tachiyomiorg/tachiyomi#5399]
## Why/User Benefit/User Problem
Looks cool. Would be nice to have.

## What/Requirements
Could you use the accent colour used in “green apple” in an AMOLED black theme.

OR
Have a separate selector for mode(light, dark, AMOLED black) and a separate one for accent colour (this would avoid similar future requests)

**Comment by Soitora** [comment]
> **AMOLED Black** is more battery efficient and popular compared to **Dark Gray**.

First of all, **AMOLED** is more battery efficient than **Dark Gray**, but only by a margin of about [**0.063%** per hour](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/), which is completely negligible.

Second, saying **AMOLED** is more popular is based on... nothing? You're just *assuming* that's the case. I can tell you right now that more people on **Tachiyomi** use **Dark Gray** over an **AMOLED** theme.

***That being said***, I'm not against your request in any way, I added the **Green Apple** theme after all. I just don't want any misleading or false statements being used as an argument for anything, ever.

**Comment by ash10r** [comment]
You’re right. In hindsight my statements were made on old data (efficiency) and a small sample size (my friend circle). I apologise and have edited my comment. Thanks for considering the request.
