### ISSUE TITLE
[Feature Request] Full App Rotation Lock Setting

### ISSUE THREAD

**Issue by raidenka** [tachiyomiorg/tachiyomi#5400]
Hi this is really minor and kinda dumb but I was wondering if there was a way for you to force portrait in the entire app and not just the reader. It's just mildly inconvenient to read something and then back out only for the screen to turn sideways and having to go turn off auto-rotation even though this is the only app I want to change it for. If it's not possible or worth the time I completely understand; just something I thought would help (at least my personal) UX

**Comment by arkon** [comment]
You can use a rotation lock app from the Play Store.
