### ISSUE TITLE
[Feature Request] <Add the ability to choose a translator.>

### ISSUE THREAD

**Issue by zhoozhich** [tachiyomiorg/tachiyomi#5402]
## Why/User Benefit/User Problem
There is no way to choose a translator. Forces to read manga through the browser.

## What/Requirements
Add the ability to choose a translator.
https://i.imgur.com/JaR9hXf.jpg

(sorry for bad english. i used google translator.)

**Comment by loocool2** [comment]
Duplicate of #969
