### ISSUE TITLE
Failed bypass cloudfare

### ISSUE THREAD

**Issue by lm9a** [tachiyomiorg/tachiyomi#5404]
Phone : tecno pop 4 
Tachiyomi version : tachij2k v.1.0.17
Extentions : مانغا ليك ،manga swat 
Steps to reproduce
Open manga swat or مانغا ليكCatalogue or manga chapter
**Expected behavior**
The catalogue list or manga chapter should load and open

**_Actual behavior_**
java.io.IOException: Failed to bypass Cloudflare!

**_Other details_**
The extension seems to work fine upon first install of Tachiyomi (The full app, not extension), however after sometime it is unable to bypass Cloudflare again.

Tried this with other sources that have Cloudflare DDoS protection (ReadComicOnline) and seem to work as expected: Cloudfare fail after cookie reset

**Comment by dmswd** [comment]
First thing 
The wrong repository
Second thing
Mangaswat is broken and there is already an opened ticket
Third thing
Mangalek sometimes doesn't load the chapter from the first time
Just press the chapter again

So you should close this

**Comment by lm9a** [comment]
> First thing
> The wrong repository
> Second thing
> Mangaswat is broken and there is already an opened ticket
> Third thing
> Mangalek sometimes doesn't load the chapter from the first time
> Just press the chapter again
> 
> So you should close this

The mangalek issue isn't only with chapters sometimes i just want to open the catalogue and would manga swat be fixed someday

**Comment by dmswd** [comment]
If it still persists
Report here
https://github.com/tachiyomiorg/tachiyomi-extensions
