### ISSUE TITLE
[Feature Request] <Compact Grid w/o manga names>

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi#5405]
---

## Why/User Benefit/User Problem
The compact grid option currently moves the name of the manga so that it is essentially comfortable grid, but with the name on top of the cover art. 

Imo it would be more aesthetically pleasing to have it so that the name simply isn't there, and only the cover art would show. Since most manga have their name somewhere on the cover art already, compacting it so the name is on top of said art is also relatively redundant.

## What/Requirements
Exactly how compact grid in the sort option currently works, except there would be no name, rather than moving the name of the manga/manhua/manhwa/webtoon up.

Side note: 
It should be a new option rather than replacing compact grid, such as "cover art grid", or "compact grid w/o names". 
Could also implement this by having a checkbox that simply removes names instead.

**Comment by CrepeTF** [comment]
#3272
