### ISSUE TITLE
[Bug] <Overheating >

### ISSUE THREAD

**Issue by N0tTechW0ke** [tachiyomiorg/tachiyomi#5406]
## Device information
* Tachiyomi version: Stable 0.11.1
* Android version: 6.0.1
* Device: Samsung Galaxy Tab S SM-T800

## Steps to reproduce
1. Open Tachiyomi 
2. Start reading 

### Expected behavior
No overheating

### Actual behavior
Device starts overheating shortly after opening Tachiyomi 

## Other details
I downloaded the stable 0.11.1 version a couple of days ago and started experiencing my (not exactly new) device overheating whenever I opened the app.

**Comment by arkon** [comment]
If you're keeping the screen on for extended periods of time, I'd expect the device to get warmer. Otherwise, we're not really doing anything special, so probably not something we'll be explicitly trying to address.
