### ISSUE TITLE
[Feature Request] A feature wherein you could label bookmarked chapters.

### ISSUE THREAD

**Issue by disori99** [tachiyomiorg/tachiyomi#5409]
## Why/User Benefit/User Problem
There are a lot of mangas that has too many chapters, and I love using the bookmark function to favorite chapters I love the most, however because some series has too much of that personally, it's really confusing what the content is for each one and would be a hassle to go through each one.

## What/Requirements
It's simple, you could label bookmarked chapters to add a short description on them when previewing all the chapters of a series.

**Comment by h-hyuuga** [comment]
Duplicate of #5043 ?
