### ISSUE TITLE
[Bug] <Track silently>

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#5411]
## Device information
* Tachiyomi version: r3521 (e5cdf745, 14/06/21, 18:36)
* Android version: 11
* Device: Galaxy A80 

## Steps to reproduce
1. First step: Enable "track silently when adding manga to library" 
2. Second step: Add a manga to library

### Expected behavior
This should happen: The app auto track (i guess)

### Actual behavior
This happened instead: Nothing

## Other details
I talked about this in discord, and the people sayed that can be just for Komga, if the case, how about tell this below the option?

**Comment by CarlosEsco** [comment]
Track silently is exclusive to the komga tracker.
