### ISSUE TITLE
[Feature Request] Show and read only the chapters of one preferred version

### ISSUE THREAD

**Issue by Tau5** [tachiyomiorg/tachiyomi#5412]
## Why
In mangas there are usually differente versions of the same chapters, some have color, some are in b/w and some are of lower quality. Aside from the fact that tachiyomi treats this versions as different chapters and because of that when you have read a version it skips to the **same chapter** but with a different version. 
Some people want to read only their manga in a color version, so it would be ideal to be able to only show, read and download only the version that the user has selected.

## What
I believe that a feature like this would function like the filter options when viewing the description of a manga. You press the filter button and select a checkbox with the version you want to watch (So if you want to see only a version, you would deselect all except that one)

**Comment by arkon** [comment]
The app has no knowledge of what the chapters contain. You can mark things as read beforehand and set the reader to not include read and/or filtered chapters.

**Comment by Tau5** [comment]
Usually this type of chapters have the same name. So I don't see how this could not be implemented

**Comment by arkon** [comment]
If you're referring to filtering by scanlator: duplicate of #969

If you're trying to somehow distinguish things like B&W vs. colour despite having the same name, that's impossible to do.

**Comment by Tau5** [comment]
Yes it was that. But seeing how the app has never had that (And also, I didn't know the nomenclature for these things) I suspected it was not proposed
