### ISSUE TITLE
[Bug] Viz doesn't work on only one of my devices that it used to work on

### ISSUE THREAD

**Issue by Absentelement** [tachiyomiorg/tachiyomi#5413]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 9
* Device: boox nova 3

## Steps to reproduce
1. First step try to use viz on book nova instead of on phone 
2. Second step it doesnt work even thought it works on tachiyomi on my phone

### Expected behavior
The extension should work on this device like it has been for months. It works fine on my phone still but not on ereader like it used to.

### Actual behavior
Constantly saying to retry

## Other details
I don't believe this is an issue with the extension because I got tachiyomi on my phone and viz on tachiyomi worked on there. All the other extensions I use on my boox nova still work fine except for viz which worked on both devices recently up until now. 

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by CrepeTF** [comment]
Don't make duplicate issues on different repos.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7689
