### ISSUE TITLE
[Bug] Auto Backup not creating backup files

### ISSUE THREAD

**Issue by jhrdcr87** [tachiyomiorg/tachiyomi#5415]
## Device information
* Tachiyomi version: r3521
* Android version: MIUI 12.0.2 Android 11
* Device: Redmi Note 9s

## Steps to reproduce
1. Use auto backup
2. Wait for proto.gz file to be created

### Expected behavior
proto.gz backup files should be in the automatic folder

### Actual behavior
No backup files created any where

## Other details

- Auto backup freq: 12h
- Backup location: internal storage/.../Tachiyomi/backup/automatic (default?)
- Max backups: 5
- Last auto backup was on 16 June 3AM (didn't the 2nd backup for the day) and no auto backup since then.
- Create backup manually no issues, proto.gz files created at selected folder

**Comment by arkon** [comment]
See https://dontkillmyapp.com/xiaomi
