### ISSUE TITLE
[Bug] MangaDex: ext setting content rating

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5417]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.110

## Steps to reproduce
1. enable content rating (for example suggestive/ero/porn/all 3)
2. browse dex (its filtered/working here)
3. search manga that shouldnt be showed(for example input `hai`)

### Expected behavior
only show manga with content rating enabled

### Actual behavior
show manga with all content rating

## Other details
filter in browse workig just fine

use this for example maybe, should only return 1 manga
https://api.mangadex.org/manga?title=hai&contentRating[]=erotica

**Comment by CarlosEsco** [comment]
closing in favor of #5584
