### ISSUE TITLE
[Bug] <Current scanlator priority broken when sorting by chapter number>

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#5420]
## Device information
* Tachiyomi version: 0.11.1 (Preview too)
* Android version: 11
* Device: A80

## Steps to reproduce
1. First step: Set "Shot by chapter tumber" in some manga who have more than 1 scanlator

### Expected behavior
This should happen: It should prioritize the current scanlator when loading the next chapter

### Actual behavior
This happened instead: when you click on chap 1 from ScanlatorX, and switch to to  chap 2 you will in the chapter from ScanlatorY, and after that the app start to show the 2 scanlators like when the filter isn't enable

**Comment by SrW0nka** [comment]
[Example](https://discord.com/channels/349436576037732353/694092459839455243/940975622254121050)

**Comment by Saud-97** [comment]
To be closed as not planned.
![image](https://user-images.githubusercontent.com/39028181/175832135-66017ab2-e98d-4b8e-aa2a-25fabd899529.png)

**Comment by alessandrojean** [comment]
It's not "not planned". It's still a issue that will eventually be addressed, it's even in the milestones.

**Comment by arkon** [comment]
Actually going to close in favour of #969. The janky prioritization thing isn't really a logical way to do it anyhow.
