### ISSUE TITLE
[Bug] Latest preview release has a major theming bug

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#5428]
## Device information
* Tachiyomi version: r3527
* Android version: 9.0
* Device: Kindle Fire HD 10 (2019)

## Steps to reproduce
1. Open up Tachiyomi

### Expected behavior
The top and left sides should be colored normally

### Actual behavior
Whatever this is:
![Screenshot_20210619-182910](https://user-images.githubusercontent.com/61708534/122656896-cd6a6400-d12c-11eb-8f68-6b5f11518835.png)
As you can see, you can't even make out the particular icon that I am on, because it just blends into the background. Though, I assume, it was the coloring of the top and left bars that was the unintended effect in the first place.

## Other details
N/A

**Comment by Soitora** [comment]
Oh right, the one thing both me and @ivaniskandar forgot to test...

**Comment by ivaniskandar** [comment]
I don't have a tablet 🤣 but dw I just forgot to look at the separate layout for it, I'll fix it ASAP
