### ISSUE TITLE
[Bug] Tracking crashes app

### ISSUE THREAD

**Issue by synthtech** [tachiyomiorg/tachiyomi#5429]
## Device information
* Tachiyomi version: Preview r3527
* Android version: 8.1
* Device: XT1671

## Steps to reproduce
1. Select any manga in library.
2. Select Tracking.

### Expected behavior
Should open the tracking sheet.

### Actual behavior
App crashes.

## Other details
Crash log: https://files.catbox.moe/rc084g.txt

**Comment by specterflare** [comment]
Yep, can reproduce. 
Crash logs: [tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6681415/tachiyomi_crash_logs.txt)
