### ISSUE TITLE
UI changes suggestions for Browse tab(Source/Extension/Migrate)

### ISSUE THREAD

**Issue by elitearmedforce** [tachiyomiorg/tachiyomi#5442]
I come here with some UI changes suggestion, from the continuous use of the Tachiyomi app and its extensions.
 
**Changes:**
-Merge of "sources" and "extension" sub-tabs of the Browse tab
-Add "Used" subsection in Extensions section. 
-Addition of collapse/expands icons to subsections(Installed, Updates Pending, and Used)(I don't know the technical word)
The suggestions provided above contains several design illustration previews attached below that were achieved through Figma.
**Note:** This issue post contains several images to provide a better explanation and understanding of the UI changes suggestion.

---
# Overall Changes suggestion(individually explained below)
![image](https://user-images.githubusercontent.com/61043834/122943280-ef135780-d387-11eb-84ac-4517bba65c3a.png)
**Image 1 - All suggested UI changes in one picture**

## User Benefit (overall UI changes benefits)
-Improves user experience
-Ofc makes life easier 😅
-Ease readability of extensions and their lists
-In the end, makes developer life easier too👨‍💻

### Why (explains why this feature should be added)
Main reason for this suggestion to merging the sub-tabs of "Source" and "Extension". Previously "Tachiyomi" app had a single extension for multiple sources, presently, this isn't the case, as each extension contains a single source. It makes no sense to have both Source and Extension sub-tabs, as they almost serve the same functionality overall. With few tweaks, they can be merged together with ease. Some changes that I came up with, will be mentioned below with illustrations.

### Problems and solution (by merging two sub-tabs, missing/removing feature)
-**Problem**
 1. Merging sub-tabs, could lead to removable of sources and extension feature, such as; 
  1.1. Holding on extension source section leads to popup that displays "Pin" and "Disable". (check image 2)
![image](https://user-images.githubusercontent.com/61043834/122944749-20d8ee00-d389-11eb-8d84-e95d8fae7055.png)
**Image 2 - Popup on hold extensions from source sub-tabs**
  1.2. Could lead to missing "extension info" from a single click (or click "Settings) on the extension sub-tab. (check image 3)
![image](https://user-images.githubusercontent.com/61043834/122945648-c4c29980-d389-11eb-95f9-d6e3fec4efc1.png)
**Image 3 - Single click on extensions on Extensions sub-tabs (this I what i meant)**
 2. Search between Global search and extension search after merge. (check image 4)
![image](https://user-images.githubusercontent.com/61043834/122946193-38fd3d00-d38a-11eb-9a86-a034b9e55e01.png)
**Image 4 - Present Global and Extension Search**

-**Solution**
 1. Solution to problem 1, is easy. 
 1.1. We don't need such pop up in the merge section, as Tachiyomi app already had pin icons and disable extension doesn't make sense, as each extension resembles single source rather than multiple sources. Users can just simply uninstall it. Although, if u want to keep such a feature, I have a suggestion for that too by adding "Options" button that will lead to popup or holding on the extension will prompt a popup with options. (check image 5)
![image](https://user-images.githubusercontent.com/61043834/122947381-27686500-d38b-11eb-8920-538b3f7b8002.png)
**Image 5 - Options button and hold on extension for popup options**
  1.2. I believe it can be accessed from hold popup feature mentioned above (check image 5)
 2. Solution for problem 2, is an easy solution is having an icon that switches the search from extension search mode to global search mode. (image 6)
![image](https://user-images.githubusercontent.com/61043834/122949165-7f539b80-d38c-11eb-87b9-4a83a940fca0.png)
**Image 6 - A button to switch from extension mode to global and vice versa**

### No changes part
The language filter option can be the same button for both even if they are merged. I have no idea that it could lead to any problem, as I am an English language user.

### Why (explains why this feature should be added)
I have almost all English extensions installed (around 160ish out of 180ish)(i know that sounds stupid😅) and hardly use all extensions. The reason I have a huge amount of extension installed to read immediately any release of mangas and manhwas added to my library from any multiple sources. Another reason for installing a huge list of extensions, in case I need One Piece manga(example)  with the latest chapters using global search to add to the library, i put it in search in the background(switch apps till search is done). Then, I add One Piece manga from different sources, in case one is down or one source doesn't update chapters in time. 
Coming back to the topic and reason for changes, as mentioned above i use various sources for a single manga from different sources in the library. I don't want to update all the extensions that are not used or contain any manga/manhwa saves from that source(i meant not no manga is added to library from that source). I just want to update only the sources that I use, whereas rest of the sources are installed and not used at all(use them to search that's all), and I don't want to update those extensions. But the present Extensions list doesn't show the difference between used source/extension and not used source/extension.

### Problem & Solution
-Problem
I have soooooooo many extensions installed, difficult to update all. Imagine updating 160, its nightmare(i am not suggesting  to go back to multiple source single extension like before) [my github post](https://github.com/tachiyomiorg/tachiyomi/issues/4748#issue-845417470) & [Aefral post](https://github.com/tachiyomiorg/tachiyomi/issues/4815#issue-855426629).

-Solution
Instead of updating all extensions manually with a single click, I suggest if the UI provide some UI Section/subsection named "Used" like "Installed" and "Updates pending"(image 8) that shows only the extensions that are used. By this I mean, if i add One Piece manga from the source/extension "MangPill", it should be listed under "Used" instead of "Installed" so that i can update the once I use rather than all. (I hope, I was able to convey my thoughts clearly) (check image 7 and 8)
![image](https://user-images.githubusercontent.com/61043834/122952014-c8a4ea80-d38e-11eb-8875-6143d692234f.png)
**Image 7 - As an example, this is list of mangas and one is from MangaPill. Also u can notice i have 159 extension updates pending**
![image](https://user-images.githubusercontent.com/61043834/122953125-892ace00-d38f-11eb-8eb4-23c631e8a66f.png)
**Image 8 - Changes I suggest to show "Used" section with update button**

## Suggestion No 3
###Why (explains why this feature should be added)
Why not😅. Imagine having so many extensions for "Installed, Updates pending, Used, All, English sections. Addition of triangle icons to collapse/expand extensions makes browsing the extensions menu way easier.
![image](https://user-images.githubusercontent.com/61043834/122954628-a7dd9480-d390-11eb-8a29-11e3a4432c74.png)
**Image 9 - Expand and Collapse icon and its working**

One thing even I am not sure what to be added instead of the "Settings" extension part, either "Options" which contains "pin, extension info, uninstall/install"(options can be covered as per suggestion no 2, hold on the extension to get options) or "Latest"(to be honest doesn't make sense to me have this)

If any suggestions mentioned above was solved by Tachiyomi's forks, then I will definitely check it out, as I don't use one.

These suggestions are based on my experience that it will make the user interface much easily accessible and browsable. 

I am definitely sure, the suggested UI design can be improved further by devs and community comments. I can share the link to Figma draft that I used for UI illustrations for better understanding. If my statement/idea isn't clear, I am available for communication in Tachiyomi's Discord server.

Lastly, thanks for the Tachiyomi app and its continuous maintenance of extension, respect the devs and community behind it.😍

**Comment by elitearmedforce** [comment]
It has been 3 days since the post has been issued, yet no comments or reply. I literally spent 3-6 hrs working on it. Comeon devs

**Comment by CrepeTF** [comment]
This request will likely not be explored further until 1.x comes out.

**Comment by CrepeTF** [comment]
The current in-development version of 1.x has already sort of addressed at least Suggestion 1 as of this moment.

**Comment by h-hyuuga** [comment]
> It has been 3 days since the post has been issued, yet no comments or reply. I literally spent 3-6 hrs working on it. Come on devs

Please be cognizant that this is an open source project, maintained by volunteers in their spare time.

**Comment by elitearmedforce** [comment]
> Please be cognizant that this is an open source project, maintained by volunteers in their spare time.

 I know that, and apologies for that message. Just wanted to know that msg reached the devs, even by reacting or a comment. Sorry again🙏.
> The current in-development version of 1.x has already sort of addressed at least Suggestion 1 as of this moment.

Happy to hear that, am looking forward to that (i was thinking that it might be addressed there, but it contains no docs or something to know)
> This request will likely not be explored further until 1.x comes out.

In that case, i might post something similar once it come out😅. Eagerly w8ing, couldn't be more excited. Any ETA on it?

**Comment by arkon** [comment]
I'll read it when I have time.

**Comment by elitearmedforce** [comment]
> I'll read it when I have time.

thank you, np take ur. now that ik the post is acknowledged, I have no worries :)

**Comment by arkon** [comment]
Going to try to comment on this based on the sections you have:

---

### Overall Changes suggestion

> -Merge of "sources" and "extension" sub-tabs of the Browse tab

We're trying to do this in 1.x, although there are definitely concerns about the list being way too long. The collapsible sections can probably help address that though, as you also included.

> -Add "Used" subsection in Extensions section.

I'm not entirely sure if grouping all languages together would be intuitive. It may be fine since we have subtitles in each item for the source language though, so I'm not sure.

> -Addition of collapse/expands icons to subsections(Installed, Updates Pending, and Used)(I don't know the technical word)

As above, probably a good idea, could replace the existing filter menu.

---

### User Benefit (overall UI changes benefits)

> -In the end, makes developer life easier too👨‍💻

Not really.

---

### Suggestion Number 1

> Previously "Tachiyomi" app had a single extension for multiple sources, presently, this isn't the case

This is not true, as a single extension can still expose multiple sources in the sense that 1 source = 1 language.

> Solution to problem 1

I think if anything, the options would need to be exposed as an overflow menu, since the "Latest" entry point still needs to be there. Likewise for update prompts. I'd need to see a more concrete example of how all of that functionality can be exposed without burying them.

> Solution for problem 2

I don't like the toggle idea. If anything, global search should be separated out within the tab as an explicit text input or something.

---

### Suggestion No 2

> I have almost all English extensions installed (around 160ish out of 180ish)(i know that sounds stupid😅) and hardly use all extensions.

Please don't, you're just abusing the system at that point.

> I just want to update only the sources that I use

Then don't have them installed. This is not a usecase we want to support.

> I have soooooooo many extensions installed, difficult to update all. Imagine updating 160, its nightmare

So don't.

---

### Suggestion No 3

Collapsable sections makes sense.

**Comment by elitearmedforce** [comment]
Sorry for the late reply. Thanks for taking ur time going through it. (ik it is toooo much to read)
replying based on ur reply.


## Overall Changes Suggestion
>-Merge of "sources" and "extension" sub-tabs of the Browse tab
>>We're trying to do this in 1.x, although there are definitely concerns about the list being way too long. The collapsible sections can probably help address that though, as you also included.

That is good news to hear and excited to see v1.x. CrepeTF also mentioned this.

> I'm not entirely sure if grouping all languages together would be intuitive. It may be fine since we have subtitles in each item for the source language though, so I'm not sure.

To be honest, I just use "English" so I am not sure how will it work out. i am just guessing tbh, sections can be "Used", "Installed" and "Updates", whereas subsections can be somewhat like "All", "English", "Spanish"(like the present implementation).

## User Benefit (overall UI changes benefits)
>In the end, makes developer life easier tooman_technologist
>> Not really.

I mean in the grand scheme, especially extension management UI and its list UI

## Suggestion No 1
>Previously "Tachiyomi" app had a single extension for multiple sources, presently, this isn't the case
>>This is not true, as a single extension can still expose multiple sources in the sense that 1 source = 1 language.

Ohh didn't know that,

>Solution to problem 1
>>I think if anything, the options would need to be exposed as an overflow menu, since the "Latest" entry point still needs to be there. Likewise for update prompts. I'd need to see a more concrete example of how all of that functionality can be exposed without burying them.

Looks like above examples aren't enough, for better understanding 🤔. Ur right about "Latest" entry point(as I don't use it, so I thought it can be added in option or removed). See, only way to approach it(from my view point) from the suggestion design idea, is by adding "Latest" near Options/Update entry points(screenshot attached)
Maybe(🤔), I can w8 till v1.x release and then approach with the same idea(ofc with better examples), as it will be easy to explain, if the idea is even needed.
![image](https://user-images.githubusercontent.com/61043834/125337703-5ce7e900-e360-11eb-8446-b99f2eaca7ca.png)
Image 1 - This one is options, the "Latest" entry point next to Option/Update.(lazy suggestion, doesn't look good for UI).
![image](https://user-images.githubusercontent.com/61043834/125344493-6f662080-e368-11eb-93e0-d8160f24dd44.png)
Image 2 - Another way to approach this, this idea inspired from Android notification number on social media icons(shows number msg). Instead here it will show only letter "L" or "N"

>Solution for problem 2
>>I don't like the toggle idea. If anything, global search should be separated out within the tab as an explicit text input or something.

Honestly, I don't know the best way to approach this. So I suggested this, there might be a better option. I Will suggest in case something clicks.

## Suggestion No 2
>I have almost all English extensions installed (around 160ish out of 180ish)(i know that sounds stupidsweat_smile) and hardly use all extensions.
>>Please don't, you're just abusing the system at that point.

>I just want to update only the sources that I use
>>Then don't have them installed. This is not a usecase we want to support.

Honestly, didn't know that I was abusing it and never thought it in that way. As am not well versed with sources in general, that is why I have all extension installed in case I search for specific manga/manhwa/manhua/comic and also helps in migrating. In that case, I will remove unnecessary ones.

**Comment by inorichi** [comment]
I created the referenced issue above without knowing about this one. I'll definitely read this later (probably tomorrow) and update the other issue accordingly. Don't hesitate to add more feedback over there.

**Comment by elitearmedforce** [comment]
weird, didn't receive any notification on my email of the above comment, 

>New Browse UI tachiyomiorg/tachiyomi-1.x#20

weird didn't receive notification for this too. looking into chats, excited,

**Comment by elitearmedforce** [comment]
weird, didn't receive any notification on my email of the above comment,

>New Browse UI tachiyomiorg/tachiyomi-1

weird didn't receive notification for this too. looking into chats, excited,

**Comment by arkon** [comment]
Closing in favour of #3486, which captures the suggestion for collapsible sections.

The other suggestions weren't quite polished enough to be considered.
