### ISSUE TITLE
App not installing on android 11 device

### ISSUE THREAD

**Issue by Anonymous-harry** [tachiyomiorg/tachiyomi#5443]
## Device information
* Tachiyomi version: 0.11
* Android version: 11
* Device: s21

## Steps to reproduce
1. First step download stable version
2. Second step press install then app does not install

### Expected behavior
This should happen. App should install

### Actual behavior
This happened instead. Getting messafe saying app not installed 

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment]
Use this app to get a more helpful error: https://play.google.com/store/apps/details?id=com.aefyr.sai

If you need more help, please check out our Discord server.
