### ISSUE TITLE
[Bug] <Bato.to Cloudflare blocked library and manga viewing >

### ISSUE THREAD

**Issue by SleepyCap** [tachiyomiorg/tachiyomi#5444]
## Device information
* Tachiyomi version: 0.10.12
* 
* Device: Amazon Fire

## Steps to reproduce
1. Open extension or open manga
2. View error

### Expected behavior
Library and manga should load normally

### Actual behavior
Instead an error appears.
java.lang.Exception: Failed to bypass Cloudflare

## Other details
Works perfectly fine in WebView.

**Comment by loocool2** [comment]
batoto has raised their Cloudflare protection level possibly due to a DDoS attack, expect to not be able to use the site or the site to be extremely slow during this time.
