### ISSUE TITLE
[Bug] Bato.to Failed To Bypass Cloudfare

### ISSUE THREAD

**Issue by EisbarGFX** [tachiyomiorg/tachiyomi#5445]
Relevant to Extension and not main, but the previous issue report of the same nature was moved to main - so I created it here.

---

## Device information
* Tachiyomi version: 0.11.1
* Android version: 10
* Device: Samsung Galaxy S9+

## Steps to reproduce
1. Install Bato.to Tachiyomi extension
2. Open extension in Browse -> Sources -> Bato.to
3. OR open a series from Bato.to already in library and pull down to refresh

### Expected behavior
The series should refresh with new chapters or the main source page should display the available series.

### Actual behavior
`java.lang.Exception: Failed to bypass Cloudflare` appears in both instances - when trying to read a chapter already in library, `No Pages Found` is shown after a loading circle is shown for a prolonged time.

## Other details
Likely related or similar to #2552 `[Bug] MangaKisa : Failed to bypass Cloudflare`

**Comment by loocool2** [comment]
batoto has raised their Cloudflare protection level possibly due to a DDoS attack, expect to not be able to use the site or the site to be extremely slow during this time.
