### ISSUE TITLE
[Feature Request] Button to set a manga to archive to avoid update checking.

### ISSUE THREAD

**Issue by GoodManWEN** [tachiyomiorg/tachiyomi#5449]
## Why/User Benefit/User Problem
(explain why this feature should be added)
Could you please add a feature to set a manga to archive.
There's some manga that you know will never update anymore so that you do not need to check for update everytime.

## What/Requirements
(explain how this feature would behave)
Add additional archive property for a manga to control weather to avoid update checking.

**Comment by arkon** [comment]
Create a category for it and exclude it from global updates.

**Comment by GoodManWEN** [comment]
> Create a category for it and exclude it from global updates.

I found the option finally, but it's not very intuitive. Will it be integrated in the category page?
