### ISSUE TITLE
[Feature Request] <Get notified when a new extension added to your preferred language>

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi#5453]
## Why/User Benefit/User Problem
It's tiring to scroll all the way down everyday to check if there is a new extension in my language (my language is Arabic and it's the last one in the extensions list). filtration of the extensions isn't a solution because I use also some English extensions and you know how many are there

## What/Requirements
Tachi users will get a notification when a new extension added to their preferred language

Thanks for providing us this awesome app, All the respect to everyone behind this app

**Comment by lm9a** [comment]
I think As a arabic user there's not even that much of arabic extension and a lot of them have issues like manga swat or manga lek even tho they're one of the best arabic extensions

**Comment by arkon** [comment]
#4363
