### ISSUE TITLE
[Feature Request/Removal?] Remove included "ptsans_narrow_bold" font and it's usages

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/tachiyomi#5455]
## Why/User Benefit/User Problem
- The library comfortable / compact grid items, and the global search items are the only places in the whole app that use this font (according to "find usages" in Android Studio)
- These seem to be the few, if not only places in the app (from a quick browse) where the system selected font does not apply.
- The font will replace some symbols with their emoji counterparts on certain devices (see below).
  - My device is a Samsung Galaxy S21 running Android 11 for context 
  - This is not an issue with Tachiyomi: other fonts built into the device do the same thing
  - However I've found a font that does not do this emoji thing, which I have installed on my device: SamsungOne
  - _However_ the ptsans font does this, and due to this emojis will be rendered where it is used

### Emoji Problem
Below, you can see that the symbols in the title are being converted to emoji; however the actual title provided by the website does not use emojis: https://mangakakalot.com/manga/tp924500
| Comfortable Grid Item (ptsans font) | Manga Header (system selected font: SamsungOne) |
|-------------------------|------------------|
![grid_item](https://user-images.githubusercontent.com/25621728/123367785-ca5de200-d537-11eb-8919-3b57d2b0503e.jpg) | ![manga_header](https://user-images.githubusercontent.com/25621728/123367896-01cc8e80-d538-11eb-9c0e-9b86b0881258.jpg)

I thought I'd open the issue here first before I went and made a PR, because the fact that the font is only used specifically in these places made me wonder if there was a specific reason it should remain in the app.

**Comment by CrepeTF** [comment]
The reasoning as to having this specific font for the grid item titles is that it's very compact, meaning that it shows more of the title.
