### ISSUE TITLE
[Feature Request] <Write short description here>

### ISSUE THREAD

**Issue by voltes2** [tachiyomiorg/tachiyomi#5456]
please add
www.mangago.me

## Why/User Benefit/User Problem
(explain why this feature should be added)
contain much more manga then else
## What/Requirements
(explain how this feature would behave)
please add www.mangago.me

**Comment by CrepeTF** [comment]
Wrong repo, also it's not going to be added.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475
