### ISSUE TITLE
Order categories in library category tabs

### ISSUE THREAD

**Issue by sunbeams001** [tachiyomiorg/tachiyomi#5460]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

User can rearrange categories in library category tabs
I have a category of "reading manga", I want to make it the first one of all categories so when I open the library I can easily reach it.
For now, the "Default" category is fixed and can not be rearranged even in the `Categories edit page`
Maybe let the "Default" category be displayed in the `Categories edit page` a better solution?

**Comment by paulo27ms** [comment]
All you have to do is go to the Categories menu and move the categories around.
I don't have a default category, not sure if it can be deleted, renamed or disabled now.

**Comment by sunbeams001** [comment]
@paulo27ms When you just add a manga to library with no category, it goes into the default one.

**Comment by paulo27ms** [comment]
Then make a category your "default" and you can move it around after.

**Comment by sunbeams001** [comment]
@paulo27ms Thanks, it IS a solution, but considering the fact there is a setting item `library-default category` and already a "default" category in it. 
A new user level default category may makes user confused.

**Comment by arkon** [comment]
It is confusing, but it's not going to change since it'd break a lot of things.

As @paulo27ms said, make another category and move everything to that. The "Default" category will then disappear by itself.
