### ISSUE TITLE
Crashes on Android 12 Beta 2.1

### ISSUE THREAD

**Issue by shim1998** [tachiyomiorg/tachiyomi#5461]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 12.1 Beta

### Device

Google Pixel 4A

### Steps to reproduce

1. Open Tachiyomi App
2. Crash

### Expected behavior

App should work

### Actual behavior

App crashes

**Comment by loocool2** [comment]
We don't support Android 12 at all right now. Any issue you have will not be fixed until Android 12 is fully released at the earliest.
