### ISSUE TITLE
Navigate only between the downloaded chapters while in "Downloaded only" filtered library

### ISSUE THREAD

**Issue by Vacui** [tachiyomiorg/tachiyomi#5463]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

Android 6.0

### Device

Energy Phone Max 2+

### Steps to reproduce

1. Enable _Downloaded only_ mode in the menu _More_
2. Open a downloaded chapter with the next/previous  downloaded chapter separated by at least two numbers
3. Reach the end/start of the document and tap/scroll to open the next/previous chapter.

### Expected behavior

In the _Downloaded only_ mode all the non-downloaded chapters are hidden in the library, I therefore expected to be able to navigate only between them.

### Actual behavior

Since the next or previous chapter is not downloaded the app tries to load it if there is a network connection active, failing otherwise.

**Comment by Soitora** [comment]
/edit-title "Navigate only between the downloaded chapters while in "Downloaded only" filtered library"

**Comment by Soitora** [comment]
/edit-title "Navigate only between the downloaded chapters while in \"Downloaded only\" filtered library"

**Comment by Vacui** [comment]
Don't know if one update added it, but just a few days ago I found out that by enabling the option _Skip filtered chapters_ in **Settings** > **Reader** >**Reading**, and applying a filter in one element of the library, it's possible to trigger the behavior I was expecting; but it doesn't work with the _Downloaded only_ global filter setting.

I'm satisfied with this workaround, I hope you will be able to figure out why the bug occurs tho.

Thx for the good work anyway,
Bye
