### ISSUE TITLE
Fingerprint unlock prompt happens twice when clicking manga links from browser

### ISSUE THREAD

**Issue by rcdailey** [tachiyomiorg/tachiyomi#5468]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11 (Oxygen OS)

### Device

OnePlus 7 Pro

### Steps to reproduce

1. Ensure the extension for whatever manga site you plan to test with is installed
1. Open browser (doesn't matter which one), go to the site with manga
1. Click manga link, it opens Tachiyomi
1. Fingerprint scan is requested once
1. For the second and onward times tachiyomi is launched, the fingerprint scan is requested twice
1. Manga appears, I can click it to open the details page and then click a chapter to read it
1. When done reading, Use "recent apps" to switch back to the browser and repeat from step 1 using a different manga.

### Expected behavior

No matter how many times I launch Tachiyomi from browser links (deeplink), I should only ever get my security prompt (fingerprint) once.

### Actual behavior

The first time I launch Tachiyomi using the steps to reproduce, I only get the fingerprint prompt once.

However, the second and onward times I repeat the steps, I get a fingerprint prompt two times back to back.

### Other details

My security settings are:

- Require Unlock: ON
- Lock when idle: Always
- Secure screen: ON
- Hide notification content: ON

I'd prefer not to modify these settings since any time I navigate away from the app, I want it to require a finger print to open it back up.

**Comment by arkon** [comment]
Courtesy of @Jays2Kings:

> if you use an older device or use system wide light theme + dark theme in app, it will prompt the fingerprint reader twice

**Comment by rcdailey** [comment]
I can confirm that theme was set to follow system. That's a very strange root cause for sure.
