### ISSUE TITLE
Skipping the same chapters if source reports few of them and you already have readen one.

### ISSUE THREAD

**Issue by 0xAB51NTH** [tachiyomiorg/tachiyomi#5469]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

There are extensions that might return a multiple sources (for example mangadex returns multiple groups in solo leveling) and it causes the user to skip thru 3 other releases before they go to another chapter, adding some sort of check (?) in order to skip the duped chapters (released by other groups) and some sort of logic to autoread the one by the same group would be a very good life quality improvement.
![example](https://i.imgur.com/aES6pgn.png)

### Other details

Currently the app will read the next chapter that will cause it to read the same chapter twice.

**Comment by CrepeTF** [comment]
Basically #2224
