### ISSUE TITLE
Translucent background after exiting reader while doing an selection

### ISSUE THREAD

**Issue by ghostbear** [tachiyomiorg/tachiyomi#5471]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3537

### Android version

Android 11

### Device

OnePlus 8

### Steps to reproduce

1. Open any chapter
2. Close the chapter 
3. Make a selection of any manga in the library

### Expected behavior

Icons and text, like search icon and library text, should disappear when selecting 

### Actual behavior

Icons and text, like search icon and library text, are grayed out/barely visible when selecting

### Other details

This is not present on the current stable release (0.11.1)

Likely it was introduced with the theme clean up (932c924)

**Video showing how to reproduce the bug**

https://user-images.githubusercontent.com/6576096/123992672-1c858400-d9cc-11eb-9d14-3a6b9df8fccd.mp4

**Comment by CrepeTF** [comment]
It's a feature

**Comment by ghostbear** [comment]
Closing because it seems that the app just was in some weird state where it didn't render the color as opaque

**Comment by ivaniskandar** [comment]
When you got this issue you should have the same translucent thing happened on bottom sheet too. I believe this was introduced by my reader theme changes but I'll need to investigate further.

**Comment by ghostbear** [comment]
Ah found a way to actually replicate the bug

> When you got this issue you should have the same translucent thing happened on bottom sheet (and possibly on anything with MaterialShapeDrawable background) too.

Yep
