### ISSUE TITLE
Search for big titles crashing the app

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#5474]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3537

### Android version

A11

### Device

Galaxy A80

### Steps to reproduce

1. Try search some manga in global search
Ex: Yahari Ore no Seishun Love Comedy wa Machigatteiru
2. Press enter and wait to the search ends 

### Expected behavior

Finishing the search and be able to browse in results 

### Actual behavior

Crash and close the app during the search or when the blue progress bar disappear 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6729469/tachiyomi_crash_logs.txt)

### Other details

1. If i search by "Yahari Ore no Seishun" the things runs as expeted, for this reason i suppose that's related to the size of the titles 
2. In 0.11.1 (Stable) all works as expect 

https://user-images.githubusercontent.com/76596575/123709564-abb36000-d843-11eb-85e5-23043c048ae4.mp4
https://imgur.com/a/RVWxeF4

**Comment by datreesezcup** [comment]
@SrW0nka I _think_ there's a possibility you might be running into an issue I encountered about a month ago, involving one of the "Hitomi.la" extension. (tachiyomiorg/tachiyomi-extensions#7224) This issue was supposedly fixed, but I'm thinking that perhaps something that changed between Tachiyomi 0.11.1 and Tachiyomi r3537 is causing this issue to resurface. 

As a test and potential workaround: Would you disable the Hitomi.la source and try searching for `Yahari Ore no Seishun Love Comedy wa Machigatteiru` again?

I myself am experiencing crashing when searching this title on r3537, however not if the Hitomi.la source is disabled. That is why I think this might be the exact issue.

If this isn't the issue then I sincerely apologize for somewhat hijacking this thread 🙇

**Comment by SrW0nka** [comment]
> @SrW0nka I _think_ there's a possibility you might be running into an issue I encountered about a month ago ([tachiyomiorg/tachiyomi-extensions#7224](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7224)), involving the "Hitomi.la" extension. This issue was supposedly fixed, but I'm thinking that perhaps something that changed between Tachiyomi 0.11.1 and Tachiyomi r3537 is causing this issue to resurface.
> 
> As a test and potential workaround: Would you disable the Hitomi.la source and try searching for `Yahari Ore no Seishun Love Comedy wa Machigatteiru` again?
> 
> I myself am experiencing crashing when searching this title on r3537, however not if the Hitomi.la source is disabled. That is why I think this might be the exact issue.
> 
> If this isn't the issue then I sincerely apologize for somewhat hijacking this thread 🙇

you're right, if Hitomi.Ia is disabled the bug disappear (thanks, now i can add my manga, without problems), so we already know what's the case...i need to open a bug report in Hitomi.la extension page at GH?

**Comment by datreesezcup** [comment]
Yeah, I'd close the issue here, and open an issue in the [extensions repo](https://github.com/tachiyomiorg/tachiyomi-extensions), with basically the same info you provided here.

Glad I could help!

**Comment by SrW0nka** [comment]
> Yeah, I'd close the issue here, and open an issue in the [extensions repo](https://github.com/tachiyomiorg/tachiyomi-extensions), with basically the same info you provided here.
> 
> Glad I could help!

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7916 done
