### ISSUE TITLE
Can't move custom category items to Default category.

### ISSUE THREAD

**Issue by tripathi-abhishek** [tachiyomiorg/tachiyomi#5475]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Samsung J8

### Steps to reproduce

1. Add any manga to library.
2. Adding will ask for category.
3. Here there is no option for default.
4. Even the already added titles can't be moved to Default.

### Expected behavior

Moving of titles between default and custom should be made available.

### Actual behavior

No movement of titles possible from custom to default category.

**Comment by CrepeTF** [comment]
Just uncheck all the categories when you try to move them, it'll go to Default.
