### ISSUE TITLE
Download Queue Unpauses Itself Whenever Something is Added to the Queue While Paused

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#5477]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Device

Lenovo Tab 4 8 Plus

### Steps to reproduce

1. Select all in library
2. Press download
3. Pause as soon as something shows up in the queue
4. Observe it unpausing itself when Tachi adds more the queue

### Expected behavior

The download queue should stay paused after the user manually pauses it, even after something new is added to the queue.

### Actual behavior

The download queue unpauses itself when something is added to the queue after the user pauses it manually while Tachiyomi is in the process of adding things to the download queue

### Other details

Reproduced by Curche

**Comment by Bogonimo1** [comment]
I also get the same bug. I get the same result as the bug stated in this reported bug.

**Comment by arkon** [comment]
Closing in favour of #7492
