### ISSUE TITLE
Use outlined icon for Delete Sweep

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5482]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

![image](https://user-images.githubusercontent.com/63973749/124057789-bac02b00-da5a-11eb-8282-c39e73010218.png)

Delete sweep has an [outlined variant](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Adelete_sweep).

**Comment by Soitora** [comment]
I intentionally filled it, it didn't look as good with outlined as the icons below it were outlined but had a different purpose.
