### ISSUE TITLE
Hiatus status 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5487]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Currently Tachiyomi has these:
• Ongoing
• Completed 
• Unknown status 

The problem comes in when a book is on hiatus, it is normally set to unknown status even though the status is already known. Depending on the extention, if the hiatus isn't known then it should say "Unknown status".

Implementing this can help the reader understand why the manga may not be updating chapters. It could also be used for filtering.

**Comment by paulo27ms** [comment]
In MD's case, it translates to Ongoing, not Unknown.

**Comment by CarlosEsco** [comment]
I don't think there plans to add more status.  MD is one of the few that actually provide more then what tachi has so this would only really be a change to that. 

There is no reason an extension can't translate whatever unique status they have to fit tachi

**Comment by zayin02** [comment]
I'll close this issue since there are no plans, but if ever there may be someone can just reopen this issue.
