### ISSUE TITLE
[Bug] Exits Full Screen On Swipe

### ISSUE THREAD

**Issue by ManHang20** [tachiyomiorg/tachiyomi#5492]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3537

### Android version

11

### Device

Pixel 4a

### Steps to reproduce

1. Full Screen option is enabled
2. Open any manga
3. Tap once to show the chapter navigation bar and tap again to go back into full screen
4. Try to swipe or scroll

### Expected behavior

It should go to the next or previous page

### Actual behavior

On closing the chapter navigation bar once (Going back to full screen mode), the first touch/swipe after that exits the full screen mode and only then further swiped are registered, can be fixed if I re open the chapter but issue again comes up when navigation bar is brought up and exited back to full screen.

Video shared in discord's Support channel
https://discord.com/channels/349436576037732353/349436576037732355/860837819273707520

**Comment by ivaniskandar** [comment]
Already fixed with #5465
