### ISSUE TITLE
bookmarked chapters can not be deleted within the app

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/tachiyomi#5494]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

android 7.1.2 N2G47H

### Device

xiaomi redmi note 5A prime

### Steps to reproduce

1.book mark a downloaded chapter
2.try to delete the chapter itself
3.app doesnt allow it and got to either remove bookmark or delet from a file manager

### Expected behavior

chapter should be deleted normally

### Actual behavior

chapter isnt deleted

**Comment by arkon** [comment]
Do you have the setting to disallow deleting bookmarked chapters enabled?

**Comment by areyance** [comment]
does that one allow me to delete chapters even if marked?

 i thought it was just to automate deleting them specfically and now that i
think about it that was a weird assumption

في السبت، ٣ يوليو، ٢٠٢١ ٥:٢٦ م arkon ***@***.***> كتب:
