### ISSUE TITLE
where to watch 'starving anonymous'

### ISSUE THREAD

**Issue by yizhanchengyan** [tachiyomiorg/tachiyomi#5495]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

where to watch 'starving anonymous'

### Other details

where to watch "starving anonymous"

**Comment by arkon** [comment]
Ask in the Aniyomi Discord server. We're not associated with that project.
