### ISSUE TITLE
Toggle to show cover images in chapters list

### ISSUE THREAD

**Issue by proplcy** [tachiyomiorg/tachiyomi#5497]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

While this may only benefit those who use a personal komga database, I believe the change would have to be made to the Chapter List, thus I am putting the feature request here.

Why/User Benefit/User Problem
When reading volumes, i.e. not individual chapters, the cover art is not displayed for each volume in the chapter list. By adding the ability to toggle the chapter list to be a grid, which would display the first page of each volume as the cover, users will be able to see all the nice cover art when browsing the volumes of their manga.

What/Requirements
Implement a layout similar to the Library display's Grid/List mode for the Chapter List, thus allowing users to toggle between a list view or a grid view displaying the cover art for each "chapter" (or volume)

### Other details

I can't understand why this is closed. https://github.com/tachiyomiorg/tachiyomi/issues/2577

This is a very important feature for watching cartoons.

**Comment by arkon** [comment]
You could read the comments in #2577 on the reasoning. Also we don't support cartoons.

**Comment by proplcy** [comment]
> You could read the comments in #2577 on the reasoning. Also we don't support cartoons.

I know too. I also posted a link.

But this definitely needs to be re-discussed.
An important feature for watching cartoons

**Comment by arkon** [comment]
I'm not sure how to make it clearer, but we don't support watching cartoons. If you're talking about Aniyomi, take it up with them.

**Comment by proplcy** [comment]
> I'm not sure how to make it clearer, but we don't support watching cartoons. If you're talking about Aniyomi, take it up with them.

need a komga.

Why do you keep mentioning cartoons?

**Comment by CrepeTF** [comment]
Anyway, this feature is just too specific, too few users use komga alone, and the vast vast majority of chapters are ordered via chapters, not volumes. End of.

If it works fine and well now, it works fine. Going any further just for this one very niche source is honestly a poor allocation of time and effort.

**Comment by arkon** [comment]
> Why do you keep mentioning cartoons?

Because your first post literally says "This is a very important feature for watching cartoons."?

> It's definitely a necessary function for komga.

This feature requires requesting every single chapter entry. That works fine for Komga since it's locally hosted, but that exception doesn't make it acceptable from an implementation point of view.

**Comment by elvesalmighty** [comment]
but i really need dis cover feature for my local doujin since i folder them based on the artist. 
there is an app named kur* r**der that can fulfil those, but i cant/wont use it because it isnt tachi.

Can i have hope?

**Comment by CarlosEsco** [comment]
> but i really need dis cover feature for my local doujin since i folder them based on the artist. 
> there is an app named kur* r**der that can fulfil those, but i cant/wont use it because it isnt tachi.
> 
> Can i have hope?

No
