### ISSUE TITLE
Botton menu becomes semitransparent

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#5498]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3537

### Android version

A11

### Device

Galaxy A80

### Steps to reproduce

Tbh idk, i just open tachiyomi, play some games and return (sorry for can't provide decent information here)

### Expected behavior

Just keep the normal color

### Actual behavior

Botton menu becomes semitransparent 

### Other details

![Screenshot_20210703-183948_Tachiyomi](https://user-images.githubusercontent.com/76596575/124367686-01b34980-dc30-11eb-85db-2c5c3a9ace69.jpg)

**Comment by zayin02** [comment]
Read #5471

**Comment by ghostbear** [comment]
Update to latest preview, this should be fixed with the new preview

**Comment by SrW0nka** [comment]
> Update to latest preview (r3556), this should be fixed with it

thanks
