### ISSUE TITLE
Merged Blue theme still has "Dark Blue" naming

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5500]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3556

### Android version

Android 11 the worst version

### Device

Redmi Note 9 Pro

### Steps to reproduce

Pick Dark Blue setting
Use Light mode

### Expected behavior

Some other naming, like Tachi Blue or whatever

### Actual behavior

Theme named Dark Blue while app is in light theme

**Comment by ivaniskandar** [comment]
The "dark" in "dark blue" here is referring to the shade of blue this theme uses.

**Comment by vengiare** [comment]
> The "dark" in "dark blue" here is referring to the shade of blue this theme uses.

Absolutely not. 0.11.1 lists this as "Light blue".

**Comment by ivaniskandar** [comment]
Well it is now...

**Comment by vengiare** [comment]
> The "dark" in "dark blue" here is referring to the shade of blue this theme uses.

Point is this isn't correct at all. It's not because "it's a dark shade of blue". "It is now" doesn't really make sense.

![Screenshot_2021-07-04-18-44-27-419_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63973749/124382034-fb88a000-dcf7-11eb-94c1-bb339e97dd30.jpg)![Screenshot_2021-07-04-18-44-33-116_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63973749/124382037-fdeafa00-dcf7-11eb-9f14-cc73b28415a8.jpg)

**Comment by Soitora** [comment]
> > The "dark" in "dark blue" here is referring to the shade of blue this theme uses.
> 
> Point is this isn't correct at all. It's not because "it's a dark shade of blue". "It is now" doesn't really make sense.

Deal with it.

The "Dark" and "Light" were previously specifically pointing to the version of the theme, while now it's just the color itself.

We've discussed this internally before we even released it.

You can't try to correct us on something you have no internal knowledge about.

**Comment by vengiare** [comment]
> You can't try to correct us on something you have no internal knowledge about.

Well I'm basing my issue on previous functionality so, literally no one else would know this "internal knowledge" then.

Anyways guess that's settled now.

**Comment by Soitora** [comment]
> > You can't try to correct us on something you have no internal knowledge about.
> 
> Well I'm basing my issue on previous functionality so, literally no one else would know this "internal knowledge" then.
> 
> Anyways guess that's settled now.

We might just rename it to something else entirely, maybe `Blue`, maybe `Legacy blue`. You'll see soon. Just don't want the different strings changing while the accent technically is static.

**Comment by arkon** [comment]
I agree that it's a bad name, so I'll change it to something else.
