### ISSUE TITLE
Follow Option

### ISSUE THREAD

**Issue by Kazuha1** [tachiyomiorg/tachiyomi#5502]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

It would be possible to add in the follow option the page: lectortmo.com, there are too many sleeves that I have to follow to look for it one by one

**Comment by CrepeTF** [comment]
no.

**Comment by CrepeTF** [comment]
this is out of the scope of the app.
