### ISSUE TITLE
Download pauses when the last chapter in queue is removed

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/tachiyomi#5503]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3556

### Android version

Android 11

### Device

Samsung A50

### Steps to reproduce

1. Queue a bunch of chapters for download.
2. Remove the last chapter in queue. 

### Expected behavior

The download should continue as it is. 

### Actual behavior

The download pauses.

**Comment by zayin02** [comment]
It does the opposite of #5477

**Comment by arkon** [comment]
Closing in favour of #7492
