### ISSUE TITLE
Custom Location for Local Source

### ISSUE THREAD

**Issue by Satria41** [tachiyomiorg/tachiyomi#5504]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I suggest this feature because changing local source Location to desired location can be useful for example: change the location to Hidden folder so The Gallery doesn't scan the Local Source

**Comment by curche** [comment]
Duplicate to #2086

Alternatively, you can also keep the files in local folder in SDCard or set up a Komga/Mango server

As for this:
> The Gallery doesn't scan the Local Source 

refer to https://tachiyomi.org/help/faq/#why-can-i-see-manga-pages-from-my-downloads-in-my-device-s-photo-gallery
