### ISSUE TITLE
Expand cover animates even with animations disabled

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi#5507]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3556

### Android version

Android 9

### Device

Lenovo Smart Tab M10

### Steps to reproduce

1. Have animations disabled as an accessibility option
2. Tap on a manga cover to see a larger version

### Expected behavior

No animation.

### Actual behavior

Animation. The effect is the same with or without animations disabled, as shown in attachment. When the settings icon appears in the nav bar, that's when I paused the video to enable animations.

### Other details

https://user-images.githubusercontent.com/34067059/124500797-64225c00-dd8e-11eb-8e19-16aa2b7c84b2.mp4

The stutteriness is thanks to the SD 450 powering the tablet, which is a different issue... the same problem is present on my phone (no stutter), which is a worse effect due to the much more significant change in cover size.

**Comment by arkon** [comment]
Noted in #5366
