### ISSUE TITLE
Amoled theme is broken

### ISSUE THREAD

**Issue by SlamZDank** [tachiyomiorg/tachiyomi#5511]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

preview r3556

### Android version

7.1.2

### Device

Samsung j3 (16)

### Steps to reproduce

1. open app
2. set the theme to amoled
3. leave the app without closing it
4. use other apps for a while
5. re-open tachiyomi from recents

### Expected behavior

labels and various icons must be visible

### Actual behavior

almost everything in the ui is invisible

https://user-images.githubusercontent.com/83764499/124655537-e0ed2d00-de97-11eb-85f4-9fd01c6f3b64.mp4

### Other details

in aniyomi r3778 you can reproduce this bug also by starting a show and going back to the menu.
![Screenshot_20210706-203015](https://user-images.githubusercontent.com/83764499/124656471-28c08400-de99-11eb-908c-a34cc9fc79c2.png)
the ui will auto correct itself if you exit the app and open it from recents or close the app and then restart it.
didn't check if it is applicable to light and dark themes.

**Comment by CarlosEsco** [comment]
There is no reason to post anything related to aniyomi as that's a different repository unrelated to tachiyomi.org

**Comment by SlamZDank** [comment]
i just simply mentioned that app to better help finding the bug as they both have the same bug with 2 ways to reproduce them. next time i won't mention that app. my b.

**Comment by M-Phuykong** [comment]
Tried it with Android 11. No luck in replicating the problem.

**Comment by SlamZDank** [comment]
yup this issue seems to be impacting my low end devices with android 7, tried this issue on a more modern phone and yes, themes work fine on there so its a matter of the device you're using.

**Comment by arkon** [comment]
Should be fixed by #5509

**Comment by SlamZDank** [comment]
the one i reported in [J2K](https://github.com/Jays2Kings/tachiyomiJ2K/issues/886) version is a different one from this as i found 2 ways to break themes. the first one is by changing the language (fixed) and the second one is by letting tachiyomi run in the background and then coming back to it after a while (using other apps in the process may help reproduce this somewhat rare issue im not sure), as you can see here's picture of the yin and yang theme to prove that this issue is still around.
![Screenshot_20210711-220802.png](https://user-images.githubusercontent.com/83764499/125210419-a3bddc00-e297-11eb-8e20-b0f4eea38f63.png)

**Comment by SlamZDank** [comment]
The bug seems to have been fixed in preview r3631, closing issue 😌.
