### ISSUE TITLE
App crash when you try to sort all manga in library

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi#5513]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3556

### Android version

Android 11

### Device

Poco x3 pro

### Steps to reproduce

1. Open any manga
2. make sort by chapter number
3. press three dots
4. check the box: apply to all manga in library

5. try to open any title

### Expected behavior

All manga in library have sort by chapters number

### Actual behavior

App crash

**Comment by arkon** [comment]
Please share the crash logs.

**Comment by arkon** [comment]
Likely addressed by 776194f5b27c1e37023efe61b6893a8874ab75e5
