### ISSUE TITLE
bad request on raw.githubusercontent.com

### ISSUE THREAD

**Issue by Merlyx** [tachiyomiorg/tachiyomi#5517]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Feature request:
Add a switch to switch to the cdn service provided by jsdelivr.

In China, there are inferior international bandwidth connections, which prevents people from requesting raw.githubusercontent.com properly.

![Screenshot_2021-07-08-22-38-48-919_eu kanade tachiyomi](https://user-images.githubusercontent.com/7742683/124942909-a07be380-e03e-11eb-8aca-032f0da1bf7e.jpg)

A simple and workable solution is to switch, for example
https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.min.json
and replacing it with
https://cdn.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json

download apk:
https://cdn.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/apk/tachiyomi-all.batoto-v1.2.13.apk

Thanks for your work, and this is a great application!

**Comment by Merlyx** [comment]
There is a problem. When the project's files are updated, jsdelivr does not actively update them.
I checked the documentation and learned that we can force an update by sending a request to jsdelivr at the following address.
(This feature needs to be requested beforehand)

https://purge.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json

Is it possible to add to the github actions for automatic tasks?
Thanks.

Related links:
https://github.com/jsdelivr/jsdelivr#purge-cache

**Comment by arkon** [comment]
> This feature needs to be requested beforehand

Did you already request it? I assume you did, since it was successful when I tried it...

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/f82b4bb69d7d85c0996e0775e2cde3d374eba5fc

**Comment by Merlyx** [comment]
> > This feature needs to be requested beforehand
> 
> Did you already request it? I assume you did, since it was successful when I tried it...

I did not send it a request.
It may just be a matter of limiting the number of high frequency refreshes, I don't know...😥

**Comment by arkon** [comment]
That's okay, I've sent a request to them. I'll close this for now since there's no actions left to be taken right now.

**Comment by arkon** [comment]
For the record:

Them:
> You need to correctly tag your releases and make sure its semver valid

Me:
> The concept of releases and semver aren’t relevant in our context as we’re only ever interested in the tip revision of this file. The application that’d retrieve this content depends on always getting the latest version.
>
> Does that mean that jsDelivr isn’t suitable for our purposes?

Them:
> jsDelivr uses tags to understand when a new version of a file was released. 
> Otherwise we would have to re-download all files every single time which is not good for production use.
>
> So unfortunately no way around that.

Me:
> Sorry, I’m a bit confused; isn’t that what the purge API is meant for? If we can purge the cache for this single file upon updating it, it should work fine.

Them:
> Purge works with CDN APIs and purges their cache. It doesn't force jsDelivr origin to pull a new file, we don't have that logic at all.
> 
> As you can see here https://www.jsdelivr.com/network/infographic we have local caches and a central permanent storage. The only way for a file to get created there is to tag a new release.

**Comment by CarlosEsco** [comment]
An option would be to use https://statically.io/
You can't purge but it purges caches daily if you we were to rename the repo branch to dev, main, or develop.

**Comment by FourTOne5** [comment]
Why not serve index.min.json through the Tachi site and use jsDelivr to download extension apk since every version of the extension has different named apk. In case GitHub can't be accessed.

**Comment by kasperskier** [comment]
I checked the behavior again. The purge actually works. I think the "permanent storage" only applies to tagged releases (which they call "[static files](https://github.com/jsdelivr/jsdelivr#caching)"), while you can still purge branch files, whose cache only last for 12 hours. @arkon 

If you still do not believe in jsDelivr, you can probably try making it an option (a switch). This will be very helpful to users who don't have stable connection to GitHub.

```
all time in UTC

2022-05-13 22:51 repo updated (8282af2)
2022-05-14 06:58 checks jsDelivr, up-to-date

2022-05-14 16:20 repo updated (faa8525)
2022-05-14 16:22 checks jsDelivr, not updated
2022-05-14 16:23 manually purges cache of index.json and rechecks, up-to-date
2022-05-14 16:25 manually purges cache of index.min.json and rechecks, up-to-date
```

By the way, you may also want to fallback this URL (for README and CHANGELOG) to jsDelivr. Probably no need to purge the cache since this is not so important, and after 12 hours of any request the cache will be purged itself.

https://github.com/tachiyomiorg/tachiyomi/blob/f1ab34e27cbd8f26f87e34238af0863d4650b960/app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt#L280

**Comment by kasperskier** [comment]
@arkon Could you please look into this if you have time? Could be as easy to address as redoing 2 commits.

**Comment by arkon** [comment]
The README and CHANGELOG links probably don't matter too much since I expect those to see lower traffic.

I assume GitHub works _sometimes_ and isn't fully blocked, otherwise installing/updating the app itself would've involved other workarounds anyway?

**Comment by kasperskier** [comment]
> I assume GitHub works _sometimes_ and isn't fully blocked, otherwise installing/updating the app itself would've involved other workarounds anyway?

Yes, but rarely, and it depends on network environment. Most time the connection is blocked. Even if you can connect to GitHub, chances are that the connection gets polluted minutes later.

The app itself updates a lot less frequently that the extension list, and you won't see the bad request toast. The Tachiyomi site is accessible so I guess people will eventually get the updates?

**Comment by kasperskier** [comment]
jsDelivr's default CDN domain was polluted (again): https://github.com/jsdelivr/jsdelivr/issues/18397

Replacing `cdn.jsdelivr.net` with `fastly.jsdelivr.net` would work. If it eventually gets polluted too, we should probably drop this fallback method. @arkon
