### ISSUE TITLE
AVIF Manga Covers cannot be decoded

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/tachiyomi#5522]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3571

### Android version

Android 11

### Device

Emulated Pixel 3

### Steps to reproduce

I am working on adding support for all supported image types to be used as covers for the Local Source (#5451).
Thus, reproducing this requires a modified version of tachiyomi, as the latest commit on master doesn't have this feature yet.

To quickly test this in a tachiyomi build you compile yourself:
1. Change the __COVER_NAME__ variable of LocalSource.kt from `cover.jpg`, to `cover.avif`
2. Run the tachiyomi build
3. Create a local manga in the filesystem, and give it an AVIF image as the cover (cover.avif)
4. Launch tachiyomi, go to Local Source.

I've been using this picture of a cow as a test for the AVIF files:
https://darekkay.com/blog/avif-images/cow-avif.avif

### Expected behavior

Since AVIF is a supported image format for Tachiyomi, the cover image for the manga should be that `cover.avif` file

### Actual behavior

The cover is not displayed for manga, and the following is logged into the console (several times):

`24088-24155/eu.kanade.tachiyomi.debug E/HeifDecoderImpl: getSize: not supported!`

### Other details

It's worth noting that AVIF images _do_ work as pages for chapters, so it seems to just be an issue with the system that decodes cover images, but not page images (I assume).

**Comment by arkon** [comment]
We use Coil for loading images outside of the reader, so it's possible that it doesn't handle those formats.

You may have to poke around their codebase/issues to confirm if that's the case first.

**Comment by ivaniskandar** [comment]
AVIF is not supported by Coil https://coil-kt.github.io/coil/getting_started/#supported-image-formats

**Comment by datreesezcup** [comment]
Well heck! That's a bummer.
Thanks for the reminder that the covers use Coil, it completely escaped my memory. I was confused how it could work in one place but not the other.

Well I guess I'll submit my PR for loading other image types as local covers, and perhaps open a feature request issue on the Coil repository to see if this is something they would implement at some point in the future.

Would you like me to close this issue (since it's a dependency issue), or should I leave it open as a sort of note for other users and/or to-do when/if Coil implements AVIF decoding?

**Comment by arkon** [comment]
You could leave it open with a reference to an issue in Coil. This will apply to whatever other formats the decoder supports that Coil doesn't too, like JPEGXL.
