### ISSUE TITLE
Sort by "Date fetched" sometimes fails

### ISSUE THREAD

**Issue by ODBLK** [tachiyomiorg/tachiyomi#5527]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Rewview r3583 & 0.11.1

### Android version

Android 11

### Device

One plus KB2000

### Steps to reproduce

Use filter and choose “Date fetched”

### Expected behavior

Mangas should sorted by update date informs which get from the extensions, form newest to oldest or swap.

### Actual behavior

Most of all are sorted like expect, but some of them has a wrong sort.
Here is a part of mangas
![L8R3W@@EA(BBPRPH5`DQY~I](https://user-images.githubusercontent.com/25927859/125191992-ee2f6080-e277-11eb-9a7e-64d66a0d7ef7.png)

Here is the sort mode
![image](https://user-images.githubusercontent.com/25927859/125192002-fa1b2280-e277-11eb-8d94-e8bc5abb9b11.png)

Here is the update timestamp
3/24/21
![image](https://user-images.githubusercontent.com/25927859/125192009-0e5f1f80-e278-11eb-85e3-55b23f4a599a.png)

5/14/21
![image](https://user-images.githubusercontent.com/25927859/125192023-2040c280-e278-11eb-9613-835df2120d05.png)

But the order of this is wrong
9/7/20
![image](https://user-images.githubusercontent.com/25927859/125192046-46fef900-e278-11eb-8ab0-e0636c2f6ea5.png)

**Comment by paulo27ms** [comment]
Fetch date isn't related to chapter upload date, it's related to when you updated the manga entry and it got new chapters. Are these manga being updated automatically at the same time?
The update tab shows you the date you fetched a chapter, check there and see if the order is correct or not.

**Comment by ODBLK** [comment]
I misunderstood the function. Could I ask for a new sorting method based on the chapter upload date?

**Comment by paulo27ms** [comment]
That's what "latest chapter" does already.

**Comment by ODBLK** [comment]
Got it, before I thought the latest chapter is based on the number of
chapters. Sorry for taking your time.

paulo27ms ***@***.***> 于2021年7月12日周一 下午6:21写道：
