### ISSUE TITLE
[BUG] Reading mode changes after setting default chapter sorting

### ISSUE THREAD

**Issue by Presac** [tachiyomiorg/tachiyomi#5529]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

App version: 0.11.1-3571 (standard, d9ea621e, 65, 2021-07-08T13:14Z)

### Android version

7.1.2 - LineageOS 14.1

### Device

Samsung galaxy note 10.1

### Steps to reproduce

1. Set sort by chapter
2. Press "Set as default"
![Screenshot_20210711-145440](https://user-images.githubusercontent.com/10221581/125196635-e57c6180-e25a-11eb-8d7c-5aff29ada043.png)

### Expected behavior

Just the chapter sorting should change. 

### Actual behavior

The chapter sorting has changed as it should, but every single manga across every source and category has had its reading mode changed to webtoon. 
![Screenshot_20210711-145515](https://user-images.githubusercontent.com/10221581/125196755-499f2580-e25b-11eb-9eb0-2f97b43c46d0.png)
![Screenshot_20210711-145541](https://user-images.githubusercontent.com/10221581/125196761-4d32ac80-e25b-11eb-84f7-edb9bb351a9a.png)

### Other details

Subsequent presses on "Set as default" makes the unwanted change to all manga again.

**Comment by arkon** [comment]
Probably fixed by 8931dbb657cfd243a48e537b25d2a8b782a6a982

**Comment by Presac** [comment]
I'll wait and see then.
But are there a way to change every manga back to default reading mode again?

**Comment by arkon** [comment]
You could try setting one manga to the default reading mode and applying that manga's settings as the default.

**Comment by Presac** [comment]
Where do I do that? Won't I just repeat the same steps described in the post?

**Comment by arkon** [comment]
I was under the impression that your entry had Webtoon set or something?

**Comment by Presac** [comment]
The manga originally had the default reading mode set. But using the "Set as default" in the first image changes it to webtoon for some reason.

**Comment by Presac** [comment]
I just discovered something. Any new manga I add have the webtoon reading mode instead of default.
