### ISSUE TITLE
add menu button when reading

### ISSUE THREAD

**Issue by cyb233** [tachiyomiorg/tachiyomi#5531]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

add a menu button at setting when reading comic

like this
![Screenshot_2021_0712_075938](https://user-images.githubusercontent.com/39186981/125213952-21f59f00-e2e7-11eb-8045-4f74cdc170fb.gif)
I want change chapter without return comic info

**Comment by arkon** [comment]
Sorry, can you try explaining more?

**Comment by cyb233** [comment]
> Sorry, can you try explaining more?

updated

**Comment by arkon** [comment]
This was rejected before. Having the list duplicated in the reader isn't any better than just going back to the full list.
