### ISSUE TITLE
Nothing happen when I click on buttons in the notifications

### ISSUE THREAD

**Issue by SkyNalix** [tachiyomiorg/tachiyomi#5541]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.0

### Device

Huawei GR5 2017

### Steps to reproduce

1. Download any image from any manga you want
2. click on the buttons 'share' or 'delete'

### Expected behavior

Actually do the action it's supposed to, 'share' -> share the image, and 'delete' -> delete the image

### Actual behavior

Nothing happen, the notification is still here, but the buttons don't work at all

### Other details
It don't only happen with a downloaded image, if i try to download some chapters, i can't click on 'pause'. It's like none of the buttons from the app work

**Comment by arkon** [comment]
Can't reproduce. Seems like a Huawei issue.
