### ISSUE TITLE
Make swipe right,left: next page and up,down: previous page

### ISSUE THREAD

**Issue by wa15** [tachiyomiorg/tachiyomi#5547]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

You can be on auto pilot with the vertical and continuous vertical but it isnt the same for left and right swiping. 
For the vertical styles, the swiping motions are the same no matter which hand you use and the up>down "direction" is universal.
For swiping, the motions are mirrored if you switch hands, and the left>right directions vary depending on type of text you read. 
So to make it easier to turn pages on auto pilot, make swiping left or right turn to the next page and swiping up or down turn to the previous page.
I think this is an improvement for the left+right swiping since it would be like a swiping version of the edge layout(tapping).

**Comment by arkon** [comment]
Sorry, but this is a pretty obscure request and seems pretty unintuitive.
