### ISSUE TITLE
extension uninstall button unreadable on yin & yang theme

### ISSUE THREAD

**Issue by svetchkill** [tachiyomiorg/tachiyomi#5548]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

preview r3583

### Android version

android 10

### Device

samsung s9+

### Steps to reproduce

1. Set theme to yin & yang
2. Enable/disable pure dark mode
3. Open extensions settings

### Expected behavior

Readable uninstall button

### Actual behavior

Pure dark mode ON:
![20210714_171704](https://user-images.githubusercontent.com/74079735/125606681-350b1e02-e9f5-4548-bba6-7ec701af9600.jpg)

Pure dark mode OFF:
![20210714_171721](https://user-images.githubusercontent.com/74079735/125606713-d36f182e-4ac1-4e5d-a8c9-b3a2f72c1124.jpg)

**Comment by Riztard** [comment]
fixed in #5535
