### ISSUE TITLE
مانغا ليك: when I open a chapter , he close and tell that no page fond.

### ISSUE THREAD

**Issue by ahmedben19** [tachiyomiorg/tachiyomi#5549]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7

### Device

Iris next P+

### Steps to reproduce

Open any chapter then he close and tell that no page fond

### Expected behavior

The chapter close automatically

### Actual behavior

The chapter must open normaly

### Crash logs

Aucun page fond

**Comment by paulo27ms** [comment]
If this is related to a single source the open the issue at https://github.com/tachiyomiorg/tachiyomi-extensions otherwise this is severely lacking in into, it's possible to know what the issue is.
