### ISSUE TITLE
Downloaded chapters unrecognized after transferring download path.

### ISSUE THREAD

**Issue by disori99** [tachiyomiorg/tachiyomi#5552]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Vivo Y15

### Steps to reproduce

1. Transfer downloads folder from ROM to SD Card
2. Change download directory to said SD Card

### Expected behavior

Downloaded chapters of each series should be recognized as downloaded.

### Actual behavior

It doesn't recognize them as such, instead as something not currently downloaded.

### Other details

Chapters could be viewed offline, but for some reason they are still recognized as not downloaded.

**Comment by loocool2** [comment]
- Did you restart the app after you changed the downloads directory
- Did you try downloading a new chapter after moving the downloads directory to make sure it's 100% correct

**Comment by disori99** [comment]
It seems that was the problem, thank you.
