### ISSUE TITLE
Library loading not smooth if "per-category display/sorting" enable

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5557]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3598

### Android version

Android 10

### Device

Mi9T

### Steps to reproduce

1. Open a manga in your library
2. Close it

### Expected behavior

Library loading should be smooth

### Actual behavior

Library loading is clunky

### Other details

Full video: https://streamable.com/8hpknp

Been using this feature for a while and never really noticed this but after updating to latest preview today (r3583 > r3598) it became noticeable. Attempted to install older preview versions and still happening so maybe I just wasn't really noticing it somehow.

**Comment by arkon** [comment]
This should be better nowadays after some of the work that @ghostbear did.
