### ISSUE TITLE
Copy from link and Paste with extra blanks at the end

### ISSUE THREAD

**Issue by dayfundora** [tachiyomiorg/tachiyomi#5559]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Device

Galaxy A50

### Steps to reproduce

1. Copy a text from a link in a browser
![photo_2021-07-15_17-25-52](https://user-images.githubusercontent.com/51751279/125860075-388fcf51-3fd4-443f-ba1d-f5e6bb9147cf.jpg)
2. Past in Tachiyomi "Search..."
![photo_2021-07-15_17-26-00](https://user-images.githubusercontent.com/51751279/125860312-659ef9e9-95b5-4160-88a4-d4808d8b6644.jpg)

### Expected behavior

As the selected text was "Solo leveling", what is expected to happen when you paste the copied text in the apk search engine is that only "Solo leveling" text will appear.

### Actual behavior

What really happens when I paste the text copied from a link to the search engine, is that 2 blank spaces are added at the end of the text.
![photo_2021-07-15_17-25-48](https://user-images.githubusercontent.com/51751279/125860785-2769bdfd-ae6f-47f3-a154-4b83dc5a4124.jpg)

### Other details

1. I already checked in other apks like notepad and others for texting and the same copied text is pasted without extra spaces.
2. This only happens with text copied from a link in a browser, if it is not from a link and it is just plain text, it is copied well.

**Comment by paulo27ms** [comment]
Can't reproduce yours but when trying to share text with a link to Tachiyomi's global search this happens for me: 
![Screenshot_2021-07-16-01-57-05-414_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/13546823/125875941-93dd78ff-7d68-433f-804b-29f9579c3594.jpg)

It's a bit odd because first time I tried this didn't happen, it only searched for the text but then I press back on the search and it sent me to another search with the text + the link, on the next tries it went directly to just text + link search

**Comment by arkon** [comment]
I tried the same steps and got the same results.

However, I also tried pasting into another text field (new category name), and it resulted in newlines being pasted in as well.

Whatever you're copying seems to have more formatting than you think.
