### ISSUE TITLE
Forced Grayscale

### ISSUE THREAD

**Issue by hendycandy** [tachiyomiorg/tachiyomi#5561]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.A715WVLU3CUF1 Device brand: samsung Device manufacturer: samsung Device name: a71 Device model: SM-A715W Device product name: a71cs

### Android version

Android 11

### Device

Galaxy A71

### Steps to reproduce

All the colored Webtoon turned to grayscale mode.

There is no setting for it. 

It changed right after the update. 

I checked all my webtoons.

### Expected behavior

Previously colored webtoons shouldn't be in grayscale mode or should have an option to turn it on or off

### Actual behavior

Everything is in black and white

### Other details

Ive searched everywhere and i cant find a solution

**Comment by paulo27ms** [comment]
Reader settings. It's a global setting.
![Screenshot_2021-07-16-05-35-22-947_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/13546823/125892405-be7e7809-78d6-4cc5-968e-4ad745784360.jpg)

**Comment by hendycandy** [comment]
Omg, i feel so stupid.

Thank you!!!!!!
