### ISSUE TITLE
Dialog buttons are missing when content is too tall

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#5562]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3598

### Android version

6.0

### Device

LAVA iris 820

### Steps to reproduce

More -> Settings -> Libary. Then try to edit the categories in global update.

### Expected behavior

A pop-up with OK and cancel button should appear.

### Actual behavior

7 Categories (Fine):
![Screenshot_2021-07-17-20-51-13-57_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/59261191/126040778-5e27794f-fd0f-4225-bc1f-017dd4d461cc.jpg)

8 Categories (Button half missing but works):
![Screenshot_2021-07-17-20-50-53-65_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/59261191/126040828-6024d9dd-7990-4df9-ad0d-5662925f0131.jpg)

9+ Categories (Button Missing):
![Screenshot_2021-07-17-20-50-36-06_79aa9bf7c61e266c5f841e42245e214b](https://user-images.githubusercontent.com/59261191/126040844-5345ba31-b0bc-4dac-b599-fa04b5ef1b9e.jpg)

### Other details

Even the color scheme is kinda messed up.

**Comment by arkon** [comment]
https://github.com/material-components/material-components-android/issues/1974
