### ISSUE TITLE
Download hidden chapters

### ISSUE THREAD

**Issue by zeredouni** [tachiyomiorg/tachiyomi#5566]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Some hidden chapters do not appear on the app .
Can you add a way to download them from the browser (webview) ?

**For example**
https://ibb.co/sWhZfxm

**Comment by arkon** [comment]
Report it in the extensions repo if a chapter isn't showing up.
