### ISSUE TITLE
Title bar stays

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5572]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3606

### Android version

Android 11

### Device

SM-A015F

### Steps to reproduce
1. Change the dark mode to anything but make sure to change it else you can't reproduce the bug.
1. Open a manga
2. Scroll down the chapter list

### Expected behavior

The title bar that says the manga name should disappear and only visible when scrolling back up.

### Actual behavior

Instead it is permanently visible no matter what and overlaps with text at the top of the phone.

### Other details

Here is a screenshot of it:

![Screenshot_20210718-171330_Tachiyomi](https://user-images.githubusercontent.com/76571965/126072860-355e54cd-b56e-45d2-854c-79f73c70be5c.jpg)

**Comment by zayin02** [comment]
It looks like it is a new bug that developed after preview r3606.

**Comment by zayin02** [comment]
Looks like it is also in the settings 

![Screenshot_20210718-173433_Tachiyomi](https://user-images.githubusercontent.com/76571965/126073195-4c9fae27-0314-4b82-aa79-a608e0434457.jpg)

**Comment by ivaniskandar** [comment]
Yep can replicate this, for now just restart the app after changing theme.
