### ISSUE TITLE
Bug mangahasu Unexpected JSON offset 0

### ISSUE THREAD

**Issue by JermanyWilhelm** [tachiyomiorg/tachiyomi#5577]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Device

Google Pixel 5

### Steps to reproduce

I tried fixing this issue by searching json offset, but it said that you need to go to web browser and wait for captcha, but it doesn't show any captcha so I thought it was fixed already

### Expected behavior

I thought it was fixed when going to web browser but it doesn't show any captcha because I always check if there will be a captcha 

### Actual behavior

It doesn't work and when I'm resuming my download in mangahasu extension it always say Unexpected JSON offset 0. I already reinstall tachiyomi and clear cache. It's almost 2 days since this issue and I thought I'm the one who have this issue

**Comment by arkon** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by JermanyWilhelm** [comment]
Oh ok Thanks mate 😊
Sorry for disturbance
