### ISSUE TITLE
setting tracking dates is one day off

### ISSUE THREAD

**Issue by ebarruel** [tachiyomiorg/tachiyomi#5579]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3606

### Android version

Android 11

### Device

OnePlus 7 Pro

### Steps to reproduce

1. Add tracking to manga
2. Set start/finish date

### Expected behavior

The start or finish date should be the day that the user selected.

### Actual behavior

The date set is the day before what was chosen, and it does not matter whether the date was chosen with the calendar or typed in.

### Other details

I only have MAL and AniList so I'm not sure if this applies to other trackers, but I have confirmed it for both.

**Comment by arkon** [comment]
What timezone are you in?

**Comment by ebarruel** [comment]
utc-7
