### ISSUE TITLE
Global search does not pass a source's filter list

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi#5583]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

N/A

### Android version

N/A

### Device

N/A

### Steps to reproduce

Set MangaDex default content ratings, and then global search for a manga that would fit that content rating

### Expected behavior

manga would show because the content rating defaults are being passed

### Actual behavior

manga does not show because by default it seems global search is only sending the text and not the sources filterList

**Comment by CVIUS** [comment]
Relevant commit https://github.com/Jays2Kings/tachiyomiJ2K/commit/45fbd9d2f5eba03f0734a58ad46de16a047ae783
