### ISSUE TITLE
Default filters for a source are not honored after the initial loading

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi#5584]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

N/A

### Android version

N/A

### Device

N/A

### Steps to reproduce

set default values for MangaDex content rating, for example only enable pornographic. click into MangaDex source, search for something would only be found with that content rating.  

### Expected behavior

filterList parameters are being passed on to subsequent request and only results that are pornographic show

### Actual behavior

filterList parameters are NOT being passed on to subsequent request and results default to MangaDex default results

### Other details

Commit from j2k that should be relevant, I haven't seen any issues reported by switching to this way of doing.

https://github.com/Jays2Kings/tachiyomiJ2K/commit/ff82157da46af1737a65fc940c6a91f42b3aaadc

**Comment by Arraiment** [comment]
What do you think about removing the `allDefault` implementation here?

https://github.com/tachiyomiorg/tachiyomi/blob/b650151693ff74973105772b0794ceab3841ac93/app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt#L147-L150
