### ISSUE TITLE
Button to open manga folder with file explorer

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5585]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Button on the manga (can be in the 3 dot menu) to open the folder for the respective manga with a file explorer.

### Other details

This would just make it easier to delete chapters you can't see because they got deleted or their name changed and the folders didn't update correctly or whatever.

**Comment by arkon** [comment]
As far as I'm aware, you can't just open a file explorer like that unless it's for actually selecting a file.

Also wouldn't work if you use an app data folder and you have a file explorer app that doesn't allow browsing those in Android 11+.
