### ISSUE TITLE
Add setting for/revert automatically setting reading status on trackers

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5588]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

This is about this commit https://github.com/tachiyomiorg/tachiyomi/commit/c0647c311002e66c54c3f85d1d075cd216124c86

It's extremely intrusive how it's changing the status on the tracker by itself without any setting to turn it off.

I can give you my example, I keep my on hold list for stuff that takes really long to receive updates to not pollute the reading list but now I gotta manually change the status each time I read a chapter.

The change on how it sets the first status when you add a manga is alright (although in my view it's also unnecessary, the user can do that themselves extremely easily), but continuously changing the status without your input is not.

**Comment by paulo27ms** [comment]
Also, original issue the commit addressed (https://github.com/tachiyomiorg/tachiyomi/issues/200) mentioned when changing from Plan to Read only and not other status, this would be fine too.

**Comment by paulo27ms** [comment]
It's an odd comparison as this wasn't exactly a bug fix, it'd be more like removing the setting to automatically update the chapters on the tracker because why do we actually need it? If someone added a tracker for something surely they must want real time syncing but the option is there to have it off because some people don't see it from that perspective (surely there must be that one guy who still has it off).

I'm seeing this more on the level of automatically marking chapters as read on Tachiyomi because you have them as read on the tracker or automatically adjusting the tracker chapters based on what you mark as read or already had read on Tachiyomi.
All things that make sense and can be useful but having default behaviors like this seems way too intrusive for syncing automatically with external services if there's no user control at all.

Not just arguing for this case but for future enhancements as well, generally a more conservative approach will be better.

**Comment by arkon** [comment]
I'm fine with gating all of the logic behind the existing setting and renaming it.

**Comment by paulo27ms** [comment]
Technically it's already like that, doesn't seem like the status changes automatically if it's disabled.
Ideally you'd have a setting for just the chapters and a setting for any automatic logic you want to add in the future (start/end dates, marking as completed, etc) as well as the current.

**Comment by arkon** [comment]
It's a simple choice: you either opt into a managed tracking experience or you have full manual control over it.
