### ISSUE TITLE
Inicio de sesion 

### ISSUE THREAD

**Issue by kevindark15** [tachiyomiorg/tachiyomi#5592]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Creo q agregando un inicio de sesion en la app serviria bastante ya q digamos ytiene un cel con bastantes mangas agregados a la biblioteca y te vas a cambiar a otro cel y debes poner todo e nuevo creo q seria aburrido eso

**Comment by loocool2** [comment]
A login will never be added to the app as we do not want to maintain any type of centralized server to store data, nor do we want the liability of user data and passwords. Use the backup and restore feature that is already in the app instead https://tachiyomi.org/help/guides/backups/
