### ISSUE TITLE
Source name truncated in info view

### ISSUE THREAD

**Issue by lucasjsoliveira** [tachiyomiorg/tachiyomi#5594]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

8.1

### Device

Xiaomi mi pad 4

### Steps to reproduce

The source name gets truncated in the manga info view (probably because of the longer status in PT-BR), making it necessary to touch it to see what the source is. Here's a example:
![Screenshot_2021-07-21-08-50-40-372_eu kanade tachiyomi](https://user-images.githubusercontent.com/9120016/126486493-d9eba335-3392-4801-abd1-9ff5212e1d35.png)
Probably a good idea to place it in a new line below the current status?

### Expected behavior

The full name of the source should be displayed in the details screen

### Actual behavior

Source name gets truncated if the current status is too long

**Comment by arkon** [comment]
Should no longer be relevant with changes in 0.12.0
