### ISSUE TITLE
Problem with extra pages referring to advertisements

### ISSUE THREAD

**Issue by nichols013** [tachiyomiorg/tachiyomi#5596]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

Android 10 (MIUI 12.0.10)

### Device

Poco X3

### Steps to reproduce

1. Open any manga that has an ad on the site of the original source while reading the chapter. (I will use as an example the Mangá Livre source and the One Punch Man manga, chapter 2, but I identified the error in several other sources and mangas)
2. Wait for loading.

### Expected behavior

After loading, it should start reading normally, and at the time of downloading all pages should be downloaded without any major problems.

### Actual behavior

What happens is that after the load, there is a spare page (if the chapter has 17 pages, 18 are listed) that is unavailable and displays a "Try Again" message; and at the time of download this same spare page is not downloaded, obstructing all content to be read offline.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6859576/tachiyomi_crash_logs.txt)

### Other details

I have already considered the possibility that it is a problem influenced by individual factors; however I already switched network, application and even cell phone and the problem ended up persisting.

**Comment by Riztard** [comment]
wrong repository, read your Acknowledgements

**Comment by alessandrojean** [comment]
Also, this source it's known for hosting broken images in the beginning and middle of the chapter. If you open the chapter you provided as an example in WebView you will see that some pages isn't loading there too, so it's not the extension fault.
