### ISSUE TITLE
Seperate "Per-category settings for sort and display" setting in two.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#5597]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

There should be dedicated setting for Per-category sort and display so people can enable one while disabling other.

**Comment by paulo27ms** [comment]
What's the advantage? You can just leave one with the default setting you want.
If this is about the performance issues maybe it's best those are addressed without workarounds: https://github.com/tachiyomiorg/tachiyomi/issues/5557

**Comment by arkon** [comment]
Agreed, just leave it as default if needed. The UI/UX needs to be improved in the future though.
