### ISSUE TITLE
Add MangaPark like source filter to MangaDex

### ISSUE THREAD

**Issue by csm-hm** [tachiyomiorg/tachiyomi#5599]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

When a Manga has more than one Scan group, there are times when reading you don't want to reread a chapter. While a filter would be a nice option, sometimes, when two groups are scanlating the same chapters, one group may miss a chapter, and if you filtered them out, you would miss the chapter making you clear the filter, read the chapter, and then reenable the filter. So, instead of a filter, why not add something MangaPark has for sources, the 'smart list,' (or something similar) but for chapters this way, you get every chapter and no duplicates.  ![Screenshot_20210722-121635](https://user-images.githubusercontent.com/59417659/126677660-e3d20535-ff1c-4037-88b1-00055e3981f2.jpeg)

**Comment by CarlosEsco** [comment]
No

**Comment by CarlosEsco** [comment]
mangapark has as you see 5 options of scanlator.  Mangadex has 100s.

**Comment by csm-hm** [comment]
I wasn't saying add all the Scan groups to the list; that'd be obsured. But can't the smart list be done simply?

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/969
