### ISSUE TITLE
List of Suggestions

### ISSUE THREAD

**Issue by rlawliett** [tachiyomiorg/tachiyomi#5600]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

SUGGESTIONS:
1. Merge duplicate titles on list of manga (Section: BROWSE-->MIGRATE, better new tab: MERGE)
-keep the ones with updated or more chapters.

2. Rename manga title (Section: LIBRARY)
-remove "manga" "manhua" on title on some library especially on some source like wuxia

3. Show in library the available category  (Section: LIBRARY)
eg. shounen, shoujo, sekai, manhua, manga, webtoon, martial arts

4. Show current number of chapters available on that title besideit (Section: LIBRARY)
-Add Option on Library--> List Icon--> Display--> Badges
eg.:
Solo Leveling    3/151
        Unread Chapters/Available Chapters
        Colored in Red/ Colored in Red

5. Change language on Titles (Section: LIBRARY)
-this will be helpful on titles with chinese names or japanese names

6. Choose on List of Source on where to search for title to migrate (Section: MIGRATE)
eg.:
Solo Leveling
Original Source: IsekaiScan
Available Source: Mangadex, Mangato, WebtoonXYZ
Only search on Mangadex on where to Migrate

7. Migrate Whole Source to another (Section: MIGRATE)
eg.:
All Library from Isekaiscan to Mangadex instead on all sources

8. Category on Extension  (Section: EXTENSION)
A. 18+ (BugHent**, DDHent**)
B. Manga (Mangadex)
C. Manhua (Mangadex, WebtoonXYZ)
D. Webtoon (WebtoonXYZ)
E. Comics (ReadComicOnline)
F. Non-Aggregate Source (1stKiss, Flame Scans, GalaxyDegenScans)

9. Back-Up Options (Section: MORE-->BACKUP AND RESTORE)
A. Library
B. Settings
C. Extensions
D. All

10. Most Read Titles with Badge on Top of Update Section (Section: UPDATES)
-Pin Favorite Titles Below the List
-Can be Modified on Library Section --> New Tab as follows: Titles, Category, Pinned
-Limit of 5 to Pin
(Category section is from suggestion Number 3)
How to Execute: Put the Icon of Manga/Comics/Manhua Below the Header

<Updates>___________________________<Refresh>
<Manga 1><Manga 2><Manga 3><Manga 4><Manga 5>

**Comment by arkon** [comment]
1 issue per request. Please also check if it's been previously requested.
