### ISSUE TITLE
Arranging downloads

### ISSUE THREAD

**Issue by Allabsolute** [tachiyomiorg/tachiyomi#5601]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

We need select button on download queue to be able to move certain chapters up or down

**Comment by curche** [comment]
You can already do that...
There is a button on left-end of a chapter in download queue which you can click and drag

**Comment by Riztard** [comment]
<img src="https://cdn.discordapp.com/attachments/825346400953827349/868103310446592040/Clipboarder.2021.07.23_50.png">
