### ISSUE TITLE
Page loading icon is much worse in most recent preview release

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#5604]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631

### Android version

9.0

### Device

Fire HD 10

### Steps to reproduce

Go to a a manga and skip forward like 10 pages

### Expected behavior

A smooth progress ring should appear, slowly completing the circle until your page is loaded

### Actual behavior

Just a black screen, followed by the brief appearance of a loading ring that quickly disappears again, and the finally the page loads

### Other details

With the old way, it was easy to tell how much your page had loaded, and how much was left. This new way is essentially useless as a progress indicator.

**Comment by specterflare** [comment]
Old:
https://user-images.githubusercontent.com/61708534/126887049-d725312a-5964-4166-873d-07da8e77e925.mp4

New:
https://user-images.githubusercontent.com/61708534/126887055-f954dbf2-023f-451f-86cd-f4c2357f18b0.mp4

The old way was SO much better.

**Comment by arkon** [comment]
Constructive feedback is always welcome, but I'm going to lock this since the wording is coming across as too aggressive. Apologies if I'm interpreting it wrong.
