### ISSUE TITLE
Group "Unable to resolve host" & "Unable to connect" error in Update Error.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#5609]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The two mentioned error gives different error for each source so umm group them. Here's a example file for current output.
[tachiyomi_update_errors.txt](https://github.com/tachiyomiorg/tachiyomi/files/6875276/tachiyomi_update_errors.txt)

**Comment by arkon** [comment]
The exceptions come from the underlying networking stack, so I'd rather not try to group them or "translate" them since they can change in the future.
