### ISSUE TITLE
[Bug] The resume button always takes you to the 1st chapter and not on the current chapter

### ISSUE THREAD

**Issue by LuciferSenpaii** [tachiyomiorg/tachiyomi#5615]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Samsung Galaxy A30

### Steps to reproduce

1. Open a chapter other than the 1st
2. Go back 
3. Click resume button

### Expected behavior

The chapter which was previously open should be the one showing after clicking the resume button instead of the 1st chapter

### Actual behavior

Shows the 1st chapter always

**Comment by arkon** [comment]
#1399
