### ISSUE TITLE
Long titles get cut off

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi#5617]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Lately there has been an emergence of manga based on light/visual novels with absurdly long names. Sometimes, these names do not fully "fit" in the designated area given to them. I created this issue as an enquiry into this matter to see if anything could be done about it.

![IMG_20210727_194844](https://user-images.githubusercontent.com/28984045/127171615-06ead7ec-32a0-4fae-80da-9576184b4d48.jpg)

In this case, the name "*It's Fun Having a 300,000 yen a Month Job Welcoming Home an Onee-san Who Doesn't Find Meaning in a Job That Pays Her 500,000 yen a Month*" is not fully visible in the name area/segment. The upper portion is simply cut off with no way to view it, (unless you copy the name by tapping-and-holding and paste it somewhere else, like I did here).

Could anything be done to make it completely viewable? Maybe entries whose names cross a certain word limit have their font size decreased, or maybe the name area itself is made scrollable?

**Comment by Soitora** [comment]
Fixed by #5796
