### ISSUE TITLE
GIFs play at 400% speed

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#5619]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631

### Android version

9.0

### Device

Fire HD 10

### Steps to reproduce

1. Go to a page that is a GIF, such as [the last page of Chapter 1 of Isekai de Kojiin wo Hiraitakedo, nazeka Darehitori Sudatou to Shinai Ken](https://mangadex.org/chapter/7d1db8a6-e5a0-42f9-a97a-8de0b92b02d9/17)
2. Observe

### Expected behavior

The GIF should play at normal speed, which it does in the browser or in Webview

### Actual behavior

The GIF plays at, what my best guess is based on artificially speeding up the browser GIF, 400% speed.

### Crash logs

N/A

### Other details

N/A

**Comment by arkon** [comment]
Probably a Coil issue, but would have to confirm outside of Tachiyomi to make sure.

**Comment by specterflare** [comment]
Yup, a little googling and I found coil-kt/coil#540.

To;dr:
“This fix will be included in the next release of the library in a few weeks (though disabled by default to let it incubate).” Posted on June 21st.

**Comment by arkon** [comment]
We'll pick up Coil updates as they release, so I'll close this since there's nothing actionable right now.
