### ISSUE TITLE
Allow user to share manga list?

### ISSUE THREAD

**Issue by proxll** [tachiyomiorg/tachiyomi#5623]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

it should work by creating a list of series that is currently bookmarked by the user, instead of screenshotting or creating backup which would create an overlap

and when another user open said list, it shows them series that they don't have and the extension which they need to install

**Comment by arkon** [comment]
No plans to do so, but somebody could easily build a tool that works based on the Tachiyomi backup files.
