### ISSUE TITLE
Anilist logo is bugged in Tracker Settings when using Light theme

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#5625]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631, Sy Preview r400

### Android version

Android 11 (LOS)

### Device

Redmi 5 (onclite)

### Steps to reproduce

1. Check the Anilist logo at More > Settings > Tracker
2. Check the Anilist logo for a manga in your library

### Expected behavior

Logo should be like the standard Anilist logo that we know and are used to

### Actual behavior

Logo seems to look bugged. Possibly because of the "white A" on a white background
![Screenshot_20210729-234025_Android_System_tracking](https://user-images.githubusercontent.com/72807749/127544238-9fc765e7-0d4b-40b5-8017-2bf9a444148c.png)

### Other details

Perhaps it might be a nice idea to reuse whatever logo is being used in the Tracking sheet inside Manga (i.e. the one shown below). Could do something similar for other Logos as well (like MAL).

![Screenshot_20210729-234049_Tachiyomi_tracking](https://user-images.githubusercontent.com/72807749/127544357-79053800-6239-4e61-9026-f7b68537d4d9.png)

**Comment by arkon** [comment]
Yeah, the tracking UI isn't finalized.
