### ISSUE TITLE
Using scoped storage

### ISSUE THREAD

**Issue by tiklii** [tachiyomiorg/tachiyomi#5627]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Tachiyomi can use scoped storage instead of legacy storage permission to access local files. It will improve user privacy.

https://developer.android.com/training/data-storage#scoped-storage

**Comment by loocool2** [comment]
This would break downloads, local storage, and increase the already slow loading times in the app. Not worth it to implement right now in my opinion unless google forces our hand

**Comment by arkon** [comment]
We're aware that we'll need to make changes for future Android versions, so I'll close this.
