### ISSUE TITLE
Add a Go To Page option in the reader

### ISSUE THREAD

**Issue by jdoxley** [tachiyomiorg/tachiyomi#5629]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Add a button in the reader that allows you to enter a page number and have the reader navigate to that page.

**Comment by CarlosEsco** [comment]
There is a seek bar, why would you need this?

**Comment by Riztard** [comment]
> There is a seek bar, why would you need this?

maybe useful for 100+ pages

**Comment by CarlosEsco** [comment]
> 
> 
> > There is a seek bar, why would you need this?
> 
> maybe useful for 100+ pages

so you slide it?  Doesn't change, adding a button go to a page just clutters the ui more, when the seek bar does almost the same thing

**Comment by vengiare** [comment]
I tried the seekbar in a 500-page entry in nh (cause nh has number of pages filter) and going to a specific page number wasn't even that difficult actually. I'd argue it's even faster than typing.
