### ISSUE TITLE
Navbar improved behavior 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5631]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

If you scroll down the chapter list the navbar disappears, and scrolling up makes it appear but this can be improved. 

Currently the navbar can be put in a cut-out position so forcing it to either appear and disappear is more useful and seems less buggy.
 

A very good example would be the Google apps like play store.

### Other details

I wasn't sure if this should be labeled as a bug since it's not really one.

Here is the cut-out:
![Screenshot_20210730-181110_Tachiyomi](https://user-images.githubusercontent.com/76571965/127681649-b124e7ee-6bbf-440c-a10a-030f1815f153.jpg)

**Comment by zayin02** [comment]
Maybe if more then 50% of the navbar is visible it should appear in full, if less it should disappear

**Comment by ivaniskandar** [comment]
FYI the app bar snap behavior is broken upstream so it's currently disabled https://github.com/tachiyomiorg/tachiyomi/pull/4845#issuecomment-820164041

**Comment by zayin02** [comment]
So I should close the issue?

**Comment by arkon** [comment]
Yeah, I'll close this for now. We'll address it if it gets fixed upstream.
