### ISSUE TITLE
A wild Tracking Sheet appears!

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#5635]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3631, Sy Preview r400

### Android version

Android 11 (LOS)

### Device

Redmi 5 (onclite)

### Steps to reproduce

1. Enable a source that has deeplink feature (i.e. link open in Browser can be used to directly view it in App)
2. Enable tracking and add tracking to one of your manga
3. Open the Tracking Sheet and then switch to Home screen (you can maybe switch to another app as well; just that tachi shud move to Recents **with** the Tracking Sheet active)
4. Open one of the supported deeplink from your browser to the app

### Expected behavior

Without any side-effects, app should search the source for the manga whose deeplink was clicked on

### Actual behavior

A wild tracking sheet appears!

### Other details

- if you're not able to reproduce this in first try, maybe try once more. 
- wasn't able to reproduce this in 0.11.1

**Comment by FourTOne5** [comment]
This can be reproduced in a different manner.

1. Start a download.
2. Open tracking sheet of a manga.
3. Click the downloading notification.

![Screenshot_20210731-232315](https://user-images.githubusercontent.com/59261191/127747746-07b294a4-a7c9-4830-b945-dd353b6c0f26.png)

**Comment by curche** [comment]
FYI, since this has been a while and a major ComposeUI rewrite is going on, the issue is still present in 0.13.6, r4963, Sy Preview r481
