### ISSUE TITLE
Interact-able downloaded only banner

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi#5637]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

## Details
Turn off Downloaded Only (or Incognito mode for that matter) when pressing or tap and holding on the banner

### Other details

N/a

**Comment by paulo27ms** [comment]
Downloaded only mode never made much sense. Why this specific filter type gets an entire mode for itself when other filters don't?

**Comment by CarlosEsco** [comment]
Because this filter is similar to airplane mode
