### ISSUE TITLE
Download queue stuck after 5th source

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5639]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3644

### Android version

A10

### Device

Redmi 8

### Steps to reproduce

1. download manga from 6 sources or more

### Expected behavior

6th source or more continue download 

### Actual behavior

6th source or more stuck even after all previous download completed

### Other details

need to pause then resume again to continue
<table>
<tr>
	<td>
	<td>
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/871255826210357268/Screenshot_2021-08-01-11-22-56-033_eu.kanade.tachiyomi.debug.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/871251794066554900/Screenshot_2021-08-01-11-27-19-143_eu.kanade.tachiyomi.debug.jpg">
</table>

**Comment by arkon** [comment]
I think this is ultimately related to #7258; we just need to rewrite the downloader at some point.
