### ISSUE TITLE
Problems in Reader and Chapter View 

### ISSUE THREAD

**Issue by Buckteethmomu09** [tachiyomiorg/tachiyomi#5642]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 8

### Device

Huawei Honor 8 lite

### Steps to reproduce

Issue 1: Comes up after reading a while
Issue 2: When opening a chapter in middle Or continuing where i left off. 

### Expected behavior

Problems on current Stable version. Some comics have
black Stripe Below after reading it a while. I Noticed that when you zoom
it out it goes out by itself.
Also when i view a comic chapter in the middle (not start) . It says
there's no previous chapter. And can't go back no matter what you do unless
you quit the chapter and manually open it.

### Actual behavior

Idk how to do dis, sorry

**Comment by arkon** [comment]
1 issue per problem please, and search for similar issues first.
