### ISSUE TITLE
Cache removal on exit 

### ISSUE THREAD

**Issue by egscodes** [tachiyomiorg/tachiyomi#5651]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

In the advanced settings one can see the clear chapter cache. The question is can their be a toggle that on exit to automatically clear it? (The same as MangaDLR)

**Comment by arkon** [comment]
There isn't a reliable way to detect arbitrary app closure (e.g. swiping it away from recents), so the best that we can do is when you back out from the main app view (i.e. not the reader).
