### ISSUE TITLE
Solution for improving download speed

### ISSUE THREAD

**Issue by piratelord69** [tachiyomiorg/tachiyomi#5652]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Every one using tachiyomi knows about the download speed and multiple download issue.
Fix 1 - I think it could be fixed by using different sources for alternative chapters.
Fix 2 - And there should be a way to balance different sources  like if someone has majority of manga from a particular source it will take time to download when they update but if they can balance it among other sources they use, it would increase the speed of download. 
I use fix 2 myself but I have to balance them manually but if it's built in to the search option, it would be great.

**Comment by CarlosEsco** [comment]
Fix 1 sounds like merged manga which there is an existing issue for.

Fix 2 is completely unrelated to the app and is on the user to do
