### ISSUE TITLE
Toomics插件问题

### ISSUE THREAD

**Issue by 64944646** [tachiyomiorg/tachiyomi#5653]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

小米9

### Steps to reproduce

第一部
进去toomics
第二部
观看漫画，
少章节

### Expected behavior

比如说章节出到20他却只显示到2。

### Actual behavior

缺少章节显示
![Uploading IMG_20210804_191345.jpg…]()

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
