### ISSUE TITLE
Auto backup making multiple json files

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi#5655]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Device

Umidigi A9 pro

### Steps to reproduce

1. Automatic backup create proto.gz file for maximum of 3 backup file
2. Automatic backup also creating json but multiple json files (currently have 76 on my phone)
3. Since json was discontinued it should not be appearing on automatic back up and even if it should it would be a maximum of 3 files like the proto.gz backup not an unlimited amount of files

### Expected behavior

In automatic back up only proto.gz files should back up 

### Actual behavior

Automatic back up creating both proto.gz backup and json backup but my automatic backup has a limit of 3 so json backup havimg 76 files should not be possible

### Crash logs

No crash to report

**Comment by arkon** [comment]
0.11.1 doesn't even have the logic to create legacy backups anymore. If they're old, you can just delete them.
