### ISSUE TITLE
Bug during the search for new chapters

### ISSUE THREAD

**Issue by Esoterya** [tachiyomiorg/tachiyomi#5656]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Device

Realme 7 Pro

### Steps to reproduce

Click the update button
Update launch
Wait while the different manwhas are scanned
Nothing happens at the end

### Expected behavior

Process lasts 10-20 seconds and at the end, if there are, new chapters appears

### Actual behavior

Process lasts 5 minutes
No new chapters

### Other details

When I start the process it takes like 5 minutes ( while it took 10 seconds before) and no new chapter is detected...
I don't know if anyone else has it, but please help me, I love this app so I'd like to continue using it thanks

**Comment by arkon** [comment]
Please follow the linked troubleshooting guide. If nothing works, please ask on Discord for support.
