### ISSUE TITLE
Filtering by category

### ISSUE THREAD

**Issue by yToddyn** [tachiyomiorg/tachiyomi#5657]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I would like you to implement a category filtering system. Because the system has a global filtering. 

Example: 

We have two categories, one being, "Reading" and the other "Stops". 

With this, the "Reading" receives filtering of the "Unread" Caps, which will show the caps that have not yet been read. 

And the "Stops" does not receive any filtering, as this will show the works that are stopped. Thus having a better organization of the manga.

**Comment by paulo27ms** [comment]
There was already https://github.com/tachiyomiorg/tachiyomi/issues/2698 for this one.
