### ISSUE TITLE
Error parsing gallery info from ManHuaGui

### ISSUE THREAD

**Issue by Hezj** [tachiyomiorg/tachiyomi#5662]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

Android 11

### Source information

ManHuaGui 1.2.9

### Steps to reproduce

Open or refresh any gallery from ManHuaGui source

### Expected behavior

Get its information

### Actual behavior

The only info I get are title, chapters and cover image. I can read the manga but author and status are displayed as unknown.
WebView is working.
Also there's a toast saying "Failed resolution of: Lkotlinx/coroutines/BuildersKt"
I've tried both Simplified and Traditional Chinese source, both will cause this issue.

### Other details

Crash log is like this (though it doesn't actually crash):

08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: Error getting manga details
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/BuildersKt;
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.extension.zh.manhuagui.Manhuagui.fetchMangaDetails(Manhuagui.kt:157)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.source.Source$DefaultImpls.getMangaDetails(Source.kt:5)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.source.CatalogueSource$DefaultImpls.getMangaDetails(CatalogueSource.kt:1)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.source.online.HttpSource.getMangaDetails(HttpSource.kt:1)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.ui.manga.MangaPresenter$fetchMangaFromSource$1.invokeSuspend(MangaPresenter.kt:4)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.BuildersKt
08-05 22:13:36.402  7443 14092 E StandaloneCoroutine: 	... 9 more

**Comment by arkon** [comment]
Proguard issue.
