### ISSUE TITLE
Updating Library takes way longer than before and prevents reading of chapters simultaneously

### ISSUE THREAD

**Issue by Dragonzroar** [tachiyomiorg/tachiyomi#5663]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

R3644

### Android version

Android 11

### Device

Note 9

### Steps to reproduce

1. Update Library
2. Try to read a manga

### Expected behavior

The mangas should update and the chapter you choose to read should load in a timely manner.

### Actual behavior

When updating it will take roughly about 30mins to an hour to update 800 mangas, I know that's lot but I have never had issues before. When I go to read a manga while it is updating it gets stuck on a blue circle spinning for at least 2 to 5mins before showing the first page and when going to the next page I have to wait about 1 to 2 mins before the page shows up.

### Crash logs

Has not crashed

### Other details

None that I can think of

**Comment by arkon** [comment]
Refer to troubleshooting guide and/or Discord support for help. If there's an actual technical bug to report, please open another issue.
