### ISSUE TITLE
Disable updating manga from specific extentions

### ISSUE THREAD

**Issue by ElNeel** [tachiyomiorg/tachiyomi#5664]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Updating Manga takes up forever when an extension is not working (like currently in case of isekaiscans.)

I can know that an extension is not working incorrectly from first update attempt from the log. It's doesn't make sense to hit the apis when I know it won't work.

Additionally (ignore if seems like asking a lot):
it would be nice to know(notified) if an extension is working as expected or not

**Comment by arkon** [comment]
Add them to a category and exclude it from global update.

**Comment by ElNeel** [comment]
> Add them to a category and exclude it from global update.

I know about disabling categories. I was asking about extensions specifically

this is my case:
I have mangas from from several extensions in my 'current reading' category and I update only this category

Now an extension is not working properly and the overall update is taking forever.

omitting extension from update like it's allowed for categories is really necessary.

**Comment by arkon** [comment]
No, because what I said already achieves the same result.

**Comment by ElNeel** [comment]
> No, because what I said already achieves the same result.

my last pitiful attempt to convince you (please don't hate me, please give it a read 🙏)

if I am to do it your way and get the results I want, I will have to categories by each extension which defeats the purpose of having customisable categories in the first place

I have categories such: reading, plan to read, on hold, favourite, etc
each categories has sources from multiple extensions.
If I am to do it your way I will have categories my mangas into no_of_categories x no_of_extension

not just that whenever there is a broken extension I have to change my update rules and revert back once its fixed

**Comment by Riztard** [comment]
manga can have multiple categories
