### ISSUE TITLE
Crop Border popup in reader

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5665]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

A10

### Device

Redmi 8

### Steps to reproduce

1. open manga
2. open chapter
3. toggle crop border

### Expected behavior

on/off in the center

### Actual behavior

some extra space after on/off
<img width =300dp src="https://cdn.discordapp.com/attachments/825346400953827349/873062238620114974/IMG_20210806_113549.jpg">

**Comment by arkon** [comment]
Xiaomi problem.
