### ISSUE TITLE
Scaling images not working (Aug 2021)

### ISSUE THREAD

**Issue by cychrn** [tachiyomiorg/tachiyomi#5666]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.1.2

### Device

X99 Android Box

### Steps to reproduce

Just open any page of the comics and it will just show small image and cannot zoom no matter what scale type i used. Looks exactly the same problem to the ticket from Justtaway in Feb 9 2016 but it happens now in the latest version.

Note: I'm using android tv box. It used to work well before. But the problem starts after i restored data from my tablet and view a few pages. Then this happened...

### Expected behavior

The picture should be able to zoom fit the screen according to the scale type

### Actual behavior

It does not zoom at all no matter which scale type i choose

### Other details

![Screenshot_20210806-230622_AnyDesk](https://user-images.githubusercontent.com/50680667/128540271-affa643c-e26e-45c8-85be-764dee852453.jpg)
Scale type: Fit screen - still no zoom

![Screenshot_20210806-230656_AnyDesk](https://user-images.githubusercontent.com/50680667/128540421-1dffe017-ef2c-4461-afc7-ec056ebb7e06.jpg)
Scale type: Stretch - no zoom

![Screenshot_20210806-230732_AnyDesk](https://user-images.githubusercontent.com/50680667/128540500-5b4be01c-6cd1-4920-9488-90840eb19f3f.jpg)
![Screenshot_20210806-230807_AnyDesk](https://user-images.githubusercontent.com/50680667/128540552-bec1755e-3f0d-41c2-9786-f7747ba2b9d6.jpg)
![Screenshot_20210806-230831_AnyDesk](https://user-images.githubusercontent.com/50680667/128540568-04b559d7-c1ac-49a1-857c-58ad22f20cf6.jpg)
![Screenshot_20210806-230852_AnyDesk](https://user-images.githubusercontent.com/50680667/128540586-a3cd9773-6431-4ef1-a459-812d5965b299.jpg)
Scale type: Fit width, Fit heighr, Original, Smart fit... Nothing makes the picture zoom

Even pinch zoom does not work...

I tried using picture viewer (X-plore viewer) and it views and zoom normally

I tried uninstall and reinstall the app, clear all cache and data, delete all downloaded pages in tachoyomi/download folder, tried older version... Nothing helps...

Extra note, i tried in another android tv box with Android 10 and it has exactly the same problem.

Please let me know what else I should try.

Thxxx a million

**Comment by arkon** [comment]
This is almost always a problem with the Android ROM's display scale being wrong and not something that can be addressed by the app.

**Comment by cychrn** [comment]
could you please give me a little guide on which part to check?

is it adb wm size, density or overscan that is causing problem on the android rom? or is it something else?

thank you very much :)
