### ISSUE TITLE
Wrong language in group names on extension tab

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi#5667]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3644

### Android version

Android 11

### Device

Samsung Galaxy S20+

### Steps to reproduce

1. Open the Browse section.
2. Switch to the Extensions tab.

### Expected behavior

Group names should use the language defined in app settings.

### Actual behavior

Group names are using the device language.

### Other details

![image](https://user-images.githubusercontent.com/14254807/128545507-a33f49b4-016b-408d-8107-7f74d8257409.png)

**Comment by arkon** [comment]
See 03980b2f27bc80bc578808f86a1e114a72a3559e
