### ISSUE TITLE
Failed Update tag

### ISSUE THREAD

**Issue by JeeyDy** [tachiyomiorg/tachiyomi#5671]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

If a content can't be updated then a tag should appear on the icon of the manga/manhua/manwha.
It's easier to recognize it, instead of checking continuously the phone "Failed Update" Notification.

### Other details

If it's possible to make migration less time consuming, adding a "source suggestion" would help finding a reliable extension (better quality, more chapters, etc)

**Comment by KineticDevil** [comment]
**Anilist** tracker is not connecting with TachiJ2K (latest version)

**Comment by ArjixWasTaken** [comment]
Since I can't post a duplicate:

A tab that contains any manga that failed to update during the global scans 3 times in a row.

It would be used so that we can easily choose to migrate the manga to another source that won't fail.

**Comment by arkon** [comment]
#4616
