### ISSUE TITLE
Github release has Firebase Analytics & Google Ad Services

### ISSUE THREAD

**Issue by zyansheep** [tachiyomiorg/tachiyomi#5672]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Irrelevant

### Steps to reproduce

Download the app, install, App Manager tells me that 3 trackers have been added. Look inside app, see .properties files for firebase and google ads.
![install image](https://user-images.githubusercontent.com/20029431/128602074-049c04ae-255a-4143-959f-6aa763ffb130.png)
![apk image](https://user-images.githubusercontent.com/20029431/128602075-8ddf5e95-5bc1-4c6c-bc0e-c28ab92e00f0.png)

### Expected behavior

App should not contain trackers because privacy is a human right.

### Actual behavior

App contains trackers.

### Other details

I also downloaded the 0.11.1 version (which I have already installed) from github and it also had trackers. I usually download Tachiyomi from F-Droid, is the F-Droid release different from github release in that trackers are removed?

**Comment by Soitora** [comment]
We do use Firebase Analytics, we do not to my knowledge use anything related to Google Ads.
F-Droid is not supported but yes it was built without any of these.

**Comment by zyansheep** [comment]
> We do use Firebase Analytics, we do not to my knowledge use anything related to Google Ads.
> F-Droid is not supported but yes it was built without any of these.

Ah, I meant google play services, not google ads.

> **EDIT:** Firebase Analytics don't track anything in which you should feel worried and entitled to privacy. We can see stuff like how many users are using a specific version, but not much more specific than that.

hmm okay, even so, I will wait for the fdroid version to come out.

**Comment by Soitora** [comment]
> hmm okay, even so, I will wait for the fdroid version to come out.

By all means wait, however we don't give support to people who choose to use an unofficial version of Tachiyomi, it has conflicts with our own version

**Comment by arkon** [comment]
You could always compile it yourself with whatever you want stripped out.
