### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by AlifianK** [tachiyomiorg/tachiyomi#5673]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

There are untranslated strings on the update tab, where 'Yesterday' and '... days ago' strings are not present in the weblate project to be translatable.

**Comment by arkon** [comment]
Relative date strings are provided by the system. Since we're removing the in-app language picker in favour of following the device language, this is a non-issue for the next version.
