### ISSUE TITLE
UI appearing then disappearing when there's no more chapters

### ISSUE THREAD

**Issue by darkwerr** [tachiyomiorg/tachiyomi#5675]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Redmi Note 8 Pro 

### Steps to reproduce

When moving to "next page" on reading mode webtoon at the end of the last chapter of any manga, sometimes, the UI will appear then disappear. Either touching the screen or pressing the volume button. (Pressing the screen and rolling with the finger is still normal if moving slowly, otherwise the same thing happen)

### Expected behavior

The UI should appear and stay there, so you can touch to go back to chapters screen, as it was on 0.11.1. 

### Actual behavior

Sometimes the UI appear then disappear.

**Comment by darkwerr** [comment]
I tested with reading mode continuous vertical and it's having the same behavior.

**Comment by KaiWa55** [comment]
I also have the same problem on android 11(asus rog phone5), app version 0.12.1

**Comment by darkwerr** [comment]
This bug is still on 0.12.2 version from Tachiyomi. Using the same device/android version.
