### ISSUE TITLE
**Anilist** tracker is not connecting/updating! (Using TachiJ2K) 

### ISSUE THREAD

**Issue by KineticDevil** [tachiyomiorg/tachiyomi#5676]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.2.1

### Android version

Android 11

### Device

Redmi note 10

### Steps to reproduce

1. Settings
2. Tracking
3. Anilist

### Expected behavior

This should be connected and in sync

### Actual behavior

Not connecting

### Crash logs

403 not found

**Comment by loocool2** [comment]
Wrong repo
