### ISSUE TITLE
add page preload like the one in J2K

### ISSUE THREAD

**Issue by Gamefire238** [tachiyomiorg/tachiyomi#5677]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

add page preload like the one in J2K

The loading speed of the page will increase if it is loaded before opening the next page, I hope the preload feature in Tachij2k is added in this application :)

Thank you :) This is a beautiful application

**Comment by arkon** [comment]
It's always been there, it's just non-configurable.
