### ISSUE TITLE
Highlighed Chapters are Difficult to Discern from Non-highlighed ones When Using Pure Black Dark Mode

### ISSUE THREAD

**Issue by VinniHub** [tachiyomiorg/tachiyomi#5679]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable version: 0.12.1

### Android version

Android 9

### Device

Galaxy Note 9

### Steps to reproduce

1. Set app to dark mode.
2. Enable Pure Black Dark Mode Slider.
2. Navigate to a manga or the updates menu.
3. Select one or more entries from the list.

### Expected behavior

Selected entires should be clearly distinguishable from ones that have not been selected.

### Actual behavior

1. Selected entries do not have their background changed at all.
2. The text color of a selected item is merely slightly tinted. This is very hard to discern at times as the color change is so minor.

### Other details

The Blue theme is probably the worst offender of this, it being nearly impossible to tell what items have been selected with "Pure Black Dark Mode" enabled.

It is also worth mentioning that even when using the Blue theme with Pure Black Dark Mode disabled the shade of color the background of selected items becomes is probably closer to the normal background color than it should be.

**Comment by arkon** [comment]
This is why AMOLED themes are bad ideas. 🤷
