### ISSUE TITLE
Add changelogs in-app for extensions.

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#5683]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Add changelogs in-app for extensions. Every time i update extensions i would prefer to see the changelog for that extension in the app itself like "bug fixes" or "added this and that". like the changelog in-app when you download a new version of tachiyomi (when avaiable). It is just a QoS improvement.

**Comment by CarlosEsco** [comment]
#3307

**Comment by CarlosEsco** [comment]
also you go into the settings for the extension and there is a button that links to the github for that extension
