### ISSUE TITLE
Retry button overlay the downloaded image 

### ISSUE THREAD

**Issue by miss1433** [tachiyomiorg/tachiyomi#5687]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.0

### Android version

Android 11

### Device

Redmi note 9s

### Steps to reproduce

![Screenshot_2021-08-08-21-51-01-285_eu kanade tachiyomi](https://user-images.githubusercontent.com/28482555/128749772-e99dcc54-d7e2-47b5-ab60-77e3b5539f26.jpg)

### Expected behavior

There should be no retry button in a downloaded image

### Actual behavior

It just one time after i updated the app

### Crash logs

None

### Other details

None

**Comment by scb261** [comment]
Just encountered this bug personally for the first time. Can't reproduce anymore. The chapter was downloaded as cbz. The bug appeared as soon as I opened the chapter. There is an error in the logs:

```
--------- beginning of main 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: Failed to initialise bitmap decoder 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:67) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 05-24 21:03:56.293 6907 9628 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012) App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 12 (SDK 31) Android build ID: SKQ1.211103.001 test-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: rain Device model: 220333QNY Device product name: rain_eea
```

Related issue - #8261. I have 4 GB RAM, the cbz file isn't really big (10.63 MB).
