### ISSUE TITLE
Improve resume/start button

### ISSUE THREAD

**Issue by superkitten12** [tachiyomiorg/tachiyomi#5690]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The resume button for manga should extend to the screen borders, to avoid accidentally selecting a chapter that is behind the button. This is because if you miss the resume button by barely tapping underneath you can end up opening a chapter way ahead of where you are reading(or waste time loading one you already read).

### Other details

![Screenshot_20210810-014240~2](https://user-images.githubusercontent.com/16422334/128815859-d38772e8-42b8-4fc2-8fa3-c9ecda18cd3c.png)

**Comment by arkon** [comment]
https://material.io/components/buttons-floating-action-button
