### ISSUE TITLE
Black bars while reading

### ISSUE THREAD

**Issue by Broplsletmein** [tachiyomiorg/tachiyomi#5692]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Xiaomi mi10t

### Steps to reproduce

![Screenshot_2021-08-10-16-57-41-265_eu kanade tachiyomi](https://user-images.githubusercontent.com/88722283/128872636-628de22c-dcf2-4fda-839e-87b364836dae.jpg)

Whenever I am reading a manhwa, manhua or manga, at the end of every page there is a black bar. When the pages ends on a speech bubble it splits the bubble into 2 parts. 

### Expected behavior

At the end of every page, the black bar shouldn't be there it should just be a smooth transition to the next page.

### Actual behavior

At the end of every page there is just a black bar.

### Other details

I don't know if it's because of the black bars but whenever I am reading it takes a lot of time for a new page to load up.

**Comment by arkon** [comment]
Use webtoon instead of continuous vertical.
