### ISSUE TITLE
App UI is formatted incorrectly when opening Tachiyomi with biometrics active and the on screen keyboard active.

### ISSUE THREAD

**Issue by Nan123721** [tachiyomiorg/tachiyomi#5698]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3668

### Android version

Android 11 (Lineage 18.1)

### Device

OnePlus 8 Pro

### Steps to reproduce

1. Open Tachiyomi with on-screen-keyboard active and biometric authentication turned on. I have found the best way to reproduce this is by searching for it in the app drawer and opening it without closing your keyboard.

### Expected behavior

The app should open as normal with the UI looking correct.

### Actual behavior

The app will have blank space where the keyboard WOULD be if it was open with the entire UI shifted up, including the buttons at the bottom.

### Other details
I have found no way to fix this besides restarting the app and turning either biometrics off or opening without the keyboard active.

**Comment by arkon** [comment]
Is this still happening in r3678+? Someone on Discord seemed to think that it was fixed.

**Comment by Nan123721** [comment]
Just Updated, Seems to be fixed now. Closing.

**Comment by Nan123721** [comment]
Accidentally closed. This IS still an issue with the latest build.

**Comment by arkon** [comment]
Forgot that insets are the bane of my existence.

**Comment by Nan123721** [comment]
Pretty sure this is fixed now.
