### ISSUE TITLE
Do not download old chapters if they get officialy translated

### ISSUE THREAD

**Issue by ziomek64** [tachiyomiorg/tachiyomi#5700]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

So sometimes fan translations are very ahead of official ones and when official one get translated into a volume they get re-downloaded. I'm not sure if this is issue with extension or app. As it happened to me on mangasee and mangahere i think. These are the only I use.

So what should happen that when we are on READ chapter 100 and official volume gets translated so let's say 50-60 they should not be downloaded again if we have auto-download. Or let user choose in settings. If we are on chapter 10, then sure re-download them

I wasn't sure if to count it as an issue or feature. It's not a bug but it's frustrating. If this an issue with extension let me know, I will open issue in extensions repository.

**Comment by Seishirou101** [comment]
Don't use sources that reupload chapters then. To tachiyomi those are *new* chapters. It has a new url, it has a new upload date, I believe it even appears on their website in their "latest chapters" because that just sorts by upload date. Mangasee and Mangalife are notorious for it as they try to upload the highest quality scans, which usually is a official rip.

**Comment by ziomek64** [comment]
Well they are 'new' but what about chapter count. App should recognize that. I understand this is workaround. But something should be done. There might be more sources like this. I use mangasee for a reason and that's quality

**Comment by Riztard** [comment]
even if the chapter number is the same, in fact that is a NEW chapter

**Comment by ziomek64** [comment]
> even if the chapter number is the same, in fact that is a NEW chapter

I dont mind redownloading same chapter. But if read chapters are higher do not download lower ones. As simple as that. If app recognizes chapter numbers on all extensions it should be easy to do.

**Comment by CarlosEsco** [comment]
Not something that's going to be added, tachiyomi just provides what the site provides

**Comment by ziomek64** [comment]
> Not something that's going to be added, tachiyomi just provides what the site provides

It has no sense for me, if tachiyomi is aware od chapter numbers it would be great feature for this app
