### ISSUE TITLE
get for new download option

### ISSUE THREAD

**Issue by hong-tm** [tachiyomiorg/tachiyomi#5703]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Can i get an option for download from chapter * to the end of the comic? it is so hard for me to download for the option now the last 10,5,1 chapter.tq!

### Other details

more easy download option

**Comment by curche** [comment]
You can select a range of chapters
Lets say you want chapter 1-7:
  - long click on chapter 1
  - then long click on chapter 7 
  - 1-7 will be selected and you get option to download or mark as read

**Comment by hong-tm** [comment]
thanks for help, it work but such a hidden option

nicki ***@***.***> 于 2021年8月12日周四 上午11:54写道：
