### ISSUE TITLE
have to reinstall app to get latest chapters

### ISSUE THREAD

**Issue by unmellow** [tachiyomiorg/tachiyomi#5708]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

10

### Device

moto g play (2021)

### Steps to reproduce

Installed tachiyomi 
added bato.to extension

Find a manga series, E.g., 

Favorite it and wait for updates

### Expected behavior

open up the app and see the latest chapter avaliable to read or some button to force it  to check for new chapters

### Actual behavior

latest chapter is missing and their is no way to force it to check for new ones without reinstalling the app

(when I installed preview version r3668 instead of actually reinstalling version 0.12.1)

after doing that though i found the latest chapter

can their please be a redownload manga info button
so i can not reinstall the whole app?

### Crash logs

their was no crash

### Other details

series in question is https://bato.to/series/84960

**Comment by unmellow** [comment]
i would also like to add even if this is a problem with the extension not alerting the app of new chapters
i still think their should be an easy to find button that deletes all the data and meta data about 
a manga/series to force a redownload (which is what  happens when you reinstall the app i assume)

**Comment by CarlosEsco** [comment]
> 
> 
> i would also like to add even if this is a problem with the extension not alerting the app of new chapters
> i still think their should be an easy to find button that deletes all the data and meta data about
> a manga/series to force a redownload (which is what happens when you reinstall the app i assume)

you can remove the manga from your library and clear the db in advanced settings

**Comment by CarlosEsco** [comment]
for your original issue, did you swipe refresh the manga?

**Comment by unmellow** [comment]
So I expected to find these options on the actual page for the individual manga and when I didn't see it

I started searching the docs and FAQ it doesn't have any sections on how to update my manga (at least not obvious labeled in my opinion)

**Comment by arkon** [comment]
Either the source URL changed (which the global update errors would indicate), or you're refreshing within the cache time.
