### ISSUE TITLE
Resume Button Overlapping Toolbar When Highlighting Chapters Instead of Disappearing

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#5709]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Device

Honor 7X

### Steps to reproduce

1. Select a manga with unread chapters
2. Select a chapter (read/unread state does not matter)(
3. Resume button will overlap the toolbar

### Expected behavior

The resume button should disappear as usual and not overlap the toolbar

### Actual behavior

The resume button is overlapped by the toolbar

### Other details

https://cdn.discordapp.com/attachments/349436576037732355/875668189978165298/Screenshot_20210813_142058_eu.kanade.tachiyomi.jpg

https://cdn.discordapp.com/attachments/349436576037732355/875668190280163348/Screenshot_20210813_142248_eu.kanade.tachiyomi.jpg

**Comment by arkon** [comment]
Can't reproduce.
