### ISSUE TITLE
Uninstalling tachiyomi doesn't uninstall its extensions

### ISSUE THREAD

**Issue by Thewisem** [tachiyomiorg/tachiyomi#5717]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.0

### Android version

Android 7

### Device

Samsung Galaxy TabA

### Steps to reproduce

1. Install tachiyomi
2. Install extensions
3. Uninstall tachiyomi
4. Reinistall tachiyomi
5. See extensions

### Expected behavior

No extensions should be available after uninstall

### Actual behavior

All of the extensions are still there

**Comment by arkon** [comment]
Extensions are separate apps and shared across Tachiyomi forks. I'm not sure if it'd make sense to uninstall them automatically, if even possible.

**Comment by zayin02** [comment]
Also if you are switching between forks, you'd probably not want the extentions to be uninstalled after deleting one of them.

**Comment by Thewisem** [comment]
How about having the option to do so?

**Comment by arkon** [comment]
No, because it's impossible for apps to uninstall other ones without manual user interaction anyway.
