### ISSUE TITLE
Turn off default tracking status change

### ISSUE THREAD

**Issue by MyangelOmoi** [tachiyomiorg/tachiyomi#5718]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The latest update keeps changing the reading status of my manga from "paused" to "reading", I would like to be able to turn off this feature in the settings.

**Comment by arkon** [comment]
See #5588

**Comment by MyangelOmoi** [comment]
Does it mean there's no chance to get this fixed/changed ? It totally breaks "Manga in progress" section on AniList as it will change status of every paused manga to reading.
I don't think people want to see their irregular schedule manga in reading section, it was perfect before the change.

**Comment by paulo27ms** [comment]
Arkon doesn't see the benefit of this but I'm not sure if he's opposed to a setting to change this behavior or not, but someone else would need to PR it.
