### ISSUE TITLE
In local manga ,dual page split doesn't work

### ISSUE THREAD

**Issue by aoki-rin** [tachiyomiorg/tachiyomi#5720]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Redmi K40 Pro

### Steps to reproduce

When using local manga to read ,dual page split doesn't work.

### Expected behavior

When using dual pages split you should see both halves of the dual page

### Actual behavior

the screen becomes blank.

### Crash logs

No response

### Other details

No response

**Comment by arkon** [comment]
Can't reproduce. If the image type is splittable (e.g. an animated image), then it won't do so regardless of it being local or not.
