### ISSUE TITLE
Editing Manga Title in Your Library

### ISSUE THREAD

**Issue by DigitalMethBaba** [tachiyomiorg/tachiyomi#5722]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

So you know how we add a manga to our library by clicking on "Add to library". I just wanted a new feature where we can change the title of a manga added in the library, which creates more personalization freedom for us Tachiyomi users. 

For example, I was making a collection of the mangas I was looking for Tokyo Ghoul Joker, a side story. But I couldn't find a separate manga for that. But I did find the Tokyo Ghoul:re manga with all the chapters in an extension, including the side story. But I already had that manga from another extension(it didn't have the side story) and wanted to create a separate manga just with the side story title and cover. Puts a neat look on your collection.

**Comment by curche** [comment]
For this particular case, it'd be best to just download the extra chapters and make it into a Local source manga. Refer to the [Local Manga Guide](https://tachiyomi.org/help/guides/reading-local-manga/)

For a more general use case, Duplicate to https://github.com/tachiyomiorg/tachiyomi/issues/4398

**Comment by DigitalMethBaba** [comment]
umm so I made it into a local manga but the manga cover doesn't seem to
appear even though I pasted the file in the manga title folder and renamed
it as cover.jpg

**Comment by curche** [comment]
From #support
> To fix missing covers on local manga:
> 1. Make sure you can read chapters you added. If not, follow the guide linked above.
> 2. Remove manga from Library.
> 3. Go to More > Settings > Advanced and tap Clear database. This only affects manga that aren't in your Library.
> 4. Add manga back to Library, the cover should be fixed now.

If you need more help, better to ask at the Discord server's #support channel
