### ISSUE TITLE
L10n of local label may make the number of chapters unreadable

### ISSUE THREAD

**Issue by Horodep** [tachiyomiorg/tachiyomi#5725]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11 (One UI 3.1)

### Device

Samsung A71

### Steps to reproduce

Change language for example to russian.
Set 4 column view.
Add local manga.

English:
![image](https://user-images.githubusercontent.com/8913017/129491513-084df4a4-8771-419b-af81-9336febed9f5.png)

### Expected behavior

Russian expected:
![image](https://user-images.githubusercontent.com/8913017/129491639-1f90c967-4172-46e2-9bf5-f4416ff49e60.png)

### Actual behavior

Russian actual:
![image](https://user-images.githubusercontent.com/8913017/129491551-17350049-612e-4c59-b92d-a1bfd33c4bc6.png)

**Comment by Horodep** [comment]
Same goes with labels in sourse manga list:
3 columns - readable:
![image](https://user-images.githubusercontent.com/8913017/129491784-8a3f8a55-cbc4-4085-837c-a78cc519fdbe.png)

4 columns - line wrapped on space symbol but second line is not displayed:
![image](https://user-images.githubusercontent.com/8913017/129491819-daf7236d-2ea9-4140-8ce1-bd63d7a97643.png)

**Comment by Horodep** [comment]
Update on 0.13.0:
1. Extention page looks great:
![SmartSelect_20220201-014149_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/151885338-8445b071-fb91-47e5-9659-491f62eda948.jpg)

2. Library issue with local badge is still here:
![SmartSelect_20220201-014204_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/151885463-265f5322-911b-410a-9cec-125f2558967c.jpg)

3. New problem with down-menu buttons:
![SmartSelect_20220201-013742_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/151885549-b579570e-0958-4b90-a874-523fe72f417d.jpg)

4. New problem with tracking button on manga page:
![SmartSelect_20220201-013758_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/151885607-d258672e-bd47-463a-a5da-123570db5922.jpg)

**Comment by arkon** [comment]
What's the expected behaviour when the words are so long?

**Comment by Horodep** [comment]
1. Smaller font for text of all buttons on that string. 0.12.3:
![Screenshot_20220201-015317_Gallery.jpg](https://user-images.githubusercontent.com/8913017/151886753-53a9ee64-98a0-4986-85d5-6a006f2593a6.jpg)
2. Or no-text-menu-buttons switch in settings 
3. Or another translation

**Comment by arkon** [comment]
1. That's not going to happen, the styling changes are consistent with regular Material 3 font sizes.
2. That won't really help with cut-off text in other places.
3. You can contribute, it's up to the people doing translations to try to have things that'll fit for most cases: https://tachiyomi.org/help/contribution/#translation

**Comment by Horodep** [comment]
1. OK. 
2. From my point of view ellipsis damage the appearance and bottom-menu is the most used part of the interface and also the front part of it. In other places perfect interface view is not so important as here, and there ellipsis goes good there. For example on traking button or badges. As for menu I believe that no text switch would be a great option. 
3. I'll think about translations where cut-off text is not an option.

**Comment by Horodep** [comment]
Found a really weird stuff with "in library" badge.
This is 3 column view:
![Screenshot_20220206-013329_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/152661234-ddb0d1bf-17e0-4a3a-8c27-62af44dc5810.jpg)
This is 4 column view on 3rd font size (in android settings)
![Screenshot_20220206-013354_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/152661270-4ab57aa8-7600-4809-9ccd-2fb0aaef6493.jpg)
This is 4 column view on 2nd font size (smaller one)
![Screenshot_20220206-013415_Tachiyomi.jpg](https://user-images.githubusercontent.com/8913017/152661289-cc1403a0-10b0-4ea5-8b8f-5f31e08ba9d4.jpg)

```
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A715FXXS7BUJ1
Device brand: samsung
Device manufacturer: samsung
Device name: a71
Device model: SM-A715F
Device product name: a71naser
```

**Comment by stevenyomi** [comment]
Is this still happening in 0.14.x?

**Comment by Horodep** [comment]
> Is this still happening in 0.14.x?

Yes. Even worse. At the moment numbers are not seen at all:

![SmartSelect_20221104-204500_Tachiyomi](https://user-images.githubusercontent.com/8913017/200031010-44ec77d1-9447-4c09-a939-4ee3830496a5.jpg)
