### ISSUE TITLE
Nothing Loads in V0.12.1

### ISSUE THREAD

**Issue by RelmOneutrus** [tachiyomiorg/tachiyomi#5726]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Samsung note 20 ultra

### Steps to reproduce

1: I update the manga
2: open the new chapter
3: waiting for it to load. 
4: never loads
Also:
1: I check the latest releases through the discover tab
2: doesn't load

### Expected behavior

New chapter loads and I start reading.

### Actual behavior

Stuck in the loading screen and new manga don't load.

### Other details

This issue happens when using both wi-fi and data.
Rolling back to v0.11 helped sove the issue.

**Comment by arkon** [comment]
Please provide better steps. What source? What entry? What chapter?

**Comment by RelmOneutrus** [comment]
All sources, all entries, all chapters.

**Comment by arkon** [comment]
You're going to have somehow provide more info for debugging then, since nobody else is affected by this.

**Comment by RelmOneutrus** [comment]
What should i provide?

**Comment by RelmOneutrus** [comment]
What should i provide?

**Comment by arkon** [comment]
I'd recommend trying to get help from the support team on Discord. If you have something reproducible / other techical details, feel free to open another GitHub issue so we can address it.
