### ISSUE TITLE
Blue Tinted Overlay When Using Hardware Keys to Navigate Chapter 

### ISSUE THREAD

**Issue by Hero-Over** [tachiyomiorg/tachiyomi#5727]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3583

### Android version

Android 11

### Device

Multiple Devices

### Steps to reproduce

1. Open Chapter
2. Use any hardware keys to navigate chapter, such as; Arrow Keys, Pg Up/Down

### Expected behavior

Unchanged manga image
https://imgur.com/DqmykV9

### Actual behavior

Blue Tinted Overlay on Image 
https://imgur.com/gJM0QfZ

### Other details

This did not happen in older builds

**Comment by Hero-Over** [comment]
Thank you for making the attempt. I tried the preview as well as built myself and the issue persists. Your commit looks like it should work, but could it also have to do with the <code>android:background="?attr/selectableItemBackgroundBorderless"</code> string?

**Comment by SoloLeveller1** [comment]
My man reading Mashle I see     (˵╹ω╹˵)b

**Comment by arkon** [comment]
Tried another thing, but I'll leave this open until it's actually confirmed to be fixed or not.

**Comment by arkon** [comment]
Does this still happen in the latest preview build?

**Comment by Hero-Over** [comment]
> Does this still happen in the latest preview build?

sorry for the late response. yes this is still happening. an easy way to test for you would be to load up the app in AVD (Android Studio Emulator) and use left/right keys to navigate chapter.

Thanks so much for your continued hard work!
