### ISSUE TITLE
Comparison of sources before attempting migration

### ISSUE THREAD

**Issue by SoloLeveller1** [tachiyomiorg/tachiyomi#5729]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

While migrating to another source, a popup which shows chapters count, latest chapter number and/or release date.

This would be useful as some sources either have chapters missing, no chapters at all or aren't updated.

### Other details

Here's something to give a reference(Am totally not proud of it :/)

![Screenshot 2021-08-16 155912](https://user-images.githubusercontent.com/77271207/129550261-b3d7e4b9-ed20-4127-a36f-66335bada91a.png)

Hope it helps in anyway to give my idea 😅😅

**Comment by SoloLeveller1** [comment]
So... is this feature doable? 😅
Would really help me in many ways, and feels quite useful to others I believe

**Comment by curche** [comment]
> While migrating to another source, a popup which shows chapters count, latest chapter number and/or release date.

long-click on the search results to open the manga. 

It has to be done manually since otherwise you will be sending more requests to the source, making the search slower and increasing the load on source servers.

Also, have patience. If you make a request, someone will get to it eventually.

**Comment by SoloLeveller1** [comment]
I didn't know there was a manual way to do that. 😮😯
Sorry for the issue 😞
