### ISSUE TITLE
Folders in Categories

### ISSUE THREAD

**Issue by rahaaatul** [tachiyomiorg/tachiyomi#5730]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

It should work like this-

Suppose, I have a category called **Manga**.
And I have lots of Manga that are related to one manga. Like, I have GTO, and other mangas related to it like, Bad Company, Paradise Lost, etc.
I want those mangas to be in a GTO folder inside Manga category. And inside folder we can customize the list in chronological order.

**Comment by loocool2** [comment]
#1803
