### ISSUE TITLE
Filter per category not working properly

### ISSUE THREAD

**Issue by AbdullahBinJahed** [tachiyomiorg/tachiyomi#5731]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Device

Redmi 6

### Steps to reproduce

category > filter (unread)

### Expected behavior

should filter only that category

### Actual behavior

filtered the category and the next category too

### Other details

![Screenshot_2021-08-16-17-57-17-676_eu kanade tachiyomi](https://user-images.githubusercontent.com/39275638/129560912-26aabe4b-5020-43a2-8d0c-e7eb3894dce5.jpg)

**Comment by arkon** [comment]
The setting doesn't even mention filtering.

#5657 for the feature request.

**Comment by AbdullahBinJahed** [comment]
> The setting doesn't even mention filtering.
> 
> #5657 for the feature request.

🥴 ... sorry then
