### ISSUE TITLE
Library not updating after latest update

### ISSUE THREAD

**Issue by imli700** [tachiyomiorg/tachiyomi#5744]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.0

### Android version

Android 11

### Device

OnePlus 6t (A6010)

### Steps to reproduce

1. Turn on auto update
2. Switch off battery optimization
3. Follow the "Don't kill my app!" Guide for OnePlus
4. The app still won't update auto-update

### Expected behavior

The app should've updated the library automatically

### Actual behavior

The app doesn't update the library despite following the guides

**Comment by curche** [comment]
Firstly, update to 0.12.1

Then disable the update setting, force close the app and then set it again. This should reset the Updater. 
If it still doesn't work, disable Battery Optimisations for the app from app settings
If still no, follow the dont kill my app guide. At this point it should start working

The library update works as expected on my device. If it still doesn't work, then the fault is on your phone being very aggressive in killing background apps even after all this and there isn't much the app can do to fix it. (Maybe try a custom ROM?)

**Comment by arkon** [comment]
This was indeed a bug with 0.12.0/0.12.1. Manually toggling the preferences will reset the jobs.
