### ISSUE TITLE
option to turn off auto-updating tracker reading status

### ISSUE THREAD

**Issue by JayFlowGT** [tachiyomiorg/tachiyomi#5745]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Reading a chapter will now set the series as currently reading even if it is already set to something else. 
I dont know why the latest update has this included without the option to turn it off.

**Comment by MyangelOmoi** [comment]
I already noted in https://github.com/tachiyomiorg/tachiyomi/issues/5718 how this behavior breaks Anilist, I hope its resolves somehow as I don't want to downgrade to 0.11 just for this change.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/5588#issuecomment-886072423
