### ISSUE TITLE
Bookmarked chapter are refusing to delete

### ISSUE THREAD

**Issue by royal78** [tachiyomiorg/tachiyomi#5746]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

samsung SM-M215F

### Steps to reproduce

1) go to any manga re webtoon
2) download chapter
3) Bookmark some of them
4) Select the bookmarked chapter or select all chapter

### Expected behavior

The bookmarked chapter is also need to be deleted like other normal chapter

### Actual behavior

But, the bookmarked chapter remain as it is even in Source folder of Tachiyomi bookmarked chapter remain as it is.

### Other details

It's the photo as an example
![Screenshot_20210819-171506_Tachiyomi](https://user-images.githubusercontent.com/76758776/130063140-35e45887-beb4-452e-a013-920c5d04710b.jpg)

|All other chapters are deleted just the bookmarked remain there`

**Comment by CarlosEsco** [comment]
you need to enable the setting to allow deleting of bookmarked items

**Comment by royal78** [comment]
Thanks bro you are life saver
