### ISSUE TITLE
Support TIFF format

### ISSUE THREAD

**Issue by wgorriijeukhsmccsjufsvroxkxzujyb** [tachiyomiorg/tachiyomi#5747]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### Describe your suggested feature

Some scan files use TIFF format
Currently, Tachiyomi says "The image couldn't be loaded"

**Comment by NotTsunami** [comment]
https://github.com/deckerst/Android-TiffBitmapFactory might be of relevance. It implements [libtiff](https://gitlab.com/libtiff/libtiff) into a usable library.

**Comment by arkon** [comment]
TIFF is so uncommon, I'm not sure it's worth bloating the app for it.
