### ISSUE TITLE
Random library update multiple times a day

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#5748]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

App version: 0.12.1-3691 (standard, 071bad123, 67, 2021-08-15T22:21Z) Android version: 11 (SDK 30) Android build ID: RKQ1.201022.002 release-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: sunny Device model: M2101K7AG Device product name: sunny_global

### Android version

Android 11

### Device

Redmi note 10 

### Steps to reproduce

1

### Expected behavior

1

### Actual behavior

Tachiyomi just updates the library regardless of the set update time. Can update after 3 hours, maybe after 2, after 5, and etc. Installed 12 hours update and different time options don't help with this error. Usually updated 5-10 times

### Other details

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7014899/tachiyomi_crash_logs.txt)

**Comment by ve1mi** [comment]
Miui 12.5.2 Xiaomi eu, and it was also on miui 12 eu. 
Permissions are given to autorun, permissions, work in the background

**Comment by paulo27ms** [comment]
How are you checking how many times it updates? Just multiple new chapters throughout the day?
Personally what I find is that Tachiyomi will sometimes (like 2~3 times a week) only update when I touch my phone despite almost every time it updating on its own when it's idle, could be just coincidence but it's odd how it happens sometimes.
Not sure if it could be related to the behavior you see.

**Comment by ve1mi** [comment]
> How are you checking how many times it updates? Just multiple new chapters throughout the day?
> Personally what I find is that Tachiyomi will sometimes (like 2~3 times a week) only update when I touch my phone despite almost every time it updating on its own when it's idle, could be just coincidence but it's odd how it happens sometimes.
> Not sure if it could be related to the behavior you see.
I'm writing about updating the Library, not the application. Notification when the screen is locked or when reading a manga, random scanning of 500 titles isn't the most pleasant thing, especially some extensions (sites) are full of garbage and take a long time to check

**Comment by ve1mi** [comment]
What's the difference how many tabs if only unfinished manga is updated
At least it cringe to create categories in the Russian version, because for 2 years translators or developers can't translate the main tab of the Library into Russian and it is called - default (it can't be renamed and it's in English, and the rest of the tabs will be in Russian)

**Comment by paulo27ms** [comment]
You can get rid of the default category if you just make more categories and move all the manga to outside of default.

**Comment by ve1mi** [comment]
Oh , it really works

**Comment by ve1mi** [comment]
You can't delete default or do anything with it. The default tab will always be shown

**Comment by CarlosEsco** [comment]
@ve1mi @paulo27ms this isn't discord the chat as strayed from the original issue.

**Comment by arkon** [comment]
Not sure what's wrong with your particular scenario, but the job is scheduled based on the preference and always replaces the existing job when updated.

You can try setting it to manual first to cancel all existing jobs.

Newer preview build has an updated version of WorkManager, so that might help too.
