### ISSUE TITLE
Add pending downloads count on Download queue

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5753]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

One on the title bar, like "Download queue (#items)"

![IMG_20210820_093601](https://user-images.githubusercontent.com/63973749/130165317-e42b9a0d-0417-4bab-8b11-240203fac5ba.jpg)

#

One on the More screen, a pending downloads counter badge on the right side. (Replacing secondary "999 remaining" text)

Reasoning for this one is that you can't see how many remaining chapters are there when downloads are paused.

![image](https://user-images.githubusercontent.com/63973749/130155707-1938224d-5930-4a68-93b6-b696fb592108.png)

(edited with a little more info)

**Comment by Platiplus** [comment]
Hi. If it is okay, I'll try to tackle this!

**Comment by arkon** [comment]
@Platiplus Go for it!
