### ISSUE TITLE
Blue theme Text highlight and cursor has the same colour as the background

### ISSUE THREAD

**Issue by HybridOta** [tachiyomiorg/tachiyomi#5762]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.12.1

### Android version

Android 10

### Device

Oneplus 5

### Steps to reproduce

1. Select App theme to "Blue"
2. Type something in the search bar of "Library" or "Browse"
3. Highlight the text or move the text cursor within the text (like when trying to fix a typo)

![image](https://user-images.githubusercontent.com/78659647/130318272-f6d0b485-b2e3-40c1-98a9-f142eb245ede.png)

### Expected behavior

The cursor and highlight colour should be a different colour than the background.

### Actual behavior

You are unable to see the cursor and highlighted text because they are the same colour as the background.

**Comment by arkon** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi/commit/dd008bc13ac153c9d8d335f46079c568a6fb3194
