### ISSUE TITLE
Select manga in tracker with double click/hold

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#5769]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Instead of having to select the manga and then press the confirmation button, let us double click/hold to select and confirm.

**Comment by arkon** [comment]
This is actually non-trivial to implement, so I'd rather just keep it as-is.
