### ISSUE TITLE
Page load icon often missing in Webtoon mode

### ISSUE THREAD

**Issue by Gamefire238** [tachiyomiorg/tachiyomi#5772]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

VIVO Y12

### Steps to reproduce

1. I open the page in Webtoon mode
2. My internet is slow
3. Page loader appears with blue ring images
4. Problems here (the blue ring logo lost and left a black page, but it only happens when loading the page only, after loading the page finished the comic image still appears) so this is just a matter of loading pages. 

### Expected behavior

the blue ring doesn't disappear when loading the page

### Actual behavior

Often the blue ring is gone and only leaves a black page afterwards, and it only happens in Webtoon mode.

**Comment by arkon** [comment]
This was adjusted later on, is it still an issue?
