### ISSUE TITLE
Manga title containing "μ" was not rendered correctly and instead the HTML code appears

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi#5773]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 8

### Device

Samsung Galaxy S7

### Steps to reproduce

I went to the Mangasee extension and added "μ & I" to my library only to see that the character μ is being rendered in code. 

### Expected behavior

The μ should render as is. 

### Actual behavior

Manga title "μ & I" is rendered as "&#956 & I".

**Comment by alessandrojean** [comment]
If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by sillysack69** [comment]
But is it an issue with the extension? I thought tachiyomi wasn't able to display the character. I tried searching on other extensions but they all use alternate spellings like myuu and so I couldn't say that it was the extensions fault. Only mangasee and Mangalife use the original title.

**Comment by alessandrojean** [comment]
Yes, it is. The extension needs to be updated to replace these HTML entities in the title. Open a issue in the extensions repo and it will be addressed by someone.

**Comment by sillysack69** [comment]
Okay.
