### ISSUE TITLE
Chapter list release time is wrong

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#5777]
### Steps to reproduce

Open any manga's chapter list

### Expected behavior

It should tell a chapter's release date by a few hours/today/yesterday, etc.

### Actual behavior

"Today/yesterday" is actually counted through hours instead of the actual release date. So in this manhua I have 4 chapters: 1 released 8/21, and 3 released 8/22. (Currently 8/23) two of those chapters are marked as released "yesterday", while the other two are marked as released "today". Only one of them is actually correct.

Everything's fine on Updates screen.

### Tachiyomi version

Preview r3681

### Android version

10

### Device

Moto G7 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
Kindly update first to latest preview (r3716) and see if the issue still persist.

**Comment by hyoretsu** [comment]
Yes it's still the same as before
