### ISSUE TITLE
Chips in pure black theme also has black bg

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5778]
### Steps to reproduce

check any manga

### Expected behavior

Dark grey color (maybe same color as tracker sheet's dark grey bg, or same color as J2K chips in pure black)

### Actual behavior

![IMG_20210823_125441](https://user-images.githubusercontent.com/63973749/130392421-c4143fe7-c8cb-4693-88b8-c19e5df44c74.jpg)

### Tachiyomi version

r3716

### Android version

A10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Will have to look into it later, at the moment of my PR it looked fine as seen in the provided screenshots.

**Comment by Matth7878** [comment]
Can confirm with Android 11. I have no background for chips in amoled mode.
