### ISSUE TITLE
Blue Theme: Reader Overlay Paints Entire Screen Blue

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi#5780]
### Steps to reproduce

Set app theme to Blue, on either light or dark mode.

### Expected behavior

![Screenshot_20210823-180415_Tachiyomi](https://user-images.githubusercontent.com/34067059/130525446-f5816218-e2a3-410e-9f30-7418f33637ba.png)

### Actual behavior

![Screenshot_20210823-165600_Tachiyomi](https://user-images.githubusercontent.com/34067059/130525335-7be8b2d6-09cb-4001-b66e-099a55d37e66.png)

### Tachiyomi version

Preview r3716

### Android version

Android 11

### Device

Oneplus 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does this still happen in the latest preview build?

**Comment by kiriya-aoi** [comment]
No, as you suspected on discord a week ago it seems to have been fixed in one of the first few commits after r3716.
