### ISSUE TITLE
Allow filters to be applied in each category independently.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#5782]
### Describe your suggested feature

Currently the filters only work on the whole library and you can't apply them for a particular category inside a library.

Make it so that you can apply different filters for seperate categories independently.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
There's a chapter filter that you can use to hide non-downloaded chapters and you can apply it to the entire library as well.

**Comment by THElegend5** [comment]
> There's a chapter filter that you can use to hide non-downloaded chapters and you can apply it to the entire library as well.

I know there is one which can be applied to the whole library and I have mentioned it in my post , but the one which is for particular category in a library doesn't do that , which means you can't do this to a particular category within a library if you want to and your only option is to apply it to the whole library.

**Comment by paulo27ms** [comment]
You mentioned the one in the "more" menu, I'm talking about the chapter list filter (3 bar menu next to the chapter list). 
You should probably change this suggestion so that chapter filters can be applied on a category-basis as a separate option, currently they can only be applied to the entire library. That'd be something more feasible to implement (I doubt your current suggestion would be done) and wouldn't drastically change current behavior.
Also, there is no category specific filters, only display and sorting, if you select the filter in the library, it applies to all categories.

**Comment by THElegend5** [comment]
> You mentioned the one in the "more" menu, I'm talking about the chapter list filter (3 bar menu next to the chapter list).
> You should probably change this suggestion so that chapter filters can be applied on a category-basis as a separate option, currently they can only be applied to the entire library. That'd be something more feasible to implement (I doubt your current suggestion would be done) and wouldn't drastically change current behavior.
> Also, there is no category specific filters, only display and sorting, if you select the filter in the library, it applies to all categories.

![IMG_20210824_205815](https://user-images.githubusercontent.com/63903377/130645251-027e1f6b-079c-408d-9603-434e99a25aad.jpg)
I was talking about this filter in a category if enabled doesn't hide the chapters which are not downloaded.

![IMG_20210824_210012](https://user-images.githubusercontent.com/63903377/130645507-68807932-c8f2-4f72-ad70-aa43dbcef7a0.jpg)
While this one which is for the whole library does hide the chapters which are not downloaded.

**Comment by THElegend5** [comment]
> > You mentioned the one in the "more" menu, I'm talking about the chapter list filter (3 bar menu next to the chapter list).
> > You should probably change this suggestion so that chapter filters can be applied on a category-basis as a separate option, currently they can only be applied to the entire library. That'd be something more feasible to implement (I doubt your current suggestion would be done) and wouldn't drastically change current behavior.
> > Also, there is no category specific filters, only display and sorting, if you select the filter in the library, it applies to all categories.
> 
> ![IMG_20210824_205815](https://user-images.githubusercontent.com/63903377/130645251-027e1f6b-079c-408d-9603-434e99a25aad.jpg)
> I was talking about this filter in a category if enabled doesn't hide the chapters which are not downloaded.
> 
> ![IMG_20210824_210012](https://user-images.githubusercontent.com/63903377/130645507-68807932-c8f2-4f72-ad70-aa43dbcef7a0.jpg)
> While this one which is for the whole library does hide the chapters which are not downloaded.

Here is an example.
![IMG_20210824_210338](https://user-images.githubusercontent.com/63903377/130646236-f7e30595-97c5-4e54-b312-e382f71fd0ef.jpg)
This is with the first one enabled .
![IMG_20210824_210353](https://user-images.githubusercontent.com/63903377/130646327-b283974e-cb9c-4376-a62d-3423e49f01c2.jpg)
While here is one with the later one enabled.

**Comment by paulo27ms** [comment]
I'm talking about this filter option (highlight in yellow when you're in "downloaded only" mode on your screenshot).

![image](https://user-images.githubusercontent.com/13546823/130646630-5f7a2326-3c82-4a05-9309-0802d29a4d25.png)

I'd say you have 2 options: either apply this filter with "downloaded" enabled as the default or change your request to add an extra option to apply this chapter filter to the current category.

Anyway, if you wanna continue the discussion head over to discord.

**Comment by THElegend5** [comment]
I found another with the same so closing this one.
