### ISSUE TITLE
Prev

### ISSUE THREAD

**Issue by Luke11057** [tachiyomiorg/tachiyomi#5783]
### Steps to reproduce

Turn on app
Select manga
Select chapter
App turns off

### Expected behavior

To be able to read

### Actual behavior

I click on any chapter from any source and it turns the app off

### Tachiyomi version

Preview r3716

### Android version

Android 9

### Device

Samsung H3113

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Post crash logs.

**Comment by Luke11057** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7040246/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
No info in those logs, and don't even match up with the device reported in the issue. Please open another issue if you get actual crash logs.
