### ISSUE TITLE
Tag display expand/collapse desynchronizes with description expand/collapse after some interactions

### ISSUE THREAD

**Issue by Octocontrabass** [tachiyomiorg/tachiyomi#5787]
### Steps to reproduce

1. Browse for manga (do not use your library)
2. Select a manga with tags that don't fit in a single line
3. Collapse the description and tags
4. Refresh the manga details or add/remove the manga from your library
5. Expand and collapse the description

### Expected behavior

The tags and description should both expand and collapse at the same time.

### Actual behavior

When expanding the description, the tags collapse. When collapsing the description, the tags expand.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Google Pixel 3a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Fixed with #5854
