### ISSUE TITLE
Can't back-up

### ISSUE THREAD

**Issue by km-mm** [tachiyomiorg/tachiyomi#5799]
### Steps to reproduce

1. Go to backup & restore
2. Tried to create a backup
3. Select path with MiXplorer file manager

### Expected behavior

App should not crash & create backup

### Actual behavior

tachiyomi automatically close/crashes & leave behind 0B .proto.gz.pkpass file 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7065118/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.12.1-3716

### Android version

7.0

### Device

Redmi Note 4

### Other details

I have already done steps in dont-kill-my-app but no luck

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Other people have had various issues with MiXplorer before. Try using another file explorer app.
