### ISSUE TITLE
Manga page loading icon too high up

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5808]
### Steps to reproduce

Load a manga

### Expected behavior

Below top bar, unobstructed by notch/punch hole

### Actual behavior

In between status bar and top bar

![IMG_20210828_074405](https://user-images.githubusercontent.com/63973749/131198671-ab8dbb5c-9d39-4db7-a35c-ddfafcf8dcd2.jpg)

### Tachiyomi version

r3716

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Other details

(Edit) Pull to refresh is normal. Only bugged on initial loading (opening a manga first time).

![IMG_20210828_074924](https://user-images.githubusercontent.com/63973749/131198846-4ed087ab-c536-45a6-96ac-09a68a397296.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Chapter selection menu also is too low.

![IMG_20210828_180038_437](https://user-images.githubusercontent.com/59261191/131217184-d2ac3403-5378-49f1-a40d-6e4deef600ec.JPG)

**Comment by vengiare** [comment]
> Chapter selection menu also is too low. (From time to time)

I already made an issue for that; #5775
