### ISSUE TITLE
Manga / Setting "Set do default" on all library crashes the app

### ISSUE THREAD

**Issue by Nydid** [tachiyomiorg/tachiyomi#5809]
### Steps to reproduce

![Screenshot_20210828-050114__01](https://user-images.githubusercontent.com/30263820/131204301-ffddfd08-1653-4497-a9c8-d267ae688c64.jpg)
![Screenshot_20210828-050122__01](https://user-images.githubusercontent.com/30263820/131204314-b77bb09c-6cd2-422a-b2b8-6f52163aedfe.jpg)
![Screenshot_20210828-050106__01](https://user-images.githubusercontent.com/30263820/131204317-a4e41bf9-9345-4808-aa68-1b734d182475.jpg)

### Expected behavior

Sorting Options / Filters should be applied to all the manga in library

### Actual behavior

With a LOT of manga titles in library, the app freezes and crashes. Upon restart, settings were not applied to library

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7070060/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Oneplus 7 Pro

### Other details

- 1000+ Manga in library
- Rooted ( Shouldn't affect )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Tested with 1053, can't reproduce.
Can you load your library on preview and see if it works with less manga?

**Comment by Nydid** [comment]
Re-did the tests. It still crashes on Stable with less manga BUT it doesn't crash on Preview with the original manga count

**Comment by arkon** [comment]
There's probably optimizations to be made in the SQL queries, but you can try clearing your database from the advanced settings first.

**Comment by Nydid** [comment]
Clearing database seems to have fixed the crashing issue
