### ISSUE TITLE
App lagging, freezing, then crashing trying to use while library is updating

### ISSUE THREAD

**Issue by Khan-MC** [tachiyomiorg/tachiyomi#5811]
### Steps to reproduce

Open app
Update library

### Expected behavior

It shouldn't be crashing

### Actual behavior

It crashes

### Crash logs

--------- beginning of crash
08-25 08:21:04.949 25084 25084 E AndroidRuntime: FATAL EXCEPTION: main
08-25 08:21:04.949 25084 25084 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 25084
08-25 08:21:04.949 25084 25084 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
08-25 08:21:04.964 25084 25707 E AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
08-25 08:21:04.964 25084 25707 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 25084
08-25 08:21:04.964 25084 25707 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
08-28 07:44:13.740  6384  6384 E AndroidRuntime: FATAL EXCEPTION: main
08-28 07:44:13.740  6384  6384 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 6384
08-28 07:44:13.740  6384  6384 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.performDrag(ViewPager.java:7)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:36)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:15199)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:15458)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9874)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9712)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9665)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10008)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9954)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10050)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:737)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
08-28 07:44:13.740  6384  6384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: FATAL EXCEPTION: main
08-28 07:48:33.281  7184  7184 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 7184
08-28 07:48:33.281  7184  7184 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.performDrag(ViewPager.java:7)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:36)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:15199)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:15458)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9874)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9712)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9665)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10008)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9954)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10050)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:737)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
08-28 07:48:33.281  7184  7184 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
--------- beginning of system
--------- beginning of main
08-28 10:47:41.605  3000  3000 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
08-28 10:54:42.416  7972  7972 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
08-28 10:57:38.865  7972 11511 E SQLiteLog: (284) automatic index on C(manga_id)
08-28 10:57:38.865  7972 11511 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.12.1 (standard, 85791a9, 67, 2021-08-06T21:36Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.M215FXXU2BUG2
Device brand: samsung
Device manufacturer: samsung
Device name: m21
Device model: SM-M215F
Device product name: m21nnxx

### Tachiyomi version

Stable 0.12.1

### Android version

Android 11

### Device

Samsung Galaxy M21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Related/same issue:
https://github.com/tachiyomiorg/tachiyomi/issues/5793
https://github.com/tachiyomiorg/tachiyomi/issues/5064
Likely the updating manga covers/metadata causing the app to crash.
