### ISSUE TITLE
Uniform Themes

### ISSUE THREAD

**Issue by chocoblin** [tachiyomiorg/tachiyomi#5812]
### Describe your suggested feature

All themes available except 'Blue' have complete white top and bottom bars. Whereas the 'Blue' theme has blue top and bottom bars
I want to switch the color but ultimately it looks so white, that i have to revert back to the 'blue' theme.
We should have the option to enable(for guys like me, who like the screen sandwiched between a particular color) or disable(for people happy with current theme system) that feature of top and bottom bars color or white.

### Other details

Basically, ability to switch the major blue areas in the 'Blue' theme with any other available colors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
A bit tangential but worth a try: did you try the `Tako` theme? It isnt like the Blue Theme but it isn't like a complete White which you have difficulty with. The new theme should be available in app version 0.12.1

Btw, regarding the top bar in manga info, that will soon be [transparent](https://user-images.githubusercontent.com/12537387/127102139-f39de787-2093-4cf9-a858-3fe8d3ba68a4.png) so maybe that helps as well?

**Comment by Soitora** [comment]
Tangent: It's already a legacy theme that shouldn't get spread 💀

**Comment by chocoblin** [comment]
@curche i actually did try tako. it seems..strange to the eyes. thanks for the heads up tho! 
also, i'm not at all affected by the manga page, rather it would be great if it looks the way ur screenshot shows.

**Comment by chocoblin** [comment]
@Soitora i'm really sorry but i don't quite understand what u said..

**Comment by arkon** [comment]
Blue theme is the only exception since it's the old theme. It's actually causing more issues to keep it around, so to be "uniform", it'd be more likely that it'd be removed than the other ones changed.
