### ISSUE TITLE
New Tablet UI threshold removed it from e-ink reader

### ISSUE THREAD

**Issue by CTalvio** [tachiyomiorg/tachiyomi#5813]
### Describe your suggested feature

I use Tachiyomi on a 7.8", 1404x1872, e-ink reader (likebook Ares), on which scrolling sucks. So the more compact chapter screen of the new tablet UI was very welcome. However, I just installed the latest update (12.1) and it seems the threshold where tablet UI is enabled changed, this returns my device to the mobile UI.

I would very much like for a way to continue using the tablet UI on my device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
You can turn on developer settings and set your DPI to 720, which is the DPI that tablet UI triggers at

**Comment by CTalvio** [comment]
@loocool2 No it isn't. I'm afraid that's not how DPI works, friend. To make apps think the screen is larger than it is, you set the number lower, not higher.

The threshold was set to 720dp on the shortest width, which granted, on some devices is the actual setting and unit of measure present in developer settings. But dp is not DPI. dp is a unit of measure used by android to determine real screen size and scale UI accordingly. On a 160 DPI screen, 1dp=1pixel, on a 320 DPI screen 1dp=2pixels, and so on.

My device runs at 320 DPI (though it's physically closer to 300) and has the horizontal resolution of 1404px. That means it comes in at 702dp. Just shy of the limit. The developer settings do not allow for a change in DPI or dp, as the version of android this thing runs is heavily modified.

I can set app specific DPIs through the optimize feature, but this only changes UI scale, it does not trigger the tablet UI to activate. Not that I would want to use the app at a DPI that much lower, with how tiny the UI gets.

**Comment by vengiare** [comment]
0df23ab deals with this issue, could be closed now.

**Comment by CTalvio** [comment]
Thank you, I'll can eagerly await the next release, now.
