### ISSUE TITLE
UI adjustments for tabs less than 10 inches

### ISSUE THREAD

**Issue by DishankJ** [tachiyomiorg/tachiyomi#5816]
### Describe your suggested feature

It seems like TabletUI was available to tabs less than 10 inches before but now has been removed which I believe is because of the backlash which is kinda sad. I think it'd be great if:
1. The cover size on manga info page was increased (refer to the attachment)
2. In manga info page in landscape mode the chapters appeared in a different column on the right and the manga info and cover on the left like in the attachment.
I don't think the first suggestion is likely to receive much backlash or hate since that just makes better use of the big screen size. However I'm not sure about that for the second suggestion but I'd appreciate if it was approved of.

### Other details

![Screenshot_20210829-120913_TachiyomiJ2K](https://user-images.githubusercontent.com/72161562/131249896-0ca548b7-e6f9-4cd7-a5ca-4a34176de984.jpg)
![Screenshot_20210829-120841_TachiyomiSY](https://user-images.githubusercontent.com/72161562/131249900-56914f60-a1fd-4209-a5f6-58d6335d1880.jpg)
![Screenshot_20210829-173804_Tachiyomi](https://user-images.githubusercontent.com/72161562/131249905-2aa9788b-c6bd-45d8-b120-a8b75613822d.jpg)
![Screenshot_20210829-174624_TachiyomiJ2K](https://user-images.githubusercontent.com/72161562/131250050-35a31251-8394-424d-b23c-c7a383755c20.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
If 0df23ab solves your initial problem (TabletUI was available to tabs less than 10 inches before but now has been removed) this could be closed.
