### ISSUE TITLE
Hide line breaks in info only when collapsed

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5817]
### Describe your suggested feature

Since #5771 line breaks were being removed. I'm guessing it's only intended for collapsed but also got applied to expanded info.
@curche 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by aldren0930** [comment]
Can you ask them add zinchanmanga.net on extensions?
