### ISSUE TITLE
Chips getting cut on manga info first load

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5819]
### Steps to reproduce

Browse -> Any source -> Any manga that hasn't been opened

### Expected behavior

Chips expanded

### Actual behavior

![IMG_20210830_022624](https://user-images.githubusercontent.com/63973749/131261765-e8ce260a-6707-4d62-b19d-c6a475b17657.jpg)

### Tachiyomi version

r3756

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't think this is an issue anymore.
