### ISSUE TITLE
Manga info not expanding/collapsing when clicking on a certain area

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5820]
### Steps to reproduce

Expand/collapse info (i think somewhere in between info and chips)

### Expected behavior

Fully expand/collapse

### Actual behavior

Expansion issue
https://user-images.githubusercontent.com/63973749/131262149-bc25894f-fb5a-49fb-b435-9457b0ca8cd8.mp4

Collapse issue
https://user-images.githubusercontent.com/63973749/131262152-dbdd4df1-24da-43de-89e4-a83d0577b48b.mp4

### Tachiyomi version

r3756

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
The collapse issue should have been fixed with #5854

As for the expansion issue you have never been able to click tags to expand so I don't see it as an issue
