### ISSUE TITLE
Tachiyomi crashes

### ISSUE THREAD

**Issue by Atsuya12** [tachiyomiorg/tachiyomi#5821]
### Steps to reproduce

Example:
1. I open the app
Issue: it crashes right away

### Expected behavior

The app should open like normal, and allow me to use it.

### Actual behavior

Instead of starting like normal, the app crashes as soon as I open it, preventing me from using it at all.

### Crash logs

[dumpstate_log.txt](https://github.com/tachiyomiorg/tachiyomi/files/7073547/dumpstate_log.txt)

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Samsung Galaxy A30s

### Other details

The problem started out of nowhere, since I didn't change anything and now I can't even download other forks that are based on tachiyomi, because the same issue happens.
I'll also provide a video with what is going on

https://user-images.githubusercontent.com/89753692/131272908-fddcc1d2-5481-426a-b4b8-831e83f2e96f.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Post crash logs.

**Comment by Atsuya12** [comment]
> Post crash logs.

Can I only get crash logs from the tachiyomi app? Because if that's the case I can't do it, since the app crashes every time I try to open it.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by arkon** [comment]
If you have the Tachidesk extension, try uninstalling that.

**Comment by Atsuya12** [comment]
> Please provide crash logs if possible.
> 
> Potential ways of getting them:
> 
> * More → Settings → Advanced → Dump crash logs
> * https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
> * https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

is that the right file? there's another one, but it's probably too big to drag and drop it, since it has 103MB

**Comment by Atsuya12** [comment]
I posted a video with what is going on with my app

**Comment by arkon** [comment]
Proper logs were never posted, so going to close this. Open another issue if you still have problems.
