### ISSUE TITLE
Relocate Downloaded only/Incognito mode banner

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5833]
### Describe your suggested feature

The current one is a bit jumpy when switching from screens with a tab bar to screens without.

![IMG_20210901_044339](https://user-images.githubusercontent.com/63973749/131574476-581ae106-2b63-4f90-a179-1a1b9c079e32.jpg)
![IMG_20210901_044329](https://user-images.githubusercontent.com/63973749/131574487-8a98fcb8-1a26-4d46-9e98-e1ba4c097446.jpg)

And it also doesn't look quite good with edge-to-edge manga info.

![IMG_20210901_044424](https://user-images.githubusercontent.com/63973749/131574499-e26e6995-7a16-42dd-812c-8c865175e61e.jpg)

I think either above top bar or bottom of the screen would be better. It wouldn't jump around, it won't cut the edge-to-edge manga info in an awkward spot, and it's used by most apps that have a top banner (Discord call/connecting, Maps incognito) or bottom banner (YouTube) of some sort. 

~~no more jumpy boi~~ 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Should probably go on the bottom. I don't think anything should go above top app bar

**Comment by vengiare** [comment]
Yeah YouTube is one example of an app that has bottom banners (Incognito/No connection) so that's also a good idea. Modified the issue.

**Comment by arkon** [comment]
The existence of the tab bar or even the toolbar is inconsistent across screens, so no plans to do this.
