### ISSUE TITLE
don't change the comic info display

### ISSUE THREAD

**Issue by Gamefire238** [tachiyomiorg/tachiyomi#5835]
### Steps to reproduce

don't change comic info display v0.12.1 to r3756

v.0.12.1
![IMG_20210901_114033](https://user-images.githubusercontent.com/78879425/131612009-1f60c1ff-a0dc-4930-a0d5-ba343e18be44.jpg)

I think the comic info display v0.12.1 is good and doesn't need any changes.

I also marked the white block above the cover because I like it, because it can disguise the bangs of my phone if the black theme is turned on, I hope it's not removed in the latest stable version, I think the view would be neater if it existed.

Sorry for my selfishness. 

### Expected behavior

I hope the comic info display is not changed in the latest version

### Actual behavior

I have explained above.

### Tachiyomi version

r3756

### Android version

Android 11

### Device

VIVO Y12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
no

**Comment by CrepeTF** [comment]
May I interest you in [TachiyomiAZ](https://tachiyomi.org/forks/TachiyomiAZ/)?

**Comment by Gamefire238** [comment]
Too bad, Thank you for the advice.

**Comment by arkon** [comment]
If you don't want your notch to show up, don't buy a phone with a notch.
