### ISSUE TITLE
TabletUI dissapeared after update

### ISSUE THREAD

**Issue by michalzxc** [tachiyomiorg/tachiyomi#5839]
### Steps to reproduce

Update to 1.12.1
Use Samsung Galaxy Tab S5E

And it is gone, it is a 10-inch tablet, phone menu is just impractical 

### Expected behavior

I expected it to still be there

### Actual behavior

Phone UI

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Samsung Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Yes, it's mentioned in the changelog that it now requires smallest width 720dp.

**Comment by michalzxc** [comment]
I don't know what dp s5e has, but it was working perfectly with it, there is no reason to disable it
Could you add some checkbox in options ?

**Comment by arkon** [comment]
It was changed based on feedback (of which there was much more than people who wanted it back after the more recent change).

Irregardless, #5830
