### ISSUE TITLE
Unparsable date

### ISSUE THREAD

**Issue by RickieTS** [tachiyomiorg/tachiyomi#5841]
### Steps to reproduce

1. Open "browse"
2. Open "heavenmanga"
3. Select 1 manga
4. It said "unparsable date '22 minutes ago'" (example)

### Expected behavior

The amount of chapter

### Actual behavior

Shows nothing

### Tachiyomi version

Stable 0.12.1

### Android version

Android 11

### Device

Vivo 1901

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.
