### ISSUE TITLE
Category Tab Still showing when disabled

### ISSUE THREAD

**Issue by ColinLabDev** [tachiyomiorg/tachiyomi#5842]
### Steps to reproduce

1. Disable Show category tabs
2. Read a manga 
3. then click the title
4. return to library

### Expected behavior

Category tab should still be hidden

### Actual behavior

category tab is duplicated

### Tachiyomi version

preview r3756

### Android version

android 9

### Device

JKM-LX2 Huawei Y9 2019

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment]
There are a few other triggers for this, like rotating your device in the library screen.
