### ISSUE TITLE
Reader Bottom Buttons ( add a new one for scale type).

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#5843]
### Describe your suggested feature

Pretty self explanatory, add a new button for scale type so you can instantly switch between them.

### Other details

I always switch between original size and fit screen because in mangadex or nhentai, the image quality are always changing, i like to use original size for most mangas and sometimes they are a perfect fit for the  screen on my phone but sometimes the image is too high of a quality or too low so they get stretched or theyre too small and you cant read the dialogue properly and i switch to fit screen or smart fit so that its perfect.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
No more buttons, just use fit screen.
