### ISSUE TITLE
Global update not being cancelled

### ISSUE THREAD

**Issue by Retashe** [tachiyomiorg/tachiyomi#5844]
### Steps to reproduce

Coloco a biblioteca para atualizar e não consigo cancelar

### Expected behavior

Eu deveria conseguir colocar para atualizar, e conseguir cancelar a hora que eu quiser

### Actual behavior

Coloco para atualizar e quando clico em Cancelar, a notificação de atualização desaparece e volta a reaparecer, continuando a atualização

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Xiomi Redmi Note 10

### Other details

Ter que clicar umas três vezes para cancelar de fato a atualização
(Três vezes ou mais)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Can reproduce in 0.12.1 but can't in r3598.
One of the changes between 14/07 and 06/08 broke it.

**Comment by arkon** [comment]
It's probably just dependant on the particular jobs being run at that time. I'll make it so it stops updating the notifications after the initial cancellation.
