### ISSUE TITLE
Downloaded Icon Error

### ISSUE THREAD

**Issue by blameitonlag** [tachiyomiorg/tachiyomi#5845]
### Steps to reproduce

![Screenshot_20210904-021406_Tachiyomi](https://user-images.githubusercontent.com/20156844/132056056-af4dfeb4-04c6-440a-a17f-23b5088b8597.jpg)
that one manga (solo leveling) keep showing that i have 1 downloaded chapter. but the fact there's nothing, i always deleted it after reading.

### Expected behavior

it should be gone after i deleted it

### Actual behavior

the mark still linger

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Samsung A6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That means there's an orphaned download. You can delete it from a file manager.

**Comment by paulo27ms** [comment]
Relateish feature: https://github.com/tachiyomiorg/tachiyomi/issues/1767
