### ISSUE TITLE
Updating category randomly shows all chapters of every manga in category in update list

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#5847]
### Steps to reproduce

Add a bunch of manga to a category
After a few days, when a new chapter is available, use the update tab to check for updates in that category.
The new updates will show up in the tab
But along with the updates, previously read chapters of every other manga in category also show up

### Expected behavior

Only manga with updates show up with the respective chapters

### Actual behavior

Every chapter shows of un updated manga.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

galaxy S9+

### Other details
![tachi bug](https://user-images.githubusercontent.com/30620767/132083765-486285e5-0721-46a6-9056-c21ac079d4df.jpg)

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> previously read chapters of every other manga in category also show up

Which sources are these manga chapters from? Are they from the same source?

**Comment by rsmyst** [comment]
@curche 
That's rgt. It's all from the source 1st kiss (en)

**Comment by arkon** [comment]
That implies the source updated all of the chapters in some way (re-uploaded, changed names, changed URL, etc.).

App is working at intended.
