### ISSUE TITLE
Migrate multiple mangas at the same time

### ISSUE THREAD

**Issue by RickieTS** [tachiyomiorg/tachiyomi#5856]
### Describe your suggested feature

1. Select multiple manga

### Other details

Uninstall multiple extension at the same time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#1231
