### ISSUE TITLE
New chapter notifications don't show when you already have notifications open from a previous library update

### ISSUE THREAD

**Issue by naturemarth** [tachiyomiorg/tachiyomi#5859]
### Steps to reproduce

1. Update library for new chapter updates
2. wait for new chapter updates to become available
3. don't swipe away previous chapter update notifications
4. Update library for new chapter updates

### Expected behavior

The list of notifications is appended with the new chapter updates

### Actual behavior

No new chapter updates are added to the list of noticifations ( or sometimes only one random is added) and the new chapters are only visible in the updates tab

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Motorola one action

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6776
