### ISSUE TITLE
[bug report] Bangumi tracking issues

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi#5860]
### Steps to reproduce

The bangumi track cookie will expire in about a week.

### Expected behavior

none

### Actual behavior

none

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Redmi K40

### Other details

The cookie of Bangumi Track will expire in about a week, It cause login failure(Prompt HTTP error 401) and have to log in again.Hope to fix this bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mutsumi63** [comment]
是bangumi的问题
换ip也会掉登入

https://bgm.tv/group/topic/349466

**Comment by ZerOri** [comment]
> 是bangumi的问题
> 换ip也会掉登入
> 
> https://bgm.tv/group/topic/349466

不是吧，那就是说无解了么😭

**Comment by arkon** [comment]
Is there something that we're supposed to do?

**Comment by ZerOri** [comment]
> Is there something that we're supposed to do?

Sorry,I don't know if this is tachiyomi or Bangumi's problem,I also reported this bug on Bangumi.Someone said it was Tachiyomi‘s problem, and someone said it was Bangumi’s problem.😂

**Comment by mutsumi63** [comment]
It is Bangumi’s problem. 
If you change your ipaddress or user-agent , bangumi's api will return 401(means token expired),then you need relogin. 
It is same problem in the bangumi web site.

**Comment by ZerOri** [comment]
> It is Bangumi’s problem.
> If you change your ipaddress or user-agent , bangumi's api will return 401(means token expired),then you need relogin.
> It has the same problem with bangumi‘s web site.

OK,now I see,thanks for your answer!
