### ISSUE TITLE
Per-manga settings for scale and zoom start

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#5861]
### Describe your suggested feature

In the settings modal, only `Viewer for this series`/`Default viewer` is per-manga. It is also the only option which has `Default` as an option.

For example, if your global reader setting for `Scale type` is `Fit height`, changing this to `Stretch` in the modal will make all manga open with that setting.

This is particularly annoying with many manhwa, which are generally read left-to-right - as I have the zoom start position on the right and swiping right to left. Which means until all the settings are per-manga I have to swipe the page to the left every page, or change the reader settings every time going from manga -> manhwa -> manga.

Version: r3783

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by wopian** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/452 was closed without addressing the two requested options.

**Comment by arkon** [comment]
As I explicitly wrote in the other issue:

> if there's specific ones wanted, please create **individual issues** for those.
