### ISSUE TITLE
Add a New Tracking Site; Kenmei

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi#5870]
### Describe your suggested feature

Basically add in the Kenmei.co tracking site to the list of manga/manhwa/manhua trackers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
No
![Screenshot_20210907-102847.jpg](https://user-images.githubusercontent.com/70870719/132321108-254ed134-f600-4c8c-934d-2522d6a65bf2.jpg)
