### ISSUE TITLE
Scale Type: Original Size shows small sized image

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi#5874]
### Steps to reproduce

Open a chapter
Set scale type to Original Size

### Expected behavior

On SumatraPDF there is this ActualSize zoom mode and the quality is a lot better than on Tachiyomi. I'm using the same files.

![Screenshot_6](https://user-images.githubusercontent.com/76444133/132402930-6e6ebbd9-a72b-4c80-a108-077617a2146b.jpg)

### Actual behavior

A small sized version of the image is shown.

![screenshot](https://user-images.githubusercontent.com/76444133/132403021-4d4e809f-911f-4d7a-8c56-88b85a609e55.jpg)

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Xiaomi Mi 10T Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That's how display scaling works. Is your Windows device the same resolution and scale?

**Comment by AlexMiniReal** [comment]
How can I see that?

**Comment by arkon** [comment]
Your system preferences.

A bit more about it if you're unfamiliar: https://www.howtogeek.com/302916/what-is-the-difference-between-scaling-and-screen-resolution-in-windows/

Regardless, actual size is based on resolution/scaling. "Physical" size means nothing.

**Comment by AlexMiniReal** [comment]
This is my phone resolution.
![photo](https://user-images.githubusercontent.com/76444133/132510649-ca9e6e51-6b1f-4f41-bb1e-45b0e99311d2.jpg)

This is my monitor resolution. 1920x1080

Shouldn't my phone get better image because it has more pixels?

**Comment by CrepeTF** [comment]
> Shouldn't my phone get better image because it has more pixels?

If your phone has a higher resolution the image would be smaller, since there would be more pixels in one area, and the image is only X pixels wide.

**Comment by vengiare** [comment]
![image](https://user-images.githubusercontent.com/63973749/132511938-af10198d-519e-4a59-ac21-bd71cf595329.png)

Your phone screenshot (left), and your pc screenshot (right)
