### ISSUE TITLE
Custom download for new chapters

### ISSUE THREAD

**Issue by Lmmb74** [tachiyomiorg/tachiyomi#5880]
### Describe your suggested feature

Hello. I would like to be able to choose the manga I want to be downloaded when new chapters are found, instead of downloading every new chapter found for every manga on my library. You should be able to select them from either the manga itself or the Downloads section under Settings (where you could manage your currently selected manga). If such an option is already integrated, or a ticket for such a feature has already been submitted, I'm afraid I have not found either. Thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Use [Categories](https://tachiyomi.org/help/guides/categories/) and then set up Download new chapters only for the categories which you want to
