### ISSUE TITLE
Manga page top bar not updating when scrolliing

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5888]
### Steps to reproduce

Scroll in manga info (can't reproduce it reliably, only sometimes)

### Expected behavior

Sometimes transparent when scrolling to top, Sometimes opaque when scrolling

### Actual behavior

(edit:) still reproducible, r3999

![Screenshot_20211205-093146](https://user-images.githubusercontent.com/63973749/144729920-90ccedcb-90cf-4117-b395-8c8461374c76.png)
![Screenshot_20211205-093158](https://user-images.githubusercontent.com/63973749/144729925-75913c6f-107a-4e63-95bb-a5b965b7eced.png)

### Tachiyomi version

r3783

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
not really need fast scroll, just normal swipe till turn opaque will be the same

**Comment by vengiare** [comment]
I couldn't really recreate the bug even a single time with just scrolling and I tried a lot

**Comment by Riztard** [comment]
https://user-images.githubusercontent.com/16263232/132946199-71da2cfb-1fc9-42ed-98e6-163a14d3fc2d.mp4

**Comment by CVIUS** [comment]
I cannot reproduce this bug. Idk if this still persist.
