### ISSUE TITLE
Snap toolbar and bottom navigation on scroll

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi#5889]
### Describe your suggested feature

Hide the top and bottom section like the animation in TachiyomiJ2K. Thats it. TYSM❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Did you mean the following setting?
> Hide bottom nav on scroll

If not, atleast provide a video example

**Comment by tanuukii** [comment]
No, not that. And I only have limited data right now so I can't send a video, sorry. But you can see it in TachiyomiJ2K. Observe how the bottom navigation thing and the search bar hides when you scroll. Its different to Tachiyomi.

**Comment by arkon** [comment]
You're going to have to be much more specific.

**Comment by tanuukii** [comment]
In TachiyomiJ2K, the bottom navigation thing automatically hides like this. 

https://user-images.githubusercontent.com/87689027/132949638-1ec1fdd8-d344-434f-bf84-259987a84310.mp4

And in Tachiyomi, it remains like this when you suddenly stop scrolling.
![Screenshot_20210911-213039201 (1)](https://user-images.githubusercontent.com/87689027/132949693-d8bb51e9-b763-4bed-b132-9ff6cd054255.jpg)

**Comment by tanuukii** [comment]
For the header/search bar (idk if it is called header), in TachiyomiJ2K, it also automatically hides like this.

https://user-images.githubusercontent.com/87689027/132950046-729333cf-a817-4402-be3a-35deeaf828a1.mp4



In Tachiyomi, same case to the bottom navigation thing. It gets cut and remains like this.
![Screenshot_20210911-213059030 (1)](https://user-images.githubusercontent.com/87689027/132950094-6740a570-518b-4139-b341-3385b78b289d.jpg)



Better video example of my suggestion from Facebook app.

https://user-images.githubusercontent.com/87689027/132950112-c66cf940-2f1f-45f9-abf9-38e3c50ad940.mp4

**Comment by vengiare** [comment]
This was intentionally changed in #5603, maybe ask them about that.

**Comment by vengiare** [comment]
> And in Tachiyomi, it remains like this when you suddenly stop scrolling.

#5603 was the commit that made this change afaik. It's related I believe.

**Comment by arkon** [comment]
It's tangentially related. From a technical perspective, the previous implementation was the built-in behaviour of automatically snapping. The requested behaviour does not match that as it also respects scroll position too.
