### ISSUE TITLE
Preview builds should be submitted to F-droid as experimental builds.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [tachiyomiorg/tachiyomi#5891]
### Describe your suggested feature

The preview builds of [Tachiyomi](http://staging.f-droid.org/packages/eu.kanade.tachiyomi) should be submitted to [F-droid](http://f-droid.org)  as experimental builds so that testers are able to automatically update to the most recent preview builds of [Tachiyomi](http://staging.f-droid.org/packages/eu.kanade.tachiyomi) via [F-droid](http://f-droid.org).

### Other details

The update cycle for preview builds is purportedly 7 days, so this should not be difficult to integrate due to slow build times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
F-Droid specifically removed Tachiyomi due to the copyright claim by Comeso GmBH https://gitlab.com/fdroid/admin/-/issues/195

**Comment by arkon** [comment]
F-Droid doesn't give you the ability to automatically update apps either anyway, does it? There's no upside to it.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/tachiyomiorg/tachiyomi/issues/5891#issuecomment-917481452

F-Droid is able to perform automatic updates.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/tachiyomiorg/tachiyomi/issues/5891#issuecomment-917480914

Until http://gitlab.com/fdroid/admin/-/issues/195 is resolved, I am doubtful that this issue should be closed because many users have installed Tachiyomi via F-Droid.

**Comment by arkon** [comment]
You're barking up the wrong tree here. We don't support F-Droid, and they're the ones that removed us from their prod stage. If you can convince them to resurface it, then you can also have someone (such as yourself) do the work to include the preview builds too. 

There's already people that still maintain the F-Droid staging version of stable Tachiyomi, but they have no affiliation with us.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/tachiyomiorg/tachiyomi/issues/5891#issuecomment-917480914

[The issue](http://gitlab.com/fdroid/admin/-/issues/195) that [@loocool2 ](http://github.com/loocool2) has specified is eight months old, and [Tachiyomi](http://github.com/tachiyomiorg/tachiyomi) [is available at F-droid](http://staging.f-droid.org/packages/eu.kanade.tachiyomi) regardless.

**Comment by CarlosEsco** [comment]
> > http://github.com/tachiyomiorg/tachiyomi/issues/5891#issuecomment-917480914
> 
> [The issue](http://gitlab.com/fdroid/admin/-/issues/195) that [@loocool2 ](http://github.com/loocool2) has specified was posted during approximately eight months before now, and [Tachiyomi](http://github.com/tachiyomiorg/tachiyomi) [is available at F-droid](http://staging.f-droid.org/packages/eu.kanade.tachiyomi) regardless.

Either way we don't support fdroid. Go talk to them
