### ISSUE TITLE
Language badge

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi#5893]
### Describe your suggested feature

I've installed the preview version out of curiosity and noticed that the language beside the source name inside the manga is gone.

My suggestion is like this.
![Screenshot_20210912-125937329 (1)](https://user-images.githubusercontent.com/87689027/132972960-19cb3e30-c0be-45d7-9f59-049d78ee74e7.jpg)

It can be turn on/off just like the other badges found under the display option. With this, us users will be aware what languages the manga is in our library.

Oh! I also think that maybe we can categorize by language too. But that will be in another issue once this is considered. TYSM❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> ### Describe your suggested feature
> I've installed the preview version out of curiosity and noticed that the language beside the source name inside the manga is gone.

It isn't actually gone it is hidden if only one language is enabled ("All" isn't considered a language so "All" will always be shown regardless) nevertheless this is actually a good suggestion (maybe the option for language badge will also be hidden if only 1 language is enabled but in this case "All"  should also be counted)
