### ISSUE TITLE
Browse loading animation gets stuck after closing and reopening the app. 

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#5897]
### Steps to reproduce

1. Tap on Popular or Latest of a source.
2. Force close the app while the source is still loading.
3. Open the app from recent. 

### Expected behavior

Loading Animation to Animate. 

### Actual behavior

Loading animation stays stuck just like the image

![Bato.to Popular](https://user-images.githubusercontent.com/59261191/132992006-10844214-e76d-4d10-abc1-e5da634182f1.png)

### Tachiyomi version

r3799

### Android version

Android 6

### Device

LAVA iris820

### Other details

Browse works as intended just the animation gets stuck. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AliyaGarcia** [comment]
Same for me

**Comment by AntsyLich** [comment]
Seems to be fixed with compose rewrite
