### ISSUE TITLE
gnirehtet, tachiyomi doesnt detect internet connection

### ISSUE THREAD

**Issue by Xellerate005** [tachiyomiorg/tachiyomi#5899]
### Steps to reproduce

1.first using a computer run gnirehtet it will use adb and share the internet between the computer and the phone
2.open tachiyomi Az and download any chapter

### Expected behavior

the chapters should download as expected

### Actual behavior

the app states that it requires an internet connection and doesnt download chapters, even though internet is available on other internet based apps seem to work fine

### Tachiyomi version

v8.6.5-AZ

### Android version

Android 11

### Device

Samsung Galaxy A20e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
https://github.com/az4521/TachiyomiAZ

**Comment by Soitora** [comment]
This is not support for an outdated fork such as **TachiyomiAZ**.

**Comment by az4521** [comment]
oi my fork isnt outdated

**Comment by arkon** [comment]
![Screenshot_20210912-172011_Discord.png](https://user-images.githubusercontent.com/4098258/133003138-142a11f7-dfd5-4faf-be92-0ef3d47def76.png)

AZ summarized it well here.
