### ISSUE TITLE
Dual Page For Pc/Tablet Users!!

### ISSUE THREAD

**Issue by Clash-Kage** [tachiyomiorg/tachiyomi#5902]
### Describe your suggested feature

Dual Page : For users on Tablets or PC's It maybe helpful if they add a dual Page feature in which instead of 1 ,2 pages show up on the scree than can be invested or changed according to pretence I have been using Tachiyomi for long now but I miss this feature that I used to have on other sites keep up the great work Work I can freely recommend my friends that this is the best way to read manga ... have a great day

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/149

**Comment by Clash-Kage** [comment]
Why'd you close sry I am new to GitHub idk what it means

**Comment by CarlosEsco** [comment]
we don't allow duplicate open issues.

**Comment by Clash-Kage** [comment]
That means the request is bieng addressed thank you very much

**Comment by CarlosEsco** [comment]
It means someone already suggested the feature, there is no guarantee it gets added
