### ISSUE TITLE
Library sort feature

### ISSUE THREAD

**Issue by mekodke** [tachiyomiorg/tachiyomi#5907]
### Describe your suggested feature

It should have a label to sort by last downloaded

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
You can sort by "latest chapter".

**Comment by arkon** [comment]
Downloaded state doesn't really exist within the app since it just checks if they exist.
