### ISSUE TITLE
Can't change app language

### ISSUE THREAD

**Issue by GlassedSilver** [tachiyomiorg/tachiyomi#5908]
### Steps to reproduce

I tried to follow the guide as described in the app help:

```
You can change language by going to more_horiz
 More → settings
 Settings → tune
 General then pressing Language.
```

### Expected behavior

To find a language setting.

### Actual behavior

Can't find the setting :/

![Screenshot_20210914_141148_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/1912133/133255321-119b3bdd-e62f-4607-a390-51ed4a53b946.jpg)

### Tachiyomi version

App version: 0.12.2-3812 (standard, 3eec20716, 68, 2021-09-13T19:17Z) 

### Android version

Android version: 9 (SDK 28) Android build ID: SHT-W09 9.1.0.335(C432E3R1P2)

### Device

HUAWEI MediaPad M5 8.4" (model: SHT-W09)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the changelog: https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.2

**Comment by GlassedSilver** [comment]
Awww shucks... :(

Thanks for the quick reply though.

**Comment by kice** [comment]
I would like to know why not just leave the option there, and warn the user if they want to change the language.

**Comment by alessandrojean** [comment]
The reason is in the changelog

> App now uses same language as rest of the device due to issues it caused with theming and layouts

**Comment by GlassedSilver** [comment]
Always worked wonderfully for me, though. Having the choice in case it works would be awesome, gotta agree with @kice here.

Warning + choice > not even being able to figure out if you're lucky for it to work.

I'm German, but I'd much rather use the app in English like I always have.

Longterm it'd be awesome if Android let you set language per app on a system level. Ugh
