### ISSUE TITLE
Automatically set tracker reading start date

### ISSUE THREAD

**Issue by EstebanOD** [tachiyomiorg/tachiyomi#5909]
### Describe your suggested feature

Clicking on the tracker would automatically add the start date to MAL, and if it doesn't, there should be an easy way to know when you've started reading the manga/manwha.

### Other details

It's been a few weeks I'm reading Juujika no Rokunin, today I decided to add it to MAL, but there's no way to know when I've started reading the manwha!
I can only know when I've read the last chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by EstebanOD** [comment]
Uh, this is not about anime tf. 😐

**Comment by paulo27ms** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/3058
You can check on MAL's history for each manga to see when you read a chapter and see the date (assuming Tachiyomi updated the chapter count).

**Comment by EstebanOD** [comment]
> #3058
> You can check on MAL's history for each manga to see when you read a chapter and see the date (assuming Tachiyomi updated the chapter count).

Um probably yeah idk, but this isn't the issue; the issue is that I cannot check the date I started reading a manga on Tachiyomi
