### ISSUE TITLE
Matching indicator in library search 

### ISSUE THREAD

**Issue by putzmarcos** [tachiyomiorg/tachiyomi#5914]
### Describe your suggested feature

When you search your library while using categories there is no easy way to see all the matches in all of them, we need to scroll through each one to know.
A feature who indicates matches would be nice

![image](https://user-images.githubusercontent.com/76596575/133444181-1db86d9c-81f8-4b01-ab66-2dc8277f32f5.png)
![image](https://user-images.githubusercontent.com/76596575/133444277-3c939437-7b70-483d-b24b-13fcf858f873.png)

Of course, it does not necessarily have to be a point/dot (something like a highlighter will do the same effect)
![image](https://user-images.githubusercontent.com/76596575/133444671-852d3826-78ee-4026-be75-11ae3f8ddbcf.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
Probably could just make the search affect "Show number of items" cause rn it doesn't. 

![IMG_20210915_222054](https://user-images.githubusercontent.com/63973749/133451264-d0ad8185-1a7e-425f-8f56-381fd5a18579.jpg)

Then for people who have the display option disabled, number of items would show up only while searching.

**Comment by Saud-97** [comment]
Also another suggestion to also filter out all categories that do not include any manga related to the search. So user will only see categories that contain manga matching the filters.

**Comment by arkon** [comment]
Show number of items now reflects search.
