### ISSUE TITLE
Page breaks are not continuous, black bar

### ISSUE THREAD

**Issue by shivamkumar13** [tachiyomiorg/tachiyomi#5918]
### Steps to reproduce

Open any webtoon
1. open chapter
2. continuous vertical scroll reader setting
3. as page/image change from one to other, not seamless continuous, as there is page/ image break , reader shows black bar (or image separated distance)

### Expected behavior

When scroll on verticle continuous, it should not show black bar on page break / image break. images should be seamless continues. 

### Actual behavior

There is a black bar at image break when moving from one image to other.

### Tachiyomi version

0.12.2

### Android version

Android 6.0.1

### Device

One plus x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
Are you sure you're using the appropriate Reading mode?

![IMG_20210916_180034](https://user-images.githubusercontent.com/63973749/133592866-598d525c-917e-4d4f-8231-c6de3e9a920b.jpg)
