### ISSUE TITLE
Slow loading all extensions

### ISSUE THREAD

**Issue by Drj0** [tachiyomiorg/tachiyomi#5919]
### Steps to reproduce

Manga pages not loading even waited for 10 min, when I go in extension they also load very slow but when I go on their site or go in web view through tachiyomi it loads instantly I can read and the site works fine. not working fine in the app
tried installing reinstalling it 3 times, cleared the cache did everything I can still the same result.
using android (android 11)
I also have a good network I don't think it's a network problem 1-2 days earlier tachiyomi was perfectly working suddenly this is happening.

extensions I have tried(only used these bcoz i find everything I want on these extensions) - 
mangalife
jaiminiBox.net
mangasee 
Readcomics online

### Expected behavior

I expected it to load manga and search manga titles normally and smoothly.titles

### Actual behavior

I expected it to load manga and search manga titles normally and smoothly. but it was loading very slow, it was like infinite loading 

### Crash logs

I have uninstalled the app so I don't have that 

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by Zackhzy** [comment]
Same bro hope they fix this 😭

**Comment by curche** [comment]
> all extension

Unless you meant [none of the 912 extensions work](https://tachiyomi.org/extensions/), please list out all Sources that you have Installed and tried
Also make sure to try each step in [troubleshoot diagnosis](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis) and report the results.
If you are still facing issues, do elaborate more, [create an issue for each Extension that is not working](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) or join the Discord server

Finally, the Disclaimer:
> Tachiyomi is not hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

**Comment by PrinceBujethia** [comment]
Same problem for me

**Comment by Zackhzy** [comment]
It is working

**Comment by Zackhzy** [comment]
Fixed

**Comment by Drj0** [comment]
thanks, it's fixed    
@Zackhzy thanks to you too for letting me know <3

**Comment by Zackhzy** [comment]
> thanks, it's fixed
> @Zackhzy thanks to you too for letting me know <3

No problem
