### ISSUE TITLE
Manga hub issue

### ISSUE THREAD

**Issue by Psycho00001** [tachiyomiorg/tachiyomi#5921]
### Steps to reproduce

1. Loading content
2. Searching manga
3. Uodating
4. Http error 520 

### Expected behavior

Content should loaded 
Library will be updated

### Actual behavior

Mangahub content cant be loaded
Manga that saved cant be update

### Tachiyomi version

0.12.2

### Android version

Andriod 9

### Device

Asus m1 max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
