### ISSUE TITLE
Search multiple ext at once with ","

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5922]
### Describe your suggested feature

for example we input `mangadex, komga` 
it will show mangadex and komga ext

### Other details

this also can be used for backup n restore purpose
for example when restoring and there is missing ext list, can add button to redirect to browse>extension and auto-fill search box 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Support regex instead?
