### ISSUE TITLE
Separate timestamps settings for manga page

### ISSUE THREAD

**Issue by kalebC** [tachiyomiorg/tachiyomi#5926]
### Describe your suggested feature

Seems like the new timestamps settings affect both the History tab and manga pages alike. I'd like there to be an option to have the setting only apply to the History tab, or maybe separate settings for each?
Basically I want to have an option to have it look like before the update. I like the long relative timestamp in History, but when I click on the manga, I'd like to see the exact publishing date on the chapters.

Hopefully these screenshots drive the point across if my explanation didn't make sense:
![IMG_20210918_024944](https://user-images.githubusercontent.com/12353487/133877825-aa37ce3e-28a1-4e64-a6b9-3c8a0d2b3e23.jpg)
![IMG_20210918_025212](https://user-images.githubusercontent.com/12353487/133877836-81add218-47ee-4dbe-9b88-7d885827e188.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
History could stay as is. Manga page could switch to a "date, relative date" format? Like "9/18/2021, today"?
This is hardly an issue since it only shows up to 6 days and that might just make it look worse but I also don't see a huge reason for a setting for this.

**Comment by arkon** [comment]
Rejecting since adding tons of settings is unreasonable.
