### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by FYCT0923** [tachiyomiorg/tachiyomi#5927]
### Steps to reproduce

Click any chapter of titles from Copy Manga

### Expected behavior

View manga normally

### Actual behavior

All mangas from Copy Manga extension pop-up this error when browsing.  Webview works but cannot be view/update in app.

![241802392_10225849153845625_4973883672607455534_n](https://user-images.githubusercontent.com/90952167/133878074-c6f8cff2-03aa-4d47-9bfe-a4e07d395ea5.jpg)

![image](https://user-images.githubusercontent.com/90952167/133878265-8a885ce3-e3f3-4d29-b58b-195a23057fe6.png)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Sony XPERIA 1 II XQ-AT52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
Actually read the acknowledgements section next time. This is an extension issue.

**Comment by FYCT0923** [comment]
Sorry
