### ISSUE TITLE
Automatically dismiss "Add manga to library?" snackbar after 10 seconds

### ISSUE THREAD

**Issue by Cheese659** [tachiyomiorg/tachiyomi#5932]
### Describe your suggested feature

popup in questions in picture below: appears when downloading manga which are not in library
It would be great if you could swipe the popup in all directions (up, down, left, right), not just to the right.
alternatively to add a **NO** button for accessibility.
how it works: simply swiping the popup to the left, down, right, or up removes the popup as opposed to it being only swipe able to the right.
how it works (alternative): pressing the **NO** button removes the popup

![image](https://user-images.githubusercontent.com/85194868/133895983-b25a2519-8e18-4d2a-83f0-6054ab815a99.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
> Alternatively to add a NO button for accessibility. 

Not sure about that.

![image](https://user-images.githubusercontent.com/63973749/133896785-a783d9c1-840d-4958-8b4e-087967779631.png)

![image](https://user-images.githubusercontent.com/63973749/133896886-7e6f01b7-e21a-4584-a1e6-34b5252b0a12.png)

Snackbars aren't even supposed to be swipeable.

![image](https://user-images.githubusercontent.com/63973749/133896984-8d5ba14a-f720-46bc-a9e5-ddafcf12a1f9.png)

#

Swipe to left would be okay, but idk how swipe up/down makes sense.

**Comment by FourTOne5** [comment]
> Snackbars aren't even supposed to be swipeable. (as seen in all Google apps)
> 
> ![image](https://user-images.githubusercontent.com/63973749/133896984-8d5ba14a-f720-46bc-a9e5-ddafcf12a1f9.png)
> 
> Swipe to left would be okay, but idk how swipe up/down makes sense.

Is it just me or Snackbar in Tachi doesn't actually disappear.

**Comment by vengiare** [comment]
> Is it just me or Snackbar in Tachi doesn't actually disappear.

Oh LOL well that's probably an oversight or something

**Comment by Cheese659** [comment]
i didn't know what a snackbar is, but anyway i brought this up in the first place because 1. it doesn't disappear and 2. because of it the blue resume button makes it basically impossible to either download or delete the 1st chapter and 3. accessibility/clarity, ive been using tachi for over a year and didnt know i could swipe it to the right (im right handed so i swipe left on muscle memory) until i did it by accident and tried to replicate it. Thank you for the info on what a snackbar is vengiare.

**Comment by arkon** [comment]
Swiping to the right is standard behaviour.

The only thing that'd sort of make sense to do here is to automatically dismiss it after some time.

**Comment by vengiare** [comment]
That's not on *this* feature request tho. 🤔

**Comment by arkon** [comment]
We're not obligated to fulfill exactly what's requested if, as you point out, it doesn't follow guidelines.

**Comment by vengiare** [comment]
Not sure why this isn't superseded by #5933 then, kinda weird.

**Comment by arkon** [comment]
As you mentioned on Discord, the only other snack bar (when deleting categories) already automatically dismisses.
