### ISSUE TITLE
Opaque manga page top bar when entering while Library top bar hidden

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5935]
### Steps to reproduce

Go to Library/Updates/History
Scroll down to hide top bar
Browse a manga

### Expected behavior

Transparent top bar

### Actual behavior

https://user-images.githubusercontent.com/63973749/133909666-8ce9c096-ce3c-400f-ace2-115a42a7411a.mp4

### Tachiyomi version

r3826

### Android version

A10

### Device

Redmi Note 9 Pro

### Other details

Not the same bug as #5888

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ivaniskandar** [comment]
Fixed by #5990
