### ISSUE TITLE
copy manga can not read

### ISSUE THREAD

**Issue by Cmoe306** [tachiyomiorg/tachiyomi#5940]
### Steps to reproduce

Open all galleries to show “missing argument” 

My device is Oppo Y31S 

APP version is 0.12.2

### Expected behavior

Can read normally

### Actual behavior

Open all galleries to show “missing argument” 

### Tachiyomi version

0.12.2

### Android version

Amdroid 11

### Device

oppo Y31s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.
