### ISSUE TITLE
Not auto-generating cover.jpg from .cbz files

### ISSUE THREAD

**Issue by niyrme** [tachiyomiorg/tachiyomi#5941]
### Steps to reproduce

1. Create (or download) a manga in `.cbz` format (comic book zip)
2. Create a directory with manga name and a functional tree understandable by tachiyomi (except a `cover.jpg` file):
    - [x] contains `details.json`
    - [x] contains `chaper X.cbz` files (`X` being the chapter number)
    - [x] contains `.nomedia` file (optional; so that gallery apps ignore the `cover.jpg` file)
3. Open Tachoyomi > Browse > Local source

### Expected behavior

When selecting the manga (or just scrolling past) a `cover.jpg` (or a different format, since that's supported now?) should be generated in the maga directory (if it doesn't exist); usually the first page of the first chapter

### Actual behavior

`cover.jpg` file does not get generated, leaving the manga in the library view without a cover image

### Tachiyomi version

0.12.2

### Android version

Android 11 OxygenOS 11.0.2.1

### Device

OnePlus 7 Pro; Model: GM1913

### Other details

Also happened in `0.11.X`.
Previously generated manga covers remain unaffected.
Reading the chapters of the manga works just fine.

I'm using the default location in `Storae/Tachiyomi/local`

Methods I tried which didn't work:
- using `Settings > Advanced > Refresh library manga covers`
- selecting the manga and manually refreshing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jak0159** [comment]
I'm also having the same issue tried tachiyomi troubleshoot guide but still cover appears to be blank. Even manually putting a cover it doesnt work

**Comment by arkon** [comment]
Potentially fixed by #6127. Please open another issue (if there isn't one) if the issue still persists in the next preview/stable build.
