### ISSUE TITLE
Toonily library not updating.

### ISSUE THREAD

**Issue by Allied-R** [tachiyomiorg/tachiyomi#5943]
### Steps to reproduce

When trying to refresh to update manga chapters it gives a No chapters found but when I click web view it shows on the site that the chapters are there and when clicking on a chapter it loads fine just not in my library. I've tried both extensions the one from the main extension and the obsolete Madera extension. I've tried uninstalling it and reinstalling and the issue persists.  I accidentally posted this in the extension category and had that one closed by a moderator.

### Expected behavior

Chapters should update in my library.

### Actual behavior

No chapters found error shows up.

### Tachiyomi version

0.12.2

### Android version

Android 10

### Device

Samsung Galaxy S9 edge

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> I accidentally posted this in the extension category and had that one closed by a moderator.

You used the wrong template. This is in the wrong repo.
