### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pandulcito** [tachiyomiorg/tachiyomi#5944]
### Steps to reproduce

No chapter loads, every time that I try to read something doesn't load, just say retry and nothing else. Please, if you can fix this o tell me how can I fix this, I'll really appreciate it. 

### Expected behavior

I'll expect that chapters load and I can read normally that I used to 

### Actual behavior

It still not working :/

### Tachiyomi version

0.12.1

### Android version

Android 9

### Device

Xiaomi Redmi Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This is likely a extension issue, so go to the extensions repo to open a issue instead. Your app is not up to date as per the checklist. It is there for a reason
