### ISSUE TITLE
Create csv/xml file from library

### ISSUE THREAD

**Issue by Luckytiger21** [tachiyomiorg/tachiyomi#5947]
### Describe your suggested feature

Instead of creating a proto.gz file, could there be a way to get a csv/xml file as the back-up. That way if something happens to the app there is a way to get your library file that is not compressed or encoded like proto.gz.

### Other details

I have looked at all of the tracking sources that are supported natively but I have not found one that has everything that I am reading. I just want to be able to export a file that I can save on my PC and migrate to another source. Yes it would be slow and painful but I would not lose my library or have to dig through 5 different trackers to still be missing some.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No plans to do this in the app, but people can build tools to convert the backups as they see fit.
