### ISSUE TITLE
Add support for alternative WebViews (i.e. Bromite)

### ISSUE THREAD

**Issue by 0fbcb238c0** [tachiyomiorg/tachiyomi#5949]
### Describe your suggested feature

After replacing the chromium webview with a more privacy respecting solution (bromite -> 
https://www.bromite.org/system_web_view)
Tachiyomi cannot be used anymore, because of a dependency on "libwebviewchromium.so".

Maybe a switch for webviews could be added?
Error Log: https://hastebin.com/ocewazizax

Thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We don't have any explicit dependency on any particular WebView implementation beyond the standard Android APIs and a user agent string comparison to check for a relatively recent version.

You'd need to make sure you're installing Bromite properly. If you are, then you'd need to report the issue to them.
