### ISSUE TITLE
Option to preload next chapters.

### ISSUE THREAD

**Issue by RamishSiddiqui** [tachiyomiorg/tachiyomi#5953]
### Describe your suggested feature

There should be an option to preload next chapters. So user shouldn't wait for the next chapter to load. Option should contain like preload 1,2,3 chapters. It would be really helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
The app already preloads the next chapter pages, its just limited

**Comment by RamishSiddiqui** [comment]
Can't we have exclusive option to preload multiple chapters. As I like to read and walk and sometimes go to the market while reading. It will be helpful.

**Comment by CarlosEsco** [comment]
If you want multiple chapters just download them and set to auto delete after read

**Comment by loocool2** [comment]
Duplicate of #3295 as well
