### ISSUE TITLE
Pictures cut in half

### ISSUE THREAD

**Issue by Billebjer** [tachiyomiorg/tachiyomi#5957]
### Steps to reproduce

Open webtoon chapter.

### Expected behavior

Pictures should be displayed seamlessly.

### Actual behavior

Pictures are cut in half vertically. Left half displayed above right half.

### Tachiyomi version

0.12.0 and 0.12.2

### Android version

Android 11

### Device

Galaxy Tab S6 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is a source issue. Open an issue in the extensions repo.
