### ISSUE TITLE
Skeleton Loader

### ISSUE THREAD

**Issue by glasszay** [tachiyomiorg/tachiyomi#5958]
### Describe your suggested feature

When it comes to loading information Tachiyomi can be slow on some devices, especially with Samsung devices. This is currently an unavoidable problem. That's why I suggest a Skeleton loader, it can create a perception of reduced waiting time, gives the user an idea of the structure of the loading content and overall just looks better.

### Other details

Here are examples I found on the web:
![0_ABjKedHjIe8El9RJ](https://user-images.githubusercontent.com/76571965/134521534-70b0dd64-9ed6-4882-95f0-1f0b30078dcb.png)

![skeleton-loader-placeholder](https://user-images.githubusercontent.com/76571965/134521665-310d38e0-9b17-42eb-bce0-9d5804f5d965.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
This idea could ​apply to chapters list, browse view for sources, and tracker search. Though I don't know if it would be weird if there's a skeleton loader but then there's no chapters/manga/tracker entry.

Also of course, it's a solid idea for manga info.

**Comment by zayin02** [comment]
Also having it in the updates section can be helpful because while it loads this it what's on the screen:
![Screenshot_20210923-214356_Tachiyomi](https://user-images.githubusercontent.com/76571965/134573663-1c96aa66-4dea-4dfa-80fb-4d922e30ee3f.jpg)

**Comment by arkon** [comment]
This was added in history, but we'll add it as appropriate in other places.

Don't really need an issue to track this.
