### ISSUE TITLE
Mangapark V3 not Updating ( ERROR : FOR INPUT STRING )

### ISSUE THREAD

**Issue by PrinzSouls** [tachiyomiorg/tachiyomi#5962]
### Steps to reproduce

1. Open any manga in MangaPark V3 and click refresh 

### Expected behavior

Chapter to be normally updated as per website

### Actual behavior

Error appear ( for input string ) ..and no chapter update

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Galaxy S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by zayin02** [comment]
Wrong repository and also already a known issue 
(https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9129)
