### ISSUE TITLE
Slow loading/updating speeds for all sources.

### ISSUE THREAD

**Issue by Mangasail** [tachiyomiorg/tachiyomi#5963]
### Steps to reproduce

1. Tap source
2. Library takes long time to load
3. Check web view
4. Source loads quickly
5. Attempt to update library 
6. Library takes a very long time to update

### Expected behavior

Usually the app loads all sources very quickly, and updates the library quickly.

### Actual behavior

All sources load slowly. And updates are very slow.

### Tachiyomi version

0.12.2

### Android version

10

### Device

Samsung galaxy note 20

### Other details

The slow loading speed is 100% not due to the sources because I've tried every source and all of them are very slow compared to before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't an actionable report. You can ask for help on Discord if needed.
