### ISSUE TITLE
the ranking of the website is needed

### ISSUE THREAD

**Issue by 1024kilobytes** [tachiyomiorg/tachiyomi#5964]
### Describe your suggested feature

I hope that we can view the rankings in the extension, such as daily rankings and weekly rankings. This feature is not available in all extensions, not for a certain extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
No.

**Comment by arkon** [comment]
Request for sorting for specific sources if the website has them.
