### ISSUE TITLE
Option to mark chapter as read *after* last page.

### ISSUE THREAD

**Issue by obskyr** [tachiyomiorg/tachiyomi#5970]
### Describe your suggested feature

I often skip to the last page of volumes I read to check credits and similar – and then go back to whichever page I was on. However, that marks the chapter as “read”, and I lose my progress! If there were an option to mark the chapter as read **only when flipping onto the “Finished” pseudo-page,** as opposed to when flipping onto the last page itself, that would be lovely and relieve me of a lot of headache.

This likely causes particular trouble in conjunction with the “delete after reading” option.

The chapter would be marked as read not on the page on the left below, but on the page on the right:  
<img alt="Last page." title="Last page." width="33%" src="https://user-images.githubusercontent.com/4363779/134790286-d680c684-1bd9-4302-9f2f-67d0deb29e1b.png"/> <img alt="Post-last page." title="Post-last page." width="33%" src="https://user-images.githubusercontent.com/4363779/134790287-cfe852da-ed9e-4c91-b95c-716a41c2b013.png"/>

Thank you all for such an incredible user experience, overall!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Yeah I was going to ask for this , This is also a problem in manga which have single page chapters as it marks the chapter as read after just opening it.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/6944#issuecomment-1173178547
