### ISSUE TITLE
MangaSee/MangaDex - Author search not working 

### ISSUE THREAD

**Issue by wangxianwuji** [tachiyomiorg/tachiyomi#5971]
### Steps to reproduce

Issue 1
1. Search & open "Dengeki Daisy" details through MangaDex or MangaSee
2. Click on Author name 
3. MangaDex / Mangasee show both "No result found" (Bato.to does)

Same thing for actively entering part of an author's name in the search field. 
--------------
Issue 2
1. Search & open "Advent of snow white of the hell" through MangaDex 
2. Click on Author name 
3. MangaDex shows 3 books but not the one we used to query the author search 

While on mangadex there are 2 pages full of books by the same author: https://mangadex.org/author/50c55f83-2193-42e3-8d0e-9f7d83bf60aa (but the app only shows 3 and not even the one I used to query)

### Expected behavior

Show books with that in the title + author? 

### Actual behavior

search should include all the books by the author

### Tachiyomi version

0.12.2

### Android version

11

### Device

Samsung Galaxy S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
First of all wrong repository and it's UpTo source how they handle search because Tachiyomi doesn't host any content.
