### ISSUE TITLE
Bato.to migration bugs due to (Official) in the name 

### ISSUE THREAD

**Issue by wangxianwuji** [tachiyomiorg/tachiyomi#5972]
### Steps to reproduce

1. Take any bato.to manga in the library that has (Official) in the name 
     >> Take for example "Koi To Dangan - Dangerous Lover (Official)" 
2. Click migrate 
3.1. Mangadex shows "Koi To Dangan"
3.2 Mangasee shows "No result found"

>> Search globally with the app for "Koi To Dangan" and MangaSee does show the manga with the English Title "Yakuza Lover" 

### Expected behavior

Mangasee to show the manga as it has it 

### Actual behavior

No Result found 

### Tachiyomi version

0.12.2

### Android version

11

### Device

Samsung Galaxy S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
First of all wrong repository and it's UpTo source how they handle search because Tachiyomi doesn't host any content.
