### ISSUE TITLE
Order chapters in Updates tab using their upload data and not when they are downloaded

### ISSUE THREAD

**Issue by Vacui** [tachiyomiorg/tachiyomi#5975]
### Describe your suggested feature

After adding several mangas to my library, my **Updates** tab was filled with over 100 chapters. Some of them are as old as 2013, but they are still shown as discovered "Yesterday".
I wonder if it is possible to add a setting to order the tab using the chapters upload data and not when you downloaded them, to not flood it when a site starts working again and you are overwhelmed by new chapters.
Let me know if it is viable.

Have a nice day and thx for the good work,
Matteo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems to ultimately be the same issue as #4732
