### ISSUE TITLE
please add az comics is translate arabic 

### ISSUE THREAD

**Issue by ah1k** [tachiyomiorg/tachiyomi#5976]
### Steps to reproduce

https://infoazcomics.wixsite.com/azcomics

### Expected behavior

is good for watching comic if you arabic

### Actual behavior

az comics

### Crash logs

add az comics

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Android

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong repository, please follow the instructions in the issue template picker page and the acknowledgements.
