### ISSUE TITLE
Tracker Support: Anime Planet

### ISSUE THREAD

**Issue by MedKing3** [tachiyomiorg/tachiyomi#5980]
### Describe your suggested feature

Please add Anime Planet as a tracker.

### Other details

Link: https://www.anime-planet.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MedKing3** [comment]
Anime Planet also tracks manga.

**Comment by Riztard** [comment]
this is also duplicate issue
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
