### ISSUE TITLE
[CatManga] Chapters not updating

### ISSUE THREAD

**Issue by AcidRav3N1** [tachiyomiorg/tachiyomi#5981]
### Steps to reproduce

1. Go to library 
2. Update library 

### Expected behavior

Mangas should be updated

### Actual behavior

![Screenshot_20210928-132623_Chrome](https://user-images.githubusercontent.com/91519324/135028312-1e14aa29-be92-409f-a064-1fb5861678e0.jpg)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Samsung S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Wrong repository
