### ISSUE TITLE
[Feature/Help] Extra display filter on Browse a Source

### ISSUE THREAD

**Issue by quangkieu** [tachiyomiorg/tachiyomi#5982]
### Describe your suggested feature

So I am working an idea for display filters in Browsing Source.
The filter would apply extra genres, string, "and/or" logic filters after the request is pulled from source query/filter
That is why I called it display filter as it just modifying display results
As I am not fully understanding the code base much so I wonder if anyone could help pin point where in the flow that I could applying the filter on.
It is still in the prototype phase

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
A majority of sources don't have genre information in listing requests, rendering this useless. This will also overcomplicate the UI logic in browse source.
