### ISSUE TITLE
Separating Animate page transitions

### ISSUE THREAD

**Issue by Cheese659** [tachiyomiorg/tachiyomi#5983]
### Describe your suggested feature

Would be cool to have the animate page transition option toggle-able in paged and webtoon separately.
from personal use id love to not have animated page transitions for paged manga but want it on for webtoons since not having an animation makes it harder to read when it jumps instantly.

as it currently is the option affects both and is located in the reader settings fifth from the top, what I'm thinking about is moving the animate page transitions options down to the paged and webtoon sections in the reader settings and make it affect the respective type of content based on if its on/off.

paged - animate page transitions off - not animated
webtoon - animate page transitions on - animated

photoshoped example below:

![page transition](https://user-images.githubusercontent.com/85194868/135071627-2f5902be-5cb8-4c03-a7c5-732801aaed0d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The fact that the settings even differ stems more from an implementation detail than as an intentional user-facing decision. We'd actually ideally strive to unify more of them if possible.
