### ISSUE TITLE
New ways for chapter date display 

### ISSUE THREAD

**Issue by Triplesweet** [tachiyomiorg/tachiyomi#5985]
### Describe your suggested feature

We can have like and option to have Approximately tell us when a chapter was uploaded. For example:

1 year ago,  2 month ago. 

Or more accurate by making it year and month like

 2 year and 4 month ago.

If it looks like a long line we can just have 

2 y 4 m. 
 We can add weeks by just having a "w" as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That's a pain to localize, so no.
