### ISSUE TITLE
[Bug] Cant go to the next chapter

### ISSUE THREAD

**Issue by IllusionElements** [tachiyomiorg/tachiyomi#5988]
### Steps to reproduce

Unsure 

### Expected behavior

Go to the next chapter

### Actual behavior

Sometimes when reading and reach the last page I can't go to the next chapter it just won't leave the current page/chapter. Swiping it to the next chapter just keeps you on the same chapter and pressing the next button does nothing. Only going back to the chapter list and manually going to the next chapter works. To be clear this isn't the last chapter it's happening on just random chapters.

### Crash logs

N/A

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

S20 Ultra Smasung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please open another issue with specific steps if this is actually reproducible.
