### ISSUE TITLE
[Visual Bug] 2 search icons (regular and globe) are seen immediately (then disappear) after a global search is performed.

### ISSUE THREAD

**Issue by WildManiac** [tachiyomiorg/tachiyomi#5992]
### Steps to reproduce

1. Go to browse tab
2. Perform search

### Expected behavior

You should see 1 search icon (the globe one?).

### Actual behavior

For a split second you will see 2 search icons (the regular and the globe) then just the regular icon.

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Samsung A32 5G

### Other details

https://user-images.githubusercontent.com/11233971/135347007-15505a9c-f230-4a80-96ce-9eca51222ba1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Won't be fixed since it's a side effect of the framework we use.
