### ISSUE TITLE
Animeworld: No chapters found

### ISSUE THREAD

**Issue by MaMMM7** [tachiyomiorg/tachiyomi#5995]
### Steps to reproduce

when i update the library the manga from animeworld (italian) extension the app give me an error.

### Expected behavior

If there is no new chapter the app shouldn't say nothing

### Actual behavior

when i update the library the manga from animeworld (italian) extension the app give me an error.

### Crash logs

Error no chapter found

### Tachiyomi version

12.2

### Android version

Android 11

### Device

Samsung S10 lite

### Other details

I guess the error happen because the animeworld site change the domain.
Old domain: Mangaworld.tv
New domain: Mangaworld.in

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please read the acknowledgement section, this is an issue with an extension.

> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by MaMMM7** [comment]
Its a tachyomi problem!!!!!

**Comment by alessandrojean** [comment]
It's an extension problem and there's already a fix submitted.
