### ISSUE TITLE
"Download completed" notification shown after cancelling or paused due to network issues

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6002]
### Steps to reproduce

1. Download any manga chapter that is in library
2. Immediately cancel the download from the notification panel

### Expected behavior

The notification shud be labelled as "Download cancelled"

### Actual behavior

![Screenshot_20211001-201451_Magisk](https://user-images.githubusercontent.com/84634607/135618543-c8a2fef4-6fc3-4bad-b5a0-2d990137a9a4.png)

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Redmi Note 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dangB99** [comment]
I hope they can fix this. My network isn't that stable so it disconnects alot and i have to leave whatever I'm doing,go to downloads then hit resume. This is what I hate most about tachiyomi, such an interrupting issue.

**Comment by Raif1** [comment]
And it seems it also stops downloading

**Comment by arkon** [comment]
Closing in favour of #7492
