### ISSUE TITLE
 create filter for newly updated chapters in library tab

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#6007]
### Describe your suggested feature

Add a filter for newly updated chapters in the library tab, seperate from unread, so that stories that aren't up to date / chapters that you have left to read later dont show up.

This could work by checking the chapter upload date hiding it if the chapter grows older than a certain amount of time.

### Other details

currently chapters of stories that have large gaps between current chapters clog up the unread section while looking at new chapters

and it is really satisfying  to empty the library filtered by unread before moving on to find new stories.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No, this is effectively the same as filtering by unread + sorting by latest chapter, except you want some cutoff too for what's considered unread — which doesn't seem useful for most people.
