### ISSUE TITLE
Chapter auto-downloads even when "wifi only" is enabled

### ISSUE THREAD

**Issue by alrlchoa** [tachiyomiorg/tachiyomi#6008]
### Steps to reproduce

1. tachiyomi setting was that chapters would only download when connected to Wifi
2. Had wifi functionality of phone enabled.
3. Did not connect to wifi
4. Had mobile data on
5. Updated chapters
6. Chapters updated and auto-downloaded

### Expected behavior

In this scenario, chapters should update but not download.

### Actual behavior

Chapters still download

### Tachiyomi version

Stable 0.12.2

### Android version

Android 11

### Device

Samsung S10+

### Other details

When I turn off Wifi, it does as expected. It no longer auto-downloads from mobile data.

Was referred by curche#0545 to post an issue.

Issue thread from discord starts here: https://discord.com/channels/349436576037732353/349436576037732355/893727232319717396

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Relevant PR that might fix this #5967
