### ISSUE TITLE
v0.12.2 封面无法自定义了

### ISSUE THREAD

**Issue by GreatWriter** [tachiyomiorg/tachiyomi#6009]
### Steps to reproduce

v0.12.2 封面无法自定义了

### Expected behavior

v0.12.2 封面无法自定义了

### Actual behavior

v0.12.2 封面无法自定义了

### Tachiyomi version

v0.12.2

### Android version

Android 11

### Device

1+8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you mean for local manga, there's already open issues.

If not, open another issue with better details instead of just repeating the same thing.
