### ISSUE TITLE
Keep screen on default setting should be changed from true to false for OLED

### ISSUE THREAD

**Issue by Sunspark-007** [tachiyomiorg/tachiyomi#6010]
### Describe your suggested feature

The setting to prevent the screen from sleeping has the potential to be dangerous on an OLED display.

If it is possible to query the device and learn whether it is LCD vs OLED, then it could be on if LCD and off if OLED. 

Otherwise I feel it should be off by default.

### Other details

Last night I fell asleep with Tachiyomi in the foreground and the screen stayed on for nearly 6 hours. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't possible.

**Comment by Sunspark-007** [comment]
What about just having it off by default then for all display types?

**Comment by arkon** [comment]
Nah, that's nonsensical for a reading app.
