### ISSUE TITLE
Bottom nav bar is visible in non-root controllers when opened externally

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#6012]
### Steps to reproduce

1. Start download.
2. Close App.
3. Remove from recent.
4. click on download notification.

### Expected behavior

![Screenshot_20211002-212555](https://user-images.githubusercontent.com/59261191/135722928-fea72fdd-fe2f-455a-9aed-d29a3ed6843f.png)

### Actual behavior

![Screenshot_20211002-212328](https://user-images.githubusercontent.com/59261191/135722948-300fffa7-876a-4867-9183-b1ae4cfd9419.png)

### Tachiyomi version

r3833

### Android version

Android 6

### Device

LAVA iris820

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by midyHamdoun** [comment]
Working on it.

**Comment by vengiare** [comment]
Did some testing cause there's a similar bug with deeplinking.

Bug introduced somewhere here.
https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3826
