### ISSUE TITLE
Close keyboard when clicking in the background

### ISSUE THREAD

**Issue by cdhiraj40** [tachiyomiorg/tachiyomi#6016]
### Describe your suggested feature

Activities do not support closing the keyboard when clicking in the background, having this feature will def make a better user experience

https://user-images.githubusercontent.com/75211982/135745971-3210d09e-83ff-4966-afcb-7a52cef69165.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Angel2001-programmer** [comment]
I would like to work on this issue.

**Comment by cdhiraj40** [comment]
> I would like to work on this issue.

sorry, but I have opened the issue and I would like to work on it.
Also I'm ready with the work if @arkon approves then i will directly open the pull request for this issue>

I will suggest you to find new issues. Thanks :)

**Comment by arkon** [comment]
@cdhiraj40 go for it

**Comment by arkon** [comment]
Unless this becomes trivial to implement, I don't think it's worth having a janky implementation for it.
