### ISSUE TITLE
[Feature Request] On restoring a backup the app should suggest the user to install manga extension based on what it has been restored

### ISSUE THREAD

**Issue by ArmeF97** [tachiyomiorg/tachiyomi#6017]
### Describe your suggested feature

- Hava a manga in your library from source "source 1"
- Do a backup
- Move to a new cellphone
- Install tachiyomi
- Restore a backup
- Tachiyomi should suggest me to install the "source 1" manga extension, but it doesn't

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already lists out the missing sources before the restore if you have a relatively recent backup that contains that data.

**Comment by ArmeF97** [comment]
I did, I had a backup from the same day and it didn't list me the sources
