### ISSUE TITLE
[Bug] After a migration to new smartphone, name of sources are not displayed

### ISSUE THREAD

**Issue by ArmeF97** [tachiyomiorg/tachiyomi#6018]
### Steps to reproduce

- Do a backup
- Move to a new smartphone
- Restore the backup

### Expected behavior

![immagine](https://user-images.githubusercontent.com/6240983/135751219-88d79bfe-b30a-4004-8469-e117b50e519b.png)

Here I should see the names of the sources my manga were from, MangaOwl is displayed because I installed the relative extension, but I don't know which extensions to install now

### Actual behavior

Source names are not displayed

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

Oneplus 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ArmeF97** [comment]
I just found the names of the source at the end of the backup (I opened it with notepad++)

```
 ¢MangaOwlõ™åÓäØ††R¢
	Mangahere¢MangaSee	
```

So there already is that information in the backup

**Comment by Riztard** [comment]
name of sources are not displayed because its not installed
and when you restore backup, it should show some warning about ext needed

**Comment by ArmeF97** [comment]
Ok then only https://github.com/tachiyomiorg/tachiyomi/issues/6017 stays open
