### ISSUE TITLE
Mangá yabu bloqueado 

### ISSUE THREAD

**Issue by IGRISS16** [tachiyomiorg/tachiyomi#6019]
### Steps to reproduce

Toda vez que dou um click, em um mangá da extensão: *mangá yabu* diz que o tachiyomi bloqueou esse site, e que devo migrar para outras fontes!!!! 

### Expected behavior

Eu esperava que vocês buscassem priorizar manter as fontes em dia!! Já que desistiram do mangá livre, que focasem em estabilizar e manter as extensões!!! Vcs vão manter ele bloqueado para sempre ? Quanto tempo necessáriamente ?

### Actual behavior

MAS, o mangá yabu virou minha fonte principal de mangás após a exclusão do *MANGÁ LIVRE* que VCS retiraram pois estavam com certas "dificuldades" de manter a extensão, ou seja além de retirar o uma das fontes mais fortes querem desistir do mangá yabu também? Patético, gostaria de receber uma explicação razoável como um usuário do tachiyomi

### Tachiyomi version

0.12.2

### Android version

11

### Device

Samsung A20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you can't read English, please at least use Google Translate. The instructions at the bottom stated that this issue does not belong in this repository.

To answer why the extension no longer works, the aggregator site is aggressively blocking Tachiyomi so that people will directly use the site so that they can make money.

**Comment by alessandrojean** [comment]
Só pra completar com o que já foi dito, este é um projeto open source que as pessoas colaboram quando tem tempo livre e vontade.

Não somos obrigados e nem vale a pena ficar dando manutenção para sites que ficam mudando o código toda hora para fazer a extensão quebrar novamente, isso é uma total perda de tempo.

Além disso, **nunca** dependa de uma única fonte, utilize várias **sempre**. Essas coisas sempre aconteceram e vão continuar acontecendo, é algo totalmente fora de nosso alcance e que não temos controle nenhum. Se você quiser reclamar com alguém, reclame com os donos desses sites.
