### ISSUE TITLE
Them setting by illustration

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#6031]
### Describe your suggested feature

It would be better if we got some simple illustration for each theme. Just like how J2K version dose that.

![IMG_20211004_141725](https://user-images.githubusercontent.com/35896230/135839982-e03ecaea-1a5a-422b-92cc-88c0e569a084.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
did you even read the acknowledgement that you acknowledge?

**Comment by ztimms73** [comment]
Update the app to latest version [**0.12.2**](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.2). What you are requesting already exists.
