### ISSUE TITLE
Sort by ignoring articles

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#6032]
### Describe your suggested feature

When sorting alphabetically, sort ignoring articles (a, an, the) at the start of manga titles.

This feature has already been implemented in J2K version. So i think you don't need to re-code the hole 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Unless there's a way to do easily do this without hardcoding articles for every language, I have no plan to do this.

**Comment by ARiyou2000** [comment]
For coding problem: It's already been implemented by J2K and we just nees reuse the code.

As for doing it for every languages: we can assign it to user. By instead of finding articles for every language and hard code, we can create a list and let the user decide about it's content. We just ignore that list content when sorting.
➖➖➖➖➖➖➖➖➖➖➖
Model 1 (recommended):
![Screenshot_2021-10-04-17-57-07](https://user-images.githubusercontent.com/35896230/135871924-7d89e8f5-1ebd-41f5-bd45-a13f176b4ec9.png)
➖➖➖➖➖➖➖➖➖➖➖
Model 2:
![Screenshot_2021-10-04-18-16-26](https://user-images.githubusercontent.com/35896230/135873041-afe485a3-673c-4cf1-9204-50cea860f015.png)

**Comment by arkon** [comment]
> For coding problem: It's already been implemented by J2K and we just nees reuse the code.

Yes... it's hardcoded and only contains English articles.

> As for doing it for every languages: we can assign it to user.

Seems like a bad idea. Would you ask users to figure out how to sort things?
