### ISSUE TITLE
Last update errors as a update-able category

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#6033]
### Describe your suggested feature

Adding new category in Updates tab and show last update errors as an item (not just text) in it.

In this new category you can try update those items again. 

Some thing like following .(this picture is just for general understanding of how it works. Finall product is similar to second picture) 
![IMG_20211004_145449](https://user-images.githubusercontent.com/35896230/135844370-143354f1-b1d5-4690-8f9b-3726fab5cb36.jpg)

It's better to use different style for managing "Update history" and "Last Update Errorss" like picture below
![IMG_20211004_151846](https://user-images.githubusercontent.com/35896230/135846741-d7dd874c-0302-45c0-9739-463bffc5a3d9.jpg)

### Other details

It's better to use different style for managing "Update history" and "Last Update Errorss" like picture below
![IMG_20211004_151846](https://user-images.githubusercontent.com/35896230/135846741-d7dd874c-0302-45c0-9739-463bffc5a3d9.jpg)
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Something similar has been proposed before but denied.

This sort of design would encourage users to blindly spam updates in an attempt to "fix" errors instead of actually figuring out why they failed.
