### ISSUE TITLE
Bookmark a page

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi#6035]
### Describe your suggested feature

The current bookmark function can only bookmark a chapter. I need to add a new bookmark function so that every page of a chapter can be bookmarked, similar to the favorite page function.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/565
