### ISSUE TITLE
Ignores 'Download with WiFi only' option

### ISSUE THREAD

**Issue by Gokujo** [tachiyomiorg/tachiyomi#6036]
### Steps to reproduce

. Tachiyomi refreshes library every 6 hours and then downloads new chapters if WiFi is avialable. But for some reason if my screen is OFF it starts to download through mobile data. 
![Screenshot_20211004_215229](https://user-images.githubusercontent.com/19776684/135916503-648df462-8c5f-46ad-9f29-cac5801b1e28.jpg)
![Screenshot_20211001_200152_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/19776684/135916505-c0b1bf66-225d-4834-a1a8-fe762cb2628c.jpg)

### Expected behavior

Tachiyomi should start to download when WiFi connection is established 

### Actual behavior

Sometimes tachiyomi downloads with mobile data

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7280986/tachiyomi_crash_logs.txt)

### Tachiyomi version

 0.12.2-3844

### Android version

Android 10

### Device

Huawei Mate 20 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already fixed by #5967
