### ISSUE TITLE
Can't download chapters

### ISSUE THREAD

**Issue by Gokujo** [tachiyomiorg/tachiyomi#6038]
### Steps to reproduce

Add some chapters to download queue and start downloading

### Expected behavior

Download starts

### Actual behavior

Download doesn't start

### Crash logs

[tachiyomi_crash_logs2.txt](https://github.com/tachiyomiorg/tachiyomi/files/7281263/tachiyomi_crash_logs2.txt)

### Tachiyomi version

0.12.3-3858

### Android version

Android 10

### Device

Huawei Mate 20 Pro

### Other details

https://user-images.githubusercontent.com/19776684/135923218-9bd84b3c-6ab5-47dd-9e9f-126a3752c0d1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
@Gokujo Can you try in this build? https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3859

**Comment by arkon** [comment]
@o01210o Can you try redownloading from https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.3 ?

**Comment by o01210o** [comment]
> @o01210o Can you try redownloading from https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.3 ?

It's works! Thanks!
