### ISSUE TITLE
Keyboard appearing when using search inside anysource

### ISSUE THREAD

**Issue by BeetRooting** [tachiyomiorg/tachiyomi#6042]
### Steps to reproduce

1.open source
2. select browse
3. type anything in search
4. open a maanga on search
5. The keyboard will pop up and disappear quickly

### Expected behavior

Keyboard should appear when opening a manga

### Actual behavior

Keyboard pops up and disappear annoyingly

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

oppo a94

### Other details

I think this could be just my phone but it doesn't happen on any other apps other than tachiyomi maybe my phone isn't that compatible with tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
Can confirm with Redmi Note 9 Pro, A10

**Comment by paulo27ms** [comment]
I don't see it when oepning a manga, I see it when I exit back to the broswing view, it sometimes shows up for half a second, it's very inconsistent and it seems like it I spend longer on the manga page when I go back there's less chances the keyboard appears.

**Comment by vengiare** [comment]
On source I get both bugs when entering and exiting. On library I only get it when exiting. It never happens on Global Search.

**Comment by zbue** [comment]
Probably has the same cause 
https://github.com/tachiyomiorg/tachiyomi/issues/6480#issuecomment-1179652766
