### ISSUE TITLE
Switch chapters straight from the reader.

### ISSUE THREAD

**Issue by rijan72** [tachiyomiorg/tachiyomi#6043]
### Describe your suggested feature

It would be nice to quickly switch between chapters straight from the reader. This will allow us to find some nostalgic chapter easily and efficiently navigate between chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This has been rejected before as it's no more efficient than going back to the full chapter list.

**Comment by rijan72** [comment]
I guess intuitive was the right word to use that time.
But understandable.

Thanks for this making manga accessible.
