### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi#6045]
### Steps to reproduce

Hello, after i update my tachi a minute ago i try to download some chapters but it's Pause automatically, when i click on resume shom me this message

![IMG_20211005_144619](https://user-images.githubusercontent.com/61906880/136035619-342b1d13-9b93-47f7-ae07-be05b2c90e61.jpg)

### Expected behavior

Work fine~~

### Actual behavior

Above

### Tachiyomi version

0.12.3

### Android version

10

### Device

Xiaomi Redmi 9C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you update a few hours ago, try redownloading the APK again. If not, please share the crash logs.

**Comment by shipoxx** [comment]
> If you updated a few hours ago, try redownloading the APK again. If not, please share the crash logs.

Sorry for late, it's work fine now

When i update it through app didn't work
But i get new version from GitHub and it's work fine now. Merci
