### ISSUE TITLE
I am getting https error 404 and 403

### ISSUE THREAD

**Issue by BlackPhoenix1747** [tachiyomiorg/tachiyomi#6055]
### Steps to reproduce

Whenever i click the update button or select a source i get the error 404 and 403. I use MangaLife and mangakakolot extensions.

### Expected behavior

It should just update my manga and look for chapter instead of giving me an error message that all Mangas were unable to be updated.

### Actual behavior

I get the 404 and 403 error. I tried the methods on the troubleshooting page but no luck. I am unsure if there is an issue with the extensions or the app itself. I suppose the app as the Asura Scans extension works.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7292989/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.12.3

### Android version

Android 10

### Device

Device: Infinix NOTE 7 Lite   Model: Infinix X656

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Tachiyomi doesn't host any content so the problem definitely lies with the extension. So next time open this in [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) 
Mangakakolot keeps changing manga url that explains the 404. 403 can come from various reason if a source keeps giving you 403 migrate to another one.
