### ISSUE TITLE
Manga page notification bar and top bar fade animation out of sync

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6070]
### Steps to reproduce

Select chapter
Deselect chapter (exit action mode)

### Expected behavior

Fade animation in sync

### Actual behavior

(animation scaling 2x so it's more obvious)

https://user-images.githubusercontent.com/63973749/136635117-afabfc97-a794-4893-a84c-35a28a764e35.mp4

### Tachiyomi version

r3859

### Android version

A10

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't think this is realistically ever going to change unless we start drawing our own fake status bar background.
