### ISSUE TITLE
Read mode: verticaly without gaps don't work

### ISSUE THREAD

**Issue by 1aam2am1** [tachiyomiorg/tachiyomi#6076]
### Steps to reproduce

1. Open manga 
2. Set read mode to vertical without gaps.

### Expected behavior

There should be no gaps between pictures.

### Actual behavior

There are gaps between pictures of manga.

### Tachiyomi version

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z) Android version: 8.0.0 (SDK 26) Android build ID: WAS-LX1 8.0.0.394(C432) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWWAS-H Device model: WAS-LX1 Device product name: WAS-LX1

### Android version

Android 8

### Device

Huawei was-lx1

### Other details

![Screenshot_20211010-132947](https://user-images.githubusercontent.com/13340383/136693781-d82d85b3-1e35-46c9-aa0a-35c82383ff8f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Are you reading in webtoon mode?

**Comment by 1aam2am1** [comment]
Webtoon mode works. Thank you.
