### ISSUE TITLE
Reader toast too low

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#6083]
### Steps to reproduce

1. read chapter
2. change reader/crop border

### Expected behavior

appear above seekbar

### Actual behavior

appear bellow seekbar
<table>
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/897158099230687272/Screenshot_20211011-232518147_1.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/897159537491062875/Screenshot_20211011-233119826_1.jpg">
</table>

### Tachiyomi version

0.12.3

### Android version

A11

### Device

Redmi 8

### Other details

maybe because of the navigation bar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Toast locations aren't really that customizable. It was centered at some point but people didn't like that either.

**Comment by Riztard** [comment]
i like centered 😀
