### ISSUE TITLE
Battery warning notification 

### ISSUE THREAD

**Issue by anasi23** [tachiyomiorg/tachiyomi#6098]
### Steps to reproduce

1.open tachiyomi go to updates tab
2.refresh mangas chapter
3.notification appears along eith progress bar

### Expected behavior

no warning regarding progress

### Actual behavior

The warning for battery drain along with higher number of mangas appears 

![Screenshot_20211014-022509](https://user-images.githubusercontent.com/92494252/137234835-79b64784-87b6-4e37-a7a0-68b64ee195ec.jpg)

### Tachiyomi version

12.3

### Android version

android 11

### Device

OnePlus 8t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
and that is aniyomi, not tachiyomi
