### ISSUE TITLE
Cannot read manga from an NSFW source if "Show in sources and extensions lists" is disabled

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/tachiyomi#6106]
### Steps to reproduce

1. Have the "show nsfw in sources and extensions lists" setting _on_
2. Add manga to library from an extension marked NSFW (like Mangadex)
3. Turn off the "show nsfw in sources and extensions lists" setting
4. Restart Tachiyomi
5. Attempt to try reading any of the manga you just added to your library

### Expected behavior

I should still be able to read the manga, since the setting's name doesn't indicate anything about effecting it.

### Actual behavior

Because that setting stops Tachiyomi from _loading_ extensions marked NSFW, trying to read/view the manga results in the same behavior as if you uninstalled the extension.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung Galaxy S21

### Other details

If you have that setting disabled, and you try to read a nsfw manga from Updates or History, you'll run into the same issue.
**EDIT:** This also causes manga updates to fail with the "Source not found" error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is actually intentional since the switch is meant to be a complete "kill-switch" to block the sources from working at all.
