### ISSUE TITLE
Fast scroll under bottom navigation bar

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#6114]
### Steps to reproduce

1. Use the scroller to fast scroll in Library, Updates, History, and Browse

### Expected behavior

The scroller should not get behind the bottom navigation bar.

### Actual behavior

It gets behind the navigation bar.

### Tachiyomi version

0.12.3 r3875

### Android version

Android 10

### Device

realme c11

### Other details

It happens even if I disable "Hide bottom navigation bar" in the Settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by tanuukii** [comment]
Hello, so I've tried previous version and found that it started to happen from v0.9.2 when https://github.com/tachiyomiorg/tachiyomi/commit/d72c51c8dd778ee14b3fc7936a43718fefe76cd8 this one was implemented.
I hope it helps. Thank you!

**Comment by arkon** [comment]
No longer relevant after some UI rewrites that are happening.
