### ISSUE TITLE
Top bar in manga page is showing after scrolling to chapters if "Hide bottom navigation bar" is disabled

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#6115]
### Steps to reproduce

1. Open a manga from the library
2. Scroll down to chapters then scroll up back to the top

### Expected behavior

Top bar should automatically hide.

### Actual behavior

![Screenshot_2021-10-16-01-10-14-80](https://user-images.githubusercontent.com/87689027/137526625-b2f66811-4b7b-4330-8581-560a04ff29c0.jpg)

### Tachiyomi version

0.12.3 r3875

### Android version

Android 10

### Device

realme c11

### Other details

![Screenshot_2021-10-16-01-09-52-20](https://user-images.githubusercontent.com/87689027/137526699-ef45df2d-acad-4725-bbfa-97ae4f3b85b0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
This can be closed since the option to turn off navigation bar hide on scroll behavior was removed in https://github.com/tachiyomiorg/tachiyomi/commit/0b77b78f6a360d759241ac42b1dcf0fe66b27d50
