### ISSUE TITLE
Using Data without permission

### ISSUE THREAD

**Issue by spicysweetboy** [tachiyomiorg/tachiyomi#6117]
### Steps to reproduce

1. Data is turned off
2. Tachiyomi app is not open
3. Tachiyomi Settings don't allow data use
4. Background data is turned off

### Expected behavior

Shouldn't use my data

### Actual behavior

Uses foreground data, and I don't know why and for what it is using it. Uses a lot even when my data is off

### Tachiyomi version

App version: 0.12.3-3875 (standard, ea34ba53b, 69, 2021-10-09T21:07Z) Android version: 10 (SDK 29) Android build ID: QPWS30.61-21-18-7 Device brand: motorola Device manufacturer: motorola Device name: lake_n Device model: moto g(7) plus Device product name: lake_n

### Android version

Android 10

### Device

Motorola Moto g7 plus

### Other details

![Screenshot_20211015-195654](https://user-images.githubusercontent.com/64571873/137565975-c7f42fa1-cccf-4dd8-b00a-90b8439a3858.png)
![Screenshot_20211015-195729](https://user-images.githubusercontent.com/64571873/137565976-0b92abea-f31c-46b6-914a-120251dd8c44.png)
![Screenshot_20211015-195720](https://user-images.githubusercontent.com/64571873/137565977-b6cccdc1-586f-4fbd-a6be-c6482d05e314.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Regardless, we could change that restriction to be Wi-Fi rather than unmetered. I'm not entirely sure if unmetered is actually super useful.

**Comment by spicysweetboy** [comment]
Yeah, but then my phone tells me "tachiyomi has used more mobile data than
usual" and also my mobile data has 100mb more usage than it should...

**Comment by spicysweetboy** [comment]
Tachiyomi's wifi data usage 

![Screenshot_20211016-105038](https://user-images.githubusercontent.com/64571873/137592020-62a7c009-6e18-467d-9e72-42d1dd567256.png)

**Comment by spicysweetboy** [comment]
Significantly more than the mobile data usage

**Comment by arkon** [comment]
Not sure what that's meant to show, they're not even the same date ranges.

As a workaround though, you should really be updating less often. Updating every 3 hours is excessive if you have a relatively high number of entries to check.
