### ISSUE TITLE
When manually updated, do not download from the Excluded Category.

### ISSUE THREAD

**Issue by Mano5JP** [tachiyomiorg/tachiyomi#6126]
### Steps to reproduce

1. Exclude a category from downloading
2. Manually update the category.

### Expected behavior

1. It should only Update the Manga from that category.

### Actual behavior

1. Updates also gets queues to downloads

### Tachiyomi version

r3903

### Android version

Android 11

### Device

Samsung galaxy Note 10+

### Other details

I have a category that has been excluded from receiving updates and downloads. As a result, when I manually updated the category, I observed that the update had been added to the download queues.

If the Manga is in the excluded category, I would like to manually download it.

[ref video](https://imgur.com/a/fs3DwyC)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I can't reproduce this, and I can't see anything wrong with the exclusion logic either. Are you able to reproduce this with new entries/categories too?

**Comment by Mano5JP** [comment]
I uninstall and reinstalled r3921. I created new categories and entries and manually update and it is downloading updates from excl. download category. [video link ](https://imgur.com/a/4Jr9MsT)

I have added new entries to a new excl. download category will let you know if it will download with an auto-update library.

**Comment by Mano5JP** [comment]
Waited for auto library update then noticed it did download from excl. Category download.
