### ISSUE TITLE
Category top bar can be briefly seen despite being disabled

### ISSUE THREAD

**Issue by anonymous5555522222** [tachiyomiorg/tachiyomi#6144]
### Steps to reproduce

1. Delete every category.
2. Go to Display and then make sure that "Show categories tabs" is disabled.
3. Open a manga entry and then go back to the Library screen.

### Expected behavior

It shouldn't appear at all.

### Actual behavior

The category top bar can be seen for a split second.

### Tachiyomi version

0.12.3 and r3903

### Android version

Android 10

### Device

Alcatel 3X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No intention to "fix" this as it's a limitation of how the views are getting created.
