### ISSUE TITLE
In local manga, cover.png is not accepted, but a PNG file renamed to cover.jpg works

### ISSUE THREAD

**Issue by anonymous5555522222** [tachiyomiorg/tachiyomi#6146]
### Steps to reproduce

 1. Create a folder in Tachiyomi/local.
 2. Copy a PNG file named cover.png to this folder.
 3. Add the local manga entry to the Library through the "Local Manga" source.

### Expected behavior

The cover should be displayed in the Library screen.

### Actual behavior

The image file isn't displayed as the manga entry cover, however renaming the PNG file to cover.jpg works.

### Tachiyomi version

r3903

### Android version

Android 10

### Device

Alcatel 3X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Potentially fixed by #6127. Please open another issue (if there isn't one) if the issue still persists in the next preview/stable build.
