### ISSUE TITLE
Blank space from entries' descriptions disappears when the user attempts to refresh metadata

### ISSUE THREAD

**Issue by anonymous5555522222** [tachiyomiorg/tachiyomi#6149]
### Steps to reproduce

1. Open any manga entry that has blank space.
2. Swipe down to look for new chapters/update metadata.

### Expected behavior

Blank space shouldn't disappear in the description section.

### Actual behavior

They disappear instead, but if the user goes to the Library screen and then re-opens the manga entry, the blank space will be back.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Device

Alcatel 3X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Merging with #6140
