### ISSUE TITLE
Improvements to large updates warning.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6159]
### Describe your suggested feature

Currently even if you have auto update set to 12 hrs or 1 week you get the same warning ( if you have certain number of manga updating at the same time , plus sometimes there isn't a way to decrease that number as for ex . I mostly read manhwa which update weekly and now I have quite a bit in my ongoing ) which doesn't give much reason for people to change auto update time from 12 hrs to 1 week or even 3 days which could decrease the load on a server. They would probably just start ignoring the warning specially as it gets hidden between errors during the update and new chapters that were found. 
What I am proposing is that maybe you don't get the warning if the update interval is set at a week with only update ongoing manga , or there could be that the warnings become less annoying like you get a prompt saying something like you are harming the source if the interval is at 12hrs decreasing to maybe please try decreasing the number of manga you are updating at a time at a week ( I proposed the earlier one as I think it would be easier to implement than this one , but I am not sure as I am not a dev ) . This gives a sort of incentive to people so as a way they might instead of ignoring the warning increase the time between auto update interval instead.
At least untill [#5734](https://github.com/tachiyomiorg/tachiyomi/pull/5734) get's implemented.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
The current suggestion is to just start chunking your larger categories into smaller ones.

**Comment by THElegend5** [comment]
> The current suggestion is to just start chunking your larger categories into smaller ones.

I have about 12 categories atm , and just have auto update off now , I just manually update the ongoing category of a particular type when I feel like there are probably more updates to something , was proposing the above in general.
