### ISSUE TITLE
Unread counter to corner + better contrast

### ISSUE THREAD

**Issue by Alpha-JS** [tachiyomiorg/tachiyomi#6161]
### Describe your suggested feature

Sometimes the contrast between things on the library are really annoying, so it would be cool if there was an option to enable a thin border around each cover title, like in J2K.
It would also be cool if the unread counter was slightly outside the cover title corner, also like J2K, since sometimes the unread counter is a little hard to read when the colours are so similar to that of the cover.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is a design choice from J2K that we aren't planning on adopting in the original app.
