### ISSUE TITLE
quick switch between mangas

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#6162]
### Describe your suggested feature

So, basically you can switch between mangas in your library and/or sources without having to exit the manga information and can instantly switch by using a button on the sides of the screen; i imagine it as an arrow of some sort...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not really interested in this since the full library is far more powerful and only 1 tap/swipe away (i.e. going back).
