### ISSUE TITLE
Add unknown in the library filter

### ISSUE THREAD

**Issue by miss1433** [tachiyomiorg/tachiyomi#6163]
### Describe your suggested feature

Basically it filter the unknown manga status in the library. What im saying is sometime some extension stop updating the manga cause maybe they change something . If the manga bookmarks pass 500 , its hard to manually check them if they are still ongoing or goes to unknown. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Duplicate of #9945
