### ISSUE TITLE
Option to change between storages to store manga covers.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#6167]
### Describe your suggested feature

Like how you can change storage in Spotify.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This would severely impact app performance.
