### ISSUE TITLE
Cant load some pages in every manga from hitomi.la

### ISSUE THREAD

**Issue by Lvl1skeleton** [tachiyomiorg/tachiyomi#6173]
### Steps to reproduce

1.enter hitomi.la
2.enter any manga
3.some page cant be loaded even if i press retry mutiple times

### Expected behavior

Page should load properly 

### Actual behavior

Cant load some pages even with multiply tries

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Realme x7 max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
