### ISSUE TITLE
Can you add a read button: continue reading the last time?

### ISSUE THREAD

**Issue by Baoziqinru** [tachiyomiorg/tachiyomi#6174]
### Describe your suggested feature

At present, the read button can only mark read from the beginning to the end, which is very inconvenient. Because I have read some contents from paper comic books and other ways. Multiple chapter marks have been read and need to be operated many times. I hope developers can add a continue reading (finally click the chapter) button.Thank you and good luck

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Mark the chapters as read. You can easily select a range by long pressing the first and last chapters you want selected.
