### ISSUE TITLE
gif animation toggle

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#6175]
### Describe your suggested feature

As an accessibility option it would be nice if there where toggles for disabling animated gifs for Title covers and in `Reader` settings.

### Other details

I find it can sometimes be nauseous / annoying seeing moving images / animated call to actions while browsing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not sure Coil (which we use to handle animated images) actually allows you to _not_ have them animate. You could potentially request it here: https://github.com/coil-kt/coil/issues

**Comment by skrshe** [comment]
thnx for the tip 👍
