### ISSUE TITLE
Amazon Fire Parse Errof

### ISSUE THREAD

**Issue by Jacksilk1** [tachiyomiorg/tachiyomi#6182]
### Steps to reproduce

Amazon fire tablet running fire is version 5.6.9.0. 
Attempt to download tachiyomi update or fresh download of release version.

### Expected behavior

Tachiyomi updates or installs.

### Actual behavior

Met with "parse error: there was a problem parsing the package. Additionally, using the browse tab results I error "id1id2: actual 0x00003430 !=expected 0x00001f8b.

### Tachiyomi version

App version: 0.10.5-2774 (standard, b88e444c, 51) Android version: 5.1.1 (SDK 22) Android build ID: LVY48F Device brand: Amazon Device manufacturer: Amazon Device name: suez Device model: KFSUWI Device product name: suez

### Android version

Fire is version 5.6.9.0

### Device

Amazon fire 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
android 5 is no longer supported.
