### ISSUE TITLE
A Library filter for Titles with an unread chapter count of over a limit

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#6184]
### Describe your suggested feature

a  filter that limits Titles below / above a selectable threshold of unread chapters** 
(may be usefull for hiding Titles that you plan to read later)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can just sort by unread chapters.

**Comment by skrshe** [comment]
boo 😿

sorry for the trouble
I just love the app and this is all I can contribute currently
