### ISSUE TITLE
[Question Curiosity] is Apk based Extension System Banned by Playstore ? 

### ISSUE THREAD

**Issue by Shabinder** [tachiyomiorg/tachiyomi#6185]
### Describe your suggested feature

I was reading through your code and really loved how well it is written. This issue is not to ask you to publish in the play store, instead more of curiosity-based.

I went on to read why this isn't available on the play store. there were 3 reasons, 
 - 18+, 
 - operates in Grey Area, 
 - Extensions APK System.

I just **want to ask questions regarding the latter**, **_Google Forbids Downloading Executable Code and loading any code from user home directory._**

But if we don't include an extension downloading and updating logic within the core app and rather ask the user to **explicitly** go to GitHub and download all the extensions OR create a helper app to do this and then the user only needs to download a single external 3rd party app.

And if can only consider showing an extensions list within the core play store published app which are legal and provide content for free _(consider some exists just for sake of question)_

So, a clean version of app is on playstore with limited functionality and if user wants to extend functionality he/she can download the extensions explicitly and install which then core app can benefit from.

Is this possible will above violate any Playstore Policies (ignoring 18+) ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
1. The makes using source convoluted.  
2.  There is no benefit for the app to be on the play store.

**Comment by Shabinder** [comment]
>     1. The makes using sources convoluted.

Ohk ,anyway lets say this isn't an issue hypothetically
 

>     2. There is no benefit for the app to be on the play store.
 
there will be Legal sources extensions on playstore(say some sources are in white are and give free content 13+)
Then will it violate any Google Play Policy?

And


if you were to rebuild the app and extension system from scratch keeping Gplay policies in mind, what system would you have opted to include extensions apk ?

**Comment by CarlosEsco** [comment]
There is no reason to rebuild this, there is no benefit for Tachiyomi to be on the play store.   I'm not giving out advice on how you can make a tachi clone that works for the play store.

**Comment by Shabinder** [comment]
@CarlosEsco I only want to have a discussion as I haven't entered and know all about Gplay policies, this is just me gathering some info,
I would have started a discussion but Discussions arent open in this repo

I am **not** gonna build a Tachiyomi clone, it is for **my side project: Spotiflyer** , check my profile.
I can move this conversation to a one on one platform (plz share if this is the case) if you are comfortable, of not letting someone use these instructions to build a clone.

**Comment by CarlosEsco** [comment]
it has nothing to do with comfortability, github is for issues and features, this is unrelated.  We don't want Tachi on the playstore at the end of the day.  It provides no benefit.  How you build something that allows side loading of apks on the playstore is none of our concerns because we aren't doing it.  I have no advice how you can get your app play store acceptable.

**Comment by arkon** [comment]
You should review the Google Play Store policies if you're looking for answers about that.

As far as I'm aware, plugin systems are allowed (e.g. the Galaxy Wearable app and plugins). Apps that act as an app manager (i.e. downloads and installs things) are not.
