### ISSUE TITLE
"Has Any" filtering option for libary and chapter.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#6186]
### Describe your suggested feature

Self-explanatory

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is far from self-explanatory.

**Comment by FourTOne5** [comment]
:pepehmm: Filtering option to show manga (or chapter) if any filter condition is satisfied. Similar to MangaDex's Tag inclusion (or exclusion) mode.

**Comment by paulo27ms** [comment]
Could be something that could serve a purpose in the future if more filters are added but seems pretty useless right now.
What are you using it for, "any manga with unread OR downloaded chapters", "downloaded OR completed", etc, the combinations just don't make much sense to be used.

**Comment by FourTOne5** [comment]
> Could be something that could serve a purpose in the future if more filters are added but seems pretty useless right now. What are you using it for, "any manga with unread OR downloaded chapters", "downloaded OR completed", etc, the combinations just don't make much sense to be used.

I mainly want this for chapter so I can see "bookmarked OR unread" chapters adding it to libary to is just an extra but necessarily not needed

**Comment by FourTOne5** [comment]
Closing in favour of #6958
