### ISSUE TITLE
1st Kiss Manhua Problem

### ISSUE THREAD

**Issue by Aslam604** [tachiyomiorg/tachiyomi#6188]
### Steps to reproduce

Unable to read any manga in 1st Kiss Manhua it is saying retry only. 
Dont know why this problem is coming please look through it. 

### Expected behavior

Able to read through 1st kiss manhua. 

### Actual behavior

I think it got stuck or there is some kind of bug dont know, but I'm unable to read any mangas from 1st kiss manhua. It is just saying retry

### Tachiyomi version

Latest 

### Android version

Miui global 12.5.1

### Device

Redmi note 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
