### ISSUE TITLE
Update all extension button

### ISSUE THREAD

**Issue by adsewse2015** [tachiyomiorg/tachiyomi#6189]
### Describe your suggested feature

A buttton in extension menu that update all the extension at once ,i have shizuku and update all source at once would be really nice especially with big update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Rejoice it's in preview build 

![IMG_20211102_220613_851](https://user-images.githubusercontent.com/59261191/139896463-da033ff0-f9c2-417c-b9c2-108c71fadc72.JPG)

**Comment by adsewse2015** [comment]
Sorry, i think its because im using TachiyomiSY

**Comment by adsewse2015** [comment]
So just need to wait

**Comment by arkon** [comment]
Ok? This isn't the SY issue tracker.
