### ISSUE TITLE
Blue Theme Broken in Preview

### ISSUE THREAD

**Issue by jobobby04** [tachiyomiorg/tachiyomi#6190]
### Steps to reproduce

1. Go to settings and turn on Blue theme

### Expected behavior

Toolbar should be a pleasant dark blue

### Actual behavior

Toolbar is horrible light blue
![sdghvhi 1](https://user-images.githubusercontent.com/17078382/139965387-570c3ab8-1ca9-4d09-8d90-8b70338718a6.png)

### Tachiyomi version

Preview 3931

### Android version

Android 11

### Device

Google Pixel 2 Emulator

### Other details

I couldn't figure it out in SY, so I am opening a issue here :sadboihours:

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I vote to finally remove this theme

**Comment by arkon** [comment]
Haven't actually looked into a fix, but I narrowed it down to 55a3094a65fe65fdb5e4492e319578f6446da23c breaking it.

**Comment by CrepeTF** [comment]
I concur with the objectively correct assessment to remove this theme

**Comment by arkon** [comment]
Theme was removed.
