### ISSUE TITLE
Can you make side padding option Manga exclusive? 

### ISSUE THREAD

**Issue by shadowbunshin** [tachiyomiorg/tachiyomi#6191]
### Describe your suggested feature

Can you make side padding option Manga exclusive?
Like you made landscape or portrait mode selection
I like to read 6/10 manga in landscape with %15 padding
And other 4 I like portrait with %0 padding

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Nah.
