### ISSUE TITLE
Per manga color bit settings

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi#6192]
### Describe your suggested feature

Instead of needing to go to settings every time you want to switch from 16-bit color to 32-bit color it should be in the reading mode settings for the manga.

### Other details

I often need to switch back from 32-bit color because the manga is lagging. It's a hassle to go all the way to settings.
32-bit color does make a substantial difference in many manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be irrelevant once #5759 is completed.
