### ISSUE TITLE
Source/Extension categorizer

### ISSUE THREAD

**Issue by schasti** [tachiyomiorg/tachiyomi#6196]
### Describe your suggested feature

It should work like how you can pin a source and then it shows separately. So you can f.ex flag a source as "manga" then it will be shown under the manga label in browse-sources. This should be custom categories so you can name the lables yourself. This would mean i could categories which sources i would use for which. Fx. "Manga" + "manwha" + "nsfw" etc 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by schasti** [comment]
Additionally this would entail a label source search. Like pinned works. So if i wanna search for stuff only under a certan category/label ive made it will only search for results in said category. This will lead to faster searches and more organized use of the app.

**Comment by arkon** [comment]
#1904
