### ISSUE TITLE
Add mangadex synchrnization feature in Tachiyomi anf TachiyomiJ2K app and Flame scans extension back

### ISSUE THREAD

**Issue by Iresh007** [tachiyomiorg/tachiyomi#6199]
### Describe your suggested feature

Like there is myanime list /ailist and other synchronization avaliable in Tachiyomi and tachiyomi J2K add mangadex synchronization also as many of us have mangadex account also.

And add Flame Scans extension back if possible .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/2370

**Comment by CarlosEsco** [comment]
extensions removed at scanlators request aren't being added back
