### ISSUE TITLE
Manga loading circle too high

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#6200]
### Steps to reproduce

1. open manga
2. refresh

### Expected behavior

loading circle place lower/previous place 

### Actual behavior

some part of loading circle hidden by phone notch

<img width="300dp" src="https://cdn.discordapp.com/attachments/825346400953827349/906412492778004490/IMG_20211106_112911.jpg">

### Tachiyomi version

0.12.3, r3931

### Android version

A11

### Device

Redmi 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment]
it seems to me that it is hidden by screen protector, not by the notch

**Comment by Riztard** [comment]
nah it also hidden by notch

**Comment by vengiare** [comment]
I reported this in #5808 before and was fixed by #5827. Wonder what broke it again.

**Comment by Soitora** [comment]
That's definitely the screen protector at fault, the distance is fine without it.

**Comment by ghostbear** [comment]
> I reported this in #5808 before and was fixed by #5827. Wonder what broke it again.

In preview r3937 I'm seeing a similar issue reported in #5808, that the swipe refresh icon is too high up. Could be phone-specific because in AS emulator it's below to status bar
