### ISSUE TITLE
Considerations over a KMM project

### ISSUE THREAD

**Issue by anis-campos** [tachiyomiorg/tachiyomi#6204]
### Describe your suggested feature

I looked out for a discussion over [Kotlin Multiplatform Mobile﻿](https://kotlinlang.org/docs/kmm-overview.html) in the previous issues and I could not find one. So the goal here is to have a fair evaluation of the possibility of using KMM for a future version of Tachiyomi.

Although KMM is in an alpha phase, there as been some success stories out there this past 2 years ([Netflix studio app](https://netflixtechblog.com/netflix-android-and-ios-studio-apps-kotlin-multiplatform-d6d4d8d25d23), [Memrise](https://engineering.memrise.com/kotlin-multiplatform-memrise-3764b5a4a0db), [Leroy Merlin](https://kotlinlang.org/lp/mobile/case-studies/leroy-merlin), [Mounty](https://medium.com/mounty-engineering/is-kmm-production-ready-how-we-migrated-our-code-to-kotlin-multiplatform-mobile-part-1-d7329874a402)) of people converting there existing apps into a KMM project.

So what are the pros: 
- **Still using Kotlin**: keeping the same would is a huge advantage for this community that is already used to it. ( specially compared to react-native, flutter, etc...)
- **Incremental implementation**: because Tachiyomi is already Kotlin/gradle, we can gradually re-implement the code in a shared module, making sure there is no regressions in the android app, and step by step making it available for a other platform. This would prevent the tunnel effect of trying to migrate the project for months and never achieving a working app.
- **Mono code base**: The elephant in the room. With a multi platform project, there might still be some extra effort in maintaining specific platforms, but having shared the business layer will make the maintenance a lot more simple, fixing business logic for all at once. 

And the cons:
- **Implement the whole iOS interface**: No sharing possible there. All the interface will need to be implemented separately, a lot of help will be needed here by some iOS experts so the UI stays closes to the android project. 
- **The plugin approach**: AFAIK, iOS as no plugin based pattern. The iOS app will need to find another way to handle the plugins, maybe by bundling them on install ? 
- **Installation**: Obviously the AppStore is a no go. So only enthusiastic, tech savvy, mac owners would be able to install the app in their devices from sources. But even if it's just half of 13k people out there that starred this repo, I might be worth it ? I hope so...
- **Updates**: Just like stated in the previous points, no automated process is possible here. Maybe it's a lost cause for mainstream users, but again, for enthusiastic, it's seems to be small price to pay. 

So from my perspective, a huge advantages, my iPad would be so much more useful 😄 and I could finally ditch my broken S9, but also some obvious obstacles. Maybe there are solutions ? I was willing to deep dive in this alone and try a port by myself for just my devices. But it seems so challenging, and I would love to do this as part of this community. 

### Other details

Disclaimer: I'm no mobile dev expert, I'm a well versed back-end dev and I'm surely lacking knowledge in this matter. Though I'm highly motivated and would like to contribute in one of my favorite apps.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The rewrite (https://github.com/tachiyomiorg/tachiyomi-1.x) is a KMM project, but there's no plans for iOS.
