### ISSUE TITLE
Adjusting brightness

### ISSUE THREAD

**Issue by masamhel** [tachiyomiorg/tachiyomi#6205]
### Describe your suggested feature

Hi. May I suggest regarding the brightness adjustment? In the past,while adjusting brightness for tachiyomi's app, the brightness adjuster becomes transparent so that I can see how low or high it is for a page. But now it's not being transparent anymore so I have to drag down the settings so I can see the page. Thank you very much

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by blackholeearth** [comment]
Please dont do this. İ dont want app to mess with  my screen brighness. İf accidently i change  via app, İt disables auto brightness it fcks up my eyes. 

This has happened with couple of other apps.
Either i deleted them. Or i disabled  brightness change  feature.

**Comment by CrepeTF** [comment]
> Please dont do this. İ dont want app to mess with  my screen brighness. İf accidently i change  via app, İt disables auto brightness it fcks up my eyes. 
> 
> This has happened with couple of other apps.
> Either i deleted them. Or i disabled  brightness change  feature.

So just don't use the option. Also the issue is regarding the brightness slider being too low in the reader settings so they can't actually preview the brightness change on the page.
