### ISSUE TITLE
Extension Problem >:(

### ISSUE THREAD

**Issue by RoseDelacruz** [tachiyomiorg/tachiyomi#6206]
### Steps to reproduce

1.Go to Tachiyomi 
2.Click Browse
3.Click Extension 
4.Click Searc
5.Search "1st kiss" or "1st kiss Manhwa"
6.click install
7.click done
8.click sources 
9.Click 1st kiss 
10.wait for loading
11.It say "(･o･;)  
Unable to resolve host "1stkissmanga.io": No address associated with hostname"

### Expected behavior

My God Please Fix it :(

"(･o･;)  
Unable to resolve host "1stkissmanga.io": No address associated with hostname"

### Actual behavior

It should pop out the Manhwa and Manga :(

### Crash logs

content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt

--------- beginning of system
--------- beginning of main
11-06 19:45:53.165 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:45:53.165 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:45:53.165 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:45:53.165 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:45:53.165 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:45:53.165 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:45:53.165 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:48:36.704 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:48:36.704 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:48:36.704 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:48:36.704 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:48:36.704 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:48:36.704 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:48:36.704 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:49:19.811 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:49:19.811 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:49:19.811 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:49:19.811 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:49:19.811 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:49:19.811 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:49:19.811 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:49:19.812 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:49:19.813 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:49:19.813 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:49:19.813 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:49:19.813 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:49:19.813 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:49:19.813 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:49:19.818 15808 20055 E System  : Uncaught exception thrown by finalizer
11-06 19:49:19.819 15808 20055 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
11-06 19:49:19.819 15808 20055 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:349)
11-06 19:49:19.819 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
11-06 19:49:19.819 15808 20055 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
11-06 19:49:19.819 15808 20055 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
11-06 19:49:19.819 15808 20055 E System  : 	at java.lang.Thread.run(Thread.java:923)
11-06 19:49:26.491 20176 20176 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
11-06 19:49:26.922 20176 25831 E SQLiteLog: (284) automatic index on C(manga_id)
11-06 19:49:26.922 20176 25831 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-06 19:49:48.419 20176 20176 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:49:58.070 20176 20176 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:50:01.124 20176 20176 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:50:32.356 20176 20176 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:50:51.888 25907 25907 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
11-06 19:50:52.297 25907 26372 E SQLiteLog: (284) automatic index on C(manga_id)
11-06 19:50:52.298 25907 26372 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-06 19:53:07.438 25907 25907 E chromium: [ERROR:network_service_instance_impl.cc(179)] Failed to grant sandbox access to network context data for /data/user/0/eu.kanade.tachiyomi/app_webview/Default with result 7: No such file or directory (2)
11-06 19:54:04.429 25907 25907 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:56:04.279 25907 25907 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
11-06 19:56:05.711 25907 29434 E chromium: [ERROR:quic_idle_network_detector.cc(102)] SetAlarm called after stopped
11-06 19:57:18.429 25907 25907 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.N770FXXS8EUI4
Device brand: samsung
Device manufacturer: samsung
Device name: r7
Device model: SM-N770F
Device product name: r7nsxx

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung Note 10 Lite

### Other details

Please fix it :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
