### ISSUE TITLE
Make "Always show chapter transitions" option per-title rather than app-wide

### ISSUE THREAD

**Issue by shockz0rz** [tachiyomiorg/tachiyomi#6207]
### Describe your suggested feature

The chapter transition page is something that I like having when reading a series with multi-page chapters, but is disruptive for series with single-page chapters, and having to toggle the option every time I switch which series I'm reading is a bit frustrating (especially on top of bug #3079 ). It would make more sense to me to have the "Always show chapter transition" setting apply to individual series rather than app-wide (although it would likely need an app-wide default setting as well).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KennySmash** [comment]
Agreed although It might make more sense to have the setting be to hide the transition page rather than always show

**Comment by arkon** [comment]
Per-title settings are way too messy to implement so it's ideal to avoid them as much as possible.

It isn't that hard to toggle it from the reader settings sheet as-is.
