### ISSUE TITLE
Tachiyomi source folders disappearing

### ISSUE THREAD

**Issue by Shaaaaarl** [tachiyomiorg/tachiyomi#6209]
### Steps to reproduce

1. Download manga chapter
2. Manga chapter should be downloaded 
3. Manga chapter isn't seen as downloaded in the manga

### Expected behavior

The manga should be downloaded for offline and is readable, not disappearing.

### Actual behavior

The source folder for the downloaded manga chapters directory isn't created thus, making the the chapter empty and a pop-up will appear with "No pages found" text

### Tachiyomi version

0.12.3

### Android version

Android 9

### Device

Xiaomi Redmi 6A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Provided steps aren't useful for debugging the issue, as this isn't happening on my device with some random entries. Try to provide more consistent steps.

**Comment by AlexCreeed** [comment]
It is also happening with me, the app downloads a chapter and after 30 minutes or 1 hour it doesn't recognizes the chapter as downloaded anymore, said chapter is still in the phone, just the app seems to be unable to read it.

**Comment by curche** [comment]
@AlexCreeed @Shaaaaarl can you confirm: is your download location set to an sdcard?

**Comment by AlexCreeed** [comment]
@Shaaaaarl yes it is, is that the reason for the bug ?

**Comment by curche** [comment]
Very likely, yes... perhaps try reading a chapter downloaded to Internal storage

**Comment by AlexCreeed** [comment]
Somehow the app is now recognizing the chapters I downloaded previously, but if it bugs out again I'll try the internal storage.

**Comment by yusireamor** [comment]
Can i tell you my bug? All the chapters in my library are gone and only provide one chapter (the latest) for one mangas. They all suddenly migrate about 1000+. As you all know, when you migrate a manga, you do it one by one. But my bug do it for all the manga al the same time. And know am i going to move the mangat from migrate to the library one by one? What should I do?
