### ISSUE TITLE
Prioritise downloading new chapters

### ISSUE THREAD

**Issue by Viren070** [tachiyomiorg/tachiyomi#6210]
### Describe your suggested feature

For example, if I am currently mass downloading a manga and then i update my library and a new chapter is released, I would want the new chapter to be moved to the top of the download queue rather than at the bottom. 
Referring to the attachment below, I would want the 2 chapters at the bottom to automatically be moved to the top as they are new chapters. 

### Other details

![Screenshot_20211107_113701](https://user-images.githubusercontent.com/71220264/140643324-80549854-5fb5-4e6d-acb2-b51419a63ee1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Use the sort options in the Download Queue options already available
Not sure why you'd want the latest chapter downloaded instead of the first one
Also, warning: do not download a lot of chapters at once since you'll end up being IP banned and not be able to download anymore

**Comment by arkon** [comment]
It's a download queue, not a download stack. You can reorder your queue needed.

**Comment by FourTOne5** [comment]
I think he probably meant new chapters from libary update  since those gets added at the bottom of the queue sorting will just mess up the existing queue in this case.
