### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#6213]
### Describe your suggested feature

Some titles have markdown texts in their description/about and it looks realy bad on tachiyomi. A way to handle the markdown and make them clikabe (using webview) would be wonderful 

Example: https://mangadex.org/title/fc7f2c19-0a26-4d89-9505-332fcb7d60c6
![Screenshot_20211107-193916_Tachiyomi](https://user-images.githubusercontent.com/76596575/140664461-dbe61f30-148b-4b9c-9d57-e2fed70f4002.jpg)

### Other details

If this is not possible something that hides the markdown will be okay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This can be fixed on the extension side by using some library like [JetBrains/markdown](https://github.com/JetBrains/markdown) to remove the Markdown tags.

Open a new issue in the extensions' repository to ask for this to be added in the extensions you're having problems.
