### ISSUE TITLE
Japanese titles (kanji/kana) appear "date fetched" in device notification window; do not appear "date fetched" in Updates

### ISSUE THREAD

**Issue by Bantlebroth** [tachiyomiorg/tachiyomi#6217]
### Steps to reproduce

Source: Any Japanese-only source with kanji (Japanese lettering) as the titles -- example Manga1000.
Step 1: Add To Library new title from source (any title with kanji-only first letter will do).
Step 2: Wait until title appears in notification bar/window of app device.
Step 3: Open Tachiyomi app, go to Updates.

### Expected behavior

"This should happen..."
... is that the kanji-only title should appear in Updates as it appeared in the notification bar/window. 

### Actual behavior

"This happened instead..."
... the kanji-only title does not appear in Updates as it appeared in the notification bar/window. 

All other titles (English letters) appear in Updates as they did in the notification bar/window.

### Tachiyomi version

Stable 0.12.2

### Android version

6.0.1

### Device

Galaxy S4 Mini

### Other details

This issue appeared in a similar manner as Issue #4576. 

I messaged the Tachiyomi Discord support page on 2021/11/11 and was helped.

It was noted that Issue #4576 was fixed, but reverted as it caused another issue.

A workaround was suggested to sort Library by "date fetched", which does allow the kanji-only titles to be accessed. However, that is not the same as having the kanji-only titles appear in the Updates section as they do in the notifications bar/window.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Nothing to do with kanji or japanese character specifically.

Dates are not provided by the website for the Updates page to sort it by so the chapters get buried at the very very bottom.

It could be solved by trying to use the date fetched for chapters and sites for which do not provide dates and use that to make them appear at the top of the Updates page, though apparently this may have led to another issue before.

**Comment by paulo27ms** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4938

**Comment by CrepeTF** [comment]
Closing in favour of #4938
