### ISSUE TITLE
Doujindesu can't do search

### ISSUE THREAD

**Issue by Megumi-chon** [tachiyomiorg/tachiyomi#6223]
### Steps to reproduce

1. Open 
2. Show manhwa list
2. manhwa name search
3. No results found

### Expected behavior

Want to do a search for the name of the manhwa title in Doujindesu and the searched manhwa title appears.

### Actual behavior

![Screenshot_20211112-191346~2](https://user-images.githubusercontent.com/94088435/141465636-5eab774d-0c08-4bc9-a3a3-72572effe7ee.png)
The title you are looking for is there
![Screenshot_20211112-191355~2](https://user-images.githubusercontent.com/94088435/141465672-ab93de3d-b6fa-45f0-a40b-e9846cf954b9.png)
But when I search for it, I can't find it

### Tachiyomi version

0.12.3

### Android version

10

### Device

Umidigi s5 pro

### Other details

Judging from the initial appearance, all the manhwa titles appear with no problems, but if you do a search with one title. Then the system displays "result not found"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Wrong repo
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.
