### ISSUE TITLE
Chapters not being deleted

### ISSUE THREAD

**Issue by SoarynAC** [tachiyomiorg/tachiyomi#6224]
### Steps to reproduce

1. Set option to automatically delete a chapter after read
2. Read a chapter

OR

1. Select a chapter
2. Click delete button

### Expected behavior

The chapter should be deleted

### Actual behavior

It shows as if the chapter was deleted, but after closing and opening the app again the chapter is still downloaded and you can access it without internet connection

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Motorola One Vision

### Other details

Occasionally the chapter gets deleted, but on most cases it doesn't.

I tried batch deleting and single chapter deleting, the behavior is the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Not something we can really solve, but there are some band-aid fixes you can try. Read this: https://tachiyomi.org/help/faq/#android-11

**Comment by arkon** [comment]
Duplicate of #4286
