### ISSUE TITLE
Cannot obtain update by 'check for updates' in preview version

### ISSUE THREAD

**Issue by in-out** [tachiyomiorg/tachiyomi#6227]
### Steps to reproduce

it reproduces in preview build
1.open about -> check for updates
2.no updates found 

### Expected behavior

same as before
popup up update details and download link

### Actual behavior

cannot find updates

### Tachiyomi version

preview r3931

### Android version

oneui 3.1(android 11)

### Device

samsung s20 fe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
+1 Also you are able to update from the notification saying new update available.
