### ISSUE TITLE
In Extension list, Add count of manga in your library for that extenstion.

### ISSUE THREAD

**Issue by asif-mistry** [tachiyomiorg/tachiyomi#6236]
### Describe your suggested feature

Add the number of manga you have in your library for that extension. (For both extensions and migrate tab).

This count will help in figuring out if there are any unused extensions that the user can remove.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Related: #3787

**Comment by arkon** [comment]
Closing in favor of #3787; it'd be more ideal to calculate the number in a deferred manner.
