### ISSUE TITLE
sort chapters alphabetically

### ISSUE THREAD

**Issue by Gujob** [tachiyomiorg/tachiyomi#6238]
### Describe your suggested feature

As the title says, I would like to request a feature in the Tachiyomi app. The feature is sorting chapters alphabetically as there is only by source, upload date and number.

### Other details

Why I would like that? Well, I tried using the "local source" to organize my own mangas and when I organize anthologies, manga magazines like jump, etc I like to name "chapters" in this order: "Author" → "Name of the chapter". It would make searching chapters much easily as I like to put everything together in one file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
You sure that's not what sorting by source does in local? I don't think it'd sort any other way actually.

**Comment by arkon** [comment]
Local source chapters are sorted by number, then name. You should be able to just name your chapters with numbers properly.
