### ISSUE TITLE
Extensión

### ISSUE THREAD

**Issue by Emanuek51** [tachiyomiorg/tachiyomi#6239]
### Steps to reproduce

If the team cam pls make de extensión of yugenmanga work again 
Its my first time writing in inglish sorry if you dont understand 

### Expected behavior

A

### Actual behavior

A

### Tachiyomi version

1.4.3

### Android version

11

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Wrong repo + already requested.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9229
