### ISSUE TITLE
Tachiyomi error (Needs authorization)

### ISSUE THREAD

**Issue by Resiak121901** [tachiyomiorg/tachiyomi#6242]
### Steps to reproduce

I want to Tachiyomi

### Expected behavior

I should have downloaded  tachiyomi

### Actual behavior

But t
![Screenshot_20211117-201116_Gallery](https://user-images.githubusercontent.com/94524098/142198883-ab0a9e24-0483-407f-9047-f7edae6eb29a.jpg)
t said that it "needs authorization"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Galaxy A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
There is no new version after 12.3. You can come to discord and ask for help in #support
