### ISSUE TITLE
Customize the "sort" and "filter" options app-wide

### ISSUE THREAD

**Issue by zZekken2** [tachiyomiorg/tachiyomi#6245]
### Describe your suggested feature

A feature that ables the user to **customize the "sort" and "filter" options app-wide**.
For example, instead of first showing the last chapter in every new addition in the library or in the extension browser, it would show, in my case, the chapter 1 and/or only the unread ones, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Doesn't the "set as default" option already do this?

**Comment by paulo27ms** [comment]
Yes it does, you can set as default and apply to every manga at once.
