### ISSUE TITLE
MAL Tracking Search Enhancement 

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6246]
### Describe your suggested feature

As noted in **_several_** issues, MyAnimeList's search does not work properly with long titles and special characters such as `~`, `[]` and others. The error is HTTP 400, or "bad request". 
The solution: add filtering to limits to the MAL search.  For grouping, such as `()` and `[]`, maybe remove the section entirely. then remove other ones like `~`, then if it is still too long, it cuts it down. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not entirely sure the solution should be to not search what the user actually inputted. If MAL has actual guidance on how to deal with it, we can look into implementing that.
