### ISSUE TITLE
Not getting error log when updating through update library button.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6247]
### Steps to reproduce

1. Add a manga which will give an error on updating library to the library.
2. Use the update library button to update library.

### Expected behavior

You get an error log telling you that there were problems with a certain no. of manga.

### Actual behavior

You don't get an error log.

### Tachiyomi version

0.12.3-3950

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

You are able to get the error log if you update the library by swiping down on that category you are trying to update through the update library button , don't know if this problem is also there for auto update library as I am not using that . This problem appeared at around the same time as when update tachiyomi button stopped working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Also all the other notifications of how many new chapter of which series were found work as normal.

**Comment by arkon** [comment]
Can't reproduce, make sure you didn't disable the notifications in the system settings.

**Comment by THElegend5** [comment]
@arkon I don't have notifications disabled , also I can get the error log if i refresh a single category by swiping down . I also gett all the other notifications except for error log when using update library.
