### ISSUE TITLE
Updates Bottom Icon Showing 999+

### ISSUE THREAD

**Issue by Zero-G-Sys** [tachiyomiorg/tachiyomi#6251]
### Steps to reproduce

-After opening the app, after installing the preview update r3937, the updates icon is showing 999+ updates.
-Performing any type of update check on sources or viewing the section will not change/clear that number.
-I'm now on preview version r3950 and bug still persists
![Screenshot_20211119-200103_Tachiyomi](https://user-images.githubusercontent.com/74690685/142711784-8a0bc9c9-11cb-4d0e-90a5-37dc037912dc.jpg)

### Expected behavior

Update icon should display only the number of updates and, clear once you enter that section.

### Actual behavior

Updates icon is locked on 999+

### Tachiyomi version

r3950

### Android version

Android 11 (One UI 3)

### Device

Samsung Galaxy S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You have 999+ unread chapters then. You can turn it off in the settings.

**Comment by Zero-G-Sys** [comment]
Certainly, seems to be a new feature. Thanks and sorry for the issue
Options > General > Show unread count on Updates icon
