### ISSUE TITLE
Title Blacklist/Not-Interested Filter in Browse

### ISSUE THREAD

**Issue by lealeelu** [tachiyomiorg/tachiyomi#6253]
### Describe your suggested feature

When the user comes across a title they know they will never want to read, they can click a button in the chapter list view that will add it to a blacklist. When the user looks through the source browse list, they will either no longer see that title, or have a marker on the preview image denoting they marked it as blacklisted.

I want this because I've come across titles that have elements I never want to see again and don't want it muddying up my browse list. Currently I have to memorize which ones I don't like.

### Other details
No offense to Mieruko fans, it just scared the $%#& out of me.
![Tachiyomi Ban Concept](https://user-images.githubusercontent.com/5091130/142745001-bce03ba8-ca21-4dc8-82eb-a27821b193b3.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lealeelu** [comment]
I would like to try and submit a pull request for this feature. Does the team have any direction on how best to implement this?

**Comment by quangkieu** [comment]
I am working on do Browse local sort + filter here https://github.com/tachiyomiorg/tachiyomi/pull/6225. 
It is draft as I got a few stop gate as the filter need some manga metadata like latest chapter that would only available when actually refresh the manga, like all of them in queue.
You could try to work from it. From your description, I think a filter by local category would work. So, you would need to flag something like "Dislike" category on that manga and filter it on response result.
Another stop gate, it is not work on auto fetch next page. I have to disable it when filter or sort is on.
But I still waiting maintainer to give the blessing on the feature.
