### ISSUE TITLE
Jinmantiantang some of tags Connection reset

### ISSUE THREAD

**Issue by ShichimiyaMizu** [tachiyomiorg/tachiyomi#6254]
### Steps to reproduce

1.Click on the tag and enter
2.Waiting for refresh

### Expected behavior

Refresh and display the comic list normally.

### Actual behavior

1.Unable to refresh and display comic list
2.The page returns the error message "Connection reset"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

xiaomi 11 pro

### Other details

I can't open the tag named loli or shota in Jinmantiantang, but I can open these tags in the original app. 
I find the version of Jinmantiantang is v1.2.16 in Extensions. 
While the latest version is 1.0 after a suddenly updating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository
