### ISSUE TITLE
Notification bar and top bar different bg when in action mode/tracking

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6256]
### Steps to reproduce

Go to Updates or Manga -> Chapter list
Select item 
Scroll down
#
Go to manga
Go to tracker search screen
Scroll down

### Expected behavior

Notification bar and top bar same bg

### Actual behavior

![Screenshot_20211205-094108](https://user-images.githubusercontent.com/63973749/144730160-65a5de14-598b-4048-8f60-7e8e1b70daba.png)
![Screenshot_20211205-094058](https://user-images.githubusercontent.com/63973749/144730167-bcd112cc-2664-4d4e-91cd-bbe95c462da9.png)

### Tachiyomi version

r3999

### Android version

A11

### Device

Redmi Note 9 Pro (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lonleyman** [comment]
I m also facing a same issue on visible navigation button and scroll bar . This is very annoying
