### ISSUE TITLE
Migrate

### ISSUE THREAD

**Issue by yusireamor** [tachiyomiorg/tachiyomi#6257]
### Steps to reproduce

1. Today I open tachiyomi as usually
2. Suddenly all the chapter are gone
3. There's only one chapter for one manga/manhwa/manhua
4. Then i try to restore and didn't work
5. Then i check again. Then found all the manga that gone is in migrate

### Expected behavior

I expect I don't have to move my manga from the migrate one by one. It's 1000+ and when it's on the search, it's take long to search. And when it complete it's only show the popular manga/manhwa/manhua. I must click the filter first so it can search the match one.

### Actual behavior

My manga in the library move by itself. All the manga in my library only show one chapter (the latest) and didn't show the rest. And turn out it move to migrate in the browse.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Redmi Note 8 Pro

### Other details

Please fix the migrate option, so I can select all of the manga and then migrate it at the same time. If it's one by one, I don't know how much time I should spend.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Update your extensions or report issues in the extensions repo appropriately.
