### ISSUE TITLE
[Feature Request] Request download all button for updating extensions all at once

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi#6258]
### Describe your suggested feature

Add a button <download all> or <update all> to automatically start downloading all the extension update available on browse > extension menu in tachiyomi app

### Other details

![Screenshot_20211121-185232_Tachiyomi](https://user-images.githubusercontent.com/36104528/142775273-df67ff90-2888-4005-a695-a35e98425173.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
There is in beta version. It'll come to stable soon™
