### ISSUE TITLE
Please add fully support for Android 11

### ISSUE THREAD

**Issue by WaruiDevil** [tachiyomiorg/tachiyomi#6259]
### Describe your suggested feature

I saw in TachiyomiJ2K that fully support A11 while this is not even preview versions not support.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Would you like to provide more details?  The app runs fine on A11.

**Comment by WaruiDevil** [comment]
Like it take time to delete manga I thought it's A11 problem or I have too much manga so it take time but it was fine in a10 I even used TachiyomiSY but there also same problem but I tried tachiyomiJ2k it have fixed maybe coz it support API 30.

**Comment by WaruiDevil** [comment]
https://user-images.githubusercontent.com/94843665/142888855-d9d4fb00-72e5-4661-b478-7c109721d6cd.mp4

Sorry if quality is bad I try to upload but it say less than 10Mb...I face like this from a11 after founding solution then I create GitHub account...😅

**Comment by arkon** [comment]
Targetting Android 11 doesn't magically make Android 11 better.

**Comment by WaruiDevil** [comment]
I know a11 sucks that's why I didn't complain from long time I use A10 now I buy new phone only a11 support...🥲 But still I coprate well not much problem but why tachiyomiJ2k work fine if that can work then why not this too....sorry if it offend u.
