### ISSUE TITLE
Ability to remove manga from trackers

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6260]
### Describe your suggested feature

Sometimes you might track the wrong manga and you have to go all the way to the site and remove it manually ( also sometimes you aren't even able to tell which one you tracked untill some time later ) , it would be nice if there would be something like a a pop up saying do you want to also remove this from mal/anilist when you remove the tracking for that title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by zaghdaneh** [comment]
I started working on this so if possible please assign to me.
Should the dialog be like in the linked picture ? or something less obstructive?
![image](https://github.com/tachiyomiorg/tachiyomi/assets/46049558/ae8fdb5a-3a63-4756-81a9-3dee210b6d08)

**Comment by AntsyLich** [comment]
We don't do assignments. Also it'll better if it's in the middle of the screen like an normal dialog

**Comment by arkon** [comment]
That looks fine, it's consistent with the date removal.
