### ISSUE TITLE
App exiting by Itself

### ISSUE THREAD

**Issue by IjustWant2Read** [tachiyomiorg/tachiyomi#6264]
### Steps to reproduce

1. I updated the app
2. Open the Library Updates
3. Read one of the updated chapters
4. The app exited by itself
5. 2-4 repeat

### Expected behavior

"I expected for the app to run smoothly after updating it."

### Actual behavior

"Instead, while reading a chapter the app exited for 3-4 seconds."

### Tachiyomi version

0.8.4

### Android version

Samsung 

### Device

Galaxy Note 9

### Other details

After updating, I noticed that my version is at 0.8.4. But the problem is below the acknowledgement of this issue said that there is a 0.12.3 version. Even though I updated it in the right way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
update your app

**Comment by arkon** [comment]
Did you update to 0.12.3 then?

**Comment by IjustWant2Read** [comment]
I did update the app but its still in 0.8.4

**Comment by IjustWant2Read** [comment]
I did update the app but it said 0.8.4 still

**Comment by arkon** [comment]
Then try to update it properly then. If you need help on how to update apps, please ask in the Discord server for assistance.
