### ISSUE TITLE
mangaowl's rest of the chapters are being hidden

### ISSUE THREAD

**Issue by deemon11** [tachiyomiorg/tachiyomi#6266]
### Steps to reproduce

1. Click any story in mangaowl
2. Suspiciously [1] tag would show above the cover knowing its unread yet its a completed story and i havent read it at all
3. Issue shows that all of the chapters but the last/recent chapter would show on the list

### Expected behavior

Upon clicking the story all chapters shuld be listed in order

### Actual behavior

Last/recent chapter would show and had to refresh the story to show the hidden chapters sometimes it wouldn't show at all

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Oppo Reno3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> If this is an issue with an extension [like Mangaowl], I should be opening an issue in the [extensions](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) repository.
> I have updated all installed extensions.
> I have tried the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) guide.

Make sure to read the acknowledgements you are acknowledging...
