### ISSUE TITLE
Subscribe to author / get notified of any new "work"

### ISSUE THREAD

**Issue by jscti** [tachiyomiorg/tachiyomi#6267]
### Describe your suggested feature

It would be great to subscribe to a favorite author (and/or artist ?) to get notified if he release any new work.
Maybe with a new tab on the "Explore menu" or "New menu" to list them

Technically I don't know if this feature should be linked to a source or MAL. but it could be very usefull.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is entirely not possible with how Tachiyomi works because there are no servers.

**Comment by arkon** [comment]
The app doesn't know anything about the actual source catalogs, so this is impossible.
