### ISSUE TITLE
I can't see manga-raw.club mangas cover photos

### ISSUE THREAD

**Issue by vent23487** [tachiyomiorg/tachiyomi#6269]
### Steps to reproduce

Open tachiyomi
Click manga-raw.club
Mangas are showing but cover photos are not
Thats the issue.
![Screenshot_2021-11-23-20-18-10-914_eu kanade tachiyomi](https://user-images.githubusercontent.com/94924330/143072637-65999e83-aff0-4fe5-a35e-634eea0cfa41.jpg)

### Expected behavior

idk
![Uploading Screenshot_2021-11-23-20-18-10-914_eu.kanade.tachiyomi.jpg…]()

### Actual behavior

idk
![Screenshot_2021-11-23-20-18-10-914_eu kanade tachiyomi](https://user-images.githubusercontent.com/94924330/143072976-a3074e11-14d8-43e6-beb3-689bc25b4ee2.jpg)

### Crash logs

![Screenshot_2021-11-23-20-18-10-914_eu kanade tachiyomi](https://user-images.githubusercontent.com/94924330/143072702-251e5e43-a222-4fd8-bfdc-1448a1abaf40.jpg)
.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Xiaomi redmi note 8

### Other details

idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jasmix555** [comment]
![Screenshot_20211124-023715_Tachiyomi](https://user-images.githubusercontent.com/94930720/143092092-88f5d6fe-627c-4fa5-acde-e6e731ce2cbf.jpg)
Same issue here

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
