### ISSUE TITLE
Make Incognito mode behavior consistent for manga in Library

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6270]
### Describe your suggested feature

Incognito mode currently doesn't mark chapters as read if a manga is not tracked. This shouldn't be the case as Incognito mode should only affect History tab, not mark as read behavior. 

If the manga is **not being tracked**, it 
should **mark the chapter as read** as intended.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
not sure if this should be considered a bug, it's been like that for a year: https://github.com/tachiyomiorg/tachiyomi/pull/4073
> Does not save chapter progress (overwritten if the manga is being tracked by a tracker)

**Comment by vengiare** [comment]
> (overwritten if the manga is being tracked by a tracker)

Maybe because the assumption was, the only use-case for Incognito mode is gonna be for Browse and not Library.

The problem is Incognito mode **also** works on Library manga. So if you use it on Library manga:

- if the manga in library **is not linked** to a tracker, it doesn't mark the chapter as read
- if the manga in library **is linked** to a tracker, it marks the chapter as read

So either it should be reverted so behavior is the same for library manga with and without tracker, or make Incognito mode only work for manga not in library.

**Comment by vengiare** [comment]
Updated the issue to use a Feature request format and could be marked as such

**Comment by ghostbear** [comment]
> Maybe because the assumption was, the only use-case for Incognito mode is gonna be for Browse and not Library.

The assumption was that if the user tracks a manga they want it tracked. 

For me, the way it currently works is perfect because I can forget to turn off Incognito when I switch between reading hentai (which is not tracked and I don't want them to be tracked) and non-hentai (which is tracked and I do want them to be tracked) that I have in my library.

**Comment by vengiare** [comment]
> The assumption was that if the user tracks a manga they want it tracked.

But if you have Incognito mode enabled, shouldn't it *not* mark any chapters as read and also not record any reading history?

**Comment by ghostbear** [comment]
It isn't added to reading history though, it just updates the tracker and marks the chapter as read for convenience. 

Which is similar to what Jay said on Discord

> i wouldnt think of it as a bug, like how you can go into a web browser's incognito mode and still sign into accounts to update or buy something, its basically the same use case here

**Comment by vengiare** [comment]
The latter suggestion would work better for that use case then; Incognito mode only working for Browse and not for Library. Cause

> The assumption was that if the user tracks a manga they want it tracked.

You could apply the same idea to library manga. If you added it to library, you want to mark it as read and track the history. And,

> I can forget to turn off Incognito when I switch between reading hentai (which is not tracked and I don't want them to be tracked) and non-hentai (which is tracked and I do want them to be tracked) that I have in my library.

You can forget to turn off incognito and still read manga in your library.

#

I still think there's a valid use-case for Incognito mode affecting library manga and manga linked to trackers. But if not, making library manga bypass Incognito still makes more sense than **just** tracked manga.
