### ISSUE TITLE
New clear database screen sometimes crashes the app

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi#6271]
### Steps to reproduce

1. Open Advanced Settings.
2. Try entering the Clear Database screen.

### Expected behavior

The new database clear screen should open and let you choose what sources you want the titles to be removed from the database.

### Actual behavior

Sometimes the screen opens with an empty message and the app crashes right after. Sometimes it does open and let me interact with it when I clear the chapter cache before trying to clear the database.

### Crash logs

[tachiyomi_crash_logs-7.txt](https://github.com/tachiyomiorg/tachiyomi/files/7591686/tachiyomi_crash_logs-7.txt)

### Tachiyomi version

r3977

### Android version

Android 11

### Device

Samsung Galaxy S20+

### Other details

Seems to be introduced by #6241.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Oops I totally have a fix for this locally that I forgot to push. Will push sometime this week.

**Comment by jmir1** [comment]
In my fork I just fixed it by using launchUI:
```kotlin
fun setItems(items: List<ClearDatabaseSourceItem>) {
    launchUI {
        adapter?.updateDataSet(items)
    }
}
```

If you want I can make a PR for that.
