### ISSUE TITLE
[Feature Request] Saving Notes per chapter

### ISSUE THREAD

**Issue by AbdullahMehiz** [tachiyomiorg/tachiyomi#6275]
### Describe your suggested feature

So, you've read a chapter and you wanted to keep some notes so you can easily find it later or add some context to why you bookmarked it before.
So all you have to do is long click a chapter, an option pops up where you can write a 128 letters or so to save as notes that can be read later on when clicking an icon that marks chapters that have notes stored with them like bookmarked chapters have bookmark icons. These Notes might as well be saved as a part of the library like bookmarks so they can be backed up and restored easily.

### Other details

Tbh, i am trying to suggest a feature similar to [Anyme](Anyme.app) as you can see from the screenshot
![Screenshot_2021-11-24-22-04-16-394_com zunjae anyme](https://user-images.githubusercontent.com/85505634/143313082-f4043f7a-961a-4187-a94f-c8ca0a504f28.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
#2155
