### ISSUE TITLE
Chapters disappeared because extension is not updated

### ISSUE THREAD

**Issue by eouuuu** [tachiyomiorg/tachiyomi#6282]
### Steps to reproduce

Ah... I opened Tachiyomi a few days ago and got confused because the chapters(including bookmarks) disappeared. I figured it out later on that I needed to update the extension. I updated it and the chapters came back but the bookmarks and the sign that I read it is gone. 

This is the first time this happened to me. The extension is MangaOwl.

### Expected behavior

I hope this doesn’t happen again, please. My bookmarks aaaaah 

### Actual behavior

When this happened to me, I refreshed the manga everything disappeared except the latest one but if I try to open it, it exits me out of the chapter. 

That’s all. I really hope this doesn’t happen again, I reread everything just to get my bookmarks back, lol. I’m sorry if this is confusing as this is the first time I wrote here and I have not slept a blink for a few days...

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung A10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This happens because the chapter URLs changed, nothing that can be done to fix it. Also, please follow the acknowledgements next time.

> If this is an issue with an extension, I should be opening an issue in the extensions repository.
