### ISSUE TITLE
Doesn't update the manga for some sources 

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi#6285]
### Steps to reproduce

1- Update the library
2- Doesn't update manga from some sources 

The problem appeared after I updated the application to the version shown in the picture
![Screenshot_20211127-081005](https://user-images.githubusercontent.com/90999286/143669054-3e1c3ef4-9a67-4705-8962-baa8f55941a9.png)
![Screenshot_20211127-081020](https://user-images.githubusercontent.com/90999286/143669121-e582d610-7d9c-4412-8017-88b83efe4748.png)

### Expected behavior

It should update

### Actual behavior

Doesn't update the manga for some sources

### Tachiyomi version

preview r3977

### Android version

Android 10

### Device

LG STYLO 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please give more specific details, we're not mind readers

**Comment by shipoxx** [comment]
مرجوا شرح اكثر حول المشكلة التي واجهتك بشكل تفصيلي مع امثلة لو في امكان لمعرفة سبب مشكلة واصلاحه.

**Comment by shipoxx** [comment]
> Please give more specific details, we're not mind readers 

I'm not sure but i think he referring to error after You update Library

**Comment by hani1998** [comment]
@shipoxx هناك بطى عن تحديث المكتبة الخاصه بي وخصوصاً لمصدر اي مانجا 
@arkon There is a delay in updating my library, especially for any manga source

**Comment by shipoxx** [comment]
> @shipoxx هناك بطى عن تحديث المكتبة الخاصه بي وخصوصاً لمصدر اي مانجا 
> @arkon There is a delay in updating my library, especially for iimanga source

اي مصدر تقصد (اسمه) ؟
دعني استوضح الامر: مكتبة خاصتك تأخد وقت طويل ليتم تحديثها او لا يتم او فقط بعض وبعض لا؟
اذ كان اي مصدر لا يتم تحديثه اعطني سمه.

**Comment by hani1998** [comment]
@shipoxx في تاخر بتحديث المكتبث الخاصة بمصدر iimanga

**Comment by hani1998** [comment]
يتاخر بالتحديث يستغرق مثلاً مانها martial peak تاخذ ربع ساعة حتى تتحدث بمصدر iimanga

**Comment by shipoxx** [comment]
> يتاخر بالتحديث يستغرق مثلاً مانها martial peak تاخذ ربع ساعة حتى تتحدث بمصدر iimanga


غريب امر لم يحدث معي ولكن الامر يعتمد على سرعة انترنت خاصة بك في مقام اول.
هذه ليست bug فغالبا سوف يتم غلق هذا
يمكنك استعانة بديسكور افضل للحصول على مساعدة.

**Comment by arkon** [comment]
If chapters don't appear after a while in comparison to the website for specific sources, open issues in the extensions repo.

**Comment by hani1998** [comment]
@shipoxx ببرنامج anyiome لايوجد مشكلة ولكن ببرنامج tachyomi النسخه الاخيرة فيها مشكلة

**Comment by hani1998** [comment]
@shipoxx ببرنامج anyiome لايوجد مشكلة ولكن ببرنامج tachyomi النسخه الاخيرة فيها مشكلة

**Comment by shipoxx** [comment]
> @shipoxx ببرنامج anyiome لايوجد مشكلة ولكن ببرنامج tachyomi النسخه الاخيرة فيها مشكلة

انت تعلم ان aniyomi ليس له اي علاقة بي tachiyomi ؟

**Comment by hani1998** [comment]
@shipoxx ولكن فيه مصادر مانجا تشيومي

**Comment by shipoxx** [comment]
ايضا ملاحظة من @arkon 

إذا لم تظهر الفصول بعد فترة وجيزة من الوقت مقارنةً بالمصادر اخرى، فافتح موضوع/بلاغ repo جديد ليس هنا بل في tachiyomi extension
هنا نختص فقط بالتطبيق وليس مصادر.

**Comment by shipoxx** [comment]
> ايضا ملاحظة من @arkon 
> 
> إذا لم تظهر الفصول بعد فترة وجيزة من الوقت مقارنةً بالمصادر اخرى، فافتح موضوع/بلاغ repo جديد ليس هنا بل في tachiyomi extension
> هنا نختص فقط بالتطبيق وليس مصادر.

@hani1998

**Comment by hani1998** [comment]
ولكن نسخة التطبيق 1.2.3 لايوجد مشاكل فيها

**Comment by hani1998** [comment]
وانما هذه النسخة يوجد فيها مشاكل

**Comment by shipoxx** [comment]
> وانما هذه النسخة يوجد فيها مشاكل

اي نسخة تقصد؟ تاشيومي او انيومي؟؟
 لقد ضيعت ماتقصد
ياريت لو تتكلم بتفصيل او سيتم تجاهل ابلاغ!

**Comment by hani1998** [comment]
@shipoxx ياخي الخلل في هذه النسخه من تطبيق تشيومي

![IMG_20211130_210607](https://user-images.githubusercontent.com/90999286/144103217-d339387e-1ac5-494e-ae44-1a95f3cfe489.jpg)

**Comment by paulo27ms** [comment]
Just because no one understands you doesn't mean you should chat on issues.
Go to discord and maybe even get some help troubleshooting on #support if you are the only one with an issue.
