### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by CiceroDaniel** [tachiyomiorg/tachiyomi#6287]
### Steps to reproduce

...

### Expected behavior

....

### Actual behavior

ERRO 403 NA EXTENSÃO DO GOLDEN MANGÁS

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1

### Device

Lg k9 Tv

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
