### ISSUE TITLE
chapter download stops if page file size is below unknown minimum

### ISSUE THREAD

**Issue by mistamal** [tachiyomiorg/tachiyomi#6290]
### Steps to reproduce

Download chapter which contains page with very small file size. Like all black or white.

### Expected behavior

Download should happen normally but stops after reaching page with small file size. Strange because page can viewed normally in reader.

### Actual behavior

Downloader stops prematurely.

### Tachiyomi version

r3984

### Android version

android 11

### Device

samsung galaxy tab s7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
What chapter from what source?
