### ISSUE TITLE
Sources to update and install automatically

### ISSUE THREAD

**Issue by miachuu** [tachiyomiorg/tachiyomi#6294]
### Describe your suggested feature

I hope there is an update all sources automatically and install automatically choices in the browse area. It's a little time consuming to manually update and install sources individually especially when almost all sources has updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Duplicate issue
