### ISSUE TITLE
Expansion for different types of 3rd-party notification systems

### ISSUE THREAD

**Issue by wisewtf** [tachiyomiorg/tachiyomi#6295]
### Describe your suggested feature

I would love for Tachiyomi to be configurable so that it sends issue available/downloaded notifications through 3rd party messaging systems, like for example via Discord webhooks or via the Telegram message API and any similar things. For example using something like https://github.com/caronc/apprise.

The reasons for this are multiple, these are a few:

1. Many Android devices absolutely do not like sending notifications, I find myself having downloaded chapters but no notifications whatsoever.
2. (In my case) I read on a tablet that is not my daily driver phone, so it is exclusively for reading and I do not see or notice any notification whatsoever, if they ever come.
3. Just overall better awareness of what Tachiyomi is doing from literally anywhere you want to

If Tachiyomi were to send me a notification on Telegram, whenever a chapter is available or downloaded then I wouldn't necessarily build up a 'neglect' backlog because I forget to check my tablet.

I would kindly ask to take this into consideration, but I understand if this feature request isn't going to be popular.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Everything that Tachiyomi does is entirely local, so it doesn't make sense for us to build out infrastructure to do push notifications.

You could use something like Tasker to intercept notifications and forward them in some way that works for you.
