### ISSUE TITLE
"Update all" button for extensions

### ISSUE THREAD

**Issue by piyooshm** [tachiyomiorg/tachiyomi#6296]
### Describe your suggested feature

Currently, when new extension updates are available, the user has to click "Update" for each extension to start downloading and installing the updates. So, it would be great if there were a button kick-off the update process for multiple or all the extensions at once.

While it may still be needed to click on "Install" for each extension, the proposed button would at least reduce number of taps by starting the download and installer process for multiple or all updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Duplicate issue, already exists in Preview.
