### ISSUE TITLE
Chapter Update Issue In Library

### ISSUE THREAD

**Issue by Memeisangry** [tachiyomiorg/tachiyomi#6297]
### Steps to reproduce

My mangas dont update automitically after i update the latest version and it still doesent work even i click the updating library arrow and it is not updating 

### Expected behavior

The library should update every 6hours according to my update frequency .

### Actual behavior

The library dosent update every 6hours and not updating anymore. And updating library arrow doesnt work even i click it and it is not updating. It only shows updating library at the bottom but not updating. 

### Tachiyomi version

The lastest version

### Android version

Android 9

### Device

Samsung glaxy a70

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
State the actual version you have numerically, also the lowest update frequency has been increased to 12 hours
