### ISSUE TITLE
When using "Update All" for extension updates if a update is stopped/aborted by user ask the user if they want to continue the update

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#6298]
### Describe your suggested feature

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't think there's actually a way to tell if a PackageInstaller-based update was actually cancelled, so the user would have to go and manually cancel/restart it anyhow.
