### ISSUE TITLE
global/permanent filter

### ISSUE THREAD

**Issue by HinzundKunz** [tachiyomiorg/tachiyomi#6299]
### Describe your suggested feature

I would like to be able to have a permanent filter for global searches, for example when I only want to look for completed series or when I only want to search for (or exclude) specific tags/categories.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't possible without adding a large amount of overhead to request every single search result.

**Comment by CarlosEsco** [comment]
> So it would need to be implemented in every single addon, right? I can see that the mangadex addon already has something like this implemented, as you can filter out permanently ecchi and mature stuff...

it's not possible because every website has their search options and filters.

**Comment by HinzundKunz** [comment]
So in some extensions it would be possible to make a permanent filter, in others not?

**Comment by CarlosEsco** [comment]
Sure but it entirely depends on the website, but there definitely wont be 1 global option like this ticket mentions.

**Comment by HinzundKunz** [comment]
OK, so I'll put in feature requests at the extensions I use and see what's possible...
