### ISSUE TITLE
Tapas - cannot log in to individual webtoon page

### ISSUE THREAD

**Issue by yimeji** [tachiyomiorg/tachiyomi#6303]
### Steps to reproduce

1. Click on a webtoon.
2. Click webview to login to tapas account.

### Expected behavior

Can login just fine with webview and continue to browse tapas via tachiyomi.

### Actual behavior

After filled in login details and clicked on login button the page will refresh without being logged in.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung A51

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We don't control WebView functionality.

**Comment by yimeji** [comment]
When browse via external browser not tachiyomi webview I can login just fine.
