### ISSUE TITLE
Webtoons.com "Trust Anchor" error.

### ISSUE THREAD

**Issue by adfafdsfadfjalfj** [tachiyomiorg/tachiyomi#6305]
### Steps to reproduce

1.Try to update or open a chapter from the webtoons extension without first opening webtoons in webview

### Expected behavior

It should update or open the chapter

### Actual behavior

It doesn't and instead gives a "trust anchor" error until I open webtoons in webview then exit, then it allows either updating or reading but only for a few hours.

### Crash logs

https://i.imgur.com/NYNjrsLh.jpg

### Tachiyomi version

Stable 0.12.3

### Android version

Android version 11

### Device

Samsung Galaxy A51

### Other details

Webtoons.com All version 1.2.32
I don't think this is a cloudflare issue as it only started happening yesterday. Although it might be due to how I have 55 things I'm following there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AxelSilverdew** [comment]
Can confirm, reproducible at my end.
I was actually just about to open an issue about this myself.

**Comment by Seishirou101** [comment]
>     * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

you're in the wrong repo, but its already been [reported](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9977) and its on their side.
