### ISSUE TITLE
sort library by personal rating

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#6307]
### Describe your suggested feature

a way of ranking titles you read (possible starting from `1` being the lowest)

and a way to sort library by this personal rating

### Other details

good for savouring your favourite titles

and less mentally taxing when hunting for a title you are invested in when there are a lot of new updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Duplicate of  #2272

**Comment by skrshe** [comment]
coolio 👍

**Comment by skrshe** [comment]
sorry for duplicate 😹
