### ISSUE TITLE
(MAL) Tell user if tracker search query exceeds character limit

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6314]
### Describe your suggested feature

MAL I believe (haven't tested other trackers) has a 64-character limit on tracker search. If you exceed that it throws an HTTP Error 400.

This isn't really obvious to users so I think they should be alerted when they exceed the character limit.

Maybe something similar to this

![Screenshot_20211205-120044](https://user-images.githubusercontent.com/63973749/144733021-2abe0604-bdee-4b65-922f-ed1b23809ac9.png)

...or maybe just a toast message.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is 64 characters actually the limit?

**Comment by vengiare** [comment]
Not entirely sure, I tested it manually last time I tried.

**Comment by paulo27ms** [comment]
It is 64, unsure if the API has an option for longer queries but other apps that also use the API also have this limit.
