### ISSUE TITLE
Directly toggle "Only include pinned sources" in global search

### ISSUE THREAD

**Issue by AnataBakka** [tachiyomiorg/tachiyomi#6315]
### Describe your suggested feature

<s>Currently, when you press the switch near languages, you're not actually ticking or unticking sources. For example:
1. untick a source.
2. disable language.
3. enable language.

What happens:
source remains unticked.

Expected:
source gets re-ticked.
I'm not saying the language switch button should be changed to tick all sources when enabled. I'm saying that another button should be implemented to do this, i.e tick / untick all sources in a language.

Why:
For filtering purposes. Since this https://github.com/tachiyomiorg/tachiyomi/issues/1484 is not possible yet, i would like at least to be able to:
1. tick all sources when i need to
2. untick all sources and then manually tick those i care about)</s>

Edit:
I just found out that i can pin the sources i care about and tick the "Only include pinned sources" in the Browse-Global search settings, to fix my issue.
It would be nice if it would be put on the filter screen, rather than hidden in the settings tho.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #6654
