### ISSUE TITLE
Feature to filter different languages from chapters

### ISSUE THREAD

**Issue by SabikOP** [tachiyomiorg/tachiyomi#6317]
### Describe your suggested feature

When we open a Manga there should be a feature to filter the different types of languages.  If an extension has a lot of languages if there is a feature to filter them it would be easy to to find the language I'm looking for.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Sources are already separated by language. What exactly are you requesting this for?
