### ISSUE TITLE
Update all extensions for <android 11 with shizuku

### ISSUE THREAD

**Issue by AnataBakka** [tachiyomiorg/tachiyomi#6322]
### Describe your suggested feature

Since this https://github.com/tachiyomiorg/tachiyomi/issues/2665 is not an issue anymore now that shizuku is a thing. Can an "update all" button be added whenever installer == shizuku pretty please?
I've seen this here https://github.com/tachiyomiorg/tachiyomi/pull/6171 but it's just for android 12 as far as i understood right? since i haven't seen the option on my side

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
already added to preview, wait for next stable update
