### ISSUE TITLE
Push Notification Toggle for Library Categories

### ISSUE THREAD

**Issue by Zaploid** [tachiyomiorg/tachiyomi#6324]
### Describe your suggested feature

When editing categories for the library be able to toggle which ones send push notifications and which ones don't. Not excluding any category from updates, just which ones give push notifications on update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'd rather keep the app simple and keep it as all or nothing.
