### ISSUE TITLE
Saying page not found in manhwa having source as asura scans

### ISSUE THREAD

**Issue by Trashol** [tachiyomiorg/tachiyomi#6328]
### Steps to reproduce

Take any manhwas having source asura scans 
And try to read any chapter of it new or old

### Expected behavior

It says page not found

### Actual behavior

Usually it lets you read the chapters like any other manhwas having other sources

### Tachiyomi version

0.12.3

### Android version

Android 9

### Device

Oppo A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
