### ISSUE TITLE
App crashes at a certain manhwas after scrolling at it

### ISSUE THREAD

**Issue by Trashol** [tachiyomiorg/tachiyomi#6329]
### Steps to reproduce

Firstly in my case I tried to update covers of my mangas and manhwas.
Many had their cover removed and was totally black, I thought they would come back after sometimes.
But this manhwa i.e (Rise from the rubble ,source:- asura scans) didn't came after a long time also. 
So on day I was scrolling my reading category {made by myself} then it suddenly crashed without any message or dialogue box, I thought it was because my phone was laging but later I tried many times but it crashes at infront of the same manhwa and if I try to open the manhwa from the asura extension also it doesn't allow to enter the chapter list and if tried to enter it crashes again .

### Expected behavior

Cover should have been updated and it shall allowed me to enter the chapter list and wouldn't crash

### Actual behavior

It crashes without any dialogue box when trying to enter chapter list through or trying to even remove it from my categroies or even scroll to it

### Tachiyomi version

0.12.3

### Android version

Android 9

### Device

Oppo A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Where's the crash logs?
