### ISSUE TITLE
App crashes when adding tracking

### ISSUE THREAD

**Issue by Daantjerrr** [tachiyomiorg/tachiyomi#6330]
### Steps to reproduce

1. Open more > settings > tracking
2. Select Anilist
3. Wait for a minute or so

### Expected behavior

Being able to log onto Anilist without the app crashing.

### Actual behavior

Tachiyomi keeps crashing when I try to log in on Anilist, from the setting > tracking menu. It does not seem to matter whether you interact with Anilist (e.g. enter log-in information) or not: the app just crashes after a minute or so. I do not get an error message, I just get transported back to the overview of all apps on the device.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 10

### Device

Boox Note Air

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please upload crash logs if the issue is about a crash.
