### ISSUE TITLE
close button "x" is not visible in manga cover

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6331]
### Steps to reproduce

1. go to manga page
2. click manga cover

### Expected behavior

close button should be visible

### Actual behavior

![IMG_20211208_134617](https://user-images.githubusercontent.com/84634607/145155409-88e9eb1b-4c0b-4465-9bab-a6b646df3313.jpg)

### Tachiyomi version

r3999

### Android version

Android 11

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by leveste** [comment]
Maybe it's on the actual phone screen that you can't see it, cause on the screenshot it looks fine. I guess it could use a darker color with the light theme, as it's a pretty faint gray.

**Comment by AnujSsStw** [comment]
Maybe it's the theme problem because with the normal white and dark mode it seems to appear fine.
![1819fd35-88af-4d04-90bc-caa675c43d0f](https://user-images.githubusercontent.com/92370865/145675904-1bb368d5-2759-4be3-a862-fdeff1f21140.jpg)
