### ISSUE TITLE
Make "remove downloaded chapters" as the default option when deleting items in library view

### ISSUE THREAD

**Issue by fayumot** [tachiyomiorg/tachiyomi#6333]
### Describe your suggested feature

I think "remove downloaded chapters" should be the default option when deleting items in library view instead of "remove manga from library.
1. Accidentally deleting your downloaded chapters are a lot more preferable than accidentally removing manga from your library
2. At least in my use case (tachiyomi set to auto-download new chapters), I use the "remove downloaded chapters" options a lot more than "remove manga from library"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
What is really needed is the ability to delete orphaned downloads. There's already issues for that though.
