### ISSUE TITLE
Per category reading mode

### ISSUE THREAD

**Issue by BhaturaGuy** [tachiyomiorg/tachiyomi#6337]
### Describe your suggested feature

Pre-specify settings (settings available when reading a chapter) in the category so that manga added or already added manga under it should default/change to that.

For example: Let's say I add X manga under Manhwa Category and I have pre-specified that manga under this category should default to Reading mode: Webtoon, so now that X manga should default to webtoon reading mode.

### Other details

Other settings can be everything under a chapter setting like _Reading Mode, General, Custom Filter_.

Maybe this can be applied to specific extension(?)
Like Toonily should always default to webtoon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by 2ndemosthenes** [comment]
It would also make sense if we could change these settings per extension, as suggested in https://github.com/tachiyomiorg/tachiyomi/issues/3318

**Comment by stevenyomi** [comment]
/edit-title "Per category readming mode and filters"

**Comment by stevenyomi** [comment]
/edit-title "Per category reading mode and filters"

**Comment by stevenyomi** [comment]
Per category filters are tracked in #305

**Comment by arkon** [comment]
I'm not sure this actually makes sense given items can be added to multiple categories.

#3318 is probably the best alternative.

**Comment by BhaturaGuy** [comment]
> I'm not sure this actually makes sense given items can be added to multiple categories.

They can simply default to different reading modes under different categories. But behave as default (in general settings) when not under any category.

> #3318 is probably the best alternative.

Kind of, but then again I can't see why this issue won't be reopened by someone again since mangasee offers both webtoon and manga for example. Setting it to default reading mode to LTR  wouldn't make any change since LTR is already default for every manga (current version), unless manually changed. But if someone wants to add a lot of webtoon fetched from mangasee and then change the reading mode to webtoon manually  would require a lot of effort.

I can see this feature request might require a lot of work, but it isn't possible that it won't be requested by someone again in future.

**Comment by arkon** [comment]
> They can simply default to different reading modes under different categories. But behave as default (in general settings) when not under any category.

An item can only have one reading mode set, hence it not making sense.

> Kind of, but then again I can't see why this issue won't be reopened by someone again since mangasee offers both webtoon and manga for example. Setting it to default reading mode to LTR wouldn't make any change since LTR is already default for every manga (current version), unless manually changed. But if someone wants to add a lot of webtoon fetched from mangasee and then change the reading mode to webtoon manually would require a lot of effort.

It's still better an enhancement to the current state. It seems more reasonable than this more unintuitive request. 

> I can see this feature request might require a lot of work, but it isn't possible that it won't be requested by someone again in future.

I don't particularly mind that either one requires effort considering it's not high priority anyway. If someone requests it, it'll just be closed as a duplicate of this request.
