### ISSUE TITLE
Include error type in "# updates failed" notification.

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi#6345]
### Describe your suggested feature

At the top of the notification should be a list of the relevant error types.

### Other details

This would be handy for convenience. If the error is a timeout or a Cloudflare error you can generally assume it will fix itself next update and dismiss the notification, but currently you need to open the log .txt file to see the error type and manually dismiss the notification which is quite cumbersome.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Would probably make more sense to have a proper in-app UI that the notification goes to. Closing in favour of #4616
