### ISSUE TITLE
5.1.1 android support

### ISSUE THREAD

**Issue by skull1** [tachiyomiorg/tachiyomi#6351]
### Describe your suggested feature

hello i just realized i cant update tachiyomi because i have the android version 5.1.1
will it get some support?
can i still continue to use the latest version of 5.1.1 without massive suffering/bug fixes or i am missing important features?
and were i can download the latest version?

thanks for your work and sorry if i used wrong label or wrong place to post.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> will it get some support?

[Tachiyomi 0.10.12](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.10.12) is the last release with Android 5.x support.

> can i still continue to use the latest version [...] without massive suffering/bug fixes or i am missing important features?

YMMV. We do not explicitly support any old versions of the app. Extension support is best-effort until we need to make larger underlying changes.

Android 5.1.1 is 5 years old and itself suffers from security issues. I'd highly recommend updating if possible.
