### ISSUE TITLE
Komga tracker and migration

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi#6354]
### Steps to reproduce

1. Have a manga from a Komga server, with Komga tracking enabled.
2. Migrate this manga to the same or a different source and opt to include trackers in migration.

### Expected behavior

Komga tracker is updated to reflect the new entry (for Komga -> Komga), or is removed when migrating to non-Komga sources.

### Actual behavior

Komga tracker is copied over directly to the new entry.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Galaxy Tab S7

### Other details

The main motivation for this is that sometimes changes to my server or to Komga itself require migration from an old Series to a new Series. Since the motivation for migrating generally also means that the old Series link (and tracker) no longer functions, the user ends up with a non-functioning Komga tracker despite migration.
The ideal case would be that the tracker automatically switches to match the Komga Series it is connected to, but a "good enough" solution in my opinion would be to not migrate the Komga tracker at all. This would make it apparent from the manga details that a tracker was missing, and the tracker filter in the library could be used to identify Komga entries that still needed their tracker updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
@gotson Do you have any input on this?

**Comment by gotson** [comment]
What's the current behavior for other trackers? It's been a long time I looked at this, so not sure if this is komga specific or not?

**Comment by arkon** [comment]
Other trackers are just copied over, but they're not as tightly coupled with the actual entry as they would be for Komga.
