### ISSUE TITLE
Sort read manga by last read for "Unread" sort mode

### ISSUE THREAD

**Issue by anoxmoxss** [tachiyomiorg/tachiyomi#6355]
### Describe your suggested feature

right now if i select the "Unread" to sort my manga it will start showing the unread manga on top. but after the unread it starts being "Alphabetically" which is very annoying. i would like to request a new "Sort" or a "modification" to the currents. 

i would like it to show "Unread" manga then "Last read" manga. right now it is "Unread" then "Alphabetically". if i want to reread the chapter i have to go and search for it among my many manga. i know there is a search feature but sometimes the manga title is so confusing i wouldn't know how to write it without copy pasting. so i want it to be "Unread" manga then "Last read" manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by zzzb123** [comment]
seconded.  some sort of sort tie-breaker config options would be nice to have.  alphabetical tie-breaking is good, but not always the best option for everyone.

**Comment by arkon** [comment]
Keeping it as alphabetical as it's always consistent/predictable.
