### ISSUE TITLE
Open With ... option for supported file formats (CBR, EPUB, etc.)

### ISSUE THREAD

**Issue by shashank-p** [tachiyomiorg/tachiyomi#6357]
### Describe your suggested feature

I know that Tachiyomi has no intention of supporting ebook features but app can give option to open those types files (epub,pdf etc) with "Open With" dialog which displays supported apps.

Except for built in ebook reader Tachi app already provides User to oraganize his/her books similar to manga (category,sorting,filtering and maybe trackers).

As Tachi supports many self hosted comic servers with extension (which also includes ebooks (epub,pdf)) from there user can download the ebooks.

### Other details

Example for mentioned feature request : 

![open with](https://user-images.githubusercontent.com/7925118/146637528-c1c2d817-f2e4-452d-ae6c-cb072ae9da4a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
This out of the scope of the app, literally. The app is an image reader, that's it.

**Comment by arkon** [comment]
This isn't really possible since the reader revolves around the concept of a library entry, not just some arbitrary file.

#3747 _might_ be similar.
