### ISSUE TITLE
XCaliBR Scans - Mirror imaged

### ISSUE THREAD

**Issue by SoloLeveller1** [tachiyomiorg/tachiyomi#6362]
### Steps to reproduce

1. Open manga "Dragon Master or Martial God Asura"(since I only had those two in library)
2. Open latest chapter/chapters

### Expected behavior

The images get mirrored

### Actual behavior

The images don't get mirrored

### Tachiyomi version

0.12.3

### Android version

Android 12

### Device

Redmi Note 7 Pro(violet)

### Other details

Webview works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Also it's already been reported.

**Comment by SoloLeveller1** [comment]
![Uploading Screenshot_20211219-105529_Tachiyomi.png…]()

**Comment by SoloLeveller1** [comment]
Oh sorry for the trouble. I'll remove the issue then

**Comment by SoloLeveller1** [comment]
I thought I was in the extention repository
