### ISSUE TITLE
Extension update not installing

### ISSUE THREAD

**Issue by Pablo0o0** [tachiyomiorg/tachiyomi#6363]
### Steps to reproduce

1. Press update extension 
2. Extension downloads
3. Extension stuck on downloading and doesn't install 

### Expected behavior

Normally after pressing update, it would download update then install immediately after download finishes 

### Actual behavior

I press update, it starts downloading but stays stuck on downloading forever. 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung Galaxy A30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
You can force stop the app and try again, or download directly on the [website](https://tachiyomi.org/extensions/)
