### ISSUE TITLE
Navigation layout. Invert L shape

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi#6368]
### Describe your suggested feature

Bottom and left would be for next page. Right and/or top would be for previous page. 

Would be nice for when reading manga do you can either tap the left it the bottom fit the next page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Sounds like `L Shaped` with invert tapping `Horizontal`. That would make the bottom and left go next, and top and right go previous

**Comment by vipzzx** [comment]
Yeah that's the word. Inverted!

**Comment by Seishirou101** [comment]
are you saying what ghostbear suggested doesn't do what you want?

**Comment by vipzzx** [comment]
What ghost bear said if exactly what I want. I just couldn't find the right word
