### ISSUE TITLE
Hidden categories

### ISSUE THREAD

**Issue by bartbouten** [tachiyomiorg/tachiyomi#6370]
### Describe your suggested feature

Toggle per category to have it hidden or locked behind a security wall. Preferably with fingerprint.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

#1508
