### ISSUE TITLE
Dynamic theme option missing in recent preview builds

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/tachiyomi#6380]
### Steps to reproduce

(This is more like the steps I did when I found the issue).

1. Be on a preview build of Tachiyomi before r4011
2. Observe that the Dynamic theme option is available on my device
3. Update preview build to r4011 or later

### Expected behavior

The dynamic theme option is still available

### Actual behavior

The dynamic theme option has disappeared

### Tachiyomi version

Preview r4011

### Android version

Android 12

### Device

Samsung Galaxy S21

### Other details

This might be a Samsung (or vendor at least) specific issue, as there's a few other theming issues across the device...

Seems like Samsung reports false to the `DynamicColors.isDynamicColorAvailable()` check introduced in tachiyomiorg/tachiyomi@9b64b01, despite the fact that dynamic colors are in fact, available (and worked before that commit).

*Samsung, please get your theming code fixed*

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This will be fixed whenever Samsung makes it to the officially supported list of vendors.
