### ISSUE TITLE
Add new source

### ISSUE THREAD

**Issue by MoElhadi** [tachiyomiorg/tachiyomi#6386]
### Steps to reproduce

1.I wanna add two new sources
2. First one https://swatmanga.co/
3. The second https://teamxmanga.com/

### Expected behavior

I expect from you to add then as fast as you can

### Actual behavior

They didn't add yet

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Galaxy A50

### Other details

Please add them 🙏 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please read the acknowledgements instead of just ticking the boxes
