### ISSUE TITLE
Slow comic and chapter loads in some extensions

### ISSUE THREAD

**Issue by totopesce** [tachiyomiorg/tachiyomi#6387]
### Steps to reproduce

1. Open flamescans.
2. It will take quite some time to load the comics, and more to load poster.
3. Open a comic, it will take a couple minutes to load the amount of chapters

### Expected behavior

It should load similar to what it takes opening the site from the app.

### Actual behavior

Now its faster to check the comics and chapters in their website that having tachiyomi load them, on tachiyomi it may take several minutes to load comics and chapters, and sometimes it seems like it just gives up and stops loading. 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Xiaomi pad 5

### Other details

I just bought this device and before I was using a samsung galaxy tab s2 and I didnt have this problem, dont know if this could be because of android 11 storage scope, IIRC, or something different.
Some load just fine, like mangadex that takes like 5 secs, and others like flamescans take minutes to just load the names of the comics, or when I open one it takes minutes for the chapters and metadata.

Edit: dont know if its because its taking the app too long to load chapters, but its been pausing my downloads frequently, and it didnt do that on my old device.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.
wrong repo, but flame scans does a lot of things to prevent scarpers so maybe thats why its slow, it loads fine for me, so maybe with your connection to them.

**Comment by totopesce** [comment]
Itas nota an issue issue with AN extensions, but with several, which could mean its the app and not the extensions, because its not only flamescans.
