### ISSUE TITLE
Forced closed

### ISSUE THREAD

**Issue by Carnaken** [tachiyomiorg/tachiyomi#6390]
### Steps to reproduce

1.open the app
2.go to browse
3. Click global search 
4. Search of a manga

### Expected behavior

The app will still continue functioning despite having multiple extension to search for a manga.

### Actual behavior

The app forced stop and crashing while scrolling in global search

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Vivo y91

### Other details

Its a hassle that every time i search manga on global search the app crashes and i will start the loading again. Specially sometimes the loading of search in global search is so slow considering i have multiple extensions using.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Share the crash logs if your issue is about a crash.
