### ISSUE TITLE
one punch man (manga freaks extension) chapter 21 can't download

### ISSUE THREAD

**Issue by sumacool** [tachiyomiorg/tachiyomi#6396]
### Steps to reproduce

first, use mangafreaks extension
second, try downlaod opm chapter 21
third, once it get to page 74 it will stuck at that page

### Expected behavior

it should be download well like the other chapter

### Actual behavior

when I tried download OPM chapter 21 it keeps stuck at 74 page then got an error
![Screenshot_20211227-202109](https://user-images.githubusercontent.com/66295833/147471481-210616a4-7b09-4f34-beed-21c890c66ced.png)

### Crash logs

![Screenshot_20211227-202109](https://user-images.githubusercontent.com/66295833/147471829-7f77fff0-00b7-489c-acf9-6a30282536af.png)

### Tachiyomi version

0.12.3

### Android version

Android 9

### Device

ADVAN TAB 10

### Other details

nothing just an download error plz fix

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
