### ISSUE TITLE
Can't open the app/Force closed

### ISSUE THREAD

**Issue by arichua** [tachiyomiorg/tachiyomi#6399]
### Steps to reproduce

1. Accidentally deleted the installed app that previously working
2. Reinstalled again from website of Tachiyomi
3. Installed then I tried to open but i can't open it. Forced closed.
4. Installed SAI app to check what is wrong (as recommended in troubleshooting)
5. Installed the app but still can't open

### Expected behavior

I should be able to open again the app since it works earlier

### Actual behavior

Forced close.  Try any possible ways to open but it keeps closing. My internet is fine though

### Tachiyomi version

0.12.3

### Android version

Miui global 12.5.3 / android 11

### Device

Redmi 9T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
