### ISSUE TITLE
 More descriptive download errors

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#6401]
### Describe your suggested feature

Whenever I get a download error all  it says is "Chapter 1 no page found" or "Chapter 1 http  error 404",  but it never actually tells me for which manga I'm downloading.
![image](https://user-images.githubusercontent.com/62863320/147548015-522ca179-9e85-4a38-8201-593062037cd0.png)
![image](https://user-images.githubusercontent.com/62863320/147548066-5319cce7-08b5-49aa-b8f5-40fc9c6306c8.png)
![image](https://user-images.githubusercontent.com/62863320/147548087-74e639d1-0433-4933-bfe5-21aa074f7284.png)

### Other details

The reason this is a big issue is because I travel a lot and I don't have access to the internet a lot so I downloaded bulk . It's kind of hard to see the issue if I don't know which manga is causing the issue. Thanks for taking it consideration my thoughts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MohitMandalia** [comment]
Would this be perfect? @arkon @CarlosEsco 
let me know if I can send a PR for this.
Regards.

![Screenshot_20211229-215529_2](https://user-images.githubusercontent.com/36087806/147683368-7f1a7b5c-ece7-45aa-908f-72d521f49dcb.png)

**Comment by FourTOne5** [comment]
You can make a pr for any issue that is open.

**Comment by MohitMandalia** [comment]
okk Thanks but I am new here so I thought of asking before sending a PR.

**Comment by FourTOne5** [comment]
next time ask in the discord server
