### ISSUE TITLE
just fix/remove this problem plz 

### ISSUE THREAD

**Issue by sumacool** [tachiyomiorg/tachiyomi#6402]
### Describe your suggested feature

(https://youtu.be/QJ9oQ50jW5Y)

### Other details

it's so damn annoying why I can't delete bookmarked chapter for no reason plz plz that annoying issue idk if it's a bug or if that was like that from the beginning but fix this annoying issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Did you enable the option to be able to delete them?

**Comment by sumacool** [comment]
> 

oh I actu but my other problem is that it un bookmarks the chapter and it's kinda annoying

**Comment by sumacool** [comment]
> Did you enable the option to be able to delete them?

oh I actually don't know that but now there's a new problem that is it un bookmarks the chapter could you fix that part

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6403

Next time also right a better description and title or i will just close the issue.
