### ISSUE TITLE
Deleting a bookmark chapter unbookmarks it

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi#6403]
### Steps to reproduce

Bookmark downloaded chapter, enable delete downloads for bookmarks, delete the chapter.  

### Expected behavior

chapter should remain bookmarked

### Actual behavior

chapter does not remain bookmarked

### Tachiyomi version

0.12.3

### Android version

XXXX

### Device

XXX

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MohitMandalia** [comment]
Hi,

Can I work on this issue may be if there is a plan to implement it.

Regards.

**Comment by arkon** [comment]
Feel free to take a stab at it.

**Comment by MohitMandalia** [comment]
Can I get some context here I downloaded a chapter and bookmarked the chapter now I cant delete the chapter until I unbookmark it.

**Comment by CarlosEsco** [comment]
> Can I get some context here I downloaded a chapter and bookmarked the chapter now I cant delete the chapter until I unbookmark it.

you need to enable the setting to delete downloads for bookmark chapter.   Then when you delete the bookmarked chapter it auto unbookmarks it when it shouldnt

**Comment by MohitMandalia** [comment]
not able to reproduce it in my case it is still bookmarked. maybe you can tell me what specific you did to reproduce it that would help.

Regards.

https://user-images.githubusercontent.com/36087806/147676794-02a3594b-7f11-4f9a-a7da-205085a4ae27.mp4

**Comment by CarlosEsco** [comment]
@sumacool since you  reported the issue

**Comment by FourTOne5** [comment]
Can't reproduce in 0.12.3 and r4045 so he probably was.
