### ISSUE TITLE
Don't count "all" and "other" as language in language badge

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi#6404]
### Describe your suggested feature

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
I can understand "other" but why "all"?

**Comment by arkon** [comment]
Doesn't really make sense to have exceptions.
