### ISSUE TITLE
No search options for several extensions

### ISSUE THREAD

**Issue by A-1K** [tachiyomiorg/tachiyomi#6405]
### Steps to reproduce

Go to extensions like mangadex, nhentai.
No search or filter option appears.

### Expected behavior

Should be a search option in the top right

### Actual behavior

Only list and open in web options available

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You need to click on the source name and not on latest button to be able to search.

**Comment by A-1K** [comment]
oh, that was dumb. my bad
