### ISSUE TITLE
Automatic tracker

### ISSUE THREAD

**Issue by Prosphyte** [tachiyomiorg/tachiyomi#6406]
### Describe your suggested feature

Pretty sure its already explained in the title

### Other details

I would suggest mal-sync...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Automatic in what sense?

**Comment by JudahGoldstein** [comment]
Pretty sure this is already implemented, unless it's an SY exclusive feature which I don't believe it is. Should sync apon completion of a chapter.

**Comment by CrepeTF** [comment]
Will close this for now, if OP elaborates and is indeed a different feature it will be reopened.
