### ISSUE TITLE
Auto-Download for Specific Categories 

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#6408]
### Describe your suggested feature

Auto Download new chapters from specific categories instead of from all categories

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Dude you trolling?
![IMG_20211229_114224_019](https://user-images.githubusercontent.com/59261191/147630948-8c3686a1-171e-4fb7-83a4-28b3f4c17947.jpg)

**Comment by kingtie** [comment]
> Dude you trolling? ![IMG_20211229_114224_019](https://user-images.githubusercontent.com/59261191/147630948-8c3686a1-171e-4fb7-83a4-28b3f4c17947.jpg)

It's not toggled on and as you can see for the Delete chapters settings it shows up when it's not even on. I would have never turned on the future knowing that it could start downloading stuff at random.
![Screenshot_20211230-134237_Tachiyomi](https://user-images.githubusercontent.com/62863320/147722398-253bfc76-eae7-4b3f-9b97-664a18013bcb.png)

**Comment by FourTOne5** [comment]
> It's not toggled on and as you can see for the Delete chapters settings it shows up when it's not even on. I would have never turned on the future knowing that it could start downloading stuff at random. ![Screenshot_20211230-134237_Tachiyomi](https://user-images.githubusercontent.com/62863320/147722398-253bfc76-eae7-4b3f-9b97-664a18013bcb.png)

We were talking about "Download New Chapter" why are you pointing out things in "Deleting Chapter"

**Comment by Soitora** [comment]
> > Dude you trolling?
> 
> It's not toggled on and as you can see for the Delete chapters settings it shows up when it's not even on. I would have never turned on the future knowing that it could start downloading stuff at random.
>

Why are you pointing at the **Delete chapters** settings? That has nothing at all to do with **Auto-download**.

Also, the setting to set only specific categories to download exists, so this issue is redundant. Explore the app.

**Comment by kingtie** [comment]
> > > Dude you trolling?
> > 
> > 
> > It's not toggled on and as you can see for the Delete chapters settings it shows up when it's not even on. I would have never turned on the future knowing that it could start downloading stuff at random.
> 
> Why are you pointing at the **Delete chapters** settings? That has nothing at all to do with **Auto-download**.
> 
> Also, the setting to set only specific categories to download exists, so this issue is redundant. Explore the app.

It was for reference to show how one was done differently than the other. Even though they exist on the same page and are settings that are quite literally marrying each other, but thank you for helping me solve my issue.

**Comment by Soitora** [comment]
> > > > Dude you trolling?
> > > 
> > > 
> > > It's not toggled on and as you can see for the Delete chapters settings it shows up when it's not even on. I would have never turned on the future knowing that it could start downloading stuff at random.
> > 
> > 
> > Why are you pointing at the **Delete chapters** settings? That has nothing at all to do with **Auto-download**.
> > Also, the setting to set only specific categories to download exists, so this issue is redundant. Explore the app.
> 
> It was for reference to show how one was done differently than the other. Even though they exist on the same page and are settings that are quite literally marrying each other, but thank you for helping me solve my issue.

**Auto delete** goes well with **Auto download**, but **Auto delete** also works for **Manual** downloads, so it's not like both are dependent on each-other, that's why you see the **Auto delete** settings without having set **Auto download**...
