### ISSUE TITLE
Misaligned Pages in Webtoon Reading Mode

### ISSUE THREAD

**Issue by alexporth** [tachiyomiorg/tachiyomi#6409]
### Steps to reproduce

1. Open a Tapas Webtoon (I think I have also seen this in Webtoons from the Webtoon source)
2. Scroll until you see a misaligned page

### Expected behavior

The pages should be aligned.

### Actual behavior

The pages are not aligned correctly. Form what I can tell some form of cropping or resizing of the images seems to be happening in "Webtoon" and in "Continuous vertical" reading modes. As when vertical is selected the images line up fine horizontally.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Device

OnePlus 5T

### Other details

It doesn't seem to happen with every page, just some. I haven't found a pattern yet. I have seen some page misaligned to the right and others to the left.
![Copy of Screenshot_20211229-122421](https://user-images.githubusercontent.com/4528445/147658366-9fba0b5a-2e3d-48a8-b7f5-684fa50c9804.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Turn off crop borders
