### ISSUE TITLE
Dynamic Color not showing on preview build

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi#6410]
### Steps to reproduce

Go to settings > appearance > select Dynamic Color

### Expected behavior

See Dynamic Color option

### Actual behavior

Dynamic Color option not showing

### Tachiyomi version

version 0.12.3-4045

### Android version

Android 12 (Pixel Experience ROM)

### Device

Galaxy Note 10+ 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6380

**Comment by keyjeyelpi** [comment]
But I'm on a custom rom, an AOSP rom to be exact, so it's not really a oneui issue

**Comment by keyjeyelpi** [comment]
It's working on the stable build, so I know that it works. It's just that the stable build doesn't have the new material you design

**Comment by FourTOne5** [comment]
Maybe try reading the full conversation

**Comment by keyjeyelpi** [comment]
> Maybe try reading the full conversation

I did. The thing is, dynamic color theme should be working on the preview build as it's working on the stable build. It's not a matter of if I'm using a Samsung phone or not since I'm using a custom rom as stated

**Comment by FourTOne5** [comment]
In Stable it just checked your android version but In preview it checks if your device is officially supported (it isn't related to your rom)

**Comment by keyjeyelpi** [comment]
> In Stable it just checked your android version but In preview it checks if your device is officially supported (it isn't related to your rom)

Ooohhh, this explains why. Thank you so much.

**Comment by keyjeyelpi** [comment]
So, quick workaround for this. Uninstall the tachiyomi preview and install an older version (r3833), select dynamic color and then update to the latest build.

**Comment by CarlosEsco** [comment]
quick workaround, this is going to stable and will be going away so either bug samsung, or get a better device.

**Comment by arkon** [comment]
More context: the Material Components library has various checks to ensure compatibility, but it mostly relies on more "vanilla" states, i.e. that a device manufactured by Samsung runs One UI and therefore (currently) doesn't properly implement dynamic colours (despite it mostly working).

The upstream dependency will eventually be updated as things change and we'll pull in those changes too. I'm unaware of how they intend on dealing with scenarios like custom ROMs that either reimplement the system or are based on 12.1+.
