### ISSUE TITLE
Hide color filter blend mode when custom filter is off

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#6411]
### Describe your suggested feature

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Done in fe82cdb9c85274e0c9b904ec6b37fac97d01ea37
