### ISSUE TITLE
"Download Now" action for whole series

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#6412]
### Describe your suggested feature

Start downloading now for a whole series.

### Other details

So that i don't have to go and do all chapters of the story one at a time or cancel all of my downloads just to have to start it back up again..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Afaik there is a button "download" with a download all option on top right corner of a library page. I think that pretty much cover your needs, am i wrong?

**Comment by kingtie** [comment]
> corner

This picture shows what happens when you download an individual chapter and then click on the download button again.
![Screenshot_20220103-181703_Tachiyomi](https://user-images.githubusercontent.com/62863320/147915247-7f0ebfa0-892d-4977-8a7d-b63eca26b8bb.png)

This one shows when you try to download the entire series.
![Screenshot_20220103-181647_Tachiyomi](https://user-images.githubusercontent.com/62863320/147915272-58753032-2c84-456b-9090-2d8006db1471.png)
I would like to feature at it where I can do the download now for the entire series and move it to the top of my download queue. I download in bulk, because of my job over the course of months I am in places where I don't have access to the internet. So I just start my downloads sometimes about a hundred series and just leave it alone, because when I do have access to the internet it's super shotty and slow.

**Comment by kingtie** [comment]
Half of the time I'm not able to download all the series so being able to move them around without  stopping is also super beneficial

**Comment by arkon** [comment]
Closed by #6794

**Comment by frankete333** [comment]
I made the pull request because I wanted this feature for mi self a long time ago, I didn't know that this has been requested before XD, I hope it's useful.
