### ISSUE TITLE
Option to flip "Updates" sort order

### ISSUE THREAD

**Issue by JudahGoldstein** [tachiyomiorg/tachiyomi#6414]
### Describe your suggested feature

Pretty self explanitory, many people (myself included) would get much more utility from the updates tab is it were sorted old to new rather than the current new to old. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Why would that be useful? You should just sort your library if you want to read things added a long time ago.

**Comment by JudahGoldstein** [comment]
In the current version of the app there's no easy way to find the oldest unread chapter in your library. Right now you need to scroll to the bottom of your updates tab then scroll all the way back up until you hit an unread chapter. 

I figure requesting the option to flip the order is easier to implement than a new sorting option to sort by oldest unread chapter in the library tab.

**Comment by FourTOne5** [comment]
"Updates" tab doesn't only include unread chapter it also includes read chapters so you can just use the Fetch Date sort in reverse order since in updates tab chapter are sorted by fetch date

**Comment by arkon** [comment]
The updates section is also intentionally capped to the past 3 months anyway.
