### ISSUE TITLE
Check update by pages and not only by chapters

### ISSUE THREAD

**Issue by velteyn** [tachiyomiorg/tachiyomi#6415]
### Describe your suggested feature

Hello, let me express my appreciation for this app that is GREAT !! 
I have a suggestion: 
Some authors update their work not by chapters but by pages.. 
As far as I understand the app scans only for new chapters and gives a [1]  blue number after the local chapter numbers are less than the discovered unread ones.
I suggest to have the option for scan also by pages numbers. If a new page is found signal  a [n] RED number for a new page discovered

### Other details

Authors like Totempole progress  page by page and you can find only 1 (one) chapter !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This would introduce unreasonable load to sources and be slow for users.

**Comment by velteyn** [comment]
oh. ok but I think it could be done on a voluntary configuration regarding a single comic... no ?

**Comment by velteyn** [comment]
also a refresh button could do..

**Comment by FourTOne5** [comment]
No still too much request.

**Comment by arkon** [comment]
If a particular source doesn't fit within the expected model/assumptions that Tachiyomi operates with, open an issue in the extensions repo for it to potentially be changed.
