### ISSUE TITLE
Add a comments section

### ISSUE THREAD

**Issue by IgnFed** [tachiyomiorg/tachiyomi#6416]
## Describe your suggested feature

# This could contain one of the follow options:
* If you swipe to the right/left side , you'll see all the comments for that manga from the server it came from.
* When you finish a chapter, at the end of this, you could see the comments for that particular chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Duplicate of #4336

**Comment by IgnFed** [comment]
Sorry, i've searched the "add comments" or "comments" word/s but nothing appeared.
I'm going to close this issue.
Thanks for answering.
