### ISSUE TITLE
to update tachiyomi (0.12.3) 

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi#6417]
### Describe your suggested feature

Why is the update of the application delayed for three months?

I don't want the beta version
![Screenshots_2021-12-30-16-25-09](https://user-images.githubusercontent.com/90999286/147756029-9ae102e6-9539-4854-a4a3-2ad08ce1376a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
There's no ETA for the next stable version and there's no problem to keep using the latest one. Wait until the next one is released.
