### ISSUE TITLE
GMANGA extension won't load manga or chapters

### ISSUE THREAD

**Issue by Salsabealk** [tachiyomiorg/tachiyomi#6420]
### Steps to reproduce

1. Open GMANGA from extensions 
2. Choose manga to read 
3. Click on Read to open chapter

### Expected behavior

It should show all mangas on the extension and load all chapters

### Actual behavior

But it didn't show any manga or load chapter and shows errors like these : 
![Screenshot_20211231-145525_Tachiyomi](https://user-images.githubusercontent.com/96913833/147827401-8df403b3-947b-4910-9443-6c9753728fb9.jpg)
![Screenshot_20211231-145549_Tachiyomi](https://user-images.githubusercontent.com/96913833/147827403-fd4253f6-ab22-48f9-981a-074f24748a04.jpg)

### Crash logs

HTTP error 400
HTTP error 103

### Tachiyomi version

Tachiyomi version 0.12.3

### Android version

Android 11

### Device

Samsung galaxy A71

### Other details

I noticed that this started to happen after I updated GMANGA in Extensions 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please read what you acknowledge instead of just checking the boxes.
