### ISSUE TITLE
Make the "Resume" button go to current chapter being read or the following after the last read chapter

### ISSUE THREAD

**Issue by Educorreia932** [tachiyomiorg/tachiyomi#6421]
### Describe your suggested feature

**Example:**
    - If I'm on page 3 of chapter 583, and I haven't read any other chapter, I want to resume in it, instead of going to chapter 1

**Example**
    - If the only chapter I've read is chapter 583, I want to resume in chapter 584, instead of going to chapter 1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You should mark the previous chapters as read.

**Comment by Educorreia932** [comment]
> You should mark the previous chapters as read.

I know, but sometimes I haven't read them yet, so I don't want to mark them as so

**Comment by Riztard** [comment]
use history
