### ISSUE TITLE
SMB function would be better than komga

### ISSUE THREAD

**Issue by Heavyarms04** [tachiyomiorg/tachiyomi#6422]
### Describe your suggested feature

I said to you in hopes of being able to acquire an SMB version 1 feature, in which you don't have to rely on a PC to access your manga stored on a Nas or on a hard drive connected to a router.

Komga is not practical since it must have a mandatory PC on all the time, it maintains an almost constant access to the hard drive even if I am not using any manga, it is extremely delayed to update your library arriving in my case up to 1 day and a half
I am hopeful that you can develop some extension that easily achieves access, I have seen applications that do but none has the fluidity of tachiyomi or the possibility to download the content to the android device

Finally if it is possible to tell me what are the difficulties to implement the SMB function, maybe someone who reads the post can help implement the desired extension

Nuevamente les pido disculpas por mi pésimo manejo del inglés espero puedan entender mis palabras

Again I apologize for my poor handling of English I hope you can understand my words

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wouldn't you need some form of PC or NAS to access with Samba?

Komga (and other similar things) offer stronger, well-defined structures that fit with how Tachiyomi works instead of arbitrary file structures.

**Comment by FourTOne5** [comment]
All extensions are community made. Komga was added by the creator of Komga themself. You can also add SMB if you wish.
