### ISSUE TITLE
linux gzip may fix "gzip finished without exhausting source"

### ISSUE THREAD

**Issue by AoEiuV020** [tachiyomiorg/tachiyomi#6424]
### Steps to reproduce

Same bug as @astraea19 (https://github.com/tachiyomiorg/tachiyomi/issues/4463)
@arkon says the file is a corrupted file (https://github.com/tachiyomiorg/tachiyomi/issues/4463#issuecomment-782685085)
But I repaired my corrupted backup file through the gzip command under linux
Here is my backup file  tachiyomi-gz-fix.zip(https://github.com/AoEiuV020/tachiyomi/releases/download/v0.12.3/tachiyomi-gz-fix.zip)

tachiyomi.proto.gz(56dddd353502a634fdf06f3202509539)   is the original backup file generated by tachiyomi ,  tachiyomi will say "gzip finished without exhausting source" when importing,
> I just transfer the file to my Synology NAS and retrieve it in a few hours
I don’t know why it’s corrupted. I think my network is healthy.  

 
tachiyomi.proto(cd70a89d1017944b47510091530499ee)   is decompress by gzip, 
```shell
cat tachiyomi.proto.gz |gzip -d > tachiyomi.proto
```

good.proto.gz(c57a0544010274638d532d977f86f625)   is recompress by gzip,   this file is healthy,  I have successfully imported this backup file,
```shell
cat tachiyomi.proto |gzip > good.proto.gz
```

### Expected behavior

Import gzip backup files normally

### Actual behavior

Invalid backup file
gzip finished without exhausting source

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

xiaomi mix 4

### Other details

I want to say that this bug should actually exist instead of simply saying that the file is corrupted and close the issue. 
Since Linux can decompress this file, Android should also be able to do it.

![image](https://user-images.githubusercontent.com/11682198/147847493-fb884e87-159e-419e-96a3-88710582af2b.png)
![Screenshot_2022-01-01-17-03-00-955_com google android documentsui](https://user-images.githubusercontent.com/11682198/147847539-0fded62e-a6f9-4c67-baec-c0d8be784bbb.jpg)
![Screenshot_2022-01-01-17-03-15-184_eu kanade tachiyomi](https://user-images.githubusercontent.com/11682198/147847537-310af31a-69fd-4aba-8fb7-7a0587b0d631.jpg)
![Screenshot_2022-01-01-17-03-11-020_eu kanade tachiyomi](https://user-images.githubusercontent.com/11682198/147847538-f0366d5e-f16b-461f-bf97-4dde6ecf8948.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AoEiuV020** [comment]
Forgot to say, I checked, the backup comics are not lost after importing

**Comment by arkon** [comment]
Preview (so next stable) tries to validate the file after creation, so it should at least throw an error if it creates an unusable file.

**Comment by AoEiuV020** [comment]
The reason has been found, and sure enough, it was damaged during backup. 
Although the gzip command is compatible with this damage and okio is not, but if the file damage problem is repaired during the backup process, there is no need to find a way to be compatible with the damaged file during restore file,
