### ISSUE TITLE
Don't use semibold for list view manga title

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6425]
### Describe your suggested feature

title

### Other details

Much like Google Contacts. Semibold in list view looks seriously horrible. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MohitMandalia** [comment]
so by manga title list view you mean the history tab correct?

**Comment by vengiare** [comment]
Library, Source view.
