### ISSUE TITLE
Manga chapter list should shrank.

### ISSUE THREAD

**Issue by MohitMandalia** [tachiyomiorg/tachiyomi#6427]
### Describe your suggested feature

There should a a way to navigate to relevant page(Implement less scrolling).
Currently if a manga has 900+ chapters , need to scroll  too long for it current filter do not help in this.

there should be a categorization of pages , something like this would help `Pages 1-10`.
let me know if this is something to consider.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can just use the scrollbar.
