### ISSUE TITLE
Tachiyomi integration with Remarkable 2 

### ISSUE THREAD

**Issue by diskxo** [tachiyomiorg/tachiyomi#6434]
### Describe your suggested feature

would it be possible to create an integration with the Remarkable 2 e-reader by synchronizing the volumes read with Tachiyomi and then with anilist and automating the movement of volumes between one device and another?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Existing issue for sync: #912

Device (Remarkable 2) isn't really relevant.
