### ISSUE TITLE
Appbar and content below side navbar/One UI pinned taskbar

### ISSUE THREAD

**Issue by Iliansic** [tachiyomiorg/tachiyomi#6436]
### Steps to reproduce

In OneUI 3.1 for tablets Samsung added a nifty function of pinning edge panel with quick-access apps.

Tachiyomi UI though works with it non-consistently. While chapter list correctly scales to limitation of display area, top UI simply cuts off buttons.

The issue persists across all views (Library, Updates, History, Browse): top ui cuts off buttons, everything under it correctly scales.

![Screenshot_20220104-201519_Tachiyomi](https://user-images.githubusercontent.com/15694943/148098154-5bdb610d-7ee3-4904-826f-58d3ec951534.jpg)
![Screenshot_20220104-201532_Tachiyomi](https://user-images.githubusercontent.com/15694943/148098159-b0086ad2-f785-46f7-a594-a903a379f930.jpg)

### Expected behavior

Top ui expected to scale the same way as all other elements

### Actual behavior

Buttons get cut off.

### Tachiyomi version

0.12.3-4067

### Android version

Android 11

### Device

Galaxy Tab S5E

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does this happen in other apps? I don't think we're doing anything out of the norm for the top appbar.

**Comment by Iliansic** [comment]
No, I haven't stumbled yet on any other app, with the same problem.

I did notice, that the edge panel changes DPI values though
Without panel:
![Screenshot_20220105-073017_Settings](https://user-images.githubusercontent.com/15694943/148161032-0eb1d01c-57b0-4f65-91ad-1a007b338a00.jpg)

With panel:
![Screenshot_20220105-073109_Settings](https://user-images.githubusercontent.com/15694943/148161030-40b208a0-13f5-4074-bfa3-5f1df32c6684.jpg)

**Comment by arkon** [comment]
For reference/note to self since it was so hard to find the option... https://websetnet.net/one-ui-update-brings-new-multitasking-features-to-the-galaxy-tab-s7/

**Comment by arkon** [comment]
Seems like the appbar and content need to properly handle the navigationBar insets, but it's kind of a mess since each controller does it separately for its own content right now.
