### ISSUE TITLE
Loading chapter don't work

### ISSUE THREAD

**Issue by Celes1989** [tachiyomiorg/tachiyomi#6438]
### Steps to reproduce

Just load chapters.

It search for 1 second and it stops.

### Expected behavior

Updated new chapters

### Actual behavior

It happens since the preview updated of the 18 december and next.

It worked fine before and it still works with the stable version.

### Tachiyomi version

preniew r4067

### Android version

Android 10

### Device

Huawei P30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
99.99% this is an extension issue.  Search that repo make sure the extension you are using already doesn't have an open issue.

**Comment by Celes1989** [comment]
I can update every manga 1 by 1 from the manga but I can't update all from the librairy

**Comment by arkon** [comment]
Default library update restrictions were changed in 818fe50f7772e42bff710b471bb0f687ab58ee10

**Comment by Celes1989** [comment]
Thanks.
It's certainly what create my problem (this change is exactly when I first have this problem).

So, I can update chapter in every manga I have in my librairy but I can't update all my librairy in one step.

So, how can I fix that ?

For the moment, it works fine with the stable version but I'm scared that it will be broken for me in the next updated of the stable version

**Comment by Celes1989** [comment]
I finally found the problem.

I searched and I found some settings in the app about the update restriction and I change some of them.

Now, it works fine.

Thanks for your help ^_^
