### ISSUE TITLE
Restoring a backup(ID1ID2)

### ISSUE THREAD

**Issue by Natonuki** [tachiyomiorg/tachiyomi#6440]
### Steps to reproduce

1. Launching tachiyomi
2. Going to the setting and selecting my backup file

### Expected behavior

What should've happen was I get the usual message of the options of needed things before doing so

### Actual behavior

But this happened instead, I get this message "Invalid backup file ID1ID2: actual 0x00000000 != expected 0x00001f8b".

### Tachiyomi version

0.10.12(tried also with the newer ver 0.12.3)

### Android version

Android 5

### Device

SM-G530W

### Other details

 I don't what to do, if I can't repair the gz, is there atleast a way to look at the written contents of the gz file? Thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Natonuki** [comment]
P.S- I have another phone which can handle the newer version.

**Comment by arkon** [comment]
Would probably help to share the file.

**Comment by Natonuki** [comment]
[tachiyomi_2021-12-31_09-52.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/7813750/tachiyomi_2021-12-31_09-52.proto.gz)
here forgot to share this.

**Comment by loocool2** [comment]
We no longer support Android 5
