### ISSUE TITLE
Download remaining in queue if you finish a chapter just as the cbz file is being created.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6442]
### Steps to reproduce

1. Download two - three chapters .
2. Read another chapter while this one finishes downloading and end the chapter you are reading when the chapter which is downloading starts getting zipped.

### Expected behavior

The one which was downloading gets zipped and gets removed from the download queue.
And the next one download starts downloading .

### Actual behavior

The one which was in the download queue gets zipped but doesn't get removed from the download queue and the next one starts downloading even when the cbz file is created.
Example image :
![IMG_20220105_130009](https://user-images.githubusercontent.com/63903377/148178592-a99766a5-9ac2-4ccf-9d05-d4806b2933c9.jpg)
The created cbz file : 
![IMG_20220105_131000](https://user-images.githubusercontent.com/63903377/148178928-32a00cd1-ce30-42e3-8c8f-22472a2808dd.jpg)
Now if you reorder the downloads , the download whose CBZ file was created will start downloading again :
![IMG_20220105_131034](https://user-images.githubusercontent.com/63903377/148179037-7dca86a9-1fcc-4184-bc54-5dd26d7396ff.jpg)
Resulting in duplicate downloads :
![IMG_20220105_131319](https://user-images.githubusercontent.com/63903377/148179250-df9d622f-8e8b-43ed-b06f-e9b3c1969be3.jpg)

[Edit] Also idk if this is related or not but whenever you read a chapter the downloads will reset , like they will check for the pages again.

### Tachiyomi version

0.12.3 - r4067

### Android version

Android 11

### Device

Redmi note 9 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #7492
