### ISSUE TITLE
Metadata update fix

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi#6444]
### Steps to reproduce

1- Go to the library settings
 2- Activate the option to update metadata
![Screenshot_20220106-135530](https://user-images.githubusercontent.com/90999286/148373363-f35977c6-be7e-4334-8df6-6a6fe92a4d70.png)

### Expected behavior

The library should happen fast

### Actual behavior

Delayed updating the library

### Tachiyomi version

0.12.3

### Android version

Android 10

### Device

LG STYLO 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It effectively means you're doubling the amount of requests, of course it's going to be slower.
