### ISSUE TITLE
Please add 👉mangareader.to👈 extension

### ISSUE THREAD

**Issue by suraj2325** [tachiyomiorg/tachiyomi#6448]
### Describe your suggested feature

mangareader.to is a awesome manga website. So its a must for Tachiyomi. Please add it ASAP🙏
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the extensions repository.

also its already been [requested.](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9112)

**Comment by suraj2325** [comment]
Ok then Dev 🙂Sent from my Galaxy
-------- Original message --------From: Seishirou101 ***@***.***> Date: 1/8/22  1:36 PM  (GMT+05:30) To: tachiyomiorg/tachiyomi ***@***.***> Cc: suraj2325 ***@***.***>, Author ***@***.***> Subject: Re: [tachiyomiorg/tachiyomi] Please add 👉mangareader.to👈 extension (Issue #6448) 

If this is an issue with an extension, I should be opening an issue in the extensions repository.

also its already been requested.
