### ISSUE TITLE
Error message, can't open any manga

### ISSUE THREAD

**Issue by flubbityfloob** [tachiyomiorg/tachiyomi#6449]
### Steps to reproduce

Open manga

### Expected behavior

Should open manga 

### Actual behavior

Shows error message 
![Screenshot_20220108-074737](https://user-images.githubusercontent.com/97352543/148650884-a3ea415a-433d-4c07-a60c-fb9c761a33f5.jpg)

### Tachiyomi version

12.3

### Android version

11

### Device

Oneplus 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Report an issue in the extensions repo if this is happening with an updated version of the extension.
