### ISSUE TITLE
Option to delete tmp and duplicate chapters.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6450]
### Describe your suggested feature

Something like a cleanup tool would be nice which could delete tmp chapter folder and duplicate chapters which could be created due to various reasons such as this bug #6442 . 

### Other details

These tmp chapter folders and duplicate chapters eventually start accumulating and start taking up space with no easy way to delete them from the app and only way to do so is to locate them individually and delete using a file manager.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Handling tmp downloads better: #1501

Pruning orphaned downloads: #1767
