### ISSUE TITLE
Clear/Limit update count

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#6451]
### Describe your suggested feature

Either an option in Settings to reset the update count badge in the bottom bar, or limit it to a certain category. I have like, 5 categories that get updates, but I'm only actually reading 1 of it at the moment. But even so my Update count is at 570.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
I think it should just show from the categories you specified in global update.

**Comment by hyoretsu** [comment]
That definitely works too and should be easier to do (though it may not be a preferred solution, since it is still an upgrade count and they'd be blocking people who want the full count but not auto-update the entire library)

**Comment by arkon** [comment]
Update count is just new updates from recent updates and is cleared when opening the screen.
