### ISSUE TITLE
reader text error not visible

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6453]
### Steps to reproduce

1. open an error chapter

### Expected behavior

reader text error shud be visible just like in [preview](https://user-images.githubusercontent.com/12537387/148583743-9abc7f79-05af-4877-8c52-8b87ea16376a.png)

### Actual behavior

![Screenshot_2022-01-09-12-25-51-440_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/84634607/148669575-bd3bfc82-3f6c-4c47-b76d-29f15d0ac02e.jpg)

### Tachiyomi version

r4083

### Android version

Android 11

### Device

Redmi Note 10

### Other details

its not visible even if you set any reader background.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pree-T** [comment]
May I work on this?

**Comment by FourTOne5** [comment]
> May I work on this?

you are free to work on any issue that is open
