### ISSUE TITLE
back button wrong tint in track

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6454]
### Steps to reproduce

1. add tracking on a manga

### Expected behavior

back button shud be visible in light mode

### Actual behavior

![IMG_20220109_131029](https://user-images.githubusercontent.com/84634607/148670319-35e58824-4861-46c3-8ced-5e7912f9fea9.jpg)

### Tachiyomi version

r4083

### Android version

Android 11

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed by #6456
