### ISSUE TITLE
Category sorting options

### ISSUE THREAD

**Issue by Nagravitts** [tachiyomiorg/tachiyomi#6459]
### Describe your suggested feature

The way this would work is just as it states, it would auto sort the categories. Just as how dynamic sorting works in Tachij2k, there would be a button in the settings menu that says either auto sort categories or just sort categories. Once you amass enough categories and they get away from you it takes quite a while to sort them.

### Other details

Preferably it would be done Alphabetically, even just sorting by the first letter or two would work. It would be easier to sort yourself from there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Hipp0x** [comment]
I'll try to work on this !
