### ISSUE TITLE
Additions to backup

### ISSUE THREAD

**Issue by dragonGod97677** [tachiyomiorg/tachiyomi#6460]
### Describe your suggested feature

Add option to backup app user modified settings
Add option to backup entire app data, including downloaded manga to external storage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Settings: #1857

Downloads makes no sense, just copy your folder.
