### ISSUE TITLE
App crashing while installing extensions

### ISSUE THREAD

**Issue by ninja1207** [tachiyomiorg/tachiyomi#6461]
### Steps to reproduce

1. Install an extension via app
2. Wait for a few seconds and the following dialog box appears 
3. 
![Screenshot_20220111-215321](https://user-images.githubusercontent.com/77534385/148985238-e88288ec-2a01-4177-a5e2-790608421ef5.png)

### Expected behavior

The extension should install perfectly all while no app crashing

### Actual behavior

After few seconds of tapping the install button the app not responding dialog box appears

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Xiaomi Poco F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please try the other installer options in advanced settings, or another ROM.

It may be worth reporting this as a bug to your ROM developer.
