### ISSUE TITLE
The "Updates" tab not showing new update of chapter.

### ISSUE THREAD

**Issue by CmmmmmmLau** [tachiyomiorg/tachiyomi#6466]
### Steps to reproduce

Update chapters in the Update tab.

### Expected behavior

Show new chapeters in the tab.

### Actual behavior

![Screenshot_20220113-181903](https://user-images.githubusercontent.com/42691172/149388112-6b430bd1-465e-4786-9e76-fc80e5fc3ca8.png)
![Screenshot_20220113-181918](https://user-images.githubusercontent.com/42691172/149388113-23c61b39-c96e-43f6-94b2-614b5ecae072.png)
Even though the notification is works properly. But the Updates tab still empty.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Device

Onyx Boox Leaf

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Probably because that source doesn't return dates, but should be fixed with #6358. Wait for next stable update
