### ISSUE TITLE
Nothing found

### ISSUE THREAD

**Issue by MaMMM7** [tachiyomiorg/tachiyomi#6467]
### Steps to reproduce

Update the library

### Expected behavior

Find the new chapter when I update the library.

### Actual behavior

I have 3 manga sources especially:

.Mangadex EN
.Mangakakalot EN
.Mangaworld IT

When I update the library the app doesn't find anything, but instead on the corrispective sites the new chapters are online.

### Crash logs

None

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung Galaxy S10 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by krae93** [comment]
I am having the same issue 😕
