### ISSUE TITLE
Easier local magna creation 

### ISSUE THREAD

**Issue by Triplesweet** [tachiyomiorg/tachiyomi#6468]
### Describe your suggested feature

My idea was some kind of automatic process for making local manga from an existing manga.

For example you open any manga and you choose "make a local manga"

It downloads all the available chapters, and making the folders in the local folder  with the name of the manga

exports the about manga section and other information available, like the name of each chapter if possible and the cover for that and name of the author  and the tags

I know I can just copy the downloaded manga and paste it in local but at least exporting the meta data can help a lot, since it's a text file and we have to do it by hand  and probably in another platform since you have to download a 3th party app to edit txt files on android

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
similar to #2289, as for meta data, you can use the one on the [website ](https://tachi-local.netlify.app/?utm_source=tachi-website&utm_medium=referral&utm_campaign=tachi-website)that someone made to make a file for you

**Comment by Triplesweet** [comment]
Can I have the link for the website? And thanks for the information

**Comment by Triplesweet** [comment]
Thanks a lot for the information then I close this issue
