### ISSUE TITLE
Updated failed can you fix please? :(

### ISSUE THREAD

**Issue by Jierachi** [tachiyomiorg/tachiyomi#6470]
### Describe your suggested feature

Updated failed can you fix please? :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Please use the Correct template ("Issue Report")
or ask at the [Discord](https://discord.gg/tachiyomi) for assistance
