### ISSUE TITLE
Can't install extensions in Android 12

### ISSUE THREAD

**Issue by enjoe842** [tachiyomiorg/tachiyomi#6473]
### Steps to reproduce

1. Install an extensionss via app.
2. Wait for a few seconds but notification to install apk does not come out.
3. Already use private DNS or VPN but didn't work to.

### Expected behavior

it should be after clicking install and downloading the apk is complete, a notification appears to install the apk

### Actual behavior

after clicking install it just says retry not installing apk

### Crash logs

--------- beginning of main
01-16 12:41:27.817 30606 30606 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
01-16 12:41:28.389 30606 30650 E SQLiteLog: (284) automatic index on C(manga_id)
01-16 12:41:28.389 30606 30650 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-16 12:51:17.577  1404  1404 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
01-16 12:51:18.447  1404  1488 E SQLiteLog: (284) automatic index on C(manga_id)
01-16 12:51:18.448  1404  1488 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 12 (SDK 31)
Android build ID: SQ1A.220105.002
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X00T_2
Device model: ASUS_X00TD
Device product name: voltage_X00T

### Tachiyomi version

0.12.3

### Android version

Android 12

### Device

ASUS Zenfone Max Pro M1 

### Other details

Using custom rom - VoltageOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please try the other installer options in advanced settings.

**Comment by enjoe842** [comment]
Problem solved, thats rom issue not from the app. Thanks you.
