### ISSUE TITLE
My Reading Manga: No Pages Found

### ISSUE THREAD

**Issue by D1o2c3** [tachiyomiorg/tachiyomi#6475]
### Steps to reproduce

Open in web view
Performed captcha successfully
Individually, open in web view and confirmed the pages are present.

### Expected behavior

Pages should load for BENNY'S manga "Animal Play (JP)".

### Actual behavior

No Pages found for BENNY'S manga "animal play (JP)".

### Tachiyomi version

O.12.3 

### Android version

Android 11

### Device

Real Me 25s

### Other details

Not just for BENNY'S works on MRM but also some older works on posted MRM has "no pages found".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
