### ISSUE TITLE
Change url 

### ISSUE THREAD

**Issue by Gui02789** [tachiyomiorg/tachiyomi#6478]
### Steps to reproduce

Change url from hunter scan 
Actual from App is https://huntersscan.tk/
Now the site is https://huntersscan.xyz/

### Expected behavior

I don t no

### Actual behavior

I dont no

### Tachiyomi version

0.12.3

### Android version

Android 9

### Device

J7pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please open in the right repository.
