### ISSUE TITLE
keyboard Vbug when searchbar is filled 

### ISSUE THREAD

**Issue by putzmarcos** [tachiyomiorg/tachiyomi#6480]
### Steps to reproduce

1. search for a term/tag in your library 
2. open one title 
3. return to library page

### Expected behavior

no visual bug 

### Actual behavior

https://user-images.githubusercontent.com/76596575/149682184-cabecd25-bbda-4a53-a214-58bae2dd847d.mp4

### Tachiyomi version

r4090 

### Android version

A11

### Device

Galaxy A80

### Other details

happens with  0.12.3 too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Astraldisaster0619** [comment]
I also have the same issue when i updated my phone to android 12. It happned with the latest versions of tachiyomi and tachij2k. Here are videos for reference

https://user-images.githubusercontent.com/91368564/152600347-5cc942e0-3d89-4a5b-8a1a-00602445a4d4.mp4

**Comment by Astraldisaster0619** [comment]
This is also happened in  tachij2k latest version v1.4.4

**Comment by zer0p1us** [comment]
Encountering the same bug in 1.13.4 on android 11 (OneUI), it also occurs if you were to search inside extensions

**Comment by zbue** [comment]
Restoring query has something to do with this. 
https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt#L91

**Comment by arkon** [comment]
Seems to be fixed in preview, although #8157 is now relevant.
