### ISSUE TITLE
Change Location of Page

### ISSUE THREAD

**Issue by aravindchow** [tachiyomiorg/tachiyomi#6485]
### Describe your suggested feature

When viewing a manga page, can the page be snapped to the top or bottom of the screen (rather than be in the middle with black on the top and bottom)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please experiment with the existing options first.
