### ISSUE TITLE
Library updates failed

### ISSUE THREAD

**Issue by Uchuuj1n** [tachiyomiorg/tachiyomi#6489]
### Steps to reproduce

Updating Library

### Expected behavior

Complete and update library

### Actual behavior

Updates failed

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Oppo reno 4 pro

### Other details

! No chapters found
  # Manganato (EN)
    - A Bad Person
    - Assassin No Kyuujitsu
    - Cheat Skill "shisha Sosei" Ga Kakusei Shite Inishieno Maougun Wo Fukkatsu Sasete Shimaimashita ~Dare Mo Shinasenai Saikyou Hiiro~
    - Deathbound Duke's Daughter And Seven Noblemen
    - Dr. Choi Tae-Soo
    - Hajimete No Suwa-San
    - Kubo-San Doesn't Leave Me Be (A Mob)
    - Legend: The Beginning
    - Mezase Gouka Kyakusen!!
    - Poison Dragon: The Legend Of An Asura
    - Ponkotsu-Chan Kenshouchuu
    - Real Man
    - Return Of The 8Th Class Magician
    - Tanaka ~Nenrei Equal Kanojo Inaireki No Mahoutsukai~
    - The Butterfly Girl
    - The Hunters Guild: Red Hood
    - The Irregular Of The Royal Academy Of Magic ~The Strongest Sorcerer From The Slums Is Unrivaled In The School Of Royals ~
    - The Magic Tower Librarian
    - The Player That Can’T Level Up
    - The Struggle Of Being Reincarnated As The Marquess's Daughter: I'll Deal With What’S Coming To Me!
    - Unreachable Girl
    - Villain To Kill
    - Wizard's Martial World
  # MangaDex (EN)
    - When I Yelled, "I Want To Play with Some Boobs!", I Ended Up Going Out with my Sister's Friend.
! Source URL has changed
  # Mangakakalot (EN)
    - A Kind World
    - Class Maid
    - Honzuki No Gekokujou
    - To a New Life
! HTTP error 502
  # MangaFast (EN)
    - A Story About A Grampa And Granma Returned Back To Their Youth.
    - Hagure Seirei Ino Shinsatsu Kiroku ~ Seijo Kishi-Dan To Iyashi No Kamiwaza ~
    - I Am The Sorcerer King
    - Imokami-Sama
    - Jimina Ken Sei Wa Sore Demo Saikyoudesu
    - Jitsu Wa Ore, Saikyou Deshita?
    - Karate Baka In Different World
    - Kemono Jihen
    - Kujibiki Tokushou Musou Harem-Ken
    - Manuke Na Fps Player Ga Isekai E Ochita Baai
    - Maou Ni Natta Node, Dungeon Tsukutte Jingai Musume To Honobono Suru
    - Mezametara Saikyou Soubi To Uchuusen-Mochi Datta No De, Ikkodate Mezashite Youhei Toshite Jiyuu Ni Ikitai
    - Moto Saikyou No Kenshi Wa, Isekai Mahou Ni Akogareru
    - My Lv999 Love For Yamada-Kun
    - Requiem Of The Shogun
    - Salaryman Ga Isekai Ni Ittara Shitennou Ni Natta Hanashi
    - Seichou Cheat De Nandemo Dekiru You Ni Natta Ga, Mushoku Dake Wa Yamerarenai You Desu
    - Senpai Ga Urusai Kouhai No Hanashi
    - Shed! Ryugasaki-San
    - The World Is Full Of Monsters Now, Therefor I Want To Live As I Wish
    - The World's Best Assassin, Reincarnated In A Different World As An Aristocrat
    - Tomb Raider King
! Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.data()' on a null object reference
  # MangaLife (EN)
    - I Summoned the Devil to Grant Me a Wish, but I Married Her Instead Since She Was Adorable
! Source not found
  # 8918520211459944430
    - Overgeared
    - The Strongest Florist

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> I have tried the [troubreshooting](https://tachiyomi.org/help/guides/troubleshooting/) guide.

Please do actually try the troubleshooting guide being linked...
If you need more help, ask at the [Discord](https://discord.gg/tachiyomi)
