### ISSUE TITLE
No chapters found

### ISSUE THREAD

**Issue by Pandaxxz** [tachiyomiorg/tachiyomi#6490]
### Steps to reproduce

Example
Opens manga from mangaowl
No pages found is written although webview opens naturally

### Expected behavior

Manga chapter should load and open

### Actual behavior

No pages found Instead appears

### Tachiyomi version

0.12.3

### Android version

11

### Device

Galaxy A51

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
