### ISSUE TITLE
Version 0.12.3 (latest stable) can't load local manga covers, version 0.10.8 can.

### ISSUE THREAD

**Issue by Atoli** [tachiyomiorg/tachiyomi#6493]
### Steps to reproduce

1. Add manga to your local folder.
2. Go to local manga library in tachiyomi 0.12.3
3. Manga have no covers.
4. Try to add a cover (make one of the manga pages the cover)
5. Nothing happens, cover is blank. 
6. Go to settings>advanced and choose "refresh library manga covers"
7. Nothing happens, local manga covers remain blank.

### Expected behavior

The local manga should have covers.

### Actual behavior

None had covers. 

[I reinstalled tachiyomi latest version and now some randomly have covers while others do not. All local manga have jpg images, they are not different formats.](https://i.imgur.com/feJKimb.png)

So there is something bugged here.

### Crash logs

No crashing.

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1

### Device

HTC Desire 12

### Other details

I tried tachiyomi 0.10.8 and [all my local manga had covers showing perfectly.](https://i.imgur.com/i9UnrGA.png) which leads me to believe there is something wrong with newest tachiyomi versions.

To reinforce this theory, [the latest tachiyomi version library update bugs, since the count goes above the max which is 194 here.](https://i.imgur.com/zrMZGVY.png)

Tried to reset the covers on settings>advanced, reinstall tachiyomi, clear cache and all app data on android app settings... but nothing worked, just downgrade from 0.12.3 to 0.10.8 fixes the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
All previously reported and fixed issues. You can either verify in the preview builds or wait for the next stable release.
