### ISSUE TITLE
Global and extension search input accepts formatted text

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi#6495]
### Steps to reproduce

1. Open the Browse section.
2. Paste a formatted text into the global or extension search input.

### Expected behavior

It should not accept a formatted text and the simple value should appear instead.

### Actual behavior

The formatted text pastes just fine.

<img width="300" src="https://user-images.githubusercontent.com/14254807/150809947-79275c6f-6850-42f7-9962-d27cc7f59343.jpg">

### Tachiyomi version

r4103

### Android version

Android 12

### Device

Samsung Galaxy S20+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by afreakyelf** [comment]
Hi Can I work on this
Can you assign it to me.

**Comment by loocool2** [comment]
@afreakyelf Again, you do **not** need any permission to work on a issue. We usually don't assign issues to people either.

**Comment by afreakyelf** [comment]
Gotcha!

**Comment by alessandrojean** [comment]
Can be reopened since the PR didn't fixed the issue. Using r4118 and the issue still happens in extension search. Global search do removes the font weight (but not the size), but sometimes it doesn't even let the text to be pasted.

![SmartSelect_20220129-194812_Tachiyomi](https://user-images.githubusercontent.com/14254807/151680116-80855bf5-3ebf-4879-a3e7-a4505a84bf8e.jpg)

**Comment by arkon** [comment]
Can you try again in r4121?

**Comment by ghostbear** [comment]
Still happening in r4121 
![Screenshot_20220130-170531.jpg](https://user-images.githubusercontent.com/6576096/151707363-56407708-4d80-47a1-b38f-f5da47ed56b1.jpg)

**Comment by alessandrojean** [comment]
I think it's maybe better to use that StackOverflow suggestion of replacing the Paste floating button with the Paste without formatting.

**Comment by alessandrojean** [comment]
Just tried with r4121. It's fixed in the global search, but not in the extension search field.

**Comment by vengiare** [comment]
PR actually (mostly) works now. Only thing not yet stripped is text-align.

But it's only on Library, Global search, and Source search. It doesn't work on Extensions + History (like others said), and also Settings search.

**Comment by alessandrojean** [comment]
Seems to be fixed already by the Compose rewrite.
