### ISSUE TITLE
Downloaded non favourite/ not added to library 

### ISSUE THREAD

**Issue by DetectiveMinh** [tachiyomiorg/tachiyomi#6496]
### Describe your suggested feature

It would be nice to search for downloaded manga that are not in the library due to accidental removal or forgetfullness. 
Otherwise one has to check every downloaded manga in the download folder with the list in tachiyomi and that's quite inconvenient 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#1767
