### ISSUE TITLE
mdYou

### ISSUE THREAD

**Issue by exkpwn** [tachiyomiorg/tachiyomi#6497]
### Describe your suggested feature

1. Use the navbar height of google photos/clocks/phone apps, not the cramped navbar height of google maps(like the height used in weekly previews)
2. using 4 tabs and moving the "more" tab into title bar?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. Maybe in the future. It's meant to make the transition from MD2 less jarring.
2. Probably wouldn't work without overflow or sidebars, neither of which are desired. This may change in the future if we adopt a search bar that'd let us remove the explicit search items.
