### ISSUE TITLE
Downloaded Images Appearing in Gallery

### ISSUE THREAD

**Issue by Hemi177** [tachiyomiorg/tachiyomi#6499]
### Steps to reproduce

1.Download any manga chapter
2. Open Gallery app
3. Images of downloaded chapter appear in gallery app

### Expected behavior

The downloaded images should not appear in the gallery app.

### Actual behavior

Downloaded chapter images appear in the gallery app.

### Tachiyomi version

0.12.3

### Android version

Android version 12

### Device

Samsung Galaxy S20+

### Other details

I recently updated the app (I believe I was on version 0.9 something). I have tachiyomi save its downloads to my phone's SD card. I didn't notice the images appearing in the gallery at first after the update, but I don't know if that just a case of me misremembering or not, but it's been a few days and the images are definitely appearing in my gallery app. I did not have this issue while I was still using the previous version. As far as I can tell there is a .nomedia file in the Tachiyomi downloads folder, but I don't know much about hiding stuff with nomedia files.
![Tachiyomi](https://user-images.githubusercontent.com/36756691/150885364-474c9378-30cb-46d3-84df-8a93b03ea188.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
The new Samsung OneUI4 update breaks SD cards somehow and so the gallery app starts ignoring the existence of the .nomedia file. Usually it fixes itself after a couple hours, we have no idea why.

**Comment by arkon** [comment]
If the .nomedia files are created and the stuff eventually disappears from the Gallery app, then it's either an issue with the Android OS MediaStore or the specific gallery app (it might try to do its own indexing than later consolidates with newer MediaStore data?).

Either way, out of scope/our control. 

You could see if it happens with other gallery apps and/or storage options.

**Comment by arkon** [comment]
Closing since this is out of our control, unless the `.nomedia` files aren't being created for some reason.
