### ISSUE TITLE
Per-category for badges

### ISSUE THREAD

**Issue by putzmarcos** [tachiyomiorg/tachiyomi#6500]
### Describe your suggested feature

This will be an increment for *per category settings for sort and display* that doesn't work for badges currently 

### Other details

as chapter list, the option for *set as default* would be cool.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
@whtann feel free, we don't assign things generally
