### ISSUE TITLE
I hope you make the application support the numbered address of the sites

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi#6502]
### Describe your suggested feature

 Like this
![Screenshot_20220125-050215](https://user-images.githubusercontent.com/90999286/150897835-8682c90e-4fc5-4e93-a128-6e5f49701267.png)
![Screenshot_20220125-050236](https://user-images.githubusercontent.com/90999286/150897987-641d98be-b83c-4bee-838e-2e4b1fed5688.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
