### ISSUE TITLE
Covers not showing

### ISSUE THREAD

**Issue by boreslayer** [tachiyomiorg/tachiyomi#6508]
### Steps to reproduce

1. Transfer manga folder to Tachiyomi folder in Phone directory
2. Open Up [Browse]->[Local Source]->[Latest]
3. Select folder to transfer to Tachiyomi library
4. Done

### Expected behavior

Transferred folder will appear with chapters in sub-folders (manually sorted, transferred from PC) and cover properly displayed in the library

### Actual behavior

Transferred folder appeared with chapters in sub-folders (manually sorted, transferred from PC) BUT cover not displayed in the library.  

### Crash logs

No crashes

### Tachiyomi version

0.12.3

### Android version

Android 10 One UI 2.5

### Device

Galaxy Note 9

### Other details

Manually setting covers via [Set as cover] option by long pressing did not work.  (I did not have to do/try this option previously.  The covers were loaded automatically)

It was working previously the last time I transferred folders to the library back in Dec 2021.  The app was on 0.12.3 back then and 0.12.3 now.  Not sure why it is not working now.  Even creating a cover.jpg manually did not work.  Cover pages are still not shown.  Just a blank.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment]
knowed bug, already fixed in preview
for now, do this: 
1. Make sure you can read chapters you added. If not, follow the guide linked above.

2. Remove manga from Library.

3. Go to More > Settings > Advanced and tap Clear database. This only affects manga that aren't in your Library.

4. Add manga back to Library, the cover should be fixed now.

**Comment by boreslayer** [comment]
Noted.  This works.  Thanks.
