### ISSUE TITLE
Double tap Browse to go to last used source

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#6515]
### Describe your suggested feature

Double click in browse will open last used extension (in latest), an easy way to save time if you have a main website.

### Other details

I also thought in use pinned extensions (this will require a hierarchy between they)/a  new option in browse settings

^ more work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Opting for #3925 instead
