### ISSUE TITLE
Way to filter out the same chapters

### ISSUE THREAD

**Issue by therealsbeve** [tachiyomiorg/tachiyomi#6519]
### Describe your suggested feature

On certain sources in Tachiyomi, we get the same chapter multiple times from different scanlations and it is bothersome at times. Would it be possible to implement a method to filter out these chapters? Maybe by only allowing the chapter numbers to be shown once forcing the other scanlations of the same chapter to not show up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cecoates** [comment]
Maybe there could be a toggle to only show the most recent version of a chapter, to accomodate when a corrected chapter is uploaded?

Or allow filtering out a specific scanlation group or uploader, if you have a preference.

**Comment by Seishirou101** [comment]
since you talked about scanlator in particular, #969
