### ISSUE TITLE
Show number of all unique mangas in library

### ISSUE THREAD

**Issue by ChocoJack** [tachiyomiorg/tachiyomi#6522]
### Describe your suggested feature

When you have the tab settings of "Show category tabs" and "Show number of items" both on, it should show number of items for the library at the top right after "Library", like it does for the categories. It should also change the number with the filter options, like the category numbers already do.

### Other details

the reason i'm suggesting this is i sometimes want to know my total manga but because you can put manga in mulitple categories at once, you sometimes can't simply add the amount of manga in each category seperatly. 
Example:
![Screenshot_20220130-062903_Tachiyomi](https://user-images.githubusercontent.com/93693473/151704898-c7cc0551-9735-485f-9fc5-daaae14f77cc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment]
"Would look better if the number was a more darkened color and maybe a variant of the font
Rather than in parenthesis and same color" [Soitora](https://discord.com/channels/349436576037732353/694092459839455243/937363938008498217)

**Comment by ComBeat** [comment]
Hey, I have been working on this issue. So far I have implemented the requested feature.

> Would look better if the number was a more darkened color and maybe a variant of the font
Rather than in parenthesis and same color

I still need to implement this.

**Comment by alessandrojean** [comment]
This is how Telegram does it with their chat folders:

![IMG_20220220_212221_843](https://user-images.githubusercontent.com/14254807/154871196-2327d0dc-c66f-4210-ae1b-a9b0946e8185.jpg)

They use the counter for unread messages. I think it will be a little bad for having them in all tabs in Tachiyomi, but it's a good UI example anyway.

**Comment by ComBeat** [comment]
Having the numbers for all categories and the library can look crowded.
As mentioned [here](https://github.com/tachiyomiorg/tachiyomi/pull/6679#issuecomment-1047411225), I will implement an option that allows the user to specifically disable the library number.
How about showing only the number of the current category?
But that should be dealt with in a separate issue.
