### ISSUE TITLE
Rework toasts

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#6530]
### Describe your suggested feature

This refers just for "copy toasts", in these situations show a preview of the text you copied is totally unnecessary. Instead of "Copied to clipboard: One piece" let's use "Title copied to clip board", the same for all  variants (author, description, extension id, ...)

### Other details

Afaik J2k already do this > maybe help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not sure why having _more_ info is unwanted for those toasts?

**Comment by SrW0nka** [comment]
> I'm not sure why having _more_ info is unwanted for those toasts?

in 90% of the cases the information's are so long that are left with only 3 words + ... 

specify what information was copied to clipboard is enough, since to be able to copy you necessary be seeing them on the screen

**Comment by arkon** [comment]
It's simpler this way since there's less strings to localize.
