### ISSUE TITLE
Completion bar does not correspond with pages downloaded

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#6532]
### Steps to reproduce

(Happens rarely)
1. Download a manga with too many pages

### Expected behavior

The completion bar should correspond with pages downloaded in that manga

### Actual behavior

The bar stops at 99% with very low amount of pages downloaded

### Crash logs

--------- beginning of main
App version: 0.13.0 (standard, a6ac2fb, 73, 2022-01-31T20:51Z)
Android version: 7.0 (SDK 24)
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido

### Tachiyomi version

v0.13.0

### Android version

Android 7 

### Device

Redmi Note 4

### Other details

![image](https://user-images.githubusercontent.com/92982808/151915332-dfbe7003-313e-452d-967c-ff0c0b15d9a6.png)
Here's a screenshot of what I am saying. As I said it happens rarely.
I have a assumption that it happens due to slow internet or prolonged downloads and in this case I have started downloading this manga at nearly 1AM at night.
Another assumption is that it can also happen because of version change as at night I was using v0.12.3 and at morning I updated to new version v0.13.0

**EDIT:-** Things got more messed up
![image](https://user-images.githubusercontent.com/92982808/151931352-62a04462-3a1c-4cd8-acb8-38efb05bc37f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #7492
