### ISSUE TITLE
Indicator in chapter list that marks your last read chapter from a tracker

### ISSUE THREAD

**Issue by R08Y** [tachiyomiorg/tachiyomi#6534]
### Describe your suggested feature

Essentially, a separate "read" indicator that appears on the last chapter read from whatever tracker you linked in the Manga's page.
If there are multiple trackers used, differently colored indicator could appear on whatever chapter you've left at there.

Adding this feature would make reading across different devices a bit easier, especially with the help of something like [MAL-Sync](https://github.com/MALSync/MALSync).

Another similar suggestion that ties into this one would be some "Resume from <tracker>" buttons, above the normal resume button (or perhaps accessing them by long tapping it? Maybe even have a setting for which one you want to replace the normal resume button), which would just instantaneously go to the next chapter from the one you've marked as read in the respective tracker. Consequently, a button that "marks as read" any chapters before the one marked as read on your trackers would also be highly useful.

### Other details

![image](https://user-images.githubusercontent.com/22418648/151990412-51af54fa-a224-4772-a944-28e5703bed1b.png)
Inspired by [MAL-Sync](https://github.com/MALSync/MALSync)'s read indicator.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6731 is more ideal
