### ISSUE TITLE
category exception override

### ISSUE THREAD

**Issue by ScromblesSmash** [tachiyomiorg/tachiyomi#6538]
### Steps to reproduce

![Screenshot_20220201-141021_Tachiyomi](https://user-images.githubusercontent.com/98847676/152043606-76871584-09f4-4cfc-ac08-49aa89583c5e.jpg)

### Expected behavior

Library update restrictions and category exceptions working together 

### Actual behavior

Category exception overriding library update restrictions

### Tachiyomi version

0.13.1

### Android version

android 11

### Device

galaxy s21 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not sure I understand the issue, this seems like the intended behaviour.

The app first gets the manga based on the category inclusion/exclusion, then filters based on the library update restrictions.
