### ISSUE TITLE
Invert install/cancel button in new update notification

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#6540]
### Describe your suggested feature

![image](https://user-images.githubusercontent.com/76596575/152076674-e70be47b-c431-4472-9b09-4aba25c1babe.png)
Usually the install button stay on right

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Usually the install button stay on right

Do you have examples?

**Comment by SrW0nka** [comment]
> > Usually the install button stay on right
> 
> Do you have examples?

![Screenshot_20220201-232151_Package installer](https://user-images.githubusercontent.com/76596575/152083567-aacc2393-88ed-4153-abf7-8b13d5890010.jpg)
iirc also in playstore update notifications however I don't have ss, but just think a little, the most targeted option is always in the right, in order to be more accessible

**Comment by vengiare** [comment]
Not entirely sure, but I believe more important **notification actions** have always been on the left side though

![Screenshot_20220202-104152](https://user-images.githubusercontent.com/63973749/152085458-6e95bdc1-463a-4fc5-b096-498b3987088f.png
![Screenshot_20220202-104315](https://user-images.githubusercontent.com/63973749/152085470-d6121d84-b29e-43a0-a380-641e8521ccd1.png)
![image](https://user-images.githubusercontent.com/63973749/152085495-3db65712-4344-4d41-9779-e0a0b081e2bd.png)

![Screenshot_20220202-104213](https://user-images.githubusercontent.com/63973749/152085467-7e676d18-fde9-475a-ac50-76da47991bfe.png)
)

**Comment by arkon** [comment]
Agreed, notification actions are usually ordered left to right. Dialogs are right to left.
