### ISSUE TITLE
Return legacy blue to themes

### ISSUE THREAD

**Issue by Mangavillia** [tachiyomiorg/tachiyomi#6543]
### Describe your suggested feature

I used the legacy blue theme before it was strangly removed in the last update. Besides liking the indigo aesthetic better, the current default theme offers poor contrast with unread chapter counts on the manga covers, and generally.

Please restore the legacy blue theme, or offer something similar.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by IsaacShoebottom** [comment]
I agree, specifically on the contrast. I find it harder to read how many chapters I have read, I tried all the themes and none of them present the same readability as the legacy theme. If they won't add it back, maybe add a custom theme that we can choose our own colors for.

**Comment by Mangavillia** [comment]
> I agree, specifically on the contrast. I find it harder to read how many chapters I have read, I tried all the themes and none of them present the same readability as the legacy theme. If they won't add it back, maybe add a custom theme that we can choose our own colors for.

Fully agree. Your idea of custom themes might actually be superior, though more work for them

**Comment by Soitora** [comment]
> The current default theme offers poor contrast with unread chapter counts on the manga covers, and generally.
> 
> Please restore the legacy blue theme, or offer something similar.
> 

Legacy Blue theme is not coming back, but maybe we can explore the contrast issue you're mentioning.

> Maybe add a custom theme that we can choose our own colors for.

That'll be a feature in the 1.x rewrite, it is not something we have planned for the current 0.x versions

**Comment by ObserverOfTime** [comment]
Yes, please. It was the only good theme.

**Comment by CarlosEsco** [comment]
No plans to re add it
