### ISSUE TITLE
Laggy tab animations

### ISSUE THREAD

**Issue by ObserverOfTime** [tachiyomiorg/tachiyomi#6545]
### Steps to reproduce

1. Open the app
2. Switch back and forth between tabs

### Expected behavior

Switching should be fast.

### Actual behavior

Switching is slower than before.

### Tachiyomi version

0.13.1

### Android version

Android 8.0.0

### Device

HONOR PRA-LX1

### Other details

The library tab seems to load significantly slower than the rest.

Perhaps a setting to disable the animations should be added?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Is this regarding the bottom nav destinations? Or the tabs inside the library (i.e. categories) ? Or the bottom nav icon animations

**Comment by ObserverOfTime** [comment]
The bottom nav icon animations, I suppose.

**Comment by Soitora** [comment]
> The bottom nav icon animations, I suppose.

That's odd, I was previously getting a bit of lag on them on my phone and Emulator, so I remade it as cleanly as possible, now both my phone and emulator is perfectly smooth

I wonder if it's something in the animation that would be affecting certain devices?

**Comment by ObserverOfTime** [comment]
Perhaps the animations are not the actual issue (or only part of it)?
Since, as I mentioned, the library contents load slower than the other tabs.
