### ISSUE TITLE
CBZ files cannot be read 

### ISSUE THREAD

**Issue by Snow2freeze** [tachiyomiorg/tachiyomi#6546]
### Steps to reproduce

Activate option to download mangas chapters under CBR format. 
Download a New chapters.
Try to read it

### Expected behavior

Manga should open correctly

### Actual behavior

Screen turn black and the return to the chapters list

### Crash logs

--------- beginning of crash
01-20 15:41:58.947  2679  2679 E AndroidRuntime: FATAL EXCEPTION: main
01-20 15:41:58.947  2679  2679 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 2679
01-20 15:41:58.947  2679  2679 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.setting.SettingsDownloadController$DownloadDirectoriesDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:5)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6518)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-20 15:41:58.947  2679  2679 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
--------- beginning of main
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 8.1.0 (SDK 27)
Android build ID: OPM1.171019.026 release-keys
Device brand: ATT
Device manufacturer: Q-Innovations
Device name: QS5509A
Device model: QS5509A
Device product name: QS5509QL

### Tachiyomi version

0.13.1

### Android version

Android 8.1

### Device

QS5509A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Important to notice that there's not any option to download as CBR, but only to download as ***CBZ***, which is a completely different file format.

**Comment by vengiare** [comment]
Is the cbr rar5?

#3988

**Comment by Snow2freeze** [comment]
Siret for the mistake on the report. The download files are CBZ files and
the downloading is done using tachiyomi.

**Comment by alessandrojean** [comment]
Are you downloading to an SD card by any chance? SD cards tends to fail over time.

**Comment by Snow2freeze** [comment]
Hi. It s true i'm using a sdcard. But the file that been download is
readable cause i download perfect viewer to read them and that work. Maybe
the issue is some place else. But thanks for tout concerne. I try some
Times again and if i have Something New i ll let toi know

Le mer. 2 févr. 2022 à 17:39, Alessandro Jean ***@***.***> a
écrit :

**Comment by arkon** [comment]
Closing in favour of #6669
