### ISSUE TITLE
Use pure colours (as in light mode colors) when "pure black dark mode" is activated

### ISSUE THREAD

**Issue by fourquestionmarksokay** [tachiyomiorg/tachiyomi#6547]
### Describe your suggested feature

In regular dark mode, the tinted colours (going into white) makes sense as the background is dark but not black, however when "Pure black dark mode" is activated, it *still* uses the tinted colours even though the background is now snapped into black. This isn't optimal especially on OLEDs where the contrast is now too sharp that it actually looks out-of-place.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Use pure colours (as in light mode colors)

A darker theme would obviously extend what's in the dark theme rather than the light theme.


> In regular dark mode, the tinted colours (going into white) 

I don't really know you're referring to with "the tinted colours (going into white)".


> This isn't optimal especially on OLEDs where the contrast is now too sharp that it actually looks out-of-place.

If you want reasonable contrast, you probably shouldn't be using a pure black theme anyway.
