### ISSUE TITLE
Local cannot be read

### ISSUE THREAD

**Issue by masamhel** [tachiyomiorg/tachiyomi#6549]
### Steps to reproduce

1. Made a local folder in a tachiyomi folder
2. Browse tachiyomi for the local manga (titles are there but chapters not found)

In the previous version in its much earlier usage, I was still able to read local mangas there but just recently before I downloaded this new version, I couldn't find the chapters anymore even though I never moved the files from the local folder under tachiyomi. I thought this new version will make me read local mangas again but still the same

### Expected behavior

I should be able to read the local manga

### Actual behavior

It says chapters are not found but the titles are there

### Tachiyomi version

0.12.3 & 0.13.1

### Android version

Android 10

### Device

Samsung M20

### Other details

![20220203_033450](https://user-images.githubusercontent.com/93823545/152224070-2212fbd5-ed2e-4828-a7b8-43ad073e1841.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Local source is working fine at my end. Please refer to the detailed [Local Source guide](https://tachiyomi.org/help/guides/local-manga/) on our website and follow the file structure specified

**Comment by masamhel** [comment]
I did follow the steps that's why I said from my post is that I was able to
read it then suddenly became like that. Did you look at the screenshot I
uploaded there? You will know what I am saying

**Comment by alessandrojean** [comment]
Your screenshot didn't help much because we can't know your file structure. Show it to us so we can try to help.

**Comment by masamhel** [comment]
![Uploading Screenshot_20220203-050613_My Files.jpg…]()

**Comment by masamhel** [comment]
![Screenshot_20220203-050619_My Files](https://user-images.githubusercontent.com/93823545/152237508-a6a5978d-ba73-4c92-aa99-090ec1c970cf.jpg)
![Screenshot_20220203-050625_My Files](https://user-images.githubusercontent.com/93823545/152237511-9b501852-0ff5-4bd1-ae65-6687a6ee401d.jpg)
![Screenshot_20220203-050633_My Files](https://user-images.githubusercontent.com/93823545/152237518-688c1807-382b-4cdb-b305-249d174c120f.jpg)
![Screenshot_20220203-050645_My Files](https://user-images.githubusercontent.com/93823545/152237523-578b5059-d73e-4f92-99d9-745e2dd312b8.jpg)
![Screenshot_20220203-050651_My Files](https://user-images.githubusercontent.com/93823545/152237527-09ab0743-a41f-4890-94ed-c40bb15381e9.jpg)

**Comment by alessandrojean** [comment]
**That's not** the file structure described in the guide [on the website](https://tachiyomi.org/help/guides/local-manga/). Please follow it strictly and the local source will work.
