### ISSUE TITLE
Need a multi download

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#6550]
### Describe your suggested feature

I need a multi download, use a single download it take more time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
No.
Parallely downloading chapters from the same source have lead to temporary/permanent IP bans and sources not working (Ref #1567)

**Comment by Riztard** [comment]
it already support multi download for different source
