### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by Shanerebello** [tachiyomiorg/tachiyomi#6551]
### Steps to reproduce

Manually refreshed the library.

### Expected behavior

All the manga series should be listed while the library should be updating for new chapters in the notification and also all the series should be checked like a previous version.

### Actual behavior

only 60 manga at random get updated and rest are not checked and when library refreshed again same series are refreshed

### Tachiyomi version

0.13.1

### Android version

10

### Device

Poco F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
read the changelog.

**Comment by Shanerebello** [comment]
Okay thanks for the info
