### ISSUE TITLE
[Feature Request] Local Tracker to save start/end date for manga. Also, use for local notes.

### ISSUE THREAD

**Issue by Jacekun** [tachiyomiorg/tachiyomi#6553]
### Describe your suggested feature

**App version:** 0.13.1
**Android Version**: 11 (API 30)

**Request**: Add Local Tracking service built-in that can be enabled in Tracker settings and be selectable on available trackers.

### Other details

Add an option on Tracking settings to enable **local tracking**. If toggled on, can use **local tracking** which is like the current UI for when adding tracking data to manga. Only saves ``start/end date``, and a ``note`` (Similar request to #2155). If another tracking service is used, **sync the start/end dates** to the tracking service. 
Saving data can be done by either of these two:

1. To comply with the other request for [ComicInfo support](https://github.com/tachiyomiorg/tachiyomi/issues/2155#issuecomment-978385736), maybe its best to store the data to the file in which the manga is downloaded.
2. Save to app database.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I really want to avoid having people use the app as a tracking/hoarding system, so it'd be more ideal to offload tracking to actual tracking services like we do today. The dates sent to those should be better inferred based on the available data though, but there's existing issues for that.
