### ISSUE TITLE
Library Update failure

### ISSUE THREAD

**Issue by SHADOWMONARCH002** [tachiyomiorg/tachiyomi#6555]
### Steps to reproduce

The library Update is not working properly.
It is only allowing to update the comics and manga which are all ready completed.
Even though the update button on the upper right corner is allows to update completed mangas. 

### Expected behavior

The update button in the upper right corner should update all manga and comics.

### Actual behavior

I do have more then 1000 comics and manga in my library but only around 140 are updating.

### Tachiyomi version

0.13.1

### Android version

11

### Device

OnePlus nord 1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That's the expected behavior with the new update default settings. You can change if you want it though, although we ***do not*** recommend.
