### ISSUE TITLE
Downloads are too slow

### ISSUE THREAD

**Issue by IgnFed** [tachiyomiorg/tachiyomi#6558]
### Steps to reproduce

1. Just need to download a chapter of any manga.

### Expected behavior

Download a chapter relatively quickly (with a internet also relatively quickly)

### Actual behavior

10-20 minutes to download a single chapter.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung Galaxy A32

### Other details

My internet is fast, but the download time is too much...
This is not necessarily a 0.13.1 problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Please try the troubleshooting guide and keep in mind some sources have rate limiting.
