### ISSUE TITLE
Problems reading a chapter

### ISSUE THREAD

**Issue by IgnFed** [tachiyomiorg/tachiyomi#6559]
### Steps to reproduce

 1. Read a chapter of any manga

### Expected behavior

The pages of the chapter should be loaded relatively quickly depending on your internet speed

### Actual behavior

The pages are slow to load, i need to exit of the chapter and enter again so that the load continues and probably this won't work either.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung Galaxy A32

### Other details

My internet is fast and is not a connection problem.
This is not necessarily a 0.13.1 problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Have you considered trying all listed steps in the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/)?
