### ISSUE TITLE
The scan update for new chapters doesn't cover my full library

### ISSUE THREAD

**Issue by KSLOA** [tachiyomiorg/tachiyomi#6560]
### Steps to reproduce

![image_2022-02-04_080333](https://user-images.githubusercontent.com/90167257/152455169-835dba8d-0d31-4bf9-bd04-69479c49398a.png)
![image_2022-02-04_080341](https://user-images.githubusercontent.com/90167257/152455185-1412e53d-f164-48ff-ad3e-a9e2d8e2ff37.png)

### Expected behavior

wanted to be able to scan the whole library

### Actual behavior

only scanned 20% of my whole library

### Crash logs

--------- beginning of system
--------- beginning of main
02-04 08:04:15.980 12817 12817 E Parcel  : Reading a NULL string not supported here.
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: CPH1937_11_F.13
Device brand: OPPO
Device manufacturer: OPPO
Device name: OP4B80L1
Device model: CPH1937
Device product name: CPH1937

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

OPPO A9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please read the changelog of the update.

The app only updates _by default_:

1. Completed titles;
2. Titles you have read all chapters available.

It's the intended behaviour, and it's not broken.

**Comment by KSLOA** [comment]
ahh i see, thanks man i didnt read the whole update
