### ISSUE TITLE
Automatic updates stuck

### ISSUE THREAD

**Issue by BaccanoMob** [tachiyomiorg/tachiyomi#6561]
### Steps to reproduce

1. Set automatic updates per X hours and wait till the timer is up.

### Expected behavior

Update the required titles in the categories, etc.

### Actual behavior

The updates sometimes get stuck stop in-between. Noticed it happening multiple times.
![Screenshot_20220204-114838_One UI Home](https://user-images.githubusercontent.com/82655889/152520116-081f0d96-4db3-41b9-9500-7186e6c03713.jpg)

The possible fix for the time being is to update a single title (apparently refreshing a single entry resumes the auto updates)

Also last time it happened, a mangadex title got a timeout error.

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Samsung galaxy note10 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by rnldyx** [comment]
This happen to me too,I've done what you've done,and it's still the same,I hope it soon will fixed

**Comment by arkon** [comment]
Did you do everything in the "Background activity" section in advanced settings already?

**Comment by rnldyx** [comment]
Yes,I already do that and everything that I think can solve the problem,but I can't solve the problem whether it's 0.13 or 0.13.1 it's still the same,I even try other fork like tachiyomi Sy or aniyomi with latest version and it's all the same

**Comment by rnldyx** [comment]
> Did you do everything in the "Background activity" section in advanced settings already?

The only solution I found is to use tachiyomi 0.12.3

**Comment by FourTOne5** [comment]
> The only solution I found is to use tachiyomi 0.12.3

that's not a solution

**Comment by Ramdhani04** [comment]
same as me too...

**Comment by BaccanoMob** [comment]
> Did you do everything in the "Background activity" section in advanced settings already?

I think this fixed it but Im not sure whether the app did auto update or not(coz so far the titles I had had no update n the least update interval is 12hrs). Ill close this issue in a few days just to be sure.

For anyone who is facing this issue. Fix is: 
Settings -> Advanced  -> Disable battery optimization under "Background activity" 

When I first started using tachiyomi (which was more than a year or 2 ago), I remember disabling the battery optimization. I think the latest update enabled it for unknown reasons.

**Comment by rnldyx** [comment]
> > Did you do everything in the "Background activity" section in advanced settings already?
> 
> I think this fixed it but Im not sure whether the app did auto update or not(coz so far the titles I had had no update n the least update interval is 12hrs). Ill close this issue in a few days just to be sure.
> 
> For anyone who is facing this issue. Fix is: Settings -> Advanced -> Disable battery optimization under "Background activity"
> 
> When I first started using tachiyomi (which was more than a year or 2 ago), I remember disabling the battery optimization. I think the latest update enabled it for unknown reasons.

No,it can't,I've done that,I always disable battery optimization for tachiyomi,and it's still won't update automatically,and if I update my library manually it's just show tiny of bit my library, example : I have 3000 manga in my library,and when I update it manually it's just show 20 or 25
"Updating library : 0/25" it's always like that,I hope it'll be fixed in new version

**Comment by BaccanoMob** [comment]
@rnldyx **[Read the lastest release notes](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1)** (they made a lot of changes). But to answer your issue, you could go to library settings and change to how it was in the previous built (and im assuming youve only read 20-25 manga up to date [check 3rd point below])

Some changes in the Library settings are:
- Changes to help avoid unnecessary heavy traffic to sources by default:
- Add option for library update only update completely read manga
- **Default to only updating manga that are ongoing and you're fully caught up on**

**Comment by rnldyx** [comment]
> @rnldyx **[Read the lastest release notes](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1)** (they made a lot of changes). But to answer your issue, you could go to library settings and change to how it was in the previous built (and im assuming youve only read 20-25 manga up to date [check 3rd point below])
> 
> Some changes in the Library settings are:
> 
> * Changes to help avoid unnecessary heavy traffic to sources by default:
> * Add option for library update only update completely read manga
> * **Default to only updating manga that are ongoing and you're fully caught up on**

Ok ty,I'll try it

**Comment by rnldyx** [comment]
> @rnldyx **[Read the lastest release notes](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1)** (they made a lot of changes). But to answer your issue, you could go to library settings and change to how it was in the previous built (and im assuming youve only read 20-25 manga up to date [check 3rd point below])
> 
> Some changes in the Library settings are:
> 
> * Changes to help avoid unnecessary heavy traffic to sources by default:
> * Add option for library update only update completely read manga
> * **Default to only updating manga that are ongoing and you're fully caught up on**

TYSM,it work fine if I just update it manually,but I don't know what happen with automatic update,I set it everyday,but till now it won't update automatically

**Comment by arkon** [comment]
If the updates seemingly don't run as scheduled or seems to be dying at some point, then it's very likely a background activity issue and you need to try to fix it via the things mentioned in the advanced settings.
