### ISSUE TITLE
Issue in updating library

### ISSUE THREAD

**Issue by Xmokiee** [tachiyomiorg/tachiyomi#6564]
### Steps to reproduce

I have 200 manga in my library and i tried to update it but while updating its only updating 92 manga.
Now o have to update separately by going into every single manga...

### Expected behavior

While updating every manga in the library should be updated...

### Actual behavior

When i tried to update only half of the manga is updating others are not updating 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Redmi note 5 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the release notes.

**Comment by Xmokiee** [comment]
Sorry for bothering you 
But where is this release notes..... 
Plz give me some link

**Comment by Xmokiee** [comment]
> Read the release notes.
               Sorry to bother you, where can I find this release notes , of possible plz give me some link to these notes

**Comment by CarlosEsco** [comment]
besides popping up whats new on a fresh install, there is an option to see in the settings, as well as going to the releases page on github https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
