### ISSUE TITLE
Webtoon view issue

### ISSUE THREAD

**Issue by Chonkythicc** [tachiyomiorg/tachiyomi#6565]
### Steps to reproduce

![Screenshot_2022-02-05-02-56-59-69_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/99044944/152586990-fa1e139c-36ab-4cfe-a915-796833451eca.jpg)

### Expected behavior

webtoons view slides should fit on my phone screen

### Actual behavior

every time im reading webtoons, the slide panels are not fit on screen, those panels are always zoom out 

### Crash logs

no crash

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Oppo Reno 4

### Other details

i hope you can fixed this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have side padding enabled?
