### ISSUE TITLE
problem when I update the library

### ISSUE THREAD

**Issue by Nabilhm06** [tachiyomiorg/tachiyomi#6566]
### Steps to reproduce

since i downloaded the last update i have in my library more than 300 manga but when i refresh the search shows only 22

### Expected behavior

.

### Actual behavior

since i downloaded the last update i have in my library more than 300 manga but when i refresh the search shows only 22
![Screenshot_20220204-221956_Tachiyomi](https://user-images.githubusercontent.com/99050688/152604781-0b522485-8cb2-463c-8510-55b42a68e892.jpg)

### Crash logs

.

### Tachiyomi version

0.13.1

### Android version

10

### Device

Samsung Galaxy a30

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the release notes. https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
