### ISSUE TITLE
Chapter closing animation can not be skipped

### ISSUE THREAD

**Issue by Kaladasas** [tachiyomiorg/tachiyomi#6567]
### Steps to reproduce

Open a chapter
Close a chapter
Try to go back to the overview while closing animation is shown

### Expected behavior

When leaving a chapter the animation should start, but if you click the back button again while in the animation, the animation should stop and you return to the previous page (which is most likely an overview).

Also the animations should be an option in the settings since it might be slower on older phones

### Actual behavior

While the opening an closing animation when reading a chapter looks nice, it can not be skipped.
Especially chapter closing animation takes nearly one second to end and can not be skipped to leave the manga.

### Tachiyomi version

0.13.1

### Android version

Android 9

### Device

Hisense A6L

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
As far as I'm aware, activity transitions can't be skipped. It could maybe be made faster?
