### ISSUE TITLE
Bring back few old App Theme or make new ones

### ISSUE THREAD

**Issue by m0nk3ybraindead** [tachiyomiorg/tachiyomi#6568]
### Describe your suggested feature

Please bring back some of the old themes!
Because when using pure black mode there's no compatible app theme, it's either too light or too dark.

### Other details

Would love to have the blue one back tortoise I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Only 1 theme (Legacy Blue) was removed and it will not be returning.
