### ISSUE TITLE
Updates button didn't update any manga

### ISSUE THREAD

**Issue by reygrey666** [tachiyomiorg/tachiyomi#6569]
### Steps to reproduce

1. Open Updates menu
2. Click Refresh icon in right top screen
3. Updating library... (0/1) appear in notification but didn't update any manga

### Expected behavior

Update every manga on my library

### Actual behavior

Didn't update any manga

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung A10s

### Other details

I can update manga only when I swipe down to refresh in every categories. Waiting until process done and move on to the next category and do it again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
read the changelog https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
