### ISSUE TITLE
[Bug] Luscious: Gifs is not playing in some galaries

### ISSUE THREAD

**Issue by Realppp** [tachiyomiorg/tachiyomi#6571]
### Steps to reproduce

1.open merged chapter with gifs

### Expected behavior

Should display gifs

### Actual behavior

Displays images only

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Galaxy S10 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Realppp** [comment]
Also there are some merged chapter that work and some doesn't. Only those that have their cover animated are animated in the merged chapter but those without the cover animated are in images even though their websites have it in gif.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

You'd also need to provide more concrete reproduction steps.
