### ISSUE TITLE
Can't open local manga in MIUI

### ISSUE THREAD

**Issue by DiodE-ui** [tachiyomiorg/tachiyomi#6572]
### Steps to reproduce

1: created /Tachiyomi/ folder in internal shared storage
2: created /local/ folder inside /Tachiyomi/
3: copied a fully readable .cbz file inside /local/
it's now /storage/emulated/0/Tachiyomi/loca/my_file.cbz

### Expected behavior

now I presume it should be readable on Tachiyomi if I looked it in "Local source"

### Actual behavior

but it doesn't show up at all, neither are any of he other cbz file in the folder.

### Tachiyomi version

0.13.1

### Android version

Android 11 (MIUI 12.5)

### Device

Xiaomi Redmi Note 8

### Other details

[picture1](https://files.catbox.moe/nkm53w.jpg)
[picture2](https://files.catbox.moe/sl0acz.jpg)
_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
You are missing the correct folder structure for adding a series. Move your cbz file into another folder inside of local and it should work
https://tachiyomi.org/help/guides/local-manga/#folder-structure

**Comment by DiodE-ui** [comment]
> You are missing the correct folder structure for adding a series. Move your cbz file into another folder inside of local and it should work https://tachiyomi.org/help/guides/local-manga/#folder-structure

wdym? I can't see the difference between the folder structure in the guide and in picture2.

**Comment by arkon** [comment]
The CBZ files need to be within another layer of folders.
