### ISSUE TITLE
Tracker and Logger

### ISSUE THREAD

**Issue by WelkinBunbury** [tachiyomiorg/tachiyomi#6573]
### Describe your suggested feature

I do not understand the reason why a FOSS manga reader need these tracker and loggers

**Tracker**

- Google Firebase Analytics
- Google AdMob

**Logger**

- ACRA
- Timber
- slf4j-timber

And if its impossible to ship without these trackers and loggers please provide with a option to turn them off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment]
https://tachiyomi.org/privacy/#privacy-policy

**Comment by CarlosEsco** [comment]
You should also figure out what a logger is next time you ask.
