### ISSUE TITLE
Cant install sources

### ISSUE THREAD

**Issue by lukatsivilashvili** [tachiyomiorg/tachiyomi#6574]
### Steps to reproduce

1. Press install on any source
2. It says retry

### Expected behavior

Download a source

### Actual behavior

Cant install a source

### Tachiyomi version

0.13.0 0.13.1

### Android version

12

### Device

Redmi note 9 pro

### Other details

Installed android 12 aosp and it won't download/any sources, used to work just fine on a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by H1ghSyst3m** [comment]
I also have the problem.

I have a **Xiaomi Mi 11 | Android 12** 
I gave the App all possible rights. I tried it with the Legacy Install method and the PackageInstaller, but still didn't work.



### Here is a small clip with the Problem

https://user-images.githubusercontent.com/60105043/152650609-1f56a7c8-48c0-4fb3-a755-64c76af0947a.mp4

**Comment by lukatsivilashvili** [comment]
Mine doesnt even go to the install screen, just says initializing for a sec and then retry

**Comment by H1ghSyst3m** [comment]
Do you use PackageInstaller or Legacy?

**Comment by lukatsivilashvili** [comment]
Didnt even know you could change it, its set as packageinstaller as default

**Comment by H1ghSyst3m** [comment]
Try Legacy. PackageInstaller does only work when MIUI Optimization is turned off. But MIUI on Android 12 doesn't have any option for MIUI Optimization

**Comment by robtorr5** [comment]
Same problem, says app not installed (see screenshot)
![Screenshot_20220205-144819](https://user-images.githubusercontent.com/69119883/152660383-d17ee20e-2e28-4522-b508-e39ee23ace0c.jpg)

**Comment by arkon** [comment]
@robtorr5 That's unrelated to this issue. Download the universal APK if you don't know what CPU architecture your device is.

As for the MIUI issues, it's supposed to default to the legacy installer if you're using MIUI and PackageInstaller otherwise. If that doesn't seem to be the case, let me know. If you unknowingly changed the setting, then that's the issue.

**Comment by robtorr5** [comment]
Ah my bad. And yes ,the universal version worked perfectly. Thanks! :)

**Comment by lukatsivilashvili** [comment]
Where can i find the universal apk? Couldnt find it in the releases

**Comment by xinkev** [comment]
Probably because extensions are built without setting `android:exported` to true.

[More details here](https://www.reddit.com/r/androiddev/comments/st16gt/if_your_app_is_targeting_the_latest_android_12/).

**Comment by arkon** [comment]
AFAIK, all current official extensions that have activities have the exported flags set.

I'm going to close this issue since the PackageInstaller option is now removed for MIUI users until it better supports it.
