### ISSUE TITLE
Adjustable disk space threshold

### ISSUE THREAD

**Issue by weedy** [tachiyomiorg/tachiyomi#6576]
### Describe your suggested feature

So in commit https://github.com/tachiyomiorg/tachiyomi/commit/93960315d99a1af46f46e8fc609279754e3e7a1e a low space threshold was added which I'd argue is way too low for /data. Maybe leaving only 50MiB on /sdcard is fine but on main storage my android skin gets cranky.

Could you add a config in Settings -> Downloads to leave X space free in save location?
In a perfect world I'd like to see leave X% free, but even if you just change the hard coded megabytes to 250-500 that would suffice.

I would think most heavier Android skins start getting cranky with only 50MiB free. Mine definitely does.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's really only meant to ensure that a chapter can be installed since it's really not the app's responsibility that the rest of the system can work with the available resources.

I'll bump it up a bit though.

**Comment by arkon** [comment]
45e4092335a83b47c257fd119e33a031d80996b5
