### ISSUE TITLE
Global search closes the app

### ISSUE THREAD

**Issue by maxobremer** [tachiyomiorg/tachiyomi#6577]
### Steps to reproduce

Steps to recreate
Step one open tachiyomi
Step two search anything in global search
Step three the app closes/crashes

I use tachiyomi-v0.13.1.apk 

### Expected behavior

I expect it to search the manga name globally across my installed extensions

### Actual behavior

Tachiyomi closes or xrashes

### Crash logs

--------- beginning of main
02-05 19:57:06.217  1136  1136 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-05 19:57:06.230  1136  1136 E libc    : Access denied finding property "runtime.mmitest.isrunning"
--------- beginning of system
02-05 19:57:06.387  1136  1165 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@51543fb
02-05 19:57:06.388  1136  1165 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@3e69c18
02-05 19:57:07.160  1136  1197 E SQLiteLog: (284) automatic index on C(manga_id)
02-05 19:57:07.161  1136  1197 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-05 19:57:08.738  1136  1176 E         : APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 10 (SDK 29)
Android build ID: SNE-LX1 10.0.0.245(C432E10R1P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWSNE
Device model: SNE-LX1
Device product name: SNE-LX1

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

HUAWEI Mate 20 lite SNE-LX1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This has happened in the past when some people have Hitomi.la installed since the search takes up a lot of memory. If you have that, try uninstalling it or not including it in pinned sources (if you set it to only search those).
