### ISSUE TITLE
If Chapter Title and Manga Title are the same, Chapter Title (after "Chapter #") is not shown.

### ISSUE THREAD

**Issue by WildManiac** [tachiyomiorg/tachiyomi#6578]
### Steps to reproduce

1. Create manga folder in Local Tachiyomi folder (using instructions from website) with name "[MANGATITLE]".
2. Create chapter folder within that manga folder with name "Chapter [#] - [MANGATITLE]".
![Screenshot_20220202-191855_Solid Explorer_1_1](https://user-images.githubusercontent.com/11233971/152659503-b957d987-b1e3-4d65-b788-9a327f9b9709.jpg)
3. View "Manga" in Tachiyomi via local source.

### Expected behavior

Chapter shows as "Chapter [#] - [MANGATITLE]".

### Actual behavior

Chapter shows as "Chapter [#]".
![Screenshot_20220202-191843_Tachiyomi_1_1](https://user-images.githubusercontent.com/11233971/152659506-b82b91d2-c0c6-4af3-aad7-d3037dffef19.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung A52 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The chapter name parsing it's broken in some way since a while, but removing the series name from the chapter name it's intentional.
