### ISSUE TITLE
Incognito option per series/manga

### ISSUE THREAD

**Issue by arichua** [tachiyomiorg/tachiyomi#6580]
### Describe your suggested feature

Incognito - when you're browsing/reading Chapter, wish there's an incognito option in the settings (Reading mode> For this series) so you don't need to leave the manga you are reading and go to 'MORE' just to on the incognito option
![Screenshot_2022-02-05-20-10-54-732_eu kanade tachiyomi](https://user-images.githubusercontent.com/96766003/152667957-662db204-f6e4-453c-9f9b-8ad51b96a358.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No.
