### ISSUE TITLE
Disable ripple effect in navbar

### ISSUE THREAD

**Issue by tAzO8596** [tachiyomiorg/tachiyomi#6583]
### Describe your suggested feature

In Gmail there is no ripple effect for material u which looks nice in my opinion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Gmail is non-standard.
