### ISSUE TITLE
Refresh feed isn't working properly

### ISSUE THREAD

**Issue by CoudStrife** [tachiyomiorg/tachiyomi#6585]
### Steps to reproduce

1. Proceed to refresh library
2. Tachiyomi starts refreshing library
3. Only MangaSee extension being refreshed and nothing else

### Expected behavior

All extensions should've been refreshed 

### Actual behavior

Only the MangaSee extension is being refreshed

### Tachiyomi version

0.13.1

### Android version

Android 8

### Device

Galaxy S8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Read the changelog. https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
