### ISSUE TITLE
INKR - could not parse the API response

### ISSUE THREAD

**Issue by yimeji** [tachiyomiorg/tachiyomi#6586]
### Steps to reproduce

1. Install extension.
2. Add a title into library.
3. Wait for library to load the chapters.

Had to search for title because nothing will be listed and it says "no result found".
![20220207_094544](https://user-images.githubusercontent.com/89035153/152712406-2ecebc81-b5a8-4253-9b63-354ed84a5b6e.jpg)

### Expected behavior

Library load all available chapters for the title.

### Actual behavior

No result found and had to search for title.

No chapter is listed under a title and gets error msg "could not parse the API response".

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung A51

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

also already reported on that repository.
