### ISSUE TITLE
Library update Restrictions

### ISSUE THREAD

**Issue by Hetarth02** [tachiyomiorg/tachiyomi#6587]
### Steps to reproduce

1.  Settings > Library > Library Update Restrictions
2. Check mark both, `Completely read series` and `Ongoing series`
3. Go to Home screen(Library)
4. Pull Down to refresh/Tap on the Global refresh button

![20220207_111104](https://user-images.githubusercontent.com/80420115/152730855-4d42cb80-58e2-4366-98e1-60b42c5279ac.jpg)

### Expected behavior

All the mangas should be updated.

### Actual behavior

Instead, only the mangas which are `Completely read` by user(me) are getting updated. Other unread mangas are not getting updated.

![20220207_111243](https://user-images.githubusercontent.com/80420115/152731037-5e171301-005d-431f-9eaf-9eb995c217aa.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 9

### Device

Samsung Galaxy on7 Prime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That's the expected behavior. If you want to update without restrictions, you need to uncheck the boxes.

**Comment by CVIUS** [comment]
If you checked `Completely read series`, titles with all read chapters will only update. If you checked `Ongoing series`, titles that have not `Completed` status will only update. 
Don't get confused.
Since you checked both, only titles with all chapters read and titles that have not `Completed` status will update. However, it is not recommended to uncheck those two to prevent extension from getting removed due to unnecessary request. If you do not want to update without restrictions, just uncheck the boxes as mentioned by @alessandrojean. Goodbye.

**Comment by Riztard** [comment]
with that amount of unread chapter just read the unread chapter first, no need to check update

**Comment by Hetarth02** [comment]
> If you checked `Completely read series`, titles with all read chapters will only update. If you checked `Ongoing series`, titles that have not `Completed` status will only update. 
> Don't get confused.
> Since you checked both, only titles with all chapters read and titles that have not `Completed` status will update. However, it is not recommended to uncheck those two to prevent extension from getting removed due to unnecessary request. If you do not want to update without restrictions, just uncheck the boxes as mentioned by @alessandrojean. Goodbye.

Thank you for the explanation, I think I now understand how the feature works.
