### ISSUE TITLE
Update checking optimization

### ISSUE THREAD

**Issue by Gimmeursocks** [tachiyomiorg/tachiyomi#6590]
### Describe your suggested feature

when refreshing it iterates through my whole library even the finished ones, so im suggesting an option that marks smth as finished or excluded from update search, to make the update checking faster for example i only need to update 6 instead of 24 total.

i know we can use categories but it would be better to implement such feature.

thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This already exists, it's called Library Update Restrictions. It's in the library settings.

**Comment by Gimmeursocks** [comment]
but it is inaccurate and depends on the source itself specifiying if the series is finished so if there was a way to mark it finished myself is what i meant

**Comment by alessandrojean** [comment]
> so if there was a way to mark it finished myself

There isn't currently, but there's already an open issue (#4398) that is related to this.
