### ISSUE TITLE
Searching in an individual extension generates a infinite loop

### ISSUE THREAD

**Issue by panoramix360** [tachiyomiorg/tachiyomi#6593]
### Steps to reproduce

1. Try to search for a word that has many titles with it
2. Scroll through the titles to reach the end
3. The next titles that will be loaded will be the same of the above and so on

### Expected behavior

I think that the correct way will be showing the next titles that fits the word searched (pagination or something)

### Actual behavior

Instead it shows the same titles that were previously shown.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

One Plus 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
99% likely this is an extension specific issue, open a ticket in that repository, and provide the extension that is causing the issue.
