### ISSUE TITLE
13.1 not updating my library manga

### ISSUE THREAD

**Issue by Owerlords** [tachiyomiorg/tachiyomi#6596]
### Steps to reproduce

13.1 not updating my library manga so i downloaded v12 again it updates abput 96 mangas

### Expected behavior

Updates all ongoing mangas in library and tells me if some sources dont update the manga anymore

### Actual behavior

Only updates about 20 mangas

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Galaxy tab s5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read the app update changelog.

https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
