### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by Ye11ow-Flash** [tachiyomiorg/tachiyomi#6597]
### Steps to reproduce

1. When I refresh by library(By dragging down and refreshing), it only refreshed 21/111 mangas

### Expected behavior

When I refresh my library, all of 111 mangas should be refreshed

### Actual behavior

Only 21/111 mangas are getting refreshed.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Realme Narzo 30 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please actually read the app update changelog.

https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.1
