### ISSUE TITLE
Cannot update the library

### ISSUE THREAD

**Issue by leandro-maciel** [tachiyomiorg/tachiyomi#6598]
### Steps to reproduce

1. Press button used to update the library

### Expected behavior

A notification with the update progress should appear, and when finished new chapters are added to the updated manga

### Actual behavior

Instead only the "updating library" message appears but nothing happens, even if the app is allowed to create notidications

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

Samsung Galaxy M20

### Other details

![Uploading Screenshot_20220207-193240_Tachiyomi.jpg…]()
Notice the lack of a notification

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6599
