### ISSUE TITLE
sub - sorting

### ISSUE THREAD

**Issue by zlehnherr** [tachiyomiorg/tachiyomi#6600]
### Describe your suggested feature

It would be nice to be able to sort manga my 1 main method, then sub-sort it into another  - more specifically what I'm looking for is to sort by last read, then alphabetically. After adding a bunch of manga at once, it would be nice to have all those sorted. I could also see others wanting to sort by last read, then date added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Could you not just use more categories

**Comment by zlehnherr** [comment]
@CrepeTF That seems like extra hassle, every time I add a new manga, I would have to then add it to a category. With the sub-sort feature, it would just automatically sort it without having to do extra steps. With the sub-sort you can also keep all manga on one page instead of different tabs.

**Comment by arkon** [comment]
Hassle to implement / complicates UX.
