### ISSUE TITLE
Ongoing / Completed status doesn't update unless you manually update the individual manga

### ISSUE THREAD

**Issue by Ugleh** [tachiyomiorg/tachiyomi#6602]
### Steps to reproduce

When doing a global update to check for chapters on all of your items (manga, whatever) The Manga status does not update. It. Will update however if you go to that Manga and refresh it.

### Expected behavior

All manga statuses should be updated with a global update check instead of individual update check.

### Actual behavior

When pressing update on an individual chapter, it will update the status, however not if you update globally.

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Google Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
#6599
