### ISSUE TITLE
American comics option

### ISSUE THREAD

**Issue by Sebas365** [tachiyomiorg/tachiyomi#6604]
### Describe your suggested feature

It would be good if tachiyomi can have american comic sites extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
They already exist, find them yourself
