### ISSUE TITLE
library animation issue

### ISSUE THREAD

**Issue by Jkccl9** [tachiyomiorg/tachiyomi#6605]
### Steps to reproduce

compact grid library, x4 portrait view (doesnt happen on x2/x3). 
scroll down to very bottom of default library list. click on any manga and then go back, to the library list. 

### Expected behavior

scroll down to very bottom of default library list. click on any manga and then go back.

it should go back the library list remembering where i scrolled down to/at the manga that i exited from

### Actual behavior

the app scrolls to half way up the library list and does a back animation on the middle row. doesnt happen on any other manga that is not on the very bottom of the library list

### Tachiyomi version

13.1

### Android version

android 11

### Device

poco f3

### Other details

also why did you change the default colour for badges and in app to a pale light blue/violet it looks so bad compared to the previous navy blue. all the other themes look bad as well, why are there three skin coloured options? i would be okay with no blue if you left the old red theme but you deleted that too and left the neon pink that hurts my eyes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Shouldn't happen in preview anymore.
