### ISSUE TITLE
Bring back the old version marked library manga

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#6608]
### Describe your suggested feature

I Just updated to new version and the old feature marked library manga on extension changed to In Blue Badge instead just darkening the manga. The old marked library manga is more comfortable and better looking than the new marked library manga.

### Other details

The old version : 0.10.3
The new version : 0.13.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
No

**Comment by HapyEnding** [comment]
> No

Care to elaborate?

**Comment by CarlosEsco** [comment]
Support for two different options is not being added.  This is the new design and its not being reverted.  aka No
