### ISSUE TITLE
Fix the unexpected error will downloading

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi#6612]
### Steps to reproduce

downloading
one chapter finish
unexpected error and the download process stop

### Expected behavior

if one chapter is downloaded, the next one will continue

### Actual behavior

the download process will meet unexpected error just after one chapter is download, and another one can't be downloaded

### Tachiyomi version

preview r4139

### Android version

Android 11

### Device

Mi pad 5 pro

### Other details

add a function to restart automatically, or just ignore this problem and continue downloading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Also why did you open the issue again?
https://github.com/tachiyomiorg/tachiyomi/issues/959
