### ISSUE TITLE
Updating 

### ISSUE THREAD

**Issue by Kuro265** [tachiyomiorg/tachiyomi#6614]
### Steps to reproduce

The global update is Too slow and the global update is not updating after few hr after the new version 

### Expected behavior

The update need to be fast 

The update need to updated for few hr like after 3hr

### Actual behavior

The updated is Too after 5min for 1 Manga.
![Screenshot_20220209-234012_Chrome](https://user-images.githubusercontent.com/91021625/153235442-68b13f46-0611-4835-803d-702da08ed12a.jpg)

After 12hr for the global update is still not updating at all 

### Tachiyomi version

1.02

### Android version

Android 10

### Device

Samsung galaxy note s20 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
1.02 is not a valid tachiyomi version, so you are more than likely using a fork.  also read the changelog.

**Comment by Kuro265** [comment]
I write wrong is 0.13.1

**Comment by CarlosEsco** [comment]
read the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/). and read the changelog
