### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kuro265** [tachiyomiorg/tachiyomi#6615]
### Steps to reproduce

The update take very long to complete 

The global update is not updating after 3hr or so 

### Expected behavior

 I have waited so long 
![Screenshot_20220209-235302_Chrome](https://user-images.githubusercontent.com/91021625/153238077-f01d4ce4-09ad-479d-bce2-227823892045.jpg)

### Actual behavior

The update is Too long and I have more than 15 min and is still at 400 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Samsung galaxy note s20 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please read the changelog and don't open new duplicate issues.
