### ISSUE TITLE
Cover bottom navigation bar when on-screen keyboard is visible

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6617]
### Describe your suggested feature

Title.

edit: Bottom navigation bar not covered in Library, Source, and Extension search. History search acts as expected.

![image](https://user-images.githubusercontent.com/63973749/153277713-80a56c5f-26cd-4274-9ded-e6700f42a334.png)

![image](https://user-images.githubusercontent.com/63973749/153278043-1b63e111-b03b-4ce1-b3bb-207f51081ab5.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No longer relevant after some UI rewrites that are happening.
