### ISSUE TITLE
Filter out read chapters in Updates tab

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6622]
### Describe your suggested feature

#3365 is requesting to add ability to filter read/unread chapters in Updates tab. This request is to filter out read chapters directly in Updates tab. Who would want to filter read chapters in Updates tab anyway? Also, when the Updates tab is empty, it displays "No recent updates", it make sense, right?😅 That's it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3365 encompasses this, not sure why a new issue was created.
