### ISSUE TITLE
Not all items in library update

### ISSUE THREAD

**Issue by TheNightReaper** [tachiyomiorg/tachiyomi#6624]
### Steps to reproduce

Under the 'updates' tab, drag down to update all items in library. Open notification panel to see the status of the update. Compare the number of items updating with how many added yo the library.

### Expected behavior

Normally all the items in the library check for updates and whatever has an update shows in the 'updates' tab. A notification during the update shows a progress bar showing for example 'Checking for updates (x/200)'

### Actual behavior

Instead of all the library items updating, according to the notification status during the update, the total number of items in the library listed '(x/200)' do not match the actual number of items '300'. With this, it is clear that only 200 out of the 300 are updating for some reason.

### Tachiyomi version

0.13.1

### Android version

Android 9

### Device

Samsung Galaxy Note 8

### Other details

This didn't occur on the pervious version and only occurred after the latest update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #6599.
