### ISSUE TITLE
DNS over HTTPS(DoH): issue to redirect/directly connect to ip 

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#6625]
### Steps to reproduce

1. Enable DoH
2. open source which redirect/only use ip 

### Expected behavior

browsing source normally

### Actual behavior

getting error NXDOMAIN

### Tachiyomi version

0.13.1

### Android version

A11

### Device

Redmi 8

### Other details

some example [from tachi ext](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10783)
same issue even if baseurl changed to ip 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
This used to happen with Komga ext, and Extensions for other Self Hosted Comic/Manga software
Relevant PR to try out: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6335

**Comment by arkon** [comment]
It wouldn't make sense to transparently ignore the DoH setting automatically. If extensions require it, they can do the above (which is probably the case for anything that access non-secured sites).
