### ISSUE TITLE
Use semibold for library badges text

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6626]
### Describe your suggested feature

Should help a lot with readability

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
![Screenshot_20220212-222401_Tachiyomi](https://user-images.githubusercontent.com/4098258/153736959-6fea0ede-720e-4a08-95fa-f5b3c7de55f7.jpg)

Sample of medium font family for numerical badges on the left and a condensed one for text like on the right.

**Comment by vengiare** [comment]
Would probably wait for others' opinion on the condensed text. Probably check it on the "In library" badge also

**Comment by CarlosEsco** [comment]
Should probably consider moving the language badge below the numerics. That solve the long language badge issue that was open also iirc
