### ISSUE TITLE
12 hours minimum update frequency is too much

### ISSUE THREAD

**Issue by exentio** [tachiyomiorg/tachiyomi#6630]
### Describe your suggested feature

I understand wanting to reduce traffic to sources, but 12 hours basically means twice a day and with no control over the times of the update. Most people don't open the app to refresh the library when they feel like they have time to read a manga, they wait for a notification so they can eventually take a break from what they're doing.  
A 3-4 hours interval is way more user-friendly while generating less traffic than 1 hour, at most 6 is acceptable too, but 12 is way too much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Most manga update weekly or monthly, checking every 3/4 hours provides nothing but extra hits on sources.  You have to realize there are people with thousands of manga in their library and these people don't even diversify their sources half the time.  

Learn some patience, you don't need to read everything the second it drops, add older manga that you haven't read with lots of chapters and then you can read those at your whim, and last but not least. The lower time is not coming back so develop better reading habits.

**Comment by exentio** [comment]
I don't have to justify my "unhealthy reading habits", which even if I did have it wouldn't be of your business. I received the rude answer I was expecting, not gonna lie. Thankfully the app is open-source and I can do it myself, I just wanted everyone to benefit from this.

**Comment by CarlosEsco** [comment]
> I don't have to justify my "unhealthy reading habits", which even if I did have it wouldn't be of your business. I received the rude answer I was expecting, not gonna lie. Thankfully the app is open-source and I can do it myself, I just wanted everyone to benefit from this.

If you thought this rude, you should be glad you asked it here and not on discord.

**Comment by Soitora** [comment]
> I just wanted everyone to benefit from this.

Everyone but the people hosting the chapters you wanna read?

**Comment by vengiare** [comment]
> I just wanted everyone to benefit from this.

Lol funnily enough literally everyone will suffer either from sources getting significantly slower due to tachi's hug of death, or from site owners blocking tachi cause it's killing their servers.
