### ISSUE TITLE
Library Update Restriction Popup Choices

### ISSUE THREAD

**Issue by KenDxD** [tachiyomiorg/tachiyomi#6634]
### Describe your suggested feature

Please kindly add a popup to select what settings is what the user need for:
-The add option for library update only update completely read manga
-Default to only updating manga that are ongoing and you're fully caught up on

Other people don't need this feature by default and it need disabled by default.

### Other details

Other user's like me don't need this feature at all and please just make it optional not enable it by default. Some user is not techie like us.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KenDxD** [comment]
If there's no popup, just disable that feature by default. The purpose of update is to update all chapters of the manga, thats all.

**Comment by KenDxD** [comment]
![Screenshot_2022-02-12-23-31-30-16_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/41190270/153717530-da4d9c2f-d4e7-487a-bc14-842a83e8ea8c.jpg)

This is what I mean, disable this feature by defaule

**Comment by CrepeTF** [comment]
Updating is one thing, but when there are over a million daily active users, congregating on popular sources and making 1 network call per manga in their library, that is another.

We do not want to kill sources unintenional DDoS nor have them actively block Tachiyomi which are very much the worst case scenario and a real one. 

Just edit it manually.

**Comment by arkon** [comment]
These were decided as sensible defaults for most users. If you feel the need to hit sources when seemingly unneeded, you're still free to do so with the settings.

You don't have to be a "techie" to peruse app settings.

**Comment by KenDxD** [comment]
That's why some users stay at 0.12.3 because of this new implementation. And for the untentional DDoS attack, you can just add some delay time to limit the update.

**Comment by CrepeTF** [comment]
There is already rate limiting and it's still happening
