### ISSUE TITLE
Filter by unread in library not removing comic after reading.

### ISSUE THREAD

**Issue by KidoVin01** [tachiyomiorg/tachiyomi#6642]
### Steps to reproduce

1. Finish reading the latest chapter (and all the previous chapters) of a comic.
2. Exit the comic page.
3. The comic still remains unread (with the number count) in the library.
4. Fixed by restarting app or refreshing the manga (swiping down on the comic page)

### Expected behavior

The comic should be filtered out and not appear under the library after reading and exiting the comic page.

### Actual behavior

The comic still remains unread (with the number count). Have to restart app or refreshing the manga (swiping down on the comic page) in order for the comic to stop appearing in the library.

### Crash logs

No crashes.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

One Plus 6

### Other details

Running LineageOS 18.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems to fine in latest version.
