### ISSUE TITLE
Having issue with Zooming video below

### ISSUE THREAD

**Issue by JasonSkylar** [tachiyomiorg/tachiyomi#6650]
### Steps to reproduce

After updating the app from v 0.12.1 to 0.13.1 I'm having issue with zooming

### Expected behavior

Zooming should be more like this....got this zoom form version 0.12.1

https://user-images.githubusercontent.com/58237533/153954247-bdc6daf9-7d97-4ab8-9068-816ef8269de7.mp4

### Actual behavior

Uploading Screenrecorder-2022-02-14-22-18-12-322.mp4…

### Tachiyomi version

Tachiyomi version 0.13.1

### Android version

Android 10

### Device

Redmi 9c

### Other details

Hope you can fix it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Use the webtoon reader.

**Comment by JasonSkylar** [comment]
it doesn't load it force close and take me back to chapter list

**Comment by arkon** [comment]
See #1908
