### ISSUE TITLE
Grid mode for reading webtoons

### ISSUE THREAD

**Issue by vongdong** [tachiyomiorg/tachiyomi#6656]
### Describe your suggested feature

Have pages in a grid view from top left to right for webtoons so it's easier/faster to read. I personally cannot stand reading webtoons in continuous vertical mode, I'm sure there are others as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Aside from that this feature is completely different from what current reader views support, Webtoons aren't all split by panel, with some sources splitting by pixels, some not splitting at all, and others doing it in other nonstandardized ways.
