### ISSUE TITLE
Enhancement to the upcoming "Started Series" feature in "Library Update Restrictions."

### ISSUE THREAD

**Issue by Mano5JP** [tachiyomiorg/tachiyomi#6657]
### Describe your suggested feature

I am currently using TachiyomiSY, and I noticed a [commit](https://github.com/tachiyomiorg/tachiyomi/commit/f18d161eaf54c9d9f74bf412447e15216f1ee1dc) in Tachiyomi that is already in the new release of TachiyomiSY Preview.
And functionality is called "Started" in Library Update Restrictions.

I'm not a coder, but I'm guessing that "Started" here refers to any (previously/Chapter 1) read chapters. So, I was thinking that instead of "Started" we could have something like "Caught 3.8/4" or has less than 10/given threshold chapters; what it's called isn't important for now. As a result, rather than any "Started Series" it checks to see if the requirements are met and includes it in the library update.

With this, we can use both ("Completely Read Series" and ("Started Series" as the name suggests)) at the same time.

The majority of my problems/request could be solved with the implementation of [PR](https://github.com/tachiyomiorg/tachiyomi/pull/5734). As a result, you can disregard the rest of my information below. 

### Here's my scenario:

I currently have 8 categories, ranging from (Reading Series, Plan to Read Series <50, Plan to Read Series >50, On Hold Series, Not Started Series, Completed Series, Plan to Drop Series, and Dropped Series). I'm thinking about adding one more Reading Series to my collection to diversify it. 
And I'm using the "Completely Read Series" restriction from "Library Update Restriction."

I have either recommended or seen worth reading series that belong in the "Not Started Series" category.
	Series X, for example, has 150 chapters.
	I finished Y chapter and transferred it from the Not Started Series to the Plan to Read Series > 50.
I am aware that "Started" will be an optional feature on Main. But I am/will hesitant to use it for the same reason that feature Suggested. 

There are three solutions to this problem.
1. Do not make use of the feature.
2. Mark read chapter to Unread.
3. Leave the feature alone and use it.

And because I use Include/Exclude categories, my last four categories are never updated/downloaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
What you say does make sense but I think we should do `Completely Read Series` -> `Has read X% of chapters` @arkon your opinion?

**Comment by Mano5JP** [comment]
Either works for me.

**Comment by arkon** [comment]
#6916
