### ISSUE TITLE
Choose global library update time

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi#6658]
### Describe your suggested feature

I'd like to be able to set the time (like at 06:00 or 20:00, ecc.) of when to execute the daily / every 2 days global update.

### Other details

overall very low priority

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
The timer starts counting from when you last edited the update frequency, so you can change it, and then change it back

**Comment by Seishirou101** [comment]
However, it'll veer farther and farther away from when you want it, but it has already been rejected before #1254, so it is your best bet.
