### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by arthuritalo** [tachiyomiorg/tachiyomi#6660]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/11094457/154248794-f835cfde-2965-44a1-b261-d66c5fb35851.png)
![image](https://user-images.githubusercontent.com/11094457/154248823-30132d3b-7cf8-4363-a0cf-8c0c5cee229e.png)

yesterday i downloaded the latest version of tachiyomi and now my library don't update all mangas only 16 and after only 11

### Expected behavior

This should not happen

### Actual behavior

idk

### Tachiyomi version

0.13.1

### Android version

7

### Device

xiaomi redmi 4x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6599
