### ISSUE TITLE
Ability to turn off the "duplicate title" and "failed update" features

### ISSUE THREAD

**Issue by gambolshroud** [tachiyomiorg/tachiyomi#6662]
### Describe your suggested feature

Maybe I'm the only one, but I like to have multiple copies of manga from different sources since some update faster than others. The new "multiple manga of the same title" notification is super annoying when I add new manga that I really like. Having the ability to turn this off would be amazing. 

The feature of getting a list of manga that didn't update properly can also be fairly annoying and it would be helpful to have the ability to turn this off as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. No. 1 extra button press for a workflow that doesn't occur that often is perfectly acceptable for any sane person.

2. You can already manage notifications.

**Comment by gambolshroud** [comment]
I don't get why y'all have to be so freaking ignorant with suggestions.

**Comment by CrepeTF** [comment]
Notification management is a standard Android feature, try holding your notifications

**Comment by CrepeTF** [comment]
> I don't get why y'all have to be so freaking ignorant with suggestions.

This project is possible through volunteers, there has to be a line as to what to add and what not to add since this all done through our free time. It's just not practical to spend time working on a feature which a very small minority would benefit from. 

Though since this is an open source project if you wish to code the feature and make a pull request you could do that.
