### ISSUE TITLE
Filter Manga By Source

### ISSUE THREAD

**Issue by zlehnherr** [tachiyomiorg/tachiyomi#6663]
### Describe your suggested feature

It would be great to filter manga by source so after mass importing a library or adding a lot to library, to filter and display all manga from one source to make it easier to categorize.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You can type the name of an extension in the search bar in Library and it'll filter

**Comment by zlehnherr** [comment]
> You can type the name of an extension in the search bar in Library and it'll filter

Thanks for the info, would it be a good request to have a filter like this added to the filter button in corner?
