### ISSUE TITLE
downloaded chapters are duplicating or not saving correctly

### ISSUE THREAD

**Issue by zlehnherr** [tachiyomiorg/tachiyomi#6664]
### Steps to reproduce

Not sure how to reproduce.

### Expected behavior

When downloading chapters, each chapter should be downloaded once.

### Actual behavior

Seems some temp files were downloaded and kept or chapters somehow duplicated.
![SmartSelect_20220216-223156_My Files](https://user-images.githubusercontent.com/49818283/154407051-ce1afab9-d755-47db-806c-4683d99ef908.jpg)
![SmartSelect_20220216-223218_Tachiyomi](https://user-images.githubusercontent.com/49818283/154407054-e6b6c0dd-ae7f-4754-b893-a064c250b5e7.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 12 One UI 4.0

### Device

Samsung Tab S7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by irfanshadikofficial** [comment]
having same issue, there's dowloaded files in my phones memory, and downloaded badges are showing too, but inside the manga there's no downloaded icon (maybe not connected properly to files). so cant use in offline.

**Comment by arkon** [comment]
Newer versions filter out tmp folders from the badges and the download cache is reworked.
