### ISSUE TITLE
Manga with same name from same source download to 1 folder, throwing off download counter

### ISSUE THREAD

**Issue by zlehnherr** [tachiyomiorg/tachiyomi#6665]
### Steps to reproduce

Webtoon may be a good source to use to recreate, such as the webtoon Clinic of Horrors.

### Expected behavior

Not sure what expected behavior should be. Maybe when 2 manga with same name are added to library, a second folder with same name is added with a number, such as "Clinic of Horrors" and "Clinic of Horrors (1)"

### Actual behavior

e chapters from both manga are downloaded to one folder causing download counter to not be accurate.
![SmartSelect_20220216-223301_Tachiyomi](https://user-images.githubusercontent.com/49818283/154407693-e38b1baa-d8a2-4d1c-b28c-a30c01ac3d53.jpg)
![Screenshot_20220216-225303_My Files](https://user-images.githubusercontent.com/49818283/154407831-c219d5a4-0511-4224-8aff-f313b612125e.jpg)
![Screenshot_20220216-225255_My Files](https://user-images.githubusercontent.com/49818283/154407845-502c0c7c-c3ec-4e98-996b-1d3f96eab5ef.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Samsung Tab S7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This has come up before, but it's a very rare case. We have strong expectations that entries are unique within a source and the extension should ideally be able to differentiate their names in some way.

Please open an issue in the extensions repo so that the Webtoons source is made to differentiate those somehow.
