### ISSUE TITLE
Western Comic trackers

### ISSUE THREAD

**Issue by The-Complex** [tachiyomiorg/tachiyomi#6667]
### Describe your suggested feature

Add Western comic trackers like Goodreads, league of comic geeks.
Adding the best comic tracker would be great

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Goodreads: #4023
LeagueOfComicGeeks: #2356
