### ISSUE TITLE
No pages found

### ISSUE THREAD

**Issue by Kunshu131** [tachiyomiorg/tachiyomi#6670]
### Steps to reproduce

I wanted to read fantastic four (1961) from the read comic online extension i can download or read the 1st issue but when i want to download or read directly the rest almost the 600 pther issues i get an error with no pages found

### Expected behavior

I should be able to download it without a problem

### Actual behavior

It gave no pages found

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Galaxy A 30s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
