### ISSUE TITLE
Chapters/pages not Found

### ISSUE THREAD

**Issue by krae93** [tachiyomiorg/tachiyomi#6672]
### Steps to reproduce

When opening or attempting to open a new/updated chapter I get a no pages error for any and all extensions and sources. Does work in website mode but not through app.

### Expected behavior

Go to  download chapter and then open to read. 

### Actual behavior

Uploading Screen_Recording_20220218-002420_Tachiyomi.mp4…

### Crash logs

--------- beginning of main
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-17 23:07:27.912  7318  9972 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:920)
02-17 23:15:50.086  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:25:40.448  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:25:45.746  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:25:54.207  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:25:56.650  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:27:47.708  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:32:39.677  7318  7318 E ViewRootImpl: sendUserActionEvent() mView returned.
02-17 23:32:51.124  7318  7318 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:34:47.604 19126 19126 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:34:47.606 19126 19126 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:34:48.055 19126 19126 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:34:48.294 19126 19223 E SQLiteLog: (284) automatic index on C(manga_id)
02-17 23:34:48.294 19126 19223 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-17 23:54:25.128 23637 23637 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:54:25.130 23637 23637 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:54:25.446 23637 23637 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:54:38.437 23813 23813 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:54:38.439 23813 23813 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:54:38.626 23813 23813 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:54:42.464 23914 23914 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:54:42.467 23914 23914 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:54:43.117 23914 23914 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:55:08.354 24083 24083 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:55:08.362 24083 24083 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:55:08.682 24083 24083 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:55:08.805 24083 24163 E SQLiteLog: (284) automatic index on C(manga_id)
02-17 23:55:08.805 24083 24163 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-17 23:59:03.902 25717 25717 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:59:03.904 25717 25717 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:59:04.372 25717 25717 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:59:07.139 25845 25845 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-17 23:59:07.140 25845 25845 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-17 23:59:07.496 25845 25845 E anade.tachiyom: Invalid ID 0x00000000.
02-17 23:59:07.626 25845 25923 E SQLiteLog: (284) automatic index on C(manga_id)
02-17 23:59:07.626 25845 25923 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-18 00:01:36.495 25845 27615 E Surface : freeAllBuffers: 8 buffers were freed while being dequeued!
02-18 00:01:36.498 25845 27574 E Surface : freeAllBuffers: 10 buffers were freed while being dequeued!
02-18 00:02:02.454 27858 27858 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:02:02.456 27858 27858 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:02:02.676 27858 27858 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:02:07.278 27967 27967 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:02:07.279 27967 27967 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:02:07.586 27967 27967 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:02:07.709 27967 28029 E SQLiteLog: (284) automatic index on C(manga_id)
02-18 00:02:07.709 27967 28029 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-18 00:02:17.472 27967 28445 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
02-18 00:02:27.653 27967 28527 E Surface : freeAllBuffers: 11 buffers were freed while being dequeued!
02-18 00:02:47.431 28639 28639 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:02:47.448 28639 28639 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:02:47.958 28639 28639 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:02:50.177 28711 28711 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:02:50.179 28711 28711 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:02:50.471 28711 28711 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:02:50.590 28711 28775 E SQLiteLog: (284) automatic index on C(manga_id)
02-18 00:02:50.590 28711 28775 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-18 00:02:58.831 28711 28943 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
02-18 00:02:58.831 28711 28940 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
02-18 00:02:58.831 28711 28943 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
02-18 00:02:58.831 28711 28940 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
02-18 00:04:03.344 29297 29297 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:04:03.350 29297 29297 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:04:03.981 29297 29297 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:11:08.300 30318 30318 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-18 00:11:08.303 30318 30318 E USNET   : USNET: appName: eu.kanade.tachiyomi
02-18 00:11:08.714 30318 30318 E anade.tachiyom: Invalid ID 0x00000000.
02-18 00:11:08.907 30318 30398 E SQLiteLog: (284) automatic index on C(manga_id)
02-18 00:11:08.907 30318 30398 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G970USQU6HULD
Device brand: samsung
Device manufacturer: samsung
Device name: beyond0q
Device model: SM-G970U
Device product name: beyond0qltesq

### Tachiyomi version

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G970USQU6HULD Device brand: samsung Device manufacturer: samsung Device name: beyond0q Device model: SM-G970U Device product name: beyond0qltesq

### Android version

Android 12

### Device

Galaxy s10e 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

> I have tried the troubleshooting guide.
