### ISSUE TITLE
Treemanga not working

### ISSUE THREAD

**Issue by allishona** [tachiyomiorg/tachiyomi#6674]
### Steps to reproduce

When opening new chapter, it will show loading then will show "Retry". I will try to download the chapter and it will say "Error Downloading".

### Expected behavior

It should open the new chapter and load it successfully. 

### Actual behavior

Just starte a loading bar and then shows "Retry".

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

S21 Ultra

### Other details

![Screenshot_20220218-002415_Tachiyomi](https://user-images.githubusercontent.com/84158024/154646230-0100ddb3-8ad2-4526-97d8-72f16e0be37e.jpg)
![Screenshot_20220218-002403_Tachiyomi](https://user-images.githubusercontent.com/84158024/154646250-6914cc41-c501-4d0f-9f54-478e9a525a1c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by allishona** [comment]
Mangaowl and Batoto works fine. Only Treemanga is doing this unusual behavior.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please actually read and follow what you acknowledge instead of just checking the boxes.
