### ISSUE TITLE
Sub-page tap navigation toggle

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#6676]
### Describe your suggested feature

One of the recent changes was adding sub-page tap navigation. I always need to zoom in a little to read manga, and it's better to keep my finger on to scroll the page. But now, when I click to go to the next page, I only jump to the end of it. (using it as intended isn't good in my case, since I go back and forth a lot)

Since you added this feature obviously you wanted it, but it can be a hassle sometimes. Hence, a toggle defaulting to sub-page navigation works just fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's already a toggle. Did you try turning it off?

**Comment by hyoretsu** [comment]
Oh, it's "navigate to pan", my bad.
