### ISSUE TITLE
startup splash on Xiaomi phones with dark mode enabled shows as dark circle briefly during initial load

### ISSUE THREAD

**Issue by SudosFTW** [tachiyomiorg/tachiyomi#6678]
### Steps to reproduce

Set any Xiaomi MIUI based phone into dark mode in Settings > Display. 

### Expected behavior

Logo should consistently show throughout the entire app startup process.

### Actual behavior

For the first few seconds, the logo is covered by a dark circle, but can be briefly seen when the app is handed over screen drawing from the splash before loading the library etc. As set up by the user.

### Tachiyomi version

0.13.1

### Android version

Android 11, MIUI 12.5.5 Stable

### Device

Xiaomi Poco M3

### Other details

This has to do with how MIUI does dark mode compared to other android variants. Essentially it inverts white to black on all interfaces. Under 12.5.5 there are additional dark mode options that can be switched off per app, and Tachiyomi has the slider switched off so text does not become unreadable. The same happens with the slider switched on.

Image of unexpected behavior:
![Screenshot_2022-02-19-09-18-23-924_eu kanade tachiyomi](https://user-images.githubusercontent.com/11806373/154805123-d3de62d7-de05-48b7-ad34-65865e2e0798.jpg)

This might be able to be fixed in the app for how it draws the startup splash screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This isn't fixable by the app. It needs to be addressed by Google and/or Xiaomi.

**Comment by CVIUS** [comment]
Just have to wait for this https://github.com/androidx/androidx/pull/327 or overwrite it if you can't wait
