### ISSUE TITLE
Enhance: Rewording/Tweaking of (Notification/Error Log)

### ISSUE THREAD

**Issue by Mano5JP** [tachiyomiorg/tachiyomi#6685]
### Describe your suggested feature

We now have a skipped series included in the error log with the release of r4170. Error log is no longer a stand-alone error log.

So, we could have like,

1. On Notification Panel
   X Update(s) failed, and X Update(s) Skipped
2. Inside Log
   Show X Update(s) Failed at Top, and X Update(s) Skipped at Bottom.

### Other details

This is how it currently appears.

| Notification | Log Info | 
| --------------- | --------------- | 
| ![Tachiyomi](https://user-images.githubusercontent.com/64928088/154908272-4dc7decd-e122-4555-859c-f2051bcf84ed.png) | ![tachiyomi_update_errors](https://user-images.githubusercontent.com/64928088/154908591-b78505e8-dd2f-4ff9-b044-6872a6cc49e8.png) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6722#issuecomment-1057331761
