### ISSUE TITLE
Crash when trying to  use deleted source

### ISSUE THREAD

**Issue by dangB99** [tachiyomiorg/tachiyomi#6689]
### Steps to reproduce

-Download any extention
-Use it so that it appears in Browse>>Sources under "Last Used"
-Uninstall the extention
-Go Browse>>Sources under "Last used" then click it
Immediate crash

### Expected behavior

I expected it not to crash, it should be cleared from "Last used" upon deletion.

### Actual behavior

It crashes,Then its cleared form "Last used" by the time you open the app again.

### Crash logs

--------- beginning of crash
02-22 08:43:28.354 17607 17607 E AndroidRuntime: FATAL EXCEPTION: main
02-22 08:43:28.354 17607 17607 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 17607
02-22 08:43:28.354 17607 17607 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property source has not been initialized
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.getSource(BrowseSourcePresenter.kt:1)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.getTitle(BrowseSourceController.kt:1)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle(BaseController.kt:4)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle$default(BaseController.kt:1)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.onChangeStarted(BaseController.kt:2)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.changeStarted(Controller.java:5)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:18)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:29)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.pushController(Router.java:4)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.openSource(SourceController.kt:3)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:4)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:1)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:5)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.view.View.performClick(View.java:7156)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7129)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.view.View.access$3500(View.java:803)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27543)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7605)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-22 08:43:28.354 17607 17607 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
--------- beginning of main
02-22 09:07:10.300 19990 19990 E         : [onConstructor]: an error ged handle
02-22 09:07:10.307 19990 20018 E         : appName=eu.kanade.tachiyomi, acAppName=/system/bin/surfaceflinger
02-22 09:07:10.307 19990 20018 E         : 0
02-22 09:07:10.668 19990 23316 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.668 19990 23319 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 20086 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 20085 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 23317 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 23318 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 20082 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:10.669 19990 20079 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:14.411 19990 23323 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:14.752 19990 23323 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:14.771 19990 23323 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:07:14.780 19990 20086 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:05.001 19990 20086 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:10.247 19990 19990 E AndroidRuntime: FATAL EXCEPTION: main
02-22 09:11:10.247 19990 19990 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 19990
02-22 09:11:10.247 19990 19990 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property source has not been initialized
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.getSource(BrowseSourcePresenter.kt:1)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.getTitle(BrowseSourceController.kt:1)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle(BaseController.kt:4)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle$default(BaseController.kt:1)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.onChangeStarted(BaseController.kt:2)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.changeStarted(Controller.java:5)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:18)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:29)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.pushController(Router.java:4)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.openSource(SourceController.kt:3)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:4)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:1)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:5)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.view.View.performClick(View.java:7156)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7129)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.view.View.access$3500(View.java:803)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27543)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7605)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-22 09:11:10.247 19990 19990 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
02-22 09:11:10.272 19990 19990 E ACRA    : ACRA caught a UninitializedPropertyAccessException for eu.kanade.tachiyomi
02-22 09:11:10.272 19990 19990 E ACRA    : kotlin.UninitializedPropertyAccessException: lateinit property source has not been initialized
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.getSource(BrowseSourcePresenter.kt:1)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.getTitle(BrowseSourceController.kt:1)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle(BaseController.kt:4)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.setTitle$default(BaseController.kt:1)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.controller.BaseController.onChangeStarted(BaseController.kt:2)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.bluelinelabs.conductor.Controller.changeStarted(Controller.java:5)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:18)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:29)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.bluelinelabs.conductor.Router.pushController(Router.java:4)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.openSource(SourceController.kt:3)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:4)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.SourceController.onItemClick(SourceController.kt:1)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:5)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.view.View.performClick(View.java:7156)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.view.View.performClickInternal(View.java:7129)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.view.View.access$3500(View.java:803)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.view.View$PerformClick.run(View.java:27543)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:883)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.os.Looper.loop(Looper.java:264)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7605)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-22 09:11:10.272 19990 19990 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
02-22 09:11:57.117 23681 23681 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-22 09:11:58.753 23681 23728 E SQLiteLog: (284) automatic index on C(manga_id)
02-22 09:11:58.753 23681 23728 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-22 09:11:58.771 23681 23681 E libc    : Access denied finding property "ro.vendor.scaler_version"
02-22 09:11:58.773 23681 23681 E libc    : Access denied finding property "ro.vendor.scaler_version"
02-22 09:11:58.890 23681 23681 E         : [onConstructor]: an error ged handle
02-22 09:11:58.904 23681 23709 E         : appName=eu.kanade.tachiyomi, acAppName=/system/bin/surfaceflinger
02-22 09:11:58.905 23681 23709 E         : 0
02-22 09:11:59.214 23681 23734 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.214 23681 23743 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.214 23681 23744 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.214 23681 23745 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.215 23681 23736 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.215 23681 23746 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.215 23681 23747 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:11:59.215 23681 23735 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:01.451 23681 23750 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:01.460 23681 23743 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:01.463 23681 23748 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:01.472 23681 23751 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:01.475 23681 23747 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-22 09:12:42.855 23681 23681 E         : [onConstructor]: an error ged handle
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 10 (SDK 29)
Android build ID: X657-H8030A-QGo-OP-211001V577
Device brand: Infinix
Device manufacturer: INFINIX MOBILITY LIMITED
Device name: Infinix-X657
Device model: Infinix X657
Device product name: X657-OP

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

Infinix X657

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Conveniently handled by #6987
