### ISSUE TITLE
Missing Chapters

### ISSUE THREAD

**Issue by einstein591** [tachiyomiorg/tachiyomi#6693]
### Steps to reproduce

I am using the MangaPark extension and I look up "Naruto: The Seventh Hokage and the Scarlet Spring" (link: https://v2.mangapark.net/manga/naruto-the-seventh-hokage-and-the-scarlet-spring).

### Expected behavior

I should be seeing all ten chapters from the website on the app.

### Actual behavior

I only see the first chapter on the app.

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

Motorola Moto E

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
