### ISSUE TITLE
Cannot delete read chapters

### ISSUE THREAD

**Issue by jasontbright** [tachiyomiorg/tachiyomi#6694]
### Steps to reproduce

1.  CBR save on SD card
2. Download chapter
3. Read chapter
4. Attempt to delete chapter in view

Note: can delete unread chapters, and can delete chapters previously marked read by first marking them unread, or by deleting all chapters in library view.

Looks almost like an attempt to protect u read chapters from deletion was reversed?

### Expected behavior

Chapter(s) should be deleted

### Actual behavior

Chapter(s) are not deleted.  Note: I am aware that deletions are not instant.  I waited a day to see if it worked.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Galaxy Tab A7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jasontbright** [comment]
More details- happens when folder is set in exemption for auto-deletion of read chapters, even if auto-deletion is off.  If I remove the folder from the exemption, behavior is as expected.

**Comment by arkon** [comment]
I don't think this happens anymore?
