### ISSUE TITLE
Mass update of manga/comic wont work

### ISSUE THREAD

**Issue by LandChit** [tachiyomiorg/tachiyomi#6696]
### Steps to reproduce

N/A

### Expected behavior

when reloading in the update tab it should update all

### Actual behavior

just updates a few of them

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Poco X3 GT

### Other details

when updated individually it works fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Read the changelog but also explained here #6599
