### ISSUE TITLE
chapter size in chapters list add function

### ISSUE THREAD

**Issue by mekodke** [tachiyomiorg/tachiyomi#6697]
### Describe your suggested feature

Please add the size of the chapters beside it in the chapters list.... If it can't be done for the undownloaded chapters then please **add it to the chapters that are downloaded** and you can also make it like images "not recalculated every time you open the chapters list of a manga"
And thank you, thank you again for the awesome updates... 🌹🌸

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
for the undownloaded.
https://github.com/tachiyomiorg/tachiyomi/issues/3132

as for downloaded this isn't a file browser, I don't see the benefit of showing the downloaded chapter size.  Plus there is barely any room as is on that row
