### ISSUE TITLE
Navbar text bigger than last preview

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6705]
### Steps to reproduce

Open app

### Expected behavior

Same font size as stable / last preview
![Screenshot_20220227-122727](https://user-images.githubusercontent.com/63973749/155868585-4a9d2b3b-038c-4801-9a85-67acda6ffcf8.png)

### Actual behavior

![Screenshot_20220227-122735](https://user-images.githubusercontent.com/63973749/155868554-85ab8f25-dd3e-49ce-8a79-7e4af665049c.png)

### Tachiyomi version

r4174

### Android version

A11

### Device

Redmi Note 9 Pro (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's just the new default in Material Components.
