### ISSUE TITLE
Add more info for tooltips with badges

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#6708]
### Describe your suggested feature

Like Gmail. Just a very small QoL. For Updates nav item, Browse nav item, and Browse > Extensions tab.

![Screenshot_20220227-220112](https://user-images.githubusercontent.com/63973749/155886387-fc7da622-dfac-44b9-a165-1905f9bb3c42.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is eventually going to be replaced with Compose which doesn't even have proper tooltip support yet.
