### ISSUE TITLE
App date logger not lining up with system time

### ISSUE THREAD

**Issue by HSO-FHertzke** [tachiyomiorg/tachiyomi#6709]
### Steps to reproduce

Look at any date while in New Zealand timezone and it will say yesterday. S22 ultra 

### Expected behavior

Events that happened today should say "today"

### Actual behavior

Events that happened today say "yesterday"

### Tachiyomi version

0.13.q

### Android version

Android 12

### Device

Samsung galaxy s22 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by RegexMC** [comment]
Device: Google Pixel 5
App version: 0.13.1

Issue occuring in Australia, AEDT timezone (at least in the updates page)

Upon refreshing library and new manga being updated, it shows _Yesterday_ in the updates section, but _Today_ in the manga itself.
screenshots attached show this happening but offset by a day as I have no new updated manga today

Unsure of when this started occuring but I believe it was the latest or one of the latest updates that caused this. 
![Screenshot_20220306-110802](https://user-images.githubusercontent.com/56909681/156903858-649bbd24-63c5-404b-a9b0-7871608c6889.png)
![Screenshot_20220306-110754](https://user-images.githubusercontent.com/56909681/156903860-e4282889-d90c-4b12-9708-19058be77ec0.png)

**Comment by FourTOne5** [comment]
For clarification:
In Updates tab the time refers to when the chapter was added to the library aka library update time.
On the other hand the time on the chapter list indicates the time the source has provided.

So you can even come to a situation where updates tab shows yesterday while the chapter list shows a time a week ago.
In my opinion it should stay the way it is.

**Comment by arkon** [comment]
What @FourTOne5 said is probably the case. If you can confirm that it's not, please reopen this or a new issue.
