### ISSUE TITLE
Scheduled library update at specific day and time

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#6712]
### Describe your suggested feature

Giving starting time, auto library updates happen for given period after that specific time and not after latest update. For example:

For daily updates, instead of update every 24 hours after last update, update at a specific time.
![timepicker-custom-element-10](https://user-images.githubusercontent.com/35896230/156113514-8a3503af-9a75-4c05-8691-3eff5e06eb54.gif)

### Other details

Its specially useful for people like me who plan to reading weekly and in holidays but might have there schedule messed up by in week updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
You can pseudo do it by changing your update frequency when you want it to update and changing it back. However it'll veer slowly away from it because of how android does things. Also, #1254
