### ISSUE TITLE
Use the chapters's filter globally

### ISSUE THREAD

**Issue by Jeluxe** [tachiyomiorg/tachiyomi#6713]
### Describe your suggested feature

As mentioned in the title, right now we are only able to use the chapter filter only within manga page and will only applied on her and only her, so in addition to filter that being applied only on one manga, so there will be a possibility to apply it to all the manga. For example: the filter that filtering all the chapters that were read, so it will be possible to filter it for all the manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Set it as the default from the overflow menu in the sheet.
