### ISSUE TITLE
App not opening or registering chapters after downloading and restarting

### ISSUE THREAD

**Issue by Tolu456** [tachiyomiorg/tachiyomi#6714]
### Steps to reproduce

Hello, I am on version 0.13.1
I have the app on boox note air 2 and the problem is that whenever I download a chapter, it gets downloaded and I can see the images in the system storage folder but when I turn off the internet I can't access the files offline
when I try to open it, I just get the error that its trying to access it online, even though I've already downloaded it

### Expected behavior

When I download a file on a phone, I am able to open it after turning off internet

### Actual behavior

when I try to open it, I just get the error that its trying to access it online, even though I've already downloaded it
if I close the app and open it again the button that shows it's downloaded reverts back to the non- downloaded one and if I try to re-download it again it shows a question mark.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8164070/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.1

### Android version

android 11

### Device

Boox note air 2 e-ink tablet

### Other details

I have enabled all permissions and file access and also disabled all power management and background app limiting on the app  
since it is on android 11 I attempted setting up ADB and running the command on the main website but it made no difference
the app is running on main storage, no SD card involved
I regularly use 10 extensions, mangakakalot, mangafreak, mangasee, webnovel etc. and the problem is the same when downloading on all extensions
I can find the files in the internal storage, I can open the pictures and read them, so they are not corrupted or anything either
the folder name is the same default one that I see on my phone
after restarting the app and device it still does not work
I have also tried moving random files to Tachiyomi/Local/Manga-Name/Ch-name but they do not show up either , they appear in the local source as readable
I am also not using the cbr setting
I am able to provide screen recording, device log files and any other thing if necessary

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is this still happening with newer versions?
