### ISSUE TITLE
Last update error badge on Manga cover in library 

### ISSUE THREAD

**Issue by T3sT3ro** [tachiyomiorg/tachiyomi#6715]
### Describe your suggested feature

It is difficult to cycle between textual log and library whenever some mangas fail to update. It could be good to add warning and/or error badges displayed directly on a Manga cover in library (e.g. Red triangle with exclamation mark) indicating that "last update for this Manga failed". It could look similar to attached picture. Upon longer tap it would show (besides the context action buttons) also a toast/error box with message. Aside from that a filter for "mangas that failed" could be added to library to help resolving problems easily.

This would be very helpful in detecting that some mangas stall because they fail with, for example, URL change.
![Screenshot_20220302_015130](https://user-images.githubusercontent.com/5300963/156274383-1946dc87-38fa-44e3-830c-fe2ce41b6e77.jpg)

### Other details

Semi-relates to #4616 and #4558

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #4616, which ought to be a list/section with Updates or something.
