### ISSUE TITLE
Asking to update my library does not check every Manga

### ISSUE THREAD

**Issue by mauricioszabo** [tachiyomiorg/tachiyomi#6716]
### Steps to reproduce

1. On the updates tab, or library, pull down until I see the icon to update
2. Updating appears on notification tab, but shows "updating 1/8" and I have about 20 Mangas on my library
3. Check that I have new updates that were not included in the check by going to individual Mangas and pulling down to update only that title

### Expected behavior

Should try to update all Mangas on my library

### Actual behavior

Only updates or check for update 8 Mangas. Can not pinpoint which ones 

### Tachiyomi version

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 9 (SDK 28) Android build ID: PPR1.180610.011.J730GUBUDCUD3 Device brand: samsung Device manufacturer: samsung Device name: j7y17lte Device model: SM-J730G Device product name: j7y17lteub

### Android version

Android 9

### Device

Samsung J7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #6599
