### ISSUE TITLE
Toggle manga language for language learners

### ISSUE THREAD

**Issue by carlospazuzu** [tachiyomiorg/tachiyomi#6717]
### Describe your suggested feature

As a language learner, I like to challenge myself by trying to read a manga in my target language for immersion and toggling back to my mother language to understand it properly. The problem is: it take a huge effort to go back and forth from one source to another. It would be awesome to do a double tap and toggle from one language to another. I would gladly help if someone instruct me what to do.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This app is geared for reading and not learning.   As Tachiyomi is just a glorified web browser to existing sites it would take a lot of magic to even get this even in a passable state.
