### ISSUE TITLE
Error notification appears because of skipped manga.

### ISSUE THREAD

**Issue by Grumsle** [tachiyomiorg/tachiyomi#6722]
### Steps to reproduce

Install preview r4170 or later and refresh a library that contains manga which fulfill the criteria to be skipped.

### Expected behavior

There should be no error notification if there are no errors, I'd assume.

### Actual behavior

You'll receive an error notification despite it saying 0 updates failed.

### Tachiyomi version

Preview r4170 and r4174.

### Android version

Android 10 and 12.

### Device

Huawei P40 Pro and Samsung Galaxy Tab 7+.

### Other details

![Screenshot_20220302_204339](https://user-images.githubusercontent.com/100799496/156439425-55ac47eb-88a6-43cb-8fad-a3c6f4316e9b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I do plan on splitting it into 2 notifications so you can turn them off individually if desired.
