### ISSUE TITLE
Add progress bar when forcing library update 

### ISSUE THREAD

**Issue by Mirimes** [tachiyomiorg/tachiyomi#6724]
### Describe your suggested feature

Loving the app, and i think this could be a little good improvement: currently if i go to the "last updates" tab and force the library update I can't see an indication that says when it's done doing it, i always need to check through all the notifications, could be an improvement seeing when it's done so i know there's no new chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The progress notification is the ideal place to have this info considering it's "global" and you don't need to stay in the updates screen.
