### ISSUE TITLE
Mangasusu have a problem

### ISSUE THREAD

**Issue by ADHIRAxKURUMI** [tachiyomiorg/tachiyomi#6727]
### Steps to reproduce

![Screenshot_2022-03-03-14-21-17-39_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/100504533/156525956-ede72bfc-57eb-4c8c-abf8-d3bdd0e9c08b.jpg)
that's a picture of the problem I'm having, can you fix it?
For Web view there is no problem, the problem is as pictured, I prefer to see it through the application than through the web view
The domain is correct no problem

### Expected behavior

I hope this problem can be solved because I'm not the only one experiencing this,My friend also experienced it

### Actual behavior

Hope it gets fixed soon

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Realme c15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment]
this looks like https://github.com/tachiyomiorg/tachiyomi-extensions ?
