### ISSUE TITLE
Tachiyomi force closed when searching in manga source

### ISSUE THREAD

**Issue by JunkCreekG** [tachiyomiorg/tachiyomi#6730]
### Steps to reproduce

1. Opened manga source
2. Typing in search field, click search
3. The app begin searching 

### Expected behavior

Showing search result

### Actual behavior

Tachiyomi suddenly closed 

### Crash logs

![Screenshot_2022-03-04-01-13-49-932_com ss squarehome2](https://user-images.githubusercontent.com/100869490/156626569-421e459b-062b-426c-b3dc-9bfdb32c83b0.png)
![Screenshot_2022-03-04-01-13-53-268_com miui bugreport](https://user-images.githubusercontent.com/100869490/156626612-1ab5b456-9a9c-4091-9278-041b8c176c1e.png)

### Tachiyomi version

0.13.1

### Android version

6

### Device

Xiaomi Redmi Note 4 Nikel

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JunkCreekG** [comment]
> Be more specific and tell what source it is.

It only happen when I do search with all installed source extension.

When I search using only pinned source it never happens.

I'd try to narrowed it down.

**Comment by DanielBragaMelo** [comment]
I have the same issue. It happens when doing a global search in all extensions. If a search is done in a specific extension, it works normaly.

**Comment by CrepeTF** [comment]
If you have any obsolete extensions; delete them then try searching

**Comment by DanielBragaMelo** [comment]
> If you have any obsolete extensions; delete them then try searching

Worked for me. Thanks!
