### ISSUE TITLE
Update all button for extensions

### ISSUE THREAD

**Issue by Hidlsh** [tachiyomiorg/tachiyomi#6732]
### Describe your suggested feature

an Update All Button on the extensions page: not simultaneously updating all your extensions at the same time, but automatically collapses them all in alphabetical order for you to press one at a time

Usually when multiple of my installed extensions have updates, i try and press "Update" on as much of them as possible before the update pop-up window shows. It would be much more convenient to have them all automatically be "clicked"? so then i can manually press update on them faster through there. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Just use shizuku

https://tachiyomi.org/help/faq/#what-is-shizuku

**Comment by CrepeTF** [comment]
Not sure why'd you would want to play this game of tapping all the update prompts

**Comment by arkon** [comment]
This already exists if you're not using the legacy installer in 0.13.1.
