### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by EDarkzz** [tachiyomiorg/tachiyomi#6733]
### Steps to reproduce

My backup file doesn't work I tried changing the proto.gz to .json still didn't work pls help

tachiyomi_2022-03-04_12-47.proto

### Expected behavior

Getting my old Libra back

### Actual behavior

Getting a text saying invalid backup file

### Crash logs

![Screenshot_20220304_190849](https://user-images.githubusercontent.com/100927107/156752840-d63bec22-111c-4d16-9f2b-eb119115de2b.jpg)

### Tachiyomi version

0.13.0

### Android version

8.1.0

### Device

Vivo y81

### Other details

I switched from old ver to newest version I forgot what ver the old one is

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Looks like you have a .proto file. 
Tachiyomi needs backups to be .proto.gz file. gz is a compressed file like zip
So you need to convert back your .proto file to a .proto.gz file and restore using that
You can try an app like ZArchiver or others to compress files

**Comment by CarlosEsco** [comment]
How did you even get a proto backup?

**Comment by EDarkzz** [comment]
> Looks like you have a .proto file. Tachiyomi needs backups to be .proto.gz file. gz is a compressed file like zip So you need to convert back your .proto file to a .proto.gz file and restore using that You can try an app like ZArchiver or others to compress files

I did it still says the same thing saying .json or something

**Comment by EDarkzz** [comment]
> How did you even get a proto backup?

Uhmmm...

**Comment by arkon** [comment]
GitHub is for actual bug reports.

If you need help, please ask on Discord. You likely just need to gzip your protobuf file again as curche mentioned.

Please don't mess with the backup files if you intend on using them with the app still.

**Comment by EDarkzz** [comment]
> 

I already did it still doesn't work is says tachiyomi_2022-03-04_12-47.proto.gz. but ok imma ask discord
