### ISSUE TITLE
Trackers: set start date based on reading history

### ISSUE THREAD

**Issue by Mano5JP** [tachiyomiorg/tachiyomi#6734]
### Describe your suggested feature

The start date should be:

- If already set from the tracker, remains the same
- If not set:
  - If there's already read chapters, use the oldest date from reading history
  - If reading chapters for the first time later, should set the start date

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourThousands** [comment]
That's an excellent idea. I've found this feature request when I searched for it before creating new issue for it.

**Comment by THElegend5** [comment]
I have also noticed that this seems to happens only when you read more than one chapter in a go, and the start date gets added just fine if you read the first chapter and exit. But am not completely sure so it would be nice if someone can confirm this.

**Comment by peepincreepin** [comment]
@arkon it seems multiple tickets have been merged into one here. However most of them are reporting a bug with the tracker, whereas the original is dealing with a feature request. Does this mean then that fixing the reported bug is being deprioritised because it's hidden within a feature improvement ticket?

**Comment by arkon** [comment]
There aren't really any priorities anyway, I'm not sure it matters.

**Comment by peepincreepin** [comment]
Okok gotcha, thank you.
