### ISSUE TITLE
Manga Download 

### ISSUE THREAD

**Issue by bonechan3** [tachiyomiorg/tachiyomi#6735]
### Describe your suggested feature

When you download a manga, its pages appear in the files
It is better that the manga pages appear inside the application only

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-can-i-see-manga-pages-from-my-downloads-in-my-device-s-photo-gallery
