### ISSUE TITLE
F-droid repo server

### ISSUE THREAD

**Issue by grrrrr** [tachiyomiorg/tachiyomi#6736]
### Describe your suggested feature

I know from #5891 that Tachiyomi will not be made available by F-Droid due to DMCA filings and as a result the only way to do the initiall install is to side-load via downloading the apk from the website.

Would you consider hosting your own F-Droid repo which could be used for distributing the app?

There is a [setup guide](https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/) on the f-droid website

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Nope no plans to

**Comment by arkon** [comment]
This question has come up a few times before, so I might as well better document the reasoning as to why we don't want to do this.

From my perspective (feel free to correct me if I'm wrong), F-Droid offers the following value-adds for users:

- Some vague promise that apps are "free" (e.g., open-source)
- Better surfacing some "anti-user" aspects (e.g., tracking)
- Centralizing app updates similar to other app stores

On the Tachiyomi side:

- We are indeed open-source, so not much to really talk about there.
- We do have some level of logging/analytics that are covered in [the privacy policy](https://tachiyomi.org/privacy/), but users are free to compile their own versions without them. The old F-Droid versions also included some level of this, which F-Droid does not prevent.
- The app manages updates by itself.

Furthermore, most users are unaware of what F-Droid is nor how to use it (especially if you need to use a third-party repo, which then removes any guarantee of the first two benefits that I listed). In either case, you're side loading apps, but at least GitHub acts more as a source of truth/mark of authenticity.

It simply doesn't seem worth it to maintain an F-Droid repo purely for Tachiyomi.

**Comment by grrrrr** [comment]
makes sense @arkon, thanks for clarifying    

> This question has come up a few times before

Sorry I did look but only say tickets about having it on the official f-droid repo.   My main reason was that if tachiyomi had it's own repo it would not be beholden to f-droid requirements, e,g. you could keep the trackers in if you wanted, heck you could use it to distribute closed source apk if you really wanted.    

But as you said most users don't know about f-droid, so it'd possibly just be looking after an extra element for a few

**Comment by arkon** [comment]
No worries, I was referring to some past conversations on Discord.
