### ISSUE TITLE
Can download only bookmarked chapter

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#6738]
### Describe your suggested feature

please add feature to download "bookmark only" chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Bookmarks are generally not a feature we work with much, so this seems too niche to focus on. Simple workaround would just be to filter chapters by bookmarked, then select all to download.
