### ISSUE TITLE
2 minor issues

### ISSUE THREAD

**Issue by kucingkembar** [tachiyomiorg/tachiyomi#6740]
### Describe your suggested feature

hi, sorry for my bad English,
I have 2 minor issues,
1.  when I read using the smartphone, I do like this:
![ezgif-1-8a90ab2366](https://user-images.githubusercontent.com/47294266/156897328-b19bd967-b270-40e3-95a9-3314bb649c2a.gif)
with slide direction like this:
![Screenshot_2022-03-06-02-15-53-025_eu kanade tachiyomi](https://user-images.githubusercontent.com/47294266/156897334-0075898d-bea9-4d9a-9d71-55d6fff8a27b.png)
the problem is: sometimes the UI appears like this:
![Screenshot_2022-03-06-02-16-01-815_eu kanade tachiyomi](https://user-images.githubusercontent.com/47294266/156897335-d7db8222-fe55-4079-8619-326820d087b1.png)
 and "accidentally" make the page "jump" to the end of the chapter,
 can you move that horizontal slider to the top instead of the bottom?

2. make auto refresh library tab when all download is complete,
this is very simple, I set my library view only "downloaded", and the library does not update/refresh when all chapter is downloaded, and I must open another tab and back to the library tab again to "offline" refresh the library page, or scroll  down the library page  to "online" the library page, please make auto refresh library tab when all download is complete,

thank you for the hard work, have a nice day

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. Stop tapping to bring up the menus if it's an issue for you.
2. Make a separate issue for this.
