### ISSUE TITLE
Backup folder getting deleted.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6741]
### Steps to reproduce

1. Be on a preview version older than r4183.
2. Set automatic backup to a backup folder ( don't know if it needs to be custom location or not , was custom in my case)
3. Make sure it has backups.
4. Update to preview version r4183.

### Expected behavior

Nothing happens to the backup folder.

### Actual behavior

Backup folder is deleted.

### Tachiyomi version

 0.13.1-4183 

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

It doesn't seem to be caused by anything external such as cloud backup as the ones I use hasn't happened happened for today yet , and one of them which was set to sync deletion on manual sync showed 5 deletions which is what I have set my backup to .
Also confirmed via discord that I am not the only one whose backup folder got deleted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
> * Set automatic backup to a backup folder ( don't know if it needs to be custom or not , was custom in my case)

Same thing on my device, which is not running any custom ROM 

r4183
Android 11
OnePlus 8

**Comment by THElegend5** [comment]
> > * Set automatic backup to a backup folder ( don't know if it needs to be custom or not , was custom in my case)
> 
> Same thing on my device, which is not running any custom ROM 
> 
> r4183
> Android 11
> OnePlus 8
> 
> 
> 
> 
> 
> 

Meant custom location , mb.
