### ISSUE TITLE
Phantom downloads in library

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6747]
### Steps to reproduce

Current download settings
Auto downloads: On
Auto deletes: 2 chapters after. 

### Expected behavior

Download count in library should match download count in the chapter viewer. Deleting all downloaded chapters by selecting all in chapter viewer (filters off or on downloads) should delete all downloaded chapters. If there are no chapters that appear in the downloaded filter in the chapter list, then the count in the library should be 0 (not appear)

### Actual behavior

Download count in library is higher. It appears even when there are no chapters downloaded. selecting all chapters in the chapter list and deleting the downloaded only deletes chapters that were shown to be downloaded correctly. The only way I have found to fix this is to select the title in the library and deleting all downloaded chapters from there, which seems to reset the count. 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Google Pixel 3

### Other details

I suspect auto-deletes/downloads may be the issue. I was told to look up "orphaned" in issues, and while i found similar issues, none seemed to be the issue. there may be some kind of misunderstanding about what these issues are on my part. Maybe #5845 (closed bug) or #1767 (FR for a tool to fix a similar problem) are related, but since it is in the current release, I suspect it isn't the closed issue, and I didn't start experiencing issues until last update or the one previous to that (at least that i noticed), so I suspect they are different. 
Better safe than sorry and create the issue just in case. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#1767 is meant to address orphaned downloads, which is what you described.
