### ISSUE TITLE
remove page transitions in right-to-left reading mode

### ISSUE THREAD

**Issue by srenk** [tachiyomiorg/tachiyomi#6749]
### Describe your suggested feature

remove page transitions in right-to-left reading mode / webtoon mode flat version / reading mode: continuous horizontal

### Other details

It's really annoying when reading manga in double pages that are separated by page transitions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
There is no continuous horizontal, which means you are probably using a fork and should open this on that github.  Plus there is already an option to disable the page transitions
