### ISSUE TITLE
[Local Manga] Can not set cover image

### ISSUE THREAD

**Issue by LastAi** [tachiyomiorg/tachiyomi#6751]
### Steps to reproduce

Add a manga to local that does not include a cover image.
In Tachiyomi browse the manga select a page, hold on screen wait for the options.
[Set as cover]
[Share]
[Save]

Select [Set as cover]
"Use this image as cover art?"
OK

the prompt 'Cover Set' breifly shows up 

### Expected behavior

The cover should be set in the Chapter Select or browse.

### Actual behavior

nothing is there, neither in the chapter select or in the browse.

### Tachiyomi version

Stable 0.13.1

### Android version

Android 12

### Device

Pixel 6

### Other details

This may be similar to issue #6737
but is not the same. Difference being that the cover IS NEVER set even after restart if the manga didn't have any cover.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Sunspark-007** [comment]
The issue might be due to the fact that the cover is created and saved, but on the internal storage instead of the sd card. The library entry still points to the sd card, so none is displayed.
