### ISSUE TITLE
Extension Accounts

### ISSUE THREAD

**Issue by Ihccato** [tachiyomiorg/tachiyomi#6752]
### Describe your suggested feature

Some extensions allow the user to have accounts is it possible for the user to be able to log in via the tachiyomi to access it? Could it work by adding a button for each source either in the app settings or going through each extension one by one to add on the browse page of the extension to open the browser to log in through that? Any way to keep it secure as well?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can typically log in via WebView. Otherwise, extensions can have explicit implementations for it.

**Comment by Ihccato** [comment]
And this log in provides updated information on the page or a way to download or update the library from it? Some extensions, have parts of their library locked behind logging in. Just asking if theres a way to view it or download it locally?

**Comment by arkon** [comment]
That's dependant on the particular website and extension.

There is no general solution to this.

**Comment by Ihccato** [comment]
Meaning? Theres no way to with tracking to store the log in information for it to communicate with the extension and allow access to download the manga? I figured tracking allows the app to communicate with the server and allow the app to when communicating to have access.

**Comment by arkon** [comment]
I'm very confused with your question. Is this a technical question or are you just trying to figure out how to use the app?

Did you try logging in to whatever the website in question is in WebView first and trying to refresh the chapters list?

**Comment by Ihccato** [comment]
No, just curious how it works if logging in does allow the app to access the library hidden behind logging in.
