### ISSUE TITLE
One question, will there be a guide on how to integrate a default extension into TachiyomiSY?

### ISSUE THREAD

**Issue by AUKUMA** [tachiyomiorg/tachiyomi#6757]
### Describe your suggested feature

hello
One question, will there be a guide on how to integrate a default extension into TachiyomiSY?

So when you install TachiyomiSY, a lectormanga extension is installed.
As well as e-henta

### Other details

hello
One question, will there be a guide on how to integrate a default extension into TachiyomiSY?

So when you install TachiyomiSY, a lectormanga extension is installed.
As well as e-henta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This isn't Tachiyomi SY repository. Please ask there instead.
