### ISSUE TITLE
Reading mode 'webtoon' issue

### ISSUE THREAD

**Issue by shiichan** [tachiyomiorg/tachiyomi#6759]
### Steps to reproduce

On the app 
Set reading mode to 'webtoon' view for seamless reading of webtoons and manga.

When setting the reader to webtoon view, webtoon chapters are now chunky instead of seamless, is there a way to correct it, the seams no longer match up causing seamless reading to become harder to read.

### Expected behavior

Pages are supposed to align and be seamless in webtoon mode

### Actual behavior

It doesn't match up or be seamless on webtoon view, cause the images and pages to misalign. And looks clunky

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung Galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably have crop borders enabled.

**Comment by shiichan** [comment]
Crop borders is disabled, and same issue

**Comment by CrepeTF** [comment]
could you provide an example you are using

**Comment by shiichan** [comment]
I'm on chapter 66 and between pages on webtoon reading mode used to be seamless page scrolling, this is happening on almost all webtoons on the app
![Screenshot_20220309-134859_Tachiyomi](https://user-images.githubusercontent.com/16157291/157522257-aa49ec30-23f0-4b8b-bbab-2553d54e2fe6.jpg)

**Comment by CrepeTF** [comment]
that is most definitely border cropping, the edges line up with the edge of the screen to well - try turning border cropping on and off if it off

**Comment by shiichan** [comment]
I... I am dumb 🤦🏻‍♀️ thank you
