### ISSUE TITLE
App won't update Manga

### ISSUE THREAD

**Issue by GeneticallyModifiedAlex** [tachiyomiorg/tachiyomi#6760]
### Steps to reproduce

1. Update Library.
2. Update initaiated

### Expected behavior

1. Update Library
2. Update complete
3. all manga are now updated or have been checked

### Actual behavior

1. Update Library.
2. Update initaiated and checks with 41/41 manga
3. Update closed
4. Updated 41 manga
5. The other 451 manga haven't been updated or registered as being present in app by the updater
6. The other manga are present, able to be read from source but will not update. (Sources vary)

### Crash logs

------- beginning of system
--------- beginning of main
03-09 22:27:05.822 32167 32167 E ResourceType: Style contains key with bad entry: 0x0101056c
03-09 22:27:05.851 32167 32167 E ResourceType: Style contains key with bad entry: 0x0101056d
03-09 22:27:05.851 32167 32167 E ResourceType: Style contains key with bad entry: 0x0101058c
03-09 22:27:05.851 32167 32167 E ResourceType: Style contains key with bad entry: 0x01010604
03-09 22:27:05.851 32167 32167 E ResourceType: Style contains key with bad entry: 0x01010605
03-09 22:27:06.455 32167 32167 E ResourceType: Style contains key with bad entry: 0x0101056d
03-09 22:27:06.455 32167 32167 E ResourceType: Style contains key with bad entry: 0x0101058c
03-09 22:27:06.455 32167 32167 E ResourceType: Style contains key with bad entry: 0x01010604
03-09 22:27:06.455 32167 32167 E ResourceType: Style contains key with bad entry: 0x01010605
03-09 22:27:08.284 32167 32230 E SQLiteLog: (284) automatic index on C(manga_id)
03-09 22:27:08.285 32167 32230 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 8.0.0 (SDK 26)
Android build ID: OPR1.170623.032
Device brand: lge
Device manufacturer: LGE
Device name: elsa
Device model: LG-H990
Device product name: elsa_global_com

### Tachiyomi version

0.13.1

### Android version

8.0.0

### Device

LG V20

### Other details

Originally had an old version of the app which made me think this was the issue. I Backed up and installed the newest stable Behavior repeated. 
I have uninstalled and restored from a backup. Tachiyomi will still repeat the behavior. 
I've installed a forked project which functions fine. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the release notes and/or #6599
