### ISSUE TITLE
Auto updates failing to download

### ISSUE THREAD

**Issue by Uncle-Squishy** [tachiyomiorg/tachiyomi#6761]
### Steps to reproduce

Swipe down or press update icon
Hope and pray

### Expected behavior

New chapters should download

### Actual behavior

Nothing happens. 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Galaxy tab S6 Lite

### Other details

Originally I had a bug where the update queue was stuck in an infinite loop of spinning circles but nothing downloaded. I uninstalled and reinstalled the app, checked my settings and ran another update and nothing was added to the queue at all. I have tried this with both the "None" exclusion and the "Default" exclusion and it still doesn't work. But if I long press on a series then tap the option to download updates, it does so for that series. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Uncle-Squishy** [comment]
Welp, for some reason the update I just ran downloaded the one series
update I had. I haven't changed anything so I'm not sure why.

**Comment by arkon** [comment]
May be related to #959. The download queue is sometimes paused without the user being aware.
