### ISSUE TITLE
Suggestions to improve browsing manga

### ISSUE THREAD

**Issue by Ihccato** [tachiyomiorg/tachiyomi#6763]
### Describe your suggested feature

I have 2 suggestions to help improve the browsing of the manga while using extensions, one allows to filter manga already added to the user's library, this becomes useful when the user has a large library. it could help improve, fewer load times as well as have it be less time consuming on the user by having faster access to new manga, after all, if I'm browsing for manga I'm searching for the manga, that it already added to my library. , the ability to mass add manga to the library page, similar to how it's done in the library tab when the user wants to download en mass or move manga to different categories, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
1 request per issue, plus there's a way to pick which category a newly added manga should go to so you can just hold on it to add it to Library

**Comment by arkon** [comment]
1. Having some difficulty finding it, but there's an issue for hiding entries that are already in your library when browsing a source.
2. #829

**Comment by FourTOne5** [comment]
1. https://github.com/tachiyomiorg/tachiyomi/issues/2941
