### ISSUE TITLE
4 bottom nav bar tabs

### ISSUE THREAD

**Issue by exkpwn** [tachiyomiorg/tachiyomi#6767]
### Describe your suggested feature

an option to hide history or updates page maybe 

5 looks crowded 

### Other details

Yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This feature was added and then removed as per https://github.com/tachiyomiorg/tachiyomi/commit/3b11ad8de8fc060f9347a1ff371f8c892a134a31
