### ISSUE TITLE
Preview r4194 "App not installed as package appears to be invalid."

### ISSUE THREAD

**Issue by bejelentkezni** [tachiyomiorg/tachiyomi#6769]
### Steps to reproduce

Try to update from r4184 to r4193.

### Expected behavior

App updates.

### Actual behavior

Update fails with "App not installed as package appears to be invalid."

### Tachiyomi version

r4184

### Android version

Android 12

### Device

Samsung Galaxy A52 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Most likley related to https://github.com/tachiyomiorg/tachiyomi/commit/538478cac811655b077716383b1598db8de5e4dc

**Comment by alessandrojean** [comment]
Can be reproduced on Galaxy S20+ too.

**Comment by arkon** [comment]
Can you try [r4197](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r4197)?

**Comment by ghostbear** [comment]
New build works for me 🎉

**Comment by bejelentkezni** [comment]
Yep, works

**Comment by alessandrojean** [comment]
Working fine now, issue solved.
