### ISSUE TITLE
Global update not working 

### ISSUE THREAD

**Issue by Varunk123** [tachiyomiorg/tachiyomi#6773]
### Steps to reproduce

Tachiyomi app global update not working properly. It doesn't update any manga in library but need to refresh the manga separately 

### Expected behavior

When refreshed in library global update need to update latest chapters.

### Actual behavior

Not updating any chapter from library but gets updated after refreshing separately.

### Tachiyomi version

0.13.1

### Android version

10

### Device

Poco f1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
#6599
