### ISSUE TITLE
Tachiyomi crush.

### ISSUE THREAD

**Issue by mabdaph** [tachiyomiorg/tachiyomi#6774]
### Steps to reproduce

Example 1:
1- go to Browse.
2- tap on Global search.
3- search for any manga.
4- app crushes.

Example 2:
1- open a manga in library.
2- tap on migrate to migrate a manga to another source.
3- app crushes.

### Expected behavior

Example 1:
It should show the manga I searched for in all installed sources.

Example 2:
A prompt should pop up to choose the migration type.

### Actual behavior

In both Examples Tachiyomi crashes 

### Crash logs

--------- beginning of main
03-13 16:00:23.727 25173 30369 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
03-13 16:00:23.727 25173 30369 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at java.lang.Thread.run(Thread.java:919)
03-13 16:00:23.727 25173 30369 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
03-13 16:00:23.727 25173 30369 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:2)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
03-13 16:00:23.727 25173 30369 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
03-13 16:00:23.727 25173 30369 E ACRA    : 	... 6 more
03-13 16:00:23.727 25173 30369 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
03-13 16:00:23.727 25173 30369 E ACRA    : 	... 15 more
03-13 16:00:23.954 29792 29792 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x20000
03-13 16:00:23.972 29792 29792 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
03-13 16:00:25.857 30103 30103 E anade.tachiyom: Unknown bits set in runtime_flags: 0x20000
03-13 16:00:25.860 30103 30103 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
03-13 16:00:26.224 30103 30499 E SQLiteLog: (284) automatic index on C(manga_id)
03-13 16:00:26.224 30103 30499 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 10 (SDK 29)
Android build ID: ONEPLUS A5000_23_201029
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5

### Tachiyomi version

0.13.1

### Android version

Android 10 

### Device

OnePlus 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Remove your obsolete manga rock extension.
