### ISSUE TITLE
Don't send default WebView header "X-Requested-With"

### ISSUE THREAD

**Issue by vetleledaal** [tachiyomiorg/tachiyomi#6781]
### Describe your suggested feature

The `X-Requested-With` header can and has been used to block Tachiyomi, see tachiyomiorg/tachiyomi-extensions#9738.

When setting `client` to `network.cloudflareClient` requests will be made with this header using the value `com.android.browser`. This should be omitted instead for all such requests.

It's not entirely obvious how this behaviour can be changed from an extension, and it appears to be beneficial for all extensions regardless.

### Other details

Although not currently blocked, other requests use the header `X-Requested-With: eu.kanade.tachiyomi`, such as when retrieving the favicon or some Cloudflare beacon stuff.

Relevant code(?) https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt#L104

```bash
# errors out with 1020
curl -H 'X-Requested-With: com.android.browser' 'https://www.toongod.com/'

# shows the normal cloudflare page
curl -H 'X-Requested-With: com.android.browsssser' 'https://www.toongod.com/'
```
![BurpSuiteCommunity_Nywnj9tdDn](https://user-images.githubusercontent.com/13540478/158500251-855896c8-5adb-414f-acd7-219b05e35f0a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
WebView always sends the header, and we at best override the initial one.

If you have the app dev environment set up, you could try [this](https://github.com/mozilla-mobile/focus-android/issues/1196#issuecomment-496487561) locally and let me know if it works.

**Comment by vetleledaal** [comment]
The linked code works fine for hiding the default package name from WebView requests outside of the initial request. Seems hard to outright remove the header though -- is this possible through reflection?

Code I tested with:
```diff
diff --git a/app/src/main/java/eu/kanade/tachiyomi/App.kt b/app/src/main/java/eu/kanade/tachiyomi/App.kt
index 53b9417d2..567ce581b 100644
--- a/app/src/main/java/eu/kanade/tachiyomi/App.kt
+++ b/app/src/main/java/eu/kanade/tachiyomi/App.kt
@@ -191,6 +191,23 @@ open class App : Application(), DefaultLifecycleObserver, ImageLoaderFactory {
             }
         }
     }
+
+    override fun getPackageName(): String {
+        try {
+            val stackTrace = Thread.currentThread().stackTrace
+            for (element in stackTrace) {
+                if ("org.chromium.base.BuildInfo".equals(element.className, ignoreCase = true)) {
+                    if ("getAll".equals(element.methodName, ignoreCase = true)) {
+                        return "com.tencent.qq"
+                    }
+                    break
+                }
+            }
+        } catch (e: Exception) {
+        }
+
+        return super.getPackageName()
+    }
 }

 private const val ACTION_DISABLE_INCOGNITO_MODE = "tachi.action.DISABLE_INCOGNITO_MODE"
diff --git a/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt b/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt
index 37c8e920d..0a8464143 100644
--- a/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt
+++ b/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt
@@ -101,7 +101,6 @@ class CloudflareInterceptor(private val context: Context) : Interceptor {

         val origRequestUrl = request.url.toString()
         val headers = request.headers.toMultimap().mapValues { it.value.getOrNull(0) ?: "" }.toMutableMap()
-        headers["X-Requested-With"] = WebViewUtil.REQUESTED_WITH

         executor.execute {
             val webview = WebView(context)
diff --git a/app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt b/app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
index 4ebcf86ec..86791470a 100644
--- a/app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
+++ b/app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
@@ -103,8 +103,6 @@ class WebViewActivity : BaseViewBindingActivity<WebviewActivityBinding>() {
                 headers = source.headers.toMultimap().mapValues { it.value.getOrNull(0) ?: "" }.toMutableMap()
                 binding.webview.settings.userAgentString = source.headers["User-Agent"]
             }
-            headers["X-Requested-With"] = WebViewUtil.REQUESTED_WITH

             supportActionBar?.subtitle = url

             binding.webview.webViewClient = object : WebViewClientCompat() {
```
![BurpSuiteCommunity_yCqmDSn6p0](https://user-images.githubusercontent.com/13540478/158702056-434fed2c-b6ba-43eb-b513-43d5d883583d.png)
![BurpSuiteCommunity_e9EwWsERqp](https://user-images.githubusercontent.com/13540478/158702070-ff62b4f2-687e-4462-bfc8-4dfe7cecf538.png)

**Comment by vetleledaal** [comment]
I think changing the default to `org.chromium.chrome` would work as a sane default. A lot of browsers use this already, so blocking it would be kinda stupid.

I'm not entirely sure where it would make sense to overwrite this, doing it in `App.kt` (as above) seems improper. Thoughts?

**Comment by quangkieu** [comment]
So should this be in this repo or extension?

**Comment by arkon** [comment]
> doing it in `App.kt` (as above) seems improper.

I suspect it may be the only way if the WebView is ultimately just calling the app context to get it.

> So should this be in this repo or extension?

Probably has to be at the app level.

**Comment by vetleledaal** [comment]
Any reason for going with `com.android.chrome` instead of `org.chromium.chrome`? Haven't seen the former used in the wild with this header

**Comment by arkon** [comment]
No particular reason other than Chrome being more popular than Chromium. Is Chromium somehow more valid?

**Comment by vetleledaal** [comment]
Chrome doesn't actually use the header, so using it would make this stick out. There might be more popular regional apps using this header, but some apps using `org.chromium.chrome` include: DuckDuckGo, Oepra GX, and Phoenix.
