### ISSUE TITLE
YugenMangas: The numbers of the chapters and their dates are not visible

### ISSUE THREAD

**Issue by SamirM15** [tachiyomiorg/tachiyomi#6783]
### Steps to reproduce

1. I enter the YugenMangas extension
2. I select any manga
3. Chapter numbers and dates are missing

### Expected behavior

Chapters and dates should be visible

### Actual behavior

The numbers of the chapters and their dates are not visible

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Samsung Galaxy A52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please actually read what you acknowledge.
