### ISSUE TITLE
Double tap history button to read last read chapter

### ISSUE THREAD

**Issue by D1VY4N5H** [tachiyomiorg/tachiyomi#6784]
### Describe your suggested feature

Double tapping history button will:
1) Open the last read chapter, if it's not read fully (like 4/5 pages read).
2) Open next chapter of the series, if the chapter was read fully.
3) Will move onto the next entry in history, if the series has chapter fully read and has no more chapters remaining.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pierre-Monier** [comment]
This looks great, I will work on that
