### ISSUE TITLE
Support for Happy Eyeballs

### ISSUE THREAD

**Issue by TheSkyLookingGood** [tachiyomiorg/tachiyomi#6785]
### Describe your suggested feature

Sometimes user have bad IPv6 configuration, Happy Eyeballs solved this problem by connecting to IPv4 and IPv6 at same time.

### Other details

OkHttp added this since **Version 5.0.0-alpha.4** 
Even though it says Alpha but according to them 
> If you're prepared to deal with small API changes between now and 5.0 final you can put it into production today. For OkHttp ‘alpha’ means ‘API instability’ but the code is extremely stable.
[Source](https://github.com/square/okhttp/issues/506#issuecomment-1046824772) 

More info about Happy Eyeballs
[Wikipedia](https://en.m.wikipedia.org/wiki/Happy_Eyeballs) 
[RFC](https://datatracker.ietf.org/doc/html/rfc8305)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
da2b30268a51afca1eeb93f08256a236447ac2b6
