### ISSUE TITLE
Add option to only update series where the latest chapter has been read

### ISSUE THREAD

**Issue by soruh** [tachiyomiorg/tachiyomi#6788]
### Describe your suggested feature

Since the recent changes in #6599 I have been missing some updates in series I am actively reading. I noticed that this was due to single unread chapters at the start of the series (mostly duplicated chapters). I think it would make sense to add an option to update all series where the newest chapter is read instead of either updating all series or updating only series where every chapter has been read. I also think that this would be a better default than the current one without putting unreasonably more load on sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You can just mark the previous chapters as read (assuming you have already read them before).

**Comment by soruh** [comment]
that's true, but I'd rather not manually go throught every single series in my library to find which ones habe duplicate chapters. At that point I will just turn on sync for everything.

**Comment by alessandrojean** [comment]
Closing since the solution is mark the things you already have read as read.

**Comment by soruh** [comment]
No I cannot. The unread filter includes series I have not finshed/started yet and ones that have new chapters so I will still need to go through a ton of series. I guess if there was an option to filter the library by the lateat chapter being read this would be feasable but at that point that could also just be an option for sync as I proposed.

**Comment by soruh** [comment]
Damn, okay. I guess I will fork and try to implement it myself.

**Comment by soruh** [comment]
P.S.: if your idea of good UX is "I categorically refuse to add this tiny feature. The user should do that work manually" idk. what to tell you.
