### ISSUE TITLE
Fix library update errors

### ISSUE THREAD

**Issue by Dake647392** [tachiyomiorg/tachiyomi#6789]
### Steps to reproduce

![Screenshot_2022-03-18-15-48-58-883_com android chrome](https://user-images.githubusercontent.com/101671513/158985850-ebffa0cd-93ab-4382-b3fe-0da59d17daae.jpg)

### Expected behavior

When even I try to update my library it's shows error

### Actual behavior

Whenever I try to update the library it's show error i am sending u screenshot with this mail

### Crash logs

![Uploading Screenshot_2022-03-18-15-48-58-883_com.android.chrome.jpg…]()

### Tachiyomi version

 0.13.1

### Android version

Android 12

### Device

Redmi note 8

### Other details

Fix this shit 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Migrate
