### ISSUE TITLE
The saved titles era not being updated

### ISSUE THREAD

**Issue by LukkeCL** [tachiyomiorg/tachiyomi#6793]
### Steps to reproduce

1. Open Tachiyomi;
2. Click on update icon on library screen;
3. Wait for update tô finish.

### Expected behavior

All titles saved in the library, that has being updated um the source, should be updated.

### Actual behavior

The titles are not being updated. Only the error report about the source os being created.

### Crash logs

There is no crash log

### Tachiyomi version

0.13.1

### Android version

11

### Device

Xiaomi Note 9S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably #6599

**Comment by LukkeCL** [comment]
Nice.
