### ISSUE TITLE
Can't update library

### ISSUE THREAD

**Issue by RNatuR** [tachiyomiorg/tachiyomi#6795]
### Steps to reproduce

1. Open Tachiyomi
2. Go to Updates tab
3. Tap the update library button on top right

### Expected behavior

It should update the Library

### Actual behavior

Didn't updated the Library, after the update

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

Redmi Note 7

### Other details

Whenever I go to Updates tab and tap update library, it doesn't work. The Toast comes up and says updating library but it doesn't work.
I have lot of Mangas in my library i can't update them one by one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#6599
