### ISSUE TITLE
MangaDex extension missing in "Browse -> Extensions", cannot be found hence cannot be installed

### ISSUE THREAD

**Issue by DgitalTrex** [tachiyomiorg/tachiyomi#6796]
### Steps to reproduce

1. Open Tachiyomi
2. Click Browse
3. Click Extensions tab
4. Search "MangaDex"

### Expected behavior

MangaDex to show

### Actual behavior

MangaDex no show

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

BlackShark 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Make sure you enabled 18+ sources in the settings.

**Comment by DgitalTrex** [comment]
@alessandrojean it is enabled. I just noticed that manga dex is gone when I needed it

**Comment by arkon** [comment]
Make sure:

1. You can get the list of extensions in general
2. 18+ sources are enabled
3. You haven't disabled the extension's language (i.e., "All" for MangaDex)
