### ISSUE TITLE
Extension Storage

### ISSUE THREAD

**Issue by jay5656** [tachiyomiorg/tachiyomi#6798]
### Describe your suggested feature

Extensions use storage right? It would be nice to see how much they take up underneath each extension, next to the language and version. 

I apologize if they don't use storage 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They do use storage since they're are just apps that are installed, but the extensions have a small size, less than 1 MB in average.

**Comment by jay5656** [comment]
> They do use storage since they're are just apps that are installed, but the extensions have a small size, less than 1 MB in average.

Oh then I'm gonna install a ton, is there at least a way to see the total storage extensions take up then?

**Comment by alessandrojean** [comment]
Don't install like all extensions available, that will make the app global search slower. You can see only how much they use in space individually in the Android Settings app list.

**Comment by arkon** [comment]
System settings shows the amount of storage taken up by apps.

**Comment by jay5656** [comment]
> System settings shows the amount of storage taken up by apps.

System settings shows each one individually, and not the total of JUST the extensions
