### ISSUE TITLE
Add link to novel info

### ISSUE THREAD

**Issue by wruizcanal** [tachiyomiorg/tachiyomi#6801]
### Describe your suggested feature

Hello.  

I want an option in the context menu of each item in the download view to see the information of the novel it belongs to.

When you have a very large download list you may not remember what you are downloading and being able to quickly access the information of the novel to see what it is can be very useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Tachiyomi is an image viewer and doesn't support novels, what do you mean?

https://tachiyomi.org/help/faq/#can-tachiyomi-read-light-novels

**Comment by arkon** [comment]
The titles are shown in the download queue.
