### ISSUE TITLE
Save, share, or set the cover that is visible on the screen.

### ISSUE THREAD

**Issue by Mano5JP** [tachiyomiorg/tachiyomi#6803]
### Describe your suggested feature

![Screenshot_Tachiyomi](https://user-images.githubusercontent.com/64928088/159439177-841b8565-a575-4dde-bc6a-a99bf3f3de1b.jpg)

Currently, saving, sharing, or setting the cover takes up the entire page.

Instead, capturing only the visible image would be preferable, as the page may be longer/smaller than usual and this is not a problem on the source side.

With this I could Zoom (In/Out) and perform actions with this.

|1st option|2nd option|
|-----------|------------|
|Have a toggle somewhere above with an option for visible or entire page.|When we save the page, it only saves the visible area, but it prompts us to share or set a cover.|

### Other details

My opinion is that the user saves, share, or set the cover for that specific moment rather than the entire page. And editing, which is a time-consuming process. Maybe I could be mistaken because it varies from user to user

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not interested in maintaining effectively image editing software within this app. Save an image and edit it in a gallery app if needed.

**Comment by Mano5JP** [comment]
It was rather like taking a screenshot, but oh well, it was only a rared use-case to me and i am fine with current process, it was just a suggestion by all means.

👍
