### ISSUE TITLE
Landscape images broken

### ISSUE THREAD

**Issue by hankgames** [tachiyomiorg/tachiyomi#6804]
### Steps to reproduce

View manhua in webtoon/vertical view.

### Expected behavior

All images should link up properly without any image breaks. Normal behavior. 

### Actual behavior

Landscape images are being split into 2, stacked on top of each other. 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Galaxy Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Turn off dual page split
