### ISSUE TITLE
Auto download feature

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#6806]
### Describe your suggested feature

Please add a feature to enable/disable the auto download feature for certain categories, or add a favorite comic storage feature and please add a auto download and install for extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
it already exists, exclude them.
