### ISSUE TITLE
Saved Image not Recognized in System Files

### ISSUE THREAD

**Issue by Qnomei** [tachiyomiorg/tachiyomi#6808]
### Steps to reproduce

1. Open any chapter and save a page.
2. Open the Android built-in files app
3. Navigate to "recent" files or the folder where tachiyomi saves images. 

### Expected behavior

The image should appear.

### Actual behavior

The image will not appear in the "recent" section of the built-in files app or be seen by any app which uses this to access the file system. It will appear in the correct folder with a placeholder box, but with no image preview. The only fix is to restart the phone.

### Tachiyomi version

App version: 0.13.1-4202

### Android version

Android version: 9 (SDK 28) Android build ID: PKQ1.181105.001

### Device

Device manufacturer: LGE Device model: LM-G710

### Other details

This does not occur in the stable version, only in preview after the latest update. I am aware of a closed ticket about images not showing in a gallery app. But my system apps have had no updates for 2 years, and this issue only occurred after an update to tachiyomi. This has not affected my LG files app nor my 3rd-party gallery app, only the Android system built-in files app.

I would safely ignore this issue if not for Discord forcing use of the system files app to upload files. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Fixed in #6800

**Comment by Qnomei** [comment]
Updated to latest version with fix #6800. Same behavior as above but image extension needs to be renamed twice to fix it.
