### ISSUE TITLE
Hidden "draggable" bar on chapter lists

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6809]
### Steps to reproduce

this is the "draggable" bar i am writing about:
![IMG_20220323_132722](https://user-images.githubusercontent.com/75091899/159699128-31e1093d-7917-44a3-baa1-5d96df148006.jpg)

https://user-images.githubusercontent.com/75091899/159698515-e49bde4a-455d-4209-af39-6b42c92a8758.mp4

1. go to the chapter list of a manga with 800+ chapters (martial peak, apotheosis etc..)
2. scrolling down until the draggable bar shows up

### Expected behavior

The app should show the draggable bar after a few chapters scrolled down.

### Actual behavior

The app shows up the draggable bar ( a size that allows me to drag it comfortably) when the 10-15% of the max amount of chapters is scrolled down.

### Tachiyomi version

0.13.1

### Android version

android 8

### Device

huawei p8 lite 2017

### Other details

This issue is not a problem when there aren't many chapters, but when the manga starts to have a lot of them (700+ chapters, see martial peak with 2000+) it becomes annoying and the user has to scroll down the 10-15% of the max amount of chapters ( 90+ and it is slow) the get the draggable bar to show up and use it to navigate through the vast amount of chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#6114

**Comment by Palloxin** [comment]
> #6114

@CrepeTF i have to say that is not the same problem
