### ISSUE TITLE
Option to disable "Open links in apps" for all extensions together 

### ISSUE THREAD

**Issue by Anutrix** [tachiyomiorg/tachiyomi#6812]
### Describe your suggested feature

1. Install Tachiyomi.
2. Open any shared link(of Tachiyomi supported site) or tabs sent from Desktop Firefox to phone.
3. See that they open in Tachiyomi instead of default browser.
There is no option disable it for Tachiyomi itself except for every one of the Tachyomi's extensions in phone settings one by one manually.

One of my friends already stopped using Tachiyomi cuz they felt it hijacked their default browser without warning.

Wish there was an option to disable opening hyperlinks for all extensions. Or atleast didn't do it by default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That's how verified links are supposed to work, and only happens if websites consciously allow it.

There's no way for apps to control what links open your app or not, because that'd be actual hijacking.

**Comment by Anutrix** [comment]
Thx for the quick answer. New things learnt.
Also, I was just thinking if adding `android:autoVerify="true"` to the `intent-filter`s in the AndroidManifest.xml will help.
I'm still new to these Android dev topics so sry if it doesn't makes sense or does something different.

**Comment by FourTOne5** [comment]
> Thx for the quick answer. New things learnt. Also, I was just thinking if adding `android:autoVerify="true"` to the `intent-filter`s in the AndroidManifest.xml will help. I'm still new to these Android dev topics so sry if it doesn't makes sense or does something different.

No it won't and it's one of the things that makes link automatically open in Tachiyomi
