### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ladysoftlighting** [tachiyomiorg/tachiyomi#6814]
### Steps to reproduce

1. Search for manga in global search
2. Start updating library 

### Expected behavior

"When searching for manga, the manga should be shown from saved extensions'
"When updating library, new chapters should update"

### Actual behavior

"When searching for manga, it shows a few results before the app crashes mid search"
"The library does not update"

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8340293/tachiyomi_crash_logs.txt)

### Tachiyomi version

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975WVLS6HVA1 Device brand: samsung Device manufacturer: samsung Device name: beyond2q Device model: SM-G975W Device product name: beyond2qltecs

### Android version

12

### Device

Galaxy S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
> When searching for manga, it shows a few results before the app crashes mid search

Update your extensions and uninstall the ones that is obsolete

**Comment by curche** [comment]
If the crash is occuring only while doing a Global Search in `Browse > Sources`, then one of your extensions is the culprit
Go to `More > Settings > Browse` and enable Global Search only Pinned sources
then you can now Pin sources in `Browse` and search for manga only in those sources. 
With this, you can experiment pinning/unpinning your sources and searching thru them to narrow out which source is the problematic one

That said, the crashlogs don't point at anything that might be related to crashing while Global Searching. Try getting the crashlogs again and see if the files differ or just upload the new files here

**Comment by ghostbear** [comment]
Can you try turning on `Only include pinned sources` for Global search 
And then pin the sources one and one doing a global search in between each pinning 
To try finding the culprit as what you're experiencing sound like one of the extensions are broken

**Comment by ladysoftlighting** [comment]
I can do that but it still doesn't explain why the library doesn't update. What about that?

**Comment by ladysoftlighting** [comment]
--------- beginning of main
03-26 02:40:33.742  1366  1366 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
03-26 02:40:33.746  1366  1366 E USNET   : USNET: appName: eu.kanade.tachiyomi
03-26 02:40:34.119  1366  1366 E anade.tachiyom: Invalid ID 0x00000000.
03-26 02:40:35.442  1366  2477 E SQLiteLog: (284) automatic index on C(manga_id)
03-26 02:40:35.442  1366  2477 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G975WVLS6HVA1
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2q
Device model: SM-G975W
Device product name: beyond2qltecs

**Comment by ghostbear** [comment]
> What about that?

Probably just be the new update criteria in global update, you are experiencing.
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries

--- 

Also, that new crashlog doesn't have anything useful to solve your issue

**Comment by ladysoftlighting** [comment]
Okay. Following your reply I modified the update criteria and its fixed now. The criteria only allowed updates for completed novels and I have no idea how that happened. The library is updating normally now. I'm currently going through the sources and I think I found the extension that's a problem. Thank you for helping me.

**Comment by curche** [comment]
Closing as issue is resolved
