### ISSUE TITLE
Removing Status Bar when Reading

### ISSUE THREAD

**Issue by Asainese** [tachiyomiorg/tachiyomi#6815]
### Describe your suggested feature

Add an option to remove Status bar when Reading so that even tapping the middle of screen won't cause the Status bar to show up. To show Status bar again, triple tap screen or include small icon in bottom corner that will show Status screen when tapped. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you don't want to see the menus, then don't tap to bring up the menus.

**Comment by Asainese** [comment]
But when scrolling its sometimes easy to accidentally tap the screen, which will cause the menus to show up. It gets really annoying when it happens continuously.

**Comment by Asainese** [comment]
> If you don't want to see the menus, then don't tap to bring up the menus.

But when scrolling, sometimes it's possible to accidentally tap the screen, which will cause the menu to pop up.
