### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Ikki505** [tachiyomiorg/tachiyomi#6817]
### Steps to reproduce

In backup & restore section when i tap restore app crashes immediately...

### Expected behavior

It should open file manager to let me pick backup file

### Actual behavior

When i tap restore tachiyomi closes automatically..

### Crash logs

--------- beginning of main
03-25 14:33:08.700 10404 10404 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
03-25 14:33:10.678 10404 10455 E SQLiteLog: (284) automatic index on C(manga_id)
03-25 14:33:10.678 10404 10455 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-25 14:33:10.840 10404 10433 E LB      : fail to open file: Permission denied
03-25 14:33:10.926 10404 10404 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
03-25 14:33:10.926 10404 10404 E libc    : Access denied finding property "ro.vendor.knock.type"
03-25 14:35:56.334 11643 11643 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
03-25 14:35:58.381 11643 11720 E SQLiteLog: (284) automatic index on C(manga_id)
03-25 14:35:58.381 11643 11720 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-25 14:35:58.500 11643 11671 E LB      : fail to open file: Permission denied
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweetin
Device model: M2101K6I
Device product name: sweetinpro

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Redmi note 10 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Xiaomi devices with MIUI are known to be very buggy out of our control.

General tips:

Use a non-default file manager when restoring backups, do NOT use MIUI's file manager. Switch MIUI Optimizations under Developer Settings to ON when restoring backups as well.
