### ISSUE TITLE
History tab not retaining search results

### ISSUE THREAD

**Issue by rspreet92** [tachiyomiorg/tachiyomi#6818]
### Steps to reproduce

I have to search again in the history tab if Open any manga from results and go back.
1. Search something in History panel
2. Open any manga from results
3. Go back 
4. Search result is gone back to History list.

Search text is there but the results are gone.

### Expected behavior

Retain the search results.

### Actual behavior

Not retaining search results.

### Tachiyomi version

Preview r4202 (0.13.1-4202)

### Android version

10

### Device

Redmi Note 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by rspreet92** [comment]
I think the other issue about retaining scroll position while this issue is about search results.

**Comment by arkon** [comment]
I know, but it's probably the same underlying issue.
