### ISSUE TITLE
"Open in app" option for anime list apps

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6819]
### Describe your suggested feature

![IMG_20220325_142441](https://user-images.githubusercontent.com/75091899/160129568-712b8a13-d2a4-48d8-ac2d-a60cfa124b88.jpg)
Add the feature "open in app" in this place(see the screenshot). anime-list websites have third party apps or official ones dedicated so i suggest to add that option for the anime list websites chosen. In my case the website is Anilist and the app is a third-party one called Anilib (actually the best one for the website) and it also is on the play store + has github.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
click the anilist logo

**Comment by Palloxin** [comment]
> click the anilist logo

the suggestion feature is to open it on a dedicated app not on the browser

**Comment by arkon** [comment]
It's ultimately up to those apps to handle the links.

**Comment by Palloxin** [comment]
> It's ultimately up to those apps to handle the links
when i visit anilist on the browser there is the option "open in app".

**Comment by Palloxin** [comment]
> It's ultimately up to those apps to handle the links.

are you telling that the developer of the app is the one that allows browsers (making it avaiable) to use the feature "open in app"?

**Comment by CarlosEsco** [comment]
yes the app has to support deep linking of the url.
