### ISSUE TITLE
Use regular browser intents instead of custom tabs

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6821]
### Describe your suggested feature

edit:so the description of the feature request is here https://github.com/tachiyomiorg/tachiyomi/issues/6819 (for some reason it got closed then reopened in another post after a clarification in the comments of this post).

original:sorry for the bother, i couldn't continue to comment in the previous issue since the comments have been locked and i don't know how other ways to.continue the conversation.
here is what he said to me: 
![IMG_20220325_153514](https://user-images.githubusercontent.com/75091899/160141644-4324685f-aae2-4dc8-9779-b874c02d93fc.jpg)

https://github.com/rev0lgenX/AniLib/issues/12

i will try to make the developer of that app to talk to you directly here

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Clicking on the "Open in browser" shows any app that can handle the link. Here for example it shows AL-chan which is not a browser but AniList client.
![Screenshot_20220325-204048](https://user-images.githubusercontent.com/59261191/160142845-bbea2191-bea1-40aa-8ec0-0484316a2c8e.png)

**Comment by CarlosEsco** [comment]
locking cause, as you see above it works fine.

**Comment by arkon** [comment]
I'm unlocking in case there's actually something useful to be discussed from the dev.

**Comment by Palloxin** [comment]
> I'm unlocking in case there's actually something useful to be discussed from the dev.

sorry, i opened a part 3 before i got the email

**Comment by rev0lgenX** [comment]
According to [docs](https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#what-happens-if-the-user-doesnt-have-a-browser-that-supports-custom-tabs-installed), currently if any browser is set as default and customtab is supported, it will directly open the link in the browser's customtatb. It will no longer show list of app and we need to remove the default browser to view the list again, many users might not be aware of this situation and want to open in any app except the browser, so I think @Palloxin  feature has some valid point.

**Comment by arkon** [comment]
So the long story short is that the feature request is to remove the usage of custom tabs.

**Comment by rev0lgenX** [comment]
@arkon Looks like that to me.

**Comment by Palloxin** [comment]
so, should i adapt the content of the feature request since that description doesm't make sense alone?

**Comment by arkon** [comment]
You can just reference your original issue.
