### ISSUE TITLE
Update check notification isn't addative

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6825]
### Steps to reproduce

Have series in separate categories
refresh one category (category1), then the other afterwards (category2)

### Expected behavior

the update check notification should say done/(category1+category2)

### Actual behavior

the update counter says done/_category2_, causing the "done" number to be more than the total. 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Google Pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This was actually fixed even before that (and i can't bother t find the commit)
