### ISSUE TITLE
BUG 'Refresh manga library cover'

### ISSUE THREAD

**Issue by Gamefire238** [tachiyomiorg/tachiyomi#6826]
### Steps to reproduce

1 enable (Refresh metadata automatically) and update library
2 or press (Refresh manga library cover)
3 problems occur when doing the above, it crashes when there is a manhua that has many chapters, For example ( manhua "martial peak" which has more than 2000 chapters)

### Expected behavior

Hope no problem Refreshing manga cover in next app update

### Actual behavior

Refreshing manga covers and updating libraries takes a long time or doesn't even finish
![Screenshot_2022_0326_213503](https://user-images.githubusercontent.com/78879425/160242635-535c1a28-68bf-4af5-ab4e-b576d3021012.jpg)

### Tachiyomi version

r4202

### Android version

Android 11

### Device

VIVO Y12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please at least include crash logs if your issue is about a crash.

For the long update, refer to the troubleshooting guide.

**Comment by Gamefire238** [comment]
Crash logs

--------- beginning of main
03-26 22:02:45.812 28348 28348 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
03-26 22:02:48.860 28348 28422 E SQLiteLog: (284) automatic index on C(manga_id)
03-26 22:02:48.860 28348 28422 E SQLiteLog: (284) automatic index on R(manga_id)
03-26 22:02:48.860 28348 28422 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-26 22:07:14.757 28348 28393 E ion     : ioctl c0044901 failed with code -1: Invalid argument
03-26 22:07:15.283 28348 29076 E ion     : ioctl c0044901 failed with code -1: Invalid argument
03-26 22:39:11.696 28348 29075 E MangaDex: error parsing chapter list
03-26 22:39:11.696 28348 29075 E MangaDex: java.net.SocketException: Software caused connection abort
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.net.SocketInputStream.socketRead0(Native Method)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okio.InputStreamSource.read(JvmOkio.kt:5)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:3)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okio.RealBufferedSource.request(RealBufferedSource.kt:6)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:1)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:1)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:4)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:1)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:1)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:5)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:8)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-26 22:39:11.696 28348 29075 E MangaDex: 	at java.lang.Thread.run(Thread.java:923)
03-26 23:01:42.620 13680 13680 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
03-26 23:01:45.278 13680 13749 E SQLiteLog: (284) automatic index on C(manga_id)
03-26 23:01:45.278 13680 13749 E SQLiteLog: (284) automatic index on R(manga_id)
03-26 23:01:45.278 13680 13749 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-26 23:01:46.891 13680 13720 E ion     : ioctl c0044901 failed with code -1: Invalid argument
03-26 23:01:46.892 13680 13769 E ion     : ioctl c0044901 failed with code -1: Invalid argument
03-26 23:01:50.422 13680 13680 E RealImageLoader: eu.kanade.tachiyomi.network.HttpException: HTTP error 403
03-26 23:01:50.422 13680 13680 E RealImageLoader: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:2)
03-26 23:01:50.422 13680 13680 E RealImageLoader: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:7)
03-26 23:01:50.422 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-26 23:01:50.422 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-26 23:01:50.422 13680 13680 E RealImageLoader: 	at java.lang.Thread.run(Thread.java:923)
03-26 23:04:45.935 13680 13680 E RealImageLoader: eu.kanade.tachiyomi.network.HttpException: HTTP error 403
03-26 23:04:45.935 13680 13680 E RealImageLoader: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:2)
03-26 23:04:45.935 13680 13680 E RealImageLoader: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:7)
03-26 23:04:45.935 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-26 23:04:45.935 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-26 23:04:45.935 13680 13680 E RealImageLoader: 	at java.lang.Thread.run(Thread.java:923)
03-26 23:05:06.166 13680 13680 E RealImageLoader: java.io.EOFException
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Stream$FramingSource.receive$okhttp(Http2Stream.kt:22)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Stream.receiveData(Http2Stream.kt:3)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.data(Http2Connection.kt:7)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:68)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:4)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:1)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:1)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:5)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:8)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-26 23:05:06.166 13680 13680 E RealImageLoader: 	at java.lang.Thread.run(Thread.java:923)
03-26 23:05:10.425 13680 13680 E RealImageLoader: java.lang.IllegalStateException: closed
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:8)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:2)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.decode.GifDecodeUtils.isGif(DecodeUtils.kt:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.decode.ImageDecoderDecoder$Factory.create(ImageDecoderDecoder.kt:3)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:9)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:4)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:43)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$1.invokeSuspend(Unknown Source:16)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
03-26 23:05:10.425 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
03-26 23:05:11.851 13680 13680 E RealImageLoader: java.lang.IllegalStateException: closed
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:8)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:2)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.decode.GifDecodeUtils.isGif(DecodeUtils.kt:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.decode.ImageDecoderDecoder$Factory.create(ImageDecoderDecoder.kt:3)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:9)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:4)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:9)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:43)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at coil.intercept.EngineInterceptor$execute$1.invokeSuspend(Unknown Source:16)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
03-26 23:05:11.851 13680 13680 E RealImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
App version: 0.13.1-4202 (standard, da2b30268, 76, 2022-03-19T21:09Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1904
Device model: vivo 1904
Device product name: 1904
