### ISSUE TITLE
Misidentifying numbers in chapters

### ISSUE THREAD

**Issue by Cicada000** [tachiyomiorg/tachiyomi#6828]
### Steps to reproduce

It will recognize all the numbers in the title as chapters.

![Stitch_20220327_083644](https://user-images.githubusercontent.com/78632923/160261656-74407316-1631-433d-b219-f4a9768d2b46.png)

### Expected behavior

No error message

### Actual behavior

![Stitch_20220327_083644](https://user-images.githubusercontent.com/78632923/160261656-74407316-1631-433d-b219-f4a9768d2b46.png)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Google Pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The chapter number detection is unfortunately best effort and doesn't handle these special cases very well. You can just ignore it when it happens since the chapter names are fairly indicative of what's actually happening.
