### ISSUE TITLE
Bandwidth-hero data server

### ISSUE THREAD

**Issue by suhan-paradkar** [tachiyomiorg/tachiyomi#6830]
### Describe your suggested feature

This feature is already implemented in the TachiyomiSY fork...
It allows compression of images with help of a user-run heroku instance, which acts as a proxy server...
It would be useful for people with limited bandwidth...
More info on bandwidth hero - https://github.com/ayastreb/bandwidth-hero-proxy

### Other details

Screenshot of implementation in SY fork
![Screenshot_2022-03-27-09-39-13-32](https://user-images.githubusercontent.com/76830230/160266327-e5c86e4e-a085-4732-be4a-6014413cdcef.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'd avoid adding this to the main app because it's quite confusing to the majority tech illiterate users and is generally pretty hit or miss in actually being able to fetch images anyway.
