### ISSUE TITLE
Crash when downloading

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#6832]
### Steps to reproduce

Just try downloading manga. The ones in my queue right now are MangaDex's Dungeon Meshi and Tritinia Scans' We May be an Inexperienced Couple.

### Expected behavior

It should download normally.

### Actual behavior

The app crashes after a few seconds.

### Tachiyomi version

Preview r4215

### Android version

Android 10

### Device

Moto G7 Power

### Other details

I'm downloading to a folder in my microSD. It has more than 1.5GB left.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If the app is crashing, please provide the crash logs as requested in the form.

**Comment by hyoretsu** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8358772/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Did you update your extension?

**Comment by hyoretsu** [comment]
Sorry for the extra Issue, updating fixed it
