### ISSUE TITLE
Some panels are enlarged 

### ISSUE THREAD

**Issue by Fur1ousPanda** [tachiyomiorg/tachiyomi#6833]
### Steps to reproduce

Open chapter 70 from Manhwa "Release the Witch"
You can see some panels are enlarged and there is no issue if you open the site from a browser. The issue can be seen in multiple webtoons but above title is only mentioned as a reference for the issue.
![Screenshot_20220328-021536](https://user-images.githubusercontent.com/102508752/160345744-86767339-be76-44a9-9d3a-aace3f070dd6.jpg)

### Expected behavior

All panels should be of same size
![Screenshot_20220328-021636](https://user-images.githubusercontent.com/102508752/160345912-cd40e7aa-20b1-487b-8d64-42b4cc3ba23a.jpg)

### Actual behavior

Some panels in between are enlarged 
![Screenshot_20220328-021536](https://user-images.githubusercontent.com/102508752/160345945-bc9df284-34a4-4d59-9d3c-12846bb1864c.jpg)

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

OnePlus 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Turn off crop borders
