### ISSUE TITLE
Tap/volume key navigation sometimes doesn't work

### ISSUE THREAD

**Issue by hungrypippo** [tachiyomiorg/tachiyomi#6835]
### Steps to reproduce

1. Select L shaped navigation or any navigation
2. Try using the tapping method to change pages

### Expected behavior

And i have the L-shaped navigation on, with tap to change pages. But the navigation doesnt work nearly 90% of the time. And when it does work, Its not that responsive.

The same issue exists with volume key navigation. 

### Actual behavior

It should work normally

### Tachiyomi version

Preview Build r451

### Android version

Android 11

### Device

Tab S7 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fiddleypotato** [comment]
I'm having the dame issue, but it's not limited to L shaped navigation.
The right side is mostly responsive, but the left side works about two times then gets unresponsive.
This started occurring in this latest update, before this it worked as expected.

**Comment by hungrypippo** [comment]
@fiddleypotato yes i updated the app to the latest preview still the same issue. 

I hope the devs fix this issue fast :disappointed:

**Comment by RhythmLunatic** [comment]
Volume button navigation isn't working here either, or S-Pen (I assume it's the same function)

**Comment by hungrypippo** [comment]
Yes same volume button isnt working either.

It exists even in the latest beta! Please please fix it!

**Comment by arkon** [comment]
I can't reproduce this. Does this happen with certain combination of settings? Is there a specific preview version when this stopped working?

**Comment by hungrypippo** [comment]
@arkon Can you see and read something form the coloredmanga extension?

**Comment by scatterthought** [comment]
I'm also seeing the same issue with the Default navigation, but it's a bit random.

My experience seems most similar to @fiddleypotato. Tapping the right side (back) always works, but tapping the left (forward) is sporadic. Sometimes if I exit the app or change mangas, it starts working again. Sometimes, I don't see the issue at all while reading.

I wonder if this is only affecting Samsung devices, as @hungrypippo and @RhythmLunatic both said they also have Samsungs.  My Samsung Tab S6 Lite updated to One UI 4.1 (Android 12) recently, but I see that it started for @hungrypippo while they were on One UI 4 (Android 11) with Tachiyomi 0.13.1. I think that was the same for me.

**Comment by CrepeTF** [comment]
@scatterthought could you make sure navigate to pan is disabled in the reader settings sheet and check?

**Comment by scatterthought** [comment]
I hadn't even noticed the addition of the "Navigate to pan" setting (and didn't know what it's for). Reading about it, I can see how that might be related.

https://github.com/tachiyomiorg/tachiyomi/pull/6481

I've switched it off, and I'll report back after using the app for a few days. Thanks!

**Comment by hungrypippo** [comment]
@CrepeTF i did everything. Its the same thing. 

And yes the settings you said, i did that too and the same thing.

**Comment by scatterthought** [comment]
It's only been three days, but so far turning off "Navigate to Pan" has worked for me. I'll toggle it on/off to see if the problem comes back and then goes away again.

**Comment by Ramon20000** [comment]
Disabling "Navigate to pan" also has fixed the issue for me and re enabling it makes it the issue come back instantly.

Oh and seeing that most people here have Samsung devices i might add that my device is a Amazon fire tablet.

**Comment by scatterthought** [comment]
I enabled "Navigate to Pan" and read a few mangas before the problem returned. When I got to a page where it didn't work, I zoomed in so that the page would be wider than the screen. Tapping the left side of the screen panned to the left (as expected), and tapping again advanced to the next page. I repeated that a few times to confirm the behaviour.

So, it seems to me that the app is getting confused as to whether it should pan or advance on some pages, and does neither.

**Comment by Di027** [comment]
I'm having the exact same issue. Moving forward doesn't always work but going backwards works fine. I tried inverting the volume keys and nothing works. Found that it constantly doesn't woke for some manga and will work with others. Weirdly enough it's not the site. Sometimes some chapters will work and some won't. Just a weird bug.

Device: Samsung Tab S7

**Comment by scatterthought** [comment]
Did you disable the setting as discussed above? In the newest version (0.14.1), it's called "Pan wide images when tapping". I've had no issues since turning that off months ago.
