### ISSUE TITLE
Updating chapters doesn't work in bulk

### ISSUE THREAD

**Issue by TDderpy** [tachiyomiorg/tachiyomi#6838]
### Steps to reproduce

When i go to the update page and pull down to update all manga in my library no updates are ever found. The same happens on automatic updates. 

If i go to update manga on there own it works and finds new chapters if they are available.

This effects multiple sources so i doubt its a bug in the extension. 

### Expected behavior

Id expect it to update chapters for all sources. 

### Actual behavior

It finds no updates unless i go individually in the manga. 

### Crash logs

N/A

### Tachiyomi version

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 11 (SDK 30) Android build ID: GM1913_21_220211 Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus7Pro Device model: GM1913 Device product name: OnePlus7Pro_EEA

### Android version

11

### Device

One plus 7 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#6599

**Comment by CrepeTF** [comment]
Make sure to catch up on your unread chapters so that they're included in the library refresh.
