### ISSUE TITLE
Black lines between pages of chapters

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6840]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/160754892-f6885e1b-c9ea-4d91-b5ba-2a2ef35b587d.mp4

set Webtoon mode (i don't know if it happens with other modes)
1. open a random chapter of a manga
2. go at the border between a page and the other
3. start zooming in and out

### Expected behavior

Black lines should not appear

### Actual behavior

Black lines appear 

### Tachiyomi version

0.13.1

### Android version

android 8

### Device

huawei p8 lite 2017

### Other details

Black lines between pages also appear without zooming in and out in a fixed state. it can be found randomly but it can be reproduceable if you go to the same source, manga, chapter and page.

https://user-images.githubusercontent.com/75091899/160756317-de41f679-f902-4d5a-a9fd-48138d712d34.mp4

manhwahentai.me>daddy wild oath>chapter 70> page 27
in the video, zooming in and out makes the black line disappear (the opposite this time) while if you adjust the zoom to the default state (double tap/click) the black line will appear again
long story short if there aren't black lines on the border between pages, zooming in and out will make the black lines appear, on the contrary if you find a black line in a fixed state, then zooming in and out will make it disappear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by rinamasahiro** [comment]
I also noticed those flickering black lines when scrolling and zooming in webtoon mode on Samsung tab s7, version 1.13.2 and whatever version I had previous to it,  but it wasn't there when I first installed tachiyomi like six months ago.

**Comment by arkon** [comment]
Probably won't be addressed without a larger rewrite of that reader mode which currently isn't planned. Closing since it keeping it open won't be very useful, but will keep in mind if we do ever rewrite it.
