### ISSUE TITLE
Doujindesu : Cant download chapter 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#6842]
### Steps to reproduce

1. Open Doujindesu
2. Search Hero manager
3. Download chapter 24
4. Cant download chapter (progress always 0 and not increase)
![Screenshot_2022-03-31-09-27-30-42_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/160964152-23f8f60e-58f4-4991-a07d-db18f80ca9bc.jpg)

### Expected behavior

Cant download chapter 

### Actual behavior

Chapter must be downloaded 

### Crash logs

--------- beginning of system
03-30 09:30:53.009   756   756 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-30 12:25:41.237 28695 28695 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-30 19:33:38.783 29738 29738 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-30 22:21:34.547 20105 20105 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-31 06:15:48.106 14306 14306 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
03-31 09:27:06.590 15604 15604 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
03-31 09:27:06.596 15604 15604 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
03-31 09:27:06.604 15604 15604 E RefClass: java.lang.reflect.InvocationTargetException
03-31 09:27:06.659 15604 15604 E libc    : Access denied finding property "ro.odm.prev.product.name"
03-31 09:27:07.263 15604 15679 E libEGL  : Invalid file path for libcolorx-loader.so
03-31 09:27:07.316 15604 15604 E anade.tachiyom: Invalid ID 0x00000000.
03-31 09:27:07.351 15604 15604 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-31 09:27:14.054 15604 15604 E ANR_LOG : >>> msg's executing time is too long
03-31 09:27:14.054 15604 15604 E ANR_LOG : Blocked msg = { when=-7s424ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction LaunchActivityItem,ResumeActivityItem hashCode, mActivityToken = android.os.BinderProxy@2ae94a6 mLifecycleStateRequest ResumeActivityItem{procState=-1,updateProcState=false,isForward=true} mActivityCallbacks [LaunchActivityItem{intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.kanade.tachiyomi/.ui.main.MainActivity bnds=[460,940][660,1150] mCallingUid=10062 },ident=105324260,info=ActivityInfo{46bf382 eu.kanade.tachiyomi.ui.main.MainActivity},curConfig={1.0 ??mcc??mnc [in_ID,ja_JP] ldltr sw360dp w360dp h764dp 320dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 720, 1600) mAppBounds=Rect(0, 71 - 720, 1600) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.25mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1163075219981734161, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},overrideConfig={1.0 ??mcc??mnc [in_ID,ja_JP] ldltr sw360dp w360dp h764dp 320dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 720, 1600) mAppBounds=Rect(0, 71 - 720, 1600) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.25mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1163075219981734161, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},referrer=com.oppo.launcher,procState=20,state=Bundle[{com.google.app_measurement.screen_service=Bundle[mParcelledData.dataSize=116], android:viewHierarchyState=Bundle[{android:views={16908290=android.view.AbsSavedState$1@eb47a93, 16908292=android.view.AbsSavedState$1@eb47a93, 16908351=android.view.AbsSavedState$1@eb47a93, 2131296311=android.view.AbsSavedState$1@eb47a93, 2131296346=android.view.AbsSavedState$1@eb47a93, 2131296369=android.view.AbsSavedState$1@eb47a93, 2131296393=android.view.AbsSavedState$1@eb47a93, 2131296418=eu.kanade.tachiyomi.widget.TachiyomiBottomNavigationView$SavedState@e32ad0, 2131296502=android.view.AbsSavedState$1@eb47a93, 2131296557=android.view.AbsSavedState$1@eb47a93, 2131296588=com.google.android.material.button.MaterialButton$SavedState@4a4cac9, 2131296642=android.view.AbsSavedState$1@eb47a93, 2131296725=android.view.AbsSavedState$1@eb47a93, 2131296766=android.view.AbsSavedState$1@eb47a93, 2131296767=android.view.AbsSavedState$1@eb47a93, 2131296768=android.view.AbsSavedState$1@eb47a93, 2131296769=android.view.AbsSavedState$1@eb47a93, 2131296770=android.view.AbsSavedState$1@eb47a93, 2131296774=android.view.AbsSavedState$1@eb47a93, 2131296775=android.view.AbsSavedState$1@eb47a93, 2131296776=android.view.AbsSavedState$1@eb47a93, 2131296777=android.view.AbsSavedState$1@eb47a93, 2131296778=android.view.AbsSavedState$1@eb47a93, 2131296779=android.view.AbsSavedState$1@eb47a93, 2131296846=androidx.recyclerview.widget.RecyclerView$SavedState@69c5ce, 2131296859=eu.kanade.tachiyomi.widget.TachiyomiCoordinatorLayout$SavedState@2a22cef, 2131296955=HorizontalScrollView.SavedState{89823fc scrollPosition=0}, 2131297011=androidx.appcompat.widget.Toolbar$SavedState@4a64a85}}], androidx.lifecycle.BundlableSavedStateRegistry.key=Bundle[{}], LifecycleHandler.routerState2131296502=Bundle[{Router.backstack=Bundle[{Backstack.entries=[Bundle[{RouterTransaction.popControllerChangeHandler=Bundle[{ControllerChangeHandler.savedState=Bundle[{AnimatorChangeHandler.removesFromViewOnPush=true, AnimatorChangeHandler.duration=-1}], ControllerChangeHandler.className=eu.kanade.tachiyomi.ui.base.controller.OneWayFadeChangeH
03-31 09:27:14.054 15604 15604 E ANR_LOG : >>>Current msg List is:
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <1> = { when=-7s422ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction TopResumedActivityChangeItem, hashCode, mActivityToken = android.os.BinderProxy@2ae94a6 mLifecycleStateRequest null mActivityCallbacks [TopResumedActivityChangeItem{onTop=true}] }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <2> = { when=-7s415ms what=9999 target=android.app.ActivityThread$H }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <3> = { when=-7s180ms what=149 target=android.app.ActivityThread$H obj=android.os.BinderProxy@2ae94a6 }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <4> = { when=-6s957ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <5> = { when=-6s892ms what=0 target=android.os.Handler callback=org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0 }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <6> = { when=-6s748ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <7> = { when=-6s745ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <8> = { when=-6s745ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <9> = { when=-6s694ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
03-31 09:27:14.054 15604 15604 E ANR_LOG : Current msg <10> = { when=-6s689ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
03-31 09:27:14.054 15604 15604 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
03-31 09:27:14.168 15604 15677 E libEGL  : Invalid file path for libcolorx-loader.so
03-31 09:27:14.192 15604 15677 E libEGL  : Invalid file path for libcolorx-loader.so
03-31 09:27:14.201 15604 15677 E libEGL  : Invalid file path for libcolorx-loader.so
03-31 09:27:20.343 15604 15833 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
03-31 09:27:20.343 15604 15833 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
03-31 09:27:33.885 15604 16019 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.12
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
