### ISSUE TITLE
Resume button position

### ISSUE THREAD

**Issue by Jeluxe** [tachiyomiorg/tachiyomi#6844]
### Describe your suggested feature

I would to make an option to change the position of the resume button between left or right, if possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pierre-Monier** [comment]
I would like to work on this. 

But don't you want to change the position for every button in the app ?

**Comment by arkon** [comment]
I'm actually going to deny this request, floating action buttons are always on the right.

**Comment by Pierre-Monier** [comment]
I read the material specification for the floating action buttons and nothing says that FAB **MUST** be on the right. There are just on the right because most peoples are right-handed

**Comment by Jeluxe** [comment]
Exactly because mostly are right-handed, and if you think about it, we all using sometimes left or right hand for the phone, so need to think of option that will work for both ways, well i think that at least the resume button should be in the center, so it will be accessed for both left or right handed

**Comment by arkon** [comment]
I'm sorry, but I really need to avoid opening the can of worms of optionally moving UI components around for little value as it introduces a lot of unnecessary bloat in the codebase.

If you can move the FAB, what's next? Moving the download buttons? The menus? Literally everything?
