### ISSUE TITLE
They migrated their website to Madara"

### ISSUE THREAD

**Issue by L0ser456** [tachiyomiorg/tachiyomi#6845]
### Steps to reproduce

1

### Expected behavior

1

### Actual behavior

1

### Crash logs

1

### Tachiyomi version

0.13.1

### Android version

0.8.1

### Device

1

### Other details

They migrated their website to Madara"

new website link:https://shimadascans.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Can't even put what website in the title of the issue..

**Comment by alessandrojean** [comment]
Closing since it lacks information. Please actually fill the information required again in a new issue.
