### ISSUE TITLE
Cover in Library keep redownload 

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#6859]
### Steps to reproduce

Open Library -> Category -> Scroll Down manga from top to bottom after that scroll Up to back In top

### Expected behavior

The Cover already load or stored in Library don't redownload again, even if more cover image has been download or stored in Library 

### Actual behavior

The Cover repeat redownload as more cover has been download or stored in Library 

### Tachiyomi version

Preview r4224

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

Just Updated to Preview r4224 and notice my Library keep repeating redownload Cover already load or storage in Library, redownload happen  after  more Cover image being stored in Library/Tachiyomi  , have video to more easy identification the problem ( the problem in the last mins)

Previously  Preview have bug which certain cover can load and already be fixed by today update, don't know if this have related issue to cause this new bug https://github.com/tachiyomiorg/tachiyomi/issues/6797

maybe this bug redownload cause by  tachiyomi cache can't go over 300MB, this will just keep stay around 270MB-280MB, seems which cause the old cache get overwritten,  so manga with old cache need to redownload cover again , will attach video too for more easy see the problem

Redownload Bug :  https://drive.google.com/file/d/1yBqMN91FhxmhZLvz-COJ6igIw5x-9JHW/view?usp=sharing

(maybe cause of bug) Cache Problem : https://drive.google.com/file/d/1xwzgTv9_em23yuEw24OK0hZkUzrrJRPe/view?usp=sharing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
If you are on Android 10 or less can you tell what's in `Android/data/eu.kanade.tachiyomi.debug/files/cover`? Mines seems to be just a folder named `custom`. The issue probably is that covers are getting removed for some reason.

**Comment by DchanN** [comment]
> If you are on Android 10 or less can you tell what's in `Android/data/eu.kanade.tachiyomi.debug/files/cover`? Mines seems to be just a folder named `custom`. The issue probably is that covers are getting removed for some reason. Do this after using Tachiyomi without internet for a while so covers doesn't get re-downloaded

After use Tachiyomi without internet, manga which don't have cover become like broken image, and `Android/data/eu.kanade.tachiyomi.debug/files/cover just contain empty folder with custom name 
![Screenshot_20220404-021546902](https://user-images.githubusercontent.com/101858971/161442268-ab923d2f-83f4-4f50-b90e-ca4d18a42f46.jpg)
![Screenshot_20220404-021612191](https://user-images.githubusercontent.com/101858971/161442272-39c5b3dd-2cf9-4eaa-8c72-48e1aa0005f1.jpg)
