### ISSUE TITLE
Lowres on all manga images

### ISSUE THREAD

**Issue by puresoul** [tachiyomiorg/tachiyomi#6863]
### Steps to reproduce

Even after clean reinstall every manga image is on low resolution

### Expected behavior

Manga should be readable

### Actual behavior

![Screenshot_20220404-140739](https://user-images.githubusercontent.com/2646309/161541066-b6987736-1c83-4348-a8a0-ab3f4425ad1c.png)

### Crash logs

--------- beginning of main
04-04 14:00:09.372 20254 20254 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-04 14:00:10.669 20254 20331 E SQLiteLog: (284) automatic index on C(manga_id)
04-04 14:00:10.669 20254 20331 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-04 14:01:24.887 20254 20447 E chromium: [ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -202
04-04 14:01:25.355 20254 20447 E chromium: [ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -202
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 11 (SDK 30)
Android build ID: RQ2A.210505.003-alihasan@ip-172-31-17-218
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: carbon_sweet

### Tachiyomi version

0.13.1

### Android version

Android 11 CarbonRom

### Device

Redmi 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Which Chapter on which Manga on which Source?

**Comment by CrepeTF** [comment]
Can you give an exact example for a series and chapter on which source

**Comment by alessandrojean** [comment]
Usually that means your ROM has a wrong DPI set IIRC, since you're using a custom ROM. You should report it to your ROM developer.

**Comment by puresoul** [comment]
ok, thanks
