### ISSUE TITLE
Add more extensions

### ISSUE THREAD

**Issue by itsmeAeRo** [tachiyomiorg/tachiyomi#6866]
### Describe your suggested feature

Like kiss asian or new asian so more people will find the app more interesting make it more flexible and do more than just manga and anime make it more flexible so people like me can watch k-drama and k-shows please😭😭

### Other details

Add more and post a voting thing to dicide weather we keep tachiyomi and aniyomi toghether or we merge them together so its easy for you focus on two or one app at a time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
no.
