### ISSUE TITLE
Multi Uninstall for Extension 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#6870]
### Describe your suggested feature

I would like to recommend to make multi Uninstall feature for installed extensions.  Because if you uninstall many extensions alternately, it will take too much time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
There are many existing apps on and off the play store already which provide the ability to batch uninstall apps

**Comment by CarlosEsco** [comment]
Use one of the many other apps to uninstall apks
