### ISSUE TITLE
Downloads dont start on their own

### ISSUE THREAD

**Issue by totopesce** [tachiyomiorg/tachiyomi#6871]
### Steps to reproduce

Just let new chapters appear.
They get added to download list, but dont start downloading.

### Expected behavior

New chapters should get added to download list and start downloading.

### Actual behavior

Chapter get stuck on download list, without ever starting, download list isnt paused.
I have to manually change the order of the chapter on the list to get them to start downloading.

### Tachiyomi version

.13.1

### Android version

Android 11

### Device

Xiaomi pad 5

### Other details

I have tachiyomi in autostart, also removed all battery optimizations for the app.
When I open the app and new chapters have come out, normally morning and night, most if not all the chapters are in the downloads list, the list is not paused, but have not started downloading. Have to move the order of the chapters or extensions and the chapters start downloading.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #7492
