### ISSUE TITLE
ReadComiconline saying no pages found when opening comics

### ISSUE THREAD

**Issue by Devthereader** [tachiyomiorg/tachiyomi#6873]
### Steps to reproduce

When I open the book it says no pages found even though I know it has pages.

### Expected behavior

It should open up to the comic issue I select but it doesn’t 

### Actual behavior

Opens up for a second to black screen and kicks you out and says no pages found

### Tachiyomi version

0.13.1

### Android version

7.11

### Device

Samsung Tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
wrong repo and its already been [reported](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11338)
