### ISSUE TITLE
Pages doesn't load

### ISSUE THREAD

**Issue by AaronDragneel** [tachiyomiorg/tachiyomi#6877]
### Steps to reproduce

Pages won't load no matter what source i read from or what ever manga i'm reading it won't Load the pages.. Its just keeps on loading.

### Expected behavior

It should load the pages of a manga or manhwa from every source.

### Actual behavior

It not loading the pages... I tried every extension and it won't load a single page and also extension opens up it shows blank.

### Tachiyomi version

Tachiyomi J2k 1.4.4

### Android version

Android 10

### Device

Xiaomi Pocophone F1

### Other details

BBB
![Screenshot_2022-04-07-13-27-57-973_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/91563049/162149727-051d98ec-b0bd-4a88-9de6-456cb81935df.jpg)
![Screenshot_2022-04-07-13-28-25-711_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/91563049/162149807-6638ee7d-8968-4051-9e2d-4ca564da1510.jpg)
![Screenshot_2022-04-07-13-27-57-973_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/91563049/162149811-ff3dc3b5-af8c-4bc0-9f08-eb0e7fe82384.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Use the troubleshooting guide first. If that doesn't help, please verify that this is an issue in the main app and not J2K before opening another issue.

**Comment by AaronDragneel** [comment]
I did actually and it didn't help
