### ISSUE TITLE
Closing when reading

### ISSUE THREAD

**Issue by zTokoyami** [tachiyomiorg/tachiyomi#6879]
### Steps to reproduce

First i need to say, i´m not a english speaker, so sorry if get a lot of gramatical errors.

 1. Open the tachiyomi
 2. Open a webtoon mode on a especifical cap where's the failure
 3. So start scrolling the page 
 4. One especifical page had the error, that one close your web and get back at the select chap viewer
![Captura de tela 2022-04-07 095542](https://user-images.githubusercontent.com/103194388/162203696-c428db6d-eeff-4d83-8b18-97f8505caae2.png)

https://user-images.githubusercontent.com/103194388/162204481-df529f53-67fa-4ba5-801a-57d6b709a063.mp4

### Expected behavior

Normally shouldn't close like that with no explain... so i don't know what to do 

### Actual behavior

One especifical page had the error, that one close your web and get back at the select chap viewer

### Tachiyomi version

0.13.1

### Android version

12

### Device

Samsung S10E

### Other details

At this moment 8 of the 72 webs that i reed presents that behavior.
On the video, tachiyomi was 0.12.1, but i've already the atualization and nothing has changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
First, you didn't provided crash logs as requested. Second, this is just the classic case when the source put a big image and your phone can't handle it. We can't really do anything about it. Migrate to other sources that splits the images into a lot of smaller ones.
