### ISSUE TITLE
When downloading comics, if the number of pictures in a chapter exceeds 40, the download will fail

### ISSUE THREAD

**Issue by dty285767** [tachiyomiorg/tachiyomi#6880]
### Steps to reproduce

Find comics and download them if there are more than 40 pictures in a single chapter

### Expected behavior

All the pictures should be downloaded

### Actual behavior

Only 40 pictures were downloaded and prompted with errors

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Realme GT Neo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This seems to be source specific, I always managed to download chapters with more pages than that of different sources with success.
