### ISSUE TITLE
I hope to add multi-threaded downloads

### ISSUE THREAD

**Issue by dty285767** [tachiyomiorg/tachiyomi#6881]
### Describe your suggested feature

The number of simultaneous downloads and threads can be selected in the download settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This already exists for multiple sources, and will not be added for the same source as it causes extra constraints on sources.

https://github.com/tachiyomiorg/tachiyomi/issues/1567
