### ISSUE TITLE
Manga covers disappear when switching to Open gl(skia)

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6884]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/162333930-ac7ba600-f254-4c9f-8728-986b9692638e.mp4

android: settings-->developer options --> renderer GPU -->  set Open GL(Skia)

### Expected behavior

covers should not disappear

### Actual behavior

covers disappear after the swotch of the renderer

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8447348/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.1

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

a crash occoured and i think it is related to this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
If i switch back to OpenGL (default) and then restarting tachiyomi, the covers will come back again

**Comment by arkon** [comment]
No plan to fix this unless it's affecting devices with default non-developer settings.
