### ISSUE TITLE
Not updating properly and crashing of app

### ISSUE THREAD

**Issue by Molu2002** [tachiyomiorg/tachiyomi#6888]
### Steps to reproduce

Its like i have 470 mangas and when i tried to update the library it only updates 125 or 127 mangas leave rest of them and when i tried to open a manga in web it crashes the app

### Expected behavior

Sir i just want you to fix the updating bug and crashes bug

### Actual behavior

My library is not updating properly i have 470 mangas it only updates upto 125 mangas plz help 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Samsung galaxy A71 

### Other details

There are no additional details sorry brother i already told you every thing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #6599, it's not a bug.

About the crash, open a new and more descriptive issue about it and attach the crash logs as requested in the issue form.

**Comment by Molu2002** [comment]
Sir what do you mean by the library not updating is not the bug i don't know what to do  it's not updating all the mangas if have solution plzzz tell me 🙏

**Comment by alessandrojean** [comment]
Literally what I said, read #6599.
