### ISSUE TITLE
Mangaowl Change web

### ISSUE THREAD

**Issue by yusireamor** [tachiyomiorg/tachiyomi#6891]
### Steps to reproduce

1. Mangaowl can be browse
2. Host name not verified

### Expected behavior

Cgange mangaowl old web address to the new one Mangaowl.net

### Actual behavior

Can't use mangaowl source 

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong repo.
