### ISSUE TITLE
Manga not saved on the history

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6894]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/162615367-1db02cbc-2df2-42ef-8e9d-0c526893cf67.mp4

1.clear your history
2. open a source
3. open a manga
4. open a chapter directly or use resume button
5. close tachiyomi without coming back
6. check history again

### Expected behavior

The app should save the manga in the history the moment i click on a chapter or the resume button

### Actual behavior

The app only saves the manga in the history if:
1. the whole chapter is read (loading then the next one)
2. without reading the whole chapter (the first one i chose), coming back to the manga screen without closing the app.

### Tachiyomi version

0.13.1

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

I know i used tachiyomiSY but i remember that this bug was also on Tachiyomi when i was using it (end of feb 2022)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed by #7121
