### ISSUE TITLE
Please add landscape UI adaptation

### ISSUE THREAD

**Issue by AimerEGOIST** [tachiyomiorg/tachiyomi#6895]
### Describe your suggested feature

![Screenshot_2022-04-10-19-49-35-832_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/48597571/162616740-4253c9d3-6a12-4139-bddc-cb1b02d7b821.jpg)
![Screenshot_2022-04-10-19-49-44-356_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/48597571/162616743-c85e7be7-1584-4da3-8752-7f5668609976.jpg)
![Screenshot_2022-04-10-19-49-57-626_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/48597571/162616745-5bf49b8a-5da6-4b55-b368-2ac1abd8d29e.jpg)

### Other details

![Screenshot_2022-04-10-19-54-18-648_com android chrome](https://user-images.githubusercontent.com/48597571/162616828-f378cb3b-5117-46c5-ba14-0a3ec3fc3721.png)
The author of tachiyomiSY told me to adjust the dp.But I think this should be adapted by the author.  There are now many tablets in China with similar sizes and resolutions, just like Samsung tablets.  Can it be adapted to the tablet?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
1. Just pasting images doesn't really explain much. Please describe what you actually are requesting
2. If you previously reported it to sy and were told to come here, then atleast give a link to the previous Discussion instead of a screenshot that doesnt really show everything (Like this: https://github.com/jobobby04/TachiyomiSY/issues/571)
3. Explore your settings! There's a setting called "Tablet UI" (you can also use search button in settings) that should do what you want. Find it and use it
4. If you still want help, ask at the [Discord server](https://discord.gg/tachiyomi)

**Comment by AimerEGOIST** [comment]
> 1. Just pasting images doesn't really explain much. Please describe what you actually are requesting
> 2. If you previously reported it to sy and were told to come here, then atleast give a link to the previous Discussion instead of a screenshot that doesnt really show everything (Like this: [Why was the horizontal screen adaptation removed? jobobby04/TachiyomiSY#571](https://github.com/jobobby04/TachiyomiSY/issues/571))
> 3. Explore your settings! There's a setting called "Tablet UI" (you can also use search button in settings) that should do what you want. Find it and use it
> 4. If you still want help, ask at the [Discord server](https://discord.gg/tachiyomi)

Thank you very much!
