### ISSUE TITLE
Replace crop button shortcut in reader bottom buttons with navigation layout options

### ISSUE THREAD

**Issue by tanuukii** [tachiyomiorg/tachiyomi#6896]
### Describe your suggested feature

Similar on how we can set reading mode and orientation type without opening the reader setting sheet. This will also help users to avoid enabling crop borders by accident.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Nah, there's no good reason to be toggling navigation layouts often enough to want a shortcut for that.
