### ISSUE TITLE
Separate filters for "sources" and "extensions" tabs

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [tachiyomiorg/tachiyomi#6897]
### Describe your suggested feature

Right now the filter works for both uninstalled and installed extensions but I would like to filter them separately.
for example filtering by english only then install some english extensions. now I don't want to see any english extension in the uninstalled list anymore but I would like to be able to see them in the installed extensions tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's no good reason to be continuously scrolling through the extensions list and there's also no good reason to selectively want to see different languages between what you want to use and what is available.
