### ISSUE TITLE
manga site not available

### ISSUE THREAD

**Issue by Hiroiq** [tachiyomiorg/tachiyomi#6898]
### Describe your suggested feature

There is a manga site that is not in the application. The site name (Arab Hentai) is a site for manga and Arabic manhwa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Please read and follow what you acknowledge, you're in the wrong repository for that.
