### ISSUE TITLE
[BUG] Manga card is glued to nav bar

### ISSUE THREAD

**Issue by D3xron** [tachiyomiorg/tachiyomi#6902]
### Steps to reproduce

I scrolled to bottom of category and there are no bottom padding of manga card, and its looks like is glued to nav bar. 
![IMG_20220411_154627](https://user-images.githubusercontent.com/46288465/162765412-e6fcbcc9-0136-4712-9936-39b398b979b3.jpg)

### Expected behavior

Manga card should be correctly displayed when scrolling to bottom of the category

### Actual behavior

Manga card is glued to nav bar

### Tachiyomi version

Tachiyomi Preview r4242

### Android version

Android 12

### Device

Xiaomi Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I assume this is with the bottom nav not hiding on scroll? I'm actually not sure that setting makes sense to keep anymore with the new, taller default height in MD3.

**Comment by arkon** [comment]
Closing this as that option is removed as part of larger Compose rewrite efforts.
