### ISSUE TITLE
[Bug] Random zooming

### ISSUE THREAD

**Issue by Tonicross360** [tachiyomiorg/tachiyomi#6904]
### Steps to reproduce

When I start reading a manga sometimes it starts making zoom in some parts by its own, I don't know if this is an actual thing or a bug. It happens with any extension. And It started happening when I updated to the last version.

### Expected behavior

It shouldnt zoom unless I double click.

### Actual behavior

Instead like I have already explained It randomly zooms in some parts by itself. 

### Tachiyomi version

0.13.2

### Android version

Android 10

### Device

Xiaomi Redmi 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This is a new default behavior of the reader, that zooms into the height of the page to help facilitate reading wide images in portrait mode. To disable this, disable zoom landscape images in the reader settings
