### ISSUE TITLE
skip updating not working

### ISSUE THREAD

**Issue by Apxcalyps3** [tachiyomiorg/tachiyomi#6906]
### Steps to reproduce

1.  go to settings then library
2.  go to skip updating
3.  choose the specific filters you wanted
4.  perform global update

### Expected behavior

update filter reduces the amount of updating chapters based on the filters selected 

### Actual behavior

1. go to settings then library
2. choose skip updating
3. choose the desired library update filter
4. perform global update
5. updates the whole library and ignores the filters

### Crash logs

none

### Tachiyomi version

0.13.2

### Android version

Android 9

### Device

Huawei Nova 3i

### Other details

happened after 0.13.2 update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's still skipping them, as shown in the notification afterwards. The main updating progress notification just shows the number to make the people who freaked out about the smaller number feel like the app is doing something.
