### ISSUE TITLE
library lag

### ISSUE THREAD

**Issue by great-yasi** [tachiyomiorg/tachiyomi#6907]
### Steps to reproduce

after i updated to <stable 0.13.2>
1. open the updated tachiyomi app
2. update my library
3. browse my updates to check for new chapters (after updating my library)
4. check my library
5. scroll up my library to select the series with the fewest additional chapter

### Expected behavior

i should have been able to scroll down on my library list.

### Actual behavior

i could not scroll down until the middle portion because the app started to hang or lag... i tried to close and re-open the app several times since updating yesterday.

### Crash logs

##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-01-04 12:52:24","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-01-07 17:29:17","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-01-15 00:10:17","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-01-21 23:09:38","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-01-27 14:50:34","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-02-03 15:37:27","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-02-10 12:18:44","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-02-17 08:05:56","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.7.0.6","appVersionCode":"10806","clientDate":"2019-02-25 21:20:16","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-03-03 09:02:22","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-03-11 10:11:36","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-03-17 11:28:46","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-03-24 21:56:16","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-04-03 07:35:17","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-04-07 09:14:59","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-04-14 10:57:33","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-04-21 22:50:43","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-04-29 22:25:55","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.8","appVersionCode":"11108","clientDate":"2019-05-05 09:54:16","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-05-12 11:21:44","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-05-21 20:37:45","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-05-26 12:34:05","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-06-02 12:05:28","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-06-09 13:31:21","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-06-16 12:51:14","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-06-23 00:49:51","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-06-30 00:16:59","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-07-08 17:02:57","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-07-14 11:21:48","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-07-21 21:08:18","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-07-28 19:28:28","pluginBaseVersionName":"1.1.1"}##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.vivo.browser","appVersionName":"5.8.0.9","appVersionCode":"11109","clientDate":"2019-08-05 06:50:10","pluginBaseVersionName":"1.1.1"}

### Tachiyomi version

0.13.2

### Android version

android 7.0

### Device

vivo 1714

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably related to #6846. Seems to be specific to Android 7, but I currently can't test in Android 7 emulators on my machine.

**Comment by great-yasi** [comment]
i reverted back to 0.12.3 as hinted be @arkon (👍 thanks by the way). hope the latest version will be android friendly. 🙏
