### ISSUE TITLE
Random zooming in Manga panels

### ISSUE THREAD

**Issue by Proffesor666** [tachiyomiorg/tachiyomi#6908]
### Steps to reproduce

After updating to 0.13.2 some manga pages just zoom in for no reason. If I open "Fate of the Returned hero" on Mangasee Chapter 16 first page the problem can be seen

### Expected behavior

There should be no zoom

### Actual behavior

There is zoom on random manga pages on any server and manga

### Tachiyomi version

0.13.2 

### Android version

10

### Device

Mi mix 2s 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Not a bug, turn off zoom landscape image if you don't want this to happen. Read the changelogs please
