### ISSUE TITLE
App exited by itself after the new update 

### ISSUE THREAD

**Issue by EishethEZ** [tachiyomiorg/tachiyomi#6909]
### Steps to reproduce

After the new update, whenever I open a new chapter or continue to read a chapter. It will show loading screen (no picture shown) then exit from the app. Before the update, there was no bug. After the update, app exited by itself without any notifications. 

### Expected behavior

Supposedly after clicking the chapter. It will load smoothly and I can read it, but after the new update. It will load, then the app exited to my main homepage. 

### Actual behavior

After the new update, whenever I open a new chapter or continue to read a chapter, It will load, then the app exited to my main homepage. 

### Tachiyomi version

0.13.2

### Android version

Android 8

### Device

Huawei Nova Lite 2 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Update your extensions.
