### ISSUE TITLE
Line spacing is higher than it should be

### ISSUE THREAD

**Issue by senkneel** [tachiyomiorg/tachiyomi#6910]
### Steps to reproduce

After the newest Stable update the line spacing for everything that has more than one line of text is higher than normal. Takes up a lot of space and looks weird.

### Expected behavior

Line spacing should be normal.

### Actual behavior

It looks like that:
![Screenshot_20220411-1536132](https://user-images.githubusercontent.com/102804833/162945144-6d113dba-0aae-429c-9d45-c4eb7ac97f54.jpg)
![Screenshot_20220412-123429](https://user-images.githubusercontent.com/102804833/162945276-11889af3-cff1-4075-b6cc-124888643c7d.jpg)

### Tachiyomi version

0.13.2

### Android version

Android 11

### Device

OnePlus 8 Pro

### Other details

Started in the newest update, the same in all forks I have checked.
I have all font settings on default on my phone and my language in German, if that helps.
Also nothing with the line spacing changes even if I change the font or font size on the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is the current Material Design default.

**Comment by Riztard** [comment]
report to Material Design then :D
