### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Azry808** [tachiyomiorg/tachiyomi#6912]
### Steps to reproduce

The mangas will not resume where I last read. I keep getting a start tab

### Expected behavior

The mangas will not resume where I last read. I keep getting a start tab

### Actual behavior

The mangas will not resume where I last read. I keep getting a start tab

### Tachiyomi version

0.13.2

### Android version

Android 12

### Device

Samsung s10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It'll always show start if you haven't actually read the first chapter. Mark chapters as read as needed.
