### ISSUE TITLE
40 Updates Skipped

### ISSUE THREAD

**Issue by ZyporeGG** [tachiyomiorg/tachiyomi#6914]
### Steps to reproduce

Just Basically Update the Library or the Updates Section

### Expected behavior

It Should've updated all since i just recently fixed the source of the individual manga

### Actual behavior

It Skipped 40 yesterday now 42

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8477279/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.2

### Android version

Android 8

### Device

Oppo A5s

### Other details

![IMG_20220413_083316](https://user-images.githubusercontent.com/78833352/163076190-7a13faa8-0a92-4f35-9570-b89c01d31ba7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Press "learn more".
