### ISSUE TITLE
Auto detect latest backup file

### ISSUE THREAD

**Issue by z0xrv** [tachiyomiorg/tachiyomi#6918]
### Describe your suggested feature

When the app is freshly installed, it should detect the latest backup file in Tachiyomi/Backups and prompt to the user that there's a backup detected and ask to load it

### Other details

This behavior is found on signal messaging app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
They have a hard coded backup location, Tachiyomi does not, it allows you to store it anywhere

**Comment by z0xrv** [comment]
Yeah, but I meant the app should check tachiyomi/Backups and it finds the backup file, ut asks the user if he wants to restore it.

**Comment by SafvanKhWork** [comment]
Kind of like 'pure writer' app found on play store . FYI: it also has flexible  backup location

**Comment by arkon** [comment]
Merging with #4138
