### ISSUE TITLE
Skip updating: Disallow enable started and unread restriction simultaneous 

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#6919]
### Describe your suggested feature

1st option overwrite the 2nd one, so turn both on must not be possible

### Other details

A menu in this template for the first two options would be clearer (since both could not be activated at the same time)
https://user-images.githubusercontent.com/76596575/155619458-aa6ed043-27b5-4242-978f-2e7c7a7a5620.png

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The restrictions can apply to different entries, so this request isn't valid.
