### ISSUE TITLE
Being able to mark manga in library and having filter for marked manga 

### ISSUE THREAD

**Issue by ariMrashid** [tachiyomiorg/tachiyomi#6920]
### Describe your suggested feature

Just like how you can mark chapters and filter the chapter to show (or not show ) marked chapters, it would be very useful to be able to do the same for the manga in your library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Just create a category and add those manga to that category
