### ISSUE TITLE
Mangalek

### ISSUE THREAD

**Issue by GTO212** [tachiyomiorg/tachiyomi#6921]
### Steps to reproduce

Classes are not opened because of the cloudfire

### Expected behavior

Solve the cloudfire problem

### Actual behavior

لم يتم حل المشكلة

### Crash logs

مشكله الكلود فاير تواجهنا بستمرار ارجو حل المشكلة بسرع وقت

### Tachiyomi version

 0.13.2

### Android version

 Android version11 

### Device

Samsung A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please actually read what you acknowledged instead of just checking all the boxes.
