### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Mazegratz** [tachiyomiorg/tachiyomi#6923]
### Steps to reproduce

well it's been three days but the Lara Manga is not fixed
![Screenshot_2022-04-14-23-20-37-04_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/103662918/163422588-3321b708-13ac-4fac-9fe3-c711fe5234ba.jpg)

### Expected behavior

I hope to fix the Lara Manga

### Actual behavior

it's been three days that the Lara Manga is not fixed I can't see the webtoon and manga

### Crash logs

![Screenshot_2022-04-14-23-20-37-04_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/103662918/163422432-770adc1e-3f10-4c14-b02a-2c93cc815cd4.jpg)

### Tachiyomi version

0.13.2

### Android version

Android 11

### Device

Oppo reno 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mazegratz** [comment]
> If

please open, thankyou

**Comment by alessandrojean** [comment]
It's an extension issue, not an app issue, so no point into reopening.
