### ISSUE TITLE
App Crashes when i start downloading a chapter

### ISSUE THREAD

**Issue by AUselessGod** [tachiyomiorg/tachiyomi#6924]
### Steps to reproduce

1. i open the app
2. i press download on a chapter
3. The app crashes after a few seconds

### Expected behavior

The chapter should be downloaded

### Actual behavior

The app crashes everytime i start a download.

### Crash logs

App version: 0.13.2 (standard, 2b38b4e, 78, 2022-04-10T16:23Z)
Android version: 10 (SDK 29)
Android build ID: RMX2027_11_A.67
Device brand: realme
Device manufacturer: realme
Device name: RMX2027
Device model: RMX2027
Device product name: RMX2027

### Tachiyomi version

0.13.2

### Android version

Android 10

### Device

realme RMX2027

### Other details

The problem started right after i updated the app today.
It was working fine before

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Update your extensions
