### ISSUE TITLE
Implement more flexible tracking filtering

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6926]
### Describe your suggested feature

Currently, the filtering for tracking in library appears to work in an "OR" mode, where if you select them all, it shows the ones tracked by any of them. I propose there be more flexibility, where you can either:
- Change it to act like an "AND", or:
- specify it MUST include a given tracking service
I imagine you can have another symbol in each checkbox (along with unselected, check, or minus) that means it will have to include that service. 

### Other details

This feature request is related to #1899 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favor of #6958
