### ISSUE TITLE
Entry chapter filter - ux suggestion

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6927]
### Describe your suggested feature

Move the filter button in the chapter listing, so it can be accessed without scrolling up to the top. 

this will help in cases like when you have the 'unread' filter on and accidentally mark it as read somehow, and need to go back. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This does seem sensible to be consistent with the library, but would it be better to push the share or download items into the overflow?

**Comment by CrepeTF** [comment]
If it does happen, keep downloads

**Comment by FourTOne5** [comment]
> If it does happen, keep downloads

Agree. I personally use Download more than I use share. Since filter button is just 1 item just moving share will be enough.
