### ISSUE TITLE
Search by Genre

### ISSUE THREAD

**Issue by FaizaanAzmat** [tachiyomiorg/tachiyomi#6929]
# **Suggested Feature:**

There should be a search by **Genre** option which will list all the manga in a particular extension by the selected genre. 

### Other details:

For example, 
If I select **fantasy** in "extension" , it will list all the manga tagged "**Fantasy**" in that particular extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kou9221** [comment]
Aren't sources from tachi supposed to have at least one genre you're looking for? Tachi have 1k+ source so it's not too hard to search for good source and if that is implemented your search will be too long to load.

**Comment by alessandrojean** [comment]
This is source dependant, not all websites have this feature of filtering search results by genres. However, if the website from the source does have it and the extension doesn't have this filter, you can request it to be added by filling an feature request in the extensions repository (not the app one).

**Comment by kou9221** [comment]
And there's also a filter by genre in every source, though I can't guarantee they have all

**Comment by FaizaanAzmat** [comment]
> This is source dependant, not all websites have this feature of filtering search results by genres. However, if the website from the source does have it and the extension doesn't have this filter, you can request it to be added by filling an feature request in the extensions repository (not the app one).

But the app should have the feature to search the genre tags so as to list all the stuff tagged with that particular genre.

**Comment by FaizaanAzmat** [comment]
> And there's also a filter by genre in every source, though I can't guarantee they have all

I haven't seen that anywhere, would you mind sharing one with me?

**Comment by kou9221** [comment]
> > And there's also a filter by genre in every source, though I can't guarantee they have all
> 
> I haven't seen that anywhere, would you mind sharing one with me?

![Screenshot_20220415-130213_Tachiyomi.png](https://user-images.githubusercontent.com/98811570/163522366-2371862b-ba67-4484-a4e0-efe39673662c.png) 

here, just don't click the "latest" when you're in sources tab because it's not supported i think

**Comment by kou9221** [comment]
> > > And there's also a filter by genre in every source, though I can't guarantee they have all
> > 
> > I haven't seen that anywhere, would you mind sharing one with me?
> 
> ![Screenshot_20220415-130213_Tachiyomi.png](https://user-images.githubusercontent.com/98811570/163522366-2371862b-ba67-4484-a4e0-efe39673662c.png)

**Comment by FaizaanAzmat** [comment]
>![Screenshot_20220415-130213_Tachiyomi.png](https://user-images.githubusercontent.com/98811570/163522366-2371862b-ba67-4484-a4e0-efe39673662c.png) 
> 
> here, just don't click the "latest" when you're in sources tab because it's not supported i think

Thanks, for the information. I think I should file this repository in the extensions section, so that they can add this feature to the extensions which currently don't have this feature.
