### ISSUE TITLE
show end-of-chapter prompt as popup instead of entire page

### ISSUE THREAD

**Issue by jacklinzoho** [tachiyomiorg/tachiyomi#6930]
### Describe your suggested feature

There should be an option to show the end-of-chapter prompt as a popup, or don't show it altogether.  The current full-page gets in the way when e.g. the 'chapter' is actually just a single page, which happens pretty often.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3079
