### ISSUE TITLE
Filter third-party self-promo pages by skipping last x pages per chapter

### ISSUE THREAD

**Issue by jacklinzoho** [tachiyomiorg/tachiyomi#6931]
### Describe your suggested feature

the scangroup promo pages that gets included at the end of chapters can get very obnoxious and flow-breaking, especially when it includes some full-sized image.  especially especially if it includes some kind of retexted manga panel begging for donations.  There should be options to filter them out.

Simplest way I can think of: option to skip the last x pages per chapter for specific manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/3274
