### ISSUE TITLE
Update Notification

### ISSUE THREAD

**Issue by LoRd4Sec** [tachiyomiorg/tachiyomi#6936]
### Steps to reproduce

Problem: There is no direct update notification, the notification is done manually when opening the application

### Expected behavior

What must happen is that when there is an update from the latest chapter or chapter an update notification appears immediately, when the application update this feature does not exist.

### Actual behavior

There is no notification that appears when updating the latest chapter or chapter

### Tachiyomi version

0.13.2

### Android version

Android 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6599
