### ISSUE TITLE
We want to add features

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi#6939]
### Describe your suggested feature

1- A feature of chatting and discussing between users of the application.
2- The evaluation features of the same sources

### Other details
Chat and discussion format
![Screenshots_2022-04-16-12-03-19](https://user-images.githubusercontent.com/87826849/163669127-bf3541d2-3511-42a1-a4f9-ea191dbfc880.png)

Format for rating sites 6.9 stars
![Screenshots_2022-04-16-12-09-12](https://user-images.githubusercontent.com/87826849/163669247-a903aff7-14d8-483e-a7be-7d225e7517ef.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
no.

**Comment by yemenihandsome** [comment]
@loocool2 Why not why?
