### ISSUE TITLE
Error when creating a backup

### ISSUE THREAD

**Issue by fukwho** [tachiyomiorg/tachiyomi#6941]
### Steps to reproduce

Example:

1. Go to "Backup and restore"
2. Select  "Create backup"
3. Select what to backup
4. Select folder where the backup file will be sent to

### Expected behavior

After selecting which the folder the backup file will go to, there shouldn't be any error and the backup file should be created.

### Actual behavior

Notification saying "java.lang.ArrayIndexOutOfBoundsException: length=0; index=0" and the backup file is not created

### Crash logs

```
--------- beginning of main
04-16 13:47:18.686 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:20.726 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:22.768 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:24.809 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:26.850 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:28.893 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:30.905 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:32.948 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:34.989 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:37.033 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:39.075 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:41.118 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:43.121 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:45.139 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:47.140 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:49.141 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:51.142 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:53.155 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:55.157 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:57.158 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:47:59.159 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:01.161 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:03.163 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:05.165 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:07.166 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:09.167 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
04-16 13:48:11.168 24845 24859 E anade.tachiyom: failed to connect to jdwp control socket: Connection refused
App version: 0.13.3 (standard, 28522f4, 79, 2022-04-15T20:39Z)
Android version: 11 (SDK 30)
Android build ID: lineage_jasmine_sprout-userdebug 11 RQ3A.211001.001 10042829
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: jasmine_sprout
Device model: Mi A2
Device product name: lineage_jasmine_sprout
```

### Tachiyomi version

0.13.3

### Android version

Android 11 (LineageOS 18.1)

### Device

Xiaomi Mi A2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Hard to tell what's the issue here, but it sounds like a scuffed ROM.

**Comment by fukwho** [comment]
By scuffed ROM do you mean the OS or the storage has some kind of problem?

**Comment by arkon** [comment]
At what point do you see the error? Can you post a screenshot?

**Comment by fukwho** [comment]
The first 2 screenshots are just before the error.

The last one is what i see.

**Comment by arkon** [comment]
You didn't post any screenshots?

**Comment by curche** [comment]
Are you perhaps trying to backup an empty library? Just checked this issue because I use the same device however with a custom ROM that's based on Android 12

While I usually use tachiyomi preview/sy, I did a fresh install of the app and tried creating a backup to get that error on empty library.
However after just adding one random manga, the error no longer appears

**Comment by fukwho** [comment]
> You didn't post any screenshots?

Sorry forgot to add the link. 
https://imgur.com/a/99TUb6h

**Comment by fukwho** [comment]
> Are you perhaps trying to backup an empty library? Just checked this issue because I use the same device however with a custom ROM that's based on Android 12
> 
> While I usually use tachiyomi preview/sy, I did a fresh install of the app and tried creating a backup to get that error on empty library.
> However after just adding one random manga, the error no longer appears

I'll try that.

**Comment by fukwho** [comment]
Thanks @curche it solved the problem. Maybe it should be added in the FAQ, so no one has this problem again
