### ISSUE TITLE
Doujindesu

### ISSUE THREAD

**Issue by Anonimgithing** [tachiyomiorg/tachiyomi#6943]
### Steps to reproduce

Exstensi atau sumber aplikasi tidak menampilkan gambar dan tidak dapat di baca

### Expected behavior

Setiap kerusakan harus di beritahukan kepada pembaca supaya pembaca tau bahwa sumber sedang bermasalah 

### Actual behavior

Untuk memudahkan pembaca

### Crash logs

Pembaruan selalu gagal dan terlewat

### Tachiyomi version

Sudah terbaru

### Android version

11

### Device

Google

### Other details

Ah entahlah pusing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
