### ISSUE TITLE
Mark as read on chapter transition

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#6944]
### Steps to reproduce

1. Open any manga with only one page (Ex. Part-Time Immortal - 78).
2. Instead of reading (not scroll to the end of the page), go back.
3. The chapter will be marked as read.

https://user-images.githubusercontent.com/7441934/163685778-eb8dd9d2-80f4-4af1-a51e-cbbf0eac7ac1.mp4

### Expected behavior

Shouldn't be marked as read. 

### Actual behavior

Marked as read.

### Tachiyomi version

0.13.3

### Android version

Android 10

### Device

Umidigi A9 Pro

### Other details

All the manga could be marked as read on the transition between chapters (or of last chapter message) to avoid unwanted marked. Or at least an option to choose wich behavior use. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. Single-page chapters are a rare edge case.
2. Transition views can be disabled.

That is to say, this behaviour won't be changed.
