### ISSUE TITLE
Crash on global search

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#6945]
### Steps to reproduce

1. Set global search to only fixed.
2. Search for "99 Ga Kansuto No Sekai De Level 800 Man Kara Sutato".
3. The app will close.

### Expected behavior

Show the manga found, or the message of not found.

### Actual behavior

The app close.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8500452/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs (1).txt](https://github.com/tachiyomiorg/tachiyomi/files/8500453/tachiyomi_crash_logs.1.txt)

### Tachiyomi version

0.13.3

### Android version

Android 10

### Device

Umidigi A9 Pro

### Other details

There were others, even on older versions, but I don't remember the name.

I have some obsolete extension, but they are working fine (Mangá Host, OTKsScanlator, Reaper Scans). And how it also happened before they became obsolete, I don't think it's in the extensions.

List of fixed source:
![1](https://user-images.githubusercontent.com/7441934/163687608-3831773f-be55-492c-855d-16ad14e8160f.jpeg)
![2](https://user-images.githubusercontent.com/7441934/163687609-99de4a17-5330-4126-a5b4-6a7049f79c94.jpeg)
![3](https://user-images.githubusercontent.com/7441934/163687611-586a1f0a-89ff-43a2-bbda-ab167a074011.jpeg)
![4](https://user-images.githubusercontent.com/7441934/163687613-0cdebef4-318d-4e1c-b6e7-5607998329bf.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Uninstall hitomi

**Comment by alessandrojean** [comment]
Also uninstall any obsolete extensions.

**Comment by joaoandre120** [comment]
> Uninstall hitomi

Thanks, it really was hitomi, is there a possibility to add an exception, so the app don't crash and close? I'll also open an issue on the extension.

**Comment by arkon** [comment]
Hitomi is known to make the app run on out of memory because of how it works. It likely won't be addressed.
