### ISSUE TITLE
Make an alternative way to trigger show menu. 

### ISSUE THREAD

**Issue by Gitlyx** [tachiyomiorg/tachiyomi#6948]
### Describe your suggested feature

**Request** 
Just like settings>reader>actions> "show in long tap", make it possible to toggle navigation menu in the same way.

**Reason**
Too often I accidentally touch the screen while reading, which opens the menu making me have to hide it again. This happens to me a lot while scrolling slowly or resting my thumb close to the screen. Would be super nice to have a toggle function that disables the menu activation on single tap allowing for a more zen-like reading mode. 

### Other details

Make the feature act like: 
settings>reader>actions> "show in long tap". But for the navigation menu instead. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.
-
Edit: renamed issue.

**Comment by CrepeTF** [comment]
Long press is already being used by the page options to save, share and set page as cover

**Comment by Gitlyx** [comment]
Would there be possible to implement double tap as an alternative option to trigger show menu?

**Comment by arkon** [comment]
Double tapping is zoom.

I hate to sound rude, but the solution to not triggering something by tapping is to not tap it. We can reconsider if this somehow seems like a common issue, but it hasn't been brought up before.
