### ISSUE TITLE
No me deja instala tachiyomi

### ISSUE THREAD

**Issue by Samcomal** [tachiyomiorg/tachiyomi#6949]
### Steps to reproduce

Buenas noches les comento que ya tenia instalado la app, pero al querer actualizar no me dejaba hacerlo, entonces lo desinstale para poder instalarlo con la nueva actualizacion pero ya no me deja, sera que le puedan ayudar a 8nstalar porfavor

### Expected behavior

Esperaba a que se instalara en mi celular 

### Actual behavior

No me deja instalarlo, me sale la leyenda que no se instalo

### Crash logs

No puedo instalarlo

### Tachiyomi version

v0.13.2

### Android version

Android 11

### Device

Xiaomi Redmi note 9 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#how-do-i-migrate-from-the-f-droid-version
