### ISSUE TITLE
Tachiyomi not opening in Nokia 2 (stable v0.13.3)

### ISSUE THREAD

**Issue by irfanshadikofficial** [tachiyomiorg/tachiyomi#6950]
### Steps to reproduce

Downloaded the latest version of tachiyomi v0.13.3,
but facing this problem since last update of the app.
Not opening the app, just showing the loading page.

### Expected behavior

Should have opened the app

### Actual behavior

The problem is nothing happens, apps not opening at all.

### Tachiyomi version

v0.13.3

### Android version

Android 7.1.1

### Device

Nokia 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce in an Android 7.1.1 emulator. Please consider uninstalling extensions/reinstalling the app/etc. if you have a backup.

**Comment by irfanshadikofficial** [comment]
@arkon already tried reinstalling so many times, (clearing app data, reinstalling extensions too), but the can't fix the problem. It just shows that blue loading page and logo, can't get in even after opening the for an hour. Having this issue from previous update, it was all good until then.

**Comment by arkon** [comment]
Merging with #7006
