### ISSUE TITLE
Compose rewrite issues

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#6951]
This is a tracking issue for various problems with the Jetpack Compose rewrite.

General:
- [x] No fast scroll
- [ ] Different ripple color
- [ ] Performance issues
- [x] No appbar elevation lift on content scroll
- [x] Inconsistent incognito/downloaded only banner visibility
- [x] Inconsistent controller/screen/scaffolds
- [ ] Missing range selection in library
- [ ] No tooltips (e.g., appbar actions; https://issuetracker.google.com/issues/171674404)

History:
- [x] Date grouping is repeated
- [x] Appbar elevation isn't reset when scrolled back to the top
- [x] General performance issues (should look into `@Stable`/`@Immutable` usage)
- [x] Padding of reset checkbox option in remove dialog
- [x] Broken/failed to load covers don't show the placeholder
- [x] Jumping to next section when an item is deleted
- [x] Nav bar inset padding needs to be adjusted
- [x] History/library data being lost on SQL upgrade for some users

**Comment by CrepeTF** [comment]
Eviscerate ripple

![Screenshot_20220417-174710_Tachibear.png](https://user-images.githubusercontent.com/70870719/163724393-bb01b533-75ad-421f-bcb6-bad9bc62850b.png)

**Comment by ghostbear** [comment]
> * [ ]  Jumping to next section when an item is deleted

Might be related to https://github.com/cashapp/sqldelight/issues/2591 and/or https://github.com/cashapp/sqldelight/issues/2434 as it also crashes when deleting on last page

**Comment by stevenyomi** [comment]
Currently having a bunch of issues related to missing state updates:
- #7418
- #7834
- #7866

**Comment by arkon** [comment]
Breaking out the library selection issue to #8071.

The other remaining ones are either already individual issues are broad enough that we'll address them when possible (e.g. tooltip support).
