### ISSUE TITLE
Update library error

### ISSUE THREAD

**Issue by mahdii3375** [tachiyomiorg/tachiyomi#6953]
### Steps to reproduce

Hi
In this new version, updating library has slowed down and frequently it show error that can't update around 15% of my library. I have to try update again 3 to 4 time until all of my library get updated. Please solve this problem.
Thanks

### Expected behavior

The previous version was awesome. Please change back updating setting of app to how it was previously.

### Actual behavior

.

### Tachiyomi version

0.13.3

### Android version

11

### Device

Poco x3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Read #6599
