### ISSUE TITLE
Wrong sort icon on the library

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6954]
### Steps to reproduce

![IMG_20220418_113421](https://user-images.githubusercontent.com/75091899/163789201-fa716015-cff5-4463-bdf0-dc1c479325b9.jpg)
the descending and ascending order are technically reversed on the library.
i suggest to simply reverse the arrow icon replacing the ↓ with ↑ and viceversa. i like the descending order being first as default (as it is now, so don't change it)

### Expected behavior

ascending and descending orders with the right icon

### Actual behavior

ascending and descending with wrong icons

### Tachiyomi version

0.13.3

### Android version

android 8

### Device

huawei p8 lite 2017

### Other details
if you check you can see the sorting of manga is the opposite the icon direction.
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
This is where it gets into semantics.  I agree with you
 but the up arrow can also signify that you have the earliest at top vs the arrow signifying that you are going to descend the alphabet

**Comment by Palloxin** [comment]
ah, yes you are right. the icons in the alphabet order is fine.
![IMG_20220418_123709](https://user-images.githubusercontent.com/75091899/163796862-a0ff2205-9348-49ed-b1d5-4c710e83494e.jpg)
the last 2.. i don't know what it sorts based on.

**Comment by arkon** [comment]
Isn't an up arrow normally used for ascending order?

**Comment by Palloxin** [comment]
> Isn't an up arrow normally used for ascending order?

yes.
Ascending order meaning change based on context:
alphabetic--> from a to z
time--> from start to end; example from year 2000 to 2004 "last read"
quantity--> from 1 to 10 "by total chapters"
in my opinion it should in this way

**Comment by arkon** [comment]
Ascending alphabet is A to Z. What are you proposing exactly?

**Comment by Palloxin** [comment]
the alphabet sorting is already in this way on the app. I propose to swap the sorting order of these circled:
![163796862-a0ff2205-9348-49ed-b1d5-4c710e83494e](https://user-images.githubusercontent.com/75091899/164036044-12d84dc0-502a-499b-a0ca-bb4f9baffa65.jpg)
the last 2 i don't know what thet sort based on.

**Comment by arkon** [comment]
Currently when ascending:

1. Alphabetically: A to Z
2. Last read: most recently read to longest ago
3. Last checked: most recently checked to longest ago
4. Unread: 1, 2, 3, etc.
5. Total chapters: 1, 2, 3, etc.
6. Latest chapter: newest chapter to oldest chapter
7. Date fetched: most recently fetched to longest ago
8. Date added: most recently added to longest ago

If so, then is the proposal to flip 2, 3, 6, 7, and 8?

**Comment by Palloxin** [comment]
so the unread sorting works in that way, my bad then. Yes, the proposal is to flip 2,3,6,7 and 8
