### ISSUE TITLE
Only updates 5 manga

### ISSUE THREAD

**Issue by UNA08** [tachiyomiorg/tachiyomi#6957]
### Steps to reproduce

1. Go to Updates
2. Click Update Library

### Expected behavior

All manga updates should show up in the Updates Menu.

### Actual behavior

It only updates 5 manga.

### Tachiyomi version

0.13.3

### Android version

Android 8.1.0

### Device

OPPO A5s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6599
