### ISSUE TITLE
Query duplicate content of the current manga source

### ISSUE THREAD

**Issue by JimmyMisl** [tachiyomiorg/tachiyomi#6960]
### Describe your suggested feature

Is it possible to query for duplicate content based on the current manga source (library)? Generally speaking, the same content on the same website should only contain one valid ID. Whether the current collection of comics can be queried based on the sorting of the source IDs has duplicate content. When there are many comic collections, the problem of duplicate collections often occurs , and it is likely that there is only a difference in the names of the sinicization groups

### Other details

In addition, is it possible to add an automatic classification function, for example, when I select comic source A to save, it will be automatically saved as category A; when I select comic source B to be saved, it will be automatically saved as category B. What I'm trying to say is that it will automatically help me categorize, rather than requiring me to manually choose which tag to put in, you know there's a chance of misplacement and not finding it.
Also, can the multi-file migration function of TachiyomiJ2K be implemented on Tachiyomi?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't understand this request. Please detail the expected steps of how it would work.

Also, make 1 issue per request please, if there isn't already an existing one.

**Comment by JimmyMisl** [comment]
这是来自Jimmy邮箱的自动回复邮件。
您好！我已收到您的邮件，感谢您的来信，我会尽快给您回复。
