### ISSUE TITLE
Unable to delete downloaded chapters, auto or manually

### ISSUE THREAD

**Issue by Anan5a** [tachiyomiorg/tachiyomi#6961]
### Steps to reproduce

Download chapter of a manga for offline
Finish reading (Donno if it's necessary)
Try deleting the chapter

### Expected behavior

Delete the downloaded chapter

### Actual behavior

Nothing happens 

### Tachiyomi version

0.13.3

### Android version

11

### Device

Realme x2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Since you're using Android 11:

https://tachiyomi.org/help/faq/#android-11

Only way is to use that adb command or deleting manually through a file manager.

**Comment by Anan5a** [comment]
Tachiyomi can download but not delete?

Sorry for NSFW,

**Comment by alessandrojean** [comment]
Deleting ≠ creating files.

All help you need is in the link I sent.

**Comment by arkon** [comment]
There's likely no actual correlation in that observation. Android 11+ is generally slow with file operations and potentially more-so on Chinese devices.

Closing in favor of #4286

**Comment by Anan5a** [comment]
Default category stuff are working fine, some manga on the nsfw category doesn't work (deleting) . I'm kinda confused. If it's SAF related it should behave same for all the manga right?

**Comment by Anan5a** [comment]
@arkon I've been trying to delete stuff and found something which I believe is a bug.

Sometimes chapter marked as read aren't deleted (manually) if I mark them unread and then try to delete it it delete without problem!!

Because of nsfw I'm not adding screen recording, if you want to see it I can send it some other way
