### ISSUE TITLE
Library and sources problems 

### ISSUE THREAD

**Issue by Viva1HA** [tachiyomiorg/tachiyomi#6963]
### Steps to reproduce

Just opened the app and checked the library 

### Expected behavior

Icons should be there, and mangatown source should open

### Actual behavior

After opening my libray i noticed everything in my library that's from mangatown had black manga covers
So i went to setting and refreshed the manga covers, but not only did it not work but other sources like manga katana had black covers .
Also when i try reading something from these sources, it just keeps loading.
This problem happened to me in the past with another manga source, i had to transfer every manga to another one :(

### Tachiyomi version

App version: 0.13.3 

### Android version

9

### Device

Razor phone 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please open the issue in the correct repository.
