### ISSUE TITLE
Mangalek issue

### ISSUE THREAD

**Issue by XOCV0** [tachiyomiorg/tachiyomi#6965]
### Steps to reproduce

1. Open mangalek sourse
2. Go to any manga
3. Open any chapter
4. Issue here (failed to bypass cloudflare

### Expected behavior

The chapter should load

### Actual behavior

Failed to bypass cloudflare

### Tachiyomi version

1.4.5 TachiyomiJ2K

### Android version

10

### Device

Huawei nova 7i 

### Other details

Please fix the issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please read what you acknowledge instead of just checking all the boxes. There's also an open issue about it in the correct repository already.
