### ISSUE TITLE
Add scroll speed for webtoon reader

### ISSUE THREAD

**Issue by rafalou38** [tachiyomiorg/tachiyomi#6966]
### Describe your suggested feature

In the webtoon mode settings, add a slider going from 0 to 1

1: scroll a full page
0.5: scroll a half page
...

### Other details

By scroll speed I'm referring to the scroll that happen when you click on the screen or press the sound buttons.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #2785
