### ISSUE TITLE
Crashes when trying to do global search

### ISSUE THREAD

**Issue by mattmorrow6** [tachiyomiorg/tachiyomi#6967]
### Steps to reproduce

Ever time I click a title to see it on the other apk  the app crashes 

### Expected behavior

When I click the title to search globally  it should bring up each place to read Manga from and show if they have that manga.

### Actual behavior

It starts to load the global search then crashes the app

### Tachiyomi version

0.13.3

### Android version

Android 12

### Device

Samsung galaxy s22

### Other details

Does on all Manga I try.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Uninstall Hitomi if you have it, and also uninstall any obsolete extension. See if it works after it.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
