### ISSUE TITLE
Manatoki ext's Override BaseURL setting is no longer honored

### ISSUE THREAD

**Issue by FoxSays** [tachiyomiorg/tachiyomi#6969]
### Steps to reproduce

1. Install Tachiyomi to 0.13.2 or later
2. Change Override BaseURL setting on NewToki / ManaToki v.1.2.22
3. Open any comic from this source or attempt to browse this source.

### Expected behavior

Tachiyomi should connect to the URL provided in Override BseURL setting.

### Actual behavior

Instead, it ignores the setting completely and attempts to connect to manatoki161.net - the default setting. Since the URL leads nowhere, nothing from this source gets loaded. 

### Tachiyomi version

0.13.2 and 0.13.3

### Android version

Android 10

### Device

Pixel 5

### Other details

As near as I can tell, only NewToki / ManaToki extension is affected. However, since nothing has changed in the extension and it still works fine for 0.13.1 and earlier, I have concluded that something must have changed in the main app to cause this behavior. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

You should open the issue in the correct repository, as it seems the extension itself needs some update.
