### ISSUE TITLE
Missing ellipsis in small screens on the extensions tab

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi#6972]
### Steps to reproduce

1. Have a device with a small screen.
2. Use a language with more larger phrases (like Portuguese or Spanish).
3. Open the Extensions tab on Browse.

### Expected behavior

The extension name and other details (language, version and obsolete/non official labels) should get ellipsis at the end when the screen is small and the Settings button is larger.

### Actual behavior

The text doesn't get ellipsis and gets underneath the Settings button.

![image](https://user-images.githubusercontent.com/14254807/164569447-76203373-f190-409c-97f5-4ce213f2885a.png)

### Tachiyomi version

r4277

### Android version

Android 12

### Device

Samsung Galaxy S20+

### Other details

Something to be probably addressed in a Compose rewrite of this tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably to be addressed after a Compose rewrite.

**Comment by alessandrojean** [comment]
Just a note that it's somehow still happening in the Compose version.

<img src="https://user-images.githubusercontent.com/14254807/172908672-3a834a00-40d4-472d-b48b-6394ee346986.png" width="350">
