### ISSUE TITLE
The "Crop Borders" feature does not work well

### ISSUE THREAD

**Issue by qwertea** [tachiyomiorg/tachiyomi#6976]
### Steps to reproduce

It really happens for a lot of manga pages, but one example is "Hazure Waku no Joutai Ijou Skill de Saikyou ni Natta Ore ga Subete wo Juurin Suru made" from the source LHTranslations. 

Go to chapter 2, page 12.

### Expected behavior

The image should be cropped to remove the white borders from all sides, including the right, left, top, & bottom sides. Something like this (manually cropped pic):
![Screenshot_20220422-132703_1](https://user-images.githubusercontent.com/24505745/164644712-9c7184e8-cc4f-4e18-b471-0fa30e796b9e.png)

### Actual behavior

It only gets cropped from the left:
![Screenshot_20220422-131703](https://user-images.githubusercontent.com/24505745/164643908-92496bab-786f-4b08-a626-4d6dc1370207.png)

### Tachiyomi version

0.13.3

### Android version

Android 11

### Device

Redmi Note 10 Pro

### Other details

The raw image for reference:
![Hazure Waku no Joutai Ijou Skill de Saikyou ni Natta Ore ga Subete wo Juurin Suru made - Chapter 2 - 12 (1)](https://user-images.githubusercontent.com/24505745/164643789-09048c55-63fe-4464-a946-e7b4728de04e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
Not a bug, just a bad image.

![image](https://user-images.githubusercontent.com/63973749/164669433-a03ac614-563e-4504-9d73-debb3134b22a.png)

**Comment by qwertea** [comment]
Oh. Well that was dumb, I'll close the issue. Hard to see black borders on amoled phones 😅
