### ISSUE TITLE
Thousands of duplicate pages downloaded

### ISSUE THREAD

**Issue by Ashburner0** [tachiyomiorg/tachiyomi#6977]
### Steps to reproduce

1. Download manga
2. Continue downloading manga as chapters update
3. Find that your phone storage is getting full and there is thousands of duplicate images "manga pages" on your phone.

### Expected behavior

Downloads should only download one image each

### Actual behavior

Downloads multiple of the same image

### Tachiyomi version

0.13.3

### Android version

12

### Device

Samsung Galaxy Note 10 Plus SM-N975W

### Other details

``![Screenshot_20220422-081412_My Files](https://user-images.githubusercontent.com/104202773/164704165-830766d6-b69a-41b4-be2a-fb25c5351f66.jpg)
![Screenshot_20220422-081450_My Files](https://user-images.githubusercontent.com/104202773/164704191-767a20f8-5447-4c1b-8d65-7da6d518ba81.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not an app issue if you're downloading the same thing from different sources.

**Comment by Ashburner0** [comment]
Sorry forgot to add that I only have one source in my library. I had no knowledge or ability to see that there is duplicates downloaded. I'm guessing this come from a mixture of moving manga to different sources and the android bug where the app won't delete chapters. Basically the issue is, if you remove a manga from library and the files aren't deleted, there is no way of knowing that those files still exist. 
![Screenshot_20220422-162602_Tachiyomi](https://user-images.githubusercontent.com/104202773/164782038-28288515-d2f9-4cda-84d4-06f41c4cf2bb.jpg)

**Comment by arkon** [comment]
See #1767/#2108.

The folders show what source they're from.

**Comment by Ashburner0** [comment]
![Screenshot_20220422-162552_Tachiyomi](https://user-images.githubusercontent.com/104202773/164783104-15a17849-7ccd-48ae-bcf8-0137cd731674.jpg)
The folders are directly in my phone storage. I'd have to go through every folder to find duplicates.
