### ISSUE TITLE
Keeps stopping on launch

### ISSUE THREAD

**Issue by Sakko-Nuuru** [tachiyomiorg/tachiyomi#6978]
### Steps to reproduce

Same as #6846

### Expected behavior

Same as #6846

### Actual behavior

Same as #6846

### Crash logs

Same as #6846

### Tachiyomi version

0.13.3

### Android version

Android 7

### Device

Symphony Symtab 60

### Other details

I couldn't reopen issue #6846 so that's why I created this. It was supposed to be fixed in 0.13.3, but it didn't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please provide more details to work with.

**Comment by Sakko-Nuuru** [comment]
I'm tired of this happening for 2 months now. I've made the move and
switched to another manga reader. Sorry I can't provide more info because
I've deleted Tachiyomi and have no plans to install it again.
