### ISSUE TITLE
Battery Saver settings - update restrictions and app mode

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6980]
### Describe your suggested feature

1) add 'android battery saver enabled' to be a library update restriction -- this way it doesn't run when the battery is low
2) when android battery saver is active, turn on the app's battery saver features (ie, animations off,  etc.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The first suggestion was added, but I'm decline the second one. Controlling animations per-app isn't really normal, nor does it really impact battery life much.
