### ISSUE TITLE
Weird delete behavior

### ISSUE THREAD

**Issue by Anan5a** [tachiyomiorg/tachiyomi#6986]
### Steps to reproduce

See additional details below

### Expected behavior

Delete files

### Actual behavior

Weird

### Tachiyomi version

0.13.4

### Android version

11

### Device

Realme x2

### Other details

  I've been trying to delete stuff and found something which I believe is a bug.

Sometimes chapter marked as read aren't deleted (manually) if I mark them unread and then try to delete it it delete without problem!!

Non nsfw example

https://user-images.githubusercontent.com/16373480/164497201-174588a9-546a-45e2-95ad-b55c55ead1fd.mp4

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#4286 for file operation issue. UI was rewritten since this issue was created.
