### ISSUE TITLE
Bring Ignore/Overwrite back to "Save Image"

### ISSUE THREAD

**Issue by AXVin** [tachiyomiorg/tachiyomi#6988]
### Describe your suggested feature

hey, earlier when i used to "Save Image" on the same one multiple times, it wouldn't do anything but now it creates duplicates.
I didn't even notice this until my Pictures/Tachiyomi folder started taking massives amounts of storage.
is there a way to somehow get the old functionality back?
i.e. either overwrite/ignore if a file already exists.
This could be a config option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
For reference: https://stackoverflow.com/questions/60632273/mediastore-contentresolver-insert-creates-copies-instead-of-replacing-the-exis

**Comment by Platiplus** [comment]
Working on it!
