### ISSUE TITLE
App closes when search new manga 

### ISSUE THREAD

**Issue by foottus** [tachiyomiorg/tachiyomi#6989]
### Steps to reproduce

1 open app
2 search for a new title or migrate extension
3 after waiting a little the app closes 

### Expected behavior

Show me the title at all my extensions to add a new manga or migrate extension 

### Actual behavior

After one or two minutes at maximum the app closes itself. It happens for several weeks in different versions 

### Tachiyomi version

0.13.4-4290

### Android version

Android 12

### Device

Samsung Galaxy S20FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Make sure you (1) don't have Hitomi installed and (2) don't have any obsolete extensions installed.

**Comment by arkon** [comment]
Post crash logs if the above aren't applicable.
