### ISSUE TITLE
Previous page automatic download

### ISSUE THREAD

**Issue by UNKNONYM0US** [tachiyomiorg/tachiyomi#6991]
### Describe your suggested feature

I hope this feature will be implemented because it helps me due to unable to recall what happened previously on the comics I'm reading because I have 100+ comics waiting for updates and reading and I can't remember what happened previously on most of them especially those comics that are taking too long to update. So I manually download it and it's quiet tiring if a lot of updates get updated and u gotta manually download every previous pages and reorder the download so that the previous page will be the 1st to download. I did this just in case I run out of data/sudden internet u stability or took too long to load. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can easily adapt the app to your needs by adjusting when download chapters are deleted.

**Comment by UNKNONYM0US** [comment]
Make the "after reading automatically delete the last chapter"?
