### ISSUE TITLE
Trouble with MangaOwl

### ISSUE THREAD

**Issue by AliceDragonSoul** [tachiyomiorg/tachiyomi#6993]
### Steps to reproduce

Going inn on source MangaOwl
Tapping on a manga
Tapping the "start" button or at a chapter 
 

### Expected behavior

When I tap the "start" button or a chapter I would expect to get to read the Manga. 

### Actual behavior

When I'm at the source MangaOwl and tap the "start" button or a chapter it pops up a black background and a message furthest down on the screen saying "finner ingen sider" in norwegian (I'm guessing it would be something like "can't find any sides" in english) 

### Crash logs

content://eu.kanade.tachiyomi.provider/ext_storage/3862-6262/Android/data/eu.kanade.tachiyomi/cache/tachiyomi_crash_logs.txt

### Tachiyomi version

0.13.4

### Android version

Android 8

### Device

HUAWEI MediaPad M5 lite 10

### Other details

This problem suddenly appeared either the 21. or the 22. of April 2022. It only happen when I use the source MangaOwl and it happens on all of the Mangas I have tested. I mainly use MangaOwl because I often can't find the Mangas I read anywhere else. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
