### ISSUE TITLE
The image couldn't be loaded

### ISSUE THREAD

**Issue by Txtbook7** [tachiyomiorg/tachiyomi#6995]
### Steps to reproduce

Any chapters that I try to read in app display the message in the title. I can read them through the WebView however.

### Expected behavior

This shouldn't happen

### Actual behavior

Attaching screenshot 

### Crash logs

![Screenshot_20220423-233016_Tachiyomi](https://user-images.githubusercontent.com/104288473/164955369-a891a34b-a8ef-495e-964f-4a608ecc4f0c.jpg)

### Tachiyomi version

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)  

### Android version

Android version: 12 (SDK 31) 

### Device

Device brand: samsung Device manufacturer: samsung Device name: c2q Device model: SM-N986U

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If this is specific to a source, open an issue in the extensions repo.

If not, provide actual reproduction steps.
