### ISSUE TITLE
Zoom Landscape Image - not working as intended

### ISSUE THREAD

**Issue by Infiziert90** [tachiyomiorg/tachiyomi#6997]
### Steps to reproduce

Any Manga with mixed images:
Open page
Wait a second

### Expected behavior

No zoom at all for non Landscape images

### Actual behavior

App starts zooming randomly into the manga page

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

Huawei P30 Pro

### Other details

Occurring since the last update.
Disabling "Zoom landscape images" removes it (its active by default now) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> any manga with mixed pages

Please provide concrete examples which anyone reading this can test. Specify a source/manga/chapter where you're facing this

Also useful if you can provide a video recording of it
Example of it working for me: 
https://cdn.discordapp.com/attachments/566585518171881493/942312591231954944/screencam_20220213_122135.mp4

**Comment by curche** [comment]
Oh nvm. I misinterpreted, my bad
Everything's working as intended. The concern was Zoom Landscape is enabled by default by the app

**Comment by zayin02** [comment]
https://user-images.githubusercontent.com/76571965/164965959-5c3a0044-ef8c-4c8c-9ad7-116654892dde.mp4

**Comment by arkon** [comment]
Can't produce. You're saying that the "Zoom landscape images" setting isn't respected?

**Comment by Infiziert90** [comment]
> Can't produce. You're saying that the "Zoom landscape images" setting isn't respected?

With activated "zoom landscape images" will tachiyomi start randomly zooming in on any type of picture.
So even if the pic is clearly not landscape (like 99% of Manga pages) the app will still try to scale it.

Disabling the option makes tachiyomi act normal.

**Comment by arkon** [comment]
Do you have concrete examples for reproduction steps?

**Comment by arkon** [comment]
No info given.
