### ISSUE TITLE
Please add an Extension for Mangareader.to

### ISSUE THREAD

**Issue by tegutistgut** [tachiyomiorg/tachiyomi#6999]
### Describe your suggested feature

Hello,
My suggestion is to add a extension for the Website https://mangareader.to

Thats it. 
Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Wrong repo + already requested
