### ISSUE TITLE
Give option to hide skipped and failed chapter update notifications

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [tachiyomiorg/tachiyomi#7000]
### Describe your suggested feature

Please give an option to hide these notifications, having these big notifications all the time is honestly making it hard to use since there is no space for any other notifications. Or at least throttle them, like show them once a day or something like that.
I get that the manga I didn't start is getting skipped, but I don't need to read it every time I want to update the others that I do actually read.

Also, I don't know if this is a bug or not but my mobile browser is set to Firefox and failed update details is still getting opened in chrome while the skipped one is opening in Firefox.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
just disable them through your android settings and app info

**Comment by YetAnotherDevWannabe** [comment]
You can't disable them without disabling the whole app from giving notifications. So not really helping since you don't know when you have new updates.

**Comment by arkon** [comment]
Notification channels are supported on Android 8+. There's no desire to add redundant support for older less used versions of Android.

**Comment by YetAnotherDevWannabe** [comment]
I have Android 10 but with MIUI 12, might be a Xiaomi limitation ? Or maybe I can but never found it :) I'll chekc what notifications channels are.
