### ISSUE TITLE
Downloaded only / Incognito mode switches show "true"/"false"

### ISSUE THREAD

**Issue by glasszay** [tachiyomiorg/tachiyomi#7004]
### Steps to reproduce

1. Install Preview r4299
2. Click on more

### Expected behavior

The toggle switches are displayed as either on/off

### Actual behavior

The Boolean values are being displayed over the toggles.
![Screenshot_20220424_190926_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/76571965/164988199-8d0a1e8c-c6c6-4fe4-95c6-8efa53a65b61.jpg)

### Tachiyomi version

Preview r4299

### Android version

Android 10

### Device

Huawei P30 lite

### Other details

I looked if there were any issues open/closed for this (couldn't find one).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
This is a issue with the compose library and is not being addressed for now

**Comment by arkon** [comment]
Pending https://issuetracker.google.com/issues/228336571
