### ISSUE TITLE
Webtoon split images 

### ISSUE THREAD

**Issue by spicysweetboy** [tachiyomiorg/tachiyomi#7005]
### Steps to reproduce

1. Open any webtoon
2. The images are split

### Expected behavior

They should be whole

### Actual behavior

They are split. This same issue happened to me before, someone had a fix, but I think a recent update brought back the issue.

### Tachiyomi version

Preview r4299

### Android version

Android 11

### Device

Motorola Moto g7 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Mention the source too

**Comment by zayin02** [comment]
Make sure your crop border setting is off in webtoon. (If the issue isn't extension specific)

**Comment by FourTOne5** [comment]
> Make sure your crop border setting is off in webtoon. (If the issue isn't extension specific)

Crop borders does not split images

**Comment by arkon** [comment]
Can you detail actual reproduction steps that someone else can follow to reproduce the problem?

And also post screenshots?

**Comment by spicysweetboy** [comment]
It seems to happy to a number of different sources, but not to every series from a source - that's why I assumed it wasn't source specific. These examples come from Webtoons.com

![Screenshot_20220424-105307](https://user-images.githubusercontent.com/64571873/164998975-e12f664d-9e1d-4982-8f92-78f9cac12322.png)
![Screenshot_20220424-105315](https://user-images.githubusercontent.com/64571873/164998978-6e91dbb2-72ef-4dc5-9e82-8eda37f2e89b.png)
![Screenshot_20220424-105343](https://user-images.githubusercontent.com/64571873/164998980-0edfc323-23f1-42b1-88a6-2075f355a2ac.png)
![Screenshot_20220424-105349](https://user-images.githubusercontent.com/64571873/164998981-fb9c0b0d-2f01-4d61-9d46-28c7bd8e9454.png)
![Screenshot_20220424-105515](https://user-images.githubusercontent.com/64571873/164998982-3b988701-e53d-458f-bd55-88a6a7759421.png)

**Comment by arkon** [comment]
Turn off crop borders.

**Comment by spicysweetboy** [comment]
> Turn off crop borders.

I did. That was the previous fix that worked last time. But now Cropped borders is off but the issue has come back...
