### ISSUE TITLE
Feature: Manga Migration Screen - New source should show latest chapter number or last modified/upload date

### ISSUE THREAD

**Issue by pkozuchowski** [tachiyomiorg/tachiyomi#7007]
### Describe your suggested feature

When user is manga screen and selects Options -> Migrate, new sources should display when the latest episode was uploaded or what is the latest chapter on each source.

Rationale:
Sometimes manga is not uploaded on current source anymore and if that happens, I'm migrating to new source, but there's no way to tell if the new source is updated or not. 
![image](https://user-images.githubusercontent.com/4470967/164991327-ba0150a0-44ff-473f-ba72-ef7d96f530c6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This has been declined before as it requires an additional network call for every search result, which would too excessive and likely just result in performance issues and sources wanting to block Tachiyomi.

**Comment by pkozuchowski** [comment]
@arkon In that case, would it be feasible to create a new button to do the callout? In that case, we wouldn't call every source needlessly, but 1 or 2 to check if other source is up to date.

**Comment by CrepeTF** [comment]
You can just hold on one of the manga to bring up their info
