### ISSUE TITLE
possible addition to the "only search pinned extensions"global search

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/tachiyomi#7009]
### Describe your suggested feature

add an additional feature tied to "search only pinned extensions" like "search other extensions"
 for when your desired manga was not found in the sources u chose to pin

### Other details

this would make the existing option dual purpose ,serving as a sort of favourite/often used extension and if those didn't return a result u can with this get directed to searching in the other extensions u didn't pin as an in-depth or thorough advanced search

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6654 instead
