### ISSUE TITLE
Automatic Download Settings do not work as intended with categories

### ISSUE THREAD

**Issue by the-codinator** [tachiyomiorg/tachiyomi#7013]
### Steps to reproduce

This is a follow-up from #6541 because the settings have only been renamed but still do not work. The earlier issue has been closed without proper validation / verification. The repro steps are the same.

Tested on latest version: 0.13.4

### Expected behavior

Chapters are automatically downloaded for all categories not explicitly excluded

### Actual behavior

Auto download does not work for any categories

### Tachiyomi version

0.13.4

### Android version

9

### Device

OnePlus 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by the-codinator** [comment]
Screenshots of latest test:

![Screenshot_20220425-085853.jpg](https://user-images.githubusercontent.com/4411711/165160356-71343f10-4f41-4132-ac01-dd1b35aae130.jpg)

![Screenshot_20220425-085900.jpg](https://user-images.githubusercontent.com/4411711/165160382-cb7882db-4459-4bf8-a0ce-f28951f191aa.jpg)

**Comment by arkon** [comment]
The commit that closed it hasn't even been released yet, what are you testing?

**Comment by the-codinator** [comment]
Oh, my apologies... I thought this went out with the 0.13.4 release recently. Closing and will re-open if needed.

**Comment by FourTOne5** [comment]
He's testing on 0.13.4 

For clarification code wise the issue has been fixed but for end user the fix will be included in next stable or preview build

**Comment by FourTOne5** [comment]
He's testing on 0.13.4 

For clarification code wise the issue has been fixed but for end user the fix will be included in next stable or preview build
