### ISSUE TITLE
Delete manga button missing in tablet UI

### ISSUE THREAD

**Issue by rini94** [tachiyomiorg/tachiyomi#7014]
### Steps to reproduce

1. Go to Settings -> Advanced -> Tablet UI. Set it as always. Restart the app.
2. Select a manga in the library.
3. The option to delete the manga is missing.

### Expected behavior

Delete option should be displayed after 'Mark as unread' option in tablet UI similar to normal UI.

### Actual behavior

When I select a manga in the library, five options are usually displayed - Set categories, Download unread chapters, Mark as read, Mark as unread, and Delete.

In normal UI the delete option is displayed, but in tablet UI the delete option is missing.

### Tachiyomi version

0.13.4

### Android version

Android 9

### Device

Alcatel 3T10

### Other details

Attaching screenshots of normal and tablet UI with the issue marked:

![Normal UI](https://user-images.githubusercontent.com/18500746/165170353-0143e5f7-e2d3-4f94-8ab0-ede4a27df818.png)

![Tablet UI](https://user-images.githubusercontent.com/18500746/165170375-3a336225-44cf-4d2e-ad68-9b465112bdcf.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
your device is not large enough/ your dpi is not high enough so that toolbar is pushed offscreen. While there is the manual option of enabling the tablet view on non-tablet devices, that does not mean that you should and will cause visual glitches such as that

**Comment by CrepeTF** [comment]
You can set your dpi/ minimum dp in android's developer settings

**Comment by rini94** [comment]
The tablet is 10 inch but the dpi maybe low I agree. But if you look at the screenshot there is obviously a lot of space left where it would fit if properly aligned similar to other components.

**Comment by arkon** [comment]
Unless the width is 720dp (which is what it's designed for and I assume it's not since you had to force the tablet layout), this isn't a valid issue.
