### ISSUE TITLE
Migrating/copying an unread manga marks ch 0 as read

### ISSUE THREAD

**Issue by punoqun** [tachiyomiorg/tachiyomi#7020]
### Steps to reproduce

1. Find a manga with a chapter 0, add to the library
2. Migrate/copy it to a different source with chapters selected
3. New entry will have the chapter 0 as read

### Expected behavior

Chapter 0 should be unread in the new manga entry

### Actual behavior

Chapter 0 is marked as read

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Samsung S8

### Other details

https://github.com/tachiyomiorg/tachiyomi/blob/5afff31f7246d0ede03344c955a47f4817e9fb92/app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchPresenter.kt#L119

probably on this line, caused by the 0f

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed with #7331
