### ISSUE TITLE
creat nomedia with cover image

### ISSUE THREAD

**Issue by Aahnafwifi212** [tachiyomiorg/tachiyomi#7021]
### Describe your suggested feature

With the cover.jpg image there should be a .nomedia file
other wise my gellary will get full.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You mean for local manga?

**Comment by Aahnafwifi212** [comment]
yeah but not only local, when i edit cpver it also creat a  folder with that name in local and has the cover.jpg inside, but not any nomedia file, so it should creat a nomedia with the cover image
