### ISSUE TITLE
Add app settings to the backup

### ISSUE THREAD

**Issue by z0xrv** [tachiyomiorg/tachiyomi#7023]
### Describe your suggested feature

Basically what I mean is that if the app settings are included in the backup, there'll be no need to set the settings over after restoring from a backup.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#1857
