### ISSUE TITLE
[Feature request] Update Order

### ISSUE THREAD

**Issue by tonizombie** [tachiyomiorg/tachiyomi#7024]
### Describe your suggested feature

Id like to request to add a setting where you can switch the update order.

For example: Update last read titles first, Update in alphabetic order, Has no unread chapters first.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by tonizombie** [comment]
Didnt find same feature request in github but after searching discord i found msg by arkon "There's no practical reason for it to exist"

**Comment by curche** [comment]
To clarify a bit more and for future reference:
Refer https://github.com/tachiyomiorg/tachiyomi/commit/65062b4bcbe65ffc75a6c5e656d39c91be327d63
> **Remove library update order setting**
> This doesn't make sense to have if the intention is to have reasonably sized global updates. Opting to remove it to remove complexity instead.
