### ISSUE TITLE
Edit details (genre) of a non-local manga in the library

### ISSUE THREAD

**Issue by bluaxees** [tachiyomiorg/tachiyomi#7025]
### Describe your suggested feature

As of the latest version, this is only possible by loading a local manga and editing the json config. This can help improve filtering, primarily for manga with missing genres/tags. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#4398
