### ISSUE TITLE
Can't view downloaded chapters

### ISSUE THREAD

**Issue by laszlosipos** [tachiyomiorg/tachiyomi#7027]
### Steps to reproduce

1. Downloaded some chapters of any manga from any source
2. Closed and reopened the app

### Expected behavior

Should still be downloaded

### Actual behavior

Chapters don't show as downloaded and can't view them

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Xiaomi MI A3

### Other details

The chapters are downloaded, I can see the files on my phone, but the app doesn't find them.
Also I had Berserk downloaded from mangadex a while ago, and I can view that, but not newly downloaded manga.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arozaqf** [comment]
Temporary workaround backup and restore
