### ISSUE TITLE
WebView freezes the app

### ISSUE THREAD

**Issue by donmor** [tachiyomiorg/tachiyomi#7030]
### Steps to reproduce

- Open the summary page of any item in bookshelf
- Click `WebView` there and the app freezes

### Expected behavior

The summary page of the book on the source site should be opened

### Actual behavior

App freezes

### Crash logs

--------- beginning of system
04-28 13:33:26.553 25334 25353 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 13:37:25.369 27851 27871 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 13:38:08.397 28300 28319 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 13:38:45.851 28470 28489 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 13:41:07.200 30153 30173 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 13:41:49.145 30528 30553 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 14:41:07.878 20835 20855 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 14:45:17.589 25480 25500 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 14:48:36.790 26969 26989 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 14:52:44.239 27966 27988 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
--------- beginning of main
04-28 15:00:50.480 30553 30572 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 15:00:54.854 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.854 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.854 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.864 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.865 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:00:54.866 30553 30553 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:01:03.476 30682 30700 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
04-28 15:01:03.476 30682 30700 E DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
04-28 15:01:03.478 30682 30700 E DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
04-28 15:01:03.586 30682 30682 E ResourceType: Style contains key with bad entry: 0x01010586
04-28 15:01:03.588 30682 30682 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:01:03.588 30682 30682 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:01:03.588 30682 30682 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:01:03.660 30682 30682 E ResourceType: Style contains key with bad entry: 0x0101058c
04-28 15:01:03.661 30682 30682 E ResourceType: Style contains key with bad entry: 0x01010604
04-28 15:01:03.661 30682 30682 E ResourceType: Style contains key with bad entry: 0x01010605
04-28 15:01:03.827 30682 30720 E SQLiteLog: (284) automatic index on C(manga_id)
04-28 15:01:03.827 30682 30720 E SQLiteLog: (284) automatic index on R(manga_id)
04-28 15:01:03.827 30682 30720 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 8.1.0 (SDK 27)
Android build ID: Flyme 8.1.5.3A
Device brand: Meizu
Device manufacturer: Meizu
Device name: 16th
Device model: 16th
Device product name: meizu_16th_CN

### Tachiyomi version

0.13.4

### Android version

Android 8.1

### Device

Meizu 16th

### Other details

The app also freezes on doing `Clear WebView data` in Settings.

Downgrading to 0.13.0 could be a temporary workout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Might be fixed in 0.13.5.
