### ISSUE TITLE
User-Agent switching for WebView

### ISSUE THREAD

**Issue by donmor** [tachiyomiorg/tachiyomi#7033]
### Describe your suggested feature

Put an option in Settings -> Browse -> User-Agent
to switch the user-agent used by WebView between Desktop Mode and Mobile Mode. Or just add a Desktop Mode checkbox to the appbar overflow menu on WebView.

### Other details

This is because that some sources removed the account system entrances from their mobile websites, forcing users to use their apps. This can be hacked by switching to desktop mode in browser, signing in, and switching back to mobile. Also, this could be helpful if there are bugs on mobile version of the webpages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
User-Agents are mainly handled extension side to bypass blocks and stuff and to provide stats for friendly sites so it'll be better to ask it in extension repo for each affected site.

**Comment by donmor** [comment]
I see. But it could be nice if users can override this. and this should be simple enough: `mWebView.getSettings().setUserAgentString("some kinds of ua");` (written in java as I'm a green hand at Kotlin).

**Comment by arkon** [comment]
If a source requires cookies from a variant of the website that's served with a particular user agent, it'd need to have that user agent set at the extension level anyway so that requests actually include that.

I'm not sure being able to change the user agent manually would be useful.

**Comment by donmor** [comment]
> If a source requires cookies from a variant of the website that's served with a particular user agent, it'd need to have that user agent set at the extension level anyway so that requests actually include that.
> 
> I'm not sure being able to change the user agent manually would be useful.

It will, I think... The cookies of manga.bilibili.com can be accessed by both webview and extension in both desktop and mobile mode (usually mobile in extension), but can only be created in webview by manual sign-in operation. Now we have to use desktop mode because they removed the sign-in entry of mobile website, making it impossible to create the cookies with account signed in.

**Comment by alessandrojean** [comment]
If they removed the sign in through the mobile website, it's nothing related to Tachiyomi. Use their own app to read paid content if you need it.

**Comment by donmor** [comment]
But it is possible to access the paid chapters if signed in under desktop mode, I think... At least it 
is tested to work in browsers, which usually come with desktop/mobile switching.

**Comment by alessandrojean** [comment]
The Chinese version of the Bilibili extension doesn't support the WebView sign in IIRC, that is just implemented in their international website source. It will not help it anyway. You can request to it to be added to the extension, but it's not guaranteed it will be added.

Closing since this is something that needs to be addressed in the extension and not the app.
