### ISSUE TITLE
Block all "Open links in apps" attempts

### ISSUE THREAD

**Issue by donmor** [tachiyomiorg/tachiyomi#7034]
### Describe your suggested feature

Ignore all "Open links in apps" requests from the webpage in WebView.

### Other details

This is considered reopening #6812 . `android.webkit.WebViewClient.shouldOverrideUrlLoading` could be the thing we needed to solve this problem, as we can just return true on any requests that causing ERR_UNKNOWN_URL_SCHEME in WebView.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have a particular page/click path as an example? It's already always `shouldOverrideUrlLoading`-ing.

**Comment by donmor** [comment]
Browse -> Chinese (HANS) -> `哔哩哔哩漫画` -> WebView -> Open any of the comics inside.

**Comment by donmor** [comment]
`https://manga.bilibili.com/m/detail/mc*****`

**Comment by alessandrojean** [comment]
I think this is a Bilibili Manga website issue, they seen to do a check if it's opened in WebView and try to redirect it to their app (maybe their own app implement WebView in some places like announcements or something similar that when have a link to a title, it gets redirected to their app screen).

Ideally it's something that would need to be bypassed at extension level maybe, by setting another User-Agent or something similar, but I don't know if it's really possible.

**Comment by donmor** [comment]
22.5.23 - Glad to see a separate working Bilibili Manga plugin. Over.
