### ISSUE TITLE
WebView (Tachiyomi Preview Version App)

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi#7044]
### Steps to reproduce

Load error during session

### Expected behavior

The WebView should load the session correctly

### Actual behavior

When trying to log in with Disquis, the Login web just doesn't advance and stays at "Loading..."

### Crash logs

![Screenshot_20220429-113505_Tachiyomi](https://user-images.githubusercontent.com/101371218/165995357-4fd54a63-4ad8-4f30-84ce-4ac1a78c864f.jpg)
 
The WebView does not go beyond there

### Tachiyomi version

Preview r4299

### Android version

Android 12

### Device

Samsung 10+

### Other details

I use the Preview app, and I try to log in to the app's website to comment manga, but the above mentioned happens, obviously I can just switch to the stable version of the app, but for some reason I feel more comfortable in the preview hehe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can open the page in a regular browser to interact with them. Disqus functionality isn't relevant to supporting app functionality.

**Comment by edmxn** [comment]
Sometimes it's a bit tedious, but it's ok, thank you very much for answering, I guess I'll use the stable version hehe
