### ISSUE TITLE
Feature Request: Update Limiting on Recently Updated Manga

### ISSUE THREAD

**Issue by ultrabear** [tachiyomiorg/tachiyomi#7046]
### Describe your suggested feature

Preface: while using the feature to ignore checking for updates if a manga already has a chapter unread, I noticed it didn't solve a more impactful issue: I read a chapter when it comes out, and then it checks for an update the next day, even though it probably wont get an update for a week/month

I propose to add an addon feature to update limiting to also not update manga that have recently been updated(gotten a new chapter) for some configurable length

I think for my and others usecase this would significantly lower network use and update time, as recently updated manga are unlikely to have a new chapter, it saves time checking

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
This is applicable for high quality sources only. Some sources do re-uploads when there are some issues, might upload chapters irregularly or split chapters into parts. I see this feature only targeted for a subset of users.

**Comment by ultrabear** [comment]
I do see the issues with that, which is why I would suggest it as an opt in feature, not default, the feature would benefit from being settable per source/manga, although per source configs don't seem to exist afaik (making it more costly to write) and per manga config would be confusing (as most per manga settings have to do with the reader, not download/update management)
I still think it would be useful to a portion of users (even w/o per manga/source config), that (like myself) just gravitate towards big sites, and it doesn't nessesarily hurt to have a feature thats not universally wanted/needed (ex: reader settings to recolor manga, incognito mode, fingerprint lock, dns over https

**Comment by lenrik1589** [comment]
I think my request is almost the same as the original, but I think about the issue a bit differently, let me introduce to you:
Cycled library updates
Every title In the library gets one special extra tag `updateCyclesSkipped` or for simplicity: `updatePriority`
And one extra setting: update cycle source limit, integer signified by N
When updating the library:
1. All titles will increase their priority by 1
2. App will assemble full list of all the titles that should be updated
3. The list will be split into different lists, based on their source
4. From each sublist then N titles are selected at random but only with highest priority
5. The selected titles are updatedtheir priority reset to 0

In my mind, this should solve "10k titles update" problem

**Comment by arkon** [comment]
Closing in favour of #5885 / #6154
