### ISSUE TITLE
Bug - Feature Request: Failed updates notification

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7048]
### Steps to reproduce

I noticed that when doing a global update in my library the error notification doesn't actually show me any error regarding missing sources. However this error will show normally when updating a single category. 

I did a test and changed the global updates filter categories to include all categories except for one. Then the notification worked out normal again without this bug. 

### Expected behavior

Show full List of errors in the notification.

### Actual behavior

Some errors do not get reported in global update but the error will get reported normally when global update excludes at least category.

### Feature request related to this bug

I suggest creating a separate notification (with new notification_ID) for missing sources error. And make it clickable and manually dismissible (i.e., doesn't disappear when clicking it).
Upon opening the notification a view would show up with a list of missing sources, how many manga coming from each source, and the language. And most importantly add an install button to allow to quickly install sources.

**Comment by arkon** [comment]
Can't reproduce, "Source not found" errors show up in the log even with no categories explicitly selected for global updates.

Please reopen with consistently reproducible steps if you figure that out.

**Comment by saud-97** [comment]
Did you try to update with dead sources (they show as ID only) and with missing sources (not installed)? Sense I have a mixture of these sources in my library.

**Comment by arkon** [comment]
Those 2 scenarios are ultimately the same thing. I tested with an extension uninstalled.

Again, do reopen this (or another issue if this gets locked) if you find consistently reproducible steps.

**Comment by saud-97** [comment]
I just deleted 400 chapters from my library and now the notification is working as expected. Weird. Now regarding the feature request shall I modify this issue or create a new one?

**Comment by arkon** [comment]
There's an existing issue for having an in-app UI for the errors. It wouldn't really be worth tracking the feature request until after that exists.
