### ISSUE TITLE
Sort Manga by least read is not working

### ISSUE THREAD

**Issue by raziel100** [tachiyomiorg/tachiyomi#7055]
### Steps to reproduce

1. Choose to sort by last read

### Expected behavior

It should sorted by last read or the opposite depending of your choice

### Actual behavior

Is randomly putting in the list

### Tachiyomi version

App version: 0.13.4-4338

### Android version

Android 11

### Device

Samsung a02

### Other details

After commit 7773dea to address issue #6954 it has stopped working correctly for last read 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by noxan-dev** [comment]
https://user-images.githubusercontent.com/59417659/166399035-107eeee5-1344-451a-8445-bb55e0205684.mp4 this is from my point of view. I get the same issue
