### ISSUE TITLE
latest chapter sort is broken r4338

### ISSUE THREAD

**Issue by bghyt** [tachiyomiorg/tachiyomi#7057]
### Steps to reproduce

Read a chapter, 
Exit manga to home screen
See manga grid that's not been updated

### Expected behavior

List would change so the latest manga would be move to the top left of the grid

### Actual behavior

Nothing happens, if I read any manga they do not move to be sorted by latest read

### Crash logs

N/A

### Tachiyomi version

R4338

### Android version

11

### Device

OnePlus 6T

### Other details

Green boxed manga is my latest read manga, after changing the sort, I read a new whole chapter to make sure it's not reading a single page and not doing as it should it moves to the first row below the top 

The manga in the top left hasn't been updated since 2021 and not read the others in over a month yet they're at the top as "last read" so
![Screenshot_20220502-010343](https://user-images.githubusercontent.com/13301381/166170756-09bfe1ba-c11d-4ac5-abf2-98af9cf7eeb6.jpg)

Original sort (I know it's been flipped) it's apart of the issue
![Screenshot_20220502-011224](https://user-images.githubusercontent.com/13301381/166170916-df5df7f7-a2c8-4843-86db-49c26ef0d9a7.jpg)

After flipping and.reading more chapters the latest chapter does not appear in any sort
![Screenshot_20220502-010825](https://user-images.githubusercontent.com/13301381/166171023-e76bdfd3-15d8-4219-a719-ab096ac086f4.jpg)

Note: I posted a big with pictures to help Vs the previous submitted one with no pictures that might not be as helpful & I won't reply till after work tomorrow so about 16 hours.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I'm with the same problem and have open the issue #7055

**Comment by TheLittlemodder** [comment]
I havet the same problem but it also affects the History tab

**Comment by HimenoKazehito** [comment]
I am having the same issue with the latest update.
