### ISSUE TITLE
Nhentai cannot use 

### ISSUE THREAD

**Issue by dadadaguoguo114** [tachiyomiorg/tachiyomi#7058]
### Steps to reproduce

1.failled to bypass cloudflare in sources
2.failled to bypass cloudflare in library

### Expected behavior

I am just a user

### Actual behavior

library and sources can use in Ehentai and other extensions expect Nhentai

### Tachiyomi version

0.13.4

### Android version

7.0

### Device

gionee

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please open the issue in the right repository.
