### ISSUE TITLE
Lost startup tab parameter in r4338

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#7061]
### Steps to reproduce

Update to r4338
Launch the app
You end up to "library" even if previously set to news
Go to settings and look everywhere
Don't find the parameter to set it back to an other tab than library

### Expected behavior

Having the parameter to set startup tab
Set tab opened at app startup

### Actual behavior

App startup always opens library

### Tachiyomi version

r4338

### Android version

Android 12

### Device

Mi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
It was removed in https://github.com/tachiyomiorg/tachiyomi/commit/0b77b78f6a360d759241ac42b1dcf0fe66b27d50
> - Start screen: redundant with app shortcuts in Android 7.1+
