### ISSUE TITLE
PGP Signature

### ISSUE THREAD

**Issue by keinezeit8** [tachiyomiorg/tachiyomi#7064]
### Describe your suggested feature

While SHA-256 checksums generally suffice when checking the integrity of a download via Github (compromising Github would be quite the task just to change a manga reader app) it is not quite that obvious when downloading via the website.
Therefore I recommend a PGP-signature of the releases.

### Other details

I understand that it would be a lot of work to manually create a signature for every preview release, and I haven't found a CI/CD template capable of signing with a private key.
Therefore I think only mainline releases need to be signed.
Additionally the public key has to be published to easily verify the signature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Downloading off the site just downloads the universal APK off of GitHub, so I'm not sure quite what difference there is between downloading directly off GitHub and the site, as you can simply go to the repo and check the SHA-256 hash of the Universal APK for the release you're downloading. 

Manually verifying PGP keys for releases would be done by a extreme minority of users as well, so I don't think it's worth implementing.

**Comment by keinezeit8** [comment]
> Downloading off the site just downloads the universal APK off of GitHub

I know that but, it is not obvious by just looking at the site. Also the site *could* be hacked and redirect to a different APK.

> All of our stable releases are signed by default as well

I missed that.

> Manually verifying PGP keys for releases would be done by a extreme minority

That's for certain, but if it is not an inconvenience to calm them I see no reason why it shouldn't be done.

***

Overall, I do not personally need it, but wanted to throw the idea out there, since some people do care a lot about it. But since the APK is already signed it would probably be enough to just publish the public key for those who really want it.

**Comment by arkon** [comment]
I feel like there's a lot of big ifs here where if it did happen, the integrity wouldn't mean much anyhow.

I sort of get the benefit, but I'm not sure it's worth it. I'm not sure anyone even verifies with the SHAs anyway.
