### ISSUE TITLE
Filter recent updates

### ISSUE THREAD

**Issue by zubhanwc3** [tachiyomiorg/tachiyomi#7066]
### Describe your suggested feature

I have a lot of stories in my library, mostly stuff that I wanna check out later when I'm in the mood for a specific genre and what not. But because of that, my recent chapter updates are constantly bombarded with new chapters for stories that I haven't tried yet. This is brings up two issues for me. One, if there is a story I read a while ago, and don't remember the name or image, I might skip over an update. And two, it creates such an influx of updates that I often ignore them as going through the updates to see which stories I've read can feel like a chore. 

What I was hoping for, would be that I can filter it so that only stories that I've read at least a single chapter would show up on the recent updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can filter your library to started entries. I'm not sure the updates page should be getting that complex, it should just be a relatively simple list for people to stay on top of a library that they're actually reading.
