### ISSUE TITLE
Skip updating titles on Hiatus

### ISSUE THREAD

**Issue by Bmswad1** [tachiyomiorg/tachiyomi#7071]
### Describe your suggested feature

Adding an option to stop updating manga on Hiatus will be great

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Bmswad1** [comment]
The new extension api should handle it (i think)
And if it doesn't I manually change the status of manga in my library every 6 months

**Comment by arkon** [comment]
See #7074
