### ISSUE TITLE
Not ableto read new chapters and app sucks

### ISSUE THREAD

**Issue by srk1835** [tachiyomiorg/tachiyomi#7073]
### Steps to reproduce

Chapters are not updating when I try to update. Update changed everything.

### Expected behavior

Usually I used to get the chapters correctly after updating. 

### Actual behavior

Usually get my updated chapters.

### Crash logs

-

### Tachiyomi version

0.13.4

### Android version

10

### Device

Poco

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Read #6599
