### ISSUE TITLE
[Feature Request] Reduce Network Calls in Global Search

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7077]
### Describe your suggested feature

I have noticed that when doing a search for a certain manga. The search still runs while I have already found the manga/source I was looking for. And this causes the chapter list and manga details to not load until the search is nearly complete.

I recommend adding a pause to the search network calls when a user leaves the browsing/searching and goes inside a manga page or if he left the search/browse. 

If pause is difficult would a top priority request to display the currently selected manga details be possible instead of having to wait the other sources to get covers pictures and other network requests in the background to complete?

### Other details

If pause is difficult would a top priority request to display the manga details be possible instead of having to wait the other sources to get covers pictures and other network requests in the background to complete?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6854
