### ISSUE TITLE
Search feature for missing chapters

### ISSUE THREAD

**Issue by UNKNONYM0US** [tachiyomiorg/tachiyomi#7079]
### Describe your suggested feature

Just like the title says, it's a search feature that let the user search for comics that has missing chapters. If it's possible, could a option that let the user search on the other extension that the user didn't installed yet when there's no result on the installed extensions of the user. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
No you can't search through extensions you haven't installed yet, that's not how that works.

While tachiyomi could maybe detect what chapters are missing, it won't know which sources have those chapters.

Tap the title of the comic from comic info/details screen
