### ISSUE TITLE
Sharing manga pages not working

### ISSUE THREAD

**Issue by FDLAHafa** [tachiyomiorg/tachiyomi#7081]
### Steps to reproduce

1. Long press manga page to share
2. Press share
3. No apps can perform this action error occurs

Saving the manga and using the notification share button crashes to home page

Sharing manga link from app works fine

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 10 (SDK 29)
Android build ID: JSN-L22 10.0.0.222(C636E3R5P1)
Device brand: HONOR
Device manufacturer: HUAWEI
Device name: HWJSN-H
Device model: JSN-L22
Device product name: JSN-L22

### Expected behavior

Android shows apps to share via

Eg discord, WhatsApp, email

### Actual behavior

No apps can perform this action error pops up with no options for sharing

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

Honor 8x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have crash logs?
