### ISSUE TITLE
Add comics view in migration tab

### ISSUE THREAD

**Issue by wruizcanal** [tachiyomiorg/tachiyomi#7082]
### Describe your suggested feature

In the Browse/Migrate tab where the comic sources for each extension are displayed, unknown sources are displayed as a large number and inside are the comics belonging to that source.

 I want when a comic is selected to show the bookmarks view of the comic and not the global browser view.

 Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Tap the cover.
