### ISSUE TITLE
The pages are tiled 

### ISSUE THREAD

**Issue by AVchaaa** [tachiyomiorg/tachiyomi#7083]
### Steps to reproduce

![Screenshot_20220506-022827_Tachiyomi](https://user-images.githubusercontent.com/105026038/167047947-d45dd0ff-0840-410d-a17b-0d6c31f1d7df.jpg)

### Expected behavior

It's happen on some manga in japscan library. 

### Actual behavior

It's happen on some manga in japscan library. 

### Tachiyomi version

All

### Android version

Android 9

### Device

Samsung galaxy s8 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Opened in the wrong repository and also will likely not be solved:

> The JapScan extension uses a very complicated method of accessing pages. If you encounter a manga that does not load or is scrambled, use a different source to read.
