### ISSUE TITLE
Filter to ignore update of titles with ten chapters accumulated

### ISSUE THREAD

**Issue by Diegofsp98** [tachiyomiorg/tachiyomi#7084]
### Describe your suggested feature

When a tittle has ten chapters accumulated it will no longer be updated along with the others

### Other details

Add in skip updating titles option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment]
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/6916
