### ISSUE TITLE
Screencapture for Webtoon Mode

### ISSUE THREAD

**Issue by Itz1ASh** [tachiyomiorg/tachiyomi#7086]
### Describe your suggested feature

You know how you can already save the page image.. Can you make an option to capture screen instead on webtoon mode. This'll be good for saving manhua obviously and just scenes in manga where it spans out past one page.  Save image can still be there in webtoon mode but maybe just another button after long tap that lets you screen capture. When you save image can you put the name of the name of the manga in the label for the screen capture.
Example of a ('save image') label: 'Spy x Family - Mission 58.2 - 14.jpg'

### Other details

Why its better to have this then just a screenshot from your phone is that the one from Tachiyomi will have the name of the Series in the title so when you are managing your photo gallery and have THOUSANDS of images you'll just be able to search for all related to it rather then manually seeing which saved screenshot is from which manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
just save the image and then crop it

**Comment by CrepeTF** [comment]
just take a screenshot
