### ISSUE TITLE
Crop Exclude

### ISSUE THREAD

**Issue by ShockedCoder** [tachiyomiorg/tachiyomi#7087]
### Describe your suggested feature

A button or the like that allows exclusion of the cropping for the page or chapter it's activated on.

Since there are some pages of some mangas that are mostly black or mostly white, the app crops them out, but since the entire page is required for the "intensity" it makes it look wonky.

I'd love there to be both a chapter excluder and a page excluder, I'm sure that there would be uses for the opposite of this, but I haven't come upon any that require that so far.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The shortcut in the bottom menu is meant to make it easy to toggle instead to avoid feature bloat.
