### ISSUE TITLE
an install update button

### ISSUE THREAD

**Issue by M7mdTl3t** [tachiyomiorg/tachiyomi#7088]
### Describe your suggested feature

when i receive an update on tachiyomi (whether it's beta or stable version) i choose to update but it only downloads and it doesn't install or show me the installation popup (idk what its called) and i can't find the apk file anywhere in my file manager i only need to go to tachiyomi website/github to download and install the update manually
so i was wondering if you can make a button in the about page or even as a popup (and if you accidentally close that popup it goes to about page) that once you download the update it shows up (and please no notifications i have a xiaomi device with no notifications grouping so it'd be a hell for me)
ty in advance.

### Other details

a better idea: a new update button that you click on it to:
1- check the updates
2- download the update
3- install the update 
and there'd be a switch that allows it to automatically install the update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can always go to More > About > Check for updates.

I'll look into making the install prompt notification to be non-swipeable though.
