### ISSUE TITLE
add music sound in manwha mode

### ISSUE THREAD

**Issue by Shadow-1223** [tachiyomiorg/tachiyomi#7089]
### Describe your suggested feature

when you read the chapter that had music its play itself just like webtoon also when music was added the atmosphere will be more good because un like reading manga and manhwa kinda bored i can't run spotify

### Other details

![Screenshot_20220507-221408](https://user-images.githubusercontent.com/87005004/167259869-a501b7d8-cf67-49f6-b0eb-52d10c997536.jpg)
like this it would be great if it added 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is far too niche to justify adding non-trivial audio support.

**Comment by Shadow-1223** [comment]
> This is far too niche to justify adding non-trivial audio support.

oh ok
