### ISSUE TITLE
[BUG] UI looks more weirder than before

### ISSUE THREAD

**Issue by D3xron** [tachiyomiorg/tachiyomi#7090]
### Steps to reproduce

This problem is a continue of issue #6902

### Expected behavior

Should be padding on extensions controller

### Actual behavior

Due to removal of "Hide nav bar on scroll" the UI started to look weird (see image)
![IMG_20220507_191141](https://user-images.githubusercontent.com/46288465/167266886-9f3ec54d-4cc8-4682-8125-32cf1206b486.jpg)

### Tachiyomi version

Tachiyomi Preview r4338

### Android version

Android 12

### Device

Xiaomi Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Is this the same as #7085?

**Comment by D3xron** [comment]
> Is this the same as #7085?

Same as your issue, yes

**Comment by alessandrojean** [comment]
Will close this one as duplicate then 👍🏻

**Comment by D3xron** [comment]
> Will close this one as duplicate then 👍🏻 

👍
