### ISSUE TITLE
Mode scanlator don't open 

### ISSUE THREAD

**Issue by Diegofsp98** [tachiyomiorg/tachiyomi#7097]
### Steps to reproduce

No results found, can you update the extension link? 

### Expected behavior

When opening the extension(mode scanlator) the titles should appear

### Actual behavior

When I open the extension = no results found. 

### Tachiyomi version

0.13.4

### Android version

11

### Device

Moto g8 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
