### ISSUE TITLE
Hide nsfw content from unpate and library

### ISSUE THREAD

**Issue by Aahnafwifi212** [tachiyomiorg/tachiyomi#7103]
### Describe your suggested feature

![Screenshot_20220510180040](https://user-images.githubusercontent.com/95229081/167623896-1ac2b71e-ed1f-47cb-b955-ac57e0830147.jpg)

Is it possible to make these option also hide all mangas from these sources, even from history and update tab.
Note: it should just hide not remove from library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I only intended on being able to avoid the content in general if desired. More advanced NSFW content filtering belongs to the more hentai-focused forks.
