### ISSUE TITLE
Update chapter 

### ISSUE THREAD

**Issue by LorenzoConclusion** [tachiyomiorg/tachiyomi#7116]
### Steps to reproduce

try to update you whole category but not all chapters updated
try to update every manga manually to see the difference 

### Expected behavior

all the chapters should be updated 

### Actual behavior

not all the chapters updated 

### Tachiyomi version

0.13.4

### Android version

android 9

### Device

Huawei Y9 2019 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries
