### ISSUE TITLE
Unable to recognize jxl formatted files when downloaded

### ISSUE THREAD

**Issue by Seishirou101** [tachiyomiorg/tachiyomi#7117]
### Steps to reproduce

Only tested with a komga related instance, if there is a site that provides files in jxl format, further testing can see if its only komga related.

1. open the komga extension from Tachiyomi
2. open the cbz with jxl files, scroll a few pages
3. exit the comic viewer
4. download the cbz
5. look at downloaded files
6. Try to read downloaded chapter

### Expected behavior

Files downloaded in jxl format and recognized by pagelist

### Actual behavior

Files are unable to be recognized and default to jpg. 
if some images are in the image cache, they will be successfully copied over as jxl but not recognized as an image and excluded from page list.

### Tachiyomi version

0.13.4

### Android version

9

### Device

ASUS ROG Phone 2

### Other details

possible related code
[Downloader.kt](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L463-L478)
[ChapterCache.kt](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/data/cache/ChapterCache.kt#L157-L175)
[ImageUtil.kt](https://github.com/tachiyomiorg/tachiyomi/blob/5dc688dc2e581ff0098f9012a3922de2ef85d2f3/app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt#L36-L43)
issue closed from extension repo [#11072](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11072)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
Worth mentioning that if `splitTallImageIfNeeded` in Downloaded.kt would split tall images into` .jpg` splits. But since the user is on stable Tachi this is not related now since the feature wasn't released on stable.

**Comment by arkon** [comment]
Haven't traced it yet, but it may be due to lack of platform support for `image/jxl`:

- https://issuetracker.google.com/issues/182703810
- https://android.googlesource.com/platform/frameworks/base/+/0ea8c8a7c060873ef94e8aa8a637bc90852777d1/core/java/android/webkit/MimeTypeMap.java
