### ISSUE TITLE
Feature Request: When search in category limit the Updating category.

### ISSUE THREAD

**Issue by Abdu20222** [tachiyomiorg/tachiyomi#7118]
Feature Request:
When search in category limit the Updating category to search result.
For example:
Like when I want to update manga from "MangaHub" I can search for manga "MangaHub" source, then refresh the category to be updated.

The current updating category will update all manga in the category.

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Searching library by source name + #4060 would satisfy this.
