### ISSUE TITLE
Started filter not updating 

### ISSUE THREAD

**Issue by noxan-dev** [tachiyomiorg/tachiyomi#7130]
### Steps to reproduce

1. Set library filter to started and sort last read (this makes it easier to see)
2. Read a manga in your library that you haven't started. Will need to turn off the filter and re enable it.
3. See that the manga wasn't added

### Expected behavior

The newly read manga should be added to the started filter. 

### Actual behavior

The newly started manga is not added when filtering by started 

### Tachiyomi version

App version: 0.13.4-4382

### Android version

Android 10

### Device

OnePlus 6t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Yup intended. You need 1 read chapter for it to be counted as started. You don't want a series you have read single page of to be marked as started now do you.

**Comment by noxan-dev** [comment]
personally would. But that's just me
