### ISSUE TITLE
error in 'Mangabat' extension : unable to resolve host

### ISSUE THREAD

**Issue by Arijitofficial** [tachiyomiorg/tachiyomi#7136]
### Steps to reproduce

go to a manga in library which is added from mangabat
try to update

### Expected behavior

new chapter gets added or the feed remains the same

### Actual behavior

An error message is popping up - 'unable to resolve host "read.mangabat.com": no address associated with hostname'

### Tachiyomi version

"0.13.4"

### Android version

"Android 11"

### Device

"Oppo F11"

### Other details

I think the problem is getting generated because of the change in mangabat url from "https://read.mangabat.com"  to  "https://m.mangabat.com" 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Wrong repo
