### ISSUE TITLE
Splitting Height for Tall Images

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7140]
### Currently

Split height is equal to screen height. Often splitted chapters have too much page count compared to when the chapter is properly paged. For example, a chapter having 20 real pages can be considered as 50 pages after splitting.

### Suggestion 
I suggest to split based on the common webtoon images ratio. The math of split height would be calculated depending on the ratio of webtoons and the page width to determine what each page should have as height logically.

This will help to make the splitted page height to have more chance to actually split actual pages inside the chapter so to make it potentially more accurate in a sense. Therefore when someone tries to share a page he would have higher chance that the image he shares actually has a complete page rather than 2 pages with a weird cutoff between them.

**Comment by saud-97** [comment]
Please replace bug tag with feature request tag.

**Comment by arkon** [comment]
There is no common webtoon image height. Closing since it was already adjusted based in max screen dimension.
