### ISSUE TITLE
Tachiyomi "updates" bubble is annoying. There should be a way to clear it.

### ISSUE THREAD

**Issue by Apa17** [tachiyomiorg/tachiyomi#7142]
### Describe your suggested feature

There is a way to clear it that i dont know? Or a way to disable the bubble "feature" at all?  I dont need it.
Thank you

![WhatsApp Image 2022-05-15 at 12 37 51 PM](https://user-images.githubusercontent.com/29444352/168481226-973bf698-36bb-4633-b9bb-c99ecc051e71.jpeg)

### Other details

Idk if i should put it as a issue or as a feature request sorry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Settings > General

**Comment by Apa17** [comment]
ah i probably enabled it and forgot. sorry for wasting your time and thank you
