### ISSUE TITLE
hide any perticular catagory

### ISSUE THREAD

**Issue by Aahnafwifi212** [tachiyomiorg/tachiyomi#7144]
### Describe your suggested feature

in catagory setting if there is a feature to hide catagory it would be great

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Rejected before.
