### ISSUE TITLE
Reading Resume FAB causes Last Page Read to jumps pages on exit

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7147]
### Steps to reproduce

See the video for a random manga I reproduced the issue with. But the issue also occasionally happen on other mangas.
Just by using webtoon mode and scrolling (doesn't matter up or down) just a bit might make the last read page become bugged and jump and skip pages.

Pay close attention to the "Page: #" and notice how it jumps.

https://user-images.githubusercontent.com/39028181/168499685-ac3eaa05-6b53-4523-b33f-25ae655b3371.mp4

**The jump in the number happens exactly the second I press back to close the reader. At the last few frames someone can clearly see that the number of current page index down have suddenly changed on close.**

### Expected behavior

Last page read should calculate correctly

### Actual behavior

Last page read is incorrect and causes the user to miss pages if he didn't notice the jump.

### Tachiyomi version

Last debug build
App version: 0.13.4-4374 (dev, 5dc688dc2e, 81, 2022-05-16T00:15Z)

### Android version

Android 9

### Device

Emulator

### Other details

I was not able to reproduce this bug all the time, I still don't know what triggers it precisely.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Frenky1993** [comment]
Could i work on this bug ?

**Comment by saud-97** [comment]
@Frenky1993 Let me know if you were able to find where is the bug located I will try to find solutions or help you on it. I still wasn't able to pin point the location of the issue since the code of reader is quite complex.

**Comment by CVIUS** [comment]
@saud-97 can you try turning off fullscreen mode or `Show content in cutout area` in reader and tell if this still persist?

**Comment by saud-97** [comment]
> @saud-97 can you try turning off fullscreen mode or `Show content in cutout area` in reader and tell if this still persist?

I tried turning off fullscreen and nothing changed. I couldn't find where is the other cutout option you mentioned, it's probably unrelated to webtoon read mode.

![image](https://user-images.githubusercontent.com/39028181/169884771-c4273462-7840-4cdd-a22f-028eb2fd0d7b.png)

![image](https://user-images.githubusercontent.com/39028181/169884827-dd65debd-d46e-43b3-9ed0-6a47bd24944d.png)

**Comment by Frenky1993** [comment]
> @Frenky1993 Let me know if you were able to find where is the bug located I will try to find solutions or help you on it. I still wasn't able to pin point the location of the issue since the code of reader is quite complex.

I am starting to work on it as soon as possible, i'll reply to you all the things that i can find and replicate

**Comment by saud-97** [comment]
Update: I was able to notice that this bug only happens when clicking continue reading button. So it will NOT happen if the chapter was opened by clicking the chapter from the list. It will happen when clicking resume button. I'm still testing this and will post more updates if needed.

**Comment by saud-97** [comment]
Thankfully I was able to pinpoint the issue. It's due to the FAB transition animations.

```
        fab.setOnClickListener {
            val item = presenter.getNextUnreadChapter()
            if (item != null) {
                openChapter(item.chapter, it) 
            }
        }
```
Removing [sharedElement = it] parameter will fix the issue but will remove the transition animations.

https://github.com/tachiyomiorg/tachiyomi/blob/c7707dc50edb817652d4e850f4f0806ab05307df/app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt#L920-L940

I am honestly bad with UI stuff otherwise I would totally PR this.

**Comment by saud-97** [comment]
> I am looking on it, but removing [sharedElement = it ] parameter seems not a fix, whatever i click on the continue button or the chapter the reader should be cycling through the pages the same way

Did you remove the parameter and saw the issue still happening? I definitely can see that the transition is causing this bug.

I only use webtoon reading mode. I wasn't able to find a manga that doesn't do the same behavior of jumping on exit after using the FAB transition. The jump seems to do a minimum of 2 pages jump and sometimes it can jump 15+ pages which is totally confusing.

**Comment by Frenky1993** [comment]
> > I am looking on it, but removing [sharedElement = it ] parameter seems not a fix, whatever i click on the continue button or the chapter the reader should be cycling through the pages the same way
> 
> Did you remove the parameter and saw the issue still happening? I definitely can see that the transition is causing this bug.
> 
> I only use webtoon reading mode. I wasn't able to find a manga that doesn't do the same behavior of jumping on exit after using the FAB transition. The jump seems to do a minimum of 2 pages jump and sometimes it can jump 15+ pages which is totally confusing.

Hi Saud-97 , i could not replicate the bug with the animation off but it seems to be linked to the resume button in the chapter pages i will try to see if removing it still cause the button to behave and create the bug.

**Comment by FourTOne5** [comment]
@saud-97 @Frenky1993 can you guys see if it also happens in https://github.com/ivaniskandar/tachiyomi/tree/manga-compose? It's a wip of manga info screen in compose.

**Comment by saud-97** [comment]
> @saud-97 @Frenky1993 can you guys see if it also happens in https://github.com/ivaniskandar/tachiyomi/tree/manga-compose? It's a wip of manga info screen in compose.



There was no FAB or start/resume button in this WIP branch. Let me know when it is completed and I can gladly verify if the bug is still there.
