### ISSUE TITLE
[FEATURE REQUEST] Hide/Collapse READ/NOT READ Chapters

### ISSUE THREAD

**Issue by sthasam2** [tachiyomiorg/tachiyomi#7149]
### Describe your suggested feature

For long series that has a lot of chapter, if we are in the middle secion say chapter 600 out of 1100 chapters it takes a lot of time to scroll to said chapter for whatever reason.

I request a feature where by there is something like a sub heading/menu of `READ` and `NOT READ`  where there are chapters of respective status. An option to collapse the list under the sub headings would makeusability a bit better. Maybe an option in the settings to enable/disable said feature.

Something like this:

![Collapsible Submenu](https://www.journaldev.com/wp-content/uploads/2015/12/android-expandablelistview-example.gif.webp)

![Collapsible](https://user-images.githubusercontent.com/51694759/168574814-ab507b20-3acf-437e-a206-9537d0dcf5c7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Just use the filter to filter out read chapters

**Comment by sthasam2** [comment]
The problem I have is not with filtering, rather with scrolling to currently reading chapter. Anything that can be done for that?

**Comment by sthasam2** [comment]
> Just use the filter to filter out read chapters

The problem I have is not with filtering, rather with scrolling to currently reading chapter. Anything that can be done for that?

**Comment by sthasam2** [comment]
> Just use the filter to filter out read chapters

Never thought about that. Thank you.
