### ISSUE TITLE
Switches for offline and incognito mode have a different look from other switches in the app

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#7152]
### Steps to reproduce

1. Open up the "More" section of the app
2.  Observe

### Expected behavior

The switches look normal

### Actual behavior

They look like this:
![Screenshot_20220516-211821](https://user-images.githubusercontent.com/61708534/168708078-3b8bc11a-6c56-436e-9e61-4b9d59f12a7a.png)

Normal switches for comparison:
![Screenshot_20220516-211836](https://user-images.githubusercontent.com/61708534/168708119-778e2502-b488-42de-ab74-3a5db24cb2f6.png)

### Tachiyomi version

r4382

### Android version

10.0

### Device

Vankyo P40 tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
The app is still in work in progress being converted to Compose. For now it's intended
