### ISSUE TITLE
Skip old chapters when you have read new chapters

### ISSUE THREAD

**Issue by codefreak558** [tachiyomiorg/tachiyomi#7155]
### Describe your suggested feature

Like said in the title. I'd like to see a way to either skip old chapters if you have already read a later chapter such as if I've read chapter 50 and they add chapter 43 redone.

So either skip downloading it/showing in updates or showing in the updates tab when it shows a "new" chapter if its 43 say somewhere that there is a later read chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
For a lot of series' scanlators might actually add new old chapters though such as a chapter 43.5 which has additional content

**Comment by joex92** [comment]
Yes, but if I already read chapter 43 and 44, and now other scan group add their chapter 43 and 43.5 (bonus chapter), it's a pain to see that I have 2 new chapters or automatically download 2 new chapter when actually it's a chapter that I have already read, and could have been that that the previous group didn't separated the bonus from the chapter and I already read the bonus too... 
This happens too often when another scan group wants to translate a title that it's already being translated, and start translating from older chapters...

**Comment by Saud-97** [comment]
Getting notified on new added chapters is still more important compared to the minor annoyance you feel when you see it is a repeated chapter. So this behavior most likely will never change since there are contradicting cases.

**Comment by joex92** [comment]
yes, but having duped "new" old chapter will make the app to omit updating the title because it has unread old chapters... I'm having the issue that suddenly some old chapters are added again and the app omits looking for new chapters because the title has old chapters marked as not read... that means that I have to mark them as read manually... that's why I'm saying this... 
I remember before version 1.13 the app would look for new chapters for each title regardless of its status... this became an issue because of the new feature added on 1.13 omitting titles because they are not read up-to-date...

**Comment by Saud-97** [comment]
Oh yeah after you clarified it I was able to get your point. What you request is basically this

*  In other words skipping manga updates should depend on latest chapter read/unread status rather than checking all chapters reading status.

**Comment by joex92** [comment]
exactly... sometimes I get behind some titles because the app omit them...

**Comment by joex92** [comment]
but marking old "new" read chapters as read would be useful...

**Comment by arkon** [comment]
#4316
