### ISSUE TITLE
Sort by chapter number ignores hyphens in Chapter Title

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7160]
### Steps to reproduce

I had a manga with so many chapter sorting issues, and after testing it seems that Tachi doesn't treat the character "-" during chapter sort same as how "." is treated.

Take this manga for example:
[God Of Martial Arts (directly open via Tachi apps)
](https://mangalek.com/manga/god-of-martial-arts/)Source: مانجا ليك (Mangalek)
![image](https://user-images.githubusercontent.com/39028181/168936744-4fcc19be-e839-4963-b986-82aa0a03238d.png)

### When "Hide chapter title" is turned on

![image](https://user-images.githubusercontent.com/39028181/168936780-deb43396-4677-45dd-8d89-49dd96d843f9.png)

### When "Hide chapter title" is turned off

![image](https://user-images.githubusercontent.com/39028181/168936948-f2de3176-dae6-4f83-8791-207f8220bf17.png)

**This leads to issues in sorting where ch 153-3 is showing before 153-1. Also when there is a mix between usage of "-" and "." in chapter titles.**

![image](https://user-images.githubusercontent.com/39028181/168937159-61f8968d-d488-4f43-a181-ba8ccc101d24.png)

### Expected behavior

Should treat or **replace** hyphen character same as dot character during sorting and when "hide chapter title" is enabled.

### Actual behavior

Tachi misreads chapter titles with 153-1 and 153-2 and shows them as equally 153 without considering they are parts and doesn't respect their correct order. See first image.

### Tachiyomi version

Latest Build

### Android version

Android 9

### Device

Emulator

### Other details

The screenshots are of J2K but the same bug happens in upstream so this is an upstream issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
> This leads to issues in sorting where ch 153-3 is showing before 153-1. Also when there is a mix between usage of "-" and "." in chapter titles.

Regarding this part, Actually upstream correctly sorts when all parts numbers contain the same character `-`. But it still misses when there is a mixture of them.

**Comment by saud-97** [comment]
Fix was submitted in PR https://github.com/tachiyomiorg/tachiyomi/pull/7161

**Comment by arkon** [comment]
Don't close issues if the PR isn't even accepted yet...
