### ISSUE TITLE
Share one manga using QR Code

### ISSUE THREAD

**Issue by CherbyMina** [tachiyomiorg/tachiyomi#7165]
### Describe your suggested feature

Hello I'd like to request a feature where we can share that one manga using a qr code...

Is it possible to add that?...

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
I must say that'd be a very niche request. 
I should be possible to Share/Copy the link to the manga and use a QR Generator [App](https://f-droid.org/en/packages/de.t_dankworth.secscanqr/) or [Website](https://duckduckgo.com/?q=qrcode+https%3A%2F%2Ff-droid.org%2Fen%2Fpackages%2Fde.t_dankworth.secscanqr%2F&t=fpas&ia=answer)

Do you have any other specific use-case?

**Comment by curche** [comment]
/edit-title "Share one manga using QR Code"

**Comment by arkon** [comment]
Agreed with the above.
