### ISSUE TITLE
Invalid download location randomly showing

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7171]
### Steps to reproduce

1.  Start downloading anything
2. The issue happens randomly
3. The download fails and can't continue due to "Invalid download location"

### Expected behavior

Download normally

### Actual behavior

Can't download anything until resetting the download location from settings.

### Tachiyomi version

0.13.4

### Android version

Android 9

### Device

Emulator

### Other details

I will try to debug it when it happens but I can't really force the random error to test.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please open again if there's more details or more consistent reproduction steps.
