### ISSUE TITLE
Want to add a slider switch to control the height of the bottom navigation bar

### ISSUE THREAD

**Issue by wbmins** [tachiyomiorg/tachiyomi#7172]
### Describe your suggested feature

Want to add a slider switch to control the height of the bottom navigation bar,The bottom feature bar now looks tall

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The bottom nav uses the standard Material Design height as seen in various other apps.

Hiding the text doesn't affect the height.
