### ISSUE TITLE
Option to turn off Warnings for bulk update/download

### ISSUE THREAD

**Issue by Sakura-Adachi** [tachiyomiorg/tachiyomi#7174]
### Describe your suggested feature

having to clear notification every time is quite annoying so at least there should be an option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Did you check App Notification settings in Android settings?

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/6599

**Comment by Sakura-Adachi** [comment]
> #6599

which one ?
i want to stop the warning notification when updating library

**Comment by Sakura-Adachi** [comment]
> Did you check App Notification settings in Android settings?

^
