### ISSUE TITLE
Add uninstall action on source hold

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7176]
### Describe your suggested feature

To add Uninstall action to this `SourceOptionsDialog`

![image](https://user-images.githubusercontent.com/39028181/169631235-0f34e9e4-c5c4-40d6-83e5-4a404ada9721.png)

Since it is convenient and doesn't require much effort. It would work as a shortcut.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Extensions may contain multiple different sources, so this can easily cause confusion. Installing and uninstalling extensions is managed from the extensions tab.
