### ISSUE TITLE
Http error 401 when tracking manga from MAL

### ISSUE THREAD

**Issue by sdMickey** [tachiyomiorg/tachiyomi#7177]
### Steps to reproduce

1. Open manga page where all the chapters are listed.
2. If you've logged in from MAL, continue ahead.
3. Click on tracking.
4. Click on add tracking.
5. It is displaying http 401 error to me.

### Expected behavior

It should open up options of manga to select mine from so that it can correctly track manga.

### Actual behavior

It's showing http error 401

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

OnePlus 7 Pro

### Other details

![Screenshot_20220521-102035](https://user-images.githubusercontent.com/54260201/169636042-4a4eebd4-6781-4885-ab3c-f42caf63287f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Logout of your tracker and login again
And see if the error persists

**Comment by sdMickey** [comment]
It is resolved thank you.
