### ISSUE TITLE
Increase Manga Update Concurrency to 5 sources

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#7180]
### Describe your suggested feature

I suggest to increase number of concurrent update jobs in `updateChaptersJob` to 5 sources at the same time during Global Updates, similar to download concurrency from 5 sources. 

**To help in speeding up updating without putting any extra pressure on sources, and to avoid slow sources throttling the update speed.**

### Other details

If this is already implemented, then I'm not sure why it isn't working as expected since updating seems to be happening 1 by 1 in my case. Let me know if this is already implemented.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
It exists. You might feel like it's updating one at a time but in reality it is updating from 5 different sources. The series in notification are the ones that are currently being updated.

![IMG_20220522_002503_948](https://user-images.githubusercontent.com/59261191/169664648-75cd6823-f948-4d2c-9a6d-3090cc15bd2d.JPG)
