### ISSUE TITLE
OCR Machine Translation or Google Translate quick share button

### ISSUE THREAD

**Issue by harkamalsr** [tachiyomiorg/tachiyomi#7181]
### Describe your suggested feature

Currently I'm individually sharing each manga page to apps like Google translate or Papago so that I can read manga which aren't being actively translated by the community. I know that most of the translations are divorced from context but in my opinion it's better than nothing.

Even a quick share button to google translate would get the job done

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#3383

**Comment by saud-97** [comment]
Maybe what he meant is a different approach, by sharing the current page image file to google translator not the text itself or a method of OCR, not sure if this is doable to share it directly to google translator though.

**Comment by CrepeTF** [comment]
They're asking for a direct share button to Google Translate it seems, bypassing the share sheet. I don't believe that is possible

**Comment by harkamalsr** [comment]
Ah, sorry I wasn't really that detailed with my description. I'll try to rephrase the question into something easier to follow

So, let's go through what I have to do to read Manga Raws in Tachiyomi.

1. I get the manga raw I want to read through the Japanese tachiyomi extensions. Then I start reading a manga; but as you can see it's in Japanese so I can't read it

![image](https://user-images.githubusercontent.com/10123690/169670960-b0fa41b1-185e-445d-8c8e-708f06406aeb.png)

2. I then share the single page that I'm currently looking at to a translation app (In my case I use Papago).
![image](https://user-images.githubusercontent.com/10123690/169671298-f2bcc6d2-67ef-485b-ae33-84bad9819b21.png)

4. After the translation finishes I can finally read the page as seen below (usually it's badly translated English)
![image](https://user-images.githubusercontent.com/10123690/169671315-88835681-5ea9-4e69-ad8b-587e7aa1ad02.png) 

5. I would then manually go back to Tachiyomi so that I can go the next page 
![image](https://user-images.githubusercontent.com/10123690/169671381-026837fc-e8dd-418d-9f00-6770d0fe02e4.png)

6.  Then I would would repeat these 4ish steps through the remaining pages (In this case 53 pages)

I suppose what I'm asking for is something to streamline this process to contain as few steps as possible.

> #3383

Issue #3383 seems to somewhat do what I'm asking but I can seem to get it working for Japanese text; even then I would still have to switch to a translation app to translate the text ripped from the manga.

So I suppose what I'm suggesting is On-screen-translation support in Tachiyomi? It doesn't have to replace the text like in Papago, but even something as simple as holding the page down and having a translate button would be nice. I'll even settle for something simple like text at the bottom of the screen like in issue #3383.

Just anything to streamline the reading of raws in a different language

**Comment by arkon** [comment]
The same points from #3383 still apply.

**Comment by harkamalsr** [comment]
> 

I see, looking through #3383 I think I agree. I suppose I'll try using a tool like automate to streamline the process. Thank you for humoring me
