### ISSUE TITLE
Feature Req: Remember zoom level across sessions per comic

### ISSUE THREAD

**Issue by foundObjects** [tachiyomiorg/tachiyomi#7184]
### Describe your suggested feature

Currently the reader resets to 100% zoom when opening a chapter. I'd like the reader to remember my last used zoom level for a comic when opening a chapter.

Context: I read on a ~10in tablet, webtoon style series work better at something like 66-75% zoom to fit more content on screen. Zooming every single time I open a chapter is annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
Webtoon Side Padding might help but It still doesn't save per session since it's a global setting for reading. I think your feature request is reasonable since I have the same annoyance.

**Comment by arkon** [comment]
#1822 should cover this too.
