### ISSUE TITLE
Delete downloaded chapters after migration/deletion

### ISSUE THREAD

**Issue by leopoldhub** [tachiyomiorg/tachiyomi#7186]
### Describe your suggested feature

When we delete/migrate a manga, there is no way to access/delete old downloaded chapters.

I think there should be a way to read/delete those chapters via the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #2108 / #2289
