### ISSUE TITLE
[Feature Request] Autodownload chapter feature in title menu

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi#7190]
### Describe your suggested feature

Rather than downloading all chapters of all titles in a category add option of auto download chapters in title menu ( option in title menu after opening a manga )

Add auto download for a single title 
And enable  a sub menu for auto downloading like new chapter's only | unread chapters only | etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Add auto download for a single title

Use categories. You put an entry in multiple categories.

> And enable a sub menu for auto downloading like new chapter's only | unread chapters only | etc

Auto downloading only downloads new unread chapters anyway.
