### ISSUE TITLE
FR: Smart fit: Smarter ultrawide images behavior 

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7193]
### Describe your suggested feature

Smart fit should take into account the total height and aspect ratio of the image before fitting it. Currently, extremely long aspect ratios (ie, a screenshot of a long line of text) is upscaled to be the equivalent of several pages long. 
Smart Fit should instead zoom out on such aspect ratios where the width is several times the height (more than a double-page). 

Going to the next page on such images (which I don't ever recall any being anything other than messages from the uploader) are tedious to scroll by, especially when a tap is set to also scroll. These images are often also unreadable due to "cropped borders" and "Smart Fit" upscaling them, making the text too large. 

### Other details

possibly related: #4566 , #1668 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
Please provide the source / chapter details. And provide a screenshot for better understanding.

**Comment by mm12** [comment]
> Please provide the source / chapter details. And provide a screenshot for better understanding.
example: (although this happens a lot)

MD: isekai kara no kigyou shinshutsu v1ch3.1 pg 18 EN
The true image ![image](https://user-images.githubusercontent.com/5874051/170402960-a2cbeb13-f5e9-437c-bb0c-2627b7283e48.png)
how the image appears for me: (what I see when I use the mentioned settings): 
![image](https://user-images.githubusercontent.com/5874051/170403196-88561f41-4767-460b-b730-b5c98ac07bb8.png)

As you can see, it is quite unreadable. Since you can't zoom out in smart-fit, its even worse, because I need to scroll several times to get past it.

**Comment by arkon** [comment]
Closing in favour of #4566. Feel free to add more details in a comment there if it doesn't quite capture your thoughts.

**Comment by mm12** [comment]
> Closing in favour of #4566. Feel free to add more details in a comment there if it doesn't quite capture your thoughts.

My problem with "Smart Fit - No Upscale" is that I often want it to upscale images. On top of that, it does not address cases where the image doesn't need upscaling, but downscaling (ie, if a group has a large file as their page, currently it can have over 2 pages of width without any upscaling.)
what I am saying is, it fixes one thing that is seen often but sacrifices things that are seen nearly always. It may be a good idea, but without modification, it hurts more than it helps. 

Here is a proposal: Make a menu in the "reading mode" section for upscaling. 
- why this makes more sense - Upscaling applies to ALL fit scaling, not just smart fit. 
- The options for upscaling: OFF, SCALED, and SMART. 
-- Scaled uses whatever upscaling the scale mode uses by default. 
-- Smart uses aspect ratio and resolution of the image to make a cutoff for the upscaling (based on screen width).
