### ISSUE TITLE
Scans full of squares

### ISSUE THREAD

**Issue by Aldoubidoche** [tachiyomiorg/tachiyomi#7194]
### Steps to reproduce

1. Open a manga scan
2. Suddenly, one of the chapters becomes bugged, full of squares that makes every scans unreadable
3. Several or all remaining chapters become unreadable

### Expected behavior

Scans are readable

### Actual behavior

The scans are unreadable because they are filled with small squares as in this example : https://cdn.discordapp.com/attachments/781281368835096610/978732444138229830/Coq_De_Combat_-_Coq_De_Combat_258_VF__Revers_et_manches_-_2.jpg

I tried to clear cache, cookies, database, download the scans, update the app but nothing worked.
It happened on several other mangas before.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Xiaomi Redmi Note 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

The website is probably scrambling the images to avoid scrappers like Tachiyomi. Open an issue in the correct repository.
