### ISSUE TITLE
Install dialog can get hidden

### ISSUE THREAD

**Issue by awinner1** [tachiyomiorg/tachiyomi#7195]
### Steps to reproduce

Start to install an extension, when the install dialog comes up, hit anywhere on the app but on the dialog, it disappears never to return, but the pending install is waiting for it, so it's hung as well. Only way I have found to recover is to kill the app. 

### Expected behavior

If I miss the dialog, some way to bring it back. 

### Actual behavior

Hung install due to not being able to authorize the install

### Tachiyomi version

13.4

### Android version

Android 12

### Device

Galaxy ultra 22, but did it on my old 9 as well

### Other details

None I can think of

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
I can reproduce the issue you face but there is a close button (x) that will cancel the installation even if it was stuck on Installing or Pending states. Are you sure you are on Tachiyomi Main not on another fork?

![image](https://user-images.githubusercontent.com/39028181/170153850-129e329a-e31b-4854-848d-9830e61e8637.png)

**Comment by arkon** [comment]
@ivaniskandar IIRC you mentioned that this is a flaw with PackageInstaller in 11+, right?

**Comment by saud-97** [comment]
I have the same issue on Android 7 where the installer popup doesn't use full screen. I have another emulator on Android 9 and the installer will use full screen so there won't be any accidental touches that will close the installer without action.

**Comment by ivaniskandar** [comment]
> @ivaniskandar IIRC you mentioned that this is a flaw with PackageInstaller in 11+, right?

Yes that's why there's a cancel button on each item
