### ISSUE TITLE
Feature Request : Added Pause Button For Each Source In Download Queue

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7199]
### Describe your suggested feature

Requires a pause button for each source in the download queue

### Other details

I think that adding a pause feature to each source can make it easier for which source to download without having to stop all downloads in the download queue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment]
Why not just move the sources you want to be downloaded first to the top?

**Comment by TheKingTermux** [comment]
> Why not just move the sources you want to be downloaded first to the top?

If I do that, when the first source is less than 10-20 chapters, then the source below will be downloaded too

**Comment by CrepeTF** [comment]
why do you need to pause it if you're the one who initiated the download

**Comment by TheKingTermux** [comment]
> why do you need to pause it if you're the one who initiated the download

Because there are some sources that are too fast or even too slow in downloading chapters.  I only rarely use 1 download source, maybe I usually use 3/4 different download sources.  Which is where some downloaded sources will consume excessive internet data (especially some sources that are fast in downloading chapters), while others will consume less internet data.  It's also possible, I only downloaded 1-15 comic chapters from several sources, but the source below will be downloaded (I'm grateful if it's a slow download source, but if it's a fast download source, then I have to pause to reduce the data package bill)  in my country).  Please note, I don't have WiFi at home, but sometimes I go to a relative's house just to download chapters if below the source above is a source with a high download speed (there are 2 sources in the download queue) and has hundreds of chapters to download.  If this really can't be added in the Tachiyomi application, or even causes some code to experience errors, please close this issue.
