### ISSUE TITLE
Don't turn Global Search query into title / Don't remove Global Search input box

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7201]
### Describe your suggested feature

Library
![Screenshot_20220527-033531_Tachiyomi](https://user-images.githubusercontent.com/63973749/170564757-52cf13f4-6e83-4e90-b779-1fa97a9e4eea.png)
History
![Screenshot_20220527-033547_Tachiyomi](https://user-images.githubusercontent.com/63973749/170564820-714fff70-99ed-460e-b897-2e6e7fd70ac4.png)
Source search
![Screenshot_20220527-034422_Tachiyomi](https://user-images.githubusercontent.com/63973749/170565325-04751332-6cac-45e3-a45a-0a8d679feb16.png)
Extensions
![Screenshot_20220527-033609_Tachiyomi](https://user-images.githubusercontent.com/63973749/170564860-1939dc5e-e656-4aac-9229-baaeed89b15a.png)
Settings search
![Screenshot_20220527-033624_Tachiyomi](https://user-images.githubusercontent.com/63973749/170564894-c4baa0d3-97bd-4770-ac8b-33a6865c832d.png)

And then there's global search
![Screenshot_20220527-033713_Tachiyomi](https://user-images.githubusercontent.com/63973749/170565012-600c2e77-0f1f-4b1b-b8ec-111ea5a2854e.png)

...which is not quickly editable. You can't tap the title to edit either.

I suggest to just keep the search input box like all the other screens.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
#3920 ?

**Comment by arkon** [comment]
Fixed by #8631
