### ISSUE TITLE
Cannot download/view offline the downloaded chapter even when SD card has 63gb left 

### ISSUE THREAD

**Issue by VirYouth** [tachiyomiorg/tachiyomi#7208]
### Steps to reproduce

1.Open app
2.Select SD card as download location
3.Download chapter/s
4.Filter to Downloads only

### Expected behavior

Expect to see all downloaded chapters and be able to read the offline.

### Actual behavior

No downloaded chapter appears and I cannot access chapters that I downloaded offline... even the SD card doesn't show the images it only show the download folder, Name of the series, And the chapter number.. BUT not the images it seems it automatically deletes itself because when I go to check the latest downloaded chapter it shows that there's a downloaded chapter and the SD card also has the image.....but after a while it suddenly disappears leaving only the series name folder without any images

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

Xiaomi Redmi 9c

### Other details

- While downloading
- 
![20220528_115513](https://user-images.githubusercontent.com/106418200/170809055-f6bf4416-c29a-4184-b093-84d1406bb2aa.jpg)
![20220528_115600](https://user-images.githubusercontent.com/106418200/170809070-e7e7375c-5e43-4a83-afd0-a5f2531cf3cf.jpg)
![20220528_115724](https://user-images.githubusercontent.com/106418200/170809115-1dc321fd-344e-4411-a832-41df75f9ce7a.jpg)
![20220528_115907](https://user-images.githubusercontent.com/106418200/170809122-9514b055-8485-4d77-896a-a374a42163f2.jpg)
 
-After Awhile
- 
![20220528_120549](https://user-images.githubusercontent.com/106418200/170809203-f3728025-0de8-4e33-b862-91f327bf5d21.jpg)
![20220528_120530](https://user-images.githubusercontent.com/106418200/170809210-614264e4-af0d-4513-9514-afb39967c66a.jpg)
![20220528_120632](https://user-images.githubusercontent.com/106418200/170809214-48932836-fc20-4e5c-a780-b7cb927be3ff.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The app doesn't delete chapters unless the user manually prompts it. If your SD card contents are disappearing by themselves, there's an issue with your SD card or something else on your device is "cleaning" it.
