### ISSUE TITLE
MangaUpdates tracker doesn't read current progress

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7209]
### Steps to reproduce

Read a manga up to any chapter like 5.
Click on track and add MU tracker.

### Expected behavior

MU shows that current tracked chapter is 1

### Actual behavior

It should match current progress chapter 5.

### Tachiyomi version

Latest Build

### Android version

Android 9

### Device

Emulator

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
MU starts counting at one. And no tracker service uses current progress when adding a new tracker

**Comment by Saud-97** [comment]
Yeah I figured that after testing. I am planning to create a PR to correctly read last read chapter progress. I think this is why it must be added but I still didn't figure out how to get the current progress number.
