### ISSUE TITLE
Backup and restore feature adjustments

### ISSUE THREAD

**Issue by Anomoly8763** [tachiyomiorg/tachiyomi#7211]
### Describe your suggested feature

As we all know, in the backup feature you can save and backup your history, manga , chapters , catgeories , etc with it but what if we can make this feature more specific? Like perhaps what if for the categories that you have made, you can pick a specific category to be backup and categories to not backup. As well as picking certain mangas,manhuas,manwhas to be added in the backup. Like if you select a catgeory make it somewhat the same as , SEE OTHER DETAILS. You can see that there is a select all feature in it right, make it something similar to that wheter you can pick to select all or no and also to pick certain comics to be read without selecting the category. Why should we add this? The question for this answer is because "YES" , jk  i know that this requires a bit or a lot of coding, money to be done , but this would be an efficient feature to have, like it may seem useless to your perspectives because you would think like why pick specific stuff one by one when you can just select all the chapters, manga , history you have read and just backup it, because it isnt even laggy to even create a backup. Well for me i think this feature would be  useful so that you can instantly send reccomendations to your friends (who use tachiyomi) and it would be instantly in their tachiyomi app. There are other things that can be said about this feature to he added, but i cant drag this topic any longer, but i would also like to talk about another feature to be added, like when you save the backup make it so that the extensions would be downloaded in the backup file as well.  This is shown in the second image in (OTHER DETAILS) when the backup is finished it will show up there, but of course make it so that you can decide whether to add the extensions to be downloaded or not (SEE 3RD IMAGE IN OTHER DETAILS). Thank you for reading this long text , maybe your having a bad day or whatnot but, yea thank you for reading this and i hope this adjustment would be added soon, and yea ill keep suggesting things if there are stuff missing in the app.

### Other details

![Screenshot_20220528-202252_Tachiyomi](https://user-images.githubusercontent.com/106426323/170817251-fe2122f9-e98e-4203-b7b7-8bb7ae09eabe.jpg)
![Screenshot_20220528-203613_Tachiyomi](https://user-images.githubusercontent.com/106426323/170817858-5fd29d3b-fff0-4ce6-af07-ebedeb67a056.jpg)
![Screenshot_20220528-204001_Tachiyomi](https://user-images.githubusercontent.com/106426323/170817949-dbaa47f6-7d70-45a0-9d6a-31cf1a03cc85.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
I would also suggest to allow user to pick what data and categories he wants to be restored from a backup similarly.

**Comment by Anomoly8763** [comment]
> 

true, like you can basically make a specific named category and put the mangas/manhuas/manwhas in that category and send that to your friend, it would make things efficient and also sorry, its my first time recommending stuff in github

**Comment by arkon** [comment]
Can you rewrite the issue to be more succinct with proper flow? It's hard to grok a wall of text that's written as if you're chatting with someone.

**Comment by Ihccato** [comment]
i think op is saying that when doing back ups, if categories are selected to be able to select all categories or individual ones. to back up that one specifically. that seems reasonable enough to do, just add another box when categories are checked. to see if the user wants all categories or just a specific one or specific 2 or 5 depending on the user and how many categories the user has.

**Comment by arkon** [comment]
Closing since OP never clarified. If someone wants to write a better issue, feel free to do so.
