### ISSUE TITLE
Stats Screen

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#7213]
### Describe your suggested feature

Source Stats
- Genre
- Manga Status

Manga Stat
- Manga Count
- Chapter Count
- Read Chapters
- Read duration (RIP my 40k chaps with read duration of 0)

Genre Stats
- Genres and item count

### Other details

Comment any additional stats you want i'll be working on this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
From Discord:
Amount of manga
Amount of genres

Quick Stats per source
Quuck Stats per category

Manga included in global update
Chapters read
Total chapters
Total downloaded
Total local

Sources installed

**Comment by Saud-97** [comment]
**I guess to allow combinations of the above for example**

> Genre
> Manga Status
> 

**and inside it for each show** 

>  Manga Count
> Chapter Count
> Read Chapters
> Read duration 
>

**Comment by Soitora** [comment]
Show stats that incriminates dumb users that overload sources, which was part of my "Manga included in global update" part

**Comment by CrepeTF** [comment]
"Amount of network calls created this month"

**Comment by vengiare** [comment]
![Screenshot_20220529-001238_Chrome](https://user-images.githubusercontent.com/63973749/170872056-9bd24a0a-0c2b-44d2-a4d4-b9e34a7282f3.png)

**Comment by arkon** [comment]
I'd avoid genres for now, considering how inconsistent they can be across sources.

**Comment by CrepeTF** [comment]
![Stats_-_Main.png](https://user-images.githubusercontent.com/70870719/189227443-22631694-eafa-4348-bba8-f1c2dd383a1d.png)

**Comment by arkon** [comment]
Closing for now. Should open separate issues for any followup enhancements.
