### ISSUE TITLE
Preview R4428, nothing displayed in library

### ISSUE THREAD

**Issue by Matth7878** [tachiyomiorg/tachiyomi#7218]
### Steps to reproduce

Update to latest build (r4428) and go to library

### Expected behavior

List of all your mangas you're following

### Actual behavior

Nothing displayed.
But still history, new are there and in explore and migrate you can see manga you follow in migrate screen.

### Tachiyomi version

0.13.4-4428

### Android version

Android version: 11

### Device

OnePlus 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Try with r4430. If it still happens, can you post the crash logs?

**Comment by Matth7878** [comment]
It's working with r4430, guess it was the same problem as the backup one. Thanks!
