### ISSUE TITLE
Bulk refresh skips completed manga, however many ongoing manga is wrongly tagged as completed

### ISSUE THREAD

**Issue by vasudeveloper001** [tachiyomiorg/tachiyomi#7221]
### Steps to reproduce

1. Add a bunch on ongoing manga which has wrong tags of being completed.
2. Do bulk refresh.
3. It will skip the completed tag manga as it should.

The problem is that wrong tag info makes the bulk update skip it altogether. 

### Expected behavior

Bulk refresh should not skip any manga and do update the chapters if available.

### Actual behavior

It skips the completed tag manga which are wrongly tagged as completed.

### Tachiyomi version

Latest release at the time of writing

### Android version

11

### Device

Xiaomi 11i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Open issues about the extensions if they're incorrectly setting statuses.

**Comment by vasudeveloper001** [comment]
It's not extension in my opinion as most manga from the same extension is fine.

**Comment by arkon** [comment]
You even acknowledged that they're wrongly tagged, so I'm not sure how your opinion is relevant.
