### ISSUE TITLE
download won't complete

### ISSUE THREAD

**Issue by jankinT** [tachiyomiorg/tachiyomi#7224]
### Steps to reproduce

normally download mangas from 8muses

### Expected behavior

the download should complete

### Actual behavior

some of the download get stuck and never complete, even when I deleted the tamp file and downloaded it again.
![Screenshot_2022-05-29-19-21-12-588_eu kanade tachiyomi](https://user-images.githubusercontent.com/42428606/170865408-ad0a2f5c-169a-49a2-911c-5b6c97e3fc16.jpg)
![Screenshot_2022-05-29-19-31-13-759_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/42428606/170865746-8eec1cc5-369b-4e41-a908-2f0809b6993d.jpg)

### Crash logs

it didn't crash

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

redmi K50

### Other details

it only appears on some of the manga's specific chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by jankinT** [comment]
> > If this is an issue with an extension, I should be opening an issue in the extensions repository.

not quiet sure, I only just installed the app for 2 days, and that is the only extension I'm using for now, but thanks anyway
