### ISSUE TITLE
Automatic Backups not running for a few days

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7227]
### Steps to reproduce

I noticed that automatic backups were not created for the last few days.
I think it may be related to the app losing the permissions randomly similar to https://github.com/tachiyomiorg/tachiyomi/issues/7171

### Expected behavior

Notify the user on backups failures or at least re-request the needed permissions from user **on app startup** to gain access to all directories the app needs access to like downloads, backups etc... and re-perform the missed scheduled operations like a scheduled backup or a scheduled update. 

### Actual behavior

It fails silently forever until the user notice the issue on his own. Which defeats the purpose of the feature since it's unreliable currently.

### Tachiyomi version

Latest Build

### Android version

Android 9

### Device

Emulator

### Other details

I noticed that I was able to create a backup manually and choose to save it inside the automatic backups directory. However the app can't use the same directory when it is doing it automatically for some reason.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's been no reports of users mysteriously losing storage permissions, and normal system typically do not do that.

**Comment by arkon** [comment]
It was pointed out to me that the Android 11+ behaviour (also backported via Google Play Services) revokes permissions after 3 months of apps being unused. However, it doesn't make sense for a user to expect backups to occur if they haven't used the app in 3 months, and that system notifies them of the revoked permissions. The app would prompt for storage permissions as usual if the user interacts with it again.

**Comment by Saud-97** [comment]
I think it was a random one time bug. After I reset the backup settings the bug never happened again. Can be ignored.
