### ISSUE TITLE
Incognito mode unintended behavior for untracked manga

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7228]
### Steps to reproduce

Have untracked manga
Enable Incognito mode
Read a chapter

### Expected behavior

Incognito mode currently doesn't mark chapters as read if a manga is not tracked. This shouldn't be the case as Incognito mode should only affect History tab, not mark as read behavior.

When a manga is **not being tracked**, It 
should not log chapter read history **but still mark the chapter as read** upon reading.

### Actual behavior

It doesn't mark chapters as read.

### Tachiyomi version

r4424

### Android version

A12

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ShockedCoder** [comment]
+1

**Comment by Soitora** [comment]
I don't think Incognito mode should mark anything read at all, it's not just for the history tab

If you use Incognito in your regular browser, it doesn't remember the links you've pressed and present them as purple in your regular browser? Why should we
