### ISSUE TITLE
"Couldn't split downloaded image"

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#7229]
### Steps to reproduce

Try downloading a webtoon, in my latest case "Is This Hero for Real?" from MangaDex, ch18~25 and still happening.

### Expected behavior

It shouldn't show that error I guess? I noticed this option a few days ago and wanted to try it, got it on some webtoons so far.

### Actual behavior

My reader's still laggy and I have an error message.

### Tachiyomi version

r4430

### Android version

Android 10

### Device

Moto G7 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
The error is most likely causes by low memory. Try a phone restart or close all other apps then re-download the same chapter and see if the issue persists. When you receive the error the page that causes the isssue will not be splitted but kept as the original size. Which is causing the reader lag you are facing.

**Comment by hyoretsu** [comment]
Somehow my memory's full even with only Tachiyomi open in the foreground and even after restarting I guess. (78% average used on last 3h according to developer options, 2.9/3.7 GB)

**Comment by AntsyLich** [comment]
The PR #7435 which will hopefully resolve this. 

Tested it on an emulator with 512mb ram. Tachiyomi was lagging hard but splitting didn't fail

**Comment by hyoretsu** [comment]
Okay, now it's officially not a RAM problem. Here's the crash log and a logcat.
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9034052/tachiyomi_crash_logs.txt)
[logcat_07-03-2022_01-01-37.txt](https://github.com/tachiyomiorg/tachiyomi/files/9034053/logcat_07-03-2022_01-01-37.txt)

**Comment by Saud-97** [comment]
It shouldn't have crashed. That's concerning @AntsyLich please take a look.

**Comment by curche** [comment]
@hyoretsu the logs you've uploads have turned out to be empty. Regardless, since this issue is already closed, create a new issue with logs
