### ISSUE TITLE
Make bottom bar not hide on scroll by default

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#7231]
### Describe your suggested feature

Can you guys make bottom bar not to hide on scroll by default? You see, I'm not a fan this *fancy* behavior (or maybe I'm not the only user?). And the issue why I'm requesting this is because, when I scroll down to the bottom of my library, or on the list of my updates/history, I have to scroll up a bit **always** (which annoys me) just to show the bottom bar so that I can navigate to where I wanted.

Neither Google Play Store, Google Photos, Google Drive, Google Clock, nor Google Maps do not have this hide bottom bar on scroll behavior. 

### Other details

I am using preview version and I've seen that the option to turn off `Hide bottom bar on scroll` in Settings > Appearance was removed in https://github.com/tachiyomiorg/tachiyomi/commit/0b77b78f6a360d759241ac42b1dcf0fe66b27d50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Not having the navigation bar hide (at least right now) would obfuscate the bottom-most option in browse

**Comment by resoue** [comment]
Then make it after the app code is completely migrated to Compose? (Idek what is that ) And lesser code?

**Comment by arkon** [comment]
No longer relevant after some UI rewrites that are happening.
