### ISSUE TITLE
Library display option sometimes behave strangely

### ISSUE THREAD

**Issue by rspreet92** [tachiyomiorg/tachiyomi#7233]
### Steps to reproduce

There is no step it's just random.
Sometimes when I change library display option to list from grid or to grid from list, it creates a strange output. Manga Cover gets too large or too small and even formatting is also not right (like grid in list and single item in grid).

I have tried different combinations to reproduce it, but it's just random.

### Expected behavior

....

### Actual behavior

Please check screenshots:

![Screenshot_2022-05-30-23-28-06-554_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87747810/171042819-a16d3291-623a-46dd-b9f1-955b3a6e0627.jpg)
![Screenshot_2022-05-30-23-27-27-310_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87747810/171042829-bbfbe181-7dab-41a3-8749-0765b7e5cea9.jpg)
![Screenshot_2022-05-30-23-27-57-283_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87747810/171042831-9638b552-e1bc-46df-a6fb-7962a848321a.jpg)
![Screenshot_2022-05-30-23-27-55-407_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87747810/171042834-17587b1f-5543-48ae-abc3-f5a35a0433c7.jpg)

### Tachiyomi version

0.13.4-4430

### Android version

10

### Device

Redmi Note 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This sometimes happens on slower devices but it'll be irrelevant once the library view is rewritten in Compose.
