### ISSUE TITLE
App crashing when restoring backup

### ISSUE THREAD

**Issue by ViktorVoloshko** [tachiyomiorg/tachiyomi#7234]
### Steps to reproduce

1) Move to More → Backup
2) Press on Restore in Backup

### Expected behavior

Explorer window show up and let choose backup.

### Actual behavior

App or Android System just crashing.

### Crash logs

Logcat (cutted and full in archive, level warn):
[2022-05-31-03-21-15.txt](https://github.com/tachiyomiorg/tachiyomi/files/8801135/2022-05-31-03-21-15.txt)
[logs-2022-05-31-03-20-27.zip](https://github.com/tachiyomiorg/tachiyomi/files/8801136/logs-2022-05-31-03-20-27.zip)
Tachiyomi:
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8801151/tachiyomi_crash_logs.txt)

### Tachiyomi version

App version: 0.13.4-4430 (standard, b36ca92dd, 81, 2022-05-28T22:38Z)

### Android version

Android 11

### Device

POCO M3

### Other details

Xiaomi.eu ROM 12.5.8.0
MIUI optimization enabled (this feature enforced by devs and I can't try w/o it without disabling via ADB)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
05-31 03:20:07.731 E/AndroidRuntime(28863): FATAL EXCEPTION: main
05-31 03:20:07.731 E/AndroidRuntime(28863): Process: android:ui, PID: 28863
05-31 03:20:07.731 E/AndroidRuntime(28863): java.lang.RuntimeException: Unable to start activity ComponentInfo{android/com.android.internal.app.ChooserActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.mi.android.globalFileexplorer/com.android.fileexplorer.activity.FileActivity}; have you declared this activity in your AndroidManifest.xml?
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:663)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:61)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:67)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.ActivityThread$H.handleMessage(Unknown Source:67)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.os.Handler.dispatchMessage(Unknown Source:19)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.os.Looper.loop(Unknown Source:249)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.ActivityThread.main(Unknown Source:134)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at java.lang.reflect.Method.invoke(Native Method)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
05-31 03:20:07.731 E/AndroidRuntime(28863): Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.mi.android.globalFileexplorer/com.android.fileexplorer.activity.FileActivity}; have you declared this activity in your AndroidManifest.xml?
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Instrumentation.checkStartActivityResult(Unknown Source:105)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Instrumentation.execStartActivity(Unknown Source:227)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.startActivityForResult(Unknown Source:44)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.startActivityForResult(Unknown Source:1)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.startActivity(Unknown Source:74)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.startActivity(Unknown Source:1)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at com.android.internal.app.ResolverActivityInjector.configureContentView(Unknown Source:276)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at com.android.internal.app.ResolverActivity.onCreate(Unknown Source:309)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at com.android.internal.app.ChooserActivity.onCreate(Unknown Source:560)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.performCreate(Unknown Source:77)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Activity.performCreate(Unknown Source:1)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:399)
05-31 03:20:07.731 E/AndroidRuntime(28863): 	... 11 more
05-31 03:20:07.747 W/ActivityTaskManager(2069):   Force finishing activity android/com.android.internal.app.ChooserActivity
05-31 03:20:07.764 W/ActivityTaskManager(2069):   Force finishing activity eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.main.MainActivity
```

This is an MIUI issue. Did this somehow work on older versions of the app?

> MIUI optimization enabled (this feature enforced by devs and I can't try w/o it without disabling via ADB)

Yes, because MIUI breaks Android in a variety of weird ways like this.

**Comment by ViktorVoloshko** [comment]
> This is an MIUI issue. Did this somehow work on older versions of the app?

Older versions mean stable 0.13.4 or much older?
> Yes, because MIUI breaks Android in a variety of weird ways like this.

Yeah, but opening a file works fine for other apps and let me choose from where to open: Camera, Gallery or Files. This looks strange to me. I report to ROM devs.

**Comment by arkon** [comment]
Feel free to reopen of the ROM dev comes back with a suggestion on how to address it from our side.

**Comment by ViktorVoloshko** [comment]
Devs of Xiaomi.eu fixed this issue. Dev said that this is a Xiaomi failure. Here is thread: https://xiaomi.eu/community/threads/some-apps-crashing-on-opening-files-stable.66010/#post-660477
Now everything works fine.
![Screenshot_2022-05-31-22-49-46-143_com miui home](https://user-images.githubusercontent.com/87974065/171283615-eeb5a16f-9518-4dc9-ba78-0a76a12359a8.jpg)
