### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CherbyMina** [tachiyomiorg/tachiyomi#7235]
### Describe your suggested feature

Hello can we have this feature? Where we can exclude nsfw manga from history??

### Other details

![Screenshot_20220601-134457](https://user-images.githubusercontent.com/86648349/171336563-f50b4d7f-bbc5-4ef8-ad73-9fb8bfe4e9a8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#7103
