### ISSUE TITLE
Extended update scheduling

### ISSUE THREAD

**Issue by Iliansic** [tachiyomiorg/tachiyomi#7236]
### Describe your suggested feature

Is it possible to implement separate automatic update schedule by category and weekday?
![Screenshot_20220601-083329_Office](https://user-images.githubusercontent.com/15694943/171334749-1722710d-096e-4934-a637-f7188eb280ff.jpg)

Case usage 1: WSJ titles on mangaplus update once a week at around the same time, so we can put them into specific category and set it to update automatically once a week separately from the main library.

Case usage 2: separating update schedule for library by weekday will help disperse load on sources without limiting some categories to manual updates (yes, I am lazy and forgetful to do it manually)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#822 for categories and I believe time based jobs can't be done unless its an alarm in android.
