### ISSUE TITLE
Lagging and jumping behaviour.

### ISSUE THREAD

**Issue by OmarH2** [tachiyomiorg/tachiyomi#7237]
### Steps to reproduce

When trying to scroll down between extensions the app becomes lagging. Jumping from the top to bottom in one motion. 

https://user-images.githubusercontent.com/68925648/171348475-a0ea23f6-5528-4b07-af8c-f95a69cf606e.mp4

### Expected behavior

To move between extensions without lagging, as if you scroll in the browser.

### Actual behavior

When scrolling down it lags and jumps to the bottom or top in one Scroll. If I want to reduce the lagging I need to scroll extremely slowly.

### Crash logs

No carsh happened so far.

### Tachiyomi version

App version: 0.13.4-4430 (standard, b36ca92dd, 81, 2022-05-28T22:38Z)

### Android version

Android version: 12 (SDK 31) 

### Device

Samsung Galaxy Note 10 Plus. SM-N975F

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I have faced the same reading a manga, the manga had a lot of pages, and for some reason it jumped from page 2 to 10, and when i have tried to go back it became crazy and shuffled between pages.

**Comment by ve1mi** [comment]
Same shit. Huge lags in the Source Extensions Migration

**Comment by arkon** [comment]
#6951
