### ISSUE TITLE
Add extra spacing for "There's no previous/next chapter" (Webtoon/Cont. Vertical)

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7242]
### Describe your suggested feature

Add extra spacing to account for `status bar + top bar`, `bottom bar + navigation bar` so that "There's no previous/next chapter" looks better when app bars are visible. 

Some mockups:

![image](https://user-images.githubusercontent.com/63973749/171795440-4d88dc06-3c46-441e-9928-a5784f4116ce.png)

![image](https://user-images.githubusercontent.com/63973749/171795106-ab5fa0f8-1138-4192-b0b7-ab74cb6a5a11.png)

### Other details

Currently it looks like this. 

![image](https://user-images.githubusercontent.com/63973749/171794658-a09a63f1-e274-4355-8a12-cbf71a18a3a0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment]
Insets are added if you turn off fullscreen mode afaik

**Comment by CVIUS** [comment]
Will be useless if using fullscreen system navigation
![Screenshot_20220603-133307_Tachiyomi](https://user-images.githubusercontent.com/84634607/171792804-c654f8ec-d1b0-4a6e-9166-3fbc8aa31f37.png)

and https://github.com/tachiyomiorg/tachiyomi/pull/7115#issuecomment-1126711176

**Comment by vengiare** [comment]
> Insets are added to current viewer if you turn off fullscreen mode afaik

![Screenshot_20220603-133311_Tachiyomi](https://user-images.githubusercontent.com/63973749/171792980-5d8a9397-e272-4675-a347-4a7d90803666.png)

> and #7115 (comment)

That's basically what i'm hoping for, extra spacing so "no prev/next chapter" are visible when app bars are visible.

**Comment by vengiare** [comment]
Mdded mockups. I don't really know a prettier way of doing it yet.
