### ISSUE TITLE
[FR] Anilist Score Modes (ScoreFormat)

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7245]
### Describe your suggested feature

Anilist supports several scoring modes. In the API it is called `ScoreFormat`. This request is to allow the user to select which they use in the app. 

API reference: https://anilist.github.io/ApiV2-GraphQL-Docs/

I am unsure how this would be implemented as a per-entry setting, so it would most likely be an app-wide setting if implemented. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nzoba** [comment]
It's automatically set to the format you were using when you logged into Anilist in the app. You can just change it in Anilist then log out from the app and log back in to update your score format

**Comment by mm12** [comment]
> It's automatically set to the format you were using when you logged into Anilist in the app. You can just change it in Anilist then log out from the app and log back in to update your score format

Appears to be already fixed. I don't use other ones personally so I cannot check, but if someone else shows this isn't right then feel free to re-open
