### ISSUE TITLE
[FR] UX: Mangadex autofill tracking

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7246]
### Describe your suggested feature

When adding tracking to a title from MD, allow users the option to attempt to allow MD to autofill tracking. This uses the MD API's `Links` section, where (in JSON format), MD shows the links to sources, tracking, etc. This includes many of the currently supported (and soon supported) tracking sites, such as MAL, Anilist, Kitsu, and MangaUpdates. 

API Location: `MangaAttributes/Links`

Users should be able to disable this in settings. 

### Other details

I haven't down too deep of a dive, but it looks like there is a variable called `media_id ` that is input into the Base string for each tracker. This should be the same as the ID stored in the MD database, from what I can tell. 

This is probably a stretch goal if I'm gonna be honest, it is low priority in terms of features. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The main app tries to avoid any source-specific logic, and the presence of tracking data from sources is far too rare to support more generically.
