### ISSUE TITLE
Download queue reordering causes redownload

### ISSUE THREAD

**Issue by openube** [tachiyomiorg/tachiyomi#7249]
### Steps to reproduce

Problem: When attempting manual reordering, the current download will rescan to redownload. Never seen this in earlier version, especially not 0.13.2 or earlier.

Reproduce:
1. Go to Download Queue, place a bunch of download, especially long list that requires scrolling
2. Simply do a manual reorder, from somewhere in the middle to the second on the queue. 

### Expected behavior

The normal behavior should have been for 
  (1) manual re-ordering in older version, 
  (2) how friendly UI would work, and
  (3) no extra network loads 
is any re-ordering should not affect current item download state, unless if the ordering is placed above current downloading item.

### Actual behavior

The action of pressing the left double bar icon to move it up will trigger then rescan/redownload.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Oneplus Nord N200

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #7492
