### ISSUE TITLE
Category update exclusion does not apply to Library and Update tabs

### ISSUE THREAD

**Issue by openube** [tachiyomiorg/tachiyomi#7250]
### Steps to reproduce

1. Start the app, the default tab is Library.  This will attempt to load all manga of the last accessed tab. It will take a long time to load, 40s to 1 min depending on the amount of manga.
2. Go to the Update tab, this will check all manga regardless any exclusion. This will also take a long time to load, 40s to 1 min, sometimes longer.
3. Library and Update tabs will remain blank when coming back to it from other tabs after a while. Take 40s to 1 min to load.
4. Make sure there is no obselete extensions

### Expected behavior

Any refreshes on Library and Update tabs should include all exclusions in Auto download or Auto update. This used to work in v0.13.2.

Any categories excluded should be excluded from any refreshes on Library or Update tabs.

### Actual behavior

Both Library and Update tabs ignore any exclusion rules. Hence took a long time.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

OnePlus Nord N200

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Those exclusions are for their own distinctive use cases.

For updates tab it'll be faster after it's rewritten in compose with sqldelight. The same also probably applies for library.

And even in my 10 year old potato with a library of 1k items it doesn't take 1 min to old

**Comment by arkon** [comment]
I don't think this applies in newer versions anymore.
