### ISSUE TITLE
Doujindesu extension cant load preview image

### ISSUE THREAD

**Issue by Ternesio** [tachiyomiorg/tachiyomi#7251]
### Steps to reproduce

1. I open tachiyomi app
2. Install doujindesu extension
3. Preview image cant load

I try again it from step 2, by re-install extension, but the result is still the same

### Expected behavior

Inage preview can load like other extension

### Actual behavior

Image preview in doujindesu extension cant load, but in other extension can
![Screenshot_20220605-001724062](https://user-images.githubusercontent.com/105666518/172018386-6a38650b-446b-48d8-ae3b-171ccf1ab829.jpg)

### Tachiyomi version

0.13.4

### Android version

10

### Device

Lenovo K5 Play

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
