### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by 64Evolution** [tachiyomiorg/tachiyomi#7255]
### Steps to reproduce

1. Open the app
2. App crashes

### Expected behavior

App should open to a functional screen

### Actual behavior

App crashes

### Crash logs

I quite literally cannot open the app to obtain crash logs. 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Galaxy S22 Ultra

### Other details

https://user-images.githubusercontent.com/78991664/172032329-1f6d7f9a-62f6-4bb7-8326-15127ec606b3.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kasperskier** [comment]
If you are offline, check https://github.com/tachiyomiorg/tachiyomi/issues/7203#issuecomment-1140151618 if you have old versions of the listed extensions installed.

Otherwise, try uninstalling extensions one by one to see if it's caused by any extension.

**Comment by 64Evolution** [comment]
The status of my wifi/cellular has no effect on the issue,

**Comment by 64Evolution** [comment]
Did not intend to close this, Wifi/cellular status has no effect on the issue, What would the file path be to the extensions to uninstall them?

**Comment by kasperskier** [comment]
> What would the file path be to the extensions to uninstall them?

System settings → Apps. Extension names start with `Tachiyomi: `.

**Comment by 64Evolution** [comment]
Even after removing all extensions it continues to crash on launch.
Ive also attempted:

- Clearing app Cache
- reinstalling app
- restarting device
- force stopping app
- fully powering down and back on device

**Comment by kasperskier** [comment]
Probably try "Take bug report" in [developer options](https://www.samsung.com/uk/support/mobile-devices/how-do-i-turn-on-the-developer-options-menu-on-my-samsung-galaxy-device/)?

**Comment by curche** [comment]
> I quite literally cannot open the app to obtain crash logs.

Try the following:
1. Tap and hold on the app icon
2. There are options for Browse, Updates..
3. Choose one of them and see if the app opens
4. If it does open the app, headover to `More > Settings > Advanced > Dump Crashlogs`

**Comment by 64Evolution** [comment]
> > I quite literally cannot open the app to obtain crash logs.
> 
> Try the following:
> 
>     1. Tap and hold on the app icon
> 
>     2. There are options for Browse, Updates..
> 
>     3. Choose one of them and see if the app opens
> 
>     4. If it does open the app, headover to `More > Settings > Advanced > Dump Crashlogs`

All of the options on tap and hold also cause the crash

> Probably try "Take bug report" in [developer options](https://www.samsung.com/uk/support/mobile-devices/how-do-i-turn-on-the-developer-options-menu-on-my-samsung-galaxy-device/)?

I assume I should post it once its done?

**Comment by curche** [comment]
> All of the options on tap and hold also cause the crash

Ohno. That's interesting. So something stranger than usual is happening.

> I assume I should post it once its done?

Yes. You shud be able to get a link or a saved file that can be shared.

Otherwise, there's also Logcat Reader. Copying from our Discord
> [Logcat Reader](https://play.google.com/store/apps/details?id\u003dcom.dp.logcatapp) makes it easy to view and save the device logs.
> Use ADB to grant android.permission.READ_LOGS to LogCatReader.
> `adb shell "pm grant com.dp.logcatapp android.permission.READ_LOGS && am force-stop com.dp.logcatapp"`
> Try to recreate the crash while logcat app is running in background and then Pause the logcat app, see if any errors did pop up, Export/Save the file

**Comment by 64Evolution** [comment]
[logcat_06-06-2022_02-39-18.txt](https://github.com/tachiyomiorg/tachiyomi/files/8843024/logcat_06-06-2022_02-39-18.txt)
Ran logcat and recreated the crash a couple of times

**Comment by kasperskier** [comment]
```
android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
```
Well...

**Comment by 64Evolution** [comment]
Well that certainly is concerning... I am entirely unsure of what to do regarding that

**Comment by Saud-97** [comment]
Install Google's webview app it might help.

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US

**Comment by curche** [comment]
Yea the app needs WebView for browsing website/sources

Check Android Settings
Enable Developer Options and try to find "WebView implementation" setting. Usually shows an Android System WebView or sometimes Chrome. (You can share a screenshot of it if you can)
Then check if that app was disabled (from Android Settings > Apps)
Or maybe it might have been updated recently. so try disabling updates (if possible)

**Comment by 64Evolution** [comment]
![Screenshot_20220606-031427_Settings](https://user-images.githubusercontent.com/78991664/172132447-5b641682-102c-4ad7-adec-9befeee38653.jpg)
This is the only option shown in the WebView Implementation section, unsure of why its that specific message as I've never used dual app features on this phone

**Comment by ghostbear** [comment]
> https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US

And if you click this link are you able to install WebView?

**Comment by 64Evolution** [comment]
Solved issue by going to Settings > Advanced features > Dual messenger > Triple Dot button in the top right > Delete all dual app data
