### ISSUE TITLE
History don't get updated after reading manga

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#7259]
### Steps to reproduce

Read Any Manga -> Navigate to History Tab

### Expected behavior

manga has been read, will appear in history

### Actual behavior

manga has been read, doesn't appear in history

### Tachiyomi version

Preview r4445

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

After Update the app to r4445, this bug appear

https://drive.google.com/file/d/1MyLrRIrWVE1oP6q8XSq55sNk6c5XURXI/view?usp=sharing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Same root cause as #7222
