### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by x3tj16** [tachiyomiorg/tachiyomi#7264]
### Steps to reproduce

1.open a manhua
2. Start scrolling 

### Expected behavior

Image should be displayed normally

### Actual behavior

at many place the picture is broken , some place it is zoomed in , some places the half of image is in top while other half which was supposed to be in its side is in bottom. I tried different extension but issue still persists
![Screenshot_2022-06-07-19-56-25-265_eu kanade tachiyomi](https://user-images.githubusercontent.com/85288581/172406818-3800c6c2-51a3-44d9-9964-09706f291263.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Redmi Note 10s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
turn off crop borders

**Comment by x-tj** [comment]
It didn't work . But then i went to settings>reader>webtoon> dual page split> turn off 
It started working as normal
