### ISSUE TITLE
No pages found

### ISSUE THREAD

**Issue by AnonymousAshiel** [tachiyomiorg/tachiyomi#7272]
### Steps to reproduce

I opened an extension. I search the manwha I was interested in and clicked the first episode and it said no pages found. I was also downloading a chapter when it said no chapters found

### Expected behavior

It should have opened the chapter

### Actual behavior

It doesn't open it just says no pages found

### Crash logs

tachiyomi_crash_logs

--------- beginning of crash
05-29 09:41:14.446  5773  8671 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb0 in tid 8671 (DefaultDispatch), pid 5773 (anade.tachiyomi)
05-29 09:41:14.726  8777  8777 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-29 09:41:14.726  8777  8777 F DEBUG   : Build fingerprint: 'samsung/a01qxx/a01q:11/RP1A.200720.012/A015FXXS5BVC1:user/release-keys'
05-29 09:41:14.726  8777  8777 F DEBUG   : Revision: '0'
05-29 09:41:14.726  8777  8777 F DEBUG   : ABI: 'arm'
05-29 09:41:14.738  8777  8777 F DEBUG   : Timestamp: 2022-05-29 09:41:14+0800
05-29 09:41:14.739  8777  8777 F DEBUG   : pid: 5773, tid: 8671, name: DefaultDispatch  >>> eu.kanade.tachiyomi <<<
05-29 09:41:14.739  8777  8777 F DEBUG   : uid: 12019
05-29 09:41:14.739  8777  8777 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb0
05-29 09:41:14.739  8777  8777 F DEBUG   : Cause: null pointer dereference
05-29 09:41:14.739  8777  8777 F DEBUG   :     r0  00000000  r1  12e7bb38  r2  131b8b28  r3  00000001
05-29 09:41:14.739  8777  8777 F DEBUG   :     r4  b8995034  r5  14967930  r6  131b8b28  r7  00000000
05-29 09:41:14.739  8777  8777 F DEBUG   :     r8  00000000  r9  d261b400  r10 12e7bb38  r11 00000197
05-29 09:41:14.739  8777  8777 F DEBUG   :     ip  f0000000  sp  b8995c50  lr  bfa94411  pc  bfa94420
05-29 09:41:14.926  8777  8777 F DEBUG   : backtrace:
05-29 09:41:14.926  8777  8777 F DEBUG   :       #00 pc 00452420  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (androidx.core.app.NotificationCompat$Builder.build+136)
05-29 09:41:14.926  8777  8777 F DEBUG   :       #01 pc 0051764d  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (eu.kanade.tachiyomi.data.library.LibraryUpdateNotifier.showProgressNotification+1484)
05-29 09:41:14.926  8777  8777 F DEBUG   :       #02 pc 005196b9  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (eu.kanade.tachiyomi.data.library.LibraryUpdateService.access$withUpdateNotification+1432)
05-29 09:41:14.926  8777  8777 F DEBUG   :       #03 pc 007e4b0b  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (eu.kanade.tachiyomi.data.library.LibraryUpdateService$updateChapterList$2$2$1.invokeSuspend+2362)
05-29 09:41:14.928  8777  8777 F DEBUG   :       #04 pc 006c5ab3  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+210)
05-29 09:41:14.928  8777  8777 F DEBUG   :       #05 pc 006da04f  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (kotlinx.coroutines.DispatchedTask.run+2174)
05-29 09:41:14.928  8777  8777 F DEBUG   :       #06 pc 005e044f  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely+46)
05-29 09:41:14.928  8777  8777 F DEBUG   :       #07 pc 005de2a9  /data/app/~~X3aK9J9PRZu5eZ7I6SKHVg==/eu.kanade.tachiyomi-1VigvKHEgAneQ-G8lEiXVQ==/oat/arm/base.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run+2640)
05-29 09:41:14.928  8777  8777 F DEBUG   :       #08 pc 000d49d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #09 pc 004bd3d3  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+294) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #10 pc 00123631  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+148) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #11 pc 003e261f  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #12 pc 003e3411  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+356) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #13 pc 003e359f  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.929  8777  8777 F DEBUG   :       #14 pc 0042311f  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1066) (BuildId: ef80691575618a5eccba9d3706a1f7ee)
05-29 09:41:14.930  8777  8777 F DEBUG   :       #15 pc 000b0547  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: 25671fc300e72247ccaaf22111af90f6)
05-29 09:41:14.930  8777  8777 F DEBUG   :       #16 pc 00066b17  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 25671fc300e72247ccaaf22111af90f6)
--------- beginning of main
06-09 09:28:06.520  8555  8555 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
06-09 09:28:08.504  8555 11627 E SQLiteLog: (284) automatic index on C(manga_id)
06-09 09:28:08.504  8555 11627 E SQLiteLog: (284) automatic index on R(manga_id)
06-09 09:28:08.504  8555 11627 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A015FXXS5BVC1
Device brand: samsung
Device manufacturer: samsung
Device name: a01q
Device model: SM-A015F
Device product name: a01qxx

### Tachiyomi version

Stable 0.13.4

### Android version

A015FXXS5BVC1 / A015FOLM5BUJ1 / A015FXXU5BUJ1

### Device

Samsung Galaxy A01

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
