### ISSUE TITLE
Make the extension repo more accessible in certain region

### ISSUE THREAD

**Issue by kasperskier** [tachiyomiorg/tachiyomi#7274]
This is a continuation of #5517. In that issue, jsDelivr's CDN (by subdomain) was used to provide fallback for GitHub.

However, as per https://github.com/jsdelivr/jsdelivr/issues/18397#issuecomment-1150588086 and my tests, jsDelivr's subdomains are gradually getting blocked.

One solution is to add a preference to let user manually enter a usable private mirror of jsDelivr (or any other mirrored repo), which can be found in the jsDelivr issue above. (which sounds unstable)

Another solution is to mirror the extension repo to another site by utilizing existing [GitHub actions](https://github.com/marketplace/actions/mirroring-repository). One choice is GitLab, which has its own support to [automatically update a mirror repo](https://docs.gitlab.com/ee/user/project/repository/mirror/) (while a manual trigger by CI can be a plus). Although anyone can set up a mirror, an official one is more preferable.

**Comment by arkon** [comment]
I feel like at some point, the onus is on the users to work around their limitations. The Great Firewall isn't really a new thing, so surely a VPN would just be an easier solution in general?
