### ISSUE TITLE
Add feature custom zoom

### ISSUE THREAD

**Issue by SAYATHEB** [tachiyomiorg/tachiyomi#728]

**Comment by SAYATHEB** [comment]
Is there any consideration for this?

**Comment by duncannduncs** [comment]
Yeah. I like to zoom out while reading horizontally since my screen isn't that big. The only zoom function that gives me that option is "fit height" however I need to constantly change the zoom ratio every page. Wish there was a custom zoom to fit my preffered zoom ratio.

**Comment by arkon** [comment]
Closing in favour of #1822
