### ISSUE TITLE
Issues with downloaded chapters with identical names/from identical titles

### ISSUE THREAD

**Issue by Elaborendum** [tachiyomiorg/tachiyomi#7280]
### Steps to reproduce

Case 1: Identical chapter names, same title.
- Download a chapter with a name identical as another from the same title
- See that Tachiyomi marks all chapters of the same name as downloaded (with the cover badge counting all chapters of the same name), even if you only downloaded one of them. 

Case 2: Two titles with identical names from the same source
- Download at least a chapter each from two entries of the same name and source
- See that the cover badge for each shows the total amount of chapters you downloaded in Step 1 instead of showing the amount downloaded per title
- If chapter names are identical, then the first one downloaded will take the place of the one with the same name in the other title.

### Expected behavior

Tachiyomi should recognize which chapter was downloaded instead of covering all chapters with the same name.

The app should also have separate folders for the two identically named series.

### Actual behavior

Case 1: Downloading one chapter out of many identical ones causes all of them to be marked as downloaded. Opening any of them only opens the originally downloaded chapter, leaving you unable to access any of the other chapters unless you delete the original.

Case 2: Tachiyomi uses the same folder for identical titles from the same source to store all downloaded chapters for each.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Galaxy A12

### Other details

You can test it out using the Cubari extension, for Case 1 you can create a Gist with multiple chapters of the same name and for Case 2 you can choose two Imgur posts with the same name.

However, the issue isn't only present in Cubari, it seems like it affects all sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #6665
