### ISSUE TITLE
Provide an alternative for Shizuku for emulators

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7281]
### Describe your suggested feature

I would like to request for a Shizuku alternative since Shizuku doesn't support emulators.

Maybe implement a root only feature for silent installation of extensions as a workaround for emulators.

See [Install apps silently, with granted INSTALL_PACKAGES permission](https://stackoverflow.com/questions/5803999/install-apps-silently-with-granted-install-packages-permission)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is definitely not worth the effort, emulators aren't even a common nor recommended usecase.
