### ISSUE TITLE
Shadow mangas's extension issues

### ISSUE THREAD

**Issue by seba1107** [tachiyomiorg/tachiyomi#7282]
### Steps to reproduce

The extension "Shadow Mangas" don't show any manga.

### Expected behavior

It should show the library when you enter to the extension

### Actual behavior

It don't show anything.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Xiaomi poco x3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Wrong repository.
