### ISSUE TITLE
Dark reader menu in light mode

### ISSUE THREAD

**Issue by Trotyl15** [tachiyomiorg/tachiyomi#7285]
### Describe your suggested feature

Is there a way to switch the reader menu to dark mode while in the light mode? (Like in v0.11.1) If not yet, I hope there can be a place where the users can choose to make it dark.
(I'm talking about the part circled in red)
<img src="https://user-images.githubusercontent.com/55414757/173201041-1d517b70-7781-48ec-a86c-41178b83e651.jpg" height="500px">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The themes were unified to simplify it. If you want a dark theme, use a dark theme.
