### ISSUE TITLE
Installing extensions in Tachiyomi

### ISSUE THREAD

**Issue by Architect-Ivy** [tachiyomiorg/tachiyomi#7286]
### Steps to reproduce

1. Go to browse
2. Swipe right to left or simply click/touch extension
3. Install extension you want

### Expected behavior

Download extension app

### Actual behavior

The extension apps did not load and unable to download even on manually

### Crash logs

![Screenshot_20220612-071332_Tachiyomi](https://user-images.githubusercontent.com/107328165/173208264-e1096867-48f4-48bb-b661-1ce274cfeb36.jpg)

### Tachiyomi version

App version: 0.12.3

### Android version

App version: 0.12.3
Android version: 11 (SDK 30) Android build ID: 
 Device brand: samsung Device

### Device

Samsung Galaxy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You didn't even read the acknowledgements.
