### ISSUE TITLE
Chapters do not load

### ISSUE THREAD

**Issue by Maratastic** [tachiyomiorg/tachiyomi#7287]
### Steps to reproduce

![Screenshot_20220611-205508_Tachiyomi](https://user-images.githubusercontent.com/74069001/173210003-8e047240-743d-4aac-8d38-b1692f0aead2.png)
Essentially when i go for opening a searched manga, no matter the extention im on, no chapters appear, ive refreshed, manually reloaded, reinstalled everything but nothing appears, despite then having chapters in their respective websites

### Expected behavior

Chapters should appears on respective chaptera

### Actual behavior

It shows no chapters (0chapters) and not actual chapters

### Crash logs

--------- beginning of main
06-11 20:58:48.436 25169 25169 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
06-11 20:58:48.437 25169 25169 E USNET   : USNET: appName: eu.kanade.tachiyomi.debug
06-11 20:58:48.699 25169 25169 E tachiyomi.debu: Invalid ID 0x00000000.
06-11 20:58:48.896 25169 25248 E SQLiteLog: (284) automatic index on C(manga_id)
06-11 20:58:48.896 25169 25248 E SQLiteLog: (284) automatic index on R(manga_id)
06-11 20:58:48.896 25169 25248 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.4-4460 (standard, d098eca69, 81, 2022-06-11T21:08Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G973WVLS6HVA1
Device brand: samsung
Device manufacturer: samsung
Device name: beyond1q
Device model: SM-G973W
Device product name: beyond1qltecs

### Tachiyomi version

App version: 0.13.4-4460 (standard, d098eca69, 81, 2022-06-11T21:08Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G973WVLS6HVA1 Device brand: samsung Device manufacturer: samsung Device name: beyond1q Device model: SM-G973W Device product name: beyond1qltecs

### Android version

Android 12

### Device

Samsung s10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Known issue with the work in progress migrations. 

Workaround is to back out and open the manga again to see the loaded chapters.
