### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Obii5000** [tachiyomiorg/tachiyomi#7291]

**Comment by Soitora** [comment]
Make sure you're using Webtoon reading mode, because there's no issue at all reading and zooming 

https://user-images.githubusercontent.com/10836780/173219757-9a318821-9bf7-4868-b90b-46706386abbb.mp4

**Comment by Obii5000** [comment]
Can I ask how can you turn that on?

**Comment by Obii5000** [comment]
> Make sure you're using Webtoon reading mode, because there's no issue at all reading and zooming
> 
>  Screen_Recording_20220612-081900_Tachiyomi.mp4

Can I ask how do you turn that on?
