### ISSUE TITLE
Force English language in app interface

### ISSUE THREAD

**Issue by NomarCub** [tachiyomiorg/tachiyomi#7294]
### Describe your suggested feature

I remember being able to change the app's language but I can't anymore. I want to change to any language or at least be able to force English. It helps with navigating incomplete or weird translations in my language and with finding the official names of settings when looking for documentation or reporting bugs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This feature was removed because it was causing several issues and it was a pain to maintain. You will be able to change the language per app in Android 13 though.

If you find the translation in your language bad or incomplete, you're welcome to help translating the project through Weblate.
