### ISSUE TITLE
Text doesn't fit

### ISSUE THREAD

**Issue by NomarCub** [tachiyomiorg/tachiyomi#7300]
### Steps to reproduce

I have at least 3 instances, where text is overly long and not handled well.

Here is the reading view, when the number of pages of the manga has 4 or more digits:
![Screenshot_2022-06-12-19-09-39-048_eu kanade tachiyomi](https://user-images.githubusercontent.com/5298006/173253537-4a92bd25-1a10-4931-a6c9-5960f3809c43.jpg)

Here's the biometric protection thing. The text in blue is "minta használata"  (~use pattern in Hungarian):
![IMG_20220612_163758](https://user-images.githubusercontent.com/5298006/173253800-16cbdc1e-bc21-4cce-957d-da79297f0766.jpg)

Here are the buttons for the 5 sections of the app in the bottom. The space between the 2nd and 3rd is too small, and I don't really like the ellipses after the 3rd either.
![Screenshot_2022-06-12-16-36-18-43_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/5298006/173253957-69a7898b-4ff1-48ef-bd66-cd6f5858f148.jpg)

These are at the top when the browsing mode is selected. They are from the TachiyomiSY fork, where there's 4 tabs here instead of 3. But still, I suspect the rules derive from here. The splitting of the word at the last letter ("Bővítménye-k") is very unnatural in Hungarian. Splitting a single word and having it in two rows in this interface is also weird.
![Screenshot_2022-06-12-17-16-49-42_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/5298006/173255599-181610c1-ccd6-4629-b7b5-1dcf9fc58433.jpg)

### Expected behavior

If possible smaller fonts would be nice here, maybe in a dynamic way only when it's necessary. Or some design that doesn't have this much text in one row.

### Actual behavior

Text overflows into the next row when the object containing it is not prepared for it well.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

OnePlus 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Here is the reading view, when the number of pages of the manga has 4 or more digits:

Will be fixed.

> Here's the biometric protection thing. The text in blue is "minta használata" (~use pattern in Hungarian):

This is controlled by the system UI.

> Here are the buttons for the 5 sections of the app in the bottom. The space between the 2nd and 3rd is too small, and I don't really like the ellipses after the 3rd either.

This is the recommended behaviour by Google. If you can think of shorter text, feel free to change them: https://tachiyomi.org/help/contribution/#translation

> Splitting a single word and having it in two rows in this interface is also weird.

This is also the recommended behaviour by Google.
