### ISSUE TITLE
new source: DragonTea.ink

### ISSUE THREAD

**Issue by Zack7292** [tachiyomiorg/tachiyomi#7301]
### Describe your suggested feature

i don't really know how to make sources and i don't have the knowledge to make the extension, so i was wondering if it was possible to add a source for https://dragontea.ink/

### Other details

https://dragontea.ink/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Wrong repository and was already requested.
