### ISSUE TITLE
Smart Fit in Preview

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#7302]
### Steps to reproduce

Open a manga with a spread/long horizontally page.

### Expected behavior

Smart Fit would fit the image so I see it all, resized. (same as "Fit Screen" without automatic zoom in)

### Actual behavior

Now it goes fullscreen. (same as Stretch)

### Tachiyomi version

Preview r4466

### Android version

Android 12

### Device

Samsung Galaxy S10

### Other details

I have always had it activated, probably cuz in the past i had problems with some pages using "Fit Screen" (also I don't like the zoom in on this).

https://user-images.githubusercontent.com/22413659/173460781-c4884bca-6b11-4479-b1a2-219b99076a72.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by antocs** [comment]
P.s IIRC it happened in r4460 too but it was late night and forgot to open an issue.

**Comment by antocs** [comment]
Where do I find that? I have never seen that option.
![Screenshot_20220614-152151_Tachiyomi](https://user-images.githubusercontent.com/22413659/173587737-7ec0f411-889a-41f2-a00f-1344fbf18b21.jpg)

**Comment by antocs** [comment]
Ok I found it, and it works exactly like Smart Fit was doing before r4460, but if there is no changes to it then I'll just switch to Fit Screen.

**Comment by curche** [comment]
Alright :ok_hand:  
It isnt exactly like Smart Fit but it has its similarities. I'll mark this as resolved then
