### ISSUE TITLE
Library update causes crash

### ISSUE THREAD

**Issue by volt001** [tachiyomiorg/tachiyomi#7304]
### Steps to reproduce

1a) Pull down on library/press update ring in corner
1b) Press update ring in corner
2) Crash

### Expected behavior

Library starts to look for updates

### Actual behavior

App crashes and then crashes one more time upon reopening the app. The second reopen is ok.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8896180/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Galaxy Note 20 Ultra

### Other details

Before this, I had an issue where a few of my extensions disappeared so I backed up my library and reinstalled the app which fixed it but then this became the problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably relevant: https://stackoverflow.com/questions/50972669/cannot-get-wake-lock-permission-on-android-8-oreo/50972790#50972790

Should be fixed in the next release.
