### ISSUE TITLE
Migrating causes Tachiyomi too freeze.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#7305]
### Steps to reproduce

1. Migrate a manga.
2. On the migration screen choose a manga to migrate to.
3. Click migrate.

### Expected behavior

Mifration completes without any issue.

### Actual behavior

The screen gets stuck on loading indefinitely and it seems like you can click around and open other manga while this happens. If you try to go back Tachiyomi freezes and after a while you get the app not responding dialogue.

### Tachiyomi version

0.13.4-4466

### Android version

Android version: 11 (SDK 30) 

### Device

Redmi Note 9 Pro Max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Matakor** [comment]
To add to this, I am unable to use Tachiyomi at all after attempting migration. It opens to the load screen and freezes. I would say this is a major issue, if anyone else has the same problem.

**Comment by AntsyLich** [comment]
This is an expected issue as we continue to rewrite parts of the app.

**Comment by jmir1** [comment]
> This is an expected issue as we continue to rewrite parts of the app.

Do you know why it doesn't work?
If we await `chaptersQueries.getChaptersByMangaId`, it just emits nothing at all...
I'm confused as to why this is happening...

**Comment by jobobby04** [comment]
db.inTransaction in migrateMangaInternal blocks other threads from querying the db. `chaptersQueries.getChaptersByMangaId` is blocked because it uses a seperate thread in the TransactionDispatcher. Which causes everything to stall.

**Comment by jmir1** [comment]
> db.inTransaction in migrateMangaInternal blocks other threads from querying the db. `chaptersQueries.getChaptersByMangaId` is blocked because it uses a seperate thread in the TransactionDispatcher(runBlocking doesnt stop other places from switching threads). Which causes everything to stall.

aaahh i get it now, thanks for the explanation.
it was simple to fix by invoking migrateMangaInternal as a suspend function instead of using runBlocking inside of it...
