### ISSUE TITLE
New chapters don't appear in Library

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi#7307]
### Steps to reproduce

1. Update some category with filter "Unread" is on

### Expected behavior

New chapters appear in library

### Actual behavior

You don't see new chapters until you swap to another screen (update,. extensions or other) and back to library

### Tachiyomi version

r4466

### Android version

MIUI 13

### Device

Xiaomi poco x3

### Other details

In stable version 0.13.4 it works correctly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This is an expected issue as we continue to rewrite parts of the app.

**Comment by Akazotik** [comment]
> This is an expected issue as we continue to rewrite parts of the app.

Also i can't update tachi from notifications. I have to download apk from git

**Comment by arkon** [comment]
Should be fixed in next preview build.

> Also i can't update tachi from notifications. I have to download apk from git

See #7439
