### ISSUE TITLE
Library Not Updating

### ISSUE THREAD

**Issue by ydahfridgeempty** [tachiyomiorg/tachiyomi#7313]
### Steps to reproduce

1. Open Tachiyomi
2. Press update button

### Expected behavior

When updating the progress is shown in the notification and stays until completed. The updates also show one by one in the updates tab.

### Actual behavior

The update process stops when it reaches 36 titles and no updates are produced in the update tab.

### Tachiyomi version

0.13.4

### Android version

12

### Device

Samsung A52

### Other details

I tried deleting and reinstalling certain extensions based on which manga the update stopped at to see if it was a problem with the extension or the manga. I also tried deleting and reinstalling the app, I went as far to restart and reset my phone but nothing. It never goes past 36 titles. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Maor-Ar** [comment]
If the libraries you are trying to update have unread chapters it may be the cause.
A couple of updates ago there was a change in order to minimize requests and to get relevant updates faster,
(Correct me if I'm wrong).
Try to mark all the chapters as read and see if it fixes the issue.

**Comment by ydahfridgeempty** [comment]
Hi. Even when that is done, it doesn't update the titles overall. I've marked all chapters as read and checked the website to ensure that there is infact a new chapter and updated a specific title but it didn't load. I've migrated certain titles to bypass it but others, I can't avoid. Thank you though appreciate it.

**Comment by arkon** [comment]
Try asking on Discord for help, there isn't enough details in this to ascertain an actual bug to be addressed.
