### ISSUE TITLE
Storage usage

### ISSUE THREAD

**Issue by WildPortal** [tachiyomiorg/tachiyomi#7318]
### Describe your suggested feature

A feature to see how much space is being used by each extension you are using and the ability to see how much each manga is using.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You mean downloads? Just use a file manager and navigate to the correct folder

**Comment by CrepeTF** [comment]
#6697

**Comment by arkon** [comment]
Duplicate of #4859
