### ISSUE TITLE
Limit Wi-Fi use

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#7319]
### Describe your suggested feature

In download queue or in downloads option, we should have an option which allows us to limit the rate of Wi-Fi usage.
In other words we should have a option by which we could control the app Wi-Fi usage

### Other details

While downloading many chapters of a manga, the server may get loaded, so to tackle this we should have a option to limit our Wi-Fi speed to lets say 1 MBPS. By doing this, till we read one chapter, the next would have been already downloaded and the servers will not get overloaded because of high speeds.
The limiting options can be -
1. 1 MBPS
2. 2 MBPS
3. 3 MBPS
4. No restriction (Default option)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No interest in implementing such a thing. Throttle your device using your router if need be.
