### ISSUE TITLE
failed to open in application

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi#7323]
### Steps to reproduce

i can view the extension and add to fav , but i can't read and download it there 

### Expected behavior

we should can open / read the chapter , and downloaded it

### Actual behavior

can't download the chapter / another manga 
![image](https://user-images.githubusercontent.com/105035665/174314834-2bf04ea5-7338-4c5c-8e6a-7188972a3a2c.png)

### Crash logs

--------- beginning of main
06-17 20:56:20.984 20178 20178 E ViewRootImpl: sendUserActionEvent() mView returned.
App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N970FXXU8HVE5
Device brand: samsung
Device manufacturer: samsung
Device name: d1
Device model: SM-N970F
Device product name: d1xx

### Tachiyomi version

0.13.4

### Android version

andorid 12

### Device

samsung galaxy note 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If this specific to a source, please open an issue in the extensions repository.

If you're experiencing this for everything, please try asking for help on Discord first.
