### ISSUE TITLE
Crashing when viewing the history page on update

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#7328]
### Steps to reproduce

1. Swipe down to start the global update
2. Go to the history page
3. After about 10-15s the app closes and the history page constantly refreshes for no reason

### Expected behavior

No crash and no constant refreshes on the history page

### Actual behavior

It crashes after about 15s on the history page and constantly refreshes this page

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8933072/tachiyomi_crash_logs.txt)

### Tachiyomi version

r4466

### Android version

Android 11

### Device

Oneplus 7

### Other details

https://user-images.githubusercontent.com/6564956/174426115-064f86d6-23c4-427d-9ec7-400c47814e07.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is this still happening?

**Comment by MrAndre96** [comment]
> Is this still happening?

It is still constantly refreshing the page when there is no update (searching for new updates when you have disabled to update the metadata won't have changes for the history page) but the crashing issue has been fixed. Can make a separate issue if that is desired and close this one

**Comment by arkon** [comment]
Make a separate issue for that please.
