### ISSUE TITLE
For CBZ download feature, please add an option to download the pages to RAM, then only write the CBZ to storage

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#7336]
### Describe your suggested feature

its to reduce the write cycles of microsd card. Not sure how much/little it will improve the life of microsd cards tho. as very few manufacturers release their TBW.

But at the very least, theoretically, it'll be half as write cycle as the current implementation

### Other details

my understanding of current implementation is
1. download pages to storage, 
2. then compress CBZ to storage, 
3. and delete the downloaded pages

the requested option for the new implementation (don't remove the current implementation, low-ram devices still benefits)
1. download pages to RAM, 
2. then compress CBZ to storage, 
3. and delete the downloaded pages from RAM.

so current implementation there are 2 writes to the memory card. while if we use RAM for downloading the pages, there will be only 1 write to the memory card.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
Will never be implemented due to people still using potato phones with 2gb ram. Some phones can't even keep 1 tall page in memory and fails at splitting them.

**Comment by orangpelupa** [comment]
> Will never be implemented due to people still using potato phones with 2gb ram. Some phones can't even keep 1 tall page in memory and fails at splitting them.

They still can use the default behavior that's currently on tachiyomi. While the download to ram is an optional feature (that potentially made people with low ram complains it made their device unstable... Hmm maybe added with a minimum ram check for it to be available?)

Anyway, i was one of the people with ancient device. My old android 6 tablet missed a bunch of features that are available on newer tachiyomi on newer Android.

**Comment by arkon** [comment]
RAM allocation per app is limited anyway, so it's always safer to flush to disk.
