### ISSUE TITLE
Specific image from "Mairimashita! Iruma-kun" not loading

### ISSUE THREAD

**Issue by CodedGamer1** [tachiyomiorg/tachiyomi#7341]
### Steps to reproduce

1. Open "Mairimashita! Iruma-kun" on MangaDex Extension
2. Open Chapter 80
3. Go to page 6

### Expected behavior

Page is loaded

### Actual behavior

Page is stuck on loading screen

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Galaxy S10+

### Other details

- Downloading image did not fix the issue
- Downloading the image from MangaDex website and replacing the png file did not fix the issue
- When adding this image to a local manga it still does not load

![006](https://user-images.githubusercontent.com/107801668/174485750-833f9e83-7717-4a07-87a0-c305366b1130.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't even see an English version on the website. Please reopen if I'm apparently looking for the wrong thing.
