### ISSUE TITLE
Reading status not updated correctly in updates screen

### ISSUE THREAD

**Issue by Sai-P** [tachiyomiorg/tachiyomi#7347]
### Steps to reproduce

- Have r4489 or any version of Tachiyomi preview after r4430 installed.
- Have any series with unread chapters in the Updates page.
- Read at least one chapter.
- Exit reader (goes back to Updates page where you started reading the chapter)
- See the read chapter still showing unread.
- You have to change screen and come back for the right read status to show.

The same issue presents itself when marking a chapter unread in the chapter details page of a manga

Commit #7296 only partly fixed the issue (#7222) but only in the case of it being correctly marked as read in the chapter details page.

Ironically, manually marking as read and unread manually works perfectly fine within the Updates page.

### Expected behavior

Read status should update correctly once you finish reading a chapter or marking a chapter as read/unread.

### Actual behavior

Read chapter still shows itself as unread in the Updates page after reading a chapter.

[Read status not updated correctly in Updates page](https://photos.app.goo.gl/kJdejh3VAFAvseSb7) 

Marking a chapter as unread in the chapter details page also does not correctly display as such unless I change to a different page and come back to it.

[Marking as unread not working correctly in chapter details page](https://photos.app.goo.gl/LwzhKF5oBAKd4WFC9) 

### Tachiyomi version

Tachiyomi Preview r4489

### Android version

Android 12, Android 13

### Device

Sony Xperia 1 III, Google Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We are slowly changing the framework under the hood which is creating this inconsistency.

**Comment by Sai-P** [comment]
Yeah that's totally fine, just wanted to raise awareness so that multiple people don't open the same issue and/or so that it doesn't get forgotten about. As far as I know the eventual implementation of #7244 should fix any and all issues regarding this.

**Comment by AntsyLich** [comment]
#7244 is for manga screen. I also have a pr ready which will rewrite updates screen leading to fixing this issue but it's halted as it relies on some stuff from #7244

**Comment by antocs** [comment]
Issue happens when bookmarking a chapter too, gotta change page for the bookmark icon to appear.

**Comment by AntsyLich** [comment]
Was closed with #7534
