### ISSUE TITLE
Privacy implications of global search

### ISSUE THREAD

**Issue by chocolatkey** [tachiyomiorg/tachiyomi#7349]
### Describe your suggested feature

This isn't an issue with the code per se, but I thought I'd bring up something I've personally thought is a privacy issue/weakness of the global search that users may not realize - when they use this search, every (debounced) bit of input they put into that global search field gets spammed to every source they have installed, including for **official sources of manga**. So with a bit of motivation from the operator of a server, and using the IP address of users, a personalized profile of users' search history can be built even long after a user has forgotten they installed an extension. I don't think there's much you can do to solve this without somehow proxying/centralizing search requests, which would of course place great burden on a host, and run counter to some of Tachiyomi's core principles. But I thought, as someone who has seen a lot of Tachiyomi search traffic, that people should be made a bit more aware of this, and maybe in the long term you can think of a solution.
![image](https://user-images.githubusercontent.com/13407784/174661074-c8d9d8c5-72f4-4612-ae62-edb407479ff6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> when they use this search, every (debounced) bit of input they put into that global search field gets spammed to every source they have installed

It should only be submitting the requests when the user explicitly submits the query in newer versions. The automatic debounced requests on input changes was removed a while back.

> So with a bit of motivation from the operator of a server, and using the IP address of users, a personalized profile of users' search history can be built 

Is that not the case for any sort of server with any sort of web request?

> I don't think there's much you can do to solve this without somehow proxying/centralizing search requests

Indeed, we won't pursue anything like that. 

> and maybe in the long term you can think of a solution.

There's nothing to really solve here. If users really are worried about servers knowing that they've made requests to them, they should be masking their traffic with tools like VPNs at a higher level.
