### ISSUE TITLE
[BUG] Unable to access any extension or update any Chapters

### ISSUE THREAD

**Issue by Dnouv** [tachiyomiorg/tachiyomi#7352]
### Steps to reproduce

Try to open any extension.

### Expected behavior

The extensions should show some response.

### Actual behavior

The response is giving "Error 500", in the web version also it's a server error. For almost all of the extensions.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Google Pixel 5a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Architect-Ivy** [comment]
Same problem here, can't read any doujin/manga chapters

**Comment by Dnouv** [comment]
It seems like all the sites related to AWS are down. Phew, at least GitHub is up for us to report issues.

**Comment by Jacfger** [comment]
I don't have such problem. Is that regional? But oof for the AWS related sites lmao

**Comment by Dnouv** [comment]
That's good buddy, we can't open Discord also. ＞︿＜

**Comment by Jacfger** [comment]
oh wow... yeah then I'm quite sure it's regional cause I'm still on Discord.
