### ISSUE TITLE
增加一键卸载失效插件

### ISSUE THREAD

**Issue by cyb233** [tachiyomiorg/tachiyomi#7358]
### Describe your suggested feature

类似一键更新，增加卸载废弃插件按钮
因为卸载必须要点开插件详情，如果长时间没使用应用可能要点开多个，

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
不需要点开详情，长按插件就可以卸载。而且插件被删除也不是高频率事件。
You can tap and hold to uninstall without entering the details page. Moreover, extensions don't get removed so often.
