### ISSUE TITLE
Conflict with update download

### ISSUE THREAD

**Issue by Chree218** [tachiyomiorg/tachiyomi#7359]
### Steps to reproduce

So I'm just trying to download it but I keep getting the same message say it conflict with a app and I have no idea how to fix it.

### Expected behavior

It should just update but it won't. 

### Actual behavior

Message saying conflict with a app 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Samsung galaxy s21

### Other details

![Screenshot_20220622-211917_Package installer](https://user-images.githubusercontent.com/108043551/175203638-e22ccc5d-8684-48a1-b6fd-ce4cdcbc5ce1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you installed from F-Droid originally: https://tachiyomi.org/help/faq/#how-do-i-migrate-from-the-f-droid-version

If not, please ask for help on Discord.
