### ISSUE TITLE
"Sakamoto Days" chapters show up in WebView but not in app

### ISSUE THREAD

**Issue by gr8stalin** [tachiyomiorg/tachiyomi#7361]
### Steps to reproduce

As a new user on a fresh install of Tachiyomi (v 0.13.4) with most recent MangaDex extension (v 1.3.165):

1. Search for "Sakamoto Days" in the MangaDex extension
2. Open manga summary page
3. App will display toast notification saying "No chapters found"
4. Click "WebView" button to open up MangaDex in the system browser
5. See that MangaDex the website is listing chapters up to 75
6. Add "Sakamoto Days" to app library by clicking the "heart" icon
7. Navigate to library
8. See that "Sakamoto Days" is successfully added to the user library
9. Open manga summary page from library
10. See that app still displays toast notification saying "No chapters found"

In app
![Screenshot_20220623-111142_Tachiyomi](https://user-images.githubusercontent.com/34779821/175338090-f67bb120-4deb-413e-8149-7ddf3a53b89e.jpg)

In WebView
![Screenshot_20220623-113554_Tachiyomi](https://user-images.githubusercontent.com/34779821/175338420-b11c0b21-5455-46b0-83fe-1d258c731da3.jpg)

### Expected behavior

I should see the chapters for Sakamoto Days in the app itself like other manga.

### Actual behavior

I get a toast notification saying that there are "No chapters found" for the manga, but the chapters are present on the MangaDex website in a desktop web browser and in WebView.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Galaxy Tab A7 Lite (SM-T220)

### Other details

The issue report instructions don't make it clear if I should be reporting this as an extension issue or if I should be reporting this as an app issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
(1) You're in the wrong repo. (2) These are external chapters, that means Dex doesn't host them and therefore it's expected to them not to show up in the extension chapter list. If you click you will see you get redirected to another website that's not Dex.

**Comment by gr8stalin** [comment]
Thank you for the response. Could it be made more clear on the repo where the division is between the app itself vs the extensions within the app when reporting issues?
