### ISSUE TITLE
local manga

### ISSUE THREAD

**Issue by ssydx** [tachiyomiorg/tachiyomi#7363]
### Steps to reproduce

1.I've downloaded some manga with cbz format.
2.I've imported them to the directory as the guides saying.

### Expected behavior

This should show manga's cover(or after manual assignment)
This should sort by chapter name after I set it sorting by chapter name.

### Actual behavior

Some manga covers cannot be displayed.
The sorting is wrong, maybe it is sorted by creation time.

### Crash logs

no

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

oppo r15

### Other details

nothing more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> This should show manga's cover(or after manual assignment)

This should already be fixed for the next release.

> This should sort by chapter name after I set it sorting by chapter name.

It sorts by detected chapter number then by name. You'll have to rename your files to handle that.

**Comment by ssydx** [comment]
> This should already be fixed for the next release.
> Thanks for your attribution,I found that if I put the folder that already contains the cbz file into the local directory, it will not be a problem; If I first create an empty folder in the local directory and then put in the cbz file, it will be a problem.
> It sorts by detected chapter number then by name. You'll have to rename your files to handle that.
>I've done it

**Comment by ssydx** [comment]
This should already be fixed for the next release.
> Thanks for your attribution,I found that if I put the folder that already contains the cbz file into the local directory, it will not be a problem; If I first create an empty folder in the local directory and then put in the cbz file, it will be a problem.
It sorts by detected chapter number then by name. You'll have to rename your files to handle that.
> I've done it.
