### ISSUE TITLE
Incorrect Chapter Order

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#7364]
### Steps to reproduce

- Open "Ahiru no Sora" from PMScans source.

### Expected behavior

A correct order, part 1 then 2.

### Actual behavior

Part 2 comes before Part 1.

### Tachiyomi version

Preview r4489

### Android version

Android 12

### Device

Samsung Galaxy S10

### Other details

This is the only manga I have from this source, and I added the manga to library before these 2 parts got added, so they were the only updated I got, the rest was already there.
Switching to display chapter number, they are all the same, both 243, but other "part x" chapters dont have this issue.
And as you can see, source from webview is correctly ordered.
![Screenshot_20220625-093316_Tachiyomi](https://user-images.githubusercontent.com/22413659/175766161-d7e28400-74d4-4eab-b828-938872810941.jpg)
-
![Screenshot_20220625-093314_Tachiyomi](https://user-images.githubusercontent.com/22413659/175766163-4d6acf83-ae19-441e-ad46-1e43c64ac824.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Appears like this in all 3 sort

![image](https://user-images.githubusercontent.com/59261191/175883716-ed295dc7-bd11-40f4-9b3e-0ce864573d19.png)
