### ISSUE TITLE
Face unlock in dark mode

### ISSUE THREAD

**Issue by Speedy04** [tachiyomiorg/tachiyomi#7367]
### Describe your suggested feature

Face unlock doesn't work in dark lighting conditions.

Solution:

Add a bright white screen when face unlock screen is shown in dark lighting conditions.

Add option to disable face unlock.

Allow bypassing face unlock with fingerprint unlock.

### Other details

My phone is using Android 12. I use phone and all apps in dark mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If your device ROM doesn't already handle that sort of scenario normally, it's not on the app's onus to do so.

**Comment by Speedy04** [comment]
Thank you for the fast response,

My device shows a white screen when I use face unlock in dark lighting conditions to unlock screen but I dont get a white screen for app lock in tachiyomi. If its possible to disable only face unlock and use fingerprint unlock that would be great.

**Comment by Speedy04** [comment]
I didn't understand why you were rude with your reply. But after reading my post again I now do. This is my first time ever doing a feature request and I thought I needed to be concise with my post like bug reports and only added few suggestions which I labelled "Solution". Which was very rude of me. I apologise for upsetting you due to my ignorance. Please keep up the good work.

**Comment by AntsyLich** [comment]
Let me be more clear the app asks android to do a security check. How android handles that security check is not upto us. arkon wasn't mad or anything
