### ISSUE TITLE
Possible to miss manga page buttons when tapping at the edge of screen

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7372]
### Steps to reproduce

Go to manga page
Tap these buttons (near edge of screen)
- Back button
- Overflow menu button
- Action bar back button
- Action bar select inverse button

### Expected behavior

Buttons hitbox extended to edge of screen
![image](https://user-images.githubusercontent.com/63973749/175797083-f60f901d-4384-465d-ae4f-6e39e68db7f0.png)

### Actual behavior

You can miss the buttons when tapping the edge of the screen
![image](https://user-images.githubusercontent.com/63973749/175797089-4dcf1d9b-2fbf-4aee-886d-68f0bc460896.png)

### Tachiyomi version

r4511

### Android version

12L

### Device

Redmi Note 9 Pro (PixelExperience+)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is standard for the official Compose Material components, so it'll depend on them changing it upstream if anything.
