### ISSUE TITLE
Extension doesn't show up in Sources tab if only `Other` is enabled

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#7373]
### Steps to reproduce

1. Install Cubari extension.
2. Turn off `All` and `English` language in the extension settings.
3. Go back to Sources tab.

### Expected behavior

Extension should show under the `Other` category in Sources tab.

### Actual behavior

Extension is not on Sources tab.

### Tachiyomi version

r4511

### Android version

Not related

### Device

Not related

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
Other is considered an source language on its own. 

There are 9 sources in total that have the other lang. You can find them here.
https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.json

**Comment by arkon** [comment]
It's a bit confusing, but you do not explicitly enable `Other` in the browse filter list. Local (which is under `Other`) shows up regardless of that setting.

**Comment by zbue** [comment]
> It's a bit confusing, but you do not explicitly enable `Other` in the browse filter list. Local (which is under `Other`) shows up regardless of that setting.

Oof, got it now. Thanks!
