### ISSUE TITLE
Manga page no extra bottom spacing when FAB is hidden

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7376]
### Steps to reproduce

Hide FAB by reading all chapters

### Expected behavior

Extra bottom spacing to account for FAB, action bar

### Actual behavior

No extra spacing

### Tachiyomi version

r4511

### Android version

12L

### Device

Redmi Note 9 Pro (PixelExperience+)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The spacing is unnecessary.

**Comment by vengiare** [comment]
There's some jerky/jumpy behavior with selecting when the extra spacing isn't there. 

https://user-images.githubusercontent.com/63973749/192139991-c0da1f5f-07b6-4486-a2f9-87b5e2185855.mp4
