### ISSUE TITLE
Swiping back from the chapter list closes the app

### ISSUE THREAD

**Issue by stevenx37** [tachiyomiorg/tachiyomi#7390]
### Steps to reproduce

1. Launch Tachiyomi
2. Tap on a manga
3. Swipe back

### Expected behavior

"3. Swipe back" should go back to the library page 

### Actual behavior

Tachiyomi closes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8987817/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.4-4524

### Android version

Android 13 beta 3.2

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by hyoretsu** [comment]
Happens whenever the new loading screen appears (way more often than before)
