### ISSUE TITLE
r4524 bug with chapter transition, next chapter goes directly to last page...

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#7391]
### Steps to reproduce

Install r4524
Start reading a title that have more than 1 chapter to read (downloaded chapters as I didn't test for online chapters).
Read the first chapter
Once the transition pass, next chapter goes directly to last page instead of remaining on first one (it seems to have the bug more often while doing the transition slowly)

### Expected behavior

Normal transition 

### Actual behavior

Next chapter goes directly to last page

### Tachiyomi version

r4524

### Android version

Android 12

### Device

Mi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Gokujo** [comment]
I have the same issue but sometimes

**Comment by Ericcrash** [comment]
Same issue here. Using a Samsung S21 Plus, same app version as above. Usually seems to jump to the middle or end of the chapter in webtoon view for me.

**Comment by VirusEcks** [comment]
same thing keeps happening with webtoon view mode
* tested with online and downloaded chapters

even more when you use the scrubber at the bottom to go back you'll find that the pages are scrumbled and even repeating no mater how much you scrub so you have to go to chapter selection and load again
* only tested with downloaded chapters

**Comment by Soitora** [comment]
Same here, here are some demo videos of different stuff happening

Am reading in Webtoon mode, downloaded  chapters

Spoilers for **Legend of the Northern Blade** I suppose

https://user-images.githubusercontent.com/10836780/176767047-c7e3f4e0-1c32-4a0a-bae5-3869fcabf3c6.mp4


https://user-images.githubusercontent.com/10836780/176767061-e786b64d-d3c9-4128-b144-a89b7dfb4934.mp4


https://user-images.githubusercontent.com/10836780/176767066-6499a9af-dd30-4435-858c-a6a0983de70e.mov

**Comment by Yossefosman** [comment]
Same problem 
**Tachiyomi version**
r4524

**Android version**
Android 11

**Device**
Redmi 7 (onclite)

Downgrading to r4489 fixes the problem

**note**: it sometimes skips a chapter not just skipping pages

**Comment by yohanim** [comment]
@arkon the revert is still not enough to completely solve the issue. My first try made me go directly to page 7 while passing the transition.

**Comment by Ericcrash** [comment]
@yohanim A combination of reverting to 4489 and turning on Auto Split Tall Images in the download settings fixed it completely for me(you'll need to re-download any chapters that you currently have downloaded to notice the change)

**Comment by yohanim** [comment]
@Ericcrash I know that reverting to r4489 solves it.
But I was giving information to Arlon that the revert tried did not solve it.

**Comment by haganbmj** [comment]
Experiencing this as well on r4553.

I think for me the following creates it consistently.
- Read a chapter with X pages.
- Advance to next chapter with X+n pages; after X pages Tachiyomi will jump as if finishing a chapter?

Tried with Webtoon, Left->Right, and Right->Left pagination. 
My case was with pre-downloaded chapters, haven't given it too much additional digging.

**Comment by AntsyLich** [comment]
Not facing the issue anymore on r4622 (seems to be fixed from https://github.com/tachiyomiorg/tachiyomi/commit/46734c525ff6f893096ed16c23e0266b61e61b57) can you check and verify

**Comment by yohanim** [comment]
Hi, I confirm not having the issue anymore.thanks
