### ISSUE TITLE
Function mark below as read Marks every chapter as read except the selected one

### ISSUE THREAD

**Issue by Gokujo** [tachiyomiorg/tachiyomi#7395]
### Steps to reproduce

1. Install r4524
2. Go to manhwa/manga
3. Select New chapter
4. Type on mark below as read (I don't know the original Name) 

### Expected behavior

Chapters below selected should be marked as read

### Actual behavior

All chapters except the selected one are marked as read

### Crash logs

App version: 0.13.4-4524 (standard, 04f0ca784, 81, 2022-06-26T20:39Z)
Android version: 13 (SDK 33)
Android build ID: TPB3.220610.004
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

### Tachiyomi version

0.13.4-4524 

### Android version

Android 13

### Device

Google Pixel 6 Pro 

### Other details

App version: 0.13.4-4524 (standard, 04f0ca784, 81, 2022-06-26T20:39Z)
Android version: 13 (SDK 33)
Android build ID: TPB3.220610.004
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Gokujo** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19776684/175909604-c92b3da2-a792-4c16-a104-4ab244ce9106.gif)
Video of this behavior

**Comment by AntsyLich** [comment]
It's literally named "Mark below as read" what do you expect?

**Comment by Gokujo** [comment]
https://i.ibb.co/rF52049/ezgif-com-gif-maker-1.gif
Video
