### ISSUE TITLE
Webview add fullscreen reading mode

### ISSUE THREAD

**Issue by Character95** [tachiyomiorg/tachiyomi#7406]
### Describe your suggested feature

When you open chapters in web-view from tachiyomi app, it would be nice to read it in fullscreen (fullscreen on scroll) add (mode,option in settings)

*:In web-view hide notification,title and navigation bar on scroll down show on scroll up?

add option (read it in fullscreen(*))like a:

mode: webview in 3 dot menu

settings: settings/reader/(add webview options)

![Screenshot_2022-06-28-13-15-40-153_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/25694091/176191173-28869272-ffa1-483c-b6c8-4f912983219f.jpg)
![Screenshot_2022-06-28-13-15-48-936_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/25694091/176191198-e4e42826-1cd8-4652-bf0c-5cf02898d99b.jpg)
![Screenshot_2022-06-28-13-16-03-145_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/25694091/176191238-928aac80-8198-4c50-8c60-1d1074b5d4b0.jpg)
![Screenshot_2022-06-28-13-15-40-153_eu kanade tachiyomi debug_1](https://user-images.githubusercontent.com/25694091/176191571-220984d6-2839-48b6-86db-966d2a19a814.jpg)

### Other details

Thanks...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
WebView is a barebones tool for helping with resolving cookie based issues. Use your browser for a better browsing experience outside of the app.
