### ISSUE TITLE
copy manga

### ISSUE THREAD

**Issue by duanzhenshu** [tachiyomiorg/tachiyomi#7409]
### Steps to reproduce

无论我怎么点都打不开

### Expected behavior

正常情况应该是可以打开的

### Actual behavior

可是我打开时没反应还显示Unexpected JSON token at offset 0:
Expected start of the object 't', but had
'instead
JSON input:
<IDOCTYPE html>
<html lang="e.....

### Crash logs

![Uploading Screenshot_2022-06-29-15-20-15-437_eu.kanade.tachiyomi.jpg…]()

### Tachiyomi version

0.13.4

### Android version

Android12

### Device

MI CC 9e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Read what you acknowledged
