### ISSUE TITLE
Protest on removing obsolete extensions

### ISSUE THREAD

**Issue by Schezuk** [tachiyomiorg/tachiyomi#7416]
When you guys pruned and removed all these obsolete extensions from repo, you were trying to ruin the users' experience with third party apps or on old androids platforms (who could dig from repo history, find extensions compatible, and do with it) and forcing them to move on, which is very presumptuous and overbearing.

I PROTEST on behalf of the Infringed.

Dup https://github.com/tachiyomiorg/website/issues/924 https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12372

You can close issues, but you cannot mute all the user base.

I derecognize the standard acknowledgement below.

**Comment by loocool2** [comment]
Go ahead, this is a open source project. There is nothing preventing users from supporting thing that we as a organization have dropped support for, but we are not going to support it in the future. Have a nice day.

**Comment by Schezuk** [comment]
Do you have to prune? Rational developers do not remove old libs and force dependants to move on.

**Comment by Soitora** [comment]
> you were trying to ruin the users' experience with third party apps or on old androids platforms

This could not be further from the truth. Your crusade is based on falsities, but I don't blame why you'd think that way.
