### ISSUE TITLE
Need some spacing between download option and scrollbar in Updates tab

### ISSUE THREAD

**Issue by Chandanjk** [tachiyomiorg/tachiyomi#7417]
### Steps to reproduce

1. Get some data in the updates tab
2. Click on download button for any of the update

### Expected behavior

When clicking on download button for any new update it should not interfere with the scrollbar

### Actual behavior

While clicking on download button for any update it is interfering with the scrollbar which is landing us to the lower section of page. We need to scroll up and click a little bit on the left side of the download button to get it correctly clicked. Please fix this issue as it is getting really annoying 

### Tachiyomi version

0.13.4

### Android version

11

### Device

Oneplus 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The scrollbar goes away when you're not scrolling. Overlap is preferred over permanent padding on smaller screens to make better use of available screen real estate. Tablet UI will likely get more padding in the future.
