### ISSUE TITLE
Option to backtrack/manually auto split tall images

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#7420]
### Describe your suggested feature

I got this problem where (I think) "auto split tall images" only works like, 1 time out of 10, for some reason. (supposedly not much RAM available) But I'd bet that triggering a split tall images (on all downloaded chapters) by itself would work, in a more calm scenario. (or when something goes wrong)

Aside from my case, it'd also be useful to split already downloaded tall images without having to hunt your webtoons that have downloaded chapters that aren't splitted.

### Other details

Since I imagine that'd be pretty heavy on the scanning part, especially for people like me who have hundreds of downloaded _mangas_, we could have a sorta database to store webtoon info, locally and/or on a server. (Though I don't think Tachiyomi has one)

The first run would download/check that database, scan unknown mangas the user has to check for webtoons, and upload/store them. On subsequent ones, the feature would only check for entries stored in the database. When the user downloads a new manga with tall images, it'd automatically get added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
A better approach is to try and optimize current implementation of images splitting to reduce this from happening. I don't think implementing a mass images splitting function will really help with anything but create even more issues and complexity.

**Comment by hyoretsu** [comment]
That'd be even better and also solve my main problem, but I'm also not sure if it'd be easier to do.As for the mass splitting in itself, I'm an example of such a case where it'd sorta help.

4537 downloaded chapters, a lot of them from even before this option was introduced and suffered from reader lag. I'd have no way of splitting those chapters aside from finding each webtoon for myself and re-downloading all chapters, since some lag while others don't, or re-download 37GB of manga.

**Comment by curche** [comment]
A manually auto split tall image Routine would be more complex, require extra work for not much gain, and I can see most people being too lazy to do it for all their downloads

Luckily, another tachiyomi user has already created their own solution. From one of the previous [discussions](https://github.com/tachiyomiorg/tachiyomi/issues/1908#issuecomment-924184106) about Long Webtoons: [TachiyomiImageSplitter](https://github.com/Lightjohn/TachiyomiImageSplitter)

Closing this in favor of improving the current auto splitter.
Do suggest improvements/bugs/crashlogs/logcat dumps on the current auto split logic on lower RAM devices (or older devices in general)

Lastly,
> 4537 downloaded chapters

this is not a small amount and I think you should consider reading through them or archiving them on a Komga (or your choice of a self-hosted manga/comics software) media server. But that's just me entirely shook by such a huge number

**Comment by hyoretsu** [comment]
> Luckily, another tachiyomi user has already created their own solution. From one of the previous [discussions](https://github.com/tachiyomiorg/tachiyomi/issues/1908#issuecomment-924184106) about Long Webtoons: [TachiyomiImageSplitter](https://github.com/Lightjohn/TachiyomiImageSplitter)

That's pretty much the feature I suggested, only difference is that it seems to scan all folders each time. And it's also splitting other images that aren't even long. (960x1400 or higher, weighing only 5MB)

> this is not a small amount and I think you should consider reading through them or archiving them on a Komga (or your choice of a self-hosted manga/comics software) media server. But that's just me entirely shook by such a huge number

It's partially because I made a habit of bookmarking chapters as Favorites and keeping them downloaded. Martial Peak alone has 155 out of 2367 chapters bookmarked. 700 others are me making a certain library and slowly reading through them.

**Comment by hyoretsu** [comment]
My phone's able to handle Tachiyomi downloading chapters and a separate app splitting chapters over 4 threads, but instantly throws a problem when Tachiyomi's trying to split it. I haven't closed https://github.com/tachiyomiorg/tachiyomi/issues/7229 because I highly doubt that this is a RAM problem.
Shame that TachiyomiImageSplitter's written in Java, not Kotlin.
