### ISSUE TITLE
Download badge not updating in library

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#7421]
### Steps to reproduce

When deleting:
1. Enable downloaded chapter badge
2.  In library, select any mangas with downloaded chapters.
3. Delete downloaded chapters

When downloading:
1. Enable downloaded chapter badge
2. In library, open any manga then download some chapters.
2. Go back to library and wait for download to finish.

### Expected behavior

Download badge should update

### Actual behavior

Download badge not updating

### Tachiyomi version

r4524

### Android version

Not related

### Device

Not related

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed in newer version.
