### ISSUE TITLE
Update xoxo Comics comic completed status

### ISSUE THREAD

**Issue by sumacool** [tachiyomiorg/tachiyomi#7430]
### Describe your suggested feature

This one really simple request because you guys just need to update the complete status comic to appear in xoxo comics extension it's quite annoying to update my manga if all the comic status  in tachiyomi is "unknown status" while in the actual website the status is complete
![Screenshot_20220701-181836](https://user-images.githubusercontent.com/66295833/176884798-2934dcb7-2a81-4ee9-86ab-bfe207335611.png)
![Screenshot_20220701-181828](https://user-images.githubusercontent.com/66295833/176884810-b454def7-63fe-4d63-ac2b-9146f9694ff0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
