### ISSUE TITLE
Don't force Add category to start with lowercase letters

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7431]
### Describe your suggested feature

It should follow keyboard preferences. (If auto-capitalization is enabled, it should be respected)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There doesn't seem to be anything at a system level to really allow apps to respect Gboard's preference, so I don't know how Gboard is supposed to force it.
