### ISSUE TITLE
Manga info page slow to load

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#7433]
### Steps to reproduce

Close Tachiyomi in recent app -> re-open app -> select manga in library 

### Expected behavior

Close Tachiyomi in recent app -> re-open app -> select manga in library -> immediately show manga info page

### Actual behavior

Close Tachiyomi in recent app -> re-open app -> select manga in library -> manga info page take a time to load

### Crash logs

--------- beginning of main
07-02 00:40:31.652  7692  7692 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
07-02 00:40:33.666  7692  7849 E SQLiteLog: (284) automatic index on C(manga_id)
07-02 00:40:33.666  7692  7849 E SQLiteLog: (284) automatic index on R(manga_id)
07-02 00:40:33.666  7692  7849 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.4-4524 (standard, 04f0ca784, 81, 2022-06-26T20:39Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191008.001.WW_user_100.10.107.123_20210131 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_Z01R_1
Device model: ASUS_Z01RD
Device product name: WW_Z01RD

### Tachiyomi version

Preview r4524

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

This happen every time tachiyomi get close in recent app, when re-open tachiyomi again , and select manga from library for first time, manga info page take a time to load, after that for second and rest immediately show, while in load occur and press back button, tachiyomi get closed itself. Tested in stable and stable dont have this issue.

Waiting

https://user-images.githubusercontent.com/101858971/176937232-82f3fbc9-0f11-4819-9553-fba29f4739bc.mp4

Press back button

https://user-images.githubusercontent.com/101858971/176937493-c0829e0b-c329-47ea-b11f-274c3fdbc665.mp4

Stable 

https://user-images.githubusercontent.com/101858971/176937703-c135e150-0e1c-4aeb-a091-c3d683b4b2c8.mp4

Update , in Preview r4622, it's happen when tachiyomi active and apparently effect maybe all manga. Sometimes load can get stuck, press back button when this happen make tachiyomi close.

https://user-images.githubusercontent.com/101858971/178096730-357131bc-1b71-4609-9b01-274832d3461d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This was improved in #7708

**Comment by DchanN** [comment]
> This was improved in #7708

@arkon Only the first manga instant to load, after that click the other/next manga still take a time to load, unlikely stable version which instant show manga info page for every manga, this last preview r4845

https://user-images.githubusercontent.com/101858971/187585449-c42e7cd5-4b73-4f9a-b56f-c1d371f5a497.mp4
