### ISSUE TITLE
No pop up after downloading the updates r4524

### ISSUE THREAD

**Issue by SebastienPret** [tachiyomiorg/tachiyomi#7439]
### Steps to reproduce

In the app pressing on the download button to have the latest version. (Same when notification pop up).
The download begin and goes all the way.

### Expected behavior

A notification pop up should appear to install the update. 

### Actual behavior

No pop up come up... Noting happen. Eaven after multiple attempts. 

### Tachiyomi version

r4524

### Android version

Android 12

### Device

Samsung A52s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There was a bug that killed the notification, you'll need to download/update using the APK directly off of GitHub: http://github.com/tachiyomiorg/tachiyomi-preview/releases/latest
