### ISSUE TITLE
logo on splash screen doesn't appear

### ISSUE THREAD

**Issue by VirusEcks** [tachiyomiorg/tachiyomi#7449]
### Steps to reproduce

splash screen on mobile with (mobile dark mode) on

### Expected behavior

the center of screen has the logo

### Actual behavior

the circle in middle of the screen shows the logo briefly before disappearing

### Tachiyomi version

all recent preview versions currently 4553

### Android version

android 11 miui 12

### Device

Xiaomi 9T / k20

### Other details

this happens regardless of the color mode of tachiyomi and the splash appears in dark mode regardless of tachiyomi settings

https://user-images.githubusercontent.com/3261210/177048921-56240de3-a2c0-45b8-be91-8337f19ccff4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is an issue between MIUI and AndroidX libraries.
