### ISSUE TITLE
Improperly scaled pages in 2 reading modes.

### ISSUE THREAD

**Issue by HandyManny0** [tachiyomiorg/tachiyomi#7455]
### Steps to reproduce

Open any comic, preferably one that is "webtoons" style which relies on scrolling down to read properly, with either the "Webtoon" and "Continuous vertical" reading modes, and scroll.
It's most noticeable on "webtoons" style comics, especially in comparison to other comics, where some images only suffer very little from images not being properly scaled, since they don't rely on it.

### Expected behavior

Both "Webtoon" and "Continuous vertical" reading modes should have properly scaled and aligned images.

### Actual behavior

Both "Webtoon" and "Continuous vertical" reading modes do not properly scale or align images. Some images/pages look very zoomed in, while others do not, sometimes they look misaligned due to this even though they might appear the same size. This is not the case with the remaining three reading modes.

![photo_2022-07-04_08-37-32](https://user-images.githubusercontent.com/95508278/177185817-7e68d91b-f2e5-4af7-a9f2-f3682cc539f7.jpg)
![photo_2022-07-04_08-37-30](https://user-images.githubusercontent.com/95508278/177185826-de07a19c-4b51-4a00-bd13-28eda979215e.jpg)
![photo_2022-07-04_08-37-28](https://user-images.githubusercontent.com/95508278/177185829-1859fdf7-63ea-45b0-a18e-5b63faa554e1.jpg)
![photo_2022-07-04_08-37-24](https://user-images.githubusercontent.com/95508278/177185831-486e9ef4-3eaf-4358-8bbd-6415e798919d.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Moto G Power (2021) XT2117-1

### Other details

Attempting to download a chapter does not change the issue. The same goes for deleting downloaded chapters, and re-downloading them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Turn off crop borders.

**Comment by HandyManny0** [comment]
> Turn off crop borders.

That was never even on... Everything is using the default settings, except the default reading mode, which I keep set on "Webtoon"
