### ISSUE TITLE
Update(s) failed

### ISSUE THREAD

**Issue by Stubbs9410** [tachiyomiorg/tachiyomi#7458]
### Steps to reproduce

Hello,
Don't know if the is the right place.
Tachiyomi not updating mangas from
! No chapters found
  # Mangakakalot (EN)
 HTTP error 404
  # Mangairo (EN)
Had this problem in the past but had extension update quickly. 

### Expected behavior

Refresh manga list and wait for it to work. 

### Actual behavior

Refresh and 54 mangas not updating Update failed

### Tachiyomi version

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)

### Android version

Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXUFHVE1 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2lteeea

### Device

Samsung S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Please read carefully
