### ISSUE TITLE
New manga site

### ISSUE THREAD

**Issue by Fares669** [tachiyomiorg/tachiyomi#7459]
### Describe your suggested feature

Add a new manga site ( Arabic manga site)
Manga site name: [Teamx](https://mnhaestate.com/) 
Manga site link:https://mnhaestate.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Wrong repo and no, they've been removed already because the scanlator requested
