### ISSUE TITLE
Add option to Disable "Skip Updates" Feature

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [tachiyomiorg/tachiyomi#7462]
### Describe your suggested feature

I like to let chapters stack a bit before I read them, but with this feature, I can't do this and I am sure that many other users have the option to choose either or not to have this feature on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment]
or maybe something like this exists already 

![Screenshot_20220706-135312_Tachiyomi](https://user-images.githubusercontent.com/63973749/177478999-abf1e166-6267-42ee-894d-dd26fa37174c.png)

**Comment by ArthurFerreiraRodrigues** [comment]
It does indeed exists already 🤡. I am sorry.
