### ISSUE TITLE
Tracker "MyAnimeList" error 401

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7465]
### Steps to reproduce

Open any comic
Add tracker from MyAnimeList
Error 401

![Screenshot_2022-07-06-18-42-16-76_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/177542813-46abd49c-42fd-447f-a3ae-5809d093a171.jpg)
![Screenshot_2022-07-06-18-42-25-93_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/177542821-06d22039-edd0-43f1-81d8-17d1b426bbac.jpg)

https://user-images.githubusercontent.com/50316075/177542824-421b7dfe-2417-4878-bef3-d046536249cb.mp4

### Expected behavior

Cant add a tracker

### Actual behavior

Successfull add a tracker

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Logout and log back into MyAnimeList

**Comment by TheKingTermux** [comment]
> Logout and log back into MyAnimeList

Okay i Will try it
