### ISSUE TITLE
Tachiyomi crashes when attempting to restore a backup

### ISSUE THREAD

**Issue by tarantinosaur** [tachiyomiorg/tachiyomi#7467]
### Steps to reproduce

Attempt to perform a backup restore

### Expected behavior

Open a file dialog to locate the backup file

### Actual behavior

App just crashes/closes

### Crash logs

--------- beginning of system
--------- beginning of main
07-06 20:45:13.705 28689 28689 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-06 20:45:22.865 28689 28744 E SQLiteLog: (284) automatic index on C(manga_id)
07-06 20:45:22.865 28689 28744 E SQLiteLog: (284) automatic index on R(manga_id)
07-06 20:45:22.865 28689 28744 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-06 20:45:23.151 28689 28717 E LB      : fail to open file: Permission denied
App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: sweet_global

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Redmi Note 10 Pro

### Other details

I have done the following:

- set the storage permission to always allow
- uninstalled and reinstalled multiple times with and without extensions

I think this line is when the crash happens.

> 07-06 20:45:23.151 28689 28717 E LB      : fail to open file: Permission denied

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This sort of error seems specific to Xiaomi devices. You can try toggling on/off MIUI optimizations.
