### ISSUE TITLE
Redering error wehn reading something 

### ISSUE THREAD

**Issue by Katzenminer** [tachiyomiorg/tachiyomi#7468]
### Steps to reproduce

Not quite sure it will be able to be reproduced 

1.open a manga in the app 
2.if ut says that an image can't load exit out of the manga(not the app)
3.download that chapter of the manga 
4.go back in

### Expected behavior

Do just show the chapter that I just download 

### Actual behavior

It renders the image could not be loaded on top of  the image 
![image](https://user-images.githubusercontent.com/63449674/177558408-2c234f67-f7f5-48e4-994b-785d07df3fe1.png)

### Crash logs

--------- beginning of main
07-06 15:03:45.977  1658  1658 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-06 15:03:45.980  1658  1658 E USNET   : USNET: appName: eu.kanade.tachiyomi
07-06 15:03:46.471  1658  1703 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:03:46.542  1658  1702 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:03:46.553  1658  1709 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:03:46.566  1658  1711 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:03:46.568  1658  1712 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:06:12.083  1658  2081 E SchedPolicy: Failed to find cgroup for tid 1658
07-06 15:06:24.583  1658  2073 E FrameEvents: updateAcquireFence: Did not find frame.
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-06 15:06:24.739  1658  2428 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:920)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-06 15:06:24.739  1658  2427 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:920)
07-06 15:06:25.100  1658  2422 E SQLiteLog: (284) automatic index on C(manga_id)
07-06 15:06:25.100  1658  2422 E SQLiteLog: (284) automatic index on R(manga_id)
07-06 15:06:25.100  1658  2422 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-06 15:07:29.053  1658  4317 E SchedPolicy: Failed to find cgroup for tid 1658
App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A528BXXS1CVF1
Device brand: samsung
Device manufacturer: samsung
Device name: a52sxq
Device model: SM-A528B
Device product name: a52sxqeea

### Tachiyomi version

App version: 0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.A528BXXS1CVF1 Device brand: samsung Device manufacturer: samsung Device name: a52sxq Device model: SM-A528B Device product name: a52sxqeea

### Android version

Android 12

### Device

Sm-A528B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by yohanim** [comment]
Same as #7452

**Comment by yohanim** [comment]
I've just got it with r4622 in Webtoon mode
