### ISSUE TITLE
Downloader Enhancement 

### ISSUE THREAD

**Issue by MohammedHalaby** [tachiyomiorg/tachiyomi#7469]
### Describe your suggested feature

In App downloader is some how slow, may be catching links or whatever make it take time to download a complete series. 
If You make it capable to download multiple chapters at once, it will be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Tachiyomi is not meant to be used as a downloader. If you need to batch download a series use some other app

**Comment by Seishirou101** [comment]
This already exists for multiple sources, and will not be added for the same source as it causes extra constraints on sources.

#1567
