### ISSUE TITLE
Auto-download not working for default category

### ISSUE THREAD

**Issue by TheUnlocked** [tachiyomiorg/tachiyomi#7471]
### Steps to reproduce

I'm not sure if all of the setup is required, but I'm trying to be as reflective of my scenario as possible.
1. Create two new categories (A and B)
2. Add different manga to the default category, A, and B (in my case the categories are mutually exclusive).
3. In the settings, enable auto-download for Default and A
4. When a new chapter is available for a manga, refresh the manga to get the new chapters

### Expected behavior

The new chapters for manga in the default category and A should automatically download.

### Actual behavior

Only the chapters in A automatically download.

### Tachiyomi version

0.13.4-4553 (standard, 267457079, 81, 2022-07-02T21:09Z)

### Android version

9 (SDK 28)

### Device

Samsung Galaxy S8 (SM-G950U1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Have you gone to settings > downloads > auto download and have you selected the ["default"] category?. 
And go to library > update > update category and already choose ["default"]?

**Comment by TheUnlocked** [comment]
Yes, all of the settings are configured correctly to have chapters in the default category auto-download.
