### ISSUE TITLE
Title for "more" says "download queue" when using gestures 

### ISSUE THREAD

**Issue by Viren070** [tachiyomiorg/tachiyomi#7478]
### Steps to reproduce

1. go to the download queue through the "More" menu
2. while using gestures (swiping instead of using a on screen back button) to go back to the "More" menu, move a chapters position in the download queue 

### Expected behavior

when returning to the "More" menu the title for the More screen should say "More"

### Actual behavior

The title for the "More" screen (text at the top of the screen) says "Download queue" 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Samsung Galaxy A52s

### Other details

here is a screen recording 
https://user-images.githubusercontent.com/71220264/177877720-01efdcfd-e54b-43ea-a588-df068f4455a6.mp4

this only happens with gestures. When using on screen buttons it works as expected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed in next version already.
