### ISSUE TITLE
Scanlator Tracker

### ISSUE THREAD

**Issue by VirYouth** [tachiyomiorg/tachiyomi#7481]
### Describe your suggested feature

It should work like the feature when you tap the name of manga/author and artist and it will put you to the works of them... 

### Other details

Being able to search the scanlator group to in library or the extensions and being able to see their works would be good :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hyoretsu** [comment]
That would only work in very few sites, like MangaDex which disclose (or even allow 3rd party) uploaders. And even then, I dont think even MD has a "uploader search" feature.

Other than that, scanlators who have their own websites also have their own extensions with their other works.

**Comment by arkon** [comment]
Seems too niche.
