### ISSUE TITLE
Library slow to open when storage on sd card

### ISSUE THREAD

**Issue by Kuro0kami** [tachiyomiorg/tachiyomi#7482]
### Steps to reproduce

1. Use SD card in device
2. Change storage location of tachiyomi to use SD card
3. Download multiple manga from multiple sources

### Expected behavior

It seems that when using SD card as main storage area for this app, the more I titles and downloads I have, the longer it takes to open and display Library pages.

### Actual behavior

There are times after opening app that I have to wait 3-5 mins for the Library of media to even display even though they are downloaded and local.

### Tachiyomi version

0.13.5

### Android version

11

### Device

Samsung Galaxy Tab A7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Kuro0kami** [comment]
If the app is left on a Library page then it will show immediately, but the chapters for what manga you select will then be delayed.

**Comment by ChoBitsZ7** [comment]
I have this trouble too
but
It would be better if you could add some read waiting animations
Or progressively read comics that are read first are displayed first

**Comment by llangil** [comment]
I have a similar issue but its internal storage for me. On my Samsung Tab S7 (Android 12) it takes ~12 min for the local library to load (I have ~11 GB of files).
I downgraded to v0.13.4 and its loading completely fine for me now.

**Comment by arkon** [comment]
Download badge count is now deferred in latest preview version.
