### ISSUE TITLE
Manga Info Page slow to load for any manga in Library

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#7483]
### Steps to reproduce

Open Tachiyomi ->  Library -> Select any manga

### Expected behavior

Manga Info Page immediately show up

### Actual behavior

Manga Info Page slow to load , and sometimes stuck on loading

### Tachiyomi version

Preview r4622

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

In previous preview r4524 it's only for cold start and for first manga only (#7433 ) but after today update r4622, it's happen when tachiyomi active and apparently effect maybe all manga. Sometimes load can get stuck, press back button when this happen make tachiyomi close

https://user-images.githubusercontent.com/101858971/178096730-357131bc-1b71-4609-9b01-274832d3461d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Kuro0kami** [comment]
I have this issue as well. Do you store your library on an SD card or on your devices internal memory?

**Comment by DchanN** [comment]
> I have this issue as well. Do you store your library on an SD card or on your devices internal memory?

All app data in Internal Memory, only downloaded manga stored in ad SD card

**Comment by arkon** [comment]
Closing in favour of #7433
