### ISSUE TITLE
Tachiyomi wont show a list of any extensions, even when installed manualy.

### ISSUE THREAD

**Issue by gittyno1** [tachiyomiorg/tachiyomi#7486]
### Steps to reproduce

install tachiyomi from github, older version 0.10.12
go to extensions

### Expected behavior

there should be list of extensions to install and read manga

### Actual behavior

no list is showing up, and no manga to read or download

### Tachiyomi version

0.10.12

### Android version

Android 5.1.1

### Device

Samsung Galaxy Note 10.1 (SM-P605 LTE 2014 edition)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.

Read what you acknowledge

**Comment by gittyno1** [comment]
> > * [x]   I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> 
> Read what you acknowledge. And fyi newer extensions are not supported in older versions

I cant update the app to higher version on android 5, it wont install.

**Comment by DchanN** [comment]
> > > * [x]    I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> > 
> > 
> > Read what you acknowledge. And fyi newer extensions are not supported in older versions
> > mistake.
> > I cant update the app to higher version on android 5, it wont install.
> > only said version works.
> 
> Anyway, how to ind older versions that work on android 5?

if u in android 5, your only choice use Fork Tachiyomi-AZ : https://tachiyomi.org/forks/TachiyomiAZ/

**Comment by gittyno1** [comment]
> > > > * [x]     I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> > > 
> > > 
> > > Read what you acknowledge. And fyi newer extensions are not supported in older versions
> > > mistake.
> > > I cant update the app to higher version on android 5, it wont install.
> > > only said version works.
> > 
> > 
> > Anyway, how to ind older versions that work on android 5?
> 
> if u in android 5, your only choice use Fork Tachiyomi-AZ : https://tachiyomi.org/forks/TachiyomiAZ/

works like a charm, even new tachiyomi extensions work with it. thanks a lot :)
