### ISSUE TITLE
Webtoon XYZ not working 

### ISSUE THREAD

**Issue by B-side09** [tachiyomiorg/tachiyomi#7489]
### Steps to reproduce

After I downloaded the recent update for the app, the extension webtoonXYZ stopped working. even after I tried to open the web view. And it did work before I updated The app 

### Expected behavior

Normally it takes some time to open up when you click on it. So when it takes to long I usually open up in web view and then go back so I can lead trough and read what I want to read.

### Actual behavior

But now when I open up web view it keeps loading even after I refresh it. Of course i can use another source but then I won’t remember where I left off.

### Tachiyomi version

0.13.05

### Android version

Android version 12

### Device

Samsung galaxy 10 e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by hyoretsu** [comment]
"If this is an issue with an extension, I should be opening an issue in the extensions repository."

Also regardless, just a tip, if you simply add the mangas to your library you would be able to remember where you left off, because you wouldn't need internet to see them.

**Comment by B-side09** [comment]
True i forget to put is in my library some times

**Comment by hyoretsu** [comment]
In that case you can also find them in "History" tab, which also doesn't need internet.

**Comment by alessandrojean** [comment]
Closing as it is in the wrong repository.
