### ISSUE TITLE
Display number of chapters available when selecting source

### ISSUE THREAD

**Issue by mcslothyface** [tachiyomiorg/tachiyomi#7494]
### Describe your suggested feature

When searching for a new manga or migrating one to a different source the only way to see how many chapters are available is to select the source/complete the migration. It can be frustrating when you know there are 100+ chapters but some sources may only have 25 or so. Displaying the number on the icons would help choose the source with the most content as well as prevent migrating to a source that is missing chapters. 

### Other details

I believe the way you can choose to display unread chapters (little square with number) would be a great way to display the number of chapters available when searching. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This would increase the number of requests the app does and it was denied before. During migration, you can hold on the cover and it will open the manga details where you can see how many chapters there are.
