### ISSUE TITLE
repeated chapters

### ISSUE THREAD

**Issue by FernandoWsky** [tachiyomiorg/tachiyomi#7498]
### Steps to reproduce

When I open an extension in Spanish, the vast majority of times they have many chapters of it, and it does not allow me to advance from chapter comfortably.
The classic extensions where it happens are TMO, leermanga xyz, inmanga, lector de manga, etc ...
I suggest that chapters of the same repeated number be eliminated, I do it in such a way that I mark them read and use the filter in "unread" but in long sleeves it is very slow.

### Expected behavior

There would be no more chapter than the ones that the manga has

### Actual behavior

I find many chapters of the same 
![Screenshot_2022-07-09-22-33-35-086_eu kanade tachiyomi](https://user-images.githubusercontent.com/86829957/178130320-b460546e-d41b-4b98-a267-2204c2288d59.jpg)
![Screenshot_2022-07-09-22-33-31-483_eu kanade tachiyomi](https://user-images.githubusercontent.com/86829957/178130321-85b0dec8-1eb0-477c-99d0-e276b851073c.jpg)

### Tachiyomi version

Stable 0.13.5

### Android version

Android 11

### Device

Xiaomi Redmi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You should request in the extensions repository for the sources to distinguish the chapters with "scanlators" if they're providing multiple versions.
