### ISSUE TITLE
Local Source on SD Card got Malformed[1]

### ISSUE THREAD

**Issue by fhc5326** [tachiyomiorg/tachiyomi#7501]
### Steps to reproduce

Open local sources

### Expected behavior

Can see comic in my local sources in SD Cards.

### Actual behavior

It tells me Malformed[1].

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Samsung Note 20 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Old instance: #905

Probably a bad ZIP file?

**Comment by fhc5326** [comment]
> Old instance: #905
> 
> Probably a bad ZIP file?

No, I put folder in local folder

look like this:
local
-test1
--test.zip
-test2
--test2.rar
--test3.zip
--test4
---test5.jpg

**Comment by fhc5326** [comment]
by the way, is external SD card.

**Comment by arkon** [comment]
I didn't say that the location was bad, I said the file itself might be bad (which it obviously is, given that it says that it's malformed).

Did you try rearchiving it?

**Comment by fhc5326** [comment]
Hi arkon:

As you said, I checked my location and structure, find out that some of my rar and zip file cause this happened, after I move away, it goes away, I'll check and rearchiving it.

we can close this case, thank you.
