### ISSUE TITLE
Disable app update check

### ISSUE THREAD

**Issue by soredake** [tachiyomiorg/tachiyomi#7504]
### Describe your suggested feature

I don't really need app update check as i installed tachiyomi from fdroid.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
We don't support the F-Droid version.

**Comment by AntsyLich** [comment]
Official release are only available on GitHub. So contact whoever released it ok F-Droid

**Comment by arkon** [comment]
It was supposedly taken down from F-Droid, so I'm not really sure what's going on over there. If there's someone still maintaining it (which we, at least officially, aren't), they should probably try to PR a different build variant back to handle the F-Droid specific behaviour that was removed after its supposed removal.

Also as an FYI: https://tachiyomi.org/help/faq/#how-do-i-migrate-from-the-f-droid-version

**Comment by soredake** [comment]
It's still here, https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/eu.kanade.tachiyomi.yml

Do f-droid maintainers really need to patch this mandatory update check?

**Comment by arkon** [comment]
> It's still here

#4267 / https://gitlab.com/fdroid/admin/-/issues/195 state that it was supposedly disabled, so 🤷

> Do f-droid maintainers really need to patch this mandatory update check?

There's no motivation for us to support F-Droid specific behaviour, so yes. See https://github.com/tachiyomiorg/tachiyomi/issues/6736#issuecomment-1059608058

**Comment by soredake** [comment]
It's still in repos and available for download. I don't think this is "f-droid specific behavior", as any app installed from app store should not check for updates by default or at least have an option to disable this.
