### ISSUE TITLE
Tachiyomi almost locks instantly after switching to another application

### ISSUE THREAD

**Issue by Alexgamer470** [tachiyomiorg/tachiyomi#7513]
### Steps to reproduce

Everytime I want to switch the app (e.g. for using an translator) and then want to switch back to the app tachiyomi always locks itself instantly regardless of the time set in the security settings. I also tried to deactivate battery optimization with no success.

Thus this problem doesn't seem to appear all the time but most of the time after switching to another application.

### Expected behavior

- Switch the application without closing tachiyomi
- Switch back to tatchiyomi
- Tachiyomi should still be unlocked as long as you switch back to it in the time frame that is set in tthe security settings

Idk if this is a good idea but you could add that the app only locks instantly if you completely close the app. Otherwise the locking timer should always run in the background regardless if you have completely closed or just switched the app.

It's just annoying to always unlock tachiyomi after searching a word up in a translator, especially if you're not speaking English so well or if there aren't many manga sources out there that support your language 

### Actual behavior

- switching the app
- do something in another app within the time frame set in the security settings
- tachiyomi is locked

### Tachiyomi version

0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)

### Android version

Android 12 (SDK 31)

### Device

Samsung Galaxy S20 FE 5G

### Other details

Android build ID: SP1A.210812.016.G781BXXS4FVF3 Device brand: samsung Device manufacturer: samsung Device name: r8q Device model: SM-G781B Device product name: r8qxeea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by andraantariksa** [comment]
It works just fine on my device. My guess is your phone is trying to free up the resource by killing the apps. You could try to reproduce the issue by plugging your phone into the USB cable and see if it appears.

From what I have read, to guarantee the app lifetime, the app should display a notification just like music app in the background.

- https://stackoverflow.com/q/63881371/3894179
- https://developer.android.com/guide/components/foreground-services

**Comment by AntsyLich** [comment]
@andraantariksa the issue is how the app handles the locking. 

The issue is properly presented by #7122
