### ISSUE TITLE
Tachiyomi Preview | Using Download->All only downloads visible chapters

### ISSUE THREAD

**Issue by juniorjacob** [tachiyomiorg/tachiyomi#7521]
### Steps to reproduce

1. Visit any manga in library / source (preferably with a small amount of downloaded chapters with a large catalog of unread chapters)
2. Use the Download option at the top right
3. Select All from the dropdown
4. Scroll further down (or up, depending on where more undownloaded chapters are)
5. Issue presents itself
6. (Optional) Verify chapters are not being downloaded via More->Download queue

### Expected behavior

Using the All option from the Download dropdown should download all chapters that are not yet downloaded.

### Actual behavior

Using the All option from the Download dropdown downloads only the visible chapters that are not yet downloaded.

### Tachiyomi version

v4631

### Android version

Android 12

### Device

Galaxy Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by juniorjacob** [comment]
https://github.com/jobobby04/TachiyomiSY/issues/630#issuecomment-1180581627

**Comment by AntsyLich** [comment]
This seems like an ui issue cause when i checked download queue all chapters were being downloaded.

**Comment by juniorjacob** [comment]
Then this a SY specific issue and he just offloaded it here without
checking...
