### ISSUE TITLE
Manga chapters not appearing in Tachiyomi app

### ISSUE THREAD

**Issue by IsaBNekomata** [tachiyomiorg/tachiyomi#7523]
### Steps to reproduce

1. Add a manga to library (This has happen in several extensions like MangaOwl and Mangadex)
2. A message saying "No chapters found" in select manga
3. Even if the manga does has chapters

### Expected behavior

Chapters appearing and being able to be downloaded

### Actual behavior

Chapters not appearing in the app even after updating the library, they're just not able to be downloaded or read even if I already had the chapters downloaded (This happened with Spy x Family)

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

LG V40 Thinq

### Other details

This has happen both with select chapters in manga or full mangas, for example in Spy x Family the whole manga is marked as being not found even if I can add it to my library and in Chainsaw Man some chapters are not found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
1. Your app is out of date
2. MangaOwl is dead migrate away
3. Make sure MangaDex has the chapters in your language available on the site and that they're not just off-site links

**Comment by IsaBNekomata** [comment]
I would upgtrade to 0.13.5 but there's a problem with microsd stored local manga also 0.13.4 isn't the first version that this has happened
