### ISSUE TITLE
Browse: Added/Removed [Library]

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi#7527]
### Steps to reproduce

The added and removed scenes from the library are displayed correctly

### Expected behavior

It happens normally the scenes

### Actual behavior

When adding titles to the library the corresponding scene is not displayed, nor is it removed

### Tachiyomi version

0.13.5-r4631

### Android version

Android 7

### Device

Samsung

### Other details

**Latest Version**

https://user-images.githubusercontent.com/70596255/178742066-83ad2edd-9e42-4af2-a585-bcc3b35b9c9a.mp4

**Very Previous Version**

https://user-images.githubusercontent.com/70596255/178742351-6e16631a-ba8c-477d-a47f-7bd526fe32b9.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Updated #7418 to also mention this.
