### ISSUE TITLE
Una sección de comentarios 

### ISSUE THREAD

**Issue by AlejandroTodoroki26** [tachiyomiorg/tachiyomi#7529]
### Describe your suggested feature

Estaría bien que pusieran una sección de comentarios para compartir tus opiniones con las demás personas y así convivir con esas personas 

### Other details

Al poner está sección de comentarios obviamente dividirla en los diferentes idiomas o poner un traductor 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#4336
