### ISSUE TITLE
Allow me to disable "Large updates" warning notifications

### ISSUE THREAD

**Issue by ChineseOuchie** [tachiyomiorg/tachiyomi#7531]
### Describe your suggested feature

I can disable many notification, but the "Large updates harm sources and may lead to slower updates and also increased batter usage" warning is missing from that list

Here is a screenshot of that notification:
![Screenshot_20220713-215832_Tachiyomi](https://user-images.githubusercontent.com/10912994/179041133-361681ea-cefe-43c2-ab9e-c22bc6d1780a.jpg)
.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It _should_ be automatically dismissed after 30 seconds on newer versions of Android already.
