### ISSUE TITLE
Cloudflare issue. it was working, but suddenly it doesn't 

### ISSUE THREAD

**Issue by ThePredAli** [tachiyomiorg/tachiyomi#7536]
### Steps to reproduce

I cant read in the app.
Before approximately 3-4 weeks, i downloaded the j2k app
And mangalek/ mangastarz was working just fine while it was stopped in the normal app. 

### Expected behavior

I should read it normally, as in the browser

### Actual behavior

Kicking me out of the chapter i want to read

### Tachiyomi version

0.13.5 or j2k version 1.5.6

### Android version

Android 12

### Device

Samsung note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
>- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Read what you acknowledge

**Comment by CarterSnich** [comment]
Same here, fails to fetch updates. Tried Google, same thing. I turned of DNS for the moment.
