### ISSUE TITLE
Resume option overlaps with pop-up menu when selecting any chapters 

### ISSUE THREAD

**Issue by nachos999** [tachiyomiorg/tachiyomi#7541]
### Steps to reproduce

1. Open Tachiyomi and start updating the library by scrolling down.
2. Go to a title that you have started but yet to finish. Means there are still some unread chapters and you will be seeing the RESUME option at the bottom right corner.
![normal 1](https://user-images.githubusercontent.com/109403928/179341353-5dda9ec3-5cc7-48f5-8235-2134d387b015.jpg)

3. Select any chapters from the title and you will see that the resume option is gone as it's supposed to be . 
![normal 2](https://user-images.githubusercontent.com/109403928/179341368-8dd5a7f0-1be7-40d9-9ad1-8456fc27b147.jpg)

4. After selecting the chapters start scrolling up and down and eventually you will see that the RESUME option suddenly appears and overlays the pop-up menu . 
![resume selected 2](https://user-images.githubusercontent.com/109403928/179341394-149de002-20a3-4fbd-8ae1-9db30bddcb06.jpg)
![resume selected ](https://user-images.githubusercontent.com/109403928/179341398-54648391-9191-4968-a362-c11b7ce94721.jpg)
That's a video recorded on a different day 

https://user-images.githubusercontent.com/109403928/179342576-b0d89c0d-29dc-4974-8b74-8d2af1b43068.mp4

### Expected behavior

After selecting the chapters the pop-up menu should have appeared and the RESUME option should have been gone . 
![normal 2](https://user-images.githubusercontent.com/109403928/179341597-f97b128e-24a1-40fe-aa71-12c2e2ae12ba.jpg)

### Actual behavior

What happens instead is that the RESUME option disappear for a moment and later spears and overlays the pop-up menu . 
![resume selected 2](https://user-images.githubusercontent.com/109403928/179341681-c3aee47b-c8cf-45ee-9a46-94863eaff7f0.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 9 / Android Pie

### Device

Xiaomi Redmi S2

### Other details

I experienced this in the 0.13.4 version and in that version this problem happened more often but in the 0.13.5 version it happens less or it takes more time to appear . Note that sometimes this bug / glitch doesn't appear or it might take some time to appear. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This has been fixed with the compose rewrite which is in preview.

**Comment by nachos999** [comment]
Ok , thanks 👍
