### ISSUE TITLE
Not going to last chapter

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#7542]
### Steps to reproduce

Series example: Martial Peak/One Piece/The God of High School

Steps to reproduce:
1. Open the last chapter
2. Press the previous button
3. Press the next button to go back to the last chapter

### Expected behavior

It should take me to the last chapter again.

### Actual behavior

It take me to the second to the last page of the current chapter instead.

### Tachiyomi version

v0.13.5 and r4631

### Android version

12

### Device

Redmi Note 10

### Other details

Marking previous as read from the 3rd to the last chapter/downloading both 2 last chapters does nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is adjusted in 0.14.x, not sure if still relevant.
