### ISSUE TITLE
Resume if you were on last page takes to next chapter

### ISSUE THREAD

**Issue by i2324561w2** [tachiyomiorg/tachiyomi#7543]
### Steps to reproduce

Read to the latest page of a chapter, you don't even know it's the latest but you have to close Tachiyomi before fully reading it, use Resume: you are now on the next chapter, and if a long time has passed maybe you don't even remember you didn't read the latest page of previous chapter

### Expected behavior

read until page 3, close TY, use Resume: page 3 is resumed and not page 4

### Actual behavior

skip a page but only if it's the latest

### Tachiyomi version

0.13.5

### Android version

LOSv17.1 (Android 10)

### Device

Xiaomi Redmi Note 8

### Other details

Edit: why posting this made a notification saying "Issue moderator workflow run succeeded for master branch" and linking to https://github.com/tachiyomiorg/tachiyomi/commit/a21aa8125e63b9e0d4377aa9c97d6614ee4acf7f and https://github.com/tachiyomiorg/tachiyomi/actions/runs/2681304133/workflow ?!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not sure I fully understand what you wrote, but a chapter is considered read if you reached the last page.

This may also be somewhat confusing in longstrip format content since "pages" aren't that well defined.

**Comment by i2324561w2** [comment]
I accept your decision, but since you wrote you didn't fully get what I wrote, I will now reply.
I actually don't use Longstrip format, so I suppose this should affect only the SinglePage format.
I often read something that is already fully translated, and I often stop reading randomly (and not when I reach the next chapter), so if I'm on the penultimate page of a chapter, press next page but then I have to go, I quit Tachiyomi: the next time I'll resume it I will be on the next chapter and maybe I won't even remember I didn't read the previous page at all.
Also the current behaviour doesn't seem to be coherent since if you are on page 3 and quit TY, the next time you'll resume you will be on page 3 and not 4.
Thank you for considering this.
