### ISSUE TITLE
Histogram equalization as another filter option for e-ink devices

### ISSUE THREAD

**Issue by joao945** [tachiyomiorg/tachiyomi#7545]
### Describe your suggested feature

Adding histogram equalization to the filters section would improve contrast in e-ink devices automatically and consistently, minimizing the need for manual screen contrast adjustment. The current "color filter blend mode", even when set to "burn/darken" doesn't improve contrast on e-ink screen in my testing, and would require manual adjustment per manga at any rate. I've annexed these images in order to show the significant contrast improvement:

<img src="https://user-images.githubusercontent.com/51891350/179360691-f1800524-27ca-4d7c-a7d1-e49c9bed7f22.jpg" width="400"><img src="https://user-images.githubusercontent.com/51891350/179360692-dab056bb-724b-4801-8c2d-3f6051733fbc.jpg" width="400">

For e-ink devices, which have low-contrast to begin with, this would enhance readability.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
To clarify adjusting custom filters is not per a manga

**Comment by CarlosEsco** [comment]
Also have you tried overlay?

Before:
![Uploading a3{f796df} (7cb8678f-f394-4256-9c5e-94a6055929c7 id=0x7f0a03c6 tag=BaseCommentFragment) …]()

After:
![Screenshot_20220716-181808.png](https://user-images.githubusercontent.com/2092019/179363284-d415d179-859a-441e-add5-2fd7adf65f65.png)

**Comment by joao945** [comment]
@CarlosEsco That works great, thanks. IMO this is sufficient to make it uisable on e-ink
