### ISSUE TITLE
Selected Category Changes

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7546]
### Steps to reproduce

Have a some Entry in a category with multiple categories.
1) In one of the categories, select an entry and remove it from the category
2) go back to the library
The category you were in will no longer be selected, it will now be the category to the left of that one. 

Also note that there may be other ways related to rotation of device of filtering to do the same, but I cannot remember how to reproduce it

My settings that might affect this: 
Default category is 'default', is empty, and is hidden when there is nothing in it. 
For this to happen, it may or may not need to not be in another category. 
I think the index of the category changes, but I am not sure if this is what is happening. 

### Expected behavior

Category selected should stay the same

### Actual behavior

selected category changes 

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Google Pixel 3

### Other details

This may be related to #7043 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No longer relevant after some UI rewrites that are happening.
