### ISSUE TITLE
Crash issue when reading 

### ISSUE THREAD

**Issue by Wandererboy263** [tachiyomiorg/tachiyomi#7554]
### Steps to reproduce

1. Continue reading in History
2. Scroll left and right
3. Scroll till it freeze

### Expected behavior

While scrolling, the app suddenly freeze

### Actual behavior

After stuck and freeze, the app restart 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9127926/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

Realme 6 

### Other details

I have a video. I'll just google drive it because I can't attach a video

(https://drive.google.com/file/d/14ADHLIAukQHvvknPY3TXnc8hObtnbW4Q/view?usp=drivesdk) [Crash Video ]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fatestaynplus** [comment]
This is happening for me as well. While reading for a certain amount of time, the app will freeze while scrolling between pages.

The issue does not seem to be specific to any manga / page as I can continue to scroll past normally once the app is restarted. 

I'm on the latest app version 0.13.5 (Stable), device is Lenovo P11 Pro tablet (Android 11). This issue is non-existent on the previous app version.

**Comment by DchanN** [comment]
this is the same of #7240? have a freeze issue too

**Comment by DchanN** [comment]
> Yeah, it seems like it's the same issue.
> 
> While I do not use Tachiyomi Preview, it's possible that whatever caused the freeze/crash was introduced into Stable in 0.13.5

maybe u can try comment your issue and steps too in #7240 because arkon label that's issue need more info

**Comment by arkon** [comment]
Closing in favour of #7240
