### ISSUE TITLE
Changing source

### ISSUE THREAD

**Issue by Nando4869** [tachiyomiorg/tachiyomi#7558]
### Steps to reproduce

Changed the source of the extension. From newtoki174.com to https://newtoki145.com/

### Expected behavior

I hope the newtoki extension can be used again

### Actual behavior

The newtoki extension cannot be used. A notification appears "newtoki174.com:NXDOMAIN"

### Tachiyomi version

0.13.5

### Android version

Android 8

### Device

Realme C1

### Other details

Sorry my English is bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you can change the url number in the extension settings. if you don't know how you can visit the discord to get more help.
