### ISSUE TITLE
Library page blank after deleting non-empty category(ies)

### ISSUE THREAD

**Issue by noobistbeach** [tachiyomiorg/tachiyomi#7563]
### Steps to reproduce

1. Navigate to categories page and delete any/all non-empty categories
2. Return to library to find that it is blank

### Expected behavior

Deleting non-empty categories should put all the entries in that particular category into the "default" category.

### Actual behavior

Deleting any/all non-empty categories results in a blank library page.

### Tachiyomi version

Preview r4631

### Android version

Android 12 

### Device

Samsung Galaxy A52 4G

### Other details

I have tried to reproduce the issue on another device, namely a friend's Samsung Galaxy A20 and it was successful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed in d977b89af1f2a8850437ebd978535fc3fbfd257e
