### ISSUE TITLE
Short images get zoomed in

### ISSUE THREAD

**Issue by farooh9999** [tachiyomiorg/tachiyomi#7565]
### Steps to reproduce

1. Open among manga or comic
2. If the image is short (horizontally rectangular) it will zoom in by itself

### Expected behavior

It shouldn't zoom in by itself

### Actual behavior

It zooms in by itself

### Crash logs

Not experiencing crashes

### Tachiyomi version

0.13.5

### Android version

11

### Device

Galaxy A10

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Go to the Reader settings and turn off "Zoom landscape image"
