### ISSUE TITLE
HTTP error 520 - Manga Chapters from MangaSee Extension Won't Load

### ISSUE THREAD

**Issue by it-wont-hurt** [tachiyomiorg/tachiyomi#7570]
### Steps to reproduce

1. Open Tachiyomi
2. Go to any Manga from MangaSee extension
3. Open a random chapter of manga

### Expected behavior

The chapter should open up without issue and I continue to read.

### Actual behavior

The chapter closes immediately without loading. Pop up in the bottom-center reads "HTTP error 520". Pop up fades away.

### Tachiyomi version

0.13.5

### Android version

Android 6.0.1

### Device

Galaxy Tab A

### Other details

I followed the Troubleshooting page. It's my first time using GitHub.
![image](https://user-images.githubusercontent.com/109727345/180175751-c24a23d4-e556-4c19-ba44-2d58211815ae.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Wrong Repo
Please read carefully
