### ISSUE TITLE
Shortcut for Tachiyomi's website to download extensions manually

### ISSUE THREAD

**Issue by 12ohit** [tachiyomiorg/tachiyomi#7571]
### Describe your suggested feature

Add one icon in the extension tab which when tapped on will open https://tachiyomi.org/extensions/ in the browser. The reason for this is that when for some reason extension is not downloading or installing you can easily go to this link and download the extension manually.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The next version should include an automatic fallback to another CDN when GitHub doesn't work for whatever reason.

If GitHub really isn't working for some reason, https://tachiyomi.org/extensions/ won't actually work either.

**Comment by 12ohit** [comment]
Got it, thanks : )
