### ISSUE TITLE
Toast of current resuming chapter

### ISSUE THREAD

**Issue by 12ohit** [tachiyomiorg/tachiyomi#7572]
### Describe your suggested feature

If I want to know which chapter I am currently on without scrolling all the way down when it's a big chapter list I should be able to just hold the resume button and it should show the toast of which chapter will be resumed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Re-Tails** [comment]
Would it be better to have the next chapter shown automatically on the button label ("Resume Ch.5") or as a toast instead?

**Comment by 12ohit** [comment]
Yes I don't mind if you guys do it like j2k fork too, I don't care how you implement it I just wanna know which chapter I am on currently without scrolling all the way down and I thought toast was the easiest way to do it so I suggest that

**Comment by arkon** [comment]
As mentioned in #7768:

> Someone on Discord suggested adopting the J2K button between the info and chapters, along with a suggestion of showing the FAB only when that button isn't visible.
> 
> We could also have a subtitle below the "x chapters" heading that tells you what's next or what you're currently on?

That said, none of these seem nice IMO.

Does it actually matter what chapter you're on?

**Comment by 12ohit** [comment]
I often switch devices to read manga that time I want to know which chapter I am on. But if you are not comfortable with this whatever you decide is ok 👍

**Comment by CarlosEsco** [comment]
> I often switch devices to read manga that time I want to know which chapter I am on. But if you are not comfortable with this whatever you decide is ok 👍

hide read chapters, and sort oldest chapters to newest and you never need the fab/button again

**Comment by 12ohit** [comment]
> > I often switch devices to read manga that time I want to know which chapter I am on. But if you are not comfortable with this whatever you decide is ok 👍
> 
> hide read chapters, and sort oldest chapters to newest and you never need the fab/button again

Bro thanks so much this works for me too🙏
