### ISSUE TITLE
Custom Rom database corruption

### ISSUE THREAD

**Issue by Kogar111** [tachiyomiorg/tachiyomi#7573]
### Steps to reproduce

Have a custom rom with a lot of optimisations (especially "Configure SQLite to operate in MEMORY mode")

1. Have a **large** library (import from backup or manually added) 
2. Update library, quickly switch between tabs(library/new/browse etc) or force close app and reopen
3. After last step of library update, after a couple quick times of switching tabs or directly after force closing and reopening app library is corrupted and partly or completly deleted from android

### Expected behavior

library data properly read/write into persistent database without data corruption. Even for longer lasting threads/large library

### Actual behavior

Database corruption when multiple parallel async threads are active (quick tab switching, library updating) or thread abruptly gets cut off (force close). Likely data written into same space because of SQLite memory mode optimisation and edge case missing in tachiyomi. (Up to now no problem with other apps)

### Crash logs

--------- beginning of main
07-21 21:30:35.166 27190 27284 E SQLiteLog: (11) database corruption at line 67658 of [5c9a6c0687]
07-21 21:30:35.166 27190 27284 E SQLiteLog: (11) statement aborts at 22: [SELECT M.*, COALESCE(MC.category_id, 0) AS category
07-21 21:30:35.166 27190 27284 E SQLiteLog:     FROM (
07-21 21:30:35.166 27190 27284 E SQLiteLog:         SELECT mangas.*, COALESCE(C.unreadCount, 0) AS unread_count, COALESCE(R.readCount, 0) AS read_count
07-21 21:30:35.166 27190 27284 E SQLiteLog:         FROM 
07-21 21:30:35.176 27190 27284 E SupportSQLite: Corruption reported by sqlite on database: /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db
07-21 21:31:43.451 27190  3080 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
07-21 21:31:43.452 27190  3080 E chromium: [ERROR:simple_index_file.cc(617)] Could not reconstruct index from disk
07-21 21:31:43.550 27190 27246 E SQLiteLog: (284) automatic index on C(manga_id)
07-21 21:31:43.550 27190 27246 E SQLiteLog: (284) automatic index on R(manga_id)
07-21 21:31:43.550 27190 27246 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 12 (SDK 32)
Android build ID: cherish_davinci-userdebug 12 SQ3A.220705.003.A1 1657645723 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: davinci
Device model: Redmi K20
Device product name: cherish_davinci

### Tachiyomi version

0.13.5

### Android version

Android 12.1 (Cherish OS 3.9)

### Device

Redmi K20

### Other details

Same problem in all other forks on many (android 12) custom roms.
https://github.com/Jays2Kings/tachiyomiJ2K/issues/1322

Similar problems found in tachiyomi Discord channel. Search keywords: "custom rom", "library vanish", "library empty", "database corrupt"

Blind assumption from me after testing multiple custom roms.
Because of "in-memory database" database doesn't get properly saved into persistent space.
In multiple custom roms i found a line similar to that in their changelog "Configure SQLite to operate in MEMORY mode"

https://www.sqlite.org/inmemorydb.html
> The database is automatically deleted and memory is reclaimed when the last connection to the database closes. 

Maybe some stuff that could help
https://www.sqlite.org/howtocorrupt.html#multiple_copies_of_sqlite_linked_into_the_same_application
https://medium.com/androiddevelopers/threading-models-in-coroutines-and-android-sqlite-api-6cab11f7eb90

Changes to SQLDelight?
https://www.sqlite.org/pragma.html
> The locking mode of temp and [in-memory databases](https://www.sqlite.org/inmemorydb.html) cannot be changed. All other databases use the normal locking mode by default and are affected by this pragma.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is there a good reason why the ROM devs believe that forcing the memory mode pragma is an "optimization" when it's also well known that Android app lifecycle is **not** reliable?

**Comment by arkon** [comment]
Closing for now since today's preview build will include the commit mentioned by ghostbear.

If the ROM still decides to break apps by forcing unwanted behaviour, then I'd suggest talking to the ROM devs or finding a more sensible ROM...

**Comment by arkon** [comment]
Yes, that's the same commit.
