### ISSUE TITLE
Update all extensions/mass update button

### ISSUE THREAD

**Issue by Ovab** [tachiyomiorg/tachiyomi#7574]
### Describe your suggested feature

Title explains it all:
Button that downloads all the updates for extensions so you only have to spam the android prompt to update all your extensions at once.

alternatively you can select a few extensions to update and do it like described above.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already exists unless you're using a Xiaomi device since they broke the Android APIs for it.

**Comment by ghostbear** [comment]
Already exists if you use Android 12 and up or if you have an older version of Android you can use the Shizuku package installer

**Comment by Ovab** [comment]
> Already exists unless you're using a Xiaomi device since they broke the Android APIs for it.

welp that explains, using a poco f3.
Unfortunate but thank you
