### ISSUE TITLE
Large library doesn't load & causes crash on update

### ISSUE THREAD

**Issue by deeplyarnab** [tachiyomiorg/tachiyomi#7576]
### Steps to reproduce

Open app then Try to update via update tab.

### Expected behavior

Load manga, update library & perform backup.

### Actual behavior

Updating via update tab causes app to freeze.
The library never loads either (tested for over 10 mins wait time).
The categories section from "more" tab is blank too but loads after 1 minute.
Backup fails after 10mins or so with "unknown error" or "job was cancelled".

### Crash logs

[logcat_07-21-2022_21-57-18.txt](https://github.com/tachiyomiorg/tachiyomi/files/9162817/logcat_07-21-2022_21-57-18.txt)
[logcat_07-21-2022_21-59-39.txt](https://github.com/tachiyomiorg/tachiyomi/files/9162819/logcat_07-21-2022_21-59-39.txt)

Gave permission via adb shell to logcat app, don't see anything useful though.

### Tachiyomi version

any above Preview r4524

### Android version

Android 11

### Device

Oneplus Nord

### Other details

I have over 5k manga in library with 20+ categories. 30% of them are from sources not supported anymore since i've been hoarding for a long time. I think the new per category setting and stuff is causing the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dragoon91786** [comment]
Been having the same problems for a while now. Now, even the extension/sources refuse to load, or they don't load content when they do appear or load it so slowly as to take hours, but the moment one rotates the screen it goes back to perpetual loading/blank screen. 🤷🏽

**Comment by Dragoon91786** [comment]
> Been having the same problems for a while now. Now, even the extension/sources refuse to load, or they don't load content when they do appear or load it so slowly as to take hours, but the moment one rotates the screen it goes back to perpetual loading/blank screen. 🤷🏽
> 
> Android 10 on LG LM-V600AM running V600AM10q.

Running nightly versions starting w/ r4553. The bug issue with backups has been going for a while. Multiple TRIM seems to have fixed the slow app load problem, but not anything internal.

**Comment by sahilbansal2701** [comment]
I have also been having the same issues, where it takes minutes for each step.
This is on Android 11, Tachiyomi v0.14.4

**Comment by arkon** [comment]
There's been significant changes since this was first opened, please open new issues if it still happens, including device info and a backup file if possible.
