### ISSUE TITLE
Local Source

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi#7577]
### Steps to reproduce

1. Open the "Local" source

### Expected behavior

The manga that I have in the tachiyomi/local folder load and appear normally.

### Actual behavior

Nothing comes out, not even the reason for the bug

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9164456/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Samsung S10+

### Other details

![Screenshot_20220721-211602_Tachiyomi](https://user-images.githubusercontent.com/101371218/180358599-84c45011-5ec2-4301-b9f9-6db7a541f96d.jpg)
![Screenshot_20220721-211613_My Files](https://user-images.githubusercontent.com/101371218/180358603-868e7e4f-e1a6-43db-ab3c-0423cdfcb995.jpg)

This only happens when I add the "Bleach" folder which contains 52 chapters in .cbr, I remove it from there and the rest loads normally, I wonder why this happens, I would appreciate an answer, I guess it is because of the weight, but it has no logic because the Opm folder (JAP) weighs 7gb and loads normally, I checked the Bleach files and they have nothing harmful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you mind pinging me on Discord (`arkon#0001`; link to server is https://discord.com/invite/tachiyomi) so you can DM me to share one of the CBR files that causes it to fail?

**Comment by edmxn** [comment]
> Do you mind pinging me on Discord (`arkon#0001`; link to server is https://discord.com/invite/tachiyomi) so you can DM me to share one of the CBR files that causes it to fail?

I can't send you direct messages, and I can't write in the group chat either because the phone verification is not working, I will edit this post and attach the file

**Comment by arkon** [comment]
This will be fixed in the next release but in the meantime, you need to rearchive your CBR files since they're in the unsupported RARv5 format.
