### ISSUE TITLE
Multiple selected serie download option with the same option as the in-series one

### ISSUE THREAD

**Issue by Vacui** [tachiyomiorg/tachiyomi#7579]
### Describe your suggested feature

When I want to evaluate multiple series I have the habit of downloading their first 10 chapters, because I think they are an amount sufficient to form an opinion, unfortunately, I have to enter each series and use the inside download button to access the "Next 10 chapters" option that allows me to do it. I would like to have the same options that are present in the in-series download button accessible in the one that appears when you select multiple mangas in the library, instead of the only option to download the entire series.

Thanks for your time,
keep up with the nice work, and have a great day.

Matteo

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Was added in [v0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.2)
