### ISSUE TITLE
Dummy source for library entries without available new one / update skip option

### ISSUE THREAD

**Issue by twwn** [tachiyomiorg/tachiyomi#7580]
### Describe your suggested feature

Some library entries, for whatever reason, lose their source but have no alternative ones available for migration.

In that state, Tachiyomi keeps notifying about a failed update: "no chapters found". (If it then adds another notification, that bundle can't be quickly swiped away from the notification tray, either.)

So it would be nice to either have a dummy source that just makes TY believe that there's "no change", or alternatively a setting that just skips that entry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You can add them to a category and have that category not update
