### ISSUE TITLE
"Skip update log"

### ISSUE THREAD

**Issue by cojoMan** [tachiyomiorg/tachiyomi#7587]
### Describe your suggested feature

Currently with the latest TY update, there are a few checkboxes for the library to skip completed/not started comics. That is great, but can we also have something to skip those in the error log as well ? I for one would like to see in the error log the errors, and the succesfully updated ones, but I am filled like 80% of the log with the ones that were skipped because "completed".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
0.13.5 doesn't include skipped entries in the error log.
