### ISSUE TITLE
'Insecure' WebView browser according to Google, prevents log in 

### ISSUE THREAD

**Issue by EstebanOD** [tachiyomiorg/tachiyomi#7588]
### Steps to reproduce

1. Open the Webtoon (English) extension
2. Click on "WebView"
3. Click on "LOG IN"
4. Click on the Google logo under "OR Log in with"
5. Enter Gmail address
6. Impossible to log in via Google:

"Impossible to connect.
This browser or application may not be secure.
 Try in another browser.  If you're already using a compatible browser, you can try logging in again."

### Expected behavior

The WebView browser should be consider 'secure' for Google to let us log in our account, so we can use our Google account to log in certain websites such as Webtoon using Google.

### Actual behavior

Google doesn't consider the WebView browser 'secure'.

### Tachiyomi version

0.13.5

### Android version

Android 10

### Device

Huawei P20 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Google intentionally doesn't allow WebView.
