### ISSUE TITLE
I have problems with language

### ISSUE THREAD

**Issue by Alirezareis** [tachiyomiorg/tachiyomi#7590]
### Steps to reproduce

I use my language as system default
its persian and its right to left
When i updated the app everything got out of place and goofy (like by swiping right it goes left etc.)
is there no way to set the lang to English?

### Expected behavior

I use my language as system default
its persian and its right to left
When i updated the app everything got out of place and goofy (like by swiping right it goes left etc.)
is there no way to set the lang to English?

### Actual behavior

I use my language as system default
its persian and its right to left
When i updated the app everything got out of place and goofy (like by swiping right it goes left etc.)
is there no way to set the lang to English?

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

poco x3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> When i updated the app everything got out of place and goofy (like by swiping right it goes left etc.)

This will be fixed in upcoming UI rewrites.

> is there no way to set the lang to English?

Not at the moment. Language changing was removed due to other bugs it caused, but may return in the future when the official API for it stabilizes.
