### ISSUE TITLE
Auto download new chapters for chosen mangas

### ISSUE THREAD

**Issue by Cypral** [tachiyomiorg/tachiyomi#7593]
### Describe your suggested feature

As of now it is possible to enable automatic download of new chapters for mangas in selected categories, but in my case for example I'd like to enable this only for mangas I read on the "Manga PLUS" extension since it can only fetch the 3 latest chapters for free, and downloading chapters when they are released make it possible to still read it after 3 weeks even if they're not fetchable anymore. I know a solution for this would be to put the mangas I want in a categories together but it's not a really good solution for me as the way me mangas are organised. Thanks for reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedziyaanmuhamed** [comment]
Create a second category for the one you want to download and add it to the category you just create and don't remove from the existing Category

**Comment by arkon** [comment]
Using an additional category is the way to go.
