### ISSUE TITLE
Pressing back button to return to library makes the filter sheet appear

### ISSUE THREAD

**Issue by TheUnlocked** [tachiyomiorg/tachiyomi#7603]
### Steps to reproduce

1. Click History, Browse, or More in the bottom navigation bar (not Updates)
2. Click the back button

### Expected behavior

Returns to library as normal.

### Actual behavior

Returns to library and immediately opens the filter sheet.

### Tachiyomi version

r4687

### Android version

9 (SDK 28)

### Device

Samsung Galaxy S8 (SM-G950U1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by von-wa** [comment]
it also happened on Updates page if you double click back button quickly for me
