### ISSUE TITLE
App closing repeatedly

### ISSUE THREAD

**Issue by Nichirin404** [tachiyomiorg/tachiyomi#7610]
### Steps to reproduce

First Step: Don't open the app for atleast straight 2 days.
Second step: You should get the error by now after opening it the next time.

### Expected behavior

The app should normally open like all other apps. But it doesn't, infact it keeps stopping repeatedly.

### Actual behavior

Tachiyomi is a great app. I've never faced any kind of bug yet but this particular one has been irritating me recently.
When I don't open the app for atleast 2days straight, it keeps closing automatically when I open it the next time. I tried everything from clearing data / cache , restarting device but it won't get fixed. The only solution is to re-install the app again. It becomes normal again until I don't open it for some days again. It's becoming irritating as everytime when it happens I lose all my data and have to restore it again by restoring the backup manually. I also lose my downloads and have to re-download them again when I already have them downloaded in my device.

### Crash logs

Sorry, as I can't even open the app during the crash, I can't retrieve the crash log after reinstalling it.

### Tachiyomi version

0.13.4 and 0.13.5 (both)

### Android version

Android 7.0

### Device

Walton Primo NH2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by Nichirin404** [comment]
Sorry for the late response :((
Here you go!

**The crashes are more frequent now!!

--------- beginning of crash
08-09 14:47:31.912 18156 18409 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 18409 (AsyncTask #2)
08-09 14:49:07.185 18698 18776 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 18776 (AsyncTask #2)
08-09 14:49:41.207 18901 18985 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 18985 (AsyncTask #3)
08-09 14:49:59.434 19011 19086 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 19086 (AsyncTask #2)
--------- beginning of system
--------- beginning of main
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 7.0 (SDK 24)
Android build ID: Walton_Primo_NH3_V08
Device brand: WALTON
Device manufacturer: WALTON
Device name: Primo NH3
Device model: Primo NH3
Device product name: Walton_Primo_NH3

**Comment by arkon** [comment]
I suspect most crashes are pretty different nowadays due to all the rewrites, so please open a new issue with new crash logs if you're still encountering issues.
