### ISSUE TITLE
Tool bar to bookmark, mark as read, etc. doesn't show up when long pressing a chapter in the "Updates" page

### ISSUE THREAD

**Issue by von-wa** [tachiyomiorg/tachiyomi#7612]
### Steps to reproduce

1. Open the "Updates" page
2. long press a chapter

### Expected behavior

the tool bar with mark as read, bookmark a chapter, etc on the bottom of the screen shows up

### Actual behavior

the tool bar  with mark as read, bookmark a chapter, etc doesn't show up
"Updates" page: https://imgur.com/a/doiSjA5

### Tachiyomi version

r4687

### Android version

Android 8

### Device

Samsung galaxy A5 2017

### Other details

The tool bar shows up in "Library" page and in individual manga pages, but not in "Updates" page
"Library" page: https://imgur.com/a/byQYz4k
manga page: https://imgur.com/a/u58Yf4n

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is this still an issue in newer builds?

**Comment by AntsyLich** [comment]
It's been fixed in #7627
