### ISSUE TITLE
R4687 Randomly trying to download random chapters

### ISSUE THREAD

**Issue by WaterCooler8** [tachiyomiorg/tachiyomi#7614]
### Steps to reproduce

N/A 

### Expected behavior

Nothing (?) 

### Actual behavior

App started in the middle of the night to download random unread chapters from random mangas that are in the library, example : chapter 16, 17, 21 and 28 of yuusha yamamura, that i havent even started

### Tachiyomi version

R4687

### Android version

Android 12

### Device

Samsung Note 20

### Other details

Didnt stop untill all mobil data was used, since wifi was disabled,  now i have 15 gb worth of random chapters :[

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Please check the following:
1. Check More > Settings > Library > Global Updates > Global Update Frequency
2. If you do have global updates enabled, check these settings: Updates Device Restrictions and Skip Updating Titles
3. Check More > Settings > Downloads > Auto download and see if its enabled
4. If you use Categories, check which categories are enabled for Global Update (from 1.) and Auto Downloads (from 3.)

> example : chapter 16, 17, 21 and 28 of yuusha yamamura, that i havent even started

You did not mention which source/website this manga is from. Also if you have dont want to update manga you have not started: then use the Skip Updating Titles setting to skip manga not started and read

**Comment by arkon** [comment]
Should be fixed by #7597
