### ISSUE TITLE
Updating one Category, updates the entire Libary

### ISSUE THREAD

**Issue by AlbedoSuzuki** [tachiyomiorg/tachiyomi#7618]
### Steps to reproduce

Initiating of the Category-Update by doing a scroll up move on the device 

### Expected behavior

Update the selected Category

### Actual behavior

Updating the entire Libary

### Tachiyomi version

0.13.5-4687

### Android version

HarmonyOS 2.0.0

### Device

Huawei MatePad 11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Fixed in https://github.com/tachiyomiorg/tachiyomi/commit/bc1f6ba5177735e76b2b42f7884edfbe8f30006e
