### ISSUE TITLE
Skip undownloaded chapter/skip label for chapters

### ISSUE THREAD

**Issue by OshidaBCF** [tachiyomiorg/tachiyomi#7619]
### Describe your suggested feature

There is a lot of manga that get multiples scanlation team on the same chapters, i usually download all the chapter except those that i know i wont read.

i currently mark those "won't read" chapters as read, then turn the "skip already read chapters"

But i love to reread manga, and for that i need to turn that option off.

I request another setting that would skip any chapter that wasn't downloaded (could only be applied if currently reading a chapter that was downloaded.

Another option would be to mark those chapters as "skipped" and those would automatically be skiped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#969 would be the proper way to handle this.

**Comment by OshidaBCF** [comment]
Does work if you have only 1 or 2, i have a few manga where it have 3-4 scan team.
