### ISSUE TITLE
Add manga release date 

### ISSUE THREAD

**Issue by bonechan3** [tachiyomiorg/tachiyomi#7620]
### Describe your suggested feature

add the original date on which the manga was released along with its title 

### Other details

Add the year in which the manga was released with the title 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Sources do not reliably provide this information.
