### ISSUE TITLE
Solicitação de Extensão 

### ISSUE THREAD

**Issue by Greed-2468** [tachiyomiorg/tachiyomi#7630]
### Describe your suggested feature

Extensão para o site https://mangasoverall.com/

### Other details

Não tem muitas extensões que adicionam mangá e webtoons de diferentes Scans no idioma português Brasil se possível gostaria que mais fossem adicionadas.

Obrigado pela atenção 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please read what you acknowledge instead of just checking the boxes.
