### ISSUE TITLE
Library search "Search globally" button hidden while keyboard is open

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7631]
### Steps to reproduce

Search in Library

### Expected behavior

"Search globally" button visible

### Actual behavior

https://user-images.githubusercontent.com/63973749/181389450-e06c24a0-88ba-4347-bcf1-838cf190e4ee.mp4

### Tachiyomi version

r4703

### Android version

12.1

### Device

Redmi Note 9 Pro (PixelExperience)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DoozyDoz** [comment]
The button is visible, click it, it works. Maybe you need to clarify more

**Comment by vengiare** [comment]
> The button is visible, click it, it works. Maybe you need to clarify more

Sometimes it is hidden initially and you would need to scroll up to see the button

![Screenshot_20220801-015730_Tachiyomi](https://user-images.githubusercontent.com/63973749/182039234-48e3c2c1-6d25-4ab0-a2ce-5ae3a7ea475a.png)

**Comment by ghostbear** [comment]
> Sometimes it is hidden initially

That statement is just wrong but okay
