### ISSUE TITLE
Tachiyomo Keep Stoping

### ISSUE THREAD

**Issue by MarkJayEspiritu** [tachiyomiorg/tachiyomi#7632]
### Steps to reproduce

there is no step 

### Expected behavior

it should be fine and the app is supposed to open

### Actual behavior

last yesterday the App is fine and im reading some manga
then yesterday i saw the notification that may Tachiyomi is not responding and i ignore it
then the night comes i want to read new manga then suddenly the App stop working and i dont know what happen

i try Everything
update, clear Data and Cache, uninstall and install and restart my phone a lot of times but still not opening

all it shown is just a Tachiyomi Logo and thats it, it keeps closing again and again
![Uploading asdsc.png…]()

### Crash logs

![asdsc](https://user-images.githubusercontent.com/110159703/181454864-ac30ebe9-ec54-4969-b3c8-0bb7fc3d2c8a.png)

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

LG K41S

### Other details

none

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
this is a issue that have been happening since preview before 13.5 and still happens sometimes until now

**Comment by arkon** [comment]
No crash logs provided.
