### ISSUE TITLE
new chapters buffered until old chapters read?

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#7634]
### Steps to reproduce

favourite a title
read some
leave 
-- no updates for months (if ever)
read some
-- update of 17 chapters the day after
read some
-- update of 15 chapters the day after
leave
-- no chapters for months (if ever)

### Expected behavior

favourite a title 
read some
-- update of n chapters whenever
-- update of n chapters whenever
-- update of n chapters whenever
read some
-- update of n chapters whenever
leave
-- update of n chapters whenever

### Actual behavior

When leaving a favourited title for an extended amount of time I often don't get updates to that title until I've read some/finished (I'm not sure which) currently available chapters.

Sometimes I've looked at the providers website and it reflects that there are no new chapters, so confused.

### Tachiyomi version

0.13.5

### Android version

12

### Device

Google pixel 4a

### Other details

I think its been happening for a few versions now, but I dont know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by skrshe** [comment]
update I checked a title that is currently doing this and there is a new chapter on the website that doesnt display in tachiyomi after refreshing the library tab that title is in.

**Comment by skrshe** [comment]
I also have auto updates set to daily

**Comment by skrshe** [comment]
why is skip updating titles with unread chapters turned on by default?

**Comment by skrshe** [comment]
never mind.

**Comment by skrshe** [comment]
solved by unchecking skip updating titles with unread chapters.

**Comment by arkon** [comment]
There's a notification that explicitly links out to https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries to explain the behaviour.
