### ISSUE TITLE
UX: Tracking: Streamline interface

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7635]
### Describe your suggested feature

Introduction New feature: 
- ONE tracking box, with the normal status, score, progress, and dates 
- - Scores and total chapter counts might be omitted depending on implementation. Otherwise:
- -- If the total chapter count differs, display a red "!" or something like that. (or display a prefered or approximate in red)
- -- Scores might be able to just use the most "detailed" number and round (ie, since AL lets you do decimal scores, inputting 7.9 would make MAL round to 8)
- Since this does not rely on an external service, it would be cool if this could also be used in filtering (ie, filter by status) 

What happens to existing features: 
- Move current tracking pane: a button for "detailed" or "advanced" tracking (or something similar) can be implemented under the new interface. This will allow users to still be able to use the current functionality if they want to on occasion 
- A new setting to "prefer detailed tracking" can be implemented to make any user who prefers this way have it as the default 

### Other details

As always, this is an _idea_, and is not meant to be exactly like what could be (or not be) implemented. Build off the base and discuss realistic ways a similar thing could be done, and if it is a good idea or not. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favor of #8459
