### ISSUE TITLE
Tick Option on Results for Migration

### ISSUE THREAD

**Issue by rlawliett** [tachiyomiorg/tachiyomi#7636]
### Describe your suggested feature

There is a tick box on search other sources to migrate wherein, entries with No Alternatives Found can be hidden so that we would not be looking for those with results and instead of scrolling through long list of empty results before getting a new one.

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There were actually complaints/confusion when the app used to automatically sources that had no results.
