### ISSUE TITLE
Start date doesn't get automatically added to tracker.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#7637]
### Steps to reproduce

1. Log into a tracker.
2. Read the first chapter of a manga.

### Expected behavior

Start date get's added along with status and progress being set automatically.

### Actual behavior

Start date doesn't get added but status and progress are set automatically.

### Tachiyomi version

0.13.5-4703

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

This has been happening for the past few previews, and it started with only a few not being added to almost all now.

The tracker I am using is anilist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #6734
