### ISSUE TITLE
Images are not loading since yesterday.

### ISSUE THREAD

**Issue by Abhinav1217** [tachiyomiorg/tachiyomi#7638]
### Steps to reproduce

I have been using Tachiyomi for past few months, But since yesterday, images are not loading. I am getting error "The image couldn't be loaded" with a 'Retry' button on every page of every comic in library, But not for those that are not in library, via search. I tried different manga source but same thing, Images are not loaded if I add it to my library. 

I updated to 0.13.5 today from website directly, but this updated version also have same issue. 

### Expected behavior

Manga pages should be loaded.

### Actual behavior

Getting error, "The images couldn't be loaded" with retry button.

### Tachiyomi version

0.13.4; 0.13.5

### Android version

Android 11 

### Device

One Plus 7 Pro

### Other details

I have tried switching source via migrating, and also by removing manga from library but adding from another source.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
Did you try to clean the cache? Try going to configuration> advanced and clean cache, webview data and cookies, maybe will fix your problem. At least here I use stable and preview versions of tachiyomi and is working in Android 11 as well

**Comment by raziel100** [comment]
No, my mistake. I'm having the same problem as you now. In close to all my sources, the old chapters that was working some times.

**Comment by animactix** [comment]
I'm also having the Same problem

**Comment by raziel100** [comment]
I have tried beta webview but apparently it's not the problem

**Comment by Allied-R** [comment]
I just started having issues with mamgahub doing this same thing today.  I tried going through webview and opening chapters of different manga but I get redirected by ads so that might he part of the problem.

**Comment by raziel100** [comment]
> I just started having issues with mamgahub doing this same thing today. I tried going through webview and opening chapters of different manga but I get redirected by ads so that might he part of the problem.

I have tried only MangaHub because he have told have tested other sources Has well, but I have tried manganato, batoto and others and mangohub is the only broken apparently I think we need to open a issue in the extension github. Not here

**Comment by raziel100** [comment]
For MangaHub have been opened a [Issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12773)  already

**Comment by raziel100** [comment]
@Abhinav1217 what source did you have tried? Apparently is a source problem than app problem

**Comment by alessandrojean** [comment]
Closing since this is something extension related and not app related.

**Comment by Abhinav1217** [comment]
@alessandrojean @raziel100 

> Closing since this is something extension related and not app related.
> What source did you have tried? Apparently is a source problem than app problem

I maybe wrong but I don't think it is extension related for the following reasons:

1. It is happening on multiple sources, so unless all extention suddenly gets corrupted, it is more likely that how app uses those extensions is what causing the issue.

2. (Taking 1manga source as example).  If I do a global search for (say "kenja no mago") and open the view the chapters from search, it is working. But when I added it to library, it isn't working anymore.  

I initially thought that the extension was the cause of issue since most of my libraries were from 1manga, So I migrated it kissmanga after checking that it was working, but when I accessed it from library (Home screen) it gave same issue. I went back to search to check if it is working or not, and it was working there in the search page, but when accessing it from library, it isn't working.

**Comment by alessandrojean** [comment]
There's a lot of sources that are broken, so define "all sources" you tried as this is very vague and isn't helping much.

**Comment by alessandrojean** [comment]
> Taking 1manga source as example

It's broken as reported in the extension repository. You also need to try the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#troubleshooting) guide first.

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12773

We can provide you more help through our [Discord server](https://discord.gg/tachiyomi), as it's very difficult to do our help procedures here, but yeah, it's most likely an extension issue and not app related, you probably just tried bad sources or ones that are known for being broken. We can know better and help better through the Discord I mentioned.

**Comment by Abhinav1217** [comment]
> And no need at all to mention me, we all receive emails when someone replies.
Ok, I didn't knew that. I will keep that in mind.

> There's a lot of sources that are broken, so define "all sources" you tried as this is very vague and isn't helping much.

Kenja no Mago:
 - Originally added in library from 1manga 
 - Migrated to Kissmanga 
 - Removed it from library and added from comicKfun (not migrated, clicked on "💗 Add to Library" button)
 - Migrated it to MangaDex,
 - Migrated it to MangaFox.

World Trigger:
- Originally from 1manga,
- Migrated it to comick fun
- Migrated it to KissManga
- Removed it from library and added from MangaBuddy (Manga Buddy is working for me)


It was at this point I confirmed that opening manga from search screen is working but opening it from library is not. 


Just to clarify, 
- I cleaned caches many times.
- I updated from 0.13.4 to 0.13.5, and instead of restoring from backup, I installed these extensions again (I already planned to reduce all extra extensions)

**Comment by alessandrojean** [comment]
MangaDex should have worked fine as it's not broken, but eventually it does have some connectivity issues related to some networks. Anyway, please ask for help in the official Discord server I mentioned and we will be able to help you better and potentially fix your issue :+1:

**Comment by Abhinav1217** [comment]
> MangaDex should have worked fine as it's not broken,

None of the sources are broken for me, even mangahub is working for me, As long as I open the chapters from the search result, not from library.

**Comment by Abhinav1217** [comment]
I have joined discord, But it is asking me to submit phone number before I could send message. I am not comfortable with this. I already tried reddit before creating issue here, but it is also locked for community members, If there is no other way to get support, just let me know.

**Comment by CrepeTF** [comment]
> I have joined discord, But it is asking me to submit phone number before I could send message. I am not comfortable with this. I already tried reddit before creating issue here, but it is also locked for community members, If there is no other way to get support, just let me know.

There is a support mega-thread on reddit which you reply to. You don't create posts.
