### ISSUE TITLE
Easier way to see titles associated with an extension

### ISSUE THREAD

**Issue by T3sT3ro** [tachiyomiorg/tachiyomi#7640]
### Describe your suggested feature

It is hard to look for titles that are associated with a source. Currently I know of two ways to do that:

1. In the library search, type the name of the extension (this can give false positives, if, by chance, some manga is named similarly to a source)
2. If you know manga X is from source Y: click on manga X-> click on extension name -> it basically does the same thing as in 1.

This is problematic when I want to identify extensions, which have small or big number of mangas. E.g. I have an extension KireiCake installed, but I don't know how many titles are associated with it, and each one of them in the library I would have to check manually.

My proposition is to add any of the following:

- search attributes in library like `source:<source>`
- source grouping in library (folds per source)
- a screen that displays titles per extension in the extensions tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Browse → migrate already has that info and you can view what stuff is from which extension in your library

**Comment by T3sT3ro** [comment]
Ok, thanks. But even then, I can't easily find which extensions have no associated titles with them. In this case, I think something in the "Browse" tab should be merged together for better UX, as that was counter-intuitive place, if I want to quickly see (and not migrate) all titles from one source. For example:

- merge sources, extensions and migration, then append `(n)` just like in "Migration" tab to sources, group them by the "installed", "not installed, and "obsolete", and inside the source add , install/uninstall buttons, local manga and browse
- OR (simpler) merge just extensions tab with migration tab.

**Comment by CrepeTF** [comment]
merging any screens would likely not happen in 0.x due to the amount of work associated with it. Though 1.x is already seeing some merged functionaility of Sources and and Extensions views

**Comment by CrepeTF** [comment]
One thing I would see being more realistic is the migrate tab also being able to show sources which you do not have entries in your library for
