### ISSUE TITLE
The image could not be loaded.

### ISSUE THREAD

**Issue by Kissieh** [tachiyomiorg/tachiyomi#7645]
### Steps to reproduce

When you open the app, go for the manga u want to read, you get new chapters but when you click to read the images do not get loaded no matter how many times you try.

### Expected behavior

Loaded images to read.

### Actual behavior

The images do not load.

### Crash logs

None.

### Tachiyomi version

0.13.5

### Android version

Android 11 MUI version 12.5.7

### Device

Redmi Note 8 Pro

### Other details

Sometimes one image loads for few seconds nd then disappears again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Kissieh** [comment]
> > If this is an issue with an extension, I should be opening an issue in the extensions repository.

this is NOT an issue with an extension, ALL extensions have the same problem.

**Comment by arkon** [comment]
All 1000±?

**Comment by Kissieh** [comment]
All my 156, should this issue still be opened in the extensions repository?
Confusion: it says "an extension" Which could be interpreted as one specific extension at a time.

**Comment by arkon** [comment]
You can try asking in the Discord server for general help if you can't figure out actual details to report after already having gone through the troubleshooting guide.
