### ISSUE TITLE
"Image can not be loaded" error

### ISSUE THREAD

**Issue by HageshiOkan** [tachiyomiorg/tachiyomi#7647]
### Steps to reproduce

Simply opening the app and pressing any manage in any repository is making the error occur.

### Expected behavior

This shouldn't happen

### Actual behavior

Getting a black screen with the text above.

### Crash logs

![Screenshot_20220729-111334_Tachiyomi](https://user-images.githubusercontent.com/110254688/181819856-a3bd8ad8-4fad-4647-a37d-6917b9dcdcd8.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 9

### Device

Galaxy S10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #7645
