### ISSUE TITLE
Custom Password

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#7649]
### Describe your suggested feature

We should able to use custom password instead of phone's password to lock Tachiyomi

### Other details

Right now Tachiyomi uses phone's password to lock itself but it isn't much of a security when someone else also knows your phone's password (In my case, majority of people, who I know, knows my phone's password).

It would be great if we could use a custom password which will increase the privacy and security of the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No, we just use the standard biometrics library.
