### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nitt007** [tachiyomiorg/tachiyomi#7668]
### Steps to reproduce

Mangahub extension is keep on failing

### Expected behavior

The chapters should be able to open

### Actual behavior

The extension is not opening any chapters.
All the global updates are collapsing or skipping. 

### Crash logs

--------- beginning of main
08-01 13:10:12.017  4877  4896 E DatabaseUtils: Writing exception to parcel
08-01 13:10:12.017  4877  4896 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=13175, uid=1000 requires the provider be exported, or grantUriPermission()
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
08-01 13:10:12.017  4877  4896 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 10 (SDK 29)
Android build ID: qssi-user 10 QKQ1.190910.002 V11.0.22.0.QFQMIXM
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: laurel_sprout
Device model: Mi A3
Device product name: laurel_sprout

### Tachiyomi version

0.13.5

### Android version

Android 10

### Device

Xiomi MI A3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Nitt007** [comment]
What happened
