### ISSUE TITLE
Library Start Screen - Including Categories 

### ISSUE THREAD

**Issue by zaib404** [tachiyomiorg/tachiyomi#7670]
### Describe your suggested feature

If the start screen setting is selected to the library. Adding an option to choose which category to open up to instead the of last opened category.

Example - 
Three categories: Reading, Completed and Dropped.

Have the Dropped category open and close the app. Upon opening the app again it would open back to the last category selected (Dropped). 

With the category start screen if the Reading category is selected, then opening the app would open up the Reading category automatically.

### Other details

Useful for those that have many categories, but not so useful to those with few categories. 

Image example -

Selecting Category Start Screen shows a drop-down of their categories and last opened. Last opened being the default.
 
![Libarary Categories](https://user-images.githubusercontent.com/22369156/182169406-5007e7a1-e7e2-42f7-a0f4-5e67f9cd7f8d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Start screen has been removed in the preview and will also be so in the Stable version whenever that drops

**Comment by arkon** [comment]
Rejecting due to unneeded complexity with little value.
