### ISSUE TITLE
Extension not functioning 

### ISSUE THREAD

**Issue by Hakeen1-0** [tachiyomiorg/tachiyomi#7671]
### Steps to reproduce

Select extension 
Read Comics Online Extension loads and nothing comes up

### Expected behavior

Read Comics Online Extension should load preview

### Actual behavior

Extension did not load preview.
Read Comics Online Extension 

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Samsung A51

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
