### ISSUE TITLE
Tachiyomi Refreshing Library Stuck

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7675]
### Steps to reproduce

Open tachiyomi
Go to update
Click refresh
Stuck

Or

Automatic refreshing library
Stuck

### Expected behavior

Everything should be running normaly

### Actual behavior

Always stops in the middle of the process when doing manual/automatic library updates

- Using WiFi 

![IMG_20220802_193551](https://user-images.githubusercontent.com/50316075/182377324-6c59f933-ba77-42a3-b61c-e3561998f381.jpg)

![IMG_20220803_025906.jpg](https://user-images.githubusercontent.com/50316075/182462569-79f8a5b6-62ea-4b46-acb5-2eb3495c4e48.jpg)

![IMG_20220804_043848.jpg](https://user-images.githubusercontent.com/50316075/182717230-073f5076-08c6-421a-851c-87cf4a2d67c3.jpg)

- Using Cellular Data

![IMG_20220803_091704.jpg](https://user-images.githubusercontent.com/50316075/182509864-7e54b851-df61-42ae-840f-42d33ab05d1f.jpg)

![IMG_20220803_190851.jpg](https://user-images.githubusercontent.com/50316075/182604314-34120734-acb9-4ba3-ae23-4c95f0f3766e.jpg)

Estimated update is usually 30-45 minutes for all update and it's going to be downloaded

### Crash logs

--------- beginning of system
08-01 19:43:26.945  9235  9235 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 01:53:04.717 10910 10910 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 05:39:44.003  4965  4965 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
08-02 14:14:26.073  4965  5011 E FrameEvents: updateAcquireFence: Did not find frame.
08-02 14:14:26.105  4965 28722 E libEGL  : Invalid file path for libcolorx-loader.so
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-02 14:14:26.510  4965 28668 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
08-02 14:14:53.772  4965  5011 E FrameEvents: updateAcquireFence: Did not find frame.
08-02 14:19:27.490  4965  5011 E FrameEvents: updateAcquireFence: Did not find frame.
08-02 14:19:27.549  4965 31288 E libEGL  : Invalid file path for libcolorx-loader.so
08-02 14:24:20.308  4965  5011 E FrameEvents: updateAcquireFence: Did not find frame.
08-02 14:24:20.344  4965  1342 E libEGL  : Invalid file path for libcolorx-loader.so
08-02 14:24:20.365  4965  4965 E anade.tachiyom: Invalid ID 0x00000000.
08-02 14:51:10.732  4965  5231 E libEGL  : Invalid file path for libcolorx-loader.so
08-02 14:53:49.637  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44172533886, retransmittable_on_wire_deadline: 44172529734, difference: 4152us
08-02 14:54:21.206  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44204145567, retransmittable_on_wire_deadline: 44204144354, difference: 1213us
08-02 14:54:21.206  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44204146059, retransmittable_on_wire_deadline: 44204144354, difference: 1705us
08-02 14:54:21.207  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44204146303, retransmittable_on_wire_deadline: 44204144354, difference: 1949us
08-02 14:54:21.207  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44204146457, retransmittable_on_wire_deadline: 44204144354, difference: 2103us
08-02 14:54:21.207  4965  5124 E chromium: [ERROR:quic_ping_manager.cc(145)] QUIC retransmittable PING deadline is in past, now: 44204146570, retransmittable_on_wire_deadline: 44204144354, difference: 2216us
08-02 15:00:00.250 24679 24679 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 15:42:01.020 12244 12244 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 15:42:57.958 13509 13509 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 15:51:02.627 17439 17439 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 15:51:46.379 18944 18944 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 15:52:46.739 20790 20790 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 16:01:20.487 27947 27947 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 16:11:31.798  4607  4607 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 16:20:50.268 20803 20803 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 16:35:36.514 32501 32501 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 17:37:33.244 11331 11331 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 18:16:55.589 13339 13339 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 19:03:41.173 13586 13586 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
08-02 19:40:13.579 13586 13586 E anade.tachiyom: Invalid ID 0x00000000.
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.14
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Did you actually try checking some of the entries that it's getting stuck at? This can happen if the dependant sources are down.

**Comment by TheKingTermux** [comment]
I've checked it about 2/3x in a day plus 2 in auto update, and it's always stuck. For the extension I don't know because sometimes the extension is deleted or removed without notification

**Comment by arkon** [comment]
Expand the notification to see which entries are stuck and go and check them individually.

**Comment by TheKingTermux** [comment]
> Expand the notification to see which entries are stuck and go and check them individually.

Yup
I found it
It seem can't be opened in tachiyomi but i test with webview it can be opened normaly
Idk why

**Comment by arkon** [comment]
Report it in the extensions repo.

**Comment by TheKingTermux** [comment]
> Report it in the extensions repo.

Yes sure
