### ISSUE TITLE
Japscan don't work

### ISSUE THREAD

**Issue by Geenzao** [tachiyomiorg/tachiyomi#7677]
### Steps to reproduce

1. Download the extension Japscan in french
2. Try download chapters or read them

### Expected behavior

Normally I can read and dl chapters from this extension.

### Actual behavior

Currently, I can't read and dl from this extension. When I try to download, I have an infinite loading, as if to read.

### Tachiyomi version

13.5

### Android version

Android 11

### Device

Oppo Reno 4Z

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
