### ISSUE TITLE
tachiyomi not downloading manga

### ISSUE THREAD

**Issue by NoNameNash** [tachiyomiorg/tachiyomi#7678]
### Steps to reproduce

1. Turn on internet
2. Open tachiyomi
3. Tap on "browse" tab below
4. Go to "sources" tab
5. Tap on your favourite extension source
6. Tap on your favourite manga
7. Tap on the download button next to the latest manga chapter

### Expected behavior

When I tap on the download button next to the manga chapter it should start downloading after some time.

### Actual behavior

When I tap on the download button next to the manga chapter it does not download the manga. Even when I press the download button again and click on "start downloading now", it does not start downloading. Sometimes a red circle with a red exclamation mark inside the circle comes.

### Crash logs

--------- beginning of main
08-03 13:46:54.714 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.714 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:46:54.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: Failed to createFile
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/9B31-3996/ADM/God/Tachiyomi/downloads/Mangabat (EN)/Jujutsu Kaisen/readmangabat.com_Chapter 192_ Sakurajima Colony ②_tmp
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2409)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2392)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda5.call(R8$$SyntheticClass:8)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-03 13:47:08.906 21347 32349 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: Failed to createFile
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/9B31-3996/ADM/God/Tachiyomi/downloads/MangaDex (EN)/Furyou Taimashi Reina/Moe Panda Scans_Vol.5 Ch.53 - Exorcism #53 - Maze_tmp
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2409)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2392)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda5.call(R8$$SyntheticClass:8)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-03 13:47:08.920 21347 32350 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
08-03 13:47:12.558 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.559 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:12.560 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.052 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.052 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.052 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.052 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.052 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:17.053 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.767 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.767 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.768 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:28.769 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.715 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:31.716 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.334 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.335 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
08-03 13:47:33.335 21347 21347 E anade.tachiyom: Invalid ID 0x00000000.
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 12 (SDK 32)
Android build ID: SP2A.220305.013.A3
Device brand: POCO
Device manufacturer: Xiaomi
Device name: gram
Device model: POCO M2 Pro
Device product name: aosp_miatoll

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

POCO M2 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I'm using the stable one and the preview one here in Android 11 and download is working, normally when the icon become red like that is because one or more images from that chapter is unavailable or the tachiyomi couldn't read it, did you look in the download folder to see if something was downloaded? Did you try other sources Has well?

**Comment by NoNameNash** [comment]
Tried different sources. Tried toggling CBZ. Reinstalled the app. Checked downloads and nothing was downloading. Not even a folder was made for the downloading manga.

**Comment by curche** [comment]
> DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/9B31-3996/ADM/God/Tachiyomi/downloads/MangaDex (EN)/Furyou Taimashi Reina/Moe Panda Scans_Vol.5 Ch.53 - Exorcism #53 - Maze_tmp

Looks like you're on an sdcard
So maybe try changing Download folder location to locations in internal storage or sdcard?

**Comment by NoNameNash** [comment]
> > DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/9B31-3996/ADM/God/Tachiyomi/downloads/MangaDex (EN)/Furyou Taimashi Reina/Moe Panda Scans_Vol.5 Ch.53 - Exorcism #53 - Maze_tmp
> 
> Looks like you're on an sdcard So maybe try changing Download folder location to locations in internal storage or sdcard?

Ok. So switching to internal worked but I wanted it on sdcard. So I ejected the sdcard and inserted it back in and it worked. It downloaded a chapter.
