### ISSUE TITLE
Add a time tag for each backup item

### ISSUE THREAD

**Issue by Doddddd** [tachiyomiorg/tachiyomi#7682]
### Describe your suggested feature

Add a time tag for each backup item, highlight the items with updates when restoring, and users can manually choose which items to restore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Add details to #3136 if still interested.
