### ISSUE TITLE
Customized download

### ISSUE THREAD

**Issue by Mohzer0** [tachiyomiorg/tachiyomi#7684]
### Describe your suggested feature

There's no option to download a specific range of chapters
Let's say i want download from ch100 to 150 how i would so it ? Should i select every ch manually
So i suggest to add an option to select first ch and last ch and download in-between

### Other details

And it would be great to show chapters in small square grid instead of long list

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
> Let's say i want download from ch100 to 150 how i would so it ?

Long click chapter 100 and long click chapter 150. Congrats you have now selected a range of chapters

**Comment by curche** [comment]
For range select, you can just do as said above

For Grid view, refer https://github.com/tachiyomiorg/tachiyomi/issues/4389
