### ISSUE TITLE
Extensions Installation via Samsung Knox

### ISSUE THREAD

**Issue by icetick** [tachiyomiorg/tachiyomi#7687]
### Describe your suggested feature

There is a way some manufacturers allows us to install applications directly (without Package Manager popup etc)
I have found this thing in Epic Games application, on Samsung Galaxy Device. If you install games through it, they install silently. After some investigation and log checking, I found the needle. 
https://docs.samsungknox.com/dev/knox-sdk/faqs/installation/is-it-possible-to-install-an-app-silently-on-a-device-using-knox-sdk.htm
and 
https://docs.samsungknox.com/devref/knox-sdk/reference/com/samsung/android/knox/application/ApplicationPolicy.html#installApplication(java.lang.String)
I think this possibility can be useful for you, as extensions is massive part of application.
The only problem IMO is to get Knox SDK you need to register the app.
Thanks for attention! 

### Other details

https://docs.samsungknox.com/devref/knox-sdk/reference/com/samsung/android/knox/application/ApplicationPolicy.html#installApplication(java.lang.String)
https://docs.samsungknox.com/dev/knox-sdk/faqs/installation/is-it-possible-to-install-an-app-silently-on-a-device-using-knox-sdk.htm

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can just use Shizuku, which works with any OEM.
