### ISSUE TITLE
Discord Rich Presence Support

### ISSUE THREAD

**Issue by jeryjs** [tachiyomiorg/tachiyomi#7698]
### Describe your suggested feature

A Feature to show what manga the user is reading on their Discord status similar to how 'MAL-Sync' does it.
Something like this-
![image](https://user-images.githubusercontent.com/77010142/183276248-1cdd2041-3551-47ff-b3e6-9563b48e2057.png)

### Other details

For adding rich presence support, This Library can be used for reference
https://github.com/dead8309/KizzyRPC

It works perfectly and it also seems to be maintained regularly.
It'd also be great if there was an option to block the rich presence for specific Manga/Source... (maybe add such an option in the "Tracking" Menu in the manga's screen?)

Anyways, I'll be looking forward to seeing Rich presence support in Tachi in the future then!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Feels like feature bloat.

**Comment by jeryjs** [comment]
Ehhh~ But there will surely be a lot of user who'll appreciate this feature right...
_Sigh..._ I really wanted rich presence in tachi 😢

**Comment by AntsyLich** [comment]
> Ehhh~ But there will surely be a lot of user who'll appreciate this feature right...

Reading <insert-hentai-name> from <insert-hentai-source>

**Comment by jeryjs** [comment]
wdym by "Reading From"?

**Comment by TheGoldenSun** [comment]
I suppose you are right that this Rich presence support could benefit the change within the tachiyomi community however it is up to their decision if they are willing to take the next step with or without the rich presence support feature. 

Sent from miss moriarty  
 
  On Sun, Aug 7, 2022 at 12:33 PM, ***@***.***> wrote:   


wdym by "Reading From"?

**Comment by henrik9999** [comment]
Discord has no official way for rpc on Android this is using the account token basically making it a self bot which is against discord TOS btw and could get your account banned

**Comment by suhan-paradkar** [comment]
Well their reddit forum just confirned that using account token for JUST rpc won't be taken as going against their TOS...

https://www.reddit.com/r/discordapp/comments/833qn9/question_are_rpc_selfbots_allowed/

**Comment by jobobby04** [comment]
That was 4 years ago, I wouldnt trust a post that old
