### ISSUE TITLE
Tooltips of action bar menu icons are missing in Compose

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#7699]
### Steps to reproduce

Long press action bar menu icons.

### Expected behavior

A tooltip of the action name should appear.

### Actual behavior

Nothing happens.

### Tachiyomi version

r4739

### Android version

Not related

### Device

Not related

### Other details

Talkback reads some of the icons correctly (like "Update all" icon in Updates screen) but some others are broken (e.g. all 3 icons in the Library screen read "Search" in English instead of local language).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Noted lack of tooltips in #6951, but Compose doesn't support it out of the box at the moment.

Content descriptions fixed in 3c2e237d6
