### ISSUE TITLE
Downloaded chapter indicators missing

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi#7705]
### Steps to reproduce

Update App

### Expected behavior

see download indicators

### Actual behavior

no see download indicators

### Tachiyomi version

Tachiyomi Preview r4739

### Android version

Android 9 and 10 (LOS)

### Device

Mi9

### Other details

Screenshots from SY but it turned out that there is an error in the basis
All versions after 464 (SY) do not display chapter downloading. At first it will be displayed but after the restart it will disappear again
![2022-08-08 17-12-58](https://user-images.githubusercontent.com/35057681/183416103-94cce0af-2055-4e74-a8e3-562071ec566c.PNG)
![Screenshot_20220808-171439_TachiyomiSY_1](https://user-images.githubusercontent.com/35057681/183416304-fde02044-ae29-48f7-bceb-6200d32b2459.png)
![2022-08-08 17-15-29](https://user-images.githubusercontent.com/35057681/183416336-f8bc5c8f-c939-4d7d-a8e8-385676ee002c.PNG)
![2022-08-08 17-15-33](https://user-images.githubusercontent.com/35057681/183416344-3b70f2b8-9323-4ead-9498-dc62bc6ca221.PNG)
But it is possible to open for reading
![2022-08-08 17-15-48](https://user-images.githubusercontent.com/35057681/183416354-1cbed548-2b42-40ff-9cf7-a81b7d909e4a.PNG)
Also the manga disappears completely in "Download only"
![2022-08-08 17-20-29](https://user-images.githubusercontent.com/35057681/183416915-9998ac2a-e08c-4f71-a522-5ba053157ed6.PNG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mythos** [comment]
I do have the same issue with TachiyomiSY and they appear after keeping the app open for like 30+ minutes. It just became very slow unfortunately.

**Comment by semiya5** [comment]
Just in case it's helpful in identifying the cause, it seems that although it recognizes the download it's not reading them. Turning off data and wifi and trying to open a downloaded chapter auto-fails and returns "unable to resolve host"

**Comment by e-shl** [comment]
> not reading them

on the penultimate screenshot it showed that the downloaded ones were opening
