### ISSUE TITLE
Bottom Bar too large

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi#7707]
### Steps to reproduce

Select a series in updates tab

Or

Scroll to bottom of category

### Expected behavior

Should be a small bar

### Actual behavior

Selector bar is larger than normal, covering a series

Nav Bar is in the way, cutting off covers of bottom row of library

### Tachiyomi version

r4739

### Android version

Android 12

### Device

RedMagic 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have screenshots?

**Comment by ghostbear** [comment]
https://discord.com/channels/349436576037732353/566585518171881493/1006221519938129920
