### ISSUE TITLE
Changing list ordering also changes the scroll position of the list

### ISSUE THREAD

**Issue by zeluqa** [tachiyomiorg/tachiyomi#7710]
### Steps to reproduce

1. Pick a category with a long list
2. Change list ordering

### Expected behavior

If I'm at the top of the list, I should stay at the top of the list after changing the ordering method.

### Actual behavior

I'm scrolled to a certain position in the middle of the list.

### Tachiyomi version

Preview r4716

### Android version

Android 10

### Device

Xiaomi Pocophone F1

### Other details

I think it was trying to keep a focused manga to stay within view even after changing the ordering.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed by #7718
