### ISSUE TITLE
Alert users if the series they searched has blacklisted tags for NSFW sources.

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi#7723]
### Describe your suggested feature

On NSFW extensions, add a setting in settings that gets the tags users don't want and a setting in which what should Tachi do when these tags were found in search(block viewing of it or warn users)

### Other details

I know this is something like #5126 but some sources has tag blocking(or don't show those with these tags, idk the name of it).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The answer in #5126 still applies.
