### ISSUE TITLE
扩展插件buon dua无法下载内容

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi#7724]
### Steps to reproduce

1.打开tachiyomi
2.打开buon dua扩展插件
3.下载内容

### Expected behavior

应该开始下载内容

### Actual behavior

无法下载，显示红色叹号，无论删除重新下载或者重新启动都不行

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

vivo iQOO neo3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by 2936747557** [comment]
alessandrojean，你的那个我看了，无法解决

**Comment by alessandrojean** [comment]
You need to open an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) as this is an extension issue.

**Comment by 2936747557** [comment]
alessandrojean，抱歉我没看太懂，你的意思是不是我应该在tachiyomi扩展中提交问题，直接打开你评论里的扩展存储库是tachiyomi扩展的问题提交页面

**Comment by 2936747557** [comment]
我去这是什么情况，为什么我提交的评论和显示的不一样，提交后显示的怎么是这个，因为现在读起来可能会引起人的反感

**Comment by 2936747557** [comment]
alessandrojean，如果你看到我的评论希望不要引起你误会，不知道为什么显示的意思似乎有点问题
