### ISSUE TITLE
Recently added/deleted series

### ISSUE THREAD

**Issue by Dexroneum** [tachiyomiorg/tachiyomi#7727]
### Describe your suggested feature

Can you add to the History or Updates screens recent added/deleted series to/from the Library?

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #6124 for filtering history to non-library items. Updates is purely library content anyway.

Recently added is already a sort option in the library.
