### ISSUE TITLE
Point to installed manga location after reinstall

### ISSUE THREAD

**Issue by patmethny1** [tachiyomiorg/tachiyomi#7728]
### Describe your suggested feature

Problem: I switched my phone and reinstalled tachiyomi, which made all the mangas which i downloaded on my previous phone, show up as not downloaded even if it's downloaded in my sd card. Afaik there is no way to allow tachiyomi to detect these or make it so that I can point to the directory myself. I'm assuming this is also the case if I reinstall the app on the same phone as well.

Suggestions:
- Option in the drop down menu which says "find downloaded manga". If this feature is too niche, then it can be placed in "backup and restore" in the "more" section or settings. 
- possible implementation methods: point a single manga to its directory OR point to the entire tachiyomi folder which contained all the mangas and detect them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Just change the download location in **Settings → Downloads → Download location**.
