### ISSUE TITLE
Add goodreads.com as a tracker.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [tachiyomiorg/tachiyomi#7732]
### Describe your suggested feature

It supports more than manga, but additionally supports some manga that the currently present trackers do not, so I utilize Goodreads instead of them when I am able to. Consequently, I ask that you support it so that I may unify my tracking across my disparate reading-software.

I am thankful for any consideration.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
It will not happen as they have retired their API 

See #4023

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Does anyone know of any comparable websites that not solely track Asian literature, but international literature, too? (And whose API keys are available!)
