### ISSUE TITLE
Default category has no name in Settings

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#7733]
### Steps to reproduce

Go to Settings>Library>Global update and set to Default (Default + something else is better to notice it)

### Expected behavior

It should show "Default" I guess?

### Actual behavior

Nothing shows up, but there's still an item there. So it shows as nothing ", category_name".

### Tachiyomi version

r4739

### Android version

Android 10

### Device

Moto G7 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already fixed for next release.
