### ISSUE TITLE
Hide/Remove global search

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi#7736]
### Describe your suggested feature

Hey Iam just asking is there any option to remove tachiyomi app(global search) from direct share . Because it will helpful in when we hide app in Android.
In Android 12 there is no option to edit or remove direct share app, so iam just asking can you do something about global search option 
![Screenshot_2022-08-13-07-20-43-387_com google android youtube](https://user-images.githubusercontent.com/109901807/184464208-04e4a1a6-52d0-46f5-b5f8-212c94f71a96.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Nope.
