### ISSUE TITLE
Cant find the manga 

### ISSUE THREAD

**Issue by Venthinks** [tachiyomiorg/tachiyomi#7738]
### Steps to reproduce

> cant find the manga in extensions like asura scan etc.

> But when i go to search in on Google/webview there's on the site but i can find in tachiyomi

> cant find the manga on the similar site 

### Expected behavior

I expect that there is a manga that i search in Google/webview in tachiyomi extensions

### Actual behavior

What happen is the manga cant be find in the extensions in tachiyomi

### Tachiyomi version

0.13.5

### Android version

6.0.1

### Device

Samsung j2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
