### ISSUE TITLE
Chapter show mostly blank

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#7743]
### Steps to reproduce

Trying to view any chapter from Asura Scans.
![Screenshot_2022 08 14_04 17 05 744](https://user-images.githubusercontent.com/62863320/184507815-a4a407f0-138d-46a4-bd10-af468d022341.png)

### Expected behavior

It should show the pages

### Actual behavior

When trying to read any chapter the first page shows up perfectly fine while all the rest of the pages show up black even when downloaded.

### Tachiyomi version

13.5

### Android version

Android 12

### Device

Galaxy s22 Ultra, Galaxy s20 plus, and BlueStacks 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> - [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Please read more carefully

**Comment by kingtie** [comment]
> 

This was just Asura Scans now it's starting to happen to Flame scans, Reaper scans, and  Mangadex

**Comment by kingtie** [comment]
> > * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> 
> Please read more carefully

I'm also curious whether or not this is an extension issue seeing that it's also happening when chapters are downloaded

**Comment by TheKingTermux** [comment]
> This was just Asura Scans now it's starting to happen to Flame scans, Reaper scans, and  Mangadex

I think you should to read this

[*Asura Scans Issues*](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12969)

[*Flame Scans*](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12092#issuecomment-1148827855)

[*Reaper Scans*](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11902#issuecomment-1130010536)

[*MangaDex*](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12662#issuecomment-1191218194)

**Comment by kingtie** [comment]
> > This was just Asura Scans now it's starting to happen to Flame scans, Reaper scans, and  Mangadex
> 
> I think you should to read this
> 
> [_Asura Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12969)
> 
> [_Flame Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12092#issuecomment-1148827855)
> 
> [_Reaper Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11902#issuecomment-1130010536)
> 
> [_MangaDex Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12662#issuecomment-1191218194)

I don't really get what this is supposed to mean. Can you explain?

**Comment by kingtie** [comment]
> > This was just Asura Scans now it's starting to happen to Flame scans, Reaper scans, and  Mangadex
> 
> > I'm also curious whether or not this is an extension issue seeing that it's also happening when chapters are downloaded
> 
> I think you should to read this
> 
> [_Asura Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12969)
> 
> [_Flame Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12092#issuecomment-1148827855)
> 
> [_Reaper Scans Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11902#issuecomment-1130010536)
> 
> [_MangaDex Issues_](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12662#issuecomment-1191218194)

None of these issues apply to my issue because I'm still able to access the website through the app I'm also able to download the chapters and read said chapters and my files. I've just opened up a whole new one explaining further in detail

**Comment by TheKingTermux** [comment]
> I don't really get what this is supposed to mean. Can you explain?

For Asura Scans series have some error reported in relation to updating, here are the ones found:
"No Chapters found",
"HTTP error 404", and
"Too many follow-up requests: 21"
Idk how to fixed it

For Reaper Scans the site is down / broken, you just wait for the site back to normal or you can just migrate to the other extension 

For Flame Scans is the domain of extension not pointed to the actual domain, idk why this happening 

For MangaDex you can just uninstall the app and reinstall again

**Comment by kingtie** [comment]
> > I don't really get what this is supposed to mean. Can you explain?
> 
> For Asura Scans series have some error reported in relation to updating, here are the ones found: "No Chapters found", "HTTP error 404", and "Too many follow-up requests: 21" Idk how to fixed it
> 
> For Reaper Scans the site is down / broken, you just wait for the site back to normal or you can just migrate to the other extension
> 
> For Flame Scans is the domain of extension not pointed to the actual domain, idk why this happening
> 
> For MangaDex you can just uninstall the app and reinstall again

I'm actually able to access all four of those right now and they're working

**Comment by kingtie** [comment]
Unless it just went down

**Comment by TheKingTermux** [comment]
> Unless it just went down

Well actually you can open them via WebView, but you can't open them via tachiyomi extension, it might happen, due to several factors, for example by changing the domain, etc.

**Comment by kingtie** [comment]
> > Unless it just went down
> 
> Well actually you can open them via WebView, but you can't open them via tachiyomi extension, it might happen, due to several factors, for example by changing the domain, etc.
 
From my experience dealing with this for the last few days the extension still work, but even when downloaded they don't show up properly. Some of these I actually downloaded somewhere between 6 months ago and now so there's no reason for those downloads to to act like that if it was just an extension issue. I also just tried to view something from Manhua ES but I'm still getting the same issue of the pages showing up blank
