### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by Shirothori** [tachiyomiorg/tachiyomi#7745]
### Steps to reproduce

Everytime i click on any webtoon or manga from mangahub it closes itself and i get a notification look at the attachment
![Screenshot_20220813_214835_com huawei himovie overseas](https://user-images.githubusercontent.com/111200513/184508816-75b35a1a-d9f1-48af-8c2c-5bf6497a1d29.jpg)

### Expected behavior

To open normal

### Actual behavior

Doesnt open

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

Huawei p30 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Bman667** [comment]
![Screenshot_20220813-203120_Tachiyomi.jpg](https://user-images.githubusercontent.com/109476083/184515470-e1c60861-f5e2-4ab4-a190-28786eff9fc9.jpg)
Same here any solution
