### ISSUE TITLE
Disappearing sources

### ISSUE THREAD

**Issue by Bartek200219** [tachiyomiorg/tachiyomi#7746]
### Steps to reproduce

1. Backup tachiyomi folder.
2. Use root app(I used swift backup) to backup tachiyomi and sources
3. Factory reset your phone 
4. Restore tachiyomi folder, app and sources
5. Everything works fine till reboot 

### Expected behavior

Everything should work fine after teboot

### Actual behavior

Tachiyomi doesn't show sources after reboot, downloaded chapters dissapear and source changes to random numbers in every manga 

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Xiaomi 12 

### Other details

App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: cupid
Device model: 2201123G
Device product name: cupid

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #4313, probably.
