### ISSUE TITLE
Field 'data' missing

### ISSUE THREAD

**Issue by XYZ4114** [tachiyomiorg/tachiyomi#7748]
### Steps to reproduce

When I open my app and go to updates to read or download my unread chapters it says that your field data is required but it is missing.

### Expected behavior

Normally it would just let me read or download without any issue.

### Actual behavior

It starts giving me a message saying,"Field 'data' is required for type with serial name 'eu.kana.de.tachiyomi.multisrc.mangahub.GraphQLDataDto', but it was missing".

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

Samsang M31

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
