### ISSUE TITLE
Manhwas.net: error updating chapters, error extension

### ISSUE THREAD

**Issue by OliverSDL** [tachiyomiorg/tachiyomi#7749]
### Steps to reproduce

1. update any series 
2. go to page source

### Expected behavior

it should show me the updated/new chapters 

when I go to the source it should show me all the content it contains

### Actual behavior

It shows me the following message when I try to update some series: "java.lang.String.org.jsoup.nodes.Element.text()" 

when I go to the source it doesn't show me any content

### Crash logs

java.lang.String.org.jsoup.nodes.Element.text()

### Tachiyomi version

0.13.5

### Android version

11

### Device

Redmi k40 gaming

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
