### ISSUE TITLE
Emoji in download path causes downloads to fail when saving in Android formatted (exFAT) external storage

### ISSUE THREAD

**Issue by orariley70** [tachiyomiorg/tachiyomi#7753]
### Steps to reproduce

1. Open https://bato.to/series/82996/tonari-no-seki-no-hen-na-senpai
2. Download any chapter

### Expected behavior

Download should start and save correctly when finished.

### Actual behavior

Attempt to invoke virtual method 'com.hippo.unifile.UniFile[] com.hippo.unifile.UniFile.listFiles()' on a null object reference

### Crash logs

--------- beginning of main
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: Failed to createFile
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/DEAD-BEEF/Tachiyomi/Bato.to (ALL)/Tonari no Seki no Hen na Senpai~/Rainbow D 🌈🍆 Translations_Chapter 7_tmp
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$4bCvm1k9sPVDva8zreiBVl41-Jo(Downloader.kt:8)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda7.call(Unknown Source:4)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 13:13:50.651  2251  6157 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: Failed to createFile
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/DEAD-BEEF/Tachiyomi/Bato.to (ALL)/Tonari no Seki no Hen na Senpai~/Rainbow D 🌈🍆 Translations_Chapter 7_tmp
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$4bCvm1k9sPVDva8zreiBVl41-Jo(Downloader.kt:8)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda7.call(Unknown Source:4)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 13:13:51.996  2251  6157 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: Failed to createFile
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/DEAD-BEEF/Tachiyomi/Bato.to (ALL)/Tonari no Seki no Hen na Senpai~/Rainbow D 🌈🍆 Translations_Chapter 7_tmp
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$4bCvm1k9sPVDva8zreiBVl41-Jo(Downloader.kt:8)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda7.call(Unknown Source:4)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 13:13:52.604  2251  6157 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: Failed to createFile
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/DEAD-BEEF/Tachiyomi/Bato.to (ALL)/Tonari no Seki no Hen na Senpai~/Rainbow D 🌈🍆 Translations_Chapter 7_tmp
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:1)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:5)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$4bCvm1k9sPVDva8zreiBVl41-Jo(Downloader.kt:8)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda7.call(Unknown Source:4)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 13:13:52.871  2251  6157 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:920)
App version: 0.13.5-4765 (standard, 5f378e28b, 81, 2022-08-13T21:10Z)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.003
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SI
Device product name: vayu_global

### Tachiyomi version

r4765

### Android version

Android 12L

### Device

vayu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can not reproduce on an emulator (Android 11 x86).

Are you sure you properly formatted the storage in Android settings? Also how do you know the file system is exFAT?

According to [Wikipedia](https://en.wikipedia.org/wiki/ExFAT), exFAT does not have restrictions on emojis in filename.

The [`DEAD-BEEF`](https://en.wikipedia.org/wiki/0xDEADBEEF) path name in the crash logs looks suspicious. Did you point the download location to a wrong path, reformatted the storage, or didn't give permissions? Is it related to custom ROM?

**Comment by arkon** [comment]
Can't reproduce either.
