### ISSUE TITLE
[Feature Request] Google Drive for local sources

### ISSUE THREAD

**Issue by OupkarSandhu** [tachiyomiorg/tachiyomi#7761]
### Describe your suggested feature

Would be nice to be able to read from a cloud location like google drive rather than just internal storage for local comics/manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Google drive is not a local source.  You can possibly request a Google drive extension but that may have already been requested.  You can possibly also just use cubari and setup it like that.
