### ISSUE TITLE
New filter

### ISSUE THREAD

**Issue by Wabaya** [tachiyomiorg/tachiyomi#7763]
### Describe your suggested feature

Add a new filter to chapter like i won't read it sometimes i need a filter to cover some chapter and i don't want to cover all the read or downloaded or bookmarked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is an incoherent request.
