### ISSUE TITLE
Problem opening doujindesu

### ISSUE THREAD

**Issue by Wapoll** [tachiyomiorg/tachiyomi#7764]
### Steps to reproduce

212.32.226.234: NXDOMAIN

### Expected behavior

I hope this doesn't happen, actually this problem has been around for a long time and hopefully it will be resolved soon

### Actual behavior

instead I hope this problem is resolved quickly so that it can be better

### Crash logs

![Screenshot_20220815-115533_Tachiyomi](https://user-images.githubusercontent.com/111265199/184580455-af5d7d8c-1add-4dcb-95b1-db5bc2004b0f.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 8

### Device

Samsung Galaxy J7 prime

### Other details

I hope that this problem/bug gets resolved quickly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
