### ISSUE TITLE
The download queue pauses automatically (下载队列会自动停止)

### ISSUE THREAD

**Issue by LittleYang0531** [tachiyomiorg/tachiyomi#7765]
### Steps to reproduce

1. Add several hundreds of chapters to the download queue
2. When downloaded dozens of chapters, it was paused automatically

Chinese Version: 
1. 在下载队列里添加很多很多章节的漫画
2. 当下载了一定数量的漫画时，下载队列会自动停止

### Expected behavior

It should download all chapters without any pause.

下载队列应该一次性下载完毕

### Actual behavior

The download queue was paused after download several dozens of chapters

下载队列在下载完一定数量的漫画后直接后自动停止了

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Xiaomi 10 Lite Zoom

### Other details

English is not my native language; please excuse typing errors.

英语并不是我的口语，请原谅我的语法错误

I may not find that there exists the same question because my poor English. If there exists, please reply me where it is, thanks!

由于我的英语水平有限，可能这里存在一个与我的问题相似的 issue 然而我却未能够发现。如果真的存在，请指出这个 issue 在哪里，谢谢!### 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The download queue has various issues that'd be addressed with a larger overhaul.

Closing in favour of #7492
