### ISSUE TITLE
problem opening sekte komik

### ISSUE THREAD

**Issue by Pengamen1kaos** [tachiyomiorg/tachiyomi#7766]
### Steps to reproduce

No comen

### Expected behavior

No comen

### Actual behavior

No comen

### Crash logs

No comen

### Tachiyomi version

0.13.5

### Android version

Android 10

### Device

Samsung s9 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also already reported
