### ISSUE TITLE
Sort by chapter number 

### ISSUE THREAD

**Issue by OshidaBCF** [tachiyomiorg/tachiyomi#7767]
### Describe your suggested feature

I wish to be able to sort manga's by chapter count, because i'm a bit sad to only find manga's with 3 chapter.

Caution : i do not know if this can be done on the app side, or if it's the manga website (mangadex in my case) that need to do it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
If you're talking about in your library, then it already exists.  If you're talking about an extension then the website has to have that sort, if it can sort by total chapters and it doesn't exist in the extension, then you can request it in extension repo.

**Comment by OshidaBCF** [comment]
I see.
I'll check later
