### ISSUE TITLE
Expand search to include chapters

### ISSUE THREAD

**Issue by Kruchji** [tachiyomiorg/tachiyomi#7769]
### Describe your suggested feature

When using search in library it currently only searches through manga titles. Would it be possible to extend this feature to search also for chapters (locally)? Or at least add another search inside a manga page (like the filter/sort menu) just for chapters?

### Other details

I read xkcd through Tachiyomi and when I want to find a specific chapter by name I have to scroll through 2657 chapters which is not very practical 😄.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It'd be pretty excessive to search all chapters from the library. #7925 seems more appropriate.
