### ISSUE TITLE
Lateral Shift in images post Auto Split Tall Images

### ISSUE THREAD

**Issue by sushantjsr13** [tachiyomiorg/tachiyomi#7771]
### Steps to reproduce

Goto Settings > Downloads > Auto Split Tall Images and enable it

### Expected behavior

Shouldn't be any lateral shift in split images.

### Actual behavior

Lateral shift in images post Auto Split of tall images.

Example 1:
![Screenshot_2022-08-16-09-11-58-563_eu kanade tachiyomi](https://user-images.githubusercontent.com/33841353/184793425-6aeb51d0-8f76-44b9-b055-408e22f9e5eb.jpg)

Example 2:
![Screenshot_2022-08-16-09-11-28-452_eu kanade tachiyomi](https://user-images.githubusercontent.com/33841353/184793446-4a8c6c4a-c11a-426f-8e4a-01f988c3a974.jpg)

### Crash logs

No Crash 

### Tachiyomi version

0.13.6

### Android version

Android 11 RKQ1.200826.002 on MIUI 12.5.1.0

### Device

Xiaomi Redmi K20 Pro

### Other details

Got this issue while reading [Ch 097 of The Max Level Hero Has Returned ](https://www.mangahere.cc/manga/the_max_level_hero_has_returned/) with auto split tall images enabled. There is a lateral shift in the split image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Turn off crop borders

**Comment by sushantjsr13** [comment]
Thanks it works!
