### ISSUE TITLE
Request for readers

### ISSUE THREAD

**Issue by Ronaldiko** [tachiyomiorg/tachiyomi#7772]
### Describe your suggested feature

Remove the limit for reading...

### Other details

Request from remove the limit readings...

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Ronaldiko** [comment]
reader have request this issue...

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
