### ISSUE TITLE
High battery usage on app update notification

### ISSUE THREAD

**Issue by AlexisTM** [tachiyomiorg/tachiyomi#7773]
### Steps to reproduce

- Have an old version of tachiyomi (I believe I had 0.13.5)
- Click on the notification "A new update is available"

### Expected behavior

A new notification appears and downloads the new version

### Actual behavior

A new notification appears and downloads the new version, but for every progress, it looked like replaced by a new notification (at an alarming rate).

Right after that and until a manual reboot, the phone battery usage was extremely high. (90 to 15% in 4h with screen of, but I usually end up with 50% at the end of the day)

After a reboot, everything went back to normal. It is possible not to be a bug with the update but that was the only out of the usual thing that happened.

### Tachiyomi version

0.13.5

### Android version

Android 11

### Device

Xiaomi Mi A3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably the same issue as https://github.com/tachiyomiorg/tachiyomi/issues/9377#issuecomment-1518747191
