### ISSUE TITLE
When updated tachiyomi0.13.6 haomanwu(好漫屋) can't load pages

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi#7774]
### Steps to reproduce

updated tachiyomi0.13.6
open haomanwu(好漫屋),find a manga and read a chapter

### Expected behavior

load pages in old version tachiyomi0.13.1
![-49e3f3fef7591851](https://user-images.githubusercontent.com/97005405/184867186-2ad4acc3-c56b-4833-8a6d-8fb9c45d7575.jpg)
![797852ee8df04272](https://user-images.githubusercontent.com/97005405/184867200-67bef77e-548c-49f5-8574-4663cd559649.jpg)

### Actual behavior

not found pages(没有找到界面)
![Screenshot_2022-08-16-19-07-40-585_eu kanade tachiyomi](https://user-images.githubusercontent.com/97005405/184867437-785209e3-0640-42b2-bba9-ee6f572c16f2.jpg)
![Screenshot_2022-08-16-19-20-00-665_eu kanade tachiyomi](https://user-images.githubusercontent.com/97005405/184867548-785e441c-0d8c-4641-b040-6f7b5061dead.jpg)

### Tachiyomi version

0.13.6 & 0.13.1

### Android version

Android 11 & Android 9

### Device

MI pad5 pro & MI 9

### Other details

Maybe this is tachiyomi's new bug

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by stevenyomi** [comment]
Can't reproduce here. Please make sure you have updated the extension to its latest version (v1.3.6) on your tablet and check if you have a valid User Agent string in **Settings → Advanced → Default user agent string**.

无法复现。请检查平板上的插件是否是最新版本（v1.3.6），并且检查 **设置 → 高级 → Default user agent string** 中的 UA 是否被更改过。
