### ISSUE TITLE
happymh 嗨皮漫画 captch cant load after tried many times after new update 0.13.6

### ISSUE THREAD

**Issue by junyaotan020517** [tachiyomiorg/tachiyomi#7775]
### Steps to reproduce

when I use captcha on tachi WebView the captcha cant pass me, but if I use it on google it can pass me the captcha, so I think maybe is the extension or software problem?

### Expected behavior

when i use it previously the captcha can pass on the previous version tachi. 

### Actual behavior

captcha keep load

### Tachiyomi version

0.13.6

### Android version

emui 12

### Device

huawei nova 5t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by junyaotan020517** [comment]
> > If this is an issue with an extension, I should be opening an issue in the extensions repository.

oo sorry open request on wrong places
