### ISSUE TITLE
Old toggle buttons

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#7776]
### Describe your suggested feature

Can we go back to the old smaller toggle buttons?The new ones look huge and when turned off they look less greyed out and more just blurry? Plus with everything else looking so much more sharp and uniform they stand out far too much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We're just using the Material Design 3 library, so no.
