### ISSUE TITLE
Space between pages on/off switch 

### ISSUE THREAD

**Issue by MrMistBear** [tachiyomiorg/tachiyomi#7777]
### Describe your suggested feature

Add an option to remove the space between pages as some drawings or word bubbles don't get connected. 
Maybe be able to choose which read to have it rather than for all of them. This applies to mainly for vertical reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
use webtoon reading mode
