### ISSUE TITLE
Automatic update updates excluded categories

### ISSUE THREAD

**Issue by Maxkun13** [tachiyomiorg/tachiyomi#7784]
### Steps to reproduce

Tachiyomi runs it's daily update under two conditions: On Wifi and charging.
I have all my saved works in an 'All' category for easier searching, and every work is at least in another category. Main reason I realized something was wrong: myreadingmanga has a probkem with the cloudflare I cannot pass even through the means provided by tachiyomi and so I had 183 failed updates. At least 80% of the myreadingmanga works are also in categories excluded from the automatic update.

### Expected behavior

Tachiyomi is supposed to not update manga that are in excluded categories, even if they are in included categories.

### Actual behavior

I think it pretty much updates my whole library that is not marked as complete, since myreadingmanga tends to have most works tagges an unknown (even doujinshi) and it is not supposed to do that.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung Galaxy S21 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed in preview already.
