### ISSUE TITLE
Library screen UI glitches

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#7786]
### Steps to reproduce

https://discord.com/channels/349436576037732353/364330965444853761/1009248802470908056

### Expected behavior

No glitches

### Actual behavior

- From the Library screen, trigger the ChangeCategoryDialog and tap "Edit". The bottom navigation bar pops up and covers the FAB. #7788
- The hairline below the tabs is too short, only covering the tabs' width. #7789
- Newly created categories does not keep sync with the display mode until you change it manually. #7790
- On clearing the library, the emoji refreshes crazily. #7791
- When the library is empty, you can't switch categories. I guess the tab bar should be hidden. #7792

### Crash logs

Not related

### Tachiyomi version

r4799

### Android version

12

### Device

Not related

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Please make separate issues for each issue and include steps to reproduce as the video is confusing and all over the place

**Comment by stevenyomi** [comment]
> Please make separate issues for each issue and include steps to reproduce as the video is confusing and all over the place

I think my description in "Actual behavior" is clear enough but I can do it if you don't mind flooding the Issues section.

**Comment by ghostbear** [comment]
Please flood the issues as it will be easier to track and mark as fixed
