### ISSUE TITLE
Add music to manga 

### ISSUE THREAD

**Issue by Wabaya** [tachiyomiorg/tachiyomi#7787]
### Describe your suggested feature

I would like to choose a music just from inside the app from the music in my phone 

### Other details

Maybe the other users can suggest some music for the chapter 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
We might as well be adding a weather forecasts into the app
