### ISSUE TITLE
Library's category tabs' bottom border line is too short

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#7789]
### Steps to reproduce

Have 2~3 categories.

### Expected behavior

The hairline below the Library's category tabs should span the whole width of the screen.

### Actual behavior

The hairline below the tabs is too short, only covering the tabs' width.

### Tachiyomi version

r4799

### Android version

12

### Device

Not related

### Other details

Extracted from #7786. Compiled video of multiple issues: https://discord.com/channels/349436576037732353/364330965444853761/1009248802470908056

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Upstream issue

**Comment by stevenyomi** [comment]
https://issuetracker.google.com/issues/242879624
