### ISSUE TITLE
Local source infinite loading

### ISSUE THREAD

**Issue by baraa272** [tachiyomiorg/tachiyomi#7793]
### Steps to reproduce

Infinite loading at local source screen 

### Expected behavior

Local source working normally 

### Actual behavior

Infinite loading 

### Crash logs

--------- beginning of main
08-17 21:26:24.293 21956 21956 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: Settings request failed.
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/127.0.0.1:443
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:18)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
08-17 21:26:24.643 21956 24755 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:920)
08-17 21:26:25.418 21956 24805 E SQLiteLog: (284) automatic index on C(manga_id)
08-17 21:26:25.418 21956 24805 E SQLiteLog: (284) automatic index on R(manga_id)
08-17 21:26:25.418 21956 24805 E SQLiteLog: (284) automatic index on C(merge_id)
08-17 21:26:25.418 21956 24805 E SQLiteLog: (284) automatic index on R(merge_id)
08-17 21:26:25.418 21956 24805 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.8.5 (standard, 7ef429176, 38, 2022-08-14T22:33Z)
Preview build: 474
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.004
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

### Tachiyomi version

Preview r474

### Android version

Android 12

### Device

Vayu Poco X3 Pro

### Other details

![Screenshot_20220817-181344_Permission controller](https://user-images.githubusercontent.com/32843097/185215486-ebc0a4d0-867e-4dac-b4d4-2792100809c7.png)
![Screenshot_20220817-140914_TachiyomiSY](https://user-images.githubusercontent.com/32843097/185215490-313119d1-bc2e-4ab6-8784-c6afeadc31bc.png)
![Screenshot_20220817-170819_MiXplorer](https://user-images.githubusercontent.com/32843097/185215491-9b0cf7d8-c25b-449d-a4e2-d395127fa498.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does this happen in the main app? We don't have the feed from SY.

**Comment by baraa272** [comment]
Just a second

**Comment by baraa272** [comment]
![Screenshot_20220817-220348_Tachiyomi](https://user-images.githubusercontent.com/32843097/185221941-8e0c900b-a23f-4c7e-b54d-5eeb2aaeb669.png)

**Comment by baraa272** [comment]
Seems like it's working

**Comment by arkon** [comment]
Open an issue in the SY repo then.

**Comment by baraa272** [comment]
Ok
