### ISSUE TITLE
[Feature Request] Migrate > Source > Select All Manga To Delete

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#7795]
### Describe your suggested feature

**Situation**
- Go to `Browse` > `Migrate` > Selected a `Source`
- You can see all the series added from that source.

**Currently**
- You cannot select all and have to manually the series one by one to remove them or migrate them.

**Suggestion**
- If you don't want to migrate any of the series. Add `Select All` with option to remove them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#1729
