### ISSUE TITLE
Ability to restrict/pause/skip a title from updating

### ISSUE THREAD

**Issue by SxMShaDoW** [tachiyomiorg/tachiyomi#7796]
### Describe your suggested feature

As a reader, I would like to prevent a title from updating its chapters until a given specific date, so that I can save bandwidth and reduce the number of errors from the app.

As you may know, authors take breaks from time to time when "seasons" end. This puts scanners in a weird state where the chapter is still on-going, but it is on pause. Authors normally release a .5 chapter describing how long they will be on break for. It would be great if we had an option to pause updates on a given title until a specific time. Ideally there would be a standard way for scanners or extensions to handle pauses, but I feel that would be too hard on the extensions to manage. I believe this would align well with the current "don't update if there are unread chapters or it hasn't been started" features.

Benefits:
- Reduce network calls on the user
- Reduce the strain on scanners websites
- Reduce the number of errors reported back due to 404/201, etc

### Other details

If this was implemented it could be in the "3 dots" menu next to edit categories or migrate.

Current workaround:
- Put chapters into their own category and don't refresh that category often

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Probably related: #5488, #5734

**Comment by SxMShaDoW** [comment]
Sorry that I didn't find those PRs (I was only searching issues). 

Thanks for linking them! I agree they are similar to those 2 PRs! I believe those PRs are actually larger and potentially adequate ways to solve it.
