### ISSUE TITLE
The Image couldn't be loaded (koushoku)

### ISSUE THREAD

**Issue by DekuBlank** [tachiyomiorg/tachiyomi#7801]
### Steps to reproduce

It's become more problems after update.
1. The Image couldn't be loaded
2. Can't download

### Expected behavior

Koushoku can use like before..

### Actual behavior

After update it's become more problem.. 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Rog 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
