### ISSUE TITLE
App loads only 1st page of chapter

### ISSUE THREAD

**Issue by PrplYoru** [tachiyomiorg/tachiyomi#7804]
### Steps to reproduce

Read any chapter of any manga from MangaKatana

### Expected behavior

It should load all the pages of the chapter I'm currently reading

### Actual behavior

It loads only the first page of every chapter

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Xiaomi Mi 10T

### Other details

Couldn't verify with other sources since most of them don't work for me.
This error started occuring today, it worked fine until yesterday.
![Screenshot_2022-08-19-03-47-18-414_eu kanade tachiyomi](https://user-images.githubusercontent.com/92819547/185526499-76edafb4-7b26-4528-a2b9-cba482dc1bdb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

...
