### ISSUE TITLE
[ Feature Request ] Series Default Filter and Sort Settings

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#7806]
### Describe your suggested feature

Whenever I added a new series to my `Library`. I have to manually set the following
- Filter = Unread
- Sort = By chapter number on Ascending Order

Would it be possible to add on `Setting` that will allow users to set a default Series `Filter` and `Sort` setup?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Already exists, you can set it in the same menu

**Comment by 8227846265** [comment]
Oh, you're correct. I have missed it. Thanks for pointing it out.

**Comment by 8227846265** [comment]
@Seishirou101 - I can only see the Library Default Filter and Sort settings.

There's no Default Series Filter and Sort settings.

**Comment by 8227846265** [comment]
Ah nvm. I found it. Thanks :)
