### ISSUE TITLE
How do I remove the page between two chapters which shows the chapter is finished

### ISSUE THREAD

**Issue by RenegadeEmperor** [tachiyomiorg/tachiyomi#7807]
### Steps to reproduce

![Screenshot_2022-08-19-09-47-47-228_eu kanade tachiyomi](https://user-images.githubusercontent.com/69721364/185544724-6129591a-f972-4444-b3be-b20452463f2b.jpg)

### Expected behavior

Na

### Actual behavior

Na

### Tachiyomi version

13.6

### Android version

Android 12

### Device

Poco X3pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
turn off chapter transitions in the settings.
