### ISSUE TITLE
Mangakatana extension issue

### ISSUE THREAD

**Issue by ramaratus** [tachiyomiorg/tachiyomi#7808]
### Steps to reproduce

Read any chapter from Mangakatana source

### Expected behavior

chapter load pages properly, eg. chapter 1 consist 14 pages, and it loads all of them in the reader

### Actual behavior

Only load page 1 and only one page. So all manga chapters from mangakatana source only have 1 page

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
This is not tachiyomi issue but a extension issue and have already been open in here https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13062
