### ISSUE TITLE
API rate limit excessed

### ISSUE THREAD

**Issue by TheeGray** [tachiyomiorg/tachiyomi#7810]
### Steps to reproduce

I read a few chapters of different comics(maybe 8-9 chapters) and then it just keeps kicking me out when I try to open a new chapter and it says API rate limit excessed. It stays that way for like half an hour then I can read 8-9 new chapters then it does the same thing.
Plss help.

### Expected behavior

It should open a chapter.

### Actual behavior

Instead it doesn't and show this message "API rate limit excessed".

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Galaxy S20+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by Lyonie** [comment]
Mangahub having this issue as well

**Comment by Lyonie** [comment]
Clearing caches & cookies in setting solve the problem but after a few chapters, API rate limit excessed happen again

**Comment by arkon** [comment]
Not sure how you still think this is the right place to post.
