### ISSUE TITLE
MangaScreen: restore old behavior of SwipeRefreshIndicator

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#7813]
### Describe your suggested feature

Make SwipeRefreshIndicator start from top of the screen instead of below the app bar.

This is an upstream issue as we cannot adjust the scroll offset multiplier (not reported yet).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Upstream: https://android-review.googlesource.com/c/platform/frameworks/support/+/2193512

**Comment by ivaniskandar** [comment]
> Upstream: https://android-review.googlesource.com/c/platform/frameworks/support/+/2193512

Not related as currently accompanist's swiperefresh is used

**Comment by stevenyomi** [comment]
> Not related as currently accompanist's swiperefresh is used

As it is being rewritten, there's no need to report in the Accompanist repo. Just wait for the upstreamed version and see if it's implemented. If not, we need to report in the Android tracker.

**Comment by stevenyomi** [comment]
> Just wait for the upstreamed version and see if it's implemented.

Turns out it's not. We'll probably need to customize our own.

**Comment by stevenyomi** [comment]
Looks like they are [considering](https://android.googlesource.com/platform/frameworks/support/+/a992a02c5530854ada64323c839d9e1c5de7b135/compose/material/material/src/commonMain/kotlin/androidx/compose/material/pullrefresh/PullRefreshIndicator.kt#70) enabling people to use the default indicator by accepting custom state. This issue can be fixed after that.
