### ISSUE TITLE
Make rateLimit and rateLimitHost not limit cached responses

### ISSUE THREAD

**Issue by vetleledaal** [tachiyomiorg/tachiyomi#7817]
### Describe your suggested feature

According to the first figure in [OkHttp's documentation](https://square.github.io/okhttp/features/interceptors/), the current rate limiting interceptors will also rate limit cached results. These should be made into network interceptors to not needlessly delay fetching from cache.

### Other details

Consider ignoring rate limits for redirects (301, 302, 307, 308) and partial network responses (304), this will likely require rewriting the interceptors to look at responses, and rate limit the subsequent requests instead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
No need to worry about 3xx responses as they would be processed by an intercepter after the rate limiter unless you disabled following redirects in the client.

**Comment by vetleledaal** [comment]
You're thinking of application interceptors, which don't have to deal with 3xx resonses. Docs say:

> Network Interceptors
> - Able to operate on intermediate responses like redirects and retries.

**Comment by stevenyomi** [comment]
I don't know what you mean but redirect responses are transparent to the rate limiter normally. It will not pass through the rate limiter at all.

Ref: https://github.com/square/okhttp/blob/69ae7f3e10dae0554f3181edaa52bcd77ee448ab/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealCall.kt#L180-L190

**Comment by stevenyomi** [comment]
I think you might have mistaken `RateLimitInterceptor` as a network interceptor. It is not.

https://github.com/tachiyomiorg/tachiyomi/blob/3760b310df8701f929d4ca4acbe7facfa97a2220/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/RateLimitInterceptor.kt#L24-L28

**Comment by vetleledaal** [comment]
I'm aware, and mentioned this in the original issue:
> These should be made into network interceptors to not needlessly delay fetching from cache.

In any case, there are multiple ways to achieve this, and it's not exclusively through network intercetors

**Comment by stevenyomi** [comment]
I see. Both means require removing from the queue. As a normal interceptor, requests with completely cached responses should be removed. As a network interceptor, we won't get requests with cached responses but need to remove requests that have subsequent retries.

**Comment by stevenyomi** [comment]
I believe this would need a second lock in the code. I doubt if this is worth it since sites may have bad cache control settings.

**Comment by stevenyomi** [comment]
> I believe this would need a second lock in the code. I doubt if this is worth it since sites may have bad cache control settings.

Currently the logic is:
```kotlin
synchronized(queue) {
    Thread.sleep(remainingTime)
    addToQueue()
}

val response = chain.proceed(chain.request())

return response
```

To achieve "removing cached requests from queue", a second lock is needed:
```kotlin
synchronized(interceptorInstance) {
    synchronized(queue) {
        while (needToWait) {
            queue.wait(remainingTime)
        }
        addToQueue()
    }
}

val response = chain.proceed(chain.request())

if (response.isFromCache) {
    synchronized(queue) {
        removeFromQueue()
        queue.notify()
    }
}
```
