### ISSUE TITLE
1 page per chapter

### ISSUE THREAD

**Issue by raith7062** [tachiyomiorg/tachiyomi#7819]
### Steps to reproduce

I'm not really sure what caused it in the first place, I went off of the app temporarily and suddenly I couldn't read any of the chapters, tachiyomi was simply acting like there was only 1 page to the chapter, and that was usually the cover of said page.

One thing I did notice was that before this happened was that some pages would simply refuse to show up as well, which was annoying, but now I straight up cannot use the app.

I tried clearing cookies, cache, deleting and reinstalling tachiyomi, I'm lost on what I should do

### Expected behavior

I should be able to read the chapter as per normal

### Actual behavior

Instead I'm stuck looking at the first page, which is usually the cover page

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Galaxy A 11

### Other details

This happened 2 days ago now, and it's been bugging me since I got no idea how it started in the first place.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
