### ISSUE TITLE
Allporncomics filter issue

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi#7827]
### Steps to reproduce

1. Go to extensions
2. Open the allporncomics extension
3. Click on filters 
4.  Use a genre

### Expected behavior

When a genre is used it should show all the entries available that match it

### Actual behavior

When the genre is used it will only return 20 entries, even if there are more matches to this genre 

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Umidigi A9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
