### ISSUE TITLE
Tachiyomi preview can't download chapters from Hiperdex 

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi#7830]
### Steps to reproduce

Note: This is a preview app issue, not extension. Stable, the extension and the website all work ok

1. Open Hiperdex
2. Open Ren arisugawa webtoon 
3. Download any chapter

### Expected behavior

chapter should download, as it does on Stable 0.13.6

### Actual behavior

chapter doesn't download, it says No Pages found

### Tachiyomi version

r4821

### Android version

Android 12

### Device

Galaxy A72

### Other details

Downloads normally on Tachiyomi Stable 0.13.6 without issue

state of chapter didn't matter, whether bookmarked, read or unread 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce. Try refreshing the entry first.
