### ISSUE TITLE
Confirmation before removing a title from library

### ISSUE THREAD

**Issue by R3migz** [tachiyomiorg/tachiyomi#7831]
### Describe your suggested feature

I use "sort by date added" to organize my library, and it's kinda annoying that one missclick can ruin everything xD, it happens to me a lot, so i would be grateful if you add a confirmation message before removing titles from library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If you're in the manga details screen, you can still easily re-tap it to add it back. If you removed it from the library screen, you had to have had explicitly checked it.

This seems a bit unnecessary.
