### ISSUE TITLE
Chapter list not refreshing properly in Tachiyomi Preview r4821

### ISSUE THREAD

**Issue by raziel100** [tachiyomiorg/tachiyomi#7834]
### Steps to reproduce

1. choose any Manga that you have read previously and have a update
2. Pull down in Manga page to update the chapter list to get the new chapter to show in it. 
3. Get back to Manga list before it have been visually updated

### Expected behavior

Even if you return to Manga list the new chapter that have been updated will show up afterwards. 

### Actual behavior

The new chapter will not show up even after 30min after, will show up only if you pull down to update and wait until you see the new chapter in the list. 

### Tachiyomi version

Tachiyomi Preview r4821

### Android version

Android 11

### Device

Samsung a02

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
https://user-images.githubusercontent.com/11368528/185777036-46d12d26-b35e-4e8c-b2fe-4d651279a29f.mp4

I have recorded a video showing the bug

**Comment by arkon** [comment]
Can't seem to reproduce this.
