### ISSUE TITLE
Multiple Backup Location

### ISSUE THREAD

**Issue by qxb3** [tachiyomiorg/tachiyomi#7835]
### Describe your suggested feature

The automatic backup should have an option to add multiple backup locations. So we can have one backup on both default storage and sdcard

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Multiple locations would be impossible if we update to a newer SDK level and have to abide by newer storage permissioning rules anyway, so this has to be rejected.
