### ISSUE TITLE
No chapter found in Asura scans

### ISSUE THREAD

**Issue by UNKNONYM0US** [tachiyomiorg/tachiyomi#7838]
### Steps to reproduce

Refresh your library or the comic it self

### Expected behavior

It will show new chapter

### Actual behavior

A pop up that says no chapter found, but when I open it on web view, I can see new chapters

### Tachiyomi version

0.13.6

### Android version

11

### Device

CPH2059

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not even the right repo.
