### ISSUE TITLE
Low download

### ISSUE THREAD

**Issue by DamianTC1903** [tachiyomiorg/tachiyomi#7839]
### Steps to reproduce

To download 

### Expected behavior

The download of chapters is very slow, what is the reason? I have excellent internet quality.

### Actual behavior

The download of chapters is very slow, what is the reason? I have excellent internet quality.
Last versión.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Redmi note 9s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
All sources are rate limited so as to not put too much burden on sources and make them mad at us

**Comment by DamianTC1903** [comment]
Thank you so much, I hadn't thought of that.
