### ISSUE TITLE
nhentai Cloudflare bypass not working

### ISSUE THREAD

**Issue by Dev-Sayyan** [tachiyomiorg/tachiyomi#7840]
### Steps to reproduce

When opening nhentai extension, after loading for sometime it shows unable to bypass cloudflare

Uploading screen-20220822-111255.mp4…

### Expected behavior

Nhentai should open like any other extension

### Actual behavior

Unable to bypass cloudflare

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Nothing Phone (1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Architect-Ivy** [comment]
Same problem, some of my friends says they open nhen (unable to bypass cloudfare) and same problem goes for me as well

**Comment by Dev-Sayyan** [comment]
Yea

**Comment by jitgho** [comment]
Same man...devs plz fix this

**Comment by jitgho** [comment]
Same bruh....devs plz fix this asap

**Comment by vetleledaal** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
