### ISSUE TITLE
Exsplore / Sources bug?

### ISSUE THREAD

**Issue by GBThor92** [tachiyomiorg/tachiyomi#7842]
### Steps to reproduce

*note! Not good at writing so there might be bad writing here and there*

For a while now whenever I look up names of certain series, no matter what series, even super common one like if I looked up "One Piece" I only seems to get no result.

Normally I would be getting all kind of results from different extensions.
I don't have a date of when this started happening, but I think it started when the last update to the app happened.

I can still kind of look up certain series, but I have to go into the part of the extensions to then look up the name.

I also get the same result when I try to migrate series.

I also sometimes have small moments where the app freeze and then get a window showing me "close the app or wait" and well if I press close then the app will close, but pressing wait does not realy do anything cause as I am reading the page will stop turning / scroll down and then about 1 min later the box appear and when pushing wait the app will continue to work as it was before it froze.

Is anyone else having a similar issue?

### Expected behavior

solve my issue i guess

### Actual behavior

Whatever i serch I keep getting no result when I look for series

### Crash logs

No crashin happens

### Tachiyomi version

newest

### Android version

not sure

### Device

S22 Ultra

### Other details

no i guess?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
Well, I can't reproduce this, I have a lot of sources here and have try search one piece like you did 
and I could find just fine, and about the freezing, is happening for some time now, there a some issue opened here because of that, #7240
And the Android version you can always find in information in your phone  configuration

**Comment by alessandrojean** [comment]
Please do actually fill the information requested...

"latest" and "not sure" are NOT valid numeric answers.

**Comment by raziel100** [comment]
> Please do actually fill the information requested...
> 
> "latest" and "not sure" are NOT valid numeric answers.

And "Expected behavior"  be "solve my issue i guess" is not a useful information as well

**Comment by arkon** [comment]
Ask in the Discord server if you need general help. Bug reports should contain useful, addressable info.

**Comment by GBThor92** [comment]
> Well, I can't reproduce this, I have a lot of sources here and have try search one piece like you did and I could find just fine, and about the freezing, is happening for some time now, there a some issue opened here because of that, #7240 And the Android version you can always find in information in your phone configuration

I knew the version number was somewhere, but was not sure on where it was.

**Comment by GBThor92** [comment]
> Please do actually fill the information requested...
> 
> "latest" and "not sure" are NOT valid numeric answers.

Sorry for this being my very first post ever on this site so I was not sure on what to write there cause it would not let me post unless i filled those in

**Comment by GBThor92** [comment]
> > Please do actually fill the information requested...
> > "latest" and "not sure" are NOT valid numeric answers.
> 
> And "Expected behavior" be "solve my issue i guess" is not a useful information as well

Sorry for this being my very first post ever on this site so I was not sure on what to write there cause it would not let me post unless i filled those in
