### ISSUE TITLE
Japscan - Chapter image is corrupted but not on website view

### ISSUE THREAD

**Issue by adamsaimi** [tachiyomiorg/tachiyomi#7845]
### Steps to reproduce

1- View Master Keaton from japscan extensions.
2- from chapter 74 to the last one every thing is corrupted

### Expected behavior

A normal view of the chapter

### Actual behavior

Corrupted chapters 
![Screenshot_20220823-002812](https://user-images.githubusercontent.com/55293825/186029846-ef5faa28-baef-472e-801b-e59126c6474a.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

One plus 7 pro

### Other details

The problem has happened on other manga from the same source. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
