### ISSUE TITLE
KOSHOUKO SOURCE - NOT WORKING

### ISSUE THREAD

**Issue by loreg0d** [tachiyomiorg/tachiyomi#7852]
### Steps to reproduce

1.added source
2.open source
3.source cannot use

### Expected behavior

Source should be available

### Actual behavior

KOSHOUKO - cannot read in source

### Crash logs

![Screenshot_20220824-214505_Tachiyomi](https://user-images.githubusercontent.com/111991148/186440617-589b172f-0009-4955-8c0a-1eb9444777e8.png)

### Tachiyomi version

0.13.6

### Android version

ANDROID 11

### Device

SAMSUNG A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
