### ISSUE TITLE
Local chapters in external usb drives do not show up

### ISSUE THREAD

**Issue by Nogooduser** [tachiyomiorg/tachiyomi#7853]
### Steps to reproduce

1. Plug in an external drive via usb (in my case I'm using an sd card plugged into a usb-c adapter)
2. Create the appropriate folder structure for local files in the root of the drive
3. Go to local source inside Tachiyomi

### Expected behavior

The manga added should show up like normal.

### Actual behavior

Nothing at all shows up under the local source despite Tachiyomi having been given access to the external drive (I can download chapters to it and read them with no issue)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung Galaxy A53 5G.  
Also tested on an Onyx Boox Note Air 2 running Android 11 with the same results.

### Other details

The sd card is formatted in exFAT if that's of any help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The app only checks for storage locations that are mounted and formatted for Android, not just arbitrary external storages.

There's no plan to add that functionality either, as it's at odds with the eventual need to scope storage to a single persistent location.
