### ISSUE TITLE
koushoku 

### ISSUE THREAD

**Issue by polayan** [tachiyomiorg/tachiyomi#7854]
### Steps to reproduce

koushoku extension doesn't work

### Expected behavior

it should download manga but doesn't 

### Actual behavior

it doesn't download anything from this extension 

### Tachiyomi version

0.13.6

### Android version

android 11

### Device

oppo a94

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the extensions repository.
