### ISSUE TITLE
Accidental removal from the library a downloaded manga

### ISSUE THREAD

**Issue by Veaxale** [tachiyomiorg/tachiyomi#7855]
### Describe your suggested feature

A scan function to show which one that removed.
Label in the library that show each different sources, and filter to listed in each different section.

### Other details

I want to remove the folder that accidentally removed from the library without erasing my reading history that usually darken when u had read it.
The feature clear database make me scared.
If there a label of source in the manga cover.
I'll check it myself which one i deleted from the library, if there such feature, its will be easier, because my downloaded folder so many.. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Hard to understand what you're saying, but if you're concerned about orphaned downloads (i.e. previously downloaded chapters that don't correspond to chapters visible in the app anymore): #1767 / #2108
