### ISSUE TITLE
Don't allow new line at the end of user agent string

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#7856]
### Steps to reproduce

1. Go to settings > advanced > Default user agent string
2. put a new line at the end of the string
3. restart the app
4. go to browse tab which crashes the app

### Expected behavior

It should not let the user add a new line at the end

### Actual behavior

It lets the user add a new line at the end, leading to crash

### Crash logs

E AndroidRuntime: java.lang.IllegalArgumentException: Unexpected char 0x0a at 117 in User-Agent value: Mozilla/5.0 (Linux; Android 9; SM-G955F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36

### Tachiyomi version

0.13.6 and r4821

### Android version

Android 12

### Device

Tecno Spark 6 (with custom aosp rom)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by M9k** [comment]
I would propose to do a trim automatically on save, so there is no need to handle the error if the user enters it.
