### ISSUE TITLE
UI Glich

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#7862]
### Steps to reproduce

I got this error message
![IMG_20220826_011912](https://user-images.githubusercontent.com/92982808/186755116-67296340-c63a-4f03-91df-b97119a7c501.jpg)
and I simply tapped it

### Expected behavior

A short error summary maybe

### Actual behavior

This UI Glich happed
![Screenshot_2022-08-26-01-13-00-620_eu kanade tachiyomi](https://user-images.githubusercontent.com/92982808/186755426-99d3e2ab-f64a-43b7-a470-518593b84c4f.jpg)

### Tachiyomi version

0.13.6

### Android version

11

### Device

Redmi Note 8 Pro

### Other details

When I tapped on back arrow beside "Download Queue", everything went back to normal.
Also, the extension is working fine.
Plus that manhwa is NSFW 😅
And that was the only chapter on downloading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed with the UI rewrites happening in preview.
