### ISSUE TITLE
Auto clear cookie

### ISSUE THREAD

**Issue by Lyonie** [tachiyomiorg/tachiyomi#7864]
### Describe your suggested feature

More sources are getting API issue so by auto clearing cookies every 5 minutes will renew API & solving the issue.

### Other details

If approved, please let us choose enable or disable "auto clearing cookies"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Lyonie** [comment]
If time setting is troublesome, exit a manga then auto clearing caches also solve API issue.

**Comment by vetleledaal** [comment]
If this is in response to MangaHub, the error messages about API rate limiting were mostly red herrings. See https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13184#issuecomment-1227043109

Even ignoring that, I think these issues are better solved in the specific extensions, rather than a hack such as this.

**Comment by Lyonie** [comment]
You maybe right but clearing cookie & cache after exit a manga actually make sense. 

I believe many reader read manga from chapter to later chapter or manga to other manga so clearing old cookie & cache does helps loading pages  performance also more secure & fix outdated cookie.

**Comment by arkon** [comment]
It's under advanced settings for a reason -- clearing cookies obviously clears things like login sessions which can be strongly undesirable to happen all the time.

Most sources don't need cookie to be repeatedly cleared to work.
