### ISSUE TITLE
No result when looking up series

### ISSUE THREAD

**Issue by GBThor92** [tachiyomiorg/tachiyomi#7865]
### Steps to reproduce

For some reason when I search for a manga, the app will show no result.
The way I usually search is by having it show me result from different extensions.

I am still able to find results, but the only way for me to find anything is to go in to the different extensions, then look up the name of the serie.

Here is a link  with a screen recording on what the issue is.
https://drive.google.com/file/d/1g6bQEirYQztnfe1cnfLDOyhlkQuGtxRt/view?usp=sharing

In the recording I look up One Piece, Naruto and Hunter x Hunter and I have at least seen them before on 7 different extensions, but after I last updated the app I get no result no matter what I search.

### Expected behavior

Not sure what to write here.
Sorry I am new to posting about issues like these.

### Actual behavior

I think it has been like this for about 2 or 3 months more or less when this started to occur.

Before the issue started If I where to look up something like One Piece on the app I would get result showing me it from basically all extensions I have, but now when I look it up the app will say no result was found.

### Tachiyomi version

0.13.6

### Android version

12

### Device

Samsung S22 Ultra

### Other details

I have tried looking up on the site to see if anyone else have similar issues, I also posted about this on a different post, but only got negative reply on the post that was not even helpful at all because of how I wrote the post, but I am very new to posting on this site related to issues, so please know that I am simply trying to figure out what is going on with the app for me and hope that if anyone else has similar problem like me can see this post and also find answer to the same problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
As the error message suggests, you need to pin sources or disable that behaviour from the browse setting.
