### ISSUE TITLE
Filter By Sources

### ISSUE THREAD

**Issue by ConfusedG** [tachiyomiorg/tachiyomi#7868]
### Describe your suggested feature

The app filters by sources where the manga is retrieved from.

### Other details

This could be useful in case there is a source that is not working so that it is easier to migrate to another source.
I am fully aware that I could go to Browse > Migrate > <Source>, however, I could not find a way to see the latest chapter of the manga there.

For example, at the time this issue is written, mangabuddy is down and I want to migrate to another source, some sources have different latest chapters (a manga could be up to chapter 100 in source A and chapter 50 in source B). Considering I have multiple manga in the source, it is quite tedious to go back to library, search the manga and double check the latest chapter to migrate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
in library you can search by source name and in migrate screen you can tap the cover to open the manga

**Comment by ConfusedG** [comment]
sorry I didn't realize that, thanks
