### ISSUE TITLE
Freezing at end of chapters

### ISSUE THREAD

**Issue by 1desousa** [tachiyomiorg/tachiyomi#7869]
### Steps to reproduce

Last page of chapter freezing Appling for about a minute then starts to work again

Download button for multiselect and top corner download function not working but individual download button beside chapter working

https://user-images.githubusercontent.com/112216062/187001985-ffd5bec0-b183-4b1c-95eb-8a14cfceec5b.mp4

### Expected behavior

Finishing reading chapter..

Be able to download multiple chapters

### Actual behavior

Freezes at end of chapter

Won't let download multiple 

### Tachiyomi version

0. 13.6

### Android version

Android 12

### Device

Samsung s22 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems to be related to the download check (#7847).
