### ISSUE TITLE
Library series icons slow load

### ISSUE THREAD

**Issue by Linnchoeuh** [tachiyomiorg/tachiyomi#7870]
### Steps to reproduce

I don't really know why this happens, but the library tab of my Tachiyomi takes around 30 seconds to display my series. And I do believe that is too long for what it needs to load.

When I launch Tachiyomi:
![Screenshot_20220827-162125_Tachiyomi](https://user-images.githubusercontent.com/64591203/187034458-bf93406a-6297-4c27-a073-785755766235.png)
After around 30 seconds:
![Screenshot_20220827-162203_Tachiyomi](https://user-images.githubusercontent.com/64591203/187034480-1c01b2ee-2d0d-46d0-8475-42d11ef57349.png)

I have 33 added series, around 3000 chapters downloaded, and 9 extensions downloaded.
The 3000 chapters are downloaded on a Micro SD card (A sandisk 256GB with120MB/s read/write)
I suspect my too large of downloaded chapter to be the cause, but as I say, I don't know why this happens.
Thanks in advance for any fix.

### Expected behavior

I guess loading series and series images in less than 5sec would be nice.

### Actual behavior

Loading series takes around 30sec.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Samsung Galaxy A70 (SM-A7050)

### Other details

My Micro SD is normally in a good state, but it could be also my Micro SD card having issue.
I believe this issue doesn't fit with the Troubleshooting > Slow Loading since it's not related to extension or chapter loading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Having downloads or local manga on SD cards will always be slow because SD card operations are always slow regardless of how fast it's advertised as due to OS limitations.

You can try to move things to internal storage and/or disable download badges to help it a bit.

Related: #4286
