### ISSUE TITLE
Add back auto update library manga even after not reading past few chapters

### ISSUE THREAD

**Issue by OutStraw** [tachiyomiorg/tachiyomi#7872]
### Describe your suggested feature

Few months ago I updated the app and they removed auto chapter update. Now if I don't read up to the latest chapter I will have to manually update the specific series by dragging down. Now I cannot remember which series has been updated or not due to the removal of auto update regardless of latest read chapter. I know it's to lessen the burden on the sources. But I hope that this feature will be added back.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
This is answered [in the FAQ](https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries) "Why does global update skip some entries?"
