### ISSUE TITLE
Tachiyomi stuck loading long strips

### ISSUE THREAD

**Issue by stevenx37** [tachiyomiorg/tachiyomi#7879]
### Steps to reproduce

1. Open a webtoon chapter

### Expected behavior

The webtoon pages should load.

### Actual behavior

The first (short) page loads, but the next long strip page freezes on the loading circle. I also tried viewing a downloaded version and same issue happened even though all the images were in the .cbz.

### Crash logs

--------- beginning of crash
08-27 21:04:38.386 21715 21715 E AndroidRuntime: FATAL EXCEPTION: main
08-27 21:04:38.386 21715 21715 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 21715
08-27 21:04:38.386 21715 21715 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:6)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-27 21:04:38.386 21715 21715 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
--------- beginning of main
08-27 21:18:19.640 26534 26534 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
08-27 21:18:19.726 26534 26571 E SQLiteLog: (283) recovered 104 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-27 21:18:19.929 26534 26633 E SQLiteLog: (284) automatic index on C(manga_id)
08-27 21:18:19.930 26534 26633 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-27 21:20:08.446 26953 26953 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
08-27 21:20:08.525 26953 26985 E SQLiteLog: (283) recovered 12 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-27 21:20:08.721 26953 27057 E SQLiteLog: (284) automatic index on C(manga_id)
08-27 21:20:08.721 26953 27057 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-27 21:23:02.669 27419 27419 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
08-27 21:23:02.759 27419 27452 E SQLiteLog: (283) recovered 52 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-27 21:23:02.947 27419 27520 E SQLiteLog: (284) automatic index on C(manga_id)
08-27 21:23:02.947 27419 27520 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-27 21:23:27.569 27419 27646 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
App version: 0.13.6-4841 (standard, 1948d55d5, 82, 2022-08-27T22:12Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.021
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole

### Tachiyomi version

0.13.6-4841

### Android version

Android 13

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenx37** [comment]
"Split tall images (beta)" was the culprit. Toggling it off fixes it.

**Comment by Seishirou101** [comment]
its hopefully already fixed by #7875
