### ISSUE TITLE
r4841 some pages not showing online or downloaded 

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#7881]
### Steps to reproduce

Download before or after (or even not) the latest chapter of at least this series and see multiple pages not showing (ring turning instead)
![IMG_20220828_085013](https://user-images.githubusercontent.com/2168165/187061525-c4b917f0-ef47-4b89-acdf-d4aca2c1bf07.jpg)

### Expected behavior

All pages showing as in r4821

### Actual behavior

Some pages, not only credits but also actual pages, are not been able to be loaded.

### Tachiyomi version

r4841

### Android version

Android 12

### Device

Mi 11t

### Other details

Reverted to r4821.
I tested chapters downloaded in r4821 and showing in r 4841, and also downloaded in r4841 and showing in r4841 or r4821. The problem is only with r4841 showing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by yohanim** [comment]
Forgot to tell I'm reading chapters in webtoon mode

**Comment by AntsyLich** [comment]
Can you provide a crash log? After you do disable "Split tall images (Beta)"

**Comment by yohanim** [comment]
You were right regarding the beta split image. With it disabled, no more issue. Here is the crash log with it enabled
--------- beginning of main
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:44:04.869 20882 20882 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-28 09:44:05.101 20882 20930 E SQLiteLog: (283) recovered 798 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-28 09:44:06.015 20882 21005 E QT      : [QT]file does not exist
08-28 09:44:06.019 20882 21005 E QT      : [QT]file does not exist
08-28 09:44:06.092 20882 20931 E SQLiteLog: (284) automatic index on C(manga_id)
08-28 09:44:06.093 20882 20931 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-28 09:44:06.687 20882 20931 E ion     : ioctl c0044901 failed with code -1: Invalid argument
08-28 09:44:07.022 20882 20998 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
08-28 09:44:07.022 20882 20998 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 0.13.6-4841 (standard, 1948d55d5, 82, 2022-08-27T22:12Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_global

**Comment by yohanim** [comment]
And for comparison purpose, the cash log with it disabled and no showing issue.
--------- beginning of main
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:05:36.811 15120 18435 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:07:29.072 15120 18605 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-28 09:08:40.345 15120 18617 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
08-28 09:44:04.869 20882 20882 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-28 09:44:05.101 20882 20930 E SQLiteLog: (283) recovered 798 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-28 09:44:06.015 20882 21005 E QT      : [QT]file does not exist
08-28 09:44:06.019 20882 21005 E QT      : [QT]file does not exist
08-28 09:44:06.092 20882 20931 E SQLiteLog: (284) automatic index on C(manga_id)
08-28 09:44:06.093 20882 20931 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-28 09:44:06.687 20882 20931 E ion     : ioctl c0044901 failed with code -1: Invalid argument
08-28 09:44:07.022 20882 20998 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
08-28 09:44:07.022 20882 20998 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 0.13.6-4841 (standard, 1948d55d5, 82, 2022-08-27T22:12Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_global
