### ISSUE TITLE
Category Selection Glitch

### ISSUE THREAD

**Issue by omega7pro** [tachiyomiorg/tachiyomi#7886]
### Steps to reproduce

1. Tap a manga and enter the info page where the chapters are listed
2. Tap the heart to add to library

### Expected behavior

Shows the category selection screen and allows you to slide up and down to pick the category that you want to put it in

### Actual behavior

Shows the category screen like normal, except it only shows the first 20 options and you can't slide anything. Not only that, there is a rather significate delay of ~3 seconds should you choose one of the options.

### Tachiyomi version

r4841

### Android version

Android 11

### Device

Galaxy Tab A

### Other details

I have checked multiple other sources on my end, even checked in my library already, and it seems to be an issue with the release, not the extensions. Also, should you hold-touch the manga (or however you describe it) rather than opening it, such that the info shows up, and going to the category thing that way, the selection works as intended.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed in #7883
