### ISSUE TITLE
Custom cover doesn't migrate successfully 

### ISSUE THREAD

**Issue by Kissieh** [tachiyomiorg/tachiyomi#7887]
### Steps to reproduce

Migrate any mannhwa and tick the custom cover migrate option.

### Expected behavior

Custom cover changes successfully.

### Actual behavior

Custom cover doesn't migrate.

### Crash logs

None.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Xiaomi redmi note 8 pro

### Other details

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems fixed in newer versions.
