### ISSUE TITLE
Bottom Library padding incorrect when the Button Navigation Bar is selected in Android.

### ISSUE THREAD

**Issue by WildManiac** [tachiyomiorg/tachiyomi#7888]
### Steps to reproduce

1. Change navigation bar type to Buttons.
2. Navigate to library with enough entries that would require you to scroll to the bottom.

### Expected behavior

For the entries on the bottom, you should see the entire cover (+ title, depending on the display type selected).

### Actual behavior

The entries on the bottom are cut off a bit.

### Tachiyomi version

Preview r4845

### Android version

Android 12

### Device

Samsung A52 5G

### Other details

| Button Navigation Bar selected |
| --- |
| ![Screenshot_20220828-123400_Tachiyomi](https://user-images.githubusercontent.com/11233971/187085971-43cf3539-b713-4ae6-a6f6-6b187033afaa.jpg) |

| Gesture Navigation Bar selected |
| --- |
| ![Screenshot_20220828-123427_Tachiyomi](https://user-images.githubusercontent.com/11233971/187085972-755b9533-9ba4-4f2a-b832-e0a0614b6b20.jpg) |

This issue is NOT present in Stable 0.13.6.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> For the entries on the bottom, you should see the entire cover (+ title, depending on the display type selected).

Why? I believe the app uses fixed spacing and the entries just happen to be not cut off on your device. On my device they are cut off.

> This issue is NOT present in Stable 0.13.6.

Preview version is rewritten in Jetpack Compose so the styles and spacing are a little bit different. That's why the behavior changed on your device.

**Comment by arkon** [comment]
I think this was fixed.
