### ISSUE TITLE
r4845 crash while reading in webtoon mode

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#7893]
### Steps to reproduce

Have the beta split images option active.
Read a chapter.
At the end, it can crash (my exemple is the following, chapter 443)
![Screenshot_2022-08-29-21-54-21-025_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/2168165/187286739-ae3ee316-599e-4874-9ad5-f0ecfcc374e2.jpg)

### Expected behavior

Normal reading 

### Actual behavior

Crash 

### Crash logs

--------- beginning of main
08-29 21:47:30.486 28617  3233 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:47:30.487 28617  3244 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:47:36.842 28617 30520 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:48:04.971 28617 30514 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:48:36.375 28617 11743 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:48:36.375 28617 11734 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:49:33.207 28617 11840 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:49:33.210 28617 11734 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:49:33.212 28617 11743 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:49:58.014 28617 11840 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
--------- beginning of crash
08-29 21:50:22.178 28617 28617 E AndroidRuntime: FATAL EXCEPTION: main
08-29 21:50:22.178 28617 28617 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 28617
08-29 21:50:22.178 28617 28617 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8268)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
08-29 21:50:22.178 28617 28617 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 21:50:22.180 28617 11743 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:22.183 28617 28617 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
08-29 21:50:22.183 28617 28617 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
08-29 21:50:22.183 28617 28617 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at android.os.Looper.loop(Looper.java:299)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8268)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
08-29 21:50:22.183 28617 28617 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 21:50:22.184 28617 11734 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:22.679 11901 11901 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
08-29 21:50:22.804 11901 11923 E SQLiteLog: (283) recovered 867 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-29 21:50:25.376 11991 11991 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-29 21:50:25.452 11991 12030 E QT      : [QT]file does not exist
08-29 21:50:25.453 11991 12030 E QT      : [QT]file does not exist
08-29 21:50:25.453 11991 12025 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
08-29 21:50:25.729 11991 12055 E SQLiteLog: (284) automatic index on C(manga_id)
08-29 21:50:25.729 11991 12055 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-29 21:50:26.129 11991 12114 E ion     : ioctl c0044901 failed with code -1: Invalid argument
08-29 21:50:26.223 11991 12028 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
08-29 21:50:26.223 11991 12028 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
08-29 21:50:34.668 11991 12183 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:34.668 11991 12151 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:36.933 11991 12069 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:37.312 11991 12075 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:38.553 11991 12076 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:38.553 11991 12072 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:39.782 11991 12151 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:39.782 11991 12044 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:39.791 11991 12183 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:43.629 11991 12069 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:46.776 11991 11991 E AndroidRuntime: FATAL EXCEPTION: main
08-29 21:50:46.776 11991 11991 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 11991
08-29 21:50:46.776 11991 11991 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8268)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
08-29 21:50:46.776 11991 11991 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 21:50:46.779 11991 12075 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:46.782 11991 11991 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
08-29 21:50:46.782 11991 11991 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
08-29 21:50:46.782 11991 11991 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at android.os.Looper.loop(Looper.java:299)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8268)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
08-29 21:50:46.782 11991 11991 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 21:50:46.783 11991 12076 E BitmapRegionDecoder: buildTileIndex failed, fall back using AOSP flow
08-29 21:50:49.337 12330 12330 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-29 21:50:49.408 12330 12371 E QT      : [QT]file does not exist
08-29 21:50:49.408 12330 12365 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
08-29 21:50:49.409 12330 12371 E QT      : [QT]file does not exist
08-29 21:50:49.679 12330 12395 E SQLiteLog: (284) automatic index on C(manga_id)
08-29 21:50:49.679 12330 12395 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-29 21:50:50.015 12330 12397 E ion     : ioctl c0044901 failed with code -1: Invalid argument
08-29 21:50:50.098 12330 12368 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
08-29 21:50:50.098 12330 12368 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 0.13.6-4845 (standard, 0e526c36b, 82, 2022-08-28T15:17Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_global

### Tachiyomi version

r4845

### Android version

Android 12

### Device

Mi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already fixed in #7892
