### ISSUE TITLE
Can't search up other than english

### ISSUE THREAD

**Issue by FischlJoa** [tachiyomiorg/tachiyomi#7894]
### Steps to reproduce

1. Search up something in korean on a korean extension
2. Nothing searched up.

### Expected behavior

Korean extensions have korean titles for manga, so when i search up in korean it should pop up.

### Actual behavior

Instead nothing popped up, though searching in numbers searches the manga with numbers in the title e.g. if the title is "9999렙", which has numbers and korean, can be searched up by typing 9999

### Tachiyomi version

0.13.6

### Android version

9

### Device

S8+

### Other details

It might be the problem with removing language change system that was in the app before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This seems like a extension issue so
>* [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
