### ISSUE TITLE
Chapter transition causes app to crash (Webtoon only)

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi#7896]
### Steps to reproduce

https://user-images.githubusercontent.com/49813589/187413088-6cf82184-3fc4-4184-93a6-90d71e419f43.mp4

1. Read any manga as webtoon ("the newbie is too strong" as reference)
2. Scroll until the end of chapter/chapter transition

### Expected behavior

1. Move to the next chapter.

### Actual behavior

1. Crashes

### Crash logs

--------- beginning of crash
08-30 18:09:19.056 23142 23142 E AndroidRuntime: FATAL EXCEPTION: main
08-30 18:09:19.056 23142 23142 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 23142
08-30 18:09:19.056 23142 23142 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 54, Size: 54
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:09:19.056 23142 23142 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: FATAL EXCEPTION: main
08-30 18:10:33.081 23143 23143 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 23143
08-30 18:10:33.081 23143 23143 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 51, Size: 51
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:10:33.081 23143 23143 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: FATAL EXCEPTION: main
08-30 18:13:16.307 23144 23144 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 23144
08-30 18:13:16.307 23144 23144 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 54, Size: 54
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:13:16.307 23144 23144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: FATAL EXCEPTION: main
08-30 18:16:40.476 25984 25984 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 25984
08-30 18:16:40.476 25984 25984 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 54, Size: 54
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:16:40.476 25984 25984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
--------- beginning of main
08-30 18:16:40.480 25984 25984 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
08-30 18:16:40.480 25984 25984 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 54, Size: 54
08-30 18:16:40.480 25984 25984 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at android.os.Looper.loop(Looper.java:288)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:16:40.480 25984 25984 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:16:40.693 22559 22559 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
08-30 18:16:40.830 22559 22586 E SQLiteLog: (283) recovered 38 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
08-30 18:16:42.510 25988 25988 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-30 18:16:42.643 25988 22666 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
08-30 18:16:42.866 25988 22696 E SQLiteLog: (284) automatic index on C(manga_id)
08-30 18:16:42.866 25988 22696 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: FATAL EXCEPTION: main
08-30 18:17:17.283 25988 25988 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 25988
08-30 18:17:17.283 25988 25988 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 50, Size: 50
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:17:17.283 25988 25988 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:17:17.285 25988 25988 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
08-30 18:17:17.285 25988 25988 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 50, Size: 50
08-30 18:17:17.285 25988 25988 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:16)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:201)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at android.os.Looper.loop(Looper.java:288)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7865)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-30 18:17:17.285 25988 25988 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-30 18:17:19.562 16890 16890 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
08-30 18:17:19.681 16890 23199 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
08-30 18:17:19.905 16890 23224 E SQLiteLog: (284) automatic index on C(manga_id)
08-30 18:17:19.905 16890 23224 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6-4845 (standard, 0e526c36b, 82, 2022-08-28T15:17Z)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.003
Device brand: samsung
Device manufacturer: samsung
Device name: d2x
Device model: SM-N976B
Device product name: aosp_d2x

### Tachiyomi version

r4845

### Android version

Android 12 (Pixel Extebded ROM)

### Device

Galaxy Note 10+ 5G

### Other details

This is the preview version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Already fixed by #7892
