### ISSUE TITLE
Agent user 

### ISSUE THREAD

**Issue by Leo-ilys** [tachiyomiorg/tachiyomi#7903]
### Steps to reproduce

I didn't find the user agent in the settings >> Advanced
Please can u add screenshots so we can understand better

### Expected behavior

It has to show a agent user like you said

### Actual behavior

It didn't show what ever I search

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Redmi 9T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Peppe3009** [comment]
You can find it in Settings -> Advanced and scrolling down till the Network section. You can also edit the string by tapping on it.
![Inkedphoto](https://user-images.githubusercontent.com/44870078/187712591-b87df79a-1b94-4178-9f2d-20de7ef02b13.jpg)
