### ISSUE TITLE
Discord usability null due to verification fault

### ISSUE THREAD

**Issue by Dook42** [tachiyomiorg/tachiyomi#7905]
### Steps to reproduce

Example:
1) have a virtual number on your cell phone
2) also have a landline
>discord doesn't accept either of these as verification as to allow posting to the server
3) attept to message admins that are online
>anyone & everyone on has message settings blocked

### Expected behavior

Someone or a grouping bot (role) available to reference/message 

### Actual behavior

Nothing functionally useful and github is what seems the only available bug reporter

### Tachiyomi version

0.13.6

### Android version

8.1.0

### Device

LG Phoenix 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dook42** [comment]
>>I'm not familiar enough with github to know how to edit label; if i even can. Sorry

**Comment by Dook42** [comment]
Catalyst42#0727.... I'm so sorry I had to be here & even commet TWICE.... selfshame

**Comment by CarlosEsco** [comment]
Discord verification levels are not changing.  If you have any bugs post here.  Or post in the subreddit if you need help
