### ISSUE TITLE
Tachiyomi Library update not working to completion

### ISSUE THREAD

**Issue by jonaslam94** [tachiyomiorg/tachiyomi#7915]
### Steps to reproduce

1. Go to Updates tab
2. Click the refresh button on the upper right corner or drag down the screen to update the library
3. Wait for update to finish
![tachiyomi 2](https://user-images.githubusercontent.com/99544462/187919056-d811338e-cb4b-4ef9-9b6d-8d6d2be61150.jpg)
![tachiyomi 1](https://user-images.githubusercontent.com/99544462/187919062-ed7d4bc3-a537-493d-93de-8e9d3dba12af.jpg)

### Expected behavior

The update should finish after a couple of minutes and display the results of the update (new chapters and errors encountered)

### Actual behavior

The update stops early on and doesn't update the entire library

https://user-images.githubusercontent.com/99544462/187919445-8697ca23-a2db-497e-83d4-58d40d5cabe5.mp4

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9469942/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung  S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Working as expected. It won't update entries where there are unread chapters

**Comment by jonaslam94** [comment]
> Working as expected. It won't update entries where there are unread chapters

it doesnt update any of the mangas in my library, unread or not

**Comment by AntsyLich** [comment]
I removed the comment but ig it was too late

**Comment by jonaslam94** [comment]
Side note: I found a workaround for it, but it's an unnecessary hassle. If I don't leave the tachiyomi app or let the phone fade to black while it's updating, it updates to completion. But if I switch to a different app or just go to the home screen of the phone, the update stops after a while

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-are-automatic-updates-not-working
