### ISSUE TITLE
Extensions page search results resets after exiting app

### ISSUE THREAD

**Issue by shabbyplace** [tachiyomiorg/tachiyomi#7920]
### Steps to reproduce

1. Go to extensions page
2. Enter something in search. Example: "manga"
3. Exit the app and open it again

### Expected behavior

The search results should be the same as they were before you exited the app.

### Actual behavior

Even if there is content in the search field, the search results are reset after exiting.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Oneplus 8T

### Other details

https://user-images.githubusercontent.com/17619547/187969702-7e342618-30dc-493d-8182-aa5caf2914f5.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed in preview.
