### ISSUE TITLE
Crashing scrolling onto next chapter

### ISSUE THREAD

**Issue by lelouchTzero** [tachiyomiorg/tachiyomi#7922]
### Steps to reproduce

Scroll normally on webtoon view and once u reach the next chapter the app crashes almost all manga and extensions will crash 

### Expected behavior

Next chapter without crashing

### Actual behavior

Crashes 

### Tachiyomi version

Preview r4845

### Android version

11

### Device

Samsung s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Fixed in next preview
