### ISSUE TITLE
Source locale script code isn't displayed properly

### ISSUE THREAD

**Issue by ObserverOfTime** [tachiyomiorg/tachiyomi#7926]
### Steps to reproduce

1. Install an extension with Chinese locale (e.g. MD)
2. Enable Simplified Chinese sources 
3. Check the locale name

### Expected behavior

* `zh-Hans` (`Chinese (Simplified)`) should be displayed as `中文 (简体)`
* `zh-Hans-CN` (`Chinese (Simplified, China)`) should be displayed as `中文 (简体，中国)`

### Actual behavior

* `zh-Hans` is instead displayed as `中文 (HANS)`
* `zh-Hans-CN` is instead displayed as `中文 (HANS,CN)`

### Tachiyomi version

0.13.6-4845 (standard, 0e526c36b, 82, 2022-08-28T15:17Z)

### Android version

Android 10 (SDK 29)

### Device

Xiaomi Redmi 9C

### Other details

I used Simplified Chinese as an example but it's reproducible with every [locale script code](https://developer.android.com/reference/kotlin/java/util/Locale#def_script).

Another example: `ko-Hang` (`Korean (Hangul)`) becomes `한국어 (HANG)` instead of `한국어 (한글)`.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already fixed by #7127

**Comment by ObserverOfTime** [comment]
I'm using the latest preview build and it doesn't look fixed to me.
