### ISSUE TITLE
[Feature request] Filter by source in Library tab

### ISSUE THREAD

**Issue by nayakvineet** [tachiyomiorg/tachiyomi#7931]
### Describe your suggested feature

It would be very useful to filter by source in Library tab. I would help in organizing into categories, checking for updates, migrating etc.

Even a sort by source in library tab would be very helpful

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Just search the source name

**Comment by jferdous70** [comment]
you can already search by source name in library

**Comment by nayakvineet** [comment]
Didn't know that was possible! Thanks!
