### ISSUE TITLE
Allow users to search extensions by supported languages

### ISSUE THREAD

**Issue by Vuizur** [tachiyomiorg/tachiyomi#7932]
### Describe your suggested feature

For rare languages, it is sometimes difficult to find extensions. For example for Czech (čeština) there are no extensions listed. They exist, but the user currently does not have any way to find them. He will only see them after installing something from the category "All" and then looking at the supported languages (For example bato.to or MangaDex). It would be nice if there was a feature that filtered for all extensions that support a specific language.

PS: You did a magnificent job on this app! Thank you for developing it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Addressed by #7956
