### ISSUE TITLE
Remove `Latest` button

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#7933]
### Describe your suggested feature

Since `Latest` and `Popular` screen has been merged into one, the `Latest` button can be removed.

*But some users only use latest/popular...*
Maybe developers can make the chips in browse source screen into this...
![IMG_20220904_082419_044~2](https://user-images.githubusercontent.com/108109611/188291783-3b207d14-1248-4d64-be37-d6104c302eac.jpg)

...and when clicked, a bottom sheet will appear(or maybe a dropdown anchored to the bottom of the chip)...
![Screenshot_20220904-082423_Google Play Store](https://user-images.githubusercontent.com/108109611/188291794-d263a9ed-9a6e-4c29-ac1e-a8338ec45005.png)

...and save the last user preference of screen(latest/popular) per source so that users won't change the screen everytime they open a source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Latest and Browse weren't merged, tapping anywhere else on the source's section will bring you to the same, previous browse page.

**Comment by arkon** [comment]
Until we figure out a better UX, this is still a sufficient shortcut to the latest listings and saves on unnecessary network requests if the user enters a source but only wants to look at Latest and not Popular.
