### ISSUE TITLE
Search text shrinks when entering extension from global search

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#7939]
### Steps to reproduce

Search for something globally and then click on one of the extensions

### Expected behavior

Search text should remain the same size 

### Actual behavior

https://user-images.githubusercontent.com/61708534/188298526-53d2e4c4-d60b-4442-9880-2c54e74ab16d.mp4

### Tachiyomi version

r4884

### Android version

10.0

### Device

Vankyo P40 Tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #7201
