### ISSUE TITLE
Settings menu in the reader can be stacked

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#7940]
### Steps to reproduce

Open any chapter and click rapidly on the icon for the settings menu

### Expected behavior

The menu should either open or close on each tap

### Actual behavior

The first part of the video is my only tapping on s, the second part is me spam tapping

https://user-images.githubusercontent.com/61708534/188298791-3a115ce2-5da1-4b7f-be49-9120c7e81807.mp4

### Tachiyomi version

r4884

### Android version

10.0

### Device

Vankyo P40 Tablet

### Other details

This is the only menu in the app with this issue, as far as I can tell

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
If you want to work on it go ahead
