### ISSUE TITLE
Cancel button for global update is visually unresponsive 

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#7941]
### Steps to reproduce

Smart a global update and click on the cancel button in the notification

### Expected behavior

The button should visually react like all the other tapable items in the app do, from covers in the library to the WebView button.

### Actual behavior

Nothing. It's like clicking on text. The first attempt is me holding to down, which does nothing and eventually opens up my tablets notification setting. The second attempt is a simple tap, also nothing.

https://user-images.githubusercontent.com/61708534/188299013-a3b75abe-2fa4-43c7-89d7-61cd1e325537.mp4

### Tachiyomi version

r4884

### Android version

10.0

### Device

Vankyo P40 Tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's a bit janky since updating the notification is actually basically just constantly replacing its contents, including the actions. It does have a visual ripple sometimes depending on timing.

Doubt we'd really address this unless there's a more ideal way of updating the notification.
