### ISSUE TITLE
Keep reading next manga

### ISSUE THREAD

**Issue by Daviid-P** [tachiyomiorg/tachiyomi#7946]
### Describe your suggested feature

When reading manga on your library, once you read the las page of the manga you're currently reading show a button to jump to6the next manga on your library.

Respecting current sorting settings.

![Screenshot_2022-09-04-15-18-04-483_eu kanade tachiyomi](https://user-images.githubusercontent.com/7734808/188316236-14156cd8-5f7b-4894-86b5-eb142da224ef.png)

In my case, after reading the nex chapter from "I Became Invincible After Descending" it should show a button to go to the latest chapter from "The Hero Returns".

I thought it could also load the chapter directly but I don't think that'd be a very good user experience.

Either click the button and go to the next manga's details or go to the next manga's newest chapter's first page. 

### Other details

Make it an toggleable options as I assume people might get annoyed at the prompt. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's no plans to leak concepts of the library into the manga details view.
