### ISSUE TITLE
Add a configurable per-source proxy support

### ISSUE THREAD

**Issue by Barracuda72** [tachiyomiorg/tachiyomi#7948]
### Describe your suggested feature

With recent block of MangaDex in Russia, the **urgency** of this feature become even more clear.

How it can be implemented (from a user standpoint):

* Add new settings item "Proxies" (maybe under the "Security" tab?).
* User can add/remove/manage several proxies (http/https/socks4/socks5).
* In each source settings user can enable proxy support and choose one of added proxies (or maybe even several going by priority? Just one will be more than enough for now).

It is very simple both from UX and implementation POV. I cannot comprehend why this is not a feature already.

I **strongly emphasize** that application-level VPN or system-level VPN is not a soulition for this problem nor is it a replacement for this feature. You might only want to route one or two sources via proxy, or you might want to route one specific source via one specific proxy.

I'm well aware that there were several other feature requests of this kind but they all were closed without any discussion whatsoever. At the same time I don't see any kind of roadblock for implementing this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> I cannot comprehend why this is not a feature already.

People too lazy to add it.

**Comment by arkon** [comment]
From MangaDex:

![](https://i.imgur.com/DQOOnfe.png)

The app already has DNS over HTTPS support with a variety of providers which is the simplest option for basic blocking scenarios.

This simply isn't worth the feature bloat given its niche use and better alternatives existing. As you mentioned, there's already existing closed issues for this (#358, #2791) that point to system-level proxying/VPNs/apps/etc. Having per-source proxies seems overly complicated. As with any other networking solution, you can toggle it as needed when visiting certain sites.

**Comment by Barracuda72** [comment]
Well, my point is, it's not really complicated and bloated (like, at all - it's just two lightweight activities and an extra parameter to a connection builder in code) and it is one of highly requested features (I can't think of another one with such a high demand and importance). There're many stuff that _I_ don't need in Tachi (like the DoH in question - it's literally useless), but I won't go as far as to reject them just because I don't need them.

And as I pointed it, system-wide and application-wide VPN is not the solution nor a replacement.

I understand that at the end of the day it's your project and you're free to refuse the ideas, but at least be honest like @AntsyLich .

**Comment by arkon** [comment]
@AntsyLich does not speak for my own thoughts.

If you think this is simple to implement and worth maintaining, feel free to contribute to a fork that agrees with that opinion. I simply do not think it's worth it. While it's unfortunate that Russia censors the Internet for their citizens, it isn't enough justification to add something that has well-known working solutions.
