### ISSUE TITLE
Empty Selectable Choice in App Language

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#7950]
### Steps to reproduce

Navigate to More -> General -> App Language

### Expected behavior

Show selection choice with language name

### Actual behavior

There are 1 empty Selectable choice (without name) in app language

### Tachiyomi version

Preview r4884

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

![Screenshot_20220905-034111018](https://user-images.githubusercontent.com/101858971/188330808-3da41e5f-881e-4945-ba15-4444f2ecc519.jpg)
![Screenshot_20220905-034118332](https://user-images.githubusercontent.com/101858971/188330810-8043e066-c650-4c01-a600-679f00e42592.jpg)

When click empty choice nothing happen, language not changing still same as default

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
Edit with correctly actual and expected behavior

**Comment by AntsyLich** [comment]
Weird doesn't show up for me
![Screenshot_20220905-172032](https://user-images.githubusercontent.com/59261191/188437442-f2209dfd-c3e9-4145-babf-6acde5eded7d.png)

**Comment by DchanN** [comment]
> Weird doesn't show up for me ![Screenshot_20220905-172032](https://user-images.githubusercontent.com/59261191/188437442-f2209dfd-c3e9-4145-babf-6acde5eded7d.png)

I'm try install tachiyomi preview in another phone 
(never used tachiyomi) and have same issue, this phone it's android 8.1

![P_20220905_211333](https://user-images.githubusercontent.com/101858971/188458658-8c33e4c3-907c-4f57-9cea-0962a5e9d3b4.jpg)
