### ISSUE TITLE
Split Tall Images (Beta) Infinite Load on Downloaded Chapters

### ISSUE THREAD

**Issue by MarrowLX** [tachiyomiorg/tachiyomi#7959]
### Steps to reproduce

1. Turn on option to split tall images (beta)
2. Pick a manwha from Asura, Isekaiscan, or presumably others
3. Either download a chapter then try to open it or attempt to open a chapter you haven't downloaded
4. Watch the loading wheel spin indefinitely.

I am on Sy but people in the discord weren't sure if it might be a broader problem so I'm submitting it here. I was able to fix this so I'm no longer having issues but they suggested I share it.

### Expected behavior

I expected downloaded chapters to load immediately and chapters I hadn't downloaded to load after a moment.

### Actual behavior

Loading wheel spins indefinitely regardless of whether you have downloaded the chapter already.

### Crash logs

--------- beginning of crash
09-06 07:00:06.457 11239 11239 E AndroidRuntime: FATAL EXCEPTION: main
09-06 07:00:06.457 11239 11239 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 11239
09-06 07:00:06.457 11239 11239 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.onLongStripSplit$lambda-9(WebtoonViewer.kt:1)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(Unknown Source:0)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:6)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-06 07:00:06.457 11239 11239 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
App version: 1.8.5 (standard, bd1acc3ae, 38, 2022-08-28T01:23Z)
Preview build: 478
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.021
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

### Tachiyomi version

Preview r478

### Android version

Android 13

### Device

Google Pixel 6 Pro

### Other details

I have this issue on Sy but people in the discord weren't sure if it might be a broader problem so I'm submitting it here. I was able to fix this so I'm no longer having issues but they suggested I share it.

![Screenshot_20220906-082739](https://user-images.githubusercontent.com/112951025/188636773-c2a51b40-e02e-4bf4-b9e9-bfeba0f614d2.png)
![Screenshot_20220906-075234](https://user-images.githubusercontent.com/112951025/188636789-6cd4395a-9813-44ca-bb99-cdf22e02d078.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
this is fixed on main preview, Sy is yet to update their app

**Comment by MarrowLX** [comment]
Thanks a lot, appreciate that. They were just letting me know in the discord too.
