### ISSUE TITLE
Update library isn't updating 

### ISSUE THREAD

**Issue by hellbreakes** [tachiyomiorg/tachiyomi#7960]
### Steps to reproduce

Go to updates
Click on the reload icon

### Expected behavior

It should have informed me if any added manga have been updated 

### Actual behavior

It is always the same even if the manga is updated......but if we go to the manga itself and reload then it will reload new chapters...plzz fix this too many manga to reload separately.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Xaoimi 11i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#library
