### ISSUE TITLE
Security pass not working on start

### ISSUE THREAD

**Issue by mrtort** [tachiyomiorg/tachiyomi#7961]
### Steps to reproduce

Shut down all apps in ram memory
First time open app
It opens without asking for security

### Expected behavior

When opening the app ask for fingerprinto or code

### Actual behavior

On opening doesnt ask por password or fingerprint

### Tachiyomi version

App version: 0.13.6-4884 (standard, 21804bfc4, 83, 2022-09-03T21:10Z)

### Android version

Android version: 12 (SDK 31) 

### Device

Samsung s10+ SM-G975F

### Other details

I tried to reset security turnit off and on, with no luck
If you  change to another app and try to go back to tachiyomi the security will work fine
But on first time open,security doesnt work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by atmazzerexe** [comment]
@arkon Can confirm this bug still occurs on r4929 @ Android 11.
I reproduced it by force stopping Tachiyomi and reopened it again. Tachiyomi will just open itself without asking for fingerprint verification to unlock it.

**Comment by arkon** [comment]
I can't seem to reproduce it. Do you have a video?

**Comment by atmazzerexe** [comment]
> I can't seem to reproduce it. Do you have a video?

https://user-images.githubusercontent.com/14852623/190927565-ba42359f-69d1-410f-8450-d473155fe56c.mp4

**Comment by AnaGomes7** [comment]
Alguem me da a senha do mrtenzus
