### ISSUE TITLE
library bug

### ISSUE THREAD

**Issue by ThatsKrazy** [tachiyomiorg/tachiyomi#7962]
### Steps to reproduce

library updates not showing in the list

### Expected behavior

everything that updated should appear

### Actual behavior

some updates not appearing in the list

### Tachiyomi version

1.8.5

### Android version

Android 8

### Device

Samsung Galaxy S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Severe lack of any useful info in this report. Please open another one with actual details.
