### ISSUE TITLE
Some mangas / comics aren't appearing

### ISSUE THREAD

**Issue by Binsmoked** [tachiyomiorg/tachiyomi#7963]
### Steps to reproduce

1. I open MangaSee on chrome then search One Piece but when I open MangaSee on Tachiyomi and search One Piece, it doesn't appear. 

### Expected behavior

I should use One Piece on MangaSee extension on Tachiyomi since I've used it before.

### Actual behavior

One Piece doesn't appear on MangaSee Tachiyomi anymore but when I search in MangaSee using chrome, One Piece can be found there.

### Tachiyomi version

0.13.6

### Android version

10

### Device

Samsung Galaxy J6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
