### ISSUE TITLE
Browse Source Screen refreshes after long pressing manga

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7964]
### Steps to reproduce

Pick a random source
Long press a manga to add to/remove from library

### Expected behavior

Dialog shows and exits without refreshing

### Actual behavior

Browse source screen refreshes

### Tachiyomi version

r4884

### Android version

12.1

### Device

Redmi Note 9 Pro (PixelExperience)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't seem to reproduce in latest version.
