### ISSUE TITLE
Increased compatibilty with e-ink devices by replacing scrolling with pages

### ISSUE THREAD

**Issue by joao945** [tachiyomiorg/tachiyomi#7968]
### Describe your suggested feature

Tachiyomi could be more compatible with e-ink devices by including an option that replaced scrolling views with paged ones, by which I mean, for example, that the main library screen would not work by swiping up and down but left and right like pages in a book, ideally without animations. Here's what that looks like on kindle: https://youtu.be/jSDP9q8J9R4?t=371 
E-ink devices cannot keep up with scrolling actions or animations in general, so that'd be a great QOL improvement for e-ink users.

### Other details

In fact all e-ink devices by maufacturers such as Amazon, Kobo and Pocketbook use paged modes of displaying library information.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KraXen72** [comment]
till this is added, you can just copy out the .cbz files of downlaods into your ereader and it should be able to read them easily (atleast pocketbook does)

**Comment by arkon** [comment]
Tapping on tabs with animations disabled in the system doesn't animate the scroll. I don't think it'd make sense to rework the UX on any of the screens that are list-based otherwise.
