### ISSUE TITLE
Custom time on automatic update feature.

### ISSUE THREAD

**Issue by turbybela** [tachiyomiorg/tachiyomi#7970]
### Describe your suggested feature

Automatic updates
○ Off
○ 12hrs
...
○ `userInput` hours.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Even if this gets added you won't have a option to lower it below 12h

**Comment by arkon** [comment]
As @AntsyLich said, we wouldn't want to allow options below 12h anyway to avoid heavy load to sources, so I'm not sure what value this is supposed to add.
