### ISSUE TITLE
manga-updates not showing as tracker

### ISSUE THREAD

**Issue by Nur-Kekse-im-Kopf** [tachiyomiorg/tachiyomi#7979]
### Steps to reproduce

Go to 'Options ... Tracking' (where you find the available tracking services)

### Expected behavior

Seeing a list of trackers including manga-updates (as of version 0.13.6?)

### Actual behavior

Seeing a list of trackers not including manga-updates

### Tachiyomi version

0.13.6

### Android version

10

### Device

Huawei Mate Pro 10

### Other details

Pls let me know if I just misread something, but from what I understood, adding manga-updates tracking was marked 'done' in may and is now mentioned under 'Features' on this very github page.

On my tachiyomi 0.13.6, only the following trackers are listed: MAL, AniList, Kitsu, Shikimori, Bangumi, Komga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
As of now, mangaupdates tracker is only available in preview builds and isn't available for stable.
