### ISSUE TITLE
Mangadex source is not working 😕

### ISSUE THREAD

**Issue by KaiMaximus** [tachiyomiorg/tachiyomi#7987]
### Steps to reproduce

Manga source 'mangadex' has HTTP error 503 after the update 

### Expected behavior

Work like others sources 

### Actual behavior

HTTP error 503 

### Tachiyomi version

0.12.3.8

### Android version

Android 11

### Device

Samsung Galaxy A50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Wieku** [comment]
It's an extension issue (3rd acknowledgement), which has been explained here: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13421
