### ISSUE TITLE
Wrong page numbers in Webtoon and Continous vertical 

### ISSUE THREAD

**Issue by Shamicen** [tachiyomiorg/tachiyomi#7988]
### Steps to reproduce

Read any Manga in Webtoon or Continous vertical mode.

### Expected behavior

Page 2 should be labeled as Page 2 

### Actual behavior

Page 1 is correctly labeled as Page 1

![Screenshot Page 1 resized](https://user-images.githubusercontent.com/84282253/189522553-5c5591d2-7ff2-4758-8b70-2366aea2d57e.png)

Page 2 is also labeled as Page 1 (If the Page is tall enough to auto split it will switch to Page 2 after it reaches the split)

![Screenshot Page 2 resized](https://user-images.githubusercontent.com/84282253/189522554-bc5f2c4c-e841-4a20-8fa3-c550274462d0.png)

Page 3 is labeled as Page 2 

![Screenshot Page 3 resized](https://user-images.githubusercontent.com/84282253/189522555-da65a43b-7203-44b1-9964-e8b029d4d532.png)

After a chapter transition the first Page will be labeled as the last Page of the old chapter 

![Screenshot chapter transition resized](https://user-images.githubusercontent.com/84282253/189522547-9ac87e85-a357-42fc-87ac-a5a432f9b064.png)

Only at Page 2 will it switch to Page 1 of the new chapter

![Screenshot Page 2 after chapter transition resized](https://user-images.githubusercontent.com/84282253/189522723-64703337-1b6d-4541-9e65-eb25f7d17a81.png)

### Tachiyomi version

0.13.6 

### Android version

Samsung Tab: Android 11 Pixel emulator: Android 12

### Device

Samsung Tab S5e/ Pixel 5 emulator

### Other details

I confirmed the bug on stable 0.13.6 but the screenshots are from an emulator running a Debug version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't seem to reproduce this in preview build.
