### ISSUE TITLE
Folder on SD card as custom source

### ISSUE THREAD

**Issue by adamcool21** [tachiyomiorg/tachiyomi#7992]
### Describe your suggested feature

I would like to keep my downloaded library on an SD card or external source and browse from there. If there was an option in sources to selec a folder, and then open it up as if it was a source, that would be nice as an alternative to custom location local folder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You can have local on SD card though?

**Comment by TheKingTermux** [comment]
Uhh
Local source can used in internal or SD card
Just create `Tachiyomi folder` in SD card and create `local folder` and then you can put your downloaded Comic in `local folder `
![IMG_20220913_114126.jpg](https://user-images.githubusercontent.com/50316075/189810498-5f78b0d3-e22e-4a09-841d-bb0a7e024ff7.jpg)

![IMG_20220913_114134.jpg](https://user-images.githubusercontent.com/50316075/189810523-be4d68c1-1da0-4672-ae55-6a14d8c88639.jpg)
