### ISSUE TITLE
Resume Button Sometimes Blocks Bottom Sheet Within Global Search

### ISSUE THREAD

**Issue by PennyJim** [tachiyomiorg/tachiyomi#7993]
### Steps to reproduce

1. Global search for a manga
1.a. Make sure it has the resume/start button
3. Open and then leave a chapter
5. Immediately hold to select a chapter
5.a. Wait too long and it seems to work fine

### Expected behavior

The resume button should just fade away while the bottom sheet is on screen

### Actual behavior

The button does its entrance fade in _with_ the bottom sheet, covering the corner of said bottom sheet.

This seems to only happen within global search. I've tried it in the library, sources, and migrate (from both library and in browse) and it doesn't happen.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Moto G Power

### Other details

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 11 (SDK 30)
Android build ID: RPMS31.Q1-54-13-11
Device brand: motorola
Device manufacturer: motorola
Device name: sofia
Device model: moto g power
Device product name: sofia_retail

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This should be fixed in the UI rewrites that's already in the preview version.
