### ISSUE TITLE
Add an optional number of unread chapters required to skip checking for updates.

### ISSUE THREAD

**Issue by Moose1be** [tachiyomiorg/tachiyomi#7994]
### Describe your suggested feature

I turned the skip updating chapters, with unread chapters feature off, if I could say, with over 5 I would willingly turn it back on. May help the mangadex load if people are willing to atlaist have a little visible backlog.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6916
