### ISSUE TITLE
Update keeps skipping

### ISSUE THREAD

**Issue by Jerickl** [tachiyomiorg/tachiyomi#7995]
### Steps to reproduce

When i update my manga 
I always keeps skipping and not updating 

### Expected behavior

To update the manga

### Actual behavior

Skipping manga update

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Infinix note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheurgicDuke771** [comment]
Hi,
Can you go to:

```settings -> Library -> Skip updating titles```

and uncheck all the options
then try to update your manga.

**Comment by Riztard** [comment]
![image](https://user-images.githubusercontent.com/16263232/189598980-c000ca01-77f5-4b6d-8f4e-e0f98ab5edcc.png)

**Comment by Jerickl** [comment]
For a month that I've been trying to fix it thanks now i can enjoy reading again
