### ISSUE TITLE
Toast message not displaying properly in light mode

### ISSUE THREAD

**Issue by TheurgicDuke771** [tachiyomiorg/tachiyomi#7996]
## Issue Description:
While updating a category or library we got toast message. 
While using light mode the message is displayed in Dark text in Dark background making it unable to read.

## Steps to reproduce:
Try to update category/library in light mode.

### Expected behavior

In light mode Toast message should be displayed in dark text on light background.

### Actual behavior

In light mode Toast message is displayed in dark text on dark background, making it unable to read.

### Tachiyomi version

0.13.6

### Android version

Android 13

### Device

Google Pixel 6a

### Other details

Screenshot in light mode [Which is having the issue]:
![Toast_LightMode](https://user-images.githubusercontent.com/25581767/189581397-5dc7cf39-d999-4b27-af92-4850a945ff86.png)

Toast is displayed properly in dark mode (i.e. - light text on dark background).
Screenshot in dark mode [Which is displayed properly]:
![Toast_DarkMode](https://user-images.githubusercontent.com/25581767/189582236-6b100d30-cba9-45b7-8417-e9da2e7cdd6f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
@ivaniskandar I think you mentioned this before? Was it something to do with how the context is handled in newer versions of Android?

**Comment by ivaniskandar** [comment]
That is for locale I think and this should be fixed on preview by https://github.com/tachiyomiorg/tachiyomi/commit/b0520df1dd4ff169f03b744954e181df94459efe. Though on Android 12+ the toast is always using light mode toast which I think is related to the app's target sdk.

**Comment by TheurgicDuke771** [comment]
Issue resolved in latest stable released, hence closing it.
