### ISSUE TITLE
Tachiyomi R4904 sometime crash when opening extension

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#8001]
### Steps to reproduce

Click any extension

### Expected behavior

Show Extension library

### Actual behavior

Tachiyomi force closed

### Crash logs

eu.kanade.data.DatabaseHandler$DefaultImpls.awaitOneOrNull$default(DatabaseHandler.kt:1)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at eu.kanade.data.manga.MangaRepositoryImpl.getMangaByUrlAndSourceId(MangaRepositoryImpl.kt:1)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at eu.kanade.domain.manga.interactor.GetManga.await(GetManga.kt:11)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.access$networkToLocalManga(BrowseSourcePresenter.kt:6)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$getMangaList$1$2$1$1.invokeSuspend(BrowseSourcePresenter.kt:4)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-13 00:47:18.323 13218 13218 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
09-13 00:47:18.323 13218 13218 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@2483140, Dispatchers.Main]
09-13 00:47:19.797 13473 13473 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
09-13 00:47:19.897 13473 13507 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
09-13 00:47:20.498 13473 13561 E SQLiteLog: (284) automatic index on C(manga_id)
09-13 00:47:20.498 13473 13561 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6-4904 (standard, 9ce1d71a4, 83, 2022-09-10T21:09Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.021
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

### Tachiyomi version

R4904

### Android version

Android 13

### Device

Poco X3 Pro

### Other details

Video Crash

https://photos.app.goo.gl/tNTPyp6Wkoo3zX7r7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by nurananto** [comment]
full log https://drive.google.com/file/d/1FdfYzD2ZNmImZOhwasFBm0qtQHxMjB_c/view?usp=drivesdk

**Comment by arkon** [comment]
Please use a ROM that doesn't force unsafe database settings.
