### ISSUE TITLE
Manga freak search disabled 

### ISSUE THREAD

**Issue by AbdallahAhmedHamda** [tachiyomiorg/tachiyomi#8004]
### Steps to reproduce

When i seaech or go into mangafreak it says failed tobypass cloudflare but it updates already existing manga correctly and when i open in webview only the search is bugged but when i open in my browser everything is fine

### Expected behavior

It should have search results

### Actual behavior

Failed to bypass cloudflare only on search

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Realme 6 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
