### ISSUE TITLE
[Security] "Require Unlock" isn't working when opening app

### ISSUE THREAD

**Issue by lucky777709** [tachiyomiorg/tachiyomi#8005]
### Steps to reproduce

Enable "Require Unlock" setting on Settings -> Security.
Lock when idle = Always
Close the app and open it again.

### Expected behavior

Tachiyomi should display the "Unlock Tachiyomi" screen (Android's "insert password/unlock device" screen) when opening the app.

### Actual behavior

Tachiyomi isn't displaying the "Unlock Tachiyomi" screen, and Tachi opens without requiring to insert the password/unlock the device, even with the aforementioned settings.

### Crash logs

The "Unlock Tachiyomi" screen appears normally when minimizing and then returning to the app.
The issue only happens when first opening the app (the lock screen isn't appearing on app start).

### Tachiyomi version

Preview r4904

### Android version

7.1.1

### Device

Samsung Galaxy J2 Pro (SM-J250M)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Duplicate of #7961
