### ISSUE TITLE
Failed To Get Extensions List

### ISSUE THREAD

**Issue by Nobuyaki** [tachiyomiorg/tachiyomi#8007]
### Steps to reproduce

Every Time Pressing the extension

### Expected behavior

Show Extension library

### Actual behavior

Tachiyomi says "Failed To Get Extensions List"

### Crash logs

--------- beginning of main
--------- beginning of system
09-14 14:39:39.930  9958  9958 E ResourceType: Style contains key with bad entry: 0x01010586
09-14 14:39:39.962  9958  9958 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:39:39.962  9958  9958 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:39:39.962  9958  9958 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:39:40.714  9958  9958 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:39:40.714  9958  9958 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:39:40.714  9958  9958 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:39:43.125  9958 10182 E SQLiteLog: (284) automatic index on C(manga_id)
09-14 14:39:43.125  9958 10182 E SQLiteLog: (284) automatic index on R(manga_id)
09-14 14:39:43.125  9958 10182 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-14 14:39:45.631  9958 10306 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.631  9958 10307 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.633  9958 10308 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.633  9958 10309 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.633  9958 10310 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.633  9958 10311 E RenderScript: SETAFFINITY ret = -1
09-14 14:39:45.635  9958 10312 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:24.940 10664 10664 E ResourceType: Style contains key with bad entry: 0x01010586
09-14 14:40:24.954 10664 10664 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:40:24.954 10664 10664 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:40:24.954 10664 10664 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:40:25.085 10664 10664 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:40:25.085 10664 10664 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:40:25.085 10664 10664 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:40:25.759 10664 10726 E SQLiteLog: (284) automatic index on C(manga_id)
09-14 14:40:25.759 10664 10726 E SQLiteLog: (284) automatic index on R(manga_id)
09-14 14:40:25.759 10664 10726 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-14 14:40:26.716 10664 10761 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.721 10664 10764 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.721 10664 10759 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.721 10664 10760 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.721 10664 10762 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.721 10664 10763 E RenderScript: SETAFFINITY ret = -1
09-14 14:40:26.722 10664 10765 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:11.706 12617 12617 E ResourceType: Style contains key with bad entry: 0x01010586
09-14 14:42:11.710 12617 12617 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:42:11.710 12617 12617 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:42:11.710 12617 12617 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:42:11.834 12617 12617 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:42:11.834 12617 12617 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:42:11.834 12617 12617 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:42:12.513 12617 12677 E SQLiteLog: (284) automatic index on C(manga_id)
09-14 14:42:12.513 12617 12677 E SQLiteLog: (284) automatic index on R(manga_id)
09-14 14:42:12.513 12617 12677 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-14 14:42:13.162 12617 12711 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.162 12617 12712 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.163 12617 12713 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.163 12617 12717 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.163 12617 12715 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.163 12617 12716 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:13.165 12617 12718 E RenderScript: SETAFFINITY ret = -1
09-14 14:42:44.313 12617 12625 E System  : Uncaught exception thrown by finalizer
09-14 14:42:44.313 12617 12625 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
09-14 14:42:44.313 12617 12625 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:336)
09-14 14:42:44.313 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:254)
09-14 14:42:44.313 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:241)
09-14 14:42:44.313 12617 12625 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:107)
09-14 14:42:44.313 12617 12625 E System  : 	at java.lang.Thread.run(Thread.java:764)
09-14 14:43:02.950 12617 12625 E System  : Uncaught exception thrown by finalizer
09-14 14:43:02.951 12617 12625 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
09-14 14:43:02.951 12617 12625 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:336)
09-14 14:43:02.951 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:254)
09-14 14:43:02.951 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:241)
09-14 14:43:02.951 12617 12625 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:107)
09-14 14:43:02.951 12617 12625 E System  : 	at java.lang.Thread.run(Thread.java:764)
09-14 14:43:08.673 12617 12625 E System  : Uncaught exception thrown by finalizer
09-14 14:43:08.674 12617 12625 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
09-14 14:43:08.674 12617 12625 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:336)
09-14 14:43:08.674 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:254)
09-14 14:43:08.674 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:241)
09-14 14:43:08.674 12617 12625 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:107)
09-14 14:43:08.674 12617 12625 E System  : 	at java.lang.Thread.run(Thread.java:764)
09-14 14:43:20.287 12617 12625 E System  : Uncaught exception thrown by finalizer
09-14 14:43:20.287 12617 12625 E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
09-14 14:43:20.287 12617 12625 E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:336)
09-14 14:43:20.287 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:254)
09-14 14:43:20.287 12617 12625 E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:241)
09-14 14:43:20.287 12617 12625 E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:107)
09-14 14:43:20.287 12617 12625 E System  : 	at java.lang.Thread.run(Thread.java:764)
09-14 14:43:44.399 16469 16469 E ResourceType: Style contains key with bad entry: 0x01010586
09-14 14:43:44.402 16469 16469 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:43:44.402 16469 16469 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:43:44.402 16469 16469 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:43:44.621 16469 16469 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 14:43:44.621 16469 16469 E ResourceType: Style contains key with bad entry: 0x01010604
09-14 14:43:44.621 16469 16469 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 14:43:45.301 16469 16519 E SQLiteLog: (284) automatic index on C(manga_id)
09-14 14:43:45.302 16469 16519 E SQLiteLog: (284) automatic index on R(manga_id)
09-14 14:43:45.302 16469 16519 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-14 14:43:47.228 16469 16563 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.233 16469 16564 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.238 16469 16565 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.241 16469 16566 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.246 16469 16568 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.246 16469 16567 E RenderScript: SETAFFINITY ret = -1
09-14 14:43:47.248 16469 16569 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.344 16469 16781 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.344 16469 16783 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.345 16469 16785 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.345 16469 16788 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.345 16469 16786 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.345 16469 16787 E RenderScript: SETAFFINITY ret = -1
09-14 14:44:43.345 16469 16784 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.776 16469 17110 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.776 16469 17112 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.776 16469 17111 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.776 16469 17113 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.777 16469 17115 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.777 16469 17114 E RenderScript: SETAFFINITY ret = -1
09-14 14:46:08.777 16469 17116 E RenderScript: SETAFFINITY ret = -1
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 8.1.0 (SDK 27)
Android build ID: OPM1.171019.026 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1811
Device model: vivo 1811
Device product name: 1811

### Tachiyomi version

0.13.6

### Android version

Android 7

### Device

Vivo 1811

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
GitHub was having some issues at one point earlier this week.
