### ISSUE TITLE
Sort manga by storage size and display the size

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#8009]
### Describe your suggested feature

Add new sorting method that allow the Manga library to be sorted by storage size. 

To make it easier to know which Manga took lots of space and how much. So it's easier to cleanup the downloaded library 

### Other details

Not an important feature as other tools like diskusage can be used. But it'll be much easier to do if it's all can be done inside tachiyomi. Instead of using diskusage to check the Manga size, then use file manager / tachiyomi to delete the files 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by orangpelupa** [comment]
> , just set tachiyomi to delete your chapters after being read and don't use it to hoard.

How to do that? Can I do it per manga?

**Comment by M9k** [comment]
> > , just set tachiyomi to delete your chapters after being read and don't use it to hoard.
> 
> How to do that? Can I do it per manga?

Settings -> Download -> "Delete chapters" -> After reading automatically delete: Last read chapter
It's a global settings.
