### ISSUE TITLE
The ability to change the sharpness of images

### ISSUE THREAD

**Issue by xeleoss** [tachiyomiorg/tachiyomi#8011]
In most cases, manga is published in low resolution. Because of this, the manga is too blurry on high-resolution screens. Because of this, it is not very pleasant to read the text. The ability to change the sharpness would allow the reader to choose between blurring and pixelation.

**Comment by loocool2** [comment]
Duplicate of #3337

**Comment by xeleoss** [comment]
@loocool2  how is sharpness related to image magnification?

**Comment by loocool2** [comment]
Apologies, this would more accurately be a duplicate of #855
