### ISSUE TITLE
Cannot Install NSFW Extension Properly 

### ISSUE THREAD

**Issue by Idiot-Hub123** [tachiyomiorg/tachiyomi#8024]
### Steps to reproduce

Attempt to download any extension/source with the "18+" mark on it.

### Expected behavior

It should pop up after downloading the extension, and I should be able to use the source to watch manga of my choosing.

### Actual behavior

I installed any source with NSFW content on it, yet I can't seems to download any extension properly. I can't open them, neither does it pop up among the list of extensions I have installed.

It doesn't matter if the source website is IP blocked in my country or not.
https://user-images.githubusercontent.com/113788673/190867611-ebf3f017-c139-4c51-b908-7e46db6f5589.mp4

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

realme X3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can try downloading from https://tachiyomi.org/extensions/ + using https://play.google.com/store/apps/details?id=com.aefyr.sai to install them if it's not working from inside the app for whatever reason.

**Comment by Idiot-Hub123** [comment]
> You can try downloading from https://tachiyomi.org/extensions/ + using https://play.google.com/store/apps/details?id=com.aefyr.sai to install them if it's not working from inside the app for whatever reason.

The problem isn't that I can't install them, it's that I can't _use_ them once downloaded. It's strange, since sfw extensions work just fine.

**Comment by AntsyLich** [comment]
seems like a case of "I disabled nsfw extension but nsfw extensions aren't appearing"
