### ISSUE TITLE
Library Search doesn't work properly 

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#8031]
### Steps to reproduce

Open Tachiyomi -> Library -> type in search bar

### Expected behavior

Library will only show keyword (manga title or source)  has been type in search bar

### Actual behavior

Nothing happen when type manga title or source in search bar, library stay with all manga show 

### Tachiyomi version

Preview r4929

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

To make library show the search result need to switch at least 1 or 2 category to library take effect to show search result, same with when want to remove search result.

Attempt to do search 

https://user-images.githubusercontent.com/101858971/190919547-66eef6a9-a628-4533-bd04-3c910a476e9d.mp4

To show search result 

https://user-images.githubusercontent.com/101858971/190919491-575208d5-51c1-49d3-9114-d92ffebe7c27.mp4

To show all manga ( exit search )

https://user-images.githubusercontent.com/101858971/190919608-9fa8b27e-2a19-450d-9110-79c26640e170.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by juniorjacob** [comment]
This also occurs when searching for new titles in extensions.
