### ISSUE TITLE
Regarding Mangadex 

### ISSUE THREAD

**Issue by Sukuna089** [tachiyomiorg/tachiyomi#8032]
### Steps to reproduce

I know recently mangadex was down which is now as per them is back for tachiyomi too but after I got 2-3updates from it now its showing http error 503

### Expected behavior

Update should be given 

### Actual behavior

No updates are given error 503

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

OnePlus 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also, MangaDex is down for maintenance

**Comment by Sukuna089** [comment]
Im really sorry Sir
