### ISSUE TITLE
Error create cover for local manga stored in SD Card

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#8034]
### Steps to reproduce

Move or Place manga in Local Manga in SD Card directory -> open tachiyomi -> Browse -> Local Source

### Expected behavior

Cover automatically create

### Actual behavior

Cover didn't create, instead show broken cover ui

### Crash logs

Crash log for local cbz and non cbz ( both have some crash log)
--------- beginning of main
09-19 11:33:26.467  5184  7505 E LocalSource: Error updating cover for test
09-19 11:33:26.467  5184  7505 E LocalSource: java.io.IOException: Permission denied
09-19 11:33:26.467  5184  7505 E LocalSource: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at java.io.File.createNewFile(File.java:1008)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.tachiyomi.source.LocalSource$Companion.updateCover(LocalSource.kt:101)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.tachiyomi.source.LocalSource.access$updateCover(LocalSource.kt:228)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.tachiyomi.source.LocalSource$fetchSearchManga$3$1.invokeSuspend(LocalSource.kt:105)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:155)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:30)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:77)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:7)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.tachiyomi.source.LocalSource.fetchSearchManga(LocalSource.kt:208)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.tachiyomi.source.LocalSource.fetchLatestUpdates(LocalSource.kt:5)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.data.source.SourceLatestPagingSource.requestNextPage(SourcePagingSource.kt:5)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at eu.kanade.data.source.SourcePagingSource$load$mangasPage$1.invokeSuspend(SourcePagingSource.kt:32)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-19 11:33:26.467  5184  7505 E LocalSource: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
App version: 0.13.6-4929 (standard, 0086743a5, 84, 2022-09-17T21:10Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191008.001.WW_user_100.10.107.123_20210131 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_Z01R_1
Device model: ASUS_Z01RD
Device product name: WW_Z01RD

### Tachiyomi version

Preview r4929

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

Testing with both cbz and non cbz format (test = CBZ , test1 =non CBZ), tested in internal storage and work fine, only for local manga in SD Card

CBZ
![Screenshot_20220919-113410943](https://user-images.githubusercontent.com/101858971/190952060-102fd5ec-2885-4f59-8ed7-67bd73d91030.jpg)
![Screenshot_20220919-113424404](https://user-images.githubusercontent.com/101858971/190952171-d753dfd9-a69e-42f8-a793-c3524a8e2405.jpg)

Non CBZ
![Screenshot_20220919-113505337](https://user-images.githubusercontent.com/101858971/190952085-6acaa7b4-c65c-4fd5-a697-98376ea9a1bf.jpg)
![Screenshot_20220919-113517132](https://user-images.githubusercontent.com/101858971/190952099-1a45ea4c-78c5-4028-8d33-c234fe7efa7c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
In version Preview r6258 , Local manga still have broken cover for first time being put in local (I'm put around 60 ) , the cover can be fix/load if manually swipe down to refresh in manga page

And bug about can't change cover fixed too

https://github.com/tachiyomiorg/tachiyomi/assets/101858971/ead5f4e8-d71d-422b-9c07-e5f135e815c1

Tested in r6274 still same as 6258

**Comment by arkon** [comment]
Closing in favor of #10186
