### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by vlatkosh** [tachiyomiorg/tachiyomi#8043]
### Steps to reproduce

Trying to update any manga, any source/extension or eve trying to check for the latest version from within the app

### Expected behavior

Should update or refresh

### Actual behavior

Timeouts

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Huawei p30 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not enough info. Please refer to the troubleshooting guide. If the source has issues, report it on the extensions repo. If you're not sure how to diagnose the problem, consult the Discord server.
