### ISSUE TITLE
Range selection in library doesn't work

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#8071]
### Steps to reproduce

1. Long press an item in library
2. Long press another item in library that's >1 position away

### Expected behavior

It should select everything in between as well.

### Actual behavior

It selects the individual items.

### Tachiyomi version

Preview

### Android version

Any

### Device

Any

### Other details

This feature wasn't ported in the Compose rewrite.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by d-najd** [comment]
I have working code, but need to do a bit of cleanup so I will push the changes tomorow
