### ISSUE TITLE
Keep the next X chapters downloaded

### ISSUE THREAD

**Issue by Lagicrus** [tachiyomiorg/tachiyomi#8078]
### Describe your suggested feature

I want to be able to set for a manga/comic that it will keep the next X say five chapters downloaded. This way I don't have to keep jumping in and out of the chapter to tell Tachiyomi to download the next ten every so often. Instead, it will keep the following ten on hand.

This helps as it means I can always have the next bunch of chapters to go through when I am say on mobile data without needing to plan ahead and make sure to grab the following X amount of chapters on WiFi before I leave.

Also, with some extensions, instead of doing say all 20 pages in the same chapter they are instead 1 page per chapter. As such it is a much worse reading process if they have to keep waiting for each page to download as Tachiyomi won't auto grab the next page - as it is a chapter instead. So having the next X always downloaded gets around this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Exists in preview. Wait for next stable release

**Comment by Lagicrus** [comment]
> Exists in preview. Wait for next stable release

Awesome! Is there a list of features anywhere I can see or an expected release date?
