### ISSUE TITLE
Download status not in sync between updates and manga screen

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#8086]
### Steps to reproduce

1. Start a download on the updates screen
2. Go to the manga screen
3. Wait here a bit (doing it on a source with a high rate limiter)
4. Go back to the updates screen and see a different status

### Expected behavior

The same status on both screens

### Actual behavior

A different status on both screens

### Tachiyomi version

r4963

### Android version

Android 11

### Device

Oneplus 7

### Other details

https://user-images.githubusercontent.com/6564956/192340521-525f4a59-9b80-4f16-a44f-5d866373bbeb.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by rooparsh** [comment]
Hi, let me know if this is resolved, or if anyone's taking a look into this? 
Happy to take a look.

**Comment by MrAndre96** [comment]
> Hi, let me know if this is resolved, or if anyone's taking a look into this? Happy to take a look.

It hasnt been resolved but idk if someone is working on it

**Comment by arkon** [comment]
Fixed by 9dd9e741f34aeb49a15a939ec7f8495a992d8bf8
