### ISSUE TITLE
Trying to do a global search brings up an empty landing page

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#8089]
### Steps to reproduce

1. Install Preview version r4953
2. Have some sources installed (preferably)
3. tap/click on the Globe-Search button on the top

### Expected behavior

As in 0.13.6, you see a placeholder text ("Global Search") where you can write a manga name and do a search query

### Actual behavior

There's no placeholder text except showing a nearly empty screen with a Search icon (not Globe Search icon anymore) at the top right.
Clicking on this new search icon, we see a different placeholder text ("Search...") and then enter a manga and do a global search
SO, we have a regression...

### Crash logs

NA

### Tachiyomi version

r4963

### Android version

12

### Device

SM-N770F

### Other details

This could be duplicate but I couldn't find a duplicate issue - please no bully

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ivaniskandar** [comment]
#7938
