### ISSUE TITLE
Manga's genre tag doesn't trigger filter search

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#8092]
### Steps to reproduce

Open MangaDex source, tap a manga in the list, wait for details to load, then tap a genre tag (Action/Horror/Slice of Life/etc).

### Expected behavior

Trigger a filter search with that genre in the source.

### Actual behavior

Filter is applied correctly, but the search is not triggered.

**Edit: also the title (MangaDex) is gone, replaced with empty search text.**

### Tachiyomi version

r4963

### Android version

12

### Device

RMX3366

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by neurodiverseEsoteric** [comment]
Having the same issue for all of my installed extensions, including the ones that used to work (ie already supported such a feature)...
