### ISSUE TITLE
Crash when specific listing is loaded when browsing

### ISSUE THREAD

**Issue by Rhordric** [tachiyomiorg/tachiyomi#8096]
### Steps to reproduce

The listing causing this for me is in nhentai English Latest browse. Unsure what the listing is but it is at least at an index before 421579 as after scrolling past that listing the app will crash. This does not seem to be occuring on the stable App version 0.13.6

### Expected behavior

Shouldn't crash

### Actual behavior

Crash occurs after scrolling to specific listing but not before

### Crash logs

--------- beginning of main
09-26 23:20:26.974 24846 24892 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
09-26 23:20:52.849 24846 24846 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
09-26 23:20:52.849 24846 24846 E ACRA    : java.lang.IllegalStateException: ResultSet returned more than 1 row for mangas.sq:getMangaByUrlAndSource
09-26 23:20:52.849 24846 24846 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsOneOrNull(Query.kt:46)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invokeSuspend(AndroidDatabaseHandler.kt:44)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$awaitOneOrNull$2.invoke(AndroidDatabaseHandler.kt:13)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$3.invokeSuspend(AndroidDatabaseHandler.kt:35)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler$dispatch$3.invoke(AndroidDatabaseHandler.kt:13)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler.dispatch(AndroidDatabaseHandler.kt:162)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.AndroidDatabaseHandler.awaitOneOrNull(AndroidDatabaseHandler.kt:7)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.data.manga.MangaRepositoryImpl.getMangaByUrlAndSourceId(MangaRepositoryImpl.kt:10)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.domain.manga.interactor.GetManga.await$1(GetManga.kt:3)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter.access$networkToLocalManga(BrowseSourcePresenter.kt:103)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$getMangaList$1$2$1$1.invokeSuspend(BrowseSourcePresenter.kt:35)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-26 23:20:52.849 24846 24846 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
09-26 23:20:52.849 24846 24846 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@902f0, Dispatchers.Main]
09-26 23:20:55.951 28400 28400 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x40000000
09-26 23:20:55.953 28400 28400 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
09-26 23:20:56.073 28400 28434 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
09-26 23:20:56.079 28400 28441 E tachiyomi.debu: Loaded layer handle (1086726391148317363) for layer /my_product/lib64/libcolorx-loader.so
09-26 23:20:56.079 28400 28441 E tachiyomi.debu: Looking for entrypoint ColorX_Check
09-26 23:20:56.079 28400 28441 E tachiyomi.debu: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
09-26 23:20:56.080 28400 28441 E tachiyomi.debu: Check failed
--------- beginning of system
09-26 23:20:56.096 28400 28400 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-26 23:20:56.415 28400 28400 E tachiyomi.debu: sysOpen failed with error=Permission denied
09-26 23:20:56.488 28400 28509 E SQLiteLog: (284) automatic index on UR(manga_id)
09-26 23:20:56.488 28400 28509 E SQLiteLog: (284) automatic index on R(manga_id)
09-26 23:20:56.488 28400 28509 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6-4977 (standard, 56722140c, 86, 2022-09-26T21:30Z)
Android version: 12 (SDK 31)
Android build ID: LE2125_11_C.63
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus9Pro
Device model: LE2125
Device product name: OnePlus9Pro

### Tachiyomi version

0.13.6-4977

### Android version

Android 12

### Device

Oneplus 9 Pro 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does it still happen after clearing the database for that source from the advanced settings?

**Comment by Rhordric** [comment]
Seems fixed now
