### ISSUE TITLE
Bring back hiding appbar and navbar on scroll

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#8101]
### Describe your suggested feature

Appbar and navbar hiding on scroll in Library and Extensions screens is removed after the Compose rewrite.

We may want to bring it back when upstream blockers are cleared.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not exactly an upstream issue, I mostly just think the Compose implementation of it looks pretty ugly (it doesn't pan linearly, it collapses in height). If they change it, we could consider bringing it back.

**Comment by Palloxin** [comment]
https://user-images.githubusercontent.com/75091899/202176283-f5db9cd9-6a63-414e-b3d7-babe5b672488.mp4
video slowed down to 0.5 too from 0.14.2

can't its behaviour be copied from when i click on settings (bar disappear) and come back like in the video?

**Comment by stevenyomi** [comment]
> can't its behaviour be copied from when i click on settings (bar disappear) and come back like in the video?

The bottom nav bar will be rewritten in Compose eventually, so this won't be a permanent solution.

**Comment by arkon** [comment]
Closing for now, we can reconsider in the future if the out-of-the-box Compose stuff ever looks better.

**Comment by Palloxin** [comment]
did someone ask to devs of the compose language to fix it?
