### ISSUE TITLE
Pressing 🔍 in Library doesn't bring up Keyboard to type search query

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#8103]
### Steps to reproduce

1. Install r4977
2. Open app, click on the Search icon (🔍) at the top right portion
3. Install 0.13.6
4. Repeat Step 2 in 0.13.6

### Expected behavior

Both shoeld behave the same

### Actual behavior

In 0.13.6, clicking on search icon, starts search and brings up the keyboard
In r4977, the top bar changes to show the placeholder text (Search..) but the keyboard doesn't pop out. Tapping on the placeholder text brings up the keyboard

### Crash logs

NA

### Tachiyomi version

r4977

### Android version

12

### Device

SM-N770F

### Other details

Also happened in previous preview and latest Sy preview (r481)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ivaniskandar** [comment]
#8095
