### ISSUE TITLE
Ability to filter searches by number of uploaded chapters

### ISSUE THREAD

**Issue by Ghostypunchy** [tachiyomiorg/tachiyomi#8104]
### Describe your suggested feature

Example: 
You're looking to read a manga you know has 100 chapters, you are able to filter out any results that have less than 100 chapters uploaded.

But some manga also include bonus chapters and you don't want that, you can choose to view manga that have exactly 100 chapters uploaded
Or the option to say "from 90 up to 100 chapters" 

### Other details

Why is this helpful? 
It will vastly reduce results that are completely empty with 0 chapters, or results that have only a few random chapters uploaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
I don't this will be useful outside of the library since the chapter list isn't loaded until you tap into the entry.
