### ISSUE TITLE
Use System Language or English for non Android 13 users.

### ISSUE THREAD

**Issue by Ghostypunchy** [tachiyomiorg/tachiyomi#8105]
### Describe your suggested feature

The ability to set the apps language to either the phones system language or English.

Example: Settings > General > language: 
Option 1: English
Option 2: System language

And vice versa, woth option 1 being the default option when installing the app.

### Other details

This is solely under the assumption that the app is being developed in English, so I thought an option to use the apps default language wouldn't be that hard to implement. And if someone wants to use a different language, can use the systems language to change it. 

This seems like a possible and hopefully easy solution to implement that many people would appreciate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
0.13.6 always uses the system language.

The ability to change the language for Android < 13 was already added back in Preview.
