### ISSUE TITLE
Tachiyomi crashes when clearing MangaDex database

### ISSUE THREAD

**Issue by Alviannn** [tachiyomiorg/tachiyomi#8110]
### Steps to reproduce

1. My tachiyomi crashes when I tried opening the MangaDex latest browse, but I saw issue #8096 and decided to try the solution.
2. Open **More** > **Settings** > **Advanced**
3. Click on **Clear Database**
4. For my case, I have "7386 non-library manga in database", and proceeded to delete only that

### Expected behavior

The database is cleared

### Actual behavior

Tachiyomi crashes

### Crash logs

--------- beginning of system
09-29 13:17:45.867 17832 17832 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-29 13:19:27.645 19012 19012 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-29 13:54:44.841 12894 12894 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
09-29 14:25:47.777 22063 22063 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-29 14:25:49.285 22063 22219 E SQLiteLog: (284) automatic index on UR(manga_id)
09-29 14:25:49.285 22063 22219 E SQLiteLog: (284) automatic index on R(manga_id)
09-29 14:25:49.285 22063 22219 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-29 14:25:49.305 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.307 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.312 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.315 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.316 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.318 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.323 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.325 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.330 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.333 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.334 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.335 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.339 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.344 22063 22063 E ANR_LOG : >>> msg's executing time is too long
09-29 14:25:49.344 22063 22063 E ANR_LOG : Blocked msg = { when=-1s933ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction LaunchActivityItem,ResumeActivityItem hashCode, mActivityToken = android.os.BinderProxy@8cea86f mLifecycleStateRequest ResumeActivityItem{procState=-1,updateProcState=false,isForward=true} mActivityCallbacks [LaunchActivityItem{intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.main.MainActivity mCallingUid=1000 },ident=92585618,info=ActivityInfo{d7e7e3a eu.kanade.tachiyomi.ui.main.MainActivity},curConfig={1.0 ??mcc??mnc [en_US] ldltr sw360dp w360dp h704dp 480dpi nrml long hdr widecg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 76 - 1080, 2208) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1163080373899898913, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},overrideConfig={1.0 ??mcc??mnc [en_US] ldltr sw360dp w360dp h704dp 480dpi nrml long hdr widecg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 76 - 1080, 2208) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1163080373899898913, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},referrer=com.oppo.launcher,procState=20,state=null,persistentState=null,pendingResults=null,pendingNewIntents=null,profilerInfo=null,assistToken=android.os.BinderProxy@42d9aeb,rotationAdj=null}] } , cost  = 1630 ms
09-29 14:25:49.344 22063 22063 E ANR_LOG : >>>Current msg List is:
09-29 14:25:49.344 22063 22063 E ANR_LOG : Current msg <1> = { when=-1s906ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction TopResumedActivityChangeItem, hashCode, mActivityToken = android.os.BinderProxy@8cea86f mLifecycleStateRequest null mActivityCallbacks [TopResumedActivityChangeItem{onTop=true}] }
09-29 14:25:49.344 22063 22063 E ANR_LOG : Current msg <2> = { when=-1s899ms what=9999 target=android.app.ActivityThread$H }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <3> = { when=-1s869ms what=0 target=android.app.ActivityThread$H callback=com.android.internal.util.function.pooled.PooledLambdaImpl }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <4> = { when=-1s792ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <5> = { when=-1s778ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <6> = { when=-1s681ms what=0 target=android.os.Handler callback=org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <7> = { when=-1s550ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <8> = { when=-1s550ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <9> = { when=-1s541ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : Current msg <10> = { when=-1s540ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
09-29 14:25:49.345 22063 22063 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
09-29 14:25:49.352 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.355 22063 22102 E Parcel  : Reading a NULL string not supported here.
09-29 14:25:49.487 22063 22105 E libEGL  : Invalid file path for libcolorx-loader.so
09-29 14:25:49.546 22063 22105 E libEGL  : Invalid file path for libcolorx-loader.so
09-29 14:25:49.553 22063 22105 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.13.6-4977 (standard, 56722140c, 86, 2022-09-26T21:30Z)
Android version: 11 (SDK 30)
Android build ID: RMX1971_11_F.06
Device brand: realme
Device manufacturer: realme
Device name: RMX1971
Device model: RMX1971
Device product name: RMX1971

### Tachiyomi version

Preview r4977

### Android version

Android 11

### Device

Realme 5 Pro - RMX1971

### Other details

I'm not really sure whether this issue is caused by the MangaDex extension or Tachiyomi, so I want to apologize in advance if I'm wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is this still occurring? If so, can you make it crash and share the logs again?

**Comment by Alviannn** [comment]
Sorry, I can't seem to reproduce it since I did a reset to my Tachiyomi, so far it hasn't occurred again
