### ISSUE TITLE
Tachiyomi doesn't import the comicinfo.xml files after extracting them from the chapter files for local source.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8112]
### Steps to reproduce

1. Add a new series with chapters that have comicinfo.xml files in the root of their archives.
2. Open this series in local source extension.
3. Tachiyomi extracts the comicinfo.xml file from the root of the first chapter.

### Expected behavior

The info from the comicinfo.xml file shows up in tachiyomi while viewing the series.

### Actual behavior

The info that is in comicinfo.xml doesn't show inside tachiyomi while viewing the series.

### Tachiyomi version

Preview r4977

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

More information on [Discord](https://ptb.discord.com/channels/349436576037732353/694092459839455243/1025007578427699220).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Shamicen** [comment]
Some more details that may help:

- Building the newest master branch inside Android Studio still works as expected. 
- Tachiyomi successfully creates .noxml files if there is no ComicInfo file at the chapter root and also successfully copies them from the archives to the chapter root like @THElegend5 already said (tested only in r4977). 
- I couldn't see any errors in logcat while running the app.

My guess would be that the xmlutil dependency does not get build correctly. 

could also reproduce the issue in r4963
