### ISSUE TITLE
Optional performance optimization when updating chapters informations of very big mangas

### ISSUE THREAD

**Issue by luzfcb** [tachiyomiorg/tachiyomi#8115]
### Describe your suggested feature

Hello, I wish there was some way to mark a certain manga so that some possible performance optimization is applied.

## Problem:

The process of getting information about Martial Peak chapter updates from Mundo Webtoon Extension/Source takes 50 minutes on my Poco X3 Pro (8GB RAM) and makes it very hot.

The manga/webtoon of Martial Peak has more than 2600 published chapters, and the original novel finished with 6009 chapters

## A possible solution

I'll try to explain my idea:

First, let's get to the context:
I don't know what the implementation details of the chapter update process are.

I can assume that currently, the crawler goes to the manga page and/or API and iterates over each page, extracts information about each chapter from each page and checks which chapters exist in the local database and which do not exist, and add them to the local database as unread, and marks them for download.

I also assume that the update crawler always goes through the entire list of chapters from the beginning.

### The solution idea

Instead of always going through the entire list of chapters, follow the following flow:

1 - Check if there is a previous cache with information from the last page obtained by the crawler.

  A - If the cache exists, try to start the crawler from the page informed in the cache. If 404 or other error is reported, then stop and start step B.

  B - If the cache does not exist, run the crawler as it is run today and on the last page obtained by the crawler, save the page information in the cache so that it can be used.

Pros: By saving informations about the last page/chapters downloaded, and starting extracting information from the last page, there will probably be a performance gain and less load on the source website.

Cons: Some sources sometimes publish intermediate chapters, which may appear on pages before the last one, and because of this, the crawler may not get information about these chapters if this optimization is enabled. That's why I think this should be an optional feature, manually activated per-manga.

That said, thanks for everyone's great work on this app.

### Acknowledgements

- [X] I have searched the existing issues, and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Mundo Webtoon only do one request to the manga details page and gets the chapters, it isn't even paginated, it's a single request. I just tried to refresh the entry now (same thing the updater does) and it loaded instantaneously.

You may want to try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#troubleshooting).

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/pt/mundowebtoon/src/eu/kanade/tachiyomi/extension/pt/mundowebtoon/MundoWebtoon.kt#L118-L126

**Comment by alessandrojean** [comment]
Inspecting a little more, this seems to be a upstream issue with Jsoup, as it for some reason fails to parse large HTML strings from this website in particular. This issue was already documented before as can be seen in tachiyomiorg/tachiyomi-extensions#10344.

> Some titles with a lot of chapters causes the Jsoup parsing to be extremely slow.

Not sure it's something that can be fixed either on the extension side or in the app side.

**Comment by luzfcb** [comment]
@alessandrojean Thanks for the quick response. 

I cleared all possible [cache options](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis), however, the general update (which updates all manga) still spends the same very long time on Martial Peak

**Comment by luzfcb** [comment]
@alessandrojean Maybe try to update the version of Jsoup to 1.15.3, since almost all release notes after 1.13.1 cite performance improvements.

If you want and have time and can create an APK with an updated version of Jsoup I can test it. ( assuming this isn't too complicated to do and Jsoup hasn't introduced a break of behavior/API Contract )

**Comment by alessandrojean** [comment]
We can't update to `1.15.3` yeat as last Stable version uses `1.14.3`, only Preview uses `1.15.3`. But on a second thought, it shouldn't matter that much as the extensions only uses the signatures (Gradle `api`), the code itself used is inside the app. I tested in Preview which has the most updated Jsoup available and it still have this issue, so yeah, nothing we can do for now.

However, you can test this by checking if it's happening in the Preview version of the app. Download it by visiting the [website](https://tachiyomi.org/download/) and choosing Preview.

**Comment by alessandrojean** [comment]
Good news, @luzfcb, managed to narrow down the issue. Some CSS selectors used to parse the manga details were making Jsoup to struggle for no apparent reason in this particular website. I changed them, and now it's loading instantaneously again. Wait for an extension update with the fix :)

**Comment by luzfcb** [comment]
@alessandrojean thankyou a lot :pray:
