### ISSUE TITLE
Security lock can be bypassed if not set to "Always"

### ISSUE THREAD

**Issue by Enzycal** [tachiyomiorg/tachiyomi#8128]
### Steps to reproduce

1. Open Tachiyomi 
2. Go to home screen and wait for Tachiyomi to lock
3. Open it via the recent apps menu
4. When prompted for fingerprint / pass / etc. press the recent apps button again
5. Select Tachiyomi

### Expected behavior

It should require authentication if it wasn't unlocked within the set amount of time. 

### Actual behavior

Tachiyomi security lock got bypassed without authentication. 

### Crash logs

--------- beginning of main
10-01 19:15:30.052 17622 17622 E UnlockActivity: Authentication cancelled
10-01 19:19:06.702 11392 11392 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-01 19:19:06.706 11392 11392 E USNET   : USNET: appName: eu.kanade.tachiyomi
10-01 19:19:07.363 11392 11572 E SQLiteLog: (283) recovered 66 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
10-01 19:19:07.388 11392 11573 E SQLiteLog: (284) automatic index on C(manga_id)
10-01 19:19:07.388 11392 11573 E SQLiteLog: (284) automatic index on R(manga_id)
10-01 19:19:07.388 11392 11573 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-01 19:19:27.644 11826 11826 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-01 19:19:27.646 11826 11826 E USNET   : USNET: appName: eu.kanade.tachiyomi
10-01 19:19:28.230 11826 11953 E SQLiteLog: (284) automatic index on C(manga_id)
10-01 19:19:28.230 11826 11953 E SQLiteLog: (284) automatic index on R(manga_id)
10-01 19:19:28.230 11826 11953 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-01 19:19:29.598 11826 11826 E UnlockActivity: Authentication cancelled
10-01 19:19:32.163 11826 11826 E UnlockActivity: Authentication cancelled
10-01 19:19:38.635 11826 11826 E UnlockActivity: Authentication cancelled
10-01 19:19:57.487 12161 12161 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
10-01 19:19:57.490 12161 12161 E USNET   : USNET: appName: eu.kanade.tachiyomi
10-01 19:19:58.029 12161 12286 E SQLiteLog: (284) automatic index on C(manga_id)
10-01 19:19:58.029 12161 12286 E SQLiteLog: (284) automatic index on R(manga_id)
10-01 19:19:58.029 12161 12286 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-01 19:21:49.445 12161 12161 E UnlockActivity: Authentication cancelled
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N975FXXU8HVGA
Device brand: samsung
Device manufacturer: samsung
Device name: d2s
Device model: SM-N975F
Device product name: d2seea

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

Bug is encountered if the "Lock when idle" setting is set to anything else beside "Always".

https://user-images.githubusercontent.com/45462298/193421889-08c56a1b-3bb9-4836-9939-820da9818e90.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Fixed in preview. Wait for next stable update

**Comment by Enzycal** [comment]
My bad, thanks!
