### ISSUE TITLE
Navigating up twice from search result triggers empty search

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#8132]
### Steps to reproduce

Open a souce and search something. Navigate up to see query in title bar. Navigate up again.

### Expected behavior

Return to Browse screen.

### Actual behavior

Triggers an empty search with empty filters.

### Tachiyomi version

r5003

### Android version

Android 12L

### Device

Emulator

### Other details

Regression from previous preview versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
This is intended behavior.

**Comment by stevenyomi** [comment]
@arkon This should not be closed. We should fix this as many sources can't properly handle an empty search with empty filters.
