### ISSUE TITLE
Show the first volume cover instead of the last volume cover

### ISSUE THREAD

**Issue by PleskarjevJanez** [tachiyomiorg/tachiyomi#8133]
### Describe your suggested feature

An option should exist that automatically replaces all cover arts (in the library and while browsing trough manga extensions) with the cover art of the first volume (instead of how it is now, where all cover arts are of the manga's last volume). This would be usefull for people who don't want to see spoilers especially if the manga in question has ended, or want to savour the feeling of seeing  the last cover art after reading all the previous volumes.

The easiest solution to this would be to just use the first page as the cover art, since normally that is the cover art for the first volume. But you could also use some manga database sites to get first volume cover arts from or even somehow get it from the extension website itself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
If the particular source has that ability on the website, request it in the extensions repo.

If not, just edit the cover yourself.

**Comment by PleskarjevJanez** [comment]
> 
I already do edit the cover myself but even then its impossible to not see the cover art
