### ISSUE TITLE
Library sorting issues 

### ISSUE THREAD

**Issue by kevin01523** [tachiyomiorg/tachiyomi#8137]
### Steps to reproduce

Open tachiyomi
Try changing sorting by date added

### Expected behavior

Library would be sorted by date added

### Actual behavior

Library manga would be sorted by first added or last added
Its sorted alphabetical and doesn't change

### Crash logs

N/a

### Tachiyomi version

App version: 0.13.6-5003 (standard, 6be9cccc7, 86, 2022-10-01T21:11Z) 

### Android version

Android version: 10 (SDK 29) 

### Device

Android build ID: lineage_twolip-userdebug 10 QQ3A.200805.001 10035824 Device brand: Xiaomi Device manufacturer: Xiaomi Device name: twolip Device model: Redmi Note 6 Pro  Device product name: lineage_twolip

### Other details

As per title library sorting is broken

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed by #8145
