### ISSUE TITLE
Tachiyomi crashes on migrating and mass adding manga to library.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8144]
### Steps to reproduce

1. Find a manga to migrate.
2. Migrate to a new source. (is komga in my case)

### Expected behavior

There is no crash.

### Actual behavior

Tachiyomi crashes.

### Crash logs

--------- beginning of system
--------- beginning of main
10-04 01:44:40.459 20618 20618 E InputMethodManager: ABORT input: ServedView must be attached to a Window
10-04 01:44:41.184 20618 20771 E CursorWindow: Failed to read row 2370, column 0 from a CursorWindow which has 2370 rows, 13 columns.
10-04 01:44:41.186 20618 20618 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
10-04 01:44:41.186 20618 20618 E ACRA    : java.lang.NullPointerException
10-04 01:44:41.186 20618 20618 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-04 01:44:41.186 20618 20618 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
10-04 01:44:41.186 20618 20618 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6a39775, Dispatchers.Main.immediate]
10-04 01:44:41.447 21315 21315 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
10-04 01:44:41.606 21315 21356 E SQLiteLog: (283) recovered 93 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
10-04 01:44:43.797 21521 21521 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
10-04 01:44:44.025 21521 21553 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
10-04 01:44:45.159 21521 21758 E SQLiteLog: (284) automatic index on UR(manga_id)
10-04 01:44:45.159 21521 21758 E SQLiteLog: (284) automatic index on R(manga_id)
10-04 01:44:45.159 21521 21758 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6-5003 (standard, 6be9cccc7, 86, 2022-10-01T21:11Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur
Device model: Redmi Note 9 Pro Max
Device product name: excalibur_in

### Tachiyomi version

Preview r5003

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

The crash happens about 95 percent of the time if migrating to an unopened manga in the new source and about 40 percent of the time if you open the manga first before migrating.
This also happens when you mass add titles to the library (this didn't happen the last two times I did so, source is komga and adding about 2-6 titles in 2-3 secs).
There are no obsolete extensions installed as I think there was a bug which caused a crash if there is a obsolete extension so that isn't a case here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrotedd** [comment]
I couldn't reproduce the error, could you be more specific about the steps to reproduce it?

**Comment by THElegend5** [comment]
> I couldn't reproduce the error, could you be more specific about the steps to reproduce it?

There aren't really any steps , it just crashes on migrating to a different source. Easiest way to reproduce it for me was to an already opened manga is to just migrate 2-3 times and it will crash. And it crashes pretty much every time if you migrate to something that hasn't been opened yet.

**Comment by arkon** [comment]
I can't reproduce this either. Can you share newer crash logs after reproducing a crash again?

**Comment by THElegend5** [comment]
> I can't reproduce this either. Can you share newer crash logs after reproducing a crash again?

--------- beginning of system
--------- beginning of main
10-15 01:21:52.796 25696 25941 E CursorWindow: Failed to read row 2369, column 0 from a CursorWindow which has 2369 rows, 13 columns.
10-15 01:21:52.801 25696 25696 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
10-15 01:21:52.801 25696 25696 E ACRA    : java.lang.NullPointerException
10-15 01:21:52.801 25696 25696 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-15 01:21:52.801 25696 25696 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
10-15 01:21:52.801 25696 25696 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5d9598, Dispatchers.Main.immediate]
10-15 01:21:53.020 27206 27206 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
10-15 01:21:53.198 27206 27233 E SQLiteLog: (283) recovered 744 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
10-15 01:21:54.526 27304 27304 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
10-15 01:21:54.705 27304 27343 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
10-15 01:21:55.767 27304 27502 E SQLiteLog: (284) automatic index on UR(manga_id)
10-15 01:21:55.767 27304 27502 E SQLiteLog: (284) automatic index on R(manga_id)
10-15 01:21:55.767 27304 27502 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.6-5018 (standard, 4b4be58d0, 86, 2022-10-08T21:11Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur
Device model: Redmi Note 9 Pro Max
Device product name: excalibur_in

**Comment by THElegend5** [comment]
I did a little more replicating and this seems to happen if a series updates the moment after migrating on it's own.

**Comment by THElegend5** [comment]
@arkon this crash doesn't seem to have been happening anymore.
Things that have changed.
Updated to preview r5071
Also updated my android version from 11 to 12.
