### ISSUE TITLE
MangaRaw Extension NXDOMAIN

### ISSUE THREAD

**Issue by ilary1995** [tachiyomiorg/tachiyomi#8148]
### Steps to reproduce

1. I select one of the mirror (mangaraw.co, mangaraw.lol or mangarawjp.com)
2. I select one of the last manga to reader
3. When i chose the chapter to read, the error mangaraw.lolhttps: NXDOMAIN

### Expected behavior

the pages of the selected chapter should appear

### Actual behavior

clicking on the chapter you want to read, the error mentioned above appears

### Tachiyomi version

0.13.6

### Android version

13

### Device

Xiaomi 11

### Other details

Maybe the addresses of the three sites have changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> * [x] If this is an issue with an extension, I should be opening an issue in the extensions repository.
