### ISSUE TITLE
Chapter download state not updated when deleted when marked as read

### ISSUE THREAD

**Issue by MadMan247** [tachiyomiorg/tachiyomi#8149]
### Steps to reproduce

1. Enable more > settings > downloads > delete chapters > after manually marked as read
2. Download a chapter of a manga that has a chapter above it
3. Hold down to select the chapter above the downloaded chapter
4. Press the "mark previous as read" button

### Expected behavior

The chapter should be deleted.

### Actual behavior

The chapter remains, unmodified.

### Tachiyomi version

App version: 0.13.6-5003 (standard, 6be9cccc7, 86, 2022-10-01T21:11Z)

### Android version

Android version: 12 (SDK 31)

### Device

Device model: SM-G781V Device product name: r8qsqw | "Samsung Galaxy S20 FE 5G" 

### Other details

[Video Example](https://user-images.githubusercontent.com/54383546/194221031-a6dfc18b-f449-4776-bfea-659421b2b41e.mp4) 

Please note that, as is demonstrated in the video, this function still works when chapters are individually selected. It is strictly the "mark previous as read" that is nonfunctional. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Btw can you check if leaving the manga screen for a few secs and opening it again still shows it as downloaded or not.

**Comment by MadMan247** [comment]
I see; I should have tested with wifi off to verify that it wasn't being deleted. Should I close this issue then? Will you guys handle that? I am new to this, so please understand.

**Comment by alessandrotedd** [comment]
I fixed it and opened a pull request, I noticed that the problem was the download icon not updating right away, but the chapter was indeed being deleted, you could see that by going back and reopening the same chapter list screen.

**Comment by arkon** [comment]
As noted in #8150:

The state change is actually [faked](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt#L686) when you explicitly delete something since the download state is normally consumed via a provider rather than an actual change on the model itself due to the (external) way that the download states are tracked.

I think we'd need to either fake the status change here too, or figure out a way to have the "real" download states actually be part of the state objects being composed.

**Comment by arkon** [comment]
Fixed for next preview build.
