### ISSUE TITLE
scroll indicator not moving in browse

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8151]
### Steps to reproduce

1. Go to browse
2. Scroll the sources list

### Expected behavior

Scroll indicator on the right side should move with the scrolling 

### Actual behavior

It stays where it is until you stop scrolling 

### Tachiyomi version

r5003

### Android version

12 

### Device

Tecno spark 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ivaniskandar** [comment]
#8139
