### ISSUE TITLE
Reaper Scans Domain Changed

### ISSUE THREAD

**Issue by SantanuLayek** [tachiyomiorg/tachiyomi#8152]
### Steps to reproduce

Reaper Scans Changed their Domain recently, But the tachiyomi extension has been missing the extension update since a couple of days.

### Expected behavior

Expected Behaviour would have been that tachiyomi gets the chapter updaters from reaper scans

### Actual behavior

error 405

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Oppo F19 pro+

### Other details

Please update the reaperscans extension as fast as possible as I am missing out on the mangas released by reaper scans.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Actually read the acknowledgements next time please.

**Comment by SantanuLayek** [comment]
If the issue is completed, where's the extension update? Please update as
soon as possible... 🙏🏻🙏🏻🙏🏻😭😭😭

**Comment by SantanuLayek** [comment]
And really sorry.
