### ISSUE TITLE
Keyboard doesn't go away on opening a manga after search.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8157]
### Steps to reproduce

1. Search for a manga.
2. Open the manga.

### Expected behavior

Keyboard goes away.

### Actual behavior

Keyboard is still there on opening a manga after search.

### Tachiyomi version

Preview r5003

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

The category tab also seems to be smaller due to this on opening the manga.

https://user-images.githubusercontent.com/63903377/194705649-7e9fee63-a9e6-4e09-a928-e8a7febd46d3.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by d-najd** [comment]
Seems like easy starter issue, I will work on this

**Comment by arkon** [comment]
You could probably just always hide the keyboard in the `*ComposeController`s' `onChangeStarted` hook (or another appropriate lifecycle hook).

**Comment by d-najd** [comment]
> You could probably just always hide the keyboard in the `*ComposeController`s' `onChangeStarted` hook (or another appropriate lifecycle hook).

Thanks, I will look into it once android studio has finished updating.
