### ISSUE TITLE
No Pages Found

### ISSUE THREAD

**Issue by Kreideprinz05** [tachiyomiorg/tachiyomi#8161]
### Steps to reproduce

When I open some chapters of manga from the extension of Mangabuddy, It says "No Pages Found" even though the website is still working fine

### Expected behavior

I expected to show the pages of chapter that I will open

### Actual behavior

But when I open the chapters of the manga from the extension of Mangabuddy it always says, "Bo Pages Found"

### Crash logs

Nothing

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Realme C15

### Other details

Pls fix the issue of "No Pages Found" from the extension of Mangabuddy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
