### ISSUE TITLE
Download queue starts if you open a to be downloaded chapter while library update is ongoing.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8172]
### Steps to reproduce

1. Start a library update with download new chapters setting turned on.
2. While the library update is going find a new chapter which is to be downloaded , open it and then close it.

### Expected behavior

The download queue remains paused while the library is still updating.

### Actual behavior

The download queue starts while the library update is still ongoing.

### Tachiyomi version

Preview r5018

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

This might also be the case with pausing a download queue even without a library update going on and going to read a chapter which you have to set to download. Also in my case the chapter I opened was a new chapter in a manga I have read the rest of the chapters of if that makes a difference.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
> This might also be the case with pausing a download queue even without a library update going on and going to read a chapter which you have set to download.
Just confirmed this also happens.

**Comment by arkon** [comment]
Closing in favor of #7492
