### ISSUE TITLE
Changing display badges setting doesn't get reflected immediately.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8174]
### Steps to reproduce

1. Open your library.
2. Change the badge settings under display such as show download badge and so.

### Expected behavior

The changes get reflected immediately.

### Actual behavior

The changes require scroll/ changing the category/ going to update section and such to reflect.

### Tachiyomi version

Preview r5018

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

https://user-images.githubusercontent.com/63903377/194746340-83b4c003-67a3-47e2-a7a0-a7448a045e83.mp4

This might be an issue for users who have just started using tachiyomi and have really small libraries and have changed the badges but it doesn't show any change in badges in the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Platiplus** [comment]
Gonna try to take a shot at this!
