### ISSUE TITLE
Mangahub isnt working 

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi#8178]
### Steps to reproduce

Chapters missing, no updates and many more

### Expected behavior

Should be uptodate with chapters but not happening

### Actual behavior

Missing chapters 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Huawei P30 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

also hub was removed
