### ISSUE TITLE
Search during migration doesn't work if manga name includes a question mark

### ISSUE THREAD

**Issue by makemefeelgr8** [tachiyomiorg/tachiyomi#8183]
### Steps to reproduce

1. Find a manga that has a question mark in it's name, like "What do I do now?"
2. Add it to your library
3. Migrate it to another source

### Expected behavior

It should... just work, I guess? Migrate?

### Actual behavior

Search just spins and spins and never ends.

### Tachiyomi version

0.13.6

### Android version

12

### Device

Galaxy Tab S7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce. Search abilities are source-dependant so if it's particular sources that aren't handling search properly, open issues in the extensions repo.
