### ISSUE TITLE
Mangapuma not loading 

### ISSUE THREAD

**Issue by lelouchTzero** [tachiyomiorg/tachiyomi#8189]
### Steps to reproduce

Open mangapuma extension 

### Expected behavior

Should show latest updated manga

### Actual behavior

Shows java.security.cert.CertPathValidatorExeption: trust anchor for certification path not found

### Tachiyomi version

Stable 0.13.6

### Android version

Android 11

### Device

Samsung s10+

### Other details

![Screenshot_20221011-093824_Tachiyomi](https://user-images.githubusercontent.com/112708780/195042093-20a1d8e9-14c7-4014-a6d8-28d6c3482989.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lelouchTzero** [comment]
Solved itself

**Comment by lelouchTzero** [comment]
Problem returned

**Comment by MrAndre96** [comment]
This should probably be opened as issue in the extensions repo on not this one
