### ISSUE TITLE
Bulk Export Manhwa/Manga Covers and Titles

### ISSUE THREAD

**Issue by jonsarz16** [tachiyomiorg/tachiyomi#8190]
### Describe your suggested feature

An option that lets you export the covers of all manhwa in the library to your gallery. 

An option that lets you export the titles of all manhwa in the library to your gallery as an image. Rather than taking snapshots everytime i recommend to other users. Very useful to avoid removal of extensions.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Removing an extension does not remove any manga from your library. Nor does the source's removing any manga. You can migrate invalid manga to other sources within the app.

I don't think exporting a title list is useful, and neither is taking screenshots.

**Comment by stevenyomi** [comment]
Sharing multiple titles sounds very niche and I think you should keep with sharing screenshots.
