### ISSUE TITLE
Download batch not queueing

### ISSUE THREAD

**Issue by DgitalTrex** [tachiyomiorg/tachiyomi#8192]
### Steps to reproduce

Select multiple mangas for download
Click download

### Expected behavior

latest chapteres to be queued on the download page

### Actual behavior

Nothing happens

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Blackshark 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Can you show a screenshot of your Download Queue or a video recording

**Comment by DgitalTrex** [comment]
I can't send a video lol. But it acts as if they're already downloaded for
some reason. Is there a code that checks for that? If you download an
already downloaded chapter, nothing happens. this is the same behavior

**Comment by arkon** [comment]
#7492 is tracking several issues, so I'll close in favor of that.

That said, newer versions have rewritten UI bits that better indicate the current download status than before so this may be a non-issue now.
