### ISSUE TITLE
Double clicking the back button quickly from the Updates page makes the filter sheet appear

### ISSUE THREAD

**Issue by von-wa** [tachiyomiorg/tachiyomi#8196]
### Steps to reproduce

1. Go to Updates page
2. double click back button quickly

### Expected behavior

Exit the app

### Actual behavior

Return to library and filter sheet appear

### Tachiyomi version

r5018

### Android version

Android 8

### Device

Samsung galaxy A5 2017

### Other details

Similar to  #7603 but only happens from the Updates page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce in newer version.
