### ISSUE TITLE
Reset previous filter list state when performing genre search

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8199]
### Steps to reproduce

NSFW Warning due to Nhentai example
https://user-images.githubusercontent.com/75091899/195790196-f69f1b46-227f-4b7b-be51-881f8f762f57.mp4
NSFW Warning due to Nhentai example
1.add in the tag bar (filter) this   -futanari,-tentacles,-yaoi,-lolicon,-shotacon,mother,-blackmail
2. set the "filter by pages" to 25 and start the search
3. pick a manga
4. click on a genre (tag)
5. the result of the search will have the filter applied before ( so no futanari no tentacles etc..) AND all the entries will have 25 pages

### Expected behavior

The app should do the search without applying the previous filters

### Actual behavior

The app does the search applying the previous filters

### Tachiyomi version

0.13.6

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

 I don't know if it was programmed that way intentionally, but when one clicks on the genre tag the app should show ALL the entries of that genre ignoring the page limit and other parameters of the filter applied before.
 in the video above i used the artist-tag instead. the main tachi doesn't have it but with that artist the results should show a lot more entries than one. i tested it with genres and the issue is is still there no worries

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
/edit-title "Use previous filter list state when performing genre search"

**Comment by stevenyomi** [comment]
/edit-title "Reset previous filter list state when performing genre search"

**Comment by stevenyomi** [comment]
This is already the default behavior since #8762.
