### ISSUE TITLE
App won't start the first time, have to manually close it 2-3 times to open the app

### ISSUE THREAD

**Issue by Cnwarry** [tachiyomiorg/tachiyomi#8202]
### Steps to reproduce

Close the app completely, then open it, it freezes on the logo, bring up the app and swipe it away, repeat 2-3 time until the app opens

### Expected behavior

The app starts normally

### Actual behavior

The app freezes the phone and requires that it's closed

### Crash logs

https://pastebin.com/GBPSfjgp

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samung Galaxy A52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Error logs only show some storage-related issues (lack of permissions or space maybe, or a bad SD card).

Not sure if still relevant.
