### ISSUE TITLE
Allow selecting a different file picker while setting backup location

### ISSUE THREAD

**Issue by TissuePowder** [tachiyomiorg/tachiyomi#8203]
### Describe your suggested feature

I found a related issue here https://github.com/tachiyomiorg/tachiyomi/issues/1349

I use custom ROM (pixel experience) on a xiaomi device and somehow borked the stock file explorer app. It keeps crashing whenever I try to start it, so I just use other file managers like mixplorer and removed the stock file app.

While tachiyomi lets me select an arbitrary file picker in the `create backup` and `restore backup` options, it doesn't let me do that in `backup location` option. Whenever I tap on `backup location`, it keeps showing me "No file picker app found".

I guess it would be great if this issue is solved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You should report to your ROM dev that the ROM isn't handling `Intent.ACTION_OPEN_DOCUMENT_TREE` properly.
