### ISSUE TITLE
Extension isnt responding

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi#8204]
### Steps to reproduce

Connection to the extension isn't responding

### Expected behavior

Should able to view the website but no signs. 

### Actual behavior

Error msg "chapmanganato.com" comes whenever I try to read a manhwa or I go search on the extension list. Basically all the extension list failed to respond. 

### Crash logs

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 10 (SDK 29)
Android build ID: MAR-L21MEB 10.0.0.273(C185E3R3P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWMAR
Device model: MAR-LX1A
Device product name: MAR-LX1A

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Huawei P30 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Wrong repository.
