### ISSUE TITLE
Stable release blockers

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#8224]
Final couple things that need to be addressed before we can ship a stable release.

- [ ] [Everything with the label](https://github.com/tachiyomiorg/tachiyomi/issues?q=is%3Aissue+is%3Aopen+label%3A%22Stable+release+blocker%22)
- [ ] ~~Select all, inverse and range selection doesn't respect search query in library~~ pulled out to #8287
- [x] With #8186 you can now select one manga from two categories (@AntsyLich working on this)
- [x] Tweak crash screen top padding
- [x] Tweak settings font sizes to fit in with the rest of the app UI
- [x] Tweak settings transitions to fit in with the rest of the app UI
- [x] Disable auto complete in tracker login password field
- [x] Disable/hide reader split tall pages
- [x] Duplicate keys in extensions/sources/updates list
- [ ] Other major logged crashes in ACRA
- [ ] Just before a release:
  - [ ] Merge translations
  - [ ] Update baseline profile

**Comment by d-najd** [comment]
@arkon do you mind giving some info on the unfixed issues mentioned above (preferably all).
 I am willing to attempt to fix all of them but I can't figure out what exactly you mean in most of them 🤔

**Comment by arkon** [comment]
> Select all, inverse and range selection doesn't respect search query in library

The mentioned actions are performed on the "full" set (based on normal filters) of library category items rather than the additionally filtered set (based on the text search query).

---

> Duplicate keys in extensions/sources/updates list

There's crashes like `Key extension--1910632571 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.` but it's quite random when trying to reproduce it. It mostly happens with the extensions list and 4138a17e29348c7057ae885a0b8d9d5c3f29cc07 _might_ help.

---

The last few items are things that I'd need to personally address.

**Comment by d-najd** [comment]
> Duplicate keys in extensions/sources/updates list

I think using `itemsIndexed` instead of `items` (line 119 `ExtensionsScreen`) should solve the issue, another alternative I could think of is using the index of the item in the calculation of the key or perhaps random UUID, worst case scenario we should end up with the same extension twice instead of the entire app crashing. what do you think @arkon?

**Comment by arkon** [comment]
Indexing the items sort of defeats the purpose of the lazy column. I've already verified that the underlying list doesn't actually include duplicate items, it's an actual issue with Compose rendering.
