### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by FeralWriting** [tachiyomiorg/tachiyomi#8230]
### Steps to reproduce

1. Have a manga update
2. Refresh the library
3. It won't show up as updated in the updates window

### Expected behavior

1. Have a manga update
2. Refresh the library
3. It shows up as updated in the updates window

### Actual behavior

Doesn't show as updated in the updates window. You have to manually refresh every manga in the library to get the updates to show.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries

**Comment by FeralWriting** [comment]
How do I change those settings, because it isn't feasible for me to go through thousands of chapters to mark them as read so I can actually see the updates.

**Comment by alessandrojean** [comment]
You can just select them in your library and tap _Mark as read_ (refer to the second image).

![image](https://user-images.githubusercontent.com/14254807/196321321-6dd3390c-accc-4744-a0a7-e65f103b0b02.png)

**Comment by FeralWriting** [comment]
Thank you, on my device the buttons have no labels and only have pictures,
so I didn't know that button existed.

**Comment by curche** [comment]
You can tap and hold on any such icon and it should have a text pop up like in the screenshot
