### ISSUE TITLE
Going to a different tab causes library to cold boot.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8236]
### Steps to reproduce

1. Open tachiyomi and let tachiyomi load completely.
2. Go to a different tab such as updates and come back to library tab or just stay at updates tab.

### Expected behavior

Library doesn't have to load again and again after first boot.

### Actual behavior

Library loads again every time the tab changes even after first boot.

### Tachiyomi version

Preview r5062

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

https://user-images.githubusercontent.com/63903377/196432182-e7ce41d7-7434-479d-8125-1cd9738e83de.mp4

This might be related to #8222 .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by atmazzerexe** [comment]
Just wanted to add that this bug also make Library to load much slower than before.
Library with more than 1000+ entries used to be able to load within 5-10 seconds. Now, it will take more than 2 minutes if it's you open Tachiyomi from cold start.

**Comment by THElegend5** [comment]
> Just wanted to add that this bug also make Library to load much slower than before. Library with more than 1000+ entries used to be able to load within 5-10 seconds. Now, it will take more than 2 minutes if it's you open Tachiyomi from cold start.

Yep can confirm but for it is more like from 15 secs to 30 secs on a ~3000 title library.
