### ISSUE TITLE
Require Unlock feature not working properly

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#8247]
### Steps to reproduce

1. Turn on "Require Unlock" setting in "Security" section
2. Close Tachiyomi app
3. Clear cache
4. Open app, it will ask for password (I have fingerprint lock)
5. Tap on black screen above the prompt, it will close the app
6. Open the app again and it won't ask for password

### Expected behavior

Tachiyomi should ask for password every time the app opens

### Actual behavior

App opens without asking for password

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9822555/tachiyomi_crash_logs.txt)

### Tachiyomi version

r5071

### Android version

Android 11

### Device

Redmi Note 8

### Other details

This issue is same as #7961 and #8128, both the issues are marked as completed but the problem still persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce this, even on a device with MIUI 12. Do you have a video?

**Comment by EdwinRodger** [comment]
https://user-images.githubusercontent.com/92982808/197121964-381b4bac-51f2-4060-80a1-9d3027209cb8.mp4

The screen recorder wasn't recording the screen lock so I have to take video from another device

**Comment by M9k** [comment]
Just tried on my Redmi Note 7 and it works fine.
Android 10, MIUI 12 china 12.5.7.0 stable.
Maybe it's related with MIUI 12 with Android 11?

**Comment by atmazzerexe** [comment]
Can confirm this is not related to MIUI. Tested both on Android 11 (My Phone) and Android 9 (Emulator) using r5085 release, if "Lock when idle" options set to "Never", the only way lock screen will activate is by force closing Tachiyomi, so it will make Tachiyomi to do cold start. Exitting Tachiyomi the normal way won't trigger lock screen.

https://user-images.githubusercontent.com/14852623/197326384-586a8d54-4a19-4f04-b226-a3f8e6f362f6.mp4

**Comment by AntsyLich** [comment]
That is how "Never" works. If you want it to *always* to close after you close the app then set it to *always"

**Comment by AntsyLich** [comment]
@EdwinRodger what options have you chose in settings?

**Comment by atmazzerexe** [comment]
> @atmazzerexe that is how "Never" works. If you want it to _always_ close after you close the app then set it to _always_
"Always" will always trigger lock screen even when you minimize the app, not only just when you closed the app. The old behaviour was "Never" will still trigger lock screen if you closed the app normally.

**Comment by EdwinRodger** [comment]
> @EdwinRodger what options have you chose in settings?

Lock when idle: Never

I think because of this setting the whole issue is happening

When I set it to Always, the app it working as intended so maybe it's partially my fault for not understanding the setting 😅

Also it would be good if you can elaborate this setting because I didn't understood this feature
