### ISSUE TITLE
Invalid Download location 

### ISSUE THREAD

**Issue by Eijar** [tachiyomiorg/tachiyomi#8249]
### Steps to reproduce

Add new chapter to download
go to download tab
error: No internet connection
![Screenshot_2022-10-20-08-49-09-17_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/71017787/196831208-9aeb6509-0485-448d-a760-ed12e6592211.jpg)

produce invalid download location when turning off wifi
![Screenshot_2022-10-20-08-49-22-58_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/71017787/196831040-bcdfa074-1aeb-4616-a912-152d0e331644.jpg)

### Expected behavior

should download

### Actual behavior

can't download 

### Crash logs

--------- beginning of main
10-20 08:40:20.403 19178 19178 E Parcel  : Reading a NULL string not supported here.
10-20 08:41:09.038 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-20 08:41:10.492 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-20 08:41:20.078 19178 19178 E Parcel  : Reading a NULL string not supported here.
10-20 08:41:22.976 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-20 08:41:42.181 19178 19178 E Parcel  : Reading a NULL string not supported here.
10-20 08:41:47.068 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-20 08:41:49.073 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 12 (SDK 31)
Android build ID: RMX3085_11_C.12
Device brand: realme
Device manufacturer: realme
Device name: RMX3085L1
Device model: RMX3085
Device product name: RMX3085T2

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Realme 8 RMX3085

### Other details

i actually downloaded 10 chapter earlier and it successfully downloaded but the next chapter produce that error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Eijar** [comment]
> ### Steps to reproduce
> Add new chapter to download go to download tab error: No internet connection ![Screenshot_2022-10-20-08-49-22-58_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/71017787/196830988-1890c121-1bbc-41a4-b0d2-e30b60faac43.jpg)
> 
> produce invalid download location when turning off wifi ![Screenshot_2022-10-20-08-49-22-58_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/71017787/196831040-bcdfa074-1aeb-4616-a912-152d0e331644.jpg)
> 
> ### Expected behavior
> should download
> 
> ### Actual behavior
> can't download
> 
> ### Crash logs
> --------- beginning of main 10-20 08:40:20.403 19178 19178 E Parcel : Reading a NULL string not supported here. 10-20 08:41:09.038 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect() 10-20 08:41:10.492 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect() 10-20 08:41:20.078 19178 19178 E Parcel : Reading a NULL string not supported here. 10-20 08:41:22.976 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect() 10-20 08:41:42.181 19178 19178 E Parcel : Reading a NULL string not supported here. 10-20 08:41:47.068 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect() 10-20 08:41:49.073 19178 22358 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect() App version: 0.13.6 (standard, [1f79444](https://github.com/tachiyomiorg/tachiyomi/commit/1f79444a531d0f4ec93cc953f3d82ea3c1094471), 82, 2022-08-14T15:52Z) Android version: 12 (SDK 31) Android build ID: RMX3085_11_C.12 Device brand: realme Device manufacturer: realme Device name: RMX3085L1 Device model: RMX3085 Device product name: RMX3085T2
> 
> ### Tachiyomi version
> 0.13.6
> 
> ### Android version
> Android 12
> 
> ### Device
> Realme 8 RMX3085
> 
> ### Other details
> i actually downloaded 10 chapter earlier and it successfully downloaded but the next chapter produce that error.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

![Screenshot_2022-10-20-08-49-09-17_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/71017787/196831208-9aeb6509-0485-448d-a760-ed12e6592211.jpg)
the correct image for the first picture

**Comment by arkon** [comment]
I'm just going to close this in favour of #7492; the existing downloader has a bunch of weird bugs.
