### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by khalid987** [tachiyomiorg/tachiyomi#8255]
### Steps to reproduce

![Screenshot_2022-10-20-21-53-02-602_eu kanade tachiyomi](https://user-images.githubusercontent.com/76953661/197065665-6bf34847-678c-49b8-abd4-005faef79392.jpg)

### Expected behavior

![Screenshot_2022-10-20-21-53-02-602_eu kanade tachiyomi](https://user-images.githubusercontent.com/76953661/197065797-740ea07d-d0a0-46fa-b47f-a1f25165cfa9.jpg)

### Actual behavior

![Uploading Screenshot_2022-10-20-21-53-02-602_eu.kanade.tachiyomi.jpg…]()

### Crash logs

![Uploading Screenshot_2022-10-20-21-53-02-602_eu.kanade.tachiyomi.jpg…]()

### Tachiyomi version

0.13.6

### Android version

11

### Device

Redmi 10c

### Other details

![Uploading Screenshot_2022-10-20-21-53-02-602_eu.kanade.tachiyomi.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not even the right repo, please use more effort.
