### ISSUE TITLE
Pure black dark mode does not reflect changes in splash screen

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8257]
### Steps to reproduce

1. Enable pure black dark mode in appearance tab
2. Launch Tachiyomi and check splash screen
..

### Expected behavior

Splash screen should be at pure black dark mode as it is part of the app.

### Actual behavior

Splash screen is gray and not in pure black dark mode.

### Tachiyomi version

Preview 5071

### Android version

Android 11

### Device

Samsung Galaxy J6

### Other details

Not really a bug but the concept of being pure black dark mode under theming must be set system-wide as it should be eyecandy for amoled users.

![Screenshot_20221021-124556666](https://user-images.githubusercontent.com/101556532/197115752-72e4c940-7b0b-4857-b461-bf05fc1a1582.jpg)
![Screenshot_20221021-124611092](https://user-images.githubusercontent.com/101556532/197115756-c706d992-bb1a-42b5-a47d-edd558bec147.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/4044#issuecomment-730390463
