### ISSUE TITLE
HentaiRead 

### ISSUE THREAD

**Issue by Metallingus7** [tachiyomiorg/tachiyomi#8259]
### Steps to reproduce

Chapters are not loading.

### Expected behavior

Chapters should load

### Actual behavior

Chapters didnt load.
![IMG_20221021_174055](https://user-images.githubusercontent.com/27897576/197192752-d36dcd8b-375c-446c-afed-aac7719e6a93.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Poco F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> - [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
