### ISSUE TITLE
Re-add the ability to disable tapping

### ISSUE THREAD

**Issue by Glogssa** [tachiyomiorg/tachiyomi#8260]
### Describe your suggested feature

Older versions of tachiyomi have the ability to disable tapping, and it gets very annoying when i cannot disable it

### Other details

![Screenshot_20221021-223912_Tachiyomi](https://user-images.githubusercontent.com/116368591/197222425-c39514f5-dd8f-4fb6-a750-b05e5a95c5e2.jpg)
![20221021_223827](https://user-images.githubusercontent.com/116368591/197222485-8e387dc5-b6b3-4b86-ad74-7fb5b83a2453.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read the release notes. https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.13.2
