### ISSUE TITLE
Browse > Sources: After pinned, add a "in library" group

### ISSUE THREAD

**Issue by Noriller** [tachiyomiorg/tachiyomi#8275]
### Describe your suggested feature

In Browse > Sources there's the pinned then each group by language, and it respects this order when searching.

So, the suggestion is to add an "in library" group after the pinned that would have sources that have items in the library.

This would mean that in a global search, the order would be pinned, sources with something already in the library, then everything else.

If this was a feature, we could have pinned be actual favorite sources while not "losing" all the other sources we use. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6654 makes more sense.
