### ISSUE TITLE
Download count isn't stored in library while using download filter

### ISSUE THREAD

**Issue by atmazzerexe** [tachiyomiorg/tachiyomi#8277]
### Steps to reproduce

1. Go to Library tab
2. Click filter button on top right or click library tab again
3. Select filter by "Downloaded"

### Expected behavior

Every manga on library with downloaded chapter(s) and local manga will show up.

### Actual behavior

None of the manga with downloaded chapter(s) are showing up. Local manga will still showing up normally.

![Screenshot_20221023-013900_Tachiyomi](https://user-images.githubusercontent.com/14852623/197363615-8296dc52-f572-445f-95b6-3d1ae37f10c4.png)

### Tachiyomi version

r5085

### Android version

Android 11 (AOSP)

### Device

ASUS Zenfone Max Pro M1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does it show up after a while? Download info is loaded asynchronously now, so there's going to be a gap between when the app is first opened and when it'll load, especially if you're using a typically slow SD card.

**Comment by atmazzerexe** [comment]
> Does it show up after a while? Download info is loaded asynchronously now, so there's going to be a gap between when the app is first opened and when it'll load, especially if you're using a typically slow SD card.

Nope. I put both local manga and downloaded chapter(s) on Micro SD, and those from local manga are showing up immediately, so Micro SD is not the issue here (And I'm also pretty sure the speed rating of my Micro SD is fast enough). But yeah, every once in a while my manga doesn't show that check mark symbol at all when I opened it even though I have downloaded chapters on it.

![Screenshot_20221023-043840_Tachiyomi](https://user-images.githubusercontent.com/14852623/197364506-d5436c20-37c7-46f4-995b-e91dc7d6e6f3.png)

**Comment by arkon** [comment]
> And I'm also pretty sure the speed rating of my Micro SD is fast enough

That sort of doesn't matter since the way that Android handles storage makes it slow regardless, so there's only so much the physical hardware actually helps there.

> I put both local manga and downloaded chapter(s) on Micro SD

Local manga only scans certain locations while downloads scan a lot more, so I'd expect the download cache priming to take longer. Did the app take a while to start in previous versions?

**Comment by arkon** [comment]
Also, can you see if it's more consistent in r5104?

**Comment by atmazzerexe** [comment]
> That sort of doesn't matter since the way that Android handles storage makes it slow regardless, so there's only so much the physical hardware actually helps there.

I see. Though I have done proper test on the microSD before using SD Card Test and I do enable legacy_storage for Tachiyomi in hope for increased performance.
Now, about this bug, I have left it for some hours r5085 and downloaded chapter(s) still won't appear at all. Just updated to r5104 and same results, though I reckon I didn't wait for that long this time. But I think I found the culprit: "Downloaded Chapters" badge on Display (Display -> Downloaded Chapters). If enabled it will properly show up.

When enabled:

![Screenshot_20221023-112209_Tachiyomi](https://user-images.githubusercontent.com/14852623/197373752-49a531d8-af6f-459f-9be2-e3a34b195a1c.png)

When disabled, all downloaded chapters are gone:

![Screenshot_20221023-112232_Tachiyomi](https://user-images.githubusercontent.com/14852623/197373775-0c966e9d-73bf-4ab1-93bd-5bf5f16336e8.png)

Both of them tested with Filter -> "Downloaded" option enabled.

> Local manga only scans certain locations while downloads scan a lot more, so I'd expect the download cache priming to take longer. Did the app take a while to start in previous versions?

> Also, can you see if it's more consistent in r5104?

Opening each manga entries sometimes can be pretty slow indeed before https://github.com/tachiyomiorg/tachiyomi/issues/8236 happened, and it seems to perform faster now with r5104. But now that I know about the existence of downloaded chapters badge, I think it shows a particular behaviour now; If you have previously downloaded manga when a chapter is available before, it will still shows up on your Library as an entry with downloaded chapter(s) even when there's no more downloaded chapter in the entry (Which is helpful to search for problematic entries, I guess).

![Screenshot_20221023-115314_Files_by_Google](https://user-images.githubusercontent.com/14852623/197374515-c154adc9-c893-48f9-8a98-0d4d7640e8ba.png)

![Screenshot_20221023_115513](https://user-images.githubusercontent.com/14852623/197374563-b6bfe315-5e17-4a68-a0f1-c4e81e9a9a3b.png)

**Comment by AntsyLich** [comment]
To introduce faster load download count isn't stored (since we need to check the downloads folder for it) unless you are using it but the existence of download filter was forgotten in that commit so download count is only stored if download badge is enabled.

Rename the title to "Download count isn't stored while using download filter"
