### ISSUE TITLE
Automatic backup/library update jobs are reset after each update

### ISSUE THREAD

**Issue by atmazzerexe** [tachiyomiorg/tachiyomi#8282]
### Steps to reproduce

1. Use Tachiyomi Preview
2. Enable automatic backup, set the frequency to "Weekly" (Any maximum amount of backups are fine)
3. Update Tachiyomi Preview regularly

### Expected behavior

Automated backup process will be triggered each week and new backup will be created.

### Actual behavior

No new backups created on automated backup folder. I have tried to set it into generating new backups every 6 hours and it works normally, which means it's not the problem on it's backup process itself. Until I tried to change it, the last time the automatic backup process triggered on my phone was on July 16th, which aligned well to Tachiyomi Beta/Preview release frequency back then.

![Screenshot_20221023-235814_Files_by_Google](https://user-images.githubusercontent.com/14852623/197542054-45573c4b-0ec4-483b-a93f-5450f04477fd.png)

### Tachiyomi version

r5104

### Android version

Android 11 (AOSP)

### Device

ASUS Zenfone Max Pro M1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
From what I can tell this might be an issue with how tachiyomi handles external folders and stuff as tachiyomi also refuses to download to a custom location unless you go and set the download again to that location after each update.

**Comment by arkon** [comment]
That's totally unrelated, this is probably just because the migration runs on every version code upgrade and sets up the jobs again.

**Comment by THElegend5** [comment]
> That's totally unrelated, this is probably just because the migration runs on every version code upgrade and sets up the jobs again.

Ah ic I'll open an issue for mine tomorrow than as download location not being set properly has been an issue for past 2-3 previews.

**Comment by arkon** [comment]
WorkManager 2.8's `ExistingPeriodicWorkPolicy.UPDATE` would actually be the cleanest solution for this, but previous attempts to upgrade resulted in crashes. We'll have to revisit that.

**Comment by atmazzerexe** [comment]
> WorkManager 2.8's `ExistingPeriodicWorkPolicy.UPDATE` would actually be the cleanest solution for this, but previous attempts to upgrade resulted in crashes. We'll have to revisit that.

It's fine, take your time. Just checked your gradle to found out that your version is stuck at 2.6 at the moment. Perhaps you can update it to 2.7.x first before jumping to 2.8 so you can deal with any other issues that comes with it.

**Comment by arkon** [comment]
Recent changed moved to `ExistingPeriodicWorkPolicy.UPDATE`.
