### ISSUE TITLE
Select all, inverse and range selection doesn't respect search query in library

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#8287]
### Steps to reproduce

1. Search something in library that narrows down the items (e.g. from 20 items down to 10)
2. Long press an item
3. Inverse the selection

### Expected behavior

Should select the other visibly filtered items.

### Actual behavior

Note that it selects 19 items rather than 9. Same behaviour applies to select all and range selection.

### Tachiyomi version

r5104

### Android version

N/A

### Device

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kingtie** [comment]
Is does the same thing for select all, not just inverse and range select
