### ISSUE TITLE
Improve browse local.

### ISSUE THREAD

**Issue by avgsandeep** [tachiyomiorg/tachiyomi#8291]
### Describe your suggested feature

Please add local sources to browser

> WebDAV, FTP.
> Custom folder to get full library via documents provider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can search existing closed issues for duplicates.
