### ISSUE TITLE
Comic type should be aligned with source category

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8306]
### Describe your suggested feature

Right now the term 'manga' is being used as universal type of comic when adding and removing from source. The string should coincide with the source category of what comic type it is after being added or removed from source.

![Screenshot_20221028-212557910_1](https://user-images.githubusercontent.com/101556532/198623776-9458c073-324a-42f6-81a9-0c6f796a85af.jpg) ![Screenshot_20221028-215357676](https://user-images.githubusercontent.com/101556532/198625672-dcdf999e-f53e-4f8f-a03a-548162a99ced.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We don't really track what type they are, those are just arbitrary genre tags from the source.

We _could_ just make all the wording more generic (e.g., "entry", "entries").
