### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Irfan000666** [tachiyomiorg/tachiyomi#8310]
### Steps to reproduce

1.When you swipe to see your different categories on the main page 

### Expected behavior

It supposed to be smooth like the previous version.

### Actual behavior

But now it have that lag and will sometimes close the app.. 

### Tachiyomi version

0.14.0

### Android version

Android 12

### Device

Samsung S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by zer0p1us** [comment]
Have experienced the same right after updating to 0.14.0 on android 12

**Comment by arkon** [comment]
Lag should improve over time as you use the app after an update as Android reoptimizes it.

Some people have noted the rougher fling animation between category tags, but that'll be fine tuned in later releases.
