### ISSUE TITLE
Update Error Titles

### ISSUE THREAD

**Issue by Conrad-M** [tachiyomiorg/tachiyomi#8311]
### Describe your suggested feature

When titles fail to update could the feature please label the titles that failed to update?

When titles fail to update it just shows the number of titles that failed to update for whatever reasons. And if I try to find the 3 failed updates in a category with 180+ titles, it takes too much time.

### Other details

So basically it should look exactly like the update notification, it says what's been updated and when you click on the drop down it shows all the failed titles. Maybe the reason why they failed aswell? It would be helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can just open the error log file from the notification.
