### ISSUE TITLE
account 

### ISSUE THREAD

**Issue by Lasha215** [tachiyomiorg/tachiyomi#8312]
### Describe your suggested feature

it would be great if we just had simple account system so whenever and wherever we download tachi my subscriptions will he transferred there as well as where i left off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#1432
