### ISSUE TITLE
Navigation bar and top header not dismissed while scrolling down on Library view

### ISSUE THREAD

**Issue by zer0p1us** [tachiyomiorg/tachiyomi#8315]
### Steps to reproduce

From the library view scroll down any category

### Expected behavior

The bottom navigation bar and top header should disappear to make space leaving only the categories at the top
![Screenshot_20221028-212956_Tachiyomi](https://user-images.githubusercontent.com/42619260/198729245-0295836e-57d9-4834-b282-90743be3cea4.jpg)

### Actual behavior

Both bottom navigation bar and top header stay in place 

![Screenshot_20221028-213152_Tachiyomi](https://user-images.githubusercontent.com/42619260/198729335-432cc8d7-7974-4218-83c0-96b5ab31941e.jpg)

### Tachiyomi version

0.14.0 and preview r5127

### Android version

Android 12

### Device

Samsung A12

### Other details

Not present in 0.13.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is intentional, the Compose version of it isn't very good. It may return in the future if the upstream support improves.
