### ISSUE TITLE
start screen option missing from latest update

### ISSUE THREAD

**Issue by WDForty1** [tachiyomiorg/tachiyomi#8317]
### Steps to reproduce

Settings > General > Start Screen option is missing from the latest release.

### Expected behavior

Settings > General > Start Screen 
Option allows you to choose which screen to act as your home when launching the app

### Actual behavior

Settings > General > Start Screen 
option is now completely missing

### Tachiyomi version

0.14.0

### Android version

Android 13

### Device

Google pixel 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please read the release notes: https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.0
