### ISSUE TITLE
Freely move categories

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#8325]
### Describe your suggested feature

The ability to move a category by more than one place.

### Other details

Before updating to 14.0 you could move categories until any order pretty easily but now we have to move one button at a time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This likely won't change unless Compose supports drag and drop better. If that ever happens, we'll come back to this.
