### ISSUE TITLE
Inserting Comic at Library from Source Problem 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8334]
### Steps to reproduce

1. Go to any source
2. Inset any comic in library
Example :
![Screenshot_2022-10-29-21-01-50-18_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/198836102-576ee65f-7a3d-4ae5-b8a1-1aa162fd6dc9.jpg)

3. The comic doesn't have attribute this comic in library on thumbnail `Before refreshing the source`
Like :
![Screenshot_2022-10-29-21-01-47-51_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/198836087-b463d446-2e83-4790-9cc4-56848f00555e.jpg)

4. Refresh the source
5. Comic have attribute this comic in library on thumbnail `After refreshing the source`
![Screenshot_2022-10-29-21-02-01-82_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/198836125-a787dd4d-bd9f-4fe0-b7d8-8948e1f61fb4.jpg)

### Expected behavior

The Comics have attributes already included in the library on thumbnails

### Actual behavior

Inserting comics in the library, but does not show that this comic is already in the library on thumbnail in source, when it is refreshed it appears that this comic is in the library on thumbnail 

### Tachiyomi version

0.14.0

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I suspect this is the same issue as #8333. You could try the latest preview build to verify if you can reproduce this semi-consistently.

**Comment by TheKingTermux** [comment]
> I suspect this is the same issue as #8333. You could try the latest preview build to verify if you can reproduce this semi-consistently.

Ok i willy try it
