### ISSUE TITLE
The new update has made navigation jittery and laggy

### ISSUE THREAD

**Issue by Veyieneq** [tachiyomiorg/tachiyomi#8338]
### Steps to reproduce

Any general usage of the app, from moving around in sources to checking your library.

### Expected behavior

Any version of tachiyomi before this was smooth and had close to no issues with navigation.

### Actual behavior

Upon scrolling, opening a source, etc. the app performs much more poorly relative to any prior update.

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Redmi Note 8

### Other details

This issue was there when I first installed the 0.14.0 version, and despite updating to 0.14.1, persisted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/8310#issuecomment-1295355232
