### ISSUE TITLE
Tachiyomi keeps crashing at launch

### ISSUE THREAD

**Issue by WooperBestPokemon** [tachiyomiorg/tachiyomi#8339]
### Steps to reproduce

I have a Nothing Phone (1) and I rooted it.

I removed these preinstalled apps:
WebViewGoogle, Chrome, Trichromelibrary.

### Expected behavior

The app should launch normally

### Actual behavior

I installed the latest version, and the preview, and both of them crash as soon as I launch them (I see Tachiyomi Logo then poof, app crashes).

### Tachiyomi version

v0.14.1

### Android version

Android 12

### Device

Nothing Phone 1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Tachiyomi requires WebView.
