### ISSUE TITLE
search function is bugged

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/tachiyomi#8341]
### Steps to reproduce

1.click navigation
2.type manga title in
3.click an entery to view it and then back out without making any further action
4.the app redirect me to the search par again which keeps prompting up the keyboard
5.this happens every time after viewing any entery

### Expected behavior

it shouldn't do that 

### Actual behavior

it does that 

### Crash logs

--------- beginning of system
--------- beginning of main
10-29 21:33:45.489 17455 17560 E SQLiteLog: (284) automatic index on C(manga_id)
10-29 21:33:45.489 17455 17560 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 7.1.2 (SDK 25)
Android build ID: N2G47H
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: ugg
Device model: Redmi Note 5A Prime
Device product name: ugg

### Tachiyomi version

App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z) Android version: 7.1.2 (SDK 25) Android build ID: N2G47H Device brand: xiaomi Device manufacturer: Xiaomi Device name: ugg Device model: Redmi Note 5A Prime Device product name: ugg

### Android version

android 7

### Device

Xiaomi redmi note 5A prime

### Other details

[discord video](https://media.discordapp.net/attachments/349436576037732355/1035832188006047814/Recorder_20221029102033.mp4) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing in favour of #8361, which describes it better.
