### ISSUE TITLE
Migrating error

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi#8354]
### Steps to reproduce

1. Migrating a title from manhwatop to 1stkissmanga
2. Always show internal error, check crash log

### Expected behavior

No error message shown

### Actual behavior

Always show error message when migrating a title

### Crash logs
```
--------- beginning of main
10-30 18:01:22.582 23980  2435 E Surface : freeAllBuffers: 7 buffers were freed while being dequeued!
10-30 18:01:53.997 23980  1620 E CursorWindow: Failed to read row 542, column 0 from a CursorWindow which has 542 rows, 19 columns.
App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211019.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: joyeuse
Device model: Redmi Note 9 Pro
Device product name: joyeuse_id
```

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Redmi note 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not sure why that error happens, but you can try:

1. Making a backup
2. Uninstalling the app
3. Reinstalling the app
4. Restoring your backup

**Comment by blanknoob36** [comment]
Well I tried and only doesn't seems to be working with manganato for me but seems to be working fine for mangadex here is a video of what happens when I try manganato to manganato

https://user-images.githubusercontent.com/84096880/198891460-730bde56-c889-4bfa-b781-f4ee86de23fc.mp4

**Comment by jferdous70** [comment]
https://user-images.githubusercontent.com/83420659/198891877-b6b0516a-04f4-4b10-82f7-ae54eef2134b.mp4

video

**Comment by jferdous70** [comment]
video 

https://user-images.githubusercontent.com/83420659/198891949-28f3de06-79df-4ad4-98b9-70f9318a601b.mp4

**Comment by MikeZeDev** [comment]
Can reproduce this on any manga from Koomanga to other sources. Its exactly a is the video. Latest extension, latest tachi, Android 12.

**Comment by arkon** [comment]
Not sure if still applicable in newer versions.
