### ISSUE TITLE
Too big navigation bar and material components

### ISSUE THREAD

**Issue by Matsukii** [tachiyomiorg/tachiyomi#8355]
### Steps to reproduce

1. open the app
2. go anywhere with "Material you" components (switches, buttons...)

### Expected behavior

Small elements that relate to labels and text, responsive to screen size.

(image from troubleshooting guide for comparison)
![image](https://user-images.githubusercontent.com/28326534/198875608-6ef333a3-2b60-4c42-8713-784c5e1fcdf5.png)

### Actual behavior

Too big switches, tall navbar taking a lot of space in screen with unnecessarily big/bold font-size

![image](https://user-images.githubusercontent.com/28326534/198875593-14345942-5a97-4955-a3d2-bb7ea2b54da0.png)
![image](https://user-images.githubusercontent.com/28326534/198874604-9e32855f-4022-469f-9c68-a915e1bb5f98.png)

### Tachiyomi version

0.14.1

### Android version

Android 7.1.1

### Device

Motorola Moto Z2 Play

### Other details

Screen resolution 1080x1920px

Seriously, how can you think that "material you" style looks better than old navbar style? why you want a background only on the icon to indicate active tab? why you want to make it much bigger than needed? this is not "material me" that's "material google". As designer I hate how Google manages to makes UI/UX worse in every new version of almost all products.

If you can make your app have its own identity, it must be much better than rely on a company that just keep doing the worst for its users.

![image](https://user-images.githubusercontent.com/28326534/198874514-8de0e6f5-f1ee-4394-900a-5ec9184ec8aa.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Take up your design complaints with google
