### ISSUE TITLE
Percentage number for page loading

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#8356]
### Describe your suggested feature

add percentage number inside or below the chapter page loading circle

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
The loading ring completes based on the progress after the page starts downloading

**Comment by Riztard** [comment]
🤔🤔🤔
