### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by Ssanfi** [tachiyomiorg/tachiyomi#8357]
### Describe your suggested feature

A simple scroll bar to navigate faster up and down the mangas

### Other details

It was already there in versions before. 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's still there so I don't know what you're talking about.
