### ISSUE TITLE
Option to save update errors

### ISSUE THREAD

**Issue by SoloLeveller1** [tachiyomiorg/tachiyomi#8358]
### Describe your suggested feature

Whenever we update our library, if any update fails, we get a notification and we can view what failed, only through the notification. If we clear the notification, can't view the errors.

Would be better if there's an auto error save, which saves the text file in same location as auto backup.

### Other details

Would be better for those with many errors/sources so you can address the errors one by one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#4616 should ideally cover this.
