### ISSUE TITLE
New Version 

### ISSUE THREAD

**Issue by huacheng3** [tachiyomiorg/tachiyomi#8359]
### Steps to reproduce

I downloaded it first using the about - check for updates button but it didn't work
Then I tried using chrome still didn't work 

### Expected behavior

When I downloaded the old version 0.13.6 the installation was fast

### Actual behavior

I tried downloading the version 0.14.1 but it says download error I even tried downloading it specifically in the app and using chrome but still download error I have a strong internet connection and enough space I don't know what's wrong:((

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Vivo y11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That usually just means you're having issues with downloading the asset from GitHub for some reason and isn't really in our control.

You can try on different devices (like a PC) or ask someone else to try downloading it and sending you the APK file.
