### ISSUE TITLE
Keyboard input keeps popping up while browsing global search results

### ISSUE THREAD

**Issue by smori001** [tachiyomiorg/tachiyomi#8361]
### Steps to reproduce

1.Go to Browser tab
2.use global search and input a name
3.enter one of mangas by random
4.back to global search

### Expected behavior

3.enter one of mangas by random, and u can see the detail of the manga normally. Nothing else happens.
4.back to global search, and browser other mangas. no input pop up and search box not in text edit mode.

### Actual behavior

3.enter one of mangas by random, and find that your input app, such as Gboard, pop up suddenly(see pic 1), but it disappears soon 
4.back to global search, and find that your input app pop up again while your search box in text edit mode.(see pic 2)

This bug after updating the new version is so annoying me.

### Tachiyomi version

0.14.1

### Android version

Android 10

### Device

Samsung Galaxy Note 9

### Other details

![Screenshot_20221030-222106_Tachiyomi](https://user-images.githubusercontent.com/50619315/198883726-42c94589-a9e9-4881-a2e3-639598571165.jpg)
![Screenshot_20221030-222111_Tachiyomi](https://user-images.githubusercontent.com/50619315/198883738-1e452109-ff08-4e19-baf9-2c5259c87a71.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This should ideally be fixed when Global Search is also migrated to Compose.

**Comment by arkon** [comment]
Fixed by #8631
