### ISSUE TITLE
Scroll pustaka slow 

### ISSUE THREAD

**Issue by rianza** [tachiyomiorg/tachiyomi#8362]
### Steps to reproduce

Scroll pustaka slow 

### Expected behavior

Scroll pustaka slow 

### Actual behavior

Scroll pustaka slow 

### Tachiyomi version

0.14.1

### Android version

Android 11 

### Device

Realme 7 i 

### Other details

https://user-images.githubusercontent.com/116883839/198886884-46d9f24a-ec87-47a2-ba8b-e08a6d925cea.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Give it a few days until the OS re-optimizes the app.
