### ISSUE TITLE
Update project default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by brettmcginnis** [tachiyomiorg/tachiyomi#8366]
### Steps to reproduce

Not Applicable - Gif configuration

### Expected behavior

project uses `main`

### Actual behavior

project using `master`

### Tachiyomi version

Not Applicable

### Android version

Not Applicable

### Device

Not Applicable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'd rather not have to update all of the tooling and get every contributor to reconfigure their local repos.

**Comment by brettmcginnis** [comment]
If it helps, I can update the tooling, and switching local branches is straight forward

**Comment by arkon** [comment]
I really don't think it's worth it for an existing project with more than a few people working on it. We'll use `main` for any new repos.

**Comment by brettmcginnis** [comment]
A few articles to consider

https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/
https://github.com/github/renaming

**Comment by arkon** [comment]
I renamed the branches on smaller repos in the org that have fewer people touching them. I won't be renaming the default branches in the "core" repos that have a lot of contributors touching them very often to avoid unnecessary churn.
