### ISSUE TITLE
Bring back or add separate feature for resume / play on history 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8374]
### Describe your suggested feature

Play / resume button on history
Or
Add a separate for resuming the comic
Like click on thumbnail for opening the comic page and click on title / chapter for resuming latest chapter

### Other details

It will help users who prefer to read the latest chapter / continue it rather than having to open a comic page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Like click on thumbnail for opening the comic page and click on title / chapter for resuming latest chapter

This is literally what it already is.

**Comment by TheKingTermux** [comment]
> This is literally what it already is.

Sorry I didn't expect it, because previously there was a resume / play button

**Comment by arkon** [comment]
It's mentioned in the 0.14.0 release notes.

**Comment by TheKingTermux** [comment]
> 

Sorry I didn't read it 😅
