### ISSUE TITLE
Missing ime padding in empty screen

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#8381]
### Steps to reproduce

1. Click search button in toolbar to show soft keyboard (either in empty history screen, library screen, or extension tab)

### Expected behavior

Stable 0.14.1
-------------
![image](https://user-images.githubusercontent.com/108109611/198950688-336d26fc-0717-46de-8b25-a856554bb314.png)

### Actual behavior

Preview r5172
-------------
![image](https://user-images.githubusercontent.com/108109611/198950712-2b7418fd-7869-4772-9a8c-de8224d9b600.png)

### Tachiyomi version

r5172

### Android version

12, EU ROM

### Device

mojito

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I assume this is from the scaffold rebase, @ivaniskandar ?

**Comment by ivaniskandar** [comment]
Yes now by default only system bars inset applied to the scaffold

**Comment by arkon** [comment]
I guess this is technically correct since content isn't supposed to shift for the IME unless it's explicitly supposed to do so (e.g. in a messaging app).
