### ISSUE TITLE
Copy manga tags to clipboard when long pressed

### ISSUE THREAD

**Issue by Satria41** [tachiyomiorg/tachiyomi#8382]
### Steps to reproduce

1: open manga
2: long press a tags

### Expected behavior

Tags should be copied to clipboard

### Actual behavior

No tags was Copied to clipboard

### Tachiyomi version

0.14.0 & 0.14.1

### Android version

Android 9 

### Device

Asus Zenfone Max Pro M2(on pixel experience)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mayorJAY** [comment]
I will like to fix this bug @arkon

**Comment by kingtie** [comment]
Don't know if this is already known, but the same thing happens for titles, sources and authors also.
