### ISSUE TITLE
Custom Cover Got Changed Automatically

### ISSUE THREAD

**Issue by Shawkik-Islam-Joha** [tachiyomiorg/tachiyomi#8386]
### Steps to reproduce

I had my own selected cover for this manga.
But that extension recently updated the cover for this manga.
So,when I refreshed the chapter page,the cover also changed automatically.

![Screenshot_2022-10-31-14-06-48-526_eu kanade tachiyomi](https://user-images.githubusercontent.com/115642951/198962231-fd74126a-a555-433d-8f3d-8fbe200a4aa0.png)

### Expected behavior

The custom cover should not get changed Automatically without user's prompt.

### Actual behavior

The Custom Cover gets changed without User's Prompt.

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Xiaomi Redmi Note 9

### Other details
I am not sure if this information is redundant.But,I had this setting off.

![Screenshot_2022-10-31-14-09-34-149-edit_eu kanade tachiyomi](https://user-images.githubusercontent.com/115642951/198962470-43d83084-cf8e-42cc-b426-bb59d4dc7305.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not sure if still applicable in newer versions.
