### ISSUE TITLE
Free Flow is missing

### ISSUE THREAD

**Issue by kent909x** [tachiyomiorg/tachiyomi#8387]
### Steps to reproduce

Previous version like 13.5 had it 

1. Browse tab.
2. Sources (I encountered it on mangadex, nhentai, hiperdex).
3. whether it's on Popular tab or Latest tab.
4. scrolling isn't free flowing like on the library tab.

### Expected behavior

free flow, is it removed or is there an option to enable it

### Actual behavior

laggy flow which is annoying

### Tachiyomi version

0.14.1

### Android version

Android 11 

### Device

Xiami 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/8310#issuecomment-1295355232
