### ISSUE TITLE
Unatteded extension updates are not working

### ISSUE THREAD

**Issue by soredake** [tachiyomiorg/tachiyomi#8388]
### Steps to reproduce

1. Have android >=12
2. Install extension
3. Wait for update
4. Prompt for updating will appear (it should not appear as tachiyomi have this [permission](https://github.com/tachiyomiorg/tachiyomi/blob/15f7e53e4fe98a05497485b953e0e5c757baa167/app/src/main/AndroidManifest.xml#L21) defined)

### Expected behavior

Extensions should update silently.

### Actual behavior

Prompt for update is shown.

### Tachiyomi version

0.13.6

### Android version

Android 12L

### Device

Redmi Note 5

### Other details

https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
PackageManager is broken by MIUI and is explicitly not used by Tachiyomi on such devices.

It'll be enabled if Xiaomi ever fixes it.

**Comment by soredake** [comment]
@arkon i don't use miui, i use crdroid which is based on aosp.
