### ISSUE TITLE
Komga tracker not working

### ISSUE THREAD

**Issue by JonatanCz** [tachiyomiorg/tachiyomi#8393]
### Steps to reproduce

1. Enable Komga tracker in settings
2. Add manga from Komga to library
3. Try to enable tracking for the manga

### Expected behavior

Tracking enabled, read progress should update

### Actual behavior

After opening tracker selection popup, a notification shows: "HTTP error 401"
After clicking "Add tracking", a notification shows: "No matching result was found" (translated - was in my system's language even though app language is set to English)
When I try to update read chapters in manga, which had the tracking already enabled "HTTP error 401" notification shows again.

### Tachiyomi version

Preview r5172 (cac80daa7, 10/30/22 10:45 PM)

### Android version

Android 11 (LineageOS 18.1 [Unofficial])

### Device

Samsung Galaxy S5 NEO SM-G903F (s5neolte)

### Other details

The tracking works normally with the stable version 0.14.1 (9.10.22 5:53 PM)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably just need to relogin to the Komga source.

**Comment by JonatanCz** [comment]
If you mean changing credentials to something else and restoring them - it's not working. But now I only see 401 message when I try to change read chapters in already tracked manga. For not tracked manga "Add tracking" still shows "No matching result was found".

**Comment by JonatanCz** [comment]
(And yes, I did restart the app after each change of credentials if you were going to ask)

**Comment by Seishirou101** [comment]
if you go to webview, are you authenticated? regardless, try also clearing cookies
