### ISSUE TITLE
webview in reader show API page

### ISSUE THREAD

**Issue by kavillock** [tachiyomiorg/tachiyomi#8396]
### Steps to reproduce

1. Open any manga chapter with extension that's use API, ie: mangadex, comickfun
2.try to open webview

### Expected behavior

Open normal chapter page (like webview in chapter browse open normal manga page)

### Actual behavior

Open API page

### Tachiyomi version

0.14.1

### Android version

Android 13

### Device

Xiaomi mi note 10 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14051#issuecomment-1296326502

**Comment by kavillock** [comment]
I don't know it's extension error, because it's happen with multiple extension, complained here.

**Comment by kavillock** [comment]
Ah, I doesn't check extensions, because happened on some more than one extension, i thonk that's app issue

**Comment by arkon** [comment]
Please read the linked comment. There's no action required for the app, the extensions will be updated later to handle it properly.
