### ISSUE TITLE
Deleted manga chapters still displaying as downloaded

### ISSUE THREAD

**Issue by Kahz3l** [tachiyomiorg/tachiyomi#8397]
### Steps to reproduce

1. Mark chapter(s)
2. Click on trash bin button
3. Chapters still marked as downloaded for about 5-15 sec

### Expected behavior

This should happen:
The tick mark should disappear immediately.

### Actual behavior

The tick mark that indicates the downloaded chapters still stays for 5-15 secs, sometimes even until leaving the manga chapter menu and opening the chapter menu again.

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Samsung A52S EUR

### Other details

The behavior was not like that before the big change.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Previously we used to assume chapter has been deleted and marked the chapter as not downloaded making it instantaneous. 
But from 0.14.0 we monitor the downloads and mark chapter as not downloaded when the chapter has been actually deleted from your storage hence the delay
