### ISSUE TITLE
Manga Extensions Search Engine / Global Search Engine 

### ISSUE THREAD

**Issue by TheGoldenSun** [tachiyomiorg/tachiyomi#8399]
### Steps to reproduce

1. Type a manga story you like
2. Swipe left or right to see the full title 
3. See if it shows you the full manga story title.

### Expected behavior

Users should be able to see the full manga title within both global search and in manga extensions search engine.

### Actual behavior

When swiping left or right within both global search and in manga extensions search engine to either copy or paste or manually research any type of manga title that's suitable sometimes the manga titles that's big doesn't allow users to swipe left or right to see the full clear title of the manga. 

### Crash logs

none

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Galaxy a02 

### Other details

![Screenshot_20221031_193308](https://user-images.githubusercontent.com/104534608/199130554-c1cd9a53-0f3e-4c7e-b70b-1466b3618998.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Works fine for me. Your screenshot seems to imply that you're long pressing it, not scrolling it.
