### ISSUE TITLE
Downloaded chpaters are missing

### ISSUE THREAD

**Issue by Key-explanation** [tachiyomiorg/tachiyomi#8403]
### Steps to reproduce

1. Download a chapter
2. update tachiyomi to the new version
3. downloaded chapters are missing

### Expected behavior

The downloaded chapter should be there to read on offline mode

### Actual behavior

The chapters are missing

### Crash logs

.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Vivo Y15

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Give it some time to index the downloads. They'll appear eventually.

**Comment by Key-explanation** [comment]
> Give it some time to index the downloads. They'll appear eventually.

It has happened when I updated to 0.14.0. It has been 2 days since then

**Comment by AntsyLich** [comment]
Settings -> Downloads -> Change location to something else and back to the original location. If this still doesn't work join the discord for better support
