### ISSUE TITLE
Animation lags

### ISSUE THREAD

**Issue by Cjojojojo** [tachiyomiorg/tachiyomi#8404]
### Steps to reproduce

1.Scroll or swipe within the app, and through mangas and chapters
2.Go to any mangas
3.Swipe up and down

### Expected behavior

It should be smooth like from v 1.36, no lags

### Actual behavior

Screen jitters, lags during scroll to chapters and lags when swiping between categories

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Oppo A74

### Other details

Not a troll here, just a concerned user. Take your time guys we know it's for the best, things to be fixed are minimal and this update is a great leap from previous versions keep up the great work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/8310#issuecomment-1295355232
