### ISSUE TITLE
Data saving mode

### ISSUE THREAD

**Issue by ossamach** [tachiyomiorg/tachiyomi#8406]
### Describe your suggested feature

By lowering the quality of pages when using mobile data

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don't host any content as such we are unable to provide low quality pages. If any source provides such option we can make a option for that source in which case you'll make a issue [here](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose)
