### ISSUE TITLE
Option to disable "open random entry"

### ISSUE THREAD

**Issue by skyorb1** [tachiyomiorg/tachiyomi#8412]
### Describe your suggested feature

An option to disable the "Open random entry" feature in Settings and set it back to just the "global update" feature.
"Open random entry" Can be enabled from settings if required.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Rejected, we don't need more trivial settings to complicate the app.

**Comment by skyorb1** [comment]
The feature to open a random entry is a trivial one that complicates the
app as well. Was there no similar issue with the inclusion of this in the
first place?
