### ISSUE TITLE
Floating action button library page

### ISSUE THREAD

**Issue by foxlore** [tachiyomiorg/tachiyomi#8414]
### Describe your suggested feature

Floating action button Bottom right corner that opens next item by sort and visible with an unread count greater than zero and an option in the display menu to toggle this on and off and an additional one for random with an unread count greater than zero and visible.

### Other details

◀️ Read next 
(🎲 Or 🔀) Read random 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Random button was added in 0.14 check the overflow button in topbar. It won't be made a fab since it is not the main function of library.

As for next button it'll still take 1 tap to open the next one manually so I see no of making another button for it
