### ISSUE TITLE
Rework logic about exclusion in downloads

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8415]
### Describe your suggested feature

Excluded categories should not exist under delete chapter and must be separated because auto download depends on it. Auto download must check first if there is exclusion and its excluded option is redundant. The node should be:
 
 2. Excluded Categories
 3. Auto-download
     - include categories (no more exclude)
 4. Delete chapter
     -
     -
     -
     - (no more excluded categories)

### Other details

I will close #8401 for now to avoid further confusion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> Auto download must check first if there is exclusion and its excluded option is redundant.

Umm what?

**Comment by arkon** [comment]
I don't really understand what this is asking, but you can download without auto download and the deletion exclusion applies to those.
