### ISSUE TITLE
Add an option to disable opening websites in Tachiyomi (via Global Search activity).

### ISSUE THREAD

**Issue by holdenli** [tachiyomiorg/tachiyomi#8416]
### Describe your suggested feature

I learned that extensions can cause Tachiyomi to open websites inside the app. I figure it's something to do with [this global search activity](https://github.com/tachiyomiorg/tachiyomi/blob/15f7e53e4fe98a05497485b953e0e5c757baa167/app/src/main/AndroidManifest.xml#L70).

I discovered this with Mangadex and I think it's set up incorrectly for so I filed a separate bug here: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14097

I do not want this behavior and I would like a way to turn it off.

Note: This behaves poorly if you have multiple forks of Tachiyomi installed. You get a "Complete Action With" popup even though mangadex extension was not installed on the fork so the action via the fork will fail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Disable it in extension app settings then?

**Comment by holdenli** [comment]
Ah. Did you mean the Mangadex extension app info? Didn't think to look there thanks. It's pretty unintuitive but maybe that's an android issue (didn't even realize the extension was considered an App).

For reference, you can go to the extension's settings and click `App info` > `Open by default` > toggle `Open supported links`.
