### ISSUE TITLE
Library : Selected mangas are not highlighted in list view when dark mode is on

### ISSUE THREAD

**Issue by MikeZeDev** [tachiyomiorg/tachiyomi#8419]
### Steps to reproduce

Open your library (mine is in list view)
Select a few titles using long press

### Expected behavior

Selected titles should be highlighted.

### Actual behavior

Selected titles are not highlighted, like they are in other view modes (grid).

### Tachiyomi version

0.14.2

### Android version

12

### Device

Samsung A51. Up to date

### Other details

Since they are highlighted in grid mode they should be too in list mode.

Its a pain to know which one you selected because there is no color differences. I tested default theme and others, all in dark mode. Light mode is hilighted ok but ofc my eyes hurts :D. "Pure Dark mode" switch changes nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It has the same selected background as any other list view (e.g. updates or chapters lists).

Do you have a screenshot?

**Comment by MikeZeDev** [comment]
So : turn out it highlighted indeed., but its barely visible if you set  "Pure Dark mode" and your phone brightness very low.
Screeshot seems ok but it does not reflect how its on my screen. I read in dark room so very little screen brightness is necessary.

Was there a related change with the latest big tachi update ? Because i remember it being more visible before.
Maybe its just me?
