### ISSUE TITLE
Library - DownloadCustomAmountDialog: Max amount does not match to downloading count

### ISSUE THREAD

**Issue by zbue** [tachiyomiorg/tachiyomi#8421]
### Steps to reproduce

1. Hold to select at least two entries in library screen (e.g., Entry X and Entry Y, where Entry X amount > Entry Y amount)
2. Select download
3. Select custom amount
4. Press the +10 chapters button until it reach maximum
5. Press OK to download

### Expected behavior

DownloadCustomAmountDialog maximum count should be Entry X amount + Entry Y amount

### Actual behavior

DownloadCustomAmountDialog maximum count is Entry X max amount only.

### Tachiyomi version

0.14.2

### Android version

N/A

### Device

N/A

### Other details

In download queue screen, it displays the correct amount (Entry X amount + Entry Y amount)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It should be the max unread from any of the entries, since the amount targets a single entry and not the total number (e.g., next 10 is next 10 unread from each entry, not just 10 in total).

That already seems to be the case too, unless I'm misunderstanding something?

**Comment by zbue** [comment]
Here's a video

https://user-images.githubusercontent.com/108109611/199507908-256805b8-1e65-4db7-8742-d6e2aaa6b534.mp4

**Comment by AntsyLich** [comment]
It's max amount of download for each entry not for all in total
