### ISSUE TITLE
Open random entry

### ISSUE THREAD

**Issue by Leunsensei** [tachiyomiorg/tachiyomi#8424]
### Describe your suggested feature

![Screenshot_2022-11-02-14-18-54-180_eu kanade tachiyomi](https://user-images.githubusercontent.com/98178685/199502480-3945113f-9a34-429d-b096-88eaa7525433.jpg)

Opening random entries should only open entries that have unread chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It respects your filters, so just filter by unread first.
