### ISSUE TITLE
Tachiyomi seems not to close database on application exit.

### ISSUE THREAD

**Issue by xkww3n** [tachiyomiorg/tachiyomi#8428]
### Steps to reproduce

1. Open Tachiyomi app
2. Do something
3. Exit the app by double-tapping the Return key
4. Browse /data/data/eu.kanade.tachiyomi/databases

### Expected behavior

There shouldn't be any `.db-shm` or `.db-wal` file.

### Actual behavior

There exists `tachiyomi.db-shm` and `tachiyomi.db-wal`.

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Google Pixel 4 XL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Are you experiencing an actual issue? The database should be handling flushing any leftover WAL logs on the next app launch.

Not entirely sure why you're browsing the app data in the first place...

**Comment by Milor123** [comment]
I have the same issueeeeee and lose all my data T_T, how can i repair the .db file? when i replace it over a new clean installation of tachiyomi, the app crash :(, i want extract my library log
