### ISSUE TITLE
is this a bug or not

### ISSUE THREAD

**Issue by SenpaiOw0** [tachiyomiorg/tachiyomi#8429]
### Steps to reproduce

https://user-images.githubusercontent.com/117149139/199539395-de9c8a6d-ab9f-49ee-a52c-5c86f2ced7c1.mp4

### Expected behavior

if i close my adguard https filtering 

### Actual behavior

it's says

### Crash logs

java.security.cert.certpathvalidatorexception trust anchor for certification path not found 

### Tachiyomi version

all version 

### Android version

android 7.0

### Device

Honor 6X

### Other details

should i close https filtering on Adguard?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Your version of Android is considered too old by parts of Internet.

---

For users on older versions of Android (earlier than 7.1.1) seeing `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found` when trying to access **MangaDex**, you need to manually install a certificate on your device:

1. Download the certificate from <https://letsencrypt.org/certificates/> (Active → ISRG Root X1 → Self-signed → pem)
2. Install the certificate by following <https://support.google.com/pixelphone/answer/2844832?hl=en> (exact settings path may differ on your device)
