### ISSUE TITLE
Unable to access chapters from History tab

### ISSUE THREAD

**Issue by Guts98** [tachiyomiorg/tachiyomi#8430]
### Steps to reproduce

Go to history tab
Click on any manga in the tab

### Expected behavior

What should happen is the chapter where I last left off from that comic is opened

### Actual behavior

An error is shown saying '' next chapter not found''

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Samsung galaxy M30s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Guts98** [comment]
> Can you provide actual reproduction steps with specific states of the chapters (which ones are read/unread, what ordering is set, what the history page shows)?

I just tried, and it seems the issue happens when there are no unread chapters and I try to access the chapter from the history tab.

If I leave off at chapter n, and chapter n+1 is marked as read, it seems the app loads chapter n+2 ( the next unread chapter)

So it skips chapters that marked as read

**Comment by arkon** [comment]
That sounds correct then, it should be the same as the resume button in the chapters list.

**Comment by Guts98** [comment]
Has there been a change? The way it is now the history tab is only useful when there are unread tabs,  it's doesn't work when I want to reread stuff, unless I mark them as unread, which isn't practical, especially when it's ongoing.

I have to manueally enter the manga and search the chpter I left off of
