### ISSUE TITLE
Blank screen on startup

### ISSUE THREAD

**Issue by jasonhpchu** [tachiyomiorg/tachiyomi#8431]
### Steps to reproduce

Start the app.
(I do my thumbprint unlock)
Only see blank screen with back arrow on the top left.

### Expected behavior

Enter the app and shows my library.

### Actual behavior

Only see blank screen with back arrow on the top left.
Pressing the arrow backs out of the app back to my android home screen.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung A53

### Other details

If I force close the app from my recent list, and tachiyomi starts fresh, it would work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does it happen if the security lock is disabled? Do you have a screen recording?

**Comment by jasonhpchu** [comment]
Ok, I've played with it a bit more to narrow down how to trigger it.
Pressing the android back button while in the library screen won't trigger it.
While in the middle of reading a page of a manga, if you pull out the android soft buttons, then quickly smash the back button to quit back to android home screen, the next launch will be at the blank screen.
However, doing the above SLOWLY, will not trigger this.  Key is pressing the back button multiple times while at a page of a manga.
The lock setting doesn't matter, I've tried it off, and it still resumes back into the blank screen.

**Comment by MajorTanya** [comment]
I encountered this issue as well, and recorded my screen.

Steps to reliably reproduce:
1. Open any manga chapter to the reader screen
2. Tap the back navigation button several times in quick succession 
3. Blank screen appears

Notes: The blank screen remains even after exiting with the arrow button in the top left-hand corner or via the home button, and re-entering Tachiyomi. It only disappears after closing or force-stopping the app.
 https://user-images.githubusercontent.com/39014446/199838218-a7a9c4a7-1a9e-45a2-a8e6-6d5ad5245d3c.mp4


App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_eea

**Comment by jasonhpchu** [comment]
> I encountered this issue as well, and recorded my screen.
> 
> Steps to reliably reproduce:
> 
> 1. Open any manga chapter to the reader screen
> 2. Tap the back navigation button several times in quick succession
> 3. Blank screen appears
> 
> Notes: The blank screen remains even after exiting with the arrow button in the top left-hand corner or via the home button, and re-entering Tachiyomi. It only disappears after closing or force-stopping the app. https://user-images.githubusercontent.com/39014446/199838218-a7a9c4a7-1a9e-45a2-a8e6-6d5ad5245d3c.mp4
> 
> App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016 Device brand: Xiaomi Device manufacturer: Xiaomi Device name: amber Device model: 21081111RG Device product name: amber_eea

Thanks for the input, I thought it was strange that out of how many people use tachiyomi that no one reported this yet.

Seeing how you said the succession of back button takes you to blank screen, I've confirmed this too.
I'm found that smashing the button exactly 3 times quickly, will take you to that blank screen.
The 4th time will take you to the android home screen, and the app will be stuck at that state until you clear it from recent apps.

**Comment by arkon** [comment]
From #8474:

> Open and read a manga in library on landscape orientation
> Exit the manga and revert to portrait orientation
> Close app
> Reopen and voila
>
> This is only fixed by removing the app from the recents tray.

**Comment by arkon** [comment]
This is a side effect of the weird Voyager + Conductor routing that's still in progress. It should go away once we're fully Voyager.

**Comment by arkon** [comment]
Should be fixed.
