### ISSUE TITLE
Selecting Default Home Setting disappeared

### ISSUE THREAD

**Issue by Crokos1** [tachiyomiorg/tachiyomi#8432]
### Steps to reproduce

In the previous version of tachiyomi u could choose you default home page. (Mine was Updates page) Now its gone and my default went back to being my library. I loved opening the app and seeing first had whats been updated since my library is so big and heavily cataloged by categories. Its not a huge issue. I just miss such a simple feature. I could easily set them to download and read them from there and then delete them. I usually never look at my actual library.

### Expected behavior

It should be in the Generals setting i think. As Default Home page I think it was called.

### Actual behavior

i choose the default home and the app will always open up to that which i choose

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Motorola 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
read the change log
