### ISSUE TITLE
Split tall images (BETA) bugged

### ISSUE THREAD

**Issue by TsumiHokiro** [tachiyomiorg/tachiyomi#8433]
### Steps to reproduce

1 - Long strip comic with a sufficient number of pages (10+);
2 - Scroll down the chapter as pages load;
3 - Notice the discontinuity of the comic.

### Expected behavior

No page skipping or transparent notification/display of page not downloaded.

### Actual behavior

Pages which might have been downloaded or are yet to be are skipped/not displayed as such.

### Tachiyomi version

Tachiyomi Preview486

### Android version

Android 10

### Device

SM-G9600

### Other details

I have noticed this happening at least since r478. A few things I've noticed are that:
1 - The longer the pages are, the more likely they are to be hidden/cropped/not displayed.
2 - In some cases, images that were downloaded and I managed to see a part of  soon were hidden, and the next one was displayed [page skip].
3 - A few ways to try to make the app display the images: Scroll Down and then all the way up again (Works best with chapters with more pages); restart reading the chapter; close the app and try it all again.
4 - The app may or not later re-display images that were skipped without user intervention.
5 - The middle of the image more often than not gets displayed, however, either/both upper or/and may be hidden.
6 - The Issue is gone once Split Tall Images (BETA) is disabled in Reader Settings. [Edited for English]
7 - This issue is similar to, but not exactly the same as #7943 and has been reported to jobobby04/TachiyomiSY#711 who recommended to report it here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by haganbmj** [comment]
r5202 here, same behavior. 

Applies to both Webtoon and Continuous Vertical and only when Split Tall Images is enabled. 

Continuous Vertical makes it more obvious when it happens as it makes the image splitting more obvious. 

Behavior appears to be that one of the resulting split images is skipped. 

I also get some jumpy behavior while scrolling up in a chapter, I'm assuming that's just with the order the splits are loaded in - appears to be jumping to the top of the batch. Doesn't seem to be specifically related though.

**Comment by vevinawynn** [comment]
Try this: setting > reader> default reading mode > continuous vertical
Fyi, continuous vertical is the same with webtoon

**Comment by Flanisch** [comment]
Pretty sure this is related to the option: Settings -> Reader -> Webtoon -> Split Tall Images (BETA). If that is turned on, try turning it off.
