### ISSUE TITLE
LAG UI & UNABLE TO LOAD COMIC ON SOURCE

### ISSUE THREAD

**Issue by dreamxyzvs** [tachiyomiorg/tachiyomi#8435]
### Steps to reproduce

Lag UI:
if i switching between 2 bookmark category, the animation will be so laggy.
in previous version the animation was so smooth & never get laggy even i have 250++ comics on every category.
———
Unable to load comic from source:
every 10mins reading, the source always give much time for loading or give unable to reach host message.
in 3 previous release version this could never happened, and the browser string user agent also changing. in previous version it was safari or linux(forget about this) but in newest update it becomes Mozilla/firefox win64.

### Expected behavior

the animation should be returned to old version.
and
it seems like the browser ua string also need to have a template to changing.

### Actual behavior

all those bug should never happen if dev do a private test before public release, but appreciate for this great work.

### Crash logs

--------- beginning of crash
11-03 11:09:11.810  6052  6052 E AndroidRuntime: FATAL EXCEPTION: main
11-03 11:09:11.810  6052  6052 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 6052
11-03 11:09:11.810  6052  6052 E AndroidRuntime: java.lang.IllegalArgumentException: Key extension-451576198 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:25)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:8)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:40)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:11)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-nXYdgZc(LazyListMeasure.kt:16)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:445)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke(LazyLayout.kt:27)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:68)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:57)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$2.invoke(AndroidOverscroll.kt:21)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:17)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:20)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:10)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(AndroidOverscroll.kt:21)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:17)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:20)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:10)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:11)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:20)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:10)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:9)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:66)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:9)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:48)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:92)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:18)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:34)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:125)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:191)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at eu.kanade.presentation.components.VerticalFastScrollerKt$VerticalFastScroller$2$1.invoke(VerticalFastScroller.kt:53)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:68)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:57)
11-03 11:09:11.810  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:9)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:66)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:9)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:48)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:92)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:18)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:34)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:125)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:191)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:198)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:57)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:9)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:66)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:9)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:48)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:92)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:18)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:34)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:125)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:22)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:7)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:8)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:80)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:55)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:14)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:21)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.draw(View.java:22707)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21579)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21535)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4529)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4249)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2177)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8803)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7878)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
11-03 11:09:11.811  6052  6052 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 32)
Android build ID: spark_os-userdebug 12 SQ3A.220705.004 336 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: Star
Device model: M2012K10C
Device product name: Star

### Tachiyomi version

0.14.2 (91)

### Android version

Android 12.1

### Device

REDMI K40

### Other details

![Screenshot_20221103-205511_Tachiyomi](https://user-images.githubusercontent.com/116648383/199739742-6d7d416c-e024-4759-b828-228dfdf2f3dd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
A janky animation is to be expected for a while until your phone doesn't optimize the app. Keep using it, and it will be eventually like before.

About the extension issue, please notice what you have acknowledged.

> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by dreamxyzvs** [comment]
> A janky animation is to be expected for a while until your phone doesn't optimize the app. Keep using it, and it will be eventually like before.
> 
> About the extension issue, please notice what you have acknowledged.
> 
> > If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

i know, but this problem seems not related to extension issue. because almost 8/10 extension giving the same problem. easy to timeout, even cant bypass the cloudflare. by the way, thanks for responding this issue & the animation still buggy xD. i think, i should go to previous version and waiting the next update. 
thanks
