### ISSUE TITLE
The app requires a full swipe to switch between categories

### ISSUE THREAD

**Issue by flgsercan** [tachiyomiorg/tachiyomi#8436]
### Steps to reproduce

Try to change categories by swiping sideways.

### Expected behavior

In the previous version, you could change categories with half a swipe and it would be smooth. 

### Actual behavior

It requires you to do a swipe from one side of the screen to the other. And transition animation is a little iffy. It will go back then change category with a not so smooth speed. It feels like there is no ease in and ease out, and it is too fast. 

### Tachiyomi version

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z) 

### Android version

Android version: 9 (SDK 28) Android build ID: JAT-L41HW 9.1.0.337(C432E2R2P1) 

### Device

Huawei Y6s JAT-L41

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/8310#issuecomment-1295355232
