### ISSUE TITLE
Downloaded chapters get deleted 

### ISSUE THREAD

**Issue by Lharci** [tachiyomiorg/tachiyomi#8438]
### Steps to reproduce

1. Downloaded some chapters to read
2. Read a few chapters 
3. Downloaded chapters delete after exiting the manga and updating the library

### Expected behavior

The chapters of the recently read manhwa should remain downloaded even after tapping the updating library icon, unless the chapters have been read or marked as read

### Actual behavior

After downloading some chapters of a manhwa, and reading a few of them, the remaing downloaded chapters get deleted
 ie. After exiting said mahwa, the issue occurs.
Sometimes occurs after updating the library

### Tachiyomi version

0.14.2

### Android version

Android 10

### Device

Samsung galxy J8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by yohanim** [comment]
I'm also seeing it. Either the last read one (even though i'm setting it to be retained. Worst, it happened for a serie for which I had 80 unread downloaded chapters and all unread chapters were deleted.

**Comment by yohanim** [comment]
I don't see anything special in logs (juste happened a few minutes ago)
--------- beginning of main
11-04 17:39:17.727  3400  3455 E QT      : [QT]file does not exist
11-04 17:39:17.727  3400  3455 E QT      : [QT]file does not exist
11-04 17:39:17.734  3400  3448 E SQLiteLog: (283) recovered 35 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
11-04 17:39:18.383  3400  3453 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
11-04 17:39:18.383  3400  3453 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
11-04 17:40:59.008  3400  3567 E ion     : ioctl c0044901 failed with code -1: Invalid argument
App version: 0.14.2-5188 (standard, 322224796, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_global

**Comment by yohanim** [comment]
Even though it's not each time the case, I've seen it most of the time when starting reading, power screen off as is, and power on screen a few hours after that.
