### ISSUE TITLE
Automatic plugin download & install 

### ISSUE THREAD

**Issue by OzakIOne** [tachiyomiorg/tachiyomi#8443]
### Describe your suggested feature

It would be nice if we could have a setting toggle to download and install tachiyomi's plugins.

I guess it would only work if the phone is rooted to be able to run a background service and also install the extension without user interaction.

### Other details

This would be only for already installed plugin and not newly added plugin

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Use Shizuku if you want that. Supporting the tiny subset of users that are rooted isn't worth it.
