### ISSUE TITLE
Add reset button next to brightness 

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi#8444]
### Describe your suggested feature

Guys i need reset button it's very important
Before bed i read some and use less brightness but now (day light) i can't see nothing even button to turn it off 

🙏

### Other details

Example

![IMG_20221101_141508-2](https://user-images.githubusercontent.com/61906880/199967485-bd53ae50-0ff2-4cd6-8abf-9a981a83c743.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
If you are not able to see the turn of button then the reset button will also be not visible.

**Comment by shipoxx** [comment]
> If you are not able to see the turn of button then the reset button will also be not visible.

Just turn off not reset settings to default smh
