### ISSUE TITLE
Teamx.fun back & proof of steal from anther scan

### ISSUE THREAD

**Issue by Novamanx** [tachiyomiorg/tachiyomi#8447]
### Describe your suggested feature

I catch team x steal chapters of SSS-Class Gacha
From anther scans( azure) like chp1 the end of it  watermark of azure photo ..

### Other details

![image0](https://user-images.githubusercontent.com/115431595/200004709-08932785-0933-4763-be0b-654549fba95a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Wrong repository, should open a source request issue in the extensions repository instead.
