### ISSUE TITLE
Library option/tab for showing all manga

### ISSUE THREAD

**Issue by VelocityRa** [tachiyomiorg/tachiyomi#8451]
### Describe your suggested feature

Currently when you put at least 1 category on a manga, it's removed from the Default tab. I'd like either an (optional?) "All" tab, or an option to make the Default tab show all of them.

Reasoning is, I don't see why wanting to organize my manga a bit should remove the ability to easily browse all of them. I don't have many anyway.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you can just make a category with all manga
