### ISSUE TITLE
Using mouse to refresh manga chapters does not work

### ISSUE THREAD

**Issue by eyao06** [tachiyomiorg/tachiyomi#8455]
### Steps to reproduce

Steps:
1. Have a mouse
2. Navigate to any area of the app that can refresh via a pull down (i.e. chapter list of a manga title)
3. Attempt to do a pull down refresh with mouse (hold right or left click > drag down > let go of mouse button)

### Expected behavior

Should refresh 

### Actual behavior

Nothing happens

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Samsung Tab s5e

### Other details

This broke after upgrading to version 0.14.1 and still broken in current version 0.14.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by anomuumi-leguaani** [comment]
This issue still persists in 0.14.4, unable to drag anything with a mouse, worked fine in 0.13.6
