### ISSUE TITLE
Multiselect extension uninstall

### ISSUE THREAD

**Issue by NikhilSaini38** [tachiyomiorg/tachiyomi#8456]
### Describe your suggested feature

User should be able to long press extension from installed list to start multiselect or a trigger multiselect view from multiselect icon in top bar on extension page and select garbage bin icon from top bar to trigger uninstall for multiple extensions. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NikhilSaini38** [comment]
Seems like its duplicate of #6870. I would implore authors to reconsider.

**Comment by arkon** [comment]
Long pressing already triggers the uninstallation flow, which also requires user input anyway.
