### ISSUE TITLE
Merge extensions 

### ISSUE THREAD

**Issue by Novamanx** [tachiyomiorg/tachiyomi#8457]
### Describe your suggested feature

I mean instead of make duplicate copies from a manhwa ,manga etc make it merge them in one icon the first extension gets new chapters is add , and the lost chapters for any of the the ather one complete it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No, the UX and implementation are both nightmares.

Curate your own content with local or a remote source like Komga if you want that.
