### ISSUE TITLE
My tachiyomi is displaying "tomorrow" instead of "today"

### ISSUE THREAD

**Issue by Tsoura** [tachiyomiorg/tachiyomi#8463]
### Steps to reproduce

1. Open App
2. Update library

### Expected behavior

Should display today instead of tomorrow

### Actual behavior

![Screenshot_20221106-012302_TachiyomiJ2K](https://user-images.githubusercontent.com/117551711/200149866-157b973e-03dc-48ac-88d6-25620c0fe763.jpg)

### Tachiyomi version

1.5.9

### Android version

Android 12

### Device

Samsung A21s

### Other details

Language: Portuguese
Tachiyomi j2k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
wrong repo, this isn't j2k but, sources saying the date a chapter is uploaded in the future are just extension things
it saying fetched tomorrow means you manually moved your device clock back or entered a different time zone

**Comment by Tsoura** [comment]
I did not move my device clock nor did i enter another time zone that's why I'm posting.

**Comment by arkon** [comment]
It's Daylight Savings.

**Comment by Tsoura** [comment]
> It's Daylight Savings.

In my country they are in 27 of March and 30 of October.
