### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by AtaideDev** [tachiyomiorg/tachiyomi#8465]
### Describe your suggested feature

This post is a question and some suggestions in case the answer to the question is "Yes" - Did Tachiyomi really put ads or is it a bug of my smartphone?  if you have placed it, I ask you to increase the time they should appear, I just saw 3 ads in less than 5 minutes. ). Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Tachiyomi does not have ads, nor will we ever have ads. Make sure to get Tachiyomi off our official site at https://tachiyomi.org instead of similar apps on the Google Play Store and such.
