### ISSUE TITLE
See what mangas you put in your library from specific extension

### ISSUE THREAD

**Issue by itszux** [tachiyomiorg/tachiyomi#8467]
### Describe your suggested feature

I have a lot of extensions and I want to reduce them by uninstalling the ones that I don't have any manga from so the suggestion is to see all the mangas you put in your library from an extension from its settings 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You can already see what titles belongs to each extension through the Migrate tab on Browse or by searching the extension name on the library.

**Comment by itszux** [comment]
Yeah but migrate tab don't show the empty extensions, and for searching it's gonna be alot to do of copy (name of extension) and paste if you have over than 50 extension
