### ISSUE TITLE
Extension-roumanwu is no longer accessiable and error at opening

### ISSUE THREAD

**Issue by walthack** [tachiyomiorg/tachiyomi#8468]
### Steps to reproduce

1. open roumanwu from source directly or open any book from roumanwu resource
2. error message: Fields [headline, best, hottest, daily, recentUpdatedBooks, enedBooks] are required for type with serial name 'eu.kanade.tachiyomi.extension.zh.roumanwu.HomePage', but they were missing at path: $.props.pageProps at Path:$.props.pageProps at path: $.props.pageProps

### Expected behavior

Should open book or webpage from roumanwu as normal

### Actual behavior

Error msg and cannot view book from that source any longer.

### Tachiyomi version

Stable 0.14.2

### Android version

Android 12

### Device

Z Fold 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Read what you acknowledged
