### ISSUE TITLE
Blank screen after re-opening the app

### ISSUE THREAD

**Issue by VenomMage** [tachiyomiorg/tachiyomi#8474]
### Steps to reproduce

I get a blank screen after reopening the app. This only happens after repeating the steps below:

1. Open and read a manga in library on landscape orientation 

2. Exit the manga and revert to portrait orientation

3. Close app

4. Reopen and voila

This is only fixed by removing the app from the recents tray.

### Expected behavior

The app opens normally.

### Actual behavior

I get a blank screen.

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung Galaxy M51

### Other details

![Screenshot_20221107-084646_Tachiyomi](https://user-images.githubusercontent.com/54541621/200453214-e5c4846d-3c38-4d7b-8455-48c02cbdb95f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Merging with #8431
