### ISSUE TITLE
Keep/Hold Place in Displayed Manga List from Library

### ISSUE THREAD

**Issue by buthub** [tachiyomiorg/tachiyomi#8475]
### Describe your suggested feature

Hi, it would be great if Tachi would hold the place you've scrolled to in my giant lists of manga when I'm switching between places. Also, when I'm returning to the library from a manga title (after leaving it alone for a while, if you return to the library from the manga, you'll wind up at the top of the list on your library category again, forcing you to scroll and scroll to find where you were), the list should at least scroll to where the manga title is. This is a pain when you're trying to methodically go through a category. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already should unless you have a low memory device (or some other reason that the app can't hold the state in memory).
