### ISSUE TITLE
Selecting mark previous as read not deleting downloaded chapters even when option delete chapter when manually marked read is selected in downloads section of settings

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi#8482]
### Steps to reproduce

This was working in previous version but does not seem to be working in latest version.
Go to download section in settings
Enable After manually mark as read in delete chapters
Go to manga which has downloaded chapters say from 1-10
Select ch 10 and click on mark previous as read

### Expected behavior

In previous versions upto  0.13.6

It would delete chapters from 1-9

### Actual behavior

Does not delete the chapters

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Asus Max pro m1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KittyCatCrunchie** [comment]
Been having this for a while too. Never got around to submitting it as a bug. But for at least the last 4 version releases lol. I'm just collecting chapters now.

**Comment by arkon** [comment]
Generally seems to work when testing. There may be a bit of a delay since managing files can be slow, especially with SD cards. You should see it being reflected if you re-enter the chapters list later.

**Comment by KittyCatCrunchie** [comment]
Hmm okay. It's sort of been like this for months already. But it's not that
big a deal i guess.
