### ISSUE TITLE
No start screen option in latest update

### ISSUE THREAD

**Issue by bungadrum** [tachiyomiorg/tachiyomi#8486]
### Steps to reproduce

I wanted to set start screen to Browse
1. More
2. General
3. Start screen 
4. Set your choice

### Expected behavior

I would like the "Start Screen" option back in More, Settings, General, Start Screen

### Actual behavior

The option is missing in latest version it redirects you to the default Libary instead

![screenshot](https://user-images.githubusercontent.com/75974100/200796868-e4e71d50-6757-416b-af06-183c830a6625.jpg)

### Tachiyomi version

Stable 0.14.2

### Android version

EMUI 12

### Device

Huawei Nova Y70

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Read the 0.14.0 changelog
