### ISSUE TITLE
Updates keep failing

### ISSUE THREAD

**Issue by elyes007** [tachiyomiorg/tachiyomi#8494]
### Steps to reproduce

Pull to refresh updates

### Expected behavior

Update operation takes a bit of time and ends in success

### Actual behavior

Update operation takes too long and ends in failure every time

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Samsung Galaxy S22 Plus

### Other details

Additionally, when clicking the notification indicating an error has happened, the app isn't opened, but we're shown a disambiguation dialog where the app is not an option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Update error log is a text file open it with one of the available options to read it. And updates failing isn't a issue with the app but one of the sources you are using so open a issue [in extensions repo](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new)  next time
