### ISSUE TITLE
DOES not update anymore .

### ISSUE THREAD

**Issue by lloskka** [tachiyomiorg/tachiyomi#8496]
### Steps to reproduce

Swipe to update your manga list.

### Expected behavior

Finish scan without errors.

### Actual behavior

It take almost like 15 Min to update 15 mangas from 2 sources ( mangafreak and mangasee )

Most of the time gives error not updated , after finished scan.

### Crash logs

Fallo al evitar Cloudflare
  # Mangafreak (EN)
    - Baki - Son Of Ogre
    - Baki-Dou (2018)
    - Boruto: Naruto Next Generations
    - Dragon Ball
    - Dragon Ball Super
    - Fairy Tail
    - Grappler Baki
    - Hunter X Hunter
    - Kimetsu no Yaiba
    - Mob Psycho 100
    - My Hero Academia
    - Nanatsu no Taizai
    - Naruto
    - One Piece
    - Onepunch-Man

! timeout
  # Mangafreak (EN)
    - OnePunch-Man (ONE)
    - Shingeki no Kyojin

### Tachiyomi version

0.14.2

### Android version

Android 12 Magic UI 6.0.172 

### Device

Honor Magic 4 Pro  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>  I have tried the troubleshooting guide.

Consult Discord for support help if that doesn't help.

**Comment by lloskka** [comment]
Ok, so it Seems latest update from my Phone Seems to have fucked UP webview somehow .

Still Cannot update after throughrously read trobleshothing.

From an clueless user, can tachiyomi somehow be made universal from any kind of combination OS  + SURFER ?

Thank you .
