### ISSUE TITLE
some text in reader  doesn't respect color theme

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#8499]
### Steps to reproduce

open a title and start reading a chapter
strings like "chapter loading", "there's no previous chapter" and "there's no next chapter" don't respect 
color theme 
reading with yin yang grayscale theme:
![Screenshot_20221111-130435](https://user-images.githubusercontent.com/40524589/201255078-6935d213-864a-43a2-819f-a267dd315262.png)

### Expected behavior

afore mentioned text respects color theme

### Actual behavior

distracting purple text breaking immersion

### Tachiyomi version

0.14.2

### Android version

android 13

### Device

google pixel 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce. Please provide more details about your settings (e.g., reader background, system dark theme).

**Comment by skrshe** [comment]
strange 

default reader background
dark mode and amoled black don't seem to affect it

gone through two updates since I noticed this,
thought it was an aesthetic change

will try backup uninstall and reinstall

**Comment by skrshe** [comment]
fixed after hard reset
