### ISSUE TITLE
options for how to resume reading a title

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#8504]
### Describe your suggested feature

Option to resume reading a title from:
- lowest unread chapter (current)
- after highest read chapter
- latest read chapter

I suggest this have global, per tab and per title setting

### Other details

***after highest read chapter:***
When I've skipped chapters I end up resuming from them instead of what I'm up to

***latest read chapter:***
When I start reading a title that I've already finished from a lower chapter than the last chapter my position isn't saved and I end up at the last chapter instead of where I left off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No, just set your sorting and mark things as read/unread as needed.

**Comment by skrshe** [comment]
😿
