### ISSUE TITLE
Clear chapter cache on app close doesn't work.

### ISSUE THREAD

**Issue by Volern** [tachiyomiorg/tachiyomi#8506]
### Steps to reproduce

The clear chapter cache on app close doesn't work for me. I have tried reinstalling and updating, force close app and just normally close app and clear app list to remove it from memory.

I can clear my manually just fine, and I've tried turning the option off and on a few times but it doesn't seem to actually be doing anything at the moment.

### Expected behavior

Chapter cache should be cleared on app close.

### Actual behavior

Nothing happens and chapter cache is retained.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Oneplus 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closing the app means pressing back until the app is dismissed and you go back to your home screen.

Killing it from recents does not trigger the app close lifecycle.
