### ISSUE TITLE
Kiryuu error

### ISSUE THREAD

**Issue by BANANA25323** [tachiyomiorg/tachiyomi#8510]
### Steps to reproduce

1. Open Tachiyomi
2. Move to Browse menu
3. Open Kiryuu extensions
4. Error "Failed to bypass CloudFlare"

### Expected behavior

Showing manga, manhwa and manhua

### Actual behavior

Error

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Realme Narzo/Realme 6i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

> I have tried the troubleshooting guide.
