### ISSUE TITLE
Webcomics Extension not working 

### ISSUE THREAD

**Issue by hydrayash** [tachiyomiorg/tachiyomi#8514]
### Steps to reproduce

Not working 
![Screenshot_20221112_204721](https://user-images.githubusercontent.com/56506857/201481014-e5471447-28c2-45c9-a21e-ad4668256032.jpg)
![Screenshot_20221112_204714](https://user-images.githubusercontent.com/56506857/201481018-8bd37dff-a746-45db-9855-c766f84149fe.jpg)

### Expected behavior

Chapter should appear 

### Actual behavior

No chapter found
![Screenshot_20221112_204721](https://user-images.githubusercontent.com/56506857/201481040-db46f7e2-dab3-4a85-b4cc-684a994748c9.jpg)
![Screenshot_20221112_204714](https://user-images.githubusercontent.com/56506857/201481041-d5034039-d7dd-471e-a315-43f09b9d82b7.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

IQOO 9 SE

### Other details

![Screenshot_20221112_204721](https://user-images.githubusercontent.com/56506857/201481077-3b6705c2-4017-4982-bdbe-ceb59d89968a.jpg)
![Screenshot_20221112_204714](https://user-images.githubusercontent.com/56506857/201481079-25a14872-a4b8-4886-b958-2a1e5dcc8963.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also at least try to put some effort into filling out the form.
