### ISSUE TITLE
Yaoi Manga Online unreadable chapters

### ISSUE THREAD

**Issue by Damselflies** [tachiyomiorg/tachiyomi#8516]
### Steps to reproduce

Chapters unreadable
When clicking on a title and attempting to read it you'll get an error, no pages found.

### Expected behavior

Opening chapter to pages to read it

### Actual behavior

Nothing lol

### Tachiyomi version

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z) 

### Android version

Android version: 11 (SDK 30) 

### Device

Motorola Moto g(9) power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
