### ISSUE TITLE
Continue reading button behaviour

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8522]
### Describe your suggested feature

_The newly added Continue reading button in library screen_

When there is no unread chapters:
1. Either hide the button 
Or
2. Show a toast/snackbar saying "no next chapter"

Imo second option would be better as the library will be visually consistent with a button on all entries.

### Other details

Currently, when there is no unread chapter the continue reading button does nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
2nd option seems fine
