### ISSUE TITLE
Reading mode for each series 

### ISSUE THREAD

**Issue by ModdyxBeast** [tachiyomiorg/tachiyomi#8533]
### Describe your suggested feature

The feature should make it that you don't have to choose between reading modes everytime you want to switch between manga or manhwa. Either by assigning a reading mode for each series individually or choosing a default reading mode for each category individually. So if I include all my Webtoons on one category I just assign that category to Webtoon reading mode while all my other series stay on right to left

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Changing reading mode inside reader (not from app settings) applies to that series only
