### ISSUE TITLE
Adjustment on Grid Size per row ...

### ISSUE THREAD

**Issue by waqar1231** [tachiyomiorg/tachiyomi#8535]
### Describe your suggested feature

Like TachiJ2k Have grid size Adjustments , Tachiyomi stable should also Include that feature. 
Please add grid size per row. 
Some people have Small phones and some just have bad eye sight so why not .. 

I will attach screenshot for convenience and Thank you very much from whole weeb community 😀 😊.  
![Screenshot_20221115-110333_TachiyomiJ2K](https://user-images.githubusercontent.com/47387148/201835457-308cc4f0-4581-473f-af02-4c5d35868199.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Take 2 minutes to explore the settings
