### ISSUE TITLE
Surrogate pair with high surrogate in string makes ComicInfo.xml generation to fail

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#8537]
### Steps to reproduce

1. Open Bilibili Comics source
2. Search Martial God Asura
3. Notice the genre "🔒 Paid" emoji "🔒" has a high surrogate "d83d"
4. Download any chapter

### Expected behavior

ComicInfo.xml to generate and Download to complete

### Actual behavior

ComicInfo.xml generation fails and there's a download error notification "In XML 1.0 the character 0xd83d is not valid"

### Tachiyomi version

Preview r5242

### Android version

N/A

### Device

N/A

### Other details

This is not exclusive to the genre field but applies to every other field. 

XmlUtil throws a error for having a high surrogate [here](https://github.com/pdvrieze/xmlutil/blob/672d85a61314957126502db639902b3a59648e6b/core/src/commonMain/kotlin/nl/adaptivity/xmlutil/core/KtXmlWriter.kt#L152)

CC @Shamicen 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Shamicen** [comment]
Short status Update:

The new version of xmlutil has been released but there was a new bug concerning Codepoints. 
The Bug has been fixed in the Dev branch, which means we will have to wait for the next release before re-enabling the creation of ComicInfo files.
