### ISSUE TITLE
Cosmic scans repeating scenes 

### ISSUE THREAD

**Issue by e786** [tachiyomiorg/tachiyomi#8538]
### Steps to reproduce

1. Get on Cosmic scans and find a series (I used [Cooking Wizard] and [Bizarre Restaurant]
2. Get on the lastest chapters
3. Find that the chapters are twice as long but scenes repeat.

### Expected behavior

The chapters should be shorter and the scenes should not repeat

### Actual behavior

Scenes repeat and makes reading to the next scene take longer

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Google Pixel 5

### Other details

Only happening for the lastest chapters of a series

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
