### ISSUE TITLE
Uninstall option when tap and hold an extension 

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#8542]
### Describe your suggested feature

When we tap and hold an installed extension, a uninstall option should be there to uninstall the extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already exists.

**Comment by arkon** [comment]
Go to the extensions tab.
