### ISSUE TITLE
Tachiyomi won't update me on chapters that have released 

### ISSUE THREAD

**Issue by CommicKick69ing** [tachiyomiorg/tachiyomi#8543]
### Steps to reproduce

1.) Click the updates tab
2.) Click the refresh circle
3.) Nothing happens 

### Expected behavior

1. Click on updates tab
2. Click refresh circle
3. Nothing happens 

### Actual behavior

The expected behavior is that it will update me whenever any new chapters are released. But it will not, the only way I can find out if new chapters have released anymore is to refresh each individual title. And it annoying 

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries
