### ISSUE TITLE
Custom delay between each manga update when updating library 

### ISSUE THREAD

**Issue by AgileGhost** [tachiyomiorg/tachiyomi#8547]
### Describe your suggested feature

I believe this would be a great feature to flatten the curve and reduce the overall impact on sources if people have the option to add a custom delay. Let's say it's 15 seconds between each manga when they update their library.

For example:
Updates Manga 1
waits 15 seconds
Updates Manga 2
waits 15 seconds
..and so on.

If people actually use this, it should reduce the impact on sources to a certain extent. But in return, it will take longer to update/ Which I believe is a fair trade-off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by d-najd** [comment]
I don't think this would work since tachiyomi has large user base the number of request per second wont change much in the grand scheme of things (you will still be checking the entire library).

#8402 is a better way to ease server load imo but I am waiting for review.

**Comment by AgileGhost** [comment]
> I don't think this would work since tachiyomi has large user base the number of request per second wont change much in the grand scheme of things (you will still be checking the entire library).

Well yeah, it wouldn't change much other than flattening out the request spikes here and there. But it would be useful when a source puts a rate limit on. But I digress. 

> #8402 is a better way to ease server load imo but I am waiting for review.
I do like the suggestion you mentioned, it would be very useful in reducing the amount of requests sent and indeed would have a better impact than my suggestion.

**Comment by arkon** [comment]
Similar to #6968
