### ISSUE TITLE
Somehow extensions show only first page

### ISSUE THREAD

**Issue by JotaFurry** [tachiyomiorg/tachiyomi#8548]
### Steps to reproduce

1- Open the app
2- Go to extensions and open any of them.
3- Scroll down
4- See a limited amount of uploads instead of loading as it scrolls down

### Expected behavior

It should keep loading new uploads on the extension as you scroll down

### Actual behavior

It loads a determined amount and stops loading new content when you scroll down

### Tachiyomi version

TachiyomiEH (unknown version) & TachiyomiAZ (8.7.2az)

### Android version

MIUI 12

### Device

Redmi Note 7

### Other details

I used to use TachiyomiEH, but it stopped working as it did because of this problem. Searching for answers, I saw a post saying TachiyomiEH wasn't going to get updates anymore and they recommended TachiyomiAZ. So I installed it but... It does not work too. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Or if this is specific to AZ, open an issue in its repo.
