### ISSUE TITLE
Details not showing for Local Manga

### ISSUE THREAD

**Issue by DakshKK** [tachiyomiorg/tachiyomi#8549]
### Steps to reproduce

A `details.json` in folder containing manga chapters, in a nested folder structure in the following format:

    - Manga
    |-- Ch1.cbz
    |-- Ch2
    |-- details.json

### Expected behavior

When browsing local source, description should be read from `details.json` as documented at [Local manga | Tachiyomi](https://tachiyomi.org/help/guides/local-manga/#editing-local-manga-details).

### Actual behavior

There are no details shown, and no information to suggest how manga description can be added; along with a phantom `.noxml` file has cropped up in all the local folders, and would want to understand if Tachiyomi was responsible for it.

Some searches have suggested the use of `ComicInfo.xml` now by Tachiyomi, so I wanted to suggest updating of documentation, or providing a resource for it.

I can update the some if references or guides are provided for it.

### Tachiyomi version

r5242

### Android version

9

### Device

Vivo Y15

### Other details

`ComicInfo.xml` was added to Tachiyomi, but can't find any documentation.

Every chapter download creates a `ComicInfo.xml`, but does not clear it after all chapters have been deleted/read, leaving a folder in the file structure, with just a `ComicInfo.xml` file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Wraith9881** [comment]
Having the same problem.  The details only display when opening the comic, and pulling down from the top to refresh.  Searching with tags doesn't work unless I've already clicked the comic before and refreshed.  Only started having this problem with this new release.

**Comment by DakshKK** [comment]
> They documented it on the v.0.14.0 release that they can read ComicInfo.xml now.  [Here](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.0)

Could you maybe share any documentation regarding the ComicInfo.xml file and it's format. Can't seem to find any docs regarding that.

Use of ComicInfo.xml is something I found via the What's New section in the app.

**Comment by curche** [comment]
https://anansi-project.github.io/docs/comicinfo/documentation

Closely associated with the Komga Manga/Comics Server  project, this was mentioned in the original PR
See https://github.com/tachiyomiorg/tachiyomi/pull/8025
Didn't really make it into the Changelogs
