### ISSUE TITLE
Choice between reading per Chapter/Volume

### ISSUE THREAD

**Issue by DakshKK** [tachiyomiorg/tachiyomi#8550]
### Describe your suggested feature

As seen on [MangaReader](https://mangareader.to), would like that a certain method of reading be implemented, since some people don't like reading individual chapters, but consolidated volumes.

To implement the same in local manga, we could maybe make a `cbz/cbr/cbv(volume)` file/folder, with nested folders of chapters/`cbz/cbr` files, in the following way:

    - Manga
    |-- Volume1.cbz
    |   |-- Chapter1
    |   |-- Chapter2.cbz
    |-- Volume2
        |-- Chapter3
        |-- Chapter4.cbz

### Other details

A method to switch between per chapter/per volume reading as per user wish, instead of setting a default method of reading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The app is heavily dependant on the current chapter structure, so this would be unlikely to ever happen.
