### ISSUE TITLE
Auto update story when pressing start or resume

### ISSUE THREAD

**Issue by sininen-blue** [tachiyomiorg/tachiyomi#8551]
### Describe your suggested feature

There should be a setting that allows for a story to update when pressing the "start" or "resume" button.

This would be particularly useful if you have some "skip updating entries" options enabled or just have long auto update intervals

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We generally don't want to make unnecessary calls to sources, so I'll have to reject this.
