### ISSUE TITLE
Date selector inputs one day less

### ISSUE THREAD

**Issue by arynthernium** [tachiyomiorg/tachiyomi#8553]
### Steps to reproduce

1. Open Tachiyomi
2. Enter any manga page within your library
3. Open the trackers menu
4. Open a "Start date" or "Finish date" selector
5. Input a date

### Expected behavior

Input should accurately reflect the date I input. For example, when entering the 17th of November 2022, shown date should be 17th of November 2022.

App should also correctly report the date to trackers. Date entered should be shown on MyAnimeList and Anilist.

### Actual behavior

After pressing "OK" in the date selector, shown date is one day before the selected date. Ex: 17th of November 2022 becomes 16th of November 2022.

Trackers become updated to the incorrect date, one day before the selected one.

https://user-images.githubusercontent.com/69891576/202524417-a45dfe4e-51d7-457d-9962-f67965beb97b.mp4

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung Galaxy S10

### Other details

App version: 0.14.2-5242 (standard, b1ccebf32, 91, 2022-11-13T17:27Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G973USQU7IVH3
Device brand: samsung
Device manufacturer: samsung
Device name: beyond1q
Device model: SM-G973U
Device product name: beyond1qltesq

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
What country are you in?

**Comment by arynthernium** [comment]
I'm in Canada, Eastern Time.
