### ISSUE TITLE
Issue with source 

### ISSUE THREAD

**Issue by UCHIHAMO** [tachiyomiorg/tachiyomi#8555]
### Steps to reproduce

1_open the manhwa then this issue appears
Attempt to invoke virtual mathed java lang String org jooup nodes Element datal)' on a null object reference

### Expected behavior

The chapter supposed to open normaly

### Actual behavior

Attempt to invoke virtual mathed java lang String org jooup nodes Element datal)' on a null object reference

### Tachiyomi version

0.14.0

### Android version

12

### Device

Oppo A 94

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
