### ISSUE TITLE
Add "custom doh" option

### ISSUE THREAD

**Issue by X-Ominier** [tachiyomiorg/tachiyomi#8557]
### Describe your suggested feature

Unfortunately non of current dohs implanted in Tachi doesn't work in my country (they are blocked). 

I want to add a custom one Wich I know works well (I tested it in other apps) but as u know it is not possible for now.

Can u add this feture in Tachi ?

### Other details

The doh server I want to add :
Https//dns.shecan.ir/dns-query

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Is it this? https://shecan.ir/

The website says `https://free.shecan.ir/dns-query`

**Comment by alessandrojean** [comment]
Isn't it worth setting it system-wide instead as you would likely also would want to use in other apps too?

**Comment by X-Ominier** [comment]
As you know ,doh support came in android 9 and I'm 6.

To force it, I should use a vpn config with an app (Which I use now) .

But for auto update feture ,that vpn needs to be turned on too . And as you know system wide proxy use more power than an app proxy.
(If enable it I need to recharge my phone every 4 houres)

And plus this dns isn't fast enough to be used as a daily thingy .
I just use it to bypass censorship.
I tried a almost all of the extentions

**Comment by X-Ominier** [comment]
> Is it this? https://shecan.ir/
> 
> The website says `https://free.shecan.ir/dns-query`

They are the same . I tested it .
But our community prefers this one . 
Reason : IDK
