### ISSUE TITLE
CBZ Download Fails - Can't open InputStream

### ISSUE THREAD

**Issue by annonmerchy** [tachiyomiorg/tachiyomi#8560]
### Steps to reproduce

1. Change "Download location" (I set it to external storage)
2. Enable "Save as CBZ archive"
3. Download Manga (NH 158097). It doesn't fail on all titles, but the one's that fail do so consistently.

### Expected behavior

Download should work

### Actual behavior

Error Notification - Can't open InputStream

### Crash logs

[tachiyomi_crash_logs.txt](https://gist.github.com/1123098d32a4d2e7ef125e087317c81d)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

I originally encountered this issue in a TachiyomiSY, but the issue occurs in the original as well.
I don't believe this to be an extension specific issue as I've managed to reproduce it on other extensions.
It's possible that this is related to Scoped Storage and/or file length, but it's unclear to me on what the specific issue is.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mutsumi63** [comment]
I have the same bug, I can download cbz to external storage. but I can‘t open the chapter if it save as cbz and in external storage. PNG/jpg is ok in external storage,same manga ,same chapter

**Comment by annonmerchy** [comment]
To clarify a bit:
- The PNG/JPG files are successfully downloaded
- The error occurs when it tries to create the ZIP/CBZ file

I just tested and confirmed that this is still an issue on version [0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest).
