### ISSUE TITLE
Can't search on Chromebook

### ISSUE THREAD

**Issue by Pherrara** [tachiyomiorg/tachiyomi#8564]
### Steps to reproduce

Install tachiyomi from the Apk and open the app.
Install mangadex or anything else as extension.
Go to sources and try searching something, when pressing <Enter> nothing happens.

### Expected behavior

Should have performed the search

### Actual behavior

Search didn't start

### Tachiyomi version

0.14.2

### Android version

Chrome OS Version 107.0.5304.110 (Official Build) (64-bit)

### Device

Asus Chromebook CX1500CK

### Other details

Everything else works fine.
I think this problem happens because when I press Enter on the keyboard it registers as "go to the next line and take some more input", and not "ok, start the search", any workaround for this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should already be fixed in preview by #8529
