### ISSUE TITLE
Long press webview to copy source url

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#8572]
### Describe your suggested feature

Long pressing webview should copy it's source url to clipboard 

### Other details

Duplicate of #8471, opening new issue because can't comment on that one.
The problem is, there are some app which doesn't show up when sharing from tachiyomi and in current version, "Copy to clipboard" option in sharing is not coming in my device so long pressing webview to copy source url is helpful in that case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mayorJAY** [comment]
I will like to implement this feature

**Comment by arkon** [comment]
Pretty cursed that your ROM doesn't show the common copy action in a share sheet...
