### ISSUE TITLE
Error 401 when I try to tracking

### ISSUE THREAD

**Issue by AzureGu** [tachiyomiorg/tachiyomi#8573]
### Steps to reproduce

1.tap tracking button
2.choose my service
3.choose manga

### Expected behavior

manually adjust reading progress

### Actual behavior

the pop-up window prompts http error 401

### Tachiyomi version

0.14.2

### Android version

Android12

### Device

Xiaomi Redmi k30pro/Poco f2 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Just relogin in the tracking settings if it's MyAnimeList. If it's Anilist it's expected to have errors at the moment as they disabled their API for third party apps like Tachiyomi; wait until they enable it again.

**Comment by AzureGu** [comment]
> Just relogin in the tracking settings if it's MyAnimeList. If it's Anilist it's expected to have errors at the moment as they disabled their API for third party apps like Tachiyomi; wait until they enable it again.

The bangumi I used was still working properly before. Today, I collected a new manga and suddenly found that it cannot be used normally.
![Uploading Screenshot_2022-11-20-22-23-29-514_eu.kanade.tachiyomi.png…]()
