### ISSUE TITLE
[Issue] Clicking on tags and then come back makes the app exit the extension

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8575]
### Steps to reproduce

1. Open an extension
2. choose an entry
3. click on a tag, wait it loads
4. press back button from the android navigation bar
5. the app exists the extension

https://user-images.githubusercontent.com/75091899/202898072-67a5da9d-b7bd-4491-b4c6-4d4df5cbfe26.mp4

### Expected behavior

The app should come back to the entry where i clicked the tag and taking the video above as example the app should come back here
![Screenshot_20221120-114930](https://user-images.githubusercontent.com/75091899/202898142-08545cbe-9066-4137-894e-e4871e557139.jpg)

### Actual behavior

The app exits the extension, and it happens on all extensions

### Tachiyomi version

0.14.2 (tachi sy r490)

### Android version

Android 8

### Device

huawei p8 lite 2017

### Other details

this dynamic occours in all extensions. i know i said tachisy but i noticed this way before i started using tachisy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is more of a feature request to retain it in the stack, but I don't think we would given the actual hierarchy of the screens.

**Comment by Palloxin** [comment]
@arkon Imagine this scenario, Bob is scrolling in an extension a lot of entries from a single filtered search and opens some entries to check the tags and the number of chapters. He clicks(or tap) on a tag by mistake and wants to go back to its scrolling. Unfortunetely he can't go back and has to do the filtered search again, scroll down all the entries he already checked until he reaches the point of that last entry. Isn't it uncomfortable?

**Comment by arkon** [comment]
The two issues aren't remotely similar. There's technical reasons for how the screen hierarchy works and we're not close to replacing that.

**Comment by Palloxin** [comment]
I see :(
