### ISSUE TITLE
"Manhwa-raw" extension No Chapters Found

### ISSUE THREAD

**Issue by Musang13** [tachiyomiorg/tachiyomi#8580]
### Steps to reproduce

1. The website yesterday (nov 20) is not available
2. When the website is back and when you gonna update chapter it says "No Chapters Found

### Expected behavior

should happen is when updating the chapter there will be new chapter comes out in tachiyomi

### Actual behavior

![Screenshot_2022-11-21-08-12-51-67](https://user-images.githubusercontent.com/90293695/202934356-de00979c-2dee-4e11-8553-668cfeaaf049.jpg)

This is happen now when site back to online

### Tachiyomi version

0.14.2

### Android version

Android 8

### Device

Oppo a5s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by d-najd** [comment]
should probably be moved to extension repository, also provide name of the extension.

**Comment by curche** [comment]
> also provide name of extension

That'd be manhwa-raw, no?

**Comment by d-najd** [comment]
> > also provide name of extension
> 
> That'd be manhwa-raw, no?

oh you are right, my bad.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
