### ISSUE TITLE
QoL: Add Toggle for Automatically deleting downloaded chapters after pressing

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8585]
### Describe your suggested feature

It should work like this...
When disabled; you will not delete downloaded chapters by holding the checkmark.

> ### Delete chapters
> Hold checkmark to automatically delete: yes/no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No, there's already 3 ways to delete downloaded chapters.

**Comment by pseudo-demon** [comment]
1. From inside the manga
2. From the library
- [X] Remove from library
- [X] Downloaded chapters
3. After reading automatically delete
Is this correct?
@arkon

**Comment by curche** [comment]
Yes
