### ISSUE TITLE
Choosing other tabs to be default when opening app

### ISSUE THREAD

**Issue by ShockedCoder** [tachiyomiorg/tachiyomi#8590]
### Describe your suggested feature

Being able to choose what tab the app opens up on startup from settings.
For example: when opening the application instead of the library tab being the first thing you see it's the history tab.

I don't quite understand why this feature was removed in the first place.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Refer to the release notes: https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.0

**Comment by ShockedCoder** [comment]
Is there a reason for removing the startscreen?
I know it's a press and hold and then there's a list, but it's rather annoying to have it that way.

**Comment by arkon** [comment]
Because there's too many rarely used settings/features littering the app and making things difficult to maintain. It's easier to opt for standard Android functionality like shortcuts (which were already supported by the app before) than maintain our own version of it.

Like any app shortcut, you can drag a shortcut to your homescreen if you want quicker access to it.

**Comment by ShockedCoder** [comment]
> Like any app shortcut, you can drag a shortcut to your homescreen if you want quicker access to it.
Never knew, thanks for the info.
