### ISSUE TITLE
Custom filter: Add +/- or custom number input from user keyboard

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8591]
### Describe your suggested feature

Add + and - next to the number in custom filter. Make user able to use keyboard to specify the number
| Custom brightness | [----🟢] |
| :--- | :---: |
| 🌞 ————⚫———— | **+ [1] -** |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pseudo-demon** [comment]
![My master knows everything chapter 5](https://user-images.githubusercontent.com/118722936/203226767-e7463ffc-144b-467e-a142-0613c40bf4da.png)
![Custom filter](https://user-images.githubusercontent.com/118722936/203263627-1a156d07-8621-48d8-8bfb-2f347a8df80c.png)
![Gboard](https://user-images.githubusercontent.com/118722936/203225274-6c4a76e3-868e-4743-b03f-bb4d194465c6.png)

**Comment by AntsyLich** [comment]
I don't see why you would need correct precision
