### ISSUE TITLE
QoL: Selected Refresh and Add refresh button on manga cover

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8592]
### Describe your suggested feature

It should work like this... when you click the refresh button, it refresh the page or cover (if there is).
| Selected Refresh in the Library | Manga cover inside the manga |
| --- | --- |
| ![Refresh button on Library tab](https://user-images.githubusercontent.com/118722936/203236947-8b122b24-8c49-454f-94f3-f33602bc2a4a.png) | ![If AI Ruled The World. Cover](https://user-images.githubusercontent.com/118722936/203231539-73347528-f76e-4374-99c0-4a86e1c02a6b.png) |
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Just global refresh

**Comment by arkon** [comment]
No, just refresh on the details screen.
