### ISSUE TITLE
3-times click refresh in the Library tab

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8593]
### Describe your suggested feature

On the Library tab, User click or press on a manga, manhwa, manhua, comic or title cover. The page will refresh

### Other details

1. User click 3 times on the manga with red border ![Library tab](https://user-images.githubusercontent.com/118722936/203235573-2238f9a1-877f-4a9a-8038-3258f921dd9a.png)
2. Page refresh

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pseudo-demon** [comment]
Inspired from #8476 bug

**Comment by arkon** [comment]
No, just refresh on the details screen.
