### ISSUE TITLE
Delete downloaded chapter from library doesn't delete empty Source folder.

### ISSUE THREAD

**Issue by aykirito** [tachiyomiorg/tachiyomi#8594]
### Steps to reproduce

1. have atleast 1 downloaded chapter manga from any source
2. try delete from library
3. check Tachiyomi download folder in file explorer. source folder remain behind 

### Expected behavior

it should delete source folder as well if no manga downloaded from the source

### Actual behavior

source folder remain in download

### Tachiyomi version

0.14.2

### Android version

Android 8

### Device

Galaxy S7 Edge

### Other details

source folder deleted together if delete downloaded chapter within manga instead library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pseudo-demon** [comment]
#2108

**Comment by pseudo-demon** [comment]
> Issues
When migrating, downloaded chapters does not migrate.
#8586

**Comment by pseudo-demon** [comment]
When you download chapters and cancel halfway, the chapters is still in Tachiyomi/downloads

**Comment by pseudo-demon** [comment]
When migrating, you delete the manga from library, right?

**Comment by pseudo-demon** [comment]
If you delete the source folder; Tachiyomi/downloads/name, it will risk deleting other chapters that are downloaded from the extension

**Comment by pseudo-demon** [comment]
[Empty folder](https://user-images.githubusercontent.com/118722936/203281923-38c6b93e-0aa0-4f70-8c00-b16d96beca5c.png)
