### ISSUE TITLE
Search in Anime-Planet

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8595]
### Describe your suggested feature

It should work like this...
When you click [Anime-Planet](https://anime-planet.com) below a manga name, will trigger search to Anime-Planet about detailed information in WebView mode. The user then can manually select the matching manga that you want.
* Add: Search manga info in Anime-Planet.
* "Show tag from Anime-Planet" that will gives you the detailed tag from anime-planet.
    * Click the tag: you will be sent to Anime-Planet searching for similar manga with the selected tag

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pseudo-demon** [comment]
This is not for watching anime

**Comment by pseudo-demon** [comment]
@AntsyLich @arkon

**Comment by loocool2** [comment]
Duplicate of #1785

**Comment by pseudo-demon** [comment]
This is not for tracking your reading history @loocool2

What's tracking?

**Comment by pseudo-demon** [comment]
This is because you can't change URLs in WebView mode.
