### ISSUE TITLE
Ability to change WebView URL

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8596]
### Describe your suggested feature

* Change URL in WebView in three vertical dots menu.
* Increasing user privacy when browsing in WebView?
* Add: view this manga in [mangaupdates](https://mangaupdates.com) or an1m3-plan3t in three vertical dots menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pseudo-demon** [comment]
#8595

**Comment by loocool2** [comment]
I don't see the point of being able to change the WebView URL, as you're not meant to use WebView to view content. 
Tachiyomi is not intended to be primarily used to view tracker entries either, trackers already can be searched with tracking and associated tracker entries to a manga can be opened in webview already as well.

**Comment by AntsyLich** [comment]
1. We hold no information of a series' mangaupdates or anime-planet page unless you are tracking the series on one of the tracking services. Tbn we don't support anime-planet tracking.
2. If you are tracking the series you can open the tracker sheet and click on it's icon to open the series page on your browser.
3. What loocool2 said

**Comment by pseudo-demon** [comment]
Just want to see "Title" recommendations and Manga tag is not detailed usually.

**Release that witch** (manhua)
| An1me-planet | 1st Kiss | mangabat | mcreader | 
| --- | --- | --- | --- |
| Action, Adventure, Drama, Fantasy, Harem, Manhua, Romance, Webtoons, Demons, Full Color, Guns, Isekai, Kingdom Building, Magic, Management, Medieval, Modern Knowledge, Nobility, Person in a Strange World, Political, Reincarnation, Religion, Royalty, Supernatural, War, Witches, Based on a Web Novel | Action, Adventure, Drama, Fantasy, Harem, Historical, Seinen, Supernatural | Action, Adventure, Drama, Fantasy, Harem, Historical, Seinen, Supernatural, Webtoons | Action, Adventure, Fantasy, Harem, Supernatural, Manhua |
| 27 tags | 8 tags | 9 tags | 6 tags |

**Comment by AntsyLich** [comment]
Point 1 and 2 still stands

**Comment by pseudo-demon** [comment]
This is what i want, @AntsyLich

By Overriding Base Url on ToonKor to https://anime-planet.com give exactly what changing WebView URL does.
![Override Base Url](https://user-images.githubusercontent.com/118722936/203308962-85f8b585-2057-43cb-a2bc-263ba36ebf9d.png)

**Comment by AntsyLich** [comment]
Just use your browser

**Comment by pseudo-demon** [comment]
LOL! it's working! 
![WebView URL change plz](https://user-images.githubusercontent.com/118722936/203310522-c6524bf5-ad97-479c-88e9-b93de21b9e5d.png)

**Comment by pseudo-demon** [comment]
Now it just need to use the manga title to search the manga in anime-planet! :smile:

**Comment by arkon** [comment]
WebView is not for browsing. Use an external browser if you want to look at arbitrary content.
