### ISSUE TITLE
Library entries are not changing categories and info

### ISSUE THREAD

**Issue by Dexroneum** [tachiyomiorg/tachiyomi#8600]
### Steps to reproduce

1 case - When you change category of entry, this entry stays in same category until you go another tab and return to the library.
2 case - When you read the chapter of entry by clicking to "Continue reading button" and return to the library, the entry are not updating counter of the read chapter.

### Expected behavior

The library entries should update dynamically whatever the case are

### Actual behavior

Cases explained on "Step to reproduce" happened

### Tachiyomi version

Tachiyomi Preview r5254

### Android version

Android 12

### Device

Xiaomi Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce.

**Comment by Dexroneum** [comment]
> Can't reproduce.

Sorry for misinformation, I didn't test it on main tachi. It was tested on Syer's fork and sometimes Syer fork breaks the code and logic of main tachi. I will close this issue now. @arkon
