### ISSUE TITLE
When you search comic, the counter of category tab are not updating

### ISSUE THREAD

**Issue by Dexroneum** [tachiyomiorg/tachiyomi#8601]
### Steps to reproduce

Same as title ones

### Expected behavior

Should descrees the counter when you search comic(manga, manhwa, etc...)

### Actual behavior

Same as title one

### Tachiyomi version

Tachiyomi Preview r5254

### Android version

Android 12

### Device

Xiaomi Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed in #8620
