### ISSUE TITLE
Open manga from web view in tachiyomi's source

### ISSUE THREAD

**Issue by Sleeping-Donut** [tachiyomiorg/tachiyomi#8607]
### Describe your suggested feature

When opening web view on an extension sites often have recommended / related titles.

Suggested feature is to have easier way of opening these links back into tachiyomi easier.

This could be getting the relevant id from the page and searching that extension for it. Alternatively by changing the currently existing way of brining that data back to tachiyomi, which is by sharing the url to tachiyomi's global search, so that it can parse the url and call the relevant search for that extension if available. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This feature needs to be implemented in the extension. So make separate feature request for each extension you are want this feature for in the extension repo
