### ISSUE TITLE
Downloaded but unread, chapter count

### ISSUE THREAD

**Issue by Tadza0641** [tachiyomiorg/tachiyomi#8610]
### Describe your suggested feature

In library page:
I want to keep all chapters downloaded, but I want to see how many unread chapters i have currently downloaded. Currently there are only 2 numbers: number of chapters downloaded and number of chapters unread. Also knowing how many chapters are there completely would be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No plans to make the library even more complicated than it already is.

You can see this number in the individual manga details screens by filtering there.
