### ISSUE TITLE
Parallel chapter download

### ISSUE THREAD

**Issue by piyush2406** [tachiyomiorg/tachiyomi#8612]
### Describe your suggested feature

Hi, amazing app.. Just wanted to check if it would be possible to allow parallel downloading of chapters? Like 2 or 3 chapter parallelly so that IP wont get blocked? Thanks!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

the answer was no.
