### ISSUE TITLE
Refresh button chapter list page

### ISSUE THREAD

**Issue by eyao06** [tachiyomiorg/tachiyomi#8614]
### Describe your suggested feature

Where this feature is located
1. Selecting a manga
2. Now you are in the page with the summary and list of chapter

New feature functionality
> Have a refresh button
> When pressed, refresh the chapter list (gets the most up to date chapters)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Pulling down on the chapter list does the same thing.
