### ISSUE TITLE
Error when building: Could not find com.github.zellius:android-shortcut-gradle-plugin:0.1.2.

### ISSUE THREAD

**Issue by alvindizon** [tachiyomiorg/tachiyomi#8615]
### Steps to reproduce

1. Clone repo
2. Try to build in Android Studio
3. Build fails with the following error:
```
A problem occurred configuring root project 'Tachiyomi'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.zellius:android-shortcut-gradle-plugin:0.1.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
       - https://dl.google.com/dl/android/maven2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Expected behavior

1. Project should be built successfully

### Actual behavior

1. Project is not built successfully

### Crash logs

```
A problem occurred configuring root project 'Tachiyomi'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.zellius:android-shortcut-gradle-plugin:0.1.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
       - https://dl.google.com/dl/android/maven2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/zellius/android-shortcut-gradle-plugin/0.1.2/android-shortcut-gradle-plugin-0.1.2.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Tachiyomi version

0.14.2

### Android version

Can't run on device as build did not succeed in the first place

### Device

Can't run on device as build did not succeed in the first place

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://status.jitpack.io/785474622
