### ISSUE TITLE
Button for Clear Updates

### ISSUE THREAD

**Issue by shivamdevs** [tachiyomiorg/tachiyomi#8621]
### Describe your suggested feature

Not much just add a clear updates button in the Updates section to remove updates history.

Also sometimes when scrolled down at much faster speed in the Updates section the App crashes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3365
