### ISSUE TITLE
Eternal loading in library and crashes

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8625]
### Steps to reproduce

1. Launch Tachiyomi
2. Wait and observe library
..

https://user-images.githubusercontent.com/101556532/204111895-d178cc49-e639-483e-876b-dc63f15a9db0.mp4

### Expected behavior

Categories should show

### Actual behavior

Stuck in loading and when pressing library filter it crashes.

### Tachiyomi version

Preview r5281

### Android version

Android 11

### Device

Samsung Galaxy J6 

### Other details

Done repopulate using backup and invalidating download index also still wont show.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by matheuswr89** [comment]
Same problem here

**Comment by ViktorVoloshko** [comment]
Happens to me too after update to latest preview.
POCO M3, Android 12.1, Pixel Experience, Magisk 25.2, GApps present.
Also app loading time significantly longer than before.
