### ISSUE TITLE
Access manga page from history tab

### ISSUE THREAD

**Issue by MacGregor129** [tachiyomiorg/tachiyomi#8634]
### Describe your suggested feature

For example as long press option 

### Other details

It's very annoying that after reading something, be it saved in library or just by browsing expansions. You can't easily get back to main"page" of that title. To add it to library, modify downloads, whatever.

History tab seems like best place for this as it's shows recent titles anyway. But afik only use it has is opening next chapter or help with copying title into search bar... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Tap on the cover in history screen
