### ISSUE TITLE
[FR] improving The Downloading process in (Weak internet situations)

### ISSUE THREAD

**Issue by Qwerty0uiop** [tachiyomiorg/tachiyomi#8646]
### Describe your suggested feature

In the normal Situation with Strong and Good internet The Downloading process is very Good, but can we make the Download process during Weak internet situations (Internet is there but weak) much better and increase its stability.

Is there any feature that make the Downloading process of manga Chapters more Coherent and Smoothly especially In Weak internet situations. 

And Can we add to the Downloading process as a whole : The percentage of the Downloading process. As (25 %) 
to make it more Stable in weak internet conditions.

Next to (the pages of chapter needed to be download as (3 / 12) + Download Bar) which is already there.

In weak internet situations when we download a manga chapter from 12 pages as example, the download process after moving to some distance and making some progress it turns backward once again and sometimes it freezes the whole process and stop the download process.

And can we make the Downloading process if stopped or canceled for any reason to be start to complete its progress with what is left over and Not to Start from the beginning.

### Other details

I knew you made some changes to the Downloading process recently by categorize the resources as a whole and separate it from each other, So the First one from each resource start its downloading process first.
That is also very Good

However in weak internet situations sometimes when we select more than one chapter to download and they moved to the Downloading Cell, the first chapter after some progress in its downloading process freezes and its moved to start the Next chapter without finishing the first one. And the 2 to 3, ..... etc,

Can we make additional Download List (Priority Chapters) in The Downloading Cell where we can select the Most Priority chapters to be Downloaded from what we selected to be downloaded from the original download cell.

So with that the Downloading process will focus much more on the high priority desired to be downloaded first without moving to another less priority.

Or if it'll be difficult Can we at least make the Downloading process more stable in weak internet situations so that it didn't freeze and not move to another chapter except after finishing the chapters before it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Make separate feature requests since you're clearly asking for more than a single thing

**Comment by Qwerty0uiop** [comment]
They are connected and There are only 2 things here,

1 - the Percentage of The Downloading process, and improving the stability of it in weak internet situations.

2 - make additional Download list in the Downloading Cell for the high Priority Chapters to be Downloaded. (Priority Chapters).
To make it easier for the Chapters to be downloaded by its order and not moving to the next until the first ones finish.

It will be good if only one of them is made, if both it will be nice.

**Comment by arkon** [comment]
1. No. We can't magically fix Internet issues unique to different users.
2. Also no. There's nearly no merit to limiting concurrency to downloading from only 1 source at a time. If your Internet is truly bad enough that it can't handle fetching data from 2 things at once (which your phone is most certainly doing a lot more at any given time), then you'll have to manually manage your download queue. It's not worth implementing that.

**Comment by Qwerty0uiop** [comment]
> 1. No. We can't magically fix Internet issues unique to different users.
> 2. Also no. There's nearly no merit to limiting concurrency to downloading from only 1 source at a time. If your Internet is truly bad enough that it can't handle fetching data from 2 things at once (which your phone is most certainly doing a lot more at any given time), then you'll have to manually manage your download queue. It's not worth implementing that.

About Problem 1, In general i talked about if there any solution to the problem of the Downloading process freezes and turn backwards after making some progress in its downloading and go some distance in the Downloading bar and it sometimes start over from the biginning. In weak internet situations.

About Problem 2, you have a misunderstanding of what i said, i have no problem of downloading from 2 Source at the same time, on the contrary i think it's a very good way and good feature.

What i have problem with is, as example if you try to download say 4 chapters from 2 different sources, each source has 2 chapter to download. So the first one on each one of them will start to download at the same time, that is good

Sometimes in weak internet situations the first chapter in resource 1 freezes and turn backwards and sometimes stopped and moved to download the Second Chapter in resource 1 without finishing what it started with the first chapter.

And that may happen too in the same way in resource 2.

What i'am talking about here, a solution to make the Downloading process to stick to the Sort/Order of the chapters we placed so the first chapter be the priority to download first and not to move the next until it finishes.

I know in the normal good internet, all that is already happening. But in weak internet situations the matter is different. (internet is there but weak, sometimes whole chapters are downloaded but took more time and sometimes the chapters freeze without completing its downloading although there was internet)

What i'am talking about here improving the Downloading process and makevit stable to download chapters even in weak internet conditions, even if the Downloading process takes all the time it needs to complete the download in Weak internet situations.
