### ISSUE TITLE
Mangasusu: no pages found 

### ISSUE THREAD

**Issue by lossdol567** [tachiyomiorg/tachiyomi#8647]
### Steps to reproduce

1.Open MangaSusu
2.Open The Manhwa
3.Open The Chapter
4.No Pages error comes up

### Expected behavior

The extension should show up the chapter images.

### Actual behavior

![Screenshot_2022-11-25-22-56-23-668_eu kanade tachiyomi](https://user-images.githubusercontent.com/116056943/204647323-971aed77-6484-45aa-bd54-0d29ce331694.jpg)

### Crash logs

--------- beginning of main
11-30 04:01:01.049 17681 17767 E SQLiteLog: (284) automatic index on C(manga_id)
11-30 04:01:01.049 17681 17767 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-30 04:01:01.407 17681 17719 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
11-30 04:01:01.407 17681 17719 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: POCO
Device manufacturer: Xiaomi
Device name: chopin
Device model: 21061110AG
Device product name: chopin_id

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

POCO X3 GT

### Other details

Mangasusu 1.3.22(Indonesia) no pages found 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
