### ISSUE TITLE
Uninstalling extension makes the app go to source tab

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8653]
### Steps to reproduce

Go to browse > extensions > [extension name] settings
Uninstall it from the button 

### Expected behavior

After uninstalling, the app should go back to the extensions tab

### Actual behavior

App goes to the sources tab

### Tachiyomi version

r5284

### Android version

Android 12 

### Device

Tecno spark 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce.

**Comment by mobi2002** [comment]
No longer happens in r5311 👍
