### ISSUE TITLE
Fullscreen cover doesn't have solid background in status bar

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8654]
### Steps to reproduce

Open a manga
Tap the cover to view it in full screen

### Expected behavior

The cover is fillscreen with solid background in status bar etc

### Actual behavior

The background accent in the status bar and navigation bar is from previous screen

![Screenshot](https://user-images.githubusercontent.com/48650614/205220659-5c56483a-096a-4358-a62e-9a0b832ae3dc.png)

### Tachiyomi version

r5284

### Android version

Android 12 

### Device

Tecno spark 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://issuetracker.google.com/issues/246909281
