### ISSUE TITLE
Google Sign-in Problem in Webview

### ISSUE THREAD

**Issue by sinnghabhay80** [tachiyomiorg/tachiyomi#8662]
### Steps to reproduce

Open tappytoon extension web view
Press login
Press login with google

### Expected behavior

It should open a Google account page to choose account to log in etc 

### Actual behavior

Does nothing

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Realme X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by alessandrojean** [comment]
Also Google intentionally blocks sign in through their accounts in WebView to avoid some known security attacks. Use a simple email and password account instead.

**Comment by sinnghabhay80** [comment]
> >  If this is an issue with an extension, I should be opening an issue in the extensions repository.

It was not related to particular extension, that was just a way to reproduce the problem.
   You can try that in other extension as well that require Google sign in.

**Comment by sinnghabhay80** [comment]
> Also Google intentionally blocks sign in through their accounts in WebView to avoid some known security attacks. Use a simple email and password account instead.

Ohhh, but my account is created via Google sign in so I can't use simple email and password method to access my purchased content.

If there's any work around.do tell me. Thank You

**Comment by mystic-man-rhino** [comment]
Try login with email click forgot password enter your email reset password with this you can login with email password.

**Comment by sinnghabhay80** [comment]
> Try login with email click forgot password enter your email reset password with this you can login with email password. 

Tried it before posting the issue, it creates a new account with the same email.
![Screenshot_2022-12-04-20-05-20-77_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/55084281/205496772-74d434ad-a0e9-4584-bc30-684f33f291e1.jpg)
