### ISSUE TITLE
[Crash log from r5311] crash when i click on "restore backup"

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8667]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/205470859-474da885-2079-4fc0-bd94-625dadc410a1.mp4

 i am not sure but i disabled the main file manager og my huawei p8 lite 2017 with adb
i replaced it with Amaze file manager(open source on github)
then i clicked on restore backup

### Expected behavior

no crash

### Actual behavior

crash

### Crash logs

[text.txt](https://github.com/tachiyomiorg/tachiyomi/files/10147739/text.txt)

### Tachiyomi version

r5311

### Android version

android 8 miui 8

### Device

huawei p8 lite 2017

### Other details

i guess this happenee because i disactivated some apps with adb, between them there is the default file manager of my huawei replaced by amaze file manager (github, so open source).
The thing is that i can open my archive on the download section when i choose the download path; the app doesn't crash there. I also didn't encounter problems with other apps regardihg the access to the storage. maybe it happens due to somethings else, let me know pls

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I found the app responsable: com.huawei.android.internal.app
i enabled it again and tachi doesn't crash anymore. what does it have to do with huawei share when the app just needs to get a file in the storage

**Comment by arkon** [comment]
We're not going to provide workarounds for people fiddling with their system in unexpected ways. If Huawei requires that system app to handle standardized intent choosers, then so be it. ¯\\\_(ツ)_/¯

**Comment by Palloxin** [comment]
at least make an error message appear saying what is the problem

**Comment by arkon** [comment]
I'd only consider doing so if it happens on unmodified stock experiences.

**Comment by Palloxin** [comment]
my device is not rooted, i used adb to disactivate it. If it is still not then nvm
