### ISSUE TITLE
Tracker entry is same for every manga

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8668]
### Steps to reproduce

Cold start the app
Open a manga
Open it's tracking sheet

Go back
Open any other manga
Open it's tracking sheet 

### Expected behavior

The tracking entry for each manga should be it's own

### Actual behavior

Tracking entry is same on every single manga, even on untracked ones. (It is from the first manga opened)
![Screenshot](https://user-images.githubusercontent.com/48650614/205472339-276b9acc-7fbe-4cb8-83c2-1e18e5e6b519.png)

### Tachiyomi version

r5311

### Android version

Android 12 

### Device

Tecno spark 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment]
I have the dame problem. This happened with the last update.
