### ISSUE TITLE
Ozul scans

### ISSUE THREAD

**Issue by uwKILLER** [tachiyomiorg/tachiyomi#8669]
### Steps to reproduce

![Screenshot_20221203_124638_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/107407548/205475708-4e6fa3e4-163b-44f5-bbc3-b792b73e755d.jpg)

### Expected behavior

Chapter loading

### Actual behavior

 image couldn't be loaded 

### Tachiyomi version

1.8.5

### Android version

10

### Device

Huawei nova 7 5G 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
