### ISSUE TITLE
6.0.1 INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2

### ISSUE THREAD

**Issue by raingart** [tachiyomiorg/tachiyomi#8671]
### Steps to reproduce

I have a tablet 6.0.1

All versions after 0.10.2 are not installed

`INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2`

### Expected behavior

0.10.2 Runs but extensions don't work
Subsequent ones are not installed.

### Actual behavior

Installation error

### Tachiyomi version

=> 0.10.3 

### Android version

Android  6.0.1

### Device

TREKSTOR SurfTab Breeze 9.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raingart** [comment]
google suggested that the problem is
- - improved zipalign, fixed installation of applications with "extractNativeLibs="false"" attribute in manifest ("INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2");

I understand that I am an exception with an outdated tablet. If there is no possibility or a conflict with the current compression method.

Then it will be enough for me to compile a personal version. Unfortunately I'm too dumb to do it myself

**Comment by AntsyLich** [comment]
Can you try installing the largest apk (65mb one) from https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.2

**Comment by raingart** [comment]
same error

**Comment by AntsyLich** [comment]
Perhaps you can join the discord server https://discord.com/invite/tachiyomi. And ping me there

**Comment by arkon** [comment]
Nothing really notable changed between 0.10.2 and 0.10.3 with regards to native libraries, so I'm not entirely sure what the issue is here.
