### ISSUE TITLE
Mangasee - stream was reset: INTERNAL ERROR"

### ISSUE THREAD

**Issue by Kilikx2** [tachiyomiorg/tachiyomi#8672]
### Steps to reproduce

1. Open Tachiyomi
2. Open Mangasee "browse" view OR "latest" view
3. Page load indefinitely
4. Show error message "stream was reset: INTERNAL ERROR"

### Expected behavior

![Screenshot_20221204-200719](https://user-images.githubusercontent.com/109612777/205489565-bb5a88d8-3b63-46b7-aa99-b4c8d7619e04.png)

### Actual behavior

![Screenshot_20221204-200257](https://user-images.githubusercontent.com/109612777/205489516-f080db9b-2f15-459e-aa8c-3af9db69350d.png)

### Tachiyomi version

0.14.2 

### Android version

Android 12

### Device

Motorola Moto G82 5G

### Other details

The site can be opened on webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
