### ISSUE TITLE
Sources doesn't show my extensions and when I try to migrate, it just shows a blank screen 

### ISSUE THREAD

**Issue by theGamerGunvir** [tachiyomiorg/tachiyomi#8677]
### Steps to reproduce

I am not 100% sure if these are the steps 
1. Open isekaiscan.com in webview
2. Go to migrate and isekaiscan.com
3. Try to migrate anything
4. It shows results from other extensions
5. Try to migrate again
6. Blank screen 

### Expected behavior

For sources "Should show my extensions"
For Migrate "Should be able to see results from other extensions when migrating"

### Actual behavior

https://user-images.githubusercontent.com/119141992/205542004-2dad973a-9f7a-46ee-87da-f24897a595f6.mp4

### Tachiyomi version

App version: 0.14.2 

### Android version

Android 11

### Device

OnePlus 7 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I assume you disabled all of the relevant language groups. If you need more help, please join the Discord server.
