### ISSUE TITLE
Dynamic Categories

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#8678]
### Describe your suggested feature

Hello, I would like to suggest a feature wherein user can create dynamic categories based on a set of rules.

**Ruleset**
---
- By unread count
- By genre
- By status
- By source

**Use Case**
---
- **Scenario 1:** A category wherein it will contain the following.
  - Unread Chapters `≤` 3

- **Scenario 2:** A category wherein it will contain the following.
  - Unread Chapters `≤` 3
  - Source `=` Asura Scans

- **Scenario 3:** A category wherein it will contain the following.
  - Unread Chapters `≤` 3
  - Source `=` Asura Scans
  - Genre `=` Action `AND` Fantasy

**Why**
---
I had always had a challenge manually managing all series I caught up reading the latest available chapter since I prefer reading at least 3 or more chapters instead of reading one by one.

With a dynamic category, users like me can put all the up-to-date series in a single category like `Up-To-Date` and during a library update, the app will automatically sort the series to a category named like `Ready to Read` if the ruleset matches.

Then once a series doesn't match the ruleset anymore. The category `Ready to Read` will be removed so that it will wait for that series again to have more chapters before re-adding the `Ready to Read` category once more.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#775
