### ISSUE TITLE
Website manga extensions 

### ISSUE THREAD

**Issue by TheGoldenSun** [tachiyomiorg/tachiyomi#8686]
### Steps to reproduce

1. It doesn't load when tapping on the word "latest"
2. The word popular only loads when I tap out of the popular column.
3. Popular column wouldn't load properly since tapping "latest" 

### Expected behavior

I've tried changing my DNS and VPN connection, nothing worked except knowing that my wi-fi router is still functioning lively. 

### Actual behavior

When I tested all manga extensions by turning off my DNS and VPN connection to see if every manga extension would load when tapping on "latest" nothing would load any manga stories especially on the popular column if I stay in the popular section too long it would continue to load afterwards.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Galaxy A02s

### Other details

![Screenshot_20221205_051047](https://user-images.githubusercontent.com/104534608/205791723-a097993e-b54e-4ac5-b997-9609eb6c8ddf.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheGoldenSun** [comment]
[Bug video one](https://platform.kik.com/content/files/2a2019d1-a458-47f3-a3d6-57d51a1e9ca1?k=7db4554502a43870f261790407241090c32ecf8f     ) 

[Bug video two ](Https://platform.kik.com/content/files/c0ca8f98-f12e-492b-ae8d-d9e3a20db4d7?k=00f3405795422bb801db5dd6ab95c5158e9049c4) 

@curche If screenshot isn't enough I hope recording was proof of the glitch.

**Comment by TheGoldenSun** [comment]
I've switched to using Aniyomi since the issue is closed, my apologies that
we couldn't come to an understanding as the proof that I provided shows the
dedication that the bug actually exists, from now on I'm going to be using
Aniyomi and not Tachiyomi anymore, good day.

**Comment by curche** [comment]
I'm finding it hard to understand what you're trying to tell.
Like here:
> with Tachiyomi's DNS built-in feature in the app it works fine

Please join the Discord and we can help you better in #support channel
GitHub doesn't really make it easy to have a quick conversation 
Which is why we closed the issue, hoping you would come to our Discord

> the issue is all manga extensions are not loading properly due to when I tap onto the word "latest" and popular column afterwards
I'll look into it more and create a new issue if I can reproduce this

Anyways, locking the issue again
