### ISSUE TITLE
Double "Back" when clicking on tracker

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi#8688]
### Steps to reproduce

1. Open title
2. Tap on tracker
3. Tap on button back
4. Again tap on button back

### Expected behavior

Back up normally. 
**(As shown in video 1)**

### Actual behavior

When opening any title at the time of clicking on the tracker (Any), you have to do a double backspace to return.
**(As shown in video 2)**

### Tachiyomi version

0.14.2 Preview r5323

### Android version

Android 11

### Device

Redmi Note 11S

### Other details

**Video 1:** Used from a previous version

https://user-images.githubusercontent.com/70596255/205921324-b79ad8d0-c185-4b49-a079-8aa78dae7d8e.mp4

**Video 2:** Used of the latest version

https://user-images.githubusercontent.com/70596255/205921175-baa7bcfc-2360-4183-91f7-a33032c21ab4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by whghjyh** [comment]
I also encountered this problem.But I have found that this phenomenon doe not occur as long as there is an interval between two 'back'.
