### ISSUE TITLE
Feature that allows you to translate comics into your own language

### ISSUE THREAD

**Issue by velteyn** [tachiyomiorg/tachiyomi#8692]
### Describe your suggested feature

There are many api online with the ability to tralsate comics
(for example : `https://www.imagetranslate.com/apis`)
So my suggestion is to add the ability for users subscribed to such api services to have local downloaded comics be tranlsated.
There are many japanese comics that will never be tranlsated in english and this is a pity.

Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
similar to #3383, don't think the app will ever hook into an api. your best bet is to just run it through the api yourself.
