### ISSUE TITLE
MAL tracking HTTP error 401

### ISSUE THREAD

**Issue by SongMujin** [tachiyomiorg/tachiyomi#8697]
### Steps to reproduce

1 add tracking 
2 add via MAL
3 gets HTTP error 401
4 unable to track manga

### Expected behavior

Ability to track my manga with MAL. After reading a new chapter, it automatically updates which chapter I'm at in MAL.

### Actual behavior

I should be able to track my manga with MAL. But it has stopped tracking anything I have read with the MAL tracking. This happend not long after the last update. 

### Tachiyomi version

App version: 0.14.2 

### Android version

Android version: 11 (SDK 30) 

### Device

Device name: OnePlus6T Device model: ONEPLUS A6013 

### Other details

![Screenshot_20221207-214710](https://user-images.githubusercontent.com/120058641/206292252-558219c6-922c-4e2d-8ae2-f062634bbb41.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Sign out and sign in again through settings.
