### ISSUE TITLE
no result found

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi#8699]
### Steps to reproduce

1. cant open the from tachiyomi but in webview it can be open

### Expected behavior

can show some of manga

### Actual behavior

1. cant open the from tachiyomi but in webview it can be open
2. no result found

![Uploading asdfasdfasdfasdfasdfasdfas.png…]()

### Crash logs

--------- beginning of main
12-08 11:57:55.389  7813 12022 E Surface : freeAllBuffers: 17 buffers were freed while being dequeued!
12-08 11:59:01.497  7813 29214 E chromium: [ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -200
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N970FXXS8HVJ1
Device brand: samsung
Device manufacturer: samsung
Device name: d1
Device model: SM-N970F
Device product name: d1xx

### Tachiyomi version

0.14.2

### Android version

android 11

### Device

samsung galaxy note 10

### Other details

https://raw.senmanga.com/ 

i can open it on web view. but not in apps

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
> - [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

You in wrong repository
