### ISSUE TITLE
Crash with random entry button 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8700]
### Steps to reproduce

Open library
Tap the random entry button in overflow menu

### Expected behavior

Should open one of the manga entry 

### Actual behavior

Crashes 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10185899/tachiyomi_crash_logs.txt)

### Tachiyomi version

r5323

### Android version

Android 12 

### Device

Tecno spark 6 

### Other details

It doesn't happens on all categories.

Happens with or without filters 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```

12-08 18:39:14.590  8843  8843 E ACRA    : java.util.NoSuchElementException: No element of the map was transformed to a non-null value.
12-08 18:39:14.590  8843  8843 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryScreenModel$State.getLibraryItemsByCategoryId(LibraryScreenModel.kt:60)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryScreenModel$getRandomLibraryItemForCurrentCategory$2.invokeSuspend(LibraryScreenModel.kt:23)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-08 18:39:14.590  8843  8843 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
```
