### ISSUE TITLE
Migrate dialog layout misaligned in android 13

### ISSUE THREAD

**Issue by shabbyplace** [tachiyomiorg/tachiyomi#8701]
### Steps to reproduce

After updating my Oneplus 8T from android 11 to android 13 the migrate dialog layout is now misaligned.

### Expected behavior

Dialog in android 11:

![Screenshot_20221208-172316](https://user-images.githubusercontent.com/17619547/206507639-c6e544e0-4824-4882-9770-54bf12209c3f.jpg)

### Actual behavior

Dialog in android 13:
![Screenshot_2022-12-08-17-23-14-67_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/17619547/206507223-0299b81c-092f-4238-92d6-9e05abdbda5c.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Oneplus 8T

### Other details

I'm not sure if this also occurs in Android 12. I skipped this android version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Fixed in https://github.com/tachiyomiorg/tachiyomi/pull/8631
