### ISSUE TITLE
Volume Scroll to have option to be like a slow drag or auto scroll 

### ISSUE THREAD

**Issue by Nafislord** [tachiyomiorg/tachiyomi#8703]
### Describe your suggested feature

The option to scroll with volume buttons currently jumps from one section to another but instead can it be done that while you hold the volume down button the manwa will scroll as if scrolling with hand smoothly. Its anoying for to be jumping around with manwha i understand with single page manga but there should be an option to scroll slow or fast or it could be the longer you hold the volume down the faster it gets. Or even better a slow auto scroll would be awesome where you can control the speed via volume rocker's.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#2093

**Comment by Nafislord** [comment]
> #2093

I saw it but it's not really the same honestly is quite different, i did mention auto scroll but my primary feature is scroll with volume rocker's at a certain speed.
