### ISSUE TITLE
Crashes phone(android 7.0)

### ISSUE THREAD

**Issue by Cisco-A** [tachiyomiorg/tachiyomi#8704]
### Steps to reproduce

1. Open the app with internet connection
2. Attempt to pass the fingerprint authentication
3. Phone shuts down without warning 

### Expected behavior

The app should open without shutting my phone down or crashing the app.

### Actual behavior

As soon as I open the app with internet connection, my phone turns off. Also, if I'm reading downloaded contents the app crashes except I'm reading online.

### Tachiyomi version

0.14.2

### Android version

Android 7.0

### Device

Samsung Galaxy S6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by M9k** [comment]
I tried with my tablet (Teclast, Android 11) but it works fine.
I think logcats or crash logs will be useful to find the problem.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by Cisco-A** [comment]
@arkon These are the crash logs:

--------- beginning of main
12-09 09:36:16.972 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101056c
12-09 09:36:16.978 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:36:16.978 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:36:16.978 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:36:16.978 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:36:17.125 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:36:17.125 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:36:17.125 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:36:17.125 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:36:18.460 29774 29844 E SQLiteLog: (284) automatic index on C(manga_id)
12-09 09:36:18.460 29774 29844 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-09 09:36:19.806 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:36:19.806 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:36:19.806 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:36:19.806 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:36:19.895 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:36:19.895 29774 29774 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:36:19.895 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:36:19.895 29774 29774 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:36:22.136 29774 29774 E ViewRootImpl: sendUserActionEvent() mView == null
12-09 09:36:24.086 29774 29774 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
12-09 09:39:28.774 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101056c
12-09 09:39:28.777 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:39:28.777 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:39:28.777 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:39:28.777 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:39:28.920 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:39:28.920 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:39:28.920 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:39:28.920 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:39:30.209 32639   318 E SQLiteLog: (284) automatic index on C(manga_id)
12-09 09:39:30.209 32639   318 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-09 09:39:31.243 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:39:31.243 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:39:31.243 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:39:31.243 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:39:31.285 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101056d
12-09 09:39:31.285 32639 32639 E ResourceType: Style contains key with bad entry: 0x0101058c
12-09 09:39:31.285 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010604
12-09 09:39:31.285 32639 32639 E ResourceType: Style contains key with bad entry: 0x01010605
12-09 09:39:33.003 32639 32639 E ViewRootImpl: sendUserActionEvent() mView == null
12-09 09:39:34.166 32639 32639 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 7.0 (SDK 24)
Android build ID: NRD90M.G920VVRU4DRE1
Device brand: Verizon
Device manufacturer: samsung
Device name: zerofltevzw
Device model: SM-G920V
Device product name: zerofltevzw

**Comment by arkon** [comment]
Is that after a crash? I don't see anything particularly interesting.
