### ISSUE TITLE
Security and Ads

### ISSUE THREAD

**Issue by shadowless16** [tachiyomiorg/tachiyomi#8705]
### Describe your suggested feature

Hello 
I have 2 thing ma to suggest firstly it think it better if the security passcode for the app is independent from the password of the phone
Secondly
It about that browers of the extension we use when I open the manga in WebView every little thing i don't ads keeps on popping up and the pages keeps in redirecting me to other ads webpages so i think it would be better if there was an extension for the web browser cuz sometimes when i read a Manga and want to comment on discord the ads from the website won't let me do it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. No, this is the standard Android behaviour that we use.
2. Use a browser with ad block if you want to actually browse the websites. WebView is there to help the app actually load content, not for actually browsing around.
