### ISSUE TITLE
Local tracking database

### ISSUE THREAD

**Issue by Onxr** [tachiyomiorg/tachiyomi#8712]
### Describe your suggested feature

There are multiple tracking services in Tachiyomi . But most of the time for unpopular titles there is no data in the trackers so we can't track those . Specially comics from **webtoons and doujinshi or any western comics** .

So we can have a local tracker which will track like others . It will have data of starting , finishing date , including chapters and reading status  . I found tachiyomi will have statistics in upcoming updates so it will be a useful feature with that .
You may suggest submitting data in the trackers but some times some rules won't let you submit or other times it takes time for their approval .

### Other details

**The local db can be linked with the other online trackers** . As you may already know nhentai and some other extensions _add more stuffs with the title_ , **we have to remove those manually while adding trackers**  . So it can be done like this , we can edit the title in local tracking db . Every individual  manga / manhwa / manhua... entry has tracking option but that will be linked to local db and local db will be linked to other online trackers .

**Also we wanted device sync for a long time** . We can have this using this feature . Suppose I read chapter 1-17 of "ABC" from x extension then I added "ABC" again from y extension and added local tracking . As it was already tracked to 1st 17 chapters locally , when we added from y extension the first 17 chapters will be marked read **(but not other stuffs example : notice )** . As the local db is connected to online trackers those will be updated and the other device will sync their online trackers with the local tracking db , that's how we can have device sync this way . One more thing let local tracking DB be backed up separately but also with the main backup system .

Finally what I wanted to say is that , I don't know anything about coding . What I wrote is easy for me to write but could be hard to implant . So it's totally upto you guys .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Refer to https://github.com/tachiyomiorg/tachiyomi/issues/6553#issuecomment-1250333649
