### ISSUE TITLE
Scrolling past last pages of webtoon causes reader to snap to next chapter. Disables going back to prev chapter

### ISSUE THREAD

**Issue by Disposablegloves** [tachiyomiorg/tachiyomi#8715]
### Steps to reproduce

1. Sample manga (vid sample recorded in transition between ch31-32): https://mangadex.org/title/707a112b-55cb-41a5-afe1-601d3e52e9a8/return-of-the-legendary-spear-knight
2. Webtoon reader mode.
3. Scroll to next chapter

Vid: https://streamable.com/1x0jqd

Only happens when last pages of webtoon is tiny in comparison to the usual webtoon page. Doesn't happen if split pages is on.

Split pages on: https://streamable.com/zrqaic

### Expected behavior

Reader transitions smoothly to next chapter and allows reader to scroll back to previous chapter

### Actual behavior

Reader locks on to last loaded image in chapter. Allows reader to conitnue reading but disables scrolling back up to previous pages of the last chapter.

### Tachiyomi version

0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)

### Android version

Android version: 12 (SDK 31)

### Device

Xiaomi Mi 10t Pro (M2007J3SG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3749
