### ISSUE TITLE
Unable to pull to refresh category if it has 0 visible entries

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#8720]
### Steps to reproduce

1. Scroll down to update a category with manga in it, but 0 shown with filters

### Expected behavior

Normal update should start

### Actual behavior

It doesnt update, need to remove filters and have at least 1 chapter visible

### Tachiyomi version

Preview r5348

### Android version

Android 12

### Device

Samsung Galaxy S10

### Other details

https://streamable.com/pucer0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Nachtalb** [comment]
https://user-images.githubusercontent.com/9467802/206912502-471787cd-9b5e-4b5a-9934-a44fb8094adf.mp4
