### ISSUE TITLE
Download (n) chapters ahead of read during update

### ISSUE THREAD

**Issue by TheEndHunter** [tachiyomiorg/tachiyomi#8725]
### Describe your suggested feature

As the title suggests add a feature to the app to only allow downloading of a set number of unread chapters from  a manga, if available when the update is triggered.  As the chapters are read, if available and there are no other restrictions (such as no network or restricted data) then it will start downloading the next available chapter in the background always keeping (n) ahead of where you are currently read up to. This will save a lot of space on devices with limited storage while also limiting the amount of requests made to sources down to only those that are required.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
There is already an option in downloads for doing this while reading. Which would be more optimal in space saving then during update.
