### ISSUE TITLE
Icon for issues with a manga

### ISSUE THREAD

**Issue by TheEndHunter** [tachiyomiorg/tachiyomi#8726]
### Describe your suggested feature

Add a set of icons that can be displayed on a manga cover when there are issues or errors when updating a manga. These icons would reflect the status of the last update preformed on that manga can can be reset by updating the manga. No errors or warnings would result in no icon being displayed.

Also allow filtering by errors/warnings in the library to allow for quick remedy when there are issues.

Here are some examples;
A ⚠️ where it would signify a need to refresh the URL.
A 🚫 could signify that the manga is no longer available on the source and needs to be migrated to an alternative.
A ⏳for the ones that are timing out.
A ⏩ for the skipped ones.
A ❗for other errors.

These icons would be placed before the downloaded chapter and unread chapter counts in the manga's cover icon with options to turn them off if needed.

These icons could also be shown in the updates tab to reflect Individual chapter issues and skips. 

I think this would improve the app when errors occur because at the moment the only ways to know something went wrong are the notification bar status and doing updates on individual manga, and to be honest there have been very few times I have even bothered to look at the status and just left it to do its job come back and just cleared my notification, at least with this the manga's would reflect the issues they have had during the last update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #8623

Closing in favour of #4616
