### ISSUE TITLE
Updates does not reflect true state after being indexed

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8727]
### Steps to reproduce

1. Launch Tachiyomi
2. Go to updates while indexing
..

https://user-images.githubusercontent.com/101556532/207041975-0221c9fa-b75f-4a3d-8b42-6cefeb7d0b4b.mp4

### Expected behavior

Entries being downloaded should be in 'checked' state because it exist.

### Actual behavior

It does not put in 'checked' mark.

### Tachiyomi version

r5348

### Android version

Android 11

### Device

Samsung Galaxy J6

### Other details

I understood if its because of being indexed that it needs arranging entries first but i felt the logic is broken. I think updates tab should not show while being indexed or contents should be unclickable to avoid confusion. Or simply put auto refresh after being indexed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I don't understand this report.

The entire point of indexing is to check the download statuses of the files. It can't show the correct download statuses until that's done.
