### ISSUE TITLE
Cant delete chapters removed in source

### ISSUE THREAD

**Issue by hortiSquash** [tachiyomiorg/tachiyomi#8730]
### Steps to reproduce

Download chapter
Source removes the chapter for some reason (new raws, new translation, redraw...?)
Cant read nor delete this chapter

### Expected behavior

Automatically delete chapters the source removed
or have them accessible so you can read and delete

### Actual behavior

There is the tick showing you have a downloaded chapter, but when scrolling you cant find it

### Tachiyomi version

0.14.2

### Android version

10

### Device

Mi A2 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#2108
