### ISSUE TITLE
Dont refresh until x days 

### ISSUE THREAD

**Issue by mickae1** [tachiyomiorg/tachiyomi#8731]
### Describe your suggested feature

Normaly a manwha is updated weekly.
Maybe we can add an option to update a manwha/manga after x days from the last release.

This should stress less the source website. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
This will be addressed by
- #5734

and similar issues are
- #5885
- #7796

I guess we can close #7796 and this one, and use #5885 to track #5734.

**Comment by mickae1** [comment]
Thanks
