### ISSUE TITLE
Combine wide images

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#8734]
### Describe your suggested feature

A button which combines current and next page.
For example the page numbers are 15, 16, 17, 18 and by tapping the button it should become like 15, 16(17+16), 18.

### Other details

This helps in seeing the wide images chronologically.
Like in [this](https://mangareader.to/read/the-worlds-strongest-butler-60932/en/chapter-8) manga, page 19 and 20 should be one single image but due to some reason it isn't.

Think of it as a opposite of *split wide images* setting (combine wide images)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
essentially #149
