### ISSUE TITLE
Constant freezing while reading

### ISSUE THREAD

**Issue by Foxygamer0110** [tachiyomiorg/tachiyomi#8735]
### Steps to reproduce

1.Just reading normally (webtoon, vertical) and it happens

### Expected behavior

Scroll without lag/freeze

### Actual behavior

Freezes for 2-5 seconds (if ~4-5 then it asks if i want to close the app or wait)
Sometimes it skips half a chapter or an entire one

### Crash logs

--------- beginning of main
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 11 (SDK 30)
Android build ID: qssi-user 11 RKQ1.200903.002 V12.0.26.0.RFQMIXM
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: laurel_sprout
Device model: Mi A3
Device product name: laurel_sprout

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Xiaomi MiA3 

### Other details

Video

https://drive.google.com/file/d/1VFSgHuYiL8or3gciGNY9rnG7sPvJlosa/view?usp=drivesdk

Issue #7240 looks similiar but it definitely is different so i guess this is a new issue

Bug can happen in any page of the manga

Bug doesnt happen for every manga/manhwa
Some extentions may (or may not) lag on a specifc manga more than others (but is usually the same

I was using "custom filters" and "crop borders", turned both off but issue continues

Been having this problem for a long time already but for this specifc manga (The Fable) it is happening way too often even while trying other extentions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Recent versions made some changes related to preloading chapters, so this is hopefully less of an issue now.
