### ISSUE TITLE
Ability to turn off scrolling through multiple categories in libraby. r5348

### ISSUE THREAD

**Issue by Ghostypunchy** [tachiyomiorg/tachiyomi#8736]
### Describe your suggested feature

Just the option to disable the ability to scroll through multiple categories at once because I'm issued to scrolling with a bit of momentum and it's harder to navigate. Or to at least the ability to change the sensitivity for when a multiple category scroll happens, if possible. Thank you for your time!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#8767
