### ISSUE TITLE
Rearranging categories (from the bottom) crashes the app immediately

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi#8738]
### Steps to reproduce

1. Go to More -> Categories
![image](https://user-images.githubusercontent.com/31158494/207517838-3056599b-4d20-44ed-aa2d-29badae849da.png)
2. Try moving the very last category using the arrows provided per item in the list
![image](https://user-images.githubusercontent.com/31158494/207513341-16459e4e-cb93-46cc-bd24-f933a759a593.png)
3. Try moving the very last category one level higher using the Up arrow in the list (doesn't work)
![image](https://user-images.githubusercontent.com/31158494/207513537-25f1c4c5-f5e6-4904-b722-7e9de60e0d71.png)
4. Try moving the second lowest item in the category list using the Down arrow in the list (crashes immediately afterwards)
![image](https://user-images.githubusercontent.com/31158494/207513789-d88eb53c-5e23-474a-8534-0912c8a44b11.png)

### Expected behavior

The second lowest category of the list will swap places with the very last one (the plan is included in the image)
![image](https://user-images.githubusercontent.com/31158494/207514074-e7fbd96d-07b4-419d-8b83-41f3cc81ebec.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/31158494/207514780-af8c59f6-4793-45b4-9ddd-21d0b0ef328f.png)
1. Moving one category up of the list (using the very bottom item) using the arrow keys (only Up is the option) doesn't move the item one up higher (illustrated in Teal).
2. Moving one category down of the list (using the second bottom item) using the arrow keys (both Up and Down arrows are available), immediately crashes the app (illustrated in Red).

### Crash logs

--------- beginning of main
12-14 13:17:18.713 16162 16344 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 13:17:18.713 16162 16344 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 13:17:18.980 16162 16194 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:17:18.982 16162 16194 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
12-14 13:17:19.797 16162 16412 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:17:19.797 16162 16412 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
12-14 13:17:33.206 16162 16354 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
12-14 13:17:33.206 16162 16354 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 20, Size: 19
12-14 13:17:33.206 16162 16354 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:161)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:13)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withNonCancellableContext(CoroutinesExtensions.kt:3)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:14)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:49)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-14 13:17:33.206 16162 16354 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
12-14 13:17:33.206 16162 16354 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@15f74a, Dispatchers.IO]
12-14 13:18:26.893 17017 17049 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 13:18:29.160 17017 17152 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 13:18:29.160 17017 17152 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 13:18:29.451 17017 17052 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:18:29.451 17017 17052 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
12-14 13:18:30.512 17017 17233 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:18:30.512 17017 17233 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
12-14 13:29:39.836 17017 17179 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
12-14 13:29:39.836 17017 17179 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 20, Size: 19
12-14 13:29:39.836 17017 17179 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:161)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:13)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withNonCancellableContext(CoroutinesExtensions.kt:3)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:14)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:49)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-14 13:29:39.836 17017 17179 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
12-14 13:29:39.836 17017 17179 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9bc4d84, Dispatchers.IO]
12-14 13:29:43.284 18254 18281 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 13:29:44.550 18254 18419 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 13:29:44.550 18254 18419 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 13:29:44.738 18254 18284 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:29:44.738 18254 18284 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
12-14 13:29:45.380 18254 18485 E anade.tachiyom: open_verbose_path:50: Could not open '/dev/goldfish_pipe': No such file or directory
12-14 13:29:45.380 18254 18485 E anade.tachiyom: open_verbose:121: both vsock and goldfish_pipe paths failed
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.004
Device brand: google
Device manufacturer: Google
Device name: redfin
Device model: Pixel 5
Device product name: redfin

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Windows Subsystem for Android (tm) version 2209.40000.28.0

### Other details

- The language used here is Filipino, but the effect is the same in English.
- I use a mouse and keyboard (since I use a laptop), and I didn't touch anything on the _Compatibility_ section in WSA settings (see image below)
![image](https://user-images.githubusercontent.com/31158494/207516381-aea15837-e066-4eed-bba8-a1dc48de8a1c.png)
- Even tried to do this in Tachiyomi Preview r5348 with the same backup, and unfortunately the same crash occurred.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please share the backup.

**Comment by CedMIX-Productions** [comment]
Here's my backup from both stable (0.14.2) and preview (0.14.2 r5348) [Keeping in mind that these are identical backups, and tried this from a freshly reset Tachiyomi Preview]
Stable:
[tachiyomi_2022-12-16_08-27.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10241780/tachiyomi_2022-12-16_08-27.proto.gz)
Preview:
[tachiyomi_debug_2022-12-16_08-45.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10241784/tachiyomi_debug_2022-12-16_08-45.proto.gz)

I'll add the debug log from the preview version:
[preview_tachiyomi_crash_logs_Dec_16_2022.txt](https://github.com/tachiyomiorg/tachiyomi/files/10241795/preview_tachiyomi_crash_logs_Dec_16_2022.txt)
