### ISSUE TITLE
[Bug] Tracker "open in browser" opens an app instead of the browser

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8743]
### Steps to reproduce

1. install anilib(anilist) or a my animelist third party app and then open it (then close if you want)
2. login your MAL account or Anilist account in the traker for tachiyomi
3. find an entry and add it to your list. now it is tracked
4. 

https://user-images.githubusercontent.com/75091899/207741392-0290acdb-410f-4a76-9d14-d53a5bc731c3.mp4

### Expected behavior

Tachiyomi should open the browser

### Actual behavior

Tachiyomi opens the third party app associated to the website archive. This happens because i set Anilib to open always the links when i click on Anilist icon (like in the video above)

### Tachiyomi version

0.14.2

### Android version

Android 8 Miui 8

### Device

Huawei p8 lite 2017

### Other details

This is also a kind of feature request. Can you make the "open in browser" option there open only links on browsers? clicking on the icon of anilist one should be able to trigger the opening of the third party app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
in the video: "Sempre" is Always while "Solo una volta" is only this time

**Comment by arkon** [comment]
This is pretty on par with how standard link handling behaves across Android.

**Comment by Palloxin** [comment]
Can't it at least open android webview?

**Comment by Palloxin** [comment]
@alessandrojean luckly that app is on github, can i ask you what should i ask the dev of anilib exactly?

**Comment by alessandrojean** [comment]
That app having the hability to open Anilist links is a feature, not something you need to ask to be removed. That's really how Android works, if you don't want the app to open these links, clear the defaults on your system settings for that app and choose the browser as the default next time.

**Comment by Palloxin** [comment]
I have a question then, just curious: Lets imagine 1st kiss has its official app and i install it. If i go to one of its entries and open its webview, will 1st kiss official app appear as a choice?

**Comment by alessandrojean** [comment]
Through WebView, no. If you click Open in Browser in the WebView screen, maybe it will prompt you which app you need to open that link (this if that said app supports deep linking as well).

**Comment by Palloxin** [comment]
@alessandrojean i just tested it on the extension Webcomics.
this one has its official app on the play store so tried.
Unluckly this has a broken extension on tachiyomi so i only tested the main screen of the website with webview. I did open in browser throught webview and Firefox opened instead of the official app. Take in mind that if i visit their website on my browser i can find the option "open in app" so i guess it supports deep links as you said. So __if__ i'm not wrong, why can webview open specifically the browser while tachi can't?

**Comment by arkon** [comment]
The WebView -> browser logic has to explicitly request a browser rather than any deep linked app to avoid infinite loops of Tachiyomi extensions handling the link and re-opening Tachiyomi.

That is not an issue for trackers. Opening tracker links should be handled by whatever the user has set to handle those links. If you want to have a choice, update your link handling settings for those app(s). This is standard Android behaviour.

**Comment by Palloxin** [comment]
What about using Webview instead of "open in browser" for trackers since the icon on the left does the exact same job?

**Comment by arkon** [comment]
No, there's no reason to open it in WebView. WebView is for resolving source loading issues, not for your browsing leisure.

**Comment by Palloxin** [comment]
I am confused then, why has been kept the icon on the left __and__ "open in browser" since they do the exact same job

**Comment by arkon** [comment]
For convenience / because people didn't realize you can tap the logo.

If you want to keep discussing this, go to Discord. This is not a discussion forum.

**Comment by Palloxin** [comment]
ah..Discord is off limits for me
