### ISSUE TITLE
"true center" Zoom start position 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#8747]
### Describe your suggested feature

Currently "Center" zoom start position only horizontally center the page. It would be helpful if there;s  an option for "true center", where zoom start position would be horizontally and vertically centered.

This would make devices with a shorter screen ratio (e.g. 4:3, 5:3) to be able to display many manga in fullscreen (with auto crop border enabled), without needing to scroll down. Because many manga did not place important elements near the top and bottom edges.

this feature request, "true center" zoom's usefulness, would diminish on taller devices. So it would be pretty much useless for most modern phones nowadays (21:9). as i don't think there's any manga with panels that tall.

it basically would help eink tablets. as most of them have shorter aspect ratio. Just like the current zoom start positions helps tall phones to view manga in fullscreen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by orangpelupa** [comment]
btw if i want to edit the source myself, any info on which file should i dig into? and if you dont mind, which line? i am basically a very bad script kiddy, so every help helps.

**Comment by stevenyomi** [comment]
> btw if i want to edit the source myself (lets say, editing the "Center" zoom to also vertically center the page), any info on which file should i dig into? and if you dont mind, which line? i am basically a very bad script kiddy, so every help helps.

Search for the setting name in the language files and use the string ID to find the preference value in the project, then trace where that preference is used.

**Comment by orangpelupa** [comment]
sorry! may i ask for more pointer? 

found this one on line 112 about center  zoom https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt

and this one seems indicates that value of "4" means center zoom https://github.com/tachiyomiorg/tachiyomi/blob/7d34ff214cad896abc2a834300d632ddce0a732f/app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt

but i failed to find which lines/files that is responsible for doing the center zoom.

**Comment by arkon** [comment]
It ultimately ends up being used here: https://github.com/tachiyomiorg/tachiyomi/blob/46417fe42778e82559cb5dd2ebc873c7fc984445/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderPageImageView.kt#L98

And is used within this library: https://github.com/tachiyomiorg/subsampling-scale-image-view/tree/846abe037f17e8dc85b70d60fa9f09d909620b58
