### ISSUE TITLE
TachiyomiJ2k Bookmark Book & Merge

### ISSUE THREAD

**Issue by teddysays** [tachiyomiorg/tachiyomi#8748]
### Describe your suggested feature

hi, i hope you guys can add a feature like "Bookmark Book" or "Favorite Book" and we can filter book in library to "show Bookmark Book only"

Second, bring "Merge Book" feature to "TachiyomiJ2K" too and we can selected what chapter we want to merge, for example Book A "Chapter 7" is missing and we can merge only "Chapter 7" Book A from another source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. Use categories
2. This isn't the J2K repo
