### ISSUE TITLE
Local sorting broken

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi#8750]
### Steps to reproduce

Have a series with numbers in title
View series inside Tachi

### Expected behavior

Should order chapters/volumes by number

### Actual behavior

Reads wrong number and sports wrong

### Crash logs

![IMG_20221215_155403](https://user-images.githubusercontent.com/1321906/208018139-595a8d70-f39d-49fe-8528-2d2e1920aaad.jpg)

### Tachiyomi version

r5348

### Android version

Android 12

### Device

RedMagic 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1. What sorting method did you set it to?
2. If set the display method to chapter numbers, what do they say?
