### ISSUE TITLE
Buon Dua ( search/filter not working )

### ISSUE THREAD

**Issue by Supernova212** [tachiyomiorg/tachiyomi#8751]
### Steps to reproduce

1. when trying to search it just give me an error no specific one 

### Expected behavior

search 

### Actual behavior

doesnt search 

### Tachiyomi version

0.14.2

### Android version

Android 11 

### Device

samsung a 30s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
