### ISSUE TITLE
never working option.

### ISSUE THREAD

**Issue by researchscum** [tachiyomiorg/tachiyomi#8755]
### Steps to reproduce

1. settings
2.advanced
3. browse
4. Turn Off Check for extension updates

### Expected behavior

no exetension new version bubble when opening app

### Actual behavior

it keep checking

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung s22

### Other details

it happen since old days no since that option available

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
That option just disables checking for extension updates in the background (when the app is not open). It will always check for updates while in the Browse tab and you shouldn't ignore them, update your extensions as outdated extensions are known for causing issues like crashes on the app over time.
