### ISSUE TITLE
Multiple source

### ISSUE THREAD

**Issue by mickae1** [tachiyomiorg/tachiyomi#8756]
### Describe your suggested feature

Sometime a team release before an another one. It would be great to add multiple source. And when one of them release first, it takes this one. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #8753
