### ISSUE TITLE
Backup option for settings

### ISSUE THREAD

**Issue by AbdullahBinJahed** [tachiyomiorg/tachiyomi#8757]
### Describe your suggested feature

It's a pain to set up the settings every time I uninstall Tachiyomi or roll back to previous version.

So it would be very nice if there were option to backup my settings

### Other details

would be nice if I could get this thing in version 0.13.6 as this was the best version of Tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Settings change over versions and it would be a lot of work do make them retrocompatible and not cause issues. We also don't support outdated versions, use the latest available version as soon extensions will stop working on the version you're using when they get updated.
