### ISSUE TITLE
Download indexing after each launch tachi

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#8765]
### Steps to reproduce

so it still turns for a long time and cannot be turned off

### Expected behavior

1

### Actual behavior

1

### Tachiyomi version

App version: 0.14.2-5369 (standard, 46417fe42, 92, 2022-12-17T22:31Z) Android version: 13 (SDK 33) Android build ID: TD1A.221105.003 Device brand: Redmi Device manufacturer: Xiaomi Device name: sunny Device model: M2101K7AG Device product name: sunny_global

### Android version

Android 13

### Device

Redmi note 10 

### Other details

![Screenshot_20221218-052133_Tachiyomi](https://user-images.githubusercontent.com/45261656/208278411-aebf866e-132f-426e-b849-1c54d6b51ae9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ve1mi** [comment]
> How many entries in there ? It seems so many it should take time.
Around 30gb 
I don’t care what time it is, but I don’t want to see it every time I start the program, it’s at least stupid and annoying

**Comment by arkon** [comment]
It'll reindex anytime you launch the app and it needs the download info (e.g., downloaded badges or downloaded filter), or later like opening the chapters or updates screens that show downloaded chapter states.

The app used to wait until it was done before actually showing anything, which is equally as slower but you couldn't do anything else.

It's also slower if you have a lot of downloads or you have slower storage (whether internal or just a slow SD card).

**Comment by ve1mi** [comment]
Lol real close. Joke. Wtf. 
Standart 10 class SD card. 
Omg every start now I will see this stupid indexing and is it normal now?
Thx arkon

**Comment by ve1mi** [comment]
Great just great, now the indexing goes after returning to the application when it was minimized (yes, filters were opened (wonderful filters that you have to click and select the same every time) . I don’t understand one thing, if this thing works by default and can't be turned off, why should I look at it that some kind of indexing is happening there? What is the meaning of this? I generally care about what is being done in the background (this indexing).
I don’t care at all what is being done in the background (this indexing) my ass just burns from this stupidity and how many thousands of times I see “indexation” in a year.

**Comment by loocool2** [comment]
Turn off the Indexing notification under notification settings in Android settings if you only want to hide the notification.

**Comment by arkon** [comment]
@loocool2 It was moved from a notification in #8746. Depending on feedback, it could be reverted. Your rude comments aren't really a good argument though.

The benefit of having obvious in the app is that it removes the confusion of people wondering why the badges or filter isn't working while it's indexing.

SD cards are always slow on Android. The OS itself doesn't use them efficiently, the actual class of the card doesn't really matter that much.

**Comment by ve1mi** [comment]
I hope that in the next versions it can still be turned off in the notification android tachi
