### ISSUE TITLE
"No match found" is not centered during indexing

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#8766]
### Steps to reproduce

Launch Tachiyomi
.

https://user-images.githubusercontent.com/101556532/208279262-7d1b46e3-e34a-409d-bb06-9daf0ef3311f.mp4

### Expected behavior

Should be centered like previous.

### Actual behavior

It was not centered.

### Tachiyomi version

r5369

### Android version

A11

### Device

Samsung Galaxy J6

### Other details

Not problematic but just to make it good looking.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Yeah I mentioned this in the commit message of 376bbeb724ca6cb7de53213c478d1750d99c8d2a

If any devs have an idea on how to better address that, let me know or please submit a PR.

**Comment by Dexroneum** [comment]
@arkon I think it's because EmptyScreen is considered as library item, so size and orientation will be as library item. If you turn  "Show layout bounds" on Developer options, you will see that its not take full space(Image 1 and 2)
![1](https://user-images.githubusercontent.com/46288465/208306137-badd838f-7a0a-411a-bd8f-4f2d9fd8a8d4.png) ![2](https://user-images.githubusercontent.com/46288465/208306145-d924c4ce-243b-470e-9918-c0dc8bbadbd3.png)

**Comment by arkon** [comment]
Well yes, that's what the commit message says.

It's an intentional change to move them into the list/grids so that the `PullRefresh` and global search items still show up.

**Comment by Dexroneum** [comment]
Understandable. If there are any method/variable/parameter that can take full width and height of Activity it can be a solution

**Comment by Dexroneum** [comment]
> Understandable. If there are any method/variable/parameter that can take full width and height of Activity, it can be a solution
