### ISSUE TITLE
Support for Sui

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#8775]
### Describe your suggested feature

Since wireless debugging is a hassle, I only really got to using Shizuku after rooting. But then Shizuku itself recommended us to use [Sui](https://github.com/RikkaApps/Sui) if we're already using root for it.
![Screenshot_20221219-191834](https://user-images.githubusercontent.com/20804322/208537673-12eaaf82-cc69-4888-9457-7b8b6796b21d.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already does?
