### ISSUE TITLE
Can't search on extensions(nox emulator)

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi#8777]
### Steps to reproduce

1. Open any source,
2. tap on searching tab,
3. write the name of manga
4. Clicking enter

### Expected behavior

The source is searching for named manga etc.

### Actual behavior

Nothing happens.

### Tachiyomi version

0.14.2

### Android version

Android 9

### Device

nox emulator(Samsung galaxy s20 Ultra)

### Other details

Searching in library working without problem. Before version 0.14 sources worked too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Not much info to work with here. You could try asking for help on Discord if the troubleshooting guide doesn't help at all.
