### ISSUE TITLE
Sources won't update after changing phones 

### ISSUE THREAD

**Issue by rakklak** [tachiyomiorg/tachiyomi#8778]
### Steps to reproduce

1. Preform tachiyomi backup
2. Move backup to new phone
3. Restore backup
4. All series/sources are skipped 

### Expected behavior

The sources should update 

### Actual behavior

Every single title from every source is skipped 

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Galaxy S20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The notification already links to the website explaining the behavior.

**Comment by rakklak** [comment]
Hello, I reviewed the faq page and the backup and restoration page, there is no documentation of this process. I was able to resolve this on my own by unchecking the skip options for updates.
