### ISSUE TITLE
Toonily Filter Adult Content

### ISSUE THREAD

**Issue by chet-sudo** [tachiyomiorg/tachiyomi#8779]
### Steps to reproduce

Filter Adult Content doesn't work for "None and Only"

### Expected behavior

Can filter Adult Content by "All/None/Only"

### Actual behavior

Filters only works on "All"

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung Galaxy Tab S8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
