### ISSUE TITLE
Remove downloaded chapters prompt below oneUI5 "taskbar" 

### ISSUE THREAD

**Issue by muddymind** [tachiyomiorg/tachiyomi#8782]
### Steps to reproduce

Unfavorite a manga with downloaded chapters so the prompt to delete the downloaded chapters appears.

### Expected behavior

The prompt should be properly visible and the buttons to remove or close should be accessible. 

### Actual behavior

It will be behind samsung's new oneUI5.0 "taskbar" (not sure if this is an Android 13 feature) and I can't click the buttons of the prompt. The prompt should appear higher above the "taskbar". 

### Tachiyomi version

0.14.2-5369

### Android version

Android 13 (oneUI5.0)

### Device

Samsung galaxy tab s7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by muddymind** [comment]
Example:
![Screenshot_20221221_191256_Tachiyomi](https://user-images.githubusercontent.com/8367895/208985053-57d0de81-c279-4a29-baa8-57f1c19cdadc.png)

**Comment by fawwazali14** [comment]
![image](https://user-images.githubusercontent.com/82845339/209482007-84967b6a-5af3-4e82-8533-a269ce64df3e.png)

Looks fine?

**Comment by muddymind** [comment]
The issue is related to when you are viewing the manga chapters and not the mangas list. See the screenshot I posted.
