### ISSUE TITLE
Mark previous as read not deleting

### ISSUE THREAD

**Issue by Ikkegwn** [tachiyomiorg/tachiyomi#8785]
### Steps to reproduce

You have a bunch of downloaded and/or read chapters.
The setting "delete chapters", after manually marked as read, is turned on
You go above and select the option.
The chapters stay downloaded and don't get deleted.
This used to work on older versions

Side note, the option "after reading automatically delete" second to last, doesn't always work either.

### Expected behavior

To delete everything below the marked point

### Actual behavior

The downloaded chapters are still there

### Tachiyomi version

Stable 0.14.2

### Android version

Android 10

### Device

Oneplus 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#6131 would address this in some way. Deletions can be quite slow and don't happen if you kill the app too fast after triggering it.

**Comment by Ikkegwn** [comment]
It's mostly that in older versions, wjen you did mark as read below, it would delete, which was convenient to mass delete
