### ISSUE TITLE
Bottom navigation icon animations repeating 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8786]
### Steps to reproduce

Go to more
Go to history
Repeat

### Expected behavior

Icon animation should occure only on the selected icon

### Actual behavior

Icon animation occurs on the previous icon as well.

https://user-images.githubusercontent.com/48650614/209126441-15cf2644-014f-4317-9bf7-35350d796366.mp4

### Tachiyomi version

r5369

### Android version

Android 12 

### Device

Tecno spark 6 

### Other details

I get that there is an enter and exit animation on these icons, especially when the icon changes when selected (like library icon being filled Vs unfilled).
But repeating the same animation when icon itself didn't change isn't necessary (the more icon)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The other icons all had exit animations in 0.14.2. This is technically more consistent?
