### ISSUE TITLE
Nhentai can't access 

### ISSUE THREAD

**Issue by musashi812** [tachiyomiorg/tachiyomi#8790]
### Steps to reproduce

![Uploading Screenshot_2022-12-23-12-42-35-37_afd66b7916d19a60815f56273408b73e.jpg…]()

### Expected behavior

Should have access to it

### Actual behavior

It's say Failed to connect to nhentai.net and when i try to open in webview It loading like eternity but if i open it in my browser it working properly 

### Tachiyomi version

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z) Android version: 10 (SDK 29) Android build ID: CPH1821EX_11_F.27 Device brand: OPPO Device manufacturer: OPPO Device name: CPH1821 Device model: CPH1821 Device product name: CPH1821

### Android version

Android 10

### Device

Oppo f7

### Other details

New user sorry if my English isn't good but i hope you understand what i try to deliver...thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

probably being blocked, try doh or vpn
