### ISSUE TITLE
different extensions and websites

### ISSUE THREAD

**Issue by 0second** [tachiyomiorg/tachiyomi#8791]
### Steps to reproduce

first, I already have the sectkomik extension
Second, but what I see in the extension is a different domain from the website
And the problem is the website domain and extension are different so I can't read on the new domain. Meanwhile, tachiyomi does not update the new extension 

### Expected behavior

When I open the sectkomik extension, I hope that the extension on tachiyomi and the website is the same

### Actual behavior

When I searched for the title of the comic I was reading, but the sektekomik extension doesn't exist because it's a different domain from the sektekomik website 

### Tachiyomi version

0.14.2

### Android version

Android 10

### Device

Redmi 9t

### Other details

![Screenshot_2022-12-23-14-24-01-714_eu kanade tachiyomi](https://user-images.githubusercontent.com/121283229/209294979-c4453621-e63c-4bef-bd09-365705d742c3.jpg)
![Screenshot_2022-12-23-14-39-25-248_eu kanade tachiyomi](https://user-images.githubusercontent.com/121283229/209295001-7807ff68-2fef-495a-8922-9471c8881398.jpg)
![Screenshot_2022-12-23-14-39-31-200_eu kanade tachiyomi](https://user-images.githubusercontent.com/121283229/209295018-cf799c24-54b7-4f34-9462-fb482a20a3b9.jpg)
![Screenshot_2022-12-23-14-39-48-995_com android chrome](https://user-images.githubusercontent.com/121283229/209295037-f5193440-e36c-4705-b02b-6ca15493ee1f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the extensions repository.
