### ISSUE TITLE
Tap & Hold doesn't open the manga info page when clicking on a manga inside Browse Search during Migration

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#8794]
### Steps to reproduce

1. Have a manga saved in your library and have two sources installed
2. Migrate the manga
3. this opens Global Search and searches your (pinned) sources for the manga name
4. Tap on a manga. Also try Tap and Hold on the manga.
5. Click on Source name (the heading like eg: MangaDex -> ). This will open a new screen where it'll search for that manga in that particular source
6. Tap on a manga. Also try Tap and Hold on the manga.

### Expected behavior

Step 4 and Step 6 behave the same
Tapping selects that manga as migration target
Tap & Hold opens the manga and lets you see the chapter list, manga info

### Actual behavior

Tap & Hold doesn't open the manga info page
it behaves the same as Tap

### Crash logs

NA

### Tachiyomi version

r5369

### Android version

Android 13

### Device

Samsung Galaxy Note 10 Lite

### Other details

Sorry the title is a mouthful...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Duplicate of #8176 .

**Comment by curche** [comment]
Nice catch!
