### ISSUE TITLE
Custom Color Filter Per Manga Series

### ISSUE THREAD

**Issue by ACViper** [tachiyomiorg/tachiyomi#8795]
### Describe your suggested feature

Would be nice to have custom filter settings for different manga. Having to turn it off or constantly change the rgba settings for each manga/manwha can be exhausting, since I have to remember the settings I put. If for some reason this isn't possible, being able to save multiple filter settings as a file and loading them would be the second best option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Per-manga settings are extremely annoying to implement, so it'd have to be very commonly different for different entries like the reading mode.

At best, having saved color filters that are more easily selectable would be something I'm open to. If you're interested in that, please open another issue for that.
