### ISSUE TITLE
Load multiple images at once

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8796]
### Describe your suggested feature

It will make it easier for readers who read online so they don't wait for the images to be loaded one by one, but instead make 1 load for 5-10 images at 1 time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already preloads the next 4 pages.
