### ISSUE TITLE
Can no longer tap the number in a picker to type in a different number

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#8799]
### Steps to reproduce

1. Go to anywhere in the app with a picker (ex. Item per row count under More > Settings > Library, rating/chapter count/finish date/start in the tracker sheet)
2. Tap the currently selected value

### Expected behavior

The keyboard or numpad should pop up and allow you to replace the current value with one from the keyboard.

### Actual behavior

No response

### Tachiyomi version

Preview r5369

### Android version

Android 9

### Device

Amazon Fire HD 10+

### Other details

Regression in features from the switch from NumberPicker to WheelPicker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fawwazali14** [comment]
Where is the picker can you give exact details?

**Comment by loocool2** [comment]
I already gave several examples of where a picker is located in the main issue body

**Comment by VeceluXa** [comment]
This! Why would you replace a picker only to remove it's core features. Now when I try to change the number of completed chapters in tracker I need to manually scroll to the correct number. It is so annoying! I hope the older picker will be back soon.
