### ISSUE TITLE
Can't Choose Searched Titles Within Categories

### ISSUE THREAD

**Issue by JeromeAugustus** [tachiyomiorg/tachiyomi#8801]
### Steps to reproduce

1. Choose a category or use the default category
2. Enter a keyword in Search
3. Choose one manga and use the Select All

### Expected behavior

Only search results with the keyword should be chosen to move, download, or delete.

### Actual behavior

All mangas in the category are chosen.

### Crash logs

No log.

### Tachiyomi version

0.14.2

### Android version

Android 12 SP1A.210812.016

### Device

Xiaomi 11T

### Other details

This is a useful feature from an older version. I wonder if it could return.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already fixed for next release.
