### ISSUE TITLE
I can't open any of my chapters

### ISSUE THREAD

**Issue by Malaziqua** [tachiyomiorg/tachiyomi#8808]
### Steps to reproduce

Whenever I click on a chapter, I get: "Unexpected JSON token at offset 17..."

### Expected behavior

When I click on a chapter I would expect it to load and display the chapter's content.

### Actual behavior

Instead, it only loads the format of the page view and then takes me back out to the chapter menu.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Samsung galaxy A01

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Malaziqua** [comment]
I'm very new to this. So, what exactly do I do now? What even is this extensions repository...

**Comment by alessandrojean** [comment]
There's a link in the acknowledgements section you checked the checkboxes, you follow it and open an issue in the other repository. There it will be a form just for extension issues which asks for more detailed stuff like extension version, reproduction steps and other things. You can ask for help in our [Discord server](https://discord.gg/tachiyomi) if you need.

**Comment by Malaziqua** [comment]
Thank you!
