### ISSUE TITLE
Chapter renamed by number, blank or (invalid)

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8810]
### Steps to reproduce

1. Download comic
2. Chapter name is from number
3. Or chapter folder named (invalid) or blank

### Expected behavior

Chapter have "Chapter" attribute on first
Like "Chapter 01"

### Actual behavior

Chapter renamed by number and in the storage became (invalid) if not have a name or blank

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Realme 7i

### Other details

![Screenshot_2022-12-27-21-48-38-95_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/209683421-065d3092-48ec-4f0d-8360-809e83082251.jpg)
![Screenshot_2022-12-27-21-49-07-46_83ab3b20d3fba5c9c905d050db1f8de3](https://user-images.githubusercontent.com/50316075/209683429-27e3915a-0e03-4783-bfde-75c09c7702b9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
What was the source/manga/chapter?

**Comment by TheKingTermux** [comment]
> What was the source/manga/chapter?

It's Doujindesu / Enjo Kouhai / All chapters

**Comment by arkon** [comment]
Looks like the chapter name == the entry name, so it gets fully stripped out. Extensions could deal with that, but I guess the app should try to account for that case somehow.

**Comment by Hipp0x** [comment]
Hi, i will work on this
