### ISSUE TITLE
Global search: multiline titles causing source to move up and down

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8814]
### Steps to reproduce

Have at least two sources
Global search on both

### Expected behavior

Both sources' result should be fixed in place

### Actual behavior

It moves up and down when scrolling the results which contain multiline titles.

_video illustrates it better_

https://user-images.githubusercontent.com/48650614/209764543-b7bb75a3-6209-4242-bae0-9ad73d5f6421.mp4

### Tachiyomi version

r5377

### Android version

Android 12 

### Device

Tecno spark 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Will probably address this by adding `minLines` once a stable version of Compose ships with that.

**Comment by arkon** [comment]
Fixed by #9122
