### ISSUE TITLE
Can't open chapter in webview with some extension

### ISSUE THREAD

**Issue by wh201906** [tachiyomiorg/tachiyomi#8816]
### Steps to reproduce

1. Install extension zh.dmzj
2. open a manga
3. open a chapter
4. click "open in webview" on the top

### Expected behavior

The chapter should be opened in webview normally.
The url should be `https://m.dmzj.com/12345/123456.html`

### Actual behavior

The chapter can't be loaded in webview. It shows `net::ERR_NAME_NOT_RESOLVED`
The url is `https://m.dmzj.com12345/123456`

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

x

### Other details

The zh.dmzj extension is up-to-date(1.3.35)
I know this issue comes with specific extension, but I checked both the code of tachiyomi and zh.dmzj and I guess this is caused by tachiyomi.
The `pageListRequest()` there is declared with `protected`.
https://github.com/tachiyomiorg/tachiyomi/blob/db3c98fe729ef6b00beba8d605bc002a7b8d1712/source-api/src/main/java/eu/kanade/tachiyomi/source/online/HttpSource.kt#L257-L259
When calling `openChapterInWebview()`->`getChapterUrl()`->`pageListRequest()`, the one in `HttpSource.kt` is always called, and the one in the extension is ignored.
https://github.com/tachiyomiorg/tachiyomi/blob/db3c98fe729ef6b00beba8d605bc002a7b8d1712/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt#L714-L721

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/cd2cf49d80d4d048c531a439bdd2deef5b6def61/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L182

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by wh201906** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14051#issuecomment-1296326502

**Comment by alessandrojean** [comment]
Protected keyword means the function can be redeclared and accessed in a class that makes inheritance of HttpSource, and not that the methot is protected from being used or something like that.

**Comment by stevenyomi** [comment]
I can fix it from the extension side.

**Comment by wh201906** [comment]
> Protected keyword means the function can be redeclared (since it has the open modifier as well) and accessed in a class that makes inheritance of HttpSource, and not that the methot is protected from being used or something like that.
> 
> https://kotlinlang.org/docs/visibility-modifiers.html#class-members

I got it. Thanks!
But the behavior does seem like the pageListRequest() in the extension is not used. I wonder why this happens.

**Comment by wh201906** [comment]
> I can fix it from the extension side.

Thanks!

**Comment by stevenyomi** [comment]
I checked the code and found that I did write the workaround. The chapter page is opening correctly in WebView and I can't reproduce your problem.

**Comment by wh201906** [comment]
I'm using Tachiyomi Stable 0.14.2 and DMZJ 1.3.35. I guess they are latest right?

**Comment by stevenyomi** [comment]
I get it. It was fixed by
- #8427
after the release of latest Stable. Just try Preview or wait for the next Stable.

**Comment by wh201906** [comment]
OK. Thanks!
