### ISSUE TITLE
Source not installed

### ISSUE THREAD

**Issue by lb-fes** [tachiyomiorg/tachiyomi#8824]
### Steps to reproduce

Sometimes( once a day or two days )

open Tachiyomi v0.14.2 or Tachiyomi automatic updates in the background

I will find Source not installed Error

Sorry, I don't know how to zoom pictures.
![1](https://user-images.githubusercontent.com/51531901/210159730-bfd99556-e391-4d2d-bb35-ef329cbee038.jpg)
![2](https://user-images.githubusercontent.com/51531901/210159731-d5e13ca5-f308-441b-8bcf-c0ed3a16b5b2.jpg)
![3](https://user-images.githubusercontent.com/51531901/210159732-b975495e-297c-4fc7-ac14-68fedcdf75d9.jpg)

I try to restart Tachiyomi, Source will be restored.

![4](https://user-images.githubusercontent.com/51531901/210160219-5fcae426-7bdf-44a0-ac83-a51e016ed1bf.jpg)
![5](https://user-images.githubusercontent.com/51531901/210160216-a0916271-507c-437c-977b-a4ac37a4c25c.jpg)
![6](https://user-images.githubusercontent.com/51531901/210160217-51bafd53-22a9-4212-acbd-7f1462383df3.jpg)

### Expected behavior

Source installed  in Browse 

### Actual behavior

Source not installed in Browse 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10328207/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Xiao mi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See #4313
