### ISSUE TITLE
Cache indexed downloads

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#8827]
### Describe your suggested feature

Currently, the app checks for indexed downloads when it opens for the first time. (which is pretty frequently in reality) We could save whatever data it indexes in a cache and on app opening, we invalidate read chapters from the date of the cache and check for any external deletions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Ihccato** [comment]
out of curiosity, how does indexing work? as in does the index create a file to reference downloads? i do bulk downloads at night, cause when i travel i dont have service, and it seems to index randomly, why not create a small file that has manga/chapter/downloads as a reference sheet, it could be a text document or anyother file type not a coder so idk, thus it has to index once it has the manga name/last update to metadata/last check to metadeta/ total chapters/downloaded chapters, and then you can change how frequently it checks to update the index. this will might end up helping out with updates, cause then it can check the file to see if there is new chapter and thus to download them, or not, cause updating the library to check for chapters/metadata is sending a bulk of data, using the library to store data that needs to checked once in while/weekly/daily and then using the index to then check what needs to be updated, if its cached, that upon first time opening, then when app crashes/phone restarts, the app has the data to instantly read and work.

**Comment by arkon** [comment]
The index is in memory. Files can be modified outside of the app, so the index may not be accurate hence the occasional refreshing (on app launch and every ~1 hour) to have a semi-reliable view of what you have downloaded without needing to check every time (which is extremely slow).

That said, that's exactly why it needs to happen on every cold start of the app -- there's 0 guarantee that the previous index was correct.

**Comment by Ihccato** [comment]
as someone with a long commute without service can it be up to the user to change when the index is and how frequently it occurs? id rather have it done at 3 AM and be set for the entire day, instead of staring out of a window waiting for it to finish. does every hr need to be done? or can it be changed to once a day? also why mod the files to be incorrect, it benefits no one.  imo i think using the index as the middle point to for, whats stored on app/device and what is updated in sources is smart, since the device can compile and accurately provide what is stable/correct and what sources say is new and needs to be updated.

**Comment by hyoretsu** [comment]
> That said, that's exactly why it needs to happen on every cold start of the app -- there's 0 guarantee that the previous index was correct.

And it would still happen on every cold start, but we'd have a headstart so that users don't need to wait to see which chapters are downloaded. Files can get modified outside of Tachiyomi, sure, but realistically that'd hardly happen. (Which isn't an excuse to slack off on it) And it's also why the cache'd get refreshed on every start/1h.

**Comment by arkon** [comment]
I'm confused as to what the issue is. This is how it always worked, except now the app is actually usable before the download index is populated on cold starts. If cold starts are an issue, then don't kill the app.

**Comment by Ihccato** [comment]
for me before id start the app, and have it run in the background, and it was clean, now it about every hr starts to index and sometimes leads to crash, thats why the i went back to 0.13, it takes a while to load/index but then runs smoothly, i never noticed that .13 did any hrly index.

**Comment by arkon** [comment]
You never noticed because it never told you. We could just hide it again.

If there's crashes, open an issue with the crash logs. There's been no reports of crashes related to indexing.

**Comment by Ihccato** [comment]
really? fascinating! ok maybe its on my end ill double check and update it. thank you for the support, i hope i wasnt too annoying or bothersome.
