### ISSUE TITLE
1-5 page manga bug transition 

### ISSUE THREAD

**Issue by SaneZer0** [tachiyomiorg/tachiyomi#8828]
### Steps to reproduce

(Always show chapter transitions is disabled in the settings)

For 1-5 paged chapters causing to bounce back to the previous page/chapter, extreme stuttering still shows chapter transitions regardless if you are reading fast or slow.

Manga in video:

https://w30.holymanga.net/the-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-girl-getting-less-and-less-tsun-day-by-day/

https://user-images.githubusercontent.com/65837094/210192457-1c61ae0a-876c-4eb4-8065-fd95d0a685fc.mp4

(Apologies for the low bitrate github compression)

### Expected behavior

Smooth experience like a normal manga like I guess with no transitions (when disabled)

### Actual behavior

Stuttering, you can see the pages have been loaded but still showing the transition (transition Is disabled) sometimes it's gets bounce back to the previous page/chapter.

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Google Pixel 6 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Transitions are always shown if it has to load the chapter.
