### ISSUE TITLE
Photos18 not loading

### ISSUE THREAD

**Issue by wsoscool** [tachiyomiorg/tachiyomi#8829]
### Steps to reproduce

1. Open Photos18

1. Open Photos18
2. Click on a cover
3. Click the chapter

### Expected behavior

Once you Open Photos18 it should load the covers

When you Open Photos18 and click on a cover to then click on the chapter it should load the images

### Actual behavior

Once you open Photos18 it doesn't seem to load the covers

When you click on the Chapter it doesn't seem to load and when you try to reload it with "Retry", it doesn't work

### Tachiyomi version

0.14.2

### Android version

Android 13

### Device

Galaxy S20+

### Other details

The WebView works fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.
