### ISSUE TITLE
Tachiyomi closed automatically 

### ISSUE THREAD

**Issue by vevinawynn** [tachiyomiorg/tachiyomi#8830]
### Steps to reproduce

1. Show all manga in Library 
2. Open tachiyomi

### Expected behavior

You can view all of the manga

### Actual behavior

Tachiyomi automatically closes on its own within 2-5 seconds after the tachiyomi logo disappear. This only happen if i view all of manga in library. But if i only choose downloaded manga, i can use the app normally.

### Tachiyomi version

13.3

### Android version

9

### Device

Samsung galaxy s8+

### Other details

This error happen after i restore backup from another device to my current device. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We don't provide support for older versions.
