### ISSUE TITLE
Can't install extension on MIUI 13

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#8834]
### Steps to reproduce

Install/update extension in the app (with legacy installer) on MIUI 13.

### Expected behavior

Install successfully.

### Actual behavior

The installer reports "parsing error".

The cause is the installation intent returning `RESULT_CANCELED` immediately while still launching the installer. The app then deletes the downloaded APK before the installer starts parsing the package.

https://github.com/tachiyomiorg/tachiyomi/blob/5cc84403e1a6de956d7b3893893e792f88497d73/app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstallActivity.kt#L21-L27

https://github.com/tachiyomiorg/tachiyomi/blob/5cc84403e1a6de956d7b3893893e792f88497d73/app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstallActivity.kt#L35-L40

https://github.com/tachiyomiorg/tachiyomi/blob/5cc84403e1a6de956d7b3893893e792f88497d73/app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstallActivity.kt#L42-L52

https://github.com/tachiyomiorg/tachiyomi/blob/5cc84403e1a6de956d7b3893893e792f88497d73/app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstaller.kt#L95-L96

### Tachiyomi version

0.14.2

### Android version

Android 11, 12, 13 (MIUI 13)

### Device

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Does it work if MIUI Optimizations are disabled?

**Comment by SudosFTW** [comment]
This doesn't seem to be a problem on MIUI 12 (12.5.10.0 Global, Poco M3) so this may be a change with the way the MIUI package installer does things in 13, AKA Android 12, which by itself did change a lot towards how apps were installed if memory serves.

But this is mostly to give feedback that it likely isn't every single MIUI device with optimization turned on, but probably MIUI 13 and beyond.

**Comment by SudosFTW** [comment]
As extension updates came through a few times in the last two days, I'm verifying that installing them through the extensions tab on MIUI 12 on 0.14.3 stable is working 100% correctly.

While the commit helps, this is just a single report from one model of phone using MIUI 12 or under, it'd probably be wise to gather more verified reports.

I'm also wondering if changing the region in the phone settings on MIUI 13 (Settings>Additional Settings>Region) changes anything with this, as it changes some behavior between reboots depending on what region you have selected based on the market. For instance, when set to Hong Kong, certain features are either unlocked or missing, while switching it to the US might remove one option in one app. 

Thus, if the region is set to China or Hong Kong, it may disallow apps to install other apps without giving you the option to allow it. Changing the region to Europe or elsewhere may possibly solve this problem altogether... But this itself needs verification as it's speculative on my part.

**Comment by stevenyomi** [comment]
My previous tests point to a bug in the Chinese version of the package installer[^1]. The latest update that I could update to on my device with the system's Xiaomi App Store is 5.0.5-20221024[^2], and it returns `RESULT_CANCELED` (only on cold start, subsequent install attempts will succeed; I could reproduce the cold start by restarting device, or by killing the package installer and retry installing in a small time window).

I'll try if newer versions on APKMirror has this bug.

MIUI Global seems to have a different package installer[^3] with a different package name (which you can check in the links), so it probably doesn't suffer from this issue. We can probably distinguish different systems by checking the package names.

[^1]: https://www.apkmirror.com/apk/xiaomi-inc/xiaomi-package-installer/
[^2]: https://www.apkmirror.com/apk/xiaomi-inc/xiaomi-package-installer/xiaomi-package-installer-5-0-5-20221024-release/
[^3]: https://www.apkmirror.com/apk/xiaomi-inc/globalpackageinstaller/
