### ISSUE TITLE
I can't download or update manga chapters

### ISSUE THREAD

**Issue by mahdii3375** [tachiyomiorg/tachiyomi#8835]
### Steps to reproduce

I can update my extensions but i can go to extensions to load mangas and ad ro library.
I can't update chapter list of mangas that already are in my library and i can't download perviously chapters of mangas that are in my library
I can open the extensions website with my browser fast and normally and i have no internet problem i cant use app anymore please help

### Expected behavior

When i enter app it must update my library to the last a d downloaded unread chapter for me but it doesn't work and completely broken

### Actual behavior

But as i said befor:
"I can update my extensions but i can go to extensions to load mangas and ad ro library.
I can't update chapter list of mangas that already are in my library and i can't download perviously chapters of mangas that are in my library
I can open the extensions website with my browser fast and normally and i have no internet problem i cant use app anymore please help"

### Tachiyomi version

0.14.2

### Android version

12

### Device

Poco x3 pro

### Other details

My miui version is 13.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

If troubleshooting doesn't help, try asking on Discord.
