### ISSUE TITLE
Color filter button according to theme

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#8840]
### Describe your suggested feature

Currently, when you are  filtering chapters on a manga, the filter button turns this gross yellow color that is fairly visually unappealing and dissonant with the rest of the app. If, instead, the filter button could be colored according to the current set theme, I think it would look significantly better.

Current look:
![Screenshot_20230106-003812](https://user-images.githubusercontent.com/61708534/210938151-b7716893-11ff-46b0-8515-bf802c8bb15b.png)

Suggested look:
![its](https://user-images.githubusercontent.com/61708534/210938190-92d2e29f-7d0f-45a3-9231-c705afcb9dbc.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It has to stand out more for people to realize it's on.
