### ISSUE TITLE
"Add to Library" snackbar super wide on tablets

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#8841]
### Steps to reproduce

Download a chapter from a non library manga to trigger the snackbar

### Expected behavior

A normal looking snackbar appears, offering to add the manga to your library

### Actual behavior

This funky thing:
![Screenshot_20230106-004624](https://user-images.githubusercontent.com/61708534/210938680-638b210c-d9ad-460d-a5ed-16327b8130c7.png)

### Tachiyomi version

r5383

### Android version

10.0

### Device

Vankyo P40 Tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is controlled by the upstream Material Design library. If they adjust it to better fit the specs, then we'll naturally get those as we update the dependency.
