### ISSUE TITLE
Cannot bypass Cloudflare for nhentai

### ISSUE THREAD

**Issue by RZeeka** [tachiyomiorg/tachiyomi#8843]
### Steps to reproduce

Unable to read manga saved in my library from the extension or browse it because it fails to bypass the Cloudflare.
Tried the "Open in webview" option but it keeps reloading the page, unable to bypass the Cloudflare as well.
Tried clearing the webview data and it led to the same result. 

### Expected behavior

Open the manga chapter and read it normally. 

### Actual behavior

Chapter loads temporarily then returns to the main manga page because it fails to bypass the Cloudflare. 

### Tachiyomi version

0.14.2

### Android version

Android 9

### Device

Oppo A1k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
If this is an issue with an extension, I should be opening an issue in the extensions repository.
