### ISSUE TITLE
Add a library filter for extension of origin

### ISSUE THREAD

**Issue by lifehackerhansol** [tachiyomiorg/tachiyomi#8846]
### Describe your suggested feature

It would be nice to be able to filter out manga by the extension from which it was added from.

This is especially useful if/when Tachiyomi marks an extension as obsolete. 

Case in point:
- This happens: https://github.com/tachiyomiorg/tachiyomi-extensions/commit/eab9f61c93a3e02e0aeed3438f726085143f6875
- A manga in your library was in it. But which one?
- Now you have to tap through every single item in your library, find `Kirei Cake` in the context of this example, then migrate it to another suitable extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#7931, you can also just use the migration tab for your usecase. If its removed from the repo, then it'd be numbers.
