### ISSUE TITLE
Download badge is displayed when filtered by downloaded 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8850]
### Steps to reproduce

Download some chapter
Apply download filter from the filter sheet in library 

### Expected behavior

Filter by download with the enabled badges shown

### Actual behavior

Download badge shown even though it is disabled 

### Tachiyomi version

r5383

### Android version

Android 13

### Device

Tecno spark 6

### Other details

![Screenshot_20230107-100212_Tachiyomi](https://user-images.githubusercontent.com/48650614/211132066-72d1661a-79b9-4475-a985-1cdcf60081c8.png)
Download badge is not checked:
![Screenshot_20230107-100221_Tachiyomi](https://user-images.githubusercontent.com/48650614/211132077-486b87db-887a-4883-a67c-0128e80890e0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
Click Downloaded chapters on badge. The first picture only shows series with Downloaded chapters, not to add a download  badge
![image](https://user-images.githubusercontent.com/87552756/211140929-e368b8cc-066b-4b52-a72e-8f6ef3d466fe.png)

**Comment by mobi2002** [comment]
> Click Downloaded chapters on badge. The first picture only shows series with Downloaded chapters, not to add a download badge
The download badge is being displayed even when it is disabled. (Only when download filter is applied)
