### ISSUE TITLE
Substantial depreciation of backup restore times.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#8853]
### Steps to reproduce

Create a backup and restore in different versions of tachiyomi.

### Expected behavior

N/A

### Actual behavior

N/A

### Tachiyomi version

Preview r5383

### Android version

Android 12

### Device

Redmi Note 9 Pro Max

### Other details

Tachiyomi backup restore speeds seem to have been detoriating quite substantially it went from 3-4 mins in 0.13 to about 20 mins in latest preview on fresh installing about 20 mins on overwriting a library with a backup in 0.13 to an hour in preview of a few months back and now upwards of 2hrs in preview from this and previous few weeks.

The exact times for different version are as follows for a fresh install.
For 3118 item library restore time for :
- 0.12.3 - 8mins , 50 secs
- 0.13.6 - 2mins , 23 secs
- 0.14.2 - 5mins , 15 secs
- r5383 - 19mins , 14 secs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
0.13.x/earlier versions of 0.14.x explicitly removed logic to do the SQL parts in transactions, which allowed for faster speeds at greater risks of database corruption.

Transactions are back now post-SQLDelight migration, which seems safer. It may be fine tuned in the future, but otherwise this is expected.
