### ISSUE TITLE
Pages do not change with tap while using stretch

### ISSUE THREAD

**Issue by GaryShem** [tachiyomiorg/tachiyomi#8863]
### Steps to reproduce

1. Use manga where the image is smaller than screen (ex. MangaPark, En En no Shouboutai, ver. Duck, ch. 114, page 3), I'm using a 10.5" tablet
2. Set scale type to Smart Stretch or Horizontal
3. Try tapping the "next page zone" - issue here

Settings used: right to left, L-shaped tap zones

Page can still be changed with swipe, or by switching back to original size for problematic chapters

### Expected behavior

The page should switch to the next one

### Actual behavior

Nojthing happens

### Tachiyomi version

0.14.3

### Android version

Android 12

### Device

Samsung Galaxy Tab a8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Does it navigate to the next page if you tap twice? Do you have "pan wide images" on?

If so, this is resolved in #8856 and will be fixed in the next Stable version.

**Comment by GaryShem** [comment]
> Do you have "pan wide images" on?
Yes.

> Does it navigate to the next page if you tap twice?
No. I can't tap to go to the next page by tapping twice or even if I zoom in. 
However, I can navigate to the previous page, zoomed in or not.

**Comment by stevenyomi** [comment]
> If I disable this, tapping starts working again.

Then it's probably the same issue. Try [the latest preview](https://github.com/tachiyomiorg/tachiyomi-preview/releases) to see if it's fixed for you.

**Comment by GaryShem** [comment]
Seems to work in the preview version.
