### ISSUE TITLE
Reading place tracking issue

### ISSUE THREAD

**Issue by amboxer21** [tachiyomiorg/tachiyomi#8868]
### Steps to reproduce

Place reading view into mahnwa mode.

### Expected behavior

I should be able to exit the app or use another app and come back to the mahnwa that i was reading at the same exact spot I left it.

### Actual behavior

If I close the app or if I use another app without closing the tachiyomi app, when I come back to the app, the page that it opens to will sometimes be 2 or 3 chapters back. Other times it will be a few pages back. Sometimes if I hit the back button and click on the title again it will be a page or two behind - all of this is done from the history page. 

### Tachiyomi version

0.14.3

### Android version

12

### Device

Pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kikepp10** [comment]
I have the same problem.

**Comment by amboxer21** [comment]
Still an issue and it's happening with manga too

**Comment by arkon** [comment]
There's been some improvements to this in recent versions around when it saves progress. Note that losing exact scroll position within the chapter for longstrip content is expected since it tracks "pages", not scroll percentage.
