### ISSUE TITLE
Return ability to hide unread chapter badges in Library

### ISSUE THREAD

**Issue by devlman127** [tachiyomiorg/tachiyomi#8871]
### Describe your suggested feature

Recently the ability to hide the unread chapter badges have been removed on the latest Preview builds. I'd just like the option back, as I find it more personally appealing

### Other details

Preview Build r5405 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The intention is for content to be eventually read.

**Comment by devlman127** [comment]
I understand you prefer it to be there, but I can already see the unread chapters if I check the entry itself. I just think the badges get in the way of the cover art
I don't understand why you're pulling a values judgement over such a small UX feature

**Comment by arkon** [comment]
We're trying to reduce the complexity that plagues the app which makes it hard to maintain.

There isn't a particularly good reason to _not_ remove the setting over "such a small UX feature" that's "personally appealing". The benefits of not having the extra logic is more beneficial than such minor functionality.

**Comment by devlman127** [comment]
There's already the ability to show & hide different badges. I can't imagine how doing the same for the unread chapters is any more complex unless it uses different different code entirely
