### ISSUE TITLE
Chapter loading problem 

### ISSUE THREAD

**Issue by Masrurkeepit** [tachiyomiorg/tachiyomi#8873]
### Steps to reproduce

1. open the extension 
2. choose a title 
3. open a chapter
4. image couldn't be loaded

### Expected behavior

1. open the extension 
2. choose a title 
3. open a chapter
4. image starts loading 

### Actual behavior

1. open the extension 
2. choose a title 
3. open a chapter
4. image couldn't be loaded

### Tachiyomi version

Tachiyomi Sy 1.8.5

### Android version

12

### Device

Samsung m21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Masrurkeepit** [comment]
> ### Steps to reproduce
> 1. open the extension
> 2. choose a title
> 3. open a chapter
> 4. image couldn't be loaded
> 
> ### Expected behavior
> 1. open the extension
> 2. choose a title
> 3. open a chapter
> 4. image starts loading
> 
> ### Actual behavior
> 1. open the extension
> 2. choose a title
> 3. open a chapter
> 4. image couldn't be loaded
> 
> ### Crash logs
> _No response_
> 
> ### Tachiyomi version
> Tachiyomi Sy 1.8.5
> 
> ### Android version
> 12
> 
> ### Device
> Samsung m21
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
