### ISSUE TITLE
Auto tracker is not working 

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi#8876]
### Steps to reproduce

The previous fix did not Fix the issue.

As i mention on discord for some reason my tachi can't update my reading progress

I download chapter then i turn off internet and read and same thing happened

And i download another chapter and i read ch (internet on) and it's works fine

So it's Offline things

### Expected behavior

-

### Actual behavior

For example i read chapter 2 offline then turn on wifi
Update library or something still tracker and website says i only read chap 1 even history says i read chap 2

### Crash logs

Unfortunately logs is empty 

### Tachiyomi version

0.14.3

### Android version

10

### Device

Xiaomi Redmi 9c

### Other details

Previous ticket #8641 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment]
Ps: Last time i uninstall my tachiyomi and re download and tracks works fine but when i update my app yesterday to latest version the issue happened again

**Comment by Key-explanation** [comment]
I have the same problem

**Comment by shipoxx** [comment]
> I have the same problem

Finally someone can understand my pain, what phone you use/have?

**Comment by Key-explanation** [comment]
Vivo y15

**Comment by MarvashMagalli** [comment]
I have the same issue, trackers only work when I'm online, and doesn't auto sync after I read something offline.
I use a SM-G935F (Samsung Galaxy S7 Edge), Android 8

**Comment by MarvashMagalli** [comment]
My old phone died, I tested this again with a Galaxy S6 (Android 7) and I still have the exact problem. Will test this again with my new phone soon.

**Comment by shipoxx** [comment]
> My old phone died, I tested this again with a Galaxy S6 (Android 7) and I still have the exact problem. Will test this again with my new phone soon.

The new update still have the same issue even the TachiyomiSY

**Comment by shipoxx** [comment]
Update: V14.1 don't have this bug so...
