### ISSUE TITLE
1st Kiss error 429

### ISSUE THREAD

**Issue by 4cactusjackburgers** [tachiyomiorg/tachiyomi#8880]
### Steps to reproduce

Update library
Gives error 429 with only 1st kiss source 

### Expected behavior

Update successfully 

### Actual behavior

Does not update

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Xiaomi Redmi note 11 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Did you actually read acknowledgements?
