### ISSUE TITLE
Reader resets to first page of the chapter when rotating my phone

### ISSUE THREAD

**Issue by Ligerx** [tachiyomiorg/tachiyomi#8881]
### Steps to reproduce

1. Open up any manga
2. Read a few pages, check in the slider that you're not on page 1 anymore
3. Rotate the device, doesn't matter which orientation you were originally in

### Expected behavior

The reader should keep the same page in view after rotation.

### Actual behavior

The reader resets back to the first page of the chapter.

If I open the overlay, the page slider still shows the page number I should actually be at.

### Tachiyomi version

0.14.3

### Android version

Android 13

### Device

Google Pixel 5a

### Other details

I just upgraded to 0.14.3 recently. This wasn't an issue on 0.14.2.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DarkCoverUnleashed** [comment]
As a fellow user. What am I supposed to do?

**Comment by stevenyomi** [comment]
> As a fellow user. What am I supposed to do?

Wait for the next stable version.
