### ISSUE TITLE
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

### ISSUE THREAD

**Issue by gionlime** [tachiyomiorg/tachiyomi#8882]
### Describe your suggested feature

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

### Other details

项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
There will never be a flutter version.
