### ISSUE TITLE
download notification 

### ISSUE THREAD

**Issue by goodguy029** [tachiyomiorg/tachiyomi#8883]
### Describe your suggested feature

hi,
actually in last version there was a feature of download completed notification which is not anymore i would like to add it again back please it is a very useful feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can tell if downloads are complete if there's no download progress notification.
