### ISSUE TITLE
Japscan don't work

### ISSUE THREAD

**Issue by ashuralong** [tachiyomiorg/tachiyomi#8886]
### Steps to reproduce

1. download  the extension japscan in french
2. Try download chapter or read them

### Expected behavior

Normally I can read and dl chapter from this extension 

### Actual behavior

Currently, I can't read and dl from this extension. When I try to download I have an infinite loading. As if to read

### Crash logs

No response 

### Tachiyomi version

O.14.3

### Android version

12

### Device

Oneplus nord

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please read the acknowledgement section.

> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
