### ISSUE TITLE
Extension Information before Installing

### ISSUE THREAD

**Issue by SamJones04** [tachiyomiorg/tachiyomi#8891]
### Describe your suggested feature

Some helpful information about extensions would be really helpful. Something like tags, preview, description, etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Not viable generally as the info would have to be done by hand and there's over 1000+ extensions available for the app (and in different languages too).

Also it would have to be maintained so that the info is up to date

**Comment by SamJones04** [comment]
When people create an extension for the app couldn't they be required to add tags

**Comment by arkon** [comment]
Similar to #8628.

We've discussed descriptions/tags before; it's too difficult to have people properly provide info considering we can barely even get 18+ content flagged consistently.
