### ISSUE TITLE
Extension Download Queue

### ISSUE THREAD

**Issue by SamJones04** [tachiyomiorg/tachiyomi#8892]
### Describe your suggested feature

I've realised when downloading multiple extensions due to the length of the list it's hard to find the ones that are being downloaded/pending/installing. Would be helpful to have a menu similar to the Download Queue for Chapters but for Extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The Android system should already have notifications when packages are pending installation if it requires manual action.

**Comment by SamJones04** [comment]
Android only gives the notification when you're in app, if you leave the app while Downloading extensions it doesn't work most of the time. I've had plenty of times where I've had to restart downloads because they're stuck on Pending/Installing/Downloading. Might just be my own individual experience though.

**Comment by arkon** [comment]
That'd imply your system is killing the app in the background. Try https://tachiyomi.org/help/faq/#application-updates
