### ISSUE TITLE
Local manga from both Micro SD Card and Internal storage

### ISSUE THREAD

**Issue by Satria41** [tachiyomiorg/tachiyomi#8894]
### Describe your suggested feature

Local source that can show local manga from both micro SD Card and Internal storage at the same time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It already does? https://tachiyomi.org/help/guides/local-manga/

Please fill out the bug report template if there's an issue with it.
