### ISSUE TITLE
Downloading make new folder for each chapter

### ISSUE THREAD

**Issue by hykzqwmx** [tachiyomiorg/tachiyomi#8899]
### Steps to reproduce

After updating to new version (14.3) when downloading few chapter it create new folder for every chapter

Step to reproduce:
1. Download all on manga chapter
2. Download started and completed
3. Checking on file manager on download
4. It create new folder for every chapter

![Screenshot_20230112-233820_My Files](https://user-images.githubusercontent.com/122554947/212130994-61ecb2bb-3988-4bdc-8a24-21ad91e90841.jpg)

### Expected behavior

Expected behaviour:
All new chapter are in the same folder of manga title and in the same folder of manga source

### Actual behavior

Actual behaviour:
For every chapter downloaded it create:
(Manga source) folder / (Manga title name) folder / chapter number folder / image downloaded

### Tachiyomi version

0.14.3

### Android version

Android 10

### Device

Samsung Galaxy S9+

### Other details

This bug occur when I finish updating to newest version (0.14.3) from previous stable version

I put the file downloaded location in my microSD, inside android/data/eu.kanade.tachiyomi/files/...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
How is the first folder named? The one that doesn't have a number at the end. Try renaming it to `MangaSee (EN)`

**Comment by hykzqwmx** [comment]
> How is the first folder named? The one that doesn't have a number at the end. Try renaming it to `MangaSee (EN)`
> 
> There is already opened issue for this: [#7492 (comment)](https://github.com/tachiyomiorg/tachiyomi/issues/7492#issuecomment-1241563085)
> 
> You can go to [discord](https://discord.gg/tachiyomi) to get help with fixing it

Hi, the previous one is from before i download updatr 0.14.3
![Screenshot_20230113-002931_My Files](https://user-images.githubusercontent.com/122554947/212137962-4008865e-9bba-4d62-b9d5-c29eee0c1402.jpg)


Also just check the link you provided, the difference is, i can still open the downloaded chapter and read as usual,
But everytime i download new chapter, it create new folder instead of using the folder that created from previous version.

But i will try to check the discord
