### ISSUE TITLE
Categories 

### ISSUE THREAD

**Issue by Irfan000666** [tachiyomiorg/tachiyomi#8901]
### Describe your suggested feature

Requesting for each categories can be sort differently.. for example like aniyomi, each of the categories can be sort and change differently and won't change for all of categories together.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You can already do this, explore your library settings
