### ISSUE TITLE
Toggle to disable indexing downloads banner

### ISSUE THREAD

**Issue by ghtesting2020** [tachiyomiorg/tachiyomi#8903]
### Describe your suggested feature

              You never noticed because it never told you. We could just hide it again.

If there's crashes, open an issue with the crash logs. There's been no reports of crashes related to indexing.

_Originally posted by @arkon in https://github.com/tachiyomiorg/tachiyomi/issues/8827#issuecomment-1376508204_
 ///////////////////////////////////////////
Please add a toggle in settings to let us either show or hide this banner. It the referenced ticket above it was mentioned the app is not usable until the index is not done. That is not the case. I can do a restart of my phone, start tachiyomi and read right away. Now a bright banner displays for up to 5 minutes saying indexing downloads.

Alternatively let us completely disable indexing or only have them happen with library updates with other toggles. Is it absolutely necessary to be indexing all the time?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> It the referenced ticket above it was mentioned the app is not usable until the index is not done. That is not the case.

If you read it properly, it says it's **now** usable. It wasn't before, the app didn't show anything until the index was done.

> Alternatively let us completely disable indexing or only have them happen with library updates with other toggles. 

No, the app relies on the index to not be extremely slow to check for the existence of downloads everywhere.

> Is it absolutely necessary to be indexing all the time?

It doesn't, which is already explained in the quoted issue.

---

I'll just hide subsequent reindexes. This is how it always worked, and nobody seemed to notice downloads being wrong before anyway.
