### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by BeingNiNa** [tachiyomiorg/tachiyomi#8904]
### Steps to reproduce

The problem here is that:
 1. Whenever, I backup my data the app closes itself and when I reopen it, it shows everything empty such as, I can't see anything like Manga , History even Updates that I have saved or bookmarked or downloaded.
 2. Additionally, I restore the backup, the restore time takes up to 2 hours and 11 min but sometimes it restores some of the manga and Force Closes itself and that's all. 
 3. When I am reading the Manga the app closes itself again.
 4. Moreover, even when I am scrolling down the app closes itself. 
 5. Same goes for Global Update, whenever I update the Library it closes itself after reaching halfway. 
 6. The said issue happened when I installed the Tachiyomi Preview version too. 

### Expected behavior

It should be smooth. 

### Actual behavior

The problem here is that:
 1. Whenever, I backup my data the app closes itself and when I reopen it, it shows everything empty such as, I can't see anything like Manga , History even Updates that I have saved or bookmarked or downloaded.
 2. Additionally, I restore the backup, the restore time takes up to 2 hours and 11 min but sometimes it restores some of the manga and Force Closes itself and that's all. 
 3. When I am reading the Manga the app closes itself again.
 4. Moreover, even when I am scrolling down the app closes itself. 
 5. Same goes for Global Update, whenever I update the Library it closes itself after reaching halfway. 
 6. The said issue happened when I installed the Tachiyomi Preview version too. 

### Crash logs

I don't get any crash log when I reopen app. 🤨

### Tachiyomi version

App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z) Android version: 10 (SDK 29) Android build ID: SuperPIE Note9 V7 - lamlazy Device brand: samsung Device manufacturer: samsung Device name: crownlte Device model: SM-N960F Device product name: crownltexx

### Android version

Android Version 10

### Device

Device model: SM-N960F

### Other details

The problem here is that:
 1. Whenever, I backup my data the app closes itself and when I reopen it, it shows everything empty such as, I can't see anything like Manga , History even Updates that I have saved or bookmarked or downloaded.
 2. Additionally, I restore the backup, the restore time takes up to 2 hours and 11 min but sometimes it restores some of the manga and Force Closes itself and that's all. 
 3. When I am reading the Manga the app closes itself again.
 4. Moreover, even when I am scrolling down the app closes itself. 
 5. Same goes for Global Update, whenever I update the Library it closes itself after reaching halfway. 
 6. The said issue happened when I installed the Tachiyomi Preview version too. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Sounds like bad hardware or ROM. Try asking on Discord for help.
