### ISSUE TITLE
Manga added to library not show up

### ISSUE THREAD

**Issue by saisot2006** [tachiyomiorg/tachiyomi#8911]
### Steps to reproduce

Hi, i used to add manga to library but now it stops working. The new manga i added recwntly didn't show up in the library no matter how i tried.

### Expected behavior

It should show up in the library.

### Actual behavior

All new manga i added don't show up in the library.

### Tachiyomi version

0.14.3

### Android version

Android 13

### Device

Samsung A73

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably have a filter enabled? Try asking on Discord for help and open another issue if you have specific steps to reproduce a bug.

**Comment by saisot2006** [comment]
Yes, i found it filtered. Thank you.
