### ISSUE TITLE
Ability to sort library by source extension 

### ISSUE THREAD

**Issue by Magegamer** [tachiyomiorg/tachiyomi#8929]
### Describe your suggested feature

Would be nice to be able to sort mangas by their extension, the extensions can be sorted alphabetically or by size (number of mangas that originate from that source). Adding a 'divider' between sources (like in the downloads) would be nice. Example: 
![IMG_20230116_115527](https://user-images.githubusercontent.com/96168266/212662458-17d08ad4-c2ca-47c2-a677-3dbd957f5f2d.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can search by a source name (or tap it from the manga details screen to do so).

No plan to add such grouping.

**Comment by Magegamer** [comment]
Did not know I could do that
Thank you
