### ISSUE TITLE
Add FileView button to local manga

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#8933]
### Describe your suggested feature

It would function as a complementary feature to the WebView button for web-based manga, and it would open up the local manga folder of that entry in whatever default file application the user has installed. This would make it easier to make small adjustments to file names, covers, etc.\

Another FileView button inside the chapters, like the newly introduced chapter version of the WebView button, would also be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's no standard intent to open file explorers to specific directories in Android.
