### ISSUE TITLE
Migrate History

### ISSUE THREAD

**Issue by CodeSpoof** [tachiyomiorg/tachiyomi#8935]
### Steps to reproduce

- Read manga
- Migrate manga
- Look into history

### Expected behavior

History entry changed to new source

### Actual behavior

History entry of old source

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

OnePlus 6T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Feels weird to effectively have "faked" reading history. Read status is migrated already. If you want to track arbitrary reading history, please use actual trackers, the app isn't really meant for storing that data.
