### ISSUE TITLE
Countinious Crashes and Sudden Force Exit While Reading

### ISSUE THREAD

**Issue by TachiNate** [tachiyomiorg/tachiyomi#8937]
### Steps to reproduce

Situation:
Whenever I read a a series, there are times that the app forces you back to home page while reading and shows an pop up message. This has been going on for months, I didn't say anything as I assumed that it was because of having little storage left but, during this months, I've discovered that there are two types of message with two options everytime it happens.

The first message says: "Tachiyomi has stopped"
With the options of "close app" and "repair."

The second message says: "Tachiyomi keeps stopping"
Along with the same options asthe first message

Naturally at first I chose repair, but it bire no results. So in the end I just ended up ignoring them.

But now they seem to be happening more frequently. Especially the sudden closing of the app.

The sudden closing of the app started happening about month after the pop ups started.

Just now I was reading "Unordinary" and for five minutes I experienced at least two Forced app exit and at least ten pop ups

Could you pls explain and fix this
Thank you

### Expected behavior

This didn't happen when I was using Tachiyomi early last year, but ever since I moved to this phone, Tachiyomi has been acting weird and when I tried it at my old phone Tachiyomi also acted weird with all the pop ups and forced exit

### Actual behavior

I tried all I could think off for the reason why these things keep happening but none of them seemed to work

### Tachiyomi version

0.14.2

### Android version

7.0

### Device

ASUS_X018D

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TachiNate** [comment]
Reading what I just wrote, I'm embarrassed since I wrote the wrong things on every area, T-T, especially now that it's published to the public....

**Comment by arkon** [comment]
Please open another issue with crash logs attached.
