### ISSUE TITLE
Support for exporting catalogs of works in "Statistics"

### ISSUE THREAD

**Issue by qb0211** [tachiyomiorg/tachiyomi#8938]
### Describe your suggested feature

There are too few features for “Statistics”.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I don't think you are making any sense. Care to elaborate more on what you are asking?

**Comment by stevenyomi** [comment]
I think the original poster wants a feature to export a list of library manga. Neither is this related to statistics nor will this be added (rejected in multiple similar issues, see #8684).
