### ISSUE TITLE
Latest update not downloading 

### ISSUE THREAD

**Issue by ladysoftlighting** [tachiyomiorg/tachiyomi#8939]
### Steps to reproduce

1. Open 'About'
2. Click 'Check for updates'
3. Click 'Download'

### Expected behavior

Update downloads and app restarts

### Actual behavior

Update does not download

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung S10+

### Other details

App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G975WVLS7IVK2
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2q
Device model: SM-G975W
Device product name: beyond2qltecs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
It should show you a notification with a button to install the update, make sure you didn't disable notifications from Tachiyomi. Alternatively you can download new version from the [website](https://tachiyomi.org/download/) or [GitHub](https://github.com/tachiyomiorg/tachiyomi/releases). Go to #support channel on [Discord](https://discord.gg/tachiyomi) to get more help if needed.

**Comment by ladysoftlighting** [comment]
I downloaded the patch from the github and downloaded the latest version
