### ISSUE TITLE
Mangabuddy buffering , unable to download

### ISSUE THREAD

**Issue by Sreesiddhi** [tachiyomiorg/tachiyomi#8944]
### Steps to reproduce

1. Open any chapter from mangabuddy
2. Endless buffering

### Expected behavior

It should load images

### Actual behavior

Buffering

### Tachiyomi version

0.14.3

### Android version

Android 10

### Device

Redmi 9

### Other details

failed to connect to s1.mbcdn1.xyz/99.83.154.118 (port 443) from /25.254.229.233 (port 52346)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CodeSpoof** [comment]
Same problem, but the last update to the extension fixed it for me.
