### ISSUE TITLE
AMOLED Black don't work on some devices

### ISSUE THREAD

**Issue by musikowskipawel** [tachiyomiorg/tachiyomi#8946]
### Steps to reproduce

Open Tachiyomi normally and set borders in reading mode to black.

### Expected behavior

I expect the borders to be black, as set, but they're grey instead, I've also set pure black mode.

![Screenshot_20230118-220350_Tachiyomi](https://user-images.githubusercontent.com/66538450/213305370-90e2e56f-401d-4fd2-8c22-764c98623c83.png)

### Actual behavior

The borders are grey instead.

![Screenshot_20230118-220357_Tachiyomi](https://user-images.githubusercontent.com/66538450/213305404-8886bb18-d52d-49f8-9f91-e22d88584868.png)

### Tachiyomi version

Latest stable 

### Android version

Android 9

### Device

Galaxy Note 4 with AOSP Extended rom

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by musikowskipawel** [comment]
Not sure if I've written this correctly, I've never written bug report before, but this was quite annoying to me, so I thought I'll do.

**Comment by arkon** [comment]
Can't reproduce, and that grey is not the same one as the grey setting.

Is your ROM somehow not returning actual black for the standard black color?
