### ISSUE TITLE
Delete all read downloaded chapters option on each manga

### ISSUE THREAD

**Issue by sombresu** [tachiyomiorg/tachiyomi#8949]
### Describe your suggested feature

It can be on the three dots menu or download icon on each manga in the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Oh wait, you meant deleting downloading chapters that are read
This is better handled using Delete After Read Settings (More > Settings > Downloads)

You'll have to just delete your read & downloaded chapters the first time before enabling that setting, and then never again

Alternatively, if you filter by Unread [❌] and Download [✅], you have what you need

Orphaned Downloaded Chapters (chapters that remain even tho manga was removed) is being considered
And at the same time, it can cover Read Downloaded Chapters as well (forks j2k and sy already support this)
That request can be seen at https://github.com/tachiyomiorg/tachiyomi/issues/1767
