### ISSUE TITLE
Disable MIUI Optimization warning

### ISSUE THREAD

**Issue by darkwerr** [tachiyomiorg/tachiyomi#8950]
### Describe your suggested feature

![IMG_20230119_092454](https://user-images.githubusercontent.com/64715322/213443344-ac1e5075-05a1-4be2-9570-119cae2f0b3f.jpg)
Can we have a way to disable this warning without changing any phone settings? There's no X to close or anything in settings to disable it (that I'm aware).
On a side note, I never had any problems with installing anything with MIUI Optimization on. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
This has been removed in #8916. Wait for the next stable version.
