### ISSUE TITLE
Invalid Location is Displayed for Remote Backup and Download Locations

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#8952]
### Steps to reproduce

1. Set up a remote download or backup location using cifs documents provider or rclone (aka rpx)
2. Point either download or backup to the remote storage location
3. The backup/download location will be prepended with "invalid location"

### Expected behavior

Invalid location should not be displayed as download and backup r/w on remote storage locations works fine

### Actual behavior

The backup/download location will be prepended with "invalid location"

### Tachiyomi version

r5452

### Android version

Android 9

### Device

Amazon Fire HD 10+

### Other details

![image](https://user-images.githubusercontent.com/36128021/213637891-15f7ffa5-b42b-44f8-bcb6-dede2ae22e0c.png)
![image](https://user-images.githubusercontent.com/36128021/213637912-7e019651-9a39-42c5-838f-18994147e891.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do newer versions still say this?

**Comment by loocool2** [comment]
Doesn't seem like it
