### ISSUE TITLE
Tachiyomi crashing when page turn/volume buttons are used

### ISSUE THREAD

**Issue by knives-repo** [tachiyomiorg/tachiyomi#8953]
### Steps to reproduce

1. Using Boox Leaf2
2. Use Tachiyomi like normal, but use the tablet's page turn buttons (which are spoofed as volume buttons) to navigate

I am doing this in the paged reader option, right to left.

### Expected behavior

The app should just work like normal, with the page turn buttons turning pages.

### Actual behavior

Everything is fine at first but eventually the page turns get slower and slower until the app freezes, and the device crashes.

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Boox Leaf2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please provide crash logs if possible.

Potential ways of getting them:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by knives-repo** [comment]
[bugreport-Leaf2-2022-11-22_10-20_3.3.1_e4f27d41a-2023-01-22-01-21-12.zip](https://github.com/tachiyomiorg/tachiyomi/files/10473514/bugreport-Leaf2-2022-11-22_10-20_3.3.1_e4f27d41a-2023-01-22-01-21-12.zip)

Hope this is useful! I took this bugreport right after the device crashed after using buttons in Tachiyomi.

**Comment by knives-repo** [comment]
Upon further testing it seems that this crash and slow down only happens when I'm using external microsd storage. For now, problem seems to go away as well if I don't use external storage, and I can use the buttons with no problem.
