### ISSUE TITLE
[Bug] begin/resume button bug when using filters

### ISSUE THREAD

**Issue by vanBras** [tachiyomiorg/tachiyomi#8957]
### Steps to reproduce

Filter a manga on read.
Have read some chapters
The button that should say resume says begin.

### Expected behavior

The button at the bottom should say resume as i have read some chapters but filter the unread chapter to not be shown

![Screenshot_2023-01-21-22-57-37-580_eu kanade tachiyomi](https://user-images.githubusercontent.com/55386563/213888538-4b903954-5e1a-42e1-831b-bbce4cb820a6.jpg)

### Actual behavior

The button says begin.
![Screenshot_2023-01-21-22-57-22-252_eu kanade tachiyomi](https://user-images.githubusercontent.com/55386563/213888543-33410782-e42b-4ae6-ac16-423d6b4ab52c.jpg)

### Crash logs

No crash

### Tachiyomi version

0.14.3

### Android version

android 10 

### Device

xioami mi 9t

### Other details

Language set to dutch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It only really considers the visible list, so this seems fine.
