### ISSUE TITLE
Novel access

### ISSUE THREAD

**Issue by Soslanders** [tachiyomiorg/tachiyomi#8958]
### Describe your suggested feature

Yo, so I know that tachiyomi is used to read manga and whatnot however I've seen that some extensions also provide novels so I was wondering if it would be viable to maybe one day in the future have a way to access the moves from such extensions the same way that manga can be accessed already. If not, perfectly fine but I thought that it may be a cool idea.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

#685 #1854 #3557 #3560 #3990 #6301 #7700 #8809
