### ISSUE TITLE
Search fails whenever there's an apostrophe in a title

### ISSUE THREAD

**Issue by JavierFlores09** [tachiyomiorg/tachiyomi#8961]
### Steps to reproduce

1. Go to the explore tab, or in your library.
2. Click the search bar.
3. Search any title with an apostrophe in it (i.e.: "Novel's Extra", "Academy's Undercover Professor" or "The Lord's Coins Aren't Decreasing?!". These are all manhwas that can be encountered in the "Asura Scans" extension)

### Expected behavior

The results should match the query

### Actual behavior

Either the results don't match the query at all or there's no results at all.

### Tachiyomi version

0.14.3

### Android version

Android 7.0 (Samsung Experience 8.1)

### Device

Samsung Galaxy J7 (SM-J710MN)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

But it seems like the search on their website just sucks.

**Comment by JavierFlores09** [comment]
> > If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> 
> But it seems like the search on their website just sucks.

While I provided examples of a single extension, this happens with all the extensions I have tried so far

**Comment by arkon** [comment]
You'll have to try more, the provided examples work fine with other sources.

**Comment by JavierFlores09** [comment]
> You'll have to try more, the provided examples work fine with other sources.

I tried more and you are right however, this also happens in the search bar within the library tab. I don't believe that is an issue with an extension.

Proof:
without apostrophe:
![Screenshot_20230121-220750](https://user-images.githubusercontent.com/113814758/213896029-b5300ab2-85c5-4170-a4bd-1badc978d7ea.png)

**Comment by arkon** [comment]
We don't differentiate between different symbols. If you search with literally `'`, it won't match `’`.

**Comment by JavierFlores09** [comment]
> You'll have to try more, the provided examples work fine with other sources.

I tried more and you are right however, this also happens in the search bar within the library tab. I don't believe that is an issue with the extension. Here is proof:

without apostrophe:
![Screenshot_20230121-220750](https://user-images.githubusercontent.com/113814758/213896082-e55cd77b-a027-4161-986c-920200d2c5fa.png)

With apostrophe:
![Screenshot_20230121-220756](https://user-images.githubusercontent.com/113814758/213896087-066a2be3-1c9b-4ed3-93d5-6751119b28b6.png)

**Comment by JavierFlores09** [comment]
> We don't differentiate between different symbols. If you search with literally `'`, it won't match `’`.

Ah, I see. Sorry for the inconveniences, didn't actually notice it was a different character
