### ISSUE TITLE
App crashes when downloading new chapters

### ISSUE THREAD

**Issue by dkooool** [tachiyomiorg/tachiyomi#8977]
### Steps to reproduce

1. Open the app
2. Go to "More" tab
3. Go to "Download queue"
4. Press "Resume"
5. App closes

### Expected behavior

The downloads should just resume

### Actual behavior

The app closes without any message or notification and all downloads are paused and it happens with all sources

### Tachiyomi version

0.14.3

### Android version

Android 12

### Device

POCO X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
You should dump the crash logs and post them here.

**Comment by dkooool** [comment]
> You should dump the crash logs and post them here.

How do I do that?

**Comment by stevenyomi** [comment]
> Where do I find the crash logs?

In **Settings - Advanced - Dump crash logs** then check the notification.

**Comment by dkooool** [comment]
> In **Settings - Advanced - Dump crash logs** then check the notification.

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10484515/tachiyomi_crash_logs.txt)

**Comment by stevenyomi** [comment]
There's nothing useful inside. Try reproducing the crash and dump the logs again.

**Comment by scb261** [comment]
```
01-23 23:08:58.202 15154 15273 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/duktape/Duktape;
01-23 23:08:58.202 15154 15273 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.hitomi.Hitomi.pageListParse(Hitomi.kt:360)
```

Hitomi.la was removed, read tachiyomiorg/tachiyomi-extensions#3475 for more info about it.

The crash happens because the old extension uses code that isn't compatible with the newer version of the app. Remove any obsolete extensions that you have and make sure that other extensions are updated.
