### ISSUE TITLE
The global update function has no effect

### ISSUE THREAD

**Issue by dty285767** [tachiyomiorg/tachiyomi#8982]
### Steps to reproduce

Use global updates

### Expected behavior

Comics on all bookshelves are updated

### Actual behavior

The global update function has no effect

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Realme GT Neo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries
