### ISSUE TITLE
Ability to lock cover images or an undo/revert option for cover image changes.

### ISSUE THREAD

**Issue by AgentX2006** [tachiyomiorg/tachiyomi#8983]
### Describe your suggested feature

An option to lock cover images during manual updates that can be toggled per title and/or preferably for all titles at once (AKA be able to set it as the default). Perhaps a confirmation before changing the cover image during a manual title update. Even an undo function for the most recent change of the cover image would suffice. Retaining only the previous cover image for an undo should have a very minimal impact on storage even for very large libraries. Just some way to prevent accidentally changing the cover image.

### Other details

Updating cover images during library updates is an opt in function (Setting->Library->Automatically refresh metadata).
Updating cover images during manual title updates happens automatically with no way to opt out.
I can't tell you the number of times I was looking for a particular manga in my library and couldn't find it because I had accidentally triggered a manual update by dragging down and it now has a completely different cover image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Set a custom cover if you don't want it to use what the source provides.

**Comment by AgentX2006** [comment]
The issue is that some sources (mainly MangaDex but also some others) routinely change the cover image (mostly with each new volume cover). Setting a custom cover image for (in some cases myself included) 100, 200, or even more titles is a lot to ask to prevent cover art changing.

An alternative with less overhead could be an option in the chapter list view to only update the chapter list. This would basically achieve the same result. Something like the circular arrow ↻ that is on the top right corner of the Updates screen could be added to the chapter list screen that would only update the chapter list for that title. In hindsight his method is probably a lot more reasonable than my original ideas.

I believe this would also benefit other users since I have spoken with several people who have the same issue with not being to find a title in their library because they are expecting to see a different cover image.

Another benefit here is for the sources themselves as people I have talked to will update the category or their whole library when they get a notification on Discord for example for a new chapter release. They do this instead of a manual update of that title because they don't want to deal with the cover image changing.

I sincerely wish you would reconsider as there are potential benefits to both users and sources by adding this functionality.

**Comment by alessandrojean** [comment]
Can't you just use the MangaDex extension setting to prefer using first volume covers instead? In that way they will never change. After applying the setting, just refresh the entries or do a library update if you have the "update metadata" setting checked as well.

**Comment by AgentX2006** [comment]
> Can't you just use the MangaDex extension setting to prefer using first volume covers instead? In that way they will never change. After applying the setting, just refresh the entries or do a library update if you have the "update metadata" setting checked as well.

I didn't even know that setting existed. This will help greatly thank you very much.
