### ISSUE TITLE
Mark series as read

### ISSUE THREAD

**Issue by walksanatora** [tachiyomiorg/tachiyomi#8987]
### Describe your suggested feature

A option in the ... menue on the chapter select screen that allows you to mark all as read
For if you were up to date on a series

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
The already existing options (shown below) should be sufficient really

![image](https://user-images.githubusercontent.com/72807749/214731878-d9dd7581-bc4c-4c1e-9afe-e0344761e35f.png)

**Comment by walksanatora** [comment]
Okay,didn't notice it because it was behind a hold-tap
