### ISSUE TITLE
Random crash when start/resume or chapter is clicked

### ISSUE THREAD

**Issue by Sliverin** [tachiyomiorg/tachiyomi#8990]
### Steps to reproduce

1. Open app 
2. Click on a manga to read
3. Tap the start/resume button or individual chapter 
4. Crash

### Expected behavior

The chapter should load without crashing.

### Actual behavior

The app crashes instead.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10514304/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.3

### Android version

9

### Device

Fire HD 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
01-26 15:08:28.166  1572  1572 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 951420 bytes
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6769)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 951420 bytes
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1129)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4027)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
01-26 15:08:28.166  1572  1572 E AndroidRuntime: 	... 7 more
```

**Comment by arkon** [comment]
Does this still happen in 0.14.4? If so, do you have newer crash logs to share?

**Comment by GustavoRamos112** [comment]
Ok, yes, this has been happening since I updated to 1.14.4, and it only happens when I'm not connected to a network or mobile data

**Comment by arkon** [comment]
Update your extensions.
