### ISSUE TITLE
Local Manga can't showing the details.json

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8993]
### Steps to reproduce

Add a random manga on local
Local only show the thumbnail

### Expected behavior

Details.json can be read on Tachiyomi 

### Actual behavior

Detail.json can't showing 

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Realme 7i

### Other details

![Screenshot_2023-01-28-12-14-29-43_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/215243621-58d8b9ac-9d99-472b-849f-b6468d6d3576.jpg)
![Screenshot_2023-01-28-12-14-40-10_6286c9febaeca36e51a6f011164cd2e8](https://user-images.githubusercontent.com/50316075/215243634-5f41b092-bb2c-4978-a1bc-14923d9c07d8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Shamicen** [comment]
Double quotes must be escaped with a backslash like this : `\"`

for example instead of `"Chika"` it should be `\"Chika\"`

Please escape all double quotes in your description and try again

**Comment by AntsyLich** [comment]
You can also use https://tachi-local.netlify.app/

**Comment by TheKingTermux** [comment]
> Double quotes must be escaped with a backslash like this: `\"`
> 
> for example instead of `"Chika"` it should be `\"Chika\"`
> 
> Please escape all double quotes in your description and try again

Alright thanks
I Will try it

**Comment by TheKingTermux** [comment]
> You can also use https://tachi-local.netlify.app/

Thanks
