### ISSUE TITLE
Random crash while restoring a backup (from another device)

### ISSUE THREAD

**Issue by CedMIX-Productions** [tachiyomiorg/tachiyomi#8994]
### Steps to reproduce

1. Create a backup from the previous device (More -> Backup and Restore -> Create backup)
2. Restore the backup to another device [using the same backup from previous device]  (More -> Backup and Restore -> Restore backup)
3. One or two things will happen:
A. The restore is successful (no problems here)
B. Somewhere in the process, it immediately crashes the app.

### Expected behavior

The restore should be completed without crashing the app as a whole.

### Actual behavior

It crashed midway while restoring a backup.

### Crash logs

Crash log dump:
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10525566/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Realme 6i (RMX2040)

### Other details

- The backup I created doesn't include tracking and I have the same set of extensions from both devices.
- For some reason, the restore confirmation isn't there anymore (the thing that checks to install the necessary extensions, not signed in to a tracker).
- I created multiple backups just in case it goes wrong:
1. Previous Backup (with tracker stuff):
[tachiyomi_2023-01-06_19-55.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10525894/tachiyomi_2023-01-06_19-55.proto.gz)
This backup contains:
- Usual updates and new entries to the usual source/extension.
- This one has one tracker logged in.

2. Current Backup (without tracker stuff): 
[tachiyomi_2023-01-27_15-45.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10525911/tachiyomi_2023-01-27_15-45.proto.gz)
This backup contains:
- A new extension added
- Migrated some entries to the new source
- Additional updates and new entries to the usual source/extension
- Excluded tracking in the backup options 
- The target device doesn't have a tracker logged in while the other device is logged in.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Crash logs is empty, so can't tell what happened.

Since you're using a Xiaomi device:

> Issues with Tachiyomi when using MIUI
> 
> Tachiyomi encounters a variety of issues when a user uses MIUI due to Xiaomi's nonstandard practices.
> 
> MIUI is extremely aggressive about killing apps in the background. Go [here](https://dontkillmyapp.com/xiaomi) to learn how to reduce the chances of Tachiyomi being killed in the background.
> 
> MIUI Optimizations
> 
> Use a non-default file manager when restoring backups, do NOT use MIUI's file manager. Switch MIUI Optimizations under Developer Settings to ON when restoring backups as well.
> 
> Switch MIUI Optimizations under Developer Settings to OFF when installing extensions or updates to extensions. Alternatively, manually download updates from [here](https://tachiyomi.org/extensions/).
