### ISSUE TITLE
Adding merge option

### ISSUE THREAD

**Issue by Winner875** [tachiyomiorg/tachiyomi#9000]
### Describe your suggested feature

Adding merge option to add two manga sources would be good for sources that the chapters are not complete like mangadex please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
See #8457 and #8753
