### ISSUE TITLE
update 14.3 broke some "selection" keyboard behavior (shift+arrow)

### ISSUE THREAD

**Issue by SailorVickFGC** [tachiyomiorg/tachiyomi#9009]
### Steps to reproduce

1. click on the title of a manga (any keyboard input work, titles are better for demonstration)
2. hold shift & press left or right arrow
※. ctrl+shift+arrows used to also select a whole word

### Expected behavior

Normally it'd create a selection.

Also "Select all (ctrl+A)" then Shift+left/right, would:
1. select all
2. start deselecting from the start or end while keeping the selection.

### Actual behavior

Now it doesn't create a selection.
Select All then shift+arrows deselects everything before moving the cursor 

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Galaxy Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The behavior is from Jetpack Compose. If it changes upstream, we'll automatically get any changes to it. We otherwise don't have control over it, so I'm going to close this since it isn't actually actionable on our end beyond using newer versions of Compose as they come out.

**Comment by SailorVickFGC** [comment]
What's Jetpack compose? 🤔 
I didn't update any keyboard app or anything, and it was working on the same day before the Tachiyomi upgrade :/

**Comment by arkon** [comment]
It's the UI framework that most of the app was rewritten with.
