### ISSUE TITLE
Flaresolverr support

### ISSUE THREAD

**Issue by Cissoubaka** [tachiyomiorg/tachiyomi#9012]
### Describe your suggested feature

Could you add support for flaresolverr to bypass all cloudflare protected site 

[https://github.com/FlareSolverr/FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The obvious answer would be no because none of that runs in the context of an Android app.

If someone wants to grok through how it does things and reimplement it, then feel free to try that.

**Comment by Cissoubaka** [comment]
I just wanted to add support for flaresolverr as a proxy, not integrate it in tachiyomi
