### ISSUE TITLE
If app fails to connect to a source with multiple "subsources", skip or lower the time-out of trying to connect to the other "subsources"

### ISSUE THREAD

**Issue by ElusiveEllie** [tachiyomiorg/tachiyomi#9017]
### Describe your suggested feature

For example, the source for Dynasty-Scans has 5 "subsources" (I'm not sure what the specific terminology is): Dynasty-Anthologies, Dynasty-Chapters, Dynasty-Doujins, Dynasty-Issues, and Dynasty-Series. At the moment of this post, Dynasty-Scans appears to be down, so when the app tries to connect, it times out after 30000ms. However, because there are five of these subsources, even though they are all from the same source, the app attempts to connect to each one and takes another 30000ms to fail. This results in the app taking two and a half minutes to move on past Dynasty when searching globally for a manga, which, since Dynasty is high up in the alphabet, results in a VERY long search time.

My suggestion is to, if the app fails to connect to a subsource, it skips attempting to connect to the remaining subsources, or at least the time-out for each one is lessened so that global searches aren't as dramatically impacted.

Here is a screenshot of the particular issue (I've covered up IP addresses and port numbers). Each one of these took 30000ms to complete before the search moved on to the rest of the sources in the global search.
![Screenshot_20230203_112541_Tachiyomi](https://user-images.githubusercontent.com/8885581/216657709-cdc58e2a-e8c4-4858-99b3-ca2a39f6e1d3.png)

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Parallel global search will come back in the next version so the app will do 5 sources at the same time, see #8906.

Your suggestion is not feasible technically as the app can't control the web client behavior of the extension.
