### ISSUE TITLE
Download Queue stays paused. When "Resume" gets clicked it doesn't do any effect.

### ISSUE THREAD

**Issue by Fre148** [tachiyomiorg/tachiyomi#9022]
### Steps to reproduce

1. Open Tachiyomi
2. Add/Select any Manga from any source (I've tried batoto, manganato, Webtoons, ComicK, MangaDex, Mangabuddy).
3. Click the download icon next to one of the chapters or the download icon in top of the screen. Select chapters.
4. Download icon animation starts.
5. Go to Download Queue on "more" > "Download Queue"
6. Try to resume.
7. Problem encountered.

### Expected behavior

Chapters should download and the queue should get resumed.

### Actual behavior

No chapters are downloaded and queue gets paused forever.

### Tachiyomi version

0.14.3

### Android version

Android 13 De-Googled

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by flflow** [comment]
Same problem.

**Comment by talhamantam** [comment]
same happens to me

**Comment by stevenyomi** [comment]
Ref #7492

**Comment by arkon** [comment]
Merging with #7492
