### ISSUE TITLE
extract metadata for each manga from library from their correspond sources

### ISSUE THREAD

**Issue by yooman1213** [tachiyomiorg/tachiyomi#9023]
### Describe your suggested feature

added extract metadata to their downloaded folder called "extract info" a feature on the three dot upon selecting a manga from library

### Other details

just like jellyfin can save nfo file to each media folder

but instead the output file is in comicinfo.xml or .json file

this could be very beneficial to user who want to migrating to private cloud services

thanks in advance. and please make it happen

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The generation of ComicInfo.xml on chapter download is supported but disabled for now due to #8537

**Comment by yooman1213** [comment]
I tried this on r5202 (my assumption for comicinfo.xml still enable)

On nhentai source it didn't have the file

Can i ask for this to be implemented on specific sources?

Currently i want to migrate to private open source services i.e komga but i need the metadata for each library
