### ISSUE TITLE
LAGGING While scrolling in catergory or between category

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi#9027]
### Steps to reproduce

Fps drop when at homepage, scrolling through manga.
The lag stop when i click into manga to read. 
Happens only at homepage catergory page

### Expected behavior

Smooth while scrolling and finding manga

### Actual behavior

This happens in extension too, not only favourited manga.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Device

Samsung galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mrabetto** [comment]
I had similar issues two or three versions now, but I thought it was due to my relatively old and weak device

**Comment by Bishopop6** [comment]
I dont think its the device, my phone may not be new but it has enough
capacity to support it.

My old phone samsung galaxy note 5 is working fine and there was no lag
between switching and scrolling category.

Is there a possibility that there are too much save manga in tachiyomi
itself causing the lag?

It was working fine in the morning, but after i updated my phone in the
afternoon, and reboot my phone, the lagness comes in.

I tried reinstalling it, clearing the cache, increasing more storage space,
clearing more ram but it is still lagging.

**Comment by alessandrojean** [comment]
You need to give your phone some time to it optimize the app. Keep using it and eventually it will be like it was before.

**Comment by Mrabetto** [comment]
It had enough time for me and the issue still persisted can you please look it up.
