### ISSUE TITLE
Long press to download or delete chapters

### ISSUE THREAD

**Issue by Mrabetto** [tachiyomiorg/tachiyomi#9028]
### Describe your suggested feature

I know the feature existed already, but I really liked using it, if possible could we bring it back as an optional behavior as it was very convenient 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Long press to download still exists. Long press to delete was removed cause many user misclicked into deleting chapters.

**Comment by Mrabetto** [comment]
I am aware it may have caused misclicks, what I am requesting is keeping it off by default while offering the option to enable it, it made downloads and delete easy and convenient right out of the box
