### ISSUE TITLE
Use tags to search in library section 

### ISSUE THREAD

**Issue by BertTooo** [tachiyomiorg/tachiyomi#9030]
### Describe your suggested feature

![image](https://user-images.githubusercontent.com/124504823/216819587-401145c4-d4ee-4c8b-ae76-9a5e36aa3700.png)
I will type one tag on the search bar and it will list all manga that has the same tag(s) in my library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Did you actually try searching before making a request?
