### ISSUE TITLE
Continue reading button scaling 

### ISSUE THREAD

**Issue by BartoszStrehlau** [tachiyomiorg/tachiyomi#9031]
### Describe your suggested feature

Main Tachi implemented a continue reading button, sadly it doesn't scale with grid.

I myself use 6x6 grid and with the button enabled - which i love it covers the whole thumbnail 
![Screenshot](https://user-images.githubusercontent.com/62762388/216829735-03df2d4a-24b3-44ef-bc28-17267c1bd7c4.png)

### Other details

Iam usinf sy fork but it is main tachi issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Apparently SY's version was just smaller and didn't do anything to scale with the number of columns. This one's intended to be more tappable.
