### ISSUE TITLE
Skip manga on update if newest chapter was X days ago

### ISSUE THREAD

**Issue by Amejonah1200** [tachiyomiorg/tachiyomi#9032]
### Describe your suggested feature

Basically, an additional skip parameter: cooldown. Most of the time, when dealing with a huge amount of entries, especially if they are not releasing on the same day, you end up updating everything even if the last chapter released yesterday. So it would be a good feature to allow to set a specific time needed before the entry will be scanned again.
Example:
You have 10 entries: 5 released yesterday and 3 5 days ago and the other ones 7 days ago. You set the time to 6 days. So it will skip the 8 which are being updated too recently and update only the oldest 2 ones.

**Comment by arkon** [comment]
Duplicate of #6154
