### ISSUE TITLE
Add it back

### ISSUE THREAD

**Issue by IceEnderman** [tachiyomiorg/tachiyomi#9034]
### Describe your suggested feature

Please enable the ability to hide unread chapter badges in library, why was it remuved ?

### Other details

wost change

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Read them or mark them as read to hide the badge.

**Comment by IceEnderman** [comment]
Why not let the user have the choice ?
