### ISSUE TITLE
MangaHub keep showing Retry and page not found

### ISSUE THREAD

**Issue by ansanyyi** [tachiyomiorg/tachiyomi#9036]
### Steps to reproduce

![Screenshot_2023-02-06-09-27-54-373_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/110255796/216861648-de0a9de1-cdff-48e3-beeb-8bb88d49f40d.jpg)

### Expected behavior

it should show image

### Actual behavior

The retry button show after every page

### Tachiyomi version

0.14.4

### Android version

Android 11

### Device

Redmi 10c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
