### ISSUE TITLE
Loading downloaded manga is significantly slower

### ISSUE THREAD

**Issue by AnotherObligation** [tachiyomiorg/tachiyomi#9038]
### Steps to reproduce

1. Open app
2. Wait

### Expected behavior

Should be able to read downloaded manga within 5 seconds like previous version 0.13.6

### Actual behavior

Downloaded manga now take 30+ seconds to load

### Tachiyomi version

0.14.4

### Android version

13

### Device

Galaxy S20

### Other details

On version 0.13.6 when I would open the app it would show a splash screen for ~5 seconds (where I assume the indexing was happening before) and then I would be able to use the app and read all downloads. Now the app opens immediately but will index the downloads for 30+ seconds before being able to read them. Even when the downloaded only filter is on my library is completely empty until all the downloads are loaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by talhamantam** [comment]
same happens to me

**Comment by Leukos8** [comment]
Same here:
Android 13
Tach version : stable 0.14.5
Device : Fairphone 4

The type of file uploaded (png or cbz) has no impact. We can notice a delay starting from a hundred of downloaded chapters (internal storage). If the files are downloaded on a SD card, it seems to be a bit slower. Need more tests.

The main problem is that it refreshes the download index every time I open the application (30 seconds).

**Comment by arkon** [comment]
Download index is cached in newer preview builds.
