### ISSUE TITLE
TachiyomiSY: Mass Migrate Error

### ISSUE THREAD

**Issue by JOZU101** [tachiyomiorg/tachiyomi#9039]
### Steps to reproduce

1. Open tachiyomiSY
2. Try to migate to any other extension
3. Take to much time fo load
4. Crash suddenly 

### Expected behavior

Normally you can mass migrate to other extension 

### Actual behavior

![inbound8723546555398635412](https://user-images.githubusercontent.com/124290733/216924344-c5108fee-9696-47f1-b3f0-55f5d4351c7b.jpg)

### Crash logs

--------- beginning of system
--------- beginning of crash
02-06 16:29:07.743 10167 10167 E AndroidRuntime: FATAL EXCEPTION: main
02-06 16:29:07.743 10167 10167 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 10167
02-06 16:29:07.743 10167 10167 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.compose.runtime.SnapshotMutableStateImpl.getValue()' on a null object reference
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.migration.advanced.process.MigrationListScreen.Content(MigrationListScreen.kt:231)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.transitions.ComposableSingletons$ScreenTransitionKt$lambda-2$1.invoke(ScreenTransition.kt:26)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:46)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3$1.invoke(ScreenTransition.kt:45)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:125)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:43)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.navigator.Navigator.saveableState(Navigator.kt:207)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3.invoke(ScreenTransition.kt:57)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:46)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:94)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:1969)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:38)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:226)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:148)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at cafe.adriel.voyager.transitions.ScreenTransitionKt.ScreenTransition(ScreenTransition.kt:197)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at eu.kanade.presentation.util.NavigatorKt.DefaultNavigatorScreenTransition(Navigator.kt:135)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity$onCreate$2$3$3.invoke(MainActivity.kt:210)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at eu.kanade.presentation.components.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:172)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:61)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:23)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:127)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:23)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:15)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:18)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:121)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:139)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at eu.kanade.presentation.components.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:876)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:40)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:9)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:63)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:135)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:127)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:33)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:20)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:70)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:33)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:46)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:25)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:40)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:63)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:135)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:127)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:51)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:18)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:40)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:45)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:37)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:31)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:70)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer$default(Placeable.kt:109)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.RootMeasurePolicy$measure$2.invoke(RootMeasurePolicy.kt:11)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:40)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:63)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:135)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:127)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:33)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:20)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:77)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:19)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:70)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:50)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:103)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:195)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:69)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onLayout(AndroidComposeView.android.kt:5)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.internalOnLayout$ui_release(ComposeView.android.kt:28)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.onLayout(ComposeView.android.kt:1)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.View.layout(View.java:23059)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6479)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3622)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3082)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2075)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8512)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:826)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8056)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-06 16:29:07.743 10167 10167 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
--------- beginning of main
App version: 1.9.0 (standard, d24a8d2, 46, 2023-02-04T23:26Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

### Tachiyomi version

1.9.0

### Android version

Android 11

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This isn't the TachiyomiSY repository
