### ISSUE TITLE
Fast scrolling issues in Library and Settings

### ISSUE THREAD

**Issue by kolorafa** [tachiyomiorg/tachiyomi#9041]
### Steps to reproduce

Example
1. Open Library
2. Do a Swipe Up over whole screen to scroll quickly down
3. The Libraries jump back to the top

Same with scrolling back up, it keeps fighting with user and going back.

Same bad jumpy behavior also in Settings. I want to scroll down to About or up to General, and it keeps getting back hiding those first/last elements...

### Expected behavior

The scroll keeps scrolling with the same speed it was while putting into mottion and slowly stopping - aka behavior before update into 0.14.4

### Actual behavior

The scroll keeps going backwards, even more that it was started from.

So you start with having 3-4 manga on the line second line in Library, you quick swipe down to quickly scroll down so you want to go to 9-10 manga below, and you get back to 1-2 manga ...

### Crash logs

No crashes.

### Tachiyomi version

0.14.4

### Android version

Android 9

### Device

Moto Z3 Play

### Other details

Video: https://nextcloud.dlk.pl/s/EJyd7pP3CHwaMF4

1. First - trying to scroll up to General, but it keeps getting hidden.
2. Later - trying to scroll down to about and it keeps getting hidden.
3. Lastly going to Library and trying to do a scroll down and it keeps going back to the starting point.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kolorafa** [comment]
Somehow I did a fresh install on my second phone (same model and Os version) and the issue is not present there.
Going to do a backup and do a fresh install on this phone with issue, as I did compare settings to the fresh one and didn't see any differences.

**Comment by kolorafa** [comment]
Dane clean reinstall on both, on one phone it's buggy, on second works perfectly normal as expected.

On 2 phones
- Device Model
- OS versin and Build
- The same Tachiyomi APK file version
- The same Tachiyomi settings (even uninstalled extensions and done a data wipe)

One device is fine, while on second scroll behave just wrong :/
Some hidden app responsible for UI got updated silently on one of the phone? 
I'm out of ideas what is the cause of it :(

**Comment by kolorafa** [comment]
No scroll issues on 0.13.6, 0.14.0, 0.14.1, 0.14.2, 0.14.3
Scroll issues preset on 0.14.4

**Comment by kolorafa** [comment]
Found out second app that behave the same - Google Play.
On good phone - scroll is fine as expected, you can quickly scroll.
On bad phone - scroll instantly bounces back whenever you rise your finger, so you can't just quickly scroll to top.
Google had to put some background update to UI components :-1:

**Comment by arkon** [comment]
Probably an upstream Compose issue. If future versions of it fixes it, you'll see it in future versions of the app.
