### ISSUE TITLE
Some unread chapters are visually grayed out

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi#9043]
### Steps to reproduce

1. Open a manga with at least 50 chapters.
2. Mark first half as read.
3.1. Scroll between read and unread chapters.
3.2. Or just open the manga and start scrolling down.

### Expected behavior

Unread chapters are displayed as unread.

### Actual behavior

Some chapter names for unread chapters are grayed out, while uploads dates are not.

### Crash logs

Crash log is empty, contains only device info

### Tachiyomi version

0.14.4

### Android version

Android 12 (MIUI 13)

### Device

Redmi 10C

### Other details

- There was another person on discord with the same issue on Samsung ([link](https://discord.com/channels/349436576037732353/349436576037732355/1072355989988323369) to discord message).
- I couldn't reproduce the bug when all chapters are unread.
- I couldn't find how exactly you need to scroll to reproduce, but it happens after enough tries.
- Scrolling the chapter away and then scrolling back to it temporarily resolves the issue (but sometimes other chapters may turn out grayed out).
- Reopening the manga page temporarily resolves the issue.
- Marking the chapter as read and then as unread temporarily resolves the issue.

<details>
  <summary>Screenshots of the issue</summary>
  
![](https://media.discordapp.net/attachments/349436576037732355/1071107703356805160/Screenshot_20230203_103921_Tachiyomi.jpg)
![IMG_20230206_191635](https://user-images.githubusercontent.com/65343233/217142993-8c6989f4-fca8-469c-b425-86e5e5cae54e.jpg)
  
</details>

<details>
  <summary>Video with the bug</summary>

00:00-00:24 - the bug
00:29 - the bug disappears after scrolling
00:30-01:40 - trying to reproduce the bug with no luck
01:41-01:50 - the bug
01:50-01:55 - the bug disappears after marking the chapter as read and then as unread

https://user-images.githubusercontent.com/65343233/217144272-3fcfe18f-26ab-4ded-a4ef-9ef1778a60a2.mp4

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Found one more [case](https://discord.com/channels/349436576037732353/349436576037732355/1071935645846605835) on Discord, but the user says that marking read-unread doesn't help

> Even when I mark the chapters in question as read then unread, the chapter numbers are still grayed out.

**Comment by scb261** [comment]
Tested with a few more themes:

- Dark, Tako
- Dark, Default
- Light, Default
- Pure black, Default

Reproduced with all of those.

![IMG_20230209_072735.jpg](https://user-images.githubusercontent.com/65343233/217726281-f7cf600b-0552-4672-9e4f-16c120f89811.jpg)

**Comment by scb261** [comment]
Figured a reliable way to reproduce (at least on my device): scroll from unread to read chapters, and then quickly scroll back a little bit

https://user-images.githubusercontent.com/65343233/217730314-ca728c5e-8d69-4982-9b8e-e141197f5536.mp4

**Comment by VirusEcks** [comment]
Uploading Screenrecorder-2023-02-11-01-23-36-402.mp4…

**Comment by scb261** [comment]
Just tried with r5513. Still happens, bff98c didn't help

**Comment by sillysack69** [comment]
Was about to report this bug myself but fortunately saw this ticket was already opened

**Comment by TheKingTermux** [comment]
Yeah itu still happen in latest version

**Comment by CodeSpoof** [comment]
Happens also in the New tab sometimes when you switch to it.

**Comment by arkon** [comment]
Is this still happening?

**Comment by scb261** [comment]
r5620, can't reproduce anymore. Looks like e458de5 fixed the issue
