### ISSUE TITLE
Can't Download Comics chapters using Mobile Data

### ISSUE THREAD

**Issue by Ineedmoremanga** [tachiyomiorg/tachiyomi#9045]
### Steps to reproduce

I recently get a new phone and so i download tachiyomi and transferred all my Comics

Its good but after a week i found an error i tried to download new chapters using Mobiledata but it didnt work for some reasons i tried to restarr my phone and delete cache but it still didnt work

And i cant read normal chapters too 

### Expected behavior

Idk what to expect but i just want it to be back normal :) 

I already do the settings for the Wifi Only (Off)

### Actual behavior

Yep it didnt work even after restarting my phone

### Tachiyomi version

0.14.4

### Android version

Android 12

### Device

OPPO 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please consult the troubleshooting guide and/or Discord for help with basic networking issues.
