### ISSUE TITLE
App FC when reading downloaded without internet

### ISSUE THREAD

**Issue by AnonimpersonJR** [tachiyomiorg/tachiyomi#9055]
### Steps to reproduce

1.with the wifi off or without internet connection you open the app.

2.When you try to read downloaded chapters the app closes itself.

Video reference: https://drive.google.com/file/d/1BS4iJGYxWGVKtVxFRs4XTvKUSlP7mAe5/view?usp=drivesdk

### Expected behavior

You can read downloaded chapters even without internet connection 

### Actual behavior

App closes itself 

### Crash logs

None (or doesn't show any)

### Tachiyomi version

0.14.4 (standard, 477e3d9, 95, 2023-02-05T15:37Z)

### Android version

10 (SDK 29)

### Device

Samsung galaxy A7 (2018)

### Other details

The downloads are saved only on phone memory, not external memory.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Update your extensions, this is already fixed.
