### ISSUE TITLE
Scrolling the library is way too resource hungry

### ISSUE THREAD

**Issue by tk2p** [tachiyomiorg/tachiyomi#9057]
### Steps to reproduce

1. Use an older device or underclock your CPU (even at 100% my 732g feels sluggish in tachiyomi, this doesn't happen in even apps made in hell such as Instagram and Twitter)
2. Scroll the library or updates in general 

### Expected behavior

It should be *smooth*(er)

### Actual behavior

It's laggy and sluggish

### Tachiyomi version

0.14.4

### Android version

Android 13

### Device

Poco X3

### Other details

Full CPU power (still lags):
![Screenshot_20230208-171816_Tachiyomi](https://user-images.githubusercontent.com/105242066/217588103-0c5c54a3-7314-4324-9f9c-2b3f01b35083.png)

Limited
![Screenshot_20230208-171149_Tachiyomi](https://user-images.githubusercontent.com/105242066/217586863-565fe22c-ece9-44a0-ac1d-228e1c57dc66.png)
Lags twice as much

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This happens because your device haven't optimized the app yet. Give it some time and it will eventually be like before.

**Comment by tk2p** [comment]
> This happens because your device haven't optimized the app yet. Give it some time and it will eventually be like before.

Thanks, I ran the optimizations myself,

https://github.com/tachiyomiorg/website/pull/998#issue-1577945526
@alessandrojean the
