### ISSUE TITLE
Scrolling i.e next page action or swiping though pages while reading is very stuttery

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi#9060]
### Steps to reproduce

1. open the app and select any manga chapter
2. scroll through the pages with swiping motions with your finger from page 1 to the chapter transition in horizontal reading mode

### Expected behavior

Silky smooth scroll like version 0.13.x.

### Actual behavior

Opening up any manga chapter in online mode and then scrolling through it especially in horizontal mode (left to right) gets progressively less and less smooth as the pages go by, becoming especially jerky and stuttery at the last few pages and the chapter transition. After the transition, the scrolling gets smoother again. Also, in the older versions prior to 0.14.x, the scrolling was seamless and silky smooth. Even though I'm complaining about the last few pages being stuttery, in truth, the baseline for the seamless scrolling pages has taken a nose dive. I don't know if it's just that tachiyomi has gotten less optimzed or my device is slow.

### Tachiyomi version

0.14.4

### Android version

Android 8

### Device

Samsung Galaxy S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Jacosci** [comment]
I've been experiencing this too since v0.14.0. But every issue report had been closed without further investigation.

Hopefully it will be different this time around because it feels like it's only getting worse. The latest v0.14.4 is just simply a stuttery fest for me.

**Comment by ARPIT5257G** [comment]
Well there's a option of another reading option - 'webtoon'.
It will make all the page verticallly scrollable,you can go to setting>reader>deafault reading mode

**Comment by sillysack69** [comment]
> Well there's a option of another reading option - 'webtoon'. It will make all the page verticallly scrollable,you can go to setting>reader>deafault reading mode

@ARPIT5257G that's not really a solution. Plus I hate reading manga like that. Better fix the problem now than let it fester I say. Also defeats the whole point of they app of being a manga reader right? Might as well just open up the camera gallery and read like that at that point
