### ISSUE TITLE
Automatic download if chapter is the 'next' latest chapter

### ISSUE THREAD

**Issue by chcoomilk** [tachiyomiorg/tachiyomi#9069]
### Describe your suggested feature

Currently the app will automatically download whenever there are new chapters from source. This includes 50 chapter old extras that just got added in recent times, which doesn't technically count as a "new" chapter. It might be great for the users and the sources/providers (possible bandwidth save) if there's an option to automatically download if the new updated chapters are the next to current chapter, and don't download if they are past chapters that are just newly added now

### Other details

Imma be blunt, I just got like 10 One Punch Man extras from 2 manga sources (just in case if 1 missed an update) from chapter 106 (~70 chapters away from the current chapter); that's like 2 years old. I was like, I don't remember what was the running gag 2 years ago.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#4316
