### ISSUE TITLE
SelectionContainer toolbar remains visible after disposal

### ISSUE THREAD

**Issue by roiiiu** [tachiyomiorg/tachiyomi#9073]
### Steps to reproduce

1.long press text
2.return to previous page

### Expected behavior

the button won't disapper and stack in top left of screen

### Actual behavior

 

https://user-images.githubusercontent.com/11494827/218329235-daa68b70-bb94-4246-83eb-2f641d215ae1.mp4

### Tachiyomi version

0.14.4

### Android version

Android13

### Device

One plus 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by strangeirdo** [comment]
as a somewhat fix, going to the search page, either through searching or clicking on a title, gets rid of the button, in my experience.

**Comment by arkon** [comment]
Seems to have been fixed in a recent Compose upgrade.
