### ISSUE TITLE
Unable to download the whole chapter because a single or few pages cannot be downloaded

### ISSUE THREAD

**Issue by ReedMan07** [tachiyomiorg/tachiyomi#9076]
### Describe your suggested feature

Downloading a whole chapter (ex. E-Hentai chapter/ 1 chapter compilations) it does not finish downloading even if one page could not be downloaded. It should be able to skip pages with error or those that cannot be downloaded and still download the other available pages and give it offline access. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3957
