### ISSUE TITLE
Lock Button

### ISSUE THREAD

**Issue by frzaaa** [tachiyomiorg/tachiyomi#9077]
### Describe your suggested feature

When I read a webtoon style manhwa, it's annoying to accidentally touch the screen and the menu pops up. please add a Lock button, like the lock button when you watch a video.
![Screenshot_20230213-115842](https://user-images.githubusercontent.com/125238685/218374349-2890485a-eabc-4919-934e-222934e0321e.jpg)
 Thanks

### Other details

![Screenshot_20230213-115849](https://user-images.githubusercontent.com/125238685/218374354-632ec956-20c0-4063-947e-94403d0a81bb.jpg)
Example of the Lock button 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This doesn't make any sense for a reading app that you'd need to interact with to navigate through pages.
