### ISSUE TITLE
Tachiyomi refuses to display anything

### ISSUE THREAD

**Issue by TadaCZE** [tachiyomiorg/tachiyomi#9079]
### Steps to reproduce

1. Install Tachiyomi
2. Try to open it

### Expected behavior

The app should have opened normally

### Actual behavior

The app does "open", but nothing gets displayed in a weird activity opening loop, see video:

https://user-images.githubusercontent.com/33400123/218433069-5596178e-dc12-43f9-b464-33a47dfbb4d0.mp4

### Tachiyomi version

0.14.4, r5513 (both preview and stable exhibit this issue)

### Android version

Android 13 (crDroid 9.1 on chime)

### Device

POCO M3 (M2010J19CG)

### Other details

I have an identical phone with crDroid 8 (android 12) without gapps (but with microg) which works perfectly. This phone doesn't have gapps at all. It's also rooted with Magisk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You might be missing a proper system WebView installation.

**Comment by TadaCZE** [comment]
I don't believe I am, I have tried an another program depending on webview and it works normally. And in developer settings the android system webview is present and selected.

**Comment by TadaCZE** [comment]
![Screenshot_20230215-104400_Nastavení](https://user-images.githubusercontent.com/33400123/218991741-b3c6ed03-9c45-4d30-a54b-b1cf5d9f69e2.png)

**Comment by arkon** [comment]
Hard to say then. You're on your own if using a non-OEM setup.

**Comment by TadaCZE** [comment]
Status update, Tachiyomi started displaying an actual error message in a chaotic way:


https://user-images.githubusercontent.com/33400123/219319825-1abcd042-fc18-40d5-8566-2a1946a223b6.mp4

**Comment by stevenyomi** [comment]
```
java.lang.Throwable: java.lang.IllegalArgumentException:
Tried to schedule job for non-existent component:
ComponentInfo{eu.kanade.tachiyomi/org.arca.sender.JobSenderService}
at android.os.Parcel.createExceptionOrNull(Parcel.java:3032)
at android.os.Parcel.createException(Parcel.java:3012)
at android.os.Parcel.readException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2937)
at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:263)
at android.app.JobSchedulerImpI.schedule(JobSchedulerImpl.java:47)
at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:406)
at org.acra.scheduIer.Schedu.erStarter.scheduleReports(Schedu.erStarter.kt:59)
at org.acra.startup.StartupProcessorExecutor.$r8$lambda$w9xmu15QlkMysmMuGxOzyJPdflo(StartupProcessorExecutor.kt:289)
at org.acra.startup.StartupProcessorExecutor$
```

**Comment by arkon** [comment]
https://github.com/ACRA/acra/issues/804

Sounds like something that affects MIUI but somehow also your ROM. If it really is something selinux related, then it's an issue at the kernel level on your device.

**Comment by TadaCZE** [comment]
Well, I will just say that my selinux was pernissive and this still occured, but this really sounds like a me problem not a Tachiyomi problem. But thanks for the help.
