### ISSUE TITLE
Unable to read downloaded chapters offline 

### ISSUE THREAD

**Issue by alexysuki** [tachiyomiorg/tachiyomi#9082]
### Steps to reproduce

When I read a downloaded manga without an Internet connection, the app closes itself. 

### Expected behavior

I hope I can read the downloaded chapters even if I don't have a connection. 

### Actual behavior

Every time I try to read a downloaded chapter of a Manga, the application closes itself. But when I do have an Internet connection, I can read the downloaded manga. 

### Tachiyomi version

0.14.4

### Android version

Android 12

### Device

Huawei Mate 20 lite 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Is this on TuMangaOnline or LectorManga? If yes, update your extensions.

**Comment by alexysuki** [comment]
Thanks for the help :D

Alessandro Jean ***@***.***> 于2023年2月13日周一 16:08写道：
