### ISSUE TITLE
Using the "Latest" feature lead to force close

### ISSUE THREAD

**Issue by Azerzra** [tachiyomiorg/tachiyomi#9084]
### Steps to reproduce

A couple days ago i update my tachiyomi from 13.6 (i believe) to 14.0. It went fine for the first two day and even on this morning. I have also tried to update to 14.4 but it all went southway. The app want me to update all my extensions but nothing happens. 

### Expected behavior

Just this afternoon, i tried to use the latest feature on Mangadex and it immediately force close. However i can still read the manga. Weirdly enough, this only happens to mangadex English. There's nothing wrong with the Mangadex Indonesia. And before this issue i used the same feature on Mangabat and it was fine. A couple hours ago i tried it again on Mangabat and the same problem occurs. The app immediately force closed. 

### Actual behavior

Just this afternoon, i tried to use the latest feature on Mangadex and it immediately force close. However i can still read the manga. Weirdly enough, this only happens to mangadex English. There's nothing wrong with the Mangadex Indonesia. And before this issue i used the same feature on Mangabat and it was fine. A couple hours ago i tried it again on Mangabat and the same problem occurs. The app immediately force closed. 

### Tachiyomi version

0.14.0

### Android version

Android 10

### Device

Xiaomi mi 9

### Other details

I apologise for my bad English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please provide the requested crash logs as well.

More > Settings > Advanced > Dump crash logs

Then share the file here.

**Comment by Azerzra** [comment]
Hold on, i don't know much about how to share the file but i will try

[Tachiyomi_Crash_Logs](content://org.telegram.messenger.provider/media/Telegram/Telegram%20Documents/5_6291858777738054092.txt)

**Comment by Azerzra** [comment]
Is the file already attached?

**Comment by alessandrojean** [comment]
You need to upload the actual file, and not the location of it in your phone.

**Comment by Azerzra** [comment]
[1676307170251_1676307148014_tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10724408/1676307170251_1676307148014_tachiyomi_crash_logs.txt)

**Comment by Azerzra** [comment]
Is it already uploaded? I'm sorry i don't know much about github

**Comment by alessandrojean** [comment]
It is and it does contain one possible cause for a crash, now you need to wait to it get fixed.

**Comment by Two-Ai** [comment]
```
02-12 16:50:45.532 11127 11127 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type eu.kanade.tachiyomi.ui.browse.migration.search.SearchController
02-12 16:50:45.532 11127 11127 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.migration.search.SearchController$MigrationDialog.onCreateDialog(SearchController.kt:7)
```
Possibly caused by this unsafe cast?
https://github.com/tachiyomiorg/tachiyomi/blob/ebddb96373e08334c3e74b5027793308a85cb754/app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchController.kt#L104

However, `SearchController` was rewritten in https://github.com/tachiyomiorg/tachiyomi/commit/f99b62a069e8e987318a0144090560795d59e3ff, so the stack trace is no longer directly applicable to the latest version.

@Azerzra Did you get a similar crash when updating to 0.14.4?

**Comment by Azerzra** [comment]
@Two-Ai I didn't get to use the 14.4 properly. The moment i update it, tachi require me to update all my extension but i'm unable to update it. It always went back to the "install" button.

**Comment by arkon** [comment]
Please create another issue if it occurs in 0.14.4, and with actual reproduction steps detailed.
