### ISSUE TITLE
Issues with Updating Library after updating to 14.4

### ISSUE THREAD

**Issue by Biozoth** [tachiyomiorg/tachiyomi#9085]
### Steps to reproduce

Either waiting for library to update or manually pulling it down to update.

### Expected behavior

Normally takes about 5-10 minutes to update chapters.

### Actual behavior

Taking up 45 mins to an hour or more to update the few chapters.

### Tachiyomi version

0.14.4

### Android version

Android 13

### Device

Google Pixel 7 Pro

### Other details

![Screenshot_20230210-100459](https://user-images.githubusercontent.com/125300773/218534296-76ec48ec-7e57-420a-81f8-195d98c02149.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please refer to the troubleshooting guide. Update speed depends heavily on networking factors like the source and your connection to it.

If you have a more concrete issue to report, please create another issue.
