### ISSUE TITLE
Adding option to revert back to old UI for filtering manga.

### ISSUE THREAD

**Issue by Ink-1** [tachiyomiorg/tachiyomi#9088]
### Describe your suggested feature

I updated the app after nearly 1 year. Lot of things changed. The UI for filtering manga also changed. (Idk what to call it, it was this floating circle thing when clicked gave option to filter manga by toggling tags. Now there is "Latest" "Popular" and "filter" option at top. I used the old filter option a lot and dont really like this new UI so please add an option in Appearance settings to revert back to old UI for filter. The new UI makes me accidently press those latest and popular buttons when clicking the filter button resetting the mangas.

### Other details

![IMG_20230214_103111](https://user-images.githubusercontent.com/83633730/218642523-02559e7d-422b-4138-bb85-811e61597ef4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
Will not happen.
I can't see how this is an issue either?

**Comment by Ink-1** [comment]
Its an issue cuz it is too easy to touch Latest/popular when trying to
touch filter. If you cant add an option to change to old UI then can you at
least add a gap between "Popular,latest" and "Filter". Im sure many will
appreciate that.
