### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by Tolla28** [tachiyomiorg/tachiyomi#9093]
### Steps to reproduce

Example:
1. Open app
2. Then Choose something to read 
3. Open the manga you wanna read
4. While reading the app crashes and closes

### Expected behavior

Like the old one I wanna read without crashing

### Actual behavior

But it always crashes whenever I read after the update

### Crash logs

##{"pluginName":"crashsdk","pluginVersionName":"3.0.2","pluginVersionCode":302,"pluginBuildDate":"2018-08-20 10:10:30","pluginBuildCommitId":"a118e93","appPackageName":"com.bbk.account","appVersionName":"5.0.0.0","appVersionCode":"5000","clientDate":"2023-02-14 04:23:02","pluginBaseVersionName":"1.1.1"}

### Tachiyomi version

0.14.4

### Android version

Android 7.1.2

### Device

Vivo 1611

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Wrong crash logs, please upload the ones from Tachiyomi.
