### ISSUE TITLE
Search option for pages

### ISSUE THREAD

**Issue by Turhvjbufv** [tachiyomiorg/tachiyomi#9095]
### Describe your suggested feature

Add search optiom for number of pages, for example adding pages:>30 in search bar will display only m/m/m with more than 30 pages 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Why.

**Comment by Turhvjbufv** [comment]
> Why.

Let's say I want to read a long manga that's in my library it's an easier option to search for it instead of going one by one

**Comment by CrepeTF** [comment]
Just sort by total amount chapters which is already a thing?

Why by individual pages

**Comment by Turhvjbufv** [comment]
> Just sort by total amount chapters which is already a thing?
> 
> Why by individual pages

What about manga with long chapter but only a few of them?

**Comment by CrepeTF** [comment]
Then that would also trigger manhua or manhwa which usually have like 100 pages

**Comment by CrepeTF** [comment]
Checking for individual pages would also mean indexing the sites for every chapter of every series you have in your library which would be a ton of network calls

**Comment by CrepeTF** [comment]
Also sorting by total chapter will still get you long manga 95% of the time. And if you have to check each and every manga you have in your library then are you just adding stuff to your library which you haven't opened to check?

**Comment by arkon** [comment]
Wouldn't work unless everything's downloaded/indexed.
