### ISSUE TITLE
Custom Batch Download 

### ISSUE THREAD

**Issue by LSXAxeller** [tachiyomiorg/tachiyomi#9096]
### Describe your suggested feature

Since Custom Download support download a (X) number from chapters from the first chapter, can we get batch download chapters from specific chapter (X) to specific chapter (Y) not only from start or last read chapter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
You can do range select and download. Tap and hold (long press) a chapter then tap and hold another to select all between them.

**Comment by ghostbear** [comment]
Long press chapter X then long press chapter Y now you have done a range select of chapters then press download

**Comment by LSXAxeller** [comment]
Still long press and select a 100 or more chapters a time consuming task

**Comment by stevenyomi** [comment]
> Still long press and select a 100 or more chapters a time consuming task

Read our replies carefully. You long press on ***both ends*** to range select all between them. You don't need to select one by one.
