### ISSUE TITLE
Unable to bypass cloudfare protection 

### ISSUE THREAD

**Issue by malto101** [tachiyomiorg/tachiyomi#9099]
### Steps to reproduce

Open any extensions with has cloudfare protection

Or open webview of the extension 

### Expected behavior

Shows a text "unable to bypass cloudfare protection" in app
Keep reloading and stuck in the cloudfare protection screen on webview

### Actual behavior

Display all the manhwa

### Tachiyomi version

0.14.4

### Android version

Android 11

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
