### ISSUE TITLE
Sort by number of unread pages

### ISSUE THREAD

**Issue by Scaliasb** [tachiyomiorg/tachiyomi#9100]
### Describe your suggested feature

Allow to sort library by unread pages. That's all.

### Other details

Sometimes you want to finish a series, and it would be helpful to sort by shortest, and chapters aren't really telling of the length of a manga since they can be extremely variable (i.e. 4-komas that have only 1 page per chapter, or some mangas with 10 page chapters, while others have 30 or 40 per, and so on).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Same problem as #9095
