### ISSUE TITLE
Tachiyomi new manga into local and downloads folder do not appear

### ISSUE THREAD

**Issue by Aaveparthe** [tachiyomiorg/tachiyomi#9101]
### Steps to reproduce

1. Place new manga according the structure required through external drive (i.e. cable from PC to phone, "Tachiyomi" folder)
2. Open tachiyomi
3. Update library

### Expected behavior

Local and downloads manga in folder should appear after updating.

### Actual behavior

New manga don't appear.

### Tachiyomi version

0.14.4

### Android version

Android 12

### Device

TECNO Spark GO

### Other details

Downloading manga from within the app does have an appearance in the library tab, but whenever I try putting manga (according to the structure and rules), and updating, nothing new appears, as if the app doesn't recognize the files, regardless of naming or format.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
For local manga, please refer to this guide: https://tachiyomi.org/help/guides/local-manga/

For downloads, the names must match the library entry and chapters exactly.

For better assistance, please ask on Discord.
