### ISSUE TITLE
Tachiyomi crash when open/reading some manga/manhua/manhwa

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#9105]
### Steps to reproduce

Open tachiyomi
Open scylla extension
Read Webtoon character na Kang Lim

### Expected behavior

Ready to Read

### Actual behavior

Tachiyomi Force Close

### Crash logs

Crash Video

https://photos.app.goo.gl/jHy4ufCzJcPwBtiQ6

Tachiyomi Log

https://drive.google.com/file/d/1dBJ52hNW8xTzlK10hmYu6Y-O5RMoNJl9/view?usp=share_link

Logcat Reader Log

https://drive.google.com/file/d/1g6-UfXN_uvW45GwoL4QdgCRVuvr6crUH/view?usp=sharing

### Tachiyomi version

Preview 0.14.4-5513

### Android version

Android 13

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
02-18 14:52:07.337 29511 29686 E ACRA    : ACRA caught a UnsupportedOperationException for eu.kanade.tachiyomi.debug
02-18 14:52:07.337 29511 29686 E ACRA    : java.lang.UnsupportedOperationException: Not implemented!
02-18 14:52:07.337 29511 29686 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.readerfront.ReaderFront.getChapterUrl(ReaderFront.kt:111)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.readerfront.ReaderFront.getChapterUrl(ReaderFront.kt:20)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$setChapters$1.invokeSuspend(ReaderActivity.kt:31)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-18 14:52:07.337 29511 29686 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```
