### ISSUE TITLE
Failure to install V0.14.5 on Amazon Fire HD 10 (7th Generation)

### ISSUE THREAD

**Issue by okurtulu** [tachiyomiorg/tachiyomi#9112]
### Steps to reproduce

I was tryin to install Tachiyomi on Amazon Kindle Fire (Used the Fire Toolbox V30.3). I tried all the versions from 14 and go down the versions and until i reach to version 10 i was getting "Parse Error, There was a problem parsing the package".

Finally i installed Tachiyomi-V0.10.12.apk. When i open the Tachiyomi and wanted to add a manga library from Browse>Extensions, i am not seeing any of the manga sources. I tried to install extension manually but it is still not showing the source. Is there a way to get a bug fix or get the Tachiyomi V0.14.5 or a way around?

### Expected behavior

I keep getting Parsing Error for V0.14, V0.13, V0.12, V0.11

V0.10 installs, but doensnt show extensions on the list. 
Manual installation of the extensions are not also working. 

### Actual behavior

either getting parsing error or extension list is not updating. 

### Crash logs

No crash

### Tachiyomi version

0.14.5

### Android version

Android9

### Device

Amazon Fire 10 HD (7th Gen)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
7th Gen Fire Tablets never got Android 9. It sounds like you're actually on Android 5, which 0.11.x dropped.

Either update your tablet's OS if possible, or considering using a fork with Android 5 support like TachiyomiAZ.
