### ISSUE TITLE
Android TV navigation broken after 14.

### ISSUE THREAD

**Issue by Enigma911x** [tachiyomiorg/tachiyomi#9113]
### Steps to reproduce

Hi
I'm using Android TV and I know APK apps may not work correctly but the old UI was working great 

so on the TV remote you only have right, left, up, down, ok, and back
I was happy with 13.6 but I was forced to update because extensions stopped working

after updating to the new IU 14.+ strange navigation behavior

example 1.

in Library I can only choose from Titles that are shown on display I CAN'T scroll down, pressing down will skip to the horizontal bar

example 2.

when browsing a source extension, I can only select popular or latest, I can't scroll down to titles or click on them 

example 3.

after clicking a title I can't press any chapter only resume from last 

and many many others, almost every time I use the app I need to open the Nvidia shield app on my phone for the trackpad

and it's very frustrating because I believe it's a simple problem in a fantastic app

I appreciate all the work you do

thanks

### Expected behavior

in Library pressing down should scroll down throw all Titles

### Actual behavior

example 1.

in Library I can only choose from Titles that are shown on display I CAN'T scroll down, pressing down will skip to the down baron

### Tachiyomi version

0.14.5

### Android version

Android 11    9.1.1

### Device

nvidia shield pro

### Other details

I tried other forks but more or less had the same problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Merging with #8869
