### ISSUE TITLE
Stuttering on category swipe animation

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#9114]
### Steps to reproduce

1) have multiple categories 
2) swipe between them, letting go midway through
3) after letting go, the animation stutters

### Expected behavior

The expected behavior can be observed if you do not let go, manually swiping the whole way

### Actual behavior

The action completes, but stutters noticably

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Google Pixel 3 

### Other details

I believe this is new to this update 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-is-the-app-laggy-after-updating

**Comment by mm12** [comment]
Oh my bad, never had this behavior on update in the past
