### ISSUE TITLE
[Bug] Crash while opening the app

### ISSUE THREAD

**Issue by GMak9** [tachiyomiorg/tachiyomi#9117]
### Steps to reproduce

When you open the app, while the library is still loading, click the library icon again. 

### Expected behavior

Nothing is expected to happen because the library is still loading. 

### Actual behavior

Whenever this procedure happens the process terminates, crash. 

### Crash logs

> --------- beginning of crash
02-19 06:12:50.272 11898 10597 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-19
02-19 06:12:50.272 11898 10597 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 11898
02-19 06:12:50.272 11898 10597 E AndroidRuntime: java.lang.NullPointerException
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:22)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-19 06:12:50.272 11898 10597 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: FATAL EXCEPTION: main
02-20 19:43:19.469 25561 25561 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 25561
02-20 19:43:19.469 25561 25561 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:4)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:1)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$onClickFilter$1$1.invokeSuspend(LibraryTab.kt:43)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
02-20 19:43:19.469 25561 25561 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
--------- beginning of main
02-20 19:43:24.357 26081 26110 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-20 19:43:24.400 26081 26081 E ResourceType: Style contains key with bad entry: 0x01010586
02-20 19:43:24.405 26081 26081 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:43:24.405 26081 26081 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:43:24.405 26081 26081 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:43:24.434 26081 26081 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:43:24.435 26081 26081 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:43:24.435 26081 26081 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:43:31.856 26081 26289 E SQLiteLog: (284) automatic index on C(manga_id)
02-20 19:43:31.856 26081 26289 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-20 19:45:09.220 26460 26460 E ResourceType: Style contains key with bad entry: 0x01010586
02-20 19:45:09.224 26460 26460 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:45:09.224 26460 26460 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:45:09.224 26460 26460 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:45:09.246 26460 26460 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:45:09.247 26460 26460 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:45:09.247 26460 26460 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:45:15.966 26460 26586 E SQLiteLog: (284) automatic index on C(manga_id)
02-20 19:45:15.966 26460 26586 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-20 19:45:42.444 26460 26460 E ViewRootImpl: sendUserActionEvent() returned.
02-20 19:45:52.072 26679 26679 E ResourceType: Style contains key with bad entry: 0x01010586
02-20 19:45:52.076 26679 26679 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:45:52.076 26679 26679 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:45:52.076 26679 26679 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:45:52.099 26679 26679 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:45:52.099 26679 26679 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:45:52.099 26679 26679 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:45:58.817 26679 26891 E SQLiteLog: (284) automatic index on C(manga_id)
02-20 19:45:58.817 26679 26891 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: FATAL EXCEPTION: main
02-20 19:46:04.132 26679 26679 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 26679
02-20 19:46:04.132 26679 26679 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:4)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:1)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$onClickFilter$1$1.invokeSuspend(LibraryTab.kt:43)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
02-20 19:46:04.132 26679 26679 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-20 19:46:04.144 26679 26679 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
02-20 19:46:04.144 26679 26679 E ACRA    : java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
02-20 19:46:04.144 26679 26679 E ACRA    : 	at kotlin.collections.EmptyList.get(Collections.kt:4)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at kotlin.collections.EmptyList.get(Collections.kt:1)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$onClickFilter$1$1.invokeSuspend(LibraryTab.kt:43)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:790)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at android.os.Looper.loop(Looper.java:164)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7000)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
02-20 19:46:04.144 26679 26679 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-20 19:46:04.144 26679 26679 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@9eba492, androidx.compose.runtime.BroadcastFrameClock@65be63, StandaloneCoroutine{Cancelling}@ee66a60, AndroidUiDispatcher@2c4bb19]
02-20 19:46:15.383 26995 27118 E ACRA    : Failed to send crash reports for /data/user/0/eu.kanade.tachiyomi/app_ACRA-approved/2023-02-20T19:46:04.331-03:00.stacktrace
02-20 19:46:15.383 26995 27118 E ACRA    : org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:173)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:43)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:96)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.JobSenderService$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:37)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.lang.Thread.run(Thread.java:764)
02-20 19:46:15.383 26995 27118 E ACRA    : Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http PUT
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:14)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:1)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:62)
02-20 19:46:15.383 26995 27118 E ACRA    : 	... 4 more
02-20 19:46:15.383 26995 27118 E ACRA    : Caused by: java.net.SocketTimeoutException: failed to connect to tachiyomi.kanade.eu/49.12.103.64 (port 443) from /192.168.0.100 (port 59535) after 5000ms
02-20 19:46:15.383 26995 27118 E ACRA    : 	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at libcore.io.IoBridge.connect(IoBridge.java:130)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at java.net.Socket.connect(Socket.java:616)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1415)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1367)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:489)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.http.BaseHttpRequest.writeContent(BaseHttpRequest.kt:29)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.kt:243)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.kt:56)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.kt:66)
02-20 19:46:15.383 26995 27118 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:13)
02-20 19:46:15.383 26995 27118 E ACRA    : 	... 6 more
02-20 19:53:44.852 27735 27766 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-20 19:53:44.892 27735 27735 E ResourceType: Style contains key with bad entry: 0x01010586
02-20 19:53:44.896 27735 27735 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:53:44.897 27735 27735 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:53:44.897 27735 27735 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:53:44.929 27735 27735 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:53:44.930 27735 27735 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:53:44.930 27735 27735 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:53:52.234 27735 27845 E SQLiteLog: (284) automatic index on C(manga_id)
02-20 19:53:52.234 27735 27845 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: FATAL EXCEPTION: main
02-20 19:53:55.331 27735 27735 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 27735
02-20 19:53:55.331 27735 27735 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:4)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at kotlin.collections.EmptyList.get(Collections.kt:1)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$onClickFilter$1$1.invokeSuspend(LibraryTab.kt:43)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:10)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
02-20 19:53:55.331 27735 27735 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-20 19:53:55.334 27735 27735 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
02-20 19:53:55.334 27735 27735 E ACRA    : java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
02-20 19:53:55.334 27735 27735 E ACRA    : 	at kotlin.collections.EmptyList.get(Collections.kt:4)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at kotlin.collections.EmptyList.get(Collections.kt:1)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$onClickFilter$1$1.invokeSuspend(LibraryTab.kt:43)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:10)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:655)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:790)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.os.Looper.loop(Looper.java:164)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7000)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
02-20 19:53:55.334 27735 27735 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-20 19:53:55.334 27735 27735 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@cecd91a, androidx.compose.runtime.BroadcastFrameClock@f1a8c4b, StandaloneCoroutine{Cancelling}@20ec628, AndroidUiDispatcher@b9abf41]
02-20 19:53:57.967 27946 27978 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-20 19:53:58.005 27946 27946 E ResourceType: Style contains key with bad entry: 0x01010586
02-20 19:53:58.010 27946 27946 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:53:58.010 27946 27946 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:53:58.010 27946 27946 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:53:58.033 27946 27946 E ResourceType: Style contains key with bad entry: 0x0101058c
02-20 19:53:58.033 27946 27946 E ResourceType: Style contains key with bad entry: 0x01010604
02-20 19:53:58.033 27946 27946 E ResourceType: Style contains key with bad entry: 0x01010605
02-20 19:54:04.656 27946 28045 E SQLiteLog: (284) automatic index on C(manga_id)
02-20 19:54:04.656 27946 28045 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 8.1.0 (SDK 27)
Android build ID: M1AJQ.G610MUBS8CTG1
Device brand: samsung
Device manufacturer: samsung
Device name: on7xelte
Device model: SM-G610M
Device product name: on7xelteub

### Tachiyomi version

0.14

### Android version

8.1.0

### Device

Samsung Galaxy J7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems to be the same crash as #7997
