### ISSUE TITLE
The updates feature is not working 

### ISSUE THREAD

**Issue by Nottezero** [tachiyomiorg/tachiyomi#9118]
### Steps to reproduce

I'm  not getting updates of new chapters being released and I have manually go to each manga and refresh it to see if there are new chapters 

### Expected behavior

I expect to get a update or notification of any manga in my library getting  a new chapter 

### Actual behavior

I'm not getting any 

### Tachiyomi version

0.14.5

### Android version

11

### Device

A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by bubuanjay** [comment]
bug global search

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-does-global-update-skip-some-entries
