### ISSUE TITLE
Scrolling feature

### ISSUE THREAD

**Issue by revenant-RONIN** [tachiyomiorg/tachiyomi#9119]
### Describe your suggested feature

Could you include a feature where the "Volume +" and "Volume -" buttons could be used for scrolling up and down? It would be very much appreciated. 

### Other details

Scrolling UP would be Volume +
Scrolling DOWN would be Volume -
This should apply to pages that scroll LEFT to RIGHT and vice versa. 

There should be a bar for adjusting how far down or up the Volume buttons can scroll. Preferably, flowing from page to page should remain seemless and smooth.  

Thank you

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
This already exists. Explore the app's settings before making an issue please.
