### ISSUE TITLE
manga cover 

### ISSUE THREAD

**Issue by derinakcay8** [tachiyomiorg/tachiyomi#9124]
### Describe your suggested feature

it would be better if you put the old wide manga cover view as an option in the view section

### Other details

İn shortly I think the display style of manga covers before version 1.4.0 should come as an option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You're either in the wrong repo or you need to explain yourself more.
