### ISSUE TITLE
An feature to skip directly skip some pages of a chapter while reading

### ISSUE THREAD

**Issue by imDusht** [tachiyomiorg/tachiyomi#9125]
### Describe your suggested feature

So all mangas have cover page and end page and some of them have one or two xtra pages after cover page & before end page, so if for each manga we can set how many page from start & from end to skip. This way after setting for a manga when reading chapters you won't even see those pages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/3274
