### ISSUE TITLE
Apostrophe normalization during manga migration 

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#9128]
### Describe your suggested feature

Different sources use mainly 2 different apostrophes in manga names which are ’ (U+2019) and apostrophe ' (U+0027).

Its almost impossible to normalize since sources have both versions and searching a source in a one try wouldn't always find the manga depending on the apostrophe version used.

I suggest to implement a workaround to check when there is an apostrophe in a manga name during migration then search the sources **twice** for that manga with both versions of apostrophe to guarantee a manga would match even if it used a different apostrophe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This opens up a whole can of worms. There's plenty of other things that may differ, ranging from per-character differences like apostrophes, dashes, or accents; to broader ones like wording differences, romanization differences, etc.

Realistically, sticking with what the websites' search functionality offers is good enough. If their search implementation handles it, then it's fine. Making `n` requests to try to cover `n` different variations is not viable, and makes the DDoS concerns even worse. There's also sources that don't even return anything (like Suwayomi) or just return everything.
