### ISSUE TITLE
Theme guidelines 

### ISSUE THREAD

**Issue by Mangeshrex** [tachiyomiorg/tachiyomi#9129]
### Describe your suggested feature

How can I make a theme for this app? I've been loving this app from 2 days now. And I want to make theme for this app. 

I am developer of [Everblush](https://GitHub.com/Everblush) and would love to port tachiyomi to my colorscheme. If I can do so, I would be glad if you could provide the details / guidelines

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I'm not entirely sure how Everblush fits into the picture here.

Themes are currently defined like so:

- Declared as Android styles here: https://github.com/tachiyomiorg/tachiyomi/blob/92bd98e45f4132d3f0eb937d39c5df5d43a772a7/app/src/main/res/values/themes.xml
- Based on colors declared here: https://github.com/tachiyomiorg/tachiyomi/tree/92bd98e45f4132d3f0eb937d39c5df5d43a772a7/presentation-core/src/main/res
- Which are then listed here: https://github.com/tachiyomiorg/tachiyomi/blob/92bd98e45f4132d3f0eb937d39c5df5d43a772a7/app/src/main/java/eu/kanade/domain/ui/model/AppTheme.kt
- And eventually applied here: https://github.com/tachiyomiorg/tachiyomi/blob/92bd98e45f4132d3f0eb937d39c5df5d43a772a7/app/src/main/java/eu/kanade/tachiyomi/ui/base/delegate/ThemingDelegate.kt

This is to subject to change once we fully move to Jetpack Compose and can drop some of the legacy theming stuff.
