### ISSUE TITLE
update icon badge not showing the unread count 

### ISSUE THREAD

**Issue by HeavenShadow** [tachiyomiorg/tachiyomi#9134]
### Steps to reproduce

activate the show unread count on updates icon in setting.

### Expected behavior

Number of unread chapters should be shown 
it was working in version 0.14.2

### Actual behavior

the badge only show when there is new chapters and gone after clicking one it 

### Tachiyomi version

0.14.5

### Android version

Android 10

### Device

Samsung On6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It was changed to reflect the concept of "new updates" rather than "all unread chapters" at some point (which the library can already show).
