### ISSUE TITLE
Trackers doesn't get updated when marking a chapter read/unread manually (with button)

### ISSUE THREAD

**Issue by soymadip** [tachiyomiorg/tachiyomi#9142]
### Steps to reproduce

1. Add any manga/manhwa to library.
2. Add any tracker(i added Anilist and Mal).
3. Now long tap any chapter and mark it as read with the 'mark as read button. Alternatively try marking the previous chapters with the 'mark previous as read button. 
4. Now check trackers, they don't get updated. Value remains as same as it was before. 
5. Same happenes if trying to mark chapters as unread. 
- Screen record:- 

https://user-images.githubusercontent.com/84225810/221361696-ac214301-1374-4ba3-afcf-da754e8370f8.mp4

### Expected behavior

The app should update trackers as we mark chapters as unread/read.

### Actual behavior

The read chapter's value remains unchanged. 

### Tachiyomi version

0.14.5-5563 (standard, a6d6a5ed8, 98, 2023-02-19T20:34Z)

### Android version

 12 (SDK 31)

### Device

Realme 9 5g SE (RMX3461)

### Other details

Android build ID: RMX3461_11_C.06

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#389

**Comment by soymadip** [comment]
> #389

Will all due respect , i read the issue. 
But wanna ask to be sure, will this be implemented?
