### ISSUE TITLE
Refresh button error

### ISSUE THREAD

**Issue by KookieCho** [tachiyomiorg/tachiyomi#9144]
### Steps to reproduce

![Screenshot_20230225_233911](https://user-images.githubusercontent.com/126341568/221365936-3a754900-8bf5-4c77-9c6a-a3af48d5f1cb.jpg)

### Expected behavior

It should update the the title for the latest chapter.

### Actual behavior

This happened instead of updating it.

### Crash logs

JsonDecodingException: Expected start of the
object', but had 'EOF' instead at path: $
JSON input: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

### Tachiyomi version

0.40.5

### Android version

Android 11

### Device

Vivo y11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
