### ISSUE TITLE
bix？

### ISSUE THREAD

**Issue by fifteen5** [tachiyomiorg/tachiyomi#9147]
### Steps to reproduce

jinmantiantang bug
![Screenshot_2023-02-26-05-47-48-239_eu kanade tachiyomi](https://user-images.githubusercontent.com/48155834/221381222-b93b6357-42f9-405d-b8de-55d8c1ad27b7.jpg)

### Expected behavior

look

### Actual behavior

look

### Tachiyomi version

0.14.5

### Android version

13

### Device

miui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also do try to put in a little more effort in filling out the requested info next time.
