### ISSUE TITLE
Random Crash after I finish reading a chapter (Different Sources)

### ISSUE THREAD

**Issue by AlbedoSuzuki** [tachiyomiorg/tachiyomi#9151]
### Steps to reproduce

Example:
    1. I click on an chapter and read it
    2. After I finish reading the chapter, I go back to the chapter list
    3. And then the app crashes somewhere between .1 and a few seconds

### Expected behavior

Nothing happens and I go smoothly back to the library

### Actual behavior

The App crashes

### Crash logs

--------- beginning of main
02-26 11:09:12.138 29294  6286 E CursorWindow: Failed to read row 2280, column 0 from a CursorWindow which has 2280 rows, 14 columns.
02-26 11:09:12.145 29294 29294 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
02-26 11:09:12.145 29294 29294 E ACRA    : java.lang.NullPointerException
02-26 11:09:12.145 29294 29294 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$getUpdatesByReadStatus$1.invoke(DatabaseImpl.kt:19)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-26 11:09:12.145 29294 29294 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-26 11:09:12.145 29294 29294 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d0ee44c, Dispatchers.Main.immediate]
02-26 11:09:12.327  8153  8153 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
02-26 11:09:12.328  8153  8153 E yomi.debug:acr: LoadAppImageStartupCache enabled : 1
02-26 11:09:12.328  8153  8153 E yomi.debug:acr: Unknown bits set in runtime_flags: 0x8000
02-26 11:09:12.332  8153  8153 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
02-26 11:09:12.365  8153  8171 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
02-26 11:09:12.559  8153  8197 E SQLiteLog: (283) recovered 481 frames from WAL file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
02-26 11:09:14.789  8285  8285 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
02-26 11:09:14.789  8285  8285 E tachiyomi.debu: LoadAppImageStartupCache enabled : 1
02-26 11:09:14.789  8285  8285 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000
02-26 11:09:14.791  8285  8285 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
02-26 11:09:14.827  8285  8302 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
02-26 11:09:14.878  8285  8321 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@9fc2520
02-26 11:09:14.885  8285  8323 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:09:14.887  8285  8323 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:09:14.978  8285  8337 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-26 11:09:15.903  8285  8510 E SQLiteLog: (284) automatic index on C(manga_id)
02-26 11:09:15.904  8285  8510 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-26 11:09:18.709  8285  8285 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
02-26 11:09:38.426  8285  8285 E HwViewGroupImpl: parse speed value length error
02-26 11:13:04.154  8285  8520 E CursorWindow: Failed to read row 2280, column 0 from a CursorWindow which has 2280 rows, 14 columns.
02-26 11:13:04.161  8285  8285 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
02-26 11:13:04.161  8285  8285 E ACRA    : java.lang.NullPointerException
02-26 11:13:04.161  8285  8285 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$getUpdatesByReadStatus$1.invoke(DatabaseImpl.kt:19)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-26 11:13:04.161  8285  8285 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-26 11:13:04.161  8285  8285 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9e77b3d, Dispatchers.Main.immediate]
02-26 11:13:05.717 10699 10699 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
02-26 11:13:05.718 10699 10699 E tachiyomi.debu: LoadAppImageStartupCache enabled : 1
02-26 11:13:05.718 10699 10699 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000
02-26 11:13:05.719 10699 10699 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
02-26 11:13:05.739 10699 10717 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
02-26 11:13:05.752 10699 10721 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@c08063a
02-26 11:13:05.769 10699 10723 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:13:05.769 10699 10723 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:13:05.934 10699 10751 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-26 11:13:06.846 10699 10816 E SQLiteLog: (284) automatic index on C(manga_id)
02-26 11:13:06.846 10699 10816 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-26 11:13:09.325 10699 10699 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
02-26 11:13:16.082 10699 10699 E HwViewGroupImpl: parse speed value length error
02-26 11:15:37.748 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:15:37.756 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:17:15.916 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:17:15.947 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:17:21.948 10699 10699 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
02-26 11:17:26.028 10699 10699 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
02-26 11:17:26.029 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:17:26.121 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:19:25.009 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:19:25.013 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:19:25.051 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:26:31.036 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:26:31.045 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:26:31.067 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:26:31.368 10699 10699 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:28:28.436 10699 14303 E CursorWindow: Failed to read row 2280, column 0 from a CursorWindow which has 2280 rows, 14 columns.
02-26 11:28:28.439 10699 10699 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
02-26 11:28:28.439 10699 10699 E ACRA    : java.lang.NullPointerException
02-26 11:28:28.439 10699 10699 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$getUpdatesByReadStatus$1.invoke(DatabaseImpl.kt:19)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-26 11:28:28.439 10699 10699 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-26 11:28:28.439 10699 10699 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2bf5020, Dispatchers.Main.immediate]
02-26 11:28:29.535 16753 16753 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
02-26 11:28:29.535 16753 16753 E tachiyomi.debu: LoadAppImageStartupCache enabled : 1
02-26 11:28:29.535 16753 16753 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000
02-26 11:28:29.537 16753 16753 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
02-26 11:28:29.559 16753 16771 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
02-26 11:28:29.628 16753 16787 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@726ac23
02-26 11:28:29.632 16753 16789 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:28:29.643 16753 16789 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
02-26 11:28:29.715 16753 16805 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-26 11:28:30.635 16753 16910 E SQLiteLog: (284) automatic index on C(manga_id)
02-26 11:28:30.635 16753 16910 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-26 11:28:33.281 16753 16753 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
02-26 11:28:38.203 16753 16753 E HwViewGroupImpl: parse speed value length error
02-26 11:28:48.515 16753 16753 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:28:48.519 16753 16753 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:28:48.549 16753 16753 E RtgSchedManager: endActivityTransaction: margin state not match
02-26 11:35:13.080 16753 16753 E SysUtils: [variable fonts] error to update font wght scale:java.lang.NumberFormatException: empty String
App version: 0.14.5-5596 (standard, 0505906e7, 99, 2023-02-25T21:09Z)
Android version: 10 (SDK 29)
Android build ID: DBY-W09S 2.0.0.260(C432E2R2P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWDBY
Device model: DBY-W09
Device product name: DBY-W09NM

### Tachiyomi version

0.14.5-5596

### Android version

10 (SDK 29)

### Device

Huawei HWDBY DBY-W09

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Similar crash to #8400
