### ISSUE TITLE
Button to delete downloaded chapters when migrating

### ISSUE THREAD

**Issue by CodeSpoof** [tachiyomiorg/tachiyomi#9153]
### Describe your suggested feature

When migrating to another source, the downloaded chapters currently remain downloaded, but only for the previous source. Therefore, they occupy storage space without the user noticing or being able to easily fix it. There needs to be a way to manage downloaded chapters for titles that are not in the library and/or a prompt to delete downloaded chapters when a title with downloaded chapters is removed from the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by semenvav** [comment]
Working on this
