### ISSUE TITLE
Text in search bar

### ISSUE THREAD

**Issue by NouRiiix** [tachiyomiorg/tachiyomi#9156]
### Steps to reproduce

Clicking on a (long) manga's name in the library or from a source/history to search for it

### Expected behavior

![Fp9dvsxWIAAjlpr](https://user-images.githubusercontent.com/126453813/221514159-982e272c-44c5-4f87-b557-02ea3426b774.jpg)
Its being searched & the cursor or **text is at the end.**

### Actual behavior

![Fp9dv46WcAEYM7N](https://user-images.githubusercontent.com/126453813/221514252-30001bc3-4591-4497-ae96-59d4fe2306fe.jpg)
Its being searched & the cursor/text isnt at the end. (no cursor anyway)

### Tachiyomi version

0.14.5

### Android version

Android 9

### Device

Galaxy S9

### Other details

having atleast the name all the way to the end (doesnt need to have the cursor since that prompts the keyboard) but alteast have **the search bar at the end of the text**, and when you click it to edit/write, it stays there at the end (Its how it was)

I'm hoping it will be reverted to "expected behaviour" 

Thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Seems better to prioritize showing content than the keyboard. Cursor does start at the end when tapped in current build.
