### ISSUE TITLE
Plural formulas are wrong for some languages in Weblate

### ISSUE THREAD

**Issue by Ereza** [tachiyomiorg/tachiyomi#9157]
### Steps to reproduce

1. Open Hosted Weblate.
2. Open Tachiyomi 0.x project.
3. Open the Catalan translation.
4. There are 14 strings with "Failing check: Missing plural".
5. If you open the list, all of them are missing the plural form "Others". However, these have been translated several times, and they keep appearing as "Missing plural" every time a new string is added to the project.

### Expected behavior

There should be 0 strings with "Failing check: Missing plural" after translating them.
The plural formula for Catalan (and other languages like Spanish) should be `n != 1`.

### Actual behavior

There are 14 strings with "Failing check: Missing plural" even after translating them. They appear as missing plural every time a new Tachiyomi string is available for translation.
The plural formula for Catalan (and other languages like Spanish) is wrong: `(n == 1) ? 0 : ((n != 0 && n % 1000000 == 0) ? 1 : 2)`.

### Tachiyomi version

N/A

### Android version

N/A

### Device

N/A

### Other details

Every time the Weblate project for Tachiyomi is updated, there are some strings with plurals that keep popping up as untranslated. For example, `lock_after_mins`. I maintain the Catalan translation and the plural formula is wrong. It should be just like in English (`n != 1`), but it is `(n == 1) ? 0 : ((n != 0 && n % 1000000 == 0) ? 1 : 2)`.

My guess is that this has to do with some change made some time ago to use different strings for things exceeding one million, but it clearly generates some issues when syncing between the GitHub repository and Weblate. For example, in Catalan I have translated the `lock_after_mins` "other" plural string many times, but it keeps disappearing each time there is a new string.

I have checked other languages and at least Spanish is also affected and has the same wrong formula. English has the correct formula.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Please report this at https://github.com/WeblateOrg/weblate/issues

**Comment by Ereza** [comment]
This is not a Weblate bug, but a configuration issue with the project. I translate other projects in Hosted Weblate and I never had this problem.

**Comment by arkon** [comment]
We use Weblate's default configuration and I can't seem to find any way to change them.

If you're seeing incorrect configurations, then it's probably a problem with their defaults?
