### ISSUE TITLE
Olympus es 

### ISSUE THREAD

**Issue by julioxd123** [tachiyomiorg/tachiyomi#9161]
### Steps to reproduce

La página de Olympus a Sido renovada y el link del mismo igual 

### Expected behavior

Actualizar la extención de Olympus con el nuevo enlace de la página 

### Actual behavior

Entro a la extención y no aparece nada, entre a la web y me apareció que avía una nueva pagina 

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Xiaomi note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also please try to write in English if possible, as that's a common language everyone can respond to; as opposed to waiting (maybe indefinitely) for someone who can read your issue
