### ISSUE TITLE
Downloads keep getting timeout on the mangakakalot extension

### ISSUE THREAD

**Issue by Ayush62** [tachiyomiorg/tachiyomi#9162]
### Steps to reproduce

i select a series form the mangakakalot extension and press on download.

### Expected behavior

all the chapters should download and within a day.

### Actual behavior

the download times out the whole time and after 5 days is still not downloaded.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10854766/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.5

### Android version

13 (SDK 33)

### Device

Samsung s 22 ultra

### Other details

it's only on this extension. the other extensions work with out any problem even when i am download around a 100 chapters

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Please also do try the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
