### ISSUE TITLE
Migrate from Hendroid

### ISSUE THREAD

**Issue by Tommy-01** [tachiyomiorg/tachiyomi#9166]
### Describe your suggested feature

A function to migrate all Data (with Groups) from Hendroid to Tachiyomi.
If I have not missed it, this is currently not available.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
This isn't something that'd be considered for the app itself. People can write tools that work with the backup restore system though, similar to what was done for aidoku
