### ISSUE TITLE
Disable Border Cropping in Webtoon mode

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#9169]
### Describe your suggested feature

Most webtoons become misaligned when border cropping is on, as they are usually made up of multiple images meant to emulate a strip, rather than one long image. This leads to user confusion when they switch readers.

The option to enable border cropping in webtoon mode should be completely removed to prevent this from happening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Will this not affect continuous vertical reader mode, which also uses the webtoon reader but with padding between pages? Continuous vertical is used primarily to read manga and comics

**Comment by FireCheck** [comment]
You only need to disable it in reader settings for webtoon only or while reading by clicking on the crop icon.
![Screenshot_2023-03-13-04-42-27-955-edit_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/84283461/224603293-05ea11db-b3dd-4bb2-b474-d26f39855abf.jpg)
Or
![IMG_20230313_044501.jpg](https://user-images.githubusercontent.com/84283461/224603455-751f099a-cfde-49c3-a9e3-46bc0f284876.jpg)
