### ISSUE TITLE
Komiku.com timeout

### ISSUE THREAD

**Issue by CanULetMeIn** [tachiyomiorg/tachiyomi#9171]
### Steps to reproduce

1. Go to browse
2.  Open komiku.com

### Expected behavior

The manga should be appear

### Actual behavior

Timeout

### Tachiyomi version

0.14.5

### Android version

Android 10

### Device

Samsung s9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
If this is an issue with an extension, I should be opening an issue in the extensions repository.
