### ISSUE TITLE
Reaper Scans: Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by SantanuLayek** [tachiyomiorg/tachiyomi#9173]
### Steps to reproduce

1. Open the Reaper Scans Extension, or Update any manga from Reaper Scans as its source
2

### Expected behavior

1. Manga Updates successfully and displays any new chapters released by reaperscans

### Actual behavior

1. Displays error message : Failed to Bypass Cloudflare

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Oppo F19 pro+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by SantanuLayek** [comment]
When will this issue be fixed?
