### ISSUE TITLE
Manga screen three-dot menu not opening

### ISSUE THREAD

**Issue by Veysinator** [tachiyomiorg/tachiyomi#9180]
### Steps to reproduce

1. Open Tachiyomi
2. Open any manga
3. Click the three-dot icon on the upper-right
![20230307_173915](https://user-images.githubusercontent.com/71281955/223454843-b1d4b668-891c-4f29-aeb0-33621a68220e.jpg)

### Expected behavior

The menu opens and choices show up

### Actual behavior

The menu does not open, just the clicking animation is shown

### Tachiyomi version

Preview r5602

### Android version

Android 8.1

### Device

Samsung Galaxy J7 Prime

### Other details

The problem was present in the previous preview release too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce. Does this happen on other screens with overflow menus?

**Comment by Veysinator** [comment]
Changed to a custom rom, it works now
