### ISSUE TITLE
App not updating

### ISSUE THREAD

**Issue by ilmastr0** [tachiyomiorg/tachiyomi#9181]
### Steps to reproduce

Can't update the app when a new version is available, pressing the download button simply closes the window. This happens both when starting the app or in the settings  under Others>Info>Check for updates

### Expected behavior

The download should start after pressing the button

### Actual behavior

The download doesn't start

### Tachiyomi version

0.14.4

### Android version

Android 11

### Device

OnePlus Nord

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You could try https://dontkillmyapp.com/oneplus

Otherwise, download from http://tachiyomi.org/download/
