### ISSUE TITLE
`Feature Request` Bind Series Custom Cover Image on Different Extension/Source

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#9182]
### Describe your suggested feature

DESCRIPTION
--
Currently, there are popular extensions that use low quality images for their series cover images, resulting to your `Library` having two types of saved series cover images.
A. Low quality cover images (e.g. blurry images or pixelated)
B. High quality cover images (e.g. animated or high resolution)

Example are series sourced from `Novelmic`
![image](https://user-images.githubusercontent.com/66582769/223604614-5c17cb8a-5c0f-4690-8aa3-f5b07afc1bd6.png)

If you want to change the low quality cover images of the series saved on your Library. 

You'll have to add custom cover images by downloading it on websites that has high quality version of the cover images and load them one by one per series on your `Library`

SUGGESTED SOLUTION
--
Please add an option for users to source custom cover image from another extensions, for example MangaDex since they have the best quality and often latest cover images available.

The implementation can be similar to `Tracker` e.g. Anilist/Manga Updates tracking wherein you can bind/tag a series to a different source to pull the cover image from the other source.

Example is `Chainsaw Man` and MangaDex as the cover image source
A. Chainsaw Man is saved in your library via Extension A
B. On the tracker settings for the series, you can bind Chainsaw Man to MangaDex.
C. When you refresh your library or the series itself. It will try to query for a custom cover and pull the Chainsaw Man latest cover image on MangaDex replacing Extension A cover image.

Note: This can work together with `Settings > Library > Automatically refresh metadata` settings.

### Other details

This will result to the user doesn't have to manually go to a different website and download images and replacing cover images one by one on the `Library`, they just have to tag the series similar to adding a tracker with Anilist/MangaUpdates.

And a `Library` with high quality cover images only.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It'd be way too convoluted to effectively use 2 sources for 1 library entry.

#5452 requested using a cover from a tracker, which would be more ideal.

**Comment by 8227846265** [comment]
Oh, right. I forgot creating that thread before... Wait, it was 2 years ago.

@arkon is #5452 is a feature request considered for this year's implementation or still considering?

**Comment by arkon** [comment]
There's no roadmap, development is entirely done by volunteers in their free time.

**Comment by 8227846265** [comment]
@arkon I see, understood. I'll just wait for it patiently, then. Thank you.
