### ISSUE TITLE
Option to see unused sources and shortcut to uninstall 

### ISSUE THREAD

**Issue by BaccanoMob** [tachiyomiorg/tachiyomi#9183]
### Describe your suggested feature

Currently tachiyomi has a tab called "migrate" which lists all sources at use and when clicked we see the list of entries.

If a user has more number of sources, having an unused sources tab or filter will be helpful to check and uninstall if needed.

Possible solution:
Migrate tab should include sources with 0 entries in them. Sorting by entries count in ascending order should push all sources with 0 entries to top. An empty list appears when clicked or a popup to uninstall the source
Or
Having a button in the topbar which opens the list of unused sources (when in either migrate or extensions tab) and shortcut button on the each item of the list to uninstall directly from menu rather than going to extensions tab after checking.

### Other details

I'm not suggesting this on save space perspective as apps use very less space. Rather than easy see and use. Also prolly helpful when using global search, where we can avoid trying to lot of unused sources (saves time) and saves data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3787
