### ISSUE TITLE
Page stuck on loading sometimes.

### ISSUE THREAD

**Issue by ashbradley6** [tachiyomiorg/tachiyomi#9191]
### Steps to reproduce

after reading for a while the the pages would stuck on loading for no reason. It happens when alot.
![Screenshot_20230310_061139](https://user-images.githubusercontent.com/80982530/224172848-ed5af40b-6b3c-4c01-9718-6283cc285490.jpg)

### Expected behavior

help me

### Actual behavior

It shows spinning circle until it shows "unexpected error" text. clicked retry and it repeats

### Crash logs

--------- beginning of system
03-09 03:09:48.461  9484  9525 E HwActivityThreadImpl: connect Error.
--------- beginning of main
03-10 06:20:05.543 17089 17089 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
03-10 06:20:05.550 17089 17089 E anade.tachiyom: LoadAppImageStartupCache enabled : 1
03-10 06:20:05.607 17089 17089 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
03-10 06:20:05.648 17089 17115 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
03-10 06:20:05.841 17089 17140 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@2471b00
03-10 06:20:06.134 17089 17178 E SQLiteLog: (283) recovered 107 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
03-10 06:20:06.299 17089 17089 E libc    : Access denied finding property "uifirst_listview_optimization_enable"
03-10 06:20:06.335 17089 17089 E libc    : Access denied finding property "itouch.predict_opt"
03-10 06:20:06.979 17089 17181 E anade.tachiyom: open file error
03-10 06:20:07.046 17089 17237 E SQLiteLog: (284) automatic index on C(manga_id)
03-10 06:20:07.046 17089 17237 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-10 06:20:07.055 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:07.056 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:07.056 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:12.469 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:12.469 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:13.566 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:13.567 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:13.611 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:13.611 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:14.194 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:14.194 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:26.532 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:20:26.532 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:20:30.407 17089 17114 E DatabaseUtils: Writing exception to parcel
03-10 06:20:30.407 17089 17114 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=17770, uid=1000 requires the provider be exported, or grantUriPermission()
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:847)
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:711)
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:248)
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
03-10 06:20:30.407 17089 17114 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)
03-10 06:21:14.548 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:21:14.548 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:21:16.802 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:21:16.802 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
03-10 06:21:41.341 17089 17089 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/17089/rtg
03-10 06:21:41.341 17089 17089 E RtgSchedIpcFile: setCommandByIoctl not opened
App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 11 (SDK 30)
Android build ID: CMA-L42CQ 4.2.0.243(C636E1R1P3)
Device brand: HONOR
Device manufacturer: HONOR
Device name: HNCMA-Q
Device model: CMA-LX2
Device product name: CMA-LX2

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Honor x7

### Other details

need help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
What source?
Did you check other sources
Try going through [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/) and [FAQ](https://tachiyomi.org/help/faq/)
