### ISSUE TITLE
We hope that the storage will move to a file download 

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi#9196]
### Describe your suggested feature

The download file should automatically go to storage Most of the other applications moved the storage to this file Android 12and more 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Huh?

**Comment by reremer** [comment]
all downloads go to storage depending on where you choose, internal or external.
