### ISSUE TITLE
无法下载章节，图片加载不完全，频繁闪退

### ISSUE THREAD

**Issue by see-cmd** [tachiyomiorg/tachiyomi#9198]
### Steps to reproduce

观看章节
下载章节

### Expected behavior

正常加载图片观看
正常下载章节

### Actual behavior

章节内图片加载不完全，并且导致频繁闪退，
网络正常，下载章节无进度，完全储存权限

### Crash logs

--------- beginning of crash
03-10 00:53:49.911 10160 24809 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-10 00:53:49.911 10160 24809 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 10160
03-10 00:53:49.911 10160 24809 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-10 00:53:49.911 10160 24809 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-10 01:04:04.062 17274  5827 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 17274
03-10 01:04:04.062 17274  5827 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-10 01:04:04.062 17274  5827 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-10 01:14:25.312 17275  6631 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 17275
03-10 01:14:25.312 17275  6631 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-10 01:14:25.312 17275  6631 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-10 01:15:33.602 17276 13509 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 17276
03-10 01:15:33.602 17276 13509 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-10 01:15:33.602 17276 13509 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-12 01:19:55.231 32665 26327 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 32665
03-12 01:19:55.231 32665 26327 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 01:19:55.231 32665 26327 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-12 01:24:51.405 12943 28761 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 12943
03-12 01:24:51.405 12943 28761 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 01:24:51.405 12943 28761 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-12 01:25:23.624 12945 29902 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 12945
03-12 01:25:23.624 12945 29902 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 01:25:23.624 12945 29902 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-12 01:25:30.262  7943 30291 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 7943
03-12 01:25:30.262  7943 30291 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 01:25:30.262  7943 30291 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-12 01:27:23.980  7941  1595 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 7941
03-12 01:27:23.980  7941  1595 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(ScrambledImageInterceptor.kt:58)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(ScrambledImageInterceptor.kt:27)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:41)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 01:27:23.980  7941  1595 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 13 (SDK 33)
Android build ID: TKQ1.220829.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: odin
Device model: 2106118C
Device product name: odin

### Tachiyomi version

0.14.5

### Android version

安卓13

### Device

小米MIX4

### Other details

MIUI14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
这是禁漫插件的问题，请到 https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose 反馈。
