### ISSUE TITLE
Can't see part of the line

### ISSUE THREAD

**Issue by Vagamin** [tachiyomiorg/tachiyomi#9205]
### Steps to reproduce

![IMG_20230313_232551](https://user-images.githubusercontent.com/39989954/224827714-a1285f91-a3bc-431d-b08b-130c6ca6f05d.jpg)
There should be the phrase "In the library" but there is only the letter "B".  Everything is fine with the translation.

### Expected behavior

Should be the full phrase  "В библиотеке". In Russian translation.

### Actual behavior

When a manga is given in the search that is in my library.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Secret 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already addressed for next release.
