### ISSUE TITLE
Incorrect display of the button text

### ISSUE THREAD

**Issue by YukioAramori** [tachiyomiorg/tachiyomi#9207]
### Steps to reproduce

I was transferring manga from one source to another and the 3 (Move) button was displayed incorrectly (vertically instead of horizontally).
![Screenshot_20230314_084920_eu kanade tachiyomi](https://user-images.githubusercontent.com/123153679/224895835-50b1e59f-bd28-487e-91f2-7b21464464c2.jpg)

### Expected behavior

horizontal button

### Actual behavior

Presumably because of the transfer

### Tachiyomi version

App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z) Android version: 10 (SDK 29) Android build ID: STK-L21VHN 10.0.0.232(C10E3R1P1) Device brand: HONOR Device manufacturer: HUAWEI Device name: HWSTK-HF Device model: STK-LX1 Device product name: STK-L21VHNRU

### Android version

Android 12

### Device

Honor 9X (SKT-LX1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Added video from #support

![SVID_20230317_220636_1.mp4](https://cdn.discordapp.com/attachments/349436576037732355/1086334944164454541/SVID_20230317_220636_1.mp4)
