### ISSUE TITLE
Sort by Ratings

### ISSUE THREAD

**Issue by DDRook** [tachiyomiorg/tachiyomi#9209]
### Describe your suggested feature

I think it would be quite usefull to sort by rating in your library, we already have the ability to link Tachiyomi with services like AniList and My Anime List, I think if we could pull the ratings for the titles in our library's and then see their score/rating  and then sort them by rating. That would be pretty cool

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
since you need ratings first to sort by the ratings, ratings in general has been rejected already. #2272
