### ISSUE TITLE
The cloudflare of Nhentai keep looping in the app

### ISSUE THREAD

**Issue by AKSRAY** [tachiyomiorg/tachiyomi#9210]
### Steps to reproduce

It's a little embarrassing to tell, but I can't access to Nhentai through the app (It was able to.)
I certify I'm not a robot and it says success.
But it will keep asking me to certify again and again
It works fine in chrome but not the app

### Expected behavior

After the certify, it should let me view the website in the app

### Actual behavior

Keep looping in the certify part
Unable to access to the web

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Samsung galaxy A22 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is already documented in the troubleshooting guide. We don't handle higher levels of CloudFlare protection, which flags bot-like traffic such as that from Tachiyomi.
