### ISSUE TITLE
Myreadingmanga and nhentai cloudflare failed by-pass 

### ISSUE THREAD

**Issue by D1o2c3** [tachiyomiorg/tachiyomi#9211]
### Steps to reproduce

Open web view
Verify
Verify loop on webview of nhentai and myreadingmanga 

### Expected behavior

Able to access website of nhentai and myreadingmanga 

### Actual behavior

Webview verify loop

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Realme 25s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
