### ISSUE TITLE
EarlyManga Close My Tachi 

### ISSUE THREAD

**Issue by ruuno123** [tachiyomiorg/tachiyomi#9212]
### Steps to reproduce

1. i open the tachi EarlyManga with the "Latest" label and it close my app ,it was working fine yesterday morning!
2. its work with the "popular" label only close my app with  "latest" and i cant see my updates! :(
3. it was issue before too with this extension but forgot how to fix

### Expected behavior

Dont close my tachi 

### Actual behavior

it close my tachi

### Tachiyomi version

0.14.0

### Android version

9

### Device

Lenovo TB-7305F

### Other details

Dont want to update my tachi app if its possible Because i may lag xD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
We don't offer any support to outdated versions of the app so you're at your own. Update the app to use recent extensions versions.

**Comment by ruuno123** [comment]
well thats cool thanks.. :§
