### ISSUE TITLE
Score synchronization 

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [tachiyomiorg/tachiyomi#9213]
### Describe your suggested feature

When I rate a series with 10/10 or 5/5 (equivalent to 10/10) for some.
The app will automatically modify the score on MD's 10 depending on you tracker.

### Other details

If you have multiple trackers, just add a feature where you can choose i.e. MAL & Anilist to be your Primary Tracker.

1/5 = 2/10
2/5 = 4/10 and so on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
More general request - #8459

**Comment by Raizanad** [comment]
I believe this would be useful, was going to suggest it. Maybe add one row where you type the score and status and it is mimicked to the rest of the trackers.

**Comment by arkon** [comment]
Closing in favor of #8459
