### ISSUE TITLE
Move chapter scanlator on chapter transition to a new line

### ISSUE THREAD

**Issue by noaione** [tachiyomiorg/tachiyomi#9216]
### Describe your suggested feature

It certainly nice having the scanlator name when moving inbetween chapters, but the scanlator name being on the same line and separated by dot is confusing to read as shown in the image below.

I suggest moving it to a separate line making it less confusing to read.

### Other details

![original](https://user-images.githubusercontent.com/34302902/225634007-c28ee1fa-eef2-49b4-b658-0bd6bd5addce.png)

How it looked originally, the right image just makes me think that the scanlator name is the chapter title.

![modified](https://user-images.githubusercontent.com/34302902/225634232-4d8a22a9-5c0c-46ef-9518-a7c419344fab.png)

Mocked image, less confusing compared to the current implementation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dalekin9** [comment]
I'm going to be working on this
