### ISSUE TITLE
Make possible to come back after clicking on a tag without the app exiting the extension

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#9218]
### Describe your suggested feature

I already did an issue about that #8575 but now i have another proposal for it without changing the screen hierarchy. I could not comment in that issue again since the bot locked it long ago.

So i am on this entry of an extension (lets say this is the first position). Normally when i click on a tag of an entry and then click on the back button to come back the app will normally exit the extension, but when i do a tag global search, click on the extension of the entry of the tag (in this case 1st kiss) i can come back to the 'first position' without exiting the extension (eventually having to type again the filtered search and scroll enough entries to reach the previous place).

https://user-images.githubusercontent.com/75091899/225649242-707f277e-4a49-43cb-ae95-5a59a7b1733a.mp4

Here is the proposal: Since we cannot change the scheme hierarchy, can the app just take the global search path "underground" without actually showing it? I guess in this way the hierarchy is not changed (maybe i'm wrong idk). Since the global search path makes possible to avoid the flaw of the feature "Search"  (impossible to come back to the entry) disappear.
![IMG_20230316_154727](https://user-images.githubusercontent.com/75091899/225655018-a6fdf801-a27b-4f8d-87ac-957f36c311e7.jpg)

### Other details

This "underground" global search path should not work as an actual global search (so no searches on other extensions except, in this case, 1st kiss). This feature should replace the actual mechanism of the feature "search" (see image above).The app has just to take that path (modified, i guess) to avoid changing the scheme hierarchy so that users can use the "Search" button without the actual flaw. 
This is the actual flaw of the feature "Search":

https://user-images.githubusercontent.com/75091899/225657586-dc9e1897-7fa4-4cab-a9b3-95a8e04fdbb0.mp4

What do you think about it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Screen hierarchy has not changed and pushing the library or browse on top does not make logical sense.
