### ISSUE TITLE
The mangabuddy extention only have two pages available

### ISSUE THREAD

**Issue by MonkeyKing0012** [tachiyomiorg/tachiyomi#9225]
### Steps to reproduce

I am having an issue on extension of Mangabuddy,
It's only showing 2 pages every chapter.
I tried to look on the webview and it's completely fine.
Other extention that i'm currently using don't have this problem.

### Expected behavior

You can see in the page number how many pages the chapter has, even if it has only a few pages, atleast the content in that chapter is complete...

### Actual behavior

It only has 2 pages, and the other contents that is not included on that 2 pages is cut off...

### Crash logs

No crash logs

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

Samsung

### Other details

Idk if other extensions have these problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
