### ISSUE TITLE
Filter by Reader mode

### ISSUE THREAD

**Issue by CodeSpoof** [tachiyomiorg/tachiyomi#9226]
### Describe your suggested feature

A filter rule to only show entries, for which tje reader is set to a specific mode (rtl, vertical, webtoon,...) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Feels like clutter. We could potentially have an advanced setting to reset everything, so make a request for that if interested.

**Comment by CodeSpoof** [comment]
It was rather meant to differentiate between types like manga and webtoons.
