### ISSUE TITLE
Mangabuddy missing pages

### ISSUE THREAD

**Issue by ReachedTheApex** [tachiyomiorg/tachiyomi#9227]
### Steps to reproduce

1. Load chapter
2. Pages available/loaded = 0/2 pages

### Expected behavior

1. Load chapter
2. Pages available 0/X 

### Actual behavior

Mangabuddy extension is currently only displaying two pages in each recent chapter for the past day, the actual webpage has the full amount of pages though.

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

S23 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
