### ISSUE TITLE
A place to see any downloaded chapter even if it not on your library

### ISSUE THREAD

**Issue by ZoMpziO** [tachiyomiorg/tachiyomi#9228]
### Describe your suggested feature

To make easier to know what what is downloaded and what is not and that way if you removed any manga from the library and forget to remove the download chapters you could easy deleted it and if you you wanted to download a shelter without putting at and your library you could easily know there place

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's no plans to effectively turn the app into a file browser for downloads considering the library acts as the database of content. 

At best: #1767
