### ISSUE TITLE
Some chapters have a 300 page Oran more and each page is is very very tiny

### ISSUE THREAD

**Issue by ZoMpziO** [tachiyomiorg/tachiyomi#9230]
### Steps to reproduce

![Screenshot_20230318_130159_eu kanade tachiyomi](https://user-images.githubusercontent.com/114371984/226101559-6902574b-27e7-4ab3-93d6-abb637e8d4aa.jpg)
Like this a lot of black lines it makes it very hard to read

### Expected behavior

.

### Actual behavior

.

### Crash logs

.

### Tachiyomi version

The last stable one

### Android version

10

### Device

Huawei y7p

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Change your reading mode - https://tachiyomi.org/help/guides/reader-settings/#default-reading-mode

Also, there is no "The last stable one" Tachiyomi version. Next time specify the exact app version from **More > About**
