### ISSUE TITLE
Missing Panels 

### ISSUE THREAD

**Issue by Jinyaaaa** [tachiyomiorg/tachiyomi#9231]
### Steps to reproduce

All of the manhwas/manhua/comics etc that is added to my library only contains 2 panels which is unusual because all of those are already done and just rereading ...😭

### Expected behavior

If you open a new chapter It usually contains a lot of panel but all of the chapter that I open only contains 2... Huhu help meeee

### Actual behavior

If I tap a new chapter It has 2 panels only I checked the other manhwas and chapter and it only contains 2 panels and some chapters have been cut like I'm rereading and some of the parts are missing and if I read to the next chapt it's not connected to where the previous chapter ended

### Crash logs

I don't know if it's a bug or something just help me huhu 😭

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Vivo y11

### Other details

![Screenshot_20230318_211225](https://user-images.githubusercontent.com/128232616/226108733-c4210008-fedc-4be1-93fa-b2ec72658bed.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Probably MangaBuddy issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15744

If not - ask for help in support channel on discord https://discord.gg/tachiyomi
