### ISSUE TITLE
bug in an extension 

### ISSUE THREAD

**Issue by Kuripoket** [tachiyomiorg/tachiyomi#9232]
### Steps to reproduce

I have a bug in the olympus sacalation extension when I see the comic has no pages and the cloudflare is not updated 

### Expected behavior

that they add a new cloudflare or because the page is under development 

### Actual behavior

I was adding manga to a list and well everything was normal until the next day arrived and well it wouldn't let me see the manga 

### Tachiyomi version

0.14.5

### Android version

11

### Device

Google pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
