### ISSUE TITLE
In library mark not shown when adding series to library 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#9235]
### Steps to reproduce

1. Browse some source
2. Add entry to library
   -> by tapping and holding
   -> by opening manga details and adding to library from there

### Expected behavior

In library mark shown for that entry in browse

### Actual behavior

In library mark not shown 

### Tachiyomi version

r5625

### Android version

Android 13

### Device

Tecno spark 6

### Other details

https://user-images.githubusercontent.com/48650614/226151431-94ca5b5c-e259-4ebe-9a1d-6c4baa6d80b1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I suspect this might be related to the removal of the subscription in #9217

**Comment by Sn0rlaxxxx** [comment]
Same, also Android 13 (redmi note 10 pro), my mangahere fav mark not showing in library.
