### ISSUE TITLE
Support for duplicate file linking. 

### ISSUE THREAD

**Issue by CodeSpoof** [tachiyomiorg/tachiyomi#9240]
### Describe your suggested feature

Since many scanlators always put the same oage at beginning or end of a chapter, it could be implemented, that files are stored using a checksum or something similar and then the download is just a list of those checksums to avoid duplicates and save much storage. It could also be implemented by replacing images by text containing the path to the actual file, but that would bring some other problems. Sadly android uses fat32 so hardlinks are not an option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See beginning of [this comment](https://github.com/tachiyomiorg/tachiyomi/issues/9238#issuecomment-1475294049); there's expectations that downloads can be (relatively) easily consumed outside of only the app.
