### ISSUE TITLE
olympus scanlation extension stopped working because i change site 

### ISSUE THREAD

**Issue by Joskeis** [tachiyomiorg/tachiyomi#9241]
### Steps to reproduce

1. I enter my manga section
2. Does not show pages 
3. I check the source 
4. They use another page 

### Expected behavior

It should open the page with the mangas 

### Actual behavior

Produces error 500

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Oppo A15

### Other details

Sorry if I'm wrong, I'm a Spanish speaker and my English is not that good. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15330
