### ISSUE TITLE
UNABLE TO UPDATE ANY EXTENTION

### ISSUE THREAD

**Issue by tenjiku** [tachiyomiorg/tachiyomi#9245]
### Steps to reproduce

GO TO BROWSE>
EXTENSION>
UPDATE ALL

### Expected behavior

IT SHOULD UPDATE THE EXTENSION

### Actual behavior

IT STARTS DOWNLOADING THEN DOES NOT INSTALL. IT JUST SHOWS BLUE UPDATE FOR ALL.

HAVE TRIED FOLLWING STEPS ALL SETTINGS ARE CORRECT YET UPDATE FAILS

Make sure that Tachiyomi has storage permission. Go to your device settings and find the app permissions. Ensure that Tachiyomi has permission to access your device's storage.

Check the storage settings within Tachiyomi. Go to Settings -> Library Settings -> Advanced Settings -> Storage. Ensure that the storage location is set to the correct directory.**FAILED**

Clear the cache and data of Tachiyomi. Go to your device settings, find the app settings for Tachiyomi, and clear the cache and data.**FAILED**

Uninstall and reinstall Tachiyomi. **FAILED**

NO CRASH LOGS . ALL I GAVE CHANGED IS FORMATTED A SAMSUNG SD CARD AS INTERNAL, 
I HAVE MANUALLY CHANGED THE DOWNLOAD LOCATION TOO.
i think it is not recognising the SD card as internal card.

 _**I have updated all installed extensions**_.  **i cant,** but as it is problem with all extension i am opening a ticket here. if i am wrong please let me know.

### Tachiyomi version

0.14.5

### Android version

android 11

### Device

redmi 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Turn MIUI Optimizations under Developer Settings to OFF

**Comment by tenjiku** [comment]
wanted to add that if i uninstall an extension then I cannot install it again.
tachiyomi has storage permission, BUT , ALL other individual extension are blank in other permission.
