### ISSUE TITLE
Allow to skip pages that cannot be downloaded

### ISSUE THREAD

**Issue by Lindvorn** [tachiyomiorg/tachiyomi#9246]
### Describe your suggested feature

Hello. Thank you for a perfect app.
It would be nice to have an option to ignore pages from chapters that throw connection errors or just can't be downloaded.
For example I often have in download queue "downloaded 299/300" and when I resume it checks all pages and stuck at the same progress. 
And if I try to open partially downloaded manga the app tries to download it page by page no matter downloaded parts. 
I speculate that remote resource might fight back manga download so that reader have to visit resource. Sometimes few pages might be ignored without losing the plot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#3957
