### ISSUE TITLE
Restoring the preferences of extensions

### ISSUE THREAD

**Issue by LinkCFF** [tachiyomiorg/tachiyomi#9249]
### Describe your suggested feature

When i restore my info, because i get a new phone, all of my mangas get restored but the preferences for the source and app did not restore. Now, when i do a update, it skipped 259 updates, because all of my mangas restore with more than one scan, so all of this new chapters are unread. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Merging with #1857
