### ISSUE TITLE
Bad Performance  when scrolling  browse-> extension list 

### ISSUE THREAD

**Issue by blackholeearth** [tachiyomiorg/tachiyomi#9250]
### Steps to reproduce

Bad Performance  when scrolling  browse-> extension list 

İt freezing when scrolling ,  Its like less than 1 fps . 
 List is big  . Freeze stutter is worst here.

Browse-> sources is less worse , cuz it has 20 item .

Even xamarin forms  is not that shtty at scrolling. 

### Expected behavior

İt should not stutter.  When scrolling on 
Browse-> sources 
Browse-> extension
 Library  on any category 

### Actual behavior

İts freezing stuttering like hell.
 Its like less than 1 fps . 
 Browse. Extension List is big  . Freeze stutter is worst here.

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Samsung a12  --  6gb ram

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Merging with #9010
