### ISSUE TITLE
Scrolling goes in opposite direction than expected

### ISSUE THREAD

**Issue by Sunspark-007** [tachiyomiorg/tachiyomi#9252]
### Steps to reproduce

On the library view, do a quick light flick upward. 

### Expected behavior

The titles should scroll upward in the same direction as the finger flick.

### Actual behavior

The page scrolls downward.

### Tachiyomi version

0.14.5

### Android version

Android 9

### Device

Samsung A70

### Other details

This doesn't happen with heavy presses, just light touch. The effect sometimes can be a "bounce" effect if you're using a medium flick downward where it scrolls down but then reverses.

This did not happen with Tachiyomi 0.13.6 and previous. Also does not happen with any other app on the device.

I feel this is somehow related to the inertia scrolling changes introduced in 0.14.0 that made it very heavy to scroll where a light touch makes it quickly come to a halt.

I want to link below two examples of a scrolling difference, done well and done badly. Samsung Internet Browser (will install on any device and is Chromium) has an excellent scrolling experience. Great inertia. Firefox browser is really leaden and unpleasant feeling. It would be wonderful if Tachiyomi could copy the inertia settings Samsung chose for the browser.
https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser
https://play.google.com/store/apps/details?id=org.mozilla.firefox

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Does it happen if you set 'Tap zones' as 'Disabled'? Note: there are two settings with this name - for paged reading modes and for webtoon reading modes.

**Comment by Sunspark-007** [comment]
Yes it does. I disabled it in paged, and I was still able to make the library titles scroll in the opposite direction.

**Comment by arkon** [comment]
Scrolling inertia was affected by the move to Compose UI. There isn't much point in us trying to change that, so you'll need to hope that they tweak it upstream.
