### ISSUE TITLE
Asura scans extension giving error message "Unable to resolve host "asura.gghttps": No address associated with hostname"

### ISSUE THREAD

**Issue by racooncitytrash** [tachiyomiorg/tachiyomi#9253]
### Steps to reproduce

Step 1. go to a Asura scan Manhwa like Relife Player
Step 2. Click on a chapter

### Expected behavior

Open the chapter that says is available to read

### Actual behavior

Chapter instantly closes, gives error "Unable to resolve host "asura.gghttps": No address associated with hostname"

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Google Pixel 6 Pro

### Other details

The extension lets you read some titles but not most. 
It worked yesterday for me but after it recently scanned for new updates it stopped letting me read the new chapters and old ones. Not sure if its a URL issue since it lets me go into the extension just has an issue with opening to chapters as if its under a new URL so I have to go through webview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
