### ISSUE TITLE
Incorrect flagging of chapters as duplicates.

### ISSUE THREAD

**Issue by agent457** [tachiyomiorg/tachiyomi#9255]
### Steps to reproduce

1. Go to the One-Punch Man manga on the MangaSee source.
2. Open chapter 112.5 (Punch 112.5) and try going to the next chapter 113 which does exist (Punch 113).

### Expected behavior

Chapter 113 (Punch 113) shows up.

### Actual behavior

Chapter 118.5 (Punch 118.5) shows up instead

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

Galaxy A53 5G

### Other details

This does seem to happen in other chapters as well (I just used my most recent experience as an example).
I don't know whether or not this is an issue with the extension or the app so I made the report here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment]
This is related to "skip duplicate" setting of reader

**Comment by agent457** [comment]
>
