### ISSUE TITLE
Tachiyomi Update 

### ISSUE THREAD

**Issue by fixonnnn** [tachiyomiorg/tachiyomi#9264]
### Steps to reproduce

It won't update.
1. I got to the old release update for tachiyomi.
2. I clicked the version 13.6 and download.
3. I installed it but it won't appear in the app. My tachiyomi stay at version 13.5
4. When I download it and install, it appears like this .
![Screenshot_2023-03-26-23-28-57-96](https://user-images.githubusercontent.com/128987674/227786322-e11fb9d1-be35-483c-ad59-3f510f2a32db.png)

### Expected behavior

After I download the 13.6 version update, it should update from 13.5 to 13.6

### Actual behavior

But it won't change. Once I installed it. The app stay in the 13.5 version. 

### Crash logs

App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 9 (SDK 28)
Android build ID: RMX1941EX_11_A.34
Device brand: Realme
Device manufacturer: Realme
Device name: RMX1941
Device model: RMX1941
Device product name: RMX1941

### Tachiyomi version

0.13.5

### Android version

Android 9

### Device

Realme C2

### Other details

![Screenshot_2023-03-26-23-22-03-78_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/128987674/227785802-c38facee-587d-4357-be9a-cee27771c4f4.png) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Use https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en_US to get a more helpful error message of why it isn't installing.

You can also download the APK from http://tachiyomi.org/download/

If you need more help, please ask on Discord.
