### ISSUE TITLE
Dump crash logs notification not show in Preview r5647

### ISSUE THREAD

**Issue by DchanN** [tachiyomiorg/tachiyomi#9265]
### Steps to reproduce

Click More -> Advanced -> select Dumb crash Logs

### Expected behavior

Show overlay notification 

### Actual behavior

Didn't show overlay notification 

### Tachiyomi version

Preview r5647

### Android version

Android 10

### Device

Asus Zenfone 5Z

### Other details

https://user-images.githubusercontent.com/101858971/227787130-5b888bb4-68f3-4d0f-98fe-677631f44988.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce, is the notification channel enabled (Settings > General > Manage Notifications > Crash logs)?

**Comment by DchanN** [comment]
> Can't reproduce, is the notification channel enabled (Settings > General > Manage Notifications > Crash logs)?

Yes all of them 

https://user-images.githubusercontent.com/101858971/227788885-0725c0eb-f92e-4c8f-a682-626562173196.mp4

Try fresh install in android 13 it's show, will try fresh install if someone with android 10 test it and working fine
