### ISSUE TITLE
Don't show "might be missing chapters" label in local manga

### ISSUE THREAD

**Issue by azarex** [tachiyomiorg/tachiyomi#9266]
### Describe your suggested feature

For local manga either remove the missing chapter label or ad an option to disable it as it doesn't work correctly with manga in volume format.
![Screenshot_20230327_015906_Tachiyomi](https://user-images.githubusercontent.com/35252152/227795640-8d22a8b5-f61e-40d1-8cc0-44b2dbf8ad61.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Was changed in 8ab7e632936a008d31a87acd335fbd5fb21d818b to only handle recognized chapter numbers, so it'd likely ignore those volume names now.

Regardless, it's going to be hit or miss like the rest of the chapter number recognition but that seems like a minor inconvenience given how inconsistently named things are.
