### ISSUE TITLE
Chapters namings ruins lives

### ISSUE THREAD

**Issue by AllLife2la** [tachiyomiorg/tachiyomi#9267]
### Steps to reproduce

1. Install extension Com-X (example)
2. Search for Zero Hour: Crisis in Time (one with 75 chapters) [https://com-x.life/1898-zero-hour-crisis-in-time-read.html](url)
3. Try to Download at least next 5 chapters

<img src="https://user-images.githubusercontent.com/8400957/227806934-a9663bc9-344a-43b1-89e4-cf2c0f41f063.jpg" width="200">

### Expected behavior

Сhapters must be downloaded with appropriate titles.
Chapter "(1994) №4" and similar must have a full title.

Like on Com-X site:
<img src="https://user-images.githubusercontent.com/8400957/227807065-463218a0-8c98-469e-8824-178db6f9f587.jpg" width="200">

### Actual behavior

When I download the first chapter, the rest of the chapters with the title [перевода не существует] are marked as downloaded.

<img src="https://user-images.githubusercontent.com/8400957/227807754-b7da449f-ccb4-447a-9b68-d9598f9d5a64.jpg" width="200">

Also Chapter "(1994) №4" and similar should have there full names, because this is crossover-event conteining issues from different titles.

### Crash logs

Not crash

### Tachiyomi version

r5653

### Android version

MIUI 12.5.1 - Android 11 Phone / EMUI 11.0.0 - Android 10 Tablet

### Device

Xiaomi mi9 / HUAWEI MediaPad M6

### Other details

Best feature might be deep customization of chapter naming:
1. Choose to keep or remove text similar to title name
2. Choose to remove or replace prohibited characters with spaces, dots, etc.
3. Allow user to create text replacement rules in chapter names (ex: [перевода не существует] -> (ENG) )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by AllLife2la** [comment]
I thought this is main app that changes names that shows in lists, one of forks shows issue names similar to title name. So extensions populates lists with them, i think.
About names with prohibited symbols shoud i make an issue in extensions repository then?

**Comment by curche** [comment]
If it only happens in a particular extension, which seems to be the case, then you can make a report for that extension

**Comment by arkon** [comment]
To clarify, the app strips out the title from the beginning of chapter names if it's an exact match. It doesn't do anything else to it.

If the source seems to be removing other parts, then the source needs to be fixed. If it's undesirable for the title to be stripped, the source also needs to account for that by prefixing something.
