### ISSUE TITLE
Timeline for dropping Android 6.x support?

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#9269]
### Describe your suggested feature

Android 6.0 is already more than a year older than 5.0 was when it was dropped. When 5.x was dropped, it held roughly [4% of the active market share](https://gs.statcounter.com/android-version-market-share/all/worldwide/2021). Currently, 6.x [barely cracks 1.5%.](https://gs.statcounter.com/os-version-market-share/android)

From what I can tell, it also has much less user activity here in the repository. Issues listing a 5.x version number were being filed right up until mere weeks from the cutoff date (#4311), but it's been more than half a year and about 1500 issues since the latest 6.x one that I could find (#7816).

Not trying to rush anything, just curious if it's in the pipeline at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Dropping Android 6 doesn't really help. When the time comes, probably both Android 6 and 7 will be dropped together. I don't know the exact details, but there were multiple discussions about this on Discord.

Also, you should ask questions on Discord (https://discord.gg/tachiyomi). GitHub is for bug reports and feature requests.

**Comment by arkon** [comment]
There's very little in the codebase that would benefit from dropping support for Android 6.0. A bunch of things are Android 8.0+, but there isn't a pressing need to go to that yet (e.g. dependencies dropping support for 6.0-7.1).
