### ISSUE TITLE
Cannot download chapters

### ISSUE THREAD

**Issue by Raeyraey** [tachiyomiorg/tachiyomi#9271]
### Steps to reproduce

1. Launched Tachiyomi
2. Opened a manga in any source
3. Proceed to download new chapter but shows "attempt to invoke virtual method" 

### Expected behavior

Download chapter/s

### Actual behavior

Doesn't download and instead notifies "attempt to invoke virtual method 'com.hippo.unifile.UniFile"

### Tachiyomi version

0.14.5

### Android version

Android 9

### Device

Vivo Y11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Check your download location; probably it's pointed to an invalid SD card or something.

**Comment by Raeyraey** [comment]
Good day! I tried downloading just now and it works fine halfway but after
that it sends a notification saying "invoke virtual boolean" I went to my
sd card to delete the chapters that was downloaded and it says "errors
during deletion" is the problem my sd card? Thank you for your help.

**Comment by Raeyraey** [comment]
Here's the message it sent

**Comment by Raeyraey** [comment]
I checked one of the manga I downloaded last week and I found these
gibberish characters with big file size, I tried deleting but it says
"errors during deletion".

**Comment by kiriya-aoi** [comment]
Yes, your SD card is dead.
