### ISSUE TITLE
It closes after i search  anything  for sources and extensions 

### ISSUE THREAD

**Issue by Ace0fFate** [tachiyomiorg/tachiyomi#9272]
### Steps to reproduce

First step : try to search something  in source
Second step: waiting to find the provided manga/manhwa
Third step: after a couple seconds and the bar being like in the middle it crashes

### Expected behavior

it should have ended the search and  and it should have been there  waiting for me to pick from what source it will be read upon

### Actual behavior

it should have ended the search and  and it should have been there  waiting for me to pick from what source it will be read upon

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/11084804/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)

### Android version

12 (SDK 31)

### Device

POCO x3 nfc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Do you have any obsolete/unofficial extensions? Did you try searching in individual extensions and see what happens?

Also, please try enabling verbose logging in Settings → Advanced and recreate the crash logs to see if there's anything else.

**Comment by Ace0fFate** [comment]
> Do you have any obsolete/unofficial extensions? Did you try searching in individual extensions and see what happens?
> 
> Also, please try enabling verbose logging in Settings → Advanced and recreate the crash logs to see if there's anything else.

Yeap also tryed in some  sources when it takes a lot it just crashes . Also i have enabled the Verbose nothing changed  and of course not a single absolete/unofficial installed.
Always the crash report has the same thing repeating 


"03-28 09:00:42.269  8733  9092 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-28 09:00:42.269  8733  9092 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 8733
03-28 09:00:42.269  8733  9092 E AndroidRuntime: java.net.SocketTimeoutException: timeout
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:5)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:9)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:62)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:5)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:3)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:172)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:622)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:33)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:187)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:241)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:33)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-28 09:00:42.269  8733  9092 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
03-28 09:03:17.340  9943  9983 E SQLiteLog: (284) automatic index on C(manga_id)
03-28 09:03:17.340  9943  9983 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-28 09:03:17.702  9943  9986 E anade.tachiyom: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found"

**Comment by Seishirou101** [comment]
do you have mangadoom installed? disable it to continue using the app.

**Comment by Ace0fFate** [comment]
> do you have mangadoom installed? disable it to continue using the app.

You are a Champion that was the problem thanks for  commenting . 
Both of you  thanks for the help :D
