### ISSUE TITLE
Browse source pager flow on main thread

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#9275]
### Steps to reproduce

https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt#L123

We should try `flowOn()` before `stateIn()`.

More importantly, we probably should switch thread more in interactors, as per [Google's guidelines that they should be main-safe.](https://developer.android.com/topic/architecture/domain-layer#threading)

### Expected behavior

On IO thread.

### Actual behavior

On main thread.

### Crash logs

Network on main thread exception before removing cover fetch

### Tachiyomi version

r5653

### Android version

N/A

### Device

N/A

### Other details

https://discord.com/channels/349436576037732353/350729100526092289/1089857829113954405

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
18f9e5ba6b080a74805db553e22f15412ddeab12

Although open to feedback if there's a better way to do this.
