### ISSUE TITLE
Crash when when use global search

### ISSUE THREAD

**Issue by buratcha0511** [tachiyomiorg/tachiyomi#9277]
### Steps to reproduce

1. Click the tittle of manga/manhua/manhwa from the main library or global search fo find other source.
2. Click any source and wait lessthan a minute it will crash
3. This happened everytime

### Expected behavior

This should easily find the manga/manhua/manhwa im looking for if i click the tittle to find better sources.

### Actual behavior

Now it's always crashing

### Crash logs

![Screenshot_2023_0328_214046](https://user-images.githubusercontent.com/62635511/228381325-48e7417e-c782-4136-b0eb-589d2ae4ecc4.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 8

### Device

Vivo 8180

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
update mangadoom extension
