### ISSUE TITLE
Broken Covers Bato.to

### ISSUE THREAD

**Issue by lythia3326** [tachiyomiorg/tachiyomi#9280]
### Steps to reproduce

Majority of the covers have a broken symbol in the middle of it. I have to go into each specific series and refresh in order for them to be normal again. I have tried refreshing the library covers and clearing the database in advanced settings but the problem still persist.

### Expected behavior

Usually, when the app opens all of the series have covers on them.

### Actual behavior

Now, whenever I open the app, 90% of the covers are not showing.

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

Samsung Galaxy S22

### Other details

![Screenshot_20230329_153535_Tachiyomi](https://user-images.githubusercontent.com/129338901/228683195-a0560fe4-a2c0-4be6-aa33-1a82f3b4f3a5.jpg)
![Screenshot_20230329_153540_Tachiyomi](https://user-images.githubusercontent.com/129338901/228683220-ce08dfbb-9f8b-4742-9cca-a5a33bfbfd06.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Bato.to covers expires after some time IIRC, there's nothing really we can do to fix it. Tap refresh thumbnails in the advanced settings of the app periodically when this happens.
