### ISSUE TITLE
Fixed chapter date

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#9283]
### Describe your suggested feature

There are websites that change the release date of already published chapters for some reason (i guess to trick the user into thinking that it is freshly updated) so i suggested to make the release date of a chapter not updateable after the first scrape.

### Other details

https://user-images.githubusercontent.com/75091899/229031245-7045293f-8ba8-47d3-a2c7-09eeea77851b.mp4

here you can see a common example thar many websites use. If they change the date what is the point in storing it? I would prefer it to be true

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
tachi just provides what the site does. if they change it, then it'll show you that change. a similar issue that was rejected before #5700
