### ISSUE TITLE
Surrogate pairs with characters between 0xE000 and 0xFFFD will have those characters replaced with NULL

### ISSUE THREAD

**Issue by Shamicen** [tachiyomiorg/tachiyomi#9284]
### Steps to reproduce

Download a chapter were any of the Metadata includes an Emoji made up of a Surrogate pair using a character between `0xE000` and `0xFFFD`.

### Expected behavior

ComicInfo files with Surrogate pairs made up of characters between `0xE000` and `0xFFFD` get created correctly

### Actual behavior

characters between `0xE000` and `0xFFFD` are replaced with `NULL` characters

### Tachiyomi version

Newest Debug Build

### Android version

Android 12

### Device

Pixel 5 emulator

### Other details

I think the Status update I wrote concerning the xmlutil Surrogate pair bug may have been Misunderstood. The original bug was indeed fixed but there was a new bug in the current release which at that point had also been fixed in the **dev branch**. Surrogate pairs with characters between `0xE000` and `0xFFFD` do not work correctly, the XML files will contain `NULL` characters instead. This should not be to big off an Issue since it only concerns Emojis that use those characters and when a `NULL` char gets imported back into Tachiyomi it just gets Ignored. Sorry if the Status Update I wrote was confusing. 
You guys can either disable ComicInfo creation again, use the xmlutil snapshot were it was fixed already or just Ignore it until the next release since it is a niche Issue that probably only really impacts a few Users, who could also fix the impacted files by hand. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is probably fine to keep enabled. We'll pick up new versions as they get released, so make sure it's reported upstream.

**Comment by Shamicen** [comment]
> This is probably fine to keep enabled. We'll pick up new versions as they get released, so make sure it's reported upstream.

It is already fixed upstream just not released yet
