### ISSUE TITLE
How do I convert the protobuf file from Tachiyomi backup to a parseable file like a JSON for use in python?

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi#9291]
### Describe your suggested feature

It's not really a feature. I just want to have my entire list of manga in the library in a JSON format for use in python. I want to be able to iterate through the list and see which ones are licensed. I am using mangaupdates through it's api to get the url and pulling information about licensing from the page itself because the api doesn't provide that for some reason. I am stuck because I can't decode the protobuf. I tried to learn what even protobuf is and stumbled on this command to decode the file with protoc:

`protoc --decode_raw < protofile.proto > output.json`

However, the output was not json compatible when I tried to load it in python. As an example, this is the first few lines of the output:

> 1 {
>   1: 9
>   2: "/manga/Onepunch-Man"
>   3: "One-Punch Man"
>   4: ""
>   5 {
>     9: 0x54415255
>     8: 0x656b757375755920
>   }
>   6: "In this new action-comedy, everything about a young man named Saitama screams \"AVERAGE,\" from his lifeless expression to his bald head, to his unimpressive physique. However, this average-looking fellow doesn\'t have your average problem... He\'s actually a superhero that\'s looking for tough opponents! The problem is, every time he finds a promising candidate he beats the snot out of them in one punch. Can Saitama finally find an evil villain strong enough to challenge him? Follow Saitama through his hilarious romps as he searches for new bad guys to challenge! READ: THERE IS NO FUCKING MISSING CHAPTER. Different versions have different number systems. Ask the author why he doesn\'t know how to count.\n\nAlternative Name: One Punch-Man, Onepunch Man, OPM"
>   7: "Action"
>   7 {
>     8: 0x657275746e657664
>   }
>   7: "Comedy"
>   7: "Drama"
>   7: "Sci-fi"
>   7: "Seinen"
>   7: "Supernatural"
>   7 {
>     9: 0x61676e61
>   }
>   8: 1
>   9: "https://temp.compsci88.com/cover/Onepunch-Man.jpg"
>   13: 1623300818994
>   17: 3
>   103: 32
> }
> 1 {
>   1: 9
>   2: "/manga/Bleach"
>   3: "Bleach"
>   5: "KUBO Tite"
>   6: "Ichigo Kurosaki has always been able to see ghosts, but this ability doesn\'t change his life nearly as much as his close encounter with Rukia Kuchiki, a Soul Reaper and member of the mysterious Soul Society. While fighting a Hollow, an evil spirit that preys on humans who display psychic energy, Rukia attempts to lend Ichigo some of her powers so that he can save his family, but much to her surprise, Ichigo absorbs every last drop of her energy. Now a full-fledged Soul Reaper himself, Ichigo quickly learns that the world he inhabits is one full of dangerous spirits, and along with Rukia, who is slowly regaining her powers, it\'s Ichigo\'s job to both protect the innocent from Hollows and to help the spirits themselves find peace.\n\nAlternative Name: Bleach"
>   7: "Action"
>   7: "Comedy"
>   7: "Drama"
>   7: "Martial Arts"
>   7: "Shounen"
>   7: "Supernatural"
>   7 {
>     9: 0x61676e61
>   }
>   8: 2
>   9: "https://temp.compsci88.com/cover/Bleach.jpg"
>   13: 1679564659097
>   17: 3
>   103: 0
> }
> 1 {
>   1: 9
>   2: "/manga/Komi-san-Wa-Komyushou-Desu"
>   3: "Komi Can\342\200\231t Communicate"
>   5: "ODA Tomohito"
>   6: "Komi-san is the beautiful and admirable girl that no-one can take their eyes off her. Almost the whole school sees her as the cold beauty out of their league, but Tadano Shigeo knows the truth: she\'s just really bad at communicating with others. Komi-san, who wishes to fix this bad habit of hers, tries to improve it with the help of Tadano-kun.\n\nAlternative Name: Komi-san wa Komyushou Desu"
>   7: "Comedy"
>   7: "Romance"
>   7: "School Life"
>   7: "Shounen"
>   7: "Slice of Life"
>   7 {
>     9: 0x61676e61
>   }
>   8: 1
>   9: "https://temp.compsci88.com/cover/Komi-san-Wa-Komyushou-Desu.jpg"
>   13: 1679562840242
>   17: 3
>   103: 0
> }

As you can see, the output is reeally messed up. A lot of the characters are also garbled like: **Komi Can\342\200\231t Communicate** instead of **Komi Can't Communicate**. So I wanted to know if there is a way to get a proper json or something similar to use in python. For reference, this is the code I'm using:

```
#"list of 'terms' from tachiyomi"=[a,b,z]

#for term in "list of 'terms' from tachiyomi":
  param={
    "search": term
  }
  
  response=requests.post('https://api.mangaupdates.com/v1/series/search',json=param)
  response_element=response.json()
  
  title=response_element['results'][0]['record']['title']
  manga_url=response_element['results'][0]['record']['url']
  
  page=requests.get(manga_url)
  tree=html.fromstring(page.content)
  licensed=tree.xpath('//*[@id="main_content"]/div[2]/div[1]/div[4]/div[22]/text()')
  licensed_clean=licensed[0].strip()
  print(title+' ~ '+licensed_clean+' ~ '+manga_url)

with open('C:/Users/Store/messedup.json') as f:
     data=json.load(f)
```

Also, I am not a programmer and barely understand what I am doing. Guidance would be much appreciated! Also I am not sure if asking a question is appropriate in feature request but I didn;t know where to ask this. Please don't ignore or delete this. Thanks in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
See https://github.com/tachiyomiorg/tachiyomi/issues/6878#issuecomment-1091960271

You might be able to get someone to help in the #programming channel on Discord.
