### ISSUE TITLE
Download Issue 

### ISSUE THREAD

**Issue by yusufyd** [tachiyomiorg/tachiyomi#9292]
### Steps to reproduce

I first updated my library
Then I tried downloading the new chapter that was released for the manhua I updated
But it's not downloading
It's telling telling me no internet connection 

### Expected behavior

It should start downloading normally 

### Actual behavior

It's not downloading 

### Crash logs

--------- beginning of system
--------- beginning of main
App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 9 (SDK 28)
Android build ID: X652B-H627CDM-P-210831V270
Device brand: Infinix
Device manufacturer: INFINIX MOBILITY LIMITED
Device name: Infinix-X652B
Device model: Infinix X652B
Device product name: H627

### Tachiyomi version

Stable 0.14.5

### Android version

Android 9

### Device

Infinix X652B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by aruto77** [comment]
I have similar issue, in my case, some of manga when i try to read or download will get error message like this
![IMG_20230406_100218](https://user-images.githubusercontent.com/30386035/230253762-8c0af37c-00bc-4bb6-b291-1962a0b46d50.jpg), the weird thing is when i try to open it on webview, the pictures will load nicely

**Comment by yusufyd** [comment]
Yeah we are probably having the same problem

**Comment by yusufyd** [comment]
I  think your problem is from d source

**Comment by arkon** [comment]
Not much info to go off of here. Try toggling the "Only on Wi-Fi" setting. VPN usage also may affect it.
