### ISSUE TITLE
Global Search Blank Screen 

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi#9298]
### Steps to reproduce

Global Search
![Screenshot_2023-04-05-14-38-25-973_eu kanade tachiyomi](https://user-images.githubusercontent.com/103346344/230014124-25f0bd05-a108-4732-a39d-30ecd76916ec.jpg)

### Expected behavior

search the title in all extension 

### Actual behavior

blank screen

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Related #8919

**Comment by arkon** [comment]
You probably don't have any pinned sources. Either pin sources or disable that.
