### ISSUE TITLE
swipe 

### ISSUE THREAD

**Issue by 2fo2** [tachiyomiorg/tachiyomi#9305]
### Describe your suggested feature

add a swipe feature so u can swipe from tabs 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by d-najd** [comment]
No idea what you mean by "swipe from tabs" but I just made a pull request for chapter swipe feature lol, maybe you meant that. here is link: https://github.com/tachiyomiorg/tachiyomi/pull/9304

**Comment by arkon** [comment]
Based on the discussion from Discord, they meant the bottom nav (side nav on larger screens). That's not a normal UX in Android apps, so no.
