### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by bolso96** [tachiyomiorg/tachiyomi#9307]
### Describe your suggested feature

I would like to ask if it would be possible to add the old app (blue and white) theme as part of the theme options. With the upper and lower parts in that characteristic blue, with white letters, basically as it used to be or as close as possible 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#6568
