### ISSUE TITLE
Doesn't download after page 2 while reading

### ISSUE THREAD

**Issue by vilewoo** [tachiyomiorg/tachiyomi#9308]
### Steps to reproduce

While reading a chapter:
• page 1 - ok
• page 2 - ok
• page 3 doesn't load image, only view message: "The image couldn't be loaded (retry)". And doesn't matter how many times you try the image don't load.
• if you use the WebView the chapter exist in the source
• if you try to download the chapter,  notification arrives: "Expected URL scheme 'http' or 'https' but no scheme was found for"
• I try in 5 different comics with the same result
![Screenshot_2023-04-08-10-14-34-807_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/36254221/230732370-26acdd53-cac1-4744-8026-818d7aea8b33.jpg)
![Screenshot_2023-04-08-10-05-48-267_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/36254221/230732435-b47e0920-b484-43df-8ece-a25481f1ff8a.jpg)
![Screenshot_2023-04-08-10-16-02-254_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/36254221/230732450-a04ae208-c2ee-4f8b-b5da-b4d585068561.jpg)

### Expected behavior

Load next page

### Actual behavior

Doesn't load next page

### Tachiyomi version

App version: 0.14.5-5666 (standard, 274218cf2, 99, 2023-04-01T21:08Z)

### Android version

Android version: 12 (SDK 31) Android build ID: SKQ1.211006.001 test-keys

### Device

Device brand: POCO Device manufacturer: Xiaomi Device model: 2201116PG DeviceName: POCO X4 Pro 5G 

### Other details

The device uses MIUI 13 version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Looks like an issue with the extension. Do you have this problem only with this source?

**Comment by arkon** [comment]
Sounds like a source-specific issue.
