### ISSUE TITLE
Pages of a manga doesn't load on WebView (Sushi-scan, french extension)

### ISSUE THREAD

**Issue by myung3007** [tachiyomiorg/tachiyomi#9313]
### Steps to reproduce

1. Use Sushi scan extension on Tachiyomi
2. Choose one manga to read
3. Pages doesn't load on Tachiyomi app
4. Open WebView to check any problems like Cloudfare etc...

### Expected behavior

1. See the internet page of Sushi scan and click one chapter of the manga (example : Naruto)
2. See the pages of the manga are ready to read on Webview
3. Return to Tachiyomi app and read on the app or download chapters

### Actual behavior

1. See the internet page of Sushi scan and click one chapter of the manga (example : Naruto)
2. See the pages of the manga are crashed
3. Return to read to Tachiyomi app
4. Pages of the manga doesn't load
5. Check on Google Chrome if the site has problems to load
6. On Google Chrome, the pages are perfectly loaded

### Crash logs

On WebView : ![338527868_724196829485627_986727521132552623_n](https://user-images.githubusercontent.com/123560095/230769105-88a5b646-9b80-461b-9886-1506979fc34e.jpg)

On Google Chrome : 
![338573141_146513475037744_3268021568550247572_n](https://user-images.githubusercontent.com/123560095/230769143-006732bf-1b26-416e-8158-69ab3804ae63.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

Vivo Y72 5G

### Other details

It's happen often on this french extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
