### ISSUE TITLE
Discord Rich Presence Support

### ISSUE THREAD

**Issue by jeryjs** [tachiyomiorg/tachiyomi#9314]
### Describe your suggested feature

A Feature to show what Manga/Manhwa the user is reading on their Discord status similar to how 'MAL-Sync' does it.
Something like this-
![183276248-1cdd2041-3551-47ff-b3e6-9563b48e2057](https://user-images.githubusercontent.com/77010142/230770772-74264841-c2b9-4f3f-a0c2-47918dd357da.png)

This feature exists in [Animiru](https://github.com/Quickdesh/Animiru) (which is a fork of Aniyomi) and I'd love to have the same feature in Tachiyomi too.

### Other details

Here are some screenshots of the discord rich presence feature in Animiru.

<img src="https://user-images.githubusercontent.com/77010142/230771073-28c6a636-2a1b-4110-a06f-b7fa1b0ff2f8.png" width=25%><img src="https://user-images.githubusercontent.com/77010142/230771282-11f583fa-d2d1-4585-8515-20a2279918b3.png" width=25%><img src="https://user-images.githubusercontent.com/77010142/230771095-bd3f8c40-3c74-484d-b487-e9d3ffcdcfa4.png" width=25%>

<img src="https://user-images.githubusercontent.com/77010142/230771014-07f5fe34-9ab5-4b8b-af0b-b8b7c0f0c9d1.png" width=25%><img src="https://user-images.githubusercontent.com/77010142/230771029-ed542a2f-b14a-485a-a4e5-fb11b5cacb79.png" width=25%><img src="https://user-images.githubusercontent.com/77010142/230771038-5e6642a4-c238-44f9-ad77-8da5690e8227.png" width=25%>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
#7698

**Comment by jeryjs** [comment]
@CrepeTF Please read the content before closing this issue...
Back then in #7698 It was closed due to reasons like how RPC might go against discord's TOS or that Kizzy was unreliable.
Now Animiru has actually implemented this feature and It's been working perfectly. 
Also, since most of the code can be taken from Animiru, It should be easier to add this feature (compared to before at least).
So please, instead of closing this issue, give it some thought since I believe lot of people who use Discord will appreciate this feature.

**Comment by CrepeTF** [comment]
It was actually closed for feature bloat

**Comment by jeryjs** [comment]
It's not really a feature bloat.. As I said, a lot of people who use Discord would definitely appreciate this feature. Besides, Adding a "Connections" tab allows for more potential features/integrations in the future and doesnt have to just stop at Discord Rich Presence.
I would really love to have this feature implemented as for the past year, I've been manually setting rich presence. Having it automated with Tachiyomi would be amazing!
Also, how can it be considered a bloat when it is one of Animiru's main features and Animiru is extremely similar to Tachi?

**Comment by arkon** [comment]
I can't speak to why Animiru exists as opposed to having its changes contributed upstream to Aniyomi. It looks like they have an implementation for Discord RPC that effectively does it from scratch (i.e. managing the websocket themselves) as opposed to using some pre-rolled library. 

I'm still not interested in having/maintaining this in Tachiyomi as Discord has aggressively gone against self-bots in the past few years as they introduce more first-party features.

Considering Animiru is a distant fork of Tachiyomi, you could just keep using that.

**Comment by jeryjs** [comment]
I believe their implementation for websocket is taken directly from the Kizzy library. Also I've been using the same implementation for a year now and haven't gotten any notices from discord.
If ur still not willing to have this feature in Tachi then it's fine, I'll give up. I'll just continue setting my rp as I have been doing till now.
One last question... Is there any way to programmatically get the name of the manga that we are reading from the reader? Or at least detect when the reader activity has been launched?
