### ISSUE TITLE
OVERHEATING AND BATTERY DRAIN

### ISSUE THREAD

**Issue by TravellingNinja** [tachiyomiorg/tachiyomi#9315]
### Steps to reproduce

Start the app

Read or download any manga or chapter

Device starts heating up after a minute even

### Expected behavior

Device shouldn't heat up and consume too much battery

### Actual behavior

Device heats up a lot and eats up battery like crazy. 
Such behavior isn't notice with other apps. Even big high fps games don't consume fraction of battery this app alone consumes in 10s of minutes 

### Tachiyomi version

0.14.5 both stable and beta

### Android version

Android 12

### Device

One plus 9

### Other details

I searched a similar issue when someone was experiencing this issue in the v12 but now the update is at v14.5 and refresh metadata is also closed. It is still overheating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Hard to do anything given the lack of any concrete info here. Note that global updates/downloads entail hundreds or thousands of network requests in rapid succession, so battery usage is expected and the app even warns about it.
