### ISSUE TITLE
Scan downloaded chapters when refreshing comics

### ISSUE THREAD

**Issue by Doddddd** [tachiyomiorg/tachiyomi#9316]
### Describe your suggested feature

Avoid clearing all download indexes due to a single comic.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The download index doesn't get cleared, and it gets updated ad-hoc as things are downloaded/deleted.

It gets fully refreshed every ~1 hour to help ensure it's somewhat consistent with what's actually on disk.
