### ISSUE TITLE
Delete chapter settings strange behavior

### ISSUE THREAD

**Issue by Hazks** [tachiyomiorg/tachiyomi#9317]
### Steps to reproduce

Problem 1:
 1) Turn on delete chapter after manually mark as read.
 2) Exclude a category.
 3) Manually mark as read any unread and downloaded chapter inside the excluded category.

Problem 2:
 1) Exclude a category.
 2) Delete any read chapter inside the excluded category.

Problem 3:
 1) Turn on delete chapter after manually mark as read.
 2) Manually mark as read any read and downloaded chapter outside the excluded category (can be done outside the entry i.e. from the category or by selecting both read and unread chapter).

### Expected behavior

Problem 1:
 Only mark the downloaded chapter as read without deleting the said chapter.

Problem 2:
 Delete the downloaded chapter.

Problem 3:
 Delete the downloaded chapter.

### Actual behavior

Problem 1:
 Mark and delete the downloaded chapter.

Problem 2:
 Nothing change.

Problem 3:
 Nothing change.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

Realme 6

### Other details

I disabled [after reading automatically] and enabled [Allow deleting bookmarked chapters].

The reason why i write the title as "behave strangely" is because "sometimes" it work and "sometimes" it doesn't; Problem 1 behave as expected with read chapter and so on for other problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I think the fix for #9520 covers this.
