### ISSUE TITLE
Mini thumnails for pages within Chapters

### ISSUE THREAD

**Issue by riber1** [tachiyomiorg/tachiyomi#9318]
### Describe your suggested feature

This feature is to add an icon in the series tab next to the chapters that will send them to a page with the thumbnail of the pages of the entered chapter, i have added pictures to illustrate bellow. the purpose of this feature is to glance at the thumbnails of the chapter to see if it contains the page you want.
![Screenshot_20230410_025810_Tachiyomi](https://user-images.githubusercontent.com/130323912/230804554-eade7f9c-f59e-45d2-b370-04db29e6763e.jpg)
![Screenshot_20230410_025844_Tachiyomi](https://user-images.githubusercontent.com/130323912/230804563-60fe0b35-dc8e-4c85-9d27-540189ea56a8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
By extension #6014
