### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by unpseudocomplique** [tachiyomiorg/tachiyomi#9320]
### Steps to reproduce

Read:
 I Am Carrying Gold From The Post-Apocalyptic World – Manhuaus

And sometimes (maybe 1 per chapter) a page is missing, have to close viewer and open again to see le missing page. It happen when Reading normaly and even when manga is downloaded so this isn't a network related issue.

### Expected behavior

Should load all page normaly and if not already loaded show spinner.

### Actual behavior

A page is often missing.

### Tachiyomi version

App version: 0.14.5-5675 (standard, c1e23ec18, 100, 2023-04-08T21:08Z)

### Android version

Android version: 13 (SDK 33) Android build ID: LE2123_11_F.75

### Device

Oneplus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
turn off Split tall images (BETA) in the reader settings inside a chapter. that is the issue most likely. #8433
