### ISSUE TITLE
Space between chapters

### ISSUE THREAD

**Issue by MountainFlowers** [tachiyomiorg/tachiyomi#9321]
### Describe your suggested feature

There is a space between two images that can get annoying when a chapter is split into 100 small images. In the picture example below, that is shown. 
![Screenshot_20230410_144522_Tachiyomi](https://user-images.githubusercontent.com/109493802/230903912-579a4b83-243f-4431-97af-3769523b80c8.jpg)
What I want is for the space between the images to be configurable. So for chapters with 100 small images, I can make the space zero.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Use Webtoon reading mode instead

**Comment by MountainFlowers** [comment]
Yeah, that fixed it. Thanks
