### ISSUE TITLE
How would I change the default theme or better yet, add a new theme then rebuild the app?

### ISSUE THREAD

**Issue by reDpz** [tachiyomiorg/tachiyomi#9323]
### Describe your suggested feature

I want to try adding a new theme or changing one then build the app from source (assuming there is no other way of doing this).

I have very basic programming knowledge, is this something I will be able to do or is it too complicated?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Some useful links for learning Android development and Kotlin - https://github.com/tachiyomiorg/tachiyomi/blob/master/CONTRIBUTING.md

You can look at pull requests that add new themes, e.g. https://github.com/tachiyomiorg/tachiyomi/pull/7825

For more questions use #programming channel on Discord https://discord.gg/tachiyomi

**Comment by reDpz** [comment]
> Some useful links for learning Android development and Kotlin - https://github.com/tachiyomiorg/tachiyomi/blob/master/CONTRIBUTING.md
> 
> You can look at pull requests that add new themes, e.g. #7825
> 
> For more questions use #programming channel on Discord https://discord.gg/tachiyomi

thanks I'll take a look into this

**Comment by reDpz** [comment]
> [](https://github.com/tachiyomiorg/tachiyomi/blob/master/CONTRIBUTING.md)
> 
> You can look at pull requests that add new themes, e.g. #7825
Was looking through the commit and I cant find the "PreferenceValues.kt" file in "tachiyomi\app\src\main\java\eu\kanade\tachiyomi\data\preference"

Do I just wget it?

**Comment by arkon** [comment]
It's since been refactored to https://github.com/tachiyomiorg/tachiyomi/blob/e3fbd2688048a4503f5a393d46580ae627d372d3/app/src/main/java/eu/kanade/domain/ui/model/AppTheme.kt
