### ISSUE TITLE
Sincronização e armazenamento de dados

### ISSUE THREAD

**Issue by AtaideDev** [tachiyomiorg/tachiyomi#9325]
### Describe your suggested feature

I noticed that the only way to not lose your mangas and the pages read in case something unforeseen happens with the smartphone (I lost my cell phone) is if a backup is made before the unforeseen event, and this is something that is not functional, because I would need to make backups every day, being that they need to be stored and without a doubt I wouldn't remember.

So a good feature for tachiyomi to evolve would be cloud storage.

### Other details

authentication method could be by google email, or accounts created by the tachiyomi app itself

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#912

**Comment by AtaideDev** [comment]
Woww 2017 e ainda não a nenhuma forma de imprementar isso no sistema?
