### ISSUE TITLE
Start Downloading Now bugged

### ISSUE THREAD

**Issue by jankenpon753** [tachiyomiorg/tachiyomi#9330]
### Steps to reproduce

1. Select mutiple series from library
2. download unread ones, they start normally
3. go inside a series
4. tap on a chapters DL icon
5. select Start Downloading Now
6. and it cancels the download most of the time

### Expected behavior

It shud move that chapter on top iof the dl list

### Actual behavior

cancels downloading for that chapter

### Tachiyomi version

0.14.5

### Android version

13

### Device

Poco F3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by staxhinho** [comment]
Up
