### ISSUE TITLE
Ability to see downloaded manga that are not in the library

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#9331]
### Describe your suggested feature

Sometimes downloaded manga files are still in tachiyomi download folder, but not in the library.

It would be nice to have the ability to see these downloaded manga that are not in the library. So we can do something (add to library, delete the downloaded manga).

Currently the only way to check downloaded manga that are not in the library is by going to the Manga "browse" extension menu, and then look for the Manga that's not in the library, then see that the chapters are already downloaded. It will have checkmark icon on the chapters. So tachiyomi did know those were already downloaded. 

===

You may wonder why people even have downloaded manga that are not in the library. Here's a few situations that could be the cause :

- selected a bunch of Manga from library, then only select "from library", leaving "downloaded chapters" unchecked. Then click OK. 
- restored from earlier backup with fewer Manga in the library 
- told tachiyomi to remove downloaded files and from library, but tachiyomi fails to remove the downloaded files (happens randomly and rarely). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#9228
