### ISSUE TITLE
Add way to disable "show only manga entries" to extensions.

### ISSUE THREAD

**Issue by K3end0** [tachiyomiorg/tachiyomi#9336]
### Describe your suggested feature

It seems a few sources have trouble with the "show only manga entires" filter when it is enabled by default. The example that highlighted the problem to me is [FreeMangaTop](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16057) which i created an extensions issue for since the source breaks with the filter on completely. 

But further testing has demonstrated that the problem affects other 'low-quality' madara sources in varying degrees. By way of example, I tested 5 other sources i use a lot and two sources "Top Manhua" and "ManhuaFast" suffer from the same problem but in a more limited form. The filter makes actual comic entries disappear on a random basis.

It is for this reason that i request the functionality to let users disable the "show only manga entries filter". I think it would work best implemented in the same way users can toggle Random Latest Agent and Custom User Agent in an individual extensions setting, and given to all extensions so users can disable it on a source by source basis if they find the filter does not work well with a given source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The main app has no knowledge/control over per-source filters. The extension could potentially provide settings for it.
