### ISSUE TITLE
No Multiple Migration function

### ISSUE THREAD

**Issue by mortalrizza** [tachiyomiorg/tachiyomi#9337]
### Steps to reproduce

1.  Go to browse.
2. Select Migrate Tab.
3. Select Manga source (isekaiscan)
4. Can't find the All button for multiple Migration tried long press but only copy the id for the site.
5. also tried long press when all the manga is present but no additional function is present.

### Expected behavior

should be there. the all function on migration.

### Actual behavior

no multiple Migration 

### Crash logs

none. maybe from the past update it was removed or disabled 😔

### Tachiyomi version

0.14.5

### Android version

12

### Device

infinix NOTE 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
there was never a mass migration in tachiyomi. #1231
