### ISSUE TITLE
Rename Continuous vertical to Webtoon with gaps/spaces

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#9339]
### Describe your suggested feature

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Maybe instead of adding a separate visual setting (both to individual manga and default reading mode), just rename

- Webtoon -> Strip/Webtoon/Continuous
- Continuous vertical -> Strip/Webtoon/Continuous with gaps/spaces

**Comment by AntsyLich** [comment]
Yeah that also works imo

**Comment by arkon** [comment]
Webtoon -> Longstrip
Continuous vertical -> Longstrip with gaps

?

**Comment by AntsyLich** [comment]
Should use Long Strip for translators convinience
