### ISSUE TITLE
Browse option gets glitched

### ISSUE THREAD

**Issue by RahmanRagib** [tachiyomiorg/tachiyomi#9348]
### Steps to reproduce

When browsing sometimes after searching the manga you cant go back it just reopens the keyboard for another search and there's no way besides closing the app to stop the glitch 

### Expected behavior

You should be able to go back to the extensions tab by tapping the back button 

### Actual behavior

After tapping the back button after browsing somewhat manga it doesn't go back rather glitches and reopens keyboard

### Tachiyomi version

1.6.5

### Android version

Android 13

### Device

Realme 9 4g

### Other details

Am new to this so dont know what should I put :|

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
1.6.5 is not a valid version of Tachiyomi, you should report it in the relevant fork repo.
