### ISSUE TITLE
Extremely long app initialization time

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi#9349]
### Steps to reproduce

1. Open the app. It must be done after force closing any previous instance running in the background.

### Expected behavior

App should display splash screen for no more than 1 second as was the case in 0.14.5.

### Actual behavior

Splash screen lasts atleast 5 seconds.

### Tachiyomi version

0.14.6

### Android version

Android 8

### Device

Samsung Galaxy S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-is-the-app-laggy-after-updating

**Comment by sillysack69** [comment]
But this is the first time this has happened. This never happened during any of the previous updates.
