### ISSUE TITLE
Move between categories in the library 

### ISSUE THREAD

**Issue by alaweeGAMAR** [tachiyomiorg/tachiyomi#9350]
### Steps to reproduce

Navigation is very slow when I click on a category. Previously, it was not like this. I hope to fix the issue 

### Expected behavior

Previously, when I clicked on the name of the category, it moved to it immediately

### Actual behavior

now it is very slow And very annoying 

### Tachiyomi version

0.14.6

### Android version

12

### Device

redmi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-is-the-app-laggy-after-updating
