### ISSUE TITLE
Add obsolete, outdated, and manually trusted extensions to crashlog

### ISSUE THREAD

**Issue by Seishirou101** [tachiyomiorg/tachiyomi#9359]
### Describe your suggested feature

When dropping a crashlog, the log should contain any obsolete or outdated extensions.

### Other details

possibly have it list the current extension version vs the installed extension version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Also extensions that were manually trusted
