### ISSUE TITLE
Click (Touch) once then swipe left or right for previous or next chapter.

### ISSUE THREAD

**Issue by Raizanad** [tachiyomiorg/tachiyomi#9365]
### Describe your suggested feature

Add an option in the library settings to enable the option to do an action (gesture) to skip/move to the previous or next chapter without scrolling through all the manga pages for the chapter, opening the menu or going back to the previous page with chapter selection.

Coming from a novel reader that does this (powered by tachi), I like this option a lot over there since I use volume up and down to move. The thing is that from experience in that app which uses the simple gesture swipe left or swipe right which leads to easily messing up, I wanted to suggest a less prone to user error option like touching once (medium/long duration on the screen) then swiping left or right (and as a must this should be toggleable I believe since people may dislike it triggering by mistake).

### Other details

As far as I know this isn't possible in the reader right now. Sorry if I didn't read hard enough, I also did a quick lookup for duplicates and didn't find any but hopefully I didn't miss it under a different name/explanation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Tap once in the center to show the UI menu then use the ◀ and ▶ button to navigate between chapters.

**Comment by Raizanad** [comment]
The suggestion was aiming to avoid using the menu interface. But fair enough! Thank you.
