### ISSUE TITLE
ADD: auto skip/remove the desired page of chapter from start to end

### ISSUE THREAD

**Issue by ChanchanReal** [tachiyomiorg/tachiyomi#9367]
### Describe your suggested feature

Sometimes there's a replay from the previous chapter i don't want to read that part again and sometimes at the end of the pages there's a spoiler of coming up page. It should work like how many pages i want to skip at the start everytime per chapters and hide or remove it automatically 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate of #3274 essentially
