### ISSUE TITLE
Passcode Lock

### ISSUE THREAD

**Issue by Useless-Panda** [tachiyomiorg/tachiyomi#9370]
### Describe your suggested feature

Currently, the `Require Unlock` option uses the lock screen password; it would be great to be able to use a custom pin for tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/1686

**Comment by CarlosEsco** [comment]
No
