### ISSUE TITLE
Battery drain when downloading on Wi-Fi only, with Wi-Fi off

### ISSUE THREAD

**Issue by dominiquelee** [tachiyomiorg/tachiyomi#9377]
### Steps to reproduce

1. Set in OS battery settings Tachiyomi as "Optimized" (rather than "No restriction" or "Limited")
2. In Tachiyomi settings, set Downloading as "Wi-Fi only" and "Automatically download new chapters"
3. Cut Wi-Fi on the device
4. Refresh your library, thus adding new entries in the download list
Alternative 4. Trigger a download from any entry in your library - I did a quick test and I think it also works, but to be confirmed
5. Send the app in background (don't kill it) and wait a few hours
6. Observe battery draining - in the OS battery settings, Tachiyomi appears as being constantly active in the last few hours

### Expected behavior

If download can't happen due to lack of Wi-Fi, battery shouldn't be drained when Wi-Fi is clearly off (and probably even if Wi-Fi is on but without actual connectivity).

### Actual behavior

Tachiyomi uses ~10% of battery every 2 hours.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Google Pixel 6a

### Other details

No mention of battery drain or wi-fi related issues in https://github.com/tachiyomiorg/tachiyomi/issues/7492

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably related to a wakelock being held while the service is active, which it perpetually will be until the downloads are actually stopped.

Ought to be "fixed" once we move over to a WorkManager job.

**Comment by arkon** [comment]
Should be fixed by #10190
