### ISSUE TITLE
Brightness Option

### ISSUE THREAD

**Issue by Hibari98** [tachiyomiorg/tachiyomi#9378]
### Describe your suggested feature

Allow us to adjust brightness when reading manga/manhwa. When the brightness from in phone is brightened only navigating the tachiyomi app is when it is applied. But as soon you click to read a manga/manhwa it goes all the way back down to default. There should be a button in settings the allows you to adjust brightness for the app itself for when you are reading a manga/manhwa. A small icon should appear whilst reading allowing users to adjust brightness if making a circle motion whilst reading. You can turn on/off this feature in settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Already exists in reader settings under custom filters
