### ISSUE TITLE
Download the new chapters for specific manga

### ISSUE THREAD

**Issue by ZoMpziO** [tachiyomiorg/tachiyomi#9380]
### Describe your suggested feature

If you want to download chepters for specific manga without downloading it every time this will make it easier you don't have to wait until you download it yourself you just have to go and read it you could put thes option in (download)
![Screenshot_20230423_154755_eu kanade tachiyomi](https://user-images.githubusercontent.com/114371984/233843614-39e18a9a-e3cf-4a46-b575-a393f1e36cf2.jpg)
Put it on the end of the list of (download)
![Screenshot_20230423_154759_eu kanade tachiyomi](https://user-images.githubusercontent.com/114371984/233843697-fe08401f-70f9-41dc-be8d-ef1af2e04446.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's already automatic download in the settings.

**Comment by ZoMpziO** [comment]
> There's already automatic download in the settings.

Yes there is but it for download all the new shepters but look here
![Screenshot_20230423_155857_eu kanade tachiyomi](https://user-images.githubusercontent.com/114371984/233844093-584e3e65-bba7-47f0-b920-04d27d98ea7a.jpg)
some of them i don't want to download it but it will be downloaded

**Comment by arkon** [comment]
Use the categories inclusion/exclusion then.
