### ISSUE TITLE
Tachiyomi preview build r5720 crashes on launch, and on attempt to get crashlogs as well

### ISSUE THREAD

**Issue by CptPakundo** [tachiyomiorg/tachiyomi#9382]
### Steps to reproduce

Here's what I did to get the app to crash:
  1. Update to r5720 from r5707.
  2. Launch Tachiyomi. (It crashed here)
  3. Attempt to share the crash log file. (It crashed here _again_)

### Expected behavior

The app is supposed to successfully launch, and then to work as expected from there onwards.

### Actual behavior

The app crashes on launch, and also when attempting to generate the crash log file.

### Crash logs

Here's a crash log file I generated by rapidly tapping the share button, because the app _also_ crashes a split-second after you try to share the crash log file:
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/11304181/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6-r5720

### Android version

Android 12

### Device

Samsung Galaxy S10 (Exynos version)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi/commit/c48accb3572d79c772875436939f7141cf5f9423, update to r5725
