### ISSUE TITLE
Using mouse to refresh manga chapters does not work still

### ISSUE THREAD

**Issue by eyao06** [tachiyomiorg/tachiyomi#9383]
### Steps to reproduce

Steps:
1. Have a mouse
2. Navigate to any area of the app that can refresh via a pull down (i.e. chapter list of a manga title)
3. Attempt to do a pull down refresh with mouse (hold right or left click > drag down > let go of mouse button)

### Expected behavior

Should refresh 

### Actual behavior

Nothing happens 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Samsung tab s7

### Other details

Reopening this previous issue https://github.com/tachiyomiorg/tachiyomi/issues/8455, because issue still occurs

And was supposed to have been fixed with this commit https://github.com/tachiyomiorg/tachiyomi/commit/f03a83413689923633c8ebe5634b34c566733961

But the issue still occurs on every version after 0.13.6
Maybe the fix was undone or it wasn't the root cause?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
f03a83413689923633c8ebe5634b34c566733961 hasn't been released in a stable version yet but is in preview builds.

**Comment by eyao06** [comment]
Ah, ic. 
My bad , thought it was out with the latest version
