### ISSUE TITLE
(preview) can't read local manga

### ISSUE THREAD

**Issue by qazo** [tachiyomiorg/tachiyomi#9389]
### Steps to reproduce

Latest (current) preview can't read local Manga. I understand that it is a preview release and not ship-worthy. Getting two different errors in two Manga that I'm reading. One is an "expected file size of 0" error., the second one says "file or folder not found" 

### Expected behavior

Reading volume

### Actual behavior

Cant read volume 

### Crash logs

Please read above

### Tachiyomi version

Current preview

### Android version

9

### Device

Figi

### Other details

Nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by specterflare** [comment]
Same, I get an error when trying to read my (zip foldered) local manga

**Comment by arkon** [comment]
Can you share a CBZ/ZIP file that this happens with (probably over Discord)?

**Comment by specterflare** [comment]
[Chapter 105.zip](https://github.com/tachiyomiorg/tachiyomi/files/11327534/Chapter.105.zip)

This file, along with all my others, produces a "No such file or directory" error.
