### ISSUE TITLE
Too much .nomedia files created for no reason

### ISSUE THREAD

**Issue by EstebanOD** [tachiyomiorg/tachiyomi#9390]
### Steps to reproduce

1. Download a chapter
2. Download a second chapter
3. Etc..
4. You have multiple .nomedia files created, one for each chapter

### Expected behavior

Tachiyomi already created a .nomedia files in Tachiyomi/downloads and this is sufficient to prevent the indexation of each .jpg files in the phone's gallery.
Re-creating more .nomedia files in each folder: Tachiyomi/downloads/source/manga/chapter/.nomedia is therefore useless, and will create tens of thousands of .nomedia files on your phone.

It should not create a .nomedia for each chapter. Only one in the main downloads directory.

### Actual behavior

It creates a .nomedia for each chapter.

### Tachiyomi version

0.14.6

### Android version

Android 10 EMUI12

### Device

Huawei P20 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
`.nomedia` handling is inconsistent across ROMs/versions so this is the workaround.
