### ISSUE TITLE
[Feature Request]: an ability to change the default sorting method of manga chapters 

### ISSUE THREAD

**Issue by noornee** [tachiyomiorg/tachiyomi#9393]
### Describe your suggested feature

by default, the chapters of the manga's i add to my library gets sorted `by source.`
I'm always changing the sorting method to be by `chapter numbers` in ascending order and it gets really tiring when i do this to every new manga i add to my library. It would be nice if an option is added to the settings where i could specify the default sorting method i want.

### Other details

nuh-uh! ❌

![Screenshot_20230425-135349](https://user-images.githubusercontent.com/71889751/234283706-2865d6ce-1676-4bb0-bd9f-98f2bb4c711d.png)
<hr>

yosh! ✔️

![Screenshot_20230425-140416](https://user-images.githubusercontent.com/71889751/234285205-fe90fc9f-0cdb-40f3-96c8-117abf55c5ce.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
click the 3 dots and set as default.

**Comment by noornee** [comment]
> click the 3 dots and set as default.

omg, i didn't know i could do that...thanks! ^ ^
