### ISSUE TITLE
Scamber traslator

### ISSUE THREAD

**Issue by JTwyla** [tachiyomiorg/tachiyomi#9394]
### Steps to reproduce

1. Al entrar a la fuente no carga se reinicia la app
2. Intento nuevamente se reinicia de nuevo
Esto desde que actualice la nueva version de extension 1.4.30

### Expected behavior

Me cargaba normal pero ya no

### Actual behavior

Reinicio constantemente aunque borre cache e intente entrar al Webview

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
