### ISSUE TITLE
Reload updated manga from the "latest" list

### ISSUE THREAD

**Issue by SpectreOfDark** [tachiyomiorg/tachiyomi#9395]
### Describe your suggested feature

[ENG]

It would be very useful to be able to reload all the mangas from "Browse/Sources/(Extension)/Latest" in the background without having to go into each manga and reload it manually so that they appear in the library, either with a button or by swiping.

This would only reload the ones already in the library. I would also add an option in settings to limit the updated mangas, either a fixed number or discard those that were updated more than X days ago, in case any extension had no limit in the "recent" section.

I don't know if my English is correct, just in case I leave it here in Spanish too, thank you very much for your time!

[ESP]

No sé si mi inglés es correcto, por si acaso aquí lo dejo también en español, muchas gracias por vuestro tiempo!

Sería muy útil poder recargar todos los mangas desde "Explorar/Fuentes/(Extensión)/Recientes" en segundo plano sin tener que entrar en cada manga y recargarlo de forma manual para que salgan en la biblioteca, ya sea con un botón o deslizando.

Esto solo recargaría los que ya están en la biblioteca. También añadiría alguna opción en ajustes para limitar los mangas actualizados, ya sea un número fijo o descartar los que se actualizaron hace más de X días, por si alguna extensión no tuviera limite en el apartado de "recientes".

### Other details

I think this feature would be very useful when many updates come together in this section.

I have come to think of this feature because at worst it takes me 20-30 minutes to reload most of the manga. There are times when the time to enter and then reload a single manga takes longer than it should and it takes me 2 or 3 minutes when on other occasions it only takes seconds.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
You can already do this by using the global update feature on the library settings.

**Comment by SpectreOfDark** [comment]
No, porque no se puede limitar de ninguna forma, y yo solo quiero recargar en la sección de "latest" en una extensión en especifico

**Comment by alessandrojean** [comment]
If you only want to update titles in your library that are from a certain extension, add them to a category and only include this category in the global update settings.

**Comment by CrepeTF** [comment]
If it's just a few then just open the manga and pull down to refresh them one by one. Otherwise just create a category for them and pull down on it

**Comment by SpectreOfDark** [comment]
If there were very few, I would do that, but some days 30 or 50 can be updated and in the end it takes a long time, so I was simply thinking of a function and wanted to share it, I don't know why it was closed so quickly.

**Comment by SpectreOfDark** [comment]
If it is something very complicated and that in the end it is not worth it, then it will stay there but I have spent several months with the application slowing down at times and I came up with this function.

**Comment by seew3l** [comment]
Esto puede ser complicado, ya que la aplicación carga los recientes por páginas y esto depende totalmente de la extensión, por lo que hacer una configuración global sería complicado. Además, esta búsqueda tendría que realizarse muy seguido para no saltarse mangas.

Lo que te recomiendo es crear categorías para tus mangas, y en la configuración puedes elegir qué categorías actualizar y/o excluir. Además, la aplicación tiene una configuración para omitir la actualización de mangas que tienen capítulos sin leer, que aún no han sido iniciados o que ya están completados. La verdad, no creo que estés leyendo 8000 mangas; seguramente tienes muchos ya finalizados o que aún no terminas de leer.
