### ISSUE TITLE
page up/down button to scroll page to "left to right" and "right to left" modes 

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#9397]
### Describe your suggested feature

Currently when using left to right or right to left mode, pressing page down will go to the next page even when there are part of the page that is still out of view (e.g. By using smart fit).

It would be great for ease of use if pressing page down would scroll the view first. Then if nothing is out of view, it go to the next page.

Currently page up/down button work for scrolling pages in webtoon view 

### Other details

This is more useful for tablets as they usually have more square aspect ratio than phones. Thus if using smart fit, some part of the Manga at the bottom would be chopped off.

Requiring using page down / volume button to change page, then use finger to swipe to see the chopped off page.

Instead of just using page down/volume button to change page then scroll to see the chopped off page, then press button again to go to the next page.

Also a plus if the scroll animation is optional. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
"Pan wide images when tapping" already does this, although maybe we should get rid of the "when tapping" part of the label.

**Comment by orangpelupa** [comment]
Unfortunately, The pan wide image only scrolls left to right or right to left.

It didn't pan top to bottom. When an image is taller than the screen.

**Comment by stevenyomi** [comment]
> Unfortunately, The pan wide image only scrolls left to right or right to left.
> 
> It didn't pan top to bottom. When an image is taller than the screen.

That's either #4690 or #8714.
