### ISSUE TITLE
Library's global update may crash app

### ISSUE THREAD

**Issue by dDmioko** [tachiyomiorg/tachiyomi#9400]
### Steps to reproduce

1. Be logined to shikimori
2. Go to Library
3. Ellipsis
4. Global update

### Expected behavior

All titles were updated

### Actual behavior

App was crashed

### Crash logs

tachiyomi_crash_logs.txt
--------- beginning of crash
04-16 08:17:39.198  4003  4334 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 08:17:39.198  4003  4334 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 4003
04-16 08:17:39.198  4003  4334 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 08:17:39.198  4003  4334 E AndroidRuntime: JSON input: 
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:57)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:117)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:46)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:73)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:31)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:161)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 08:17:39.198  4003  4334 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
04-27 03:13:40.526 29269 29308 E SQLiteLog: (283) recovered 387 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
04-27 03:13:41.356 29269 29412 E SQLiteLog: (284) automatic index on C(manga_id)
04-27 03:13:41.356 29269 29412 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-27 03:13:41.743 29269 29310 E anade.tachiyom: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211019.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: curtana
Device model: Redmi Note 9S
Device product name: curtana_ru

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

Redmi Note 9S

### Other details

As I understand the essence of the error is that exceptions are not tracked during the global update.
At the same time, if you try to update a specific title with a swipe down, the data will be pulled up and the application not crashes.
I think that the crash of the application due to incorrect tracking is not very pleasant to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Very confused why you didn't just update the app after reading the acknowledgment. This is already fixed.

**Comment by dDmioko** [comment]
Yup, shikimori fixed. But behaviour - not.
If the next time any tracking falls off for one reason or another, the error will repeat...
And waiting for the linked tracking to change until the next update does not look like the best solution. Plus, it will not always be possible to solve this by simply changing the URL

**Comment by arkon** [comment]
Interceptor exceptions are better caught now too.
