### ISSUE TITLE
Images not loading after resuming reading a few hours later

### ISSUE THREAD

**Issue by buthub** [tachiyomiorg/tachiyomi#9402]
### Steps to reproduce

I'm not sure if it's only relevant to certain sites/extensions or not, so I kept it in the general section. It definitely happens with Bato and Webnovel though.

1. You're in the middle of reading a manga chapter.
2. You come back several hours later.
3. The next few pages seem to load fine, but then every page after in that chapter has a Retry error message. No matter how many times you click retry (even if you go back to the manga page and refresh the page), the pages will not load.

A way to get around this is to download the chapter. Haven't tried clearing the cache, but I don't think it's the same as this issue, 
https://github.com/tachiyomiorg/tachiyomi/issues/3093

### Expected behavior

Images should load fine after resuming reading several hours later.

### Actual behavior

I get the Retry error message a few pages later instead.

### Tachiyomi version

0.14.6 (although it seems to be a long-term error)

### Android version

Android 6.0.1 & 11

### Device

Nexus 7 (2013) & Lenovo Yoga Tab 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
What extension does this usually happen

**Comment by arkon** [comment]
Those are indeed all sources where the images expire, so clearing the cache is indeed the correct solution in those cases (or reading within the expiration time or downloading beforehand).
