### ISSUE TITLE
Divide the chapters into portions.

### ISSUE THREAD

**Issue by missboa** [tachiyomiorg/tachiyomi#9403]
### Describe your suggested feature

If the chapters are long, it would be helpful to have a range selector to make it easier to find specific sections.

![Screenshot from 2023-04-27 10-07-23](https://user-images.githubusercontent.com/131508966/234758823-f90d7980-80f1-4a5c-8c87-56d0ea6d4022.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#6710
