### ISSUE TITLE
Source name in "Updates" tab

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#9407]
### Describe your suggested feature

Add the Source name in the Updates tab, so it would show:

One Piece
Chapter 30 • MangaDex

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Would be too busy, and I'm not sure what the real value is.
