### ISSUE TITLE
Add settings to lock the Browse menu

### ISSUE THREAD

**Issue by tdnzr** [tachiyomiorg/tachiyomi#9420]
### Describe your suggested feature

Problem: I want to use Tachiyomi to read and finish specific select manga I download in advance. But occasionally I instead end up seeking out new mangas via the Browse menu.

Feature request: Add some settings for users who want to use Tachiyomi mostly as a manga reader app, rather than also as a manga browsing app. (This feature request is inspired by app blockers, as well as browser extensions like LeechBlock or Freedom. Put differently, I have already installed apps like LeechBlock so I don't seek out new mangas in my mobile browsers, but currently lack a comparable option for Tachiyomi.)

The general idea here is to offer settings which would constitute roadblocks to browsing for new mangas. I don't have strong preferences for specific suggested settings. But such optional settings (all off by default) might include:

- Lock the Browse menu (and app shortcut) behind e.g. a PIN or password, or behind a random 16-128-character text you have to type into the app, or only unlock it while the smartphone is charging, or something..
- Lock or disable the WebView button.
- Allow locking the aforementioned anti-browsing settings, e.g. via a password, or only unlock them while the smartphone is charging, or something.

### Other details

PS: I already saw [this previous rejected feature request](https://github.com/tachiyomiorg/tachiyomi/issues/4521), but I think mine is a) sufficiently different to warrant a new issue, and b) it sounds easier to implement. Also, Android nowadays already has native options to limit app screentime, but not the ability to limit partial app behavior.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably need to take a step back and think about what the problem here is and how inane this request sounds.

This is almost like asking alcohol companies to put a lock on bottles to help limit their alcoholism but they still buy it. I have no interest in supporting this sort of thing, but you're free to maintain your own fork that suits any niche features desired.
