### ISSUE TITLE
Download manager 

### ISSUE THREAD

**Issue by hamoody348** [tachiyomiorg/tachiyomi#9423]
### Describe your suggested feature

Download using other apps 

### Other details

Add the ability to use download manager apps or the android downloader to download the chapters instead the internal cuz sometimes it bugs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
That's not how it works...
