### ISSUE TITLE
Manhwa dowload 

### ISSUE THREAD

**Issue by Cosmicvoid2607** [tachiyomiorg/tachiyomi#9428]
### Steps to reproduce

When I start a download, it doesn't load and gives an error in several manhwas

### Expected behavior

This shouldn't happen since I can't read anything

### Actual behavior

Start the download and it doesn't download

### Crash logs

#
![Screenshot_20230430-001223](https://user-images.githubusercontent.com/132181170/235333757-4f68131b-5901-4885-a4d7-c529924d324f.png)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

M10 45 PRO X

### Other details

Just that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
probably something wrong with the site or your download location, you can ask for help in discord.
