### ISSUE TITLE
option to disable Long press on Reader view

### ISSUE THREAD

**Issue by AbuzarGhazanfarKhan** [tachiyomiorg/tachiyomi#9432]
## sometimes the long press when reading somethings keeps opening the popup
![WhatsApp Image 2023-05-01 at 3 32 59 PM](https://user-images.githubusercontent.com/92223697/235441362-6dbd2604-1aba-4449-88f7-fa440cf085c8.jpeg)

# So instead we can add toggle in settings for readers view to turn off long press if its not needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Settings → Reader → Actions → Show on long tap.
