### ISSUE TITLE
TuMangaOnline does not download chapters

### ISSUE THREAD

**Issue by hentei009** [tachiyomiorg/tachiyomi#9437]
### Steps to reproduce

1. I select the manga I want to download 
![Screenshot_2023-05-02-07-26-45-56_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/39165912/235680297-e0b96237-f7d9-4101-ad5e-ad7660060de2.jpg)

2. I get the following notification and the manga won't download 
![Screenshot_2023-05-02-07-21-07-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/39165912/235680246-0ea930d3-6274-4207-b039-025f09697b67.jpg)

### Expected behavior

The manga should be downloaded as it has been doing 

### Actual behavior

The manga won't download 

### Crash logs

05-02 07:19:52.284  7285  7285 E IPCThreadState: attemptIncStrongHandle(104): Not supported
05-02 07:19:52.285  7285  7285 E IPCThreadState: attemptIncStrongHandle(95): Not supported
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: CPH2363_11_C.36
Device brand: OPPO
Device manufacturer: OPPO
Device name: OP533FL1
Device model: CPH2363
Device product name: CPH2363

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

OPPO Reno 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please do read what you have acknowledged.
