### ISSUE TITLE
Opening a local archive shows only DEFLATED entries can have EXT descriptor

### ISSUE THREAD

**Issue by uenoshita** [tachiyomiorg/tachiyomi#9438]
### Steps to reproduce

1. Open a local archive 
2. Click on the book
3. Clicking on the chapter 

### Expected behavior

Be able to read local zip files. Older versions worked fine.

### Actual behavior

Shows an error "only DEFLATED entries can have EXT descriptor"

### Tachiyomi version

0.14.6-5745

### Android version

10 sdk 29

### Device

Teclast P20HD_EEA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
can you provide an example file that gave you that error so when a dev looks at it they have it on hand?

**Comment by uenoshita** [comment]
Can I send the file via discord? I'm waiting in the support channel.

**Comment by Seishirou101** [comment]
you can drop the file in #support and link it in github or drop it and ping me or another support for them to upload it for you

**Comment by Seishirou101** [comment]
sample file was provided by user but too big to upload. crashlog did not show anything relevant. issue does not appear in stable and un-zipping the files and re-zipping them apparently works but previous files that worked before no longer work until unzip/rezip is done.

**Comment by Seishirou101** [comment]
[119zm8.zip](https://github.com/tachiyomiorg/tachiyomi/files/11383986/119zm8.zip)
another example provided by @uenoshita

**Comment by arkon** [comment]
Can try with the next preview build which swaps to a different implementation.
