### ISSUE TITLE
Re opening manga to previous read chapter

### ISSUE THREAD

**Issue by Dutchlikeme** [tachiyomiorg/tachiyomi#9440]
### Steps to reproduce

1. Read manga
2. Close app/switch to some other app and let the Tachiyomi app be in the background
3. Re open app
4. Manga opens to previous chapter of what you've read (Chapter 160 instead of 163)

### Expected behavior

Open on chapter 163

### Actual behavior

Opens on chapter 160, 2 chapters behind of what I've read

### Tachiyomi version

0.14.6 (16/04/2023)

### Android version

Android 13

### Device

Samsung A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GammaBurst101** [comment]
I couldn't reproduce the bug. The app opened the correct chapter. Maybe it's a device-specific bug.
App Version: 0.14.6 (16/04/23)
Android Version: 12
Device: Redmi Note 9 Pro Max

**Comment by scb261** [comment]
From #9515

> i already noticed this behavior on other phones that uses ColorOs;
OPPO ( colorOs)
Realme (RealmeUi)
Oneplus( OxygenOs )

There were also quite a few reports of this on discord

**Comment by Phoenix751** [comment]
I have the same behavior. When I leave the app in the background for a longer time it switches to the chapter I started to read.
Like I was at chapter x read to y.
After switching back the reader is at x again.
But it tracks the read status properly and re-opening the reader brings me back on track.

**Comment by HNEnd** [comment]
I have the same issue as well. When i leave the app(when reading a chapter) in the background and do something else like watch a YouTube video and come back after a while. It always jumps back to a previous read chapter even if i haven't opened that chapter the same day. But as stated before when exiting the reader and pressing resume gives me the correct chapter.

App version: 0.14.6-5863 (standard, 7d4af1f8c, 103, 2023-06-24T21:09Z)
Android version: 13 (SDK 33)
Device brand: Xiaomi
Device model: 2109119DG

**Comment by SamB** [comment]
This doesn't occur unless the system decides to kill Tachiyomi's process, which on my phone seems to happen when there's not enough RAM to go around.

The guide at https://developer.android.com/topic/libraries/architecture/saving-states should serve as a useful overview of the relevent stuff, and I think there's a dev setting to kill background activities even without memory pressure in order to test this exact type of scenario.

**Comment by arkon** [comment]
Does this still happen in newer preview builds? The progress saving was changed to happen more often.

**Comment by fotuoh** [comment]
Have this same issue happening to me. Tachyiomi keeps sending me back to previously read chapter, not keeping a proper track of progress. 

Tachiyomi version: 0.14.6 standard
Android version: 13
Device brand: Samsung 
Device model: S20 FE 5G

**Comment by fotuoh** [comment]
> Does this still happen in newer preview builds? The progress saving was changed to happen more often.

Yep, got this same issue happening to me. Tachyiomi keeps sending me back to previously read chapter, not keeping a proper track of progress. 

Tachiyomi version: 0.14.6 standard
Android version: 13
Device brand: Samsung 
Device model: S20 FE 5G

**Comment by arkon** [comment]
> Tachiyomi version: 0.14.6 standard

That's not a preview build.

**Comment by HNEnd** [comment]
I haven't come across it in normal use. I also tried to replicate it this last week but it didn't occur.
Preview r6053
