### ISSUE TITLE
Downloader connection checking only check interfaces

### ISSUE THREAD

**Issue by Lightjohn** [tachiyomiorg/tachiyomi#9441]
### Steps to reproduce

For my tablet I'm using https://github.com/Genymobile/gnirehtet (reverse USB tethering) which mean the PC is giving internet to the tablet.

I can watch manga put when I add them to downloader it says there is no internet connection because I'm not connected to any wifi.
It's true because internet is coming from a fake vpn. 

The downloader component should maybe make a true request to a website or check if a vpn is setup

### Expected behavior

Manga are downloaded normally

### Actual behavior

Downloader doing nothing and saying there is no internet

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy Tab Pro T320 WiFi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
did you turn off the restriction to only download on wifi?

**Comment by Lightjohn** [comment]
Good call that was it :) 
Thanks
