### ISSUE TITLE
Asura scans manhwa

### ISSUE THREAD

**Issue by demon456blade** [tachiyomiorg/tachiyomi#9447]
### Steps to reproduce

Open the app
Go to the manhwa
Refresh it

### Expected behavior

A new chapter should be shown

### Actual behavior

Gives an error even after migration of the manhwa
![Screenshot_2023-05-03-21-10-46-133](https://user-images.githubusercontent.com/82254389/236084988-51f5060b-0913-4fd5-9549-dd6db9e67bbb.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Red magic 7s pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
