### ISSUE TITLE
Asura Scans HTTP error 404

### ISSUE THREAD

**Issue by ansanyyi** [tachiyomiorg/tachiyomi#9448]
### Steps to reproduce

appear everytime trying to update for new chapters

### Expected behavior

Should show new chapters 

### Actual behavior

HTTP error 404 appear instead 
![Screenshot_2023-05-04-09-25-43-965_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/110255796/236088947-91c7ad67-f743-4efb-bbf9-0ab04f7bfb2c.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi 10c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16251
