### ISSUE TITLE
Source title shortening

### ISSUE THREAD

**Issue by josjuu** [tachiyomiorg/tachiyomi#9454]
### Describe your suggested feature

As an user
I would like to be able to change the source title in the  chapter list
So that I can see more relevant information

For example, we have the manga "KonoSuba: God's Blessing on this Wonderful World!". A chapter could look like the following "KonoSuba: God's Blessing on this Wonderful World! Legend of Crimson - Chapter 1 - Some kinda chapter title". 

A regex input that could either search for an user input to shorten it to "KonoSuba - Chapter 1 - Some kinda chapter title" or "Chapter 1 - Some kinda chapter title" would be a possible solution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The app already strips out the entry title from the beginning of chapter titles if they match. You could request for specific cases to be addressed at the source/extension level if possible.

Otherwise, #5270.
