### ISSUE TITLE
Add a download size preview

### ISSUE THREAD

**Issue by BriccioCulicio** [tachiyomiorg/tachiyomi#9455]
### Describe your suggested feature

It should probably appear when selecting a chapter or multiple for download and that's literally it. 

As an user who usually has a limited amount of data I, for example, would like to know if I can download only one chapter or maybe two before pressing the download button, and maybe (if not implemented for individual items), make it so it shows the total download size, for when selecting various items.

It doens't really matter how it's implemented just that it's visible in the ui maybe next to the current download button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/8193
