### ISSUE TITLE
Manga Chapter not updating

### ISSUE THREAD

**Issue by PotatoArca** [tachiyomiorg/tachiyomi#9456]
### Steps to reproduce

So after updating my Tachiyomi to the latest update, I've notice that Im getting lesser updates than the usual.
1. I usually get at least 20 chapters unread every Monday, but now I cant see the other udpates due to error http 404.
2. When I checked the webview, it gives me a no page appearance telling me the page cannot be found, but when I check the webview from the source itself, it shows me that the manga has an update but the app detected the page is not existing.
3. I have a lot of manga that are suffering from dis and its quite tiresome to migrate all of them since some of them have downloads for offline reading

### Expected behavior

![Screenshot_2023-05-06-02-15-44-914_eu kanade tachiyomi](https://user-images.githubusercontent.com/132701485/236536711-ab3d4682-9180-4167-a66c-d9154ec689b2.jpg)
![Screenshot_2023-05-06-02-16-02-228_eu kanade tachiyomi](https://user-images.githubusercontent.com/132701485/236536741-76afb70d-6914-4063-a2f6-c09f88abed23.jpg)

### Actual behavior

![Screenshot_2023-05-06-02-09-08-668_eu kanade tachiyomi](https://user-images.githubusercontent.com/132701485/236536308-0ec5d9ab-ed89-4699-a7f6-0dcfb503fdef.jpg)
![Screenshot_2023-05-06-02-09-16-117_eu kanade tachiyomi](https://user-images.githubusercontent.com/132701485/236536336-fd76dfdc-03dd-48ca-bec1-860a591d0cdb.jpg)
![Screenshot_2023-05-06-02-10-34-745-edit_eu kanade tachiyomi](https://user-images.githubusercontent.com/132701485/236536387-0df4d6a7-e861-487c-b932-3764eaf95120.jpg)

### Crash logs

No crash logs since the app is running smoothly

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi 9

### Other details

Its not just the extension im using, some of my manga from different sources are acting like that. I just used asura since most of my manga are there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16251
