### ISSUE TITLE
Enable Reactions and Comments in the source for each chapter.

### ISSUE THREAD

**Issue by hamdyahmed18** [tachiyomiorg/tachiyomi#9457]
### Describe your suggested feature

When I read a chapter of any manga from any source, I should be able to react to it and, if possible, add comments to the source website itself so that we can support them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#4336
