### ISSUE TITLE
Problem in Downloading Extensions

### ISSUE THREAD

**Issue by itsanup1** [tachiyomiorg/tachiyomi#9462]
### Steps to reproduce

Whenever I Click On Install or try to update the extension it stops without showing any message.
I Tried Everything Even reinstalling the app 

### Expected behavior

It should have downloaded in one click.

### Actual behavior

But it gets cancelled again and again....

### Tachiyomi version

0.14.6

### Android version

Android 7

### Device

Mi Redmi note 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by itsanup1** [comment]
Pls try to solve this issue as soon as possible...

**Comment by arkon** [comment]
If you're using MIUI, you can:

- try using the legacy installer setting 
- turn off MIUI Optimizations
- download from the website
