### ISSUE TITLE
Can't Read Downloaded Chapters on 0.14.6-5766

### ISSUE THREAD

**Issue by Agnath5206** [tachiyomiorg/tachiyomi#9465]
### Steps to reproduce

Reading manhwa then I notice there's a new version on notification.

Close the app and update then install the latest version Tachiyomi 0.14.6-5766.

Continue reading and press downloaded chapter error "org.apache.commons.compress.archivers.zip.ExtraFieldUtils" appears. 

Deleted downloaded chapters then read no error.

Download chapter then read same error appears.

Tried on other sources same happen. 

### Expected behavior

Can read downloaded chapter in any sources if I pressed downloaded chapters. 

### Actual behavior

When tried to read downloaded chapters in any sources "org.apache.commons.compress.archivers.zip.ExtraFieldUtils" preventing me from reading downloaded chapters

### Crash logs

--------- beginning of crash
05-06 10:19:57.353 13349 13349 E AndroidRuntime: FATAL EXCEPTION: main
05-06 10:19:57.353 13349 13349 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 13349
05-06 10:19:57.353 13349 13349 E AndroidRuntime: java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.LinearLayout{7d6ef57 V.E...... ......ID 0,1640-720,2362}
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(SourceFile:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(SourceFile:132)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(SourceFile:9)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(SourceFile:23)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:20836)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5427)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5204)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5144)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5116)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.ReaderTransitionView.bind(SourceFile:47)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonTransitionHolder.bind(SourceFile:32)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onBindViewHolder(SourceFile:42)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:1)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:43)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:979)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:59)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:835)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:61)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:72)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:6)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(SourceFile:388)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:45)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
05-06 10:19:57.353 13349 13349 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:813)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.View.layout(View.java:23321)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6553)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4009)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3441)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2364)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9220)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1139)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:918)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:834)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1112)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:241)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:342)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8128)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
05-06 10:19:57.354 13349 13349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
--------- beginning of main
05-07 07:50:51.245 23396 23626 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#6](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
05-07 07:50:51.948 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:51.960 23396 23626 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#6](f:0,a:5) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
05-07 07:50:52.602 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.617 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.636 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.651 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.668 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.683 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.700 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.719 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.735 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.753 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.768 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.797 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:52.815 23396 23457 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
05-07 07:50:55.566 23396 23457 E OpenGLRenderer: EglManager::makeCurrent mED = 0xb400006e9a4c74d0, surface = 0x0, mEC = 0x6e3a4f61a0, error = EGL_SUCCESS
05-07 07:51:24.265 23396 24008 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#7](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
App version: 0.14.6-5766 (standard, 1b25290d3, 103, 2023-05-06T21:09Z)
Android version: 12 (SDK 31)
Android build ID: LG7n-H892ABCD-S-GL-230320V1330
Device brand: TECNO
Device manufacturer: TECNO
Device name: TECNO-LG7n
Device model: TECNO LG7n
Device product name: LG7n-GL

### Tachiyomi version

0.14.6-5766 

### Android version

Android 12

### Device

Tecno Pova 4 LG7n

### Other details

![Screenshot_20230507-065039](https://user-images.githubusercontent.com/34466418/236651164-31637acb-9472-4696-bb27-af8fe7d9ea3d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by randomgamming027** [comment]
Manhwa but Screenshot is Manhua LOL

**Comment by JuniPlum** [comment]
Yea, I'm having this issue too.

**Comment by JuniPlum** [comment]
Yea, I'm having this issue too.
![Screenshot_2023-05-07-08-27-36-768_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/79726414/236652084-e9a80147-445b-4f57-b300-bdb0805c7fd6.jpg)
