### ISSUE TITLE
Http error 404

### ISSUE THREAD

**Issue by Kshn12017** [tachiyomiorg/tachiyomi#9466]
### Steps to reproduce

1. Download Asura extension.
2. Browse to the Asura
3. Click on any comic
4. It will either won't show any data or show data but when you reload/ refresh it, you'll get the error

### Expected behavior

The new chapters should be added to the chapter list when refreshed if they were not present.

### Actual behavior

A Toast appeared saying "HTTP error 404"

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Device

Redmu Note 10 pro max

### Other details

![Screenshot_2023-05-07-06-22-48-291_eu kanade tachiyomi](https://user-images.githubusercontent.com/81675155/236652314-eda7eb6c-248b-4c66-ac8d-b658d606cf39.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by Gaurav-Paul** [comment]
I'm having the same problem, so I tried looking up the link through webview and it said that the page no longer exists so I assumed that they removed the series but after checking the series list I confirmed that they didn't and that the only difference was that the link for the new manhwa page had some number that the webview version didn't, although I have only noticed this with the ones where I have an issue of the chapters not updating, the other series that do update have the updated version of the url for some reason
