### ISSUE TITLE
Download ahead while reading doesn't work.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#9471]
### Steps to reproduce

1. Enable download ahead while reading.
2. Start reading a title with atleast 2 chapters downloaded.

### Expected behavior

Tachiyomi downloads ahead the number of chapters ahead as specified in the settings.

### Actual behavior

Tachiyomi doesn't download the chapters.

### Tachiyomi version

0.14.6 r5767

### Android version

Android 13

### Device

Samsung S21 FE

### Other details

Have tried various combinations of different amounts of chapters to download ahead with random number of chapters already downloaded and nothing seems to work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DennyRodrigues** [comment]
I've worked on this issue and created a PR to solve it. 
Link: https://github.com/tachiyomiorg/tachiyomi/pull/9640
