### ISSUE TITLE
Error on opening large downloaded cbzs.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#9474]
### Steps to reproduce

1. Download a chapter with a large size. (>250MBs)
2. Try to open the downloaded chapter.

### Expected behavior

The chapter opens and you can read normally.

### Actual behavior

The chapter doesn't open.

### Tachiyomi version

0.14.6 r5767

### Android version

Android 13

### Device

Samsung S21 FE

### Other details

![Screenshot_20230508_025358_Tachiyomi](https://user-images.githubusercontent.com/63903377/236703349-e94bfdcc-352d-490b-abf4-b314063183e8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Closed by 6f59c6c6bb12f1ef123abd418001c7a86d43ef7a
