### ISSUE TITLE
Categories swipe Twitching

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#9475]
### Steps to reproduce

1. swipe to the next library categories 

### Expected behavior

at the categories tab the shadow/indicator/idk sliding smooothly 

### Actual behavior

at the categories tab the shadow/indicator/idk sliding back a little bit(twitching)
*sliding normally in tachi stable

https://user-images.githubusercontent.com/16263232/236711063-a87e7abd-eb8d-4cc9-a776-5a97838a4265.mp4

### Tachiyomi version

r5767

### Android version

A13

### Device

Redmi 8

### Other details

also swiping categories is heavier compared to non compose

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I think this is improved in Preview already.
