### ISSUE TITLE
On Tachiyomi Preview: Menus are not deploying from the bottom.

### ISSUE THREAD

**Issue by Raizanad** [tachiyomiorg/tachiyomi#9480]
### Steps to reproduce

1. Enable full screen touch gestures without the bottom buttons on display.
2. Use the app.

### Expected behavior

Menu deploy from bottom with no gap.

### Actual behavior

There is a gap for the button on display.

### Tachiyomi version

Preview

### Android version

Android 10

### Device

Xiaomi Mi 8

### Other details

If I enable the buttons at the bottom then it works fine, the gap is because it is setting the deployment with them in mind apparently. In Tachiyomi Stable menus worked fine.
![1683573427414](https://user-images.githubusercontent.com/131222736/236913697-311a65b3-dc98-49e7-8d95-f460a2529968.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This will happen on any ROM with a bad implementation of hiding the navbar.

**Comment by Raizanad** [comment]
@arkon pinging because I don't know if you receive notifications for closed issues (since I don't).

**Comment by arkon** [comment]
The underlying `Dialog` component that Compose provides, which is what the rewrite of that UI ended up using, doesn't handle insets properly right now. If it ever gets fixed upstream, then we'll pick it up then.
