### ISSUE TITLE
Fails to restore a backup on a different phone

### ISSUE THREAD

**Issue by mks-h** [tachiyomiorg/tachiyomi#9483]
### Steps to reproduce

- On one phone, backup the library
- On the other phone, restore the library

### Expected behavior

Library restoration

### Actual behavior

Fails (doesn't crash) with the following error message:
```
kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 3
```

### Tachiyomi version

0.14.6

### Android version

Android 11 / 12

### Device

Sony Xperia Z3 Compact / Xperia 10

### Other details

From the phone which is being backed up:
```
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: lineage_z3c-userdebug 11 RQ3A.211001.001 4ed284f7bf
Device brand: Sony
Device manufacturer: Sony
Device name: z3c
Device model: Xperia Z3 Compact
Device product name: lineage_z3c
```

From the phone which is being restored:
```
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 32)
Android build ID: lineage_kirin-userdebug 12 SQ3A.220705.004 fdcc822340
Device brand: Sony
Device manufacturer: Sony
Device name: I4113
Device model: I4113
Device product name: I4113
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Are you sure you're using the valid backup file?

**Comment by mks-h** [comment]
You are right, I have accidentally used `tachiyomi-v0…` the apk, instead of `tachiyomi_2.…` the proto.gz, due to ellipses in the grid view of the file chooser.
