### ISSUE TITLE
Asura scans 404 error

### ISSUE THREAD

**Issue by BangtanExo27** [tachiyomiorg/tachiyomi#9487]
### Steps to reproduce

First step : reload or refreshing manga to get new chapters
Second step : HTTP error 404 result, no new chapters refreshed

### Expected behavior

Chapters should refresh normally without error, I checked the website, and there is no problem with Asura scans we page. All new chapters that are not refreshing are on the webpage. 

### Actual behavior

I refreshed multiple Mangas on asura scans and almost 70 of my manga are showing 404 error 

### Crash logs

--------- beginning of main
05-10 17:41:15.934  6314 27261 E DatabaseUtils: Writing exception to parcel
05-10 17:41:15.934  6314 27261 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=27511, uid=1000 requires the provider be exported, or grantUriPermission()
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:757)
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:630)
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1028)
05-10 17:41:15.934  6314 27261 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1001)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 10 (SDK 29)
Android build ID: MAR-L01MEB 10.0.0.266(C316E3R1P1)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWMAR
Device model: MAR-LX1A
Device product name: MAR-LX1A

### Tachiyomi version

App version: 0.14.6 

### Android version

Android 10

### Device

HUAWEI P30 LITE

### Other details

![Screenshot_20230501_192030_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/97855182/89c28812-1a7c-446f-b077-abf571b491ca)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
>* [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Read what you acknowledge. Also already reported https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16251

**Comment by BangtanExo27** [comment]
Hi there, sorry about that, only acknowledged it because I didn't know where to find the extension repository, figured someone else might know as long as I mentioned it. 😅
