### ISSUE TITLE
The covers are not updating for 1stkissmanhua 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi#9490]
### Steps to reproduce

The images of cover are not showing for 1st kiss manhua extension

### Expected behavior

The cover should have pictures 

### Actual behavior

But the covers are without picture 

### Tachiyomi version

R5774

### Android version

Android 13

### Device

One plus 8t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Read what you acknowledge
