### ISSUE TITLE
Adapt Thachiyomi for IOS

### ISSUE THREAD

**Issue by byteboys** [tachiyomiorg/tachiyomi#9498]
### Describe your suggested feature

I think the Devs could make an adaptation of tachiyomi for IOS, as there are many IOS users who wanted to enjoy this incredible experience that is Thachiyomi. IOS users. I hope you hear me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/faq/#will-there-be-an-ios-version
