### ISSUE TITLE
Tachiyomi renames (suffixes) download folders with _tmp on upgrade between r5774 to r5789

### ISSUE THREAD

**Issue by Amejonah1200** [tachiyomiorg/tachiyomi#9503]
### Steps to reproduce

Upgrade to [r5789](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r5789)

### Expected behavior

Not "migrate", no difference.

### Actual behavior

Puts a suffix "_tmp" on current folders
![image](https://github.com/tachiyomiorg/tachiyomi/assets/50181314/0cb9ed78-5446-4ac4-b24b-6a0752a1bc30)

### Tachiyomi version

r5789

### Android version

Android 12

### Device

Samsung Note 10

### Other details

I don't know if it just renames them, or literally copies them over, as my phone was getting hot, and it took too long, so I stopped tachi and downgraded back.

**Comment by FlaminSarge** [comment]
I am also seeing this behavior. On launch, the app stalls on loading and attempts to rename all source download folders to have the _tmp suffix.

**Comment by scb261** [comment]
One more person with the same issue on discord

```
App version: 0.14.6-5789 (standard, a3a9c8ac8, 103, 2023-05-14T02:52Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: dandelion
Device model: M2006C3LII
Device product name: dandelion_in
```

> Also, I had this issue in the morning when I was on 5787. I had updated it to 5789, hence it's showing 5789 above. And my downloads are on SD card

![](https://media.discordapp.net/attachments/349436576037732355/1107170074378391642/IMG_20230514_102553.jpg)

**Comment by arun07as** [comment]
> One more person with the same issue on discord
> 
> ```
> App version: 0.14.6-5789 (standard, a3a9c8ac8, 103, 2023-05-14T02:52Z)
> Android version: 10 (SDK 29)
> Android build ID: QP1A.190711.020
> Device brand: Redmi
> Device manufacturer: Xiaomi
> Device name: dandelion
> Device model: M2006C3LII
> Device product name: dandelion_in
> ```
> 
> > Also, I had this issue in the morning when I was on 5787. I had updated it to 5789, hence it's showing 5789 above. And my downloads are on SD card
> 
> ![](https://camo.githubusercontent.com/6438e72f5c4e9aa2315a00bc35897d8579adce3e33f18c1a605a9157ff369065/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3334393433363537363033373733323335352f313130373137303037343337383339313634322f494d475f32303233303531345f3130323535332e6a7067)

To add more details, there are two Asura Scans folders in the screenshot because when I downloaded new chapters, a new Asura Scans folder was created

**Comment by TheOnlyZii** [comment]
i got the same issue 
the app does stalls for quite sometime after updating then after i finally got it it dosent recognized all of my previously downloaded chapters

`App version: 0.14.6-5789 (standard, a3a9c8ac8, 103, 2023-05-14T02:52Z)
Android version: 13 (SDK 33)
Android build ID: TKQ1.220829.002 release-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: alioth
Device model: M2012K11AG
Device product name: alioth`

**Comment by FlaminSarge** [comment]
r5745 appears unaffected. It may be #9453

**Comment by scb261** [comment]
Looks like it happens both on Samsung and MIUI, but I can't reproduce it on my MIUI, Andoid 12.

One more report from discord (sy fork, but the same issue):

```
App version: 1.9.3 (standard, f37b66130, 54, 2023-05-14T04:07Z)
Preview build: 520
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.T500XXU4CWD2
Device brand: samsung
Device manufacturer: samsung
Device name: gta4lwifi
Device model: SM-T500
Device product name: gta4lwifixx
```

**Comment by FlaminSarge** [comment]
The rename no longer occurs after the above fix but the app still stalls on startup.
