### ISSUE TITLE
Add feature to compress images with wsrv.nl proxy

### ISSUE THREAD

**Issue by 3ekodomo** [tachiyomiorg/tachiyomi#9509]
### Describe your suggested feature

wsrv.nl is [open source](https://github.com/weserv/) project & an image cache & resize service. That Manipulate images on-the-fly with a worldwide cache. And have CloudFlare CDN. (It can be used as  image compressor.)

With this, the size of manga pic(pages) can be manipulated , decreases as need. Saving a lot of data.
All information and API reference is available [here](https://images.weserv.nl/docs/).

### Other details

Here is example of result : <https://images.weserv.nl/docs/size.html>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Relevant comment from back when there used to be a similar alternative requiring heroku 

https://github.com/tachiyomiorg/tachiyomi/issues/6830#issuecomment-1086653234

**Comment by 3ekodomo** [comment]
@curche but it doesn't require user run heroku server.
The server is already deployed by it's developer though;
And API is ready to use no need of API key or anything.

**Comment by 3ekodomo** [comment]
Tested the API with some site, not work as intended.
So, closing the issue
