### ISSUE TITLE
Add option to copy & share chapter url

### ISSUE THREAD

**Issue by 3ekodomo** [tachiyomiorg/tachiyomi#9510]
### Describe your suggested feature

**Hey there, first of all thanks for maintaining this app to all collaborators!**

Please, can you add option to **copy & share chapter URL**. That'll surely help to share specific chapter with others and save chapter url to notes with HOf copy URL.

## Here is example:

![Shareandcopy](https://github.com/tachiyomiorg/tachiyomi/assets/133636085/c2f205a0-d499-41c4-9609-20bfb91b5094)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Open chapter -> Open WebView -> Share

**Comment by 3ekodomo** [comment]
> Open chapter -> Open WebView -> Share

AL: "Are you sure you pushed the last copy edit live?"

Me: "Yes it is live and I tested it."

AL: "I just looked and it still shows the old copy text."

Me: "Did you try clearing your browser cache?"

AL: "What's that? How do I do that? Can't you just have the site do that for me?"

JOKES ASIDE, 
Wow, quite a reply ! [🙂🙂](QXJlIHlvdSBmdWtpbmcgZHVtYiA/)
@AntsyLich

**Comment by 3ekodomo** [comment]
Please assign this to the appropriate person.

**Comment by AntsyLich** [comment]
What do you mean act professional? I didn't even close the issue i just gave a solution that i thought would work
