### ISSUE TITLE
Manga library automatic refresh rate

### ISSUE THREAD

**Issue by shinobs** [tachiyomiorg/tachiyomi#9516]
### Describe your suggested feature

In older versions, we could set the automatic refresh rate of the manga library to 1 hour or 3 hours or more. Now, the minimum is set to 12 hours :

![Screenshot_20230518-130704](https://github.com/tachiyomiorg/tachiyomi/assets/132357254/7ab7c2f7-afe1-42cf-ade6-b628c637ac4d)

Is it possible to have the old choices back? It's more convenient than refreshing manually every few hours.

Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Why would you need to check for updates every hour when it releases once a week at best

**Comment by shinobs** [comment]
Because there are a few updates everyday when you have a big library. A refresh every 3 or 6 hours was more convenient before. But, nevermind...

**Comment by CarlosEsco** [comment]
> hen you have a big library. A refresh every 3 or 6 hours was more convenient before. But, nevermind...

So you think having a big library and hitting all the sources every 3h makes sense when <1% are getting probably getting updated each day

**Comment by shinobs** [comment]
I understand your point. You don't need to be so haughty... The option was there and it was convenient. I understand that it won't come back. 

You guys need to relax on your tone when you don't agree with someone else. Have a good one.
