### ISSUE TITLE
Colored pages download in black and white

### ISSUE THREAD

**Issue by dbjordan** [tachiyomiorg/tachiyomi#9517]
### Steps to reproduce

1. Open app.
2. Select a manga or manhwa that has colored pages.
3. Open any chapter and let the chapter load.
4. The spinner and pages display in black and white.

### Expected behavior

The pages that display should be in color if they are colored pages.

### Actual behavior

Colored pages display in black and white as opposed to in color.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy S22 Ultra

### Other details

![Screenshot_20230518_091458_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/4612712/48e65f6e-0db5-4bf8-9c54-705846b7a3b1)
![Screenshot_20230518_091452_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/4612712/f25e89f5-6001-49de-9c30-4642ec15153b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dbjordan** [comment]
Hello @Seishirou101, can you direct me to where those custom filters are. I'm not seeing it in the docs and I'm obviously looking in the wrong places in the app.

**Comment by Seishirou101** [comment]
its in the reader settings, if you still can't find it you can go on discord and ask for help.
