### ISSUE TITLE
Ability to Grouping Categories for Easy Navigation

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#9518]
### Describe your suggested feature

Since I have many Categories in my Tachiyomi and it would take long times to scroll from left to right, It would be great features for other people who have issue like me. 

I think microsoft edge grouping tabs would be best example in this case:

1. Can choose the group or can make new group
<img width="364" alt="image" src="https://github.com/tachiyomiorg/tachiyomi/assets/82807360/a96d5e53-b3f4-455e-8b6d-051004758835">

2. Can have many groups
![image](https://github.com/tachiyomiorg/tachiyomi/assets/82807360/62e85a82-3eca-4cda-a019-ef4f21ba7ba2)

3. Can collapse or expand the group 
![image](https://github.com/tachiyomiorg/tachiyomi/assets/82807360/f770d1fa-0ceb-4952-bd55-1c308e36d39a)

Thanks in Advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#1803
