### ISSUE TITLE
Automatic updates not working

### ISSUE THREAD

**Issue by FeralWriting** [tachiyomiorg/tachiyomi#9521]
### Steps to reproduce

1. Turn on automatic updates.
2. Select time frame, I chose daily.
4. Wait.

### Expected behavior

I should be seeing updated chapters in the updates tab and the "library last updated" should be at most 24 hours ago, since my automatic updates should be daily. Also, I should be getting notifications telling me how many chapters had updates and how many entries were skipped.

### Actual behavior

Nothing happens and I have to update myself manually.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Google Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
What does Settings > Advanced > Worker Info say?

**Comment by FeralWriting** [comment]
Id: aca508c6-2eab-4d9c-8c25-34b7e5e49018
Tags:
 - eu.kanade.tachiyomi.data.updater.AppUpdateJob
 - UpdateChecker
State: ENQUEUED

Id: 419c3920-2bbb-461a-840e-50b1d4e371cb
Tags:
 - ExtensionUpdate
 - eu.kanade.tachiyomi.extension.ExtensionUpdateJob
State: ENQUEUED

Id: 9c948e64-a5e5-4ce2-ac6e-d69f3f501723
Tags:
 - BackupCreator
 - eu.kanade.tachiyomi.data.backup.BackupCreatorJob
State: ENQUEUED

Id: f84ca0c2-2486-4d1e-a099-af3811514ae5
Tags:
 - eu.kanade.tachiyomi.data.library.LibraryUpdateJob
 - LibraryUpdate
State: ENQUEUED

-
-

**Comment by arkon** [comment]
Are you sure you don't have some restrictions set up?

**Comment by FeralWriting** [comment]
What do you mean by restrictions?

**Comment by arkon** [comment]
The setting under the setting that you set to daily.

**Comment by FeralWriting** [comment]
Ah, the only restriction was "Only on Wi-Fi". But my phone was connected to
the wifi during that time

**Comment by arkon** [comment]
The debug info in v0.15.0 now says when the next scheduled run is too, so you could reference that. If it never seems to run, I'd assume the system is killing it for some reason but there isn't much we can do beyond the usual suggestions to disable battery optimization / Don't Kill My App stuff already present in the app's advanced settings.
