### ISSUE TITLE
 Turn OFF/ON Pop-Up "Are Your Sure?" notify When adding a series to Library

### ISSUE THREAD

**Issue by Chennick17** [tachiyomiorg/tachiyomi#9522]
### Describe your suggested feature

Feature that can turn off/on turn off/on pop up "Are Your Sure" notify When adding a series to a Library

### Other details

![Screenshot_2023-05-20-02-40-20-942-edit_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/86345327/c725ace9-570a-4c5e-9ef5-9eec6fb9a75b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Very curious why are you adding the same thing over and over again that it's irritating

**Comment by Chennick17** [comment]
> some series I've been reading have corrupted or error chapters on it. Its not tachiyomi fault the error has been on website, so here's the thing I'm going around to one particular extension and add same series to read but this pop-up always show don't get me wrong its Great to have this feature but sometimes i want pause it shows.
