### ISSUE TITLE
Speech Bubble Zoom

### ISSUE THREAD

**Issue by AdityaAnand99** [tachiyomiorg/tachiyomi#9524]
### Describe your suggested feature

There's only one thing that wish Tachiyomi had and it's Google's BUBBLE SPEECH ZOOM. It uses machine learning to recognise speech bubbles and intelligently zoom into them for easier reading. Move from bubble to bubble one tap at a time, and still allows to keep the full-page experience. This vastly improves the reading experience and allows to enjoy the comic without zooming anywhere, especially on devices with smaller screens, like phones. The difference is night and day. 

Here's a demo. https://www.theverge.com/platform/amp/2016/7/21/12229074/google-play-books-bubble-zoom-machine-learning-sdcc-2016

Bubble Zoom on Google Play Books: https://youtu.be/1v7dS8i5G9U

Seems like the guys over at [Seeneva](https://github.com/Seeneva/seeneva-reader-android) have built an **open source** manga/comic reader with this feature. Maybe there is a way to work with them to include such features into Tachiyomi :)

### Other details

I requested the exact same thing about 2 years ago but was declined due to lack of open source ML models. But now that some folks have already done the heavy lifting and made the ML models open source, I am hoping it should be easier to implement.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This is not J2K repository and this has been denied for Tachiyomi for 4 reasons total not 1

**Comment by AdityaAnand99** [comment]
Sorry for the typing mistake, my bad. But what are the other 3 reasons?

**Comment by AntsyLich** [comment]
Check arkon's comment on the original feature request

**Comment by arkon** [comment]
As far as I can tell, Seeneva didn't open source their model.

You could ask the maintainers of that project if they're interested in combining efforts by contributing to Tachiyomi.
