### ISSUE TITLE
"No pages found" In downloaded chapters after deleting Images

### ISSUE THREAD

**Issue by JHidro** [tachiyomiorg/tachiyomi#9529]
### Steps to reproduce

1. Download a manga/manhwa/manhua chapter from an extension (in this case we can use  mangadex and manga at)
2. Download Google files and go to images
3. Find images that shows the chapter you downloaded
3. Delete all of those images
5. Go back to tachiyomi and try opening the chapters that had their images deleted from Google files 

### Expected behavior

Should open the downloaded chapter

### Actual behavior

Gives a "No pages found" message

### Tachiyomi version

0.14.6

### Android version

Android 9

### Device

Razer phone 2

### Other details

My storage was filled with something in images so I checked in Google photos without any luck, when I downloaded Google files I found over 25GB of images and it looks like they're all coming from downloaded tachiyomi chapters, full manga, manhwa, and manhua's from all of my current extensions. 

I deleted over half of the images that were there and now I'm having a problem where I'd go to open a chapter I've downloaded before and it says "page not found". Some downloaded chapters work fine, I'm guessing it's because those were the other half of the images I haven't deleted.

I've tried reinstalling the app and restoring backed up data, but it still shows that those chapters are downloaded and gives the same message. I've also tried reinstalling the extensions but it hasn't changed anything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Delete the empty folders.

**Comment by JHidro** [comment]
> Delete the empty folders.

Thank you so much!!! Found the folders

**Comment by arkon** [comment]
Either using a proper file manager (not the images list in Google Photos or Google Files), or just delete the now-empty downloaded chapter from within the Tachiyomi app.
