### ISSUE TITLE
Ensure that covers can always be displayed

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#9534]
### Describe your suggested feature

Ensure that a cover can always be displayed.Tachiyomi should cache covers forever and only delete/change them if it can successfully download a new cover. 
It should apply only to entries that had a cover successfully downloaded before and that (for some reason) tachi is not able to download anymore like in the video.

https://github.com/tachiyomiorg/tachiyomi/assets/75091899/43e2271b-5861-4e8f-a510-f120496ac43e

### Other details

As you can see in the video that entry doesn't have a cover, but in the past tachi had it downloaded so why did the app delete it the moment it couldn't fetch(or find) a new one? it is better to keep the one that already exist until it finds a new onr.

If it was previously downloaded and all of a sudden the app can't fetch the cover anymore tachi should keep the previous one UNTIL it is able to fetch a new one. Doing so the entries can always have a cover on.
If can be only applied to entries in the library or all entries, you choose.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#8476
