### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by yuasenpai** [tachiyomiorg/tachiyomi#9537]
### Describe your suggested feature

More custom for people to do and make it look cool

### Other details

Customization
Like custom background and more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Theme colors may eventually be more customizable once the app is fully Compose but otherwise there's no active plans to make the app harder to maintain.
