### ISSUE TITLE
Grid size slider may shrink as label text gets longer

### ISSUE THREAD

**Issue by Lzmxya** [tachiyomiorg/tachiyomi#9538]
### Steps to reproduce

1. Open the library settings dialog and go to the display tab
2. Adjust the grid size slider between values 9 and 10
3. Issue occurred

### Expected behavior

The slider should not be resized when sliding.

### Actual behavior

The slider may be resized when sliding.

### Tachiyomi version

0.14.6-5796

### Android version

Android 13

### Device

Google Pixel 4

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/5507263/a5e8b37d-215b-4610-addb-9c053e77604a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Artemis-CtrlAltDel** [comment]
Hi

I'm working on this issue
