### ISSUE TITLE
App update download progress notification still present after download complete. 

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#9553]
### Steps to reproduce

1. Check for an update.
2. See the notification for the download progress.

### Expected behavior

Download progress notification goes away after download is complete and is replaced with install notification.

### Actual behavior

Download progress notification is still present with the install notification.

### Tachiyomi version

r5796

### Android version

Android 13

### Device

Samsung S21 FE

### Other details

![Screenshot_20230528_103828_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/63903377/de6e716c-4917-473b-9878-475c56df99ae)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ve1mi** [comment]
Fix this please, otherwise every update in the preview is annoying
