### ISSUE TITLE
Sliding doesn't work properly

### ISSUE THREAD

**Issue by Fiea0** [tachiyomiorg/tachiyomi#9555]
### Steps to reproduce

1. I slide my finger on the screen to scroll down

### Expected behavior

If I slide hard enough, it should keep scrolling down for a while after I remove my finger 

### Actual behavior

No matter how hard I slide my finger to scroll, the scrolling stops the moment I left my finger, it's like the screen is glued to my finger

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Galaxy A70

### Other details

Sometimes it starts working properly again but that's rare the majority of the time it's not working properly,

I should also mention, I don't face this problem when I'm in the reader but mostly in Library, updates, history, browse

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce this.

This is almost certainly an upstream issue with Jetpack Compose for specific circumstances, so there's nothing actionable here from us other than updating as they release new versions and for you to pray that it was somehow addressed.
