### ISSUE TITLE
Sort By Source not working

### ISSUE THREAD

**Issue by Lukyzzz** [tachiyomiorg/tachiyomi#9559]
### Steps to reproduce

1 - Choose a extension that post the same chapter from multiple sources.    (Like "Comick" or "MangaDex")
2 - Choose a manga/manhwa that have the same chapters by multiple sources.       (Like "Eternal Club", for example)
3 - Go to the "Sort" option on the Manhwa and try to sort "By Source"

### Expected behavior

Sort by Source, like..... Grouping the chapters from the same source together, like

Chapter 1 - Source x
Chapter 2 - Source x
Chapter 3 - Source x
Chapter 1 - Source y
Chapter 2 - Source y
Chapter 3 - Source y

### Actual behavior

It doesn't, it just group "By the Chapter Number" like

Chapter 1 - Source x
Chapter 1 - Source y
Chapter 1 - Source z
Chapter 2 - Source x
Chapter 2 - Source y
Chapter 2 - Source z

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy M62

### Other details

The way it is, you read the same chapters over and over again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
"By source" means the same sort the site returns in or default sort. 
"By chapter number" and "By upload date" is for when the source returns the chapter in wrong order

**Comment by arkon** [comment]
Those are scanlators, not sources.

**Comment by Lukyzzz** [comment]
Oh, mb, so there's no option for sort by scanlator then ? Then I'll make a feature request about that if there's none already

**Comment by arkon** [comment]
There's #969
