### ISSUE TITLE
Could not bypass Cloudflare 

### ISSUE THREAD

**Issue by ljw2803** [tachiyomiorg/tachiyomi#9562]
### Steps to reproduce

1. Use Jinman Tiantang  extension.
2. Click one certain manga to enter 

### Expected behavior

I hope it can be fixed and we can click a certain manga and the chapter can be loaded so that we can read the content.

### Actual behavior

While using the Jinman Tiantang extension, the app could show the cover. But after click a certain manga or book the app is just loading for a while and says "could not bypass Cloudflare".

The situation above have only happened at Jinman Tiantang.

### Tachiyomi version

0.14.6

### Android version

Android 9

### Device

Mi 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

在插件设置里更换镜像 URL，关闭 VPN，或者在应用高级设置里更换 User Agent。
