### ISSUE TITLE
Filtering releases by source/extension in the library

### ISSUE THREAD

**Issue by LowTechRider** [tachiyomiorg/tachiyomi#9563]
### Describe your suggested feature

It would be nice to filter your favorited releases by their extensions, it would make merging from a OOD/EOL extension easier. Right now you have to check every item by itself to confirm their source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You can already tap the source name from the details screen to filter the library by that source name.
