### ISSUE TITLE
Tachiyomi preview crash after being left open in background

### ISSUE THREAD

**Issue by von-wa** [tachiyomiorg/tachiyomi#9564]
### Steps to reproduce

1. Open a chapter
2. Open another app without closing the Tachiyomi app
3. Wait a few minutes
4. Re-open the tachiyomi app

### Expected behavior

The app should be working normally

### Actual behavior

The app crashes after a few seconds

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/11617295/tachiyomi_crash_logs.txt)

### Tachiyomi version

Preview r5813 (the crash started happening from the last version)

### Android version

Android 8

### Device

Samsung A5 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
04-04 02:02:43.036  7950  7950 E AndroidRuntime: FATAL EXCEPTION: main
04-04 02:02:43.036  7950  7950 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 7950
04-04 02:02:43.036  7950  7950 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.debug/cache/chapter_disk_cache/85b0ec27e4067a7b96d6ff1bd2e6ddb8.0 (No such file or directory)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at java.io.FileInputStream.open0(Native Method)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(HttpPageLoader.kt:15)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$setImage$2.invokeSuspend(WebtoonPageHolder.kt:6)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-04 02:02:43.036  7950  7950 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
```
