### ISSUE TITLE
Is there any hope of getting tachiyomi for pc in the future 

### ISSUE THREAD

**Issue by as-fuck** [tachiyomiorg/tachiyomi#9571]
### Describe your suggested feature

I'd like to have tachiyomi in pc without using any other emulator apps like LD Player and so...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
The closest there is and will be for Tachiyomi for PC is the built-in WSA for Windows 11

**Comment by ArthurKun21** [comment]
I am using Tachiyomi in WSA for windows 11 and the current preview version of WSA supports file sharing to the windows

https://github.com/microsoft/WSA/discussions/321
