### ISSUE TITLE
[Request] Ability to edit the title of manga 

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi#9572]
### Describe your suggested feature

>In tachiyomi when you add manga to your library you should be able to edit the manga name to whatever you like (It should be helpful if you want the manga title to be in your preferred language, like martial peak instead of peak of martial arts . )

>If possible the option to edit tags and sheeting the status would be appreciated (It is possible in TachiJ2K .

### Other details

The following is available in TachiJ2K . Maybe you could copy the code

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#4398
