### ISSUE TITLE
Trying to downloading multiple chapters behaves strangely

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#9577]
### Steps to reproduce

1. Open Manga
2. Select bunch of chapters
3. Put them all for download

### Expected behavior

All chapters get put in queue at the same time and start downloading one by one

### Actual behavior

The first chapter starts downloading
After it completes, the rest of the chapters are put to download and start downloading one by one

Video attached: https://imgur.com/a/w8ANPKE
![](https://imgur.com/a/w8ANPKE)

### Crash logs

N/A

### Tachiyomi version

r5813

### Android version

12

### Device

SM-N770F

### Other details

Worked like expected fine on stable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Two-Ai** [comment]
Might be an issue with [`statusFlow`/`progressFlow`](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt#L376-L403).
