### ISSUE TITLE
Source Filters don't reset

### ISSUE THREAD

**Issue by AwkwardPeak7** [tachiyomiorg/tachiyomi#9585]
### Steps to reproduce

1.  Apply some specific filter on a source
2a) Tap reset on filter sheet
2b) exit out of browse screen

### Expected behavior

filters reset to default state

### Actual behavior

filters remain until app restart

### Tachiyomi version

r5829

### Android version

Android 13

### Device

Tecno Spark 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mosab01** [comment]
does this happen to all sources or does it only occur to only one
