### ISSUE TITLE
Consolidate Local Source and Downloads locations

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi#9591]
### Describe your suggested feature

Local Source currently reads from a hardcoded location of `Tachiyomi/local` in every mounted storage disk. This is:

- Confusing due to its difference from a customizable Downloads location
- Confusing because it merges multiple storage locations
- Slow because it reads from multiple locations

It'd be simpler to just put it with the Downloads location, e.g. for a Downloads location set as `Tachiyomi/downloads`: `Tachiyomi/downloads/local`.

Alternatively, we truly consolidate all locations so for a location set as `Tachiyomi`, the app handles hardcoded subpaths of `local`, `downloads`, and `backups` within it. That would probably be more ideal for handling scoped storage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ArthurKun21** [comment]
btw, I just did think of something to be added to the feature request.

If possible, all of the local manga will be automatically added to a category named `local`. If the category doesn't exist It will create it first then add all of the local manga there

**Comment by arkon** [comment]
We now use a single unified location so that we can eventually use scoped storage permissions.

Based on the chosen location, it follows the previous default structure of:

```
/sdcard/emulated/0/Tachiyomi/ (or user-selected directory)
|-- backups
|   |-- automatic
|-- downloads
|-- local
```

**Comment by BrutuZ** [comment]
```
...
|-- covers
```
For custom covers in the future, maybe, hopefully 😇
