### ISSUE TITLE
Update metadata for bato.to extension

### ISSUE THREAD

**Issue by Kiaasma** [tachiyomiorg/tachiyomi#9594]
### Steps to reproduce

Just browse the extension a few times and you will notice that some covers don't load properly even they they do have covers.
![Screenshot_20230607-094753](https://github.com/tachiyomiorg/tachiyomi/assets/112895023/f1454004-c616-4f31-bc34-ca004f7ba9b0)

### Expected behavior

The covers should load everytime I open the extension to browse.

### Actual behavior

The covers don't lead at all unless I clear the database for the extension or open each individual manga and refresh it for the covers to load. This has happened on multiple devices.

### Tachiyomi version

1.6.6

### Android version

Android 13

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
