### ISSUE TITLE
Built-in proxy support

### ISSUE THREAD

**Issue by JohnKratos33** [tachiyomiorg/tachiyomi#9606]
### Describe your suggested feature

I have searched the Issues section and saw the following been closed & rejected, however respectfully, I do not think enough thought has gone into this and why users want it:
- #7463 - Duplicate
- #3788 - Duplicate
- #2791 - Using a proxy at the system-level, or a VPN 24/7, means potential network slowdowns/failures and in general increases instability and/or variables that could be causing issues in any app. Recommending to use a proxy at the system level is not a good alternative for a proxy in the app.
- #2438 - It is not out of scope as users have issues connecting to sources through this app
- #358 - Same as above

I love this app and have been using it for many months, but since the start, my home WiFi and a few other access points I connect to regularly fail to connect to my library sources (such as content from MangaSee). Using a DNS over HTTPS does not fix this, only using a VPN does (and I'd assume a proxy too but I haven't tested this) - however not many people want to use a VPN 24/7. Having this app fetch library updates, and content, through a proxy is much cleaner.

Please reconsider your policy on potentially implementing this, I'm sure many others have a similar issue and would love this feature.

### Other details

I am completely happy if this is made a low priority, but please do not close it just because no one wants to work on this currently.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
We've never said use a proxy or VPN 24/7 at the system level. You can toggle it when you need it, and that's already readily available with no effort required from us at an app level, "for free". The DNS over HTTPS setting will likely go away too if Android ever surfaces the system level support for it via a UI (they currently only surface DNS over TLS in the UI).

Proxies and VPNs are not a catch-all solution anyway, different websites will behave differently depending on different network configurations. You'll have to do whatever works for you.
