### ISSUE TITLE
No chapters

### ISSUE THREAD

**Issue by NET1337** [tachiyomiorg/tachiyomi#9609]
### Steps to reproduce

1. Download Allhentai
2.Visit extension
3. more manga got no chapters
4. On site work chapters

### Expected behavior

This should happen after update extension allhentai

### Actual behavior

More manga have no chapters but on site have chapters

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung S23 Ultra

### Other details

you need acc for chapters, I have registered and chapters are working on the site, but there are no chapters in tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

Wrong repository, please read what you have acknowledged.
