### ISSUE TITLE
No chaptesr found 

### ISSUE THREAD

**Issue by Tadaningenda** [tachiyomiorg/tachiyomi#9612]
### Steps to reproduce

1. Global update
2. Updating
3. Swatmanga: no chapters found 

### Expected behavior

Jj

### Actual behavior

No chapters found 

### Tachiyomi version

App version: 0.14.6-5839 (standard, fc4fd487f, 103, 2023-06-10T21:08Z)

### Android version

Android version: 10 (SDK 29) Device name: HWSTK-HF Device model: STK-LX1 Device product name: STK-L21VHN

### Device

Android build ID: STK-L21VHN 10.0.0.233(C185E2R4P1) Device brand: HONOR Device manufacturer: HUAWEI 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by Doo77m** [comment]
Same with me
Please fix this asap
