### ISSUE TITLE
HAPPYMH Unable to Search Manhua

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi#9615]
### Steps to reproduce

Unable to search using happymh, always show error

"Cannot begin reading element, unexpected token: 10 at path: $  JSON input" "

### Expected behavior

Please fix asap. Try reinstalling, clear cache, change agent  webstring, force close app.

### Actual behavior

.

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Samsung galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by Bishopop6** [comment]
How do i solve this issue?
