### ISSUE TITLE
i can't open extension 

### ISSUE THREAD

**Issue by Wapoll** [tachiyomiorg/tachiyomi#9616]
### Steps to reproduce

![Screenshot_2023-06-19-14-07-05-44](https://github.com/tachiyomiorg/tachiyomi/assets/111265199/619778b5-60fa-463a-bd25-68ea16ca4b37)

### Expected behavior

i hope this will be fine

### Actual behavior

this actually happens when I use a private network but when using wifi it's like that, I beg you to be able to fix this 

### Crash logs

I can't open the extension many times, I've done various ways

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Oppo A5 2020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
I can see you did not do multiple things that you have acknowledged. You can ask for help on discord regardless.

**Comment by Wapoll** [comment]
> Saya dapat melihat Anda tidak melakukan banyak hal yang telah Anda akui. Anda dapat meminta bantuan tentang perselisihan.

I really don't know what else to do so that the web can open without using a private network

**Comment by Wapoll** [comment]
come on bro
