### ISSUE TITLE
ADMIN DOESN'T HELP ANYTHING

### ISSUE THREAD

**Issue by Wapoll** [tachiyomiorg/tachiyomi#9622]
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Crash logs

.

### Tachiyomi version

0.13.6

### Android version

Android 8

### Device

Samsung Galaxy J7 prime

### Other details

BITCH

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
From #9616:
> this actually happens when I use a private network but when using wifi it's like that

We can't fix your ISP if they're blocking your access to those websites. Next time you'll be blocked from the organization, consider this a warning.
