### ISSUE TITLE
Readcomiconline, "Unable to parse rguard script" 

### ISSUE THREAD

**Issue by OokiiKuma1** [tachiyomiorg/tachiyomi#9627]
### Steps to reproduce

1. Go to Readcomiconline
2. Click on any comic
3. The page will load for a couple of seconds before "Unable to parse rguard script" appears and closes the comic 

### Expected behavior

Clicking the comic should just open the comic, especially when readcomiconline has been the most stable western comic experience between Comic extra, xoxo comics, and Read Comics Online. 

### Actual behavior

Anything that has been previously downloaded works fine, but if I switch to viewing in app without having downloaded previously, the error pops up every time. 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Samsung Galaxy A52 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
