### ISSUE TITLE
jmcomic，bug

### ISSUE THREAD

**Issue by llnqdx** [tachiyomiorg/tachiyomi#9633]
### Steps to reproduce

![Screenshot_2023-06-23-19-44-05-922_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/137621900/df374669-46ae-4175-bde3-876c0aad736d)

### Expected behavior

能验证成功

### Actual behavior

一直验证失败

### Tachiyomi version

0.14.6

### Android version

安卓13

### Device

Xiaomi 13ultra，Xiaomi 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by ececleon** [comment]
maybe WebView problem ? i have same question
