### ISSUE TITLE
High Ram usage while reading using WebView

### ISSUE THREAD

**Issue by KayllonDouglas** [tachiyomiorg/tachiyomi#9643]
### Steps to reproduce

I discovered this problem when reading a Chinese manga with a lot of pages for about 3 hours straight, but after an hour of use I noticed that when opening a Web-view and closing it and then repeating the process, after a certain time the app starts to freeze a lot, my Redmi Note 11's ram counter showed less than 500mb of ram free, the usual is 2gb to 2,7gb free, when i closed the app the ram usage normalized

The steps are:

- 1 - Open a Chinese Manga with a lot of pages (50,100+)

- 2 - Read (or just wait for everything to load) and close the WebView

- 3 - Repeat consecutively for a few minutes (With me it starts to lag/freeze the app around 10 to 15 minutes)

### Expected behavior

I expected that the ram consumption was not so high, which happens if I open and close a Web-view with many manga pages consecutively

### Actual behavior

High consumption of ram memory making it impossible to read because the app starts to freeze and then forces me to close and open it to continue reading

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Redmi Note 11

### Other details

I hope i can express what is happening well, my English isn't that good too so if any more info is needed fell free to ask

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
What's wrong with the app that you are reading through webview

**Comment by KayllonDouglas** [comment]
Nothing, it's just that some scans cut the chapters into several images and then in the app it's a little uncomfortable to read more than 60 pages (the pages also, when cut, sometimes makes the reading very unpleasant), in the webview I just scroll down and I can read normally and it's easier

**Comment by CrepeTF** [comment]
Use the webtoon reading mode, it'll be the same thing
