### ISSUE TITLE
Azora: impossible de contourner cloudflare

### ISSUE THREAD

**Issue by Soymamouma** [tachiyomiorg/tachiyomi#9649]
### Steps to reproduce

The azora extension doesn't open and it's writen java.io.IOE exception impossible de contourner cloudflare

### Expected behavior

Azora opens and shows manga icons

### Actual behavior

The azora extension doesn't open and it's writen java.io.IOE exception impossible de contourner cloudflare

### Tachiyomi version

Last version

### Android version

Last version

### Device

Galacy j6+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by chcoomilk** [comment]
I feel there should've been more people reporting this issue, yet there's only a few couple of them. I think there's a regression inside WebView or Cloudflare being Cloudflare. Either way we're stuck with traditional browsers.

This is very unfortunate as more and more websites are using Cloudflare and there's not many options we can do as an open source project :/

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
