### ISSUE TITLE
manhuaren plugin always response "No value for response"

### ISSUE THREAD

**Issue by fusigi0930** [tachiyomiorg/tachiyomi#9653]
### Steps to reproduce

1. install Manhuaren plugin version 1.4.8
2. browse the comic list

### Expected behavior

the comic list should be shown and read the comic 

### Actual behavior

no value for response

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Google Pixel 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
