### ISSUE TITLE
Unable to bypass cloudflare verification

### ISSUE THREAD

**Issue by crClarkluis** [tachiyomiorg/tachiyomi#9656]
### Steps to reproduce

1. Open any Extension that is cloudflare protected
2. Says > "Unable to bypass cloudflare"
3. Open the browser version of the extension
4. Cloudflare tries to verifies
5. > "failed"
Repeats 4. 5. Again and again.

### Expected behavior

I usually can bypass cloudflare these past few months without a hitch.

### Actual behavior

Now i cannot. even i have to manually open the extension browser and check the cloudflare verification myself. However, i now can not do that these past few weeks.

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)

### Android version

Android version: 13 (SDK 33)

### Device

Device brand: samsung Device model: SM-A528B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by breaking-loss** [comment]
You should raise the issues related to extensions on  https://github.com/tachiyomiorg/tachiyomi-extensions . I also reported the same issue but there was no action taken . Move to another source which doesn't require captcha .

**Comment by breaking-loss** [comment]
Isuue #9657 is my proposed idea to this solution .

**Comment by alessandrojean** [comment]
Closing as this is extension related and the Cloudflare section in the troubleshooting guide (including changing your user agent string) solves most of the cases. If a site turns on the DDos protection mode on Cloudflare, there's really nothing much we can do.
