### ISSUE TITLE
Adopt Kotatsu's Webview Mechanism

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi#9657]
### Describe your suggested feature

I do not know any coding but i have observed that while tachiyomi-extensions suffer from " unable to solve captcha "  problem from time to time the Kotatsu's inbuilt sources which require captcha doesn't face this problem .

For example n-hentai in kotatsu is working now but the n-hentai in tachiyomi-extensions is not working . The webview is not able to solve the captcha .

Please forgive me if this suggestion is dumb . I don't have any experience in coding .

### Other details

The source for kotatsu :
https://github.com/KotatsuApp/Kotatsu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Have you followed the Cloudflare section in the troubleshooting guide entirely? Including changing your user agent string?

Changing the user agent solves most cases people have.

**Comment by breaking-loss** [comment]
Tried it now and experienced that chrome webview worked but the other browser's webviev didn't . But I still request you to consider implementing the webview mechanism of Kotatsu as others unaware of this solution might exist like myself .

**Comment by arkon** [comment]
Unless I'm missing something, I don't see any tangible difference other than accepting third party cookies (which I could add), and a different default user agent string.

The user agent string has always needed updates, and we added the ability for the user to control that so the app doesn't need to get updated to fix those issues.
