### ISSUE TITLE
Unable to bypass Nhentai

### ISSUE THREAD

**Issue by Architect-Ivy** [tachiyomiorg/tachiyomi#9663]
### Steps to reproduce

1: Open Browse
2: Open Nhentai (Any language is fine but I'm currently using english)
3: Wait or Open webview (If you view the page through webview please do 4)
4: Wait for Captcha and verify (after verifying you'll see a glimpse of second saying failure)

### Expected behavior

Should open nhentai and you'll see the list available in that source

### Actual behavior

Pops up java.io.IOException: Failed to bypass cloudfare

### Tachiyomi version

Stable: 0.14.6

### Android version

Android 11

### Device

Galaxy A12

### Other details

![Screenshot_20230702-215913_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/107328165/799f2cd0-1189-4900-b351-6392a02e207f)
I already tried doing all the ones in guide regarding to cloudfare but none of it worked, been a week since it happened

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Architect-Ivy** [comment]
Btw, nhentai on my chrome works perfectly fine

**Comment by arkon** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

**Comment by kazma777** [comment]
Me too
