### ISSUE TITLE
Flutter Port of whole Project

### ISSUE THREAD

**Issue by CntrlX** [tachiyomiorg/tachiyomi#9664]
### Describe your suggested feature

I would like to export the whole project to Flutter so we can have a multi-platform app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CntrlX** [comment]
I would like to know How the extensions work in the app after that I could port the whole project

**Comment by arkon** [comment]
This almost comes across as a troll post, but if you're serious:

- Extensions are packaged APKs and installed at apps that are loaded at runtime using the app context's class loader.
- I'm pretty sure there's already other projects that use Flutter, but I don't know how they handle sources.

We have no interest in redoing the project in Flutter. Multiplatform (for Android and desktop JDK) is already possible with Kotlin Multiplatform. We have no interest in iOS/iPadOS considering app store restrictions.
