### ISSUE TITLE
MangaDex extension: crashes app on interaction

### ISSUE THREAD

**Issue by jeffreys518** [tachiyomiorg/tachiyomi#9665]
### Steps to reproduce

1. Open the Browse tab
2. Press on the MangaDex source or select the Latest button

### Expected behavior

Pressing the MangaDex source should open the source (sorted by Latest if using the Latest button).

### Actual behavior

The Tachiyomi app immediately closes instead. 

### Crash logs

--------- beginning of system
07-02 18:15:40.267 14563 14563 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
07-02 18:18:47.221 14563 14563 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
07-02 18:18:47.221 14563 14563 E ACRA    : java.lang.NullPointerException
07-02 18:18:47.221 14563 14563 E ACRA    : 	at java.io.Reader.<init>(Reader.java:167)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at java.io.InputStreamReader.<init>(InputStreamReader.java:93)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.createBundle(Intl.kt:73)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.access$createBundle(Intl.kt:22)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Intl.kt:39)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Intl.kt:39)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.getBaseBundle(Intl.kt:39)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.access$getBaseBundle(Intl.kt:22)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Intl.kt:42)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Intl.kt:41)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.getBundle(Intl.kt:41)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.get(Intl.kt:51)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFilters$HasAvailableChaptersFilter.<init>(MangaDexFilters.kt:37)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFilters.getMDFilterList$tachiyomi_all_mangadex_v1_4_182_release(MangaDexFilters.kt:19)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDex.getFilterList(MangaDex.kt:763)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceScreenModel.<init>(BrowseSourceScreenModel.kt:555)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceScreen.Content(BrowseSourceScreen.kt:128)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.transitions.ComposableSingletons$ScreenTransitionKt$lambda-2$1.invoke(ScreenTransition.kt:26)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:44)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3$1.invoke(ScreenTransition.kt:45)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:122)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:45)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.navigator.Navigator.saveableState(Navigator.kt:208)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3.invoke(ScreenTransition.kt:53)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:44)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:92)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:589)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:32)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:228)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:106)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:7)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt.ScreenTransition(ScreenTransition.kt:196)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.presentation.util.NavigatorKt.DefaultNavigatorScreenTransition(Navigator.kt:136)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity$onCreate$2$3$3.invoke(MainActivity.kt:204)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:21)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:15)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:189)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:46)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:70)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:46)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:135)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:33)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:68)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:388)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1410)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:442)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:918)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:240)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.os.Looper.loop(Looper.java:351)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8399)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
07-02 18:18:47.221 14563 14563 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
07-02 18:18:47.221 14563 14563 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@f33f928, androidx.compose.ui.platform.MotionDurationScaleImpl@bfb7641, StandaloneCoroutine{Cancelling}@f5f57e6, AndroidUiDispatcher@a44b127]
07-02 18:18:48.851 17566 17566 E anade.tachiyomi: Unknown bits set in runtime_flags: 0x40000000
07-02 18:18:48.943 17566 17566 E SchedAssist: sysOpen failed with error=Permission denied
07-02 18:18:48.943 17566 17566 E SchedAssist: sharedImFd failed with error=Permission denied
07-02 18:18:48.990 17566 17701 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-02 18:18:49.043 17566 17566 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@458bc8d
07-02 18:18:49.479 17566 17783 E SQLiteLog: (284) automatic index on C(manga_id)
07-02 18:18:49.479 17566 17783 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-02 18:18:51.405 17566 17566 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
07-02 18:18:51.405 17566 17566 E ACRA    : java.lang.NullPointerException
07-02 18:18:51.405 17566 17566 E ACRA    : 	at java.io.Reader.<init>(Reader.java:167)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at java.io.InputStreamReader.<init>(InputStreamReader.java:93)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.createBundle(Intl.kt:73)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.access$createBundle(Intl.kt:22)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Intl.kt:39)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Intl.kt:39)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.getBaseBundle(Intl.kt:39)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.access$getBaseBundle(Intl.kt:22)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Intl.kt:42)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Intl.kt:41)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.getBundle(Intl.kt:41)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.lib.i18n.Intl.get(Intl.kt:51)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFilters$HasAvailableChaptersFilter.<init>(MangaDexFilters.kt:37)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFilters.getMDFilterList$tachiyomi_all_mangadex_v1_4_182_release(MangaDexFilters.kt:19)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangadex.MangaDex.getFilterList(MangaDex.kt:763)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceScreenModel.<init>(BrowseSourceScreenModel.kt:555)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceScreen.Content(BrowseSourceScreen.kt:128)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.transitions.ComposableSingletons$ScreenTransitionKt$lambda-2$1.invoke(ScreenTransition.kt:26)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:44)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3$1.invoke(ScreenTransition.kt:45)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:122)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:45)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:31)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.navigator.Navigator.saveableState(Navigator.kt:208)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$3.invoke(ScreenTransition.kt:53)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:44)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:92)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:589)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:32)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:228)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:106)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:7)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at cafe.adriel.voyager.transitions.ScreenTransitionKt.ScreenTransition(ScreenTransition.kt:196)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.presentation.util.NavigatorKt.DefaultNavigatorScreenTransition(Navigator.kt:136)
07-02 18:18:51.405 17566 17566 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity$onCreate$2$3$3.invoke(MainActivity.kt:204)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:21)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:15)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:189)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:46)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:70)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:46)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:135)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:33)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:68)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:388)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1410)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:442)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:918)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:240)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.os.Looper.loop(Looper.java:351)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8399)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
07-02 18:18:51.406 17566 17566 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
07-02 18:18:51.406 17566 17566 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@5aec016, androidx.compose.ui.platform.MotionDurationScaleImpl@f2ad97, StandaloneCoroutine{Cancelling}@2021b84, AndroidUiDispatcher@b601f6d]
07-02 18:18:52.355 17567 17567 E anade.tachiyomi: Unknown bits set in runtime_flags: 0x40000000
07-02 18:18:52.408 17567 17567 E SchedAssist: sysOpen failed with error=Permission denied
07-02 18:18:52.408 17567 17567 E SchedAssist: sharedImFd failed with error=Permission denied
07-02 18:18:52.453 17567 17971 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-02 18:18:52.507 17567 17567 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@458bc8d
07-02 18:18:52.671 17567 18042 E SQLiteLog: (284) automatic index on C(manga_id)
07-02 18:18:52.671 17567 18042 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: LE2117_13.1.0.500(EX01)
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus9TMO
Device model: LE2117
Device product name: OnePlus9TMO

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

OnePlus 9 LE2117

### Other details

Since the app is being affected, I submitted the issue here. Let me know if I should repost in the extensions repo.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

Also already fixed, update to v1.4.183.
