### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by wecn23002** [tachiyomiorg/tachiyomi#9666]
### Describe your suggested feature

It would be nice to have shaders to improve the quality of the manga no matter what extension you use, for example in [mpv](https://mpv.io/)  we have [Anime4k](https://github.com/bloc97/Anime4K). Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Upscaling has already been rejected multiple times.

Anime upscaling wouldn't even work well on manga anyway.
