### ISSUE TITLE
Edit Title

### ISSUE THREAD

**Issue by 3dycosmo** [tachiyomiorg/tachiyomi#9672]
### Steps to reproduce

Error, the edit titles always comr back to the original titles after an auto update (12h)

### Expected behavior

The edit titles should not change again

### Actual behavior

The edit titles changed to the original title after auto update 12h

### Tachiyomi version

1.6.6

### Android version

Android 11

### Device

Techno

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Open issue at TachiJ2K's repo: https://github.com/Jays2Kings/tachiyomiJ2K
