### ISSUE TITLE
Transfering bookmarks to the app

### ISSUE THREAD

**Issue by patorixk** [tachiyomiorg/tachiyomi#9676]
### Describe your suggested feature

Hi i'm a new user to tachiyomi and i really love it but i cant really use it to it's full extent because i cant automatically transfer my bookmark from my sources into the library. I've read and bookmarked over 200books in mangageko and I'm currently reading 100+ and its a struggle to transfer my bookmarks into my library and it's discouraging me I'm not sure if it's possible to combine my mangageko or mangahasu account into the tachiyomi app but please try. otherwise its a great app. I'm sorry for disturbing you if this isn't possible 

### Other details

What I'm really asking for is for tracker support for other manga extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by patorixk** [comment]
Ooh i just properly read the tracking explanation and what this post means is to add tracking to mangageko and mangahasu

**Comment by arkon** [comment]
Those aren't trackers. You can try to request in the extensions repository for those sources to have deep link handlers added though so that you can at least more easily open links from those websites with Tachiyomi.
