### ISSUE TITLE
Three Touches 

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi#9680]
### Steps to reproduce

1. Touch any area of ​​the application.

### Expected behavior

It works normally without the need to tap three times.

### Actual behavior

When trying to touch an area, you have to touch it three times for it to take effect and carry out the action.

### Tachiyomi version

Tachiyomi Preview r5882

### Android version

11

### Device

Redmi Note 11S

### Other details

It happens in any zone (search, library, sources, etc).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have a video? There seems to be no similar reports of this sort of thing.

**Comment by AntsyLich** [comment]
I happened to have noticed this in library tab but it was rather random. I thought something was wrong on my side

**Comment by KasukeLp23** [comment]
Thanks
