### ISSUE TITLE
Download icon in chapters.

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi#9681]
### Steps to reproduce

Download chapters (when updating manually)

### Expected behavior

Icon animation occurs normally.

### Actual behavior

It stops and does not appear as if it is downloading the chapter.

### Tachiyomi version

Tachiyomi Previewer 5882

### Android version

11

### Device

Redmi Note 11S

### Other details

It only happens when updating the titles manually.
And as it happens in the video:

https://github.com/tachiyomiorg/tachiyomi/assets/70596255/a368d8c7-634e-4059-9987-ed273cd7f41a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Same issue as #9577
