### ISSUE TITLE
Chapter not marked read after reading it

### ISSUE THREAD

**Issue by AwkwardPeak7** [tachiyomiorg/tachiyomi#9687]
### Steps to reproduce

Read a chapter
Get to "no next chapter" reader screen
Exit out of reader

### Expected behavior

Chapter marked as read in chapter list 

### Actual behavior

Chapter not marked as read, it shows last page as read.

### Tachiyomi version

r5899

### Android version

Android 13

### Device

Tecno spark 6 

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/48650614/3f7ded81-9342-41ca-8be0-48d782bdf97d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I did some testing and seems like until the current chapter is changed a chapter isn't marked as read

**Comment by Kytoh** [comment]
Tachiyomi Version:
r5899

Android 13
Oppo Find X5 Pro

Same issue
