### ISSUE TITLE
Filter chapters list by scanlator

### ISSUE THREAD

**Issue by shogunreaper** [tachiyomiorg/tachiyomi#969]
Since scanlator was added on chapter list can we have a way to hide/select specific groups?

**Comment by Dangelman** [comment]
Yeah, it's pretty annoying, especially when reading. "Sorting by Source/Chapter number" doesn't change anything for me.
A toggeable option in the filters to hide certain sources would be great.
![OPM](https://user-images.githubusercontent.com/26676154/87234256-95f92080-c3cf-11ea-90fd-92cac9769df4.png)

**Comment by CarlosEsco** [comment]
Current Options are either of the following
1. Block the group on mangadex
2.  Mark the chapters as read and enable skip read setting
3. Use neko

**Comment by Jaykoerner** [comment]
> Current Options are either of the following
> 1. Block the group on mangadex
> 2.  Mark the chapters as read and enable skip read setting
> 3. Use neko 
> 

That leaves only number 2 as a valid workaround for anything other the MangaDex, and with some titles having 5-10 scanlators often redoing the work from scratch it can be a major annoyance,

My preference would be a toggelable per title drop-down per scanlator/source

When you first open it all of them are closed and in the drop-down bar it states latest chapter number/title out of total number of chapters and last updated, from there you can enable/disable groups.

Just my thoughts on the matter

**Comment by RvI101** [comment]
I think I'll try my hand at this, seeing as it's something I wanted as well. I'm thinking an extra drop-down option in the filter menu.

**Comment by lucscamps** [comment]
> I think I'll try my hand at this, seeing as it's something I wanted as well. I'm thinking an extra drop-down option in the filter menu.

Guy from Neko already did that. Wouldn't it be possible to just talk to him and copy the code?

**Comment by CarlosEsco** [comment]
being the guy from Neko, Its not straightforward to do and still be clean with the current tachiyomi code.

**Comment by Kyusetzu** [comment]
This feature request has been opened almost 4 years ago.
When will this be a thing? I can only +1 what the others said - Neko already has it and it would be a real QoL thing to have.

**Comment by mm12** [comment]
I also want this, but I have something to add. the filtered chapters (which I think should be able to be done individually as well, and should have both global and by title cases) should not be included in counts, such as unread count and total chapter count. Just an idea.

**Comment by Yankyal** [comment]
Why in God's name is this not in the app yet? It's such an annoying thing to deal with and had been requested for 5 fucking years

**Comment by CrepeTF** [comment]
You're right, we can aim for 10

**Comment by mm12** [comment]
Implementation suggestion: A good way to do this would be to have something similar to 'bookmarks' (same behavior), and then also implement a way to select a chapter range, duplicates, or all chapters by group. This way, you can filter as if they were bookmarks. 
For example, when you are in select mode, you can have something that highlights or points out duplicates, so they are easier to find. 

With this method, if a group too over for another and there is overlap, you don't need to block them, just tag the chapters.

**Comment by arkon** [comment]
If anyone wants to look at this, TachiyomiJ2K's current implementation is probably the best starting point.

**Comment by Yankyal** [comment]
It's been 9000 years and this STILL isn't a feature? It ruins reading experiences when you have to skip every other damn chapter because there's still no way to just filter or remove duplicate chapters...

**Comment by max-niederman** [comment]
I haven't worked on Tachiyomi before, but the lack of this feature has annoyed me for a while and I may try to implement it.

**Comment by mm12** [comment]
> I haven't worked on Tachiyomi before, but the lack of this feature has annoyed me for a while and I may try to implement it.

I also kind of wanted to try, but my computer crashed last time I ran Android Studio, so unlikely for now :(

**Comment by Lukyzzz** [comment]
> Current Options are either of the following
> 1. Block the group on mangadex
> 2.  Mark the chapters as read and enable skip read setting
> 3. Use neko 
> 

Mark as Read literally hundreds of hundreds of chapters ? Kinda hard

**Comment by Lukyzzz** [comment]
> This feature request has been opened almost 4 years ago.
> When will this be a thing? I can only +1 what the others said - Neko already has it and it would be a real QoL thing to have.

6 years then

**Comment by lectern** [comment]
After reading the docs, it seems this feature was already implemented. I tested this and it works.

https://tachiyomi.org/help/faq/#mangadex
![Screenshot_20230626_155701_Samsung Internet.jpg](https://github.com/tachiyomiorg/tachiyomi/assets/30962319/4ba0afd7-6ac9-47d8-a492-9c14c7f3bd72)

Hope this helps.

**Comment by AntsyLich** [comment]
That only works with MangaDex so no it wasn't implemented

**Comment by dimateos** [comment]
I've been using this feature in [TachiyomiSY](https://github.com/jobobby04/TachiyomiSY) and works flawlessly. Sadly this fork is missing other features from the main version.

This could be the code pointer from where to start looking at their implementation:
https://github.com/jobobby04/TachiyomiSY/blob/ee47d74b5e2473091a45919aa8c19d75d4176031/app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt#L1287

**Comment by AntsyLich** [comment]
Maybe you haven't noticed but I made a attempt (#8803). It has some bugs. But I'm not working on it currently. I'll work on it after August if nothing goes wrong.

**Comment by AntsyLich** [comment]
Only took 6 years
