### ISSUE TITLE
mangaship can't pass cloudflare.

### ISSUE THREAD

**Issue by NekoManga** [tachiyomiorg/tachiyomi#9693]
### Steps to reproduce

mangaship can't pass cloudflare.

### Expected behavior

mangaship can't pass cloudflare.

### Actual behavior

mangaship can't pass cloudflare.

### Crash logs

mangaship can't pass cloudflare.

### Tachiyomi version

0.14.6

### Android version

Andorid 12

### Device

xoami redmi 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

> I have gone through the FAQ and troubleshooting guide.
