### ISSUE TITLE
why not add a browser core?

### ISSUE THREAD

**Issue by engineer011** [tachiyomiorg/tachiyomi#9702]
### Describe your suggested feature

we need a browser core to cheat with cloudflare.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Cloudflare may be solved by changing the user agent

**Comment by arkon** [comment]
What does this even mean
