### ISSUE TITLE
The feature deletes the reading history of certain extensions

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#9705]
### Describe your suggested feature

I thought this would be an interesting feature,where this feature can delete a reading history in the application for certain extensions. For example, if I have R-18 rated reads in an extension (e.g. NHentai), I can delete the read history of that NHentai extension completely or only partially (e.g. which is more than 3 days, 7 days, 30 days, and 90 days or comics that were read recently or deleted all of them)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Clearing the database for non-library items for a given source from advanced settings already achieves this.

**Comment by TheKingTermux** [comment]
> Clearing the database for non-library items for a given source from advanced settings already achieves this.

Ohh 
I didn't know that
Thanks for the answer
