### ISSUE TITLE
Chapter not marking read properly 

### ISSUE THREAD

**Issue by AwkwardPeak7** [tachiyomiorg/tachiyomi#9709]
### Steps to reproduce

Have two, one page chapters(?)
Read both in succession
Exit reader

### Expected behavior

Both marked read

### Actual behavior

Last one not marked read

### Tachiyomi version

r5901

### Android version

Android 13

### Device

Tecno spark 6 

### Other details

https://media.discordapp.net/attachments/1032932274271952909/1128892778424844379/Picsart_23-07-13_08-34-50-884.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Should be fixed by efabe801be56476bf9ee536747f39ab8d486ca12
