### ISSUE TITLE
New Feature: add update interval for each book in the global book update to prevent IP bans from certain websites

### ISSUE THREAD

**Issue by wwssllabcd** [tachiyomiorg/tachiyomi#9714]
### Describe your suggested feature

add update interval for each book in the global book update to prevent IP bans from certain websites

### Other details

Perhaps we can set the update interval for each book in the global bookshelf to be between 20 and 40 seconds to prevent IP bans. This may slow down the update speed for all books, but it will ensure successful updates and prevent further bans.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
It's being worked on https://github.com/tachiyomiorg/tachiyomi/pull/5734
