### ISSUE TITLE
Aquamanga Issue: Failed to bypass cloudflare

### ISSUE THREAD

**Issue by Pr3c1s1on** [tachiyomiorg/tachiyomi#9715]
### Steps to reproduce

1. Open tachiyomi
2. Access aqua manga in tachiyomi
3. Failed to bypass Cloudflare
4. Press webview button
5. Success and website loaded
6. Back to tachiyomi app
7. No luck and still cloudflare failure. 
8. Cleared cookies in webview
9. Still no luck

### Expected behavior

Able to access aquamanga and see the comic list and use all the available features in tachiyomi app. 

### Actual behavior

Failed to bypass cloudflare. Cant search too. But, website view function properly and able to see the site and comic list. 

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 13 (SDK 33) Android build ID: TP1A.220624.014 Device brand: Xiaomi Device manufacturer: Xiaomi Device name: amber Device model: 21081111RG Device product name: amber_id

### Android version

Android 13 TP1A.220624.014

### Device

Xiaomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
