### ISSUE TITLE
nhentai constant CloudFlare failure

### ISSUE THREAD

**Issue by BallisticAri** [tachiyomiorg/tachiyomi#9716]
### Steps to reproduce

try to access the nHentai extention at all

### Expected behavior

when opening webviuew, it should go through cloudflare and then to the website

### Actual behavior

it says "Failure" when trying to go through cloudflare and the page refreshes

### Tachiyomi version

0.14.6

### Android version

13

### Device

Samsung S21 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by BallisticAri** [comment]
sorry, doesnt work

**Comment by BallisticAri** [comment]
i have tried everything on your little troubleshooting website.

**Comment by SiegFish** [comment]
you can try to close random user agent  and clear costom agent in extensions setting.
