### ISSUE TITLE
nhentai constant CloudFlare failure 

### ISSUE THREAD

**Issue by BallisticAri** [tachiyomiorg/tachiyomi#9717]
### Steps to reproduce

try to access the nHentai extention at all via webview

### Expected behavior

when opening webviuew, it should go through cloudflare and then to the website

### Actual behavior

it says "Failure" when trying to go through cloudflare and the page refreshes

### Tachiyomi version

0.14.6

### Android version

13

### Device

Samsung S21 5G

### Other details

YES, I HAVE ALREADY BEEN TO YOUR WEBSITE WITH TROUBLESHOOTING, NONE OF IT WORKED.
THIS HAS BEEN AN ISSUE FOR 3 MONTHS NOW.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In case you actually can't read:

>  If none of these help, wait until they lower their protection or migrate to other sources.

You're not going to get any more magical help than what's already been documented.
