### ISSUE TITLE
Follow-up Aqua manga: cloudflare 

### ISSUE THREAD

**Issue by Pr3c1s1on** [tachiyomiorg/tachiyomi#9718]
### Steps to reproduce

As previously said, open tachiyomi, access the extension, cloudflare issue, and then stop. Website both chrome and webview through app is accessible. 

### Expected behavior

Extension is accessed and all features are available. 

### Actual behavior

Cloudflare prevents it, however website view in both chrome and tachiyomi view is possible. 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Xiaomi

### Other details

Fixes tested but futile:
1. Cleared cookies, cache, database, webview data uo to 3 times and restarting the app each time, still to no avail fix the issue. 

2. Changed user agent string seven different times from suggested websites and restart app each time while checking webview and chrome (accessible) and also clearing cookies and webview data each time but still futile. 

3. Used vpn (note: triggered cloudflare, but was able to bypass and access website in both webview and chrome. Tested twice to see if any more cloudflare shows up, but only did it once, and so consecutive visits are possible.) but still nothing. 

4. Updating webview also does not fix the issue

Understood the note that if fixes didnt work that the  website increased cloudflare protection hence tachiyomi cant access. But in this case both webview from the app and chrome was possible so i dont know if that counts and would like to hear more details. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
As the guide says: if none of the instructions works, migrate to better sources or wait until they lower their protection. Not much to be done, really.
