### ISSUE TITLE
New expansion mangazavr.ru

### ISSUE THREAD

**Issue by ANILUZUMAKI** [tachiyomiorg/tachiyomi#9719]
### Describe your suggested feature

I ask the tachiemi team to add a new Russian extension. mangazavr.ru

### Other details

Url: mangazavr.ru

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
