### ISSUE TITLE
add a new function about user-agent

### ISSUE THREAD

**Issue by engineer011** [tachiyomiorg/tachiyomi#9726]
### Describe your suggested feature

add a new function：random user-agent may let the app tachiyomi more convenient for everyone who use this.

### Other details

nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Extensions that needs this already have it implemented. If you think there's one that could benefit from it, open an issue in the extensions repository instead.
