### ISSUE TITLE
A Better Scroll Bar - the current one is too thin and difficult

### ISSUE THREAD

**Issue by buthub** [tachiyomiorg/tachiyomi#9728]
### Describe your suggested feature

Not sure if this should be under feature request, but...

Too often I wind up pressing the download button or wind up going into a chapter itself or slipping off it completely when trying to scroll a long chapter list with the current scroll bar. Can you please make the scroll bar better? Maybe an option to make the scroll bar permanent and thick to make scrolling easier. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mcgirr5799** [comment]
Are you interested in this being an accessibility mode-only bar?
