### ISSUE TITLE
Scrollbar in manga screen jumps depending on visibility of header list item

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#9730]
### Steps to reproduce

If there are less than 10 chapters after tags scrollbar disappears and reappears on the third chapter.
If there are more than 10 chapters, then in the last 6 chapters during the swipe, 2-4 lags occur and after 6 chapters, the swipe becomes smooth again 
https://drive.google.com/file/d/1-pCnfhP7bgboGl1hKyx0RFWt_PzWXItu/view?usp=drivesdk
### Expected behavior

1

### Actual behavior

1

### Tachiyomi version

App version: 0.14.6-5933 (standard, ec08ba05f, 104, 2023-07-15T21:08Z)
Android version: 13 (SDK 33)
Android build ID: TKQ1.230426.002
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: mojito
Device model: Redmi Note 10
Device product name: aospa_sunny

### Android version

Android 13

### Device

Redmi note 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Your Google Drive link isn't public.

**Comment by ve1mi** [comment]
> Your Google Drive link isn't public.

Now everything is fine?

**Comment by arkon** [comment]
Yes, it works now.

This is a known issue and inherent in how scrollbars work with non-uniformly sized list items. I don't think this will realistically ever be addressed.
