### ISSUE TITLE
The popup about "This comic is already in the library" doesn't work properly 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#9732]
### Steps to reproduce

1. Search a source
2. Add to liblary
3. Search a same source again but in different website (extension) and a little bit different on title (like Adding words "Bahasa Indonesia" in back of the title, removing some Special Character, etc)
4. The source is succesfully added to liblary even it have the same title

### Expected behavior

1. Add this source to liblary
https://kiryuu.id/manga/rougo-ni-sonaete-isekai-de-8-manmai-no-kinka-wo-tamemasu/
![Screenshot_2023-07-17-18-32-38-80_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/5cef0aa9-5ba5-4558-a61a-673ee631c64f)

2. And then add this source to liblary but in different website
https://mangayaro.net/manga/rougo-ni-sonaete-isekai-de-8-manmai-no-kinka-wo-tamemasu/
![Screenshot_2023-07-17-18-33-54-86_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/9e70e12c-620f-49fa-bdbb-2bdeed63ec02)

The popup about "This comic is already in the library" appears fine

### Actual behavior

Add this source
https://mangatale.co/manga/fff-class-trashero/
![Screenshot_2023-07-17-18-31-33-28_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/bfa78e17-3db8-4052-a950-0ef97f221aeb)

Then add this source but in different website
https://kiryuu.id/manga/fff-class-trashero/
![Screenshot_2023-07-17-18-32-02-71_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/fb41cdd3-66b5-486b-bd26-de894dd941a6)

The popup about "This comic is already in the library" doesn't work properly because in [this image](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/bfa78e17-3db8-4052-a950-0ef97f221aeb) (first picture) there is an additional "Bahasa Indonesia" in the title

### Crash logs

--------- beginning of system
07-17 06:48:18.234  8985  8985 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
07-17 06:50:38.341  8985  8985 E ActivityThread: Failed to find provider info for eu.kanade.tachiyomi.DropDataProvider
07-17 06:50:40.849  8985  8985 E ActivityThread: Failed to find provider info for eu.kanade.tachiyomi.DropDataProvider
07-17 06:50:48.023  8985  8985 E ActivityThread: Failed to find provider info for eu.kanade.tachiyomi.DropDataProvider
07-17 09:28:27.439 12963 12963 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
07-17 16:32:28.812 18937 18937 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
07-17 18:24:01.924  2260  2260 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
07-17 18:24:01.955  2260  2260 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-17 18:24:01.972  2260  2260 E RefClass: java.lang.reflect.InvocationTargetException
07-17 18:24:02.068  2260  2260 E libc    : Access denied finding property "ro.odm.prev.product.name"
07-17 18:24:09.409  2260  2260 E ANR_LOG : >>> msg's executing time is too long
07-17 18:24:09.409  2260  2260 E ANR_LOG : Blocked msg = { when=-7s373ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction LaunchActivityItem,ResumeActivityItem hashCode, mActivityToken = android.os.BinderProxy@9fa9c1c mLifecycleStateRequest ResumeActivityItem{procState=-1,updateProcState=false,isForward=true} mActivityCallbacks [LaunchActivityItem{intent=Intent { flg=0x14000000 cmp=eu.kanade.tachiyomi/.ui.reader.ReaderActivity (has extras) mCallingUid=10063 },ident=172809397,info=ActivityInfo{eda69ca eu.kanade.tachiyomi.ui.reader.ReaderActivity},curConfig={1.0 ??mcc??mnc [in_ID,ja_JP] ldltr sw360dp w360dp h764dp 320dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 720, 1600) mAppBounds=Rect(0, 71 - 720, 1600) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.37mThemeChanged= 1, mThemeChangedFlags= 17, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3468918229195428113, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},overrideConfig={1.0 ??mcc??mnc [in_ID,ja_JP] ldltr sw360dp w360dp h764dp 320dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 720, 1600) mAppBounds=Rect(0, 71 - 720, 1600) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.37mThemeChanged= 1, mThemeChangedFlags= 17, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3468918229195428113, mMaterialColor= 0, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1},referrer=eu.kanade.tachiyomi,procState=20,state=Bundle[{com.google.app_measurement.screen_service=Bundle[mParcelledData.dataSize=120], android:viewHierarchyState=Bundle[{android:views={16908290=android.view.AbsSavedState$1@b76c73b, 2131296310=android.view.AbsSavedState$1@b76c73b, 2131296317=android.view.AbsSavedState$1@b76c73b, 2131296323=android.view.AbsSavedState$1@b76c73b, 2131296326=android.view.AbsSavedState$1@b76c73b, 2131296329=android.view.AbsSavedState$1@b76c73b, 2131296330=android.view.AbsSavedState$1@b76c73b, 2131296367=android.view.AbsSavedState$1@b76c73b, 2131296491=android.view.AbsSavedState$1@b76c73b, 2131296641=android.view.AbsSavedState$1@b76c73b, 2131296642=android.view.AbsSavedState$1@b76c73b, 2131296730=android.view.AbsSavedState$1@b76c73b, 2131296749=android.view.AbsSavedState$1@b76c73b, 2131296750=com.google.android.material.slider.BaseSlider$SliderState@4e8fe58, 2131296778=android.view.AbsSavedState$1@b76c73b, 2131296779=android.view.AbsSavedState$1@b76c73b, 2131296780=android.view.AbsSavedState$1@b76c73b, 2131296781=android.view.AbsSavedState$1@b76c73b, 2131296783=android.view.AbsSavedState$1@b76c73b, 2131296793=android.view.AbsSavedState$1@b76c73b, 2131296795=android.view.AbsSavedState$1@b76c73b, 2131296937=androidx.appcompat.widget.Toolbar$SavedState@4c34bb1, 2131296938=android.view.AbsSavedState$1@b76c73b, 2131296974=android.view.AbsSavedState$1@b76c73b}}], androidx.lifecycle.BundlableSavedStateRegistry.key=Bundle[{}], android:lastAutofillId=1073741823, android:fragments=android.app.FragmentManagerState@41d5896, menuVisible=false}],persistentState=null,pendingResults=null,pendingNewIntents=null,profilerInfo=null,assistToken=android.os.BinderProxy@b809c17,rotationAdj=null}] } , cost  = 6793 ms
07-17 18:24:09.409  2260  2260 E ANR_LOG : >>>Current msg List is:
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <1> = { when=-7s371ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction TopResumedActivityChangeItem, hashCode, mActivityToken = android.os.BinderProxy@9fa9c1c mLifecycleStateRequest null mActivityCallbacks [TopResumedActivityChangeItem{onTop=true}] }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <2> = { when=-7s363ms what=9999 target=android.app.ActivityThread$H }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <3> = { when=-7s117ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <4> = { when=-7s62ms what=149 target=android.app.ActivityThread$H obj=android.os.BinderProxy@9fa9c1c }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <5> = { when=-6s992ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <6> = { when=-6s887ms what=0 target=android.os.Handler callback=org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0 }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <7> = { when=-6s673ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <8> = { when=-6s655ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda0 }
07-17 18:24:09.409  2260  2260 E ANR_LOG : Current msg <9> = { when=-6s430ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
07-17 18:24:09.410  2260  2260 E ANR_LOG : Current msg <10> = { when=-6s296ms what=0 target=android.app.ActivityThread$H callback=android.app.-$$Lambda$ActivityThread$A4ykhsPb8qV3ffTqpQDklHSMDJ0 }
07-17 18:24:09.410  2260  2260 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
07-17 18:24:09.460  2260  2303 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:09.491  2260  2303 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:09.494  2260  2303 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:09.494  2260  2303 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:09.498  2260  2303 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:13.564  2260  2260 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:67)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-17 18:24:35.649  2260  3635 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
07-17 18:26:48.419  2260  5736 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:26:49.492  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:27:04.493  2260  5753 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 18:27:04.494  2260  5753 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 18:27:06.173  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:31:41.960  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:31:50.151  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:31:57.582  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:32:12.404  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:33:48.390  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:37:27.321  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:39:44.691  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
07-17 18:41:01.939  2260  5788 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.16
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Realme 7i

### Other details

Please fix soon, although not in a hurry, maybe it will be available in the next app update, hopefully

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's best effort, I'm not sure we can realistically know if something is the same if the titles are actually different.
