### ISSUE TITLE
Tachiyomi taking unnecessary space while using it

### ISSUE THREAD

**Issue by Key-explanation** [tachiyomiorg/tachiyomi#9733]
### Steps to reproduce

1. Check the memory(3.12GB)
2. Use the tachiyomi app for sometime.
3. Check the memory again. Now the memory is at 2.22GB

### Expected behavior

The app shouldn't use memory unless I download something 

### Actual behavior

The app uses memory just by using it

### Crash logs

.

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Vivo Y15

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Data is cached. You can clear the chapter cache from the app's advanced settings.
