### ISSUE TITLE
Option to automatically mark duplicate chapters as read

### ISSUE THREAD

**Issue by skrshe** [tachiyomiorg/tachiyomi#9739]
### Describe your suggested feature

Settings/reader/mark skipped chapters as read
Turn on
Now any skipped chapters will be marked as read

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
#9661 ?

**Comment by skrshe** [comment]
True, Sorry
I really suck at finding duplicates before submitting issues
Will try better 😹
