### ISSUE TITLE
Requesting feature be added to detect and prompt the user which version of a chapter they want to read.

### ISSUE THREAD

**Issue by JeisonPham** [tachiyomiorg/tachiyomi#9741]
### Describe your suggested feature

Sources like MangaDex often have multiple scanlations for the same chapter of a given series. For example, this [series](https://mangadex.org/title/04c892b3-a202-46f5-ad11-0d433e712ab8/mikadono-sanshimai-wa-angai-choroi) has two versions of chapters 1-4. The feature I am proposing would automatically detect if there are multiple versions of the same chapter and either prompt you to pick one, or skip the other one given that you've already read it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#8804
