### ISSUE TITLE
Latest manhua update function on manhuafast not showing

### ISSUE THREAD

**Issue by User56477385** [tachiyomiorg/tachiyomi#9745]
### Steps to reproduce

Step 1.
Clicking the latest function button when you open the extension page.

### Expected behavior

Should show the latest manhua's that got an update on their latest chapter.

### Actual behavior

It's saying "No results found", No matter how many times i retry and updated the extension to the latest.

### Crash logs

--------- beginning of system
--------- beginning of main
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: KF8-H696ABFAlAm-R-GL-230324V1663
Device brand: TECNO
Device manufacturer: TECNO MOBILE LIMITED
Device name: TECNO-KF8
Device model: TECNO KF8
Device product name: KF8-GL

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Tecno Spark 7 Pro

### Other details

![Screenshot_20230721-182841](https://github.com/tachiyomiorg/tachiyomi/assets/96574060/711b7ef9-612e-4f86-b05d-c6238ade8462)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
