### ISSUE TITLE
Cascading the consecutively read chapters

### ISSUE THREAD

**Issue by Fivenan** [tachiyomiorg/tachiyomi#9746]
### Describe your suggested feature

When opening a manga with hundreds or thousands of chapter, it's hard to go to the middle, where we want to read, even after sorting the chapter ascendingly or descendingly. Pressing the continue reading button doesn't let us to go to the middle part and delete the specific read chapters. 

Possible solutions:
1. In the ascending mode: cascade read chapters
2. Hide read chapters
3. Button: go to the middle
4. Cascade every hundred chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
essentially #6710

**Comment by Fivenan** [comment]
We can put an option in the settings: "cascading" or "grouping".
