### ISSUE TITLE
Mangadex and some other sources missing in installation page

### ISSUE THREAD

**Issue by iD-666** [tachiyomiorg/tachiyomi#9754]
### Steps to reproduce

1. Uninstall Mangadex
2. Go to Browse -> Extensions
3. Scroll to Multi

### Expected behavior

It showed up in Tachiyomi J2K 1.6.6

![image](https://github.com/tachiyomiorg/tachiyomi/assets/139281826/7ab5a42b-f73b-4e55-a7ba-7aaaf19eb12b)

### Actual behavior

It doesn't appear in Tachiyomi 0.14.6

![image](https://github.com/tachiyomiorg/tachiyomi/assets/139281826/44193c72-7cbf-40dc-a638-1148757886a1)

### Tachiyomi version

0.14.6

### Android version

Android 9

### Device

Redmi 6A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
MangaDex is not listed under Multi, it's listed under specific languages.
