### ISSUE TITLE
Undo option after deletion of library entries

### ISSUE THREAD

**Issue by AnshulGoel123** [tachiyomiorg/tachiyomi#9755]
### Describe your suggested feature

When u delete an entry from ur library, it would show an undo button on the bottom of screen. which reverts the deletion and makes the entry have place in ur library again.

Like how gmail or youtube has it when u archieve or unsubscribe to some chanel u get the option to undo the action

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
You need to confirm twice to remove something from your library not sure how you would still mistakenly do it

**Comment by arkon** [comment]
You need to explicitly choose to do that from the library screen and you can just re-add from the manga details screen.
