### ISSUE TITLE
Saving image causes unknown exception to occur

### ISSUE THREAD

**Issue by d3ullist** [tachiyomiorg/tachiyomi#9758]
### Steps to reproduce

Using the source MangaDex:

- Open Manga "Sometimes Even Reality Is a Lie!"
- Open Chapter 164.5 and navigate to page 3 of 3
- Save the page 

The image is succesfully saved, and an unknown exception popup appears
![image](https://github.com/tachiyomiorg/tachiyomi/assets/4577990/4f01faf6-fc2f-4bcf-a059-03edac8a62d9)

Occurs on multiple devices:  Galaxy s20, pixel 3a
Occurs on Tachiyomi Preview r5955 as well

### Expected behavior

Image is saved, unknown error does not occur

### Actual behavior

Image is saved and a unknown error occurs 

### Crash logs

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.G981BXXUHHWED
Device brand: samsung
Device manufacturer: samsung
Device name: x1s
Device model: SM-G981B
Device product name: x1sxeea

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy S20

### Other details

Additionally discussed in [Tachiyomi Discord Support channel ](https://discord.com/channels/349436576037732353/349436576037732355/1133879960961024070)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
as discussed in discord, the file is observed to be a .gif which does end up getting saved 
So it might be throwing a warning/error somewhere in the midst of that (maybe its from the imagedecoder?)

Additionally reproduced at my end on another Samsung device (Samsung Galaxy Note10 Lite) and a Pixel 3 (blueline), both running Android 13
