### ISSUE TITLE
To know the number of chapter is missing

### ISSUE THREAD

**Issue by ZoMpziO** [tachiyomiorg/tachiyomi#9759]
### Describe your suggested feature

In the top of chapters list a red line when you click it tell you haw much cheaper nad the number of them is missing like
10 cheapers are missing
Chapter 2
Chapter 7
Chapter 13.   And like this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ZoMpziO** [comment]
I really need this

**Comment by arkon** [comment]
#9259
