### ISSUE TITLE
App zooms in randomly while reading. 

### ISSUE THREAD

**Issue by jglorias** [tachiyomiorg/tachiyomi#9761]
### Steps to reproduce

I'm not sure what exactly triggers this behavior; however, this can easily be fixed by turning off the "Zoom landscape image" menu on Tachiyomi. 

Before I toggled this, it would randomly zoom in on parts of the manga's page on its own, even when the image is not a landscape image, and just a normal manga panel page. This happened when I was using the "Webtoon" reading mode. 

This happened quite often that there are now YouTube videos telling users how to fix this. 

### Expected behavior

No random zooming into the panels while reading. 

### Actual behavior

Every couple pages or so, it would randomly zoom into the page. 

### Tachiyomi version

0.14.6

### Android version

12

### Device

Xiaomi Poco F2 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> this can easily be fixed by turning off the "Zoom landscape image" menu

> This happened when I was using the "Webtoon" reading mode.

Weird. I don't think zooming landscape image behavior should affect Webtoon mode.

I did discuss the normal zoom landscape behavior in #9410.

**Comment by KanekiLeChomeur** [comment]
Got the same problem here

**Comment by dan9112** [comment]
I was using the application with default settings and the problem appeared while reading chapter 4 and then from every page. Until I set forced scaling in width, I constantly gave the maximum zoom to the right side of the page. I thought it was related to the extension and wanted to write to them. I don't know what is the default mode.

**Comment by arkon** [comment]
Not enough info.
