### ISSUE TITLE
`extensions-lib` Add ability to remove popular section from an Extension

### ISSUE THREAD

**Issue by touhidurrr** [tachiyomiorg/tachiyomi#9762]
### Describe your suggested feature

Some sources have broken the Popular section but the latest section works. For those sources, the popular section should be removed and the latest section should be the default section.

### Other details

See https://github.com/tachiyomiorg/tachiyomi-extensions/pull/17265#issuecomment-1653425159

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
The new source API (not any time soon) will introduce custom listings.

You can treat the current popular as "default" listing and just put latest there (and hide latest).
