### ISSUE TITLE
Cloudflare solving

### ISSUE THREAD

**Issue by Aversess** [tachiyomiorg/tachiyomi#9764]
### Describe your suggested feature

Would it be possible to add the ability to resolve Cloudflares on your own like the Kotatsu app does?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The app already tries to bypass Cloudflare when needed under the hoods. If it isn't working for you, try following the User Agent part in the troubleshooting guide. If that doesn't work either, migrate to better sources.
