### ISSUE TITLE
Filter or Sort without "raw" Source title so I can Select and download chapters that only English subs

### ISSUE THREAD

**Issue by mohamed-magdy26** [tachiyomiorg/tachiyomi#9765]
### Describe your suggested feature

Some chapter are followed by raw and I would love to download only English so if we can to be able to filter chapters without raw
or sort them by name but taking in consideration the raw in the title so we can be able to select all English or sequence of chapters instead of the following approach

![03dad045-39bc-4ba0-b255-f0f168e0eb05](https://github.com/tachiyomiorg/tachiyomi/assets/66481427/74df6d34-1ac6-4ff6-b613-ae8bc4c2d7aa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
