### ISSUE TITLE
Ability to archive titles

### ISSUE THREAD

**Issue by gawainXX** [tachiyomiorg/tachiyomi#9766]
### Describe your suggested feature

Over half of my library are completed titles that I've finished reading and will no longer have any updates.
They are however still putting some overhead on the app and sources each time I check for updates.
I would like to keep these in the library for reference but don't want the app to keep checking for updates for these titles.

Is there a way to add an archive feature so that titles that are completed can be archived and kept on a list without having to be deleted from the library?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
just put them in a category excluded from updating.

**Comment by arkon** [comment]
Entries with a "Completed" status are also skipped in global updates by default, so those don't actually get checked.
