### ISSUE TITLE
A better upgraded UI to select your read status directly in the visible screen

### ISSUE THREAD

**Issue by missboa** [tachiyomiorg/tachiyomi#9782]
### Describe your suggested feature

I don't know how I actually describe this. Just like in the image, no. 2, it would be best to categorize from the main screen. 

### Other details

![sorting](https://github.com/tachiyomiorg/tachiyomi/assets/131508966/019f432a-0143-4bc3-9004-bad017c9a739)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
How often do you change them

**Comment by arkon** [comment]
For convenience, you can still tap the "24 chapters" part to bring up that sheet. The sheet itself is consistent with the library.
