### ISSUE TITLE
Not able to decode backups from the provided backup schema in the app.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#9785]
### Steps to reproduce

1. Get the backup schema from debug info in the app.
2. Use it to decode a backup.

### Expected behavior

Backup gets decoded successfully.

### Actual behavior

The decode fails with the following error
Tachiyomi_backup_format_2023-08-01.proto:73:26: Field numbers must be positive integers.
Tachiyomi_backup_format_2023-08-01.proto:136:25: Field numbers must be positive integers.

### Tachiyomi version

r5985

### Android version

Android 13

### Device

Samsung S21 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
You probably need to remove all of the fields prefixed with `broken` if the tool you're using has stricter validation than the in-app one.
