### ISSUE TITLE
Failed to bypass cloudfare

### ISSUE THREAD

**Issue by iOXGN90** [tachiyomiorg/tachiyomi#9789]
### Steps to reproduce

When accessing specially nhent*i:
1. Can't bypass cloudfare
2. Will open the "Open in browser". 
3. Checking the verification if human.
4. Then no. 3 loops with no destination, you always check the verification and cannot get inside the website. 

### Expected behavior

It should be after checking the cloudfare verification, it will see the content of the website. 

### Actual behavior

Instead, after checking the verification, it is asking again to check again and again, it never stops. 

### Tachiyomi version

App version: 0.14.6 

### Android version

Android 12

### Device

Realme C7

### Other details

I already did restarting the phone and Tachiyomi itself and clearing the cookies, it did not solve anything. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
