### ISSUE TITLE
مشاركة 

### ISSUE THREAD

**Issue by hmamk** [tachiyomiorg/tachiyomi#9796]
### Steps to reproduce

لا يمكنني ان اشارك المانجا معى اصدقائي

### Expected behavior

طريقة ارسال الرابط او اختيار تطبيق للمشاركة 

### Actual behavior

يقول لا يوجد تطبيق لاتمام الاجراء

### Crash logs

![Screenshot_20230803_203705_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/121422496/caa78e02-196e-4089-b58d-8ea18241768e)
![Screenshot_20230803_204841_com huawei android internal app](https://github.com/tachiyomiorg/tachiyomi/assets/121422496/aa33b956-49a3-4ef0-976a-f99d5808f7a6)

### Tachiyomi version

0.14.6

### Android version

Android emui 9.1.0

### Device

HUAWEI y6s

### Other details

ارجاء ارشادي كيف اقوم بمشاركة المانجات معى أصدقائي او ما هي التطبيقات التي يجب ان اقوم بستخدمها 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
