### ISSUE TITLE
Option to not automatically mark as unread when source updates chapters

### ISSUE THREAD

**Issue by poliwag12** [tachiyomiorg/tachiyomi#9799]
### Describe your suggested feature

Sometimes sources update chapters in bulk and there is no telling if it is bonus chapters or update to official versions. This messes with the tracking of which chapter you're on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not possible. Most of the time the site removes the old chapters and upload new ones. The app does it's best to mark the new chapter as read if the old one was also read. But in some cases (where user updates like every hour like a madman) the old chapters are removed from the app before the source has re-uploaded the new chapters. So when you do a library update an hour after to the app those reupload seems like new chapters keeping them unread
