### ISSUE TITLE
Fix This: Download while reading

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi#9810]
### Steps to reproduce

![Screenshot_2023-08-05-16-47-59-813_com android chrome-edit](https://github.com/tachiyomiorg/tachiyomi/assets/97629848/3bc052f6-32ed-40e7-be80-37a402016c2e)

### Expected behavior

I don't know

### Actual behavior

Ok

### Crash logs

...

### Tachiyomi version

Most recent

### Android version

13

### Device

Redmi 10c

### Other details

Help 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do fill the issue form correctly and provide the requested information.
