### ISSUE TITLE
Random 10 Extensions per language of the week

### ISSUE THREAD

**Issue by quangkieu** [tachiyomiorg/tachiyomi#9815]
So i would like to suggest github flow could create list of random source extension of the week
We would have different list
List of Multi, English, Chinese
We also have list of scan group too. Thought this would depend on another suggestion.
Each source should be tag if this is scan or AGGREGATORS
And we should have more filter for source extension
And i think github should know how many time the extensions downloaded, which how popular, the randomizer should avoid the heavy one. May be 1 every 2 months only
Then the app would use the list to recommend in the app

**Comment by stevenyomi** [comment]
https://tachiyomi.org/help/faq/#general-2

**Comment by arkon** [comment]
How'd you manage to open an issue without a template?

**Comment by stevenyomi** [comment]
Probably by selecting some text then in the menu click "Reference in new issue".
