### ISSUE TITLE
[Download Queue] Move series to bottom

### ISSUE THREAD

**Issue by ItsABlackScreen** [tachiyomiorg/tachiyomi#9816]
### Describe your suggested feature

Currently there is an option in the Download Queue to move a series to top

If possible could there be an option of "Move series to bottom", because sometime when a source is bugged, and the series cannot download, having to manually move all the other series on top of it is time consuming. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed by #9918
