### ISSUE TITLE
Remove long strip's "Crop borders" setting

### ISSUE THREAD

**Issue by vetleledaal** [tachiyomiorg/tachiyomi#9817]
### Describe your suggested feature

The 'crop borders' setting under long strip should be removed. I can't see a reasonable use case for it.

Most sources cut Manhwa at wherever<sup>[citation needed]</sup>, which inevitably will be straight through a panel. This along with the wide variance in width makes the setting somewhat useless, outside of creating activity in #support.

### Other details

The only semi-reasonable compromise is making the cropped pages consistent for the whole chapter. This has the issue of having to read in all images at once, before displaying it. This would also be cumbersome. Manhwa tend to span the width at least once within a chapter<sup>[citation needed]</sup>, making this compromise not really that useful (as it won't have any effect).

kw: webtoon, cropping, removal, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
^ what he said

**Comment by vetleledaal** [comment]
I think "continuous vertical" would work for that use case, but I see that was renamed to 'long strip with gaps', and the whole group was removed from the settings. Fair enough.
