### ISSUE TITLE
[QoL] Add ability to hide "F-Droid builds is not supported officially" banner

### ISSUE THREAD

**Issue by SadmL** [tachiyomiorg/tachiyomi#9818]
## Device information
* Tachiyomi version: Stable 0.14.6
* Android version: 13
* Device: Xiaomi Mi 9 Lite

## Steps to reproduce
None

## Issue/Request
Add ability to hide "F-Droid builds is not supported officially" banner from settings

## Other details
I don't understand much about F-Droid shenanigans, which I read here and in F-Droid Gitlab.
But as F-Droid build user this banner annoys me. I perfectly understand from devs state that F-Droid builds is not supported by any means and want an ability to hide this banner.

Please don't take it as rude, even if it may sounds like that.

**Comment by arkon** [comment]
We need a prominent way of letting users know why they aren't getting app updates, which was a common question before adding such banner. If you're interested in removing it, please consider switching to the official GitHub builds.
