### ISSUE TITLE
A notification feature that will notify when the latest chapter is released.

### ISSUE THREAD

**Issue by missboa** [tachiyomiorg/tachiyomi#9820]
### Describe your suggested feature

Choose few mangas, so that you will be notified instantly when the new chapter for your choosen manga is released.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
it'll notify you next time it checks for updates.
