### ISSUE TITLE
Intersection of categories

### ISSUE THREAD

**Issue by andrei-cosmin** [tachiyomiorg/tachiyomi#9822]
### Describe your suggested feature

Every user can make custom categories and add/remove titles for them, but you can only display titles from one category at a time.

I would like to be able to filter titles using the custom categories I made.

Example:
I create Currently-Reading, On-Hold, Completed, Favorites as my custom categories.
I manually add my titles to these accordingly.
I wish to display the titles I am currently reading which are also favorites.

This does not seem possible, as I can only group by category and then cyvle through each one, but not show intersections or unions of different custom categories.

Note:
I am explicitly taking about custom categories, not tags, metadata or genres taken directly from the source.

I found older issues similar to mine, but they were misunderstood as wanting filters for tags or genres, which is why I tried to be as explicit as possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You have a single title in multiple categories though

**Comment by Opi-Txm** [comment]
Want to work on this if it's still needed :D

**Comment by arkon** [comment]
I'm not sure I even understand what the requested UX would be — best to clarify what the intention is before anyone actually tackles an implementation (if actually deemed acceptable).

**Comment by Opi-Txm** [comment]
I thought of 
- a new category tab when there are more than 2 categories
- the tab contains 2 dropdown lists of categories and AND/OR filtering mangas and displaying it below

**Comment by arkon** [comment]
Sorry, I'm not interested in maintaining that level of feature bloat in this app.

I think it'd actually make more sense to show a special "All"-like category (#3800) when searching with a text-based search allowing for categories similar to how tags are handled.
