### ISSUE TITLE
Low frame rate when scrolling through library and menus. 

### ISSUE THREAD

**Issue by z-bradshaw** [tachiyomiorg/tachiyomi#9824]
### Steps to reproduce

When scrolling through library, FPS drops significantly and the app feels sluggish. The menus also feel sluggish and there is brief delay when clicking a button to switch from different menus (like from library --> history, or browse --> more). The reader is not laggy in comparison, it is just when navigating the menus. 

https://github.com/tachiyomiorg/tachiyomi/assets/122636031/c0b00abf-fb32-4117-a412-91e80ddd45c2

### Expected behavior

The lag when scrolling through the library was not always present, was usually smooth and not noticeable. I have disabled 32-bit color, cleared cookies, chapter cache, and have tried to fix the issue by tweaking with various settings. 

In preview version r5985, the frame rate drops are almost non-existent and there is only minimal lag between pressing a button and the action occuring. This is with an identical backup of the stable version of Tachiyomi that is experiencing the issue. 

### Actual behavior

Slow, unresponsive button clicks and frame rate drops when scrolling through menus. 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Samsung Galaxy Tab S6 (SM-T860)

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/122636031/7b89368e-74f7-4c02-8881-5f44a154fd7c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably just https://tachiyomi.org/help/faq/#why-is-the-app-laggy-after-updating
