### ISSUE TITLE
Could not load Manhuaren漫畫人

### ISSUE THREAD

**Issue by Nam1031** [tachiyomiorg/tachiyomi#9825]
### Steps to reproduce

Manhuaren漫畫人 could not updated the booklist, it cannot see anything. 

### Expected behavior

It should be can see new update Manga or etc. 

### Actual behavior

Error

### Tachiyomi version

 0. 14.6

### Android version

Android11

### Device

Pixel5

### Other details

It has been half month

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
