### ISSUE TITLE
Doujindesu extension

### ISSUE THREAD

**Issue by Clawfiery** [tachiyomiorg/tachiyomi#9826]
### Steps to reproduce

Hello, I'm claw
Yesterday or two days ago I'm opening the app to the update my library
I found the cover's went blank then i check the website via browser app i usually use, the website's domain changed to .tv from .xxx (there's announcement about the change)

### Expected behavior

The cover should be able to see when the issue fixed

### Actual behavior

The cover went blank and I can't read the content as well as open the website via tachiyomi app (if streaming the comics)
I can still read the downloaded comics without any problem

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Poco x3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
