### ISSUE TITLE
Phone suddenly stopped working, tachiyomi was backing up in internal

### ISSUE THREAD

**Issue by sahaab** [tachiyomiorg/tachiyomi#9828]
### Describe your suggested feature

So, I was pretty sure I was backing tachiyomi to my external drive, but the last tachiyomi backup I can find is from 2021. 

Is there anyway I can get a tachiyomi backup? E.g., does tachiyomi get data from anilist, or some other way to get all my manga I was following?

Did tachiyomi back up to google drive by any chance? that would have been awesome

I even have google one, but cant seem to find tachiyomi on it. Soo many years of daily manga reading down the drain....

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
if you don't have a current backup no, if you had trackers you can rebuild your library manually.

**Comment by sahaab** [comment]
> if you don't have a current backup no, if you had trackers you can rebuild your library manually.

Theres no support to automatically get data from trackers? I have trackers though only for 160 manga, while my library was 500+ manga -.-'

Only backup I can find is from 2021 October, uugh
