### ISSUE TITLE
MANHWA-LATINO PRESENTA ESTE ERROR

### ISSUE THREAD

**Issue by Fran2184** [tachiyomiorg/tachiyomi#9832]
### Steps to reproduce

![Screenshot_20230810_152520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/121770368/639851cc-53e2-405a-9604-22f14e4d7ebc)
Adjunto captura del error al abrir capitulo 

### Expected behavior

Entrar a tachiyomi 
Seleccionar la extensión de manhwa latino
Escoger una serie 
Leerla

### Actual behavior

Entro a tachiyomi
Selecciono la extensión de manhwa latino
No me abre las series
Adjunto captura del error

### Tachiyomi version

O.14.16

### Android version

Android 13

### Device

Samsung galaxy a03

### Other details

![Screenshot_20230810_152520_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/121770368/acf351b2-8ab9-4e43-8399-2af38dcee146)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do read what you acknowledge

> If this is an issue with an extension, I should be opening an issue in the extensions repository.
