### ISSUE TITLE
Add an auto mark as read on update

### ISSUE THREAD

**Issue by Paavalen** [tachiyomiorg/tachiyomi#9833]
### Describe your suggested feature

There are multiple sources that update their old chapter, others have multiple scans that upload in the same manga entry like Mangadex. These chapter are unread, its a pain to mark them as read manually each times and its also a problem when you have auto downloads on, I don't want my storage to filled up.

I suggest when there is a library (global and category) update its mark as read all chapters below the highest read one.
Maybe this feature can make the update process slower so its would be nice if there is a toggle in the library setting.

### Other details

There is another feature request #9482 that is similar to this one but don't take in consideration when a chapter is replaced

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#9661
