### ISSUE TITLE
Automatically update start and finish date

### ISSUE THREAD

**Issue by Enlil50** [tachiyomiorg/tachiyomi#9834]
### Steps to reproduce

1. Start a manga
2. Continue reading it

### Expected behavior

When I start a manga, start date should be automatically added. The same exact behaviour when I remove from the library an entry with a start date.

Tracker communicates with anilist about start and end date.

When I pick the dropped Manga from another source and add the tracker, if there is an end date (there should already be a start date) and I read a new chapter, it removes the end date and keeps the start date. When I remove it from library, it automatically updates the end date

### Actual behavior

There is no automatical start or end date update.
If I read a manga and track it, it automatically puts it in reading, but no start nor end date are created. I have an example right before me now. 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung S21fe 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Start date already covered by #6734

**Comment by Enlil50** [comment]
I can't understand if they work or not.
As they clearly don't work in my app

**Comment by arkon** [comment]
The referenced commits don't exist in a stable release yet, you need to wait until that happens.
