### ISSUE TITLE
Not able to update old extension also not able to install new extension 

### ISSUE THREAD

**Issue by Gowtham871** [tachiyomiorg/tachiyomi#9835]
### Steps to reproduce

I've been using v14.6 for the past few weeks I can't able to update the extension list , I went into extension page clicked update..

Also tried in v14.5 and v14.4

### Expected behavior

Every extension should've been updated but, it's not

### Actual behavior

It's not getting updated , and i tried installing new extension it's also not getting installed 

### Crash logs

--------- beginning of system
--------- beginning of main
08-11 14:12:00.481 20055 20098 E SQLiteLog: (284) automatic index on C(manga_id)
08-11 14:12:00.481 20055 20098 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)
Android version: 9 (SDK 28)
Android build ID: PKQ1.180904.001
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: whyred
Device model: Redmi Note 5 Pro
Device product name: whyred

This is the crash log when I tried installing new extension file in new tachiyomi app 

### Tachiyomi version

V14.6/14.5/14.4

### Android version

Android 9

### Device

Redmi note 5 pro

### Other details

I am attaching a video of that

https://github.com/tachiyomiorg/tachiyomi/assets/76026333/2f96a21f-a4ab-45bf-9ca4-ff74ef6689b0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment]
Try switching MIUI Optimizations under Developer Settings to OFF when installing extensions or updates to extensions. Alternatively, manually download updates from [here](https://tachiyomi.org/extensions/).

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/#why-can-t-i-install-or-update-extensions-from-the-app-properly
