### ISSUE TITLE
cloudflare verification failure in webview mode

### ISSUE THREAD

**Issue by Atlanticboy** [tachiyomiorg/tachiyomi#9840]
### Steps to reproduce

when I try updating manhua in ManhuaUs extension its saying failed to pass cloudflare. So I opened the webview to pass the human verification but its failed and i reaperedely tried but it keeps failing and then I tried opening the website in chrome it opens without a problem then I tried other extensions on tachiyomi and every single extension which require human verification keeps failing in tachiyomi webview but opens in other browers. the extensions are en.manhuaus, all.nhentai
![WhatsApp Image 2023-08-13 at 12 00 25](https://github.com/tachiyomiorg/tachiyomi/assets/110555879/52540b56-8edf-4e95-a673-1ec482ae54e0)
![j](https://github.com/tachiyomiorg/tachiyomi/assets/110555879/7f649cd7-52b8-4246-975c-dc457e77aeed)

### Expected behavior

when opening webview the human verification should show success and starts showing the website.

### Actual behavior

when I try updating manhua in ManhuaUs extension its saying failed to pass cloudflare. So I opened the webview to pass the human verification but its failed and i reaperedely tried but it keeps failing and then I tried opening the website in chrome it opens without a problem then I tried other extensions on tachiyomi and every single extension which require human verification keeps failing in tachiyomi webview but opens in other browers. the extensions are en.manhuaus, all.nhentai
![j](https://github.com/tachiyomiorg/tachiyomi/assets/110555879/586a2080-7907-4a6e-9c09-f2ea1510a91a)
![WhatsApp Image 2023-08-13 at 12 00 25](https://github.com/tachiyomiorg/tachiyomi/assets/110555879/3510162e-5be5-4ab2-8910-3f4c6926c6b3)

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12328924/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Vivo Z1 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
