### ISSUE TITLE
Nhentai not working 

### ISSUE THREAD

**Issue by Key-explanation** [tachiyomiorg/tachiyomi#9843]
### Steps to reproduce

1. Open the extension
2. Go to webview 
3. Cannot verify 

### Expected behavior

I should have access to site after verifying it at webview 

### Actual behavior

It keeps asking me to verfy

### Crash logs

.

### Tachiyomi version

0.14.6

### Android version

Android 11 

### Device

Vivo Y15 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Key-explanation** [comment]
I still can't access it.

**Comment by alessandrojean** [comment]
As stated in bold in the troubleshooting guide: **If none of these help, wait until they lower their protection or migrate to other sources.**
