### ISSUE TITLE
Resume Button

### ISSUE THREAD

**Issue by Kococola07** [tachiyomiorg/tachiyomi#9844]
### Steps to reproduce

Not going back to the page/panel you last read.

### Expected behavior

After Clicking/touching resume button it should go to the panel or page you last read

### Actual behavior

When you click/touch the resume button you go back way to much like, when you're already in chapter 10, when you click or touch resume button it goes to chap 1

### Crash logs

-------- beginning of main
08-14 00:12:38.145 21996  4291 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#28](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=5, currentMaxAcquiredBufferCount=2
08-14 00:12:39.157 21996 19799 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#28](f:0,a:4) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=5, currentMaxAcquiredBufferCount=2
08-14 00:12:39.173 21996 19799 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#28](f:0,a:6) isEGL=1, mPendingRelease.size()=3, mMaxAcquiredBuffers=5, currentMaxAcquiredBufferCount=2
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: X666B-P740AED-S-OP-230421V1481
Device brand: Infinix
Device manufacturer: INFINIX
Device name: Infinix-X666B
Device model: Infinix X666B
Device product name: X666B-OP

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Infinix 12

### Other details

I asked the other members if they're experiencing same issue, some said yes some said it's working fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closing as the expected behavior is opening the first unread chapter of the list. If you have already had these previous chapters, mark them as read.
