### ISSUE TITLE
Mangabuddy not showing searched manga correctly when compared to web search 

### ISSUE THREAD

**Issue by riber1** [tachiyomiorg/tachiyomi#9845]
### Steps to reproduce

Search manga name in global search 

### Expected behavior

Manga is displayed 

### Actual behavior

List of popular mangas or mangas of same category is displayed, not the desired manga even though it is avaliable in manga buddy 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung a71

### Other details

I'm unable to screenshot the issue because of policies i apologies if it is vague. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
