### ISSUE TITLE
checking if the site connection is secure stuck

### ISSUE THREAD

**Issue by AhmedSamir899** [tachiyomiorg/tachiyomi#9850]
### Steps to reproduce

extension does not reach the site and when i open browser it stuck at "checking if the site connection is secure" and refresh
that prevent the  extension from reach site

### Expected behavior

extension reach site

### Actual behavior

it stuck at "checking if the site connection is secure"

### Tachiyomi version

0.14.6

### Android version

13

### Device

xiaomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues
