### ISSUE TITLE
No result found

### ISSUE THREAD

**Issue by ChikaTempest** [tachiyomiorg/tachiyomi#9852]
### Steps to reproduce

1. Can't display anything
2. Can't search anhthing
3. Everything we do only show no result found

### Expected behavior

We search for manhwa should be show up like i search for eleceed, the it will show up

### Actual behavior

But insteat this show no result found

### Crash logs

--------- beginning of main
08-18 22:56:30.882  3780  3780 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (5556) crash detected (code -1).
08-18 23:01:53.919  3780  3780 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (9271) crash detected (code -1).
08-18 23:02:24.945  3780  3780 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (10078) crash detected (code -1).
08-18 23:02:36.213  3780  3780 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (10697) crash detected (code -1).
08-18 23:04:06.376  3780  3780 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (11843) crash detected (code -1).
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N970FXXS8HWG2
Device brand: samsung
Device manufacturer: samsung
Device name: d1
Device model: SM-N970F
Device product name: d1xx

### Tachiyomi version

0.14.6

### Android version

12

### Device

Samsung galaxy note 10

### Other details

![Screenshot_20230818_230240](https://github.com/tachiyomiorg/tachiyomi/assets/105035665/f2c242bb-1279-4f67-b2b3-ead71b0c227b)
 
![Screenshot_20230818_230220](https://github.com/tachiyomiorg/tachiyomi/assets/105035665/abf33c00-8e92-4041-8046-5ea8235aba43)
![Screenshot_20230818_230212](https://github.com/tachiyomiorg/tachiyomi/assets/105035665/24cc2f97-f26d-42b3-960b-e52ebc736534)
Guess

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
