### ISSUE TITLE
Long press webview button to copy chapter URL

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi#9854]
### Describe your suggested feature

While you're in the reader view, there's a webview button on the top right that acts only to access the chapter in the webview. I suggest implementing a press-and-hold feature there as well to copy the link to the specific chapter we are on.

### Other details

This "long press to copy url" feature is already available for when we want to copy the link to a manga (from the manga details screen), but not for chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
There's no WebView button in reader anymore it has been replaced with a overflow menu that has "Open in WebView" and "Share"

**Comment by AntsyLich** [comment]
The changes will be in the next update

**Comment by arkon** [comment]
Pixel users can also copy the URL from the overview screen.
