### ISSUE TITLE
cuts in the chapter 

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi#9857]
### Steps to reproduce

Intermittent image issue from the extension , where Tachyomi downloads the chapter  piece by piece
![Screenshot_2023-08-19-11-17-01-413_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/102795903/cb6a51f3-cad7-44d1-92d3-b8d346031bc2)

### Expected behavior

One long chapter that isn't cutting 

### Actual behavior

This happen because the original chapter is cutting
![IMG_20230819_112447](https://github.com/tachiyomiorg/tachiyomi/assets/102795903/505fdb14-d7b1-47c0-8e2e-c7f3d2e3569c)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi 10C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Just tap retry

**Comment by arkon** [comment]
Report in the extensions repo if the page specifically can't load.

The concept of pages is not a bug.
