### ISSUE TITLE
Help restoring data

### ISSUE THREAD

**Issue by UmarTaslim123** [tachiyomiorg/tachiyomi#9862]
### Steps to reproduce

I tried to restore a backup after my phone was forced to be factory reset

### Expected behavior

I expected my daily backup stored on as card to function so I request to know the location of the actual data so that I may restore it

### Actual behavior

But it was corrupted so I request to know where the app data is stored for tachiyomi so that I can attempt to restore my original app data

### Crash logs

M

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Infinix note 8

### Other details

Please help I had 600 manga in my library I can't just find them again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
It's wherever you set it to. By default it's `Storage/Tachiyomi/backup/automatic`.

**Comment by arkon** [comment]
In case it wasn't obvious, local backups are useless if you factory reset and wipe the data. You would've needed a copy somewhere else.
