### ISSUE TITLE
( DragonTea ) - Cannot begin reading element, unexpected token: 10 at path $...

### ISSUE THREAD

**Issue by The-Lazy-1** [tachiyomiorg/tachiyomi#9863]
### Steps to reproduce

![Screenshot_20230821-102016](https://github.com/tachiyomiorg/tachiyomi/assets/142790683/3382c002-42a3-428b-8171-fbe6e66f2034)

This keeps popping up recently when I'm trying to use Dragontea extension when attempting to read using this extension.  Unable to view any chapter of any manga/manhua available on Dragontea extension without this coming up.

### Expected behavior

Should tap on chapter then be able to view and read.

### Actual behavior

![Screenshot_20230821-102016](https://github.com/tachiyomiorg/tachiyomi/assets/142790683/81fb884d-249b-4d43-a9f0-f27f1f6f525d)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Google Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Read what you acknowledge
