### ISSUE TITLE
Statistics overview card looks weird

### ISSUE THREAD

**Issue by T3sT3ro** [tachiyomiorg/tachiyomi#9865]
### Steps to reproduce

Go to the statistics screen and look at Overview when stats and labels span multiple lines

### Expected behavior

Icons should be vertically aligned, numbers should be the main focus (instead of labels), maybe the longest number (total time read) should be centered.

Imo what could help:
- horizontal order of total, duration, completed would place the longest number in the center
- vertical order of icon, number, secondary label would make things aligned

### Actual behavior

the icons are weirdly misaligned, the card is right-heavy (i.e. looks like that due to lengthy text on the right), multiline secondary label pushes other stats up making card look uneven

### Tachiyomi version

0.14.6

### Android version

EMUI 12

### Device

Huaweii P20 Pro

### Other details

![image](https://github.com/tachiyomiorg/tachiyomi/assets/5300963/b0c72cb9-5427-4679-ba85-33e7b7dee912)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ksh1710** [comment]
If you don't mind, I would like to work on this issue.
