### ISSUE TITLE
please reopen https://github.com/tachiyomiorg/tachiyomi/issues/9752

### ISSUE THREAD

**Issue by yakagami** [tachiyomiorg/tachiyomi#9866]
### Steps to reproduce

1: try to respond to https://github.com/tachiyomiorg/tachiyomi/issues/9752

### Expected behavior

possible

### Actual behavior

impossible

### Tachiyomi version

latest

### Android version

10

### Device

pixel 5

### Other details

Sorry for asking this way. I have built https://github.com/tachiyomiorg/tachiyomi/issues/9752 and it doesn't work. The additional preference options appear but the functionality is not present. I would like to ask the author what is wrong. I am interested in continuing his work if possible. I think some button may be missing because in my mind the reader is always going to consume the tap area either to change the page or to bring up the reader menu options. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
It's a duplicate so no
