### ISSUE TITLE
please *unlock* 9752

### ISSUE THREAD

**Issue by yakagami** [tachiyomiorg/tachiyomi#9867]
### Describe your suggested feature

Sorry, I didn't mean to ask to *reopen* https://github.com/tachiyomiorg/tachiyomi/issues/9752 in https://github.com/tachiyomiorg/tachiyomi/issues/9866. I understand that the status of that feature being implemented is unlikely to change. What I want is to *unlock* that issue so that I can write in it. The issue was first closed but still allowed users to comment in it. Then the issue was locked automatically and only because there was no follow up. But one month in truth is not too long and I don't think that the bot locking the issue means that it cannot be unlocked (not to imply you would hold otherwise, as I mistakenly was asking for something else before). I see that Arkon also wanted to know about the resulting app size increase; since I have built it, I have that information. It also implies that he is not completely against the feature (which is already a digression from my aim; I am not advocating for this feature to be implemented here). When I said I am interested in implementing the feature I meant for myself to see how well an integration like that would work. 

I also apologize for spamming the issue catalog with this request, and acknowledge that I am not using it exactly as intended. I hope this request does not come across the wrong way. With this in mind do you think it would be possible to unlock that issue?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
i'll ask arkon to unlock it
