### ISSUE TITLE
Reindex option per manga

### ISSUE THREAD

**Issue by llreizh** [tachiyomiorg/tachiyomi#9869]
### Describe your suggested feature

Sometimes downloaded chapter not detected even when file exist. ( because renamed mangadex or etc )
Option to reindex per manga should fix it.

### Other details

I have tried the global reindex downloaded chaoter from advanced setting. It doesn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Downloads are normally renamed upon updating if possible. Reindexing doesn't fix mismatched downloads, so this wouldn't help.
