### ISSUE TITLE
Download custom amout starts from last read chapter and not from last downloaded chapter.

### ISSUE THREAD

**Issue by E-Radjas** [tachiyomiorg/tachiyomi#9871]
### Steps to reproduce

1. Download chapters from a manga
2. Read a few chapters
3. Download more chapters

### Expected behavior

Downloads starting from the most recently downloaded chapter (e.g. Even if you've read 50 chapters and downloaded 100, when you download 50 more you should end up with 150 downloaded chapters.)

### Actual behavior

Download starts from most recently read chapter, even if the next chapters are already downloaded (e.g. You've read 50 chapters and downloaded 100, if you download 50 more you still have only 100 chapters downloaded.)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Galaxy note 10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Expected behavior is to download the next x unread chapter according to the applied sorting method.

Custom amount was also removed for the next release in favor of having the user explicitly select items to have better control (e.g. with a long press range select).
