### ISSUE TITLE
Reader stops loading pages after stopping at one chapter and returning next day to continue reading

### ISSUE THREAD

**Issue by EfronC** [tachiyomiorg/tachiyomi#9873]
### Steps to reproduce

1. Open a new unread manga in one of the affected extensions(Tested on Mangapark, MangaKatana, and one more I don't remember).
2. Read a few chapters without getting to the last one(Leave a few ones).
3. Return to the home menu, and wait some time(Not sure if it's about the time, or you have to close the app and reopen after a little).
4. Go back to the manga, and try to open the next chapter from the one you left, or the current chapter if you closed at the first pages of the next one.
5. Pages from that point, on that specific chapter, won't load, and will only have the retry button, which will do nothing. Reopening the chapter also doesn't fix it.

### Expected behavior

Chapter loads correctly, and you can read correctly all pages.

### Actual behavior

Pages from the page you closed it won't load.

### Tachiyomi version

0.14.6

### Android version

Android 7.1.1

### Device

Lenovo Yoga Tab 3

### Other details

This is something weird to explain(I'm not sure if the name of the issue is the correct way to refer to it), to the point that I don't know if this might be a problem with the extensions, or with Tachiyomi, but considering it happens with more than one, I'll consider it is related with the reader, yet I'm still unsure since only seems to happen with a few sources(For the moment).

I still haven't found of a way to force the chapters to reload, seems like once one chapter gets bugged, it will never load the pages again(Caché problem probably?). If I open those chapters in Webview, it loads correctly all the pages there, so doesn't seems to be problem with the server(And even after doing this, the pages won't load on the reader).

Don't think it's useful, but this is what shows instead of loading the images

![Screenshot_2023-08-25-20-26-51-836](https://github.com/tachiyomiorg/tachiyomi/assets/5926318/19c4f918-1d8f-41a3-847f-c315c27886c6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
those sites probably use temp links. mangapark also doesn't use their latest site update so that probably is broken anyways, also do what you acknowledge... 

>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
>I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
