### ISSUE TITLE
[Feature Request] Torrenting Support

### ISSUE THREAD

**Issue by LelIllumina** [tachiyomiorg/tachiyomi#9876]
### Describe your suggested feature

Torrents on Nyaa.si Usually have better quality pages than any HTTPS sources and could even improve download speed in certain cases. RSS feeds for torrents could also provide torrent links.

### Other details

I am certain this is the appropriate repo and not the extensions one but i apologize if that isnt the case

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The app doesn't work that way
