### ISSUE TITLE
Pages not loading after 2nd page on mangakakalot

### ISSUE THREAD

**Issue by God-Slayer01** [tachiyomiorg/tachiyomi#9882]
### Steps to reproduce

1. Open mangakakalot
2. Open any manga or manhua (some of them will work)
3. After page 2 it says "Page couldn't be loaded."

### Expected behavior

Pages should load

### Actual behavior

Pages are not loading 

### Tachiyomi version

0.14.6

### Android version

Android 9

### Device

Realme U1

### Other details

The other servers are working fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
> - [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
