### ISSUE TITLE
add a scroll to the "update" widget and add another "library" widget, also with a scroll

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#9887]
### Describe your suggested feature

Widgets are not bad, if they are convenient and look good. In this form, the tachiyomi widget is so useless that I don't even know why it's needed.  I would like it to look like a telegram chat widget or a google keep widget. It would be convenient to leaf through the library with those filters that are already configured in the library, if it is possible to implement it, of course.  And you can set some maximum result for the update, say 100 positions, and so on

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No desire to effectively reimplement more complex parts of the app as widgets.
