### ISSUE TITLE
Bug Manhwa Raw

### ISSUE THREAD

**Issue by Chocolalolz** [tachiyomiorg/tachiyomi#9888]
### Steps to reproduce

Can't get into the website even when i already change user agent when verify check it always fails no matter what VPN i use it's always fail. All i can do just using browser to read not the apps 

### Expected behavior

.

### Actual behavior

.

### Crash logs

...

### Tachiyomi version

Latest 

### Android version

Android 11

### Device

Infinix note 11

### Other details

Can't open the extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
