### ISSUE TITLE
Better way to manually select chapters

### ISSUE THREAD

**Issue by TheJackal32** [tachiyomiorg/tachiyomi#9894]
### Describe your suggested feature

As of right now, the only way to select chapters manually is by clicking in each one of them manually.  I suggest adding a "slide select" feature. It would work by holding the first chapter you want to select normally but swiping down or up to slide that direction while selecting the chapters that your finger passes by. Also it could slide slower or faster the furthest you go from the start point of the screen. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
1. Long press chapter A
2. Long press chapter B
3. *Selects all chapters inbetween*
