### ISSUE TITLE
View History

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#9896]
### Describe your suggested feature

Since we already have the reading history of the manga, add a menu to show it, example in print.

### Other details

![Registro de Leitura 2](https://github.com/tachiyomiorg/tachiyomi/assets/7441934/587fa518-824b-46fc-962e-10d88c470275)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
No real intention to incorporate more in-depth history/tracking since it'd just encourage data hoarding which negatively impacts app performance.

Connect the app with real tracking services if you want that info somewhere.

**Comment by joaoandre120** [comment]
It wouldn't be add more functions, but showing what we already have.
