### ISSUE TITLE
Cant read or download chapters 

### ISSUE THREAD

**Issue by Hellsunny** [tachiyomiorg/tachiyomi#9902]
### Steps to reproduce

I dont know if this issue is related to internet connection or extension but mangakatana seemed to work great for me for the past months but suddenly starting this morning i cant read my webtoons from the extension 

### Expected behavior

Normally i can download any chapters i want from mangakatana 

### Actual behavior

I cant download or read any chapters from mangakatana for reasons i dont understand

### Crash logs

java.net.SocketTimeoutException: timeout

### Tachiyomi version

0.14.6

### Android version

Android 8.1.0

### Device

Vivo y91

### Other details

![Screenshot_20230903_104253](https://github.com/tachiyomiorg/tachiyomi/assets/143922377/58d90162-6d39-4cab-a93d-dc529a083ebe)
![Screenshot_20230903_104214](https://github.com/tachiyomiorg/tachiyomi/assets/143922377/cea495ea-8279-4a0f-a3a8-2c3fcfac0a32)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

please read what you acknowledge... but also you can easily just check and mangakatana seems to be down.
