### ISSUE TITLE
Lower Side-Padding Options for webtoons

### ISSUE THREAD

**Issue by jtipt** [tachiyomiorg/tachiyomi#9908]
### Describe your suggested feature

I would like to request for the addition of lower padding percentages, lower than the current minimum of 5%, such as 2% or 3%. My reason being I use a curved screen phone and don't like the content being displayed on curved edges but using even 5% padding seems excessive to me, a lower amount like 2-3% would be ideal. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Already available in preview build, will be in next stable release.
