### ISSUE TITLE
Mangaswat

### ISSUE THREAD

**Issue by ahmedezzat69** [tachiyomiorg/tachiyomi#9910]
### Steps to reproduce

![Screenshot_2023-09-06-08-28-13-121_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/122267012/c91b1d2d-54b3-4703-9e0e-ebee65fc3a5f)

### Expected behavior

Open and browse manga

### Actual behavior

![Screenshot_2023-09-06-08-28-13-121_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/122267012/0ae5df33-5777-4cfa-bebd-20047be9bbb4)

### Crash logs

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: apollo
Device model: M2007J3SY
Device product name: apollo_eea

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Xiaomi mi 10t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
