### ISSUE TITLE
chapters title is missing

### ISSUE THREAD

**Issue by fulfoo** [tachiyomiorg/tachiyomi#9911]
### Steps to reproduce

1. i was try to update chapters
2. when the update is done the chapters show missing title, and that makes the chapter duplicated (refer when i was try update again new chapters)

### Expected behavior

the chapter should have the title.
example: chapter 12

### Actual behavior

the chapter title was missing and i don't know why is that happening.
example: chapter title is blank " ", instead like this "chapter 12"

### Crash logs

--------- beginning of main
09-06 20:26:18.036 16113 16651 E DatabaseUtils: Writing exception to parcel
09-06 20:26:18.036 16113 16651 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=17809, uid=1000 requires the provider be exported, or grantUriPermission()
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
09-06 20:26:18.036 16113 16651 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.WW_Phone-17.2017.2012.438-20201203
Device brand: asus
Device manufacturer: asus
Device name: ASUS_X00T_6
Device model: ASUS_X00TD
Device product name: WW_X00TD

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Asus ZenFone Max Pro (M1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
