### ISSUE TITLE
tachiyomi-dev breaks Manhuagui extension

### ISSUE THREAD

**Issue by yshui** [tachiyomiorg/tachiyomi#9915]
### Steps to reproduce

1. install manhuagui in tachiyomi-dev

### Expected behavior

extension shows up in sources

### Actual behavior

extension doesn't show up

### Crash logs

08.09 15:33:08.294 10412 18069 18209 eu.kanade.tachiyomi.debug E/ExtensionLoader: Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method eu.kanade.tachiyomi.source.online.HttpSource.generateId, parameter lang

### Tachiyomi version

r6037

### Android version

13

### Device

Xperia 5 IV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Send the full crash log not just a snippet

**Comment by arkon** [comment]
This is slightly weird behavior with order of operations of how things are being instantiated.

It'll be a bit less awkward once we move more things to more extensions-lib 1.5 APIs.
