### ISSUE TITLE
Can't see the new chapters

### ISSUE THREAD

**Issue by StartechGamers** [tachiyomiorg/tachiyomi#9917]
### Steps to reproduce

It is showing the error code HTTP 520, I searched abt this but I can't see anything abt this error in faq...
The extinction was ManagaLife 
![Screenshot_20230909_164411_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/92879933/5abfab0b-babe-4ca0-a08a-fb9a0ddabddf)

### Expected behavior

After scroling down, It should refresh and update new chapters which are released recently...

### Actual behavior

It's not showing any new chapters, and Displaying an error code HTTP 520.

### Crash logs

No crashes i experienced ...

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung F42 5G

### Other details

Already attached photo above*
I tried to explain as much I can....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
1. Extension issues go to the extension repository, not the app repository. Read the acknowledgment section.
2. HTTP errors 5xx are server side errors, so nothing we can do about. It's in the list of common errors in the troubleshooting guide, please do read the acknowledgment section.
