### ISSUE TITLE
not updating trackers and history

### ISSUE THREAD

**Issue by crowlv** [tachiyomiorg/tachiyomi#9923]
### Steps to reproduce

when i read a chapter it does not update the tracking after reading it, it appears as read in the list of chapters but not in the history, however, when i put the number of chapters read in the tracking manually it updates in anilist (the one i use)

### Expected behavior

in theory and because I have been using the application for a long time, it should update the tracking after reading a chapter, as long as you have the option "update progress after reading" which I have activated, besides, after reading a chapter, it should appear in the history, which does not happen

### Actual behavior

when i read a chapter it does not update the tracking after reading it, it appears as read in the list of chapters but not in the history, however, when i put the number of chapters read in the tracking manually it updates in anilist (the one i use)

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12571328/tachiyomi_crash_logs.txt)

(i don't know if that's what you're asking for)

### Tachiyomi version

preview r6049

### Android version

android 13

### Device

samsung galaxy a22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I can't reproduce this. Do you have Incognito Mode turned on?

**Comment by crowlv** [comment]
think it was a bug or something because now it works, but I didn't have
incognito mode enabled. I've tried some things and it seems to be when you
mark several chapters as read, because when you read one by one it updates
the counter in anilist.

**Comment by arkon** [comment]
Ah that's #389 then

**Comment by crowlv** [comment]
Was the problem already there? I didn't know sorry I thought it was
something new, do you know why it happens?

**Comment by arkon** [comment]
Manually marking things as read has never affected trackers nor history.

**Comment by crowlv** [comment]
Thanks for the help
