### ISSUE TITLE
Mangafire extension broken change the link to https://mangafire.to/home

### ISSUE THREAD

**Issue by Cuckultry** [tachiyomiorg/tachiyomi#9925]
### Steps to reproduce

1. Click on it
2. Doesn't work

### Expected behavior

It should work

### Actual behavior

It doesn't

### Crash logs

Null:

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Samsung a52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
