### ISSUE TITLE
Galaxy manga manhwas aren't updating

### ISSUE THREAD

**Issue by Jaj29** [tachiyomiorg/tachiyomi#9931]
### Steps to reproduce

![Screenshot_20230913-192345_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/144594100/6c6b73b1-baf2-4d37-90da-a51666893e43)
Acc to the pic it's not updating and it always gives me this message 

### Expected behavior

They should be updated 

### Actual behavior

Manhwas on Galaxy manga site are not updating 

### Crash logs

For help on how to fix library update errors, see https://tachiyomi.org/help/guides/troubleshooting

! Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: ....."thumbnail":null,"createdAt":"2023-09-11T17:14:46.000000Z"}]
  # Ø¬Ø§Ù„Ø§ÙƒØ³ÙŠ Ù…Ø§Ù†Ø¬Ø§ (AR)
    - Kidnapped Bride

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Realme 6i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
