### ISSUE TITLE
Select/Download/Bookmark All by scanlator

### ISSUE THREAD

**Issue by Jhinnie99** [tachiyomiorg/tachiyomi#9932]
### Describe your suggested feature

Hi can you add select,bookmark or download all by specific source because some extension have multiple source like mangadex and I only want to download one source so I have to book mark each chapter one by one before filtering it in Bookmarked then Download All.

I know I can use other extension with only 1 source but I like mangadex because some that only have 1 source tends to be down like Isekaiscan or some have buggy chapter, duplicate or wrong chapter and unavailable image in a chapter like mangakakalot

![SmartSelect_20230914_152051_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/144994468/4a710268-5f7b-4d89-8cb2-db3ff2b2fc98)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
These are internally referred to as scanlators, but some sources used them for different concepts.

#969 + regular selection would allow for this, so closing in favor of that.
