### ISSUE TITLE
Put a manga to sleep untill X chapters are available

### ISSUE THREAD

**Issue by Matth7878** [tachiyomiorg/tachiyomi#9934]
### Describe your suggested feature

Some mangas have regular updates but they release a small number of content to read. (For instance 1 chapters per week with 10 pages max)
For those you would want to stack chapters for laters but doing that is kind of difficult as you can be too eager to read what's happening. Putting them in an ignore category don't work really well as you still want to read them as soon as possible and you would need to check regularly your ignore category to decide if there is enough content. Beside you could be tempted to read them anyways.

To avoid that it would be nice if Tachiyomi could act as if there was no update until X new chapters are available. X would be a setting specific to each manga.
Doing that you would notice you have new content only when you desired number of chapters are availables.

To achieve that a new chapter state (beside unread and read) could be added. New state would be "dormant".
In the library if you were filtered to show only manga with unread chapters then mangas with dormants chapters should not appears. But if you're displaying mangas with read chapters they should.

As soon as X chapters available is reached then chapters should no longer be considered as dormants but as unread. User would be notified that X chapters are available as if they were all published at the same time that the most recent one.
In the library if you were filtered to show only manga with unread chapters the related manga should appears as dormants chapters changed state to unread.

Hope I make sense and it is something that could be considered!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
A similar thing would be probably better - update manga when it's expected to have x unread chapters. And have a setting for global default. E.g. by default wait for 10 chapters, but have a per-manga setting to wait for different amount. I would definitely use it.

**Comment by BrutuZ** [comment]
Sounds like something #5734 will be able to handle

**Comment by Matth7878** [comment]
I don't think updating only when expecting a set of episodes is available is the same thing. Mainly because releases can be faster than expected or slower. Also because you could decide to read dormants chapters even if it was below your set threshold. It's especially true if you are short on new chapters.

What this issue is requesting is to hide notification and new chapters from unread filter until set number of episodes are available. It is desired to be able to see new chapters if you are not filtering on unread.
What it's not asking is to only check on an estimated update intervals. Before opening this request I checked and saw those kind of requests. And IMHO they weren't what I wanted to suggest and so opened this issue.

**Comment by arkon** [comment]
No thanks. Just disable or hide the notification content and rely on the unread badges in the library if you want something like this.

**Comment by Matth7878** [comment]
I fully understand it's something you don't want to implement and there is no problem about it.

Yet @arkon I don't understand how what you proposed would work for someone wanting this ?
This request is about to temporary hide unread chapters for some manga (and so also unread badges). So relying on unread badges seems to be the opposite of what is expected ?
Same for hiding notification, it's not about not being notified but to suspend temporarily notification for some mangas and not all of them. Is there a way to disable notification only for some ? Maybe putting them in a category make it possible to hide only some notifications ?

Anyway it doesn't really matter, I just thought it would be nice to have something like this and as modification it was mainly involving adding a new chapter state. It would have been super convenient. No problem about closing it.

**Comment by arkon** [comment]
> I don't understand how what you proposed would work for someone wanting this ? This request is about to temporary hide unread chapters for some manga (and so also unread badges). So relying on unread badges seems to be the opposite of what is expected ?

You can use the unread badges to judge whether there's enough chapters for you to read.
