### ISSUE TITLE
Add Comment Section

### ISSUE THREAD

**Issue by Saksham1970** [tachiyomiorg/tachiyomi#9935]
### Describe your suggested feature

So I have read through the issues regarding adding comments in the app, and also the problems indicated that don't allow adding them. The main problem that I see is:
> A generic way of viewing comments is likely difficult to support for a majority of sources

From what I understand it seems like scraping comments for each website would be difficult to do and then it will be hard to maintain in the long run.

So I would like to discuss the idea of having the comments separated from mangas and sites altogether. The idea behind this is that like tracking the titles on say myanimelist, one can add a discussion group to a title, and that group will be used to add comments to the chapters. For example, let's take a manga spy x family, when one clicks the comments button on the title screen with all the chapters listed, like tracking it will open up a few names like "spyxfamily comments", "sxf discussions", etc. which are probably made by users. The basic idea is comments separated from titles and more or less made specifically for this app.

Now, I figured out that creating comments from the ground up and not scraping would probably require high server costs and not be viable for an app like this. I first thought of Disqus, since most manga websites out there use Disqus, but it's also not free. Maybe Facebook or other forums can be used for this. [Here](https://freestuff.dev/tags/comment/) a lot of comment systems are shared. My favorite out of these is Giscus, where I think users can create their own repositories for discussion on certain titles and share them with the app which can be listed as I mentioned earlier.

In summary, I would like the creation of discussion groups that are created by users and can be added to the mangas like tracking myanimelist, irrespective of the fact that it is of the same manga or another, and use them for comments for the chapters.

It will probably still be hard to implement but I thought I'd share my alternative on the popular feature demand which I personally also want.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Giscus seems cool however one of the big underlying issues with adding comments is moderating it. 
This would be very hard to moderate as the tachiyomi userbase is simply very large and multilingual.

**Comment by Blonteractor** [comment]
Is it possible to use the extension’s comment section instead of having our own? For example asura scans has its own comment section

**Comment by Saksham1970** [comment]
Well, my idea was to have a comment section independently created and maintained by the community, moderation done probably by volunteers in the community itself, making so that it is not a liability for the app since comments are supposed to be optional in this model (and you can probably switch to some other comment group if required).

But this was an early rough draft of the idea, and I can see it might not align with app's goals so maybe it can be fleshed out by other people.

**Comment by arkon** [comment]
> moderation done probably by volunteers in the community itself

I have no desire to open that can of worms given it's hard enough to moderate the Discord server and we can't even control the existing community beyond the official social media accounts.

Linking to something like MAL or Reddit may be reasonable, but there's no good APIs for that (there's MAL APIs to get the forum boards, topics, and a topic detail; but I don't know how we'd be able to really figure out which one's the appropriate post in a consistent manner).
