### ISSUE TITLE
Where is the file that have the conf of the app

### ISSUE THREAD

**Issue by LightZee7** [tachiyomiorg/tachiyomi#9946]
### Steps to reproduce

I see many (Nearly all) the problems in Tachiyomi can be solved by adding codes to a certain place eg. "Move Series to Bottom" in downloads, But I can't find the file that I need to add the code in.
Can someone Please tell me where can I find the file?

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Lenovo A8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LightZee7** [comment]
> Can you elaborate on the problems you are trying to solve

I want to add the "Move Series to Bottom" in downloads

**Comment by AntsyLich** [comment]
The files are added to the source code. The source code is then compiled/made into an app. Now you wait for an app update which has the new features are compiled

**Comment by LightZee7** [comment]
> The files are added to the source code. The source code is then compiled/made into an app. Now you wait for an app update where the new features are compiled

that's why I am asking where can I find this source code?
When I downloaded Tachidesk I found this file: "system.conf" in the Tachidesk folder, where I can add/remove some things, But I can't find the file with the same function in Tachiyomi's folder

**Comment by CrepeTF** [comment]
Tachidesk is completely different from tachiyomi
