### ISSUE TITLE
MangaRabic Domain Changed

### ISSUE THREAD

**Issue by ADAhmedDeviL** [tachiyomiorg/tachiyomi#9948]
### Steps to reproduce

1. Opened Tachiyomi
2. Opened a manga
3. Couldn't connect to the extension's domain
4. Checked the website of the extension and it works but with a different domain

### Expected behavior

Extension Opens so I watch my manga

### Actual behavior

It didn't and instead showed me "java.net.UnknownHostException:mangaarabics.com: SERVFAIL"

### Crash logs

None

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

V2026

### Other details

The Extension doesn't work because the domain has changed long ago and this is the new domain (https://mangarabic.com)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
