### ISSUE TITLE
Kistu Login error

### ISSUE THREAD

**Issue by Anish-XD** [tachiyomiorg/tachiyomi#9949]
### Steps to reproduce

1. Try to login into kitsu through app

### Expected behavior

Kistu will be added as as tracking site

### Actual behavior

Https error 400

### Crash logs

A
![IMG_20230920_135023](https://github.com/tachiyomiorg/tachiyomi/assets/145568969/488716f5-d10b-45b9-9e2d-ed6f54c0a059)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begoniain
Device model: Redmi Note 8 Pro
Device product name: begoniain

### Tachiyomi version

0.14.6

### Android version

11 (SDK 30)

### Device

Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
This is user error, use the correct credentials to log in.
