### ISSUE TITLE
Hooks & Events for Extensions

### ISSUE THREAD

**Issue by Wiz1991** [tachiyomiorg/tachiyomi#9950]
## Overview 
Currently the [extensions lib](https://github.com/tachiyomiorg/extensions-lib) is pretty simple.
Each extension supports some configuration, localization, and fetching the manga details and chapters. 

What would be nice for extension developers is to have more configuration + events. 

## Example 
Lets take into example what is likely the most used extension, mangadex, and go over a few scenarios. 

1. There are a lot of mangas which have the same chapter scanlated by multiple groups. Inside the app, you will always see all the chapters, but is not something the user might want. Users have their preferred sources, so it would be cool to be able to configure which scanlation group you want. 
2. Mangadex has accounts/lists and support for marking chapters as read. This is something [Neko](https://github.com/CarlosEsco/Neko)  does. It would be nice, when possible, to be able to login to the website and mark as read. 
3. Because mangadex has links to anilist/mal, it would be cool to read these links and automatically add tracking info. 
4. #9935

## Possible implementation:

1. Implement events per extensions. Meaning, each extension can listen to different events which happen to a manga of that source. Example: Chapter marked as read/unread, manga added to library, Changed categories
2. Implement configuration of extension per manga. This would show a menu on the manga details page where you'd be able to change specific settings, this would allow extensions developers to have more freedom. 

I believe if this is expanded upon it will open up a lot more possibilities 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
For examples:
1 is being worked on in #8803
2 is pretty much applies to only 1% or even less sources so not sure if it something worth implementing
3 only applies to like 2 sources afaik
4 has its own issue

For possible implementation:
Not sure how the events in 1 helps in anyways
For 2 it also imo will only apply to some small amount of sources

Imo you should get better examples and use case first and open a new discussion in https://github.com/tachiyomiorg/tachiyomi/discussions

**Comment by arkon** [comment]
For 2: there's the concept of enhanced tracking services but they're currently built into the app rather than the extensions. That could potentially change at some point, but tracking services' implementations tend to not change as often so there hasn't been a strong need to move them to an extension model.

For 3: #8691

---

> Implement events per extensions. Meaning, each extension can listen to different events which happen to a manga of that source. Example: Chapter marked as read/unread, manga added to library, Changed categories

I feel like tracking services cover most of the relevant events.

> Implement configuration of extension per manga. This would show a menu on the manga details page where you'd be able to change specific settings, this would allow extensions developers to have more freedom.

Like what? If anything, there's a strong desire to cut down on settings as it greatly complicates the app and makes it harder to maintain over time and ensure compatibility across versions/forks.

---

> Imo you should get better examples and use case first and open a new discussion in https://github.com/tachiyomiorg/tachiyomi/discussions

Discussions are limited to contributors.
