### ISSUE TITLE
Ability to set external storage for saved Pictures location

### ISSUE THREAD

**Issue by Essent1** [tachiyomiorg/tachiyomi#9951]
### Describe your suggested feature

Allow the user to change the exact location of storage they want their photos at so its not only at the internal storage. Or have the feature to actually save photos within the app and save it to the gallery if wanted

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Are you talking about when you save a specific page or cover?

**Comment by Essent1** [comment]
When you save a page on a manga

**Comment by KraXen72** [comment]
+1

**Comment by arkon** [comment]
As far as I know, Android doesn't have a concept of an external Pictures location.

**Comment by KraXen72** [comment]
Could we pick a specific folder to allow tachiyomi write access to, for saving pictures on the SD Card? @arkon

**Comment by arkon** [comment]
Could potentially put it in the same place as the user-set storage location (i.e. downloads, autobackups, etc.), but that'd be a separate feature request.

**Comment by KraXen72** [comment]
do you mean the same folder? why can't they be separate? also, iirc, the autobackups folder can be set differently than the downloads folder (i have both set to different folders on the sd card)

**Comment by arkon** [comment]
Those locations have already changed in v0.15.0 to be in the same parent folder for security reasons.

**Comment by KraXen72** [comment]
damn. Well, i do use J2K, so i wasn't aware of that change. Having it under one parent folder all would be good. I'll open a new feature request
