### ISSUE TITLE
tachiyomi reporting ie 55ch available when 65+ on website are available

### ISSUE THREAD

**Issue by IchorMortis** [tachiyomiorg/tachiyomi#9953]
### Steps to reproduce

![Screenshot_20230923-131206_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/145872716/d74a1b46-8371-40ec-8512-20c371680df6)
![Screenshot_20230923-131224_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/145872716/2860b95e-6272-4cd8-a8a2-0912dda7d21e)

Just so. This is an example, I'm certain not only asurascans is behaving this way as I've noticed it before on others as well without really realizing what a problem this actually represents for readers, and so I didn't particularly note which manhwa were troubling me. 

In any case that's what lead me to believe its not an issue with a specific extension, but I wouldn't actually know.

"steps to reproduce" 
1. Use tachiyomi
2. Realise it occasionally only displays half whats available to a particular comic

### Expected behavior

All chapters can be seen an accessed

### Actual behavior

Not ^

### Crash logs

No crash, it simply doesn't acknowledge that updates exist after a certain arbitrary point I have no understanding of

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.A205WVLSCCWD1 Device brand: samsung Device manufacturer: samsung Device name: a20 Device model: SM-A205W Device product name: a20cs

### Android version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.A205WVLSCCWD1 Device brand: samsung Device manufacturer: samsung Device name: a20 Device model: SM-A205W Device product name: a20cs

### Device

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.A205WVLSCCWD1 Device brand: samsung Device manufacturer: samsung Device name: a20 Device model: SM-A205W Device product name: a20cs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Comment by IchorMortis** [comment]
I clearly stated it wasn't an extension issue. Your shits fucked, I reported it.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by IchorMortis** [comment]
Do with it what you will

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by alessandrojean** [comment]
Asura changes their URLs from times to times, you need to migrate from Asura to Asura from times to times to update the entry URL to get the latest chapter updates. It is an extension issue, but it isn't something we can fix anyway as it's a bad behavior from them.

**Comment by arkon** [comment]
The app relies on knowing what URL to check. Some sources, like Asura Scans, like to constantly change URLs to avoid users not using their website.

Not a whole lot we can do here, but migrating to the "new" copy on Asura Scans is the best you'll get if you insist on using that source.
