### ISSUE TITLE
Backup is not working

### ISSUE THREAD

**Issue by Achuabdu** [tachiyomiorg/tachiyomi#9955]
### Steps to reproduce

1 when am trying to backup the data it is not forming

### Expected behavior

Backup should have happened

### Actual behavior

Backup is not happening

### Tachiyomi version

0.14.6

### Android version

Android 6.0

### Device

Huawei Cam l 21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
![IMG_20230924_195838.jpg](https://github.com/tachiyomiorg/tachiyomi/assets/145904014/739b4e49-e8a0-4081-8899-be7dd4899be0)

**Comment by arkon** [comment]
What does "not happening" mean? You don't even see the progress notification or it creates an incomplete file?

Did you turn off battery optimizations?

**Comment by Achuabdu** [comment]
> What does "not happening" mean? You don't even see the progress notification or it creates an incomplete file?
       I can see the progress notification but no  
Data is thereI![IMG_20230924_195838.jpg](https://github.com/tachiyomiorg/tachiyomi/assets/145904014/117ee8f0-1c01-4b59-a581-3159bbdc6ab6)


> 
> Did you turn off battery optimizations?

Yes

**Comment by Achuabdu** [comment]
Can the issue can be solved I want the data to be backuped and download to my new phone

**Comment by arkon** [comment]
That usually means your device is killing the job before it can finish, and we can't really fix that. Note that Chinese devices are notorious for breaking background job behavior.

You can follow the "Don't Kill My App" link in https://tachiyomi.org/docs/faq/library#why-aren-t-library-updates-working to see what else you can do on your Huawei device.

**Comment by Achuabdu** [comment]
> That usually means your device is killing the job before it can finish, and we can't really fix that. Note that Chinese devices are notorious for breaking background job behavior.
> 
> You can follow the "Don't Kill My App" link in https://tachiyomi.org/docs/faq/library#why-aren-t-library-updates-working to see what else you can do on your Huawei device.

Ok
