### ISSUE TITLE
Feature Request: Ability to Customize Manga Display Names

### ISSUE THREAD

**Issue by V3semir** [tachiyomiorg/tachiyomi#9959]
### Describe your suggested feature

Currently, Tachiyomi displays manga titles as they are, which is great for most cases. However, there's a common issue with manga series that have sequels or numbered volumes. For example, series like "Soul Land (Douluo Dalu)" are displayed like this:

1. Soul Land
2. Douluo Dalu 2
3. Soul Land III
4. Soul Land 4
5. Douluo Dalu V

These are sequels, and it would be incredibly useful to have the ability to manually customize the displayed names for such manga series. This customization would enhance user experience by making it easier to follow and understand the order of the series.

For instance, if I have this series in my library, I should be able to rename it as follows:
1. Soul Land
2. Soul Land II
3. Soul Land III
4. Soul Land IV
5. Soul Land V

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
essentially #4398
