### ISSUE TITLE
Crashes sometime when reaching a certain page again and again before it loads, regardless if it was read before or not or not

### ISSUE THREAD

**Issue by BadhuL** [tachiyomiorg/tachiyomi#9960]
### Steps to reproduce

1. Download chapters of any webtoon
2. Scroll through the downloaded pages 

### Expected behavior

'n'th page should load normally

### Actual behavior

Not only the app but whole device crashes upon reaching the same page even if It's already downloaded. But shows no issues sometimes.

### Crash logs

--------- beginning of main
09-27 20:18:11.332 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:18:14.435 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:18:25.759 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:18:27.070 20954 21568 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
09-27 20:18:27.070 20954 21568 E chromium: [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
09-27 20:18:27.774 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:18:49.172 20954 21069 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:18:49.197 20954 21108 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:18:49.219 20954 21108 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:18:49.245 20954 21069 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:18:49.264 20954 21069 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:03.211 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:19:03.345 20954 20954 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:19:21.308 22070 22070 E anade.tachiyom: Unknown bits set in runtime_flags: 0x8000
09-27 20:19:21.312 22070 22070 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
09-27 20:19:22.552 22070 22176 E chromium: [0927/201922.541779:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
09-27 20:19:22.555 22070 22176 E chromium: [0927/201922.555657:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
09-27 20:19:26.727 22070 22070 E GraphicExt: Can't load libboost_ext_fwk
09-27 20:19:26.727 22070 22070 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-27 20:19:27.056 22070 22167 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-27 20:19:27.982 22070 22162 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:27.982 22070 22431 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:31.882 22070 22434 E SQLiteLog: (284) automatic index on C(manga_id)
09-27 20:19:31.882 22070 22434 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-27 20:19:32.666 22070 22443 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:32.694 22070 22443 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:32.725 22070 22433 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:32.764 22070 22425 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
09-27 20:19:32.801 22070 22433 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 10 (SDK 29)
Android build ID: TB-8505F_S320019_220720_BMP
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: 8505F
Device model: Lenovo TB-8505F
Device product name: LenovoTB-8505F 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

LenovoTB-8505F

### Other details

It's not an issue with the extension. I have tired different sources. And the system webview is updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> 2/3GB RAM

Try turning on the split tall images in downloads settings and download the chapter. See if it still crashes, but this is most likely just #1908
