### ISSUE TITLE
Option to reload pages

### ISSUE THREAD

**Issue by Gamerproq** [tachiyomiorg/tachiyomi#9961]
### Describe your suggested feature

An option that allows the user to reload the page they are on

### Other details

Sometimes I have an issue where the page of a manhua or manhwa does not load properly. It would be easier if there was a reload page option as the only other method is to edit the reader and reload. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
There's normally a retry button, what are you seeing?

**Comment by Gamerproq** [comment]
Sometimes for the mahwa and manhua, a pages gets cut. I'm not sure if it's a network or device issue. I have attached screenshots of before and after images of the issue. Currently the only way to reload the pages in such a situation is to exit the reader and reload the chapter. I made the feature request as I thought it would be easier to reload the pages when such an issue occurs.

________________________________

**Comment by arkon** [comment]
You haven't attached anything (you need to do it on GitHub, not in an email), but I assume this is just #8433.

**Comment by Gamerproq** [comment]
Yes it is. I guess I dint understand the title properly. Sorry for raising the issue again.

________________________________
