### ISSUE TITLE
 Couldfalre application does not bypass 

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi#9962]
### Steps to reproduce

1-Access a source 
2-It is found in it Verify I am not a robot
3-It is not achieved when this same interface is aware of other applications, bypasses it and presses the check mark.

This interface followed the error.
![Screenshot_٢٠٢٣٠٩٢٨-١٢١١٢٧](https://github.com/tachiyomiorg/tachiyomi/assets/144265316/66ba4fe9-011e-4d11-9529-1cef8da7e36b)

### Expected behavior

It must be overridden when I press that I am not a robot 

### Actual behavior

Log in again and have not been verified

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

LG V60 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>I have gone through the FAQ and troubleshooting guide.

particularly the cloudflare part.
