### ISSUE TITLE
Reader: Touch zones are anchored to the image and not to screen

### ISSUE THREAD

**Issue by fellinir** [tachiyomiorg/tachiyomi#9963]
### Steps to reproduce

1. Open a manga in landscape mode
2. Choose a reader mode allowing to zoom-out (ex. continuous reading)
3. Pinch to zoom out the picture (decrease the size)
4. Try to swipe the pages by touching the black zones on the edge

### Expected behavior

As per logic and comfort, I should be able to slide the formed black zones on the sides of the scaled-down image, as well as touch them to change pages if setting is enabled.

### Actual behavior

Instead, I am forced to extend the finger further to reach the image to be able to swipe up-down and to tap. It does not make sense and it is uncomfortable to anchor this sensible areas to the picture, and it should be anchored to the screen's edge

### Tachiyomi version

0.14.6

### Android version

13 LOS

### Device

OnePlus 5T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already done in #9654 I believe.
