### ISSUE TITLE
Bacakomik and shinigami id domain change

### ISSUE THREAD

**Issue by mgibranfadilla** [tachiyomiorg/tachiyomi#9965]
### Steps to reproduce

The domain change and should be fixed

### Expected behavior

Fix the extension

### Actual behavior

Webview is working fine

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please open one issue per source and use the URL change report form instead.
