### ISSUE TITLE
Cannot check for updates

### ISSUE THREAD

**Issue by dhimanAdhikari** [tachiyomiorg/tachiyomi#9967]
### Steps to reproduce

Settings > About > Check for Updates

### Expected behavior

Checks for Updates and updates to new build if available.

### Actual behavior

"Connection closed" on both Wi-Fi and mobile data.
I've tried basic troubleshooting like clearing Cache and WebView and restarting the app. Also enabled DoH.

### Tachiyomi version

Preview r6064

### Android version

Android 11 (LineageOS 18.1)

### Device

Moto G5 Plus

### Other details

I don't know exactly when it started happening but I noticed I didn't get an update notification for ~2weeks. And when I manually clicked on Check for Updates I encountered this error. I updated to the latest build but that didn't solve it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [x] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by oyehanif** [comment]
I would like to work on this issue

**Comment by arkon** [comment]
I'm not really sure how this would be tackled but it sounds like a networking issue.

**Comment by dhimanAdhikari** [comment]
So I just got a new fiber this week for my personal use. If it only happened on that it'd be understandable, but it is also happening on my old fiber that I've been using just fine all this time (2 connections in my home). And its also happening on mobile data too.

I haven't changed ANY network related stuff on my routers or my phone (aside from enabling uPnP and changing SSID and password on my new connection).

**Comment by alessandrojean** [comment]
Check if you can connect to all GitHub domains such as `raw.githubusercontent.com` and `api.github.com` as well. The app uses the last to check for updates and the first to download IIRC.

**Comment by dhimanAdhikari** [comment]
> Check if you can connect to all GitHub domains such as `raw.githubusercontent.com` and `api.github.com` as well. The app uses the last to check for updates and the first to download IIRC.

Both of them are opening. The first one just opens Github homepage and the other as shown in the screenshot (dunno if this is how it should look like, all links here also open like that).

![Screenshot 2023-09-30 205850](https://github.com/tachiyomiorg/tachiyomi/assets/20817945/ffa23ced-13aa-4dc2-82d6-ff09743517f4)

**Comment by dhimanAdhikari** [comment]
UPDATE: I have no idea what happened but Check for Updates is working again even though nothing changed.

I'll close the issue I guess.
