### ISSUE TITLE
If the month leght is too long won't display on trackers date. 

### ISSUE THREAD

**Issue by gerardodinardo** [tachiyomiorg/tachiyomi#9968]
### Steps to reproduce

This issue may only be reproducible on certain languages.  Go to tracker, set start or finished date.
![imagen](https://github.com/tachiyomiorg/tachiyomi/assets/30539376/9e534cb0-c885-4ca0-ab9d-3e33b420b617)

### Expected behavior

The month name should be displayed. 

### Actual behavior

We can't see the month name.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The date picker's been changed in the preview versions so this won't be an issue in the next version.
