### ISSUE TITLE
Why take it so long

### ISSUE THREAD

**Issue by christmovies** [tachiyomiorg/tachiyomi#9970]
### Steps to reproduce

Enter the app

### Expected behavior

-5s

### Actual behavior

+10s~+15s

### Tachiyomi version

r6071

### Android version

13

### Device

Redmi 10c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Ashutoshgupta22** [comment]
I would like to work on this.

**Comment by arkon** [comment]
Are you using the Private installer mode?
