### ISSUE TITLE
Mangago Http 404 error

### ISSUE THREAD

**Issue by Myakuro** [tachiyomiorg/tachiyomi#9974]
### Steps to reproduce

When opening any manga source from Mangago, does not open and always says "http 404" 

When opening for WebView, works perfectly fine on website

### Expected behavior

Usually when opening the manga, it should load in properly 

### Actual behavior

Instead of opening, it kicks you out from the loading screen and hits you with "http 404"

### Tachiyomi version

0.14.6

### Android version

Android 11 

### Device

Google pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
