### ISSUE TITLE
latest version does not recognize mangadex, bato.to and mangapark v3 extensions anymore

### ISSUE THREAD

**Issue by jxsl13** [tachiyomiorg/tachiyomi#9975]
After updating to the version below,
the app shows me that the mangadex, bato.to and mangapark v3 mangas do not belong to a source anymore (red triangle warning symbol in migration view)
The app does not know of those extensions anymore as well.

Reinstalling the Mangadex extension manually from the website did not fix the problem.

App version: 0.14.6-6071 (standard, afb1ee220, 106, 2023-09-30T21:07Z)
Android version: 13 (SDK 33)
Android build ID: TQ3A.230901.001
Device brand: google
Device manufacturer: Google
Device name: lynx
Device model: Pixel 7a
Device product name: lynx
WebView user agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36

**Comment by jxsl13** [comment]
![Screenshot_20231002-021735](https://github.com/tachiyomiorg/tachiyomi/assets/371944/6cdd0464-19cd-4a63-9bab-b123e49c1466)

**Comment by jxsl13** [comment]
Extensions are installed:
![Screenshot_20231002-022006](https://github.com/tachiyomiorg/tachiyomi/assets/371944/5d3c9b67-7971-4544-be5d-71e2a9fbd587)

**Comment by jxsl13** [comment]
![Screenshot_20231002-022119](https://github.com/tachiyomiorg/tachiyomi/assets/371944/cb1d6b65-1d1d-4c50-bdb0-f4caf0d5aeaf)

**Comment by BrutuZ** [comment]
"NSFW (18+) Sources" enabled in Browse settings?

**Comment by jxsl13** [comment]
oh man, that might be it, daamn
