### ISSUE TITLE
Page Indicator Text Dislocation (Preview r6071)

### ISSUE THREAD

**Issue by rurires** [tachiyomiorg/tachiyomi#9976]
### Steps to reproduce

1.Enter any comic reading scene;
2.Look at the Page Text, changing the background to white will make it more obviously.

### Expected behavior

![Tachiyomi_Preview_r5745_PageNum](https://github.com/tachiyomiorg/tachiyomi/assets/33484515/75dfa597-81ae-4c5b-913f-aa5416f67bcb)

### Actual behavior

![Tachiyomi_Preview_r5767_PageNum](https://github.com/tachiyomiorg/tachiyomi/assets/33484515/c55defc3-8aa8-4a40-8751-7dd188a6f9c6)

### Tachiyomi version

0.14.6 (Preview r6071)

### Android version

MIUI12.5 (Android 10)

### Device

Xiaomi Mix 2S

### Other details

it happens in [Tachiyomi Preview r5767](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r5767) and later version after [Migrate PageIndicatorTextView to Compose (3c79777)](https://github.com/tachiyomiorg/tachiyomi/commit/3c79777e66d701958c2a20dfb5ccbdfef6e5c294).

it may only happens on some old special Android versions like MIUI12.5 (Android 10).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have any sort of text/font customization at the system level (for example, bigger font size)?

**Comment by rurires** [comment]
> Do you have any sort of text/font customization at the system level (for example, bigger font size)?

no, I use the default "MiLan Pro" (variable fonts) font with default size.
and I have tested other fonts such as "MiLan", "Roboto" and so on. Some of them perform better but still show a "dislocation" situation.
