### ISSUE TITLE
Invalid download location on SD card / can't read CBZs

### ISSUE THREAD

**Issue by Orskelo** [tachiyomiorg/tachiyomi#9977]
### Steps to reproduce

When trying to set a custom download location on a new SD card I just purchased, the file path seems to get messed up and result in an Invalid Location error, however an existing SD card I have is able to set the custom location to the SD card without issues.

To reduce file path noise, I am just going to try setting it to the _Tach_ folder right on the root of the SD card. The SD cards name is _ED7B-FC1F_. I do not know why it looks like _ED7B-F24B_.

<img src="https://github.com/tachiyomiorg/tachiyomi/assets/6544666/d1d875bb-13d2-433b-ac2b-3262c37ac594" width=50% height=50%>

<img src="https://github.com/tachiyomiorg/tachiyomi/assets/6544666/ebf91a1a-15c8-4558-83bb-688ab9fafc16" width=50% height=50%>

<img src="https://github.com/tachiyomiorg/tachiyomi/assets/6544666/3ffd11fa-977b-478e-be34-4013f119af0b" width=50% height=50%>

The exact SD card that is having this issue is [this one](https://www.amazon.com/dp/B09X7C2GBC). It was formatted in exFat by default, with the only other option being NTFS. The working SD card (Generic MicroCenter SD, pictured below) was formatted in Fat32. Changing to NTFS on the SanDisk SD card did not change the behavior.

### Expected behavior

<img src="https://github.com/tachiyomiorg/tachiyomi/assets/6544666/e2e83831-c80d-4f15-9a46-1760033e34a8" width=50% height=50%>

### Actual behavior

Invalid Location. Things seem to still download to the chosen location, sort of. The first time this happened when I tried to open a downloaded chapter it popped open a maybe 50x50 pixel black square and closed again, and I did not check the actual file location for what state it was in.

Right now as I am checking again to verify, it seems to be actually fully downloading to the folder and opening correctly in the app, and the files are all there.

### Crash logs

I was having a difficult time getting logs since it didn't actually crash, and dumping the logs had nothing of value in them. I wasn't able to figure out exactly what verbose logging did or where it logged to, but if that would help let me know how and I will get that.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

OnePlus Nord N30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Orskelo** [comment]
I believe the issue I had once where I was unable to view the downloaded files was because I had Save as CBZ archive on, and they do not open for me for whatever reason

**Comment by RAINNFLOATT** [comment]
u can fix this just by turning off the "Save as CBZ Archive" in the download section. and then download normally "just ignore the message saying Invalid Location", after downloading chapter completed try opening it and it's back to normal. even though the word "Invalid Location" still there

Have a good day
