### ISSUE TITLE
Randomly missing pages on both long strip mode

### ISSUE THREAD

**Issue by sombresu** [tachiyomiorg/tachiyomi#9979]
### Steps to reproduce

1. Open any comic, preverably vertical webcomic
2. Chose long strip reading mode
3. Be confused as the story doesn't make sense since Tachiyomi skip pages randomly without any placeholder to tell that the pages failed to load.
4. Read with worry every second 

### Expected behavior

All pages load in long strip

### Actual behavior

Randomly missing page without any warning or sign that it fail

### Tachiyomi version

0.14.6-6071

### Android version

Android 12 Miui 13.0.5

### Device

Poco X3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
since this is preview you probably have split tall images in the reader settings on, turn that off.
