### ISSUE TITLE
Add drop/abandon option for a series

### ISSUE THREAD

**Issue by tgoel-dev** [tachiyomiorg/tachiyomi#9981]
### Describe your suggested feature

I just want a feature that allows me to mark a series as "dropped/abandoned," but still stay within my library. The series could then not be updated during the routine updates. 
The option could be added to the menu at the top-right, alongside Migrate and Share. Remaining chapters could simply show a "--" to indicate that the series has been dropped, and not fully read. 

This would make it much easier to keep track of my progress for that manga. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
1. Create a Category
2. Name it "Dropped", "Abandoned" or whatever suits your fancy
3. Mark it as excluded from library updates (Settings > Global Update > Categories)
4. Add that category to all your dropped stuff
5. Profit!

**Comment by arkon** [comment]
Categories is the way to go, but also the app is not meant for hoarding data forever.
