### ISSUE TITLE
mangaspark change website

### ISSUE THREAD

**Issue by satyogi** [tachiyomiorg/tachiyomi#9982]
### Steps to reproduce

mangaspark change website from .com to .org

### Expected behavior

no

### Actual behavior

no

### Crash logs

no

### Tachiyomi version

0.14.6

### Android version

15

### Device

samsung a52s

### Other details

the website change to [mangaspark](https://mangaspark.org/)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Comment by satyogi** [comment]
can you add a new website https://mangaspark.org/ ?
