### ISSUE TITLE
Add two sites to the application

### ISSUE THREAD

**Issue by tttaima** [tachiyomiorg/tachiyomi#9993]
### Steps to reproduce

Hello Tachiyomi app workers
I would like you to add two sites for reading manga
I will provide you with a link to the two sites, so you know that they are Arabic sites
1st site: [dilartube](https://dilar.tube/) 
2nd site: [mangalike](https://manga-like.net/)

### Expected behavior

It is expected that the two sites will be added, thank you

### Actual behavior

Read manga better without looking where we were when reading the chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
>- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
