### ISSUE TITLE
Value bookmarks as a already-read chapters in the update condition

### ISSUE THREAD

**Issue by matte22ladde** [tachiyomiorg/tachiyomi#9994]
### Describe your suggested feature

Tachiyomi has enough features to track marked chapters by utilizing its "Incognito Mode" and "Last Page Read Number". If that's somehow not enough, there is "Custom Category". With that being said, bookmarks are best used for marking unwanted chapters. Valuing bookmarks as already-read chapters in the update condition improves the versatility to adjust to the standards of multiple source providers that work on the same title.

An example of this would be to sacrifice one chapter to be bookmarked and to divide chapters into fully grayed chapters and bookmarked chapters through the "Skipping 1 Chapter" warning. This is enough to track two source providers with two different standards. If there is one more source provider with a different standard, repeat another sacrifice and leave the grayed chapters be.

### Other details

The "Custom Category" is to be used personally in case if this feature request is denied.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Your description basically makes no sense, but I think #969 is what you're looking for.
