### ISSUE TITLE
Expected Release Date Weirdness

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi#9995]
### Steps to reproduce

1) Have Expected Release Date on
2) run it for a week

### Expected behavior

Should be finding the chapters when it says

### Actual behavior

Sometimes it's math is off, or sometimes it's checks are off

### Tachiyomi version

SY531

### Android version

Android 13

### Device

RedMagic Pro 8S

### Other details

![Screenshot_20231008_092032](https://github.com/tachiyomiorg/tachiyomi/assets/1321906/bdaa25d5-8477-45e6-835f-918c4e808685)
Example series of both weird bugs

Series is Bi-Weekly with a very consistent schedule but Tachi says 12 days (I realize it doesn't have 10 chapter yet, which is checks for)

And it only checked today for a new entry, 17 days after last release

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by peepincreepin** [comment]
I am also experiencing this same issue. It's not clear exactly how this function works, tbh. It may have been explained elsewhere, but I think I may have missed it. This is how I thought it would work:
- User sets the delay period (e.g. 7 days)
- Tachiyomi looks at the release date of the most recent chapter.
- If Current Date - Latest Release Date < Delay Period, then Tachi will not refresh the series.
- If Current Date - Latest Release Date >= Delay Period then Tachi adds the series to the global library update and refreshes the series with the rest of the library 
- Tachi continues to do the above until a new chapter is released, at which point the Latest Release Date variable is reset, and the Delay Period starts again.

Is this how the function is meant to work?

**Comment by semiya5** [comment]
That'd be the simplest, but currently the app auto-detects the "best" delay time and that's the default. User can change it, but sadly it's not working correctly as there's some series I can't even set it for.

**Comment by peepincreepin** [comment]
Oh I thought the "default" means that the delay time function is off for that series? And it only kicks in if/when the user selects a delay period? I think that that's how it's working for me currently. At least that's how it appears to be working on mine. Interesting that it doesn't let you set it in some instances. :/

The issue I'm personally having is that when I do set a delay period, some series stop updating entirely, and some series keep updating regularly instead of using the delay period.

**Comment by arkon** [comment]
I think this is fixed by 22589a9c3056312dcbd0dfca08b53987cbc4a73d

There's some other issues I noticed around being able to update with a custom interval in the dialog, but I'll address that in a followup commit.
