### ISSUE TITLE
Sort chapters alphabetically

### ISSUE THREAD

**Issue by PHBN1964** [tachiyomiorg/tachiyomi#9997]
### Describe your suggested feature

When you choose a manga to read you should be able to sort the chapters by alphabetically by the title name, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Why would this be more useful than the existing sorting methods?

**Comment by PHBN1964** [comment]
Because some sources like kemono or allporncomics have "mangas", like HQPorno.com.br/TZComiX.com Comics (Various) - Allporncomics , with  many stories put together that turns difficult to read the chapters sequentially, like , so it would be easier to read them if they were sorted alphabetically

**Comment by Opi-Txm** [comment]
Hey, I would like to work on this feature if no one is doing it :D

**Comment by PHBN1964** [comment]
Ok
